### PR TITLE
Merged master into release 1.17

### PR DESCRIPTION
**Pull request by VineethReddy02**
Merged master into release-1.17 to keep in sync as part of docs release teamwork.

### CODE REVIEW

**Comment by jimangel** [comment]
Any idea why there's 175 commits in this PR but the branch says it's 194 commits behind master?

Worst case scenario we can cut (hard reset) from the last `master` commit before the release.

**Comment by kbhawkey** [comment]
Hi @VineethReddy02 . Should this pull request remain open?

**Comment by sftim** [comment]
@VineethReddy02 would you like help getting this merge done?

**Comment by VineethReddy02** [comment]
@sftim @kbhawkey We don't need this anymore. Sorry for the confusion
/close

**Pull request closed without merging**
