### PR TITLE
mark feature-gate HPAContainerMetrics as removed

### PR DESCRIPTION
**Pull request by carlory**
k/k: https://github.com/kubernetes/kubernetes/pull/126862
/hold
/cc @sanposhiho

### CODE REVIEW

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Comment by sftim** [comment]
@carlory I imagine this is held until https://github.com/kubernetes/kubernetes/pull/126862 merges

Have I got that right?

**Comment by carlory** [comment]
Yes

**Comment by carlory** [comment]
/hold
upstream is merged.

**Pull request merged**
