### PR TITLE
Update typo in base64 call in nginx key generation

### PR DESCRIPTION
**Pull request by atavakoli**

### CODE REVIEW

**Comment by heckj** [comment]
thanks @atavakoli  - if you haven't already signed the CLA, please do so that we can merge you contributions, which we appreciate! The instructions, if you need them, are included in the comments above within this PR.

/approve
/assign

**Comment by heckj** [comment]
Hey @atavakoli - I'd love to accept this PR in, and it's being held on the CLA being signed. Please sign the CLA and we'll see this merged!

**Comment by steveperry-53** [comment]
Closing as duplicate of #7727.

**Pull request closed without merging**
