### PR TITLE
Update cluster-intro.html

### PR DESCRIPTION
**Pull request by kangni**
fix translate error

### CODE REVIEW

**Comment by kangni** [comment]
signed cla

**Comment by kangni** [comment]
I signed it

**Review by SataQiu — COMMENTED** [review]
LGTM,  but please sign the CLA first.
/approve

**Comment by kangni** [comment]
I signed it

**Comment by kangni** [comment]
I signed it

**Review by irvifa — COMMENTED** [review]
/lgtm

**Pull request merged**
