### PR TITLE
[zh] Create docs/images

### PR DESCRIPTION
**Pull request by my-git9**
[zh] Create docs/images/

### CODE REVIEW

**Comment by tengqm** [comment]
Are these files referenced from Chinese pages?

**Comment by my-git9** [comment]
> Are these files referenced from Chinese pages?

/zh/docs/contribute/style/digram-guide.md 有引用英文部分的，这方面是否需要尽量保持中文的本地化引用？

**Comment by tengqm** [comment]
OK. It is fine to copy them over, in hope someday someone can help localize these images.
/lgtm
/approve

**Pull request merged**
