### PR TITLE
Update French documentation for concept architecture

### PR DESCRIPTION
**Pull request by rekcah78**

### CODE REVIEW

**Comment by perriea** [comment]
> /lgtm
> 
> /approve

No... I had a pending revision with many changes ...

**Comment by remyleone** [comment]
Maybe putting the PR in draft could be a good convention to prevent fast reviews/merge. What do you think?

**Comment by remyleone** [comment]
Feel free to send your changes they will be reviewed as well.

**Comment by rekcah78** [comment]
For large MRs, it should not be the same person who adds the lgtm label and the one who approves

**Comment by perriea** [comment]
> For large MRs, it should not be the same person who adds the lgtm label and the one who approves

For XXL PR It's logiest, yes. For small no. 
I think we can submit this rule globaly because this isn't the first time this has happened.

**Pull request merged**
