### PR TITLE
blog: Introducing Cozystack: A Free PaaS Platform based on Kubernetes blog post

### PR DESCRIPTION
**Pull request by kvaps**
Hi there!

Remember when I wrote about [Kubernetes-in-Kubernetes and automated Kubernetes farms](https://kubernetes.io/blog/2021/12/22/kubernetes-in-kubernetes-and-pxe-bootable-server-farm/)?
This post is about my new project - Cozystack.

I've now decided to build a community of passionate people and start a new project to join all these amazing technologies into a single distro for service providers. And it seems now is the best moment to let people know about it.

Thank you ❤️

### CODE REVIEW

**Comment by sftim** [comment]
Thanks.  This would be more appropriate for the Cozystack or the CNCF blog, I think. We're super wary of having product announcements on our blog, even if they are products with a link to Kubernetes.

/hold

**Review by gaalw — APPROVED** [review]
Change the text to the next one:

```
The initial release of the free PaaS platform Cozystack, which is built on Kubernetes, has been published. The project is positioned as a ready-to-use platform for hosting providers and a framework for constructing both private and public clouds. The code is accessible on GitHub and is distributed under the Apache-2.0 license.

Cozystack is a system that is installed directly on servers and encompasses all aspects of preparing infrastructure for delivering managed services. The installed platform enables the creation of tenant Kubernetes clusters, databases, and virtual machines on demand.

Talos Linux and Flux CD serve as the foundational elements of the technology stack. The kernel and all necessary kernel modules are pre-built into system images, which are distributed and installed atomically. This approach eliminates moving parts and ensures stable operation.

KubeVirt technology is used to execute virtual machines, enabling the running of traditional virtual machines inside containers and providing all the necessary Cluster API integrations. This facilitates the operation of tenant Kubernetes clusters within a main Kubernetes cluster.

The platform incorporates a complimentary implementation of the network fabric based on Kube-OVN, utilizing Cilium for service networking, and MetalLB for external announcements. Storage is implemented using LINSTOR, with ZFS serving as the base layer for storage and DRBD for replication. Additionally, a pre-configured monitoring stack based on VictoriaMetrics and Grafana is included.
A key feature of the platform is its straightforward installation method in a fresh data center using PXE and a Debian-like installer, talos-bootstrap.
```

**Comment by sftim** [comment]
/close

Superseded by:
- https://github.com/kubernetes/website/pull/45289
- https://github.com/kubernetes/website/pull/45432
- https://github.com/kubernetes/website/pull/45498

**Pull request closed without merging**
