### PR TITLE
little correction

### PR DESCRIPTION
**Pull request by dblugeon**
Fix "utiliser" word.

### CODE REVIEW

**Comment by oussemos** [comment]
Welcome @dblugeon

Could you please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA ?

**Comment by remyleone** [comment]
Welcome @dblugeon

Could you please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA ?

**Comment by kbarnard10** [comment]
@dblugeon I'm going to close this for now since there hasn't been any movement in awhile. Please feel free to reopen it when you get a chance to sign the CLA. Let us know if you need any help. Thank you!

**Pull request closed without merging**
