### PR TITLE
Update ru translation in README-ru.md

### PR DESCRIPTION
**Pull request by zhanw15**
The site cannot build without a local copy of the theme. Use `git submodule update --init --recursive --depth 1` update the theme.
use `make serve` to build and test website locally.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/lgtm

**Comment by shurup** [comment]
I've also made #25808 where this command is fixed (with many other things to make the whole README up-to-date).

**Comment by sftim** [comment]
/lgtm cancel
as there is a merge conflict

**Pull request closed without merging**
