### PR TITLE
add ptux to ja reviewer

### PR DESCRIPTION
**Pull request by ptux**
I have checked the requirements for the reviewer of ja documents.

Requirements:
https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer

I think I am ready to be a reviewer.
I would like to speed up the translation and improve quality of the ja documents.

merged:

https://github.com/kubernetes/website/pulls?page=1&q=is%3Apr+is%3Amerged+author%3Aptux

reviewed:

https://github.com/kubernetes/website/pulls?q=is%3Apr+reviewed-by%3Aptux

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@ptux Thank you for your devotion and hard work. 😊

And please note that you need to add yourself in https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml too. 😊

Please refer to my case: #28948

**Comment by ptux** [comment]
@nasa9084 

https://github.com/kubernetes/org/pull/3354 is merged.
Cloud you merge this PR then?

**Pull request merged**
