### PR TITLE
Remove Stackpoint.io page (#15262)

### PR DESCRIPTION
**Pull request by furukawa3**
Since [Stackpoint.io](https://stackpoint.io/) has been retired and nobody can refer, This commit removes [Running Kubernetes on Multiple Clouds with Stackpoint.io](https://kubernetes.io/docs/setup/production-environment/turnkey/stackpoint/) .

### CODE REVIEW

**Comment by sftim** [comment]
Alongside this removal, take a look at:
- [`data/setup.yml`](https://github.com/kubernetes/website/blob/f60947b370786a707740ea58614e41c3f81e549b/data/setup.yml)
- [static redirects](https://github.com/kubernetes/website/blob/f60947b370786a707740ea58614e41c3f81e549b/static/_redirects)

that reference the removed page.

**Comment by furukawa3** [comment]
> Alongside this removal, take a look at:
> 
> * https://github.com/kubernetes/website/blob/f60947b370786a707740ea58614e41c3f81e549b/data/setup.yml#L54
> * [static redirects](https://github.com/kubernetes/website/blob/f60947b370786a707740ea58614e41c3f81e549b/static/_redirects)
> 
> that reference the removed page.

Ooops!!! Good catch!!  I'll fix it.

**Comment by sftim** [comment]
/unassign @mistyhacks 
/assign @zacharysarah 

@mistyhacks is stepping down

**Comment by zacharysarah** [comment]
For context: https://blog.netapp.com/netapp-acquires-stackpoint-io/

Stackpoint.io's blog hasn't been updated in over a year, so it looks pretty defunct. I think we can safely remove this content. Thanks for the update, @furukawa3! 🌟 

/lgtm
/approve

**Pull request merged**
