### PR TITLE
Fix errors #27565, #27569

### LINKED ISSUE #27565: Links to labels-annotations-taints are broken or outdated
**This is a Bug Report**

**Problem:**
Links to labels-annotations-taints are broken
- In https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost ,
the link `controller.kubernetes.io/pod-deletion-cost` is broken.
- Some other links are outdated.

**Proposed Solution:**
- In `content/en/blog/_posts/2019-12-09-kubernetes-1.17-release-announcement.md`
  - `https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#nodekubernetesioinstance-type`
  => `/docs/reference/labels-annotations-taints/#nodekubernetesioinstance-type`
  - `https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesioregion`
  => `/docs/reference/labels-annotations-taints/#topologykubernetesioregion`
  - `https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesiozone`
  => `/docs/reference/labels-annotations-taints/#topologykubernetesiozone`
- In `content/en/blog/_posts/2020-09-03-warnings/index.md`
  - `/docs/reference/kubernetes-api/labels-annotations-taints/#beta-kubernetes-io-arch-deprecated`
  => `/docs/reference/labels-annotations-taints/#beta-kubernetes-io-arch-deprecated`
- In `content/en/docs/concepts/scheduling-eviction/assign-pod-node.md`
  - `/docs/reference/kubernetes-api/labels-annotations-taints/`
  => `/docs/reference/labels-annotations-taints/`
- In `content/en/docs/concepts/workloads/controllers/replicaset.md`
  - `/docs/reference/command-line-tools-reference/labels-annotations-taints/#pod-deletion-cost`
  => `/docs/reference/labels-annotations-taints/#pod-deletion-cost`
- In `content/en/docs/concepts/workloads/pods/pod-topology-spread-constraints.md`
  - `/docs/reference/kubernetes-api/labels-annotations-taints/`
  => `/docs/reference/labels-annotations-taints/`
- In `content/en/docs/reference/_index.md`
  - `/docs/reference/kubernetes-api/labels-annotations-taints/`
  => `/docs/reference/labels-annotations-taints/`

[FYI: There exist redirect rules in `static/_redirects`]
```
/docs/api-reference/labels-annotations-taints/     /docs/reference/labels-annotations-taints/ 301
/docs/reference/kubernetes-api/labels-annotations-taints/ /docs/reference/labels-annotations-taints/ 301
```

[Optionally, add this line in `static/_redirects`]
```
/docs/reference/command-line-tools-reference/labels-annotations-taints/     /docs/reference/labels-annotations-taints/ 301
```

**Pages to Update:**
- https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost
- ...

/assign

### LINKED ISSUE #27569: Errors in reference/command-line-tools-reference/feature-gates.md
**This is a Bug Report**

**Problem:**
In https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates
a typo ("resouce") exists.

**Proposed Solution:**
`resouce` => `resource`

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

/assign

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Resolves #27565
- Resolves #27569

### CODE REVIEW

**Comment by kbhawkey** [comment]
/kind cleanup

Page preview:
https://deploy-preview-27577--kubernetes-io-master-staging.netlify.app/docs/reference/labels-annotations-taints/

**Comment by kbhawkey** [comment]
Thanks @jihoon-seo .
/lgtm

**Comment by jihoon-seo** [comment]
I found another error in `content/en/docs/reference/labels-annotations-taints.md`.

[As-is]
```
[Pod Deletion Cost](/docs/content/en/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost)
```

[To-be]
```
[Pod Deletion Cost](/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost)
```

PTAL again after my commit, squash, and force-push.
Thanks!

**Comment by kbhawkey** [comment]
Thanks @jihoon-seo .
/approve

**Pull request merged**
