### PR TITLE
Kubernetes Docs Sprint: lowercase volume

### PR DESCRIPTION
**Pull request by shivaylamba**
Signed-off-by: Shivay Lamba <shivaylamba@gmail.com>

Update Volumes to lowercase based on https://github.com/kubernetes/website/issues/37487

- [x] (content/en/docs/concepts/storage/volumes.md)

### CODE REVIEW

**Comment by shivaylamba** [comment]
@reylejano @natalisucks @bradtopol @chrisnegus

**Comment by Rishit-dagli** [comment]
/lgtm
Congrats on your first contribution!

**Review by Rishit-dagli — APPROVED** [review]
/lgtm
Congrats on your first contribution!

**Pull request merged**
