### PR TITLE
Branch sync: Merge master release 1.18

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Branch sync: Merge master release 1.18

cc: @zacharysarah @jimangel @kbarnard10 

/assign @jimangel

### CODE REVIEW

**Comment by zacharysarah** [comment]
/approve
Explicit hold for @jimangel 
/hold

**Review by sftim — CHANGES_REQUESTED** [review]
This doesn't look right to me: the only changes are from the _zh_ localization.

**Comment by savitharaghunathan** [comment]
> This doesn't look right to me: the only changes are from the _zh_ localization.

The branch was created yesterday. When I checked today it was ~30 commits behind the main branch. I will verify it again just to be sure.

**Comment by savitharaghunathan** [comment]
@sftim You are right. This branch is still 14 commits behind the main branch :(

**Comment by zacharysarah** [comment]
@savitharaghunathan Can you open another merge PR?

**Comment by savitharaghunathan** [comment]
> @savitharaghunathan Can you open another merge PR?

Yes, I will. Thanks, @zacharysarah!

**Comment by savitharaghunathan** [comment]
@zacharysarah @sftim : Created https://github.com/kubernetes/website/pull/23365 which has all the ~14 commits that were missed. Apologies for the inconvenience

**Pull request merged**
