### PR TITLE
Fixed Broken link in Feature gates

### PR DESCRIPTION
**Pull request by AmarNathChary**
This PR fixes issue #40653

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The proposed change would fix the broken link.
LGTM makes sense.
/lgtm

**Comment by dipesh-rawat** [comment]
@AmarNathChary Thanks for the fix.
We do occasionally see Netlify build failures due to timeouts. You could try the following to retrigger Netlify build without losing `lgtm` label.

```
git reset
git commit --amend --no-edit
git push --force-with-lease
```

**Comment by AmarNathChary** [comment]
Hi @dipesh-rawat thanks for helping now Checks have passed PTAL

**Review by sftim — COMMENTED** [review]
Thanks
/approve

**Pull request merged**
