### PR TITLE
Add content/es/docs/concepts_workloads_controllers/jobs-run_and_replicaset

### PR DESCRIPTION
**Pull request by emedina**
Spanish Translation

### CODE REVIEW

**Comment by raelga** [comment]
Thanks! Tracked at #13948.

**Comment by glo-pena** [comment]
Hi, apologies. Been quite busy lately. I will get to this one this week. Promise

**Comment by raelga** [comment]
Perdón por la demora!

**Comment by emedina** [comment]
@raelga @alexbrand @glo-pena Actualizado con lo último de master...

**Pull request merged**
