### PR TITLE
Update metrics documentation for v1.31

### PR DESCRIPTION
**Pull request by mengjiao-liu**
### Issue

Closes: #48538

Wait for the upstream PR https://github.com/kubernetes/kubernetes/pull/128376 to merge first.
/hold

### CODE REVIEW

**Comment by mengqiy** [comment]
/lgtm

Preview: https://deploy-preview-48568--kubernetes-io-main-staging.netlify.app/docs/reference/instrumentation/metrics/

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/pull/48684

**Comment by mengjiao-liu** [comment]
> @mengjiao-liu if v1.32 is released and this still hasn't merged, please change this PR to target the _release-1.31_ branch, then unhold it.

Okay, if it's not merged by then, here's what I'll do. Thanks!

**Comment by tengqm** [comment]
/hold cancel
Thanks for pushing this forward.

**Pull request merged**
