### PR TITLE
Promote it-sprout-team

### PR DESCRIPTION
**Pull request by LeonidPistryi**

### CODE REVIEW

**Comment by sftim** [comment]
Hi @LeonidPistryi . Can you explain the thinking behind submitting this PR?

**Comment by LeonidPistryi** [comment]
> Hi @LeonidPistryi . Can you explain the thinking behind submitting this PR?



> Hi @LeonidPistryi . Can you explain the thinking behind submitting this PR?

Hi, Tim Bannester, yep sure, out team want to demonstrate a project

**Comment by LeonidPistryi** [comment]
> Thanks for contributing here; however, this repository is for actual contributions to Kubernetes. If you'd like to work on a different piece of work, please consider setting up your own repository.

But here is example of cloud-agnostic K8S implementation

**Comment by sftim** [comment]
You were hoping to promote your tproject?

- we don't accept promotional messages
- also, please do not remove existing documentation when making unrelated changes

/hold
/retitle Promote it-sprout-team
We should not make this change

**Comment by LeonidPistryi** [comment]
> You were hoping to promote your tproject?
> 
>     * we don't accept promotional messages
> 
>     * also, please do not remove existing documentation when making unrelated changes
> 
> 
> /hold /retitle Promote it-sprout-team We should not make this change

Hi, Tim Bannister, 
Thanks for remarks,
Could you tell me a recommendation for a better way to promote a project project ?

**Comment by reylejano** [comment]
@LeonidPistryi , please add a description for this PR
How does this fit and improve the stateless application tutorial section?

**Comment by LeonidPistryi** [comment]
> @LeonidPistryi , please add a description for this PR How does this fit and improve the stateless application tutorial section?

@reylejano , hi, thanks for you`re a comment )
1. Run WordPress in stateless
2. Use Tekton for build
3. Have full CI/CD to deploy AWS/GCP/Azure

**Comment by sftim** [comment]
Thanks for the explanation @LeonidPistryi 

The change you're suggesting is not useful to make.
I propose to close this pull request.

**Pull request closed without merging**
