### PR TITLE
修复翻译问题

### PR DESCRIPTION
**Pull request by wangjuns**
bin packing在这里不是指“二进制打包”，而是指“装箱”。see https://en.wikipedia.org/wiki/Bin_packing_problem

### CODE REVIEW

**Comment by wangjuns** [comment]
CLA signed

**Comment by xichengliudui** [comment]
You need to sign the cla agreement first

**Comment by wangjuns** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> :memo: **Please follow instructions at <https://git.k8s.io/community/CLA.md#the-contributor-license-agreement> to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify.  Thanks.
> 
> ---
> 
> - If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> - If you signed the CLA as a corporation, please sign in with your organization's credentials at <https://identity.linuxfoundation.org/projects/cncf> to be authorized.
> - If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: <https://support.linuxfoundation.org/>
> - Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: login-issues@jira.linuxfoundation.org
> 
> 
> 
> <details>
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
> </details>
> 	

CLA signed

**Comment by wangjuns** [comment]
> You need to sign the cla agreement first

I have signed CLA, but CLA check not run again, how to fix this? Thanks

**Comment by RA489** [comment]
> > You need to sign the cla agreement first
> 
> I have signed CLA, but CLA check not run again, how to fix this? Thanks

do you mind verifying that the e-mail address you have on GitHub matches the one you signed the CLA with?

**Comment by wangjuns** [comment]
> > > You need to sign the cla agreement first
> 
> > 
> 
> > I have signed CLA, but CLA check not run again, how to fix this? Thanks
> 
> 
> 
> do you mind verifying that the e-mail address you have on GitHub matches the one you signed the CLA with? 

I have verified email followed instruction , same email used for GitHub and CLA

**Comment by RA489** [comment]
> > > > You need to sign the cla agreement first
> > 
> > 
> > > 
> > 
> > 
> > > I have signed CLA, but CLA check not run again, how to fix this? Thanks
> > 
> > 
> > do you mind verifying that the e-mail address you have on GitHub matches the one you signed the CLA with?
> 
> I have verified email followed instruction , same email used for GitHub and CLA

If so, add a comment that says "I signed it". so that the CLA tchecker will re-verify.

**Comment by wangjuns** [comment]
I signed it

**Comment by wangjuns** [comment]
> > > > > You need to sign the cla agreement first
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > I have signed CLA, but CLA check not run again, how to fix this? Thanks
> > > 
> > > 
> > > do you mind verifying that the e-mail address you have on GitHub matches the one you signed the CLA with?
> > 
> > 
> > I have verified email followed instruction , same email used for GitHub and CLA
> 
> If so, add a comment that says "I signed it". so that the CLA tchecker will re-verify.

Seemed that does't work, it's there any other way to trigger CLA check again?

**Comment by tengqm** [comment]
Failed to check CLA status after 30 days.
/close

**Pull request closed without merging**
