### PR TITLE
fix the percent to set to disable percentageOfNodesToScore

### PR DESCRIPTION
**Pull request by yashbhutwala**

### CODE REVIEW

**Comment by denkensk** [comment]
Thanks. @yashbhutwala  I guess that `100` means that we use `numAllNodes`. And it may also means that we disable this feature of `percentageOfNodesToScore`.
```go
func (g *genericScheduler) numFeasibleNodesToFind(numAllNodes int32) (numNodes int32) {
	if numAllNodes < minFeasibleNodesToFind || g.percentageOfNodesToScore >= 100 {
		return numAllNodes
	}
```

**Comment by yashbhutwala** [comment]
@denkensk I see, you may be right.   You're referencing the code [here](https://github.com/kubernetes/kubernetes/blob/567c1bb4ec25776851c7cd7a50cbc5c460074477/pkg/scheduler/core/generic_scheduler.go#L440).  [This](https://github.com/kubernetes/kubernetes/blob/b8b7c376edb62ce8be42cef3728112c5c71d9fa4/staging/src/k8s.io/kube-scheduler/config/v1alpha1/types.go#L78) comment is also interesting, maybe misleading.  I think I'm more confused about this now 😄

**Comment by yashbhutwala** [comment]
ping @sftim the original author on this, could you please clarify? 😃

**Comment by sftim** [comment]
@kubernetes/sig-scheduling-pr-reviews are best placed to comment on the technical side
/sig scheduling

**Comment by sftim** [comment]
Ping @kubernetes/sig-scheduling-pr-reviews

**Comment by kbhawkey** [comment]
Hello @yashbhutwala . Thanks for opening this PR.
From reading the previous comments, there appear to be remaining questions.
A technical review would help clarify the changes.

Just noting that in the source code, `minFeasibleNodesToFind = 100`.
https://github.com/kubernetes/kubernetes/blob/567c1bb4ec25776851c7cd7a50cbc5c460074477/pkg/scheduler/core/generic_scheduler.go#L58

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-17389--kubernetes-io-master-staging.netlify.com/docs/concepts/scheduling/scheduler-perf-tuning/

**Comment by kbhawkey** [comment]
@Huang-Wei, @ahg-g . Would you have a moment to provide a technical review of this PR or suggest another reviewer from SIG-Scheduling? Thank you!

**Comment by Huang-Wei** [comment]
@yashbhutwala @kbhawkey We should keep the doc (100 meant to evaluate all nodes) as is. Because if `percentageOfNodesToScore` is set to 0, scheduler will calculate a ratio range from 5% to 50%:

```go
	adaptivePercentage := g.percentageOfNodesToScore
	if adaptivePercentage <= 0 {
		basePercentageOfNodesToScore := int32(50)
		adaptivePercentage = basePercentageOfNodesToScore - numAllNodes/125
		if adaptivePercentage < minFeasibleNodesPercentageToFind {
			adaptivePercentage = minFeasibleNodesPercentageToFind
		}
	}
```

**Comment by kbhawkey** [comment]
Thank you @Huang-Wei .

**Comment by kbhawkey** [comment]
Hello @yashbhutwala ,
I plan to close this pull request.
If you feel that you have further questions about this PR, you can reopen the pull request.
/close

**Pull request closed without merging**
