### PR TITLE
Update authentication.md

### PR DESCRIPTION
**Pull request by mdgrotheer**
Small grammatical corrections

### CODE REVIEW

**Comment by mdgrotheer** [comment]
I signed the CLA

**Comment by mdgrotheer** [comment]
I signed it

**Comment by irvifa** [comment]
@mdgrotheer can you please sign the cla?

**Comment by mdgrotheer** [comment]
> @mdgrotheer can you please sign the cla?

I thought I had. I just went back through the process and signed it

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-24604--kubernetes-io-master-staging.netlify.app/docs/reference/access-authn-authz/authentication/

**Comment by kbhawkey** [comment]
Thanks for contributing @mdgrotheer .
/lgtm

**Pull request merged**
