### PR TITLE
Update network-policies.md

### PR DESCRIPTION
**Pull request by suratwant**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.13-ko.<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by caseydavenport** [comment]
Looks fine, though I'd expect this to be defaulted by the apiserver anyway - @suratwant were you not seeing this defaulted when attempting to create this policy?

**Comment by suratwant** [comment]
Thank you, no issues faced in practice. Objective was to provide explicit
context for first time readers.

**Pull request merged**
