### PR TITLE
[zh] Fix typo

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/36566/files

### CODE REVIEW

**Comment by Sea-n** [comment]
Could you give us some insight about what's the value of this PR?

**Review by Arhell — COMMENTED** [review]
Synchronization with the English version, I checked, there is only this change

**Review by bishal7679 — APPROVED** [review]
/lgtm

**Review by Pradumnasaraf — APPROVED** [review]
/lgtm

**Pull request merged**
