### PR TITLE
Merge main branch into dev-1.30

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
This PR syncs the dev-1.30 branch with the main branch to keep the dev-1.30 branch up to date.

cc: @drewhagen @Princesso @chanieljdan @celestehorgan

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
The merge conflict which was resolved, ptal:
```
$ git diff content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
diff --cc content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
index 428fc53959,6ebddabd8a..0000000000
--- a/content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
+++ b/content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md
@@@ -96,11 -96,11 +96,18 @@@ your cluster. Those fields are
    A domain is a particular instance of a topology. An eligible domain is a domain whose
    nodes match the node selector.
  
 +  <!-- OK to remove this note once v1.29 Kubernetes is out of support -->
    {{< note >}}
++<<<<<<< HEAD
 +  Before Kubernetes v1.30, the `minDomains` field was only available if the
 +  `MinDomainsInPodTopologySpread` [feature gate](/docs/reference/command-line-tools-reference/feature-gates/)
 +  was enabled (default since v1.28). In older Kubernetes clusters it might be explicitly
++=======
+   The `MinDomainsInPodTopologySpread` [feature gate](/docs/reference/command-line-tools-reference/feature-gates/)
+   enables `minDomains` for pod topology spread. Starting from v1.28,
+   the `MinDomainsInPodTopologySpread` gate
+   is enabled by default. In older Kubernetes clusters it might be explicitly
++>>>>>>> upstream/main
    disabled or the field might not be available.
    {{< /note >}}
```

**Review by sftim — COMMENTED** [review]
/lgtm

**Pull request merged**
