### PR TITLE
Travis - Checkout the right K8s release and align on go version

### PR DESCRIPTION
**Pull request by DanyC97**
Fixes https://github.com/kubernetes/website/issues/13121

cc @zacharysarah  as per our last night slack chat

### CODE REVIEW

**Comment by DanyC97** [comment]
ouch, does that mean the majority of our examples needs some _attention_ ?

**Comment by Bradamant3** [comment]
cc @tengqm -- Qiming, do you have ideas here? Seems related to fixes to the examples tests you've provided in the past. (See also #sig-docs Slack)

**Comment by tengqm** [comment]
Every release of k8s introduces some changes and/or refactoring that lead to test failure. The failure of this PR is expected and should be fixed. Need to examine the upstream code base to find out where the testing facility has been relocated.

**Comment by kbhawkey** [comment]
Hello. After some searching, here is one package change:
ValidationDaemonSet
ValidationDeployment
...
https://github.com/kubernetes/kubernetes/blob/56735065400825d03f8e8f1a546c7a7b5ba9c5fd/pkg/apis/apps/validation/validation.go

**Comment by kbhawkey** [comment]
@tengqm, I have not looked at the tests closely. Is this run for every build or only when an example changes. This area could use some documentation 👍

**Comment by DanyC97** [comment]
> is this run for every build or only when an example changes.
@kbarnard10 is run on every build i think - see https://github.com/kubernetes/website/blob/master/.travis.yml#L23-L26

**Comment by tengqm** [comment]
@kbhawkey The test cases use to run on every build, before #11555 was merged. For all branches we maintain, we are supposed to use the correct version of go-lang and the correct version of upstream code for checking. This ensures that the examples we provide are usable for the version against which we have checked. I agree we should document this -- every time we create a `dev-x.yz` branch, we should adapt the travis CI job to use the latest versions of go-lang and upstream code. There could be changes that require revisions to the examples (thus the merits of the tests), e.g. beta version of resources got dropped, testing facility relocated etc.

**Comment by kbhawkey** [comment]
Thanks for the explanation @tengqm.
- Is there a way to automate this when a new docs dev branch is created? For example, this file would be updated on the docs 1.1.4 dev branch now?
- The changes for 1.13 are retroactive and would be evaluated with package/build updates in this patch?

**Comment by DanyC97** [comment]
@tengqm i see you created a new PR, if that is the case i'll close this PR in favour of yours

**Pull request closed without merging**
