### PR TITLE
Fix Content Got Mixed btw EBS & EFS

### PR DESCRIPTION
**Pull request by imuneeeb**
### Description

Contente was mixed btw ebs and efs

### Issue
https://github.com/kubernetes/website/issues/48049

Closes: #

### CODE REVIEW

**Comment by stmcginnis** [comment]
/lgtm

Note, you should edit the PR description to put the issue number reference after the "Closes: #" so it properly links and closes the issue when this PR merges.

**Review by dipesh-rawat — COMMENTED** [review]
/approve

**Comment by imuneeeb** [comment]
@stmcginnis I didn't include it in the "Closes" section because this PR only addresses the content mix-up that occurred. I was hoping to see if there could be a more comprehensive fix to address the underlying issue and prevent similar mix-ups in the future.

**Pull request merged**
