### PR TITLE
[ko] Update apt repo GPG key URL

### PR DESCRIPTION
**Pull request by Affan-7**
English PR https://github.com/kubernetes/website/pull/42156/files

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@Affan-7 Thanks for your contribution! Not sure if these are the intended changes because there are more than 840 commits spanning various localized languages in this pull request. Please do look into it.

**Comment by dipesh-rawat** [comment]
Explicit hold to avoid accidental merges of (current) incorrect changes.
/hold

**Comment by Affan-7** [comment]
Yes, there is something wrong.

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de en es fr hi id it ja pl pt ru uk vi zh
/remove-sig release

**Pull request closed without merging**
