### PR TITLE
releng: Update release-managers doc

### PR DESCRIPTION
**Pull request by cici37**
Related issue: https://github.com/kubernetes/sig-release/issues/2152

/hold until https://github.com/kubernetes/sig-release/pull/2156 merges.

/assign @jeremyrickard
/cc https://github.com/orgs/kubernetes/teams/release-managers
/milestone v1.27
/priority important-soon

### CODE REVIEW

**Comment by tengqm** [comment]
#2156 is in.
/hold cancel

**Comment by reylejano** [comment]
https://github.com/kubernetes/sig-release/pull/2156 merged
/lgtm

**Pull request merged**
