### PR TITLE
add BFE-ingress-controller to the document ingress-controllers.md.

### PR DESCRIPTION
**Pull request by clarinette9**
add BFE Ingress Controller to the document ingress-controllers.md. 
I edit both the english and zh(simplified chinese) docs.

### CODE REVIEW

**Comment by clarinette9** [comment]
Hello, I have finished the CLA signature.  
Please help to proceed. Thank you.


Jian Song (clarinette9)













在 2021-11-06 20:44:34，"Kubernetes Prow Robot" ***@***.***> 写道：

Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: ***@***.***

Instructions for interacting with me using PR comments are available here. If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository. I understand the commands that are listed here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by clarinette9** [comment]
Hello, I have finished the CLA signature.
Please help to proceed. Thank you.

**Review by tanjunchen — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
