### PR TITLE
Annual cleanup of OWNERS_ALIASES - part 2

### PR DESCRIPTION
**Pull request by divya-mohan0209**
**Context:** We've been using the [maintainer's tool](https://github.com/kubernetes-sigs/maintainers) to clean up the OWNERS_ALIASES file for k/website annually. With this exercise, we aim to keep the file updated and hope to foster healthy community leadership within SIG Docs. The results of running the tool this year have been provided below.

**What do I need to do if I have been tagged on this PR:**
If you wish to continue as an approver, reviewer, or localization owner, please confirm your intent on this PR by **20th December 2023.**

**Points to note:**
- We recognize that GitHub isn't the only way to contribute and are **seeking confirmation on the intent to continue as an approver/reviewer for the next year based on your bandwidth.** 
- We also recognize that several of the listed names are localization owners and removal will warrant a discussion about the continuity of their respective localizations. 
- Failure to confirm your intent within the lazy consensus timeframe will cause removal from the OWNERS_ALIASES file.

**Changes proposed by this PR:**
- Remove @mehabhalodiya  from sig-docs-en-reviews
~~- Remove @rlenferink from sig-docs-de-owners and sig-docs-de-reviews~~
- Remove @bells17 and @kakts  from sig-docs-ja-reviews
- Remove @gochist from sig-docs-ko-reviews and sig-docs-ko-owners
~~- Remove @Fale and @mattiaperi from sig-docs-it-owners and sig-docs-it-reviews~~
- Remove @92nqb and @raelga from sig-docs-es-reviews and sig-docs-es-owners
- Remove @awkif and @feloy from sig-docs-fr-reviews and sig-docs-fr-owners
- Remove ~~@ariscahyadi~~and @danninov from sig-docs-id-reviews and sig-docs-id-owners
- Remove @femrtnz and @yagonobre from sig-docs-pt-reviews and sig-docs-pt-owners
- Remove @huynguyennovem and @truongnh1992 from sig-docs-vi-reviews and sig-docs-vi-owners
~~- Remove @nvtkaszpir from sig-docs-pl-reviews anf sig-docs-pl-owners~~
~~- Remove @kpucynski from sig-docs-pl-reviews~~

``` 
✗ maintainers prune --repository-devstats "kubernetes/website" --repository-github "kubernetes/website" --dryrun=true                
Running script : 11-16-2023 21:33:33
Processed /Users/divyamohan/Desktop/website/OWNERS
Processed /Users/divyamohan/Desktop/website/OWNERS_ALIASES
Found 40 unique aliases
Found 109 unique users
............................................................................................................................................................


>>>>> Contributions from kubernetes/website devstats repo and kubernetes/website github repo : 94
>>>>> GitHub ID : Devstats contrib count : GitHub PR comment count
sftim : 10387 : 1059 
tengqm : 7894 : 1968 
windsonsea : 2615 : 703 
reylejano : 533 : 349 
dipesh-rawat : 1605 : 323 
ydFu : 392 : 299 
divya-mohan0209 : 1679 : 297 
stormqueen1990 : 1392 : 142 
kbhawkey : 549 : 162 
Arhell : 507 : 168 
atoato88 : 438 : 129 
mengjiao-liu : 483 : 116 
my-git9 : 453 : 115 
t-inu : 377 : 111 
nasa9084 : 322 : 209 
shannonxtreme : 390 : 45 
Babapool : 376 : 42 
mrerlison(MrErlison) : 587 : 65 
seokho-son : 628 : 94 
asa3311 : 340 : 105 
jihoon-seo : 475 : 80 
howieyuen : 303 : 110 
saschagrunert : 261 : 73 
nate-double-u : 212 : 87 
krol3 : 163 : 49 
natalisucks : 159 : 79 
Sea-n : 125 : 82 
pacoxu : 225 : 49 
electrocucaracha : 109 : 56 
bishal7679 : 108 : 39 
edsoncelio : 108 : 66 
xmudrii : 265 : 39 
devlware : 144 : 38 
ramrodo : 213 : 31 
shurup : 127 : 37 
soltysh : 105 : 23 
enj : 133 : 22 
bradtopol : 91 : 31 
mehabhalodiya : 89 : 21 
bene2k1 : 69 : 29 
anubha-v-ardhan : 81 : 21 
katcosgrove : 62 : 20 
perriea : 68 : 19 
a-mccarthy : 80 : 18 
onlydole : 61 : 37 
kinzhi : 48 : 16 
MaxymVlasov : 95 : 13 
SataQiu : 41 : 11 
habibrosyad : 40 : 27 
ysyukr : 72 : 15 
jcjesus : 54 : 14 
cici37 : 85 : 13 
pohly : 127 : 12 
mfilocha : 43 : 15 
bentheelder(BenTheElder) : 40 : 11 
jeremyrickard : 39 : 10 
cpanato : 24 : 271 
remyleone : 31 : 26 
rekcah78 : 21 : 22 
ritazh : 67 : 10 
palnabarun : 28 : 13 
xichengliudui : 20 : 11 
ariscahyadi : 19 : 8 
girikuncoro : 18 : 15 
fabriziopandini : 16 : 18 
inductor : 14 : 17 
puerco : 18 : 14 
tanjunchen : 14 : 12 
mrbobbytables : 19 : 11 
justaugustus : 12 : 8 
huynguyennovem : 11 : 7 
nvtkaszpir : 14 : 5 
yagonobre : 11 : 5 
Fale : 17 : 7 
rlenferink : 8 : 7 
kpucynski : 9 : 9 
jmyung : 61 : 6 
jimangel : 6 : 11 
bells17 : 10 : 7 
92nqb : 7 : 4 
SaranBalaji90 : 8 : 3 
ameukam : 7 : 4 
truongnh1992 : 4 : 3 
Verolop : 4 : 4 
mattiaperi : 3 : 2 
tabbysable : 3 : 1 
salaxander : 3 : 2 
gochist : 2 : 2 
kakts : 2 : 2 
awkif(AWKIF) : 1 : 1 
danninov : 2 : 0 
raelga : 2 : 3 
femrtnz : 7 : 2 
feloy : 7 : 1 


>>>>> Missing Contributions in kubernetes/website (devstats == 0): 15
IanColdwater
Potapy4
annajung
chenrui333
chenxuc
cjcullen
cji
ianychoi
idvoretskyi
joelsmith
jrsapi
micahhausler
mkorbi
ptux
yoonian


>>>>> Low reviews/approvals in kubernetes/website (GH pr comments <= 10 && devstats <=20): 24
92nqb
Fale
SaranBalaji90
Verolop
ameukam
ariscahyadi
awkif
bells17
danninov
feloy
femrtnz
gochist
huynguyennovem
justaugustus
kakts
kpucynski
mattiaperi
nvtkaszpir
raelga
rlenferink
salaxander
tabbysable
truongnh1992
yagonobre
```

cc: @natalisucks @reylejano 

/kind cleanup

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Explicit hold till 20th December 2023.
/hold

**Comment by rlenferink** [comment]
I hereby confirm that I am still involved with sig-docs PR reviews.

I am not an active contributor at the moment but I **am** actively reviewing created PRs that are appointed to me.

**Comment by mattiaperi** [comment]
I confirm I am still involved as well.

**Comment by Fale** [comment]
I confirm I'm still involved a well

**Comment by ariscahyadi** [comment]
I confirm I still invlolved as well.

**Comment by nvtkaszpir** [comment]
I confirm I am still involved in reviews for Polish language, some suggestions are in direct talk to @mfilocha and not through github.

**Comment by kpucynski** [comment]
I confirm I am still involved in reviews for Polish language along with @nvtkaszpir and @mfilocha.

**Comment by divya-mohan0209** [comment]
@a-mccarthy @seokho-son @natalisucks @reylejano @sftim @onlydole @kbhawkey @tengqm 

FYA - The Vietnamese localization **does not** have a stable set of approvers/reviewers per the above review. We'll mark this as an agenda item for the next localization + SIG Docs meeting to seek consensus on the next steps.

The hold on this PR will be maintained till we outline those steps.

**Comment by a-mccarthy** [comment]
I've reached out twice in the Vi slack channel, https://kubernetes.slack.com/archives/CPHAWNF1Q/p1704733335575119, but have not heard back

**Comment by truongnh1992** [comment]
Hi, I still want to be involved in Vi localization. I want to nominate @dangdong163 to be a reviewer/approver as well

**Comment by a-mccarthy** [comment]
@truongnh1992 thank you for replying here. If you are planning to nominate someone to help with the review/approving for the localization they will need to be [Kubernetes Github Org members](https://github.com/kubernetes/community/blob/master/community-membership.md#member), be active in helping the localization, and then be added to the review/approver list in a separate PR. 

cc: @seokho-son

**Comment by divya-mohan0209** [comment]
Ack!

**Comment by asem-hamid** [comment]
Hi @divya-mohan0209 is their any tool for check individual devstats

**Comment by raelga** [comment]
I still want to be involved in Es localization. Thanks!

**Comment by JaxVN** [comment]
Hi, I still want to be involved in Vi localization.

**Comment by divya-mohan0209** [comment]
For folks who have commented *after* the target date, please note that you can **continue contributing** to the localization. However, we will be monitoring the activity over this year and if there's lesser activity noted, we will be laying down further processes to streamline the sustainability of localisations. This might/might not result in certain aliases being removed during the next annual activity. 

I'll be closing this PR with the changes tomorrow & would request people to **NOT COMMENT** further.

**Comment by kakts** [comment]
Sorry, I still want to be involved in Ja localization

**Comment by divya-mohan0209** [comment]
Okay, it seems that I screwed up the commit history & will be opening a new PR with these changes.
/close

**Pull request closed without merging**
