### PR TITLE
Update zh translation in container-runtimes.md

### PR DESCRIPTION
**Pull request by guzj11**
this pr updates some zh translation in container-runtimes.md

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
This is an incomplete PR.
Everytime we change a page that has already been translated, we have to check and sync all upstream changes from the English version, or else we will lose change tracking.
To find out what have been changed:

```
./scripts/lsync.sh content/zh/docs/setup/production-environment/container-runtimes.md
```

**Comment by guzj11** [comment]
I have signed the cla

**Comment by tanjunchen** [comment]
@guzj11
plz, consider the advice from tengqm. thanks

**Comment by guzj11** [comment]
this pr add a  translation and the english part related is consistent with the english version

**Pull request closed without merging**
