### PR TITLE
[ja] Fix link to dev@kubernetes mailing list

### PR DESCRIPTION
**Pull request by jberkus**
Update the link to the new Dev Googlegroup. Submitting one PR per localization per @sftim

### CODE REVIEW

**Comment by jihoon-seo** [comment]
/retitle [ja] Fix link to dev@kubernetes mailing list

**Review by ptux — COMMENTED** [review]
I've checked the preview and verified the change works.

**Review by Arhell — COMMENTED** [review]
/assign @nasa9084

**Pull request merged**
