### PR TITLE
Case studies refactor

### PR DESCRIPTION
**Pull request by bep**
This relates to #9481 and the video meeting we had last week. This is the first of a series of smaller PRs with the end goal of making it easier to add more languages to the Kubernetes site, and also hopefully make the site easier to maintain.

This particular PR is a rewrite of how the Case Studies section is built:

* Each case study is converted to a bundle with the images bundled with some simple naming convention: Images with "feature", "logo", and "video" in the filename is recognized.
* The hard-coded Case Studies landing pages is now a proper layout page with some simple loops.
* To add a showcase to the featured section in the top, add `featured: true` to front matter.
* For the video box, the first showcase with `video:` in front matter is chosen.
* The quotes shown is set in the front matter, key `quote`.
* The order of the "Kubernetes Users" list is slightly different from kubernetes.io. It is now sorted by the default Hugo sort order (in practice weight then title).

Note that the showcase pages themselves are still what I would consider being hardcoded HTML -- and will need some more work, but I thought I should take this in the same go as the home page.

/cc @zacharysarah

### CODE REVIEW

**Comment by zacharysarah** [comment]
@alexcontini 👋 PTAL
/assign @alexcontini

**Comment by mistyhacks** [comment]
Link for review: https://deploy-preview-9822--kubernetes-io-master-staging.netlify.com/case-studies/

**Comment by mistyhacks** [comment]
I think it is disconcerting that the header is inconsistent with the rest of the site. It almost looks like it hasn't fully loaded. Is this a bug in your implementation? The old case studies page does have the universal header.

**Comment by bep** [comment]
>Is this a bug in your implementation? 

Might be. There are some CSS class dependencies (from front matter) that we also might want to look at. I will look at it right now and come back with a fix.

**Comment by bep** [comment]
@mistyhacks I have pushed a fixed version.

* It fixes the layouts to be inline with kubernetes.io. I should have noticed that.
* I have also synched the Case Studies with master. I had to squash the commits to make that merge a little easier.
* There is one more "Kubernetes User" in this version vs. kubernetes.io, but I suspect that is a glitch in the old version: ING is featured, but not listed as a user.
* The order is also now weighted, which makes it slightly different in the user list, but it give you more control.

**Comment by mistyhacks** [comment]
/lgtm

Needs review and sign-off from the people in charge of case studies at CNCF.  Maybe @zacharysarah can assign the correct people.

**Comment by kbarnard10** [comment]
/assign @kbarnard10
/assign @alexcontini 

@alexcontini Can you take a look at this? 

@bep The Kubernetes User's section should be sorted alphabetically, otherwise looks good to me.

**Comment by alexcontini** [comment]
@mistyhacks @zacharysarah looks great to me! other than the Kubernetes user section not being alphabetical but that was already mentioned above

**Comment by bep** [comment]
>other than the Kubernetes user section not being alphabetical but that was already mentioned above

Note that it is easy to change the sort order. Now both the featured section and users section have the same order (weight and then title).

**Comment by kbarnard10** [comment]
@bep Could you change the user's section to just be sorted by title then? I don't think we'll have a situation where we'll want that sorted by weight.

**Comment by bep** [comment]
>@bep Could you change the user's section to just be sorted by title then? I 

Done.

**Comment by bep** [comment]
@zacharysarah I have rebased this to resolve the new merge conflict with master. It would be good to get this merged, as there is are certain dependencies/order to my work.

**Comment by zacharysarah** [comment]
@bep Thanks for the updates.

/lgtm
/approve

**Pull request merged**
