### PR TITLE
[ja] Fix secret name to be consistent with examples

### PR DESCRIPTION
**Pull request by mengjiao-liu**
[ja] sync content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md
en PR: https://github.com/kubernetes/website/pull/29072

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
/assign @nasa9084 
for approval

**Comment by mengjiao-liu** [comment]
ping @inductor @nasa9084 
for approval

**Comment by nasa9084** [comment]
sorry to be late
/approve

**Pull request merged**
