### PR TITLE
Fix link in local storage capacity isolation blog

### PR DESCRIPTION
**Pull request by reylejano**
Fix link in blog titled "Kubernetes 1.25: Local Storage Capacity Isolation Reaches GA"
/area blog

### CODE REVIEW

**Comment by Sea-n** [comment]
LGTM too.
/lgtm

**Review by ydFu — APPROVED** [review]
Now is the right link
/lgtm

**Comment by nate-double-u** [comment]
/lgtm
/approve

thanks everyone!

**Pull request merged**
