### PR TITLE
Placeholder for Built-in Defaulting

### PR DESCRIPTION
**Pull request by apelisse**
Place-holder pull-request (for now) for built-in defaulting (https://github.com/kubernetes/enhancements/issues/1929).

### CODE REVIEW

**Comment by annajung** [comment]
/hold cancel
k/k merged

**Comment by annajung** [comment]
hi @apelisse with k/k merged, please take some time to fill out the docs content to make sure this gets reviewed before the deadline. Once it's ready, please change the stage of PR from draft to ready for review.

**Comment by apelisse** [comment]
k/k's not merged, there are still several PRs that need to be merged and orchestrated. We're still confident we'll do it in time though.

**Comment by annajung** [comment]
Ah okay! thanks for the clarification. We were only tracking https://github.com/kubernetes/kubernetes/pull/95423 and wasn't aware of other PRs. Please remove the hold when all relevant PRs have been merged! Thank you

/hold

**Comment by sftim** [comment]
Hi @apelisse 

The earlier you can provide _some_ content, the earlier that SIG Docs can get reviewing. We'd really appreciate a chance to get as much reviewing done as we can before KubeCon.

**Comment by apelisse** [comment]
Thanks, that's great to know, we'll get started asap. We're still mostly rushing through for code-freeze, but I'll see what we can do.

**Comment by annajung** [comment]
Note:

Exception filed (pending approval)

**Comment by annajung** [comment]
/hold cancel
exception approved, k/k merged

**Comment by reylejano-rxm** [comment]
Hi @apelisse, please keep in mind that the [Docs PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) deadline is around the corner on Monday, November 23

**Comment by annajung** [comment]
looks like another PR was open to replace this PR https://github.com/kubernetes/website/pull/25151

/milestone clear
/close

**Pull request closed without merging**
