### PR TITLE
[docs] fix client-go example

### PR DESCRIPTION
**Pull request by dougsland**
- [en]: Add package main to client-go example 
- [ko]: Add package main to client-go example
- [zh]: Add package main to client-go example 
- [en]: add missing context module for the go example
- [ko]: add missing context module for the go example
- [zh]: add missing context module for the go example
- [zh] fix import examples for the client-go

### CODE REVIEW

**Comment by dougsland** [comment]
Hey @pjhwa @bradtopol anything I can do to move this patch set forward?

Thanks!

**Comment by pjhwa** [comment]
@dougsland Thank you for your contribution. 
Korean Team follows English documents. So, after approval for English document, we can check then.

**Review by tanjunchen — APPROVED** [review]

**Comment by tengqm** [comment]
/approve
for English and Chinese.

**Comment by pjhwa** [comment]
/lgtm
for Korean

**Pull request merged**
