### PR TITLE
 Update config.toml 1.27 for 1.28 release

### PR DESCRIPTION
**Pull request by Rishit-dagli**
Updating the supported releases for version 1.28.

/hold
/milestone 1.28

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
The base branch is wrong; it should be _release-1.27_

/approve
/hold
We need to fix the base branch.

**Review by sftim — COMMENTED** [review]
If you rebase against _main_, you'll see that the `fullversion` parameter has already been removed.

**Comment by Rishit-dagli** [comment]
> The base branch is wrong; it should be release-1.27

Yep so, on this. TL: DR I was earlier advised to make this on `dev-1.27` because we don't have a `release-1.27` branch.

Longer Version on Slack: [The thread with 1.27 docs lead](https://kubernetes.slack.com/archives/C0156PJ62RE/p1691683432301969?thread_ts=1691518062.898999&cid=C0156PJ62RE)

**Pull request closed without merging**
