### PR TITLE
[ko] add searchbar to index page

### PR DESCRIPTION
**Pull request by Arhell**

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
This change of adding searchbar looks in sync with main website ('en') [homepage](https://kubernetes.io/).
lgtm

[Preview Korean Homepage](https://deploy-preview-45068--kubernetes-io-main-staging.netlify.app/ko/)

**Review by jongwooo — COMMENTED** [review]
Thanks!

/lgtm

**Review by Arhell — COMMENTED** [review]
cc @seokho-son

**Pull request merged**
