### PR TITLE
Document ClusterTrustBundle promotion to beta

### PR DESCRIPTION
**Pull request by ahmedtd**
Placeholder

Enhancements Issue: https://github.com/kubernetes/enhancements/issues/3257

### CODE REVIEW

**Comment by chanieljdan** [comment]
Hi @ahmedtd 👋 just a reminder to take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday March 12th 2024 18:00 PST. 

Thank you!

**Comment by drewhagen** [comment]
/hold
@ahmedtd Kubernetes 1.30 is releasing today.
This PR will need to be targeting the `dev-1.31` branch once it is available. Our team will keep you posted.

**Comment by drewhagen** [comment]
You can reopen this in the next release cycle and target `dev-1.31`. Thanks! :)

**Comment by drewhagen** [comment]
Heads up that `dev-1.31` branch is created now, if you choose to reopen this for the new release.

**Pull request closed without merging**
