### PR TITLE
fix outdated admission option

### PR DESCRIPTION
**Pull request by fisherxu**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7297)

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
For those who want to get the context, ref: https://github.com/kubernetes/kubernetes/pull/58123

**Comment by tengqm** [comment]
should go to the release-1.10 branch.

**Comment by tengqm** [comment]
Also mention "closes: #7235"

**Comment by fisherxu** [comment]
@tengqm go to the release-1.10?

**Comment by tengqm** [comment]
@fisherxu yes, this change is to be released in 1.10, so should not be proposed to master branch.

**Comment by chenopis** [comment]
When I try to change the base branch, it introduces a deluge of commits. This PR should be rebased, or we should reimplement it in a separate PR that is targeted at `release-1.10`.

**Comment by Bradamant3** [comment]
Looks as though this issue was fixed in another PR. Closing unmerged.

**Pull request closed without merging**
