### PR TITLE
Merge main branch into dev-1.30

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
This PR syncs the dev-1.30 branch with main to keep the dev-1.30 branch up to date.

cc: @Princesso @drewhagen  @chanieljdan @celestehorgan

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
/lgtm

**Comment by dipesh-rawat** [comment]
Just a minor observation: The **_milestone 1.30_** isn't applied to the PR (incl. few other PRs) as expected, given its targeting of the `dev-1.30` branch. I see a changes merged in test/infra as part of https://github.com/kubernetes/test-infra/pull/31473 to update the milestone applier for k/website dev-1.30 release branch. It might be worthwhile to investigate if additional configuration is necessary. Perhaps this warrants the attention of the Release Docs team for further review. 
_(cc Release Team 1.30 Docs Lead @drewhagen)_

**Comment by dipesh-rawat** [comment]
One of the @kubernetes/sig-docs-leads would be able to assist with the approval needed for merging this branch synchronization PR.

**Comment by Vyom-Yadav** [comment]
@dipesh-rawat https://github.com/kubernetes/test-infra/pull/31860 should fix milestone applier failure.

**Review by Princesso — COMMENTED** [review]
/lgtm

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by drewhagen** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: **Once this PR has been reviewed and has the lgtm label**, please assign [tengqm](https://github.com/tengqm) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubernetes%2Fwebsite).
> 
> Needs approval from an approver in each of these files:
> * **[content/en/OWNERS](https://github.com/kubernetes/website/blob/dev-1.30/content/en/OWNERS)**
> * **[content/ja/OWNERS](https://github.com/kubernetes/website/blob/dev-1.30/content/ja/OWNERS)**
> * **[content/ko/OWNERS](https://github.com/kubernetes/website/blob/dev-1.30/content/ko/OWNERS)**
> * **[content/ru/OWNERS](https://github.com/kubernetes/website/blob/dev-1.30/content/ru/OWNERS)**
> * **[content/zh-cn/OWNERS](https://github.com/kubernetes/website/blob/dev-1.30/content/zh-cn/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment

/assign tengqm

**Comment by drewhagen** [comment]
Hello @tengqm! Can we get an approval for this?

I appreciate it, thanks! :)

**Pull request merged**
