### PR TITLE
Update hello-minikube.md

### PR DESCRIPTION
**Pull request by rbrtmrtn**
Fixed a few minor typos 😄

### CODE REVIEW

**Comment by rbrtmrtn** [comment]
I signed my CLA!

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-29811--kubernetes-io-main-staging.netlify.app/docs/tutorials/hello-minikube/

**Comment by kbhawkey** [comment]
Thanks @rbrtmrtn .
/lgtm

**Pull request merged**
