### PR TITLE
Revise device plugins page

### PR DESCRIPTION
**Pull request by sftim**
- Tweak wording for Device Plugins concept 
  - link to current API reference, not old deprecated one
- Clean up front matter
- Convert a tab to spaces to match other lines in snippet
- Add third party content disclaimer

[_Preview_](https://deploy-preview-30818--kubernetes-io-main-staging.netlify.app/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/)

### CODE REVIEW

**Comment by annajung** [comment]
@kubernetes/sig-node-pr-reviews PTAL

**Comment by sftim** [comment]
(this might not need tech review) - @annajung do you think it does?

**Comment by annajung** [comment]
You're right. The content is the same, just rewording and clean up.
Thank you!

/lgtm

**Comment by reylejano** [comment]
This PR cleans up the device plugins page
Thank you for the PR
/lgtm
/approve

**Pull request merged**
