### PR TITLE
update phase command to upload certs after expiration

### PR DESCRIPTION
**Pull request by Joseph94m**
Issue #17453

### CODE REVIEW

**Comment by neolit123** [comment]
thank you for sending the fix. looks fine..

/lgtm
i guess you also need to sign the CNCF CLA, as the bot requested above.

**Comment by Joseph94m** [comment]
CNCF CLA signed

**Comment by neolit123** [comment]
> commit missing GitHub user

this usually means that you have to add the CLA email as part of your github account.

**Comment by Joseph94m** [comment]
> > commit missing GitHub user
> 
> this usually means that you have to add the CLA email as part of your github account.

I already have, maybe it takes a while to update.

**Comment by neolit123** [comment]
/check-cla

> I already have, maybe it takes a while to update.

around 20% of the time the CNCF CLA signage does not work properly and one has to contact the CNCF help desk. :(

**Comment by neolit123** [comment]
actually looking at the commit:
> Joseph authored and Joseph94m 

you'd have to author only from the github user that has the CLA and the `git push -f` the new commit.

**Comment by Joseph94m** [comment]
I will redo the pull request with the appropriate user. push -f is not removing the old one

**Pull request closed without merging**
