### PR TITLE
misspell in french

### PR DESCRIPTION
**Pull request by cyplp**
just a small misspell in french

### CODE REVIEW

**Comment by cyplp** [comment]
cla signed

**Comment by remyleone** [comment]
/lgtm
/approve

Em dom, 21 de jul de 2019 13:58, Cyprien Le Pannérer <
notifications@github.com> escreveu:

**Comment by tengqm** [comment]
@cyplp Please try follow instructions here to debug CLA status if you have signed it.

**Comment by cyplp** [comment]
@tengqm done

**Pull request merged**
