### PR TITLE
en-docs: Add kubectl Installation Via Homebrew

### PR DESCRIPTION
**Pull request by kihahu**
- Add kubectl Installation Via Homebrew

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
looks good to me.
Checked https://docs.brew.sh/Homebrew-on-Linux . However, I don't have a Linux system to validate it.

@sftim could you please check this for technical accuracy and leave an lgtm.

**Comment by sftim** [comment]
I'll need to make a Linux sandbox with Homebrew in it, so it might be a while before I can get to this.

**Comment by kihahu** [comment]
@Rajakavitha1 @sftim Would a screenshot from me of the command run help with the validation?

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1 @sftim Would a screenshot from me of the command run help with the validation?

That would be awesome!! Thanks @kihahu

**Comment by kihahu** [comment]
@Rajakavitha1 @sftim see below screenshots.

Installing brew on linux
linux-install-brew


Installing kubectl with `brew install kubectl`
install-kubectl

Installing kubectl with `brew install kubernetes-cli`
install-kubectl-2

**Comment by Rajakavitha1** [comment]
Thank you so much for the screenshots @kihahu !!!
I have a suggestion for better content organisation: can we have a new title that reads: "Install using other package management" have the content for snap and homebrew in tabs similar to https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-native-package-management

**Comment by kihahu** [comment]
@Rajakavitha1  Take a look at the updated PR.

**Comment by Rajakavitha1** [comment]
I just checked: https://deploy-preview-17928--kubernetes-io-master-staging.netlify.com/docs/tasks/tools/install-kubectl/#install-using-other-package-management. The updates look good to me.
/lgtm
/approve

**Pull request merged**
