### PR TITLE
Translate blog into Chinese

### PR DESCRIPTION
**Pull request by liushaobo05**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by tengqm** [comment]
@liushaobo05 pls split this pr into two: one for blog, the other for tool's doc.
/hold

**Comment by markthink** [comment]
@liushaobo05  请参考此文档 https://github.com/k8smeetup/k8s-official-translation 签署 CLA 协议..

**Comment by liushaobo05** [comment]
已完成CLA协议签署





在 2019-06-09 21:42:20，"Xiaolong He" <notifications@github.com> 写道：


@liushaobo05 请参考此文档 https://github.com/k8smeetup/k8s-official-translation 签署 CLA 协议..

**Comment by tengqm** [comment]
@liushaobo05 I'm closing this PR because the CLA status check has not been resolved for over a month and the gate is unhappy of the changes. Please

- feel free to reopen this if you are still working on it, and
- try follow instructions [here](https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting) to debug your CLA status if you have already signed it.

**Pull request closed without merging**
