### PR TITLE
Update Documentation  for the feature https://github.com/kubernetes/kubernetes/issue…

### PR DESCRIPTION
**Pull request by smrutiranjantripathy**
Hi Team, 
I'm updating the document for the feature Support Elastic Ips in NLB.
https://github.com/kubernetes/kubernetes/issues/63959

### CODE REVIEW

**Comment by smrutiranjantripathy** [comment]
I signed it

**Comment by onlydole** [comment]
+1 - I agree with @jimangel

**Comment by smrutiranjantripathy** [comment]
> @smrutiranjantripathy is this documented anywhere on AWS? I would think an external link would be a better solution given the SIG Docs 3rd party content [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-docs/20191020-doc-policies-for-third-party-content.md)/ [issue](https://github.com/kubernetes/website/issues/20232).

Its not documented on AWS docs. It was a lot of trouble in finding the PR, so I thought of putting in the kubernete main document.

**Comment by sftim** [comment]
@smrutiranjantripathy I _strongly_ recommend that you update either https://github.com/kubernetes/cloud-provider-aws/tree/master/docs/book or https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/load-balancing.md - or attempt that - and then if that lands you change the Kubernetes documentation to hyperlink there.

If neither of those places accepts the change you want then in terms of updating the Kubernetes website your options are limited: the policy on documenting third party details is to hyperlink rather than to put that documentation into the website itself. What we can do from a SIG perspective is add some weight to your request to document this change elsewhere.

**Comment by zparnold** [comment]
@smrutiranjantripathy just to keep things clear, I'm going to close this, but we really do want your contribution! So if you have a chance to address the comments and reopen this PR I'd be happy to help you get this merged!

/close

**Pull request closed without merging**
