### PR TITLE
Fix #11982

### LINKED ISSUE #11982: Issue with k8s.io/docs/concepts/workloads/controllers/deployment/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
The nginx version of `yaml` file in the Creating a Deployment session should be `1.7.9` instead of `1.15.4`.
Because the examples of the following sessions(eg. Updating a Deployment,Rolling Back a Deployment... ) in this page both start with `1.7.9`
For example:
In Updating a Deployment session:
> Suppose that you now want to update the nginx Pods to use the nginx:1.9.1 image instead of the nginx:1.7.9 image.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4 <--- should be 1.7.9
        ports:
        - containerPort: 80
```

**Proposed Solution:**
Change `image:nginx: 1.15.4` to `image: nginx:1.7.9` in [https://k8s.io/examples/controllers/nginx-deployment.yaml](https://k8s.io/examples/controllers/nginx-deployment.yaml)

Change `Run the nginx image at version 1.15.4` to  `Run the nginx image at version 1.7.9`
**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment

### PR DESCRIPTION
**Pull request by DrmagicE**
Fix #11982

### CODE REVIEW

**Comment by DrmagicE** [comment]
CLA  signed

**Comment by Rajakavitha1** [comment]
@DrmagicE  thanks for the PR
/lgtm

**Comment by Hartmarken348** [comment]
11983

**Comment by mistyhacks** [comment]
Thanks for your submission. In the future, please provide more detail about the problem you are fixing in the title and description. Remember that the title of the PR becomes part of the commit message.

/approve

**Pull request merged**
