### PR TITLE
typo

### PR DESCRIPTION
**Pull request by ou-bing**
typo

### CODE REVIEW

**Comment by ou-bing** [comment]
> verify

verify

**Comment by tengqm** [comment]
Thanks.

**Comment by tengqm** [comment]
Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). To find out what are the upstream changes to be synced, do this:

```
./scripts/lsync.sh content/zh/docs/tasks/access-application-cluster/connecting-frontend-backend.md
```

**Comment by ou-bing** [comment]
> ./scripts/lsync.sh content/zh/docs/tasks/access-application-cluster/connecting-frontend-backend.md

I ran this command, It doesn't look like to update anything.

**Comment by tengqm** [comment]
@ou-bing Do NOT run the command on your local PR branch. Run it against the master branch, then you will see the diffs that need to be sync'ed.

**Comment by ou-bing** [comment]
> @ou-bing Do NOT run the command on your local PR branch. Run it against the master branch, then you will see the diffs that need to be sync'ed.

Do you mean the new file should contain all the changes in the output? like：

**Comment by tengqm** [comment]
Yes. Every patch to Chinese localization must be a "complete" one. See [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87).

**Pull request closed without merging**
