### PR TITLE
Fix broken link on Access Clusters Using the Kubernetes API page.

### PR DESCRIPTION
**Pull request by kadtendulkar**
Follow up on #35224

Updated on page [Access Clusters Using the Kubernetes API](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/)

### CODE REVIEW

**Comment by kadtendulkar** [comment]
Hello @divya-mohan0209 and @mehabhalodiya , please review the PR.

**Comment by shannonxtreme** [comment]
I'm not sure why the preview is failing, but the URL update LGTM

**Comment by divya-mohan0209** [comment]
Hello @kadtendulkar , please could you push the changes once again. I'd be happy to sign off on the change once the deploy preview is ready. Thanks!

**Comment by kadtendulkar** [comment]
I have raised new PR with the same changes because this PR is failing the test.
/close

**Pull request closed without merging**
