### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by MadalinaPatrichi**

### CODE REVIEW

**Comment by neolit123** [comment]
hi @MadalinaPatrichi,

`FSGroup` starts with an abbreviation `FS` and `F` is pronounced as `ef`, thus it's correct to have `an` before it. :)

**Comment by pweil-** [comment]
Agree with @neolit123.  Since it is pronounced 'ef-ess-group' it is correct to have 'an' here.

**Comment by neolit123** [comment]
BTW, @MadalinaPatrichi, we do have broken links in some places and possibly actual typos, so please free to contribute more changes!

help is greatly appreciated. :)

**Comment by Bradamant3** [comment]
@MadalinaPatrichi see review comments. Thanks for the PR, but we need to close unmerged.

**Pull request closed without merging**
