### PR TITLE
Note that Service Cloud Installer task is Google Cloud specific

### PR DESCRIPTION
**Pull request by sftim**
Relevant to #13017

### CODE REVIEW

**Comment by kbhawkey** [comment]
have you tried /hold cancel?

**Comment by zacharysarah** [comment]
@sftim Thanks for the PR. The WIP label does seem like it was applied arbitrarily. Maybe the fine folks in @kubernetes/sig-testing-pr-reviews 👋 have some input?

**Comment by kbhawkey** [comment]
/remove-do-not-merge/work-in-progress

**Comment by stevekuznetsov** [comment]
The PR started as a draft PR, which is why the label was added. Looking into why it was not removed when the PR was marked as ready for review

**Comment by sftim** [comment]
I'll close this and make a new PR.

**Pull request closed without merging**
