### PR TITLE
Fix a minor spelling error

### PR DESCRIPTION
**Pull request by Comradin**
Fixed a minor spelling error "disem" -> "diesem"

### CODE REVIEW

**Comment by raelga** [comment]
@Comradin  👋 Welcome to Kubernetes!

It looks like you're trying to merge to the dev branch `dev-1.15` instead of `master`. Please change the base of the pull request before proceeding and rebase your fork if is not up to date with upstream/master.

Don't hesitate to reach me at slack at `@rael` if you find any issue :)

**Comment by Comradin** [comment]
@raelga Thanks for the hint.

Can I change this in this pull request or should I close it and create a new one?

Never did something that `advanced` with a pull request before.

**Comment by Comradin** [comment]
Ah, sorry .. found the edit button before but did not recognize that the branch selection changed a drop down menue. Thought I could only edit the title ..

**Comment by rlenferink** [comment]
/lgtm
/approve
/hold cancel

Thanks for the trigger @raelga !

**Pull request merged**
