### PR TITLE
setup/independent: fix cilium installation guide for kubeadm

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <aanm90@gmail.com>

fixes https://github.com/kubernetes/website/issues/14323

### CODE REVIEW

**Comment by DanyC97** [comment]
thanks @neolit123 
/lgtm

@zhangxiaoyu-zidif please help review and approve, thx

**Comment by aanm** [comment]
@DanyC97 @neolit123 can we merge this so we can avoid having users running into issues? Thanks!

**Comment by neolit123** [comment]
@aanm 
the PR needs approval from sig-docs.

**Pull request merged**
