### PR TITLE
Fix feature state for PVC volume resize

### PR DESCRIPTION
**Pull request by rishavnandi**
Fixed 36628

- Changed feature-state shortcode to reflect that the feature is stable as of v1.24

### CODE REVIEW

**Comment by rishavnandi** [comment]
@sftim closed an old PR as I had included issue numbers in the commit messages.. kindly check this one out..lemme know if any changes are needed : )

**Comment by sftim** [comment]
/retitle Fix feature state for PVC volume resize

**Comment by mk46** [comment]
@rishavnandi Thanks for your effort.
https://github.com/kubernetes/website/issues/36628 was addressed in https://github.com/kubernetes/website/pull/36638
So, I am closing this.

**Pull request closed without merging**
