### PR TITLE
Replace Mermaid Inline diagrams with Mermaid SVG diagrams

### PR DESCRIPTION
**Pull request by chrismetz09**
[Broken Mermaid Graphs issue #31960 ](https://github.com/kubernetes/website/issues/31960) documents a problem where Mermaid inline diagrams will periodically generate a Mermaid syntax error. [Issue #32010](https://github.com/kubernetes/website/issues/32010) also documented this problem. 

Inline means Mermaid code is added to the .md file. Mermaid+SVG means an svg image file is generated from the [mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor) and added to the .md file using the `{{< figure >}} shortcode`. For a detailed explanation of these approaches, see the [Diagram Guide](https://kubernetes.io/docs/contribute/style/diagram-guide/).

This solution eliminates the Mermaid syntax error. 

Once the root problem of the Mermaid syntax error is identified and tested, a future PR will be created so the Mermaid inline approach can be used without generating a syntax error.

### CODE REVIEW

**Comment by chrismetz09** [comment]
https://deploy-preview-33971--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/ingress/

**Comment by chrismetz09** [comment]
Replaced mermaid inline with mermaid svg files in source-ip.md to address [Issue #32010](https://github.com/kubernetes/website/issues/32010)

**Comment by zacharysarah** [comment]
@chrismetz09 Thanks, this does fix the problem. After catching up on #31960 (whew!) I'm willing to approve this PR, though I do wonder how quickly the links to `mermaid.live` will go stale, and whether it might be better to remove the `link` attributes. Still, it's awfully handy functionality, and the choice shouldn't hold up this fix.

Other reviewers, feel free to LGTM.

/approve

**Review by sftim — COMMENTED** [review]
I'd sooner have this than not

/lgtm

**Pull request merged**
