### PR TITLE
Minor fix: Add code to the values.

### PR DESCRIPTION
**Pull request by Shubham82**
Add code to the node page size i.e. **2048KiB** and **1048576KiB** mentioned under [Manage HugePages](https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/#api), for better readability.

### CODE REVIEW

**Comment by Shubham82** [comment]
PTAL!

**Comment by tengqm** [comment]
I don't think this is appropriate. Those numbers are not literals to use for huge pages.

**Comment by Shubham82** [comment]
Hi @tengqm 

> Those numbers are not literals to use for huge pages.

I agree with this, but here it uses as an example so can we bold these words? just for better readability.
WDYT?

**Comment by Shubham82** [comment]
If it does not seem good to you then I will close this PR.

**Comment by Shubham82** [comment]
> I agree with this, but here it uses as an example so can we bold these words? just for better readability.
> WDYT?

Hi, @tengqm your thoughts on this?

**Comment by reylejano** [comment]
imo, the code example is already in inline code format, `hugepages-2Mi` and `hugepages-1Gi`. 

I agree with @tengqm and closing this PR
Feel free to reopen with `/reopen` in a comment to further discuss
/close

**Pull request closed without merging**
