### PR TITLE
Migrate styles for Community page

### PR DESCRIPTION
**Pull request by sftim**
/kind cleanup

Helps with #41171

Move the community styles into the SCSS asset we already have (both legacy and current). Also, drop the code for custom style loading.

[Before](https://k8s.io/community/) | [After](https://deploy-preview-47825--kubernetes-io-main-staging.netlify.app/community/)

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The [preview page (here) ](https://deploy-preview-47825--kubernetes-io-main-staging.netlify.app/community/)looks good and is rendering correctly.

/lgtm

**Comment by tengqm** [comment]
just a clarification: the contents from the community.css file are now merged into custom.css in this PR. this is a big change. Is the goal to eventually kill those customization or something else? If we are about to kill the customization (to better align with Docsy), why don't we just kill them from where they are today?

**Comment by sftim** [comment]
I can't send in my changes for https://github.com/kubernetes/website/issues/41171 as is, as they total about 15000 lines and the PR would be too big to review.

Instead, I expect to send this in as around 60 smaller PRs. This is one of those (see issue #41171 for a partial list of the others). Eventually the community page will align even more with Docsy, but this is a step on the journey.

We also have about five localizations where the community page in that localization uses the old styles, not even the current styles that we plan to replace. Before we can easily upgrade Docsy, we'll need to tackle (update? delete?) those pages too.

This feels like the right interim approach: it affords (makes possible) the switch to Docsy, it doesn't particularly harm the rendering of any of the up-to-date localizations, and it drops some legacy legacy support that we don't want to keep.

**Comment by sftim** [comment]
One direct benefit we get from making _this_ change: if [a proposed change to] the styles are outright invalid, the site doesn't build and the PR doesn't pass CI.

**Comment by tengqm** [comment]
My standing point is as this: as a docs community, we should strive to maintain as less code as we can. Better alignment to an existing theme/framework is one way to achieve this. So long we have a consensus on the eventual goal, I don't have an objection moving this forward.

**Comment by sftim** [comment]
(ready for another review)

**Comment by natalisucks** [comment]
We've spoken about aligning to the new Docsy for several reasons across our community meetings, and while I understand Qiming's concerns about maintaining less code, I also agree with Tim's approach that doesn't break other pages or burden other localizations too hastily who need to make updates (or at least review updates we will help them with).

Thanks @sftim for this work – adding my approval.
/approve

**Review by dipesh-rawat — COMMENTED** [review]
Good for us to take steps to align with upstream Docsy. The [preview page (here) ](https://deploy-preview-47825--kubernetes-io-main-staging.netlify.app/community/) is rendering correctly.

/lgtm

**Pull request merged**
