### PR TITLE
Remove kubelet --allow-privileged flag for etcd HA setup with kubeadm

### PR DESCRIPTION
**Pull request by ialidzhikov**
Ref #15045.

### CODE REVIEW

**Comment by cstoku** [comment]
@smana please approve this pr

**Comment by inductor** [comment]
@Smana ping

**Comment by inductor** [comment]
Can this be merged sooner? 👀

**Comment by ialidzhikov** [comment]
@tengqm, could you pleases assist?

**Comment by inductor** [comment]
@zacharysarah Can you merge this? :)

**Comment by zacharysarah** [comment]
@ialidzhikov 👋 In the future, please open different PRs for each language changed. Because each language has its own set of approvers, PRs with multiple languages slow reviews down. 

I opened an issue to make this clearer in the docs contribution guide: #15762. 

/approve

**Pull request merged**
