### PR TITLE
Fix command format in tutorial

### PR DESCRIPTION
**Pull request by tengqm**
Closes: #8788

### CODE REVIEW

**Comment by Bradamant3** [comment]
Hi @tengqm -- almost, but this still isn't right for continuing numbered lists. Sigh. There's a PR against the smoke test page here that explains what to do, #8622 if you want to read everything. TL;DR:

2. Numbered lists can have paragraphs or block elements within them.

        Just indent the content to be one tab stop beyond the text of the bullet
        point. **This paragraph and the code block line up with the `m` in
       `Numbered` above.**

(note from Jennifer: actually, they line up with the `N`, but I'm quoting from the PR)

If you could fix one more time, that would be great. Thanks!

**Comment by tengqm** [comment]
@Bradamant3 Thanks for the feedback. Will give it another stab.

**Comment by tengqm** [comment]
@Bradamant3 Ready for review now. The hack is ugly.

**Comment by Bradamant3** [comment]
@tengqm unfortunately, it's not a hack. It's the result of the very loose markdown spec and the differences between Kramdown, which we've been used to with GitHub and Jekyll, and BlackFriday, which Hugo uses. It doesn't look as though anything will change, either, unless a large and effective group puts pressure on Hugo. BlackFriday maintainers seem uninterested in these issues. (I did some digging into the issues that Misty links to from the PR cited in comments ^^)

Thanks for your patience -- I guess we all have to get used to The New Way(s) of Writing Markdown now.

/lgtm
/approve

**Pull request merged**
