### PR TITLE
Topology manager

### PR DESCRIPTION
**Pull request by sharjeelaziz**
Minor update to fix a typo.

### CODE REVIEW

**Comment by jimangel** [comment]
/lgtm
@sharjeelaziz would you mind squashing your commits? Other than that, this is good to merge.

**Comment by sharjeelaziz** [comment]
> /lgtm
> @sharjeelaziz would you mind squashing your commits? Other than that, this is good to merge.

Thanks for the feedback. I will keep an eye on that in the future.

**Comment by jimangel** [comment]
> Thanks for the feedback. I will keep an eye on that in the future.

@sharjeelaziz no problem! You can also squash this open PR. This might help: https://stackoverflow.com/a/47936110/4879521

Feel free to reach out with any questions!

**Comment by sharjeelaziz** [comment]
> > Thanks for the feedback. I will keep an eye on that in the future.
> 
> @sharjeelaziz no problem! You can also squash this open PR. This might help: https://stackoverflow.com/a/47936110/4879521
> 
> Feel free to reach out with any questions!

I tried and I am not sure if it is working for me as I end up with tons of commit messages in logs. Could be because I have merged and put a couple of additional pull requests after this one. So do not want to make it worse than it is.

**Comment by sftim** [comment]
@sharjeelaziz there's a [guide](https://kubernetes.io/docs/contribute/intermediate/#work-on-the-local-repository) to contributing that explains how to rebase. Does that help?

**Comment by sharjeelaziz** [comment]
@sftim thank you guys I will go through this guide and see if I can fix this.

**Comment by sharjeelaziz** [comment]
Does not seem to be working so closing the request.

**Comment by sftim** [comment]
@sharjeelaziz if you'd like more help making this contribution you can ask in [Slack](https://kubernetes.slack.com/messages/C1J0BPD2M/), or reply here.

(for a Slack invitation, visit https://slack.k8s.io/)

**Comment by sharjeelaziz** [comment]
> @sharjeelaziz if you'd like more help making this contribution you can ask in [Slack](https://kubernetes.slack.com/messages/C1J0BPD2M/), or reply here.
> 
> (for a Slack invitation, visit https://slack.k8s.io/)

Thanks for all the help guys. Really appreciate it. I tried fixing it but I was not able to fix this particular branch. Was able to fix my test repos according to the guides/information that you provided so learned a lot there. I have since closed this pull request and put in a new one. Sorry for adding to your work :)

**Pull request closed without merging**
