### PR TITLE
[ja] remove pod-overview.md and update links

### PR DESCRIPTION
**Pull request by s-kawamura-w664**
This PR remove content/ja/docs/concepts/workloads/pods/pod-overview.md.
That file was removed at #22603 for en.
That PR removed the following two files.
- content/ja/docs/concepts/workloads/pods/pod-overview.md
- content/en/docs/concepts/workloads/pods/pod.md

The pod.md was already removed from ja.
To remove pod-overview.md, I checked the fixes in #22603 against ja and found that most of the files have been fixed.
This PR updates the following.
- Remove pod-overview.md.
- Update the links.

memo:
We can confirm content/ja/docs/reference/glossary/pod.md by clicking `Pod` tooltip on https://deploy-preview-40034--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/workloads/controllers/deployment/.

### CODE REVIEW

**Comment by s-kawamura-w664** [comment]
I executed  force push because Netlify build failded.

**Comment by s-kawamura-w664** [comment]
Netlify build succeeded once and generated a preview, but for some reason it failed. Let's retry.

**Comment by atoato88** [comment]
/lgtm

Thank you for continuous works about improve the formatting aspect.

**Review by nasa9084 — COMMENTED** [review]
/assign
/approve

Thank you!

**Pull request merged**
