### PR TITLE
update-imported-docs in golang

### PR DESCRIPTION
**Pull request by mengqiy**
`update-imported-docs/config.yaml` should have the src and dest paths for the target files.

fixes: #4283

/assign @steveperry-53 

I'm not sure what branch (master or release-1.9) should this PR target.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6642)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@mengqiy The master branch is fine for this PR.

**Comment by mengqiy** [comment]
@steveperry-53 Are you going to use this script to update the imported docs for 1.9 release? Or if you want to keep the PRs that are manually crafted i.e. #6614 #6619 #6628?

**Comment by steveperry-53** [comment]
@mengqiy I was thinking I would use this script, and make a new PR to replace #6614, #6619, and #6628. Does that sound reasonable?

**Comment by mengqiy** [comment]
SG. I guess you only need to run it once after you populate the config.yaml. IOW, I guess you will only need 1 PR.

One concern: if this PR is merged into master branch, will you guys do fast-forward (or something else) to make 1.9 branch have this program as well?

**Comment by steveperry-53** [comment]
@mengqiy At this point, we should wait until after the 1.9 release to merge this PR. On Wednesday, 12/13, the plan is to merge kubernetes/website/release-1.9 into kubernetes/website/master. After that, we can merge this PR into master. In the meantime, I have cloned mengqiy/website:play, and am running the script to generate docs. I'll submit those generated docs in a PR to kubernetes/website:release-1.9. I should be able to do that tonight.

**Comment by steveperry-53** [comment]
See #6658.

**Comment by mengqiy** [comment]
Thanks for you feedback.
Can you provide me the `config.yaml`?
So I can reproduce it and check why it happens. And then fix it.

**Comment by steveperry-53** [comment]
```
repos:
- name: kubernetes
  remote: https://github.com/kubernetes/kubernetes.git
  branch: release-1.9
  files:
  - src: docs/admin/cloud-controller-manager.md
    dst: docs/reference/generated/cloud-controller-manager.md
  - src: docs/admin/kube-apiserver.md
    dst: docs/reference/generated/kube-apiserver.md
  - src: docs/admin/kube-controller-manager.md
    dst: docs/reference/generated/kube-controller-manager.md
  - src: docs/admin/kubelet
    dst: docs/reference/generated/kubelet.md
  - src: docs/admin/kube-proxy.md
    dst: docs/reference/generated/kube-proxy.md
  - src: docs/admin/kube-scheduler.md
    dst: docs/reference/generated/kube-scheduler.md
  - src: docs/user-guide/kubectl/kubectl.md
    dst: docs/reference/generated/kubectl/kubectl.md
- name: federation
  remote: https://github.com/kubernetes/federation.git
#  # Change this to a release branch when federation has release branches.
  branch: master
  files:
  - src: docs/admin/federation-apiserver.md
    dst: docs/reference/generated/federation-apiserver.md
  - src: docs/admin/federation-controller-manager.md
    dst: docs/reference/generated/federation-controller-manager.md
  - src: docs/admin/kubefed_init.md
    dst: docs/reference/generated/kubefed_init.md
  - src: docs/admin/kubefed_join.md
    dst: docs/reference/generated/kubefed_join.md
  - src: docs/admin/kubefed.md
    dst: docs/reference/generated/kubefed.md
  - src: docs/admin/kubefed_options.md
    dst: docs/reference/generated/kubefed_options.md
  - src: docs/admin/kubefed_unjoin.md
    dst: docs/reference/generated/kubefed_unjoin.md
  - src: docs/admin/kubefed_version.md
    dst: docs/reference/generated/kubefed_version.md
  ```

**Comment by mengqiy** [comment]
Thanks! I will dig it tomorrow or next Monday.

**Comment by mengqiy** [comment]
> See #6658. Notice that in some topics, the synopsis appears twice.

Do you mean it appears once in `synopsis` and once in `Example`?

> Example: kubectl options.

The link you gave actually links to `kubefed options`.

After digging this a bit, I found it's not the problem of this script. The generated doc looks the same. So if the format is wrong, then the issue is in the `federation` repo.

**Comment by steveperry-53** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/website/6642#-:-L0zSo4y6nfwo-nFv1-w:bnfp4nl)*

**Comment by steveperry-53** [comment]
@mengqiy Thanks for checking into this. My mistake on the link text; I meant it to say kubefed options. Ar you ready for me to merge this PR now?

These are the files that had the double synopsis:
* kubectl.md
* kubefed.md
* kubefed_init.md
* kubefed_join.md
* kubefed_options.md
* kubefed_unjoin.md
* kubefed_version.md

The synopsis appeared once just below the title and once just below the Synopsis heading. [This commit](https://github.com/kubernetes/website/pull/6658/commits/b4e8f3b2f6210edfd4f56efae0d8de35fb339f2c)shows the files where I removed the synopsis that appeared under the title.

When I get a chance, I'll take a look at the federation scripts, and see about getting those fixed.

Before I did the removal, the pages looked like this:

**kubefed init**

Initialize a federation control plane

**Synopsis**

Init initializes a federation control plane.

**Comment by mengqiy** [comment]
> kubefed init
Initialize a federation control plane
Synopsis
Init initializes a federation control plane.

> kubefed join
Join a cluster to a federation		
Synopsis
Join adds a cluster to a federation. 

The wording are not the same, so I think they not duplicate but they are generated from different origins with similar meaning.

**Comment by steveperry-53** [comment]
@mengqiy Should I go ahead and merge this PR?

**Comment by mengqiy** [comment]
Please go ahead and merge it. :)
It should not have any risk.

**Pull request merged**
