### PR TITLE
Fix direct link issue in docs/concepts/workloads/pods/pod-overview

### PR DESCRIPTION
**Pull request by lovejoy**
change it to relative link

### CODE REVIEW

**Comment by ajaeger** [comment]
This looks wrong - it will not work once we branch the document, e.g. https://v1-10.docs.kubernetes.io/docs/concepts/workloads/pods/pod-overview/

**Comment by lovejoy** [comment]
I can't unstand the problem you are describe
It works well in https://deploy-preview-9366--kubernetes-io-master-staging.netlify.com/docs/concepts/workloads/pods/pod-overview/

________________________________

**Comment by lovejoy** [comment]
@ajaeger

**Comment by ajaeger** [comment]
@lovejoy, if we branch this page to 1.12, the link to the blog will not work. Example: https://v1-10.docs.kubernetes.io/blogs does not exist - and with your changes it would need to exist (for 1.12) to work.

**Comment by lovejoy** [comment]
@ajaeger  ok , I understand .

**Pull request closed without merging**
