### PR TITLE
Update config.toml for bengali language 

### PR DESCRIPTION
**Pull request by rajibmitra**
Added minimum-required-content for bengali language.

### CODE REVIEW

**Comment by rajibmitra** [comment]
cc @nikhita  @raelga  @zacharysarah

**Comment by remyleone** [comment]
@rajibmitra Thanks for starting the localization effort :) You can find the official documentation about starting a localization here: https://kubernetes.io/docs/contribute/localization/  You can also check out the Vietnamese translation that got started recently: https://github.com/kubernetes/website/pull/16965/files

**Comment by raelga** [comment]
Hello @rajibmitra, thanks for starting this localisation effort!

It would be great to include all the [minimum-required-content](https://kubernetes.io/docs/contribute/localization/#minimum-required-content) in this Pull Request to get things started:

 - [x] [Modify the site configuration](https://kubernetes.io/docs/contribute/localization/#modify-the-site-configuration)
 - [ ] [Add a new localization directory](https://kubernetes.io/docs/contribute/localization/#add-a-new-localization-directory)
 - [ ] [Add a localized README](https://kubernetes.io/docs/contribute/localization/#add-a-localized-readme)
 - [ ] [Setting up the OWNERS files](https://kubernetes.io/docs/contribute/localization/#setting-up-the-owners-files)

Also you will need to make a PR in [cncf/foundation](https://github.com/cncf/foundation/tree/master/code-of-conduct-languages)

 - [ ] [Localize the Community Code of Conduct](https://kubernetes.io/docs/contribute/localization/#localize-the-community-code-of-conduct)

You can use https://github.com/kubernetes/website/pull/13543, https://github.com/kubernetes/website/pull/13822 or https://github.com/kubernetes/website/pull/12548 as reference.

Feel free to ping me on slack at `@rael`.

**Comment by zacharysarah** [comment]
@rajibmitra Thanks for undertaking this localization! 

You must also create a repository label for Bengali content by opening a pull request in k/test-infra. You can use the [Vietnamese label](https://github.com/kubernetes/test-infra/pull/14817) as an example.

**Comment by zacharysarah** [comment]
@rajibmitra Please feel free to `/reopen` when you're ready to resolve merge conflicts and continue.

/close

**Pull request closed without merging**
