### PR TITLE
[zh] optimise translation of taint-and-toleration.md

### PR DESCRIPTION
**Pull request by howieyuen**
Co-authored-by: @keashem
related https://github.com/kubernetes/website/pull/28938#event-5023776075

### CODE REVIEW

**Comment by tengqm** [comment]
@howieyuen Do you mind adding `Co-authored-by: @keashem` in the PR message?

**Comment by howieyuen** [comment]
> @howieyuen Do you mind adding `Co-authored-by: @keashem` in the PR message? I'm asking because keashem obviously messed up his/her PR commits due to lack of understanding about the comparison script. However he/she did tried to help fix the same issue.

I read the conversation history, I though he closed PR and not plan to continue, so I create new PR.

**Comment by howieyuen** [comment]
Co-authored-by: @keashem

**Comment by tengqm** [comment]
Thanks.
/lgtm
/approve

**Pull request merged**
