### PR TITLE
Update link in page authorization

### PR DESCRIPTION
**Pull request by gaoguangze111**
Update link in Chinese page authorization.md. Page updated: https://kubernetes.io/zh/docs/reference/access-authn-authz/authorization/

### CODE REVIEW

**Comment by tengqm** [comment]
@gaoguangze111 We have a helper script for finding link problems. You will find a lot of missing links to fix if you run the following command:

```
./scripts/linkchecker.py -l zh -f /docs/reference/access-authn-authz/**/*.md
```

I'd encourage you to include more fixes in a PR rather than many small PRs with a few fixes.

**Comment by gaoguangze111** [comment]
Updated more links in this PR @tengqm

**Review by markthink — COMMENTED** [review]
/lgtm
/approve

**Comment by tengqm** [comment]
Thank you,
/lgtm
/approve

**Pull request merged**
