### PR TITLE
Add glossary entry for Quantity

### PR DESCRIPTION
**Pull request by Sajiyah-Salat**
Issue: https://github.com/kubernetes/website/issues/30885
Old PR: https://github.com/kubernetes/website/pull/39014

Hello, I am trying to solve the above given issue. From my old pr you can see that I have messed up the final part before merge which is squashing a pr. Because of this I am opening this pr to make things wasy for me. Thank you.

### CODE REVIEW

**Comment by Sajiyah-Salat** [comment]
Hello @NitishKumar06 please merge this pr. Thank you.

**Comment by sftim** [comment]
/retitle Add glossary entry for Quantity

Also, please rename `content/en/docs/reference/glossary/Quantity.md` to `content/en/docs/reference/glossary/quantity.md` (all lowercase)

**Comment by Sajiyah-Salat** [comment]
This file already exist. Check it out [here](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/quantity.md). Now should I make change to the old file or close this pr.

**Comment by sftim** [comment]
I would change the existing file. You don't need to make a new PR. Sorry about the mix up.

**Comment by sftim** [comment]
/hold

There is a glossary entry already; we might want to keep it as-is, or to clarify it.

**Comment by Sajiyah-Salat** [comment]
if you want to clarify I would like to help you in that. since I have already worked on it. I have better understanding like what to add or not. If you are okay i will start to work on that for sure.

**Pull request closed without merging**
