### PR TITLE
[zh] Update /reference/kubectl/_index.md

### PR DESCRIPTION
**Pull request by JieweiYan**
fixed some semantic errors.

### CODE REVIEW

**Comment by aj11anuj** [comment]
@JieweiYan, Thank you for raising a PR! 

You need to sign CLA for Authorization, before your PR can get reviewed. You can easily sign CLA by following instructions of EasyCLA bot from above.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by windsonsea** [comment]
This will be closed due to failed CLA check. Feel free to re-open it when you have signed CLA, thanks.

/close

**Pull request closed without merging**
