### PR TITLE
DNM: Testing build script

### PR DESCRIPTION
**Pull request by tengqm**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For Chinese localization, base branch to release-1.14
>
> For Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by kbhawkey** [comment]
@tengqm, if you edit the commit message to start with WIP, the PR will be, `WIP` or hold.

**Comment by tengqm** [comment]
@jimangel any idea why I cannot see any output from the script?

**Comment by tengqm** [comment]
@chenopis any hints on debugging the build environment so that the example test scripts can be resurrected?

**Comment by jimangel** [comment]
@tengqm will you fix the merge conflicts? Once the PR is clean, I'm happy to help looking into debugging the output. Thanks!

**Comment by kbhawkey** [comment]
@tengqm , What is the status of this PR? Close?

**Comment by tengqm** [comment]
Ya. This can be closed. It is impossible to debug this without proper access to the netlify infra. But I do hope someone with privileges can take over this job to ensure that all examples we reference from the documentation actually work.

**Pull request closed without merging**
