### PR TITLE
[hi] Add README file for Hindi

### PR DESCRIPTION
**Pull request by riyak-783**
This is a simple Hindi readme file.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@riyak-783, thanks so much for your contribution! Appreciate the effort. But we already have a [README.md](https://github.com/kubernetes/website/blob/main/content/hi/README.md) file for the **_Hindi_** localization located in the [content/hi (here)](https://github.com/kubernetes/website/tree/main/content/hi#readme) folder, so we may not need an additional one.

**Comment by dipesh-rawat** [comment]
/retitle [hi] Add README file for Hindi

**Comment by dipesh-rawat** [comment]
/hold
Apply hold on this PR to avoid accidental merge. 
There is already README.md file present for Hindi [(here)](https://github.com/kubernetes/website/blob/main/content/hi/README.md).

**Review by divya-mohan0209 — COMMENTED** [review]
Hi @riyak-783, thank you so much for your contribution!

As @dipesh-rawat has mentioned, we already have a README.md file for Hindi and if you'd like to suggest any improvements, we'd be happy to accept another PR. As it stands currently, I'll be closing this one off.

/close

**Pull request closed without merging**
