### PR TITLE
Update kubelet-config-file.md

### PR DESCRIPTION
**Pull request by dgvigil**
Updated the link from v1alpha1 to v1beta1

### CODE REVIEW

**Comment by mtaufen** [comment]
@dgvigil FYI there were a number of things that also needed to be updated, so I sent #7561. Thanks!

**Comment by mtaufen** [comment]
also noticed that the generated previews have `FEATURE STATE: Kubernetes v1.9` at the top, when it should say `FEATURE STATE: Kubernetes v1.10` for any docs changes for our next release...

**Comment by heckj** [comment]
@dgvigil if you haven't already, please sign the CLA so we can accept this update/patch. Is this specific to the release of 1.10, or relevant for the current version (v1.9)?

/assign

**Comment by mtaufen** [comment]
@heckj this is a dup of #7561, it can probably be closed (I don't have permissions).

**Comment by heckj** [comment]
closing as duplicate of #7561

**Pull request closed without merging**
