### PR TITLE
Add the banner for KubeCon + CloudNativeCon EU 2023

### PR DESCRIPTION
**Pull request by dipesh-rawat**
This PR:
Adds banner for KubeCon + CloudNativeCon EU 2023 on the K8s website.

kubecon23-banner

### CODE REVIEW

**Comment by sftim** [comment]
/committee steering
/lgtm
/approve

Thanks for adding it.

I can see that it overrides the k8s.gcr.io announcement banner during KubeCon.

**Comment by cblecker** [comment]
As we've done this previously and it's time limited to this week, I'm going to approve on behalf of steering.

/approve

**Comment by tpepper** [comment]
lgtm too

**Pull request merged**
