### PR TITLE
Last branch sync for main-> dev-1.22

### PR DESCRIPTION
**Pull request by PI-Victor**
Last branch sync before the release, this will merge the frozen main branch into the frozen dev-1.22 before we merge 1.22 back into main.

/cc @ashnehete @carlisia @chrisnegus @ritpanjw 

/assign @reylejano @annajung 

/milestone 1.22

### CODE REVIEW

**Comment by PI-Victor** [comment]
The last commit in this PR has failed because there's a freeze on the repo, which means i'll have to merge it manually, otherwise there are no failed commits here.

**Comment by annajung** [comment]
perfect! thanks Victor

/lgtm

**Comment by reylejano** [comment]
/hold for manual merge
/approve

remove hold when ready for manual merge

**Comment by PI-Victor** [comment]
/hold cancel

thanks!

**Pull request merged**
