### PR TITLE
tą instalację -> tę instalację

### PR DESCRIPTION
**Pull request by wojtekidd**
https://sjp.pwn.pl/poradnia/haslo/te-czy-ta;1598.html

### CODE REVIEW

**Comment by wojtekidd** [comment]
I signed the CLA

**Comment by mfilocha** [comment]
@wojtekidd Are you sure the CLA is signed an your commit uses the same email like the one defined in GitHub?

**Comment by wojtekidd** [comment]
I was changing emails lately, so probably that's the issue. Should I sign another CLA for the GitHub email or can I change the email in the already signed CLA to the one I use on GitHub?

**Comment by mfilocha** [comment]
@wojtekidd From https://identity.linuxfoundation.org/projects/cncf:
> 6. I signed the ICLA with the wrong email, what do I do?
> 
> Neither the email on the ICLA (captured from you Linux Foundation ID profile when you signed) nor the current email on the profile matters for passing the GitHub check.
> 
> For a PR to pass, each commit must pass this check: the Github user that the commit is attributed to (based on a match between the commit authorship and Github profile) must be linked to a Linux Foundation ID user (on the "social network logins" tab), who is authorized by a signed ICLA and/or a CCLA.

**Comment by wojtekidd** [comment]
This is how it looks on my end

Screen Shot 2020-01-16 at 14 40 43

**Comment by mfilocha** [comment]
@wojtekidd I'm afraid that _check-cla_ command doesn't work as expected. Before we open an issue, could you ensure the e-mail address and name _in your commit_ is exactly the same as is in _your GitHub profile_. I think it is the same, but please double check it.

**Comment by wojtekidd** [comment]
My apologies - the commit was using my old work email. I've updated my email settings now, but please let me know if it would be more convenient for you guys to close this PR and I'll create a new one from scratch.

**Comment by mfilocha** [comment]
@wojtekidd It should be enough to amend this commit with the proper email.

**Comment by mfilocha** [comment]
@wojtekidd I think you should squash all commits into one with the proper email. And push it with `--force-with-lease`

**Comment by wojtekidd** [comment]
I think I've done so, but can't see any changes here :/

**Comment by mfilocha** [comment]
No, there are three commits in this PR: https://github.com/kubernetes/website/pull/18701/commits

**Comment by mfilocha** [comment]
https://kubernetes.io/docs/contribute/intermediate/#work-on-the-local-repository

**Comment by wojtekidd** [comment]
I give up here, but thanks for the tip - I'll start once again from scratch according to the tutorial and I hope this time it will work. Sorry for all the problems caused :/

**Pull request closed without merging**
