### PR TITLE
Add Hyperlink to Kubernetes API

### PR DESCRIPTION
**Pull request by Ksmith30**
Adding a hyperlink to Kubernetes API for easier navigation of documentation as requested here (#18485)

### CODE REVIEW

**Comment by Ksmith30** [comment]
I have signed the CLA

**Comment by sftim** [comment]
Thanks @Ksmith30 
/lgtm

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-18852--kubernetes-io-master-staging.netlify.com/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

**Comment by Ksmith30** [comment]
@savitharaghunathan I could be wrong, but is that styling for markdown files? Am I able to style that link that way within an HTML file?

**Comment by savitharaghunathan** [comment]
@Ksmith30 , Thats a very good question. My understanding is that markdown styles can be used at all the places, but I might be wrong. @sftim can you provide some insight into where to use markdown and where to use html? TIA

**Comment by sftim** [comment]
I don't think Markdown will work here. If you [preview locally](https://kubernetes.io/docs/contribute/intermediate/#view-your-changes-locally) you can try this out for yourself.

**Comment by savitharaghunathan** [comment]
Thank you @sftim for your response. @Ksmith30 , your changes looks good. Sorry for any inconvenience that I caused.

**Comment by Ksmith30** [comment]
@savitharaghunathan No problem or inconvenience at all! I appreciate you showing me the style guide because this will help me in the future. 

@sftim I verified what you said locally.

**Comment by kbhawkey** [comment]
Thanks, @Ksmith30 .
/approve

**Pull request merged**
