### PR TITLE
add probe to glossary

### PR DESCRIPTION
**Pull request by MRHUB0**
Add Probe definition to glossary

Probe - a diagnostic performed periodically by the [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) on a container. To perform a diagnostic, the kubelet either executes code within the container, or makes a network request. 
 
/retitle Add glossary entry for probe
/language en
/kind feature

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Hi.

2 problems, one really important:
- the path `content/en/docs/reference/glossary/Probe.md` should be all lowercase (no capital P)
- `content/en/docs/reference/glossary/Probe.md` is empty, there's no glossary entry

/hold

OK to unhold this once there is content to review.

**Comment by natalisucks** [comment]
@MRHUB0 This is a friendly ping to address the review comments above, thanks!

**Comment by natalisucks** [comment]
@MRHUB0 Another ping regarding the review of this PR. If you wouldn't mind addressing Tim's feedback, then we can continue to review this week. If you don't have capacity right now, which is totally fine, you can close this PR until you're able to return to it. Thanks!

**Comment by natalisucks** [comment]
As per the above comments and the time that has elapsed for addressing feedback, I'll be closing this PR. The author can certaintly re-open and continue working when they have the capacity. Thanks again for your interest in contributing to the Kubernetes documentation!

/close

**Pull request closed without merging**
