### PR TITLE
[ko] Translate reference/glossary/storage-class.md in Korean

### PR DESCRIPTION
**Pull request by santachopa**
from #26393

### CODE REVIEW

**Comment by seokho-son** [comment]
@ClaudiaJKang 리뷰 가능하실까요  ~ ? ^^

/assign @ClaudiaJKang

**Comment by irvifa** [comment]
/retitle [ko] Translate reference/glossary/storage-class.md in Korean

**Comment by seokho-son** [comment]
Thank you @santachopa ~! It looks good.
/lgtm
/approve

**Pull request merged**
