### PR TITLE
modifying change cause for deployment

### PR DESCRIPTION
**Pull request by dejanu**
### Updating resources 
Add  command to update `CHANGE-CAUSE` in the Deployment revision

### CODE REVIEW

**Comment by reylejano** [comment]
The kubernetes.io/change-cause annotation is typically recorded when `--record` is used with kubectl
I don't know if it's best to override this annotation manually

**Comment by dejanu** [comment]
> reylejano

`--record` has been or will be deprecated? if yes what is the alternative to record change?

**Comment by stmcginnis** [comment]
I have not seen any plans or discussion to deprecate `--record`. That is the recommended way of capturing updates.

**Comment by sftim** [comment]
No evidence that this is change improves our docs.

/close

**Pull request closed without merging**
