### PR TITLE
docs-fr | reference | glossary | cri

### PR DESCRIPTION
**Pull request by ryanzidago**

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@zacharysarah the PR was lgtm'd and approved but cannot be merged due to the pending checks. Any way to trigger the check again?

**Comment by zacharysarah** [comment]
@xiangpengzhao That's odd--it looks like a serious netlify hiccup, and unfortunately I can't trigger a rebuild because it's trying to build as @rlenferink. (?!?!)

@remyleone 👋 Do you mind if I use my magic repo admin powers to manually merge this PR?

**Comment by remyleone** [comment]
@zacharysarah Please use your magic 🧙‍♂️✨

**Comment by rlenferink** [comment]
This is strange, I don't know what's happening here. When clicking on 'Details' for a `*-rlenferink` job (still don't know how these got created / started) I get a `Page not found. You might not have permissions to see this page.` on Netlify. When signing in to Netlify only 1 site is showing (https://celix-staging.netlify.com/, which is correct). Nothing related to k8s.

The strange thing is that GitHub checks is showing `Netlify / Header rules - kubernetes-rlenferink => started 40d 15h 20m 59s ago`. And it seems that it is still running.

**Pull request merged**
