### PR TITLE
Merged main into dev-1.24

### PR DESCRIPTION
**Pull request by nate-double-u**
Week 15 update to bring `main` into `dev-1.24` branch.

### CODE REVIEW

**Comment by nate-double-u** [comment]
/cc @JamesLaverack, @marosset FYI
/cc @jlbutler @sftim @reylejano

Note the update to Docsy v0.2.0 in this set.

This is an update to the closed https://github.com/kubernetes/website/pull/32943.

**Comment by nate-double-u** [comment]
please double check the merge of ` content/en/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md`

**Comment by nate-double-u** [comment]
Errors:
* [89c91ff](https://github.com/kubernetes/website/pull/33046/commits/89c91ff2c5a78ffb9b6881079726b43436b6ff1a) - Waiting for build to complete. I expect this is a Netlify issue.

**Comment by reylejano** [comment]
content/en/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md looks good!

**Comment by nate-double-u** [comment]
@sftim, could you take a look and give your `/lgtm` if the Docsy update looks correct to you. Now it's built I think it is, but since you made the original update PR in `main` I'd like your OK.

**Comment by reylejano** [comment]
Preview
https://deploy-preview-33046--kubernetes-io-vnext-staging.netlify.app

Docsy update looks to be there in .gitmodules

/approve

**Comment by nate-double-u** [comment]
weird, the bot didn't apply the approved label on @reylejano's /approve...

**Comment by reylejano** [comment]
> weird, the bot didn't apply the approved label on @reylejano's /approve...
> 
> Why does it want approval from [data/announcements/OWNERS](https://github.com/kubernetes/website/blob/dev-1.24/data/announcements/OWNERS)?

@nate-double-u because of the dockershim banner

**Comment by reylejano** [comment]
/assign @justaugustus 
This PR syncs the `dev-1.24` branch with `main` including PR https://github.com/kubernetes/website/pull/32805 that added a banner for the dockershim removal and requires a steering member to approve

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
