### PR TITLE
Updating directions for testing out kompose

### PR DESCRIPTION
**Pull request by CooperHanke**
Made some corrections to the documentation, as the output was not what I experienced, and also added directions for cleaning up after testing the example.

This is the first time I've contributed to open source, so if I need to change something, please let me know.

### CODE REVIEW

**Review by cdrage — APPROVED** [review]
LGTM

**Comment by CooperHanke** [comment]
@kbhawkey sorry I didn't mean to tag you in this yet, label is missing for `lgtm`; misunderstood the approval and didn't wait for the tag to be applied.

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
