### PR TITLE
Fixes: Diagram not rendering correctly on Ingress page with Chrome/Ubuntu #27008

### PR DESCRIPTION
**Pull request by ShivamTyagi12345**
I have updated the file referencing and copied contents and replace everything in [ static/js/mermaid.min.js](https://github.com/kubernetes/website/blob/main/static/js/mermaid.min.js) from the latest CDN (https://unpkg.com/mermaid@8.9.1/dist/mermaid.min.js). As suggested   [here ](https://github.com/kubernetes/website/issues/27008#issuecomment-800357845) .

### CODE REVIEW

**Comment by sftim** [comment]
Hi @ShivamTyagi12345 

If you [sign the CLA](https://github.com/kubernetes/website/pull/29334#issuecomment-897007004), we can review the changes you're suggesting.

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by ShivamTyagi12345** [comment]
> Hi @ShivamTyagi12345
> 
> If you [sign the CLA](https://github.com/kubernetes/website/pull/29334#issuecomment-897007004), we can review the changes you're suggesting.

hey @sftim @Arhell ,I signed the CLA just about now .Thanks

**Review by sftim — CHANGES_REQUESTED** [review]
This PR _does_ change `static/js/mermaid.min.js` but then a later commit reverts that.
@ShivamTyagi12345 this should be 1 single commit that changes 2 files:
- `static/js/mermaid.min.js`
- `layouts/partials/head.html`

Do you know how to make that change?

**Comment by ShivamTyagi12345** [comment]
> This PR _does_ change `static/js/mermaid.min.js` but then a later commit reverts that.
> @ShivamTyagi12345 this should be 1 single commit that changes 2 files:
> 
> * `static/js/mermaid.min.js`
> * `layouts/partials/head.html`
> 
> Do you know how to make that change?

I am not sure what exactly  is the cause that reverts the changes made in  `static/js/mermaid.min.js` . How can I make this right @sftim ?

**Comment by sftim** [comment]
To be honest, the easy way might be to open a brand new pull request. If so, feel free. Mention #29334 in the description of the new PR.

**Comment by ShivamTyagi12345** [comment]
> To be honest, the easy way might be to open a brand new pull request. If so, feel free. Mention #29334 in the description of the new PR.

Yes doing that right about now, Thanks

**Pull request closed without merging**
