### PR TITLE
Add VMware Kubernetes Engine to solutions list

### PR DESCRIPTION
**Pull request by jonasrosland**
This PR adds VMware Kubernetes Engine (VKE) to the list of hosted solutions, and a link to documentation to the list of IaaS Providers.

### CODE REVIEW

**Comment by tengqm** [comment]
LGTM.

Please try resolve the conflicts. @jonasrosland

**Comment by jonasrosland** [comment]
@tengqm I've resolved the conflicts, it should be good to go now.

**Comment by tengqm** [comment]
/lgtm
Thanks for the update.

**Comment by zacharysarah** [comment]
@jonasrosland 👋 Please feel free to reopen when you've resolved the merge conflict.

**Comment by cantbewong** [comment]
as suggested by k8s-ci-bot
/assign @jaredbhatti

**Pull request closed without merging**
