### PR TITLE
Fix tiny typo on deprecation-policy.md

### PR DESCRIPTION
**Pull request by kohbis**
### Description

Fix tiny typo

### Issue

Closes: nothing

### CODE REVIEW

**Review by Okabe-Junya — COMMENTED** [review]
LGTM

[Deploy Preview](https://deploy-preview-47479--kubernetes-io-main-staging.netlify.app/docs/reference/using-api/deprecation-policy/#deprecating-a-metric)

/assign @natalisucks

**Review by ydFu — APPROVED** [review]
/lgtm 

Fix typo

**Comment by Okabe-Junya** [comment]
Netlify doesn't work well?

**Comment by nate-double-u** [comment]
Hi @kohbis, thanks for this!
Please be careful to [avoid trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) in the future. Here are things to consider when making minor changes:
* Can the file be improved further?
* Does the small change greatly enhance the quality of the content?

To re-trigger the checks for this PR to merge, @kohbis, can you either `git commit --amend --date=now` or `git commit --allow-empty` and force push to your fork.

**Comment by Okabe-Junya** [comment]
xref: https://kubernetes.slack.com/archives/C1J0BPD2M/p1724177733039439?thread_ts=1724171554.489249&cid=C1J0BPD2M

> Thank you for taking a look!
> 
> Your feedback is spot on, and the comment about Trivial Edits is also very important. Thank you!
> 
> In the Japanese l10n project (and possibly in other l10n projects as well), we have been accepting many trivial changes to follow upstream, so I had slightly forgotten the important perspective on Trivial Edits. Thank you again for pointing that out.
>

**Pull request merged**
