### PR TITLE
hello service

### PR DESCRIPTION
**Pull request by webcane**
there is no `backend` service to be deleted. It was named originally `hello`

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
Hello @webcane .
Can you check if you have signed the CLA with your credentials?

**Comment by jimangel** [comment]
Hey there! @webcane, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
Hi @webcane .
Without a signed CLA, this pull request cannot be reviewed.
I plan on closing this PR; however, you can reopen this pull request at any time.
/close

**Pull request closed without merging**
