### PR TITLE
Restore images in Kubernetes Dashboard blog post

### PR DESCRIPTION
**Pull request by maciaszczykm**
Closes https://github.com/kubernetes/website/issues/27004.

### CODE REVIEW

**Comment by floreks** [comment]
@kbhawkey @sftim PTAL

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-27006--kubernetes-io-master-staging.netlify.app/blog/2021/03/09/the-evolution-of-kubernetes-dashboard/

**Comment by kbhawkey** [comment]
👋 @maciaszczykm .
The changes seem fine.
nit: You could add spacing between the images or possibly add a heading and then list an image.
The blog team approves blog updates/PRs.
/lgtm

**Comment by sftim** [comment]
Happy to see these images reinstated
/approve

**Pull request merged**
