### PR TITLE
Added short code around include statement

### PR DESCRIPTION
**Pull request by JuleeB1**

### CODE REVIEW

**Comment by cody-clark** [comment]
/assign @JuleeB1 
There's a few more notes

**Comment by cody-clark** [comment]
https://deploy-preview-10006--kubernetes-io-master-staging.netlify.com/docs/tasks/federation/federation-service-discovery/

**Comment by mistyhacks** [comment]
/lgtm
/approve
/hold
(in case the hackathon peeps are tracking these somewhere else. @Bradamant3 ?)

**Comment by Bradamant3** [comment]
/hold cancel

and thank you @mistyhacks for thinking of it. Improv all the way, though :-)

**Pull request merged**
