### PR TITLE
[pt-br] remove link

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/30496/files
/assign @edsoncelio
/assign @devlware

### CODE REVIEW

**Comment by edsoncelio** [comment]
Thanks, @Arhell, I'll check this tomorrow :)

**Comment by Arhell** [comment]
This is the same https://github.com/kubernetes/website/pull/30884
But I checked on the EN version, too, there is no this link, so everything is ok

**Pull request merged**
