### PR TITLE
Update Docker installation instructions

### PR DESCRIPTION
**Pull request by hakman**
The docs for installing Docker are a bit outdated. https://github.com/kubernetes/kubernetes/issues/82326#issuecomment-548777172
Thanks for clarifying and suggesting this @neolit123.

### CODE REVIEW

**Comment by neolit123** [comment]
/lgtm
Thanks!

**Comment by daminisatya** [comment]
Perfect Thank you so much @hakman 

/lgtm

**Comment by hakman** [comment]
Thanks a lot @neolit123 @daminisatya. This was very fast.
Please let me know if there is anything else I need to do and if I need to cherrypick this on other branches also.

**Comment by neolit123** [comment]
> Please let me know if there is anything else I need to do and if I need to cherrypick this on other branches also.

i'm pretty sure, the k/website respository does not allow cherry pics.

**Comment by hakman** [comment]
> i'm pretty sure, the k/website repository does not allow cherry pics.

Guess it was a n00b question :).
Meant if there is any need to create PR for the `dev-1.17` or `release-1.16` branches.

**Comment by neolit123** [comment]
given we are targeting 1.17 with this change then ideally this PR here should be against the dev-1.17 branch and this should be the only PR.

**Pull request closed without merging**
