### PR TITLE
[zh-cn] sync run-application/*

### PR DESCRIPTION
**Pull request by my-git9**
Changes to be committed:
```
#       modified:   content/zh-cn/docs/tasks/run-application/configure-pdb.md
#       modified:   content/zh-cn/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
#       modified:   content/zh-cn/docs/tasks/run-application/run-replicated-stateful-application.md
#       modified:   content/zh-cn/docs/tasks/run-application/run-single-instance-stateful-application.md
#       modified:   content/zh-cn/docs/tasks/run-application/run-stateless-application-deployment.md
```

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
/approve

**Comment by ydFu** [comment]
/lgtm
thanks

**Pull request merged**
