### PR TITLE
Format page rendering

### PR DESCRIPTION
**Pull request by angao**
- hugo markdown rendering engine can auto generate page catalog by paragraph structure

### CODE REVIEW

**Comment by angao** [comment]
@Bradamant3 yes, but the article is normal rendering in community repo, because it's rendering by github markdown engine. But it has rendering errors on office website

**Comment by Bradamant3** [comment]
@angao yeah, good point. But we don't want to maintain this content ourselves, either.

@chenopis ideas?

**Comment by angao** [comment]
@Bradamant3 en... if this content is copy from community repo, I think that's ok, they are independent and don't affect the content, just the format

**Comment by Bradamant3** [comment]
@angao yes but then we have to reformat every time there's a change to the source and we re-import. Andrew set up this workflow; I'd like him to weigh in before we make a final decision about how to proceed.

/assign @chenopis

**Comment by chenopis** [comment]
@angao This looks fine to me. I will figure out the long term issue of having two different markdown flavors between the repos. If you can fix the merge conflicts for this PR, we can then merge it.

/lgtm
/approve

**Comment by zacharysarah** [comment]
@angao 👋 Please feel free to reopen this PR when you're ready to resolve the merge conflicts.

**Pull request closed without merging**
