### PR TITLE
Update create-external-load-balancer.md

### PR DESCRIPTION
**Pull request by georgespatton**
Clearer descriptions and fixed typos.

### CODE REVIEW

**Comment by T-Lakshmi** [comment]
Hi @georgespatton,
As per community guidelines, it is mandatory to sign CLA before your PR can get reviewed. Please follow the steps to sign CLA  [here](https://contributor.easycla.lfx.linuxfoundation.org/#/cla/project/d8cead54-92b7-48c5-a2c8-b1e295e8f7f1/user/7684107d-aa22-4abb-931d-ece4df1a6ea0?redirect=https:%2F%2Fgithub.com%2Fkubernetes%2Fwebsite%2Fpull%2F43226) and get CLA signed.

**Comment by georgespatton** [comment]
@T-Lakshmi I don't know if I will be able to fulfill that CLA requirement.  Can you just take the code change and PR it yourself?

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by natalisucks** [comment]
@georgespatton Hi there – if you're unable to sign the CLA, then I'd recommend closing this pull request. Unfortunately, without the CLA signed, we won't be able to review and merge these changes. Thanks again for contributing and let us know if you have any questions.

**Pull request closed without merging**
