### PR TITLE
Update pod-lifecycle.md

### PR DESCRIPTION
**Pull request by climent**
Redundant "without problems" removed.

### CODE REVIEW

**Comment by bradtopol** [comment]
@climent Thank you for your contribution. Please sign the CLA so we can accept your PR for review.
/assign

**Review by Arhell — COMMENTED** [review]
@climent
1. Login to the [CLA site](https://identity.linuxfoundation.org/projects/cncf) and change it to match what you use as your default email address on your GitHub account
2. Change your default email address on your GH account to the same one you used to sign the CLA.

**Comment by zparnold** [comment]
Hi @climent we'd love to review your PR but we haven't heard from you. Please sign the CLA using the debug instructions when you have a sec so we can continue 😄

**Comment by zparnold** [comment]
Whoops! Looks like it is signed, I will review!

**Pull request merged**
