### PR TITLE
Fixed wrong imagepullsecret name

### PR DESCRIPTION
**Pull request by aleerizw**
Fixed a minor typo and some escaping

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7426)

### CODE REVIEW

**Comment by Bradamant3** [comment]
@aleerizw did you test this? The last time I ran bash scripts to send JSON, I needed the escape characters.
Nice catch on the secret name :-)

**Comment by aleerizw** [comment]
@Bradamant3 Yes, i tested this on bash. The command with the quotes wasn't working and this one works.

**Pull request merged**
