### PR TITLE
Update job.md

### LINKED ISSUE #29840: New line is needed between a unordered list item and a paragraph
**This is a Bug Report**

**Problem:**

[As-is]
https://kubernetes.io/docs/concepts/workloads/controllers/job/#completion-mode

```markdown
- `NonIndexed` (default): the Job is considered complete when there have been
  `.spec.completions` successfully completed Pods. In other words, each Pod
  completion is homologous to each other. Note that Jobs that have null
  `.spec.completions` are implicitly `NonIndexed`.
- `Indexed`: the Pods of a Job get an associated completion index from 0 to
  `.spec.completions-1`. The index is available through three mechanisms:
  - The Pod annotation `batch.kubernetes.io/job-completion-index`.
  - As part of the Pod hostname, following the pattern `$(job-name)-$(index)`.
    When you use an Indexed Job in combination with a
    {{< glossary_tooltip term_id="Service" >}}, Pods within the Job can use
    the deterministic hostnames to address each other via DNS.
  - From the containarized task, in the environment variable `JOB_COMPLETION_INDEX`.
  The Job is considered complete when there is one successfully completed Pod
  for each index. For more information about how to use this mode, see
  [Indexed Job for Parallel Processing with Static Work Assignment](/docs/tasks/job/indexed-parallel-processing-static/).
  Note that, although rare, more than one Pod could be started for the same
  index, but only one of them will count towards the completion count.
```

image

---

[Before the commit d6b142070dd6ed0ce4992a36f0f071f8d7012d4b]

```markdown
- `NonIndexed` (default): the Job is considered complete when there have been
  `.spec.completions` successfully completed Pods. In other words, each Pod
  completion is homologous to each other. Note that Jobs that have null
  `.spec.completions` are implicitly `NonIndexed`.
- `Indexed`: the Pods of a Job get an associated completion index from 0 to
  `.spec.completions-1`, available in the annotation `batch.kubernetes.io/job-completion-index`.
  The Job is considered complete when there is one successfully completed Pod
  for each index. For more information about how to use this mode, see
  [Indexed Job for Parallel Processing with Static Work Assignment](/docs/tasks/job/indexed-parallel-processing-static/).
  Note that, although rare, more than one Pod could be started for the same
  index, but only one of them will count towards the completion count.
```

**Proposed Solution:**

Edit [`en/docs/concepts/workloads/controllers/job.md`](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/workloads/controllers/job.md) as follows:

```diff
  `.spec.completions-1`. The index is available through three mechanisms:
  - The Pod annotation `batch.kubernetes.io/job-completion-index`.
  - As part of the Pod hostname, following the pattern `$(job-name)-$(index)`.
    When you use an Indexed Job in combination with a
    {{< glossary_tooltip term_id="Service" >}}, Pods within the Job can use
    the deterministic hostnames to address each other via DNS.
  - From the containarized task, in the environment variable `JOB_COMPLETION_INDEX`.
+                  
  The Job is considered complete when there is one successfully completed Pod
  for each index. For more information about how to use this mode, see
  [Indexed Job for Parallel Processing with Static Work Assignment](/docs/tasks/job/indexed-parallel-processing-static/).
  Note that, although rare, more than one Pod could be started for the same
  index, but only one of them will count towards the completion count.
```

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/job/#completion-mode

/kind bug
/language en
/good-first-issue

### PR DESCRIPTION
**Pull request by yedamao**
Add new line to fix #29840

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Please sign the CLA for this PR to be reviewed, more information here https://github.com/kubernetes/website/pull/29844#issuecomment-929055145

**Comment by jihoon-seo** [comment]
And your commit message
```
Update job.md
Add new line to fix #29840
```
contains hashtag(#), but 
> [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

So you have to remove hashtag(#) in your commit message. 😊

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by yedamao** [comment]
@jihoon-seo Thanks for your guide. I fixed the commit message and done the CLA.

**Comment by kbhawkey** [comment]
👋 @yedamao . Thanks for contributing.
This issue has been fixed in PR #29880. I plan to close this pull request.
/close

**Pull request closed without merging**
