### PR TITLE
fix(shortcode): Amend glossary definition shortcode

### PR DESCRIPTION
**Pull request by mariasalcedo**
When an "index-less" glossary definition  is being rendered, hugo throws the following `nil pointer`error:
```
execute of template failed: template: shortcodes/glossary_definition.html:15:19: executing "shortcodes/glossary_definition.html" at <$term_info.Content>: nil pointer evaluating resource.Resource.Content
```

This PR fixes this "nil pointer" error, by using an "Eager/greedy" evaluation of `$term_info`.
Error lines will be `else` thrown if `$term_info` variable is nil, stated at the `else` portion, instead of the initial `if`.

It won't show a more helpful error because all helpful errors are already included in the code.

### CODE REVIEW

**Comment by sftim** [comment]
@mariasalcedo I think with the PR description you're saying that the existing error message is:

> ```
> execute of template failed: template: shortcodes/glossary_definition.html:15:19: executing "shortcodes/glossary_definition.html" at <$term_info.Content>: nil pointer evaluating resource.Resource.Content
> ```

and that this PR improves on that by showing a more helpful error. Have I got that right?

**Comment by mariasalcedo** [comment]
> @mariasalcedo I think with the PR description you're saying that the existing error message is:
> 
> > ```
> > execute of template failed: template: shortcodes/glossary_definition.html:15:19: executing "shortcodes/glossary_definition.html" at <$term_info.Content>: nil pointer evaluating resource.Resource.Content
> > ```
> 
> and that this PR improves on that by showing a more helpful error. Have I got that right?

@sftim Sorry for not being clearer on the purpose of this PR! 😞 
It won't show a more helpful error because all helpful errors are already included in the code.
This PR fixes the "nil pointer" error, thrown when an "index-less" glossary definition is being rendered.

I will then add a more comprehensive explanation on the description.

Please let me know if the above explanation isn't clear enough.

**Comment by sftim** [comment]
OK, cool. Thanks for explaining.

**Comment by mariasalcedo** [comment]
@sftim PR description enriched!

**Pull request merged**
