### PR TITLE
[ko] fix broken links in install kubectl windows page

### PR DESCRIPTION
**Pull request by niteshseram**
It seems the same issue #29570 exist in this localization as well. 
/language ko

### CODE REVIEW

**Comment by niteshseram** [comment]
Deploy preview of the modified page https://deploy-preview-29574--kubernetes-io-main-staging.netlify.app/ko/docs/tasks/tools/install-kubectl-windows/

**Comment by jihoon-seo** [comment]
[As-is]
https://kubernetes.io/ko/docs/tasks/tools/install-kubectl-windows/
```
curl -LO https://dl.k8s.io/release//bin/windows/amd64/kubectl.exe
```

[Preview]
https://deploy-preview-29574--kubernetes-io-main-staging.netlify.app/ko/docs/tasks/tools/install-kubectl-windows/
```
curl -LO "https://dl.k8s.io/release/v1.22.0/bin/windows/amd64/kubectl.exe"
```

Nice fix! 😊
/lgtm

**Comment by seokho-son** [comment]
Thanks !
/approve

**Pull request merged**
