### PR TITLE
Tweak reference docs section index

### PR DESCRIPTION
**Pull request by sftim**
No need to mention the quickstart twice, so don't.

Existing page: https://kubernetes.io/docs/contribute/generate-ref-docs/quickstart/

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
+1 . The changes look good!

/lgtm

**Review by Arhell — COMMENTED** [review]
/lgtm

**Review by ydFu — APPROVED** [review]
Great, looks more readable
/lgtm

**Pull request merged**
