### PR TITLE
Typo fix in implementation-details.md

### PR DESCRIPTION
**Pull request by AdamDang**
does not exists->does not exist
does not contains->does not contain

### CODE REVIEW

**Comment by bradtopol** [comment]
Hi @AdamDang Thank you for your contribution. For the typo fix you made to the file under the blog folder, there is a  a separate set of reviewers for those posts. They appreciate comments on improving wording, but this PR will not be able to update that.  Please remove that update from this PR and I will then approve the remaining typo fixes.  cc @heckj @zacharysarah

**Comment by AdamDang** [comment]
Thanks! @bradtopol
I got it.  The blog changes was moved.
Sorry to know little about the project and make some troubles to you guys.

**Comment by zacharysarah** [comment]
@bradtopol Well, I just learned a very valuable lesson about k8s-ci-bot syntax! 😆

**Pull request merged**
