### PR TITLE
[ja] fix bind-address on scheduler

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/26500

### CODE REVIEW

**Comment by sftim** [comment]
Thanks @Arhell

**Comment by atoato88** [comment]
@Arhell 
What about assign @nasa9084 for approver because [k8s-ci-robot say do that](https://github.com/kubernetes/website/pull/27378#issuecomment-812223477)?
If I understand correctly, @oomichi don't have approving authority.

**Comment by oomichi** [comment]
> 
> 
> @Arhell
> What about assign @nasa9084 as approver because [k8s-ci-robot say do that](https://github.com/kubernetes/website/pull/27378#issuecomment-812223477)?
> If I understand correctly, @oomichi don't have approving authority.

That is normal thing to assign people who put `/lgtm` as an assignee even if they are not approvers.
We just need to get more eyes from approvers after that.

**Comment by nasa9084** [comment]
/assign
/approve
Thank you all

**Pull request merged**
