### PR TITLE
[ru] Update stale StatefulSet with Cassandra example

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubernetes/website/pull/47087/files

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Proposed change to `terminationGracePeriodSeconds` looks in sync with 'en' PR https://github.com/kubernetes/website/pull/47087/files

LGTM

**Comment by sftim** [comment]
/retitle [ru] Update stale StatefulSet with Cassandra example

**Comment by sftim** [comment]
LGTM

**Comment by shurup** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
