### PR TITLE
Update cron-jobs.md

### PR DESCRIPTION
**Pull request by corvofeng**
Sync with the english documents:

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

### CODE REVIEW

**Comment by tengqm** [comment]
@corvofeng Please sign the CLA.

**Comment by corvofeng** [comment]
I signed it

**Comment by corvofeng** [comment]
I signed it

**Comment by idealhack** [comment]
thanks for fixing this!

can you please add spaces between English and Chinese? and please fix the English text in the code comments above as well, otherwise LGTM.

if possible, please squash your commits and force push to your branch.

**Pull request merged**
