### PR TITLE
[zh] fix links

### PR DESCRIPTION
**Pull request by unbyte**
fix some links to english pages in Chinese pages and wrong links.

Btw, I noticed that the heading anchor in some Chinese pages is damaged. Maybe I will open another PR to fix these problems when I have time.

### CODE REVIEW

**Comment by tengqm** [comment]
Thanks for the help.
Could you move changes to tasks section into a separate PR?
I'm working on fixing links in the tasks section and the change made is quite extensive.

**Comment by tengqm** [comment]
BTW, if you can help focus on continue fixing the concepts section, here is a list of problems detected, for your info:

```
$ ./scripts/linkchecker.py -l zh -f /docs/concepts/**/*.md
Language: zh
File: content/zh/docs/concepts/configuration/secret.md
    /zh/docs/tasks/manage-kubernetes-objects/kustomization/: Missing link for [使用 Kustomize 管理对象]
File: content/zh/docs/concepts/scheduling-eviction/taint-and-toleration.md
    /zh/docs/concepts/configuration/pod-priority-preemption/: Missing link for [Pod 优先级]
File: content/zh/docs/concepts/storage/volume-snapshots.md
    /zh/docs/concepts/storage/persistent-volumes/: Missing link for [持久卷]
    /zh/docs/concepts/storage/persistent-volumes/#volume-snapshot-and-restore-volume-from-snapshot-support: Missing link for [卷快照和从快照还原卷]
File: content/zh/docs/concepts/storage/storage-classes.md
    /zh/docs/concepts/storage/persistent-volumes: Missing link for [持久卷]
    /zh/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims: Missing link for [PersistentVolumeClaim 章节]
    /zh/docs/concepts/storage/persistent-volumes/#provisioning: Missing link for [卷绑定和动态分配]
File: content/zh/docs/concepts/storage/volumes.md
    /zh/docs/tasks/configure-pod-container/security-context/: Missing link for [特权容器]
    /zh/docs/concepts/storage/persistent-volumes/: Missing link for [持久卷]
    /zh/docs/concepts/storage/persistent-volumes/: Missing link for [持久卷示例]
    /zh/docs/concepts/configuration/manage-compute-resources-containers/: Missing link for [resource]
    /zh/docs/concepts/storage/persistent-volumes/#raw-block-volume-support: Missing link for [安装您的带有块卷支持的 PV/PVC]
File: content/zh/docs/concepts/storage/dynamic-provisioning.md
    /zh/docs/concepts/storage/persistent-volumes/: Missing link for [`PersistentVolume` 对象]
    /zh/docs/setup/best-practices/multiple-zones/: Missing link for [多区域]
File: content/zh/docs/concepts/workloads/pods/disruptions.md
    /zh/docs/setup/best-practices/multiple-zones/: Missing link for [多区域集群]
    /zh/docs/tasks/administer-cluster/safely-drain-node/#the-eviction-api: Missing link for [Eviction API]
    /docs/concepts/workloads/pods/pod-lifecycle/#pod-termination: Link not using localized page
    /zh/docs/tasks/administer-cluster/safely-drain-node/: Missing link for [排空节点]
File: content/zh/docs/concepts/workloads/pods/ephemeral-containers.md
    /zh/docs/reference/using-api/deprecation-policy/: Missing link for [Kubernetes 弃用政策]
File: content/zh/docs/concepts/workloads/pods/_index.md
    /zh/docs/concepts/workloads/containers/job/: Missing link for [Job]
    /zh/docs/tasks/configure-pod-container/security-context/: Missing link for [安全性上下文]
    http://aurora.apache.org/documentation/latest/reference/configuration/#job-schema: Use HTTPS rather than HTTP
File: content/zh/docs/concepts/workloads/controllers/ttlafterfinished.md
    /zh/docs/concepts/workloads/controllers/jobs-run-to-completion/#clean-up-finished-jobs-automatically: Missing link for [示例]
File: content/zh/docs/concepts/workloads/controllers/cron-jobs.md
    /zh/docs/concepts/workloads/controllers/jobs-run-to-completion/: Missing link for [Jobs]
File: content/zh/docs/concepts/workloads/controllers/daemonset.md
    /docs/concepts/configuration/assign-pod-node/: Link using redirect records, should use /docs/concepts/scheduling-eviction/assign-pod-node/ instead
    /docs/concepts/configuration/assign-pod-node/: Link using redirect records, should use /docs/concepts/scheduling-eviction/assign-pod-node/ instead
    /zh/docs/concepts/configuration/pod-priority-preemption/: Missing link for [Pod 抢占]
File: content/zh/docs/concepts/workloads/controllers/deployment.md
    /docs/concepts/workloads/pods/pod/: Link using redirect records, should use /docs/concepts/workloads/pods/ instead
    /docs/concepts/workloads/controllers/replicaset/: Link not using localized page
    /docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/: Link not using localized page
    /docs/concepts/cluster-administration/manage-deployment/#canary-deployments: Link not using localized page
    /docs/tutorials/stateless-application/run-stateless-application-deployment/: Link using redirect records, should use /docs/tasks/run-application/run-stateless-application-deployment/ instead
    /docs/concepts/overview/working-with-objects/object-management/: Link not using localized page
    /docs/concepts/workloads/pods/pod-overview/#pod-templates: Link using redirect records, should use /docs/concepts/workloads/pods/ instead
    /docs/concepts/workloads/pods/pod/: Link using redirect records, should use /docs/concepts/workloads/pods/ instead
    /docs/concepts/overview/working-with-objects/labels/: Link not using localized page
    /docs/tasks/run-application/rolling-update-replication-controller/: Missing link for [滚动更新]
    /docs/concepts/workloads/pods/pod-lifecycle/#container-probes: Link not using localized page
File: content/zh/docs/concepts/workloads/controllers/statefulset.md
    /zh/docs/concepts/storage/persistent-volumes/: Missing link for [PersistentVolumes]
    /zh/docs/concepts/storage/persistent-volumes/: Missing link for [PersistentVolume]
File: content/zh/docs/concepts/workloads/controllers/replicaset.md
    /docs/user-guide/kubectl/: Link using redirect records, should use /docs/reference/kubectl/kubectl/ instead
    /docs/concepts/workloads/controllers/deployment/: Link not using localized page
    /docs/concepts/overview/object-management-kubectl/overview/: Link using redirect records, should use /docs/concepts/overview/working-with-objects/object-management/ instead
    /docs/concepts/workloads/pods/pod-overview/#pod-templates: Link using redirect records, should use /docs/concepts/workloads/pods/ instead
    /docs/concepts/workloads/pods/pod/: Link using redirect records, should use /docs/concepts/workloads/pods/ instead
    /docs/concepts/workloads/pods/pod-lifecycle/#restart-policy: Link not using localized page
    /docs/admin/kubelet/: Link using redirect records, should use /docs/reference/command-line-tools-reference/kubelet/ instead
    /docs/concepts/overview/working-with-objects/labels/: Link not using localized page
    /docs/concepts/workloads/controllers/garbage-collection/: Link not using localized page
    /docs/concepts/workloads/controllers/deployment/: Link not using localized page
    /docs/tasks/run-application/run-stateless-application-deployment/: Link not using localized page
    /docs/concepts/jobs/run-to-completion-finite-workloads/: Link using redirect records, should use /docs/concepts/workloads/controllers/job/ instead
    /docs/concepts/workloads/controllers/daemonset/: Link not using localized page
File: content/zh/docs/concepts/workloads/controllers/job.md
    /docs/user-guide/replication-controller: Link using redirect records, should use /docs/concepts/workloads/controllers/replicationcontroller/ instead
File: content/zh/docs/concepts/workloads/controllers/replicationcontroller.md
    /docs/reference/command-line-toolls-reference/kubelet/: Missing link for [Kubelet]
    /docs/concepts/workloads/controllers/job/: Link not using localized page
File: content/zh/docs/concepts/architecture/cloud-controller.md
    /docs/tasks/administer-cluster/developing-cloud-controller-manager/: Link not using localized page
    /docs/tasks/administer-cluster/running-cloud-controller/#cloud-controller-manager: Link not using localized page
File: content/zh/docs/concepts/architecture/control-plane-node-communication.md
    /zh/docs/reference/access-authn-authz/authentication/: Missing link for [身份认证]
    /zh/docs/reference/access-authn-autha/authentication/#anonymous-requests: Missing link for [匿名请求]
    /zh/docs/reference/access-authn-authz/authentication/#service-account-tokens: Missing link for [服务账号令牌]
    /zh/docs/tasks/extend-kubernetes/setup-konnectivity/: Missing link for [Konnectivity 服务任务]
File: content/zh/docs/concepts/extend-kubernetes/extend-cluster.md
    /zh/docs/reference/using-api/deprecation-policy/: Missing link for [支持政策]
    /zh/docs/concepts/extend-kubernetes/api-extension/custom-resources/: Missing link for [自定义资源概念指南]
    /zh/docs/reference/access-authn-authz/authentication/: Missing link for [身份验证文档]
    /zh/docs/reference/access-authn-authz/authentication/: Missing link for [身份认证]
    /zh/docs/reference/access-authn-authz/authentication/#webhook-token-authentication: Missing link for [身份认证 Webhook]
    /zh/docs/concepts/extend-kubernetes/api-extension/custom-resources/: Missing link for [自定义资源]
File: content/zh/docs/concepts/extend-kubernetes/operator.md
    /zh/docs/concepts/extend-kubernetes/api-extension/custom-resources/: Missing link for [自定义资源]
    /zh/docs/concepts/extend-kubernetes/api-extension/custom-resources/: Missing link for [自定义资源]
    /zh/docs/concepts/extend-kubernetes/api-extension/custom-resources/: Missing link for [自定义资源]
File: content/zh/docs/concepts/extend-kubernetes/_index.md
    /zh/docs/reference/using-api/deprecation-policy/: Missing link for [预定义的支持策略]
    /zh/docs/concepts/extend-kubernetes/api-extension/custom-resources/: Missing link for [自定义资源概念指南]
    /zh/docs/reference/access-authn-authz/authentication/: Missing link for [身份认证文档]
    /zh/docs/reference/access-authn-authz/authentication/: Missing link for [身份认证]
    /zh/docs/reference/access-authn-authz/authentication/#webhook-token-authentication: Missing link for [认证 Webhook]
    /zh/docs/concepts/extend-kubernetes/api-extension/custom-resources/: Missing link for [自定义资源]
File: content/zh/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
    /zh/docs/concepts/configuration/manage-resources-container/#extended-resources: Missing link for [扩展资源命名方案]
    /docs/tasks/administer-cluster/extended-resource-node/: Link not using localized page
    /zh/docs/tasks/adminster-cluster/topology-manager/: Missing link for [拓扑管理器]
File: content/zh/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
    /zh/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/: Missing link for [使用自定义资源定义扩展 Kubernetes API]
File: content/zh/docs/concepts/overview/kubernetes-api.md
    /zh/docs/reference/using-api/deprecation-policy/: Missing link for [API 废弃策略]
    /zh/docs/concepts/extend-kubernetes/api-extension/custom-resources/: Missing link for [自定义资源]
    /zh/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/: Missing link for [CustomResourceDefinition]
File: content/zh/docs/concepts/policy/resource-quotas.md
    /zh/docs/concepts/storage/persistent-volumes/: Missing link for [存储资源]
    /zh/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims: Missing link for [PVC]
    /zh/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims: Missing link for [持久卷申领]
    /zh/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims: Missing link for [PVC]
    /zh/docs/concepts/configuration/pod-priority-preemption/#pod-priority: Missing link for [优先级]
File: content/zh/docs/concepts/policy/pod-security-policy.md
    /zh/docs/concepts/security/pod-security-standards/#policy-instantiation: Missing link for [Pod 安全标准]
    /zh/docs/concepts/security/pod-security-standards/: Missing link for [Pod 安全标准]
File: content/zh/docs/concepts/cluster-administration/logging.md
    /examples/debug/counter-pod.yaml: Examples link, skipped
    /zh/docs/tasks/debug-application-cluster/logging-stackdriver/: Missing link for [Stackdriver 日志]
    /zh/docs/tasks/debug-application-cluster/logging-stackdriver/: Missing link for [Stackdriver]
File: content/zh/docs/concepts/cluster-administration/monitoring.md
    /zh/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior: Missing link for [Kubernetes 指标弃用策略]
File: content/zh/docs/concepts/cluster-administration/_index.md
    /zh/docs/reference/access-authn-authz/authentication/: Missing link for [认证]
```

**Comment by unbyte** [comment]
I'm happy to help when I have time. Anyway, I will remove the changes to the tasks section first.

**Comment by unbyte** [comment]
@tengqm I've done. I'll open another PR to solve problems in concept section.

**Comment by tengqm** [comment]
Gate isn't happy though this is good work ...

**Comment by unbyte** [comment]
The failure just now may be due to a bug😂now it works happily

**Comment by tengqm** [comment]
A big thank you!
/lgtm
/approve

**Pull request merged**
