### PR TITLE
Fix Broken layout for tabs page in Korean

### PR DESCRIPTION
**Pull request by Evalle**
PR Summary:
- Fixes https://github.com/kubernetes/website/issues/23739
- Preview: https://deploy-preview-23752--kubernetes-io-master-staging.netlify.app/ko/docs/setup/production-environment/container-runtimes/

### CODE REVIEW

**Comment by gochist** [comment]
@Evalle Thank you!!!
/lgtm

**Comment by Evalle** [comment]
@gochist 천만에요 :)

**Pull request merged**
