### PR TITLE
Corrección al uso confuso de container

### PR DESCRIPTION
**Pull request by AdolfoJulcamoro**
Dice: you need to build a new container that includes the change

Debe decir you need to build a new image that includes the change

### CODE REVIEW

**Comment by AdolfoJulcamoro** [comment]
I signed it

**Comment by zacharysarah** [comment]
@AdolfoJulcamoro 👋  Por favor firme la [licencia de contribuidores](https://identity.linuxfoundation.org/projects/cncf) para continuar. Para las propuestas de cambios por Ingles, por favor hablemos en Ingles. Gracias

**Comment by AdolfoJulcamoro** [comment]
Hello, I already signed the agreement. Mi proposal for change is:

The document says: 
...you need to build a new container that includes the change...

but, it should be say: 
...you need to build a new image that includes the change...

**Pull request merged**
