### PR TITLE
[id] working-with objects and owners and dependences file added

### PR DESCRIPTION
**Pull request by kelvinparmar**
working-with objects and owners and dependences file added

### CODE REVIEW

**Comment by aj11anuj** [comment]
You need to resolve these (Commit ID and EasyCLA) issue, before your PR can be reviewed.

**Comment by Gauravpadam** [comment]
Hey @kelvinparmar! Thanks for the PR. Please do mention the Issue ID you're addressing in the description of the PR. Additionally, You need to complete the CLA before a reviewer can review your PR

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by kelvinparmar** [comment]
@aj11anuj 

i have sign in CLA but it will redirect to my previous pr #39488

how can i get new id for this pr?

**Comment by onlydole** [comment]
Howdy, @kelvinparmar - starting with a new PR on this effort might be best, and ensuring you've signed the EasyCLA. Please don't hesitate to let us know if you have any other questions, though I will close this in the meantime, as the code won't merge with the failing checks. Feel free to open it if you can solve the EasyCLA issues.

/close

**Pull request closed without merging**
