### PR TITLE
Add kinzhi to sig-docs-zh-reviews

### PR DESCRIPTION
**Pull request by kinzhi**
I want to applied to join sig-docs-zh-reviews.

Application related links: https://github.com/kubernetes/org/pull/4007

Thanks!

/cc @tengqm @mengjiao-liu

### CODE REVIEW

**Comment by tengqm** [comment]
please squash the PR into a single commit.

**Comment by kinzhi** [comment]
> please squash the PR into a single commit.

I've squash it

**Comment by ydFu** [comment]
@kinzhi is an active contributor to localization in zh-cn, looking forward to your continued contribution

**Comment by windsonsea** [comment]
Thanks and welcome 👍 
/lgtm

**Pull request merged**
