### PR TITLE
mirror article non-code-contributors.md in website

### LINKED ISSUE #28889: Mirror article “How to choose a SIG as a non-code Kubernetes contributor”
**This is a Blog issue**

**What would you like to be added**
Copy article https://www.k8s.dev/blog/2021/07/09/how-to-choose-a-sig-as-a-non-code-kubernetes-contributor/ into the blog (folder `content/en/blog`)

**Why is this needed**
We mirror most articles from https://www.k8s.dev/blog/ to https://www.k8s.io/blog/

**Comments**
Set the `canonicalUrl:` field in the [front matter](https://gohugo.io/content-management/front-matter/) to: `https://www.k8s.dev/blog/2021/07/09/how-to-choose-a-sig-as-a-non-code-kubernetes-contributor/`

/area blog
/language en
/good-first-issue

See https://github.com/kubernetes/contributor-site/pull/205#issuecomment-877324201
(I'm fine for someone else to do that copying)

### PR DESCRIPTION
**Pull request by Shatakshi0805**
fixes #28889
copied article non-code-kubernetes-contributors.md in website

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Preview: https://deploy-preview-28990--kubernetes-io-main-staging.netlify.app/blog/2021/07/19/how-to-choose-a-sig-as-a-non-code-kubernetes-contributor/

/lgtm
:)

**Comment by Shatakshi0805** [comment]
@sftim could you please tell if I need to make any updates?

**Comment by Shatakshi0805** [comment]
Hi, @sftim could I please get your review on this PR?

**Comment by sftim** [comment]
@Shatakshi0805 we didn't get around to approving this soon enough, and now the next Kubernetes release is imminent.

My apologies to you, and I'm going to close this.
/close

**Pull request closed without merging**
