### PR TITLE
Update portuguese documentation

### PR DESCRIPTION
**Pull request by brunopadz**
## Updating portuguese documentation
- Fix grammar error in README
- Update i18n strings for the Portuguese site.

### CODE REVIEW

**Comment by sftim** [comment]
/uncc
I don't speak Portuguese

**Comment by devlware** [comment]
Thank you for your contribution @brunopadz.

/lgtm
/approve

**Comment by devlware** [comment]
Would mind taking a look too @femrtnz ?

/assign @femrtnz

**Comment by femrtnz** [comment]
Thanks @brunopadz 

/approve

**Comment by femrtnz** [comment]
Hi @kbhawkey, can you approve this one? the translation is fine.

/assign @kbhawkey

**Comment by kbhawkey** [comment]
@brunopadz , @femrtnz , who is the approver for the Portuguese translation team?

**Comment by brunopadz** [comment]
Hi @kbhawkey, I believe @devlware and @femrtnz.

**Comment by devlware** [comment]
Hello @kbhawkey I believe there is some issue with the PR system, me and @femrtnz should be assigned as reviewers and so we could lgtm the PR. But the k8s-ci-robot did not assigned us.

**Comment by kbhawkey** [comment]
hello @devlware . OK.
/approve

**Pull request merged**
