### PR TITLE
[placeholder] blog for Respect PodTopologySpread after rolling upgrades

### PR DESCRIPTION
**Pull request by denkensk**
Signed-off-by: Alex Wang <wangqingcan1990@gmail.com>

### CODE REVIEW

**Comment by katcosgrove** [comment]
Hi from the Comms team! We need to start reviewing blogs and assigning publication dates. Is there anything we can do to help get this ready?

**Comment by fsmunoz** [comment]
Hello @denkensk, I'm  Comms shadow for 1.25. This blog has been scheduled for publication on September 26th. Today is the deadline for review readiness, it would be great if you could add the content and submit if for review.

**Comment by sftim** [comment]
@denkensk it'd be great to get this PR ready for review. Would you like help with that?

**Comment by fsmunoz** [comment]
@sftim , this feature blog was removed from our target list after confirming with @denkensk that it wasn't possible to move forward with the content for review; unless something changed, I would close this PR.

**Comment by sftim** [comment]
I'll close it. @denkensk you are welcome to reuse this work for a future blog article.

/close

**Pull request closed without merging**
