### PR TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics

### PR DESCRIPTION
**Pull request by Philipsty**
This PR adds navigation buttons to return "previous module" or "home" at the end of the interactive tutorials in each of the Kubernetes basics module as detailed in [issue #19835](https://github.com/kubernetes/website/issues/19835)

language/en

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/28292#issuecomment-855165397

**Comment by kbhawkey** [comment]
Rename title to remove issue number
/retitle Improvement for k8s.io/docs/tutorials/kubernetes-basics

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-28292--kubernetes-io-master-staging.netlify.app/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by jimangel** [comment]
@Philipsty thanks for this PR! I love the functionality that it brings, but I have a feeling the user experience is lacking a bit. Mainly the fact that all the buttons are pointing to the right (generally indicating "forward" / "next"):

image

I wonder if we could have the left button point left, home have no arrow indicator, and next point right? If that's too complex, even removing the arrow from "home" would be better IMO.

**Comment by Philipsty** [comment]
Hi @jimangel thanks for the feedback, I will make the changes

**Comment by Philipsty** [comment]
@jimangel I made a change the button arrows as requested, please let me know what you think. Thanks!

image

**Comment by jimangel** [comment]
@Philipsty, your picture looks perfect! However, I believe you need to still push your commits to your local clone / fork so we can test it in Netlify before merging. Let me know if you have any questions about that! Thanks!

**Comment by Philipsty** [comment]
Hi @jimangel 
Thanks for the feedback, I have pushed the changes and updated the PR to be rechecked

**Review by sftim — COMMENTED** [review]
/lgtm
/approve

Thanks!

**Pull request merged**
