### PR TITLE
Update cheatsheet.md

### PR DESCRIPTION
**Pull request by Franziskus79**
Corrected a little typo.

### CODE REVIEW

**Comment by mkorbi** [comment]
/lgtm
/approve

@Franziskus79 thank you for your contribution, to be able to push it finally through the pipe, can you please sign the CLA https://identity.linuxfoundation.org/projects/cncf

**Comment by tengqm** [comment]
/approve cancel

@Franziskus79 Please sign the CLA in order for this to be merged.

**Comment by Franziskus79** [comment]
approved cla

**Pull request merged**
