### PR TITLE
Update Windows pause image

### PR DESCRIPTION
**Pull request by perithompson**
Updating the windows documentation to reflect changes in the version numbering of the windows pause image.

### CODE REVIEW

**Comment by jsturtevant** [comment]
could you also update the pause image section to use 3.6? https://deploy-preview-30327--kubernetes-io-main-staging.netlify.app/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#pause-container

**Comment by ianychoi** [comment]
Removing language/ko label, - I confirm that such small change does not affect on existing Korean transnlation

**Comment by perithompson** [comment]
Thanks @jsturtevant sorry for the delay, this should be all now?

**Comment by jsturtevant** [comment]
@perithompson sorry I think we are still missing a section right above the microsoft line:

```
Kubernetes maintains a multi-architecture image that includes support for Windows.
For Kubernetes v1.22 the recommended pause image is `k8s.gcr.io/pause:3.5`.
For Kubernetes v1.22 the recommended pause image is `k8s.gcr.io/pause:3.5`.
The [source code](https://github.com/kubernetes/kubernetes/tree/master/build/pause)
The [source code](https://github.com/kubernetes/kubernetes/tree/master/build/pause)
is available on GitHub.
is available on GitHub.
```

**Comment by perithompson** [comment]
I was only searching on the mcr.microsoft.com image, I'm hoping I've found all of them now! @jsturtevant

**Comment by sftim** [comment]
@perithompson please revise this to only change English documentation.

Teams managing downstream localizations follow their own workflows to pull in updates and translate them etc.

**Comment by perithompson** [comment]
> and keeping language/ko label since actual Korean doc file is being updated

as the Korean reviewer is ok, should I just remove the Chinese content? as we are only changing an image tag, I thought consistency may be better as I didn't update any actual text?  Happy to remove the other languages though if that is the right approach

**Comment by sftim** [comment]
I recommend removing all the other languages. **Once this merges** it's fine to suggest the same change to those downstream localizations.

**Comment by jimangel** [comment]
This PR looks good to me once you [remove the other localization changes](https://kubernetes.io/docs/contribute/new-content/#languages-per-pr) @perithompson! Thanks!

**Comment by shuaijinchao** [comment]
hi, @perithompson

According to the [Chinese document guidelines](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87), we will refuse to modify some pages of the Chinese document. Part of the modification is for the situation where there are other changes in the English upstream of the corresponding page that need to be synchronized. Once we merge this PR, we will not be able to determine whether there will be other upstream changes that have not been synchronized in the future based on when the file was last changed. Please understand that.

You can follow the Chinese document guide to synchronize all English document changes or remove the Chinese document in the current PR.

/hold

**Comment by sftim** [comment]
@perithompson, would you be willing revise this based on https://github.com/kubernetes/website/pull/30327#issuecomment-986343281 and similar feedback?

If it's easier to do so, you could close this PR and open a new one that only targets English.

**Comment by perithompson** [comment]
@sftim @shuaijinchao @jimangel I have removed the other languages so this will be english only now

**Comment by sftim** [comment]
Taking LGTM from https://github.com/kubernetes/website/pull/30327#issuecomment-986343281 plus own opinions.
/lgtm
/approve

**Pull request merged**
