### PR TITLE
Update Kubernetes API 1.11 ref docs

### PR DESCRIPTION
**Pull request by steveperry-53**
Updated scheduling:PriorityClass from v1alpha1 to v1beta1. Regenerated the Kubernetes API ref docs for 1.11.

Preview of giant ref page: https://deploy-preview-8977--kubernetes-io-vnext-staging.netlify.com/docs/reference/generated/kubernetes-api/v1.11/

Preview of left nav: https://deploy-preview-8977--kubernetes-io-vnext-staging.netlify.com/docs/reference/kubernetes-api/

### CODE REVIEW

**Comment by steveperry-53** [comment]
@Bradamant3

**Comment by mistyhacks** [comment]
The docs look good but need to be added to https://deploy-preview-8977--kubernetes-io-master-staging.netlify.com/docs/reference/ and the TOC. Why is only 1.10 in the TOC now even though the landing page has all the way back to 1.5?

/hold

**Comment by steveperry-53** [comment]
@mistyhacks I updated  https://deploy-preview-8977--kubernetes-io-master-staging.netlify.com/docs/reference/  to include a link to the 1.11 API ref docs. I also trimmed the list to include the current version and the four previous versions.

I the past we talked about what to show in the left nav. We decided to show only the current version of the API ref docs in the left nav. But the feeling was not strong one way or the other. So I'm open to a discussion about putting the current + four past versions in the left nav.

**Comment by steveperry-53** [comment]
Stand by. Still fiddling with the left nav.

**Comment by steveperry-53** [comment]
OK, I'm finished adjusting the left nav. I know this is not an elegant solution, but it works, and it matches what we did in 1.10. It's tricking getting content from /static to appear in the left nav.

**Comment by steveperry-53** [comment]
Stand by again. I lost my changes to the left nav. Working on that now.

**Comment by steveperry-53** [comment]
@mistyhacks OK, this is ready for review and merging when you think it's ready.

**Comment by mistyhacks** [comment]
/lgtm
/approve
/hold cancel

Thank you! 🙏

**Pull request merged**
