### PR TITLE
Official 1.20 Release Docs

### PR DESCRIPTION
**Pull request by annajung**
### 🛑 DO NOT MERGE 🛑 UNTIL KUBERNETES 1.20 IS RELEASED
Target Date: 2020-12-08

### Release deadlines
From [sig-release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.20#timeline)
| Date | Description |
| -- | -- |
| NOV 6 | Open placeholder PRs |
| NOV 23 | PRs ready for review |
| NOV 30 | All PRs reviewed and ready to merge |

### More information
Contact: @annajung @reylejano-rxm @SomtochiAma @eagleusb @kcmartin with any questions

/hold

### CODE REVIEW

**Comment by seokho-son** [comment]
@annajung I have a question ~ !
Korean localization team has our own development branch in k/website (currently, [dev-1.19-ko.6](https://github.com/kubernetes/website/tree/dev-1.19-ko.6)), and we merge the branch into Master branch after we complete localization works for 2~3 weeks)

If necessary, we will change the date for merging dev-1.19-ko.6 into master to avoid any inconvenience to the Docs 1.20 Release.

I aware of the Target Date: 2020-12-08, but I hope to check which date would be nice for finalizing Korean l10n development branch and freezing PR to master branch.

**Comment by annajung** [comment]
Hi @seokho-son I asked other members of Sig Docs chime in here and posted a question in #sig-docs channel. It looks like there is no concern in merging the Korean dev branch into `master` before the release. 

If you want to follow up, here is the thread https://kubernetes.slack.com/archives/C1J0BPD2M/p1606759320421800

thank you!

**Comment by jimangel** [comment]
143 commits, 97 files changed, no conflicts, branch no behind any commits on master, looks very release-y. 🎉 

/lgtm

**Review by irvifa — COMMENTED** [review]
/approve

**Comment by kbhawkey** [comment]
Page previews:
https://deploy-preview-24138--kubernetes-io-vnext-staging.netlify.app/docs/home/
https://deploy-preview-24138--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.20/

**Pull request merged**
