### PR TITLE
[bn] Delete Localization READMEs section in localized README

### PR DESCRIPTION
**Pull request by Okabe-Junya**
### Description

ref. https://github.com/kubernetes/website/pull/47763#issuecomment-2400322169

- Delete Localization READMEs section in localized README
    - Now, these links don't work well

/kind cleanup

### Issue

Closes: #

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
/assign @asem-hamid 
for approval

**Comment by asem-hamid** [comment]
@Okabe-Junya Thanks for these changes. This was one of my first questions when I started contributing: 'Why do I need approval from leads to make changes in bn?' . Thanks for fixing the process.

**Comment by asem-hamid** [comment]
But why are we removing the links instead of updating their path in local files?

**Comment by Okabe-Junya** [comment]
> @Okabe-Junya Thanks for these changes. This was one of my first questions when I started contributing: 'Why do I need approval from leads to make changes in bn?' . Thanks for fixing the process.

Thank you for your comment :)

> But why are we removing the links instead of updating their path in local files?

In #47763, we transitioned the ownership of localized READMEs from TL (website-admins) to each l10n team. 
At that time, we moved the localized READMEs from the root of the tree to `content/xx`.

These paths should be specified based on the English version — all l10n in k/website is based on the English content as the source for translations. 
There is little need to link between other languages (especially in the README) — and currently, it doesn’t work, so removed this section

**Comment by asem-hamid** [comment]
If you allow me i can help on that

**Comment by asem-hamid** [comment]
Code : 

```md 

## Localization READMEs

| Language                      | Language                         |
| ----------------------------- | -------------------------------- |
| [Bengali](../bn/README.md)    | [Japanese](../ja/README.md)      |
| [Chinese](../zh-cn/README.md) | [Korean](../ko/README.md)        |
| [English](../../README.md)    | [Polish](../pl/README.md)        |
| [French](../fr/README.md)     | [Portuguese](../pt-br/README.md) |
| [German](../de/README.md)     | [Russian](../ru/README.md)       |
| [Hindi](../hi/README.md)      | [Spanish](../es/README.md)       |
| [Indonesian](../id/README.md) | [Ukrainian](../uk/README.md)     |
| [Italian](../it/README.md)    | [Vietnamese](../vi/README.md)    |


```


preview ( from my fork ):  https://github.com/asem-hamid/website/blob/link-test/content/bn/README.md#localization-readmes

**Comment by Okabe-Junya** [comment]
OK, I don't absolutely want to delete it, so I will respect your and each l10n team's opinion.

fixed by defd7fe

**Comment by asem-hamid** [comment]
Thank you @Okabe-Junya 

/lgtm

**Review by asem-hamid — APPROVED** [review]

**Comment by asem-hamid** [comment]
> Code :
> 
> ```
> ## Localization READMEs
> 
> | Language                      | Language                         |
> | ----------------------------- | -------------------------------- |
> | [Bengali](../bn/README.md)    | [Japanese](../ja/README.md)      |
> | [Chinese](../zh-cn/README.md) | [Korean](../ko/README.md)        |
> | [English](../../README.md)    | [Polish](../pl/README.md)        |
> | [French](../fr/README.md)     | [Portuguese](../pt-br/README.md) |
> | [German](../de/README.md)     | [Russian](../ru/README.md)       |
> | [Hindi](../hi/README.md)      | [Spanish](../es/README.md)       |
> | [Indonesian](../id/README.md) | [Ukrainian](../uk/README.md)     |
> | [Italian](../it/README.md)    | [Vietnamese](../vi/README.md)    |
> ```
> 
> preview ( from my fork ): https://github.com/asem-hamid/website/blob/link-test/content/bn/README.md#localization-readmes
> 
> I cover every language here



Also those code valid for all localization . Others can use it if they want to adopt

**Pull request merged**
