### PR TITLE
[zh-cn] update device plugin proposal link

### PR DESCRIPTION
**Pull request by Garrybest**
From [community](https://github.com/kubernetes/community/blob/master/contributors/design-proposals) to [design-proposals-archive](https://github.com/kubernetes/design-proposals-archive)

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @Garrybest,

Thanks for contributing k8s website! In this repo, we limited to one language for each PR.

For `content/en/blog/_posts/2017-09-00-....md`, we usually don't update blog posts older than 1 year.

You can try to start with `content/id/docs/` one. And make another PR for `zh-cn` one.

**Comment by Garrybest** [comment]
Hi @Sea-n, thanks for reminding, I have now made a change to zh-cn docs only.

**Pull request merged**
