### PR TITLE
[zh] Url is outdate ...

### PR DESCRIPTION
**Pull request by yuandongx**

### CODE REVIEW

**Comment by tengqm** [comment]
There is another change to sync:

```
./scripts/lsync.sh content/zh/docs/tasks/manage-kubernetes-objects/kustomization.md
diff --git a/content/en/docs/tasks/manage-kubernetes-objects/kustomization.md b/content/en/docs/tasks/manage-kubernetes-objects/kustomization.md
index f5e20a94c..d655d39be 100644
--- a/content/en/docs/tasks/manage-kubernetes-objects/kustomization.md
+++ b/content/en/docs/tasks/manage-kubernetes-objects/kustomization.md
@@ -590,7 +590,7 @@ spec:
       containers:
       - name: my-nginx
         image: nginx
-        command: ["start", "--host", "\$(MY_SERVICE_NAME)"]
+        command: ["start", "--host", "$(MY_SERVICE_NAME)"]
 EOF

```

**Comment by yuandongx** [comment]
> There is another change to sync:
> 
> ```
> ./scripts/lsync.sh content/zh/docs/tasks/manage-kubernetes-objects/kustomization.md
> diff --git a/content/en/docs/tasks/manage-kubernetes-objects/kustomization.md b/content/en/docs/tasks/manage-kubernetes-objects/kustomization.md
> index f5e20a94c..d655d39be 100644
> --- a/content/en/docs/tasks/manage-kubernetes-objects/kustomization.md
> +++ b/content/en/docs/tasks/manage-kubernetes-objects/kustomization.md
> @@ -590,7 +590,7 @@ spec:
>        containers:
>        - name: my-nginx
>          image: nginx
> -        command: ["start", "--host", "\$(MY_SERVICE_NAME)"]
> +        command: ["start", "--host", "$(MY_SERVICE_NAME)"]
>  EOF
> ```
Done.

**Pull request merged**
