### PR TITLE
[ja] updated init-containers.md

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/33328/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Comment by atoato88** [comment]
I agree to hold this PR for the same reason.

**Comment by divya-mohan0209** [comment]
Hello @Sea-n @atoato88 , please could you advise when we'd be able to merge this PR? I understand there have been changes in the English version that have prompted this hold however there has been no activity on the PR for ~ 2 months now. Would we be able to target a date?

**Comment by Sea-n** [comment]
The old link: https://kubernetes.io/ja/docs/tasks/debug-application-cluster/debug-init-containers/
This PR changes to: https://kubernetes.io/ja/docs/tasks/debug/debug-application/debug-init-containers/

The new one is still unavailable, so I think it's better to close PR and let the person who moved and synced file to do this.
/close

**Pull request closed without merging**
