### PR TITLE
updating kubernetes architectural diagram - 2

### PR DESCRIPTION
**Pull request by dkypuros**
This PR updates the "Kubernetes architectural diagram" graphic image, located in Kubernetes Documentation > Concepts > Overview > Kubernetes Components [reference URL](https://kubernetes.io/docs/concepts/overview/components/)

This PR is part of an effort to improve consistency between Kubernetes icons and diagrams on the official Kubernetes Docs website. Several of us have been commenting and collaborating, on the image/png file changed here via a [Google Draw document](https://docs.google.com/drawings/d/11P-yXzso7zapqyqP3ulnIsQ1UE7IbzEi-7kp5jNebLM/edit?usp=sharing). This effort still has an outstanding [SoW for CNCF](https://docs.google.com/document/d/1D94DyIb7CjSYjR7CXs7TgihiMHVrvzGoIUK1ZMdZKgE/edit?usp=sharing), that will work to add even more updates soon.

### CODE REVIEW

**Comment by dkypuros** [comment]
He're is the new PR @sftim

**Comment by sftim** [comment]
Thanks @dkypuros. Will take a look.

**Comment by sftim** [comment]
There's a preview: https://deploy-preview-20767--kubernetes-io-master-staging.netlify.app/docs/concepts/overview/components/

My take on this, now I see it in context:
- the existing image is higher resolution; the new one is “fuzzy” (I'm viewing on a 2160p monitor)
- it would be nice to have SVG rather than PNG if feasible
- moving from text to icons, a legend might be useful(?)
- it might be OK to use the original etcd logo rather than the Kubernetes-specific version
- I would draw the cloud as just a cloud shape, rather than a cloud in a circle labelled “Cloud”

More importantly, the existing diagram highlighted relationships between the node and its components (kubelet, kube-proxy) that this new diagram does not.
@dkypuros how about I try to draw a revised diagram that uses these graphic elements and also preserves that relationship detail?

**Comment by dkypuros** [comment]
> There's a preview: https://deploy-preview-20767--kubernetes-io-master-staging.netlify.app/docs/concepts/overview/components/
> 
> My take on this, now I see it in context:
> 
> * the existing image is higher resolution; the new one is “fuzzy” (I'm viewing on a 2160p monitor)
> * it would be nice to have SVG rather than PNG if feasible
> * moving from text to icons, a legend might be useful(?)
> * it might be OK to use the original etcd logo rather than the Kubernetes-specific version
> * I would draw the cloud as just a cloud shape, rather than a cloud in a circle labelled “Cloud”
> 
> More importantly, the existing diagram highlighted relationships between the node and its components (kubelet, kube-proxy) that this new diagram does not.
> @dkypuros how about I try to draw a revised diagram that uses these graphic elements and also preserves that relationship detail?

I'll take another look at the original diagram.

**Comment by kbhawkey** [comment]
How about holding
/hold

**Comment by sftim** [comment]
An aside: https://diagrams.mingrammer.com/ looks like it could be useful as well.

**Comment by dkypuros** [comment]
> There's a preview: https://deploy-preview-20767--kubernetes-io-master-staging.netlify.app/docs/concepts/overview/components/
> 
> My take on this, now I see it in context:
> 
> 1 the existing image is higher resolution; the new one is “fuzzy” (I'm viewing on a 2160p monitor)
> 2 it would be nice to have SVG rather than PNG if feasible
> 3 moving from text to icons, a legend might be useful(?)
> 4 it might be OK to use the original etcd logo rather than the Kubernetes-specific version
> 5 I would draw the cloud as just a cloud shape, rather than a cloud in a circle labelled “Cloud”
> 
> More importantly, the existing diagram highlighted relationships between the node and its components (kubelet, kube-proxy) that this new diagram does not.
> @dkypuros how about I try to draw a revised diagram that uses these graphic elements and also preserves that relationship detail?

Apologize for the delay on this comment (I've been a bit delayed by other pressing projects :-S ). I did want to check-in @sftim and see if you were able to "try to draw a revised diagram"? I've updated my diagram per comments 4 and 5, but I would like to see your diagram before I tackle the  other comments.

Does that make sense?

**Comment by sftim** [comment]
I do plan to draw / sketch a revised diagram for comparison, sorry about the holdup.

**Comment by dkypuros** [comment]
> I do plan to draw / sketch a revised diagram for comparison, sorry about the holdup.

Sounds good. Here is a draft of what I have so far...

[componens-of-kubernetes.svg](https://drive.google.com/file/d/16aCkYa54gOiYHKsoVd05ysd3TV7vWpzZ/view?usp=sharing)

[components-of-kubernetes.png](https://drive.google.com/file/d/1aCxo2CbrI_Gq0aIOlvLvYKYsi8FJBhRb/view?usp=sharing)

**Comment by sftim** [comment]
@dkypuros I just realized that I don't have access to the SVG image in that Google Drive. I've requested access.

**Comment by dkypuros** [comment]
> @dkypuros I just realized that I don't have access to the SVG image in that Google Drive. I've requested access.

Your added. No worries!

**Comment by sftim** [comment]
Here's what I'm thinking at the moment:
Components of Kubernetes

@dkypuros what do you think? I've done this in Inkscape rather than Google Apps because I'm more comfortable working in that tool. I can try to port it back into the Google drawing though, I hope time allows.

**Comment by dkypuros** [comment]
I really like the improvements. The arrows and the legend are really helpful. I’ll port changes back into google draw this week.

**Comment by sftim** [comment]
I'd like to make the icons for the cloud-controller-manager and the kube-controller-manager more different from the icon for the API server.

Maybe have the inner symbol be a loop for the k-c-m and use a cloud for the c-c-m. Does that work?

**Comment by sftim** [comment]
Also, to be clear @dkypuros, I have a `.svg` file from Inkscape. It's a raster file here to keep GitHub happy.

**Comment by dkypuros** [comment]
Do you have a link for - https://diagrams.mingrammer.com ? Maybe I'll work on that platform...

**Comment by sftim** [comment]
> Do you have a link for - https://diagrams.mingrammer.com ? Maybe I'll work on that platform...

Implementing the Kubernetes icons for that tool sounds like a nice piece of work, but a _big_ nice piece of work.

**Comment by sftim** [comment]
Oh! https://diagrams.mingrammer.com/docs/getting-started/examples#exposed-pod-with-3-replicas-on-kubernetes already has icons.

**Comment by kbhawkey** [comment]
Hi @dkypuros .
Just checking if you are actively working on this pull request?

**Comment by dkypuros** [comment]
@kbhawkey Well, not very actively but yes. Work has been nuts with COVID, so I"m trying to keep up. I could use some technical help on syncing my fork. I started looking at docs for PR, and couldn't find much on this topic.

**Comment by sftim** [comment]
I might open my own PR that follows on from this work. Hope that's OK(?)

**Comment by dkypuros** [comment]
@sftim I would appreciate it greatly. I think I'll be able to contribute more after things cool off at work.

Thanks Tim.

**Comment by kbhawkey** [comment]
> 
> 
> @kbhawkey Well, not very actively but yes. Work has been nuts with COVID, so I"m trying to keep up. I could use some technical help on syncing my fork. I started looking at docs for PR, and couldn't find much on this topic.

Hi @dkypuros . Does this information help, https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by dkypuros** [comment]
@kbhawkey That helps.

@sftim Tim, can you add this "updating kubernetes architectural diagram - 2 #20767" PR to your PR, so we can keep track of the conversation please?

**Comment by dkypuros** [comment]
@sftim did you start another PR yet? I was just curious :-)

**Comment by sftim** [comment]
Later today I hope.

**Comment by sftim** [comment]
/close

Superseded by #23138

**Comment by sftim** [comment]
The diagram at https://kubernetes.io/docs/concepts/overview/components/ came about because of really useful work on this and other PRs.

Thank you @dkypuros !

**Comment by dkypuros** [comment]
> The diagram at https://kubernetes.io/docs/concepts/overview/components/ came about because of really useful work on this and other PRs.
> 
> Thank you @dkypuros !

@sftim I remember when you first mentioned needing better diagrams during our SIG-Docs meeting back in November 2019! Many of us agreed, and I've learned so much working on this PR with you. I appreciate your support on the final merge of this PR and #20767

**Pull request closed without merging**
