### PR TITLE
Propose Jailton, Yago and Ricardo as pt approvers

### PR DESCRIPTION
**Pull request by rikatz**
due to the effort of the Brazilian community to improve the pt documentation, per issue #26622 I would like to propose myself and Yago, which are long time org members to help in the review and approval of those docs and also to coordinate with the contributors this efforts. 

Thanks

### CODE REVIEW

**Comment by sftim** [comment]
This sounds fine by me.

I believe the official process is to get SIG Docs agreement and PR a change to https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml - and then mirror that change here.

(SIG Docs chairs - is that right?)

**Comment by jailton** [comment]
Following the official process of SIG Docs, PR kubernetes/org#2531 have added us as sig-docs-pt-owners, sig-docs-pt-reviews, and website-maintainers (https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml).

**Comment by yagonobre** [comment]
@sftim now that we have the change to `teams.yaml ` merged, can we have it merged as well? Thanks!

**Review by onlydole — APPROVED** [review]
Thank you, @rikatz and @sftim! This looks good to me

**Pull request merged**
