### PR TITLE
Update rollout deployment

### PR DESCRIPTION
**Pull request by Mac24**
modify nginxi:1.16.1,Context correspondence

### CODE REVIEW

**Comment by Mac24** [comment]
language/zh

**Review by tanjunchen — COMMENTED** [review]
/lgtm

**Comment by tengqm** [comment]
/hold
pls submit full PRs (https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87).
To see what are other changes that need syncs, run:

```
./scripts/lsync.sh content/zh/docs/concepts/workloads/controllers/deployment.md
```

**Pull request closed without merging**
