### PR TITLE
Remove Static Password File section

### PR DESCRIPTION
**Pull request by shu-mutou**
Due to removed on v1.19, remove Static Password File section from docs/reference/access-authn-authz/authentication.md

### CODE REVIEW

**Comment by sftim** [comment]
@kubernetes/sig-auth-pr-reviews please verify that this looks how you'd like

**Comment by tengqm** [comment]
Hi, @shu-mutou, small world...

**Comment by shu-mutou** [comment]
@sftim This section was removed from English version, but not from Japanese version. So it's issue for Japanese docs team. 😉

**Comment by shu-mutou** [comment]
We need to backport this to v1.19 or later. Please let me confirm which branches should I send this PR again. We don't have `ja` branches for v1.19 or later, so is it enough sending PR to release-1.19 and dev-1.19 ~ 1.20?

**Comment by sftim** [comment]
@kubernetes/sig-docs-ja-reviews is this OK to land in _master_ first?

**Comment by shu-mutou** [comment]
After this PR merged, I'll backport this PR to `release-1.19` branch.

**Comment by kakts** [comment]
Thank you so much!
/lgtm

**Comment by kakts** [comment]
@sftim 
Sorry for late reply.
It's ok to land in master first.

**Pull request merged**
