### PR TITLE
Fix hudo anchor in readme (id)

### PR DESCRIPTION
**Pull request by Arhell**
More fixes)

### CODE REVIEW

**Comment by girikuncoro** [comment]
thanks a lot @Arhell for fixing this! 🎉 

/lgtm
/approve

**Comment by girikuncoro** [comment]
@Arhell is there a script or tooling you used for detecting this broken hugo anchor? if you don't mind can you share? so we can put it our CI for detecting this kind of error

**Comment by Arhell** [comment]
@girikuncoro 
Hi, unfortunately not, manually

**Comment by Arhell** [comment]
@kubernetes/sig-docs-id-reviews

**Comment by Arhell** [comment]
[issue](https://github.com/kubernetes/website/issues/19511)

**Pull request merged**
