### PR TITLE
Update pod-lifecycle.md

### PR DESCRIPTION
**Pull request by ZhangJinbao520**
Updates the ordering of the sample ordered list of pod terminations.（更新Pod终止的举例有序列表的排序。）
Addresses an issue where the pod termination example is not aligned with the parent.（解决Pod终止的举例说明与父级未对齐问题。）

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Sea-n** [comment]
Hey @ZhangJinbao520,

Since you didn't sign the CLA agreement, we cannot review this PR and move forward.

Please refer to [the tutorial here](https://git.k8s.io/community/CLA.md).

**Comment by Sea-n** [comment]
Hi @ZhangJinbao520,

You have to sign the CLA so that we can review this PR and move forward.
Just click on the red NOT COVERED button in the first comment.
哈囉，你需要先簽署 CLA 貢獻者授權協議，我們才能 Review 並合併這個 PR
請點擊上方第一個留言的紅色 NOT COVERED 按鈕，並依網站指示操作

After signing the CLA, you may use this command to refresh the status:
/easycla

If you have any problem, please take a look at [the CLA tutorial](https://git.k8s.io/community/CLA.md).
如果用起來還有問題，可以先看看 [這篇教學](https://git.k8s.io/community/CLA.md) 的操作截圖

**Comment by mengjiao-liu** [comment]
>Updates the ordering of the sample ordered list of pod terminations.（更新Pod终止的举例有序列表的排序。）

I don't see what's wrong with the ordering.
link: https://kubernetes.io/zh-cn/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination

>Addresses an issue where the pod termination example is not aligned with the parent.（解决Pod终止的举例说明与父级未对齐问题。）

Do you mean this place? 
image

But your PR doesn't fix this.
preview page:
https://deploy-preview-35211--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination

**Comment by ZhangJinbao520** [comment]
> > Addresses an issue where the pod termination example is not aligned with the parent.（解决Pod终止的举例说明与父级未对齐问题。）
> 
> Do you mean this place? image
> 
> But your PR doesn't fix this. preview page: https://deploy-preview-35211--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination

yes.
And the orederd list.

**Comment by mengjiao-liu** [comment]
Yes, you have only fixed one of the two issues. Please modify  another.
- [x] Updates the ordering of the sample ordered list of pod terminations.（更新Pod终止的举例有序列表的排序。）

- [ ] Addresses an issue where the pod termination example is not aligned with the parent.（解决Pod终止的举例说明与父级未对齐问题。）
your PR doesn't fix this.

**Comment by Sea-n** [comment]
Hey @ZhangJinbao520,

It's been a while since the last update, would you like to address issues in the [previous comments](https://github.com/kubernetes/website/pull/35211#issuecomment-1206149927) so that we can move forward?

**Comment by Sea-n** [comment]
Hey @ZhangJinbao520,

前面 @mengjiao-liu 這 PR 雖然解決了一個問題，但仍然有部分待修正

這個 PR 也放一陣子了，您有時間來處理了嗎

**Comment by Sea-n** [comment]
Hey @ZhangJinbao520,

Thanks for purposing this PR. But since you didn't respond for a while, we have to close this PR now.
/close

Feel free to `/reopen` when you are ready to move forward.
(Note that please don't push anything while PR closed, or you won't be able to reopen it.)

**Pull request closed without merging**
