### PR TITLE
Localize docs/home in Hindi

### PR DESCRIPTION
**Pull request by mittalyashu**
This PR localizes the content of `docs/home` directory in Hindi.

Closes https://github.com/kubernetes/website/issues/13914

### CODE REVIEW

**Comment by mittalyashu** [comment]
Can you suggest a better word for `संस्करण` it means version?

/cc @Rajakavitha1

**Comment by mittalyashu** [comment]
I do also need to localize this file too https://github.com/kubernetes/website/blob/master/content/en/docs/home/_index.md?

@Rajakavitha1

**Comment by mittalyashu** [comment]
This PR is ready for review.

**Comment by kbhawkey** [comment]
Hello @Rajakavitha1!
Would you have time to review this PR?
Thanks

**Comment by jimangel** [comment]
It appears there is still some needed translated content (as marked in the localization guides: https://kubernetes.io/docs/contribute/localization/#translating-content)

Feel free to message me if you have any questions. However, I cannot effectively review the translated content.

/unassign

**Comment by kbhawkey** [comment]
Hello @mittalyashu ,
Since this pull request has been open for a long time, I plan to close it.
You can reopen this pull request at any time.
/close

**Pull request closed without merging**
