### PR TITLE
Cherry pick PR - Fix site build (#16531) 

### PR DESCRIPTION
**Pull request by aimeeu**
Cherry-picking PR #16531  from master to 1.16 so we can move to Hugo 0.57.2. See also PRs #16104 and #16151. 

The `*.profile` file referenced do not need to be provided in a separate
file. Making them separate files is preventing hugo from correctly
building the site.

PRs in this "cherry pick" group: #16645, #16646, #16647, #16648, #16650

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @aimeeu. Is there a plan/need to port this fix to the last five versions?

Page preview:
https://deploy-preview-16645--k8s-v1-16.netlify.com/docs/tutorials/clusters/apparmor/

/lgtm

**Comment by aimeeu** [comment]
@kbhawkey yep - all the PRs have now been submitted: #16645, #16646, #16647, #16648, #16650.  Updating other PRs now with this info.

**Comment by zacharysarah** [comment]
@aimeeu @kbhawkey 👋 This PR isn't technically necessary: 

- This change is already in `master`
- The current version is 1.16, which points to `master`
- The docs release lead will merge `master` to `release-1.16` during the 1.17 cycle

So we can safely close this one.

/close

**Pull request closed without merging**
