### PR TITLE
Rename "schedule-eviction" to "schedule-and-eviction"

### PR DESCRIPTION
**Pull request by Hsiny**
Rename `scheduling-eviction` to `scheduling-and-eviction` , mentioned in https://github.com/kubernetes/website/pull/19385

* id,ja,pt: move `scheduling` to `scheduling-and-eviction`
* en,ko,zh: move `scheduling-eviction` to `scheduling-and-eviction`

### CODE REVIEW

**Comment by alculquicondor** [comment]
/lgtm
but I'm leaving some thoughts in #19081

**Comment by Hsiny** [comment]
I just resolved a conflict using auto-merge

**Comment by Hsiny** [comment]
> @Hsiny would it be possible to separate this PR into multiple PRs (one per language)? Each language has their own branching strategy and merging this as a single PR could cause conflicts.
> 
> Thanks!

there will be almost 9 PRs, is it ok?



> @Hisny, we've just recently [stopped using capture shortcodes](https://github.com/kubernetes/website/pull/21359).
> 
> Would you be willing to rebase the changes in this PR against _master_?

I rebase the changes against _master_ and  fix conflicts

**Pull request closed without merging**
