### PR TITLE
Adding a back button on last module

### PR DESCRIPTION
**Pull request by jimangel**
Closes: https://github.com/kubernetes/website/issues/10073

Example: https://deploy-preview-10089--kubernetes-io-master-staging.netlify.com/docs/tutorials/kubernetes-basics/update/update-interactive/

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Thanks for the update @jimangel ! 
/lgtm

**Comment by BenHall** [comment]
thanks! lgtm

**Pull request merged**
