### PR TITLE
Issue with https://k8s.io/blog/

### LINKED ISSUE #15540: Issue with https://k8s.io/blog/
**This is a Feature Request**

The Blog links are not well centered

**What would you like to be added**
adjust design and center links in the Blog 

**Why is this needed**
better UI
k8s-old-blog

### PR DESCRIPTION
**Pull request by medmedchiheb**
adjust and center Blog links

k8s-new-blog

Fixes #15540

### CODE REVIEW

**Comment by poothia** [comment]
lgtm

**Comment by medmedchiheb** [comment]
@zacharysarah  needs approve :)

**Pull request merged**
