### PR TITLE
Fix typo in blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs/

### LINKED ISSUE #44965: A single typo in blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs
**This is a Bug Report**

**Problem:**

As being pointed in https://github.com/kubernetes/website/pull/42335#discussion_r1470970765 , `spec.unhealthyPodEvictionPolicy` should be `.spec.unhealthyPodEvictionPolicy`

**Proposed Solution:**

**Page to Update:**

https://kubernetes.io/blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs/

### PR DESCRIPTION
**Pull request by mikutas**
close #44965

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
nice catch!!

This is not review, but LGTM

**Review by Gauravpadam — COMMENTED** [review]
Thanks @mikutas

/lgtm
/approve

**Comment by Gauravpadam** [comment]
/remove lgtm

as per https://github.com/kubernetes/website/issues/44965#issuecomment-1919299646

**Comment by Gauravpadam** [comment]
/remove-lgtm

as per https://github.com/kubernetes/website/issues/44965#issuecomment-1919299646

**Pull request closed without merging**
