### PR TITLE
Improve readability in persistent volume introduction

### LINKED ISSUE #17174: Issue with https://kubernetes.io/docs/concepts/storage/persistent-volumes/
**This is a Bug Report**

**Problem:**

The page at 
https://kubernetes.io/docs/concepts/storage/persistent-volumes/ currently starts off saying:

  Managing storage is a distinct problem from managing compute.

("Compute" is a verb, and is not really a noun, so that introductory sentence is a bit jarring.)

**Proposed Solution:**

It should say something like:

  Managing storage is a distinct problem from managing computation.

or:

  Managing storage is a distinct problem from managing computing resources.

 **Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

### PR DESCRIPTION
**Pull request by christophercarney**
Fixes #17174 

Modify the wording around "compute" to adjust readability of the compute jargon term and make it clear it is a noun as opposed to a verb.

### CODE REVIEW

**Comment by sftim** [comment]
“compute” is jargon, meaning “the abstract concept of performing computation”. That's analogous to how the existing text has “storage” rather than “storage devices”.

Although “compute” is jargon, replacing it with “computers” doesn't feel right either: it changes the meaning. For examples of the jargon in common use, see https://aws.amazon.com/lambda/ and [https://www.fastly.com/products/edge-compute](https://www.fastly.com/products/edge-compute).

@christophercarney can you suggest an alternative rewording that leaves the meaning and nuance intact?

**Comment by christophercarney** [comment]
@sftim I see your point, but I believe that probably stems that "storage" is much more colloquial in technical jargon than "compute". Compute here reads awkwardly because used without some kind of qualifier it reads foremost as a verb. In your examples, the real jargon phrase would probably be "edge compute" and "compute time" rather than just "compute" alone. The qualifiers of time and edge add context to the word compute, giving it meaning. 

In light of that, I'd then suggest adding some kind of qualifier to compute to make it clear that it is jargon rather than the verb. Brainstorming a couple of possibilities below:
```
compute resources
compute power (computing?)
compute problems
compute concepts
compute issues
```

**Comment by bradtopol** [comment]
So it is very common in cloud computing for compute to be used as a noun.  See
https://www.techopedia.com/definition/6580/compute

That being said, if you prefer changing compute to either "compute nodes"  or "compute instances" 
I would find both of those options as acceptable changes that improve readability.  Computers is definitely not the proper change here.  
 
/cc @zacharysarah @sftim 
/assign

**Comment by christophercarney** [comment]
I agree computer is wrong. I also agree compute is common as a noun in cloud computing but in this context the sentence reads a little strangely, especially to people who may be unfamiliar with cloud computing concepts. So I think adding the modifier to compute makes it increases overall readability.

**Pull request merged**
