### PR TITLE
Remove Roboto

### PR DESCRIPTION
**Pull request by celestehorgan**
Closes https://github.com/kubernetes/website/issues/22095. 
Umbrella issue: https://github.com/kubernetes/website/issues/22024

This PR investigates removing the Roboto font face, as we don't really need it (and it introduces font inconsistencies across the site.):

* Docsy's theme uses Open Sans and provides a full extended-latin character set
* For other languages like Japanese and Arabic we fall back on system fonts rather than using Roboto anyways

This should help reduce a bit of the bloat and introduce more visual consistency.

This PR will be initially presented for review on a commit-by-commit basis, so that reviewers can see what each incremental change actually does. 

Notes: 
1. ~One of the uses of Roboto in our current site is in the Katacoda examples, where it's called directly in-line. When I get to these changes, I'll likely open a separate PR for each language to avoid confusion.~ I ended up _not_ removing these from Katacoda. Katacoda apparently has its own version of Bootstrap, nestled in with some customization that calls Roboto from... elsewhere? This did not seem like the time or place to investigate this issue.

2. For the most part this PR will focus on removing specific mentions of Roboto in CSS/HTML files. ~I will open a separate PR to remove the font itself after it isn't referenced anywhere.~ I ended up removing the font files in this PR due to the results of #23656.  

3. This PR is multi-language, but the changes in `fr`, `ja`, and `zh` are one line each. 

4. This PR spawned a subsequent issue, https://github.com/kubernetes/website/issues/23660, to normalize the look-and-feel of case studies (font-wise) and generally improve maintainability of those pages.

### CODE REVIEW

**Comment by celestehorgan** [comment]
Commit https://github.com/kubernetes/website/pull/23656/commits/0da853bb11368a20fb782fa94a480d705a5875ec removes Roboto from `partner-styles.css`, where it was used in a `button` class. Because I was in the neighborhood, I also applied `border: 0px` in the `_base.scss` `button` class, which should fix the awkward gray border we currently have on buttons that's been bothering me across the site.

This does the following:

| **BEFORE** | **AFTER** |
| --- | --- |
| Screen Shot 2020-09-02 at 10 05 54 AM | Screen Shot 2020-09-02 at 10 18 14 AM |

**Comment by celestehorgan** [comment]
Commit https://github.com/kubernetes/website/pull/23656/commits/08154800362054c1317f226e7bf9622199553f16 removes `blog.css` entirely (as well as its mention of Roboto!!) because we don't use it anymore. 

This changes nothing.

Always be deleting!

**Comment by celestehorgan** [comment]
Commit https://github.com/kubernetes/website/pull/23656/commits/c186b6d1d7f797c6d0dcd1a7a60dde91ca34872c removes Roboto from all the case study pages, including the Case Study `list.html` (index) page.

Rather than screencap each individual change, it's probably best to just double check the [https://kubernetes.io/case-studies/](live site) versus the [deploy preview](https://deploy-preview-23656--kubernetes-io-master-staging.netlify.app/case-studies) for _all_ pages.

I recommend whomever reviews this check all case study pages for consistency.

---

As a side note, I've opened https://github.com/kubernetes/website/issues/23660 to capture the work that remains in cleaning up the case study CSS and HTML. As it is it's a bit of a nightmare to maintain.

**Comment by celestehorgan** [comment]
Commit https://github.com/kubernetes/website/pull/23656/commits/fcb5d5adef3e88ee47ca46da3bb11ad733fd5cd5 removes Roboto from `/training` (where it appeared on button labels only) and `/community`, where it appeared everywhere.

Once again, rather than screencapping individual differences, I'd take a look at [the live site's /community](https://kubernetes.io/community/) vs. the [deploy preview](https://deploy-preview-23656--kubernetes-io-master-staging.netlify.app/community).

**Comment by celestehorgan** [comment]
https://github.com/kubernetes/website/pull/23656/commits/6ec2f71e58d36d88e8f75b298074dc96780cbd40 removes `base_fonts.css`. Theoretically, this should affect nothing at this point!

**Comment by celestehorgan** [comment]
https://github.com/kubernetes/website/pull/23656/commits/ba3f527b73171f05b4d051bf60ea2523d15e933c does what it says on the tin ;)

**Comment by zacharysarah** [comment]
Thanks, @celestehorgan! ✨ 

/lgtm
/approve

**Pull request merged**
