### PR TITLE
update import doc script, python3

### PR DESCRIPTION
**Pull request by kbhawkey**
- modified update-imported-docs script for python3
- may need further tweaks, testing

### CODE REVIEW

**Comment by kbhawkey** [comment]
See #16777

**Comment by aimeeu** [comment]
This kind of duplicates the WIP PR #16681 that I opened a while ago.

**Comment by kbhawkey** [comment]
@aimeeu , I was under the impression from reading the proposed changes to the docs about the import script that you were unable to successfully run the script with python3. I created this PR to evaluate if that is possible. I will close this PR and you can continue to work on your own PR.

**Comment by aimeeu** [comment]
Sorry @kbhawkey - I guess I wasn't clear that the problem was the Go version being 1.13 instead of 1.12

**Pull request closed without merging**
