### PR TITLE
Add figure shortcode example to smoke tests

### PR DESCRIPTION
**Pull request by mistyhacks**
Whoops, sorry about Github making this branch exist on the main repo and not my fork! 😱 

/assign @chenopis

### CODE REVIEW

**Comment by zacharysarah** [comment]
@mistyhacks Should there be a broken image link?

screen shot 2018-05-31 at 3 52 59 pm

/lgtm
/approve
/hold

**Comment by mistyhacks** [comment]
The image is broken because it is in `/static/` and I don't know how to fix that. I think @chenopis pinged @bep about this but i don't think we got any answers about what to do about those files in that directory. The problem is that the `/content/en/docs/` -> `/docs/` transform means that `/static/` is inaccessible.

So the broken image isn't the fault of this PR, so I think this PR is OK to go in with it.

**Comment by zacharysarah** [comment]
@mistyhacks OK, I'll lift the hold and we can sort out image URLs separately.

/hold

**Comment by zacharysarah** [comment]
Good to know that k8s-bot doesn't parse edited comments! 

/hold cancel

**Pull request merged**
