### PR TITLE
Relocation of a file in ZH-CN directory

### PR DESCRIPTION
**Pull request by NitishKumar06**
Fix: #35386

The following file's path has been changed as required.

### CODE REVIEW

**Comment by seokho-son** [comment]
/hold

The issue #35386 is not related with this PR (contents and title).
Please feel free to unhold when this mistake is resolved.

**Comment by NitishKumar06** [comment]
@seokho-son But the following issue demanded to change the path of the file. Isn't it?

**Comment by seokho-son** [comment]
Hi @NitishKumar06 

The issue is related with `zh-cn` language but you changed `ko` language contents. (please read contents in the issue carefully)

Also, please take a look on https://github.com/kubernetes/website/issues/35386#issuecomment-1195023663

@windsonsea wants to resolve #35386. 
Since windsonsea handles the language/zh-cn, Maybe @windsonsea is the most suitable contributor to resolve the issue. So, I hope to assign windsonsea to the issue. 
But I am not maintaining zh-cn language, I hope @NitishKumar06 interact with @windsonsea to resolve the assignment.

**Pull request closed without merging**
