### PR TITLE
Update 1.16 config.toml for release 1.20

### PR DESCRIPTION
**Pull request by annajung**
Updated config.toml for release v1.20
Versions were updated based on [latest patch releases](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md)

/hold until 1.20 release day

### CODE REVIEW

**Review by savitharaghunathan — COMMENTED** [review]
lgtm 

will leave the actual `/lgtm` for sig-docs leads

**Review by sftim — COMMENTED** [review]
/lgtm

**Review by sftim — COMMENTED** [review]
/approve

**Review by savitharaghunathan — COMMENTED** [review]
/approve

**Pull request merged**
