### PR TITLE
Add missing --allow-privilege flag

### PR DESCRIPTION
**Pull request by ToroNZ**
--allow-privilege seems to be missing from kubelet v1.10 documentation

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.10 Features: set Milestone to 1.10 and Base Branch to release-1.10
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by heckj** [comment]
thank you @ToroNZ, but since these are generated docs, we need to make any changes to the upstream content. Please make an updated PR to the source content, and we'll get it included in an update - if you want to be more proactive, you can poke us when when it's merged and we'll regenerate the docs and make an update for the current release.

**Comment by ToroNZ** [comment]
@tengqm The flag should be included in documentation because it still works. Thanks anyway.

@heckj May I suggest the team to correct the instructions then?
image

https://kubernetes.io/docs/home/contribute/create-pull-request/

**Comment by heckj** [comment]
excellent point @ToroNZ - thank you, I'll take that and make it happen

**Comment by tengqm** [comment]
@ToroNZ We are working on that in another thread, FYI. #7944

**Pull request closed without merging**
