### PR TITLE
[zh] Create examples/mongodb

### PR DESCRIPTION
**Pull request by my-git9**
[zh] Create examples/mongodb

### CODE REVIEW

**Comment by tengqm** [comment]
Please check whether these files are referenced anywhere in Chinese pages.

**Comment by my-git9** [comment]
> Please check whether these files are referenced anywhere in Chinese pages.
only a command:
```shell
kubectl apply -f https://k8s.io/examples/application/mongodb/mongo-deployment.yaml
```

**Comment by tengqm** [comment]
The service file is not referenced?

**Comment by my-git9** [comment]
> The service file is not referenced?

Not yet

**Comment by tengqm** [comment]
It is referenced in `content/zh/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md`.
/lgtm
/approve

**Pull request merged**
