### PR TITLE
Update uk translation in README-uk.md

### PR DESCRIPTION
**Pull request by zhanw15**
The site cannot build without a local copy of the theme. Use `git submodule update --init --recursive --depth 1` update the theme.
use `make serve` to build and test website locally.

### CODE REVIEW

**Comment by sftim** [comment]
@kubernetes/sig-docs-uk-reviews please take a look at this one

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by MaxymVlasov** [comment]
Thank you!
/approve

**Comment by MaxymVlasov** [comment]
/assign @sftim 
please merge, it's OK

**Comment by sftim** [comment]
Echoing https://github.com/kubernetes/website/pull/24840#issuecomment-759688033
/approve

**Pull request merged**
