### PR TITLE
Fix the etcd client certs

### PR DESCRIPTION
**Pull request by h4ghhh**
Using ‘server’ key is easily misunderstood.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Hello @h4ghhh 
I recommend you to include only the English version changes in this PR,
and the Chinese version changes in another PR. 😊

---

https://kubernetes.io/docs/contribute/new-content/#languages-per-pr
> # Languages per PR
> Limit pull requests to one language per PR. If you need to make an identical change to the same code sample in multiple languages, open a separate PR for each language.

**Comment by h4ghhh** [comment]
> Hello @h4ghhh I recommend you to include only the English version changes in this PR, and the Chinese version changes in another PR. blush
> 
> https://kubernetes.io/docs/contribute/new-content/#languages-per-pr
> 
> > # Languages per PR
> > Limit pull requests to one language per PR. If you need to make an identical change to the same code sample in multiple languages, open a separate PR for each language.

@jihoon-seo 
Ok.
Another pr for Chinese is https://github.com/kubernetes/website/pull/30665.  Could you review them for me?
Thanks.

**Comment by jihoon-seo** [comment]
Hmm, I wish someone else do a technical review on this PR 😊.
/remove-language zh

**Comment by jimangel** [comment]
@h4ghhh in many cases those certificates are automatically generated and are named `server.*`. I don't believe this change is technically accurate, but feel free to reopen with more supporting evidence! Thanks!

/close

**Comment by h4ghhh** [comment]
> @h4ghhh in many cases those certificates are automatically generated and are named `server.*`. I don't believe this change is technically accurate, but feel free to reopen with more supporting evidence! Thanks!
> 
> /close

Ok, thanks.

**Pull request closed without merging**
