### PR TITLE
Update documentation to include links

### PR DESCRIPTION
**Pull request by MarcBruins**
Update the docs to include links to `kubelet` and `kube-proxy`

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Thanks for your pull request @MarcBruins . Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

memo Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

**Comment by MarcBruins** [comment]
Signed

**Comment by zparnold** [comment]
Hey there! @MarcBruins, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by zparnold** [comment]
Hey there! @MarcBruins, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Rajakavitha1** [comment]
Hi @MarcBruins !!!! I am closing this PR for now.
Please feel free to reopen it after you sign the CLA.
/close

**Pull request closed without merging**
