### PR TITLE
modify `kubeadm init` link

### PR DESCRIPTION
**Pull request by Mac24**
`kubeadm init`, the previous link cannot be opened, 404, I revised the link again

### CODE REVIEW

**Comment by howieyuen** [comment]
please follow the instruction and sign the CLA first~
Welcome to join us 👍

**Comment by Mac24** [comment]
> please follow the instruction and sign the CLA first~
> Welcome to join us 👍

hi, I signed it

**Comment by rayw000** [comment]
> @rayw000: changing LGTM is restricted to collaborators
> 
> In response to [this](https://github.com/kubernetes/website/pull/25615#issuecomment-745012105):
> 
> > /lgtm
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

OK, just make a try 😃

**Pull request merged**
