### PR TITLE
[ja] Remove content/ja/docs/reference/kubectl/overview.md

### PR DESCRIPTION
**Pull request by s-kawamura-w664**
content/ja/docs/reference/kubectl/overview.md should be removed from ja because it had been removed from en.
In en, the contents of overview.md was moved in _index.md and overview.md removed in #29847.
It is needed the same fix in ja.

This PR is included the following.
1. The contents of content/ja/docs/reference/kubenet/overview.md was moved to content/ja/docs/reference/kubenet/_index.md.
2. The _index.md was fixed the top's comment(line 12-20) and "What's next" at the bottom.
3. The link to docs/reference/kubectl/overview/ was changed to /docs/reference/kubectl/ in some files.
4. The content/ja/docs/reference/kubelet/overview.md was removed.

Related: #29847
Fixes: #39848

### CODE REVIEW

**Comment by s-kawamura-w664** [comment]
I have realized something when I was creating this PR.
I think it needs to be fixed in another PR.

- The content/ja/docs/reference/kubectl/_index.md need to be updated to the latest like en.
- The content/ja/docs/tasks/tools/install-kubectl.md will need to be removed. Instead, the following 3 files will need to be created.
  - content/ja/docs/tasks/tools/install-kubectl-linux.md
  - content/ja/docs/tasks/tools/install-kubectl-macos.md
  - content/ja/docs/tasks/tools/install-kubectl-windows.md

**Comment by s-kawamura-w664** [comment]
The netlify build (deploy) failed with error 'Build exceeded maximum allowed runtime'.
After force push, the build was able to pass.

**Comment by atoato88** [comment]
The main target page on preview site:
- https://deploy-preview-39849--kubernetes-io-main-staging.netlify.app/ja/docs/reference/kubectl/

And we could check the [removing of overview page](https://deploy-preview-39849--kubernetes-io-main-staging.netlify.app/ja/docs/reference/kubectl/overview).

**Comment by atoato88** [comment]
@s-kawamura-w664 
I would like to check the content of update.
As you wrote in description, the content of `_index.md` is as-is on current content, just moved?
In other word, you didn't update the content of `_index.md` to sync with `_index.md` on current `en`?

**Comment by atoato88** [comment]
Current codebase of this PR does not include the section of [here "In-cluster authentication and namespace overrides" in `en`](https://deploy-preview-39849--kubernetes-io-main-staging.netlify.app/docs/reference/kubectl/#in-cluster-authentication-and-namespace-overrides), that's why I commented above.

**Comment by s-kawamura-w664** [comment]
@atoato88 
> As you wrote in description, the content of `_index.md` is as-is on current `ja` content, just moved?
> In other word, you didn't update the content of `_index.md` to sync with `_index.md` on current `en`?
Yes.
The first, I just moved from overview.md to _index.md.
I tried to fix _index.md to the latest in the second commit, but it was so much to fix, so I decided to do it in the next PR.

**Comment by atoato88** [comment]
Ok, I also think it's reasonable.

**Comment by atoato88** [comment]
Content of this PR looks good.

But building preview failed, this didn't  relate with the content of this PR, I think.
Could you create empty commit for building preview again?

**Comment by atoato88** [comment]
/assign @nasa9084 
Could you review this?

**Comment by nasa9084** [comment]
/approve
Thank you~

**Pull request merged**
