### PR TITLE
Update the GitHub repo url of Java Operator SDK

### PR DESCRIPTION
**Pull request by haoxins**
Update the GitHub repository URL of Java Operator SDK since the repository is migrated to another organization.

### CODE REVIEW

**Comment by windsonsea** [comment]
Providing a description helps reviewers understand the purpose and context though your change is good to fix the url instead of redirection.

image

**Review by kundan2707 — COMMENTED** [review]
existing link if working fine. and no change required

**Comment by haoxins** [comment]
> Providing a description helps reviewers understand the purpose and context though your change is good to fix the url instead of redirection.
> 
> image

added

**Review by divya-mohan0209 — COMMENTED** [review]
The existing link redirects to the new link mentioned by @haoxins. 

The submitter needs to note that this is a [trivial edit](https://www.kubernetes.dev/docs/guide/pull-requests/#:~:text=with%20less%20friction.-,Trivial%20Edits,the%20entire%20file%20a%20review.) since it doesn't significantly improve the quality of the documentation because it's not a broken link.

That being said, I'd like to approve it for the sake of correctness.
/approve

**Pull request merged**
