### PR TITLE
[ko] branch name in 'Korean L10n guide' page is updated

### PR DESCRIPTION
**Pull request by bishal7679**
# Fixes:- #34930 

`master` branch in 'Korean L10n guide' page is updated to `main` branch

### CODE REVIEW

**Comment by seokho-son** [comment]
https://github.com/kubernetes/website/issues/34930#issuecomment-1180469038

Hi @bishal7679 
Thank you for your contribution.

But I need to say, IMO, self-assigning (and opening a PR) is not a good way to proceed handling an open issue in an open source project. 
We need to check who are going to handle the issue. (especially, if you are not the author of this issue)

@jihoon-seo I hope to check your willingness first for handling this issue.

**Comment by seokho-son** [comment]
/retitle [ko] branch name in 'Korean L10n guide' page is updated

**Comment by jihoon-seo** [comment]
For anyone's information:
Regarding @seokho-son's [comment](https://github.com/kubernetes/website/pull/34936#issuecomment-1180469466):
please see [this](https://github.com/kubernetes/website/issues/34930#issuecomment-1182720540).

/lgtm

**Comment by seokho-son** [comment]
Hi @bishal7679 

Thank you for your contribution!
Korean localization uses development branch (currently, it is **dev-1.24-ko.2**) and are avoiding PRs to main branch to prevent conflicts.
But, I am going to approve this PR in **main** branch since it is a hot-fix.

/approve

**Pull request merged**
