### PR TITLE
Update expose-intro.html

### PR DESCRIPTION
**Pull request by Kylsky**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jihoon-seo** [comment]
/test all
Because:
image

**Comment by jimangel** [comment]
Hey there! @Kylsky, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
CLA not ready for over a month.
Feel free to reopen when it is signed.
/close

**Pull request closed without merging**
