### PR TITLE
de translation for project slogan

### PR DESCRIPTION
**Pull request by sftim**
Translate “Production-Grade Container Orchestration” (not sure about wording, I wrote this one rather than copying).

[Preview](https://deploy-preview-18263--kubernetes-io-master-staging.netlify.com/de/)

/language de
/kind cleanup

### CODE REVIEW

**Comment by sftim** [comment]
Partial fix for #17593

**Comment by mkorbi** [comment]
@sftim I also was thinking about it to translate it but for me, it sounds odd in german. Could think about "Produktionsreife Container-Orchestrierung".

Or throw this phrase away and found a better one. I think no one has doubts about the production readiness of K8s :)

**Comment by sftim** [comment]
Any localization is fine by me.

**Comment by sftim** [comment]
Wording amended.

**Comment by sftim** [comment]
Relevant to issue #14137

**Comment by rlenferink** [comment]
_Adding approved label manually because this is a German localization effort and @mkorbi already gave his approval as de-owner in the following comment: https://github.com/kubernetes/website/pull/18263#issuecomment-568795761_

**Comment by sftim** [comment]
@rlenferink you [set](https://github.com/kubernetes/website/pull/18263#issuecomment-569407674) a high standard for traceability and explanation. Thank you!

**Pull request merged**
