### PR TITLE
Fix broken links to Ansible docs

### PR DESCRIPTION
**Pull request by sshnaidm**
Fix broken links to Ansible docs - variables and inventory.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Thanks for the contribution, @sshnaidm .
The link has been corrected (see PR #27473). I plan to close this pull request.
/kind cleanup
/close

**Comment by sshnaidm** [comment]
@kbhawkey well, sure. But my issue was submitted earlier than #27473 . Is there a way to bring attention of reviewers to my issues so they wouldn't be ignored? IRC, maillist, something else?
Thanks.

**Comment by sshnaidm** [comment]
@kbhawkey actually after closer inspection of #27473 I see it solved only one link. My patch solve all two broken links. Probably still need to be merged?

**Comment by kbhawkey** [comment]
👋 @sshnaidm .
OK, You can reopen this PR. I may have missed the second change.

**Comment by sshnaidm** [comment]
@kbhawkey seems like second link was fixed in https://github.com/kubernetes/website/pull/27366, so I close this PR

**Comment by kbhawkey** [comment]
OK, thanks for checking!

**Pull request closed without merging**
