### PR TITLE
Remove /static/js/anchor-4.1.1-min.js

### PR DESCRIPTION
**Pull request by sabazubair**
**Description:** The following PR completes #22040 and serves as my first contribution to an open source project. 🎉  I removed anchor-4.1.1-min.js from /static/js/anchor-4.1.1-min.js, not /scripts/js/anchor-4.1.1-min.js as no such file exists in /scripts. Then, I removed the corresponding call in /layouts/partial/head.html.

**Help Needed:** I was not able to preview my changes locally. After installing Hugo, I ran into a "socket too many files open" error. I learned how to check and change maxfiles and maxfileperproc (using this site: https://krypted.com/mac-os-x/maximum-files-in-mac-os-x/) but I felt uncomfortable making a permanent change without fully understanding what the side-effects would be (if there are any at all). If you could please suggest how I may go about solving this error, I would appreciate it, as I feel I'll run into it again. Thank you.

### CODE REVIEW

**Comment by sabazubair** [comment]
1) CLA is signed 
2) For your review: /assign @jimangel

**Comment by celestehorgan** [comment]
/assign

Hi @sabazubair! Thanks for taking this on! 

I've raised your concern re: the build error you encountered locally on the #sig-docs channel in the Kubernetes slack workspace. I encountered a similar issue (and set the maxfiles higher – it's nbd), but you're the only other person I've seen who's had the same problem.

I'll review this change for you, since I created the issue! 

PS: Saba is the name of one of my best friends ❤️

**Comment by sabazubair** [comment]
Thanks @celestehorgan ☺️

**Comment by celestehorgan** [comment]
/lgtm 

I tested this by:
1. Navigating to a docs content page, i.e. https://deploy-preview-22311--kubernetes-io-master-staging.netlify.app/docs/concepts/overview/what-is-kubernetes/#why-you-need-kubernetes-and-what-can-it-do, and noting that both the side nav links work and that anchor links are added beside every header.
2. Navigating to a blog post page, i.e. https://deploy-preview-22311--kubernetes-io-master-staging.netlify.app/blog/2020/06/working-with-terraform-and-kubernetes/#terraform-kustomize-provider, and noting that both the side nav links work and that anchor links are added beside every header.
3. Checking all top level pages: [Training](https://deploy-preview-22311--kubernetes-io-master-staging.netlify.app/partners/#kcsp), [Parnters](https://deploy-preview-22311--kubernetes-io-master-staging.netlify.app/partners/), [Community](https://deploy-preview-22311--kubernetes-io-master-staging.netlify.app/community/), [Case Studies Home](https://deploy-preview-22311--kubernetes-io-master-staging.netlify.app/case-studies/) and noting that anchor links were **not** generated on headers for these pages.
4. Checking individual case study pages, i.e. https://deploy-preview-22311--kubernetes-io-master-staging.netlify.app/case-studies/spotify/, and noting that anchor links were not generated on headers for these pages
5. Checking a translation for all items listed in 1-4.
6. Searching the repo for the string `anchor-4.1.1-min.js` (and finding nothing)

---

May I suggest @sftim or @onlydole do a second review and double-check?

**Comment by celestehorgan** [comment]
By the way @sabazubair, could you try building this again locally and then copy-pasting the error log either here or in the #sig-docs channel?

**Comment by sabazubair** [comment]
Hey @celestehorgan. Thanks for your help so far. Here's the error I get when I run `hugo server --buildFuture`: `ERROR 2020/07/10 15:20:12 Error: listen tcp 127.0.0.1:1313: socket: too many open files`. You mentioned changing maxfile limit is fine. Should I go ahead with that and try again? I require some guidance here though, for example: What limit would be acceptable?

**Comment by celestehorgan** [comment]
@sabazubair could you leave a comment on this PR with the words "I signed it"? This will retrigger the CLA check and allow us to merge the PR.

`/check-cla` is apparently not working.. 🤔

**Comment by sabazubair** [comment]
I signed it.

**Comment by sftim** [comment]
I'm also going to fix the PR title
/retitle Remove /static/js/anchor-4.1.1-min.js

**Comment by celestehorgan** [comment]
Hey @sabazubair, 

Could you follow the instructions [here](https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) when you have a moment? It looks like your commit isn't linked to an email address, which is why the CLA check is failing.

(Don't despair! Everyone's first commit to a big open source project is a bit rough.)

**Comment by sabazubair** [comment]
Hey @celestehorgan. Sorry about that. I've followed the link as best as I can (Github's UI has changed). It should work now. I would re-trigger /check-cla for you, but I'm unsure if I have that privilege (guess I'll find out shortly). Fingers crossed!

**Comment by sabazubair** [comment]
@celestehorgan I ran `git log` on my branch and understand why the cla check is failing. I made the commit using my (former) work email. Fixing now. In case someone is running into the same issue, you can pass this along:  https://stackoverflow.com/questions/26004587/git-commits-are-not-getting-linked-with-my-github-account

**Comment by sabazubair** [comment]
@celestehorgan I ran `git log` on my branch, as suggested [here](https://stackoverflow.com/questions/26004587/git-commits-are-not-getting-linked-with-my-github-account), and know why the CLA check is failing. I recently changed my github email from my work to my personal email address. I have navigated back into my branch and changed the git config but when I refresh here, I don't see that change being reflected. Any ideas? Going to keep trying. Thanks for your help so far!

**Comment by sabazubair** [comment]
@celestehorgan I contacted Github and they advised me to re-add my work email. I did. It should be good now. Thanks for your help & encouragement. (Alternatively, I could've re-written the repo history but they did not recommend that.)

**Pull request merged**
