### PR TITLE
[ko] Added the correct korean translations.

### LINKED ISSUE #29027: [ko] Wrong Korean translations
**This is a Bug Report**

**Problem:**
- `PodCondition` / `pod condition` 이 `파드(의) 조건` 으로 번역된 경우가 있음.
- `node condition` 이 `노드(의) 조건` 으로 번역된 경우가 있음.

**Proposed Solution:**
Replace:
- `파드 조건` -> `파드 컨디션`
- `파드의 조건` -> `파드의 컨디션`
- `노드 조건` -> `노드 컨디션`
- `노드의 조건` -> `노드의 컨디션`
- `조건` -> `컨디션` (문맥을 잘 파악하면서 선택적으로 replace 해야 함)

**Page to Update:**
- https://kubernetes.io/ko/docs/concepts/workloads/pods/pod-lifecycle/
- https://kubernetes.io/ko/docs/tutorials/stateful-application/basic-stateful-set/
- https://kubernetes.io/ko/docs/concepts/scheduling-eviction/taint-and-toleration/
- ...

/language ko

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
Fixes #29027

### CODE REVIEW

**Comment by reylejano** [comment]
/retitle [ko] Added the correct korean translations.

**Review by jihoon-seo — COMMENTED** [review]
@jayesh-srivastava Thank you for your contribution! 😊
I reviewed and wrote some comments.
PTAL!

**Comment by jihoon-seo** [comment]
/assign

Previews:
- https://deploy-preview-29732--kubernetes-io-main-staging.netlify.app/ko/docs/concepts/scheduling-eviction/taint-and-toleration/
- https://deploy-preview-29732--kubernetes-io-main-staging.netlify.app/ko/docs/concepts/workloads/pods/pod-lifecycle/
- https://deploy-preview-29732--kubernetes-io-main-staging.netlify.app/ko/docs/tutorials/stateful-application/basic-stateful-set/

**Comment by jihoon-seo** [comment]
If the PR #30287 is merged, then this PR will be okay to be closed.

**Comment by ianychoi** [comment]
In my opinion, @jihoon-seo 's comment can be addressed through another PR (e.g., @suhhee1011 's PR) considering language barrier. @jihoon-seo: thoughts?

Now one question is: is it possible to rebase this PR by owner like @gochist and @seokho-son ? If possible, we can rebase and merge.

The PR looks good to me although additional Korean context needs to be added like @suhhee1011 's follow-up.

**Comment by jihoon-seo** [comment]
@ianychoi I totally agree with you! 😊

**Comment by seokho-son** [comment]
I usually prefer waiting a response from the contributor :) 
@jayesh-srivastava could you follow up reviewers' comments in this PR ?

**Comment by jihoon-seo** [comment]
Closing due to [author not responding to comments or feedback in 2 or more weeks](https://kubernetes.io/docs/contribute/participate/pr-wranglers/#when-to-close-pull-requests),
and covered by the PR #31365.

/close

**Pull request closed without merging**
