### PR TITLE
[ja] replaced {{< codenew ... >}} with {{% codenew ... %}}

### PR DESCRIPTION
**Pull request by andreygoran**
This is a continuation of PR https://github.com/kubernetes/website/pull/42180 (Replace {{< codenew ... >}} with {{% codenew ... %}})
Fixes https://github.com/kubernetes/website/issues/42179 (Copy To Clipboard breaks YAML format)

### CODE REVIEW

**Review by t-inu — COMMENTED** [review]
Thank you and sorry for the late review.
It's fine about changed files.
Could you please include the following file? This file was added after this PR was created.
https://github.com/kubernetes/website/blob/be456cc0dc8a5e43334e71fe7de0d8c9e94a80ae/content/ja/docs/tutorials/stateful-application/zookeeper.md?plain=1#L65

**Review by t-inu — COMMENTED** [review]
Thank you!
/label tide/merge-method-squash
/lgtm

**Comment by nasa9084** [comment]
/approve
Thanks!

**Pull request merged**
