### PR TITLE
Remove outdated rkt guide

### LINKED ISSUE #7279: conformance status for /docs/getting-started-guides/rkt
Per #7278, we are looking to identify guides that are stale vs actively maintained but need work to become conformant.

The content of `/docs/getting-started-guides/rkt` has been identified as stale, because it refers to Kubernetes version `v1.3.0-beta.2` which is very old.

PING owners/approvers/contributors @dchen1107 @yifan-gu @lavalamp @lizrice @steveperry-53

### PR DESCRIPTION
**Pull request by errordeveloper**
Closes #7279. Ping #7278.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7376)

### CODE REVIEW

**Comment by errordeveloper** [comment]
@heckj as it's a deletion, do I still need an LGTM from someone?

**Comment by heckj** [comment]
yeah - since you commented to @yifan-gu, i was thinking they would apply it, but if that was just for info i can add it here. wasn’t sure about your intent

**Comment by errordeveloper** [comment]
Yeah, it was just for info, or in hope the @yifan-gu
<https://github.com/yifan-gu> would review sooner.

—
Ilya Dmitrichenko

**Comment by heckj** [comment]
got it
/lgtm

**Pull request merged**
