### PR TITLE
All files for Haufe Groups case study

### PR DESCRIPTION
**Pull request by kbarnard10**
- HTML, CSS, and images for Haufe Group case study
- Updated case study landing page

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7051)

### CODE REVIEW

**Comment by kbarnard10** [comment]
Do you have an estimate for when this will be published?

**Comment by zacharysarah** [comment]
@kbarnard10 When do you need it by?

**Comment by kbarnard10** [comment]
@zacharysarah - Would Wednesday or Thursday be doable?

**Pull request merged**
