### PR TITLE
Graduate NonPreemptingPriority to GA

### PR DESCRIPTION
**Pull request by denkensk**
Update the doc
ref https://github.com/kubernetes/enhancements/issues/902

### CODE REVIEW

**Comment by denkensk** [comment]
/hold 
Waiting for https://github.com/kubernetes/website/pull/31267 merged.
/cc @sftim

**Comment by jimangel** [comment]
Since we're waiting on https://github.com/kubernetes/kubernetes/pull/107432 to merge, should this PR target dev-1.24.

/cc @nate-double-u 
/milestone 1.24

**Comment by denkensk** [comment]
> Since we're waiting on https://github.com/kubernetes/kubernetes/pull/107432 to merge, should this PR target dev-1.24?
> 
> 
> 
> /cc @nate-double-u 
> 
> /milestone 1.24

yes, this is for 1.24

**Comment by nate-double-u** [comment]
I agree with @jimangel, if this is for 1.24, it should target the `dev-1.24`. Thanks @denkensk!

**Comment by denkensk** [comment]
@nate-double-u 
I will change the target branch to dev-1.24.
I want to know if I need to sync to main or not？or some automatic will do it？

**Comment by nate-double-u** [comment]
Depending on which branch you split from, there will be some commits that may be removed from the timeline, but that's intentional.

Here's [GitHubs docs on swapping base branches](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request). Let us know if this doesn't answer your concerns @denkensk 🙂

**Comment by denkensk** [comment]
> Assigning @sftim since he is the one engaged on this.
> 
> /assign @sftim 

since https://github.com/kubernetes/kubernetes/pull/107432  has been merged
@sftim  pls review this pr.

**Comment by denkensk** [comment]
> I agree with @jimangel, if this is for 1.24, it should target the `dev-1.24`. Thanks @denkensk!

Done

**Comment by PI-Victor** [comment]
NFC
/lgtm

**Comment by reylejano** [comment]
The changes look good for 1.24
Thank you
/approve

**Pull request merged**
