### PR TITLE
Removed false statement regarding storage class objects

### LINKED ISSUE #42958: Docs says that `StorageClass` objects cannot be updated after creation.
It says here that `StorageClass` objects cannot be updated after creation:

https://github.com/kubernetes/website/blob/badc695f6960e5df1ed62e0fee40191b77e9191e/content/en/docs/concepts/storage/storage-classes.md?plain=1#L35-L38

It's not true. I tried editing the `allowVolumeExpansion` field of a storage class I had deployed, and that worked fine.

### PR DESCRIPTION
**Pull request by gaiters-cafes**
Fixes #42958 

I've removed all the instances of this across all the different languages it has this statement.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@gaiters-cafes Thank you for your contribution! This PR affects files in multiple languages, but the documentation follows distinct processes per localization. We usually don't merge PRs impacting multiple languages at once. I would recommend modifying only the primary website content (which means only English content) initially with this PR. And after this English PR merge, submit separate PRs for other languages. Hope this suggestion is helpful.

**Comment by dipesh-rawat** [comment]
/hold

Until this PR only covers one language

**Comment by sftim** [comment]
/label tide/merge-method-squash

(to avoid touching the other localizations)

**Pull request merged**
