### PR TITLE
added image volume type in ephemeral volumes

### PR DESCRIPTION
**Pull request by saireddyb**
Image volume type falls under ephemeral volumes.

### CODE REVIEW

**Comment by salaxander** [comment]
This is still an alpha feature right? Is that worth noting here?

**Comment by saireddyb** [comment]
> This is still an alpha feature right? Is that worth noting here?

I was excited about this feature and didn't find in ephemeral page.
So though to create my first PR.
Should I close this PR.

**Comment by tengqm** [comment]
> > This is still an alpha feature right? Is that worth noting here?
> 
> I was excited about this feature and didn't find in ephemeral page. So though to create my first PR. Should I close this PR.

What @salaxander suggested was that the stage of the feature should be mentioned somewhere.
This is not a blocker to document it.
I'm as excited by this feature as you, and my perception is that we need to document this feature in more details so that people get to know about its usage and caveats.

**Comment by saireddyb** [comment]
> I'm as excited by this feature as you, and my perception is that we need to document this feature in more details so that people get to know about its usage and caveats.

ok, but the detailed info is already available [here](https://kubernetes.io/docs/concepts/storage/volumes/#image)

**Review by mengjiao-liu — COMMENTED** [review]
/lgtm

**Pull request merged**
