### PR TITLE
Make glossary/kube-proxy.md follow v1.17 of the original text

### LINKED ISSUE #21300: ja: Make glossary/kube-proxy.md follow v1.17 of the original text
**This is a Feature Request**

**What would you like to be added**
Update glossary/kube-proxy.md to follow v1.17 of the original (Englist) text.

**Why is this needed**
content/ja/docs/reference/glossary/kube-proxy.md it outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.2/content/ja/docs/reference/glossary/kube-proxy.md

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/reference/glossary/kube-proxy.md

diff between translated and v1.17
https://gist.github.com/oke-py/8ee394140807a614af6fba10eda08961

**Note**
Currently, we use `dev-1.17-ja.2` branch. Please open a PR targeting the branch.

ref
[How To Contribute](https://kubernetes-docs-ja.kibe.la/shared/entries/c5878aa5-ad1f-4f29-a5bb-25853cbc14ec)
[翻訳スタイルガイド](https://kubernetes-docs-ja.kibe.la/shared/entries/5efe4fa7-d2a1-4a1d-8bc3-ce7ccdc064a6)

If you have a question, feel free to ask us here or slack.k8s.io #kubernetes-docs-ja channel.

### PR DESCRIPTION
**Pull request by onsd**
Close #21300

### CODE REVIEW

**Comment by inductor** [comment]
@onsd Hello, Thank you very much for your contribution!
Could you possibly sign to the CLA? It is necessary for the process.

Thanks in advance 🙏

**Comment by onsd** [comment]
@inductor Yes, I signed to the CLA!

**Comment by inductor** [comment]
@onsd you need to be careful that Linux foundation registered information and github information should be the same

**Comment by onsd** [comment]
@inductor After reading [here](https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement), I understand that the email addresses need to match.
I have confirmed that the email addresses are the same. What else should I look for?

**Comment by onsd** [comment]
@inductor I was happy to just register my Linux Foundation ID.
now signed the CLA.

**Pull request merged**
