### PR TITLE
Making dockershim FAQ evergreen

### PR DESCRIPTION
**Pull request by chris-short**
After a brief discussion in [ContribEx Slack](https://kubernetes.slack.com/archives/C1TU9EB9S/p1674655189336319), we realized we shouldn't mark the [dockershim FAQ](https://k8s.io/dockershim) as out of date once it hits a year old. It's still relevant, accurate, and I know I reference it at least once a month still.

@reylejano says [we should mark it as `evergreen`](https://kubernetes.slack.com/archives/C1J0BPD2M/p1674665054450249) and this PR accomplishes that.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Thanks for your attention to details and calendars, @chris-short!


I'd strike through:
> You can discuss the decision to remove dockershim via a dedicated
> [GitHub issue](https://github.com/kubernetes/kubernetes/issues/106917).

(with a note about why), as that ship has sailed.

---

To make this evergreen, also change:
```diff
-[v1.24 release](/releases/#release-v1-24) actually removed the dockershim
+v1.24 release actually removed the dockershim
```

and edit the source for https://k8s.io/docs/tasks/administer-cluster/migrating-from-dockershim/ &ndash; add a prominent comment to the front matter. The comment should say that if we are removing that page / section, we need to go back and edit https://kubernetes.io/blog/2022/02/17/dockershim-faq/ to remove the link to it.

**Review by Arhell — COMMENTED** [review]
Please re-push commit for reload netlify

**Comment by chris-short** [comment]
> and edit the source for https://k8s.io/docs/tasks/administer-cluster/migrating-from-dockershim/ – add a prominent comment to the front matter. The comment should say that if we are removing that page / section, we need to go back and edit https://kubernetes.io/blog/2022/02/17/dockershim-faq/ to remove the link to it.

@sftim I was a little confused by this at first (might be the lack of coffee).  
  
But, basically you want a comment at the top of migrating-from-dockershim file stating update the FAQ if this page is changed/removed? Same PRs or different ones?

**Comment by sftim** [comment]
> But, basically you want a comment at the top of migrating-from-dockershim file stating update the FAQ if this page is changed/removed? Same PRs or different ones?

Same PR is good, because that shows we've checked the boxes for making the blog article need minimum maintenance. What we _don't_ want is to have to set reminders to check for or fix these things every few months. `evergreen` means we're promising to maintain the article, or that it doesn't need maintenance.

**Comment by sftim** [comment]
/approve

/hold

@chris-short you're welcome to unhold this if you judge that you've made the article evergreen, and you've got an LGTM from another contributor to confirm that.

**Comment by reylejano** [comment]
/lgtm
@chris-short , feel free to unhold when ready

**Comment by reylejano** [comment]
Re-applying lgtm
/lgtm
@chris-short feel free to unhold when ready

**Comment by reylejano** [comment]
/unhold
A followup PR can be made to address [comment](https://github.com/kubernetes/website/pull/39106#pullrequestreview-1269811474)

**Pull request merged**
