### PR TITLE
Update enforcing-pod-security-standards.md

### PR DESCRIPTION
**Pull request by eyherabh**
Replaces "per" with "as per", turning "... allowed per current best practices" into "... allowed as per current best practices" because I think the intention was to mean "according to current best practices" and "as per" conveys that meaning while "per" does not/need not.

### CODE REVIEW

**Comment by vaibhav2107** [comment]
Hi @eyherabh , you need to sign the CLA before your PR can be reviewed 
You can follow [CLA guide](https://github.com/kubernetes/community/blob/master/CLA.md) for the reference

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by deepak4566** [comment]
@eyherabh hey this looks yours first pr ,thanks for ur contribution to community 🎉🎉🎉
Seems like CLA not authorised so click on the red button in comments to complete the process

**Comment by deepak4566** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/42469/#/?version=2)
> 
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/42469/#/?version=2) - login: @eyherabh / name: Hugo Gabriel Eyherabide . The commit ([5d99234](https://github.com/kubernetes/website/commit/5d9923424e518ce1993d89e3341da77c737c80fb)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/42469/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

Click on red button to complete the process

**Comment by reylejano** [comment]
Imo, I prefer the original wording
@eyherabh , I'm closing this PR as this PR fails the CLA check
Feel free to reopen this PR when you have signed the CLA and you disagree with my comment about preferring the original
You can reopen this PR with a `/reopen` in a comment
/close

**Pull request closed without merging**
