### PR TITLE
Removed kubenet from docs

### LINKED ISSUE #31659: Remove kubenet from docs
**This is a Bug Report**

**Problem:** Per https://github.com/kubernetes/kubernetes/issues/100707 the kubenet network plugin is no longer needed / used / part of Kubernetes.

**Proposed Solution:**
Find all mentions of kubenet in the documentation and, for v1.24 of Kubernetes, remove those mentions

**Kubernetes Version:**
v1.24

**Additional Information:**
/milestone 1.24
/language en

### PR DESCRIPTION
**Pull request by mk46**
Removing reference of `kubenet` from docs.
/kind cleanup
/language en 
Fixes #31659 
Part of https://github.com/kubernetes/kubernetes/issues/100707

### CODE REVIEW

**Comment by mk46** [comment]
/sig node
@sftim Would you mind to take a look? Thanks!!

**Comment by reylejano** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/100707
Should this target the _dev-1.24_ branch for when dockershim is gone then kubenet is gone

**Comment by mk46** [comment]
> Related to [kubernetes/kubernetes#100707](https://github.com/kubernetes/kubernetes/issues/100707) Should this target the _dev-1.24_ branch for when dockershim is gone then kubenet is gone

Yes, I missed adding milestone.
/milestone 1.24

**Comment by tengqm** [comment]
/hold
/milestone 1.24

Please retarget dev-1.24 branch rather than 'main'.

**Comment by mk46** [comment]
Hi @tengqm, I have created another PR for the dev-1.24 branch. Please take a look on https://github.com/kubernetes/website/pull/31667.
Could we close this or keep it open for main till https://github.com/kubernetes/kubernetes/issues/100707?
Thanks!!

**Pull request closed without merging**
