### PR TITLE
show the output from metrics server

### PR DESCRIPTION
**Pull request by digininja**
It seems a shame to install it and then not show it in use. The first thing I did after installing it and then seeing the next command was to uninstall it was to go and google what it is and how to get data from it.

### CODE REVIEW

**Comment by T-Lakshmi** [comment]
> It is still showing an X by it, do I have to do this for every PR?

No, we need to sign CLA(Contributor License Agreements) only once, It will take some time to reflect here.
Please wait some time.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by digininja** [comment]
I've just filled the form in a second time and it seems happier now.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-44116--kubernetes-io-main-staging.netlify.app/docs/tutorials/hello-minikube/

**Pull request merged**
