### PR TITLE
fix the command output

### PR DESCRIPTION
**Pull request by chenhuan12**
fix the command output

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6791)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
did you test it by release-1.9? @chenhuan12

**Comment by chenhuan12** [comment]
release-1.8.5 @zhangxiaoyu-zidif

**Comment by zhangxiaoyu-zidif** [comment]
Now master branch should keep same pace with release 1.9.  I am not sure whether there is diff between 1.8.5 and 1.9.X. You'd better validate it. Thanks. =)

**Comment by chenhuan12** [comment]
I have verified on version 1.9.0.Thanks. @zhangxiaoyu-zidif 
-bash-4.2# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by zhangxiaoyu-zidif** [comment]
good， thanks！

**Pull request merged**
