### PR TITLE
replaced deprecated 'kubectl run' for minikube setup

### LINKED ISSUE #10956: Issue with k8s.io/docs/setup/minikube/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The page mentions `kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080` though when running the command with `kubectl` 1.12.2 a warning is emitted:

```
$ kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
kubectl run --generator=deployment/apps.v1beta1 is DEPRECATED and will be removed in a future version. Use kubectl create instead.
deployment.apps/hello-minikube created
```

**Proposed Solution:**
Update `kubectl` syntax.

**Page to Update:**
https://kubernetes.io/k8s.io/docs/setup/minikube/

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by sluetze**
swapped kubectl run for kubectl create -f - against stable api

fixes #10956

### CODE REVIEW

**Comment by Bradamant3** [comment]
@sluetze it looks as though this PR should retarget the `dev-1.13` branch, yes? If you could take care of it, that would be great. Thank you so much for your contribution!

**Comment by tfogo** [comment]
Hi @sluetze, I'm trying to get all PRs for 1.13 merged asap. Could you let me know what the status of this PR is? Thanks!

**Comment by Bradamant3** [comment]
@tfogo I'll leave this one to you for final decision, but my inclination is to discard this PR since we're shipping 1.13 so soon.

**Comment by mistyhacks** [comment]
I agree, please discard this PR and make a new PR targeting `release-1.12` if you are still interested in fixing this for that version.

**Pull request closed without merging**
