### PR TITLE
Fix case of fstype param name for aws-ebs storage type

### PR DESCRIPTION
**Pull request by hercynium**
This is in reference to issue #13512 

I've checked the source code in k8s and fixing it to work like the docs has the potential to break other people's systems, therefore I think this should be strictly a documentation fix.

### CODE REVIEW

**Comment by jsafrane** [comment]
I think that StorageClass.Parameters are parsed case-insensitive, so both `fsType` and `fstype` should work.

https://github.com/kubernetes/kubernetes/blob/6fef6e8613c0b4fec54b129e9c8b74daff253296/pkg/volume/awsebs/aws_util.go#L126

Traditionally, we used camelCase that's common in Kubernetes json / yaml files.

**Comment by hercynium** [comment]
> I think that StorageClass.Parameters are parsed case-insensitive, so both `fsType` and `fstype` should work.
> 
> https://github.com/kubernetes/kubernetes/blob/6fef6e8613c0b4fec54b129e9c8b74daff253296/pkg/volume/awsebs/aws_util.go#L126
> 
> Traditionally, we used camelCase that's common in Kubernetes json / yaml files.

Ah... this looks like it was broken in 217a3d89021 which is from k8s v1.12.5 (which I am currently using) and then fixed in 732eb69597f which is from v1.14.0

So, in k8s prior to 1.14.0, this param is all lowercase, and after that case insensitive.

**Comment by jsafrane** [comment]
Indeed, it was broken between 217a3d890219abf7eb759e9b64c0403c6ee40e2c and 732eb69597f6b397b9be0253a1ff44759190483b, i.e. in 1.12 and 1.13.

Filled https://github.com/kubernetes/kubernetes/issues/75941, https://github.com/kubernetes/kubernetes/pull/75943 and https://github.com/kubernetes/kubernetes/pull/75944

**Comment by DanyC97** [comment]
@jsafrane many thanks for providing valuable tech input!
@hercynium should we add a small note Or just close this PR ? wdyt @jsafrane ?

**Comment by hercynium** [comment]
> @hercynium should we add a small note Or just close this PR ? wdyt @jsafrane ?

I'd prefer adding a note, since not everybody will be on the latest release and when setting the fstype with the wrong case fails, it does silently (because the param simply isn't recognized)

**Comment by tengqm** [comment]
So ... if the problem no longer exists in 1.14, we should close this one? @hercynium

**Comment by Bradamant3** [comment]
@hercynium this is a nice catch, but unfortunately the way we manage docs versioning the change in this PR won't work, and we probably wouldn't take changes submitted to earlier branches (for the affected K8s versions). If you could submit a new PR with a note about the affected versions, we'll see whether that approach works. Thanks for understanding!

**Pull request closed without merging**
