### PR TITLE
[en] Fix tag that do not match

### PR DESCRIPTION
**Pull request by bconfiden2**
Related Issue : #36957

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Looks good to me!
/lgtm

**Review by rolfedh — APPROVED** [review]
Language review. Looks good to me.

**Comment by sftim** [comment]
Why should we make this change @bconfiden2 ?

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by tengqm** [comment]
I don't think this is a needed fix.
/close

**Pull request closed without merging**
