### PR TITLE
[bn] Localized content/bn/docs/reference/glossary/_index.md

### PR DESCRIPTION
**Pull request by Mouly22**
Signed-off-by: Umme Abira Azmary [abiraazmary22@gmail.com](mailto:abiraazmary22@gmail.com)
Localizes content/bn/docs/reference/glossary/_index.md> to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/kubernetes/website/issues/31677

### CODE REVIEW

**Comment by mitul3737** [comment]
@Mouly22 I think you should follow this page while localizing: https://github.com/kubernetes/website/blob/main/content/en/docs/reference/_index.md

**Review by mitul3737 — CHANGES_REQUESTED** [review]
You should have followed this page I guess while localizing: https://github.com/kubernetes/website/blob/main/content/en/docs/reference/_index.md

**Review by Imtiaz1234 — APPROVED** [review]
LGTM

**Review by mitul3737 — APPROVED** [review]
LGTM

**Comment by mitul3737** [comment]
Hey @divya-mohan0209 , Can you look into this PR?

**Review by mitul3737 — APPROVED** [review]
lgtm

**Pull request closed without merging**
