### PR TITLE
WIP Document matchLabelKeys for Pod (anti)affinity [ALPHA]

### PR DESCRIPTION
**Pull request by alculquicondor**
/sig scheduling

### CODE REVIEW

**Comment by Princesso** [comment]
Hello @alculquicondor  👋, I looked at this PR, and the file change highlights it as TODO. Please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday 14th November 2023. Thank you!

**Comment by Princesso** [comment]
Hello @alculquicondor @sanposhiho 👋, gentle reminder to take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday 14th November 2023. Thank you!

**Comment by sanposhiho** [comment]
@Princesso I'll take over the doc PR from @alculquicondor, and just opened https://github.com/kubernetes/website/pull/43812 as a new PR.

**Comment by Princesso** [comment]
Thanks @sanposhiho. Do we need to close this one?

**Comment by alculquicondor** [comment]
/close
in favor of #43812

**Pull request closed without merging**
