### PR TITLE
Fix typo: gPRC

### PR DESCRIPTION
**Pull request by sftim**
gPRC (short perhaps for gRPC procedure remote call?) &rarr; gRPC

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-30709--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/#feature-gates

/lgtm

**Comment by mehabhalodiya** [comment]
LGTM!

**Comment by sftim** [comment]
@mehabhalodiya you can reply with “/lgtm” (on a line by itself) to confirm that this change is technically correct

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya you can reply with “/lgtm” (on a line by itself) to confirm that this change is technically correct

Yes, but thought that `/lgtm` label is already added, so why not to write `LGTM` simply instead of label style!

**Pull request merged**
