### PR TITLE
[ko] typo fix for cloud-controller.md

### PR DESCRIPTION
**Pull request by sean-k1**
misspelling

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@sean-k1  Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.

You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by sean-k1** [comment]
@dipesh-rawat 
 thanks I signed CLA

**Comment by seokho-son** [comment]
Hi @sean-k1 
Thank you for the typo fix! :)

Could you apply this PR based on (and target to) the dev-1.26-ko.1 (the current Korean development branch) ?
This is to reduce merge conflict when we merge dev-1.26-ko.1 into main. :)

**Comment by sean-k1** [comment]
@seokho-son 
hi seokho-son i based change to dev-1.26.-ko.1 
but some files conflicted

could you let me know which branch version I should follow?

**Comment by seokho-son** [comment]
Hi @sean-k1 
I guess it is because you've changed the target branch only. 
The base of [sean-k1:patch-3](https://github.com/sean-k1/website/tree/patch-3) should be [kubernetes:dev-1.26-ko.1](https://github.com/kubernetes/website/tree/dev-1.26-ko.1)
If you feel hard to change the base, you can open another PR. (base: dev-1.26-ko.1 -> make the change again, open a PR targeting to dev-1.26-ko.1)

**Pull request closed without merging**
