### PR TITLE
[ko] Mention kubernetes/websites everywhere in the same way

### PR DESCRIPTION
**Pull request by MaxymVlasov**
Related to https://kubernetes.slack.com/archives/C0191RDKHU1/p1680549820387879

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @MaxymVlasov 

Sorry for this late response. As you know Korean localization team try to update Korean documents according to changes in English documents (main branch). 
Could you let us know the related PR that has been merged in the main branch for English ?

Also, currently, we are using our development branch. https://github.com/kubernetes/website/tree/**dev-1.27-ko.1**

According to the Korean localization guideline, 
the base of your feature branch and target (base) branch of this PR needs be "dev-1.27-ko.1"

**Comment by seokho-son** [comment]
I guess the current 

deploy/netlify — Deploy preview failed to build (either branch is broken, or a Netlify bug)
 [Details](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/642c29f515a7a70008f90c35)

can be resolved when you change the target and base branches for this PR.

**Comment by MaxymVlasov** [comment]
> Korean localization team try to update Korean documents according to changes in English documents (main branch).

Aha, got it

>Could you let us know the related PR that has been merged in the main branch for English?

This one, also has poor reviewers responsibility. But because you have no blogpost mentioned in the review, all OK.
https://github.com/kubernetes/website/pull/40493

But of course, I can wait until it will be merged to EN first

**Comment by seokho-son** [comment]
Thanks @MaxymVlasov !

Let's use (updated) this PR after https://github.com/kubernetes/website/pull/40493 . (and let me see if I can facilitate the PR as well although I am not an English reviewer)

**Comment by MaxymVlasov** [comment]
@seokho-son https://github.com/kubernetes/website/pull/40493 just merged

**Pull request closed without merging**
