### PR TITLE
[pt-br] add content/pt-br/docs/tasks/access-application-cluster/access-cluster/

### PR DESCRIPTION
**Pull request by DanielViniciusAlves**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Sea-n** [comment]
Hey @DanielViniciusAlves,

The email used for commit this PR is not binding to your GitHub account, so the CLA validation won't pass.

Please goto GitHub Settings > Access > Emails > Add email address:
https://github.com/settings/emails

If you have other issues, please take a look at [the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Comment by AmanSarraf** [comment]
Thank you @DanielViniciusAlves , for your contribution.Please sign the [CLA](https://github.com/kubernetes/community/blob/master/CLA.md) so that we can accept your PR for review.
/assign

**Comment by jimangel** [comment]
Hey there! @DanielViniciusAlves, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Sea-n** [comment]
Hey @DanielViniciusAlves,

You have to sign the CLA so that we can review this PR and move forward.
Just click on the red NOT COVERED button in the first comment.

After signing the CLA, you may use this command to refresh the status:
/easycla

If you have any problem, please take a look at [the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Pull request closed without merging**
