### PR TITLE
Continued Fixing Translate extend cluster

### PR DESCRIPTION
**Pull request by prabangkoro**

### CODE REVIEW

**Comment by prabangkoro** [comment]
please kindly review
/assign @irvifa
/assign @girikuncoro 
/assign @phanama 

issue ticket: #15341

**Comment by girikuncoro** [comment]
@prabangkoro thanks for the follow up PR, this looks great! can you squash all your commits first into 1 before getting this in? this is for cleaner commit body message in master branch. refer to: https://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request

/lgtm

**Comment by prabangkoro** [comment]
okaay, I'm trying to squash it

**Comment by girikuncoro** [comment]
@prabangkoro please write proper commit message as this will be the only message shown in master branch, instead of "fix comment" how about "Following up PR #16421 to fix typos and wordings"
image

also, please becareful on rebasing so that you don't add additional "merge commit". Refer to this if you need it: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase or https://blog.algolia.com/master-git-rebase

The straight forward way, you can simply go back to the commit before your change, rebase with upstream master (or origin master if your forked master is synced), apply your latest changes, then force push to your fork/branch

**Comment by prabangkoro** [comment]
@girikuncoro 
I'm sorry, I don't really get it and get confused on the rebase stuff :")
Hmm, I hope I get it right this time hehe

**Comment by girikuncoro** [comment]
@prabangkoro this is perfect, thank you for doing this! 🎉 as usual, feel free to pick any other pages or fixes, so that you can claim your [hacktoberfest](http://hacktoberfest.digitalocean.com) tshirt

/lgtm
/approve

**Pull request merged**
