### PR TITLE
The fix clicks the error hyperlink that 'here' appears

### PR DESCRIPTION
**Pull request by xichengliudui**
The fix clicks the error hyperlink that 'here' appears

### CODE REVIEW

**Comment by xichengliudui** [comment]
@zacharysarah  OK，Thanks

**Comment by zacharysarah** [comment]
@xichengliudui 👋 I missed that this was an updated link to k/k, not k/website. Sorry! 🙇 

It looks like the link you're updating has changed significantly, with its contents moved to a different repo. I've modified the entire link path here.

**Pull request merged**
