### PR TITLE
Update what-is-kubernetes.md

### PR DESCRIPTION
**Pull request by nickbullock**
Fix typo in "what-is-kubernetes.md"

### CODE REVIEW

**Comment by sharikovvladislav** [comment]
Thank you! Good job, lad.

**Comment by nickbullock** [comment]
I signed it

**Comment by sftim** [comment]
LGTM (but I'm not a strong Russian speaker)

**Comment by php-coder** [comment]
@sftim PTAL

**Comment by php-coder** [comment]
@sftim Could you approve this, please?

**Comment by sftim** [comment]
Hi @php-coder. I'm not an approver for Russian localization.

**Comment by php-coder** [comment]
> Hi @php-coder. I'm not an approver for Russian localization.

Ok, I'm sorry for bothering you, Tim.


@kubernetes/sig-docs-ru-owners Please, approve.

**Pull request merged**
