### PR TITLE
Revise task for practising NGINX Ingress controller

### PR DESCRIPTION
**Pull request by sftim**
Improve [Set up Ingress on Minikube with the NGINX Ingress Controller](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/) [[preview](https://deploy-preview-29206--kubernetes-io-main-staging.netlify.app/docs/tasks/access-application-cluster/ingress-minikube/)]

- style tweaks
- fix sample output being marked as Bourne-style shell code
- mention that you need Kubernetes v1.19 minimum

This change does _not_ fix issue #29204, about Minikube deploying a too-old version of Kubernetes. That can come separately.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Before: https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
After: https://deploy-preview-29206--kubernetes-io-main-staging.netlify.app/docs/tasks/access-application-cluster/ingress-minikube/

**Comment by kbhawkey** [comment]
@sftim, would you rebase?

**Comment by sftim** [comment]
(I rebased)

**Comment by sftim** [comment]
Might help with issue #30127

**Pull request merged**
