### PR TITLE
Fixed an issue on custom-resource-definition-versioning.md

### PR DESCRIPTION
**Pull request by jimoosciuc**
Fixed an issue on CustomResourceDefinition yaml

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
Hi @jimoosciuc 👋 , Thank you for thr PR. Can you sign the [CLA](https://github.com/kubernetes/community/blob/master/CLA.md), so that this PR can be reviewed?

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-22925--kubernetes-io-master-staging.netlify.app/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

**Pull request merged**
