### PR TITLE
Removed the redundant text

### LINKED ISSUE #12861: copy/paste problem in EN doc Setup Kubeadm
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
i think there was a copy / paste problem during writing

**Proposed Solution:**
If you see Pods in the RunContainerError, CrashLoopBackOff or Error state after deploying the network solution and nothing happens to coredns (or kube-dns), **it’s very likely that the Pod Network solution and nothing happens to the DNS server,** it’s very likely that the Pod Network solution that you installed is somehow broken.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm/#pods-in-runcontainererror-crashloopbackoff-or-error-state

### PR DESCRIPTION
**Pull request by hpandeycodeit**
Fixes #12861 

Removed the redundant text as per the above issue.

### CODE REVIEW

**Comment by neolit123** [comment]
please change `Issue #12861` to `Fixes #12861`

**Comment by hpandeycodeit** [comment]
done

**Comment by Rajakavitha1** [comment]
checked the updates on: https://deploy-preview-12868--kubernetes-io-master-staging.netlify.com/docs/setup/independent/troubleshooting-kubeadm/

/approve

**Comment by hpandeycodeit** [comment]
@Rajakavitha1 thank you! :)

**Comment by lledru** [comment]
thanks :)

**Comment by hpandeycodeit** [comment]
thanks @lledru :)

**Pull request merged**
