### PR TITLE
Fix visibility of "Learn Kubernetes Basics" button on homepage

### LINKED ISSUE #43396: Learn Kubernetes Basics button difficult to read when hovered
**This is a Bug Report**

**Problem:** On the home page of website I found that the Learn Kubernetes Basics button needs to be edited as when we hover upon it the words are not clearly visible.

**Proposed Solution:** We can make this button same as the buttons in other pages of the website like for example, under the documentation tab we have View Concepts and View Tutorial buttons.

**Page to Update:**
https://kubernetes.io/

I would like to work upon this issue if you assign it to me. Thankyou.

### PR DESCRIPTION
**Pull request by Gauravpadam**
Closes #43396

Changed the link into a button, Now our asset classes apply on it

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for the fix!
/lgtm

[Deploy Preview Homepage](https://deploy-preview-43969--kubernetes-io-main-staging.netlify.app) | [Current Website Homepage](https://kubernetes.io/)

**Comment by dipesh-rawat** [comment]
/retitle Fix visibility of "Learn Kubernetes Basics" button on homepage

**Review by kumarankit999 — APPROVED** [review]
/lgtm to me

**Review by divya-mohan0209 — APPROVED** [review]
/approve

**Pull request merged**
