### PR TITLE
Fix #16806 - Update link for patch release manager in in skew support policy.

### LINKED ISSUE #16806: Issue with k8s.io/docs/setup/release/version-skew-policy/
**This is a Bug Report**

**Problem:** Broken link in 3rd paragraph, "This decision is owned by the patch release manager." where link, `patch release manager` results in 404.

**Proposed Solution:** Resolve link location.

**Page to Update:**
https://kubernetes.io/docs/setup/release/version-skew-policy/

### PR DESCRIPTION
**Pull request by miteshskj**
fixes #16806

### CODE REVIEW

**Comment by miteshskj** [comment]
thanks for the review/comment @sftim 
Is the responsibility now with the "Release Managers" as explained [here](https://github.com/kubernetes/sig-release/tree/master/release-team#retired-release-team-roles) or its the "Patch release team" as explained [here](https://github.com/kubernetes/sig-release/blob/master/release-managers.md#patch-release-team).?
I will update the wording and link accordingly.

**Comment by sftim** [comment]
> Is the responsibility now with the "Release Managers" as explained here or its the "Patch release team" as explained here.?

Sorry @miteshskj: 🤷
I don't know which of those options is correct.

**Comment by sftim** [comment]
Maybe someone on [Kubernetes Slack](https://kubernetes.slack.com/) will know how to resolve the mismatch?

**Comment by zparnold** [comment]
/lgtm
/approve
@miteshskj Please let us know if you're able to address @sftim 's concerns

**Comment by miteshskj** [comment]
Thanks @zparnold @sftim - Confirmed from the sig-release channel on slack. I will send another PR to fix the text.

**Pull request merged**
