### PR TITLE
add a link to CCM

### PR DESCRIPTION
**Pull request by syswuheng**
Only Oracle has a link to find the implemented CCM source code.

We add a link to any other implemented CCMs

- Digital Ocean
- AWS
- GCE
- Azure

### CODE REVIEW

**Comment by DStorck** [comment]
@syswuheng please sign the CLA

**Comment by syswuheng** [comment]
@DStorck Thanks

**Comment by Rajakavitha1** [comment]
@syswuheng Thanks for the fix.
/lgtm

**Pull request merged**
