### PR TITLE
Remove GA ServiceNodePortStaticSubrange feature gate

### PR DESCRIPTION
**Pull request by xuzhenglun**
This PR remove GA feature gate ServiceNodePortStaticSubrange

code remove in k/k: https://github.com/kubernetes/kubernetes/pull/124738

KEP: https://github.com/kubernetes/enhancements/issues/3668

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/hold

Please only update the `en` localization for changes to this branch.

(The release docs team only work in English.)

OK to unhold once this PR doesn't include any Chinese / other localization changes.

**Comment by xuzhenglun** [comment]
PR to remove the feature gate has been merged. furthermore, this PR does not include other localization any more. 

/unhold

**Review by mengjiao-liu — COMMENTED** [review]
The description of the status of this feature on this page  https://kubernetes.io/docs/concepts/services-networking/service/#avoid-nodeport-collisions should also be removed.

**Comment by xuzhenglun** [comment]
@mengjiao-liu

> The description of the status of this feature on this page https://kubernetes.io/docs/concepts/services-networking/service/#avoid-nodeport-collisions should also be removed.

Thanks for reminding, It has been addressed now.

**Pull request merged**
