### PR TITLE
generate kubectl command reference (1.23)

### PR DESCRIPTION
**Pull request by kbhawkey**
Built kubectl command reference (testing v1.23)

### CODE REVIEW

**Comment by sftim** [comment]
@kbhawkey:
/hold

this should target the v1.23 branch _I think_

**Comment by reylejano** [comment]
Thank you @kbhawkey for testing this
cc @jlbutler

**Comment by jlbutler** [comment]
@kbhawkey thanks for this! can you rebase to `dev-1.23`?

**Comment by kbhawkey** [comment]
Hi @jlbutler .
I reran the kubectl reference build in an environment that includes k8s v1.23.0-rc.1 and the dev-1.23 branch in website.
I did not generate any files from the build. I used Go 1.17. I suggest to build with the GA or release version of k8s to confirm if there are any kubectl updates to document. I assume the cmd reference go.mod file should be updated.
I think that I generated the change in this PR using Go 1.16.

**Comment by jlbutler** [comment]
@kbhawkey ah I understand. Ok as we planned, I'll try a build once the release is cut and see if we have a different outcome. I have stumbled on a few dependency issues. Once we have a release tag, we can triage further. Thanks again!

**Comment by sftim** [comment]
/hold cancel

v1.23 is out

**Comment by kbhawkey** [comment]
Hi. I built the kubectl command reference yesterday (a second time) and added the files to PR https://github.com/kubernetes/website/pull/30799. I will build again and add the generated kubectl command reference files to a new PR.

**Pull request closed without merging**
