### PR TITLE
Update dead Link to Docker EE Installation

### PR DESCRIPTION
**Pull request by eyenx**
Link to official documentation. Mirantis Link is dead (404)

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
hi, we had the same PR here, but the contributor did not sign the CLA.
https://github.com/kubernetes/website/pull/21862

the new link looks valid.
/lgtm
/sig cluster-lifecycle

**Comment by eyenx** [comment]
> hi, we had the same PR here, but the contributor did not sign the CLA.
> #21862
> 
> the new link looks valid.
> /lgtm
> /sig cluster-lifecycle

FYI I tested it with windows OSVersion 1809. I was able to install Docker through that link and afterwards `kubeadm join` worked.

**Review by sftim — COMMENTED** [review]
/sig windows
/approve

**Pull request merged**
