### PR TITLE
[zh] service-network: add some clarity to headless service

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/26446

### CODE REVIEW

**Comment by tengqm** [comment]
Output from `./scripts/lsync.sh content/zh/docs/concepts/services-networking/service.md` shows that the upstream file has other changes to sync.

**Comment by Arhell** [comment]
> ./scripts/lsync.sh content/zh/docs/concepts/services-networking/service.md

Checked, writes
`content/zh/docs/concepts/services-networking/service.md is still in sync
` in this branch

**Comment by tengqm** [comment]
@Arhell Maybe you were running this command under the `service` branch? How about running in under the `master` branch and check it again?

**Comment by Arhell** [comment]
You are right, looked, thanks

**Pull request closed without merging**
