### PR TITLE
[hi] Add content/hi/releases/_index.md

### PR DESCRIPTION
**Pull request by AvineshTripathi**

### CODE REVIEW

**Comment by anubha-v-ardhan** [comment]
Resolves #31273

**Review by jayesh-srivastava — CHANGES_REQUESTED** [review]
The word `रिलीज` is wrongly written, should actually be `रिलीज़`. Please do the needful wherever applicable.

**Comment by AvineshTripathi** [comment]
@jayesh-srivastava thanks I missed that

**Comment by anubha-v-ardhan** [comment]
Thank you @AvineshTripathi :)

**Pull request merged**
