### PR TITLE
[fr] translate task run-application/horizontal-pod-autoscale-walkthrough.md

### PR DESCRIPTION
**Pull request by k0rventen**
Hi,

This adds the French translation for the task 'HorizontalPodAutoscaler Walkthrough', from the "Run Applications" section. This is the [reference document](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/).

I also added the missing example file for the task.

### CODE REVIEW

**Review by perriea — APPROVED** [review]

**Comment by k0rventen** [comment]
Hey @perriea , I just realised that one of the glossary reference (quantity at the very end of the page) isn't translated in French. I pushed the translation to the same branch but as it's already merged, how should I proceed ? Do I open a new PR just for this change ?

**Comment by perriea** [comment]
@k0rventen open a new PR and assign me :)

**Comment by perriea** [comment]
> opened #41911 but I don't have the permission to assign it. Thx !

@k0rventen if you want assign, type this command `/assign <user>`
https://prow.k8s.io/command-help?repo=kubernetes%2Fwebsite

**Comment by k0rventen** [comment]
> > opened #41911 but I don't have the permission to assign it. Thx !
> 
> @k0rventen if you want assign, type this command `/assign <user>` https://prow.k8s.io/command-help?repo=kubernetes%2Fwebsite

Wasn't aware of such command, thx for the tip !

**Pull request merged**
