### PR TITLE
document plugin resolution as subcommand for builtin commands

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR adds document for the alpha stage of https://github.com/kubernetes/enhancements/issues/3638

### CODE REVIEW

**Comment by ardaguclu** [comment]
> I think `content/en/docs/reference/kubectl/kubectl.md` is automatically generated; if that's right, then you don't need to send in this change. However, if there's no other documentation, will people know that they could try using it?

Thanks @sftim. Shouldn't I add this new environment variable into somewhere to feed this auto generated page content/en/docs/reference/kubectl/kubectl.md?

**Comment by LukeMwila** [comment]
Hey @sftim @ardaguclu, just following up on the changes to `content/en/docs/reference/kubectl/kubectl.md`. This docs PRs have to be merged by end of today.

**Comment by ardaguclu** [comment]
I mimicked the same place in this PR https://github.com/kubernetes/website/pull/37788. If there is any other place should be added, I gladly can add there.

**Comment by LukeMwila** [comment]
> > Hey @sftim @ardaguclu, just following up on the changes to `content/en/docs/reference/kubectl/kubectl.md`. The docs PRs have to be merged by end of today.
> 
> I checked https://github.com/kubernetes/sig-release/tree/master/releases/release-1.27 The docs PRs have to be ready to merge today. Merges should be done by the start of the 10th of April.
> 
> I don't know whether SIG Docs has capacity to get all the pending 1.27 PRs reviewed today. My guess is no.

Thanks for the response @sftim, and sorry or the confusion. I meant ready to merge.

**Comment by LukeMwila** [comment]
> I mimicked the same place in this PR #37788. If there is any other place should be added, I gladly can add there.

I had a look at the previous PR that you referred to. Thanks.

**Comment by reylejano** [comment]
This will be overwritten when the kubectl reference docs are generated

**Comment by divya-mohan0209** [comment]
I'm happy to lgtm this change so that this is reflected in the 1.27 change log. However, this will be overwritten during the reference doc generation & I'd advise @ardaguclu to refer to [this page](https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/) for amending the correct files & getting the relevant changes reflected.

/lgtm

**Comment by divya-mohan0209** [comment]
@sftim / @reylejano / @tengqm  : Please advise if the information I've supplemented wrt the guide is incorrect.

**Comment by tengqm** [comment]
/approve

The auto-generated contents is here: static/docs/reference/generated/kubectl/

**Pull request merged**
