### PR TITLE
[pt] Updated resources of README.md

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/43043/files
/assign @stormqueen1990

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The proposed changes looks good when compared to the modifications in the English PR.  Deferring "lgtm" to Portuguese reviewers, allowing them to perform their formal review and move forward with the merge.

**Review by stormqueen1990 — APPROVED** [review]
/lgtm

@dipesh-rawat if you have root approval permissions please feel free to approve.

**Comment by sftim** [comment]
Portuguese localization team: you should add an `/approve` comment to this to record your approval of the change. That's an unambiguous signal to the website approvers that this has signoff (and by whom).

**Comment by sftim** [comment]
@stormqueen1990 pointed out on Slack that https://github.com/kubernetes/website/pull/43378#pullrequestreview-1664939948 was an approving review (using GitHub's API approval, not Prow).

/approve

**Pull request merged**
