### PR TITLE
Add template for tool reference docs

### PR DESCRIPTION
**Pull request by kbhawkey**
- provide a template for generating tool reference docs.
- use in reference-docs/gen-compdocs/generators to create
  consist looking markdown files for the tools.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Preview test page:
https://deploy-preview-11618--kubernetes-io-master-staging.netlify.com/docs/reference/kubectl/kubectl-test-page/

**Comment by kbhawkey** [comment]
@tengqm, @jimangel. If you have time, would you mind giving the template a quick read. I did a bit of testing in the incubator reference-docs repo to generate the component docs using a mock template from the website docs repo. The tool-reference template could be used in the docs generator golang code to create a standard look-and-feel for the component tool documentation and should be flexible to create all tool documentation. The kubelet-test markdown file would be deleted before merging, or moved to a test area in this repo or in the incubator reference-docs repo. This file is just an example of the rendered output. Let me know what you think. Thanks.

**Comment by tengqm** [comment]
@kbhawkey What are the suggested changes? Could you be more specific?

**Comment by kbhawkey** [comment]
> 
> 
> @kbhawkey What are the suggested changes? Could you be more specific?
This template would help to unify the rendered tool reference docs. I updated the generator code in the incubator reference-docs repo as well.

**Comment by tengqm** [comment]
@kbhawkey Thanks for the clarification.
/lgtm

**Pull request merged**
