### PR TITLE
Fix oldMinorVersion in version-skew-policy.md

### PR DESCRIPTION
**Pull request by mahmut-Abi**
Fix oldMinorVersion in version-skew-policy.md

### CODE REVIEW

**Comment by mahmut-Abi** [comment]
/retitle [zh-cn] Fix oldMinorVersion in version-skew-policy.md

**Review by Sea-n — COMMENTED** [review]
Looks good to me, thanks for your contribution! 🎉
/lgtm

It's your own PR, next time you could just edit the title via GitHub web interface.

**Comment by mahmut-Abi** [comment]
thanks

**Pull request merged**
