### PR TITLE
Update service.md

### PR DESCRIPTION
**Pull request by stephanwesten**
I like 'producer' and 'consumer' more than 'back-end' and 'front-end' - especially for a server-side applications. I associate front-end with a user-interface. I see that the changes are pretty invasive and that is why I stopped at ±75%.

> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6861)

### CODE REVIEW

**Comment by stephanwesten** [comment]
The proposed change is not complete, but see if you like the direction.

**Comment by heckj** [comment]
@stephanwesten I'm good with the language updates - since you mentioned you were still working on this in a previous commit, I put a "hold/wip" tag on the content, let me know when you're ready for a review and potential merge. the PR now does need a rebase as well.

**Comment by heckj** [comment]
Also please sign the CLA (if you haven't already) so that we can accept the changes

**Comment by zacharysarah** [comment]
👋 We've migrated the site's framework to Hugo. Please re-open this PR with changes to files in their post-migration location (`/content/en/docs/...`).

**Pull request closed without merging**
