### PR TITLE
[hi] Ensure seccomp starts with small letter

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/43209/files

### CODE REVIEW

**Review by kundan2707 — COMMENTED** [review]
seccomp is standerd short for secure computing mode so it should be in lower case.

**Review by kundan2707 — COMMENTED** [review]
/lgtm
thanks

**Review by kumarankit999 — COMMENTED** [review]
Thanks for your Contribution @Arhell! It Look's Nice, But I don't think it can add much value to us, Can you reference the issue related to this!

**Comment by divya-mohan0209** [comment]
Hello @arhell, could you advise if this change has been made across the English & other localization websites, as well?
/hold

**Comment by Arhell** [comment]
This is a small synchronization, look at my contributions, they are like that.
en https://github.com/kubernetes/website/pull/43209
ja https://github.com/kubernetes/website/pull/43940
ru https://github.com/kubernetes/website/pull/43972
pl https://github.com/kubernetes/website/pull/43959

and others https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Aarhell+is%3Aclosed

**Review by divya-mohan0209 — COMMENTED** [review]
Thank you for the reference PRs, @Arhell !
/hold cancel
/approve

**Pull request merged**
