### PR TITLE
DNS subdomain translation corrected

### PR DESCRIPTION
**Pull request by sushil97**
Hello!
Part of #24389 
I have changed the korean translation of DNS subdomain from **DNS 하위 도메인** to **DNS 서브도메인** in the docs mentioned. 
Please review and let me know what you think

### CODE REVIEW

**Review by pjhwa — COMMENTED** [review]
@sushil97 Thank you for your contribution!

/lgtm

**Comment by seokho-son** [comment]
@sushil97 Thank you !!
/approve

**Pull request merged**
