### PR TITLE
Update 1.18 config.toml for release 1.20

### PR DESCRIPTION
**Pull request by annajung**
Updated config.toml for release v1.20
Versions were updated based on [latest patch releases](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md)

/hold until 1.20 release day

### CODE REVIEW

**Review by savitharaghunathan — COMMENTED** [review]
lgtm 

will leave the actual `/lgtm` for sig-docs leads

**Comment by kbhawkey** [comment]
Thanks @annajung 
/lgtm

**Comment by irvifa** [comment]
Related PR https://github.com/kubernetes/org/pull/2364 and https://github.com/kubernetes/sig-release/pull/1354

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
