### PR TITLE
Update extend-api-custom-resource-definitions.md

### PR DESCRIPTION
**Pull request by ningning54321**
update it for v1.10:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#customresourcedefinition-v1beta1-apiextensions-k8s-io

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by ningning54321** [comment]
signed the CLA

**Comment by zhangxiaoyu-zidif** [comment]
in fact this url is valid only for v1.10, so I think it could be changed to a absolute path(v1.10 directly)

**Comment by ningning54321** [comment]
@zhangxiaoyu-zidif I haven't gotten chance to check the work flow of the version update of k8s website. In case the next version (e.g. 1.11) will be cloned from this one, it will be handy to keep the template code.

**Comment by nikhita** [comment]
>  it could be changed to a absolute path(v1.10 directly)

IIUC if we use the template, when 1.11 will be released, it will point to the 1.11 CRD reference automatically. If we use the absolute path, I think we will need to change the url for every release.

> in fact this url is valid only for v1.10

I think this url will be valid for future versions as well. Until of course, CRD goes from beta to GA. :)

/assign @steveperry-53 
to confirm the above and for approval

**Pull request merged**
