### PR TITLE
WIP: [pt-br] Add docs/setup/production-environment/container-runtimes.md

### PR DESCRIPTION
**Pull request by xcirel**

### CODE REVIEW

**Comment by jihoon-seo** [comment]
/retitle WIP: [pt-br] Translate 'Container Runtimes'
Many parts are not translated yet.

/label tide/merge-method-squash

**Comment by MrErlison** [comment]
Hello @santoseric!  Thanks for your contribution! 

If you need help, please don't hesitate to ask us in Portuguese slack channel #kubernetes-doc-pt

**Comment by stormqueen1990** [comment]
Hello there, @santoseric! 👋 

Thanks for your contribution! 🎉 

Unfortunately, we cannot accept partially translated content. Would you feel comfortable finishing this translation so we can start reviewing and then move your contribution forward?

If you need any help, please don't hesitate to reach out to us on Kubernetes Slack, as @MrErlison mentioned.

**Comment by stormqueen1990** [comment]
/retitle [pt-br] Add docs/setup/production-environment/container-runtimes.md

**Comment by stormqueen1990** [comment]
/retitle [pt-br] WIP: Add docs/setup/production-environment/container-runtimes.md

**Comment by stormqueen1990** [comment]
/retitle WIP: [pt-br] Add docs/setup/production-environment/container-runtimes.md

**Comment by stormqueen1990** [comment]
Hello there, @xcirel! :wave: 

Thank you very much for your work on this PR. However, it has been open and reviewed for a while with no action taken. For this reason, I will be closing this PR. If you wish to continue your work on this, please feel free to reopen it.

Should you have any questions, please don't hesitate to reach out to the `#kubernetes-docs-pt` channel in Kubernetes Slack.

---

Olá, @xcirel! :wave:

Obrigada pelo teu trabalho neste PR. Devido a inatividade após a revisão, irei fechá-lo. No entanto, caso desejes continuar teu trabalho, podes reabrir o PR a qualquer momento.

Se tiveres dúvidas, não hesita em contatar-nos através do canal `#kubernetes-docs-pt` no Slack do Kubernetes.

/close

**Pull request closed without merging**
