### PR TITLE
[id] Fix configuration overview example link

### PR DESCRIPTION
**Pull request by championshuttler**
Fix configuration overview example link

### CODE REVIEW

**Review by habibrosyad — COMMENTED** [review]
@championshuttler I just noticed that #29311 hardcoded `master` as replacement for `{{< param "githubbranch" >}}`. Could you update line 67 of this file as well, as it is also need to be updated accordingly?

Fyi, this not ES but ID localization.

**Review by ariscahyadi — COMMENTED** [review]
ok.

**Pull request merged**
