### PR TITLE
Remove unnecessary paragraph

### PR DESCRIPTION
**Pull request by tddorgtfo**
Fixes issue #15027

### CODE REVIEW

**Comment by sftim** [comment]
I'm going to unassign myself from this one (I don't have strong views on what the fix should be, BTW).
/unassign

**Comment by kbarnard10** [comment]
@tddorgtfo Can you update the wording based on the additional discussion in #15027?

**Comment by tddorgtfo** [comment]
@kbarnard10 Revised as per discussion

**Comment by poothia** [comment]
lgtm

**Pull request merged**
