### PR TITLE
Placeholder PR for KEP-4265

### PR DESCRIPTION
**Pull request by sohankunkerkar**

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@sohankunkerkar We should consider setting the **`dev-1.31`** branch as the target branch rather than the _main_ branch for this pull request. Since the change is related to the feature targeting beta in 1.31.

**Comment by hacktivist123** [comment]
Hello @sohankunkerkar  :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday, July 16th, 2024 18:00 PST. Thank you!

**Comment by Princesso** [comment]
Hi @sohankunkerkar, a gentle reminder that tomorrow is the deadline for having your Docs PR ready for review. Please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before tomorrow, Tuesday, July 16th, 2024 18:00 PST.

**Comment by sohankunkerkar** [comment]
I'm closing this PR as the docs for this feature are already up-to-date.

**Pull request closed without merging**
