### PR TITLE
Bringing I18n branch up-to-date with master branch.

### PR DESCRIPTION
**Pull request by anvithks**
Updating the i18n branch.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7254)

### CODE REVIEW

**Comment by dhilipkumars** [comment]
@chenopis As you remember this is just a dev branch for multi-lingual support. Anvith wants to merge this to i18n branch.  
/lgtm from me
/approve

**Comment by chenopis** [comment]
@anvithks I'm not sure why the CLA check is not passing. It says you are authorized, but it doesn't say what the problem is. Do you know if there are any commits in this PR from people who are not CLA authorized?

Would it be possible for you to rebase so we only see your commits, not all the other ones from `master`?

**Comment by anvithks** [comment]
@chenopis Thank you.

**Pull request merged**
