### PR TITLE
[ko] Translate docs/home/supported-doc-versions documentation.

### PR DESCRIPTION
**Pull request by anubha-v-ardhan**
Translated `This website contains documentation for the current version of Kubernetes and the four previous versions of Kubernetes.` of https://github.com/kubernetes/website/blob/dev-1.21-ko.5/content/en/docs/home/supported-doc-versions.md in Korean which was missing earlier.

Issue -> https://github.com/kubernetes/website/issues/28512

### CODE REVIEW

**Comment by yoonian** [comment]
@anubha-v-ardhan thank you for your contribution
/lgtm
/assign @seokho-son check it please.

**Comment by seokho-son** [comment]
/unassign @ysyukr 
@anubha-v-ardhan Contributors don't need to assign reviewer :) We have a PR wrangler system ;)

**Comment by anubha-v-ardhan** [comment]
> /unassign @ysyukr
> @anubha-v-ardhan Contributors don't need to assign reviewer :) We have a PR wrangler system ;)

oh! okay, thanks

**Comment by tengqm** [comment]
> Contributors don't need to assign reviewer

Yes, they don't need to but they are allowed to.

**Comment by seokho-son** [comment]
@anubha-v-ardhan Thank you for the contribution ~ !
/approve

**Pull request merged**
