### PR TITLE
翻译Kubernetes-On-Aws_15博客

### PR DESCRIPTION
**Pull request by chenrui333**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

### CODE REVIEW

**Comment by chenrui333** [comment]
signed CLA

**Comment by zhangxiaoyu-zidif** [comment]
Hi, we have a repo for CN-translation, https://github.com/kubernetes/kubernetes-docs-zh
you can send PR there. And we will sync it here.
Thanks for you work

**Comment by chenrui333** [comment]
@zhangxiaoyu-zidif sounds good, thanks!

**Comment by chenrui333** [comment]
@zhangxiaoyu-zidif can you show me one of the PR reference in that repo, I can re-structure this PR for review over there (like directory layout or something and keeping the english original script). Thanks!

**Comment by zhangxiaoyu-zidif** [comment]
@chenrui333 you can send this PR here. Sorry. :)  https://github.com/kubernetes/kubernetes-docs-zh will not be maintained ever I heard  yesterday.

**Comment by chenrui333** [comment]
not a problem! good to hear. 😄

**Comment by zacharysarah** [comment]
https://github.com/kubernetes/kubernetes-docs-zh is actively maintained and is where Chinese translation PRs should go. Closing this PR.

**Pull request closed without merging**
