### PR TITLE
Update API reference to contain API group and versino info

### PR DESCRIPTION
**Pull request by tengqm**
The updated reference is generated using the https://github.com/kubernetes-sigs/reference-docs/pull/172 change.

Related: #2979

Follow up PRs needed to add reference to the API groups section where appropriate.

### CODE REVIEW

**Comment by tengqm** [comment]
Preview link: https://deploy-preview-24635--kubernetes-io-master-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.19/#-strong-api-groups-strong-

**Comment by kbhawkey** [comment]
Hi @tengqm .
This pull request updates the v1.19 API reference by adding an API groups table.
The changes look good.
/approve

**Pull request merged**
