### PR TITLE
Update pod-priority-preemption.md

### PR DESCRIPTION
**Pull request by penance-zh**

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@penance-zh Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by windsonsea** [comment]
This will be closed due to failed CLA check for a long time. Feel free to re-open it when you have CLA signed, thanks.

/close

**Pull request closed without merging**
