### PR TITLE
[ko] update cert-manager docs link

### PR DESCRIPTION
**Pull request by SgtCoDFish**
안녕하세요! This is the Korean version of #30432 (split into a separate PR following the example of #28753 which was a similarly simple change).

/language ko

### CODE REVIEW

**Comment by jmyung** [comment]
/lgtm

@SgtCoDFish 
기여 감사드립니다.

en 문서도 동일한 오류가 있으므로, en 문서에 upstream 기여도 같이 진행해주시면 좋을 것 같습니다.  😄

**Comment by seokho-son** [comment]
@SgtCoDFish Thank your for the contribution !! LGTM too.

Let me approve this PR after upstream (English) PR #30432 is merged :)

**Pull request merged**
