### PR TITLE
Move files out of old user-guide directory.

### PR DESCRIPTION
**Pull request by steveperry-53**
This PR moves some YAML configuration files out of the old user-guide directory and into the newer concepts/cluster-administration directory.

This PR also updates the topic that uses these YAML files:  [Managing Resources](https://deploy-preview-7384--kubernetes-io-master-staging.netlify.com/docs/concepts/cluster-administration/manage-deployment/).

The Managing Resources topic also needs and edit pass for style, but that is not a goal of this PR.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7384)

### CODE REVIEW

**Comment by heckj** [comment]
@steveperry-53 this one also appears to be failing on the go-based validation tests - guessing related to the update you were making at https://github.com/kubernetes/website/pull/7405 ...

**Comment by steveperry-53** [comment]
Eventually, in examples_test.go, we need to add apps.Deployment.

**Pull request merged**
