### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by jaekel**
Added k8s offerings by Ionos Enterprise Cloud.

### CODE REVIEW

**Comment by jaekel** [comment]
I signed it

**Comment by kbhawkey** [comment]
hello @jaekel . Thanks for the PR.
Page preview:
https://deploy-preview-15494--kubernetes-io-master-staging.netlify.com/docs/setup/
It would be great to list the English version of the `Managed Kubernetes` site:
`https://www.ionos.de/enterprise-cloud/managed-kubernetes`. Would this be possible?

**Comment by jaekel** [comment]
Hello @kbhawkey.

> It would be great to list the English version of the `Managed Kubernetes` site:
> `https://www.ionos.de/enterprise-cloud/managed-kubernetes`. Would this be possible?

Sure! But I am confused: list it where? What should I do?

**Comment by sftim** [comment]
If you hyperlink to https://www.ionos.co.uk/enterprise-cloud/managed-kubernetes instead of to https://www.ionos.de/enterprise-cloud/managed-kubernetes then that is a page in English rather than in German.
The two pages are not equivalent but I can see why it's useful to link to the English language page.

**Comment by jaekel** [comment]
Is this better?

I changed it to ionos.com instead of ionos.de. I believe that should honor the browser language preference and default to English.

**Pull request merged**
