### PR TITLE
Add Nate Waddington as an approver for docs

### PR DESCRIPTION
**Pull request by natalisucks**
As Nate is a blog approver and will now be doing PR Wrangling, he needs to be added to our approver list to unlock this work.

Congratulations, Nate! 🎉 

@reylejano @sftim @divya-mohan0209

### CODE REVIEW

**Comment by sftim** [comment]
I'm not sure if I understand the logic here (blog approvers don't need to be website approvers), but I am nonetheless happy to see Nate become an approver for the English localization.

**Comment by nate-double-u** [comment]
Thanks! (love that the bot asked me to review 😅)

**Comment by natalisucks** [comment]
@sftim Apologies Tim, this information was provided additionally on top of Nate having shadowed PR Wrangling for a while, in terms of further strengthening his growth to approver (as opposed to this being the reason). Great to hear this has your support!

**Comment by nate-double-u** [comment]
The chat that @reylejano and I had about PR https://github.com/kubernetes/website/pull/37152 was to add me as an approver, not only a reviewer. This PR corrects that and allows me to `/approve` and be on the wrangling team 🙂

**Pull request merged**
