### PR TITLE
Update to sync latest release of the Kompose version from 1.21.0 to 1.22.0

### PR DESCRIPTION
**Pull request by paranlee**
DESCRIPTION

Hello, i am paran lee.

I check new release of Kompose program.

this pull request is about

update to sync latest release of the Kompose version from 1.21.0 to 1.22.0

https://github.com/kubernetes/kompose/releases

Thank you.

### CODE REVIEW

**Comment by irvifa** [comment]
Hey @paranlee could you please sign the CLA first?

**Comment by paranlee** [comment]
> Hey @paranlee could you please sign the CLA first?

acknowledge, thank you!

**Review by irvifa — COMMENTED** [review]
/lgtm

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
