### PR TITLE
Fix a typo in the configmap concept page

### PR DESCRIPTION
**Pull request by tengqm**

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The change made here looks appropriate.

/lgtm

**Review by Pradumnasaraf — APPROVED** [review]
The changes look good.

/lgtm

**Review by dipesh-rawat — COMMENTED** [review]
Deploy Preview: [deploy-preview-40907-configmap](https://deploy-preview-40907--kubernetes-io-main-staging.netlify.app/docs/concepts/configuration/configmap/)

/lgtm

**Review by Pradumnasaraf — APPROVED** [review]
/lgtm

**Pull request merged**
