### PR TITLE
Fix search input overlapping site nav

### LINKED ISSUE #26269: Search page rendering incorrectly
**This is a Bug Report**

**Problem:** Navbar prevents search input field from being clicked on

Can reproduce on Firefox, Chrome on latest builds

**Proposed Solution:** Remove navbar from search page

**Page to Update:**
https://kubernetes.io/search/
Screenshot 2021-01-28 110732

### PR DESCRIPTION
**Pull request by notchairmk**
Implements header filler class from docs search page. Removes broken docs-specific button site search input.

Fixes #26269

### CODE REVIEW

**Comment by kbhawkey** [comment]
Thanks @notchairmk .

Page preview:
https://deploy-preview-26278--kubernetes-io-master-staging.netlify.app/search/
https://deploy-preview-26278--kubernetes-io-master-staging.netlify.app/search/?q=kubectl

/kind cleanup

**Review by onlydole — APPROVED** [review]
LGTM ✨ thank you @notchairmk and @kbhawkey

**Pull request merged**
