### PR TITLE
Add translation for ReplicaSet in ID localization

### PR DESCRIPTION
**Pull request by joshuabezaleel**
This address #15341

### CODE REVIEW

**Comment by joshuabezaleel** [comment]
Should be okay for now. Looking forward to your review! :slightly_smiling_face: 
@irvifa @girikuncoro

**Comment by irvifa** [comment]
Nice work.. thanks..
/lgtm
/approve

**Comment by irvifa** [comment]
Nice work.. thanks..
/lgtm
/approve

**Pull request merged**
