### PR TITLE
Avoid confusion between TLS encryption and TLS authentication in flags description

### PR DESCRIPTION
**Pull request by ikarlashov**
Hi,

I found out that current description of some flags could bring confusion for k8s newbies. Confirmed confusion with my colleague as well.

### CODE REVIEW

**Comment by jimangel** [comment]
@tengqm @kbhawkey is this page also not auto-generated? If not feel free to approve...
/lgtm

**Comment by kbhawkey** [comment]
Hello @ikarlashov .
Thanks for opening this pull request.
This reference page is auto-generated.
To update the text found on this page, you should open a pull request in 
https://github.com/kubernetes/kubernetes.
Thanks!

**Pull request closed without merging**
