### PR TITLE
Fixed Markdown syntax error in list

### PR DESCRIPTION
**Pull request by dsbos**
Can someone verify that my correction is correct? (I don't know how to view the rendered form of the Markdown.)

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hello @dsbos .
You can run the Hugo server locally to verify your changes.
See the Kubernetes docs project README,
https://github.com/kubernetes/website/#running-the-website-locally-using-hugo

Page preview:
https://deploy-preview-20651--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/monitoring/

**Comment by RainbowMango** [comment]
/lgtm
Thanks @dsbos !

**Pull request merged**
