### PR TITLE
Prepare for v1.21 + indentation + local common definitions

### PR DESCRIPTION
**Pull request by feloy**
Preview at https://deploy-preview-26413--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/

- Prepares the API Reference documentation for v1.21

- Moves some Definitions from Common Definitions page to specific page (ex Handler, NodeAffinity, etc moved to Pod page).

- Enables deep indentation for nested fields.

Pages generated by https://github.com/kubernetes-sigs/reference-docs/pull/207

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @feloy . I am looking at the generated pages (and will read through the source changes). Some feedback:
- I think it is a good idea to reference an issue for any medium-sized changes (relocation of definitions).
- Can you point me to a page that displays the new indentations for nested fields?
- Should these changes merge into the `dev-1.21` branch just before the release date? Or do you want these changes to go in now?
- Should the links to the original object definitions redirect from the "Common Definitions" page to an individual resource page?

A couple of page previews:
https://deploy-preview-26413--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/workloads-resources/pod-v1/#NodeAffinity

https://deploy-preview-26413--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/workloads-resources/pod-v1/#Handler

**Comment by feloy** [comment]
> Hi @feloy . I am looking at the generated pages (and will read through the source changes). Some feedback:
> 
> * I think it is a good idea to reference an issue for any medium-sized changes (relocation of definitions).
> * Should these changes merge into the `dev-1.21` branch just before the release date? Or do you want these changes to go in now (master branch)?

I'm not sure of the implications. My idea is to wait for the definitive swagger definition of v1.21 before to merge this PR. The definitive swagger won't come before the Release Candidates.


> * Should the links to the original object definitions redirect from the "Common Definitions" page to an individual resource page?

Do you mean making redirections so links created in the actual pages are not broken when this PR is merged? As the pages are not crawled by robots, do you think it is necessary?


> 
> A couple of page previews:
> https://deploy-preview-26413--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/workloads-resources/pod-v1/#NodeAffinity
> 
> https://deploy-preview-26413--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/workloads-resources/pod-v1/#Handler
> 
> Related to issue #25505.

**Comment by kbhawkey** [comment]
Re: Do you mean making redirections so links created in the actual pages are not broken when this PR is merged? As the pages are not crawled by robots, do you think it is necessary?

-OK. That seems correct.

**Comment by feloy** [comment]
New version of the reference reflecting the changes in v1.21-beta.0
- CronJob v2alpha1 removed

**Comment by kbhawkey** [comment]
Hi @feloy .
What do you think about publishing these changes to the dev-1.21 branch?
You could use the latest release candidate of the spec and then update the files after the release if needed?
That way, this documentation is included in the 1.21 reference documentation set.
What do you think?

**Comment by feloy** [comment]
Hi @kbhawkey . I have based the PR on the dev-1.21 branch.

I'll watch if there are any changes to the spec after the docs release.

**Comment by reylejano** [comment]
Hi @feloy, are the steps documented to prepare the API Reference documentation for 1.21?
Should this process be included in future release cycles and conducted by the release docs team?
We can add the steps to prepare the API Reference documentation in the [release docs role handbook](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md)

**Comment by feloy** [comment]
Hi @reylejano 

The process to prepare the API reference doc has been briefly described in the README.md file of this k/website repository (https://github.com/kubernetes/website/blob/master/README.md#building-the-api-reference-pages) and in the README of the generator (https://github.com/kubernetes-sigs/reference-docs/blob/master/gen-resourcesdocs/README.md).

For the 1.21 release, all the needed work is included in this PR, so I think there is nothing to do more than merging it.

For the next releases, adding more detailed information to the release docs role handbook would be nice.

**Comment by kbhawkey** [comment]
Hi @feloy .
I ran through several resources and common definitions. Looks good.
One thing I noted (Markdown list not rendering):
https://deploy-preview-26413--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#alpha-level

Do you want to keep the separate commits or rebase into one commit?

/lgtm

**Comment by feloy** [comment]
Hi @kbhawkey Thanks for the review. I just squashed my commits

**Comment by irvifa** [comment]
Feel free to unhold when the time comes
/hold

**Comment by feloy** [comment]
Thanks @irvifa 
/hold cancel

**Pull request merged**
