### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by alexcontini**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.9 Features: set Milestone to `1.9` and Base Branch to `release-1.9`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: Please check the “Allow edits from maintainers” box (see image below) to
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.
>
> NOTE: After opening the PR, please *un-check and re-check* the "Allow edits from maintainers" box. This is a temporary workaround to address a known issue with GitHub.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6153)

### CODE REVIEW

**Comment by abiogenesis-now** [comment]
Generally seems reasonable (seems like you're grouping things in `div`s so that you'll be able to hook into them with Javascript), but do you mind responding in a short comment what this change is intended to do?

Once that's done, I'll feel safer merging. Thanks! :)

**Comment by alexcontini** [comment]
Hi! Sorry about that, I didn't mean to commit a couple times.

The intention is to make this page:
https://kubernetes-io-user-journeys.netlify.com/partners/ have the
capability to sort the sections when clicking the corresponding button, "Add
JavaScript so that when a user clicks on "See KCSP Partners" the page only
displays listings for that category. Same with "See Technology Partners"
and "See Services Partners"  was the request. Let me know if there are any
problems!

**Comment by abiogenesis-now** [comment]
OK, that makes sense!

**Comment by abiogenesis-now** [comment]
(Yeah, next time would prefer if the Javascript code was included in the same PR, but this time I'll go ahead and merge)

**Comment by alexcontini** [comment]
Thank you so much!! I appreciate it

**Pull request merged**
