### PR TITLE
Create advanced.md

### PR DESCRIPTION
**Pull request by Sophy417**

### CODE REVIEW

**Comment by tengqm** [comment]
很抱歉，user journey 下面的内容貌似已经废弃。

**Comment by Sophy417** [comment]
> 很抱歉，user journey 下面的内容貌似已经废弃。

那我 直接把这个删除关闭掉就行了，是吧？

**Comment by tengqm** [comment]
Wait, let's see how the SIG sees it.

**Comment by Sophy417** [comment]
> Wait, let's see how the SIG sees it.

OK👌

**Comment by sftim** [comment]
I don't see that there's an upstream page to localize. Is that correct?

**Comment by tengqm** [comment]
Yes, @sftim. Maybe the author was reading an old version of the site.
The advanded.md is still there in the repo, `deprecated/content/en/docs/user-journeys/users/application-developer/advanced.md`

**Comment by kbhawkey** [comment]
Hi. Content in the `deprecated` directory is not published to the site. I would wait to translate the page?
It may be worth tracking the deprecated user journey pages by opening an issue.

**Pull request closed without merging**
