### PR TITLE
Line separation add

### PR DESCRIPTION
**Pull request by rushikeshadhav**
Line separation is added in reference/kubectl/overview.md

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/30551#issuecomment-973051324

**Comment by jihoon-seo** [comment]
- This PR resolves #30357
- This PR is similar with the PR #30359
- This PR is similar with the PR #30425

**Comment by rushikeshadhav** [comment]
CLA signed

**Comment by RA489** [comment]
> CLA signed

/check-cla

**Comment by rushikeshadhav** [comment]
what is original CLA

**Comment by divya-mohan0209** [comment]
Thank you for your efforts! Hello @rushikeshadhav , this has now been fixed by [the PR](https://github.com/kubernetes/website/pull/30359). A good way to ensure there's no duplication of efforts is to assign the issue to yourself or ask the person who has raised the issue to assign it to you.

**Pull request closed without merging**
