### PR TITLE
Update authentication links

### PR DESCRIPTION
**Pull request by mrbobbytables**
This PR works towards #9286 with updating the authentication internal links to what they should be according to the [redirects file](https://github.com/kubernetes/website/blob/master/static/_redirects).

Previous Link: `docs/admin/authentication`
New Link: `docs/reference/access-authn-authz/authentication`

**Note:** 
In one of the docs ([content/en/docs/setup/scratch.md](https://github.com/kubernetes/website/blob/master/content/en/docs/setup/scratch.md)), the content itself has been moved to a different page and I linked to what I could find as the best match:

Old content: 
https://v1-7.docs.kubernetes.io/docs/admin/authentication/#creating-certificates

The best match I could find was the content here:
https://kubernetes.io/docs/concepts/cluster-administration/certificates/

### CODE REVIEW

**Comment by mistyhacks** [comment]
Deploy preview for *kubernetes-io-master-staging* ready!

Built with commit 8c4e2dcd2a683f152d2cb488559a513fe9cca2df

https://deploy-preview-9452--kubernetes-io-master-staging.netlify.com

**Comment by mistyhacks** [comment]
@mrbobbytables do you need to add any redirects? See `/static/_redirects`. Nice GH handle, btw!

**Comment by mrbobbytables** [comment]
@mistyhacks Thanks :) and nope, don't need to update the redirects file. Just going through and trying to clean up the internal links and 404s.

**Pull request merged**
