### PR TITLE
Update debug-cluster.md

### PR DESCRIPTION
**Pull request by jumping**
remove the ":" after "具体情况: " and "缓解措施："

### CODE REVIEW

**Comment by jumping** [comment]
I signed it

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by tengqm** [comment]
@jumping Please check if you are committing the PR using the email you used for CLA. You may want to recommit this PR if not.

**Review by chenrui333 — APPROVED** [review]
/lgtm

**Pull request merged**
