### PR TITLE
Create OWNERS for ar localization

### PR DESCRIPTION
**Pull request by mboukhalfa**
Adding OWNERS to fix the issue with approve for arabic team. 

Slack discussion :  https://kubernetes.slack.com/archives/CP9FKRD51/p1710921248918939

### CODE REVIEW

**Comment by a-mccarthy** [comment]
Thanks for opening this! I think you also need to add `sig-docs-ar-reviews` to the https://github.com/kubernetes/website/blob/dev-1.29-ar.1/OWNERS_ALIASES file. Right now you just have `sig-docs-ar-approvers` in that file but both list `sig-docs-ar-reviews` and `sig-docs-ar-approvers` in ins PR adding content/ar/OWNERS

Are you also willing to be a reviewer for AR? If so, i'd add your name on to the reviews list as well.

**Comment by mboukhalfa** [comment]
> Thanks for opening this! I think you also need to add `sig-docs-ar-reviews` to the https://github.com/kubernetes/website/blob/dev-1.29-ar.1/OWNERS_ALIASES file. Right now you just have `sig-docs-ar-approvers` in that file but both list `sig-docs-ar-reviews` and `sig-docs-ar-approvers` in ins PR adding content/ar/OWNERS
> 
> Are you also willing to be a reviewer for AR? If so, i'd add your name on to the reviews list as well.

done

**Comment by a-mccarthy** [comment]
/lgtm

thanks!

**Pull request merged**
