### PR TITLE
add shortcode to training page

### PR DESCRIPTION
**Pull request by Arhell**
this PR https://github.com/kubernetes/website/pull/24014

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-24924--kubernetes-io-master-staging.netlify.app/ko/training/
/assign @pjhwa

**Comment by pjhwa** [comment]
@Arhell Thank you for your contribution!

/lgtm

**Comment by ianychoi** [comment]
Thank you for your contribution for Korean @Arhell + good review @pjhwa

**Pull request merged**
