### PR TITLE
Merge main into dev-1.25 branch: July 21st

### PR DESCRIPTION
**Pull request by sethmccombs**
This PR syncs the main branch with the dev-1.25 branch.

### CODE REVIEW

**Comment by Sea-n** [comment]
/retitle Merge main into dev-1.25 branch: July 21st

And I think the PR description is not clear. Seems like merge `dev-1.25` into `main` branch.
> This PR syncs the main branch with the dev-1.25 branch.

Maybe this would be better
> This PR syncs the `dev-1.25` branch (with the `main` branch).

**Comment by sethmccombs** [comment]
> /retitle Merge main into dev-1.25 branch: July 21st
> 
> 
> 
> And I think the PR description is not clear. Seems like merge `dev-1.25` into `main` branch.
> 
> > This PR syncs the main branch with the dev-1.25 branch.
> 
> 
> 
> Maybe this would be better
> 
> > This PR syncs the `dev-1.25` branch (with the `main` branch).

Sounds good. I just copied over the description from our last release branch sync PR

**Comment by reylejano** [comment]
I took a look at [5ebea62](https://github.com/kubernetes/website/pull/35229/commits/5ebea6226fe9a450e8a3d72816b01a6583b47760) for an unverified commit signature. It was part of merged PR https://github.com/kubernetes/website/pull/35003 to update the list of release managers. The author of the PR is a SIG Release Tech Lead.
/approve

**Comment by cici37** [comment]
HI just curious if we plan to merge main to dev-1.25, why don't we do https://github.com/kubernetes/website/compare/dev-1.25...main ? Just to avoid confusion on if any personal commit added :)

**Comment by cici37** [comment]
/lgtm
I guess it is for version control on time and potential conflicts? The PR looks good. Thanks

> HI just curious if we plan to merge main to dev-1.25, why don't we do [dev-1.25...main](https://github.com/kubernetes/website/compare/dev-1.25...main) ? Just to avoid confusion on if any personal commit added :)

**Pull request merged**
