### PR TITLE
Removing New Relic CronJob Monitoring content

### PR DESCRIPTION
**Pull request by sNathan13**
This PR removes content related to New Relic CronJob Monitoring.
Edited page - https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/#new-relic-kubernetes-monitoring-integration

Issue #15770

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
ping @jimangel as this is similar to your merged PR https://github.com/kubernetes/website/pull/10458

**Comment by aimeeu** [comment]
@xiangpengzhao @jimangel @stewart-yu  Vendor-specific content has been removed in PR #15747 - which is waiting for final approval

**Comment by xiangpengzhao** [comment]
As per @aimeeu 's comment, the change in this PR is already included in the earlier PR https://github.com/kubernetes/website/pull/15747. I'm going to close this PR. Thanks @sNathan13 anyway and welcome for further contributions!
/close

**Pull request closed without merging**
