### PR TITLE
Graduate Indexed Job to stable

### PR DESCRIPTION
**Pull request by alculquicondor**
/sig apps
/area batch

Graduate IndexedJob to stable

kubernetes/enhancements#2214

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
Holding this until upstream kubernetes/kubernetes#107395 is in.

**Comment by tengqm** [comment]
/hold cancel
Upstream code merged.
/approve

**Comment by reylejano** [comment]
Code PR in https://github.com/kubernetes/kubernetes/pull/107395 has merged
/approve

**Comment by reylejano** [comment]
Code PR in https://github.com/kubernetes/kubernetes/pull/107395 has merged
/lgtm

**Pull request merged**
