### PR TITLE
[WIP] [KEP-4191]: add section on split filesystem

### PR DESCRIPTION
**Pull request by kannon92**

### CODE REVIEW

**Comment by sftim** [comment]
@kannon92 I'm marking this as a work in progress.
/retitle [WIP] [KEP-4191]: add section on split filesystem

It's on you to mark this ready for review, once it is.
/sig node storage

**Comment by drewhagen** [comment]
Hello @kannon92 👋 please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday March 12th 2024 18:00 PST. Thank you!

**Comment by drewhagen** [comment]
Hello @kannon92! Thanks for putting this PR up for review.

I notice there is WIP here, so I want to extend a friendly reminder. The deadline for [PRs to finish review](https://kubernetes.io/docs/contribute/new-content/new-features/#all-prs-reviewed-and-ready-to-merge) is by Tuesday March 26th, 2024, 18:00 PM PT :clock6: This gives 2 weeks, though there may be many busy with KubeCon EU next week also!

As a user of Kubernetes, I really appreciate your contribution. 🚀
Best,
Drew

**Comment by kannon92** [comment]
We won't be able to release this in 1.30 as thought. We are pushing this to 1.31 so we will close this PR now.

**Comment by Princesso** [comment]
Hi @kannon92, gentle reminder to reopen the Doc placeholder PR for this enhancement before June 27th, 2024 which is the deadline for having a doc PR up.

**Pull request closed without merging**
