### PR TITLE
Fixed "Show the app in the terminal" URL (en)

### PR DESCRIPTION
**Pull request by craigcomstock**
The app is listening on port 8080 so that must be included otherwise port 80 (default) is used and the curl request will fail.

Issue: 41259

### CODE REVIEW

**Comment by stormqueen1990** [comment]
Hello there, @craigcomstock! 👋

Thank you for your contribution!

I see this PR includes changes for more than one localization. However, docs follows different processes for each localization, and we usually don't accept PRs that affect multiple localizations at once. I suggest splitting this PR into separate ones, one for each localization affected.

**Comment by craigcomstock** [comment]
> Hello there, @craigcomstock! 👋
> 
> Thank you for your contribution!
> 
> I see this PR includes changes for more than one localization. However, docs follows different processes for each localization, and we usually don't accept PRs that affect multiple localizations at once. I suggest splitting this PR into separate ones, one for each localization affected.

I was wondering. Sounds good. I'll split them up. I noticed that there were many more localizations that seemed to be lacking this same document so just changed the ones that were "easy to find". Should I look harder or just go with the three I found?

I do see https://kubernetes.io/docs/contribute/ but sorry I haven't read through it completely. The change proposed is rather small so probably with your guidance I can contribute something useful here without too much trouble.

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
