### PR TITLE
'subscribe' button translate

### PR DESCRIPTION
**Pull request by Arhell**
issue https://github.com/kubernetes/website/issues/23224

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-23230--kubernetes-io-master-staging.netlify.app/pt/#kubeweekly
/language pt

**Comment by sftim** [comment]
Sorry, I'm not able to review for the Portuguese localization.
/unassign @sftim

**Comment by Arhell** [comment]
@sftim 
Hi, I know, lgtm and approve is, you need to merge, thanks

**Comment by sftim** [comment]
Great, thanks @femrtnz and @jhonmike 

Echoing https://github.com/kubernetes/website/pull/23230#issuecomment-675809016 and https://github.com/kubernetes/website/pull/23230#issuecomment-679117791
/lgtm
/approve

BTW you can assign kubernetes/sig-docs-leads for approvals, rather than assigning a specific person.

**Comment by femrtnz** [comment]
Hi @zparnold, could you please have a look?

The Portuguese translation is approved, but we can't approved the PR

/assign @zparnold

**Pull request merged**
