### PR TITLE
WIP: CronJob TimeZone blog

### PR DESCRIPTION
**Pull request by soltysh**
Adds blog post for https://github.com/kubernetes/enhancements/issues/3140

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/hold

pending assignment of a publication date

(also, this doesn't look like it'll be ready for review by the deadline)

**Comment by divya-mohan0209** [comment]
@soltysh : Do we aim to publish this blog for one of the future releases this year?

**Comment by sftim** [comment]
Hi @soltysh 

You - or anyone who you're collaborating with - is very welcome to make a new article about scheduled Jobs in Kubernetes and the different options people have there. Timezones can be part of that story!

We wouldn't announce this feature though as the v1.28 release is out now. Thanks for your work on this.

/close

**Comment by soltysh** [comment]
I've eventually run out of time to finish this post, I'll probably figure out a different post, like you proposed about general CronJob bits.

**Pull request closed without merging**
