### PR TITLE
[id] Remove unused templates directory

### PR DESCRIPTION
**Pull request by habibrosyad**
Reflect changes done in #20893

xref https://github.com/kubernetes/website/issues/26955 https://github.com/kubernetes/website/issues/26955#issuecomment-802629943

/cc @ariscahyadi @irvifa

### CODE REVIEW

**Comment by ariscahyadi** [comment]
Let's cc all kube-sig-doc-id reviewers!
/cc @kubernetes/sig-docs-id-reviews

**Comment by habibrosyad** [comment]
> Let's cc all kube-sig-doc-id reviewers!
> /cc @kubernetes/sig-docs-id-reviews

Oh my bad, forgot about that!

**Review by ariscahyadi — COMMENTED** [review]
thanks @habibrosyad !

/lgtm

**Pull request merged**
