### PR TITLE
Add jmyung to sig-docs-ko-reviews

### PR DESCRIPTION
**Pull request by jmyung**
I'd like to apply for sig-docs-ko-reviews role.
I've met the requirements for reviewer:

18 PRs merged: https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Ajmyung
35 PRs reviewed: https://github.com/kubernetes/website/pulls?q=type%3Apr+reviewed-by%3Ajmyung
Member of Kubernetes for 3+ months
Thanks!

/assign @jmyung 
(According to the steps in https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/#becoming-a-reviewer)

### CODE REVIEW

**Comment by sftim** [comment]
Hi @jmyung 

A note about processes
We'd expect to make this change first in https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml and then copy the same change here.
/hold

**Comment by seokho-son** [comment]
+1

@jmyung is a very helpful Korean l10n contributor !!
 I think @jmyung is eligible to be a reviewer of Korean contents.

@jmyung , you can open a PR to https://github.com/kubernetes/org to update `config/kubernetes/sig-docs/teams.yaml`. (recent reference https://github.com/kubernetes/org/pull/2830 / https://github.com/kubernetes/website/pull/28948)

**Comment by jmyung** [comment]
@sftim @seokho-son 
Thanks !

I edited. Can you check this pr? 😺 
https://github.com/kubernetes/org/pull/2872

**Comment by jihoon-seo** [comment]
+1
@jmyung is a very passionate Korean l10n contributor!
/lgtm

**Comment by reylejano** [comment]
https://github.com/kubernetes/org/pull/2872 has merged to add @jmyung to [`kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml`](https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml#L160)

Releasing the hold
/hold cancel

**Pull request merged**
