### PR TITLE
fix markdown in readme it & anchor

### PR DESCRIPTION
**Pull request by Arhell**
[issue](https://github.com/kubernetes/website/issues/19355)

### CODE REVIEW

**Comment by Arhell** [comment]
Ping @kubernetes/sig-docs-it-owners

**Comment by sftim** [comment]
@arhell - I'm not an Italian-localization reviewer or approver.
@kubernetes/sig-docs-it-reviews might be willing to take a look.

**Comment by Arhell** [comment]
@sftim , got it, thanks)

**Comment by rlenferink** [comment]
/approve

Thanks for fixing

**Comment by rlenferink** [comment]
Ah, forgot that the README is a special thing to approve.

@sftim it seems your approval is still needed ;)

**Comment by sftim** [comment]
echoing https://github.com/kubernetes/website/pull/19441#issuecomment-594813300
/approve

**Pull request merged**
