### PR TITLE
Add a helper script for localization

### PR DESCRIPTION
**Pull request by gochist**
The script generates a report of outdated contents in `content/<l10n-lang>` directory by comparing two l10n team milestone branches.

> At the beginning of every team milestone, it’s helpful to open an issue comparing upstream changes between the previous development branch and the current development branch. 
> -- from [Localizing Kubernetes Documentation](https://kubernetes.io/docs/contribute/localization/#branching-strategy)

### CODE REVIEW

**Comment by gochist** [comment]
This script is used for #16242, #16068 and #15745. Please take a look.

**Comment by zacharysarah** [comment]
@gochist 👋 Thanks for adding this script--it's a handy tool for @kubernetes/sig-docs-l10n-admins. ✨ 
Please update [`/scripts/README.md`](https://github.com/kubernetes/website/blob/master/scripts/README.md) with a description, otherwise LGTM.

**Comment by gochist** [comment]
@zacharysarah Thank you! I have addressed your comment.

**Pull request merged**
