### PR TITLE
Removed Contiv.io

### PR DESCRIPTION
**Pull request by ixodie**
Project did not have direct integration with k8s.

URL to project info goes to malicious browser plugin install and ad-based squatter on contiv.io.

### CODE REVIEW

**Comment by reylejano** [comment]
Link to https://contiv.io is no longer valid.
The last commit to https://github.com/contiv/netplugin is from 2019.
I agree to remove Contiv because it seems that it is no longer maintained

/lgtm

**Review by sftim — COMMENTED** [review]
I agree about not hyperlinking to https://contiv.io/ and we should remove that part.

However, https://github.com/contiv/netplugin/tree/965773066d2b8ebed3514979949061a03d46fd20/install/k8s implies that you can install this into Kubernetes cluster and get cluster networking. If that's true then we should retain the section, even if the product isn't current. It's not SIG Docs' place to judge product _quality_.

**Comment by sftim** [comment]
BTW this is for #20232

**Comment by reylejano** [comment]
> I agree about not hyperlinking to https://contiv.io/ and we should remove that part.

Agree with @sftim 's [comment](https://github.com/kubernetes/website/pull/29695#pullrequestreview-753652675) to only remove the hyperlink to contiv.io
/lgtm cancel

**Pull request merged**
