### PR TITLE
Sync community-values.md from k/community

### PR DESCRIPTION
**Pull request by Sea-n**
Apply changes from January 2021.
- https://github.com/kubernetes/community/pull/5411

Add similar text adopted from [/content/en/comm/coc.md](https://github.com/kubernetes/website/blob/main/content/en/community/code-of-conduct.md?plain=1#L8-L16) to link to the canonical version.

Netlify preview: https://deploy-preview-34311--kubernetes-io-main-staging.netlify.app/community/values

### CODE REVIEW

**Review by zacharysarah — APPROVED** [review]
@Sea-n Thanks for updating this. ✨ 

The preview now centers body text, but I don't see any formatting or CSS changes. It's not blocking, just noticeable. 🤷🏻

Otherwise LGTM

**Comment by zacharysarah** [comment]
I'm willing to give an LGTM but would prefer a co-chair perform the approval. 👋🏻 @natalisucks @reylejano @divya-mohan0209 

/lgtm

**Comment by Sea-n** [comment]
Oh, thanks @zacharysarah for pointing the style mismatch out!

I've fixed that, waiting for others to review.

**Review by divya-mohan0209 — COMMENTED** [review]
Thank you for bringing this to our attention @zacharysarah and thank you so much for fixing this @Sea-n !
/approve

**Pull request merged**
