### PR TITLE
Fix styling of tutorial pages

### PR DESCRIPTION
**Pull request by kbhawkey**
- Fix styling of tutorial pages (navbar, fonts, feedback, create issue buttons, last modified date)
- For further information, see issue #17108
- tutorials/kubernetes-basics intro pages all include the local styles.css for styling multi-column graphics on page
- Also see PR #17051

### CODE REVIEW

**Comment by kbhawkey** [comment]
@BenHall , if you have time, I would appreciate your input. Thanks!
The interactive tutorial pages also link to overrides.css, for example:
/docs/tutorials/kubernetes-basics/public/css/overrides.css. I suggest this link be removed too, but have not tested yet.

**Comment by kbhawkey** [comment]
One of preview pages:
https://deploy-preview-17177--kubernetes-io-master-staging.netlify.com/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

**Comment by BenHall** [comment]
The changes look good to me. Thank you.

I believe `overrides.css` is what we hide the sidebar TOC on the Katacoda interactive pages so give the terminal more space. This should remain in place as it's only required on those pages.

**Comment by bradtopol** [comment]
So changes looked good to me and @sftim, and @BenHall is good with the changes so I think we are all set. Great job!!!!
/lgtm
/approve

**Pull request merged**
