### PR TITLE
[WIP][Scheduler User Guide Documentation] Add how scheduler works.

### PR DESCRIPTION
**Pull request by Violet-Guo**
The scheduler is one of the core components of Kubernetes. Understanding how does the scheduler works can help us better understand why Pod is running on this nodes, how to choose an optimal node,  and helps us better customize and extend our own scheduler.

The PR is from: https://github.com/kubernetes/kubernetes/issues/69768

/sig scheduling
/kind documentation

### CODE REVIEW

**Comment by zparnold** [comment]
@Violet-Guo Have you had a chance to review @misterikkit 's comments?

**Comment by Violet-Guo** [comment]
@zparnold Sorry for the late reply and inactivity within 90 days.
Thanks @misterikkit 's comments.
How about adding more information about how scheduler interactive with other components?

**Comment by Rajakavitha1** [comment]
@misterikkit could you please let @Violet-Guo know what would be the best approach to move this forward.

**Comment by Violet-Guo** [comment]
> @misterikkit could you please let @Violet-Guo know what would be the best approach to move this forward.

Thank you!

**Comment by mistyhacks** [comment]
Is this related to #10702? What is the current status of this PR? We haven't heard from you in a month.

**Comment by sftim** [comment]
Hi @Violet-Guo 

Can we give you any help with moving this PR forward?

**Comment by Violet-Guo** [comment]
> Hi @Violet-Guo
> 
> Can we give you any help with moving this PR forward?

Yes, that will be so great with your help.

**Comment by sftim** [comment]
I'll see if I can find time to help with this. It might be a while before I can.

**Comment by sftim** [comment]
@Violet-Guo I made a new pull request (#14637). Would you like to revise this PR and close the new one, or close this PR? (or something else).

**Pull request closed without merging**
