### PR TITLE
Update blog CSS

### PR DESCRIPTION
**Pull request by lucperkins**
I feel like the CSS for the blog could use a refresh. This PR leaves some elements alone (like the sidebar nav) but updates the text CSS, the basic container and layout, etc.

Here's an example post:

https://deploy-preview-11607--kubernetes-io-master-staging.netlify.com/blog/

### CODE REVIEW

**Comment by jimangel** [comment]
/lgtm

I also checked the link on mobile vs. current blog and the text is easier to read. +1 Thanks!

**Comment by kbhawkey** [comment]
@lucperkins, Quickly looked, the blog page appears brighter and tidy, though, the area for the blog text seems small now in proportion to the right nav. There is a lot of extra space on the right hand side and the social media icons appear larger.

**Comment by mistyhacks** [comment]
/assign @kbarnard10 

/hold

Please provide feedback or lift the hold and approve. Thanks!

**Comment by lucperkins** [comment]
@kbhawkey I do agree with that assessment but I'm going to try to do this incrementally. Would it be cool if we get this through and then we can re-assess?

**Comment by kbhawkey** [comment]
@lucperkins, Sure, go ahead.

**Comment by sftim** [comment]
This will need updating now that #13113 is merged

**Pull request closed without merging**
