### PR TITLE
Rename Google Container Engine to Google Kubernetes Engine

### PR DESCRIPTION
**Pull request by chenopis**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6300)

### CODE REVIEW

**Comment by chenopis** [comment]
@ryanmcginnis Are we supposed to remove the acronym "GKE" as well, or is that still okay?

**Comment by ryanmcginnis** [comment]
@chenopis Yes, please remove the acronym. We shouldn't use it in documentation.

**Comment by chenopis** [comment]
@zacharysarah FYI, `Google Container Engine` was just renamed to `Google Kubernetes Engine`, and we're not supposed to use the acronym `GKE` in the documentation.

**Comment by zacharysarah** [comment]
@chenopis Good to know, thanks. Is there a preferred acronym to replace it?

**Comment by chenopis** [comment]
If the context is Google, then "GKE" should be changed into "Kubernetes Engine". Otherwise, if an acronym has to be used then "GKE" is still okay.

**Comment by chenopis** [comment]
closes #6302

**Pull request merged**
