### PR TITLE
Update controller.md - grammar adjustment

### PR DESCRIPTION
**Pull request by mariuskimmina**
I believe in this context it should be "In contrast with" instead of "By contrast with"

I'm not a native speaker so I might be wrong. "In contrast with" sounded more natural to me.

I also found this source pointing towards using "In contrast" when followed by with/in.
https://english.stackexchange.com/questions/7642/what-is-the-difference-between-by-contrast-and-in-contrast

### CODE REVIEW

**Comment by Krishnamohan-Yerrabilli** [comment]
yeah the change makes sense, I like to listen to other thoughts as well

**Comment by reylejano** [comment]
This is a trivial edit, please look at our policy on trivial edits
https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits 

    If you find one grammatical or spelling error, it is likely there are more in that file, you can really make your Pull Request count by checking the formatting, checking for broken links, and fixing errors and then submitting all the fixes at once to that file.

    Some questions to consider:

    Can the file be improved further?
    Does the trivial edit greatly improve the quality of the content?

**Comment by mariuskimmina** [comment]
@reylejano  I was unaware of the policy regarding trivial edits, it just stood out to me and used the "Edit the page" button to make a small change. 

Anyway, I read the whole page again and found two other small improvements. Other then that the page still looks good to me.

**Pull request merged**
