### PR TITLE
Replace k8s.gcr.io references with registry.k8s.io

### PR DESCRIPTION
**Pull request by pkprzekwas**
Replaced some leftover `k8s.gcr.io` references.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks @pkprzekwas for your contribution. In general we do not want PRs spanning across multiple languages. If you could break this up into multiple PRs, where we have a single PR per language that would be great.

**Comment by pkprzekwas** [comment]
> Thanks @pkprzekwas for your contribution. In general we do not want PRs spanning across multiple languages. If you could break this up into multiple PRs, where we have a single PR per language that would be great.

Will do :)

**Comment by pkprzekwas** [comment]
I removed changes in `ko/` folder, so no this change touches only files inside `en/`. I don't know why CI checks failed. Looks like timeout?

**Comment by dipesh-rawat** [comment]
> I removed changes in `ko/` folder, so no this change touches only files inside `en/`. I don't know why CI checks failed. Looks like timeout?

@pkprzekwas We do occasional see Netlify build failures due to timeouts. Could you try to trigger the build again using `git commit --amend --no-edit && git push --force-with-lease`

**Review by dipesh-rawat — COMMENTED** [review]
Just noticed there is another PR #39511 (opened earlier) which is addressing the same issue and few of blog files are same.

**Comment by pkprzekwas** [comment]
Do you want me close this issue in this case?

**Comment by dipesh-rawat** [comment]
Hi @pkprzekwas 
Thank you for your efforts.

Unfortunately, this seem to be like a duplicate of PR https://github.com/kubernetes/website/pull/39511
Since PR https://github.com/kubernetes/website/pull/39511 came first, that is most likely to get merged first. You may choose to close this PR.

/triage duplicate

**Comment by pkprzekwas** [comment]
Closing as it's a duplicate of https://github.com/kubernetes/website/pull/39511

**Pull request closed without merging**
