### PR TITLE
Add CNCF logo to homepage 

### PR DESCRIPTION
**Pull request by kbarnard10**
cc // @dankohn

### CODE REVIEW

**Comment by kbarnard10** [comment]
@bobsky - let me know if you have any feedback

**Comment by dankohn** [comment]
It is on all other project sites already. I like Bob's design better.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
LGTM

**Pull request merged**
