### PR TITLE
Update ingress-minikube.md

### PR DESCRIPTION
**Pull request by Megapixel99**
moved ``` to above and below yaml code for proper formatting

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For Chinese localization, base branch to release-1.14
>
> For Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by Megapixel99** [comment]
I was using the documentation for a project I am working on and noticed some code is not formatted properly on Step 1 of https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress-resource. My change seems to fix the formatting issue.

**Comment by Megapixel99** [comment]
I signed it

**Comment by tengqm** [comment]
The preview is still incorrect.

**Comment by kbhawkey** [comment]
Is this a duplicate of #14295?

**Pull request closed without merging**
