### PR TITLE
Removed colon and made description consistent

### PR DESCRIPTION
**Pull request by SvanBoxel**
Fixed a small typo in [Hello Minikube](https://kubernetes.io/docs/tutorials/hello-minikube/) tutorial.

Also made the description a bit more consistent and added proper markdown.

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@SvanBoxel 
Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

memo Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

**Comment by SvanBoxel** [comment]
@Rajakavitha1 signed! 🖊

**Comment by Rajakavitha1** [comment]
@SvanBoxel Thanks for the fix!!!
/lgtm

**Pull request merged**
