### PR TITLE
 Update Kubelet RotateKubeletClientCertificate feature since v1.8

### PR DESCRIPTION
**Pull request by lf1029698952**
fix feature-gates.md and kubelet-tls-bootstrapping.md Kubelet RotateKubeletClientCertificate feature since v1.8 instead of v1.7

### CODE REVIEW

**Comment by philips** [comment]
confirmed this is right.

/lgtm

**Comment by DanyC97** [comment]
@cody-clark any chance you can help with a final approve? thank you

**Comment by Bradamant3** [comment]
@lf1029698952 if you could please fix the merge conflicts we'll get this PR merged, with apologies for the delay. Thanks!

**Comment by lf1029698952** [comment]
@Bradamant3 @philips I have resolved merge conflicts, because this conflicts with v1.14 feature update.

**Pull request merged**
