### PR TITLE
Fix the feature state of PodSecurity (zh-cn)

### PR DESCRIPTION
**Pull request by houjun41544**
Fix the feature state of PodSecurity in zh-cn doc.

### CODE REVIEW

**Comment by tengqm** [comment]
Please resync the whole page.
Line 598, 612 should be changed.
/hold

**Comment by Sea-n** [comment]
Hey @houjun41544,

Although this page is out-of-sync, it's not hard to resync this page.

Please run this command in `main` branch:
```bash
./script/lsync.sh content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md
```

You will see only 4 lines are changed. Then you can add them to this PR and force-push.

**Comment by houjun41544** [comment]
@Sea-n 
Thanks a lot！

**Review by Sea-n — COMMENTED** [review]
Unhold since it's up-to-dated.
/unhold

And thanks for syncing this page! It looks nice to me. 😊
/approve

Your first commit looks weird, maybe you would like to squash them into one. Or we can ask the @k8s-ci-robot to do the job.
/label tide/merge-method-squash

**Comment by houjun41544** [comment]
@Sea-n  Done!

**Pull request merged**
