### PR TITLE
Update API reference for v1.30

### PR DESCRIPTION
**Pull request by tengqm**
This PR updates the single-page API reference for v1.30.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
This PR doesn't cover https://kubernetes.io/docs/reference/kubernetes-api/ - let's mention that in the description.

**Review by dipesh-rawat — COMMENTED** [review]
/approve

**Review by sftim — COMMENTED** [review]
Thanks

[Preview](https://deploy-preview-45914--kubernetes-io-main-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.30/) LGTM

/lgtm

**Review by sftim — COMMENTED** [review]
Thanks

[Preview](https://deploy-preview-45914--kubernetes-io-main-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.30/) LGTM

/lgtm

**Pull request merged**
