### PR TITLE
README.md - Add notes about hugo extended version

### PR DESCRIPTION
**Pull request by dougsland**
- README.md: add troubleshooting session for Hugo
- README.md: Specify Hugo version

### CODE REVIEW

**Comment by dougsland** [comment]
@onlydole @kbarnard10 @zacharysarah just a friendly ping. :)

**Comment by dougsland** [comment]
> @onlydole @kbarnard10 @zacharysarah just a friendly ping. :)

ping :)

**Review by irvifa — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
