### PR TITLE
test redirect of api ref index page

### PR DESCRIPTION
**Pull request by kbhawkey**
Testing (correcting) the redirect of docs/reference/kubernetes-api/ after index.md was renamed to api-index.md.
For further information, see issue #17261.

### CODE REVIEW

**Comment by jimangel** [comment]
Good catch! I still see the following warning:
```
9:05:07 AM: WARN 2019/10/30 14:05:07 Content directory "/opt/build/repo/content/en/docs/reference/kubernetes-api" have both index.* and _index.* files, pick one.
9:05:07 AM: WARN 2019/10/30 14:05:07 Content directory "/opt/build/repo/content/en/docs/reference/kubernetes-api" have both index.* and _index.* files, pick one.
```

I have yet to try a cleared-cache build. I'm thinking I can test this on my personal Netlify account for comparison.

**Comment by kbhawkey** [comment]
@jimangel , I don't see the warnings now after I updated the es and zh files?

**Comment by jimangel** [comment]
I can confirm, the latest build does not have the warnings. Thanks for your persistence on this!

Before merging, it's worth syncing with the zh and es localization teams to ensure this PR won't impact their branching strategies (since we traditionally don't touch their files).

/cc @chenrui333 @tengqm (zh)
/cc @raelga @alexbrand (es)
/cc @zacharysarah (awareness)

**Pull request merged**
