### PR TITLE
[es] Translate install-kubectl-windows.md

### PR DESCRIPTION
**Pull request by rituisboy**
This pull request solves issue #41884 created new  install-kubectl-windows.md in spanish

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please re-puch commit

**Comment by electrocucaracha** [comment]
Thanks for participating into the Kubernetes Website project. The Spanish translation team would like to facilitate your contribution's journey, so please share your goals and/or skills in order to assist you better. We also encourage new contributors to participate in their native speaking language.

**Comment by tengqm** [comment]
/close
This has been stagnating for a while now.
Feel free to reopen and fix the gate issue, and at least sign the CLA in order for your PR to be reviewed.

**Pull request closed without merging**
