### PR TITLE
update list of Intel device plugins

### PR DESCRIPTION
**Pull request by bart0sh**
Updated a list of Intel device plugins with the info from the [project repository](https://github.com/intel/intel-device-plugins-for-kubernetes)

Fixes: https://github.com/intel/intel-device-plugins-for-kubernetes/issues/878

### CODE REVIEW

**Comment by reylejano** [comment]
I reviewed the [Intel device plugins for Kubernetes](https://github.com/intel/intel-device-plugins-for-kubernetes) GitHub repo and the update in this PR is correct
/lgtm
/approve

**Comment by tengqm** [comment]
Gate is still unhappy about this change. @bart0sh Mind doing a rebase?

**Comment by bart0sh** [comment]
@reylejano @tengqm 
> Gate is still unhappy about this change. @bart0sh Mind doing a rebase?

done. Please approve again.

**Comment by tengqm** [comment]
Reapply lgtm
/lgtm

**Pull request merged**
