### PR TITLE
fix rendering errors

### PR DESCRIPTION
**Pull request by 0xff-dev**
fix rendering errors

current:  https://kubernetes.io/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions

preview: https://deploy-preview-35214--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions

### CODE REVIEW

**Review by Sea-n — COMMENTED** [review]
/lgtm

Next time it would be better to attach current and preview pages in PR description. 😊

https://kubernetes.io/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions

https://deploy-preview-35214--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions

**Comment by mengjiao-liu** [comment]
Please run the following command on the `main` branch to sync the upstream version:
```
./scripts/lsync.sh content/zh-cn/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
```

/hold

**Comment by tengqm** [comment]
@0xff-dev The upstream english text has some trivial changes, please sync them to the translated version **even if the translation doesn't need to be changed.**.

**Comment by 0xff-dev** [comment]
@tengqm @mengjiao-liu @Sea-n  It has been updated, please review again, thank you.

**Comment by tengqm** [comment]
Thanks.
/lgtm
/approve

**Pull request merged**
