### PR TITLE
Fix #19195

### LINKED ISSUE #19195: Issue with k8s.io/ja/docs/concepts/workloads/controllers/deployment/
**This is a Bug Report**

**Problem:**
same as #11982 

nginx-deployment.yaml on Japanese and Chinese is differed on others.
- [English](https://github.com/kubernetes/website/blob/master/content/en/examples/controllers/nginx-deployment.yaml#L19)
- [Japanese](https://github.com/kubernetes/website/blob/master/content/ja/examples/controllers/nginx-deployment.yaml#L19)
- [Chinese ](https://github.com/kubernetes/website/blob/master/content/zh/examples/controllers/nginx-deployment.yaml#L19)

Due to this, the version information is not matched
image
image

**Proposed Solution:**
Change `image:nginx: 1.15.4` to `image: nginx:1.7.9` 

**Page to Update:**
- [Japanese](https://kubernetes.io/ja/docs/concepts/workloads/controllers/deployment/#deployment%E3%81%AE%E6%9B%B4%E6%96%B0)
- [Chinese ](https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#%E6%9B%B4%E6%96%B0-deployment)

### PR DESCRIPTION
**Pull request by cawamata**

### CODE REVIEW

**Comment by cawamata** [comment]
I signed it

**Comment by inductor** [comment]
@cawamata nginx 1.7 and 1.9 are very old and I think the doc should be fixed with newer version

**Comment by cawamata** [comment]
@inductor Let's discuss another issue ticket.
This PR is document bugfix to match version info not only each language but also other languages.

**Comment by makoscafee** [comment]
@cawamata and  @inductor  could this be closed in favour of https://github.com/kubernetes/website/pull/19198 ?

**Comment by cawamata** [comment]
@makoscafee Thank you following up
@inductor deal with my issue by other PR, so I close this PR

**Pull request closed without merging**
