### PR TITLE
#7198 Adding Linux Binary to Repo

### PR DESCRIPTION
**Pull request by chris-short**
To do this yourself I suggest this from Dave Cheney: https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5

Signed-off-by: Chris Short <chris@chrisshort.net>

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7201)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@chenopis Could you take this one? The update-imported-docs binary is already in the repo. So I don't understand why we need this PR.

**Comment by chenopis** [comment]
@steveperry-53 I guess Golang binaries aren't cross-platform compatible, so we need separate binaries for Linux and macOS.

**Comment by chenopis** [comment]
@chris-short We should have two binaries that are named `update-imported-docs-linux` and `update-imported-docs-macos`, so don't overwrite the old one, just rename it.

**Comment by chris-short** [comment]
100% agree. I will fix that.

**Comment by heckj** [comment]
👋 @chris-short - it's been a while, so wanted to check it - the PR needs a rebase at least, wasn't sure if you were complete with your changes otherwise though

**Comment by chenopis** [comment]
I believe this was taken care of in a different PR.

**Pull request closed without merging**
