### PR TITLE
Update README-ru.md

### PR DESCRIPTION
**Pull request by techschneiderrr**

### CODE REVIEW

**Comment by sftim** [comment]
Hi @techschneiderrr

Once you've signed the contributor agreement, we can review this. Would you like any help with getting that signed?

**Review by Arhell — COMMENTED** [review]
About CLA info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
👋 @techschneiderrr . Thanks for contributing!
Would you verify that you have signed the CLA?

**Pull request closed without merging**
