### PR TITLE
Issue with k8s.io/docs/tutorials/ #15518

### LINKED ISSUE #15518: Issue with k8s.io/docs/tutorials/
**This is a Bug Report**
Always after copy to clipboard data, reset scroll position to begin page.

**Problem:**
At all pages where you have active element for copy(example yaml data) to clipboard, after click on copy element and later approve on dialog copy to clipboard I'm scroll to begin page. Have problem on next browsers: Chrome and Firefox.

bug_scroll_up_2019-07-24_12-02

**Proposed Solution:**
Don't have. Need see what you use for make single pages.

**Page to Update:**
https://kubernetes.io/docs/tutorials/

**Additional Information:**
Google Chrome: Version 75.0.3770.142 (Official Build) (64-bit)
Firefox Quantum: Version 68.0 (64-bit)
Linux tester-ubuntu 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by medmedchiheb**
update sweetAlert and fix scrolling after copy

k8s-new-alert

Fixes #15518

### CODE REVIEW

**Comment by ryanmcginnis** [comment]
seems like this fixes #4205! thanks!

**Comment by xiangpengzhao** [comment]
/assign @lucperkins 
for approval

**Comment by xiangpengzhao** [comment]
ping @kbarnard10 for approval :)

**Pull request merged**
