### PR TITLE
Update service.md

### PR DESCRIPTION
**Pull request by DylanGraham**
Update from ReplicationController and rolling-update to ReplcaSet and Deployment rollout

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by Bradamant3** [comment]
@DylanGraham I see what you want to do here, and it's headed in the right direction. But it's not as simple as RelicationController -> ReplicaSet and rolling update -> deployment -- especially not the latter. The way you've substituted the terms, it reads as though a ReplicaSet manages a Deployment, when in fact it's the other way around. 

See in particular https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#when-to-use-a-replicaset.

Props for tackling a tricky and needed update, but it needs a bit more work before we can merge. lmk if you have questions.

**Comment by DylanGraham** [comment]
Thanks for the feedback @Bradamant3 
Do you think the text should be:
``` (e.g. when scaling up or down or when being triggered by a deployment rollout).```

**Comment by Bradamant3** [comment]
@DylanGraham let's get rid of any mention of Deployments for now, and leave just the scaling example in the parentheses. The whole intro para to this topic should probably be written sometime, but that's a much bigger task, and in the meantime getting your change in is good. So let's include just `(e.g. when scaling up or down)`.

**Pull request merged**
