### PR TITLE
Fix typo in 'replicalimit-param.yaml' example YAML

### PR DESCRIPTION
**Pull request by aslafy-z**
Fix wording of `namespace` in validatingadmissionpolicy/replicalimit-param sample

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for the fix!
/lgtm

**Comment by dipesh-rawat** [comment]
/retitle Fix typo in 'replicalimit-param.yaml' example YAML

**Review by kundan2707 — COMMENTED** [review]
/lgtm
thanks

**Comment by kundan2707** [comment]
Create issue for zh-ch https://github.com/kubernetes/website/issues/44192

**Review by kumarankit999 — COMMENTED** [review]
Thanks @aslafy-z for contributing.
It has been fixed noww!!

**Comment by aslafy-z** [comment]
@kundan2707 @kumarankit999 it was fixed for chinese documentation. See https://github.com/kubernetes/website/blob/main/content/en/examples/validatingadmissionpolicy/replicalimit-param.yaml. 
Please reopen :pray:

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks for the fix!
/approve

**Pull request merged**
