### PR TITLE
[en] update case-studies/amadeus folder links

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubernetes/website/issues/42638

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The current HTTP url appears to redirect to HTTPS with a response code of 301. In any case, the proposed changes to update the link LGTM.

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Review by ydFu — APPROVED** [review]
/lgtm
Thanks for updating.

**Review by sftim — APPROVED** [review]
/approve

**Pull request merged**
