### PR TITLE
[WIP] PDB GA documentation

### PR DESCRIPTION
**Pull request by mortent**
This is a placeholder PR for the docs for the PDB to GA KEP https://github.com/kubernetes/enhancements/pull/904

### CODE REVIEW

**Comment by simplytunde** [comment]
@mortent  looks like this is no more a WIP. can you remove the do-not-merge/work-in-progress label?

**Comment by mortent** [comment]
@simplytunde  This change didn't make the deadline so it will be pushed to 1.17. I was planning to just close this PR and open a new one once the change lands in 1.17.

**Comment by simplytunde** [comment]
Thanks @mortent. can you close this?

**Pull request closed without merging**
