### PR TITLE
Update kubeadm-upgrade-1-13.md

### PR DESCRIPTION
**Pull request by Pancongwen**
fix typo of 'Ugrade'

### CODE REVIEW

**Comment by neolit123** [comment]
@Pancongwen 
please read here so that you can sign the CLA.
https://github.com/kubernetes/website/pull/13438#issuecomment-476571432

without the CLA we cannot accept the PR. :)

**Comment by Pancongwen** [comment]
ok, i have signed the CLA

**Comment by neolit123** [comment]
> ok, i have signed the CLA

thanks, now someone from the docs team needs to approve. :)
/assign @Rajakavitha1 @tfogo

**Pull request merged**
