### PR TITLE
Fix example url for downloading specific version

### PR DESCRIPTION
**Pull request by manjush08**
- Fix example url in docs for downloading a specific kops version.

### CODE REVIEW

**Comment by tengqm** [comment]
@manjush08 pls sign the CLA in order for the PR to be reviewed.

**Review by Arhell — COMMENTED** [review]
About CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
👋 @manjush08 .
Would you verify that you signed the CLA?

**Pull request closed without merging**
