### PR TITLE
Fix navbar Search text visibility and background color on scroll

### PR DESCRIPTION
**Pull request by dev-johnn**
Made cahnge to make Search text appear.

Fixes https://github.com/kubernetes/website/issues/45587
Also, this will fix https://github.com/kubernetes/website/issues/45586

image

image

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/retitle Fix navbar Search text visibility and background color on scroll
_(Added little context in the title for the reviewers)_

**Review by dipesh-rawat — COMMENTED** [review]
Nice job on swiftly addressing the reported issue in this PR! Looking at the [deploy preview (here)](https://deploy-preview-45594--kubernetes-io-main-staging.netlify.app/), the changes appear to be satisfactory.

**Comment by dipesh-rawat** [comment]
/label tide/merge-method-squash

@dev-johnn If you're able to squash all the changes into 1 commit, that would be great (it makes things cleaner). You can find helpful guidance at https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

**Comment by dipesh-rawat** [comment]
I'm can give my approval for this. Since it's a modification to the live site, we need another person to review and confirm it with "LGTM".

/approve

**Review by Gauravpadam — COMMENTED** [review]
Yeah, that's clean
/lgtm
Thanks @dev-johnn

**Pull request merged**
