### PR TITLE
Fix typo for kubeadm in instruction for upgrading

### PR DESCRIPTION
**Pull request by sarjeet2013**
This  PR fix the typo for kubeadm in instruction for upgrading kubelet and kubeadm.

Note: Minor fix, Can be merged safely.

### CODE REVIEW

**Comment by sarjeet2013** [comment]
This needs to be fixed in `release-1.11` as well. Can this be cherry-picked or need a new PR? LMK

**Comment by Bradamant3** [comment]
@sarjeet2013 the 1.11 version on the docs site (that is, the latest version) is built from master, so we're good to go. Thanks!

**Pull request merged**
