### PR TITLE
Fixed typo in documentation

### PR DESCRIPTION
**Pull request by ashispavan**
Fixed typo in documentation page.

### CODE REVIEW

**Comment by ashispavan** [comment]
Signed CLA with CNCF. Please verify.

**Comment by zacharysarah** [comment]
@ashispavan 👋 Please verify that the email you used to sign the CLA is the same one attached to your GitHub ID, and specifically attached to this PR's commit.

**Comment by zacharysarah** [comment]
@ashispavan 👋 Please feel free to `/reopen` when you're ready to continue.

**Pull request closed without merging**
