### PR TITLE
switch New York Times case study to use youtube shortcode (ko)

### PR DESCRIPTION
**Pull request by Arhell**
issue https://github.com/kubernetes/website/issues/25124

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-25287--kubernetes-io-master-staging.netlify.app/ko/case-studies/newyorktimes/
/assign @pjhwa
/assign @seokho-son

**Comment by pjhwa** [comment]
@Arhell Thank you for your contribution!

/lgtm

/unassign @seokho-son

**Comment by pjhwa** [comment]
@Arhell Korean working branch is now set to dev-1.19-ko.6. And I'm working on the outdated files of dev-1.15-ko.5  for dev-1.19-ko.6. This file is one of outdated files. (#25284)

Could you rebase the target to our working branch, dev-1.19-ko.6 instead of master?

**Comment by pjhwa** [comment]
Thank you very much, @Arhell ! 👍 

/lgtm

**Comment by ianychoi** [comment]
/lgtm
/approve

Thank you!

**Pull request merged**
