### PR TITLE
Added the file operator-pattern.md and translated to Hindi

### PR DESCRIPTION
**Pull request by ankitsingh241**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by Babapool** [comment]
Hi @ankitsingh241 ,thank you for your contribution. Please sign the CLA before your PR can get reviewed. Thanks.
For more information on the CLA : https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Garima-Negi** [comment]
> Details

hi @ankitsingh241 can you go through this page to get CLA ready? [https://contributor.easycla.lfx.linuxfoundation.org/#/cla/project/d8cead54-92b7-48c5-a2c8-b1e295e8f7f1/user/f0dc9975-ea35-465c-8239-a62372094481?redirect=https:%2F%2Fgithub.com%2Fkubernetes%2Fwebsite%2Fpull%2F37858](https://contributor.easycla.lfx.linuxfoundation.org/#/cla/project/d8cead54-92b7-48c5-a2c8-b1e295e8f7f1/user/f0dc9975-ea35-465c-8239-a62372094481?redirect=https:%2F%2Fgithub.com%2Fkubernetes%2Fwebsite%2Fpull%2F37858)

**Comment by ankitsingh241** [comment]
Hello @Garima-Negi , Thanks for your help but that link redirecting me to your PR at https://github.com/kubernetes/dashboard/pull/6615
I have raised a ticket to CLA support desk if it will be solved then fine otherwise I think I have to close the PR and raise it again.

**Pull request closed without merging**
