### PR TITLE
Updates for file README-uk.md

### PR DESCRIPTION
**Pull request by Andygol**
Update to README-uk.md

With intention to reignite work on translation docs into Ukrainian, I updated README-uk.md with up-to-date content.

Now the content in Ukrainian corresponds to the content in English

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@Andygol Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Comment by Andygol** [comment]
👋 @dipesh-rawat 

I've already passed the CLA sign-in step 3 times in the last 10 minutes. 😞 

Can you help me with the issue

**Review by dipesh-rawat — COMMENTED** [review]
Let me try to re-trigger the check.
/easycla

**Comment by Andygol** [comment]
@dipesh-rawat  In my user settings, I see that access to EasyCLA is granted👇

**Comment by dipesh-rawat** [comment]
@Andygol Could you try to trigger the PR build again by pusing empty commit using `git commit --amend --no-edit && git push --force-with-lease` , maybe that would force a EasyCLA check again.

**Comment by Andygol** [comment]
@dipesh-rawat 
Unfortunately `git commit --amend --no-edit && git push --force-with-lease` didn't help to trigger CLA check 😢 

What if I revoke permission for EasyCLA in my GitHub profile and then go through the sign-in step again?

**Comment by dipesh-rawat** [comment]
@Andygol I've noticed that your commit ([PR-45017/commits](https://github.com/kubernetes/website/pull/45017/commits)) in this PR includes `transifex-integration[bot]` alongside your username. This might be causing an issue with EasyCLA checks.

> transifex-integration[bot] authored and Andygol committed

**Comment by Andygol** [comment]
> commit ([PR-45017/commits](https://github.com/kubernetes/website/pull/45017/commits)) in this PR includes `transifex-integration[bot]`

This is because I use Transifex to maintain translation process 🤷‍♂️

**Comment by Andygol** [comment]
This is really strange to not use systems that ease translation maintenance.

I've cut new PR https://github.com/kubernetes/website/pull/45019 where is no automation and it passed CLA check 🩹.

I close this PR in favour of the new one.

**Pull request closed without merging**
