### PR TITLE
Changed term-id from cri to container-runtime-interface

### LINKED ISSUE #46343: Incorrect glossary tooltip
**This is a Bug Report**
There is a wrong reference to the Container runtime interface in [this](https://kubernetes.io/docs/reference/instrumentation/cri-pod-container-metrics/) page. It take to container runtime instead of CRI.

Should be updated with correct reference to CRI page.

### PR DESCRIPTION
**Pull request by pranav-pandey0804**
fixes #46343

### CODE REVIEW

**Comment by pranav-pandey0804** [comment]
fixes #46343

**Review by dipesh-rawat — COMMENTED** [review]
/lgtm

[Preview Page](https://deploy-preview-46397--kubernetes-io-main-staging.netlify.app/docs/reference/instrumentation/cri-pod-container-metrics/)

**Review by mengjiao-liu — COMMENTED** [review]
/lgtm

**Comment by pranav-pandey0804** [comment]
@salaxander thanks :)

**Pull request merged**
