### PR TITLE
Accessibility updates - main landmark roles

### PR DESCRIPTION
**Pull request by ChaitanyaKaranam**
This PR fixes below accessibility issues:

1. The document should have only one ``main`` element. 
Multiple occurrences of ``main`` element are removed.
2. ``main`` element is added to documents wherever applicable.
3. The CSS for ``main`` element is replaced with class ``.main-section``

### CODE REVIEW

**Comment by ChaitanyaKaranam** [comment]
Fixes [issue](https://github.com/kubernetes/website/issues/17104)

**Comment by sftim** [comment]
Looks good at a glance. I'll try to make time to review this in more detail.

**Comment by zparnold** [comment]
This also looks good to me. Pending @sftim this is approved.
/approve

**Comment by bradtopol** [comment]
Assigning @sftim since its waiting his review
/assign @sftim

**Pull request merged**
