### PR TITLE
Fix hugo anchor in readme

### PR DESCRIPTION
**Pull request by Arhell**
Hi!
Fix anchor in readme
[issue](https://github.com/kubernetes/website/issues/19487)

### CODE REVIEW

**Comment by sftim** [comment]
I'll need a /lgtm from a Hindi localization approver

**Comment by mittalyashu** [comment]
@Arhell Were you able to test the changes locally on your machine?

**Comment by Arhell** [comment]
@mittalyashu 
Of course!

**Comment by mittalyashu** [comment]
@sftim I do have access to merge the PR.

Just want to double-sure, should I merge it?

**Comment by sftim** [comment]
If you're a Hindi approve and you approve, it's OK to /approve

**Comment by php-coder** [comment]
just one more
/lgtm
:)

Thank you!

**Comment by Arhell** [comment]
Ping @kubernetes/sig-docs-hi-owners

**Comment by Arhell** [comment]
сс @sftim

**Comment by jimangel** [comment]
@mittalyashu to approve a PR you need both `/lgtm` and `/approve`. I see a `/lgtm` but I don't see 
an `/approve` anywhere in your comments. Will you give that a try?

If you still have issues, I can approve this PR.

Thanks!

**Comment by sftim** [comment]
@mittalyashu to approve a PR, you need both /lgtm and /approve. I see a /lgtm but I don't see
an /approve anywhere in your comments. Will you give that a try?

**Comment by mittalyashu** [comment]
@sftim @jimangel Seems like I don’t have required permission to use the approve command. 🤔

**Comment by sftim** [comment]
With https://github.com/kubernetes/website/pull/19314#issuecomment-623050482 recording approval, I can echo that:
/approve

**Pull request merged**
