### PR TITLE
Fixed small bug in 2017-10-00-Five-Days-Of-Kubernetes-18.md

### PR DESCRIPTION
**Pull request by xichengliudui**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.13-ko.<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by xichengliudui** [comment]
Ref: 
https://github.com/kubernetes/website/pull/13472
https://github.com/kubernetes/website/pull/13471
https://github.com/kubernetes/website/pull/13470

**Comment by Bradamant3** [comment]
sorry @xichengliudui we don't take changes to older blog posts. See https://kubernetes.io/docs/contribute/intermediate/#blog-issues

**Pull request closed without merging**
