### PR TITLE
Add CCM Hetzner

### PR DESCRIPTION
**Pull request by pouledodue**
Add CCM Hetzner

### CODE REVIEW

**Comment by zacharysarah** [comment]
Hold pending outcome of the KEP arising from #15748 

/hold

**Comment by sftim** [comment]
I'm minded to let this PR through. If the outcome of the KEP is to tidy up that page, it will involve more changes than just the Hetzner line.

**Comment by zacharysarah** [comment]
@sftim That's reasonable.

/approve
/hold cancel

**Pull request merged**
