### PR TITLE
fixed the grammatical mistake in hi docs

### PR DESCRIPTION
**Pull request by Vikash-8090-Yadav**
updated some Grammar meaning to the actual one.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Any updates on this pr @dipesh-rawat

**Review by Arhell — COMMENTED** [review]
/assign @anubha-v-ardhan

**Review by anubha-v-ardhan — COMMENTED** [review]
/lgtm

Thank you @Vikash-8090-Yadav

**Comment by anubha-v-ardhan** [comment]
LGTM in my opinion as a maintainer for Hindi localization. Feel free to merge this.

**Comment by Vikash-8090-Yadav** [comment]
> LGTM as a maintainer for Hindi localization. Feel free to merge this.

Thanks!

**Comment by Vikash-8090-Yadav** [comment]
Hey @anubha-v-ardhan @dipesh-rawat @Arhell please approve this pr. If there's something that needs to be updated please do let me know as well. Thanks!

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Comment by Vikash-8090-Yadav** [comment]
Hey @anubha-v-ardhan @natalisucks Let me know if any further changes are needed. Thanks!

**Pull request merged**
