### PR TITLE
add shortcode for training page

### PR DESCRIPTION
**Pull request by Arhell**
this PR https://github.com/kubernetes/website/pull/24014

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-24875--kubernetes-io-master-staging.netlify.app/training/
/assign @tengqm

**Comment by howieyuen** [comment]
I don't see any difference after updating, it seems to be a frame update, right?

**Comment by Arhell** [comment]
@howieyuen 
Hello, there will be no difference, just replaced the iframe with a short code, and the page shows that everything works, as here
https://github.com/kubernetes/website/pull/24014

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
