### PR TITLE
Updated and added links in 'Networking on Windows' doc

### LINKED ISSUE #46458: Update and add links to "Networking on Windows" doc
**Problem:**
In [Networking on Windows](https://kubernetes.io/docs/concepts/services-networking/windows-networking/) doc under [Network modes](https://kubernetes.io/docs/concepts/services-networking/windows-networking/#network-modes):
1) `win-bridge` redirects to https://github.com/containernetworking/plugins/tree/main/plugins/main/windows/win-bridge which shows that the documentation has been moved.
2) Similarly, `win-overlay` redirects to https://github.com/containernetworking/plugins/tree/main/plugins/main/windows/win-overlay which again shows that the documentation is moved.
3) No hyperlink for `Flannel host-gateway`
4) No hyperlink for `Flannel VXLAN`

**Proposed Solution:**
1) For `win-bridge` replace https://github.com/containernetworking/plugins/tree/main/plugins/main/windows/win-bridge with https://www.cni.dev/plugins/current/main/win-bridge/
2) For `win-overlay` replace https://github.com/containernetworking/plugins/tree/main/plugins/main/windows/win-overlay with https://www.cni.dev/plugins/current/main/win-overlay/
3) For `Flannel host-gateway` add this hyperlink: https://github.com/flannel-io/flannel/blob/master/Documentation/backends.md#host-gw
4) For `Flannel VXLAN` add this hyperlink: https://github.com/flannel-io/flannel/blob/master/Documentation/backends.md#vxlan

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/windows-networking/

### PR DESCRIPTION
**Pull request by Aaina26**
Fixes #46458

### CODE REVIEW

**Comment by jayunit100** [comment]
Wow thanks ! I wonder if for overlay we should also add antrea and calico ?

**Comment by jayunit100** [comment]
Either way this can merge I think..... will let the docs folks take it from here.

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for the fix!

/approve

**Pull request merged**
