### PR TITLE
update shortcode branch name

### PR DESCRIPTION
**Pull request by Arhell**
sycn PR https://github.com/kubernetes/website/pull/24994
this issue https://github.com/kubernetes/website/issues/24973

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-25047--kubernetes-io-master-staging.netlify.app/ko/docs/contribute/new-content/overview/#%EC%82%AC%EC%9A%A9%ED%95%A0-git-%EB%B8%8C%EB%9E%9C%EC%B9%98%EB%A5%BC-%EC%84%A0%ED%83%9D%ED%95%9C%EB%8B%A4
/assign @pjhwa
/assign @ianychoi

**Review by sftim — COMMENTED** [review]
/lgtm

@kubernetes/sig-docs-ko-reviews what branch should this change target?

**Comment by pjhwa** [comment]
> /lgtm
> 
> @kubernetes/sig-docs-ko-reviews what branch should this change target?

dev-1.19-ko.5
Thank you, @sftim, @Arhell

**Comment by seokho-son** [comment]
In case of Korean l10n, we have a dev-branch for contribution. 
However, since this PR is a simple bug fix, I'd like to approve this PR for the master branch.
Thank you for the contribution!!
/approve

**Pull request merged**
