### PR TITLE
[ja] Update `content/ja/docs/home/_index.md`

### LINKED ISSUE #44616: [ja] Update `content/ja/docs/home/_index.md`
**This is a Feature Request**

Update `content/ja/docs/home/_index.md`

**Why is this needed**

Many people view this page.  Updating the links on this page is useful for many people.

**Comments**

/assign
/language ja
/area localization

### PR DESCRIPTION
**Pull request by Okabe-Junya**
close #44616 

## Change List

- Update `content/ja/docs/home/_index.md`
    - Updated some links and their descriptions

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
The target page on the deploy preview:

- https://deploy-preview-44619--kubernetes-io-main-staging.netlify.app/ja/docs/home/

**Review by nasa9084 — COMMENTED** [review]
/approve
Thank you~

**Review by ydFu — APPROVED** [review]
/lgtm

**Pull request merged**
