### PR TITLE
[ja] Fix the description of Service External IPs to match the YAML ex…

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/39768/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
This change is in sync with English PR
/lgtm

**Comment by atoato88** [comment]
LGTM

**Review by nasa9084 — COMMENTED** [review]
sorry to be late~
/approve

**Comment by nasa9084** [comment]
ah sorry we may need to update the manifest as well

**Pull request merged**
