### PR TITLE
containerd configuration improvement

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/website/issues/22858

### CODE REVIEW

**Comment by pjhwa** [comment]
#22591 
After merging PR which fixes the problem for language/en, and then language/ko will accept this PR. 
Thank you very much.

**Comment by pjhwa** [comment]
The content of this PR has applied with #23827 .
Thank you for your contribution, @npu21

**Comment by seokho-son** [comment]
This issue has been handled by #23827 (in terms of Ko team branch management).
I am going to close this PR. Thank you for your contribution. @npu21

**Pull request closed without merging**
