### PR TITLE
[zh] sync using-api/server-side-apply.md

### PR DESCRIPTION
**Pull request by guzj11**
#25155

### CODE REVIEW

**Comment by tengqm** [comment]
Wait ... @zhaojizhuang is working on a batch update for this, https://github.com/kubernetes/website/issues/25247#issuecomment-734663537

Please help see if there are other files you can help sync? #25247

**Comment by helight** [comment]
LGTM

**Comment by zhaojizhuang** [comment]
> Wait ... @zhaojizhuang is working on a batch update for this, [#25247 (comment)](https://github.com/kubernetes/website/issues/25247#issuecomment-734663537)
> 
> Please help see if there are other files you can help sync? #25247

@guzj11 yeah...,I'm working on `using-api` series now, you can try some other files

**Comment by tengqm** [comment]
This is a happy accident. Let's figure out how we can avoid conflicts so that we can use our passions/time more efficiently.

**Comment by guzj11** [comment]
got it

**Pull request closed without merging**
