### PR TITLE
Update encrypt-data.md

### PR DESCRIPTION
**Pull request by BRONSOLO**
Fix as ---> at typo

Small typo fix.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@BRONSOLO Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Comment by Shubham82** [comment]
Thanks, @BRONSOLO 
The preview looks good
https://deploy-preview-44776--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/encrypt-data/#cleanup-all-secrets-encrypted

/lgtm

**Review by kundan2707 — COMMENTED** [review]
@BRONSOLO  thanks for correction.

**Pull request merged**
