### PR TITLE
Fix for namespace not specified in example yaml 

### PR DESCRIPTION
**Pull request by tamilselvan1102**
Issue: [#42772](https://github.com/kubernetes/website/issues/42772)

### CODE REVIEW

**Comment by tamilselvan1102** [comment]
Mentioning namespace in the yaml file would give clear understanding for readers than keep as a parameter in the kubectl command

**Comment by tamilselvan1102** [comment]
preview page: https://deploy-preview-42824--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/

**Comment by tengqm** [comment]
I don't think specifying namespace in a manifest is the recommended practice.

**Comment by tamilselvan1102** [comment]
As per below statement,  Most often k8s objects information are provide in .Yaml file  
https://kubernetes.io/docs/concepts/overview/working-with-objects/#describing-a-kubernetes-object

**Comment by tengqm** [comment]
> As per below statement, Most often k8s objects information are provided in .Yaml file https://kubernetes.io/docs/concepts/overview/working-with-objects/#describing-a-kubernetes-object

No. You will provide the name of the API object in the YAML, together with some labels, annotations etc. You typically don't provide namespace in the YAML. You switch between namespaces using `kubectl` contexts. You create and operate resources under your current namespace. Leaving namespace out of the YAML makes the manifest portable across namespaces. Or else, you have an assumption that the namespace must exist before you create a resource.

**Comment by tamilselvan1102** [comment]
Thank you for the details information. Completely agreed.

**Pull request closed without merging**
