### PR TITLE
zookeeper.md - remove extra "to"

### PR DESCRIPTION
**Pull request by amosshapira**

### CODE REVIEW

**Comment by harshitasao** [comment]
Thanks!
/lgtm

**Comment by amosshapira** [comment]
> Thanks! /lgtm

Thanks for the `/lgtm` but the instructions say that only `/approve` is accepted...

**Review by Arhell — COMMENTED** [review]
/lgtm

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Pull request merged**
