### PR TITLE
[ja] Updated content/ja/docs/concepts/workloads/pods/_index.md file

### PR DESCRIPTION
**Pull request by ziyi-xie**
There are several updates in [the original English text](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/workloads/pods/_index.md) and therefore this page is outdated.
This PR updated Japanese translation for the [content/ja/docs/concepts/workloads/pods/_index.md](https://kubernetes.io/ja/docs/concepts/workloads/pods/) file.

Fixes https://github.com/kubernetes/website/issues/35828

### CODE REVIEW

**Comment by t-inu** [comment]
The original page has "Pod update and replacement" section between "Pod templates" and "Resource sharing and communication".
It looks like this section should be added to the Japanese page as well.

ref: https://github.com/kubernetes/website/pull/25756

**Comment by ziyi-xie** [comment]
> The original page has "Pod update and replacement" section between "Pod templates" and "Resource sharing and communication". It looks like this section should be added to the Japanese page as well.
> 
> ref: #25756

Thank you for your kind instruction! I will go check it right away.

**Comment by ziyi-xie** [comment]
/retitle [WIP][ja] Updated content/ja/docs/concepts/workloads/pods/_index.md file

**Comment by ziyi-xie** [comment]
/retitle [ja] Updated content/ja/docs/concepts/workloads/pods/_index.md file

**Comment by nasa9084** [comment]
/assign
/approve
but I'm not sure we should use `{{< skew currentVersion >}}` in Japanese page (because actually sometimes Japanese pages are not well-maintained... sadly though)

**Comment by ziyi-xie** [comment]
> /assign /approve but I'm not sure we should use `{{< skew currentVersion >}}` in Japanese page (because actually sometimes Japanese pages are not well-maintained... sadly though)
@nasa9084 Thank you for your approval! 
And regarding `{{< skew currentVersion >}}`, could I ask that what would happen if I still use this piece of code and didn't maintain these pages on time? I thought it will change automatically when there's new kubernetes version come out. Thank you so much!

**Comment by ziyi-xie** [comment]
/cc @t-inu @atoato88 
Hi! I've updated Japanese translation for the [content/ja/docs/concepts/workloads/pods/_index.md](https://kubernetes.io/ja/docs/concepts/workloads/pods/) file., would you mind checking if everything looks alright at your convenience time please?

**Comment by nasa9084** [comment]
> And regarding {{< skew currentVersion >}}, could I ask that what would happen if I still use this piece of code and didn't maintain these pages in time? I thought it will change automatically when there's new kubernetes version come out. Thank you so much!

Yes, as you said, it will change automatically when there's a new kubernetes version, even the document is not updated.
so, my concern is, if `.spec.os.name` field affects scheduling with a new kubernetes version and this page is not updated, the page will say "the field won't affect scheduling with THE NEW VERSION"....
anyway, I can go as it is for now

**Review by t-inu — COMMENTED** [review]
I reviewed and left comments.

**Comment by ziyi-xie** [comment]
> > And regarding {{< skew currentVersion >}}, could I ask that what would happen if I still use this piece of code and didn't maintain these pages in time? I thought it will change automatically when there's new kubernetes version come out. Thank you so much!
> 
> Yes, as you said, it will change automatically when there's a new kubernetes version, even the document is not updated. so, my concern is, if `.spec.os.name` field affects scheduling with a new kubernetes version and this page is not updated, the page will say "the field won't affect scheduling with THE NEW VERSION".... anyway, I can go as it is for now

@nasa9084 Thank you so much for your detailed explanation!

**Comment by atoato88** [comment]
It's LGTM.
Should I add ltgm label or wait for adding lgtm tag by other reviewers?

**Comment by atoato88** [comment]
BTW, I agree with the topic about `{{< skew currentVersion >}}` spoken here.
And an original English contents have also ` {{< skew currentVersion >}}`, so it's a same situation both of EN and JP(and maybe also same with other language).

**Comment by t-inu** [comment]
Looks good!
/lgtm

**Comment by atoato88** [comment]
LGTM too :smile:

**Pull request merged**
