### PR TITLE
Updated the badges 

### PR DESCRIPTION
**Pull request by heysagnik**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by sftim** [comment]
Hi. This PR is too large (2392 commits) and targets the wrong branch.

Would you like help to learn about fixing that @heysagnik ?

/hold

**Comment by heysagnik** [comment]
> Hi. This PR is too large (2392 commits) and targets the wrong branch.
> 
> Would you like help to learn about fixing that @heysagnik ?
> 
> /hold

Yeah definitely, guide me  @sftim

**Comment by reylejano** [comment]
Hi,

This PR looks like its syncing the `main` branch from when you last pulled into the `dev-1.22-hi.1` branch along with your desired changes to the `dev-1.22-hi.1` branch.

I'm going to close this for now, if you would like to fix this PR, feel free to reopen the PR with `/reopen` in a comment

To create a new PR, on your local clone of your fork, checkout the `dev-1.22-hi.1` and create a new branch based on `dev-1.22-hi.1` then apply your changes or cherry-pick your changes in the new branch and create a PR

/close

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de en es fr id it ja ko pl pt uk vi zh
/remove-sig release

**Pull request closed without merging**
