### PR TITLE
Fix markdown syntax error

### PR DESCRIPTION
**Pull request by dcoliversun**
*XX*+space = Italic

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
There is a similar problem in line 206. Can you fix it together?
```
*内核监视器（Kernel Monitor）*是节点问题检测器中支持的系统日志监视器守护进程。
内核监视器观察内核日志并根据预定义规则检测已知的内核问题。
```

**Comment by dcoliversun** [comment]
> There is a similar problem in line 206. Can you fix it together?
> 
> ```
> *内核监视器（Kernel Monitor）*是节点问题检测器中支持的系统日志监视器守护进程。
> 内核监视器观察内核日志并根据预定义规则检测已知的内核问题。
> ```

OK, I'll pull new request.

**Comment by dcoliversun** [comment]
> There is a similar problem in line 206. Can you fix it together?
> 
> ```
> *内核监视器（Kernel Monitor）*是节点问题检测器中支持的系统日志监视器守护进程。
> 内核监视器观察内核日志并根据预定义规则检测已知的内核问题。
> ```

OK, Done !

**Pull request merged**
