### PR TITLE
Add information about InTreePluginAzureFileUnregister and InTreePlugi…

### PR DESCRIPTION
**Pull request by miteshskj**
Add information about the InTreePluginAzureFileUnregister and InTreePluginAzureDiskUnregister feature gate.
Fixes https://github.com/kubernetes/website/issues/32689

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Markdown LGTM

**Comment by sftim** [comment]
@kubernetes/sig-storage-pr-reviews could you give this a once-over for technical accuracy?

**Comment by mehabhalodiya** [comment]
enhancement ref: https://github.com/kubernetes/enhancements/issues/1885
/assign @didicodes

**Comment by jsafrane** [comment]
/lgtm
from storage point of view

**Review by sftim — COMMENTED** [review]
Thanks
/approve

**Pull request merged**
