### PR TITLE
Add admonition type to shortcode

### PR DESCRIPTION
**Pull request by lucperkins**
In response to issue #9397.

This is mostly done but I'll need to wait on the current multilingual work (so that we can rely on language-specific terms for "note," "caution", etc.).

### CODE REVIEW

**Comment by zacharysarah** [comment]
@lucperkins Thanks for this, it's a nice quality of life improvement. I'm happy to approve it when you're ready. 👍

**Comment by zacharysarah** [comment]
@lucperkins Ping--looks like #10355 (and any dependent PRs it spawns) is the last of the language-related PRs. Pending merge conflict resolution, is this PR still good to go?

**Comment by lucperkins** [comment]
@zacharysarah This is good to go. In the future I'd like to use localized terms for "note," "caution," etc. but I think we can punt on that, as the Chinese repo, for one, was already using the English terms and the others may be as well.

**Comment by lucperkins** [comment]
@zparnold Okay, this is once again ready to go.

**Comment by zacharysarah** [comment]
@lucperkins 👋 Good grief, looks like previous `/approve` comments didn't take. If you resolve the merge conflicts _again_, I'll make it so that this PR can merge with a simple `/lgtm` and `/hold cancel`.

/approve
/hold

**Comment by zacharysarah** [comment]
@lucperkins 👋 Ping

**Comment by lucperkins** [comment]
@zacharysarah Done!

**Pull request merged**
