### PR TITLE
Fix en language misspell

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
If possible, i want to add tools:

- check spell for en
- clean up white noise for all markdown files

**Comment by daixiang0** [comment]
@sftim can i add a tool for all markdown files to clean up white noise in other PR?

**Comment by sftim** [comment]
> @sftim can i add a tool for all markdown files to clean up white noise in other PR?
How about opening an issue to describe the improvement? That'd be a good place to put the discussion.

**Comment by kbhawkey** [comment]
@daixiang0 , Thank you for fixing the spelling errors. I reviewed the spelling changes in detail.
It would be best to limit cleanup of white space changes to one or two files per PR.
Sometimes the formatting of the page can be affected and reviewing the changes can take an extended period of time.

A couple of previews:

https://deploy-preview-18201--kubernetes-io-master-staging.netlify.com/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

https://deploy-preview-18201--kubernetes-io-master-staging.netlify.com/docs/setup/production-environment/windows/intro-windows-in-kubernetes/

**Comment by daixiang0** [comment]
@kbhawkey thanks for review, i would limit files sum in PRs and be careful about changes in web page.

**Comment by kbhawkey** [comment]
👍

**Pull request merged**
