### PR TITLE
Removed the link of Obsolete online interactive tutorial in the Confi…

### PR DESCRIPTION
**Pull request by sandy-ai-arch**
Removed the link for Obsolete online interactive tutorial in the Configuring a Java Microservice page for kubernetes documentation

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
@sandy-krishna-ai Thanks for this change. But this is in alignment with what we had planned for.

Reference discussion items/PRs/issues:
#40306
#40292
#33936

**Comment by divya-mohan0209** [comment]
Commented on the issue #42401 , however leaving it here for the visibility of other reviewers and approvers

"Hello folks, thank you for bringing this up!

The link you all are trying to drop is from a tutorial page itself, which in turn, redirects to another tutorial page that is interactive in nature.

Removal of the interactive tutorial section will not benefit this page UNLESS somebody is willing to rewrite the whole page to remove all mentions of the interactive tutorial in it & make the overall text seem sensible.

If that seems like something you want to attempt, I'd be happy to see those changes suggested over a PR.

But the changes to just remove the section as a quick fix will not fit the flow of the document, IMO."

**Comment by sftim** [comment]
We shouldn't make this change. @sandy-krishna-ai what are your plans for this PR?

We can close this for you if you are not sure how to adjust this to something we could merge.

**Comment by sandy-krishna-ai** [comment]
@sftim 
Could you please assist me here, 
Kind of stuck, Not sure how to proceed further!
Note: I am a first time contributor on Kubernetes

**Comment by sftim** [comment]
Try this:
- delete Configuring a Java Microservice page
- edit other pages not to link to that page

**Comment by sandy-krishna-ai** [comment]
@sftim, Thanks for helping me out!
I have removed the page configuring a java microservice & I can't see any other pages linked to this page
Please have a look at latest commit

**Comment by AmarNathChary** [comment]
Please squash your PR into a single commit

**Comment by nate-double-u** [comment]
I suggest we remove the entire "Objectives" section in `content/en/docs/tutorials/configuration/external-configuration-using-microprofile.md` rather than just removing the link to the old tutorial.

**Comment by sftim** [comment]
I think we ought to remove https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/ entirely.

Does that seem reasonable?

**Comment by kbhawkey** [comment]
Hello @sandy-ai-arch .
Do you have more changes to add?

**Comment by kbhawkey** [comment]
Let's hold this pull request. After the changes, I'm not clear on the focus of the tutorial page.
/hold

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-42495--kubernetes-io-main-staging.netlify.app/docs/tutorials/configuration/external-configuration-using-microprofile/

**Comment by divya-mohan0209** [comment]
Hello @sandy-ai-arch , I'll be closing off this PR since there isn't any response from your end since August. Please note that if you have the bandwidth to advise on the suggestions above, we'd be happy to pick this up where we left off and you just need to issue the /reopen command to do so.
/approve

**Comment by divya-mohan0209** [comment]
Mistaken approve command issued there, my bad.
/close

**Pull request closed without merging**
