### PR TITLE
Add SIG API Machinery spotlight

### PR DESCRIPTION
**Pull request by fsmunoz**
Add SIG API Machinery spotlight.

The `contributor-site`  original is here: https://github.com/kubernetes/contributor-site/pull/505 . Please provided feedback/reviews in that repository, unless it's about `website` specific things (like differences in formatting). 

I will remove the WIP tag when the `contributor-site` article is reviewed, and sync the content here.

### CODE REVIEW

**Comment by sftim** [comment]
/hold

This needs:
- assigned **future** publication date
- LGTM from a blog reviewer

OK to unhold once:
- we have those
- the associated contributor blog PR has LGTM

**Comment by fsmunoz** [comment]
Updated publication date for next week.

**Pull request merged**
