### PR TITLE
Update OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by Rajakavitha1**
added rajakavitha1 to the owners list

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.13-ko.<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by Bradamant3** [comment]
/lgtm

with a reminder to all of us to be careful about any changes to technical information. There's the `/sig` command to help identify tech reviewers -- most sigs have aliases that let us assign out without specifying an individual. Welcome Rajie!

**Comment by Rajakavitha1** [comment]
> 
> 
> /lgtm
> 
> with a reminder to all of us to be careful about any changes to technical information. There's the `/sig` command to help identify tech reviewers -- most sigs have aliases that let us assign out without specifying an individual. Welcome Rajie!

Thank you so much @Bradamant3 . Yes, I will be careful about the changes to technical information.

**Pull request merged**
