### PR TITLE
Follow the style guide

### PR DESCRIPTION
**Pull request by makocchi-git**

### CODE REVIEW

**Comment by makocchi-git** [comment]
[preview is here](https://deploy-preview-12760--kubernetes-io-master-staging.netlify.com/docs/concepts/workloads/pods/init-containers/)
[original](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)

**Comment by DanyC97** [comment]
nice, right on time with my PR #12783

**Comment by Rajakavitha1** [comment]
Thanks for the PR @makocchi-git . There is a PR that addresses the consistency in code formatting. https://github.com/kubernetes/website/pull/12783. I am closing this PR for now.
Please feel free to open the PR after the recommended guidelines in https://github.com/kubernetes/website/pull/12783. are approved.

**Pull request closed without merging**
