### PR TITLE
[ja] Fix broken links due to using githubbranch param

### LINKED ISSUE #31680: [ja] Broken links due to using "githubbranch" param
**This is a Bug Report**

**Problem:**
Regarding https://github.com/kubernetes/website/issues/31248, I found the similar broken links on other pages.

English pages have already been fixed. ref: https://github.com/kubernetes/website/pull/29311
Japanese pages also need to be fixed.

**Proposed Solution:**
* Fixes broken links including `{{< param "githubbranch" >}}` to `master`.
* In the case of link to https://releases.k8s.io/, fixes to `{{< param "fullversion" >}}`.
  * ref: https://github.com/kubernetes/website/pull/29311#discussion_r685845250

**Page to Update:**
<details>
<summary>These pages</summary>

https://kubernetes.io/ja/docs/setup/best-practices/multiple-zones/
https://kubernetes.io/ja/docs/setup/production-environment/turnkey/aws/
https://kubernetes.io/ja/docs/setup/production-environment/turnkey/gce/
https://kubernetes.io/ja/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
https://kubernetes.io/ja/docs/tasks/configure-pod-container/configure-projected-volume-storage/
https://kubernetes.io/ja/docs/concepts/containers/container-environment/
https://kubernetes.io/ja/docs/concepts/cluster-administration/manage-deployment/
https://kubernetes.io/ja/docs/concepts/workloads/controllers/statefulset/
https://kubernetes.io/ja/docs/concepts/configuration/overview/
https://kubernetes.io/ja/docs/concepts/services-networking/service/
https://kubernetes.io/ja/docs/concepts/services-networking/connect-applications-service/
https://kubernetes.io/ja/docs/tutorials/stateful-application/basic-stateful-set/

</details>

**File to Update:**
<details>
<summary>These files</summary>

```
https://github.com/kubernetes/website/blob/main/content/ja/docs/setup/best-practices/multiple-zones.md
これは、より範囲の広いCluster Federationの軽量バージョンです(以前は["Ubernetes"](https://github.com/kubernetes/community/blob/{{< param "githubbranch" >}}/contributors/design-proposals/multicluster/federation.md)の愛称で言及されていました)。

https://github.com/kubernetes/website/blob/main/content/ja/docs/setup/production-environment/turnkey/aws.md
"Guestbook"アプリケーションは、Kubernetesを始めるもう一つのポピュラーな例です: [guestbookの例](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/guestbook/)
より完全なアプリケーションについては、[examplesディレクトリ](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/)を参照してください。

https://github.com/kubernetes/website/blob/main/content/ja/docs/setup/production-environment/turnkey/gce.md
For more complete applications, please look in the [examples directory](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/).  The [guestbook example](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/guestbook/) is a good "getting started" walkthrough.

https://github.com/kubernetes/website/blob/main/content/ja/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
[server.go](https://github.com/kubernetes/kubernetes/blob/{{< param "githubbranch" >}}/test/images/agnhost/liveness/server.go)

https://github.com/kubernetes/website/blob/main/content/ja/docs/tasks/configure-pod-container/configure-projected-volume-storage.md
* [all-in-oneボリューム](https://github.com/kubernetes/community/blob/{{< param "githubbranch" >}}/contributors/design-proposals/node/all-in-one-volume.md)のデザインドキュメントを読む

https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/containers/container-environment.md
サービスは専用のIPアドレスを持ち、[DNSアドオン](http://releases.k8s.io/{{< param "githubbranch" >}}/cluster/addons/dns/)が有効の場合、DNSを介してコンテナで利用可能です。

https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/cluster-administration/manage-deployment.md
例えば、異なるアプリケーション間では、異なる`app`ラベルを使用したり、[ゲストブックの例](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/guestbook/)のようなマルチティアーのアプリケーションでは、各ティアーを区別する必要があります。frontendというティアーでは下記のラベルを持ちます。:

https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/workloads/controllers/statefulset.md
* 提供されたPodのストレージは、要求された`storage class`にもとづいて[PersistentVolume Provisioner](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/staging/persistent-volume-provisioning/README.md)によってプロビジョンされるか、管理者によって事前にプロビジョンされなくてはなりません。

https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/configuration/overview.md
- `{ app: myapp, tier: frontend, phase: test, deployment: v3 }`のように、アプリケーションまたはデプ ロイメントの __セマンティック属性__ を識別する[ラベル](/ja/docs/concepts/overview/working-with-objects/labels/)を定義して使いましょう。これ らのラベルを使用して、他のリソースに適切なPodを選択できます。例えば、すべての`tier：frontend`を持つPodを選択するServiceや、`app：myapp`に属 するすべての`phase：test`コンポーネント、などです。このアプローチの例を知るには、[ゲストブック](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/guestbook/)アプリも合わせてご覧ください。

https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/services-networking/service.md
[makeLinkVariables関数](https://releases.k8s.io/{{< param "githubbranch" >}}/pkg/kubelet/envvars/envvars.go#L72)を確認してください)や、より簡単な`{SVCNAME}_SERVICE_HOST`や、`{SVCNAME}_SERVICE_PORT`変数をサポートします。この変数名で使われるService名は大文字に変換され、`-`は`_`に変換されます。

https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/services-networking/connect-applications-service.md
前者はそのまま使用でき、後者は[CoreDNSクラスタアドオン](https://releases.k8s.io/{{< param "githubbranch" >}}/cluster/addons/dns/coredns)を必要とします。
これらはすべて[nginx httpsの例](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/staging/https-nginx/)から取得できます。
- [nginxサーバー](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/staging/https-nginx/default.conf)はポート80のHTTPトラフィックと443のHTTPSトラフィックを処理し、nginx Serviceは両方のポート を公開します。

https://github.com/kubernetes/website/blob/main/content/ja/docs/tutorials/stateful-application/basic-stateful-set.md
* [PersistentVolumeのプロビジョニング](https://github.com/kubernetes/examples/tree/{{< param "githubbranch" >}}/staging/persistent-volume-provisioning/)
```

</details>

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #31680

### CODE REVIEW

**Review by nasa9084 — COMMENTED** [review]
/approve

**Comment by t-inu** [comment]
11 files changed are OK.
However, the following file is missing. This is also listed in https://github.com/kubernetes/website/issues/31680.
```
https://github.com/kubernetes/website/blob/main/content/ja/docs/concepts/containers/container-environment.md
サービスは専用のIPアドレスを持ち、[DNSアドオン](http://releases.k8s.io/{{< param "githubbranch" >}}/cluster/addons/dns/)が有効の場合、DNSを介してコンテナで利用可能です。
```

**Comment by championshuttler** [comment]
@t-inu done thanks for review

**Comment by t-inu** [comment]
@championshuttler Thanks for the quick response!
/lgtm

**Pull request merged**
