### PR TITLE
Fix broken link to KEP doc in `data/user-personas/contributors/code-contributor.yaml`

### PR DESCRIPTION
**Pull request by amolmote**
Signed-off-by: amolmote <amolmote201@gmail.com>

Fixex #36721 
Updated the link of KEP process from outdated to latest one.

### CODE REVIEW

**Comment by mtardy** [comment]
/retitle Fix broken link to KEP doc in `data/user-personas/contributors/code-contributor.yaml`

**Comment by mtardy** [comment]
Thanks for the PR! Same comment as [here](https://github.com/kubernetes/website/issues/36721#issuecomment-1245166195), I struggled to find how this data is used on the website, if anybody knows!

/lgtm

**Comment by amolmote** [comment]
thank you @mtardy

**Comment by amolmote** [comment]
@mtardy, you mean how this yml manifest is being used in website?

**Comment by mtardy** [comment]
> @mtardy, you mean how this yml manifest is being used in website?

Yes, do you have any examples of templates or web pages where it's used? How did you discover the issue?

**Comment by amolmote** [comment]
@sftim need approval to merge this pr

**Comment by mtardy** [comment]
Note that related or not to the mergeability of this PR, we should definitely investigate if this stuff is still used or not, and remove it instead of maintaining useless data.

**Comment by amolmote** [comment]
yeah that's true, we should investigate this

**Comment by amolmote** [comment]
you can hold this PR @mtardy  if you want

**Comment by amolmote** [comment]
@mtardy could you please approve this PR as our discussion is over, and we already conclude this that yaml are being in used.

**Comment by mtardy** [comment]
> @mtardy could you please approve this PR as our discussion is over, and we already conclude this that yaml are being in used.

I cannot as I am not a reviewer and I don't think we have concluded that this file is used, I'm quite still convinced of the contrary.

**Pull request closed without merging**
