### PR TITLE
Adjust HTML generated for announcements

### LINKED ISSUE #21788: adjust integration of announcement banners
**This is a Feature Request**
The HTML partials, announcements.html and frontpage-announcements.html, contain
a `main` element which duplicates the `main` element found in the body of the page.

This became an issue as the docsy theme updates page anchors in the script `anchors.js`.
https://github.com/google/docsy/blob/master/assets/js/anchor.js
This script depends upon the `main` element and failed to find the H1 - H6 level headings on
the page to udpate.

**What would you like to be added**
Investigate how to include the announcement banner on the docs pages (front page, docs, blog, and so on) without the `main` element. Investigate changes to the corresponding stylesheet.

**Why is this needed**
Clean up or adjust the preexisting, related code as well as the current templates and stylesheet.
Provide a flexible way to add and remove content such as announcement or banners on the pages.

**Comments**
For additional information, see PR #21780.

### LINKED ISSUE #22036: Announcement banner now in Google search snippets
The announcement banner text (merged in #21505) is being used as the Google search snippet for docs pages.  This may not have been your intention.

https://www.google.com/search?q=kubernetes+cluster+bootstrapping

image

### PR DESCRIPTION
**Pull request by sftim**
Mark front page announcements as `<aside>` elements

This matches the HTML that gets generated for announcements on the rest of the site. It helps avoid search engines treating the announcement banner as the primary content of the web page.

Spotted during triage for issue #22036.

Fixes #22036.
Fixes #21788.

### CODE REVIEW

**Comment by kbhawkey** [comment]
As part of this PR, would you add the attribute, `data-nosnippet`?
Related issue #22036.
/hold

**Comment by sftim** [comment]
/retitle [WIP] Adjust HTML generated for announcements

**Comment by sftim** [comment]
Related to #21788

**Comment by celestehorgan** [comment]
Is this still on hold?

**Comment by kbhawkey** [comment]
/hold cancel
Thanks @sftim

**Comment by kbhawkey** [comment]
As an aside (😄 ), the front page has a better margin for the text in the announcement.
The other pages have a small left hand margin. I don't remember what the margin looked like when the announcement was first added. The Case Studies page announcement looks better.
Should open another issue to address the styling.
Thanks.
/approve

**Comment by kbhawkey** [comment]
@sftim, I noticed that this pr closed (automatically) a couple of issues.
This worked, but are there any follow-on issues (release/merging)?

**Comment by sftim** [comment]
I don't see any further work - if I've missed something then feel free (anyone!) to point it out.

**Pull request merged**
