### PR TITLE
Adding references to page for better understanding

### PR DESCRIPTION
**Pull request by rajeshdeshpande02**
Adding all required reference links to the page for better navigations to understand related concepts.

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
This change LGTM. I'd like to defer to sig-apps folks for a lgtm label.
/approve
also
/cc @janetkuo @erictune

**Comment by rajeshdeshpande02** [comment]
Hi @janetkuo , @erictune, Can you please review it. This is already approved.

**Pull request merged**
