### PR TITLE
Add statefulsets for ID localization.

### PR DESCRIPTION
**Pull request by irvifa**
Addresses #15341

### CODE REVIEW

**Comment by irvifa** [comment]
Address https://github.com/jk8s/sig-docs-id/issues/17

**Comment by irvifa** [comment]
Related to https://github.com/jk8s/sig-docs-id/issues/17

**Comment by girikuncoro** [comment]
I have reviewed this but it is currently blocked, because everytime I submit my PR review comments (77 comments and suggested changes), github is crying, any idea how to fix? most likely hit by this issue: https://github.com/envoyproxy/envoy/issues/3125

**Comment by girikuncoro** [comment]
@irvifa looking good, thanks for your continuous contribution to kubernetes docs and community! 🎉 

/lgtm
/approve

**Pull request merged**
