### PR TITLE
update link in page access-cluster

### PR DESCRIPTION
**Pull request by gaoguangze111**
Update two links in page access-cluster.md. Page updated: https://kubernetes.io/zh/docs/tasks/access-application-cluster/access-cluster/

### CODE REVIEW

**Comment by howieyuen** [comment]
/lgtm
Thanks for the contribution

**Comment by tengqm** [comment]
Can we do a more complete PR?

```
./scripts/linkchecker.py -l zh -f /docs/tasks/access-application-cluster/access-cluster.md
Language: zh
File: content/zh/docs/tasks/access-application-cluster/access-cluster.md
    /docs/user-guide/kubectl-cheatsheet: Link using redirect records, should use /docs/reference/kubectl/cheatsheet/ instead
    /docs/user-guide/kubectl-overview: Link using redirect records, should use /docs/reference/kubectl/overview/ instead
    /docs/admin/accessing-the-api: Link using redirect records, should use /docs/reference/access-authn-authz/controlling-access/ instead
    /docs/concepts/cluster-administration/authenticate-across-clusters-kubeconfig/: Link using redirect records, should use /docs/tasks/access-application-cluster/configure-access-multiple-clusters/ instead
    /docs/concepts/cluster-administration/authenticate-across-clusters-kubeconfig/: Link using redirect records, should use /docs/tasks/access-application-cluster/configure-access-multiple-clusters/ instead
    /docs/reference/using-api/client-libraries/: Link not using localized page
    /docs/tasks/configure-pod-container/configure-service-account/: Link not using localized page
    /docs/admin/node: Link using redirect records, should use /docs/concepts/architecture/nodes/ instead
    /docs/user-guide/pods: Link using redirect records, should use /docs/concepts/workloads/pods/ instead
    /docs/user-guide/services: Link using redirect records, should use /docs/concepts/services-networking/service/ instead
    /docs/user-guide/services: Link using redirect records, should use /docs/concepts/services-networking/service/ instead
    /docs/concepts/services-networking/service/#ips-and-vips: Link not using localized page
```

**Comment by gaoguangze111** [comment]
Updated more links

**Review by markthink — COMMENTED** [review]
/lgtm
/approve

**Review by tanjunchen — COMMENTED** [review]
/lgtm

**Comment by tengqm** [comment]
A big thank you.
/lgtm
/approve

**Pull request merged**
