### PR TITLE
Placeholder for maxUnavailable for StatefulSet

### PR DESCRIPTION
**Pull request by krmayankk**
Add documentation for maxUnavailable for StatefulSets

### CODE REVIEW

**Comment by SomtochiAma** [comment]
Hi @krmayankk! 

Thanks for opening a draft PR. The docs deadline is coming up on 23rd November(right after KubeCon NA) and we would appreciate it if you could get started on fleshing out the contents of the docs so it can be reviewed by Sig Docs before Kubecon and other events in November.

If you need any help getting the PR ready, please reach out to us on the #sig-docs channel on slack or tag me on this PR!

**Comment by annajung** [comment]
hi @@krmayankk this is no longer being tracked for 1.20 release.
Please see https://github.com/kubernetes/enhancements/issues/961#issuecomment-726538797 for details 
Feel free to reopen when an exception has been filed/approved. 

/milestone clear
/close

**Pull request closed without merging**
