### PR TITLE
[zh] Translate guestbook-logs-metrics-with-elk.md

### PR DESCRIPTION
**Pull request by yixin21**
zh-trans guestbook-logs-metrics-with-elk.md
ref:k8smeetup/website-tasks#3362

### CODE REVIEW

**Comment by tengqm** [comment]
@yixin21 pls rebase this onto master and see if the gate is happy then.

**Review by tanjunchen — COMMENTED** [review]
@yixin21
any update?

**Comment by tengqm** [comment]
Please feel free to reopen when you get cycles to continue this work.
/close

**Pull request closed without merging**
