### PR TITLE
[ko] Update nodes.md

### LINKED ISSUE #37426: [ko] Wrong translation of the term "cordoned"
Please note that:
**Contributor that opens a PR to resolve this issue should branch off the feature branch from `dev-1.25-ko.1`,
and set the merge target branch to `dev-1.25-ko.1` as well.**

---

**This is a Bug Report**

**Problem:**
In https://kubernetes.io/ko/docs/concepts/architecture/nodes/ ,
the term "cordoned" is translated as "코드화된", which is wrong.

**Proposed Solution:**
"코드화된" -> "통제된(cordoned)"

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/architecture/nodes/

/language ko

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
Closes #37426

### Chnaged proposed

Fix Wrong translation of "**cordoned**" as "**코드화된**", changed to the correct one - **통제된**

### CODE REVIEW

**Review by bishal7679 — APPROVED** [review]
Looks Good!

**Comment by seokho-son** [comment]
Hi @Pradumnasaraf 
Thank you for the contribution ! :)

#37426

> Please note that:
> Contributor that opens a PR to resolve this issue should branch off the feature branch from dev-1.25-ko.1,
> and set the merge target branch to dev-1.25-ko.1 as well.

Korean localization uses development branch.
Please change base branch :)

Also, this PR does not fully follow the proposed solution in #37426

> Proposed Solution:
> "코드화된" -> "통제된(cordoned)"

Please try to apply it when you update the base branch.

**Comment by seokho-son** [comment]
/hold

for the right target branch and base branch of this PR.

**Comment by Pradumnasaraf** [comment]
Hey, @seokho-son thank you for the instructions. I have corrected the docs. 

Base branch `dev-1.25-ko.1` as mentioned in the issue. Can you please guide what I am doing wrong?

**Comment by seokho-son** [comment]
@Pradumnasaraf 
Nothing wrong. :) Looks nice.

Could you squash the commits into one ?

https://kubernetes.io/docs/contribute/new-content/open-a-pr/#addressing-feedback-locally

**Comment by Pradumnasaraf** [comment]
Thank you for the help @seokho-son. Done, I have rebased the PR :).

**Comment by seokho-son** [comment]
Thank you @Pradumnasaraf , and welcome to Kubernetes !

/approve

**Comment by Pradumnasaraf** [comment]
> Thank you @Pradumnasaraf , and welcome to Kubernetes !
> 
> /approve

Thank you so much, Seokho. Looking forward to more contribution.

**Pull request merged**
