### PR TITLE
[it] Fix broken Netlify status badge link in README

### PR DESCRIPTION
**Pull request by dev-johnn**
I was going through the repo README files and found a broken Netlify status badge link in README-it.md. Fixed the badge link by using the value from the english README.md file. The badge now works.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The update looks good to me. Thanks!

/lgtm

**Review by Arhell — COMMENTED** [review]
/assign @Fale

**Review by dipesh-rawat — APPROVED** [review]
> /approve

Taking approval from https://github.com/kubernetes/website/pull/45727#issuecomment-2054010866

/approve

**Pull request merged**
