### PR TITLE
Convert CRLF to LF

### PR DESCRIPTION
**Pull request by mk46**
/kind cleanup feature
/language en
Part of https://github.com/kubernetes/website/issues/33898

### CODE REVIEW

**Comment by tengqm** [comment]
This PR is big in terms of "lines changed". Please confirm no changes have been introduced other than EOL characters.

/approve

**Comment by Sea-n** [comment]
Hey @mk46,

When we review PR, it's not about how you did it, but how could we know it's correct.

We all know `dos2unix` could do this job, but could you provide some method about how could we ensure no other modifications in this PR?

Many thanks for cleaning the historical mess, we are looking forward to merging this once the concern is solved! 👍

**Comment by Sea-n** [comment]
Hey @mk46,

It's been two weeks since last response.

Could you provide some viable way to review this PR? We are all looking forward for this PR merged.

**Comment by mk46** [comment]
Hi @Sea-n, I used Vscode to verify the no-content changes. See example for `content/en/docs/tasks/administer-cluster/topology-manager.md`

Screenshot from 2022-08-03 09-58-02

I didn't find any red-green on the left corner of the attached image.
Looking for your LGTM.
Thanks!!

**Comment by mk46** [comment]
CI looks green.
PTAL.

**Comment by Sea-n** [comment]
This PR still can't convince me to put LGTM, maybe you can try to ask it in `#sig-docs` channel on Slack.

**Pull request merged**
