### PR TITLE
Add idealhack as a reviewer

### PR DESCRIPTION
**Pull request by idealhack**
I'd happily provide my review for Chinese docs.

sponsor:
/cc @zacharysarah

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
We don't have a sig-docs-cn-reviewers group yet.

**Comment by zacharysarah** [comment]
@idealhack After #14085 merges (tomorrow, hopefully!) we’ll have an alias for `sig-docs-zh-reviews`, which is where your new entry belongs in alphabetical order.

**Comment by idealhack** [comment]
Cool, I'll rebase this PR by then.

**Comment by zacharysarah** [comment]
@idealhack 👋 #10485 has merged. Please rebase so we can continue.

**Comment by idealhack** [comment]
@zacharysarah thanks, rebase done.

**Comment by zacharysarah** [comment]
@tengqm 👋 Would you please add @idealhack to https://github.com/orgs/kubernetes/teams/sig-docs-zh-reviews/members? Thanks in advance! 🙇

**Comment by idealhack** [comment]
@tengqm @zacharysarah Thank you!

**Pull request merged**
