### PR TITLE
kubectl  command for master node ready IP's  and the resource quota for each node

### PR DESCRIPTION
**Pull request by saiyam1814**
Kubectl command to get the internalIp's of the master nodes whose status is not Ready and kubectl command to get the resource quota for each node.

### CODE REVIEW

**Comment by bgrant0607** [comment]
Hi, @saiyam1814. I'm sorry it took so you to get you a response. We need to do a better job keeping reviewers up to date.

I'm sorry, but I don't think these two commands should be added to the cheatsheet. At minimum, more explanation would be required.

The first won't work on most/all managed Kubernetes services, and won't work on all Kubernetes distributions and bootstrapping tools, either. I assume you tested it on a kubeadm cluster.

As for the 2nd, the human-readable get and describe output isn't guaranteed to be stable. The command should use json/yaml output instead.

cc @seans3

**Comment by saiyam1814** [comment]
@bgrant0607  I will test the first one on different cluster right now I tested for kubeadm. the command above it also gives the external Ip, still if that dosent work we can write explicitly kubeadm ? 
for the second one it actually give a more human readable output (can you try it once ? ) . I feel it would be a good way to get resource quota quickly. Rest your call.

**Comment by zacharysarah** [comment]
Closing per @bgrant0607. ☝️ 

/close

**Pull request closed without merging**
