### PR TITLE
patooworld/kubernetes-website

### PR DESCRIPTION
**Pull request by patooworld**

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@patooworld Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Comment by dipesh-rawat** [comment]
@patooworld Also, would be helpful if you could provide details and clarification on the reasoning behind this change in the [PR description](https://github.com/kubernetes/website/pull/44102#issue-2011861695). Without that information, it becomes challenging to provide any feedback.

**Comment by sftim** [comment]
/hold

Within this project, we default to not using GitHub Actions.

**Comment by divya-mohan0209** [comment]
Hello @patooworld , good day! Thank you for the PR and your contribution.

As noted above, we do not default to GitHub actions and require you to update your description with the changes you intend to propose via this PR.

Subsequently, we have seen a lot of activity on the PR but haven't seen any response from your end, due to which I'll be closing the PR.

Kindly consider reopening when you have the bandwidth to work on aforementioned comments.

/close

**Pull request closed without merging**
