### PR TITLE
CSI GA doc updates

### PR DESCRIPTION
**Pull request by msau42**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.13 Features: set Milestone to 1.13 and Base Branch to dev-1.13
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by tfogo** [comment]
Hi @msau42, can you please complete this PR as soon as you can and let us know when it's done? The docs deadline is approaching fast and we want to start reviews ASAP. Thanks!

**Comment by msau42** [comment]
Holding until we confirm backwards compatibility support

**Pull request merged**
