### PR TITLE
Bump up deployment version in folder tutorials/stateless-application

### PR DESCRIPTION
**Pull request by nashasha1**
I will create a bunch of PRs for bumping up deployment version.  A pr contains all changes in a folder.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7320)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@nashasha1 Under tutorials/stateless-application/, these files are no longer used in the docs. Please use this PR to delete them:

deployment-scale.yaml
deployment-update.yaml

This file is still used. So go ahead with the version bump:

deployment.yaml

**Comment by nashasha1** [comment]
@steveperry-53  Done. Thanks for help.

**Pull request merged**
