### PR TITLE
Update security contacts and approvers

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR updates lists of repo security contacts and approvers.

/assign @Bradamant3 @jaredbhatti @jimangel @kbarnard10

### CODE REVIEW

**Comment by zacharysarah** [comment]
@xiangpengzhao 👋 Apologies--you should have been on the approvers list already!

**Comment by jimangel** [comment]
/lgtm

I know I can approve, just feel like it'd be better coming from someone else; since it involves me / elevated access.

👀 @jaredbhatti @Bradamant3 😄

**Comment by xiangpengzhao** [comment]
@zacharysarah thanks for adding me to the list! :smile:

**Pull request merged**
