### PR TITLE
Update Hello Minikube tutorial to use Metrics Server and not Heapster

### LINKED ISSUE #18420: Improvement for k8s.io/docs/tutorials/hello-minikube/
Heapster is not available in the add on list. Maybe it needs to be added to the docker image.

### PR DESCRIPTION
**Pull request by BenHall**
Fixes #18420 

Replace Heapster usages with Metrics Server as Heapster is no longer available via Minikube.

### CODE REVIEW

**Comment by xichengliudui** [comment]
/LGTM
from Chinese

**Comment by inductor** [comment]
LGTM for Japanese

**Comment by ClaudiaJKang** [comment]
LGTM from Korean

**Comment by gochist** [comment]
Where simple substitutions are possible, as in this PR, it may be more efficient to modify several languages at once, but the general guidelines are:

> If a PR contains changes to source in more than one language, ask the PR contributor to open separate PRs for each language.
> 
> --from https://kubernetes.io/docs/contribute/intermediate/#working-with-localized-content

And if each localization team follows the guidelines below, submitting a PR only for English documents will eventually be reflected in other languages.
> At the beginning of every team milestone, it’s helpful to open an issue comparing upstream changes between the previous development branch and the current development branch.
> 
> --from https://kubernetes.io/docs/contribute/localization/#branching-strategy

**Comment by BenHall** [comment]
Thanks @gochist - Happy to close and raise on a English PR. Let me know the preference.

**Comment by gochist** [comment]
Thanks @BenHall . I prefer to follow the guidelines.

**Comment by php-coder** [comment]
The changes to Russian translation has been cherry-picked there: #18611

**Pull request closed without merging**
