### PR TITLE
Update device-plugins.md

### PR DESCRIPTION
**Pull request by ahalim-intel**
adding SRIOV Network device plugin in Examples section.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.11 Features: set Milestone to 1.11 and Base Branch to release-1.11
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by ahalim-intel** [comment]
@xiangpengzhao @tengqm Could you please recheck and approve the PR? Thanks

**Comment by zacharysarah** [comment]
Thanks for the review, @tengqm. I see nothing specific to 1.11, so I think we can merge to master.

/lgtm
/approve

**Comment by zacharysarah** [comment]
@ahalim-intel Please sign the CLA in order to proceed.

**Comment by ahalim-intel** [comment]
@zacharysarah I've signed the CLA for some reason it's not picking it up here. Possibly because I signed up after this PR was submitted. Please advise how to resolve this. Signed doc can be viewed [here](https://identity.linuxfoundation.org/system/files/clas/signed/cla_individual-274d30cd70969ed368408362ec44b96acf465c61.pdf)

**Comment by tengqm** [comment]
/lgtm
/approve

Approve again since the CLA check passed.

**Pull request merged**
