### PR TITLE
Correction for one small typo in content\en\docs\concepts\services-networking\service.md

### PR DESCRIPTION
**Pull request by jmyung**
from #18237

### CODE REVIEW

**Comment by anshprat** [comment]
Though this commit correctly fixes the typo, it touches other lines, new line changes etc ( I am assuming due to IDE being used). Is there a guideline on the IDE to be used for this project? 
@sftim I had the same issue for #18231 PR. Thoughts on whats the right way to handle such IDE lead space / new line changes?

**Comment by jmyung** [comment]
Thanks for letting me know. @anshprat 

I've used atom editor for now.
As you mentioned, it removed other white spaces automatically, but it never changed the line position of contents.
For my opinion, I think that this is ok, because markdown doesn't allow additional white spaces.

**Comment by anshprat** [comment]
@jmyung - I also use atom editor :)
From a reviewer's perspective, having unrelated changes in a PR is always a red flag. However I will let more experienced folks chime in. Think of it like this - this may show as a diff for original authors and their IDE may again change these back.

**Comment by jmyung** [comment]
/close this
I opened another PR.

**Comment by jmyung** [comment]
close this.
I opened another PR.

**Pull request closed without merging**
