### PR TITLE
Add link to reclaiming policy

### PR DESCRIPTION
**Pull request by tengqm**
This PR adds a link to the "reclaiming" section in the persistent volumes page.
Fixes: #41089

### CODE REVIEW

**Review by Shubham82 — CHANGES_REQUESTED** [review]

**Comment by sftim** [comment]
@tengqm do you need to rebase against _main_? If not, it's odd to see a build timeout.

**Comment by Shubham82** [comment]
@tengqm it seems all good, only one concern can we change the `Required Kubernetes version` for the `CSI` volume type here:
https://github.com/kubernetes/website/pull/41278/files#diff-5627fff71c9e12d025ce7d053af700cf7afcef2ddcbb79f20f659b71706eb3f1L130

As it mentioned [here](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/) `ExpandCSIVolumes` feature gate is GA k8s v1.24 and removed  in v1.26

WDYT?

**Comment by tengqm** [comment]
> As it mentioned [here](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/) `ExpandCSIVolumes` feature gate is GA k8s v1.24 and removed in v1.26

Because the feature gate is gone, we cannot set it on any control plane components. That is the reason we can remove the `feature-state` shortcode.

**Comment by Shubham82** [comment]
Thanks @sftim for your thoughts. It makes sense.


> For this PR, I'm happy to see all the feature state shortcodes go, as proposed.

I'm ok with that.

**Comment by Shubham82** [comment]
Thanks, @tengqm The changes look good to me.
/lgtm

**Pull request merged**
