### PR TITLE
Improve content

### PR DESCRIPTION
**Pull request by JavierBmrg**
Added 'imperative' word, line 82 in order to define more accurate the way of use declarative API.

### CODE REVIEW

**Comment by zacharysarah** [comment]
@JavierBmrg Please sign the CLA in order to continue.

**Comment by mikedanese** [comment]
> Added 'imperative' word, line 82 in order to define more accurate the way of use declarative API.

The Kubernetes API is declarative? How does adding the word "imperative" more accurately describe Kubernetes' declarative API?

**Comment by JavierBmrg** [comment]
Hi @zacharysarah, actually I can't sign CLA 'cause the validation email hasn't sent, I don't what happened, I have the GitHub Auth approval and I just waiting for the email confirmation, it may be bug/error. I could create PR again.

> The Kubernetes API is declarative? How does adding the word "imperative" more accurately describe Kubernetes' declarative API?

I didn't try to describe 'declarative API'. Actually, It's just a 'way' which you can use the API itself, for example, you can use the API using declarative way (JSON, YAML) or imperative way (kubectl)

**Pull request closed without merging**
