### PR TITLE
Startup probe is in beta since 1.18

### PR DESCRIPTION
**Pull request by alex-slynko**
Startup probe is in beta since 1.18

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#features-graduated-to-beta

### CODE REVIEW

**Comment by sftim** [comment]
@alex-slynko if you can sign the CLA, this sounds like it's going to be a useful PR to review and then merge!

**Comment by alex-slynko** [comment]
@sftim I have changed the company and now have trouble in changing the Linux Foundation email.
I will sign the CLA as soon as possible.

**Comment by alex-slynko** [comment]
done @sftim

**Review by sftim — COMMENTED** [review]
/lgtm
/approve
/sig node
/kind cleanup

Thanks @alex-slynko

**Comment by sftim** [comment]
Relevant to issue #19405

**Pull request merged**
