### PR TITLE
Fix whitespace handling in 'features-state' using Go comment tags

### PR DESCRIPTION
**Pull request by r21gh**
### Description

- Utilized Go comment tags {{- /* Comment Text here */ -}} to manage whitespace
- Improved indentation for better readability
- Prevented unwanted line breaks or spaces in the rendered HTML output

### Issue

Closes: #48323

/area web-development

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by sftim** [comment]
Thanks
/lgtm

**Pull request merged**
