### PR TITLE
[uk] Fix language code for tutorials

### PR DESCRIPTION
**Pull request by sftim**
Mark these as Ukrainian.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Updating the HTML language attribute to reflect the correct language code for Ukrainian ("uk") makes sense. Looks good to me.

/lgtm

**Review by Arhell — COMMENTED** [review]
Thanks
/lgtm

**Review by Princesso — COMMENTED** [review]
/lgtm

**Pull request merged**
