### PR TITLE
remove announcemnt deprecationwarning from lang it

### PR DESCRIPTION
**Pull request by harik8**
* Remove announcement and deprecationwarning shortcodes

### CODE REVIEW

**Comment by celestehorgan** [comment]
Hi @harik8! 

Please remove the issue number from the PR title and commit text. It messes with the build system 😅

**Comment by harik8** [comment]
@celestehorgan Oops! :D I have updated them.

**Comment by fabriziopandini** [comment]
/approve
I leave final lgtm to @celestehorgan

**Comment by sftim** [comment]
Well, it
/lgtm

**Pull request merged**
