### PR TITLE
[hi] Add content/hi/docs/_index.md 

### PR DESCRIPTION
**Pull request by anubha-v-ardhan**
This PR is a part of ongoing `hi` localization effort here #29353 

/language hi

### CODE REVIEW

**Review by verma-kunal — COMMENTED** [review]
LGTM 👍

**Review by mittalyashu — APPROVED** [review]

**Comment by anubha-v-ardhan** [comment]
Hey @mittalyashu , I guess we will get a separate branch to work on till the localization goes live as suggested here https://kubernetes.io/docs/contribute/localization/#branching-strategy. @sftim also comfirmed this. Are you sure we want to merge these PRs to `main`

**Comment by mittalyashu** [comment]
Hmm... I checked the deploy preview and it doesn't seems to indict such change for now.

For the remaining PRs should we change the base branch to `dev-1.22-hi`?

**Comment by anubha-v-ardhan** [comment]
@mittalyashu I don't have much Idea about these. We discussed this matter with Tim and SIG-Docs promised us a different base branch. Tim suggested us to make draft PRs for now and open them on new branch once we are provided the branch. : )

**Comment by mittalyashu** [comment]
Okay, I will ask him in Slack.

**Pull request merged**
