### PR TITLE
fix typo of healthcheck #14985

### PR DESCRIPTION
**Pull request by icheikhrouhou**
fix type of healtcheck to healthcheck.

### CODE REVIEW

**Comment by kbhawkey** [comment]
hello, @icheikhrouhou. Thanks for this PR. I _think_ a good portion of these files are generated. The updates may need to be made on the kubeadm source files, not the generated output files.

**Comment by icheikhrouhou** [comment]
@kbhawkey thanks, I'm still new, I dont know much about these, Can you please explain to me how these files are generated ?

**Comment by kbhawkey** [comment]
@icheikhrouhou, it would be good to open a new issue to address the typos.
Checking with @neolit123.

**Comment by neolit123** [comment]
hello, thanks for finding these typos.
they should be fixed in the kubernetes/kubernetes reporsitory.
you can search for the word with the typo `healtcheck` under `/cmd/kubeadm/app` and send a PR for that same repository.

please, make sure you mention me on the new PR.
thank you.

**Comment by icheikhrouhou** [comment]
@neolit123 @kbhawkey thanks for the help, 
I will do that.

**Pull request closed without merging**
