### PR TITLE
[ko] Update outdated files in dev-1.21-ko.5 (p2)

### PR DESCRIPTION
**Pull request by jihoon-seo**
Related issue: #28473

> ### 4 files to be modified
> 122. [ ]  M122.  `content/en/docs/tutorials/_index.md`  | 1(+XS) 1(-)
> 131. [ ]  **M131.**  `content/en/docs/tutorials/stateless-application/guestbook.md`  | **138(+L) 66(-)**
> 132. [ ]  M132.  `content/en/examples/application/guestbook/frontend-deployment.yaml`  | 12(+S) 15(-)
> 133. [ ]  M133.  `content/en/examples/application/guestbook/frontend-service.yaml`  | 7(+XS) 4(-)
> 
> ### 2 files to be deleted
> 2. [ ]  D2.  `content/en/examples/application/guestbook/mongo-deployment.yaml`
> 3. [ ]  D3.  `content/en/examples/application/guestbook/mongo-service.yaml`

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Direct links to the preview:

- https://deploy-preview-28523--k8s-dev-ko.netlify.app/ko/docs/tutorials/
- https://deploy-preview-28523--k8s-dev-ko.netlify.app/ko/docs/tutorials/stateless-application/guestbook/

**Comment by seokho-son** [comment]
/assign @ysyukr 
리뷰 가능하실까요? ^^

**Comment by ysyukr** [comment]
리뷰가 늦어 죄송합니다. 그리고 고생 하셨습니다 😄 
/lgtm

**Pull request merged**
