### PR TITLE
Improve mobile user experience on pages under /docs

### LINKED ISSUE #10067: Improve mobile experience on all pages under /docs
The heading vertical menu (technically `#vendorStrip` element) is overflowed in any pages under https://kubernetes.io/docs/ when you view on mobile (or narrow-screen devices).

## current screenshots
kubernetes-docs-vendor-strip-before

## to-be screenshots
kubernetes-docs-vendor-strip-after

### PR DESCRIPTION
**Pull request by tnir**
Force `#docs #vendorStrip` elements to use `overflow-x: scroll` in CSS.

Closes #10067
Replaces #10068

### CODE REVIEW

**Comment by tnir** [comment]
@xiangpengzhao @bep Thanks for handling this PR. While I confirmed if this PR works in my local env (with `make docker-serve`)

Preview hosted by Netlify doesn't work well: https://deploy-preview-10072--kubernetes-io-master-staging.netlify.com/docs/

What should I check about previewing with Netlify for this repository?

**Comment by zparnold** [comment]
@tnir Please resolve merge conflicts so we can continue

**Comment by tnir** [comment]
@zparnold I just confirmed both that there is no conflict and that this PR works well at https://deploy-preview-10072--kubernetes-io-master-staging.netlify.com/docs/home/

/assign @zparnold

**Comment by zacharysarah** [comment]
@tnir 👋 This PR still has a merge conflict with `static/css/styles.css`. Please feel free to reopen when you've resolved the conflict.

**Comment by tnir** [comment]
@zacharysarah Thanks. Just reopened and fixed the PR, which is ready to be merged at this moment 😄

**Comment by chenopis** [comment]
/cc @Bradamant3 
I think this PR inadvertently caused a UI issue. I'm seeing this:

screen shot 2018-10-19 at 3 52 30 pm

There is an extra gray bar underneath the secondary nav and search box.

If you compare the two deploy previews:
* https://deploy-preview-10071--kubernetes-io-master-staging.netlify.com/docs/home/?path=users&persona=app-developer&level=foundational
* https://deploy-preview-10072--kubernetes-io-master-staging.netlify.com/docs/home/?path=users&persona=app-developer&level=foundational
It seems to change in this PR.

Can this be addressed?

**Pull request merged**
