### PR TITLE
Update debug-application.md

### PR DESCRIPTION
**Pull request by j-zimnowoda**
A Service has targetPort to indicated Pod's containerPort (service.spec.ports.targetPort)

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by bradtopol** [comment]
@j-zimnowoda Thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by j-zimnowoda** [comment]
> @j-zimnowoda Thank you for your contribution. Please sign the CLA so we can accept your PR for review

@bradtopol I will do so. I am waiting for my organization to signup. I should happen soon.

**Comment by tfogo** [comment]
Hi @j-zimnowoda, any update on signing the CLA?

**Comment by j-zimnowoda** [comment]
> Hi @j-zimnowoda, any update on signing the CLA?

Signed

**Pull request merged**
