### PR TITLE
Update hello-minikube.md

### PR DESCRIPTION
**Pull request by cell13**
modify:
Katacoda environment only: Type `30369`, and then click **Display Port**.

### CODE REVIEW

**Comment by bradtopol** [comment]
@cell13 Thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by bradtopol** [comment]
@BenHall can you review this change for accuracy? Just add /lgtm if you approve.  Thanks.

**Comment by BenHall** [comment]
Thanks, I'll investigate and get back to you ASAP.

**Comment by cody-clark** [comment]
It looks like the last [PR](https://github.com/kubernetes/website/commit/0a0655c646ba760884852a1ff56756617a9144ef/) for this page removed the instructions for entering the NodePort. We can't list a specific port because Minikube selects from a range (30000-32xxx something), but it would be good to add back the step for adding entering the port, not just 8080.

**Comment by cell13** [comment]
@bradtopol  @cody-clark 
Yes. While In this page example, the port used 8080:30369，so I think the 5th step should use the same port 30369. It would be easy to understand by new one like me.

**Comment by bradtopol** [comment]
@cell13 It looks like you have some merge conflicts that need to be resolved

**Comment by Rajakavitha1** [comment]
@cell13 could you please resolve the merge conflicts.

**Pull request merged**
