### PR TITLE
Changed Spellings For The Hindi Documentation

### PR DESCRIPTION
**Pull request by ShivamPandya**
Changed "कुबरनेट्स" to "कुबरनेटिस"
Both terms have different pronunciations.
Before:
कुबरनेट्स : Pronunciation goes like koo-bar-ne-tas
After:
कुबरनेटिस : Pronunciation goes like koo-bar-ne-tis

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by ShivamPandya** [comment]
I have completed the CLA Process and have signed the agreement successfully. Please check it.

**Comment by mittalyashu** [comment]
Hello @ShivamPandya,

I suggest you take a look at **Kubernetes Hindi-language team glossary** https://docs.google.com/spreadsheets/d/1UmL4K0v4yaN34k4WzYDZBobLBp5OZQp4GCTi28AfwQM/edit?usp=sharing

> `कुबरनेट्स`: Pronunciation goes like `koo-bar-ne-tas`
> After:
> `कुबरनेटिस`: Pronunciation goes like `koo-bar-ne-tis`

As you have suggested that the spellings are incorrect as it spells incorrectly.

I understand that, but it's not always the case, the Hindi language can be a bit tricky in those scenarios when it comes to the actual word and the way we write is different.

Even if you speak the word **Kuberntes** word aloud, you will notice that `a` in `tas` become silent.

**Comment by Rajakavitha1** [comment]
> Hello @ShivamPandya,
> 
> I suggest you take a look at **Kubernetes Hindi-language team glossary** https://docs.google.com/spreadsheets/d/1UmL4K0v4yaN34k4WzYDZBobLBp5OZQp4GCTi28AfwQM/edit?usp=sharing
> 
> > `कुबरनेट्स`: Pronunciation goes like `koo-bar-ne-tas`
> > After:
> > `कुबरनेटिस`: Pronunciation goes like `koo-bar-ne-tis`
> 
> As you have suggested that the spellings are incorrect as it spells incorrectly.
> 
> I understand that, but it's not always the case, the Hindi language can be a bit tricky in those scenarios when it comes to the actual word and the way we write is different.
> 
> Even if you speak the word **Kuberntes** word aloud, you will notice that `a` in `tas` become silent.

I am not sure about the `a` in `tas` becoming silent . kubernetes is pronounced /koo-ber-nay'-tace/ and means "sailing master".... we may need to update this document https://docs.google.com/spreadsheets/d/1UmL4K0v4yaN34k4WzYDZBobLBp5OZQp4GCTi28AfwQM/edit?usp=sharing accordingly.

**Comment by kbhawkey** [comment]
Hello @ShivamPandya .
Because this pull request has been open for an extended time, I plan to close it.
You can reopen the PR to continue to work on the changes.
/close

**Pull request closed without merging**
