### PR TITLE
Write headings in sentence case for StatefulSet tutorial

### PR DESCRIPTION
**Pull request by sftim**
Update the [tutorial](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/) for StatefulSets to write headings in sentence case, per the [style guide](https://kubernetes.io/docs/contribute/style/style-guide/#headings).

Part of PR #42767

/kind cleanup

### CODE REVIEW

**Review by PranitRout07 — COMMENTED** [review]
'Cascading delete' is more correct in my opinion @sftim .

**Comment by sftim** [comment]
Oops, how did that get in. Good spot!

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/lgtm

**Pull request merged**
