### PR TITLE
fix community banner so it fills the whole space

### PR DESCRIPTION
**Pull request by alexcontini**

### CODE REVIEW

**Comment by alexcontini** [comment]
@celestehorgan here is the PR to fix the community page banner, I thought I would tag you as I think you can merge, let me know if there are any issues, thank you!!

**Comment by celestehorgan** [comment]
@alexcontini I actually can't, but this looks good to me!

**Comment by sftim** [comment]
@celestehorgan feel free to reply /lgtm to mark that it looks good to you.

**Pull request merged**
