### PR TITLE
[ko] Correcting API field paths

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/45337/files

### CODE REVIEW

**Review by jongwooo — COMMENTED** [review]
@Arhell Thanks!
/lgtm

**Review by Arhell — COMMENTED** [review]
cc @seokho-son

**Comment by Okabe-Junya** [comment]
Hi @Arhell

I asked on Slack to move some PRs forward. Thank you.

FYI: https://kubernetes.slack.com/archives/CA1MMR86S/p1716299264903579

**Comment by seokho-son** [comment]
Thanks!

/approve

**Pull request merged**
