### PR TITLE
[zh] update determine-reason-pod-failure.md

### PR DESCRIPTION
**Pull request by my-git9**
[zh] Update  debug-pod-replication-controller.md

### CODE REVIEW

**Comment by howieyuen** [comment]
/retitile [zh] sync content/zh/docs/tasks/debug-application-cluster/determine-reason-pod-failure.md

**Review by howieyuen — APPROVED** [review]
/approve

**Comment by mengjiao-liu** [comment]
/lgtm
Thanks.

**Comment by mengjiao-liu** [comment]
/lgtm
Thanks.

**Pull request merged**
