### PR TITLE
Clean up zh training content

### PR DESCRIPTION
**Pull request by ydcool**
Ref: #19500 

/kind cleanup

### CODE REVIEW

**Review by tanjunchen — COMMENTED** [review]
/lgtm

**Review by tanjunchen — COMMENTED** [review]
Thanks

**Comment by tengqm** [comment]
Are these all the files changed from the upstream commit?
Do we need to change `content/zh/docs/tutorials/_index.md`?

**Comment by ydcool** [comment]
> Are these all the files changed from the upstream commit?
> Do we need to change `content/zh/docs/tutorials/_index.md`?

Changes made in upstream commit of the `_index.md` was outdated, so I just ignored that. I think we should open another pr to update the `_index.md` with latest en one.

**Comment by tengqm** [comment]
@ydcool I'd suggest we keep each PR self-contained. Removing a file in one PR and adding back the same file back in a different PR is not the best practice.

**Comment by ydcool** [comment]
@tengqm  Sorry I missed the line changed in `content/en/docs/tutorials/_index.md`

**Pull request merged**
