### PR TITLE
Merge master into release-1.19 to keep in sync

### PR DESCRIPTION
**Pull request by annajung**
Merge `master` into the current release branch (`release-1.19`) to keep in sync
Final sync before the release

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
lgtm

b905af1 looks good as well. `x` is due to the prow/tide label issue

**Review by irvifa — COMMENTED** [review]
/lgtm

**Comment by irvifa** [comment]
I’m not sure on how we handle tide error for this case though.

**Comment by annajung** [comment]
> I’m not sure on how we handle tide error for this case though.

imo, since the `Merging is blocked by issue 25464` error is intentional, I don't think there is any action required to resolve it.

**Review by irvifa — COMMENTED** [review]
/approve

**Comment by raghvenders** [comment]
@annajung if you click on tide details merge blocking issue #25464  , it is not getting listed in prow.k8s.io , are you able to see?

**Pull request merged**
