### PR TITLE
[zh] Update organize-cluster-access-kubeconfig.md

### PR DESCRIPTION
**Pull request by chengxiangdong**
sync with en
```
content/zh-cn/docs/concepts/configuration/organize-cluster-access-kubeconfig.md
```

### CODE REVIEW

**Comment by chengxiangdong** [comment]
@windsonsea  can you help me review

**Comment by windsonsea** [comment]
These changes look good to me if no any conflict with another PR #37425 for this same file.

**Comment by chengxiangdong** [comment]
> These changes look good to me if no any conflict with another PR #37425 for this same file.

I also saw another PR, I will rebase it after it is merged.

**Pull request merged**
