### PR TITLE
Fix some 404 links in Chinese docs

### PR DESCRIPTION
**Pull request by WanLinghao**
Fix some 404 links in Chinese docs

### CODE REVIEW

**Comment by WanLinghao** [comment]
@tengqm PTAL

**Comment by tengqm** [comment]
@WanLinghao PR looks good. Can you help check if we need a similar change to the English version?

**Comment by WanLinghao** [comment]
@tengqm I have checked this， English version is OK

**Comment by tengqm** [comment]
@WanLinghao Thanks for the confirmation, sir.
/lgtm
/approve

**Pull request merged**
