### PR TITLE
update feature gate list for KEP-3178 to GA

### PR DESCRIPTION
**Pull request by danwinship**
KEP-3178 IPTablesOwnershipCleanup is going GA, so update the feature gate list.

### CODE REVIEW

**Review by kundan2707 — COMMENTED** [review]
seems good as IPtable ownership is now GA

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Comment by sftim** [comment]
@danwinship is there a k/k PR that this depends upon

**Comment by danwinship** [comment]
https://github.com/kubernetes/kubernetes/pull/119374, which already merged

**Review by sftim — COMMENTED** [review]
/approve

_Optionally_, add an update paragraph to https://kubernetes.io/blog/2022/09/07/iptables-chains-not-api/ to explain the new GA-ness.

**Pull request merged**
