### PR TITLE
Remove namespace reference in kubectl cheatsheet

### PR DESCRIPTION
**Pull request by gprasath**
- PV is not namespace scoped object. So, removed the namespace reference in `list pv` command

### CODE REVIEW

**Comment by gprasath** [comment]
@sftim Can this be approved

**Comment by sftim** [comment]
This is ready for approval

**Comment by sftim** [comment]
@gprasath the good news is I'm an approver now so I could approve.
The bad news is: the page in _master_ has changed. Can you revise / rebase?

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-18253--kubernetes-io-master-staging.netlify.com/docs/reference/kubectl/cheatsheet/

**Comment by jimangel** [comment]
It appears this was fixed in https://github.com/kubernetes/website/pull/18877. Closing for now. Thanks!

/close

**Pull request closed without merging**
