### PR TITLE
Avoid confusing term in API Priority and Fairness concept

### PR DESCRIPTION
**Pull request by NitishKumar06**
Fix: #36393

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
@MikeSpreitzer : Please have a look at this PR & confirm whether this is good for merge?

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
Thanks!

**Comment by NitishKumar06** [comment]
@divya-mohan0209 I believe this PR is ready to be merged. Any more suggestions from your end?

**Pull request merged**
