### PR TITLE
add latency requirements to aggregated apiserver discovery

### PR DESCRIPTION
**Pull request by deads2k**
https://github.com/kubernetes/kubernetes/pull/82092 adds a latency requirement (and opt-out) for aggregated discovery requests.

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

need to be sure the real PR lands and then this is a featuregate.

**Comment by deads2k** [comment]
Updated for feature gate in https://github.com/kubernetes/kubernetes/pull/82146

/hold cancel

**Comment by enj** [comment]
/hold

Uh did the k/k PR merge?

**Comment by enj** [comment]
Ah I see it in https://github.com/kubernetes/kubernetes/pull/82146

/hold cancel

**Comment by tengqm** [comment]
@deads2k Please rebase the PR onto dev-1.16 branch. Thanks.

**Comment by tengqm** [comment]
@deads2k Also please confirm this one should go 1.16. Looks like the old PR kubernetes/kubernetes#82092  has been replaced by kubernetes/kubernetes#82146, which is now landed.

**Comment by deads2k** [comment]
opened https://github.com/kubernetes/website/pull/16371

**Comment by deads2k** [comment]
opened https://github.com/kubernetes/website/pull/16372

**Comment by simplytunde** [comment]
@deads2k  You need to update this page with the feature gate. ```/docs/reference/command-line-tools-reference/feature-gates/```.  You can use this PR for reference. 
https://github.com/kubernetes/website/pull/15514/files#diff-de82bd337b186802e14e2adc7f0ec5fa
I will appreciate if we can get this in very soon.

**Comment by simplytunde** [comment]
please ignore the above comment. It is meant for https://github.com/kubernetes/website/pull/16372

**Comment by simplytunde** [comment]
You can close this PR

**Pull request closed without merging**
