### PR TITLE
[ko] Added link to netcat official site and '-v' key to netcat comman…

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/44600/files

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The proposed change of adding inline link for netcat and including '-v' in the command looks in sync with 'en' PR https://github.com/kubernetes/website/pull/44600/files

[Preview Page](https://deploy-preview-45739--kubernetes-io-main-staging.netlify.app/ko/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)

/lgtm

**Review by jongwooo — COMMENTED** [review]
Thanks!

/lgtm

**Review by Arhell — COMMENTED** [review]
cc @seokho-son

**Comment by seokho-son** [comment]
Thanks!

/approve

**Pull request merged**
