### PR TITLE
[zh] fix wrong dns record

### PR DESCRIPTION
**Pull request by 0xff-dev**
fix wrong dns record.
[namespace of service](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#namespaces-of-services)

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @tengqm

**Comment by tengqm** [comment]
@0xff-dev Can you help sync the following changes as well?

```
@@ -217,13 +217,13 @@ following pod-specific DNS policies. These policies are specified in the
 
 - "`Default`": The Pod inherits the name resolution configuration from the node
   that the pods run on.
-  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers/#inheriting-dns-from-the-node)
+  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers)
   for more details.
 - "`ClusterFirst`": Any DNS query that does not match the configured cluster
   domain suffix, such as "`www.kubernetes.io`", is forwarded to the upstream
   nameserver inherited from the node. Cluster administrators may have extra
   stub-domain and upstream DNS servers configured.
-  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers/#effects-on-pods)
+  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers)
   for details on how DNS queries are handled in those cases.
 - "`ClusterFirstWithHostNet`": For Pods running with hostNetwork, you should
   explicitly set its DNS policy "`ClusterFirstWithHostNet`".
```

**Comment by 0xff-dev** [comment]
> @0xff-dev Can you help sync the following changes as well?
> 
> ```
> @@ -217,13 +217,13 @@ following pod-specific DNS policies. These policies are specified in the
>  
>  - "`Default`": The Pod inherits the name resolution configuration from the node
>    that the pods run on.
> -  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers/#inheriting-dns-from-the-node)
> +  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers)
>    for more details.
>  - "`ClusterFirst`": Any DNS query that does not match the configured cluster
>    domain suffix, such as "`www.kubernetes.io`", is forwarded to the upstream
>    nameserver inherited from the node. Cluster administrators may have extra
>    stub-domain and upstream DNS servers configured.
> -  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers/#effects-on-pods)
> +  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers)
>    for details on how DNS queries are handled in those cases.
>  - "`ClusterFirstWithHostNet`": For Pods running with hostNetwork, you should
>    explicitly set its DNS policy "`ClusterFirstWithHostNet`".
> ```

OK, let me add it

**Comment by 0xff-dev** [comment]
> @0xff-dev Can you help sync the following changes as well?
> 
> ```
> @@ -217,13 +217,13 @@ following pod-specific DNS policies. These policies are specified in the
>  
>  - "`Default`": The Pod inherits the name resolution configuration from the node
>    that the pods run on.
> -  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers/#inheriting-dns-from-the-node)
> +  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers)
>    for more details.
>  - "`ClusterFirst`": Any DNS query that does not match the configured cluster
>    domain suffix, such as "`www.kubernetes.io`", is forwarded to the upstream
>    nameserver inherited from the node. Cluster administrators may have extra
>    stub-domain and upstream DNS servers configured.
> -  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers/#effects-on-pods)
> +  See [related discussion](/docs/tasks/administer-cluster/dns-custom-nameservers)
>    for details on how DNS queries are handled in those cases.
>  - "`ClusterFirstWithHostNet`": For Pods running with hostNetwork, you should
>    explicitly set its DNS policy "`ClusterFirstWithHostNet`".
> ```

Updated. Please review again, thank you.

**Comment by tengqm** [comment]
Thanks.
/approve

**Pull request merged**
