### PR TITLE
Updated Job Documentaion

### LINKED ISSUE #37574: Outdated Jobs documentation
Outdated Kubernetes Job Docs!
I tried running the k8s job pi example which is present in Job docs here: https://kubernetes.io/docs/concepts/workloads/controllers/job/
But when I did describe, I saw the "Pod statuses" field as "Active" not "Running". Also there are new fields that are added into job description like "Completion Mode"

This is what I see in the docs for "kubectl describe job pi" command:
```
Name:           pi
Namespace:      default
Selector:       controller-uid=c9948307-e56d-4b5d-8302-ae2d7b7da67c
Labels:         controller-uid=c9948307-e56d-4b5d-8302-ae2d7b7da67c
                job-name=pi
Annotations:    kubectl.kubernetes.io/last-applied-configuration:
                  {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"pi","namespace":"default"},"spec":{"backoffLimit":4,"template":...
Parallelism:    1
Completions:    1
Start Time:     Mon, 02 Dec 2019 15:20:11 +0200
Completed At:   Mon, 02 Dec 2019 15:21:16 +0200
Duration:       65s
Pods Statuses:  0 Running / 1 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=c9948307-e56d-4b5d-8302-ae2d7b7da67c
           job-name=pi
  Containers:
   pi:
    Image:      perl:5.34.0
    Port:       <none>
    Host Port:  <none>
    Command:
      perl
      -Mbignum=bpi
      -wle
      print bpi(2000)
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  14m   job-controller  Created pod: pi-5rwd7
```

And this is what I see in my local cluster when I run the same command:
```
Name:             pi
Namespace:        default
Selector:         controller-uid=0cd26dd5-88a2-4a5f-a203-ea19a1d5d578
Labels:           controller-uid=0cd26dd5-88a2-4a5f-a203-ea19a1d5d578
                  job-name=pi
Annotations:      batch.kubernetes.io/job-tracking: 
Parallelism:      1
Completions:      1
Completion Mode:  NonIndexed
Start Time:       Fri, 28 Oct 2022 13:05:18 +0530
Completed At:     Fri, 28 Oct 2022 13:05:21 +0530
Duration:         3s
Pods Statuses:    0 Active / 1 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=0cd26dd5-88a2-4a5f-a203-ea19a1d5d578
           job-name=pi
  Containers:
   pi:
    Image:      perl:5.34.0
    Port:       <none>
    Host Port:  <none>
    Command:
      perl
      -Mbignum=bpi
      -wle
      print bpi(2000)
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  21s   job-controller  Created pod: pi-xf9p4
  Normal  Completed         18s   job-controller  Job completed
```

### PR DESCRIPTION
**Pull request by Karthik-PM**
Fixes #37574

please do give me your inputs as this is my first PR

### CODE REVIEW

**Comment by akankshakumari393** [comment]
could you please describe which kubernetes version and distribution you were trying to run this Job on?

**Comment by Kart121** [comment]
> 

@akankshakumari393  the issue was created by someone else

**Comment by akankshakumari393** [comment]
@Kart121 I think its not always safe to assume that the issue has to be on the latest version of kubernetes on the basis of when the issue was created.

Did you not try reproducing the issue at your end. I was trying to reproduce the issue on kind cluster but it gave me different result than what has been changed in the PR.

**Comment by Kart121** [comment]
no actually i didnt , since i switched to a different OS but which version of kubernetes are you using?

**Comment by Kartik494** [comment]
@Kart121 could you change the PR description from 
`PR for resolving #issuenumber` to `Fixes #issuenumber` it will automatically close this issue once PR got completed.

**Comment by Kart121** [comment]
> 

@Kartik494  will do it , thanks !

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by reylejano** [comment]
Can you also update the results in the `kubectl get job pi -o yaml` tab so they align

**Comment by reylejano** [comment]
Thank you for also updating the `kubectl get job pi -o yaml` tab
/lgtm

**Review by sftim — COMMENTED** [review]
Thanks

/approve

**Pull request merged**
