### PR TITLE
[zh] Sync content/en/docs/concepts/configuration/configmap.md

### PR DESCRIPTION
**Pull request by mengjiao-liu**
[zh] Sync content/zh/docs/concepts/configuration/configmap.md

Part of #27672

### CODE REVIEW

**Comment by tengqm** [comment]
/lgtm
This PR looks good. Preferably, you can sign on a few items outlined in issue #27672, so that the synchronization work can be coordinated.

**Comment by mengjiao-liu** [comment]
OK, I'll do it

**Review by tanjunchen — COMMENTED** [review]
@mengjiao-liu 
/approve

**Pull request merged**
