### PR TITLE
I am going to pull it as I see a change can be pushed on the kubernetes.io page

### PR DESCRIPTION
**Pull request by ShubhasisMathur**
<!-- 🛈

 Hello!

 I would like to let you know that one of the page needs an update in the yaml. The contsraint template at https://kubernetes.io/blog/2019/08/06/opa-gatekeeper-policy-and-governance-for-kubernetes/ needs an update of the voilation which is missing.

instead of deny it should ne violation. Here is the revised yaml after I corrected it:

apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
name: k8srequiredlabels
spec:
crd:
spec:
names:
kind: K8sRequiredLabels
listKind: K8sRequiredLabelsList
plural: k8srequiredlabels
singular: k8srequiredlabels
validation:
# Schema for the parameters field
openAPIV3Schema:
properties:
labels:
type: array
items: string
targets:
- target: admission.k8s.gatekeeper.sh
rego: |
package k8srequiredlabels

    **violation[**{"msg": msg, "details": {"missing_labels": missing}}] { // this line needs update
      provided := {label | input.review.object.metadata.labels[label]}
      required := {label | label := input.parameters.labels[_]}
      missing := required - provided
      count(missing) > 0
      msg := sprintf("you must provide labels: %v", [missing])
    }

### CODE REVIEW

**Comment by ShubhasisMathur** [comment]
/assign @kbarnard10 

Allow me to pull the repo. I intend to change the content template given as an example https://kubernetes.io/blog/2019/08/06/opa-gatekeeper-policy-and-governance-for-kubernetes/

This needs a change of one variable, instead of deny it should be violation, here is the change:
  deny[**{"msg": msg, "details": {"missing_labels": missing}}] { // this is the current line
 **violation[**{"msg": msg, "details": {"missing_labels": missing}}] { // deny should be changed to violation for it to work

**Comment by kbhawkey** [comment]
Hello @ShubhasisMathur .
Thanks for opening this pull request.
Is this related to issue #25976?
If so, you should create a branch with your changes to merge to the master branch, not `dev-1.21`.
For more information, see the contributing guide:
https://kubernetes.io/docs/contribute/
https://kubernetes.io/docs/contribute/new-content/open-a-pr/#fork-the-repo
If you need more information or help, you can reach out on Slack.

**Review by sftim — CHANGES_REQUESTED** [review]
This pull request does not make sense to merge

**Comment by tengqm** [comment]
What is this? Is it an automation for merging changes in master to dev-1.21?

**Comment by sftim** [comment]
As this PR does not make sense (description is *blank*) and the changes neither, I will close it.

/close

**Comment by tengqm** [comment]
@sftim My observation is that this PR automagically pulls all PRs merged into master and include them here to the `dev-1.21` branch. Isn't that a time saver?

**Comment by kbhawkey** [comment]
> @sftim My observation is that this PR automagically pulls all PRs merged into master and include them here to the `dev-1.21` branch. Isn't that a time saver?

@tengqm, No. It is not clear what the author intends to do with this pull request.

**Comment by tengqm** [comment]
@kbhawkey I've been watching this PR since it was submitted. I had the same question ... what the .. is it? During the past 2 days, what I saw was that all PRs merged into the master branch are automatically added into this PR. It doesn't look like there is a human sitting there watching the changes.

@ShubhasisMathur Can you help clarify the purpose of this PR and see if we can improve it somehow?

**Comment by sftim** [comment]
> all PRs merged into the master branch are automatically added into this PR

No magic here. That's because the source branch for this PR is, in fact, _master_.

**Comment by tengqm** [comment]
@sftim If I have a PR sourcing the master, empty one, and I propose it to `dev-1.21`, the PR will get automatically updated when something merged into master? I never know that.

**Pull request closed without merging**
