### PR TITLE
Update patch-releases.md

### PR DESCRIPTION
**Pull request by mrhan1993**
Fix page format rendering issues

change it before

after

### CODE REVIEW

**Comment by windsonsea** [comment]
This file has some more changes. Would like to include it in this PR? You can find it by running the command on your `main` branch:

```
./scripts/lsync.sh content/zh-cn/releases/patch-releases.md
```

**Comment by mrhan1993** [comment]
> This file has some more changes. Would like to include it in this PR? You can find it by running the command on your `main` branch:
> 
> ```
> ./scripts/lsync.sh content/zh-cn/releases/patch-releases.md
> ```
> 
> 

ok, include it . doc in english version does not include this line.

**Review by windsonsea — COMMENTED** [review]
**Removing lines 192 - 207 can solve this issue.**

We need not to add `What's Next` to the zh version that will be inconsistent with en upstream. Those en text at bottom are for reference link. The zh localization has a different style like line 77:

```
请遵循 [Cherry Pick 流程](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md)。
```

**Comment by mrhan1993** [comment]
> **Removing lines 192 - 207 can solve this issue.**
> 
> We need not to add `What's Next` to the zh version that will be inconsistent with en upstream. Those en text at bottom are for reference link. The zh localization has a different style like line 77:
> 
> ```
> 请遵循 [Cherry Pick 流程](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md)。
> ```

a new commit,  I think that’s what you mean

**Comment by windsonsea** [comment]
Please squash your commits into a single one. The preview looks good now:

https://deploy-preview-42788--kubernetes-io-main-staging.netlify.app/zh-cn/releases/patch-releases/

**Comment by mrhan1993** [comment]
> Please squash your commits into a single one. The preview looks good now:
> 
> https://deploy-preview-42788--kubernetes-io-main-staging.netlify.app/zh-cn/releases/patch-releases/

It seems that my misoperation has made things worse, and I think resubmitting PR is an easier choice.

**Comment by windsonsea** [comment]
Refer to our docs to squash commits: https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

**Comment by mrhan1993** [comment]
> Refer to our docs to squash commits: https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

thx for your help, I think is ok this time.

**Review by windsonsea — COMMENTED** [review]
Good job 👍 

The commented en text on line 152 can be removed too while the corresponding zh text is removed now.

You can use the command below to keep the single commit after you edit locally:

```
git add .
git commit --amend --no-edit
git push origin patch-1 -f
```

**Comment by mrhan1993** [comment]
> Good job 👍
> 
> The commented en text on line 152 can be removed too while the corresponding zh text is removed now.
> 
> You can use the command below to keep the single commit after you edit locally:
> 
> ```
> git add .
> git commit --amend --no-edit
> git push origin patch-1 -f
> ```

done

**Review by windsonsea — APPROVED** [review]
Thanks.
/approve

**Pull request merged**
