### PR TITLE
Fix URL nginx-deployment.yaml

### PR DESCRIPTION
**Pull request by haru01**
"https://k8s.io/docs/user-guide/nginx-deployment.yaml" is not found

### CODE REVIEW

**Comment by haru01** [comment]
change https://k8s.io/docs/concepts/overview/working-with-objects/nginx-deployment.yaml

**Comment by heckj** [comment]
@haru01 please also sign the CLA- instructions are above in this PR - so that we may consider merging your pull request

**Comment by heckj** [comment]
/assign

@haru01 👋 please sign the CLA so that we can consider including your content update

**Pull request merged**
