### PR TITLE
add $3 as a parameter to awk print in line 110

### PR DESCRIPTION
**Pull request by andreimoraru**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.11 Features: set Milestone to 1.11 and Base Branch to release-1.11
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by tengqm** [comment]
@andreimoraru Please sign the CLA for this to be merged.

**Comment by ajaeger** [comment]
Duplicate of #8527 - which fixes another issue as well.

**Comment by andreimoraru** [comment]
@tengqm I just have signed CLA.

**Comment by Bradamant3** [comment]
Duplicate, plus the content has moved in the repo. Closing unmerged, but thanks for diligent catching!

**Pull request closed without merging**
