### PR TITLE
Tweak page style for resource-bin-packing.md

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
1. Remove extra spaces
2. Reformat the shape section preceded with 2 spaces
3. Remove redundant blank lines

### CODE REVIEW

**Comment by tengqm** [comment]
This is not a good practice. We in general discourage submitting patches to more than one languages.
Please consider split such PRs into separate ones.

/approve

**Comment by Zhuzhenghao** [comment]
> This is not a good practice. We in general discourage submitting patches to more than one languages. Please consider split such PRs into separate ones.
> 
> /approve

Sry, I was commiting another file to this branch by mistake. Resetted.

**Pull request merged**
