### PR TITLE
Fix up Tutorials landing page and Tutorials left nav.

### LINKED ISSUE #8247: Hugo Migration: Tutorials—missing pages, formatting, other issues
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
The Tutorials section of the staged Hugo site has several issues:
* [Landing page](https://k8sio-hugo-migration.netlify.com/docs/tutorials/) bulleted list has formatting issues. For example, Stateless Applications has three bullets next to it
* Landing page's lists of tutorials doesn't reflect table of contents (TOC)
* The following pages are missing:
  * Kubernetes Basics (it has become Try Our Interactive Tutorials again)
  * Online Training Courses > Scalable Microservices with Kubernetes (Udacity)
  * Online Training Courses > Introduction to Kubernetes (edX)
  * Stateful Applications > Run a Single-Instance Stateful Application
  * Stateful Applications > Run a Replicated Stateful Application
* Ordering of sections doesn't reflect production site. For example, Stateful Applications > Stateful Basics should be at the top of that section, but it's at the bottom
* [Running a Single-Instance Stateful Application](https://k8sio-hugo-migration.netlify.com/docs/tutorials/stateful-application/run-stateful-application/) is missing from site
* [Running a Stateless Application Using a Deployment](https://k8sio-hugo-migration.netlify.com/docs/tutorials/stateless-application/run-stateless-application-deployment/) is missing
* [Using a Service to Access an Application in a Cluster](https://k8sio-hugo-migration.netlify.com/docs/tutorials/stateless-application/expose-external-ip-address-service/) is missing
* [Connecting a Front End to a Back End Using a Service](https://k8sio-hugo-migration.netlify.com/docs/tutorials/connecting-apps/connecting-frontend-backend/) is missing
* According to @jaredbhatti, "Try Out Interactive Tutorials" should be "Kubernetes Basics"
* Hello Minikube is buried under Stateless Applications. There is a footer link throughout the site that replaces the Get Started link used in [production](https://kubernetes.io/docs/tutorials/). Seems to me that Hello Minikube should be outside of a TOC section, like it is in production

**Proposed Solution:**
Investigate and resolve these migration issues.

**Page to Update:**
https://k8sio-hugo-migration.netlify.com/docs/tutorials/

### PR DESCRIPTION
**Pull request by steveperry-53**
Closes #8247.

This PR moves some tutorial files to different directories, so that the left nav includes all tutorials. This PR also aligns the Tutorials landing page with the Tutorials left nav.

Preview: https://deploy-preview-8557--kubernetes-io-master-staging.netlify.com/docs/tutorials/

### CODE REVIEW

**Comment by steveperry-53** [comment]
@Bradamant3, The bot ate your LGTM. Could you do it again? Thanks.

**Comment by Bradamant3** [comment]
silly bot

**Pull request merged**
