### PR TITLE
Commit work from 1.18 milestone

### PR DESCRIPTION
**Pull request by inductor**
Merge upstream work for release-1.18

Ref: https://github.com/kubernetes/website/pull/26817

### CODE REVIEW

**Comment by atoato88** [comment]
Netlify ci job failed :cry: 
Refering "deploy/netlify" job, [error is found](https://app.netlify.com/sites/k8s-v1-18/deploys/60ae206a9bc41c0008c3edaf#L91).
```
7:19:16 PM: Error: Error building site: "/opt/build/repo/content/ja/training/_index.html:115:5": failed to extract shortcode: template for shortcode "cncf-landscape" not found
```

I don't know about details of `cncf-landscape` shortcode.
But the file using `cncf-landscape` shortcode is only `content/ja/training/_index.html` in branch `release-1.18-ja.1`.
I checked this by `grep` command.
```bash
# move to top for website repository and:

$ git checkout release-1.18-ja.1
$ grep cncf-landscape -r .
./content/ja/training/_index.html:    {{< cncf-landscape helpers=false category="kubernetes-training-partner" >}}
```
Other language files doesn't use `cncf-landscape`.

Some wrong commit is included in this PR? :thinking:

**Comment by inductor** [comment]
@atoato88 good catch! I fixed it.

**Comment by atoato88** [comment]
Netlify deploy job completed :100: 
We can check the preview site from [here](https://deploy-preview-28130--k8s-v1-18.netlify.app/). :smile:

**Comment by atoato88** [comment]
Here we can access to [preview site](https://deploy-preview-28130--k8s-v1-18.netlify.app/)

**Comment by atoato88** [comment]
/lgtm
I confirmed some commits are renderd w/ no errors, and also pages for case study exists.

**Pull request merged**
