### PR TITLE
Update content/zh-cn/docs/concepts/policy/resource-quotas.md

### LINKED ISSUE #37690: [zh] Localization of resource quota scopes subtopic is not idiomatic Chinese
Hi All，I noticed a defect at https://deploy-preview-37680--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/policy/resource-quotas/#quota-scopes, I don't think this sentence is very smooth. The existence of Chinese documents should make readers understand them better, rather than translate them from English as much as possible。
The specific text is "需要注意的是，你不可以在同一个配额对象中同时设置 Terminating 和 NotTerminating 作用域，你也不可以在同一个配额中同时设置 BestEffort 和 NotBestEffort 作用域。"

### PR DESCRIPTION
**Pull request by xzyangPlus**
fix #37690

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
I know it's not necessary to repeat `你` everywhere, but this change looks very tiny 😺 

Could you please check this file through while `./scripts/lsync.sh` tells us `still in sync`, which means this file may have some inconsistency with en upstream.

**Comment by tengqm** [comment]
This is a waste of time.
/close

**Comment by xzyangPlus** [comment]
> This is a waste of time. /close

First of all, everyone has their own ideas. As a Chinese, I think the revised document is more smooth to read. Second, you can deny it. Do you think I waste time? How did your family teach you to talk?

**Comment by xzyangPlus** [comment]
> This is a waste of time. /close

First of all, everyone has their own ideas. As a Chinese, I think the revised document is more smooth to read. Second, you can deny it. Do you think I waste time? How did your family teach you to talk?

**Comment by tengqm** [comment]
@xzyangPlus Please refer to https://github.com/cncf/foundation/blob/main/code-of-conduct.md for the community code of conduct. This is a warning.
As for the reason to close this PR, pleaser refer to https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits, and also https://kubernetes.io/docs/contribute/review/reviewing-prs/#other.
Trivial edits wastes the time of contributors and the reviewers, it generates email and other notifications when its status is changed. Such email are sent to all contributors who are watching this repo. Even a single word change (no matter it is meaningful or not), will trigger a server side CI gate for validation. So, please think twice when proposing such a PR.

**Comment by xzyangPlus** [comment]
> @xzyangPlus Please refer to https://github.com/cncf/foundation/blob/main/code-of-conduct.md for the community code of conduct. This is a warning. As for the reason to close this PR, pleaser refer to https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits, and also https://kubernetes.io/docs/contribute/review/reviewing-prs/#other. Trivial edits wastes the time of contributors and the reviewers, it generates email and other notifications when its status is changed. Such email are sent to all contributors who are watching this repo. Even a single word change (no matter it is meaningful or not), will trigger a server side CI gate for validation. So, please think twice when proposing such a PR.

好的，非常感谢您，我会继续在社区学习。

**Pull request closed without merging**
