### PR TITLE
Improve network policies concept

### PR DESCRIPTION
**Pull request by sftim**
Improve https://kubernetes.io/docs/concepts/services-networking/network-policies/ ([preview](https://deploy-preview-18091--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/network-policies/))

- reword in line with website style guide
- make example policies downloadable

### CODE REVIEW

**Comment by bradtopol** [comment]
@cmluciano Can you serve as a techical reviewer for this? Simply add a /lgtm when you feel it is acceptable.
/cc @cmluciano 
/assign

**Comment by cmluciano** [comment]
ack @bradtopol - will review today

**Comment by sftim** [comment]
Thanks for the feedback @cmluciano

**Pull request merged**
