### PR TITLE
[de] sync content/de/docs/concepts/_index.md from upstream

### PR DESCRIPTION
**Pull request by JarHMJ**

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
LGTM

**Comment by JarHMJ** [comment]
please review @sftim

**Comment by sftim** [comment]
That's an informal LGTM. I'm not a reviewer for the German localization.

**Comment by Sea-n** [comment]
Those contents are not "removed". It's rewritten to each page, please refer to PR #21997.

- #21997

/hold

**Comment by Sea-n** [comment]
Hey @JarHMJ,

It's been a while since last update, would you like to sync the rewritten article so that we can move forward?

**Comment by JarHMJ** [comment]
> Hey @JarHMJ,
> 
> It's been a while since last update, would you like to sync the rewritten article so that we can move forward?

Sorry. I can't translate German, maybe someone else can.

**Pull request closed without merging**
