### PR TITLE
Apply content template in "docs/reference/kubernetes-api/labels-annotations-taints/"

### PR DESCRIPTION
**Pull request by makocchi-git**
* apply template (and remove double bullets in TOC)
* remove analytics tags
* add an anchor link
* remove duplicated description in overview

### CODE REVIEW

**Comment by makocchi-git** [comment]
[preview url is here](https://deploy-preview-9232--kubernetes-io-master-staging.netlify.com/docs/reference/kubernetes-api/labels-annotations-taints/)
[original](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/)

**Comment by Rajakavitha** [comment]
@makocchi-git Thanks for making the fixes. The document reads much better now. However, I had one minor clarification. That I have listed in the review comment.

**Comment by Rajakavitha1** [comment]
@makocchi-git  Thanks for the update. The document reads much better now.
Just a minor suggestion. I am not sure if we need a section that reads:
failure-domain.beta.kubernetes.io/region but the content reads: See failure-domain.beta.kubernetes.io/zone. I am wondering if we could have a section title that reads something like failure-domain.beta.kubernetes.io/zone or region

**Pull request merged**
