### PR TITLE
 Correct wrongly written characters

### PR DESCRIPTION
**Pull request by sdghchj**
wrongly written characters

### CODE REVIEW

**Comment by anubha-v-ardhan** [comment]
@sdghchj Please sign the CLA so that your PR can be reviewed
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by sdghchj** [comment]
> @sdghchj Please sign the CLA so that your PR can be reviewed
> https://github.com/kubernetes/community/blob/master/CLA.md

Have signed

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by xichengliudui** [comment]
> > @sdghchj Please sign the CLA so that your PR can be reviewed
> > https://github.com/kubernetes/community/blob/master/CLA.md
> 
> Have signed

check whether your `git commit` signature is consistent

**Comment by sdghchj** [comment]
> > > @sdghchj Please sign the CLA so that your PR can be reviewed
> > > https://github.com/kubernetes/community/blob/master/CLA.md
> > 
> > 
> > Have signed
> 
> check whether your `git commit` signature is consistent

The email is same, but how to set user.name in git, `Full Name` or `Linux Foundation ID` of CLA?

**Comment by sdghchj** [comment]
> > > @sdghchj Please sign the CLA so that your PR can be reviewed
> > > https://github.com/kubernetes/community/blob/master/CLA.md
> > 
> > 
> > Have signed
> 
> check whether your `git commit` signature is consistent

Done

**Comment by xichengliudui** [comment]
good job
/lgtm
/approve

**Comment by tengqm** [comment]
@xichengliudui This file was OUT OF SYNC, and the fix was invalid... Please be careful next time when approving a PR. We need to check whether the targeted file is still in sync.

**Pull request merged**
