### PR TITLE
Docs for: API Server Tracing

### PR DESCRIPTION
**Pull request by dashpole**
Placeholder PR for https://github.com/kubernetes/enhancements/issues/647

### CODE REVIEW

**Comment by sftim** [comment]
@dashpole, did you intend this to be for the v1.20 release? If so, pkease update this PR to target _dev-1.20_ as its base branch.

**Comment by SomtochiAma** [comment]
Hi @dashpole!

This is a friendly reminder that the docs deadline is coming up on 23rd November(right after KubeCon NA). We would appreciate it if you could provide some/all docs content for this feature early so it can be reviewed by  Sig Docs before Kubecon and other events in November.

**Comment by annajung** [comment]
hi @dashpole this is no longer being tracked for 1.20 release.
Please see https://github.com/kubernetes/enhancements/issues/647#issuecomment-726537517 for details 
Feel free to reopen when an exception has been filed/approved. 

/milestone clear
/close

**Pull request closed without merging**
