### PR TITLE
Update expose service intro

### LINKED ISSUE #25341: Using a Service to Expose Your App - misleading documentation
In this document (https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/) service type External name is explained as follows:

**ExternalName** - _Exposes the Service using an arbitrary name (specified by externalName in the spec) by returning a CNAME record with the name. No proxy is used. This type requires v1.7 or higher of kube-dns._

This is misleading. The correct explanation could be (from https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) as follows:

**ExternalName**: _Maps the Service to the contents of the externalName field (e.g. foo.bar.example.com), by returning a CNAME record with its value. No proxying of any kind is set up. This type requires v1.7 or higher of kube-dns, or coreDNS version 0.0.8 or higher._

### PR DESCRIPTION
**Pull request by prankul88**
Fixes #25341

### CODE REVIEW

**Comment by prankul88** [comment]
@sftim Hi, Can you please take a look at this.

**Comment by kbhawkey** [comment]
Ping SIG Network for review
/cc @kubernetes/sig-network-pr-reviews

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-25488--kubernetes-io-master-staging.netlify.app/docs/tutorials/kubernetes-basics/expose/expose-intro/

**Review by sftim — COMMENTED** [review]
LGTM. Would like SIG Network to confirm.

**Comment by prankul88** [comment]
> LGTM. Would like SIG Network to confirm.

Got it. Would wait for them to take a look.

**Pull request merged**
