### PR TITLE
Update assign-pod-node.md

### PR DESCRIPTION
**Pull request by abhi1604**
Removed superfluous sentence

### CODE REVIEW

**Comment by abhi1604** [comment]
I signed it

**Comment by prasadkatti** [comment]
Can you make sure you used the same email address for authoring the commit that you used when signing the CLA?

**Comment by abhi1604** [comment]
> Can you make sure you used the same email address for authoring the commit that you used when signing the CLA?

Hi, Yeah I used the same mail address.

**Comment by abhi1604** [comment]
> @abhi1604 although I agree that the existing text is wordy, the replacement also seems not quite write.
> 
> Values don't run Pods; it's a Node (or the kubelet on that node) that runs a Pod, and the page needs to align with this. I worry that otherwise it could be too confusing for a reader who is new to Kubernetes.

Yeah makes sense, closing PR.

**Pull request closed without merging**
