### PR TITLE
Add YouTube social button in header and footer

### LINKED ISSUE #10226: YouTube channel should be linked from k8s.io
**This is a...** 

- [x ] Feature Request
- [ ] Bug Report

**Problem:**

We have a youtube channel with over 9k subscribers, but we don't link to it from the website! 

**Proposed Solution:**

Link to youtube.com/kubernetescommunity from the kubernetes.io website. Probably at the bottom with a little icon like we do our other properties? 

**Page to Update:**
https://kubernetes.io/

### PR DESCRIPTION
**Pull request by hvaara**
This adds a YouTube social button in the header and footer. The button links to https://www.youtube.com/kubernetescommunity

image

Closes #10226

### CODE REVIEW

**Comment by sftim** [comment]
/lgtm
Thanks for the suggestion @hvaara

**Comment by hvaara** [comment]
Thanks for the review @sftim!
/assign @bradamant3

**Comment by hvaara** [comment]
Rebased on master, fixed merge conflict

**Comment by kbhawkey** [comment]
@hvaara , LGTM.

Page previews:
https://deploy-preview-16838--kubernetes-io-master-staging.netlify.com/

https://deploy-preview-16838--kubernetes-io-master-staging.netlify.com/blog/

https://deploy-preview-16838--kubernetes-io-master-staging.netlify.com/community/

https://deploy-preview-16838--kubernetes-io-master-staging.netlify.com/docs/tutorials/

**Comment by hvaara** [comment]
Thanks a lot for reviewing @kbhawkey!

@Bradamant3 Friendly ping 😃 Do you have time to take a look?

**Comment by hvaara** [comment]
@zacharysarah do you think it's a good idea for me to continue working on this? I'd be happy to update again so it reflects the changes merged in #17325

**Comment by zacharysarah** [comment]
@hvaara It sounds like a cool improvement, so go for it!

**Comment by zacharysarah** [comment]
@hvaara 👋 Please feel free to `/reopen` this when you're ready to resolve merge conflicts and continue.

/close

**Comment by hvaara** [comment]
Hi @zacharysarah 👋 I am currently working on this 

/reopen

**Comment by hvaara** [comment]
@zacharysarah Just pushed my changes. PTAL when you have time
/assign @zacharysarah

**Pull request merged**
