### PR TITLE
FortiADC new ingress controller

### PR DESCRIPTION
**Pull request by erezyfntn**
Hi,

I've added FortiADC to the list, as now FortiADC supports the K8s ingress controller.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@erezyfntn Thanks you for your contribution.

Could you please sign the CLA before the PR can be reviewed.

You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by kbhawkey** [comment]
👋 @erezyfntn 
Before we can review your pull request, you must have a valid CLA.
I am closing this PR. Feel free to reopen it after you have set up your CLA.

/close

**Pull request closed without merging**
