### PR TITLE
Promote ServiceLBNodePortControl feature to GA

### PR DESCRIPTION
**Pull request by tengqm**
xref: kubernetes/kubernetes#107027, kubernetes/kubernetes#107692

### CODE REVIEW

**Comment by reylejano** [comment]
Code PR in https://github.com/kubernetes/kubernetes/pull/107027 has merged
/approve

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-32334--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features

**Pull request merged**
