### PR TITLE
Revise cluster DNS task pages

### PR DESCRIPTION
**Pull request by sftim**
Revise https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/ and https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

(including renaming the latter to https://kubernetes.io/docs/tasks/debug-application-cluster/dns-debugging-resolution/)

### CODE REVIEW

**Comment by tengqm** [comment]
Reapproving
/lgtm
/approve

**Comment by tengqm** [comment]
@sftim When checking the Chinese localization version of the "DNS debugging" page, I realized that this "dns-debugging-resolution.md" should be in the "administer cluster" section. It should not be relocated.

Yes, the content is related to debugging, but DNS debugging is the job for the cluster administrator, not the cluster user (application). Placing this page under the debug-application-cluster may be confusing.

**Comment by sftim** [comment]
I'm not sure how much we want to distinguish tasks by role. Maybe we could have a separate pair of pages to help people find tasks for a particular role. These feel to me like blurred lines.

**Comment by tengqm** [comment]
A long time ago, there was an initiative for role based journey. As a cluster administrator, you are supposed to manage things like node configuration, network and storage configuration etc. As an application developer, you are tasked with things like managing the Deployments, Jobs, application specific Secrets and ConfigMaps, etc. DNS is one of the area for administrator roles. That was the reason the page should not be relocated.

**Comment by sftim** [comment]
@tengqm have you got the cycles to track an issue?
(in my view, the switch to Docsy gives us the lit tinder to tweak the structure of Tasks to cover a little or a lot of chances)

**Comment by tengqm** [comment]
yup.

**Pull request merged**
