### PR TITLE
[ja] fix typo in the cloud-controller-manager section

### PR DESCRIPTION
**Pull request by iterable-company**
It seems very trivial, but it confuses readers for a bit.
I would like to fix it for a time saving for many people.

#### en: 
`If you are running Kubernetes on your own premises, or in a learning environment inside your own PC, the cluster does not have a cloud controller manager.`

####  ja(before):
`KubernetesをオンプレミスあるいはPC内での学習環境で動かす際には、クラスターにcloud container managerはありません。`

#### ja(after):
`KubernetesをオンプレミスあるいはPC内での学習環境で動かす際には、クラスターにcloud controller managerはありません。`

#### diff
```diff
- cloud container manager
+ cloud controller manager
```

### CODE REVIEW

**Comment by bishal7679** [comment]
@iterable-company refrain from using `[ja]` in your commit message. push an empty commit with proper message so that all checks might be passed!

**Comment by t-inu** [comment]
@bishal7679 
For future reference, I would like to know why we need to refrain from using [ja] in the commit message.
Does it mean this string affects the Netlify's deploy process?
Or is it just in order to autorun again?

**Review by t-inu — APPROVED** [review]
It is still unclear the reason why need to refrain from using [ja] in the commit message, but the fix is fine.
/lgtm

**Comment by atoato88** [comment]
Nice catch!
LGTM :+1:

**Comment by iterable-company** [comment]
@t-inu 
Is there anything I have to do for this PR merged?

**Comment by atoato88** [comment]
You don't need any actions, we need to wait the reveiw by approvers.
This PR already has `lgtm` label and need `approve` label next.

**Comment by iterable-company** [comment]
@atoato88 
thanks a lot!

**Comment by nasa9084** [comment]
sorry to be late, and thank you for your first contribution~ :tada:
/approve

**Pull request merged**
