### PR TITLE
Update apt repo GPG key URL

### LINKED ISSUE #42144: Unable to install kubeadm, kubelet and kubectl on Ubuntu 22.04 due to known GPG key issue
The documentation for [Installing kubeadm, kubelet and kubectl](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) fails in step 2 for debian based installs (particularly ubuntu 22.04) due to a known issue: 
https://github.com/kubernetes/release/issues/2862

> 2. Download the Google Cloud public signing key:
> 
> ``` bash
> curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
> ```

The workaround is to use https://dl.k8s.io/apt/doc/apt-key.gpg instead of the google url:
https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585

### PR DESCRIPTION
**Pull request by mrgiles**
Update apt repo GPG key URL to redirect. Fixes #42144

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks @mrgiles 
preview looks good to me: https://deploy-preview-42156--kubernetes-io-main-staging.netlify.app/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

/lgtm

**Review by neolit123 — COMMENTED** [review]
/lgtm
as mentioned on the ticket, this is recommended by sig k8s infra.

**Comment by sftim** [comment]
Thanks

/approve

**Pull request merged**
