### PR TITLE
Add Kusk Gateway

### PR DESCRIPTION
**Pull request by aabedraba**
Adding [Kusk Gateway](https://kusk.kubeshop.io) to the third-party section of the Ingress Controllers

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
please sign CLA
more info https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by aabedraba** [comment]
Thanks @Arhell , on it!

**Review by sftim — COMMENTED** [review]
Thanks

/lgtm

**Pull request merged**
