### PR TITLE
Kill all federation v1 related tasks pages.

### PR DESCRIPTION
**Pull request by Colstuwjx**
Just kill all federation v1 related tasks pages as it is deprecated and outdated.

As discussed in PR #17893 ,  there is leaving page https://kubernetes.io/docs/concepts/cluster-administration/federation/ for telling users that the federation v1 is outdated and it already offers federation v2 link from the deprecation warning block.

Thanks.

### CODE REVIEW

**Comment by Colstuwjx** [comment]
I'm not sure about the next plan about the kubefed documentation building for our website, maybe we need to talk with kubefed OWNERS and make a decision, leave it alone with its own repo, or build some related content in our website.

If it is required to build kubefed docs in our website repo, we may need to create this label `sig/kubefed` and assign OWNERS for this area.

Thanks.

**Comment by sftim** [comment]
I wonder: does it make sense to drop this content during a release, eg for v1.18?
A release leaves room for publicity, release notes, etc and an opportunity to point out why the content has disappeared.

I'm very open to persuasion. If “kill it now” is the better choice, let's do that.

**Comment by Colstuwjx** [comment]
I suggest put this thing on our community meeting and have a conclusion, since kubefed collaborator also [could NOT make this decision](https://github.com/kubernetes-sigs/kubefed/issues/1173#issuecomment-564449242).

**Comment by zacharysarah** [comment]
@Colstuwjx Are you able to attend a weekly meeting to discuss this PR?

**Comment by jimangel** [comment]
@zacharysarah @sftim I'm not sure if this needs discussion as the folks at kubefed already said federation v1 is dead (context: https://github.com/kubernetes/website/issues/13905)

Am I missing anything here? Otherwise LGTM.

**Comment by kbhawkey** [comment]
Placing a hold until agreement is reached.
/hold

**Comment by zacharysarah** [comment]
@jimangel Good point!

@kubernetes/sig-multicluster-pr-reviews 👋 We'd like to delete these deprecated docs. If we haven't heard otherwise from you within 48 hours, we'll go ahead and remove them. (Feel free to chime in sooner! 😅 )

**Comment by Colstuwjx** [comment]
Rebased for ready to merge.

**Comment by kbhawkey** [comment]
Has a decision been made about the federation task content?
@jimangel , I guess your umbrella issue, https://github.com/kubernetes/website/issues/13905,
lists the federation concepts page(s) as out of scope. 

```
Out of scope, to be left alone and updated by #sig-multicluster before EOY 2019

    https://kubernetes.io/docs/concepts/cluster-administration/federation/
    https://kubernetes.io/docs/tasks/federation/
```

There is also the content in the _redirects file.

**Comment by zacharysarah** [comment]
@kbhawkey No response from @kubernetes/sig-cluster-lifecycle-pr-reviews, so feel free to LGTM. 👍 

/hold cancel
/approve

**Comment by neolit123** [comment]
> @kbhawkey No response from @kubernetes/sig-cluster-lifecycle-pr-reviews, so feel free to LGTM.

SIG Multicluster might have missed this PR. not sure who is still active in this group.

sending them a message in #sig-multicluster might provide more visibility.
i see the channel is still active.

**Comment by zacharysarah** [comment]
@neolit123 Will do. Temporary hold:

/hold

**Comment by zacharysarah** [comment]
@neolit123 No response in 24 hours from [#sig-multicluster](https://kubernetes.slack.com/archives/C09R1PJR3/p1582056262085700) so I think we're good to proceed.

@kbhawkey Feel free to LGTM when ready

/hold cancel

**Comment by kbhawkey** [comment]
The federation task section is indeed removed.
Should follow up with a PR to remove the information in the main task page,
https://deploy-preview-17949--kubernetes-io-master-staging.netlify.com/docs/tasks/#administering-federation

**Pull request merged**
