### PR TITLE
Graduate JobReadyPods to beta

### PR DESCRIPTION
**Pull request by alculquicondor**
Update the feature gates table. The only documentation for the feature is in the API field itself.

/sig apps

kubernetes/enhancements#2879

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
As this is a minor detail and we don't document equivalent fields (eg `status.readyReplicas`), I think this is the only docs change required here.

LGTM.

**Comment by tengqm** [comment]
/hold
Adding a hold for accidental merge before the upstream change kubernetes/kubernetes#107476 makes its way into 1.24.

**Comment by tengqm** [comment]
/hold cancel
Upstream code is in now.

**Pull request merged**
