### PR TITLE
content: zh-cn: Resync concepts/workloads/controllers/statefulset

### PR DESCRIPTION
**Pull request by knthm**
**Gib** (Gibibit) was used where **GiB** (Gibibyte) is intended.

#### Related PRs

- #43238
- #43319
- #43320
- #43321
- #43322
- #43323

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @knthm , zh-cn location does not accept partial changes, which my compromise the effect of `./scripts/lsync.sh`. You can find more insynced content with en upstream by running this command on your local `main` branch:

```
./scripts/lsync.sh content/zh-cn/docs/concepts/workloads/controllers/statefulset.md
```
image

/hold

**Comment by knthm** [comment]
@windsonsea 

Looks good to me :shrug:

**Comment by knthm** [comment]
@windsonsea 

I've amended the commit with all missing changes marked by `lsync.sh`.

I don't speak Mandarin Chinese, so I used ChatGPT to translate the missing segments. Hopefully they're acceptable.

**Comment by knthm** [comment]
Closed in favor of #43397

**Pull request closed without merging**
