### PR TITLE
[de] Fix typo in "Pods" page

### PR DESCRIPTION
**Pull request by peacock-2000**
correted Typo in German Docs about Networking of Pods

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@peacock-2000 Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Comment by dipesh-rawat** [comment]
/retitle [de] Fix typo in "Pods" page

**Review by Arhell — COMMENTED** [review]
/easycla

**Review by rlenferink — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
