### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by gabe-sky**
Simply fixing a typo in the CSI volume cloning document

### CODE REVIEW

**Review by Aut0R3V — APPROVED** [review]

**Review by Arhell — COMMENTED** [review]
@gabe-sky
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by bradtopol** [comment]
Hi @gabe-sky Thank you for your contribution. Please sign the CLA so we can accept your PR for review.

**Comment by kbhawkey** [comment]
Hi @gabe-sky .
Reach out if you need more information to sign the CLA?

**Comment by kbhawkey** [comment]
👋 @gabe-sky .
I am closing this pull request. Without a signed CLA, this PR cannot move forward.
You can reopen this PR at any time to continue to work on the changes.
Reach out if you need help or have questions.
/close

**Pull request closed without merging**
