### PR TITLE
add a annotation for spec.selecter

### PR DESCRIPTION
**Pull request by shenyuanyu**

### CODE REVIEW

**Comment by shenyuanyu** [comment]
@zhangxiaoyu-zidif

**Comment by zhangxiaoyu-zidif** [comment]
seems to be easy to understand for newbee.
how do you think, @tengqm

**Comment by steveperry-53** [comment]
Tough call, but I agree with @tengqm. I would rather call out specific aspects of the yaml file in the surrounding text. That way a yaml file can be shared by multiple topics . Each topic could then call out the relevant fields of the yaml file in the context of the topic. I recommend closing this PR. But I'm open to further discussion if others want to continue pursuing this.

**Comment by shenyuanyu** [comment]
I just want the pure newbie can get more infomation from a  emaple  yaml file. If you think that is not necessary, I will close the PR.

**Pull request closed without merging**
