### PR TITLE
Control Plane object is updated

### PR DESCRIPTION
**Pull request by varadaprasanth**
Control Plane object is formatted

### CODE REVIEW

**Comment by sftim** [comment]
@varadaprasanth can you briefly explain why this is the right change to make (why is “control plane” the wrong capitalization)?

**Comment by varadaprasanth** [comment]
> @varadaprasanth can you briefly explain why this is the right change to make (why is “control plane” the wrong capitalization)?

@sftim   I have seen that Control Plane is defined in the Glossary section in below link
https://kubernetes.io/docs/reference/glossary/?all=true#term-control-plane
As per those standards, corrected this wrong capitalization.

**Comment by sftim** [comment]
I wrote about “control plane” vs  “Control Plane” in the conversation thread that starts at https://github.com/kubernetes/website/pull/20265#issuecomment-615279059 

I prefer “control plane” here @varadaprasanth

**Comment by varadaprasanth** [comment]
> I wrote about “control plane” vs “Control Plane” in the conversation thread that starts at [#20265 (comment)](https://github.com/kubernetes/website/pull/20265#issuecomment-615279059)
> 
> I prefer “control plane” here @varadaprasanth

@sftim thanks for posting the other thread for my reference to your conversation.
But actually I have some confusion here now, whether the "control plane" should be capitalized or should not be, as per the standards.

**Comment by sftim** [comment]
With my approver hat on, I recommend “control plane” in the main text of an article. It's rare to write the term capitalized in running text.

**Comment by varadaprasanth** [comment]
> With my approver hat on, I recommend “control plane” in the main text of an article. It's rare to write the term capitalized in running text.

@sftim sure, got your point. Let it be with no change there, I will be closing this PR :)

**Comment by varadaprasanth** [comment]
No change is required, hence closing this PR.

**Pull request closed without merging**
