### PR TITLE
Fix minikube description

### PR DESCRIPTION
**Pull request by gt814**
Fix minikube description
docs/tasks/_index.md

Related issues
https://github.com/kubernetes/website/issues/38201

### CODE REVIEW

**Review by Shubham82 — CHANGES_REQUESTED** [review]
you can remove the word minikube, it appears two times. write like below one:

> locally. `minikube` runs an all-in-one or a multi-node local Kubernetes cluster on your personal

**Comment by gt814** [comment]
> you can remove the word minikube, it appears two times. write like below one:
> 
> > locally. `minikube` runs an all-in-one or a multi-node local Kubernetes cluster on your personal

Thank you for your comment! 
Done.

**Comment by Shubham82** [comment]
Preview look good to me: https://deploy-preview-38219--kubernetes-io-main-staging.netlify.app/docs/tasks/tools/#minikube

/lgtm

**Pull request merged**
