### PR TITLE
TR Docs

### PR DESCRIPTION
**Pull request by halil-bugol**
Turkish documentation file base added.

### CODE REVIEW

**Comment by reylejano** [comment]
Hi @halil-bugol , are you looking to start a localization for Turkish?
Please take a look at this section on starting a new localization: https://kubernetes.io/docs/contribute/localization/#start-a-new-localization
Have you brought up starting a localization for Turkish on the [sig-docs](https://kubernetes.slack.com/messages/sig-docs) or [sig-docs-localization](https://kubernetes.slack.com/messages/sig-docs-localizations) Slack channel?

One of the first steps is to have 2 contributors for the Turkish localization. The contributors should be Kubernetes org members so they can be added to the appropriate owners file for the Turkish localization in a development branch for the Turkish localization. A SIG Docs co-chair (such as myself) or tech lead helps create the development branch for the Turkish localization when there are 2 contributors (who are Kubernetes org members) willing to start the Turkish localization.

**Comment by natalisucks** [comment]
/hold

Hi @halil-bugol! I'm another co-chair of SIG Docs and one of the current Localization subproject leads. Its great to see an interest in starting a Turkish localization!

As @reylejano mentioned, there are a few steps to progress through before creating Turkish files. As leads, its hard for us to support a localization when the first time we're hearing about it is through a PR. With this in mind, we'd love for you and other interested Turkish folks to attend the upcoming Localization meeting, which is available on the SIG Docs calendar – please join the [SIG Docs mailing list](https://groups.google.com/forum/#!forum/kubernetes-sig-docs) to gain access. It takes place monthly, with the next one coming up on April 3rd. Alternatively, we'd be happy to chat to you in our #sig-docs-localizations channel on the Kubernetes Slack if attending the meeting isn't possible right now.

By chatting through your intentions with us, we can help you understand the requirements, answer your questions, and also help with any other administrative needs to be able to get the localization going. With this being the case, I am holding this PR until that conversation takes place.

Looking forward to chatting to you and other interested parties soon 🤘

**Pull request closed without merging**
