### PR TITLE
Add area/localization label in content/bn/OWNERS

### PR DESCRIPTION
**Pull request by Okabe-Junya**
## Feature Description

- Add `area/localization` label in content/bn/OWNERS
    - other languages have `area/localization` label (ref. #42206 )

```console
$ pwd
/path/to/website
$ grep -RIn "area/localization" ./content/**/OWNERS
./content/bn/OWNERS:13:- area/localization
./content/de/OWNERS:14:- area/localization
./content/es/OWNERS:14:- area/localization
./content/fr/OWNERS:14:- area/localization
./content/hi/OWNERS:14:- area/localization
./content/id/OWNERS:14:- area/localization
./content/it/OWNERS:12:- area/localization
./content/ja/OWNERS:14:- area/localization
./content/ko/OWNERS:14:- area/localization
./content/pl/OWNERS:14:- area/localization
./content/pt-br/OWNERS:12:- area/localization
./content/ru/OWNERS:14:- area/localization
./content/uk/OWNERS:14:- area/localization
./content/vi/OWNERS:14:- area/localization
./content/zh-cn/OWNERS:14:- area/localization
```

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/lgtm

Thanks

**Comment by Okabe-Junya** [comment]
Sorry, I add empty line, so PTAL again @sftim

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for identifying and fixing this!

/lgtm

**Comment by Okabe-Junya** [comment]
/assign asem-hamid 

PTAL @asem-hamid to move forward this PR, thank you!! 

(Since I know you are actively worked in the bn l10n team, let me assign)

**Pull request merged**
