### PR TITLE
update link to CloudProvider Interface

### PR DESCRIPTION
**Pull request by ping035627**
The link to CloudProvider Interface is mistake, I update it.

### CODE REVIEW

**Comment by tengqm** [comment]
can we avoid using a hash code? maybe a tag would be better...

**Comment by ping035627** [comment]
The link is right in release-1.12, but the link in master is wrong, if it isn't allowed to modify the master branch, I think it should be closed.

**Comment by tengqm** [comment]
@ping035627 We had this kind of PRs as workarounds. Pinning to a specific hash id is not a good practice. We can wait until there is a stable branch?

**Pull request closed without merging**
