### PR TITLE
chore: fix invalid location.hash

### PR DESCRIPTION
**Pull request by oke-py**
The correct links are
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#eviction-api

### CODE REVIEW

**Comment by oke-py** [comment]
https://deploy-preview-26783--kubernetes-io-master-staging.netlify.app/docs/concepts/workloads/pods/disruptions/

**Comment by kbhawkey** [comment]
👋 @oke-py . Thanks for contributing!
/lgtm

**Pull request merged**
