### PR TITLE
Add link to KubeCon Virtual EU 2021

### PR DESCRIPTION
**Pull request by inductor**
This PR adds link to KubeCon Virtual EU 2021 in the index.html

image

### CODE REVIEW

**Comment by sftim** [comment]
Markdown looks OK
/lgtm

_aside_ I think we could use [headless bundles](https://gohugo.io/content-management/page-bundles/#headless-bundle) to represent events and generate pages that use them. Maybe even JSON-LD as well.

**Comment by inductor** [comment]
@sftim I think it should be dealt with as a new issue. I would not mind if you wanna close it and try the new way for this time

**Review by irvifa — COMMENTED** [review]
/lgtm

**Comment by irvifa** [comment]
Do we need a separate PR to deal with the bundle? Or will we need to solve here there?

**Comment by zacharysarah** [comment]
Let’s approve for now, and treat headless bundle implementation as a separate issue.

/approve

**Pull request merged**
