### PR TITLE
Merge master into dev-1.22 

### PR DESCRIPTION
**Pull request by PI-Victor**
Merge master into dev-1.22 to keep in sync - SIG-Release 1.22 Docs team 6/4/21

/cc @ashnehete @carlisia @chrisnegus @ritpanjw

### CODE REVIEW

**Comment by PI-Victor** [comment]
commit https://github.com/kubernetes/website/pull/28289/commits/cbb5e9e18120c25ceac90afbd9cb44e27bc8372c https://github.com/kubernetes/website/pull/28289/commits/fcefe0776a9d24f2ff2d64b248add7fe219a6e84  was resolved in https://github.com/kubernetes/website/pull/27963

**Review by irvifa — COMMENTED** [review]
/approve

**Comment by kbhawkey** [comment]
Looks like we may need another round of approvals (SIG release and steering committee)?
/cc @kubernetes/sig-release-leads @kubernetes/steering-committee

**Comment by kbhawkey** [comment]
Hello @kubernetes/steering-committee.
Would you have time to review/approve? There appears to be a file that requires your approval. Thanks!

**Pull request merged**
