### PR TITLE
remove nodes resource from CoreDNS rbac

### PR DESCRIPTION
**Pull request by nberlee**
~~merge when https://github.com/kubernetes/kubernetes/pull/117521 is merged~~

 https://github.com/kubernetes/kubernetes/pull/117521 is merged

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Review by dipesh-rawat — COMMENTED** [review]
Hi @nberlee Thank you for your contribution!
We have different processes followed within different localisations of the project. Therefore, I'd request you to make changes to ONLY the main website i.e. the _English_ language with this PR and then raise a separate PR for other languages.

**Comment by nberlee** [comment]
I've forced pushed the request change so it follows the process, even if it doesn't makes to much sense to me in this context

**Review by dipesh-rawat — COMMENTED** [review]
LGTM makes sense.

/lgtm

Deploy Preview: [deploy-preview-40800-dns-debugging-resolution](https://deploy-preview-40800--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/dns-debugging-resolution/)

**Comment by sftim** [comment]
/hold
> merge when https://github.com/kubernetes/kubernetes/pull/117521 is merged

**Comment by reylejano** [comment]
https://github.com/kubernetes/kubernetes/pull/117521 merged
/approve

**Pull request merged**
