### PR TITLE
Fix relative links issue in ko content

### PR DESCRIPTION
**Pull request by chenrui333**
relates to #13296

### CODE REVIEW

**Comment by gochist** [comment]
@chenrui333 Thank you! :+1: FYI, the Korean localization team usually tracks upstream(English) changes and apply them to downstream(Korean) on every team milestone(2~3 weeks interval). 

@ianychoi @ClaudiaJKang For Korean localization, we usually use `dev-1.13-ko.<latest team milestone>` as a base branch following the [l10n guide](https://kubernetes.io/docs/contribute/localization/#branching-strategy). However, we were done with our last iteration for 1.13(`dev-1.13-ko.8`) at 19th March and now we are just waiting for 1.14 release. So now there's no working branch for ko-l10n temporarily. So I think using `master` branch is okay before we have `dev-1.14-ko.1`. What do you think? If you agree, please give "approve" for this PR.

/lgtm

**Comment by ClaudiaJKang** [comment]
@chenrui333 Thank you! 

@gochist I agree with you 👍 

/approve

**Pull request merged**
