### PR TITLE
Merged master dev 1.17

### PR DESCRIPTION
**Pull request by daminisatya**

### CODE REVIEW

**Comment by zacharysarah** [comment]
@daminisatya It looks like the [do-not-merge](https://github.com/kubernetes/website/pull/17958#issuecomment-562053285) label is related to #17888 and #17889, which have GitHub magic words in the title. I'm surprised the individual PRs didn't have warning labels.

UPDATE: It looks like #17888 and #17889 did have `do-not-merge` labels, but the PR author manually removed the labels to circumvent Prow.

**Comment by daminisatya** [comment]
Thank you @zacharysarah. 

Once your fix is merged, I need to remerge master into dev-1.17

**Comment by zacharysarah** [comment]
Per [Slack](https://kubernetes.slack.com/archives/CA1MMM1HU/p1575588951060000), reverting doesn’t remove the problematic commits. In this case, the best solution to bad behavior is...yet more bad behavior. 🤦‍♂ I’m removing the warning label and hoping we never have to deal with this again.

**Comment by daminisatya** [comment]
+1

**Pull request merged**
