### PR TITLE
feat: Add ngrok k8s ingress controller to the list of Ingress Controllers

### PR DESCRIPTION
**Pull request by russorat**
ngrok has released a new kubernetes ingress controller. This PR adds that controller in alphabetical order to the list of existing ingress controllers for kubernetes. 

for more information, see https://github.com/ngrok/kubernetes-ingress-controller

thank you!

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@russorat  Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by russorat** [comment]
hi, i believe the CLA is signed. please let me know if there is anything else to do here. thanks!

**Comment by mengjiao-liu** [comment]
Now you just need to wait for the review.
/label tide/merge-method-squash

**Pull request merged**
