### PR TITLE
change to "host namespaces" and remove command prompts

### LINKED ISSUE #9524: Issue with k8s.io/docs/concepts/policy/pod-security-policy/
**This is  a  request to provide better clarification to PSP doc page. ** 

- [x] Bug Report

**Problem:**
I believe the line "Usage of the root namespaces" is confusing. It can be better understood with "Usage of the host namespaces". Also discussed this with @liggitt 

**Proposed Solution:**
Change the line to "Usage of the host namespaces"

**Page to Update:**
https://kubernetes.io/docs/concepts/policy/pod-security-policy/

### PR DESCRIPTION
**Pull request by makocchi-git**
closes #9524 

* change to `host namespaces` from `the root namespaces`
* remove command prompts
* wrap a note by shortcodes

### CODE REVIEW

**Comment by makocchi-git** [comment]
[preview is here](https://deploy-preview-9553--kubernetes-io-master-staging.netlify.com/docs/concepts/policy/pod-security-policy/)
[original](https://kubernetes.io/docs/concepts/policy/pod-security-policy/)

**Comment by CaoShuFeng** [comment]
> remove command prompts

Why remove them?

**Comment by tengqm** [comment]
@CaoShuFeng https://kubernetes.io/docs/home/contribute/style-guide/#code-snippet-formatting

**Comment by tallclair** [comment]
/lgtm
Thanks!

**Pull request merged**
