### PR TITLE
Clarify PDB line in disruptions concept page

### PR DESCRIPTION
**Pull request by wiggitywhitney**
✿♬ﾟ+.(｡◡‿◡)♪  Happy Sunday!

Since this line got changed in the glossary entry, Divya suggested that I change it here too.  ♫

### CODE REVIEW

**Comment by wiggitywhitney** [comment]
Here is the related PR where Divya makes the suggestion:
https://github.com/kubernetes/website/pull/30566

**Comment by divya-mohan0209** [comment]
/lgtm to me.
Will await approval from another sig docs reviewer for sign-off.

**Review by sftim — COMMENTED** [review]
/approve

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/30586#issuecomment-977933821 intended to set /lgtm
/lgtm

BTYW @divya-mohan0209 trailing text makes Prow wary of counting the LGTM.

**Comment by divya-mohan0209** [comment]
@sftim noted! Apologies for the confusion :)

**Pull request merged**
