### PR TITLE
Add clarifications for volume snapshots

### PR DESCRIPTION
**Pull request by xing-yang**
This PR adds clarifications for volume snapshots.

### CODE REVIEW

**Comment by xing-yang** [comment]
@jingxu97 @saad-ali Please take a look.  Thanks.

**Comment by zparnold** [comment]
Hi @xing-yang @saad-ali I pinged you both on Slack, but just for record here, could I please have some 👀 on this PR?

**Comment by zparnold** [comment]
/approve 
from docs as long as we get a technical lgtm

**Pull request merged**
