### PR TITLE
[no] add searchbar to index page

### PR DESCRIPTION
**Pull request by Arhell**

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Although the changes look good, just noticed that the Norwegian language is disabled in the [hugo.toml](https://github.com/kubernetes/website/blob/main/hugo.toml#L37), and there are no formal [reviewers/approvers](https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES) defined. This suggests that the Norwegian localization might not be live which raises uncertainty about merging these changes. 

Deferring to the Localization Subproject chairs @seokho-son  @a-mccarthy, for their advice in this particular situation. _(Apologies for the ping, folks!)_

**Comment by seokho-son** [comment]
Hi @dipesh-rawat,

Thank you for the notification! 😊

I wanted to clarify that the Norwegian language addition to the Hugo localization was initially for testing purposes, as seen in this commit: [1b5ff98](https://github.com/kubernetes/website/commit/1b5ff98a4473be60d94d35e330d9801640d6f58d#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77). 
Since we have multiple active languages, maintaining a test language isn't necessary. Any new tentative language additions should use the existing examples as a reference.

I'm inclined to accept this PR, but please be informed that I plan to organize the removal of the test content subsequently.

**Review by kumarankit999 — COMMENTED** [review]
looks good, seokho ??

**Comment by sftim** [comment]
LGTM; also having regard to https://github.com/kubernetes/website/pull/43793#issuecomment-1791872901

**Pull request closed without merging**
