### PR TITLE
[bn] adding files in content/bn/example

### PR DESCRIPTION
**Pull request by SAShameem**
adding files in content/bn/example
Fixes : #44993

### CODE REVIEW

**Comment by asem-hamid** [comment]
wonderful @SAShameem . 

Thanks for contributing

**Review by mitul3737 — APPROVED** [review]

**Review by Imtiaz1234 — APPROVED** [review]

**Comment by asem-hamid** [comment]
To fix netlify build  errors follow this steps :

image


 1 ) go to your fork repo .
 2) go to dev-1.24-bn.1 branch 
 3 ) sync fork  
     
image

4) go to PR section and create new PR 

image


5) take your own forked repo as a base repository 

image


6) take your PR branch as base 

image


7) take dev-1.24-bn.1 as compare and create PR  

image


8)  
image

9) merge this PR 

image

10 ) and done

**Comment by asem-hamid** [comment]
@SAShameem  Kubernetes is one of the largest open-source repositories in the world, and as such, we encounter many obstacles along the way. It's our responsibility to address and overcome them  as a contributor .

**Comment by SAShameem** [comment]
> wonderful work @SAShameem .
> 
> Thanks for contributing

Thanks Bhaiya for giving the opportunity. Happy to be a part of Kubernetes with my little contributions; 

I will fix the netlify build errors soon.

**Comment by asem-hamid** [comment]
Well done vaiya 

/lgtm

**Pull request merged**
