### PR TITLE
Remove trailing spaces from it documents(#16742)

### PR DESCRIPTION
**Pull request by furukawa3**
This PR removes trailing spaces from "it" doc.  Following command are used.
```
sed -i 's/[ ]*$//' $(find content/it -type f -not -name "*.png" -not -name "*.jpg" -not -name "*.svg" -not -name "*.gif")
```

### CODE REVIEW

**Comment by furukawa3** [comment]
@rlenferink  Hi,  could you also review my patch, please??

**Comment by rlenferink** [comment]
I left it open because it will definitely conflict with PR #15349, which restructures the Italian pages. After merging that one, feel free to rebase this PR / close and open another PR to remove the spaces.

**Comment by furukawa3** [comment]
> I left it open because it will definitely conflict with PR #15349, which restructures the Italian pages. After merging that one, feel free to rebase this PR / close and open another PR to remove the spaces.

I see.  will do it !  Thanks.

**Comment by rlenferink** [comment]
#15349 is merged. Can you rebase this PR against the latest master?

**Comment by furukawa3** [comment]
> #15349 is merged. Can you rebase this PR against the latest master?

Sure!!  will rebase it!

**Comment by kbhawkey** [comment]
Ping @rlenferink , Would you have time to review?

**Comment by rlenferink** [comment]
Thanks for the ping, will take a look tomorrow!

**Pull request merged**
