### PR TITLE
Fix broken anchor link of #type-nodeport in service.md

### PR DESCRIPTION
**Pull request by sandipanpanda**
This PR fixes the broken anchor link of [#nodeport](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) in [Service](https://kubernetes.io/docs/concepts/services-networking/service/). 

We can see that [many files](https://cs.k8s.io/?q=https%3A%2F%2Fkubernetes.io%2Fdocs%2Fconcepts%2Fservices-networking%2Fservice%2F%23type-nodeport&i=nope&files=&excludeFiles=&repos=) redirect to https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport.  But the anchor link is broken. In the website it is https://kubernetes.io/docs/concepts/services-networking/service/#nodeport. Merging this PR will fix this issue and correctly redirect to the linked portion of the Type NodePort.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
However, many files redirect to https://kubernetes.io/docs/concepts/services-networking/service/#nodeport too.

https://cs.k8s.io/?q=docs%2Fconcepts%2Fservices-networking%2Fservice%2F%23nodeport&i=nope&files=&excludeFiles=&repos=

image

---

https://cs.k8s.io/?q=docs%2Fconcepts%2Fservices-networking%2Fservice%2F%23type-nodeport&i=nope&files=&excludeFiles=&repos=

image

**Comment by geoffcline** [comment]
I agree with @jihoon-seo, it's better to fix the references then rename the target.

**Comment by sandipanpanda** [comment]
As in https://github.com/kubernetes/website/pull/30388#issuecomment-963772337, you can see that no. of files redirecting to [#type-nodeport](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport) is 230, whereas for [#nodeport](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) it is only 31. Making changes to 230 files is though possible, but would take much toil. Hence, I thought making changes to the latter will be practically feasible. 

I have made PRs for the necessary updates to the `en` docs and other repos. Updating the anchor link in various localization remains to be done.

**Comment by tengqm** [comment]
/label tide/merge-method-squash

If using '#nodeport' is the preferred fix, why this one is still using '#type-nodeport'?

**Comment by sandipanpanda** [comment]
Thank you @tengqm for your feedback, I believe using `#type-nodeport` is the preferred fix, that's why I think it is used to around 230 files in upstream code comments. `#nodeport` is used only in some markdown files and updating them would be an easy fix.

**Comment by reylejano** [comment]
/hold
I tested the proposed change in this PR and the proposed update breaks the link
Original link (URL based not path based to test)
https://kubernetes.io/docs/concepts/services-networking/service/#nodeport
Proposed link
https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport

**Comment by sandipanpanda** [comment]
> /hold As @jihoon-seo stated this will break many links The original link is correct and working and should not be changed

But what about the links in 230 files that are already broken? Any suggestions on how to fix that?

**Comment by sandipanpanda** [comment]
Thank you @reylejano for the /lgtm :tada:

**Pull request merged**
