### PR TITLE
Localizes Kubernetes expose and update fragments to Bengali

### PR DESCRIPTION
**Pull request by Acesif**
Signed-off-by:  Acesif asifpalak@gmail.com

Localizes `content/bn/docs/tutorials/kubernetes-basics/expose/_index.md`, `content/bn/docs/tutorials/kubernetes-basics/expose/expose-interactive.html`, `content/bn/docs/tutorials/kubernetes-basics/expose/expose-intro.html` and `content/bn/docs/tutorials/kubernetes-basics/update/_index.md` to Bengali

Tracking issue: #31677

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/hold

This PR changes existing _English_ text into Begali. We should instead add new Bengali pages.

**Comment by mitul3737** [comment]
@sftim  I will  check this case from now on.

**Comment by mitul3737** [comment]
Kindly close this issue @Acesif

**Pull request closed without merging**
