### PR TITLE
[fr] Update hyperlinks to point to main branch

### PR DESCRIPTION
**Pull request by KoditkarVedant**
#31744 - Update hyperlinks present in Français locals pages to point to main branch

### CODE REVIEW

**Comment by natalisucks** [comment]
Thanks for these changes 👏

/lgtm

**Comment by mtardy** [comment]
/lgtm
This PR fixes all the issues in the French translation (and remove 4 trailing white lines btw).
However we can spot a few others (2 in *zh* and 1 in *en*) doing `grep -r 'website/blob/master' content`
```text
content/zh/blog/_posts/2018-11-08-kubernetes-docs-update-i18n.md:<!-- L10n teams can now review and approve their own PRs. For example, review and approval permissions for English are [assigned in an OWNERS file](https://github.com/kubernetes/website/blob/master/content/en/OWNERS) in the top subfolder for English content.  -->
content/zh/blog/_posts/2018-11-08-kubernetes-docs-update-i18n.md:L10n 团队现在可以审查和批准他们自己的 PR。例如，英语的审核和批准权限在位于用于显示英语内容的顶级子文件夹中的 [OWNERS 文件中指定](https://github.com/kubernetes/website/blob/master/content/en/OWNERS)。
content/fr/docs/contribute/localization.md:Les localisations doivent inclure le contenu des éléments suivants [`i18n/en.toml`](https://github.com/kubernetes/website/blob/master/i18n/en.toml) dans un nouveau fichier spécifique à la langue.
content/fr/docs/contribute/participating.md:Pour postuler, ouvrez une pull request et ajoutez vous à la section `reviewers` du fichier [top-level OWNERS](https://github.com/kubernetes/website/blob/master/OWNERS) dans le dépôt `kubernetes/website`.
content/fr/docs/contribute/participating.md:Pour postuler, ouvrez une pull request pour vous ajouter à la section `approvers` du fichier [top-level OWNERS](https://github.com/kubernetes/website/blob/master/OWNERS) dans le dépot `kubernetes/website`.
content/fr/docs/contribute/participating.md:Ces deux plugins utilisent les fichiers [OWNERS](https://github.com/kubernetes/website/blob/master/OWNERS) et [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES) à la racine du dépôt Github `kubernetes/website` pour contrôler comment prow fonctionne.
content/fr/docs/contribute/participating.md:Un fichier [OWNERS](https://github.com/kubernetes/website/blob/master/OWNERS) contient une liste de personnes qui sont des relecteurs et des approbateurs SIG Docs.
content/en/blog/_posts/2018-11-08-kubernetes-docs-update-i18n.md:L10n teams can now review and approve their own PRs. For example, review and approval permissions for English are [assigned in an OWNERS file](https://github.com/kubernetes/website/blob/master/content/en/OWNERS) in the top subfolder for English content.
```

**Comment by natalisucks** [comment]
I'd have us open separate PRs to address the other link changes needed in zh and en docs 👍 
/approve

**Comment by mtardy** [comment]
> I'd have us open separate PRs to address the other link changes needed in zh and en docs 👍 /approve

I can do that!

**Comment by mtardy** [comment]
Ok done :D

**Pull request merged**
