### PR TITLE
[ar] Merge main branch into Arabic dev branch

### PR DESCRIPTION
**Pull request by mboukhalfa**
Rebase arabic dev branch on main to keep updated with latest version

### CODE REVIEW

**Comment by sftim** [comment]
/hold

We don't rebase this kind of branch; instead, we merge in the smallest fix that we need to.

**Comment by sftim** [comment]
Ah, this PR is actually a PR to launch Arabic?

/retitle [ar] Launch Arabic localization

/hold
The localization doesn't look ready to launch, and it will need tech lead approval once it is.

**Comment by sftim** [comment]
I had it backwards. This isn't a rebase; it's a merge of _main_ into the Arabic branch.

/retitle [ar] Merge main branch into Arabic dev branch

However, this won't work. Ask on Slack about alternative approaches @mboukhalfa

**Comment by mboukhalfa** [comment]
surpassed by #46447

**Pull request closed without merging**
