### PR TITLE
Update docs for v1 resource quota configuration

### PR DESCRIPTION
**Pull request by liggitt**
Hold for https://github.com/kubernetes/kubernetes/pull/85099 and https://github.com/kubernetes/kubernetes/pull/85098

/cc @deads2k

### CODE REVIEW

**Comment by liggitt** [comment]
cc @ravisantoshgudimetla @ahg-g

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-17547--kubernetes-io-vnext-staging.netlify.com/docs/concepts/policy/resource-quotas/

**Comment by kbhawkey** [comment]
@liggitt , duplicate with #17548 , #17549?

**Comment by daminisatya** [comment]
@liggitt @kbhawkey Is this supposed to by merged first? and then https://github.com/kubernetes/website/pull/17548 and https://github.com/kubernetes/website/pull/17549 ?

**Comment by kbhawkey** [comment]
These changes look OK (docs), though, the other PRs seem to contain the identical content. I don't see the point of including this exact change in the other PRs. Thanks.

**Comment by liggitt** [comment]
> @liggitt @kbhawkey Is this supposed to by merged first? and then #17548 and #17549 ?

Yes

> These changes look OK (docs), though, the other PRs seem to contain the identical content. I don't see the point of including this exact change in the other PRs. Thanks.

They touched the same files for different reasons, and doing independent PRs would have caused rebase issues as each PR was merged

**Pull request merged**
