### PR TITLE
[hi] Updated menu option to "Documentation" from "Home"

### PR DESCRIPTION
**Pull request by steve-hardman**
Taking hint from https://github.com/kubernetes/website/issues/43900#issuecomment-1810988608  to come up with fix.

This will fix https://github.com/kubernetes/website/issues/43900

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/retitle [hi] Updated menu option to "Documentation" from "Home"

**Review by dipesh-rawat — COMMENTED** [review]
Based on the rendered preview, the change looks fine.
LGTM

Preview Page: [https://deploy-preview/hi/docs/home](https://deploy-preview-43943--kubernetes-io-main-staging.netlify.app/hi/docs/home/)

**Review by aj11anuj — COMMENTED** [review]
/lgtm

**Pull request merged**
