### PR TITLE
Replace network solution with network add-on

### LINKED ISSUE #26722: Terms "network solution" and "network add-on" should be unified.
**This is a Bug Report**

**Problem:**

There are words should be unified in [Troubleshooting kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/) and [Installing Addons](https://kubernetes.io/docs/concepts/cluster-administration/addons/).

For the sake of clarity, the same words should be used for things that have the same meaning.

**Proposed Solution:**

We should use either the terms "network solution" or "network add-on".

**Page to Update:**

- Troubleshooting kubeadm: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/
- Installing Addons: https://kubernetes.io/docs/concepts/cluster-administration/addons/

### PR DESCRIPTION
**Pull request by neha-viswanathan**
Closes #26722 

This PR replaces `network solution` with `network add-on` in [Troubleshooting kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/).

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the PR

/lgtm
/sig cluster-lifecycle

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-26770--kubernetes-io-master-staging.netlify.app/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#pods-in-runcontainererror-crashloopbackoff-or-error-state

**Comment by kbhawkey** [comment]
👋 @neha-viswanathan . Thanks for contributing!
/approve

**Pull request merged**
