### PR TITLE
Highlight important comment in API encryption at rest task

### PR DESCRIPTION
**Pull request by sftim**
This is split out from PR https://github.com/kubernetes/website/pull/33285 in order to make a review more likely. See that PR and its previews to show the changes in a wider context. There is also a [preview](https://deploy-preview-44675--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/encrypt-data/#understanding-the-encryption-at-rest-configuration) for _this_ PR.

Make a comment in some YAML extra obvious to readers.

/sig security docs
/language en

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Highlight important comment in API encryption at rest task

**Review by Princesso — COMMENTED** [review]
/lgtm

**Review by vaibhav2107 — APPROVED** [review]
/lgtm

**Comment by reylejano** [comment]
Highlighting the caution is good for readers
/approve

**Pull request merged**
