### PR TITLE
add IBM cloud instruction for internal lb

### PR DESCRIPTION
**Pull request by linsun**
as titled

### CODE REVIEW

**Comment by linsun** [comment]
working on cla now cc @bradtopol

**Comment by zacharysarah** [comment]
@linsun 👋 Do you need help signing the CLA?

**Comment by linsun** [comment]
@zacharysarah thanks much - I'm working on that with @bradtopol.

**Comment by bradtopol** [comment]
@linsun please check your inbox for an invitation related to the cla

**Comment by bradtopol** [comment]
Hi @linsun Your email is in the CNCF list but the check is still failing. So the next thing to check is to make sure the email address in the commit header matches the email we put in the cncf list. You can check this by doing a git log to see what email is in the Author field of the commit and you can change the email by doing a 
git commit -s --amend
 and changing the email to be your ibm email address.

Thanks

**Comment by linsun** [comment]
Hi @bradtopol thank you for the help!  I followed the instruction:

```
website $ git log             

commit 669afcb2acda9882629e2bf1592b0d625e503e60 (HEAD -> patch-1, origin/patch-1)
Author: Lin Sun <linsun@us.ibm.com>
Date:   Fri Apr 3 17:06:36 2020 -0400

    add IBM cloud instruction
```

let me know if you have other things to check.

**Comment by linsun** [comment]
just tried to manually amend my email per @bradtopol 's suggestion

```
website $ git commit -s --amend --author="Lin Sun <linsun@us.ibm.com>"
[patch-1 24bd13bd5] add IBM cloud instruction
 Date: Fri Apr 3 17:06:36 2020 -0400
 1 file changed, 10 insertions(+)
(⎈ |linistio14/boft3r6w0p5blanmm18g:default) git:(patch-1)  
website $ git push -f  
```

**Comment by duglin** [comment]
@bradtopol I had to add her as a "contributing employee" in the CNCF CLA stuff. That seems to have fixed it.

**Comment by bradtopol** [comment]
> @bradtopol I had to add her as a "contributing employee" in the CNCF CLA stuff. That seems to have fixed it.

Thanks @duglin! Much appreciated!!! I had never seen that happen before. I will be on the lookout for that from now on!!!

**Comment by bradtopol** [comment]
Great job @linsun!!! Your first contribution looks perfect!  Thanks for contributing to Kube Documentation!
/lgtm
/approve

**Pull request merged**
