### PR TITLE
localization for subscribe button

### PR DESCRIPTION
**Pull request by Arhell**
issue #21407
en [PR ](https://github.com/kubernetes/website/pull/20878)

/language ja

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-21420--kubernetes-io-master-staging.netlify.app/ja/#kubeweekly

**Comment by sftim** [comment]
/unassign

I'm not a reviewer for Japanese

**Comment by Arhell** [comment]
@sftim Hi, need an approve with rights to merge
[comment](https://github.com/kubernetes/website/pull/21420#issuecomment-637490445)

**Comment by sftim** [comment]
@Arhell this is not ready for approval - it is waiting for a /lgtm

**Comment by Arhell** [comment]
/assign @sftim 
Hi, [approve](https://github.com/kubernetes/website/pull/21420#issuecomment-637490445)
[lgtm](https://github.com/kubernetes/website/pull/21420#pullrequestreview-423153934)

**Pull request merged**
