### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by 1ttric**
* Removes an extraneous `"` character
* Corrects a minor grammar issue
* Splits a sentence to improve flow

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@1ttric Welcome and thank you for your contribution!

BTW, Netlify build failed with no specific reason.
> Build exceeded maximum allowed runtime
- https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/62dc258689cc2f00081f7379#L78
- (Not Found) https://deploy-preview-35296--kubernetes-io-main-staging.netlify.app

I think that if you (force-)push again, then a new Netlify build will be triggered.

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @1ttric , thank you for your contribution! A couple of things that I feel need to be mentioned. 

1. I understand you found this minor typo and raised a PR to fix the issue. However, PR reviewing is massive effort & per our trivial change policy we'd request that you scan the entire page for any such issues/typos and consider submitting the PR.
2. As suggested by a reviewer above, please consider resubmitting after signing the CLA so that the build is triggered again.

**Comment by 1ttric** [comment]
> Hello @1ttric , thank you for your contribution! A couple of things that I feel need to be mentioned.
> 
>     1. I understand you found this minor typo and raised a PR to fix the issue. However, PR reviewing is massive effort & per our trivial change policy we'd request that you scan the entire page for any such issues/typos and consider submitting the PR.
>     2. As suggested by a reviewer above, please consider resubmitting after signing the CLA so that the build is triggered again.

Sure - I've corrected an additional couple small items for this page.

Looks like checks are green as well.

**Pull request merged**
