### PR TITLE
[zh]sync removed file for content/en/docs/reference

### LINKED ISSUE #25247: [zh] reference section out of sync for 1.19
**Problem:**

docs under `content/zh/reference` section are out of sync from English site.
See the following report:

```
$ ./scripts/lsync.sh content/zh/docs/reference/
22	39	content/en/docs/reference/kubernetes-api/labels-annotations-taints.md
1	4	content/en/docs/reference/scheduling/config.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_list.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_etcd.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_all.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
10	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
3	3	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-healthcheck-client.md
0	7	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_scheduler.md
0	7	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-kubelet-client.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_control-plane.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-peer.md
0	7	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_control-plane.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
0	7	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md
2	9	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_etcd_local.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-client.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-server.md
17	0	content/en/docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
0	2	content/en/docs/reference/setup-tools/kubeadm/kubeadm-version.md
6	4	content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
0	2	content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
11	0	content/en/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
0	4	content/en/docs/reference/setup-tools/kubeadm/kubeadm-token.md
1	0	content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase.md
41	35	content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
11	5	content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
0	3	content/en/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
0	1	content/en/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
36	33	content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
108	23	content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
10	9	content/en/docs/reference/command-line-tools-reference/kube-proxy.md
3	2	content/en/docs/reference/command-line-tools-reference/feature-gates.md
385	283	content/en/docs/reference/command-line-tools-reference/kubelet.md
33	25	content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
21	62	content/en/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
2	2	content/en/docs/reference/glossary/platform-developer.md
3	4	content/en/docs/reference/glossary/customresourcedefinition.md
1	1	content/en/docs/reference/glossary/admission-controller.md
11	3	content/en/docs/reference/glossary/cluster-operations.md
1	1	content/en/docs/reference/glossary/configmap.md
1	1	content/en/docs/reference/glossary/preemption.md
1	1	content/en/docs/reference/glossary/container.md
1	1	content/en/docs/reference/glossary/cri-o.md
1	1	content/en/docs/reference/glossary/pod-priority.md
1	1	content/en/docs/reference/glossary/toleration.md
12	0	content/en/docs/reference/glossary/control-plane.md
1	1	content/en/docs/reference/glossary/quantity.md
3	3	content/en/docs/reference/glossary/node.md
11	5	content/en/docs/reference/glossary/replication-controller.md
1	1	content/en/docs/reference/glossary/kubeadm.md
3	4	content/en/docs/reference/glossary/kubelet.md
2	2	content/en/docs/reference/glossary/cluster-infrastructure.md
**removed**	content/en/docs/reference//glossary/rkt.md
3	3	content/en/docs/reference/glossary/taint.md
2	2	content/en/docs/reference/issues-security/security.md
1	1	content/en/docs/reference/kubectl/overview.md
12	0	content/en/docs/reference/kubectl/jsonpath.md
7	0	content/en/docs/reference/kubectl/cheatsheet.md
2	2	content/en/docs/reference/_index.md
27	1	content/en/docs/reference/access-authn-authz/authentication.md
3	3	content/en/docs/reference/access-authn-authz/bootstrap-tokens.md
3	3	content/en/docs/reference/access-authn-authz/authorization.md
72	60	content/en/docs/reference/access-authn-authz/service-accounts-admin.md
**removed**	content/en/docs/reference//access-authn-authz/controlling-access.md
4	4	content/en/docs/reference/access-authn-authz/admission-controllers.md
26	26	content/en/docs/reference/access-authn-authz/rbac.md
111	71	content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
24	2	content/en/docs/reference/access-authn-authz/_index.md
2	2	content/en/docs/reference/tools.md
**removed**	content/en/docs/reference//using-api/api-overview.md
8	438	content/en/docs/reference/using-api/api-concepts.md
4	4	content/en/docs/reference/using-api/deprecation-policy.md
7	4	content/en/docs/reference/using-api/client-libraries.md
1	1	content/en/docs/reference/using-api/server-side-apply.md
12	12	content/en/docs/reference/using-api/health-checks.md
123	2	content/en/docs/reference/using-api/_index.md
```

**Proposed Solution:**

Sync changes from English site.

**Page to Update:**

As listed above.

/help
/language zh

### PR DESCRIPTION
**Pull request by zhaojizhuang**
Related #25247  [zh]sync removed file for `content/en/docs/reference`

### CODE REVIEW

**Comment by tengqm** [comment]
Please change the "Fix #25247" text in your commit message into "Related #25247".
This PR is not a complete fix 25247. Putting "Fix #25247" there will get the issue auto-closed.

**Comment by zhaojizhuang** [comment]
> Please change the "Fix #25247" text in your commit message into "Related #25247".
> This PR is not a complete fix 25247. Putting "Fix #25247" there will get the issue auto-closed.

ok

**Pull request merged**
