### PR TITLE
Italiano: Reword Kubernetes case studies title

### PR DESCRIPTION
**Pull request by sftim**
Reword ~disabled~ draft page https://kubernetes.io/it/case-studies/

I think this wording is right but I'm not sure, I don't speak Italian well. Seems like it's worth having a go to help out.

/kind cleanup

### CODE REVIEW

**Comment by sftim** [comment]
@mattiaperi / @micheleberardi is this wording OK?

**Comment by sftim** [comment]
/retitle Italiano: Reword Kubernetes case studies title

**Comment by mattiaperi** [comment]
Hi @sftim, I confirm Italian translation for "case studies" is "casi di studio".

**Comment by sftim** [comment]
Cool!
Feel free to /lgtm (& possible /approve) if you're happy with these changes.

**Pull request merged**
