### PR TITLE
[en] Update operator.md

### PR DESCRIPTION
**Pull request by ptux**
- fix subject

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
I think we could merge your suggestion into the original statement instead of deleting it altogether.

Possible rephrase could include,

Kubernetes' {{< glossary_tooltip text="operator-pattern" term_id="operator pattern >}} concept lets you extend the cluster's behaviour without modifying the code of Kubernetes itself by linking {{< glossary_tooltip text="controllers" term_id="controller" >}} to one or more custom resources.

WDYT?

**Comment by ptux** [comment]
@divya-mohan0209 

I'll take your advice cause it's more readable.
Thanks.

**Comment by divya-mohan0209** [comment]
Please could you squash & merge the changes into one commit? I'll add an LGTM and have another sig docs reviewer approve it then

**Comment by ptux** [comment]
@divya-mohan0209 

Done!

**Pull request merged**
