### PR TITLE
Doc update for promotion of GMSA feature to Stable

### PR DESCRIPTION
**Pull request by JeremyWx**
Doc update for promotion of GMSA feature to Stable

Original PR opened by @ddebroy https://github.com/kubernetes/website/pull/19349

### CODE REVIEW

**Comment by sftim** [comment]
@VineethReddy02 this looks like it should be tracked for /milestone 1.18

**Comment by VineethReddy02** [comment]
Hi @JeremyWx 
Is this PR duplicate of #19349 ? If so, can you please close the duplicate PR?
As tomorrow is the deadline for docs placeholder PR's to be ready to merge state. It helps me to track the docs with ease.

**Comment by ddebroy** [comment]
Lets go with https://github.com/kubernetes/website/pull/19349 - the original PR. I have updated the branch with the desired changes with a clean commit history.

**Comment by VineethReddy02** [comment]
@ddebroy can you close this? As this already tracked by #19349

**Comment by JeremyWx** [comment]
I will close it.

**Pull request closed without merging**
