### PR TITLE
Added error handling to find_pr script

### PR DESCRIPTION
**Pull request by rlenferink**
Updated the `find_pr.py` script to have error handling in place. I wanted to use the script and first had to detect what was going wrong because of a python backtrace filling my terminal. This will improve and (hopefully ;) ) return a better error message.

/assign @remyleone 
/cc @zacharysarah

### CODE REVIEW

**Comment by rlenferink** [comment]
/assign @bradtopol 
as PR wrangler for this week

**Comment by rlenferink** [comment]
/assign @zacharysarah 
for approval

**Comment by zacharysarah** [comment]
@rlenferink Nice! ✨ 

/approve

**Pull request merged**
