### PR TITLE
Fix command issues of apply-resource-quota-limit

### PR DESCRIPTION
**Pull request by mooncak**
Signed-off-by: mooncake <xcoder@tenxcloud.com>

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
> Help editing and submitting pull requests:  https://deploy-preview-9510--kubernetes-io-master-staging.netlify.com/docs/contribute/start/#submit-a-pull-request.
> Help choosing which branch to use, see
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

Fix command issues of apply-resource-quota-limit:
remove the duplicated word "limits"

### CODE REVIEW

**Comment by stewart-yu** [comment]
IMO, this is wrong fix
`kubectl describe limits <limits-name> -n <namespaces-name>`
In our case, the name of  limits is `limits`.
WDYT? @mooncak

**Comment by mooncak** [comment]
@stewart-yu  Shall I revert the changes?  and change to "kubectl describe limits <limits-name> -n <namespaces-name>" so it's more clearly?

**Comment by tengqm** [comment]
@stewart-yu Thanks for the catch. PR reverted.

**Pull request merged**
