### PR TITLE
Updated config.toml as part of release-1.18

### PR DESCRIPTION
**Pull request by VineethReddy02**
Updated config.toml

### CODE REVIEW

**Comment by sftim** [comment]
Helps with issue #19841

**Comment by jimangel** [comment]
Same as the other issue, I do not see 1.18 in the dropdown.

https://deploy-preview-19843--k8s-v1-14.netlify.com/

**Comment by sftim** [comment]
Should have checked more. Following https://github.com/kubernetes/website/pull/19843#issuecomment-604095157
/lgtm cancel

**Comment by kbhawkey** [comment]
Preview looks okay, https://deploy-preview-19843--k8s-v1-14.netlify.com/
The "maintenance" banner text is formatted nicely in the 1.14 version compared to >= 1.16.
/lgtm

**Pull request merged**
