### PR TITLE
Update outdated files in dev-1.19-ko.5 part-02

### PR DESCRIPTION
**Pull request by pjhwa**
This PR is the part of #24860 issue.

This PR contains the following updated files:
- [x] content/en/docs/concepts/storage/volumes.md 1 file changed, 443 insertions(+), 475 deletions(-)
- [x] content/en/docs/setup/production-environment/container-runtimes.md 1 file changed, 227 insertions(+), 214 deletions(-)
- [x] content/en/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md 1 file changed, 145 insertions(+), 86 deletions(-)

/language ko

### CODE REVIEW

**Comment by pjhwa** [comment]
Preview page:
- https://deploy-preview-25152--k8s-dev-ko.netlify.app/ko/docs/concepts/storage/volumes/
- https://deploy-preview-25152--k8s-dev-ko.netlify.app/ko/docs/setup/production-environment/container-runtimes/
- https://deploy-preview-25152--k8s-dev-ko.netlify.app/ko/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/

**Comment by seokho-son** [comment]
/assign @gochist 
리뷰 부탁 드립니다.. :)

**Comment by gochist** [comment]
/lgtm
/unassign
@seokho-son  제가 저자와 소속 회사가 같으므로 다른 분이 승인해주시면 좋겠습니다.

**Comment by seokho-son** [comment]
감사합니다!
/approve

**Pull request merged**
