### PR TITLE
zh-trans: Add manage-resources/cpu-default-namespace.md

### PR DESCRIPTION
**Pull request by AdamDang**
Add manage-resources/cpu-default-namespace.md

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
could you squash these commits and call me back to merge?

**Comment by AdamDang** [comment]
@zhangxiaoyu-zidif 
squash done, Thanks!

**Comment by AdamDang** [comment]
@tengqm @markthink @zhangxiaoyu-zidif 
I've added the Yaml files used in this doc, that's the root cause for failure.
Please lgtm again.

**Pull request merged**
