### PR TITLE
Adding v1.19.0 release notes

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Adding v1.19.0 release notes

cc: @zacharysarah @jimangel @sftim @kbhawkey @annajung

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
This looks important!
/approve

**Comment by savitharaghunathan** [comment]
My apologies for the delayed merge.

**Comment by savitharaghunathan** [comment]
Preview: https://5f483616c547580007c43eee--kubernetes-io-master-staging.netlify.app/docs/setup/release/notes/

**Comment by sftim** [comment]
Preview looks good to me

**Pull request merged**
