### PR TITLE
[ja]Update "Installing kubeadm" page references apt repositories

### PR DESCRIPTION
**Pull request by aoki-taquan**
issue : #44495 

I've just submitted my first Pull Request. If anything seems off or if I missed any steps, I'd appreciate your guidance. Excited to be part of the project!

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @nasa9084

**Comment by nasa9084** [comment]
it looks really great, but maybe updating step 2 (and the description for step 2 and 3, if possible) as well would help users a lot as it is related to the updated step 3, can you update?

**Comment by aoki-taquan** [comment]
Okay!
I will update step 2 and the description for step 2 and 3.

**Comment by aoki-taquan** [comment]
I finish update step 2 and the description for step 2 and 3.

**Comment by nasa9084** [comment]
/approve

for other reviewers, the step 1 has been updated by https://github.com/kubernetes/website/pull/44181

**Comment by aoki-taquan** [comment]
I'm not well-versed in Git operations, and things have ended up in a strange state. What should I do?

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de en es fr hi id it ko pl pt ru uk vi zh
/remove-sig release

**Comment by t-inu** [comment]
Don't worry about it.
I suggest closing this PR and creating a new one.

**Comment by aoki-taquan** [comment]
> Don't worry about it. I suggest closing this PR and creating a new one.

Thank you. I try it.

**Pull request closed without merging**
