### PR TITLE
Updating broken links

### PR DESCRIPTION
**Pull request by SaranBalaji90**
Updating broken links for content/id/docs/concepts/cluster-administration/networking.md and content/id/docs/concepts/cluster-administration/addons.md

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@SaranBalaji90 Thanks for your contribution. It seems this PR modifies files in different languages ([Indonesian](https://github.com/kubernetes/website/blob/a9c45e9618c9c48456664a326228ed75f3f0b242/content/id/docs/concepts/cluster-administration/networking.md) and [Japanese](https://github.com/kubernetes/website/blob/a9c45e9618c9c48456664a326228ed75f3f0b242/content/ja/docs/concepts/storage/storage-limits.md)). However, the documentation process differs for each localization, and we usually don't accept PRs that affect multiple languages at once. I suggest only changing content for one language and submitting a separate PR for each language.  I hope this suggestion is helpful.

**Comment by dipesh-rawat** [comment]
/hold
Hold till the PR addresses changes only related to a single language.
_(OK to unhold once that's corrected)_

**Comment by SaranBalaji90** [comment]
@dipesh-rawat Thank you for taking a look and guiding me with the process. I will update the PR accordingly.

**Comment by dipesh-rawat** [comment]
/unhold
PR now targets single language

**Review by habibrosyad — APPROVED** [review]
Thanks!

/lgtm

**Pull request merged**
