### PR TITLE
[bn] merging main in to dev-1.24-bn.1 

### PR DESCRIPTION
**Pull request by asem-hamid**
Merging main in to dev-1.24-bn.1  to update dev-1.24-bn.1 branch

Fixes Issue : https://github.com/kubernetes/website/issues/44993

Tracking Issue: https://github.com/kubernetes/website/issues/31677

/cc @sftim 
/cc @seokho-son 
/cc @a-mccarthy 
/cc @dipesh-rawat 
/cc @divya-mohan0209

### CODE REVIEW

**Comment by seokho-son** [comment]
/lgtm

Considering this PR is to update [dev-1.24-bn.1](https://github.com/kubernetes/website/tree/dev-1.24-bn.1) branch to make it up to date (from upstream/main) and there is no merge conflict. This PR will help reducing merge conflict when we try to merge dev-1.24-bn.1 into main branch for the first live version of Bengali localization. :)

Note that I am not sure any possible build errors exist in the dev-1.24-bn.1 (Netlify build test is for main branch), if there is, we need to fix it in the dev branch.

**Comment by sftim** [comment]
> Note that I am not sure any possible build errors exist in the dev-1.24-bn.1 (Netlify build test is for main branch), if there is, we need to fix it in the dev branch.

For any PR, you can always pull it locally and run a test to confirm that it builds OK.

**Comment by asem-hamid** [comment]
@seokho-son Actually, yes, we have build errors, but most of them are glossary-related. We are already [working](https://github.com/kubernetes/website/issues/45729) on that.

**Review by divya-mohan0209 — COMMENTED** [review]
My two cents on this issue.

This is a very large change, and I haven't seen a precedent for it earlier on despite also being a maintainer for the Hindi localisation. I understand that we're very close to the minimum requirement, and it'd help if we approved this change, but I'm also wary of such changes being forced through for a localisation because certain files are missing.

I'd rather have the second approach listed on [this PR](https://github.com/kubernetes/website/pull/46210#issuecomment-2096943984) by 
@sftim followed and would not recommend the approach of merging main into the dev branch like we do for branch syncs during a release.
 
@natalisucks @reylejano : I would like your thoughts on this, as well.

**Comment by reylejano** [comment]
Technically the dev-1.24-bn.1 branch was created from what was the 1.24 docs. The main branch is currently for the 1.30 docs. I don't think we should merge main into dev-1.24-bn.1.

**Comment by asem-hamid** [comment]
@divya-mohan0209 
@reylejano
@sftim 

  Thanks for suggestion , we are going with option 2 from this https://github.com/kubernetes/website/pull/46210#issuecomment-2096943984 now

**Comment by divya-mohan0209** [comment]
@asem-hamid Can we close this PR, please, if we're following option #2?

**Comment by asem-hamid** [comment]
ok

**Pull request closed without merging**
