### PR TITLE
Update API reference for v1beta4

### PR DESCRIPTION
**Pull request by Vincent-zzb**
Adapt to v1beta4 format.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@Vincent-zzb Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: https://git.k8s.io/community/CLA.md

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

_To re-trigger the EasyCLA bot check_

**Review by Arhell — COMMENTED** [review]
/easycla

**Review by dipesh-rawat — COMMENTED** [review]
It looks like the necessary updates have already been addressed and are live ([see here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/)) as part of https://github.com/kubernetes/website/commit/19fd1be30228a183604c0beee21c1145a8fdb2b2. Appreciate your effort on this, but since the issue has been resolved, I’ll go ahead and close this PR. Thanks again!

/close

**Pull request closed without merging**
