### PR TITLE
fix italics syntax

### PR DESCRIPTION
**Pull request by dixudx**
Currently the italics is not well rendered.

Please check https://kubernetes.io/cn/docs/tasks/administer-cluster/static-pod/ for reference.

### CODE REVIEW

**Comment by dixudx** [comment]
After this fix,

https://deploy-preview-9083--kubernetes-io-master-staging.netlify.com/cn/docs/tasks/administer-cluster/static-pod/

**Comment by tengqm** [comment]
If I'm understanding this correctly, the fix is to be proposed to the CN translation repo and get reviewed there. People will periodically sync the translated version back to the main repo.

**Comment by dixudx** [comment]
> If I'm understanding this correctly, the fix is to be proposed to the CN translation repo and get reviewed there. People will periodically sync the translated version back to the main repo.

@tengqm Seems not. They are not synced.

https://raw.githubusercontent.com/kubernetes/kubernetes-docs-zh/master/docs/tasks/administer-cluster/static-pod.md

**Comment by tengqm** [comment]
@zacharysarah Please advise how are we supposed to do with these kind of PRs. I'm okay with merging it if it has been fixed in the translation repo. However, doing this kind of manual checking is not fun. Can we do this in batches by following some protocols? using bots?

**Comment by zacharysarah** [comment]
@tengqm Fixes to translated content should definitely go through the translation repo. In this particular case, the repo may not have been synced because they're holding off for the Hugo migration and subsequently for 1.11.

@dixudx If the fix has been made upstream, I'll go ahead and close this PR.

**Pull request closed without merging**
