### PR TITLE
Text select fix before tags

### PR DESCRIPTION
**Pull request by Arhell**
#19591

### CODE REVIEW

**Comment by sftim** [comment]
@arhell, can you explain why this is the right fix? The PR description isn't clear.

**Comment by Arhell** [comment]
I wrote a solution to the issue, chose it because it does not break performance.
In other words, if I remove the bug in general, then the anchors will not work very well.
before fix 
after fix 


Second

The hover will not work and the anchors will not be visible


and the third is what I did, the functional works but there are moments where there isn't
Exemple:
https://deploy-preview-19605--kubernetes-io-master-staging.netlify.com/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/#kubernetes-clusters

h1 tag not select "Using Minikube to Create a Cluster"

**Comment by sftim** [comment]
Would you be willing to update the PR description to summarize the changes and explain why these are the right fix?
It looks like a reviewer (eg me) could work this out but right now that will involve some detective work. I am afraid that I did not fully follow the explanation you wrote so far @Arhell.

**Comment by Arhell** [comment]
@sftim 
As for me this is the best option, but there are other solutions, for example here
https://docs.zephir-lang.com/0.12/en/welcome
a similar situation, only I don't know if it will suit you.
If there are more options, I will be glad to consider them.

**Comment by sftim** [comment]
@Arhell in terms of the choice of a fix, I don't mind which fix you adopt so long as it works.

Here's what I _don't_ want to happen:
- I approve this change
- Prow & Tide merge the PR
- that merge introduces a regression
- the website experience for readers is impaired

So, to help the person who reviews this PR, what can you say to give them confidence that this change is safe to make? A good fix addresses a defect without side effects.

The existing commit message: “Text select fix before tags” provides only a little detail. I have to guess at what effect the change has; your intent (fix a bug) is clear, but the means to achieve that intent I do not yet know.

**Comment by Arhell** [comment]
Hi @sftim 
Thank you, I'm sure of a fix.
But I would like for someone else to look, because there may be other ideas to fix this bug.

**Comment by jimangel** [comment]
@Arhell would you mind updating the description with clear details on what was changed / why. It might just be me, but I struggle to see what this fixes.

When testing anchor links with your PR against the main website - they both behave the same way.

**Comment by Arhell** [comment]
Hi, I will close this PR, it fixes the problem but others arise. So we are waiting for a new topic.
/close

**Pull request closed without merging**
