### PR TITLE
[ko] Clean up various broken links

### PR DESCRIPTION
**Pull request by tallclair**
Clean up broken links reported through the HackerOne bug bounty program.

Localized version of #32783

/committee security-response

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @tallclair 
Thank you for the contribution.

I have a question regarding `Contiv`.

https://github.com/kubernetes/website/pull/32917/files#diff-1e3d7eea6e6ef57fce9ac297762d24e73c02b1e441fa4b0fe6ad662831ea43a0R24
 > ```* [Contiv](https://contivpp.io/)는 다양한 유스케이스와 풍부한 폴리시 프레임워크를 위해 구성 가능한 네트워킹(BGP를 사용하는 네이티브 L3, vxlan을 사용하는 오버레이, 클래식 L2 그리고 Cisco-SDN/ACI)을 제공한다. Contiv 프로젝트는 완전히 [오픈소스](https://github.com/contiv)이다. [인스톨러](https://github.com/contiv/install)는 kubeadm을 이용하거나, 그렇지 않은 경우에 대해서도 설치 옵션을 모두 제공한다.```

This change is not aligned with English document (the HEAD of `main` branch). 
There is no description for `Contiv` in 
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/cluster-administration/addons.md

I checked PR history regarding `en/docs/concepts/cluster-administration/addons.md`.
---

The line for `Contiv` in English document has been removed by your PR (#31760).
Also the line for `Contiv` in Korean document has been removed by  PR (#32782), but this PR restore the line for `Contiv` in Korean document. 

@tallclair Could you check #31760 includes a mistake (removing the line instead of changing URL). 
If it is a mistake, please update English document first. 
(PTAL @reylejano . if we need to take care anything regarding this issue)

**Comment by tallclair** [comment]
@seokho-son thanks for flagging that. I added it back in https://github.com/kubernetes/website/pull/32938

**Comment by seokho-son** [comment]
Thanks! :)

/lgtm
/approve

**Pull request merged**
