### PR TITLE
Fix dashboard link

### PR DESCRIPTION
**Pull request by campionfellin**
This fixes https://github.com/kubernetes/website/issues/7930

### CODE REVIEW

**Comment by campionfellin** [comment]
Upon reading this issue https://github.com/kubernetes/website/issues/7904 and this discussion https://github.com/kubernetes/website/pull/7890 about developing a long term solution for this. Maybe it's better to hold off on these quick fixes? I'd be interested in helping develop the long term solution if there is someone who can help guide me on what we want to do.

**Comment by zacharysarah** [comment]
@campionfellin Any long-term fix we adopt would likely produce a PR with exactly these kinds of changes. I think we can proceed with the ones you've opened (though this one could use a tech review first). 

If you're interested in larger-scale fixes, we've got an agenda item to discuss link validation and CI/CD improvements in the SIG Docs weekly meeting (Tuesday, 3 April, 10:30am Pacific).

**Comment by campionfellin** [comment]
Hey @zacharysarah I'm definitely interested in helping with more large-scale fixes, though I cannot make it to the meeting tomorrow. Is there any way I can get notes or a recording? If not, that's fine, please let me know what I can do to help!

**Comment by zacharysarah** [comment]
@campionfellin There will be a recording available, the URL is in the `#sig-docs` channel on https://kubernetes.slack.com.

**Comment by heckj** [comment]
:wave:  @bryk, @mikedanese, @rf232 - would you mind taking a look at this change and letting us know if it is technically accurate?

/assign

**Comment by heckj** [comment]
/assign @bryk @mikedanese @rf232 

👋 I was hoping one of you might have a moment to review this PR to validate it's accuracy for the docs.

**Pull request merged**
