### PR TITLE
Update code render and format auto-generate list

### PR DESCRIPTION
**Pull request by angao**

### CODE REVIEW

**Comment by angao** [comment]
- [Deploy Preview](https://deploy-preview-9070--kubernetes-io-master-staging.netlify.com/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-secret)

- [Official Website](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-secret)

**Comment by tengqm** [comment]
@angao Pls resolve the conflicts and review comments.

**Pull request merged**
