### PR TITLE
Added "OR sun,mon,tue,wed,thu,fri,sat" to CronJob

### PR DESCRIPTION
**Pull request by guettli**
Added "OR sun,mon,tue,wed,thu,fri,sat" to CronJob documentation.

Using a string for the day of the week reduces cognitive load.

### CODE REVIEW

**Comment by sftim** [comment]
@kubernetes/sig-apps-pr-reviews do we officially support this way of indicating a day-of-week?

**Comment by reylejano** [comment]
I confirmed this works with CronJobs in 1.23
/lgtm

**Pull request merged**
