### PR TITLE
Adding Niranjan Darshan to Hindi reviewers

### PR DESCRIPTION
**Pull request by divya-mohan0209**
Adding @niranjandarshann to Hindi reviewers

cc: @dipesh-rawat for approval.

@niranjandarshann : Once this PR is merged, you'll need to add yourself to [this file](https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml) and seek approval from Dipesh and me.

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Awaiting confirmation from @niranjandarshann as to whether he is an org member, since he seems to have said the following on chat:

"At org level yes i have member role in k8s."

**Comment by niranjandarshann** [comment]
> Awaiting confirmation from @niranjandarshann as to whether he is an org member, since he seems to have said the following on chat:
> 
> "At org level yes i have member role in k8s."

@divya-mohan0209 yes I have member role in k8s org. the username entered is wrong . correct one is **niranjandarshann**

**Comment by divya-mohan0209** [comment]
Added the correct name, thanks Niranjan!
/unhold

**Review by dipesh-rawat — COMMENTED** [review]
Looks good. 
Welcome to the Hindi l10n team.

/lgtm
`/approve` _(Unofficially giving the nod of approval; official PR approval can only be applied by `sig-docs-website-owner` for changes in OWNERS file.)_

**Pull request merged**
