### PR TITLE
certificates: update required credential name for kubelet.conf

### LINKED ISSUE #44876: Incorrect credential name set for kubelet.conf in External CA mode
**This is a Bug Report**

**Problem:**

Invalid user set for kubelet.conf in external CA mode at https://kubernetes.io/docs/setup/best-practices/certificates/#configure-certificates-for-user-accounts

incorrect:
* default-auth

correct:
* `system:node:<nodeName>`

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/setup/best-practices/certificates/#configure-certificates-for-user-accounts

### PR DESCRIPTION
**Pull request by vrutkovs**
This name must match Common Name to be accepted by kubelet

Fixes #44876

### CODE REVIEW

**Comment by T-Lakshmi** [comment]
@vrutkovs  
Thanks for raising PR. As per k8s community guidelince, we do not accept PR with multiple languages. 
I would recommend modify only the primary website content (English) initially with this PR. After the merge of the English content, we could create separate pull request for the remaining language(s). I hope this suggestion is helpful.

**Comment by T-Lakshmi** [comment]
/hold
Hold until PR only covers single language(Feel free to unhold once remove other languages content).

**Comment by T-Lakshmi** [comment]
@vrutkovs,
 below are some links that may help you to find k8s community contributor guidelines.
https://www.kubernetes.dev/docs/guide/#contributor-guide
https://kubernetes.io/docs/contribute/
https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md

**Comment by vrutkovs** [comment]
Oh, thanks. Updated the PR (keeping the hold just in case)

**Comment by dipesh-rawat** [comment]
Okay to unhold now as PR covers single language.

/unhold

**Comment by stlaz** [comment]
/close
We discovered out-of-band that this used to be a kubelet legacy behavior (~1.18). Arbitrary usernames can now be used.

**Pull request closed without merging**
