### PR TITLE
[ja] Update CronJob example yaml apiversion: batch/v1beta1 --> batch/v1

### PR DESCRIPTION
**Pull request by mengjiao-liu**
```
batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```
[ja] Update CronJob example yaml apiversion: batch/v1beta1 --> batch/v1

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm
Nice catch.
Thank you to create this :smile:

**Comment by mengjiao-liu** [comment]
/assign @nasa9084
for approval

**Comment by mengjiao-liu** [comment]
/cc @sig-docs-ja-owners 
for approval

**Comment by bells17** [comment]
/assign @inductor 
for approval

**Comment by mengjiao-liu** [comment]
Any chance you'll find time to review it so we can merge it?
This PR has been long delayed. @inductor @nasa9084

**Comment by bells17** [comment]
@mengjiao-liu Sorry for delaying approval.
I'm contacting to @inductor @nasa9084 directly.
I'd like for you to wait a little longer.

**Comment by mengjiao-liu** [comment]
Thx！@bells17

**Pull request merged**
