### PR TITLE
Fix sentence structure

### PR DESCRIPTION
**Pull request by AghaSaad04**
Signed-off-by: Agha Saad Fraz <agha.saad04@gmail.com>

## Description:
I was reading the documentation of Kubernetes and found an error in a sentence. I have suggested the fix by fixing the sentence structure

### CODE REVIEW

**Comment by zacharysarah** [comment]
@AghaSaad04 👋 Please verify that the email you used to sign the CLA is the same one attached to your GitHub ID.

**Comment by AghaSaad04** [comment]
> @AghaSaad04 👋 Please verify that the email you used to sign the CLA is the same one attached to your GitHub ID.

Hi @zacharysarah I just signed the CLA with the same email that is attached with my Github.

**Comment by zacharysarah** [comment]
@AghaSaad04 Does your CLA email match the email attached to this commit?

**Comment by sftim** [comment]
@AghaSaad04 can I offer you any help in signing that agreement, or in persuading the bot to check that?

**Comment by zparnold** [comment]
Hi @AghaSaad04 we'd love to review your PR but we haven't heard from you. So I'm going to temporarily close this PR, feel free to reopen when you're ready to continue 😄

**Pull request closed without merging**
