### PR TITLE
Merge master into dev-1.20 to keep in sync

### PR DESCRIPTION
**Pull request by SomtochiAma**
Merge master into dev-1.20 to keep in sync - SIG-Release 1.20 Docs team 10/07/20

### CODE REVIEW

**Comment by irvifa** [comment]
Hmm seems like there’s an invalid commit messages label, how we usually handle this?

**Comment by annajung** [comment]
Hi @irvifa `invalid commit message` is a known issue. It happened during out last sync as well (https://github.com/kubernetes/website/pull/24290)

There is an issue open in `test-infra` to address this (https://github.com/kubernetes/test-infra/issues/17893)

We are currently manually removing the label for now. 

In other news, looks like there is a x checkmark next to this commit in the history https://github.com/kubernetes/website/pull/24408/commits/8729c6d366b7e882f0f37115da1c3423f1ea6726 -- clicking on details, I don't see any errors, but second eyes on this will also be helpful!

**Comment by sftim** [comment]
I removed the invalid commit message label
https://github.com/kubernetes/website/pull/24408#event-3852978565

**Comment by sftim** [comment]
I don't see a problem with 8729c6d366b7e882f0f37115da1c3423f1ea6726 - I think that's down to Prow's behavior around merging without marking Prow's own test result as a pass.

**Comment by sftim** [comment]
[Preview](https://5f7dd56fa32eae0007805140--kubernetes-io-vnext-staging.netlify.app/docs/home/supported-doc-versions/) looks good to me.
/lgtm

**Comment by kbhawkey** [comment]
Thanks @SomtochiAma .
The changes look good.
Preview: https://deploy-preview-24408--kubernetes-io-vnext-staging.netlify.app/
/lgtm

**Pull request merged**
