### PR TITLE
Blog post for Poseidon-Firmament Scheduler

### PR DESCRIPTION
**Pull request by anvithks**
This is the blog post for announcing the Poseidon-Firmament Scheduler.  
CC: @deepak-vij @shivramsrivastava

### CODE REVIEW

**Comment by anvithks** [comment]
/assign @natekartchner 

This blog post is wrt the [Poseidon-Firmament Scheduler](https://kubernetes.io/docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler/), an alternate scheduler for Kubernetes.  

Ref #12069 and #12343

**Comment by kbarnard10** [comment]
Thanks @anvithks - is there a specific day you're aiming to have this published?

**Comment by deepak-vij** [comment]
> Thanks @anvithks - is there a specific day you're aiming to have this published?

Hi @kbarnard10 - there is no timeline as such. Is there a publishing cycle for blog posts? We recently completed/merged all other relevant documentation for this project as Anvith mentioned earlier. We would like to complete the blog post as well in order to close the loop on this. This blog post will help the community understand the project better. Thanks.

**Comment by anvithks** [comment]
@kbarnard10 as @deepak-vij mentioned this blog is an announcement for the Poseidon-Firmament scheduler.

If there is a schedule being followed to publish posts when is the earliest we can get this published?

**Comment by kbarnard10** [comment]
@anvithks @deepak-vij I can get this published tomorrow morning.

**Comment by deepak-vij** [comment]
> @anvithks @deepak-vij I can get this published tomorrow morning.

Perfect, thanks.

**Comment by anvithks** [comment]
@kbarnard10 that would be great.
Thank you 🙂

**Comment by deepak-vij** [comment]
> @kbarnard10 that would be great.
> Thank you

Hi @anvithks - I just noticed that we need to make minor changes to the "Key Advantages" section. Let us do that today so that it is ready by tomorrow morning @kbarnard10 time.

@anvithks , I will call you tonight to make these minor changes. Thanks.

**Comment by kbarnard10** [comment]
@anvithks @deepak-vij Let me know when you're ready for me to merge.

**Comment by anvithks** [comment]
> @anvithks @deepak-vij Let me know when you're ready for me to merge.

@kbarnard10 I just pushed the changes. You can go ahead and merge when the checks are passed and if everything else is on order.
Thank you.

**Pull request merged**
