### PR TITLE
Merge main branch into dev-1.26

### PR DESCRIPTION
**Pull request by krol3**
Merge main branch into dev-1.26 to keep in sync, part of the Docs activities in the release process.

CC 1.26 Docs Team: @cathchu  @mickeyboxell @katmutua @Rishit-dagli 
cc @reylejano

### CODE REVIEW

**Comment by sftim** [comment]
Thanks
/approve

**Comment by dims** [comment]
@krol3 let's please ping @kubernetes/steering-committee folks ( am no longer on it )

**Comment by krol3** [comment]
> @krol3 let's please ping @kubernetes/steering-committee folks ( am no longer on it )

CC [palnabarun](https://github.com/palnabarun)

**Pull request merged**
