### PR TITLE
Merge release-1.12 for sig-docs-zh team

### LINKED ISSUE #13745: Propose to merge release-1.12 into master
sig-docs-zh team has worked on release-1.12 for quite a long time, we should seriously think about merge the branch to master and work on the release-1.13 (release-1.14 was out recently).

This issue is created to address the effort of doing the merge and serve as place to discuss it.

/cc @zacharysarah @kubernetes/sig-docs-zh-owners 
/cc @xichengliudui @SataQiu @tengqm

### PR DESCRIPTION
**Pull request by chenrui333**
closes #13745

### CODE REVIEW

**Comment by chenrui333** [comment]
I am going to fix the PR merge issue now.

**Comment by SataQiu** [comment]
Greate job！
/lgtm

**Pull request closed without merging**
