### PR TITLE
[zh]Remove extra double quotation mark

### PR DESCRIPTION
**Pull request by luolanzone**
Remove unnecessary double quotation mark

### CODE REVIEW

**Comment by tengqm** [comment]
@luolanzone There is a minor change needed.

Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). To find out what are the upstream changes to be synced, do this **on the main branch**:

```shell
./scripts/lsync.sh content/zh/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
```

/hold

**Comment by luolanzone** [comment]
Hi @tengqm  thanks for reviewing this PR, I tried and got below info, I suppose it means it's already synced?
```
content/zh/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md is still in sync
```

**Comment by tengqm** [comment]
> Hi @tengqm thanks for reviewing this PR, I tried and got below info, I suppose it means it's already synced?
> 
> ```
> content/zh/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md is still in sync
> ```

你必须在 main 分支下运行这个命令，否则你要检查的文件可能已经被污染。

**Comment by luolanzone** [comment]
@tengqm yes, I was trying it in main branch, and I double checked it, my local copy is latest: 

```
commit 9b9ac3a458a118dacef1e0e1d924684a3513256c (HEAD -> main, origin/master, origin/main, origin/HEAD, master)
Merge: c0eef74a2 fb58df71c
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Tue Mar 29 22:34:27 2022 -0700

    Merge pull request #32609 from my-git9/pod-configmap-env-var-valueFrom

    [zh]Pod configmap env var value from
```
and the result is the same as below, let me know if I missed anything. thanks!
```
✘ luolan  luolanzone/website   main  ./scripts/lsync.sh content/zh/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
content/zh/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md is still in sync
```

**Comment by tengqm** [comment]
Okay. The Chinese page has been updated on Mar 27. So the page is now in sync.
/lgtm
/approve

**Pull request merged**
