### PR TITLE
Fix the nodename typo of the untaint command in zh-cn-doc-taint

### PR DESCRIPTION
**Pull request by BIAOXYZ**
修正删除taint命令中关于节点名称的一处笔误(kube11 --> node1)。

### CODE REVIEW

**Comment by BIAOXYZ** [comment]
Pleae ignore `PR15303`(https://github.com/kubernetes/website/pull/15303) in which I did not notice that the merge w.r.t zh-cn-doc should be to release-1.14 but not master.

**Comment by idealhack** [comment]
thank you, @BIAOXYZ!

**Comment by BIAOXYZ** [comment]
@idealhack Happy to help.:smile:

**Pull request merged**
