### PR TITLE
Merged master into release 1.16

### PR DESCRIPTION
**Pull request by daminisatya**

### CODE REVIEW

**Comment by daminisatya** [comment]
@jimangel @zacharysarah Kindly review and Merge.

**Comment by zacharysarah** [comment]
@daminisatya I see commits included in this merge that aren't passing CI. We may need to revert this PR if `release-1.16` doesn't build correctly.

Screen Shot 2019-11-04 at 1 07 32 PM
Screen Shot 2019-11-04 at 1 07 13 PM

**Comment by zacharysarah** [comment]
> We may need to revert this PR if release-1.16 doesn't build correctly.

It's passing, so I think we're all good. 💯

**Comment by daminisatya** [comment]
Awesome @zacharysarah

**Pull request merged**
