### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by sarat1669**

### CODE REVIEW

**Comment by Arhell** [comment]
@sarat1669  you might need to check that the email address you're using in Git matches the email address that you signed the CLA with

**Comment by sarat1669** [comment]
I just signed CNCF Individual Contributor License Agreement

**Comment by sarat1669** [comment]
@Arhell need /approved label to merge this PR

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-22087--kubernetes-io-master-staging.netlify.app/docs/concepts/containers/images/

**Comment by kbhawkey** [comment]
Thanks @sarat1669 .
/approve

**Pull request merged**
