### PR TITLE
Add weights, move files: Tasks>AdminClust>MemCPU

### PR DESCRIPTION
**Pull request by steveperry-53**
Partially addresses #8398.

Preview: https://deploy-preview-8635--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/

This is one of several PRs that I will submit to get the Tasks left nav in order.

### CODE REVIEW

**Comment by steveperry-53** [comment]
@steveperry-53 @chenopis @Bradamant3 @zacharysarah Please don't hold off on getting this and my other PRs merged. I'm working on the Tasks left nav in a sequence of PRs, each of which does a small part of the overall joj. So please move this and my other Tasks PRs forward. We can tackle the mixing of individual topics with folders at a later time.

**Comment by bradtopol** [comment]
@steveperry-53 Makes sense! Will do!
/approve
/lgtm

**Pull request merged**
