### PR TITLE
[zh-cn]Fix bold is not displayed correctly

### PR DESCRIPTION
**Pull request by javadoors**
Bold is not displayed correctly

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
This file is out of sync. Please don't do partial fix.

```
./scripts/lsync.sh content/zh-cn/docs/concepts/security/multi-tenancy.md
```

**Comment by Sea-n** [comment]
Hey @javadoors,

It's been a while since the last update, would you like to address issues in the [previous comments](https://github.com/kubernetes/website/pull/35799#issuecomment-1208870673) so that we can move forward?

**Comment by javadoors** [comment]
> Hey @javadoors,
> 
> It's been a while since the last update, would you like to address issues in the [previous comments](https://github.com/kubernetes/website/pull/35799#issuecomment-1208870673) so that we can move forward?

I think it should be able to merge now, right?

**Pull request closed without merging**
