### PR TITLE
Writing Sample

### PR DESCRIPTION
**Pull request by jonquil2002**
### Issue

Closes: #

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by dipesh-rawat** [comment]
@jonquil2002 Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

Also, reading the EasyCLA bot failure [message (here)](https://github.com/kubernetes/website/pull/48680#issuecomment-2466921191) it looks  like the commits of this PR are authored by a different github user ID (@GoddessOfTheUniverse), which might be causing the CLA check to fail.

**Comment by dipesh-rawat** [comment]
Explicit hold on this PR to prevent accidental merges until the CLA is signed.
_(Okay to unhold once the CLA is signed)_

/hold

**Comment by reylejano** [comment]
I'm closing this PR due to the CLA not signed
When you have signed the CLA, feel free to reopen this PR with "/reopen" in a comment
/close

**Pull request closed without merging**
