### PR TITLE
ja-trans: Translate content/ja/docs/tutorials/kubernetes-basics/create-cluster/_index.md in Japanese

### PR DESCRIPTION
**Pull request by hhiroshell**
ja-trans: Translate content/ja/docs/tutorials/kubernetes-basics/create-cluster/_index.md in Japanese

ref: #10821

### CODE REVIEW

**Comment by tnir** [comment]
Looks good but changes are still hard to have a look 🤔 . 
 Actual change is db52199099fd9657b8112178b9691270382609a1 only.

**Comment by mistyhacks** [comment]
@cstoku Please review this one and approve or provide feedback, or assign to another translator to review. Thanks!

**Comment by cstoku** [comment]
recreate this pr to #12059
/close

**Pull request closed without merging**
