### PR TITLE
fix small grammatical error in operator.md

### PR DESCRIPTION
**Pull request by renato1891**
fixes a small grammatical error in operator.md

"una falha..." -> "uma falha..."

### CODE REVIEW

**Review by jcjesus — APPROVED** [review]
Good job @renato1891!
Thanks

**Comment by jcjesus** [comment]
Hi @renato189!

Please, you need to make your cla/linuxfoundation registration.

Follow the steps on this URL:
[CLA Registration steps](https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-pt.md#assinando-o-cla )

**Review by yagonobre — COMMENTED** [review]
Thanks! Please sign the cla
/lgtm
/approve

**Pull request merged**
