### PR TITLE
E2E testing blog post

### PR DESCRIPTION
**Pull request by pohly**
This blog post has been shared previously with @timothysc as a Google doc who assigned it to @castrojo for publication. I believe the next step is this PR...

Regarding timing: it's mostly about enhancements in 1.13, but also some that will land in 1.14. I suppose it's fine to be published whenever it's ready.

/assign @castrojo

### CODE REVIEW

**Comment by kbarnard10** [comment]
@pohly Thanks - I'll give this a final spelling/grammar check before publication, but overall looks good to me! I have an opening on Friday (03/22) or I can hold it until after the 1.14 release next week. Do you have a preference?

**Comment by pohly** [comment]
Kaitlyn Barnard <notifications@github.com> writes:
> I have an opening on Friday (03/22) or I can hold it until after the
> 1.14 release next week. Do you have a preference?

I prefer before. Let's give everyone something to think about while
waiting for 1.14...

**Comment by pohly** [comment]
/hold

A recent discussion around https://github.com/kubernetes/kubernetes/pull/69105#pullrequestreview-216944509 showed that the recommended solution for flags has drawbacks. I'm working on a revised proposal and at least would like to get a link to that into the text.

**Comment by pohly** [comment]
/hold cancel

Ready for publishing again. I added a section about the recent work for command line parameters.

**Pull request merged**
