### PR TITLE
Merged master into dev-1.18

### PR DESCRIPTION
**Pull request by VineethReddy02**
As a part of docs release teamwork syncing up branches between master and dev-1.18
I see all the changes came up as a single commit in this PR. Is that fine?
@zacharysarah @jimangel

### CODE REVIEW

**Comment by zacharysarah** [comment]
@VineethReddy02 There should be a lot more commits. Can you share the commands you used in your local branch to create this PR?

See https://github.com/kubernetes/website/pull/19453 for what this merge PR should look like.

**Comment by zacharysarah** [comment]
Closing in favor of #19453 
/close

**Comment by VineethReddy02** [comment]
@zacharysarah 
```
$ git remote add upstream https://github.com/kubernetes/website.git
$ git fetch upstream
$ git checkout upstream/dev-[future release]
$ git merge upstream/master
$ git checkout -b merged-master-dev-[future release]
$ git commit -m "merged master into dev-[future release] to keep in sync"
## if needed: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/
## git add ...
## git commit -m "resolving conflicts"
$ git push origin merged-master-dev-[future release]
```
I used exactly this cmds. Previously when I did sync up I used to see the commit history.
When I was syncing up I noticed conflicts. I resolved them and ran ```git add .``` followed by ```git commit -sm "xx"``` and followed by raised a PR by push it to a new branch.

**Comment by zacharysarah** [comment]
@VineethReddy02 Thanks for sharing. I think the problem is more related to #19500.

**Pull request closed without merging**
