### PR TITLE
Merged main into dev 1.24

### PR DESCRIPTION
**Pull request by nate-double-u**
Week 9 update to bring `main` into `dev-1.24` branch.

### CODE REVIEW

**Comment by nate-double-u** [comment]
Error relates to the EasyCLA — Missing CLA Authorization.

/cc @JamesLaverack, FYI
/cc @jlbutler @sftim @reylejano

**Comment by sftim** [comment]
I've manually marked this as having CLA authorization with labelling, because the CLA bot we used at the time of that commit marked things as OK. That won't be enough though.

If @JamesLaverack can re-sign the CLA, great; if not, we can deal with this exception manually.

**Comment by sftim** [comment]
Provided the changes are OK, it's fine to proceed with reviews.

**Comment by nate-double-u** [comment]
Hi @jarmee, Could you please take a look at the [easy CLA message](https://github.com/kubernetes/website/pull/32118#issuecomment-1061280903) above?

> ❌ login: jarmee / name: Jari Möllenbernd (https://github.com/kubernetes/website/commit/734aa6b6735ca20a72814c0c10176c4c29765013). This user is authorized, but they must confirm their affiliation with their company. Start the authorization process[ by clicking here](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/32118/#/?version=2), click "Corporate",select the appropriate company from the list, then confirm your affiliation on the page that appears. For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

**Comment by reylejano** [comment]
easyCLA error
/approve

**Comment by jlbutler** [comment]
well apparently the CLA is still throwing weird issues (i don't think the 1.24 docs lead is missing a CLA), but it's now blocking merges. not sure how to unstick this.

@reylejano @JamesLaverack any idea?

**Comment by marosset** [comment]
From a mail to dev@kubernetes.io @nate-double-u should file a ticket at https://jira.linuxfoundation.org/servicedesk/customer/portal/4 and post in https://github.com/kubernetes/org/issues/3068

**Comment by sftim** [comment]
I merged this manually. We may well still need to look into that CLA trouble, as it will crop up again when we want to merge _dev-1.24_ into _main_.

**Pull request merged**
