### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by kancherlanagaraju**
The sentence correction

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@kancherlanagaraju Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by niranjandarshann** [comment]
@kancherlanagaraju  Thank you for your contribution.
You can find the process about how to sign the CLA.
please find https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by niranjandarshann** [comment]
closing this PR for now you can reopen it once CLA get signed.
/close

**Pull request closed without merging**
