### PR TITLE
[ja] update audit.md

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/31025/files
/assign @atoato88
/assign @inductor

### CODE REVIEW

**Comment by nasa9084** [comment]
can you apply the removing line in en PR too?

**Review by Arhell — COMMENTED** [review]
@nasa9084, done thanks

**Review by ptux — COMMENTED** [review]
/lgtm

**Review by nasa9084 — COMMENTED** [review]
/approve

**Pull request merged**
