### PR TITLE
[ja] Drop turnkey cloud solutions

### PR DESCRIPTION
**Pull request by ystkfujii**
Ref: https://github.com/kubernetes/website/pull/24768/

/kind cleanup

### CODE REVIEW

**Review by t-inu — COMMENTED** [review]
/lgtm

**Comment by t-inu** [comment]
This is just information.
In en, these contents were replaced with [Turnkey Cloud Solutions](https://kubernetes.io/docs/setup/production-environment/turnkey-solutions/) page.
That page needs to be translated.

**Comment by ystkfujii** [comment]
> This is just information. In en, these contents were replaced with [Turnkey Cloud Solutions](https://kubernetes.io/docs/setup/production-environment/turnkey-solutions/) page. That page needs to be translated.

Thanks for information.
PR https://github.com/kubernetes/website/pull/40714  created.

**Comment by ystkfujii** [comment]
/assign @nasa9084

Could you review this?

**Pull request merged**
