### PR TITLE
Bump up Deployment version

### PR DESCRIPTION
**Pull request by nashasha1**
I am creating a bunch of PRs for bumping up deployment version.  A pr contains all changes in a folder.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7344)

### CODE REVIEW

**Comment by heckj** [comment]
@nashasha1 thank you for the efforts, we do appreciate it. This topic of how to represent the changes to versions has come up previously and we don’t yet have solid guidance for our conventions in these docs other than to also specify the version that the example applies to for clarity. It’s going to be discussed (hopefully) in the SIG Docs meeting tomorrow, following on issue #7232, so I’m going to put a /hold on all of these until we have some improved instructions.

When you are doing these broad changes, it is also much easier for us to review the changes when they are all lumped together into a single PR with a single purpose (such as updating the API version tags), so doing these kinds of things as a single PR would be very much appreciated in the future

/hold

**Comment by nashasha1** [comment]
@heckj  Thank you for your reply. Sorry for confusing you guys. I thought the size is too big if I put all of these in one pr.  Next time, I will put them together and make a clear tag.  
Waiting for your good news.

**Comment by heckj** [comment]
Could you please review that recommendation and update these PRs to [include min-kubernetes-server-version in the front-matter of the various documents](https://kubernetes.io/docs/home/contribute/style-guide/#versioning-kubernetes-examples)?

**Comment by nashasha1** [comment]
@heckj  Thanks for your reply. I will close this PR and move the changes to  kubernetes/kubernetes-docs-cn.

**Pull request closed without merging**
