### PR TITLE
[ko] Update outdated files in dev-1.22-ko.3 (M19-M26)

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Related issue: #30414

> 19. [ ]  M19.  `content/en/docs/contribute/review/reviewing-prs.md`  | 32(+M) 1(-)
> 20. [ ]  M20.  `content/en/docs/reference/access-authn-authz/authorization.md`  | 15(+S) 0(-)
> 21. [ ]  M21.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 2(+XS) 6(-)
> 22. [ ]  M22.  `content/en/docs/reference/glossary/extensions.md`  | 1(+XS) 1(-)
> 23. [ ]  M23.  `content/en/docs/reference/glossary/namespace.md`  | 2(+XS) 2(-)
> 24. [ ]  M24.  `content/en/docs/reference/issues-security/security.md`  | 1(+XS) 1(-)
> 25. [ ]  M25.  `content/en/docs/reference/scheduling/config.md`  | 44(+M) 11(-)
> 26. [ ]  M26.  `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`  | 5(+XS) 1(-)

---

[`content/ko/docs/contribute/review/reviewing-prs.md` 문서의 mermaid 그림 관련]
1. [영문 버전 그림 링크](https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoiZmxvd2NoYXJ0IExSXG4gICAgc3ViZ3JhcGggZm91cnRoW1N0YXJ0IHJldmlld11cbiAgICBkaXJlY3Rpb24gVEJcbiAgICBTWyBdIC0uLVxuICAgIE1bYWRkIGNvbW1lbnRzXSAtLT4gTltyZXZpZXcgY2hhbmdlc11cbiAgICBOIC0tPiBPW25ldyBjb250cmlidXRvcnMgc2hvdWxkPGJyPmNob29zZSBDb21tZW50XVxuICAgIGVuZFxuICAgIHN1YmdyYXBoIHRoaXJkW1NlbGVjdCBQUl1cbiAgICBkaXJlY3Rpb24gVEJcbiAgICBUWyBdIC0uLVxuICAgIEpbcmVhZCBkZXNjcmlwdGlvbjxicj5hbmQgY29tbWVudHNdLS0-IEtbcHJldmlldyBjaGFuZ2VzIGluPGJyPk5ldGxpZnkgcHJldmlldyBidWlsZF1cbiAgICBlbmRcbiBcbiAgQVtSZXZpZXcgb3BlbiBQUiBsaXN0XS0tPiBCW0ZpbHRlciBvcGVuIFBSczxicj5ieSBsYWJlbF1cbiAgQiAtLT4gdGhpcmQgLS0-IGZvdXJ0aFxuICAgICBcblxuY2xhc3NEZWYgZ3JleSBmaWxsOiNkZGRkZGQsc3Ryb2tlOiNmZmZmZmYsc3Ryb2tlLXdpZHRoOnB4LGNvbG9yOiMwMDAwMDAsIGZvbnQtc2l6ZToxNXB4O1xuY2xhc3NEZWYgd2hpdGUgZmlsbDojZmZmZmZmLHN0cm9rZTojMDAwLHN0cm9rZS13aWR0aDpweCxjb2xvcjojMDAwLGZvbnQtd2VpZ2h0OmJvbGRcbmNsYXNzRGVmIHNwYWNld2hpdGUgZmlsbDojZmZmZmZmLHN0cm9rZTojZmZmLHN0cm9rZS13aWR0aDowcHgsY29sb3I6IzAwMFxuY2xhc3MgQSxCLEosSyxNLE4sTyBncmV5XG5jbGFzcyBTLFQgc3BhY2V3aGl0ZVxuY2xhc3MgdGhpcmQsZm91cnRoIHdoaXRlIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)
image

2. [한국어 버전 그림 링크](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiXG5mbG93Y2hhcnQgTFJcbiAgICBzdWJncmFwaCBmb3VydGhb66as67ewIOyLnOyekV1cbiAgICBkaXJlY3Rpb24gVEJcbiAgICBTWyBdIC0uLVxuICAgIE1b7L2U66mY7Yq4IOyekeyEsV0gLS0-IE5b67OA6rK97IKs7ZWtIOumrOu3sF1cbiAgICBOIC0tPiBPW-yDiCDquLDsl6zsnpDqsIAg7Ja065akIOy9lOupmO2KuOulvDxicj7rsJjsmIHtlaDsp4Ag7ISg7YOd7ZW07JW8IO2VqF1cbiAgICBlbmRcbiAgICBzdWJncmFwaCB0aGlyZFtQUiDshKDtg51dXG4gICAgZGlyZWN0aW9uIFRCXG4gICAgVFsgXSAtLi1cbiAgICBKW-uzuOusuOqzvCDsvZTrqZjtirgg7ZmV7J24XS0tPiBLW05ldGxpZnkg66-466as67O06riwIOu5jOuTnOuhnDxicj7rs4Dqsr3sgqztla0g66-466as67O06riwXVxuICAgIGVuZFxuIFxuICBBW-yXtOugpCDsnojripQgUFIg66qp66GdIO2ZleyduF0tLT4gQlvroIjsnbTruJTsnYQg7J207Jqp7ZWY7JesPGJyPlBS7J2EIO2VhO2EsOungV1cbiAgQiAtLT4gdGhpcmQgLS0-IGZvdXJ0aFxuICAgICBcblxuY2xhc3NEZWYgZ3JleSBmaWxsOiNkZGRkZGQsc3Ryb2tlOiNmZmZmZmYsc3Ryb2tlLXdpZHRoOnB4LGNvbG9yOiMwMDAwMDAsIGZvbnQtc2l6ZToxNXB4O1xuY2xhc3NEZWYgd2hpdGUgZmlsbDojZmZmZmZmLHN0cm9rZTojMDAwLHN0cm9rZS13aWR0aDpweCxjb2xvcjojMDAwLGZvbnQtd2VpZ2h0OmJvbGRcbmNsYXNzRGVmIHNwYWNld2hpdGUgZmlsbDojZmZmZmZmLHN0cm9rZTojZmZmLHN0cm9rZS13aWR0aDowcHgsY29sb3I6IzAwMFxuY2xhc3MgQSxCLEosSyxNLE4sTyBncmV5XG5jbGFzcyBTLFQgc3BhY2V3aGl0ZVxuY2xhc3MgdGhpcmQsZm91cnRoIHdoaXRlXG4iLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)
image

/language ko

### CODE REVIEW

**Comment by jmyung** [comment]
@jihoon-seo 금일 밤에 꼭 진행하겠습니다. 리뷰가 늦어져 죄송해요.

**Comment by jihoon-seo** [comment]
@jmyung 리뷰 감사합니다. 😊
주신 의견들을 반영했습니다.
2차 변경 사항을 보실 수 있도록, sqaush는 하지 않았습니다.
확인 부탁드립니다. 😊

/label tide/merge-method/squash

**Comment by jmyung** [comment]
/lgtm 

수고 많으셨습니다. 👍 
마지막으로 squashing 부탁드려요.

**Comment by jihoon-seo** [comment]
squash 완료하였습니다.
감사합니다. 😊

/remove-label tide/merge-method-squash

**Comment by seokho-son** [comment]
감사합니다!
/approve

**Pull request merged**
