### PR TITLE
Modify spacing term ReplicaSet in Korean

### PR DESCRIPTION
**Pull request by coolguyhong**
- change from 레플리카 셋 to 레플리카셋

### CODE REVIEW

**Comment by coolguyhong** [comment]
from #22146

**Comment by gochist** [comment]
@coolguyhong 감사합니다!
/lgtm
/unassign
/assign @seokho-son

**Comment by seokho-son** [comment]
@coolguyhong @gochist 감사합니다 ^^
/approve

**Comment by coolguyhong** [comment]
@gochist @seokho-son 리뷰 해주셔서 감사합니다.^^

**Pull request merged**
