### PR TITLE
Improve Russian translation of README file

### PR DESCRIPTION
**Pull request by lex111**

### CODE REVIEW

**Comment by sftim** [comment]
Я плохо говорю по-русски
/uncc
/language ru

**Comment by sftim** [comment]
@kubernetes/sig-docs-ru-reviews would you like to take a look?

**Comment by Potapy4** [comment]
@sftim could you help us to push this? 🙂

**Comment by sftim** [comment]
> /assign @sig-docs-en-reviews

I'm not sure an English-language reviewer can help here. What kind of help did you have in mind?

**Comment by lex111** [comment]
@sftim the `README-ru.md` file is [owned by the sig-docs-en team](https://github.com/kubernetes/website/blob/master/OWNERS#L4), therefore, in order to accept a pull request we need approval from a member of this team, so the bot just informs us about this.

cc @zacharysarah

**Pull request merged**
