### PR TITLE
[zh-cn] Unify Simplified-Chinese translation of control-plane

### PR DESCRIPTION
**Pull request by KKtheGhost**
## PR Summary

In the kubernetes `zh-cn` **[zh-cn::Glossary page](https://kubernetes.io/zh-cn/docs/reference/glossary/?all=true#term-control-plane)** we could find that the recommended Simplified-Chinese translation of `control plane` is `控制平面`。

While it is not incorrect to translate it as `控制面`, as mentioned in `zh-cn/docs/contribute/localization_zh.md`, both translations are valid.

However, in the Kubernetes Docs, we could find that the term `Control Plane` has been translated as `控制面` in nearly 80 pages, as `控制平面` in over 200 pages.

When these two translations are mixed together, it can indeed potentially confuse the readers.

From the perspective of document consistency, unifying the standard translation according to **Glossary Page** should help reduce ambiguity to some extent.

<br>

Best Regards,

Kivinsae Fang

### CODE REVIEW

**Comment by tengqm** [comment]
Thanks for proposing this fix.
Please confirm that all pages touched by this PR are already sync'ed with the English upstream.
/hold

**Comment by KKtheGhost** [comment]
Hi @tengqm 

Thanks so much for the review!

I apologize for bothering you again.
I would like to confirm once again whether I should handle the confirmation with the ENG upstream sync by myself or if it should be done by other trusted reviewers. Should I attach a upstream sync report to this PR?
Thanks for any reply in advance, and wish u a nice week.

Best Regards,
Kivinsae Fang

**Comment by tengqm** [comment]
@KKtheGhost Please read https://kubernetes.io/zh-cn/docs/contribute/localization_zh/ before proceeding. There are quite a few conventions established for this teamed work.

In your particular case, we are very concerned about ["partial updates"](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#update). For example, if a page X has a lot of changes in the English version that are not yet been translated. When we accept your change to the same page X, which is about a trivial edit, the timestamp on page X will mask the more important changes that are yet to be sync'ed. We track changes by commit timestamps, and that is the reason we do not accept partial updates.

If you are interested in fixing all the inconsistencies, you may have to check the contents of those pages (using the scripts/lsync.sh tool). We can review and merge changes one by one, not in a huge batch.

**Comment by KKtheGhost** [comment]
@tengqm  Thank you very much for providing such a thorough explanation for me.
I sincerely apologize for my lack of attentiveness while reading the contribution convention page. It was entirely my fault.
Would you kindly assist me in closing this pull request? I will then perform the necessary sync check and proceed to create a separate pull request for each page individually.
Once again, I truly appreciate your response and advice! Wishing you a wonderful day.

Best Regards,
Kivinsae Fang

**Pull request closed without merging**
