### PR TITLE
ZH-trans: merge release1.16-temporary to master

### PR DESCRIPTION
**Pull request by xichengliudui**
/cc @chenrui333 @markthink @zhangxiaoyu-zidif @idealhack @SataQiu

### CODE REVIEW

**Comment by xichengliudui** [comment]
日志暂时不可用，我会继续更新 pr。
```
9:05:05 PM: [ERROR] Deploy logs are currently unavailable. We are working on resolving the issue.
```

**Comment by sftim** [comment]
```

**Comment by xichengliudui** [comment]
I have deleted the extra `{{% /capture %}}`, I think it may be caused by other problems but I can't see the log now which is the most troublesome

**Comment by markthink** [comment]
@xichengliudui  谢谢

/lgtm
/approve

**Comment by idealhack** [comment]
Hi, it seems there're some broken links after this merge https://kubernetes.slack.com/archives/CE3LNFYJ1/p1577291939000900

**Pull request merged**
