### PR TITLE
Update configure-liveness-readiness-startup-probes.md

### PR DESCRIPTION
**Pull request by ulrich**
Kept coherence. Using "vous" instead of "tu".

### CODE REVIEW

**Comment by ulrich** [comment]
CLA step done.

**Comment by tengqm** [comment]
@ulrich Maybe you can try verify if git config has the email set to the one you used for CLA. You may also want to do a `git commit --amend --reset-author` followed by a `git push -f` to trigger another CLA check.

**Comment by ulrich** [comment]
> @ulrich Maybe you can try verify if git config has the email set to the one you used for CLA. You may also want to do a `git commit --amend --reset-author` followed by a `git push -f` to trigger another CLA check.

Thank for reply @tengqm 

❯ git config --local -l 

image

**Comment by ulrich** [comment]
Restarted the CNCF signing process from scratch. Seems to be good now.

**Pull request merged**
