### PR TITLE
[zh-cn] resync reference/command-line-tools-reference/feature-gates.md

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
Resync `content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md` with en upstream PR #38734.

Format line 930.

### CODE REVIEW

**Comment by tengqm** [comment]
Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). To find out what are the upstream changes to be synced, do this **on the main branch**:

```shell
./scripts/lsync.sh content/zh-cn/docs/reference/command-line-tools-reference/feature-gates.md
```

/hold

**Comment by Zhuzhenghao** [comment]
@tengqm Thanks. I have checked the file and add the missing part.

**Comment by tengqm** [comment]
> @tengqm Thanks. I have checked the file and add the missing part.

Did you check the output from the script? The description for gate `DynamicResourceAllocation`, `CrossNamespaceVolumeDataSource`, `WindowsHostNetwork`, `CSIMigrationRBD` all need update.

**Comment by Zhuzhenghao** [comment]
```
@@ -496,6 +502,8 @@ Each feature gate is designed for enabling/disabling a specific feature:
   [downward API](/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information).
 - `DryRun`: Enable server-side [dry run](/docs/reference/using-api/api-concepts/#dry-run) requests
   so that validation, merging, and mutation can be tested without committing.
+- `DynamicResourceAllocation": Enables support for resources with custom parameters and a lifecycle
+  that is independent of a Pod.
 - `EndpointSliceTerminatingCondition`: Enables EndpointSlice `terminating` and `serving`
    condition fields.
 - `EfficientWatchResumption`: Allows for storage-originated bookmark (progress
```

Refer to this [section](https://github.com/kubernetes/website/pull/38677/files#diff-3755580998cf87ec515439aa9038ec4f29d223484b2d6ca1a8ea77eb2ce053adR738-R745).

I see this change has been synced already.

`CrossNamespaceVolumeDataSource`,` WindowsHostNetwork`, `CSIMigrationRBD` are all synced in that PR.


I am confused do I miss something?

**Comment by tengqm** [comment]
Okay. Maybe the English change was merged after the Chinese sync had been merged.
/lgtm
/approve

**Pull request merged**
