### PR TITLE
Fix typo in german docs

### PR DESCRIPTION
**Pull request by pirgeo**

### CODE REVIEW

**Review by bene2k1 — APPROVED** [review]

**Review by sftim — COMMENTED** [review]
Ideally, we'd update the German text to be level with the [English original](https://kubernetes.io/docs/concepts/containers/images/).

**Comment by pirgeo** [comment]
Oh, I didn't realize that they had diverged. I feel like bringing the two more in line is a separate PR though, WDYT?

**Comment by pirgeo** [comment]
I think this PR is still missing a LGTM label before it gets auto-merged. Anything I need to do to get that? Anyone in particular to tag or assign? I am pretty new to the whole process here...

**Review by Sea-n — COMMENTED** [review]
The changes looks good to me, this PR is ready for merge! 🎉
/lgtm

**Pull request merged**
