### PR TITLE
Merge master to release-1.16.

### PR DESCRIPTION
**Pull request by irvifa**
Merge master to release-1.16.

### CODE REVIEW

**Comment by sftim** [comment]
I don't understand the motivation for this pull request. The v1.17 release is some way off, right?

Website CI runs off the _master_ branch so when v1.17 comes out someone will update the v1.16 label to include everything from _master_, and then merge the v1.17 content into _master_. This PR does not seem needed.

@irvifa does that make sense?

**Comment by inductor** [comment]
Also PR is here https://github.com/kubernetes/website/pull/17448 too. What's the difference, really?

**Pull request closed without merging**
