### PR TITLE
Added new owner for pt-BR

### PR DESCRIPTION
**Pull request by devlware**
Added new owner for pt-BR.

### CODE REVIEW

**Comment by zacharysarah** [comment]
/unassign

@xiangpengzhao Thanks for reviewing this PR. For localization owner changes, please let the localization team LGTM/approve any changes.

**Comment by xiangpengzhao** [comment]
@zacharysarah I saw that @femrtnz lgtm'd the PR and as he is an owner of pt, so I tried to help approve the PR (and seems like that I couldn't :rofl: )

**Pull request merged**
