### PR TITLE
Fix kubectl zsh completion instructions

### PR DESCRIPTION
**Pull request by ahmetb**
taking over from #3787.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5731)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@mengqiy Can you give tech approval for this? Thanks.

**Comment by ahmetb** [comment]
@mengqiy friendly ping.

**Comment by zhangxiaoyu-zidif** [comment]
ping @mengqiy  @pwittrock @shiywang

**Pull request merged**
