### PR TITLE
Merged main into dev 1.24

### PR DESCRIPTION
**Pull request by nate-double-u**
Week 6 update to bring `main` into `dev-1.24` branch.

### CODE REVIEW

**Comment by nate-double-u** [comment]
No errors this week. 🙂

/cc @JamesLaverack, FYI
/cc @jlbutler @sftim @reylejano

**Comment by reylejano** [comment]
👍 clean sync 
/lgtm

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
