### PR TITLE
Tidy install guide for container runtimes

### PR DESCRIPTION
**Pull request by sftim**
Changes to https://kubernetes.io/docs/setup/cri/

- Use a `{{< feature-state >}}` note to indicate feature status
- Make it clear these instructions apply to Linux
- De-emphasise the advice on `cgroupfs` (because the detailed instructions are already adapted)
- Explain what cgroup is short for

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@bradtopol Please take a look at this PR.

**Comment by Rajakavitha1** [comment]
@bradtopol could you please take a look at this PR.

**Comment by bradtopol** [comment]
Great job!
/lgtm
/approve

**Pull request merged**
