### PR TITLE
fix namespace name in the example

### PR DESCRIPTION
**Pull request by amirensit**
Fix the namespace name in the example.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/28918#issuecomment-878944251

**Comment by amirensit** [comment]
I signed it.

**Comment by reylejano** [comment]
/check-cla

@amirensit ,
if the check cla fails, check if your git config has the same email as the one you registered with for the CLA, if it is then you can also try to add the `--signoff` option with `git commit` to verify your info for the commit

**Comment by kbhawkey** [comment]
Testing
/close

**Comment by reylejano** [comment]
The example is trying to state that a pod in a different namespace can resolve a service in another namespace.
The original example is correct and should not be changed
Closing this PR
/close

**Pull request closed without merging**
