### PR TITLE
Update configure-cloud-provider-firewall.md

### PR DESCRIPTION
**Pull request by jrudley**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

### CODE REVIEW

**Comment by jrudley** [comment]
I worked with Microsoft support and this feature is supported on AKS. "I did reach out to my backend team for clarification and they assured that this should work for you though the document doesn’t specify that it will work on Azure."

**Comment by bradtopol** [comment]
@jrudley Thank you for your contribution. Please sign the CLA so we can accept your PR

**Comment by mistyhacks** [comment]
If you're having trouble signing the CLA, or you have signed it and it's not
working correctly, see https://github.com/cncf/servicedesk for more info. You
can also contact #sig-contribex on Slack. We cannot accept this contribution
until the checks are working correctly. Thanks!

**Comment by zparnold** [comment]
@jrudley Just a friendly reminder to sign the CLA if you are able to

**Comment by jrudley** [comment]
Sorry, I will not be able to get to this as I am out of town. Please reject the pr

⁣

**Comment by zparnold** [comment]
@jrudley Ok. Thanks!

**Pull request closed without merging**
