### PR TITLE
[bn] Launch the first Bengali localization

### PR DESCRIPTION
**Pull request by seokho-son**
This PR will launch the first version of Bengali localization live.
- Reference: #31677
- Following a request for assistance from the Bengali localization team (see [Slack thread](https://kubernetes.slack.com/archives/C0191RDKHU1/p1706710693916689?thread_ts=1706256431.759859&cid=C0191RDKHU1)), I, as one of the localization subproject leads, have opened this PR.

The purpose of this PR is to merge all commits from dev-1.23-bn.1 into the main branch, enabling Bengali localization to go live.
 - The feature branch `seokho-son:dev-1.23-bn.1` is the result of rebasing the upstream `dev-1.23-bn.1` onto the latest main branch. I manually resolved merge conflicts, specifically in `OWNERS_ALIASES` and `hugo.toml`.
 - This PR will merge only one squashed commit.
 - The decision to squash commits from dev-bn into one was made to eliminate redundant or irrelevant commit messages.
 - This commit message includes all co-authors who contributed to this significant effort.

This PR encompasses the following contributions: [is:pr base:dev-1.23-bn.1 is:merged](https://github.com/kubernetes/website/pulls?q=is%3Apr+base%3Adev-1.23-bn.1+is%3Amerged+)

A huge thank you to all contributors and members of the Bengali l10n Team! (Bengali l10n Team [Slack channel](https://kubernetes.slack.com/archives/CQ0TD298C))

---

This PR also includes changes to the OWNERS_ALIAS file; therefore, SIG Docs leads need to review it before merging.

```
  sig-docs-bn-owners: # Admins for Bengali content
    - Imtiaz1234
    - mitul3737
    - rajibmitra
  sig-docs-bn-reviews: # PR reviews for Bengali content
    - Imtiaz1234
    - mitul3737
    - rajibmitra
```

### CODE REVIEW

**Comment by seokho-son** [comment]
CC 
- @mitul3737
- @Imtiaz1234
- @rajibmitra
- @asem-hamid

**Comment by seokho-son** [comment]
Noticed build failure: https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/65bb75d46a968500081eb2ab

**Comment by sftim** [comment]
For the squash, I suggest listing all the coauthors in one section at the end of the commit message.

**Comment by sftim** [comment]
Also see #44986

**Comment by sftim** [comment]
@seokho-son I propose closing this in favor of a new PR that aims to merge in _dev-1.24-bn.1_.

How about that?

**Comment by sftim** [comment]
/close

in favor of https://github.com/kubernetes/website/pull/45009

**Pull request closed without merging**
