### PR TITLE
Updated kubectl describe svc output

### PR DESCRIPTION
**Pull request by kundan2707**
updated  kubectl describe svc my-nginx output
fixes : #38903

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Please edit the PR description to ensure you mention the issue that it fixes, as well.

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by kundan2707** [comment]
> Please edit the PR description to ensure you mention the issue that it fixes, as well.

Added issue in description

**Comment by nate-double-u** [comment]
Thanks for this @kundan2707!

/approve

**Pull request merged**
