### PR TITLE
Fix typo in metrics page PersistenVolume -> PersistentVolume

### PR DESCRIPTION
**Pull request by aneurinprice**
### Description

Fix typo

### Issue
 N/A

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
This [Kubernetes Metrics Reference](https://kubernetes.io/docs/reference/instrumentation/metrics/) page is [auto-generated](https://kubernetes.io/docs/reference/instrumentation/metrics/#auto-generated-edit-notice).
We should fix either the generator code or the API definition that the generator uses as its input.

_For more information on generating Metrics page, please refer to the documentation here: https://kubernetes.io/docs/contribute/generate-ref-docs/metrics-reference/._

**Comment by dipesh-rawat** [comment]
/hold

PR is modifying the auto generated page directly.

**Comment by mengjiao-liu** [comment]
Previously @windsonsea  mentioned PR in K8s upstream to solve this problem 
- https://github.com/kubernetes/website/pull/47827

Maybe we do need to open this PR again?

**Comment by mengjiao-liu** [comment]
PR https://github.com/kubernetes/kubernetes/pull/117540 is also dealing with this issue.

**Pull request closed without merging**
