### PR TITLE
Fix poor web style in some page footers

### LINKED ISSUE #48225: The Footer Text is Not readable
**What Happened**
The **kubernetes.io/partners** footer is having text which is not readable and instead of logos it is having a white box which is making the page inconsistent.

**How to resolve it:**
Improve the look and feel of partners css file in which footer design should be improved. So that the element written in footer can be easily visible.

**Page to resolve :**
https://kubernetes.io/partners/

**Image The issue is talking about( To understand it easily)**

### PR DESCRIPTION
**Pull request by niranjandarshann**
This PR Fixes #48225

### CODE REVIEW

**Comment by sftim** [comment]
This does seem to fix it

/retitle Fix poor web style on partners page

**Comment by niranjandarshann** [comment]
This also resolve Case Studies poor web style on footer as well.

**Comment by sftim** [comment]
/retitle Fix poor web style in some page footers

**Review by divya-mohan0209 — COMMENTED** [review]
Per [this preview](https://deploy-preview-48226--kubernetes-io-main-staging.netlify.app/partners/), the proposed change fixes the issue. Approving it.
/approve

**Pull request merged**
