### PR TITLE
Blog post: Gardener Project Update

### PR DESCRIPTION
**Pull request by rfranzke**
This is a follow-up blog post of https://kubernetes.io/blog/2018/05/17/gardener/ (#8546).

It talks about updates and progress of [Project Gardener](https://gardener.cloud) made in the past one and a half years. Also, it outlines the next steps and what the community plans for the future.

Preview: https://deploy-preview-17516--kubernetes-io-master-staging.netlify.com/blog/2019/11/10/gardener-project-update/

### CODE REVIEW

**Comment by vasu1124** [comment]
@parispittman @Rajakavitha1 , could you please have a look? 

We had a lot of requests from the last KubeCon and would like to get this out for the upcoming one ...

**Comment by hardikdr** [comment]
+100

**Comment by rfranzke** [comment]
@parispittman @kbarnard10 @Rajakavitha1 @caniszczyk - any feedback or suggestions?

**Comment by mrbobbytables** [comment]
/lgtm -- from technical perspective 👍 
ping @kbarnard10 for approve

**Comment by mrbobbytables** [comment]
/lgtm
forgot to put it on a separate line. 🤦‍♂

**Comment by rfranzke** [comment]
@mrbobbytables @kbarnard10 what's the status of this PR now?

**Comment by rfranzke** [comment]
Thank you very much @kbarnard10 :)

**Pull request merged**
