### PR TITLE
Prevent hugo's wrong yaml rendering

### LINKED ISSUE #9569: resource-quotas.md YAML inside bullet point not rendering correctly
- [ ] Feature Request
- [x] Bug Report

**Problem:**

YAML inside bullet point is not rendering correctly at https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-per-priorityclass

image

Source code, today: https://github.com/kubernetes/website/blob/bac30c0774057562f198402c5964cab400722630/content/en/docs/concepts/policy/resource-quotas.md

**Page to Update:**
https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-per-priorityclass

This might be a Hugo or chroma issue (YAML highlighter used by Hugo). ~~See this issue: https://github.com/alecthomas/chroma/issues/141~~

### PR DESCRIPTION
**Pull request by makocchi-git**
This PR fixes #9569
* remove command prompt
* split each code snippet into command and output
* wrap note by shortcodes

### CODE REVIEW

**Comment by Bradamant3** [comment]
@makocchi-git can you please merge/rebase to resolve conflicts? And we'll get this merged. Thanks for wrestling with Blackfriday markdown!

**Comment by makocchi-git** [comment]
@Bradamant3 Thank you for your comment.
Rendering issue was fixed by #9906, so this PR fixes only code snippets.

**Pull request merged**
