### PR TITLE
Fix broken link on issue-wrangler.md

### PR DESCRIPTION
**Pull request by able8**
The correct link is https://kubernetes.io/docs/contribute/review/for-approvers/#triage-and-categorize-issues

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for fix!
/lgtm

[Preview Page](https://deploy-preview-43712--kubernetes-io-main-staging.netlify.app/docs/contribute/participate/issue-wrangler/)

**Review by kundan2707 — COMMENTED** [review]
/lgtm
thanks

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by kundan2707** [comment]
@able8  you changes has been deleted by your lataest commit

**Comment by windsonsea** [comment]
/unhold

Please squash your commits into a single one. Refer to:
https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

**Pull request merged**
