### PR TITLE
Update _redirects

### PR DESCRIPTION
**Pull request by c-mcdonnell**
Updated the redirects for "Resource Bin Packaging".

### CODE REVIEW

**Comment by sftim** [comment]
I think this is intended to be part of PR #23359 

@c-mcdonnell you would need to revise that pull request, I'm afraid, incorporating the changes you're suggesting here. I don't think you're able to do all that via GitHub's web interface only.

**Comment by c-mcdonnell** [comment]
@sftim, I just revised the description for PR #23359 but got an error saying it is not mergeable because it doesn't meet label requirements.

**Comment by sftim** [comment]
You can revise pull requests during a merge freeze, but the approvers won't merge them until the merge freeze ends.

**Comment by zacharysarah** [comment]
Per review ☝️ , this PR's changes need to fold into #23359. 

/close

**Pull request closed without merging**
