### PR TITLE
Add Managed Computer Resources for DigitalOcean

### PR DESCRIPTION
**Pull request by omarismail**
### Description

DigitalOcean runs a Managed Kubernetes offering. The `Meaning of CPU` in the [Kubernetes Documentation](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) does not list DigitalOcean. This PR adds DigitalOcean to that list. 

### Docs

According to the [DigitalOcean Kubernetes Documentation page](https://www.digitalocean.com/docs/kubernetes/#worker-nodes-and-node-pools), the Worker Nodes run on Droplets, and abide by the same standard Droplet resources. 

See image below of the detailed description of compute resources during Cluster Create:
image

### CODE REVIEW

**Comment by omarismail** [comment]
@zparnold I just signed up for the Contributor Lisencing Agreement:

image

**Comment by jimangel** [comment]
@omarismail thanks for this PR! However, I think instead of listing each cloud provider, it would be better to simplify our docs. I opened up PR #19797 to resolve this.

Let me know if you have any questions! Thanks!

/close

**Pull request closed without merging**
