### PR TITLE
Update outdated links

### PR DESCRIPTION
**Pull request by jihoon-seo**
Related issue: #28575

/language en

### CODE REVIEW

**Comment by seokho-son** [comment]
Thanks! :)
/lgtm

**Comment by kbhawkey** [comment]
Page previews:
https://deploy-preview-28748--kubernetes-io-main-staging.netlify.app/docs/reference/glossary/?all=true#term-preemption
https://deploy-preview-28748--kubernetes-io-main-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/

**Comment by kbhawkey** [comment]
Thanks @jihoon-seo .
/approve

**Pull request merged**
