### PR TITLE
[zh]Sync reference-14

### PR DESCRIPTION
**Pull request by nameYULI**
related issue: https://github.com/kubernetes/website/issues/33478
reference-14
```
580	165	content/en/docs/reference/using-api/api-concepts.md
```

### CODE REVIEW

**Comment by tengqm** [comment]
This is an improvement to the previous sync.

**Comment by sftim** [comment]
@nameYULI it turned out that these changes led to the website build not working. Would you be willing to make a new PR (based on the latest _main_ branch) that does the same thing? We'll make sure to test that that works; if you can, please also test that locally in case the same issue arises.

**Comment by sftim** [comment]
I think the problem may have only showed up after the merge; our Netlify system builds the branch and not a simulated merge.

(if you want a bit more context on what that means, see https://github.com/actions/checkout/issues/15).

Anyway, these changes still need doing, that's the short version. Thank you for sending them in and I hope you will be willing to try once more.

**Comment by tengqm** [comment]
@nameYULI Please manually rework this PR. We are losing track of the change date for this file. I hoped that it can be fixed in an easy way, but ... the whole PR is now reverted.

**Pull request merged**
