### PR TITLE
[ja] fix kubeadm-cert.md

### PR DESCRIPTION
**Pull request by ystkfujii**
fix skew shortcode, typo and syntax error

### CODE REVIEW

**Comment by ystkfujii** [comment]
Deploy page:

https://deploy-preview-39976--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

**Review by t-inu — COMMENTED** [review]
Good catch!
/lgtm

**Comment by ystkfujii** [comment]
@t-inu 
Thank you !

/assign @nasa9084
Could you review this?

**Pull request merged**
