### PR TITLE
add AppDirect case study

### PR DESCRIPTION
**Pull request by alexcontini**

### CODE REVIEW

**Comment by alexcontini** [comment]
/approve

@zacharysarah @kbarnard10 please review and merge when you have a chance, thank you!

**Comment by alexcontini** [comment]
@zacharysarah when you have a chance, will you please merge (I have been asked to make sure it goes live tmrw so they can notify AppDirect) - sorry if you are not the one I should be tagging for this!

**Comment by zacharysarah** [comment]
@alexcontini I'm happy to merge this once code thaws for k/website. (We're frozen for release day.)

**Comment by kbarnard10** [comment]
@alexcontini Can you make sure going forward the new case studies are added on the homepage and top section on the case studies pages?

**Comment by alexcontini** [comment]
thank you very much!!! @kbarnard10 will fix that right away

**Pull request merged**
