### PR TITLE
Fix typos in replicationcontroller.md

### PR DESCRIPTION
**Pull request by leo8a**

### CODE REVIEW

**Comment by raelga** [comment]
Buenas @leo8a, para poder aceptar la contribución, es necesario que firmes la CLA:

https://git.k8s.io/community/CLA.md#the-contributor-license-agreement

Si tienes cualquier duda, puedes contactar conmigo por slack o por correo.

Un saludo!

**Comment by zparnold** [comment]
@leo8a thanks for your contribution! 🎉 We really would love to have it, unfortunately to continue we need to have your (or your company's) signature on a CLA! For now I'm going to close this, but fret not! You can re-open whenever you have a chance. Thanks!
/close

**Comment by raelga** [comment]
@leo8a I just created a new PR to apply your fix, but let me know if you have any issue with the CLA for your next contribution!

**Pull request closed without merging**
