### PR TITLE
Create blog post template

### PR DESCRIPTION
**Pull request by rolfedh**
- Fix issue #27843 Create an annotated blog post template.
- For discussion and development

### CODE REVIEW

**Comment by rolfedh** [comment]
I already signed the CLA.  I'm setting your commit email address in Git to see if it fixes this failed check.

**Comment by rolfedh** [comment]
I signed it

**Comment by rolfedh** [comment]
The CLA system is broken.

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
Unfortunately this won't work as intended :( It shows up as a blog page on the site. It could be done as [hugo archtype](https://gohugo.io/content-management/archetypes/) but I doubt people would use it. =/

**Comment by nate-double-u** [comment]
> Unfortunately this won't work as intended :( It shows up as a blog page on the site. It could be done as [hugo archtype](https://gohugo.io/content-management/archetypes/) but I doubt people would use it. =/

Would setting `draft: true` in the frontmatter solve this?

**Comment by rolfedh** [comment]
> > Unfortunately this won't work as intended :( It shows up as a blog page on the site. It could be done as [hugo archtype](https://gohugo.io/content-management/archetypes/) but I doubt people would use it. =/
> 
> Would setting `draft: true` in the frontmatter solve this?

That sounds like a good idea. I'll update the PR accordingly.

It would be critical for this template to show up conspicuously in the *same* place contributors create their new blog posts. Otherwise, as @mrbobbytables has pointed out, folks aren't likely to know about or use it.

**Comment by kbhawkey** [comment]
Hi @rolfedh .
I like the idea of creating a template. The example blog page you provided seems similar to the docs test page (which is not published). See, `/docs/test.md`.

**Comment by kbhawkey** [comment]
Testing
/close

**Comment by kbhawkey** [comment]
@rolfedh , Can you double check,
`If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. `

**Comment by nate-double-u** [comment]
> Hi @rolfedh .
> 
> I like the idea of creating a template. The example blog page you provided seems similar to the docs test page (which is not published). See, `/docs/test.md`.

I think the smoke test is published, it's just not on the menu:

https://kubernetes.io/docs/test/

If it isn't intended to be published at all we may want to open a separate issue.

**Comment by kbhawkey** [comment]
> 
> 
> > Hi @rolfedh .
> > I like the idea of creating a template. The example blog page you provided seems similar to the docs test page (which is not published). See, `/docs/test.md`.
> 
> I think the smoke test is published, it's just not on the menu:
> 
> https://kubernetes.io/docs/test/
> 
> If it isn't intended to be published at all we may want to open a separate issue.

Right, it is published but not publically. I think this is okay.

**Comment by rolfedh** [comment]
> @rolfedh , Can you double check,
> `If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. `

I'm not sure. I've gone through all the recommended troubleshooting steps multiple times and everything seems to check out. I've heard folks talk about the PR not picking up the updated email address. I'll create a test PR when I start working on this again tonight.

**Comment by RA489** [comment]
> I signed it

/check-cla

**Comment by rolfedh** [comment]
Closing this PR. Will try a new one with some of the recommendations here and elsewhere.

**Comment by rolfedh** [comment]
Closing this PR. Will try a new one with some of the recommendations here and elsewhere.

**Pull request closed without merging**
