### PR TITLE
fix-24683

### LINKED ISSUE #24683: [zh]: Custom DNS example mistakes
Please replace the code from 

```
proxy .  172.16.0.1
```

to 

```
forward .  172.16.0.1
```

please kindly check the mistake in below link

https://kubernetes.io/zh/docs/tasks/administer-cluster/dns-custom-nameservers/#%E7%A4%BA%E4%BE%8B

### PR DESCRIPTION
**Pull request by guiadco**
Fix mistake on `dns-custom-nameservers` regarding another language.

Close #24683

### CODE REVIEW

**Comment by guiadco** [comment]
I signed it

**Comment by Aisuko** [comment]
@guiadco Thanks for you contributing, maybe you can sign in the CLA and try to push the code again?

**Comment by guiadco** [comment]
@Aisuko Now normally it's ok for the CLA

**Comment by Aisuko** [comment]
@sftim May you help us out?  This a configuration mistakes in `zh` language but may not reference to the language itself.

**Comment by howieyuen** [comment]
> @sftim Sorry to bother you. May you help us out? This a configuration mistakes in `zh` language doc, but may not reference to the language itself. So,the PR can be merge

According to EN page(https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#example), code block is different from description, so it's the PR working for .

**Comment by howieyuen** [comment]
/lgtm
/approve
Welcome to kubernetes/website! Thanks for your contribution ! 👏

**Pull request merged**
