### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by Joy-Walker**
Update _index.md

update "应用程式" to "应用程序"

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@Joy-Walker  Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Comment by tengqm** [comment]
@Joy-Walker You have to sign the CLA in order for this PR to be reviewed and merged.

**Comment by tengqm** [comment]
CLA missing for more than a month. Closing.
/close

**Comment by scydas** [comment]
I will fix it, thanks!

**Pull request closed without merging**
