### PR TITLE
create a secret failed

### PR DESCRIPTION
**Pull request by illidan33**
There is an extra space before the field 'type', so to create a secret failed. The message is "error: error parsing nginxsecret.yaml: error converting YAML to JSON: yaml: line 5: did not find expected key".

### CODE REVIEW

**Comment by reylejano** [comment]
@illidan33 Please sign the [CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement). This PR will not be reviewed until the [CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement) is signed.

**Comment by illidan33** [comment]
> @illidan33 Please sign the [CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement). This PR will not be reviewed until the [CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement) is signed.

sure, i have signed.

**Review by sftim — COMMENTED** [review]
Thanks!
This change matches the English equivalent of that page.
/lgtm

**Pull request merged**
