### PR TITLE
Updates documentation pertaining to VMware

### PR DESCRIPTION
**Pull request by venilnoronha**
This PR produces the following changes.
* Adds `301` redirection for [/docs/getting-started-guides/vsphere/](https://kubernetes.io/docs/getting-started-guides/vsphere/) to https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/
* Updates hyperlinks from [/docs/getting-started-guides/vsphere/](https://kubernetes.io/docs/getting-started-guides/vsphere/) to https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/
* Updates solution table entries for VMware vSphere
* Fixes typos i.e. VMWare/Vmware -> VMware

Please review and merge.

Thanks,
Venil

### CODE REVIEW

**Comment by heckj** [comment]
:wave: @venilnoronha - this migrates all the vsphere storage pieces, but seems to be dumping the VMware cloud provider detail in the process. Is that intended?

**Comment by venilnoronha** [comment]
👋 @heckj the removal of vSphere Cloud Provider documentation is intended as we want to maintain all documentation at a single location, which is https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/. Thanks!

**Comment by bradtopol** [comment]
In this scenario, the removal of vSphere Cloud Provider documentation so that they can maintain all documentation at a single location simplifies everyone's lives.
/lgtm

**Pull request merged**
