### PR TITLE
Consolidate YAML files [part-9]

### PR DESCRIPTION
**Pull request by tengqm**
This PR relocates the YAML files referenced by the data injection topic.

### CODE REVIEW

**Comment by tengqm** [comment]
Links to previews:

- https://deploy-preview-9361--kubernetes-io-master-staging.netlify.com/docs/tasks/inject-data-application/define-command-argument-container/
- https://deploy-preview-9361--kubernetes-io-master-staging.netlify.com/docs/tasks/inject-data-application/define-environment-variable-container/
- https://deploy-preview-9361--kubernetes-io-master-staging.netlify.com/docs/tasks/inject-data-application/distribute-credentials-secure/
- https://deploy-preview-9361--kubernetes-io-master-staging.netlify.com/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
- https://deploy-preview-9361--kubernetes-io-master-staging.netlify.com/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
- https://deploy-preview-9361--kubernetes-io-master-staging.netlify.com/docs/tasks/inject-data-application/podpreset/

**Comment by stewart-yu** [comment]
But i have question, why not move `example/` directoty into `docs/content/en/`?

**Comment by tengqm** [comment]
@stewart-yu Thanks for the review. The examples directory lives in the `content/en` subdirectory, out of `content/en/docs` because team prefer to have the sample files isolated from the markdown contents. The intent is to enable 1) the sample files to be updated, referenced, tested and used independent from the markdown contents; 2) the content files to be freely shuffled without requiring the contributors to move the sample files and update the examples_test.go file every time they do so.

**Pull request merged**
