### PR TITLE
[zh-cn] Fix bold format

### PR DESCRIPTION
**Pull request by Sea-n**
In this Markdown parser, the format `中文**字串（English）**中文` will not parsed as bold.

In `web-ui-dashboard.md`, `**CPU 需求（核数）**和**内存需求（MiB）**` is parsed as `<b>CPU 需求（核數）<b>和</b>記憶體需求（MiB）</b>`.

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Changes Looks good.

**Comment by windsonsea** [comment]
/lgtm

The preview looks good.

https://deploy-preview-37531--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/cluster-administration/

**Pull request merged**
