### PR TITLE
Modify invalid url in docs

### PR DESCRIPTION
**Pull request by csskuber**
Modify invalid url link in docs

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
hmmm, seems like that repo will not be maintained any longer...

**Comment by csskuber** [comment]
@xiangpengzhao translation work should be commited to https://github.com/kubernetes/website, it seems better.

**Comment by chenopis** [comment]
@csskuber, I see you have signed the CLA in your other PRs, but this PR is not recognizing it. Can you open a new PR w/ these changes? Thx

**Pull request closed without merging**
