### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Anorlondo448**
Fix typo on concept page

### CODE REVIEW

**Comment by inductor** [comment]
@Anorlondo448 Can you set the target branch to `dev-1.17-ja.2` ?

**Comment by Anorlondo448** [comment]
@inductor Changed target branch.

**Comment by inductor** [comment]
@Anorlondo448 Please remove unnecessary changes.

**Comment by Anorlondo448** [comment]
@inductor Sorry. I understood the meaning of your point. Changed target branch again.

**Pull request merged**
