### PR TITLE
Add Kannada README.md

### PR DESCRIPTION
**Pull request by Shubhamkashyap1601**
Added a new language kannada for README

### CODE REVIEW

**Comment by Gauravpadam** [comment]
Hey @Shubhamkashyap1601, Thanks for your contribution! Would you please sign the CLA so that reviewers can review your PR?

**Review by dipesh-rawat — COMMENTED** [review]
We currently do not have a Kannada localization in place, which means there will be an additional barrier following the CLA process.

@Shubhamkashyap1601 Are you interested in starting localization for Kannada? It's important to note that a localization team should consist of at least two members. For guidance on getting started with a new localization, please refer: [Start a new localization](https://kubernetes.io/docs/contribute/localization/#start-a-new-localization)

Have you already discussed the idea of starting Kannada localization on the [sig-docs](https://kubernetes.slack.com/messages/sig-docs) or [sig-docs-localization](https://kubernetes.slack.com/messages/sig-docs-localizations) Slack channel?

One of the initial requirements is to have two Kannada localization contributors, who should also be members of the Kubernetes organization. This allows them to be added to the relevant owners file for the Kannada localization in a development branch. When there are two willing contributors who are Kubernetes org members, a SIG Docs co-chair or a tech lead will assist in creating the development branch for the Kannada localization.
I hope this information proves helpful!

/hold

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by sftim** [comment]
Thanks you for proposing this change. As you haven't signed our licence agreement, we can't accept it.

See https://github.com/kubernetes/website/pull/43592#issuecomment-1771441356

/close

**Pull request closed without merging**
