### PR TITLE
fix the default k8s version in kubeadm

### LINKED ISSUE #9884: Issue with k8s.io//docs/reference/setup-tools/kubeadm/kubeadm-init/ [File: /content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
```bash
--kubernetes-version string     Default: "stable-1.10"
--
  | Choose a specific Kubernetes version for the control plane.
```

The `stable-1.10` is out of date.

**Proposed Solution:**
Use `default "stable-1.11"`

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

v1.11

I found the out of date info is in `generated/kubeadm_init.md`. I wanna fix this, but I do not know how this file is generated.

### PR DESCRIPTION
**Pull request by xlgao-zju**
Fix #9884 

/assign @neolit123

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Isn't this file generated from some file else?

**Comment by neolit123** [comment]
files like that are only generated post release and only sig docs owns the HTML formatting.
in the meantime we need to fix things manually.

also the process of updating reference docs is outlined here:
https://github.com/kubernetes/kubeadm/blob/master/docs/updating-command-reference.md

**Comment by xlgao-zju** [comment]
> Isn't this file generated from some file else?

wdyt? @neolit123

**Pull request merged**
