### PR TITLE
Migrate “Contributing new content” overview into section index

### PR DESCRIPTION
**Pull request by mehabhalodiya**
resolves: #25123

### CODE REVIEW

**Comment by kbhawkey** [comment]
Temporarily holding to sort out questions in the issue. Thanks.
/hold

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-28302--kubernetes-io-master-staging.netlify.app/docs/contribute/new-content/

**Comment by kbhawkey** [comment]
Original pages:
https://kubernetes.io/docs/contribute/new-content/
https://kubernetes.io/docs/contribute/new-content/overview/

**Comment by kbhawkey** [comment]
Should the `_index.md` page remain a section index?
Or, should we turn off the section index functionality and manually manage/add links to the other pages?

**Comment by mehabhalodiya** [comment]
> Should the `_index.md` page remain a section index?
> Or, should we turn off the section index functionality and manually manage/add links to the other pages?

I think it should remain as it is.

**Comment by mehabhalodiya** [comment]
@kbhawkey Can you please let me know, what to do further?
Any changes needed?

**Comment by kbhawkey** [comment]
:wave: @mehabhalodiya .
The changes look okay.
/lgtm

**Comment by mehabhalodiya** [comment]
>  @mehabhalodiya .
> The changes look okay.
> /lgtm

Now what to be done? @kbhawkey

**Comment by mehabhalodiya** [comment]
@kbhawkey @jimangel @kbarnard10 @tengqm

**Comment by mehabhalodiya** [comment]
@kbhawkey @jimangel @kbarnard10 @tengqm @sftim
Requesting you to take a look!

**Comment by sftim** [comment]
We couldn't merge this as-is as there is a conflict that the automatic system does not know how to resolve.

@mehabhalodiya if you haven't done a rebase before, you really have 2 options
1. Learn about Git rebasing. It's a great skill if you often work with source control; on the other hand, if you're mostly a writer or focus your skills in other areas than Git, it's probably not worth the effort (it's genuinely not that easy to learn the first time round).
2. Close this pull request, and open a new one based on the `main` branch that makes the same changes. In the new PR, mention that it's a replacement for PR #28302.

**Comment by sftim** [comment]
/remove-label tide/merge-method-squash

@mehabhalodiya can we help you to move this change forward?

**Comment by mehabhalodiya** [comment]
> /remove-label tide/merge-method-squash
> 
> @mehabhalodiya can we help you to move this change forward?
> 
> 

Yes, @sftim help me to move forward!

**Comment by reylejano** [comment]
Hi @mehabhalodiya , here are some time for the following:
- [merge conflicts and rebasing](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#merge-conflicts-and-rebasing)
- [squashing commits](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits)

You can also go with @sftim's second [suggestion](https://github.com/kubernetes/website/pull/28302#issuecomment-864603066):
> Close this pull request, and open a new one based on the main branch that makes the same changes. In the new PR, mention that it's a replacement for PR Migrate “Contributing new content” overview into section index #28302.

**Comment by RinkiyaKeDad** [comment]
Hey @mehabhalodiya! Do you need any help rebasing the PR? Please also feel free to close this and create a new one if you're more comfortable doing that like Tim and Rey mentioned above.

**Comment by kbhawkey** [comment]
👋 @mehabhalodiya .
I plan to close this pull request.
Feel free to open a new PR.
/close

**Pull request closed without merging**
