### PR TITLE
[WIP] KEP-784

### PR DESCRIPTION
**Pull request by aroradaman**
enhancement issue: https://github.com/kubernetes/enhancements/issues/784

### CODE REVIEW

**Comment by a-mccarthy** [comment]
Hi @aroradaman  👋 just checking in on this PR, is this for docs updates for 1.31 or a blog post?

**Comment by Princesso** [comment]
Hello @aroradaman :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday July 16th 2024 18:00 PST. Thank you!

**Comment by aroradaman** [comment]
closing this MR, will be targeting this for the next release cycle.
/close

**Comment by aroradaman** [comment]
@a-mccarthy @Princesso 
I'm aiming for this for the **1.31** release.
This will be a doc PR and I will try to get this reviewed before the deadline.

**Comment by drewhagen** [comment]
This website has been frozen for 1.31 and we will release tomorrow.

Changing the milestone to 1.32.

/milestone 1.32

**Comment by hacktivist123** [comment]
Hello @aroradaman 👋 :wave:! I'm reaching out from the Docs team. Just checking in as we approach Docs Freeze on Tuesday November 26th 18:00 PDT. This documentation appears to still be under review. To meet the Docs Freeze, this PR must have a technical review as well as `lgtm` and `approve` labels applied, without any unaddressed comments or concerns from SIG Docs. Thank you!

**Pull request closed without merging**
