### PR TITLE
Correct server-side-apply.md

### PR DESCRIPTION
**Pull request by wasimj**
Spelling mistake

DESCRIPTION: corrects spelling mistake

### CODE REVIEW

**Comment by Tej-Singh-Rana** [comment]
Hello, @wasimj You have to sign CLA to approve your PR.

**Review by Arhell — COMMENTED** [review]
more info about CLA, check please
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by celestehorgan** [comment]
Hi @wasimj, 

Are you having issues signing the CLA?

**Comment by wasimj** [comment]
signed

**Pull request merged**
