### PR TITLE
Redis Fix

### PR DESCRIPTION
**Pull request by thecrudge**
Redis fix
Closes: #14104

### CODE REVIEW

**Comment by bradtopol** [comment]
Hi @thecrudge does this need a technical review, or did you try it?

**Comment by thecrudge** [comment]
> Hi @thecrudge does this need a technical review, or did you try it?

We can put this on hold. Seems like there is a few issues with the tutorial 

/hold

**Comment by sftim** [comment]
Looks like #14177 (merged) covers a the same kind of fix.

**Comment by DanyC97** [comment]
i agree @sftim this PR was superseded by https://github.com/kubernetes/website/pull/14177

@thecrudge you happy to close the PR or i should go and do it ? 

P.S - will close the PR in next 24h in case we don't hear anything from you.

**Comment by thecrudge** [comment]
> i agree @sftim this PR was superseded by #14177
> 
> @thecrudge you happy to close the PR or i should go and do it ?
> 
> P.S - will close the PR in next 24h in case we don't hear anything from you.

While I agree with both of you, the tutorial needs a tech review. It is currently broken as it stands.

**Comment by DanyC97** [comment]
> > i agree @sftim this PR was superseded by #14177
> > @thecrudge you happy to close the PR or i should go and do it ?
> > P.S - will close the PR in next 24h in case we don't hear anything from you.
> 
> While I agree with both of you, the tutorial needs a tech review. It is currently broken as it stands.

which bit is broken as it stands @thecrudge  ?

**Comment by thecrudge** [comment]
This can be closed.

**Pull request closed without merging**
