### PR TITLE
[zh]translate content/docs/reference/kubernetes-api/common-definition…

### PR DESCRIPTION
**Pull request by howieyuen**
related: https://github.com/kubernetes/website/issues/32435

### CODE REVIEW

**Comment by tengqm** [comment]
/approve
Some dependent not available yet.

**Comment by howieyuen** [comment]
this PR cannot pass checks until https://github.com/kubernetes/website/pull/32518 get merged
see deploy log:
```
10:55:46 AM: ERROR 2022/03/28 02:55:46 [zh] REF_NOT_FOUND: Ref "../common-definitions/quantity": "/opt/build/repo/content/zh/docs/reference/kubernetes-api/common-definitions/resource-field-selector.md:56:25": page not found
```

**Comment by tengqm** [comment]
@howieyuen This one needs a rebase

**Pull request merged**
