### PR TITLE
Clarify sources of voluntary disruptions

### PR DESCRIPTION
**Pull request by mltsy**
See issue #22391

### CODE REVIEW

**Comment by mltsy** [comment]
Okay, I've signed the CLA and am using the correct e-mail address on the commit now...I did just sign it 30 minutes ago... is there a way to re-trigger the CLA check?

**Comment by RA489** [comment]
> Okay, I've signed the CLA and am using the correct e-mail address on the commit now...I did just sign it 30 minutes ago... is there a way to re-trigger the CLA check?

/check-cla

**Comment by mltsy** [comment]
Trying again, after connecting my Github account:
/check-cla

**Review by Arhell — COMMENTED** [review]
About CLA, check please
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by mltsy** [comment]
Well I've submitted a support request, because I've followed all the instructions there and can't figure out what the problem is.  If someone wants to just take this minor change and submit it themselves, please feel free! :sweat_smile:

**Comment by kbhawkey** [comment]
@mltsy , It is not clear what is happening with the CLA.
You could open a new PR (with these changes)?

/close

**Comment by kbhawkey** [comment]
Here you go

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-26840--kubernetes-io-master-staging.netlify.app/docs/concepts/workloads/pods/disruptions/

**Comment by mltsy** [comment]
Ah!  Well that was interesting :smile:   Thanks!

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
