### PR TITLE
Remind folk cron uses UTC.

### PR DESCRIPTION
**Pull request by g--**

### CODE REVIEW

**Comment by g--** [comment]
okay, I've signed the CLA

**Comment by erictune** [comment]
@g-- thanks for first kubernetes PR!

**Comment by zparnold** [comment]
@g-- What do you think of the copyedit I made on your branch? Is it still clear? It adds hugo shortcodes to make the callout a bit more visible

**Comment by g--** [comment]
ping @erictune and @zparnold can I get a 👍?

**Comment by g--** [comment]
What's the difference between /lgtm and /approved ?

**Pull request merged**
