### PR TITLE
[bn] Adding shortcode upcoming-releases.html

### PR DESCRIPTION
**Pull request by asem-hamid**
Adding shortcode upcoming-releases.html in bn version to solve this error 

image

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
This change of copying the [upcoming-releases](https://github.com/kubernetes/website/blob/main/layouts/shortcodes/upcoming-releases.html) shotrcode source to the Bengali language dev branch looks good to me!

/lgtm
`/approve` (Unofficially giving the nod of approval; the [dev-1.24-bn.1/OWNERS_ALIASES](https://github.com/kubernetes/website/blob/dev-1.24-bn.1/OWNERS_ALIASES#L35) is not currently synced with main for me to be able to approve this; officially need an approval from **sig-docs-en-owners** in [dev-1.24-bn.1/OWNERS_ALIASES](https://github.com/kubernetes/website/blob/dev-1.24-bn.1/OWNERS_ALIASES#L35)

**Comment by asem-hamid** [comment]
@reylejano Requesting for approval

**Review by sftim — COMMENTED** [review]
The best thing to do for this is to merge in the _main_ branch.

/hold

**Comment by sftim** [comment]
/lgtm cancel

This is the wrong way to do it; instead, I'd prefer to see either:
1. a PR merging _main_ into _dev-1.24-bn.1_
1. the localized text for the Bengali patch releases page being a localized version for the merge base of _dev-1.24-bn.1_
  In less technical language: localize an older version of that page that doesn't rely on this missing shortcode

If taking option #<span>2</span>, someone will need to update the patch releases page in Bengali after the localization has launched. **This is OK**; after any localization launches, there is still lots of work that people can do to improve it.

**Comment by asem-hamid** [comment]
@sftim Thanks for suggestion , we are going with option 2

**Pull request closed without merging**
