### PR TITLE
Typo in command description

### PR DESCRIPTION
**Pull request by dedok1997**
Use prepositional(предложный падеж) instead genitive(родительный падеж)

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@dedok1997  You can make your emails match up in one of two ways:

1. Login to the [CLA site](https://identity.linuxfoundation.org/projects/cncf) and change it to match what you use as your default email address on your GitHub account
2. Change your default email address on your GH account to the same one you used to sign the CLA.

**Comment by dedok1997** [comment]
I signed it

**Review by Potapy4 — APPROVED** [review]
/approve

**Pull request merged**
