### PR TITLE
Revert "zh_trans: kubeadm_alpha_phase_kubeconfig_user.md"

### PR DESCRIPTION
**Pull request by Chucky122**
Reverts kubernetes/website#11901

### CODE REVIEW

**Comment by xichengliudui** [comment]
@Chucky122  Why delete them?

**Comment by xichengliudui** [comment]
Please sign the CNCF agreement

**Comment by markthink** [comment]
@Chucky122 cla 要签一下，具体可参考 https://github.com/k8smeetup/k8s-official-translation

**Comment by zparnold** [comment]
Hey there! @Chucky122, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
CLA pending for over one month.

**Pull request closed without merging**
