### PR TITLE
Create Kubernetes Adoption Challenges

### PR DESCRIPTION
**Pull request by snyamars**
This request is for blog post on kubernetes adoption challenges.

### CODE REVIEW

**Comment by DanyC97** [comment]
@snyamars have you signed up the CLA ?

**Comment by snyamars** [comment]
Hi Dani,
Yes. I am an employee of Wipro Ltd and we have signed corporate CLA recently.
Kindly suggest if I have to do any thing additionally.

Rgds
Sreekanth


[http://marketing.wiprodigital.com/apps/wipro-esig/assets/images/logo-01.png]<http://www.wipro.com/>

Sreekanth Nyamars

COE OpenSource

Service Transformation

M: +91 99007 32506<tel:+91%2099007%2032506>

Wipro Limited








Sensitivity: Internal & Restricted

**Comment by kbarnard10** [comment]
Closing this one out since it's been published on DevOps.com.

**Pull request closed without merging**
