### PR TITLE
[es] Localize "Validate IPv4/IPv6 dual-stack" page in Spanish

### PR DESCRIPTION
**Pull request by jheimar**

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/retitle [es] Localize "Validate IPv4/IPv6 dual-stack" page in Spanish

**Comment by dipesh-rawat** [comment]
@jheimar Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: https://git.k8s.io/community/CLA.md

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by network-charles** [comment]
Thanks for opening this PR, @jheimar. Could you do the following:
1. Sign the CLA to validate your PR.
2. Provide a better description of the PR.

**Comment by electrocucaracha** [comment]
@jheimar alguna novedad con este cambio, DM si necesitas ayuda

**Comment by ramrodo** [comment]
@jheimar could you do a `git squash` to isolate the problem to one commit? Since this PR has four commits and two different authors.

**Comment by ramrodo** [comment]
@jheimar I'll create a fork of this progress to have the PR ready to merge and continue your contribution :)

**Comment by reylejano** [comment]
Hi @jheimar , I'm closing this PR since this PR has been open for several months without signing the CLA by the author.
When you get the chance to sign the CLA, you can reopen this PR with `/reopen` in a comment
/close

**Pull request closed without merging**
