### PR TITLE
modify a misprint

### PR DESCRIPTION
**Pull request by MFullStack**
只是 -> 这是

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by xichengliudui** [comment]
Thank you for your initial contribution, but please sign the cncf-cla agreement.

**Comment by markthink** [comment]
@MFullStack 请先签署 CLA 协议，[可参考](https://github.com/k8smeetup/k8s-official-translation)

**Comment by markthink** [comment]
@MFullStack  [参考翻译文档](https://github.com/k8smeetup/k8s-official-translation)

**Pull request closed without merging**
