### PR TITLE
Merged main into dev 1.24

### PR DESCRIPTION
**Pull request by nate-double-u**
Week 10 update to bring `main` into `dev-1.24` branch.

### CODE REVIEW

**Comment by nate-double-u** [comment]
Errors:
* [8dfd425](https://github.com/kubernetes/website/pull/32305/commits/8dfd425486d9e7e8033060061c55ee126fd844ad) - easyCLA
* [4e98cfe](https://github.com/kubernetes/website/pull/32305/commits/4e98cfe32ed4d5397c30b41ef70d7f132ea6a73f)
* [2bd4fcd](https://github.com/kubernetes/website/pull/32305/commits/2bd4fcdf8ab424dac012d162669b41c2929f8f7d)
* [636cff2](https://github.com/kubernetes/website/pull/32305/commits/636cff2b55079e4614afeed5f889b898281b6cfd)

(will update with reasons shortly)

**Comment by nate-double-u** [comment]
I'm assuming that these errors are fine as the build seemed to work fine: https://deploy-preview-32305--kubernetes-io-vnext-staging.netlify.app/

**Comment by tengqm** [comment]
double checked #32277, there was no reason that PR is breaking the build. I believe it was caused by a transient netlify issue.

**Comment by nate-double-u** [comment]
Thanks for checking @tengqm!

**Pull request merged**
