### PR TITLE
Localize “email address” placeholder on home page

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/website/issues/19409

/language de

### CODE REVIEW

**Comment by sftim** [comment]
@kubernetes/sig-docs-de-owners happy to see this merged?
(I can echo your approval to make Prow happy)

**Comment by rlenferink** [comment]
@sftim can you echo to make prow happy ? :)

/unassign @xiangpengzhao
/assign @sftim

**Comment by sftim** [comment]
/approve
echoing https://github.com/kubernetes/website/pull/19410#issuecomment-596419433 and https://github.com/kubernetes/website/pull/19410#issuecomment-596420219

**Pull request merged**
