### PR TITLE
Document new API Priority and Fairness metrics

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
This PR documents the additions made in  https://github.com/kubernetes/kubernetes/pull/91177 and also brushes up the descriptions of some of the older metrics.

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
The force-push to 800a602e3 fixes a couple of speling misteaks.

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Comment by jimangel** [comment]
Would it be possible to get a technical `lgtm` from @kubernetes/sig-api-machinery-api-reviews ?

**Comment by MikeSpreitzer** [comment]
@joelbyronbarker : thanks for the review.  I have revised accordingly.

**Comment by lavalamp** [comment]
tech
/lgtm

**Comment by jimangel** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
