### PR TITLE
[zh] Remove ServiceAccount Secret automounting section

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/website/pull/26379

### CODE REVIEW

**Comment by irvifa** [comment]
/retitle [zh] Remove ServiceAccount Secret automounting section

**Review by irvifa — COMMENTED** [review]
/lgtm

**Comment by tengqm** [comment]
Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). To find out what are the upstream changes to be synced, do this:

```
./scripts/lsync.sh content/zh/docs/path/to/page.md
```

/hold

**Pull request closed without merging**
