### PR TITLE
Set feature state version for kubelet config task

### LINKED ISSUE #20692: inconsistent version, feature state for tasks/administer-cluster/kubelet-config-file
**This is a Feature Request**
The task page, 
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
refers to the feature state as reaching beta in `v1.18`, however, the text in the task
page refers to the version as `v1.10`.

**What would you like to be added**
Confirm when the feature reached beta and adjust the text on the page.

**Why is this needed**
The content is not consistent.

**Comments**
Let me know if you need help resolving this issue.

### PR DESCRIPTION
**Pull request by prasadkatti**
Fixes #20692

### CODE REVIEW

**Comment by prasadkatti** [comment]
/assign @kbhawkey 
Hi. I need help with PR title.

**Comment by kbhawkey** [comment]
How about something like:
Set feature state version for kubelet config task

**Comment by prasadkatti** [comment]
Thanks @kbhawkey. I will force push the commit with the right commit msg.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-20766--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/kubelet-config-file/

**Pull request merged**
