### PR TITLE
Add Git info to per-page template

### LINKED ISSUE #1973: Show last updated date on documentations
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
A few doc pages on kubernetes.io are relatively stale. While we are working hard to rearrange our docs structure and improving the existing docs, it would be nice to show last updated date along with the docs, which can give users a better sense of how old the docs are.

**Proposed Solution:**
Show last updated date on docs.

**Page to Update:**
http://kubernetes.io/docs/

### PR DESCRIPTION
**Pull request by mistyhacks**
Add a per-page footer element to show the last modification date and link to the commit that did it

To disable this, set a page's frontmatter variable `showcommit` to false.
Fixes #1973

/assign @chenopis 
/assign @steveperry-53

### CODE REVIEW

**Comment by mistyhacks** [comment]
This looks funny on pages with really wide TOCs like https://5b356612c6aed61270e392a3--kubernetes-io-master-staging.netlify.com/docs/imported/release/. I think maybe it is a layout problem with those pages and not with this.

**Comment by techtonik** [comment]
Can there also be a link to full page history?

**Comment by mistyhacks** [comment]
You can get to that fairly easily now (if you click the Edit button, you get a choice to view the page source instead). But I can consider it.

**Comment by mistyhacks** [comment]
@techtonik it was pretty trivial so I added it.

**Comment by zacharysarah** [comment]
I'm noticing there's no netlify preview for this PR. This may indicate a larger issue with Netlify for the repo.

**Comment by mistyhacks** [comment]
@zacharysarah There is a problem with Netlify, that it is not currently populating in the Tests section. However, Netlify is leaving a comment with a link to the preview. The problem is unrelated to this PR.

**Pull request merged**
