### PR TITLE
First draft of generated component docs.

### PR DESCRIPTION
**Pull request by steveperry-53**
This PR puts first drafts of generated snippets in place for the [kubeadm ref docs](https://deploy-preview-9007--kubernetes-io-vnext-staging.netlify.com/docs/reference/setup-tools/kubeadm/kubeadm-init/).

This PR also puts first drafts of generated ref docs in place for these commands:

* cloud-controller-manager
* kube-apiserver
* [kube-controller-manager](https://deploy-preview-9007--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/kube-controller-manager/)
* kubelet
* kube-proxy
* kube-scheduler
* kubectl
* [federation-apiserver](https://deploy-preview-9007--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/federation-apiserver/)
* federation-controller-manager
* [kubefed_init](https://deploy-preview-9007--kubernetes-io-vnext-staging.netlify.com/docs/reference/setup-tools/kubefed/kubefed-init/)
* kubefed_join
* kubefed
* kubefed_options
* kubefed_unjoin
* kubefed_version

These generated docs and snippets do not have the nicely formatted tables that @tengqm has been working on.

@tengqm, As you get the more nicely formatted version of these generated docs ready, please replace the docs and snippets that I am submitting here.

### CODE REVIEW

**Comment by steveperry-53** [comment]
There's a problem with tables rendering as HTML. I'm working on that now.
Example: [kube-apiserver](https://deploy-preview-9007--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/kube-apiserver/)

**Comment by Bradamant3** [comment]
/hold

(put hold on to help me track -- feel free to remove when tables issue is fixed.)

Nice to have: remove TOC at the top. Not sure whether we'd write a separate script to update the front matter for the files, or adjust the script that generates in the first place. I'm guessing the first, but I still have a lot to learn about how this whole process works.

**Comment by steveperry-53** [comment]
I can't get the generation code at kubernetes/website/update-imported-docs to work. I've tried the current version, and I've tried the original version from a previous commit. In all cases, something goes wrong during the phase where files are copied from kubernetes/kubernetes/docs to kubernetes/website/.

The generated files are fine in kubernetes/kubernetes/docs. But after they are copied to kubernetes/website, they have extraneous html table elements.

Closing this PR, because there's no point in keeping it open.

**Pull request closed without merging**
