### PR TITLE
Added secret keyword to kubectl-command.html file

### PR DESCRIPTION
**Pull request by nitishfy**
Fix: #35577

### CODE REVIEW

**Comment by able8** [comment]
Hi, why you re-open this PR, i can see the old PR https://github.com/kubernetes/website/pull/35586

See the previout comments: 
https://github.com/kubernetes/website/pull/35586#issuecomment-1200367839
    This file (website/static/docs/reference/generated/kubectl/kubectl-commands.html) is auto-generated, please don't fix it here.

https://github.com/kubernetes/website/pull/35586#issuecomment-1200369137
    FWIW, the upstream source code is here:
    https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/create/create_secret_tls.go#L93

**Comment by Ritikaa96** [comment]
Hi @nitishfy , Are you still working on this PR? '
If yes , then I'll suggest you to first make change  [here](https://github.com/kubernetes/kubernetes/blob/f9f00da6bcc04559b44e0d6e127cb4b0c00b0370/staging/src/k8s.io/kubectl/pkg/cmd/create/create_secret_tls.go#L92C1-L92C1)

Then after the PR is merged you can raise for a change in website, Please note that this file is auto-generated , so on sync up even if you change it here without change in source file the text will be reverted back.

**Comment by Ritikaa96** [comment]
Please raise the pr request for change in source file in kubernetes/kubernetes .
Also confirm here if you are still working on this Issue.

**Comment by tengqm** [comment]
/lgtm
/approve
as a workaround.

**Pull request merged**
