### PR TITLE
fix the Chinese single quotes in the code to English single quotes

### PR DESCRIPTION
**Pull request by giiiiiithub**
fix the Chinese single quotes in the code to English single quotes

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @giiiiiithub, please only include a single language (such as english) in a single PR, and leave other languages for localization teams.

**Comment by giiiiiithub** [comment]
> Hi @giiiiiithub, please only include a single language (such as english) in a single PR, and leave other languages for localization teams.

done, this pr only include zh-cn

**Comment by windsonsea** [comment]
/hold

Need to wait for #44447 merged

**Comment by windsonsea** [comment]
After checking [history](https://github.com/kubernetes/website/commits/main/content/zh-cn/docs/tasks/configure-pod-container/configure-pod-configmap.md), this change is good, no more in-synced content.

/approve
/lgtm

**Pull request merged**
