### PR TITLE
Lossless image optimization

### PR DESCRIPTION
**Pull request by sftim**
Run `optipng -o7` across (subsets of) website PNG images to make **lossless** savings in image sizes.

Similar to the intent of PR #18971; this one comes with a signed CLA and a merge-able set of commits.

Aside: :bulb: if anyone ever wants to, we could lint to check that (modified) images are within _n_% of being optimized.

### CODE REVIEW

**Comment by sftim** [comment]
`size/XS` huh? :smile:

**Comment by sftim** [comment]
/remove-area blog
Some blog changes snuck in when I didn't want them to.
(I hope this is correct and possible)

**Comment by neolit123** [comment]
in nowadays bandwidths of 100s of megabits, these types of optimizations stripping a few kilogbytes may be quite negligible. i think the overall reduction here is near 500kb or less.

but if this was already discussed already it seems fine.

**Comment by sftim** [comment]
It's not going to make much different to page load time. OTOH it didn't take long to PR this either.

**Comment by kbhawkey** [comment]
@sftim , Are these changes the same as PR #18971? Or, possibly generated using a different tool?

**Comment by sftim** [comment]
Roughly the same aim but a different tool.

**Comment by kbhawkey** [comment]
@sftim, I would think that this type of change should be agreed upon by the docs group (discussed  during docs weekly meeting or mentioned in docs agenda)?
/hold

**Comment by sftim** [comment]
Happy to see this discussed.

**Comment by sftim** [comment]
For now I'll close this. Easy enough to reopen.
/close

**Pull request closed without merging**
