### PR TITLE
fixing the huge whitespace in sidebar

### LINKED ISSUE #29001: huge whitespace in sidebar menus
**This is a Bug Report**

**Problem:**
I saw by accident very big page files on Kubernetes documentation.
For example https://kubernetes.io/docs/tasks/ is 21850 lines long and the lines 286-20056 are taken for the sidebar menu containing a lot of whitespace (do right-mouse and "view page source").

**Proposed Solution:**
I reported the issue already with Docsy: https://github.com/google/docsy/issues/637 and proposed a pull request.
But this will not be enough. Somebody has to update https://github.com/kubernetes/website/blob/main/layouts/partials/sidebar-tree.html too.

**Page to Update:**
https://github.com/kubernetes/website/blob/main/layouts/partials/sidebar-tree.html

### PR DESCRIPTION
**Pull request by niteshseram**
This reduces quite a lot of whitespace from the sidebar.
Closes #29001

### CODE REVIEW

**Comment by jimangel** [comment]
Thanks for the PR @niteshseram, I'm struggling to see the difference between https://kubernetes.io/docs/tasks/ and https://deploy-preview-29006--kubernetes-io-main-staging.netlify.app/docs/tasks/

Can you link or describe a better example or test for review?

**Comment by niteshseram** [comment]
> Thanks for the PR @niteshseram, I'm struggling to see the difference between https://kubernetes.io/docs/tasks/ and https://deploy-preview-29006--kubernetes-io-main-staging.netlify.app/docs/tasks/
> 
> Can you link or describe a better example or test for review?

Hi @jimangel, There is no difference in content as such. But as said in the issue #29001, when you go to this page https://kubernetes.io/docs/tasks/ and right click and click on view page source. You will see a 21850 lines long and the lines 286-20056 are taken for the sidebar menu containing a lot of whitespace. This PR removes those huge empty spaces.

**Pull request merged**
