### PR TITLE
Line separation is needed in reference/kubectl/overview

### LINKED ISSUE #30357: Line separation is needed in `reference/kubectl/overview`
**This is a Bug Report**

**Problem:**
Line separation is needed in [`reference/kubectl/overview`](https://kubernetes.io/docs/reference/kubectl/overview/#in-cluster-authentication-and-namespace-overrides)

[Markdown]
```Markdown
If:
* there is Kubernetes service account token file mounted at
  `/var/run/secrets/kubernetes.io/serviceaccount/token`, and
* the `KUBERNETES_SERVICE_HOST` environment variable is set, and
* the `KUBERNETES_SERVICE_PORT` environment variable is set, and
* you don't explicitly specify a namespace on the kubectl command line
then kubectl assumes it is running in your cluster. The kubectl tool looks up the
namespace of that ServiceAccount (this is the same as the namespace of the Pod)
and acts against that namespace. This is different from what happens outside of a
cluster; when kubectl runs outside a cluster and you don't specify a namespace,
the kubectl command acts against the `default` namespace.
```

[Rendered]
image

**Proposed Solution:**
```diff
If:
* there is Kubernetes service account token file mounted at
  `/var/run/secrets/kubernetes.io/serviceaccount/token`, and
* the `KUBERNETES_SERVICE_HOST` environment variable is set, and
* the `KUBERNETES_SERVICE_PORT` environment variable is set, and
* you don't explicitly specify a namespace on the kubectl command line
+          
then kubectl assumes it is running in your cluster. The kubectl tool looks up the
namespace of that ServiceAccount (this is the same as the namespace of the Pod)
and acts against that namespace. This is different from what happens outside of a
cluster; when kubectl runs outside a cluster and you don't specify a namespace,
the kubectl command acts against the `default` namespace.
```

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/overview/#in-cluster-authentication-and-namespace-overrides

/kind cleanup
/language en
/good-first-issue

### PR DESCRIPTION
**Pull request by igwejk**
This fix improves the content formatting by separating bullet point list from a block of remarks that are related to ALL the points in the list.

### CODE REVIEW

**Comment by tengqm** [comment]
@igwejk Looks like the commit message 'Fixes kubernetes#30357' in your commit (to your fork) needs to be revised, as suggested by the bot.

**Review by RinkiyaKeDad — COMMENTED** [review]
LGTM too, friendly ping to fix the commit message so we can merge this :)

**Comment by igwejk** [comment]
Fixed the commit message @tengqm @RinkiyaKeDad

**Comment by jihoon-seo** [comment]
- This PR resolves #30357
- This PR is similar with the PR #30359
- This PR is similar with the PR #30551

**Comment by divya-mohan0209** [comment]
Thank you for your efforts! Hello @igwejk , this has now been fixed by [this PR](https://github.com/kubernetes/website/pull/30359). A good way to ensure there's no duplication of efforts is to assign the issue to yourself or ask the person who has raised the issue to assign it to you.
I will now be closing the PR to avoid redundancy.

**Pull request closed without merging**
