### PR TITLE
Merge master into dev-1.20 to keep in sync

### PR DESCRIPTION
**Pull request by reylejano-rxm**
Merge master into dev-1.20 to keep in sync - SIG-Release 1.20 Docs team 10/14/20

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @reylejano-rxm .
I'd expect to see a sync up from master into `dev-1.20`?

**Comment by reylejano-rxm** [comment]
> Hi @reylejano-rxm .
> I'd expect to see a sync up from master into `dev-1.20`?

@kbhawkey Yes, you're right. I will close this and make the PR to the `dev-1.20` branch

**Review by sftim — COMMENTED** [review]
(informally) looks good to me

**Review by irvifa — COMMENTED** [review]
Thanks!!
/lgtm
/approve

**Pull request merged**
