### PR TITLE
Change the backgrounds of “Case studies” logos from gray to transparent

### LINKED ISSUE #16772: “Case studies” logos clash with page's gray background
**This is a Bug Report**

**Problem:**
The logos on https://kubernetes.io/case-studies/ have gray backgrounds. Depending on your user agent and how it handles sRGB / color spaces, that might not be the same gray as the page background.

**Proposed Solution:**
~Recreate these logos using PNG format and a transparency (alpha) channel.~
One of:
- Use an image for the page background, so that the images don't match
- Migrate to use SVG logos

**Page to Update:**
https://kubernetes.io/case-studies/

**Additional Information:**
Also potentially relevant: https://css-tricks.com/color-rendering-difference-firefox-vs-safari/

/kind cleanup

### PR DESCRIPTION
**Pull request by shuuji3**
Resolves #16772.

Page preview: https://deploy-preview-27501--kubernetes-io-master-staging.netlify.app/case-studies/

You can compare to the current page: https://kubernetes.io/case-studies/

### CODE REVIEW

**Comment by sftim** [comment]
Much better!
/area web-development
/lgtm
/approve

**Comment by shuuji3** [comment]
Thank you!

**Pull request merged**
