### PR TITLE
Minor fixes in container runtime install and kubeadm install instructions

### PR DESCRIPTION
**Pull request by naeem98**
- All changes require privileged access (sudo) to run
- Install instructions have been tested on Ubuntu ditro

### CODE REVIEW

**Comment by bart0sh** [comment]
This documentation already mentions that root privileges are required:
```
You should execute all the commands in this guide as root. For example, prefix commands with sudo, or become root and run the commands as that user.
```

**Comment by bart0sh** [comment]
Changing only instructions for one runtime would make this confusion from my point of view.

**Comment by naeem98** [comment]
In my experience and I think most of the users just copy and paste the commands and try to run them. 
The commands on all other pages like install kubeadm etc. have sudo included with them so I think it will be better to include sudo in container run time commands as well to be in sync with other pages.

**Comment by naeem98** [comment]
I agree that updating only one container runtime might create confusion. 
I will update the other container runtimes as well.

**Comment by naeem98** [comment]
Updated the PR for all runtimes. Please review.

**Comment by naeem98** [comment]
@bart0sh In the container runtime doc, these are the places that are already including sudo with the commands. Hope this PR will help sync all the commands in this doc 

https://github.com/kubernetes/website/pull/20869/files#diff-3bd86cac4141e310827931cf9674f406L190

https://github.com/kubernetes/website/pull/20869/files#diff-3bd86cac4141e310827931cf9674f406L194

https://github.com/kubernetes/website/pull/20869/files#diff-3bd86cac4141e310827931cf9674f406L202

https://github.com/kubernetes/website/pull/20869/files#diff-3bd86cac4141e310827931cf9674f406L205

https://github.com/kubernetes/website/pull/20869/files#diff-3bd86cac4141e310827931cf9674f406L211-L213

https://github.com/kubernetes/website/pull/20869/files#diff-3bd86cac4141e310827931cf9674f406L216

https://github.com/kubernetes/website/pull/20869/files#diff-3bd86cac4141e310827931cf9674f406L229

**Comment by tengqm** [comment]
@naeem98 pls resolve the conflicts so we can merge this.

**Comment by naeem98** [comment]
> @naeem98 pls resolve the conflicts so we can merge this.

Conflicts resolved.

**Comment by tengqm** [comment]
@naeem98 pls squash your commits as well.

**Comment by naeem98** [comment]
@tengqm I have created a clean PR and it has more changes as well. Please review.
https://github.com/kubernetes/website/pull/21897

**Comment by tengqm** [comment]
@naeem98 So ... you are closing this one in preference of #21897?

**Comment by naeem98** [comment]
@tengqm yes I am going to close this one.

**Pull request closed without merging**
