### PR TITLE
Added training course from Alta3 Research

### PR DESCRIPTION
**Pull request by hilaryfryer**

### CODE REVIEW

**Comment by hilaryfryer** [comment]
I signed it

**Comment by zacharysarah** [comment]
@hilaryfryer Thanks for the PR. Please note that we don’t accept links to third-party content outside the Setup page. For more information, see https://github.com/kubernetes/enhancements/pull/1327.

/close

**Comment by bryfry** [comment]
@zacharysarah I don't understand.  The [Overview of Kubernetes Online Training](https://github.com/kubernetes/website/blob/master/content/en/docs/tutorials/online-training/overview.md) page is entirely composed of links to third-party content.

Please help me understand how this PR is different than any of the previous commits which have added links to third-party content.  Thanks!

**Comment by zacharysarah** [comment]
@bryfry See #19500.

**Pull request closed without merging**
