### PR TITLE
Update what-is-kubernetes.md

### PR DESCRIPTION
**Pull request by pelligrag**
minor changes

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For Chinese localization, base branch to release-1.14
>
> For Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by rlenferink** [comment]
Hi @pelligrag thanks for your contribution! Before we can have a look, can you sign the CNCF CLA? Instructions on how to do that are described [here](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement)

After that, @micheleberardi can you have a look at this PR?

**Comment by rlenferink** [comment]
Thanks @micheleberardi!

@pelligrag before we are able to merge this, you need to sign the CNCF CLA following the instructions above. After that, I'll `/approve` this PR :)

**Comment by rlenferink** [comment]
@pelligrag were you able to follow the steps for signing the CNCF CLA?

**Comment by tengqm** [comment]
@pelligrag I'm closing this PR because the CLA status check has not been resolved for over a month. Please

- feel free to reopen this if you are still working on it, and
- try follow instructions [here](https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting) to debug your CLA status if you have already signed it.

**Pull request closed without merging**
