### PR TITLE
Replace {{< codenew ... >}} with {{% codenew ... %}} in all English docs

### PR DESCRIPTION
**Pull request by andreygoran**
#### Description

This PR fixes the problem with Copy To Clipboard function breaking YAML format under some conditions, and closes https://github.com/kubernetes/website/issues/42179

The proposed solution is to replace all  `{{< codenew ... >}}` code with `{{% codenew ... %}}` in all files.
The result of this change is that parent indentation does not propagate into the resulting HTML code, and YAML code is not altered.

#### Details

99% of this PR was completed by Find And Replace using a regex.
The remaining 1% was manually fixing places where regex did not apply, either because of inconsistencies in code formatting or because `codenew` was part of text. Full list of pages where manual fixes were needed:
* docs/contribute/style/hugo-shortcodes/
* docs/contribute/style/write-new-topic/
* docs/tasks/access-application-cluster/ingress-minikube/
* docs/tasks/manage-daemon/pods-some-nodes/
* docs/test/
* fr/docs/concepts/cluster-administration/logging/
* fr/docs/contribute/style/write-new-topic/
* fr/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
* ko/docs/contribute/style/write-new-topic/
* ru/docs/contribute/style/write-new-topic/
* zh-cn/docs/contribute/style/write-new-topic/
* zh-cn/docs/contribute/style/hugo-shortcodes/
* zh-cn/docs/tasks/manage-daemon/pods-some-nodes/
* zh-cn/docs/test/

#### Fixed bugs

https://github.com/kubernetes/website/issues/42179

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@andreygoran Thank you for your contribution!
 It appears that this PR includes changes to files across multiple languages _(de, es, fr ... etc_). However, the docs team follows distinct processes for each localization, and we usually prefer not to merge pull requests that affect multiple languages at once. The recommendation would be to concentrate on modifying the primary website content  (which means only English content) initially with this PR. Once the English content is successfully merged, we can proceed to create separate pull requests for the remaining languages.

**Comment by tengqm** [comment]
This solution is neat.
Please remove localizations other than English from the PR.

**Comment by andreygoran** [comment]
@dipesh-rawat, @tengqm 

> Please remove localizations other than English from the PR.

Done

**Comment by tengqm** [comment]
Please squash your PR into a single commit?

**Comment by andreygoran** [comment]
> Please squash your PR into a single commit?

I messed up and merged my repo instead of doing interactive rebase first. Not sure if this can be fixed now without messing up even more :) Do you want me to add another PR or it's fine as is?

**Comment by sftim** [comment]
/retitle Replace {{< codenew ... >}} with {{% codenew ... %}} in all English docs

**Review by sftim — COMMENTED** [review]
Great. Thanks.

/lgtm

**Comment by andreygoran** [comment]
> 



> We have ~magic~ technology.

Magic indeed! Thank you!

**Pull request merged**
