### PR TITLE
Moved “Resource Bin Packing” into Scheduling & Eviction section

### PR DESCRIPTION
**Pull request by c-mcdonnell**
Moved resource-bin-packaging into scheduling-eviction by renaming the path from: content/en/docs/concepts/configuration/resource-bin-packing.md to content/en/docs/concepts/scheduling-eviction/resource-bin-packing.md

Updated [static/_redirects ](https://github.com/kubernetes/website/blob/master/static/_redirects)

Responding to issue #22534

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
@c-mcdonnell this is nice.

We should also redirect from the old path to the new one, at least for the English localization (other localization teams will pick this up later on their own schedule).

You can add those changes to [`static/_redirects`](https://github.com/kubernetes/website/blob/master/static/_redirects), and I recommend that you do. The existing redirects in that file should let you work out how to add another one - if you'd like advice, though, reply to this PR and someone will help.

/sig scheduling

**Comment by sftim** [comment]
All pull requests are currently frozen until Kubernetes v1.19 is released (should be quite soon!)

**Comment by zacharysarah** [comment]
Holding for the author to add changes from #23380. 

/hold

**Comment by sftim** [comment]
Hi @c-mcdonnell 

Would you be willing to incorporate the changes from PR #23380 into this one?

**Comment by c-mcdonnell** [comment]
@sftim I made the changes from both commits in the master branch of my forked repo and deleted the branches patch-1 and patch-2, hoping I could update this PR with my master branch. However, by deleting those branches, I seem to have closed the PR. How should I proceed?

**Comment by irvifa** [comment]
Seems like the changes is somehow deleted any suggestions @sftim

**Comment by sftim** [comment]
We could move forward with PR https://github.com/kubernetes/website/pull/24232 if that seems like a valid approach?

**Pull request closed without merging**
