### PR TITLE
remove "recommended" from Minikube description

### PR DESCRIPTION
**Pull request by sfabel**
Now that there are multiple predictable and stable upstream solutions to deploy Kubernetes, we should not express an opinion as to which one to recommend without also mentioning the reasons for it.

### CODE REVIEW

**Comment by cody-clark** [comment]
Hi, @sfabel, thanks for pointing that out! I added an apposition to better describe Minikube's relationship with Kubernetes. Could you also alphabetize the local solutions to make the list more neutral?

@zacharysarah is there anything your want to add (or subtract)?

**Comment by zacharysarah** [comment]
@sfabel Thanks for this change; I agree on its importance. 👍 

@cody-clark Great choice for neutral language! ✨ 

/lgtm
/approve

**Comment by zacharysarah** [comment]
@cody-clark If this looks good to you, please go ahead and dismiss your review.

**Pull request merged**
