### PR TITLE
Update nodes.md

### PR DESCRIPTION
**Pull request by nbouron**
Link "services" updated in "Management" section

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7353)

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/lgtm
Thanks!

**Comment by xiangpengzhao** [comment]
@nbouron please sign your CLA :)

**Comment by nbouron** [comment]
@xiangpengzhao I have already sign in, i don't understand, my email is the same, and github is registred in "Social network logins"

**Pull request merged**
