### PR TITLE
feat: add print directive allows print sections.

### PR DESCRIPTION
**Pull request by Colstuwjx**
This PR addresses #26808, and it's a follow-up PR after  #26814 get merged!

### CODE REVIEW

**Comment by Colstuwjx** [comment]
In this PR, which is different from PR #26809, I don't change the layout anymore, just add a `print entire section` at the right bar:

image

/cc @kbhawkey @sftim @jimangel

**Comment by Colstuwjx** [comment]
@kbhawkey Any suggestions?

**Comment by kbhawkey** [comment]
Preview page (print):
https://deploy-preview-26926--kubernetes-io-master-staging.netlify.app/docs/concepts/overview/_print/

**Comment by kbhawkey** [comment]
👋 @Colstuwjx .
The change looks good.
/approve

**Pull request merged**
