### PR TITLE
Fix Wrong footer rendering #31509

### LINKED ISSUE #31509: Wrong footer rendering
**This is a Bug Report**

**Problem:**
(Despite the PR #31277 has been merged, it seems that the error still exists. 🤔
So opening an issue here. 😊)

From the PR #31277:

> The [community page](https://kubernetes.io/community/) has the wrong rendering for the page footer.
> We should:
> - ensure that the footer is as wide as the viewport.
> - improve how the text in the footer is laid out when the viewport is quite wide.

[As-is]
image
image

[To-be]
image
image

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/community/

CC @sftim
/area web-development

### PR DESCRIPTION
**Pull request by ravikiranr26**
Changes to fix the footer wrong rendering on different screen resolutions.

fixes #31509

I have tested this on browser stack after the fix and seems ok. Please test before merging once.
image

/sig ui
/kind bug

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@ravikiranr26 Welcome and thank you for your first PR on this repo! 😊

Preview: https://deploy-preview-31547--kubernetes-io-main-staging.netlify.app/community/

image
image

CC @sftim 
/lgtm

To everyone: We need to check once again after this PR gets merged. 😊

**Review by Arhell — COMMENTED** [review]
remove width: 100vw;
and float: left !important;

no other changes needed

**Review by Arhell — COMMENTED** [review]
@ravikiranr26  thanks
/lgtm
/label tide/merge-method-squash

**Comment by ravikiranr26** [comment]
> remove width: 100vw; and float: left !important;
> 
> no other changes needed

Hello @Arhell Thanks for review, I had already removed the float: left: in my First PR which was causing the issue. 
Now in the latest PR have removed width: 100vw which would have set the width based on the viewport regardless of screen resolution but otherwise also works fine.

**Comment by sftim** [comment]
Hi @ravikiranr26 

Please would you [squash commits](https://www.kubernetes.dev/docs/guide/github-workflow/#squash-commits) for this PR - there's more advice in https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits - and pick a message that's valid. You must not mention issues and pull requests in commit messages.

Once you've done that, we should be able to approve the change.

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/31547#issuecomment-1024869373 explains a bit more about why this PR isn't acceptable.

**Comment by ravikiranr26** [comment]
@sftim Hello, I have some issues doing a rebase, can i send in a new PR ?

**Comment by sftim** [comment]
It's fine to open a new PR and close this one @ravikiranr26

**Pull request closed without merging**
