### PR TITLE
[ko] fixed the controller pod deletion cost link to korean

### PR DESCRIPTION
**Pull request by imoisharma**
Signed-off-by: Mohit Sharma <imoisharma@icloud.com>

I noticed, one user, raise an issue regarding the wrong navigation of the controller pod deletion cost documentation. 

The issue can be found here: https://github.com/kubernetes/website/issues/29852
I have already tested the navigation is now pointing to the right doc. Please look at this PR, and merge it to the `main`/`master` branch.

Best Regards
Mohit Sharma

### CODE REVIEW

**Comment by ClaudiaJKang** [comment]
@imoisharma Thank you for your contribution! 
Could you change the target branch `main` to `dev-1.22-ko.1`? 
Korean Team's working branch is `dev-1.22-ko.1`!

**Comment by imoisharma** [comment]
Hi @ClaudiaJKang, I have updated the target branch. Cheers.

**Comment by ClaudiaJKang** [comment]
Hi @imoisharma ! Thank you for your immediate action.
But I think you should change the base branch `main` -> `dev-1.22-ko.1` because this PR includes commits unrelated to #29852.

**Comment by imoisharma** [comment]
Hi @ClaudiaJKang, sorry but I am clear with your above comment. I already update the `main` -> `dev-1.22-ko.1` for the base branch. Please provide me with some information on this. Thanks

**Comment by ClaudiaJKang** [comment]
@imoisharma Thank you! I will check.

**Pull request closed without merging**
