### PR TITLE
move kubeadm to /docs/reference/generated directory

### PR DESCRIPTION
**Pull request by wackxu**
move kubeadm to /docs/reference/generated directory

/assign @steveperry-53

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6326)

### CODE REVIEW

**Comment by wackxu** [comment]
@steveperry-53 Also this one is related to kubefed that has been moved.PTAL

**Comment by steveperry-53** [comment]
@wackxu LGTM. I'll merge after you resolve the merge conflict.

**Comment by wackxu** [comment]
@steveperry-53 Done, PTAL

**Comment by xiangpengzhao** [comment]
@wackxu any discussion on moving this? I didn't find the reason why we want do this :)

**Comment by wackxu** [comment]
@xiangpengzhao  https://github.com/kubernetes/website/issues/6037

**Comment by xiangpengzhao** [comment]
@wackxu thanks for clarifying! SGTM.

**Pull request merged**
