### PR TITLE
Fix the raw HTML code being displayed on the website

### PR DESCRIPTION
**Pull request by ThePrincelle**
The HTML code was not processed and therefore was [displayed on the website in raw HTML](https://kubernetes.io/fr/docs/reference/kubectl/kubectl/).

The page concerned is the one about the [`kubectl`command](https://kubernetes.io/fr/docs/reference/kubectl/kubectl/).

### CODE REVIEW

**Comment by ThePrincelle** [comment]
Netlify has finished building the preview website. 

Here's the page concerned : 
https://deploy-preview-25231--kubernetes-io-master-staging.netlify.app/fr/docs/reference/kubectl/kubectl/

**Comment by feloy** [comment]
Thanks @ThePrincelle for this fix 👍

**Pull request merged**
