### PR TITLE
Clean up case study images in content/ja/case-studies

### PR DESCRIPTION
**Pull request by habibrosyad**
Fix broken images in case study pages, part of #22086 as a follow up from #22636 for JA.

xref #23708 

/kind cleanup
/area web-development

### CODE REVIEW

**Comment by habibrosyad** [comment]
Preview:
- https://deploy-preview-24400--kubernetes-io-master-staging.netlify.app/ja/case-studies/appdirect
- https://deploy-preview-24400--kubernetes-io-master-staging.netlify.app/ja/case-studies/chinaunicom
- https://deploy-preview-24400--kubernetes-io-master-staging.netlify.app/ja/case-studies/nav
- https://deploy-preview-24400--kubernetes-io-master-staging.netlify.app/ja/case-studies/nordstrom
- https://deploy-preview-24400--kubernetes-io-master-staging.netlify.app/ja/case-studies/sos
- https://deploy-preview-24400--kubernetes-io-master-staging.netlify.app/ja/case-studies/spotify

**Comment by bells17** [comment]
Thank you for fixing image paths!

/lgtm

**Pull request merged**
