### PR TITLE
Tweaks to write K8s as proper noun

### PR DESCRIPTION
**Pull request by sftim**
I saw #12969 and wondered if the same change applied elsewhere. Here's where I think it does.

### CODE REVIEW

**Comment by DanyC97** [comment]
@sftim looks good to me, although my vote doesn't help (for now) moving this PR ;)

**Comment by zacharysarah** [comment]
@sftim Nice, thanks!

/lgtm
/approve

**Comment by zacharysarah** [comment]
@DanyC97 Are you not an org member yet? If you [want to join](https://github.com/kubernetes/org/issues/new/choose), I'll sponsor you. You'll need to get another member to co-sponsor, but you can link your [PR record](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Adanyc97+is%3Aclosed) to [#sig-docs](https://kubernetes.slack.com/messages/C1J0BPD2M/details/) and ask for one.

**Pull request merged**
