### PR TITLE
Removed Big Switch Fabric

### PR DESCRIPTION
**Pull request by ixodie**
The links for this entry are broken.

### CODE REVIEW

**Comment by geoffcline** [comment]
removing this content (cloud provider specific) seems fine to me. 

/lgtm

**Comment by reylejano** [comment]
Confirmed links for BigSwitch no longer works, BigSwitch was acquired by Arista networks
/lgtm

**Review by sftim — COMMENTED** [review]
Those links look broken to me.

/lgtm
Thanks @ixodie

**Pull request merged**
