### PR TITLE
[pt-br] add docs/tasks/access-application-cluster/web-ui-dashboard

### PR DESCRIPTION
**Pull request by EuricoAbreu**
Hi everyone,

I opened this PR to fix the requested changes on an old PR closed due inactivity.

PR for reference: #30181

### CODE REVIEW

**Comment by MrErlison** [comment]
/retitle [pt-br] add docs/tasks/access-application-cluster/web-ui-dashboard

**Comment by devlware** [comment]
@EuricoAbreu thanks for helping the project.
Can you please translate the word dashboard to painel? Painel Web do Kubernetes and variants like this will be welcome to portuguese readers.

**Comment by divya-mohan0209** [comment]
Hello @EuricoAbreu @devlware : Please note that this PR has been open for ~5 months with no activity & will be closed off per our guidelines around inactive PRs. Whenever you have the bandwidth to resume work on the PR, please consider reopening the PR with a /reopen command instead of opening a new one.
/close

**Pull request closed without merging**
