### PR TITLE
Improve visibility for tutorial diagrams through color change

### PR DESCRIPTION
**Pull request by PranitRout07**
Solves issue #43711

**SCREENSHOT OF DIAGRAM BEFORE UPDATE**

Screenshot 2023-10-27 152210

**SCREENSHOT OF DIAGRAM AFTER UPDATE**
Screenshot 2023-10-28 161709

### CODE REVIEW

**Comment by windsonsea** [comment]
The diagram contrast looks better.

/lgtm

Our [diagram style](https://kubernetes.io/docs/contribute/style/diagram-guide/) has no this kind of color (yellow or orange) spec yet.

**Comment by PranitRout07** [comment]
Hi @windsonsea color used is almost similar to yellow and orange , so that's why i mentioned changing yellow color to orange color. :)

**Review by aj11anuj — APPROVED** [review]
Looks good to me too, 👍

**Comment by PranitRout07** [comment]
Hey @aj11anuj  i have used this color #F29202 .

**Comment by sftim** [comment]
/retitle Improve visibility for tutorial diagram through color change

I'm changing the title because what we pick ends up in the commit history.

**Comment by sftim** [comment]
> Is there any way to add a colour to style guide? As this one looks good to me for diagrams. 👍

The page to update: https://kubernetes.io/docs/contribute/style/diagram-guide/

**Review by sftim — APPROVED** [review]
/approve

**Pull request merged**
