### PR TITLE
Correcting invalid links

### PR DESCRIPTION
**Pull request by yuxiaobo96**
ref: #17649

### CODE REVIEW

**Comment by onlydole** [comment]
Hello @yuxiaobo96, thank you for your contribution! Can I get your help in modifying only the portions of the page that need updates? Right now it's hard to review as most of the document has been changed.

**Comment by yuxiaobo96** [comment]
@onlydole 
Thank you for your advice, I have updated it.

**Comment by onlydole** [comment]
Thank you, @yuxiaobo96! 
/lgtm
/assign @mrbobbytables

**Comment by mrbobbytables** [comment]
/approve

Thanks!

**Pull request merged**
