### PR TITLE
Merged main dev 1.30

### PR DESCRIPTION
**Pull request by chanieljdan**
This PR syncs the dev-1.30 branch with the main branch to keep the dev-1.30 branch up to date.

cc: @drewhagen @Princesso @chanieljdan @fsmunoz

### CODE REVIEW

**Comment by chanieljdan** [comment]
The merge conflict which was resolved, ptal:

```
diff --cc content/en/docs/concepts/workloads/pods/sidecar-containers.md
index 76eca5cf59,0ad25781ff..0000000000
--- a/content/en/docs/concepts/workloads/pods/sidecar-containers.md
+++ b/content/en/docs/concepts/workloads/pods/sidecar-containers.md
@@@ -9,43 -9,21 +9,53 @@@ weight: 5
  
  Sidecar containers are the secondary containers that run along with the main
  application container within the same {{< glossary_tooltip text="Pod" term_id="pod" >}}.
 -These containers are used to enhance or to extend the functionality of the main application
 -container by providing additional services, or functionality such as logging, monitoring,
 +These containers are used to enhance or to extend the functionality of the primary _app
 +container_ by providing additional services, or functionality such as logging, monitoring,
  security, or data synchronization, without directly altering the primary application code.
  
 +Typically, you only have one app container in a Pod. For example, if you have a web
 +application that requires a local webserver, the local webserver is a sidecar and the
 +web application itself is the app container.
 +
  <!-- body -->
  
 -## Enabling sidecar containers
 +## Sidecar containers in Kubernetes {#pod-sidecar-containers}
 +
++<<<<<<< HEAD
 +Kubernetes implements sidecar containers as a special case of
 +[init containers](/docs/concepts/workloads/pods/init-containers/); sidecar containers remain
 +running after Pod startup. This document uses the term _regular init containers_ to clearly
 +refer to containers that only run during Pod startup.
 +
 +Provided that your cluster has the `SidecarContainers`
 +[feature gate](/docs/reference/command-line-tools-reference/feature-gates/) enabled
 +(the feature is active by default since Kubernetes v1.29), you can specify a `restartPolicy`
 +for containers listed in a Pod's `initContainers` field.
 +These restartable _sidecar_ containers are independent from other init containers and from
 +the main application container(s) within the same pod.
 +These can be started, stopped, or restarted without effecting the main application container
 +and other init containers.
 +
 +You can also run a Pod with multiple containers that are not marked as init or sidecar
 +containers. This is appropriate if the containers within the Pod are required for the
 +Pod to work overall, but you don't need to control which containers start or stop first.
 +You could also do this if you need to support older versions of Kubernetes that don't
 +support a container-level `restartPolicy` field.
 +
```

I accepted the changes in the current branch (HEAD) rather than the incoming changes (upstream/main).

**Comment by drewhagen** [comment]
/lgtm

@sftim I was told you were involved with these changes so I wanted to tag and ask if this resolution looks good to you.

**Comment by sftim** [comment]
> @sftim I was told you were involved with these changes so I wanted to tag and ask if this resolution looks good to you.

No need for me to check as https://github.com/kubernetes/website/pull/45195 is not yet approved / merged.

**Review by Princesso — COMMENTED** [review]
/lgtm

**Review by divya-mohan0209 — COMMENTED** [review]
Should be fine!

Thanks
/approve

**Pull request merged**
