### PR TITLE
[en] fix spelling error in system-trace.md 

### PR DESCRIPTION
**Pull request by having-dlrow**
fix https://github.com/kubernetes/website/issues/37249

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
This change should target the _main_ branch.

If you fix that, we can accept it @having-dlrow 

/hold
pending that change

It's even better if you review the whole page against our [style guide](https://kubernetes.io/docs/contribute/style/style-guide/).

**Comment by having-dlrow** [comment]
@sftim  I'm late to check because my vacation is getting longer. Thank you for letting me know.
I changed it to the main branch.

**Comment by sftim** [comment]
However, these changes would break _main_ and we shouldn't merge them. Could you adapt this PR so that it only makes the fix you intended @having-dlrow?

/hold

OK to unhold once the PR is corrected.

**Comment by having-dlrow** [comment]
@sftim Thank you for letting me know.
I checked changed file against the main branch.

**Pull request merged**
