### PR TITLE
Added More Base64 Online Tool

### PR DESCRIPTION
**Pull request by rahulkumarsingh73690**
I noticed this https://www.base64encode.org/ Tool is not working in the safari browser, So I added alternative tool that I found is working on safari and another browser.

Please Check Link that I added :)

Thanks

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

Please follow instructions at https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting to resolve the issues that you face in signing the CLA.

**Comment by rahulkumarsingh73690** [comment]
Already Signed

**Comment by rahulkumarsingh73690** [comment]
> it's a good point and it looks like a good addition

Then what are you waiting for Approve this PR :)

**Comment by mhamdisemah** [comment]
I can’t approve it but already i added lgtm label , you should wait for an approver

**Comment by rahulkumarsingh73690** [comment]
@Rajakavitha1  Review this PR

**Comment by sftim** [comment]
I can approve this too now
/approve

**Pull request merged**
