### PR TITLE
Typo in concepts/extend-kubernetes/api-extension/apiserver-aggregation/apipserver-aggregation.md

### PR DESCRIPTION
**Pull request by joao-luna-98**
Typo in concepts/extend-kubernetes/api-extension/apiserver-aggregation/apipserver-aggregation.md

### CODE REVIEW

**Comment by viniciusbds** [comment]
do you think it is better to do this in another PR @devlware ?

**Comment by devlware** [comment]
Thanks for pointing out @viniciusbds. 
@joao-luna-98 Can you check the glossary_tooltip?

**Comment by joao-luna-98** [comment]
@devlware @viniciusbds I prefer to do it in another PR

**Comment by viniciusbds** [comment]
no problem
thanks @joao-luna-98 
/approve

**Pull request merged**
