### PR TITLE
content/en/case-studies: remove OWNERS

### PR DESCRIPTION
**Pull request by nikhita**
For kubernetes/org#2013

As a part of cleaning up inactive members (who haven't been active since
the release of v1.11) from OWNERS, this commit removes the OWNERS file
for content/en/case-studies.

Original commit message below.

----

As a part of cleaning up inactive members (who haven't been active since
the release of v1.11) from OWNERS, this commit removes sarahkconway from
the content/en/case-studies/OWNERS file.

Note: With this change, we are only left with one approver for this
directory. We should look at adding more approvers, but this commit
addresses the problem for the short term by ensuring that the bot
doesn't suggest inactive members for approval.

/assign @alexcontini @zacharysarah 
cc @mrbobbytables @SarahKConway

### CODE REVIEW

**Comment by nikhita** [comment]
/hold

> @nikhita: GitHub didn't allow me to assign the following users: alexcontini.

This is concerning because @alexcontini won't be able to lgtm/approve PRs either if they are not a member of the @kubernetes org.

**Comment by zacharysarah** [comment]
@nikhita 👋 Coukd you please delete the entire OWNERS file here? Thank you! 🙇

**Comment by nikhita** [comment]
Done :heavy_check_mark:

**Pull request merged**
