### PR TITLE
Remove zh/docs/concepts/cluster-administration/monitoring.md

### PR DESCRIPTION
**Pull request by ydcool**
Ref: #21202 

/kind cleanup

### CODE REVIEW

**Comment by tengqm** [comment]
Please don't do this.
We are partially "replicating" the English site change to Chinese.
This will make tracking changes a lot difficult.

Instead please file some issues if you have read #21202. This file is not dropped if I'm understanding it correctly. It is moved.

**Comment by ydcool** [comment]
> Please don't do this.
> We are partially "replicating" the English site change to Chinese.
> This will make tracking changes a lot difficult.
> 
> Instead please file some issues if you have read #21202. This file is not dropped if I'm understanding it correctly. It is moved.

Yes I was noticed that's a `rename` file,  which should target to `../cluster-administration/system-metrics.md`, but the target file has been translated as a `add` action in #23623 
So as you said, we should delete current `system-metrics.md` and rename this one then apply the latest content to it, right?

**Comment by tengqm** [comment]
@ydcool Thanks for the explanation. I just wanted to ensure things are not broken in unexpected ways.

**Pull request merged**
