### PR TITLE
grammar and syntax errors

### PR DESCRIPTION
**Pull request by dba-git**
just little errors that i think need to be fixed

### CODE REVIEW

**Comment by zacharysarah** [comment]
@dba-git 👋 Please sign the [CLA](https://identity.linuxfoundation.org/projects/cncf) so we can review and approve this PR. Let us know if we can help!

**Comment by dba-git** [comment]
> @dba-git wave Please sign the [CLA](https://identity.linuxfoundation.org/projects/cncf) so we can review and approve this PR. Let us know if we can help!
@zacharysarah done!

**Comment by zacharysarah** [comment]
@dba-git Thanks for the fixes.

/lgtm
/approve

**Pull request merged**
