### PR TITLE
Remove IBM course

### PR DESCRIPTION
**Pull request by victorshinya**
Since January 2020, IBM removed all microservice courses and specialization on Coursera.

### CODE REVIEW

**Comment by victorshinya** [comment]
Created a CLA with my Github account

**Comment by kbhawkey** [comment]
Ping @victorshinya , Would you look into signing the CLA or investigating if you need to take further action to complete the CLA. Thanks!

**Comment by victorshinya** [comment]
Completed the CLA process. Is there anything to pass the tide review?

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-18836--kubernetes-io-master-staging.netlify.com/docs/tutorials/online-training/overview/

**Comment by kbhawkey** [comment]
Thanks @victorshinya .
/lgtm

**Pull request merged**
