### PR TITLE
ServiceLoadBalancerClass is GA

### PR DESCRIPTION
**Pull request by tengqm**
Upstream: kubernetes/kubernetes#107979

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
@tengqm I see https://github.com/kubernetes/website/pull/31815 is also opened up for the same purpose but @XudongLiuHarold hasn't made much changes there.

So, I would like to keep this PR open and consider closing https://github.com/kubernetes/website/pull/31815. Please correct me if I am wrong, thanks!

**Comment by mehabhalodiya** [comment]
enhancement ref: https://github.com/kubernetes/enhancements/issues/1959

**Comment by tengqm** [comment]
> So, I would like to keep this PR open and consider closing #31815. Please correct me if I am wrong, thanks!

I agree.

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Comment by reylejano** [comment]
Code in PR https://github.com/kubernetes/kubernetes/pull/107979 has merged
/approve

**Pull request merged**
