### PR TITLE
Fix broken link in zh language version

### PR DESCRIPTION
**Pull request by ayhaadam**
As title.
The "guestbook-all-in-one.yaml" link in zh language version is broken.
Fixed it with English version link.

### CODE REVIEW

**Comment by ayhaadam** [comment]
Hi @chenrui333, Please check this PR, thanks.
/assign @chenrui333

**Review by Arhell — COMMENTED** [review]
/assign @tengqm

**Comment by tengqm** [comment]
Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). To find out what are the upstream changes to be synced, do this **on the main branch**:

```shell
./scripts/lsync.sh content/zh/docs/concepts/configuration/overview.md
```

/hold

**Pull request closed without merging**
