### PR TITLE
Fix kubectl download url in spanish docs

### PR DESCRIPTION
**Pull request by ebarped**
Fix the windows´s kubectl download url in spanish docs

### CODE REVIEW

**Comment by ebarped** [comment]
I signed it

**Comment by raelga** [comment]
Hello @ebarped, thanks for the fix but the issue is the extra initial `(`. Can you update the PR?

**Comment by raelga** [comment]
https://deploy-preview-27669--kubernetes-io-master-staging.netlify.app/es/docs/tasks/tools/install-kubectl/#instalar-el-binario-de-kubectl-con-curl-en-windows

/lgtm
/approve

**Comment by raelga** [comment]
Thanks for the fix @ebarped and welcome to Kubernetes! 🎉

**Pull request merged**
