### PR TITLE
Fix case studies logo paths on homepage

### LINKED ISSUE #9721: Case Study logos on home page are incorrect
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The ING case study on the home page has the Wikimedia image.

**Proposed Solution:**

Change `background-image` value on selector `#home #caseStudiesWrapper div:nth-child(4)`.

**Page to Update:**
https://kubernetes.io/

Browser: Firefox Developer Edition 62.0b13

### PR DESCRIPTION
**Pull request by blatayue**
~~The paths were adjusted in the generated sass files at one point, but not in _base~~ (Actually not 100% certain, thought I ran across it at one point) so I changed them to match the text and links. Tested with docker as well. 

Fixes #9721

### CODE REVIEW

**Comment by zacharysarah** [comment]
@lucperkins WDYT? Please feel free to close this PR if it's obsolete from your recent work.

**Comment by zacharysarah** [comment]
@blatayue 👋 Thanks for opening your first PR in k/website! 

- Please refactor this PR to include changes only to `assets/sass/_base.sass`. 

- Please resolve the merge conflicts. These may be due to downstream results (`resources/_gen/assets/sass/*`) having changed.

**Comment by zparnold** [comment]
I'm going to close this @blatayue , but we totally want to have your contribution! Please reopen it when you have some more time to take a look at these comments. 😄 
/close

**Pull request closed without merging**
