### PR TITLE
Device Plugin to Glossary page

### PR DESCRIPTION
**Pull request by daminisatya**
#5993

### CODE REVIEW

**Comment by daminisatya** [comment]
/assign @bradtopol
/assign @cody-clark 

Need your help, kindly please review :)

**Comment by daminisatya** [comment]
/assign @Rajakavitha1 

Thank you so much for the review. I updated the PR. The sentence helped me understand about Device Plugin in a much clearer way :) 👍

**Comment by Rajakavitha1** [comment]
> 
> 
> Hi @daminisatya . Thanks for the update. Just a minor suggestion: Device Plugins are containers running in Kubernetes that provide access to a vendor specific resource. Device Plugins advertise these resources to kubelet and can be deployed manually or as a DeamonSet, rather than writing custom Kubernetes code.

You are always welcome!!! Thanks for the update.

**Comment by Rajakavitha1** [comment]
/lgtm

@cody PTAL and let me know if it is okay for an approve :)

**Comment by Rajakavitha1** [comment]
/assign @zparnold 

Please take a look and let me know if we can approve!!!

**Pull request merged**
