### PR TITLE
fix-manage-compute-resources-container-view

### PR DESCRIPTION
**Pull request by tiny1990**
k8s doc 
 https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

My Container is terminated  view error .

### CODE REVIEW

**Comment by stewart-yu** [comment]
Thanks for your contribution, please  sign the CLA.
/lgtm

**Comment by tiny1990** [comment]
cla authorized

**Comment by tengqm** [comment]
@tiny1990 There is a conflict...

**Pull request merged**
