### PR TITLE
[zh] Clean PodPreset related pages/examples

### PR DESCRIPTION
**Pull request by tengqm**
This PR drops the contents related to PodPreset in zh localization. Wherever a resync of the page needed, a resync is performed.

### CODE REVIEW

**Comment by howieyuen** [comment]
just curious, how do you know the wherever? I wanna learn~

**Comment by tengqm** [comment]
@howieyuen There is a util script under /scripts.  `./scripts/lsync.sh content/zh/<path>` generates a summary of pages that are out of sync. `./scripts/lsync.sh content/zh/<path>/<file>.md` generates a diff of the upstream changes that are not synced to zh localization. These all assume we are strictly following the "no-partial-patch" policy.

**Comment by howieyuen** [comment]
> @howieyuen There is a util script under /scripts. `./scripts/lsync.sh content/zh/<path>` generates a summary of pages that are out of sync. `./scripts/lsync.sh content/zh/<path>/<file>.md` generates a diff of the upstream changes that are not synced to zh localization. These all assume we are strictly following the "no-partial-patch" policy.

so it is, I have always followed the scripts summary to make sure whether zh doc is out of sync.

**Review by tanjunchen — COMMENTED** [review]
/approve

**Review by tanjunchen — COMMENTED** [review]
/approve

**Pull request merged**
