### PR TITLE
Enhance Readability with Markdown Formatting Improvements To README.md

### PR DESCRIPTION
**Pull request by ywh555hhh**
### Description

Dear Team,

I've submitted this PR to enhance the readability and cleanliness of our `README.md` document. I noticed some minor formatting issues that could affect the presentation of our documentation, and I have made the following careful adjustments:
- **MD022/blanks-around-headings**: I've added necessary blank lines around all headings to ensure they stand out visually and are more distinct.
- **MD031/blanks-around-fences**: Similarly, I ensured that code blocks are surrounded by blank lines, making the code easier to read while maintaining consistency across our documentation.

### Why This Is Needed
We all know that a well-formatted document can greatly enhance the efficiency of information delivery. By following the recommendations of `markdownlint`, we not only enhance the professionalism of our documentation but also improve the experience for everyone who reads it.

### Testing Instructions
- This update mainly involves formatting changes, so no code-level testing is needed.
- I have manually reviewed all changes to ensure formatting correctness and maintain content accuracy.

### Additional Information
- I decided to disregard the MD013/line-length issues to preserve our content's original form and style. Sometimes, flexibility in rules is necessary to keep our language flowing naturally.

Let's continue to strive for maintaining high standards and usability in our documentation, making it a strong support in our work. Thank you everyone for your efforts and contributions!

### Issue

Closes: none

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Related page -> https://github.com/kubernetes/website/blob/main/README.md

**Comment by utkarsh-singh1** [comment]
/language en 

It would be beneficial for the readability, but I don't think it would make changes after render.

**Comment by utkarsh-singh1** [comment]
But it improves the documentation, Thanks @ywh555hhh

**Review by Okabe-Junya — COMMENTED** [review]
Thanks! This is unofficial, but LGTM!

FYI: related issue - #47418

**Comment by ywh555hhh** [comment]
> /language en
> 
> It would be beneficial for the readability, but I don't think it would make changes after render.

This is really something I don't know, thanks for sharing

**Comment by ywh555hhh** [comment]
Will someone please take a look?

**Comment by Okabe-Junya** [comment]
I Reached out this week's PR wrangler, thanks!

FYI: https://kubernetes.slack.com/archives/C1J0BPD2M/p1724165931998779?thread_ts=1724102379.279539&cid=C1J0BPD2M

**Comment by Okabe-Junya** [comment]
/auto-cc
Please take a look this PR :)

**Comment by tengqm** [comment]
/kind cleanup
/lgtm
/approve

Referring to our policy on [trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits), please consider contribute nontrivial commits to the site next time.

**Comment by ywh555hhh** [comment]
> /kind cleanup /lgtm /approve
> 
> Referring to our policy on [trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits), please consider contribute nontrivial commits to the site next time.

Thanks for reminding me, I'll take care of it later!

**Pull request merged**
