### PR TITLE
Remove page that only contains placeholder text

### LINKED ISSUE #7673: Issue with k8s.io/docs/setup/hosted-solutions/overview/
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
This place holder content was inadvertently published as part of  #4630 

**Proposed Solution:**
Remove the page, and update website/_data/setup.yml to use a different landing page

**Page to Update:**
https://kubernetes.io/docs/setup/hosted-solutions/overview/

### PR DESCRIPTION
**Pull request by pmallory**
fixes #7673

I'm not sure if/how to change the `landing_page` element in the yaml file. The TOC looks fine in staging, but referring to a nonexistent page as the landing page seems wrong.

### CODE REVIEW

**Comment by steveperry-53** [comment]
@pmallory This all looks good, except for a small glitch in the landing page path. I think you should remove the trailing slash from landing_page: /docs/setup/pick-right-solution/#hosted-solutions/. 

Go [here](https://deploy-preview-7697--kubernetes-io-master-staging.netlify.com/docs/home/?path=users&persona=app-developer&level=foundational). Scroll down to the Browse Docs section. Under Setup, click Hosted Solutions. For me, this goes to the top of the /docs/setup/pick-right-solution page. It doesn't go to the Hosted Solutions section.

**Comment by pmallory** [comment]
Thanks for catching that. Fixed :+1:

**Comment by pmallory** [comment]
@steveperry-53 bump

**Pull request merged**
