### PR TITLE
WIP: Refactor concept page for Secrets

### PR DESCRIPTION
**Pull request by shannonxtreme**
Umbrella issue: #4491
Blockers: #34291 

This PR refactors the concept page for secrets, at https://kubernetes.io/docs/concepts/configuration/secret/

The scope of work is defined in [this Google doc](https://docs.google.com/document/d/1VQ8UFux1HifjXo9rRwm2-mOoUOzmMF7zGf-C0BhurdQ/edit#heading=h.nq4idzs84lru).

Preview: https://deploy-preview-34168--kubernetes-io-main-staging.netlify.app/docs/concepts/configuration/secret/

/sig docs
/language en
/label refactor
/do-not-merge work-in-progress
/cc @sftim

### CODE REVIEW

**Comment by sftim** [comment]
https://github.com/kubernetes/website/issues/32869 is likely to be relevant here.

**Comment by shannonxtreme** [comment]
> #32869 is likely to be relevant here.

Fixed with the following content: 

For the YAML:

The values that you provide in the `data` field must be the base64-encoded
values for the public/private key pair. This data must be the same as in PEM,
without the first and last lines in PEM. For example, for a certificate, do not
include the `--------BEGIN CERTIFICATE-----` and `-------END CERTIFICATE----`
lines.

For the kubectl command:

You can also create a TLS Secret in the command line using the [`kubectl create secret tls`](/docs/reference/generated/kubectl/kubectl-commands#-em-secret-tls-em-) subcommand and providing the public/private key pair. Both files must be .PEM-encoded. The public key certificate must be in DER format as described in [Section 5.1 of RFC 7468](https://datatracker.ietf.org/doc/html/rfc7468#section-5.1). The public certificate must match the private key, which must be PKCS #8 in DER format as described in [Section 11 of RFC 7468](https://datatracker.ietf.org/doc/html/rfc7468#section-11).

**Comment by shannonxtreme** [comment]
@sftim So I think im in a bit of a catch 22. This PR removes a lot of content in the Secret concept. I will have other PRs coming that add or direct that content to existing topics. The way I see the PRs roll up is the smaller PRs and topics migrate the info out of the concept.

When those PRs are merged, we rebase this PR and see what's left to clean up before merging this PR last. 

Issue is that this will keep some content duplication across our docs until this PR is merged. I'm open to suggestions (such as removing the content from the concept topic relevant to each smaller PR in that smaller PR and rebasing this PR as I go)

**Comment by sftim** [comment]
I _think_ that the position in https://github.com/kubernetes/website/pull/34168#issuecomment-1165873366 is wrong. Some of the existing documentation about Secret is wrong too.

TLS Secrets (Secret type `kubernetes.io/tls`) store a private key and a certificate. The convention is for these to be PEM encoded as per https://datatracker.ietf.org/doc/html/rfc7468#section-11 and https://datatracker.ietf.org/doc/html/rfc7468#section-5.1 respectively. 

We don't need to mention that PEM encoding uses base64 or that the inner contents are ASN.1 in DER. Those are details we can actually skip.

More code that interacts with Secret type `kubernetes.io/tls` expects PEM format; any docs that suggests using bare DER are wrong. However, Kubernetes itself doesn't validate the format of these data. Maybe one day there'll be an admission controller that can and does.

**Comment by sftim** [comment]
@shannonxtreme I'm afraid that the “smaller PRs first” approach is likely to be right.

When I've made big PRs like this, sometimes the easier way to get it over the line has been to leave the big PR open to allow reference back to the overall Netlify preview, to show intent. Then open a series of smaller PRs that cherry-pick updates from the big PR, piece by piece, until eventually the big PR becomes a no-op.

If you do that, you need to make the situation clear to reviewers. Even then, sometimes you'll find that reviewers don't read the context enough and ask you to make a big PR. You just have to make the situation extra clear and explain why you have _n_ smaller PRs open.

Once the big PR (this one) becomes a no-op, close it. And pour yourself one out!

**Pull request closed without merging**
