### PR TITLE
Change to VolumeSnapshot CRD v1beta1

### PR DESCRIPTION
**Pull request by xing-yang**
This PR changes VolumeSnapshot CRD version from v1alpha1 to v1beta1.

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@xing-yang could you please ref the code PR here so that we can track the status of it? Thanks!

**Comment by xing-yang** [comment]
This is delayed to 1.17.  PR is here:
https://github.com/kubernetes/kubernetes/pull/80058

**Comment by msau42** [comment]
@sftim we should not have merged this PR, as the feature is delayed to 1.16

**Comment by sftim** [comment]
Oops! Let me PR something to revert that.

**Comment by sftim** [comment]
🤦

**Pull request merged**
