### PR TITLE
removal of the detailed steps for Secret use cases

### PR DESCRIPTION
**Pull request by sanchita-07**
Modified Use Cases in Secrets. 
"Use case: As container environment variables" is removed.
"Use case: Pod with SSH keys" - content deleted and use case is marked in bullet.
"Use case: Pods with prod / test credentials" and "Use case: Secret visible to one container in a Pod" are now a part of [Distribute Credentials Securely Using Secrets](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure) and the links are attached in bullets.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by shannonxtreme** [comment]
I opened #38084 hoping to prompt some additional discussion before migrating the content, just in case steps like "prod/test" credentials weren't really needed, etc, and in case the Secrets use case would be better served in its own task. I won't hold this PR but I do hope that we can get some additional insight from other members before we merge anything

**Comment by shannonxtreme** [comment]
I agree and disagree at the same time. The use case for prod/test credentials seems self evident - you refer to one secret from one pod and another secret from another pod. There's nothing too complicated being done there. So I wonder if we can even get rid of the instructions for it. 

For the other one (secret visible to only one container), I still am torn between migrating it to the existing page or creating a new page with actual steps, justification, and guidance.

I do agree that neither of those should remain on the concept page for Secrets, but I think we should get more opinions on *how* the content should exist if at all

**Comment by sanchita-07** [comment]
Sure, looking forward for more opinions.

**Comment by tengqm** [comment]
/hold
This PR is touching more than one localization for non-trivial changes.
Please consider split it into several PRs, starting from the English change.

**Comment by Sea-n** [comment]
Seems @sanchita-07 you encountered a git problem.
Could you fix it or open a new PR?

**Comment by Sea-n** [comment]
Ping @sanchita-07 again, please let us know if you need any help.

**Comment by tengqm** [comment]
/close
This PR is insane in its current state.

**Pull request closed without merging**
