### PR TITLE
Merged main into dev 1.32

### PR DESCRIPTION
**Pull request by spurin**
This PR syncs the dev-1.32 branch with the main branch to keep the dev-1.32 branch up to date.

cc: @chanieljdan @AnshumanTripathi @rdalbuquerque @spurin @hacktivist123 @michellengnx

### CODE REVIEW

**Comment by spurin** [comment]
Closed and Re-opened in an attempt to re-run netlify

**Comment by dipesh-rawat** [comment]
@spurin Could you try to trigger the Netlify build again by pushing an empty commit using:
```
git commit --amend --no-edit && git push --force-with-lease
```

**Comment by spurin** [comment]
Done @dipesh-rawat 

fyi, I ended up running the following to trigger this:

```
git commit --amend --no-edit && git push --force-with-lease origin merged-main-dev-1.32
```

**Comment by spurin** [comment]
A merge conflict which was resolved:

```
Merging 'upstream/main' into 'dev-1.32' to stay current with upstream changes.
Executing: git merge upstream/main -m 'Merge main into dev-1.32 to keep up-to-date'
Auto-merging content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
CONFLICT (content): Merge conflict in content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
Automatic merge failed; fix conflicts and then commit the result.
```

```
% cat content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
---
title: AnonymousAuthConfigurableEndpoints
content_type: feature_gate
_build:
  list: never
  render: false

stages:
  - stage: alpha
    defaultValue: false
    fromVersion: "1.31"
    toVersion: "1.31"
  - stage: beta
    defaultValue: true
    fromVersion: "1.32"
---
<<<<<<< HEAD
Enable [configurable endpoints for anonymous auth](/docs/reference/access-authn-authz/authentication/#anonymous-authenticator-configuration)
=======
Enable [configurable endpoints for anonymous auth](/docs/reference/access-authn-authz/authentication/#anonymous-authenticator-configuration)
>>>>>>> upstream/main
for the API server.
```

dev-1.32 appears to have the equivalent line in question but also includes newer examples, committed 2024-09-04 by Vinayak Goyal:

```
% git blame upstream/main -- content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  1) ---
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  2) title: AnonymousAuthConfigurableEndpoints
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  3) content_type: feature_gate
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  4) _build:
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  5)   list: never
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  6)   render: false
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  7)
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  8) stages:
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  9)   - stage: alpha
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000 10)     defaultValue: false
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000 11)     fromVersion: "1.31"
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000 12) ---
229e3aca2af (Dipesh Rawat  2024-10-29 00:55:29 +0000 13) Enable [configurable endpoints for anonymous auth](/docs/reference/access-authn-authz/authentication/#anonymous-authenticator-configuration)
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000 14) for the API server.
 
% git blame dev-1.32 -- content/en/docs/reference/command-line-tools-reference/feature-gates/anonymous-auth-configurable-endpoints.md
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  1) ---
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  2) title: AnonymousAuthConfigurableEndpoints
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  3) content_type: feature_gate
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  4) _build:
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  5)   list: never
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  6)   render: false
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  7)
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  8) stages:
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000  9)   - stage: alpha
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000 10)     defaultValue: false
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000 11)     fromVersion: "1.31"
7a1cdab150e (Vinayak Goyal 2024-09-04 14:48:27 +0000 12)     toVersion: "1.31"
7a1cdab150e (Vinayak Goyal 2024-09-04 14:48:27 +0000 13)   - stage: beta
7a1cdab150e (Vinayak Goyal 2024-09-04 14:48:27 +0000 14)     defaultValue: true
7a1cdab150e (Vinayak Goyal 2024-09-04 14:48:27 +0000 15)     fromVersion: "1.32"
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000 16) ---
7a1cdab150e (Vinayak Goyal 2024-09-04 14:48:27 +0000 17) Enable [configurable endpoints for anonymous auth](/docs/reference/access-authn-authz/authentication/#anonymous-authenticator-configuration)
4b2940eb26d (Vinayak Goyal 2024-06-26 21:32:55 +0000 18) for the API server.
```

Given the identical line and the newer changes from Vinayak, the commit from dev-1.32 was selected.

**Review by dipesh-rawat — COMMENTED** [review]
/lgtm

**Comment by chanieljdan** [comment]
/assign sftim

Hi @sftim! Could we get your approval for this week's branch sync?

**Pull request merged**
