### PR TITLE
Removed usage of docker from replicationControllers, containers, pods and daemonsets

### LINKED ISSUE #30965: Action on Docker mentions in Concepts > Workloads
Umbrella issue: #30771 
Originating issue: #30774 (partially fixes)

File: /concepts/workloads/controllers/daemonset.md
URL: https://k8s.io/docs/concepts/workloads/controllers/daemonset

Line 207 contains `(e.g. start directly via Docker).`

The code sample includes docker mentions. 

Action: remove the phrase. Add warning about code samples potentially breaking. Test code samples on a cluster with a different runtime and on a cluster with cri-dockerd and Docker. 

---

File: /concepts/workloads/controllers/deployment.md
URL: https://k8s.io/docs/concepts/workloads/controllers/deployment

Line 65 contains Docker Hub as an example.

Action: keep, since it's an example image.

---

File: /concepts/workloads/controllers/replicaset.md
URL: https://k8s.io/docs/concepts/workloads/controllers/replicaset

Last sentence in line 392 contains Docker as an example.

Action: Rephrase to "some agent on the node, such as the kubelet"

---

File: /concepts/workloads/controllers/replicationcontroller.md
URL: https://k8s.io/docs/concepts/workloads/controllers/replicationcontroller

Line 142 and 273 have Docker as an example. 

Action: 

* Line 142: remove "or Docker".
* Line 273: rephrase to "some agent on the node, such as the kubelet."
---

File: /concepts/workloads/pods/_index.md
URL: https://k8s.io/docs/concepts/workloads/pods/

Line 35 - 48: Uses Docker to describe what Pods are.

Action: reword the overview of a Pod to describe it without a reliance on a third party. Use content from our Glossary. 

---

File: /concepts/workloads/pods/init-containers.md
URL: https://k8s.io/docs/concepts/workloads/pods/init-containers

Output in line 189 and 190 seem to use docker as the runtime.

Action: not sure. Replace example output with the output while using containerd or cri-o?

---

File: /concepts/workloads/pods/pod-lifecycle.md
URL: https://k8s.io/docs/concepts/workloads/pods/pod-lifecycle

Line 208 uses docker as the container ID example

Action: keep as-is. 

/sig docs
/language en
/help-wanted

### PR DESCRIPTION
**Pull request by rogue-gamer-ryt**
## Description
**Issue being addressed** - Fixes #30965

- Removed the usage of "docker" in [daemonsets](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#init-scripts). The code sample was tested on contianerd runtime
- Updated the phrasing used in [replicationcontroller](https://k8s.io/docs/concepts/workloads/controllers/replicationcontroller) and removed the usage of "or Docker"
- Removed usage of "docker" in [pods](https://k8s.io/docs/concepts/workloads/pods/)
- The output for [init-containers](https://k8s.io/docs/concepts/workloads/pods/init-containers) was captured when using containerd runtime.

### CODE REVIEW

**Comment by reylejano** [comment]
I may be wrong but I believe the `quay.io/fluentd_elasticsearch/fluentd:v2.5.2 image` expects the `volumemount` `varlibdockercontainers`

I recomment to check the upstream fluentd 
https://docs.fluentd.org/container-deployment/kubernetes#logging-to-elasticsearch

Please test manifests if they will be changed

**Comment by rogue-gamer-ryt** [comment]
> I may be wrong but I believe the `quay.io/fluentd_elasticsearch/fluentd:v2.5.2 image` expects the `volumemount` `varlibdockercontainers`
> 
> I recommend to review the upstream fluentd https://docs.fluentd.org/container-deployment/kubernetes#logging-to-elasticsearch

I am not sure around the older image of fluentd_elasticsearch (2.5.2) but I went through the link you shared. 
So in the upstream they have an example[ daemonset.yaml](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml#L64) for fluetd_elasticsearch and it has the following volume mount definition
```yaml
# When actual pod logs in /var/lib/docker/containers, the following lines should be used.
# - name: dockercontainerlogdirectory
#   mountPath: /var/lib/docker/containers
#   readOnly: true
# When actual pod logs in /var/log/pods, the following lines should be used.
- name: dockercontainerlogdirectory
  mountPath: /var/log/pods
  readOnly: true
```
Do you think the example in our daemonset should also be mounting `/var/log/pods` instead of the docker logs mount path?

**Comment by rogue-gamer-ryt** [comment]
Hey @jimangel,
Since you are the PR wrangler for the week I am assigning you as a reviewer.

/assign @jimangel

**Review by Sea-n — COMMENTED** [review]
/lgtm

**Review by sftim — COMMENTED** [review]
Thanks

/lgtm

**Pull request merged**
