### PR TITLE
update link to metrics-server design doc

### PR DESCRIPTION
**Pull request by dlbewley**
Update to follow link to new archive location of metrics-server design doc.

### CODE REVIEW

**Comment by Babapool** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/34088/#/?version=2)
> 
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/34088/#/?version=2) - login: @dlbewley / name: Dale Bewley . The commit ([5672390](https://github.com/kubernetes/website/commit/56723902994f6b331f5b87c51603a74efe1c1027)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/34088/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

Hi @dlbewley, thank you for your contribution and welcome to Kubernetes. Before your PR gets reviewed, it would be great if you could sign the CLA , the steps are mentioned here : https://github.com/kubernetes/website/pull/34088#issuecomment-1143064681 Thanks.

**Comment by bradtopol** [comment]
Hi @dlbewley Thank you for your contribution! Please sign the CLA so we can accept it for review. Thanks!
/assign

**Comment by Sea-n** [comment]
Yeah, the document has been moved.
/lgtm

**Pull request merged**
