### PR TITLE
Kuberhealthy 2.1.0 blog post

### PR DESCRIPTION
**Pull request by joshulyne**
Hello! I'm one of maintainers of the Kuberhealthy project -- an operator for synthetic monitoring on Kubernetes. We recently added some new features and made updates after the announcement of our 2.0.0 release at KubeCon San Diego 2019 and would like to share with the rest of the community through our 2.1.0 release!

### CODE REVIEW

**Comment by castrojo** [comment]
/lgtm

Kaitlyn will adjust the date to schedule it, thanks!

**Comment by onlydole** [comment]
@joshulyne - Regarding the images for this post, I'd recommend that they be included directly (so they rely on the kubernetes.io CDN and prevent breakage in the future). While we do permit externally linked images, having them directly put into our Hugo site guarantees that they will not likely break.

**Comment by joshulyne** [comment]
@mrbobbytables Thanks for the review -- I agree with you! Definitely think we can flesh this out more with tangible examples and tutorials on how to get it working. We've also been doing more work on the project since I submitted the blog post so there may be better content opportunity there. Will ping you once the blog post is ready for review again!

@onlydole I was curious about that! I saw it being done both ways on some blog post prs so I took the lazier route :D Will update that as well! 

Thank you both for the feedback!

**Comment by sftim** [comment]
@joshulyne can you update the images per https://github.com/kubernetes/website/pull/19389#issuecomment-602920280 ?

**Comment by zacharysarah** [comment]
@joshulyne :wave: Please feel free to `/reopen` this issue when you’re ready to continue.

/close

**Pull request closed without merging**
