### PR TITLE
Update job.md to add a newline

### PR DESCRIPTION
**Pull request by toli**
add a newline per bug #29840
https://github.com/kubernetes/website/issues/29840

### CODE REVIEW

**Comment by toli** [comment]
completed the CLA as Toli Kuznets, tkuznets@salesforce.com
think it has my regular toli github.com username

**Review by mallow111 — APPROVED** [review]

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-29880--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/job/#completion-mode

**Comment by kbhawkey** [comment]
Thanks @toli .
/lgtm
/approve

**Pull request merged**
