### PR TITLE
【CN】using page.version rather than hardcode version in link

### PR DESCRIPTION
**Pull request by stewart-yu**
using page.version rather than hardcode version in link

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7060)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@stewart-yu 
we do not maintain the Chinese translation here.
you may check https://github.com/kubernetes/kubernetes-docs-cn 
thanks!

**Comment by stewart-yu** [comment]
I saw some PRs, [https://github.com/kubernetes/website/pull/6858](https://github.com/kubernetes/website/pull/6858)， [https://github.com/kubernetes/website/pull/6549](https://github.com/kubernetes/website/pull/6549)also change file in `/cn` directory. may i misunderstanding it? @zhangxiaoyu-zidif

**Comment by zhangxiaoyu-zidif** [comment]
yes, recently I saw @zacharysarah  closed some `/cn` related PR, so I close this one. 
/cc @tengqm 
If I am wrong, re-open it =)

**Comment by tengqm** [comment]
@zhangxiaoyu-zidif I have no idea what was happening regarding CN translation. There seem two groups of people working in parallel. As you may know, I have been actively reviewing the contents committed to this repo, but I don't have another eye for a new repo.

**Comment by zacharysarah** [comment]
@tengqm @stewart-yu 👋 Please open Chinese translation PRs in https://github.com/kubernetes/kubernetes-docs-cn.

**Comment by zacharysarah** [comment]
@tengqm Would you like an invitation to the monthly translation sync? It's on fourth Mondays at 5pm PST.

**Comment by tengqm** [comment]
@zacharysarah Okay.

**Pull request closed without merging**
