### PR TITLE
From container image concept page, signpost readers to Kubernetes downloads

### PR DESCRIPTION
**Pull request by sftim**
Revise [Images](https://kubernetes.io/docs/concepts/containers/images/) concept in Kubernetes. This is a top match for the search term “Kubernetes container images”.

Help readers find Kubernetes container images for download [[preview](https://deploy-preview-37874--kubernetes-io-main-staging.netlify.app/docs/concepts/containers/images/)].

### CODE REVIEW

**Comment by sftim** [comment]
/retitle From container image concept page, signpost readers to Kubernetes downloads

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Pull request merged**
