### PR TITLE
[hi] Homepage hyperlinks Updated

### LINKED ISSUE #40370: [hi] Update hyperlinks on the homepage to open in new tab
**This is a Bug Report**

**Problem:**

In the English and Hindi version of the website, some hyperlinks on the homepage that are redirecting the user to a different website (other than Kubernetes) are not getting redirected to a separate tab.

**Proposed Solution:**

I will make them redirect to the separate tab using the target="_blank" property.

**Page to Update:**

https://kubernetes.io/ and https://kubernetes.io/hi/

Screenshot 2023-03-27 at 8 19 24 PM

Screenshot 2023-03-18 at 12 23 57 AM

Screenshot 2023-03-18 at 12 25 08 AM

I want to work on this issue.
/assign

### PR DESCRIPTION
**Pull request by Jai-Solania-29**
Fixes #40370 

I have successfully updated the code, Now the hyperlinks on the homepage are opening in a new tab ✅.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@Jai-Solania-29  Thanks for your contribution. Currently this PR has changes to both _English_ and _Hindi_ languages. In general we do not want PRs spanning across multiple languages. If you could break this up into multiple PRs, where we have a single PR per language that would be great.

**Comment by divya-mohan0209** [comment]
Hello @Jai-Solania-29, thank you for your contribution. 

Is there a specific value add with this change other than opening the linked website on a new tab? 

Was the value add/change discussed over an issue/PR and has it been agreed upon to affect this change only to these two specific pages of the documentation by any maintainer/reviewer/approver?

As one of the maintainers for Kubernetes documentation, I'd recommend that you follow the below steps:

- close this PR with the /close command and first discuss whether this change is required over an issue.
- Also, understand where this change needs to be applied i.e. the scope of the change. You have applied it to a single page & I'm sure there are more pages that have this same issue.
- Open an umbrella PR for the English localisation AFTER agreement and get it approved + reviewed.
- Make the changes for Hindi localization via another umbrella PR.
- We will then need to notify other localisations to follow suite.

**Comment by divya-mohan0209** [comment]
Explicit hold to avoid accidental merges.

/hold

**Comment by Jai-Solania-29** [comment]
Thank you @divya-mohan0209, I will follow the suggested steps ✅

**Pull request closed without merging**
