### PR TITLE
Update scheduling-gpus

### PR DESCRIPTION
**Pull request by jakspok**

### CODE REVIEW

**Comment by bradtopol** [comment]
/assign
Hi @jakspok thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @jakspok , thank you for your contribution! It seems you're trying to translate the English documents into Spanish. Please follow the below while working on localising the Kubernetes documentation
- Sign the CLA
- Work with your localisation leads on Slack to understand the process
- Make changes to the correct branch/directory.

Since none of the above processes have been followed, we'll be closing the PR. Kindly follow the steps mentioned above before opening a PR.

**Comment by sftim** [comment]
Thanks for signing the CLA! Please ensure that you target the right path for localization to Spanish.

This change _replaces_ an English document with a Spanish document, which is the wrong process.

/hold

**Comment by Sea-n** [comment]
Hey @jakspok,

Thanks for purposing this PR. But since you didn't respond (see [this comment](https://github.com/kubernetes/website/pull/32820#issuecomment-1160695941)) for a while, we have to close this PR now.
/close

Feel free to `/reopen` when you are ready to move forward.

**Pull request closed without merging**
