### PR TITLE
[WIP]: add csi rbd migration blog article

### PR DESCRIPTION
**Pull request by humblec**
Place holder blog PR for https://github.com/kubernetes/enhancements/issues/2923

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
Cc @xing-yang

**Review by sftim — COMMENTED** [review]
Thanks @humblec 

Rather than focusing on RBD, it'd be great to have a survey of the state of the art around migrating from in-tree to CSI, regardless of the storage technology.

Is that something we could aim for?

**Comment by humblec** [comment]
> Thanks @humblec
> 
> Rather than focusing on RBD, it'd be great to have a survey of the state of the art around migrating from in-tree to CSI, regardless of the storage technology.
> 
> Is that something we could aim for?

@Jiawei0227 @xing-yang @msau42 could you please share your thoughts on this ?

**Review by sftim — CHANGES_REQUESTED** [review]
The blog articles that are for publication after the v1.24 release should target _main_ (and not _dev-1.24_).

Please change the base branch for this PR; it will save you time if you can do that before you start work.

**Comment by humblec** [comment]
I am closing this PR for now. Thanks @sftim and @xing-yang

**Pull request closed without merging**
