### PR TITLE
[zh] sync persistent-volumes.md

### PR DESCRIPTION
**Pull request by asa3311**
Related to task-3 of issue https://github.com/kubernetes/website/issues/39985.

content/en/docs/concepts/storage/persistent-volumes.md

### CODE REVIEW

**Comment by windsonsea** [comment]
This link shall be synced too, which you can find by running `./scripts/lsync.sh`:

**Comment by asa3311** [comment]
@windsonsea thanks, but when I running ./scripts/lsync.sh ,it shows 
image
This works right?

**Comment by asa3311** [comment]
@windsonsea  thanks,./scripts/lsync.sh works on main branch. Now,I have corrected, please review.

**Comment by tengqm** [comment]
please squash your PR into a single commit.

**Comment by asa3311** [comment]
thanks I will squash PR

**Comment by tengqm** [comment]
@asa3311 I was asking you to squash the PR into a single commit, not closing the PR.
Opening a new PR will lose all the review history. For large PRs, this wastes your own life and the reviewers.
Can you learn yourself some basics on `git rebase -i` and `git push -f` ?

**Comment by asa3311** [comment]
> @tengqm Sorry,I try to git rebase -i, but due to too much commits, there is something wrong. I will pay attention next time.All commits have been merged into #40016 .Please review #https://github.com/kubernetes/website/pull/40016.

**Comment by asa3311** [comment]
hi @tengqm ,Now I squashed commits , but you can review another pr https://github.com/kubernetes/website/pull/40016. because that  PR content is relatively complete. Please review~

**Comment by howieyuen** [comment]
I see open another PR, closing this one

**Pull request closed without merging**
