### PR TITLE
Update _index.md for concepts/extend-kubernetes/

### PR DESCRIPTION
**Pull request by snowcrystall**
update the webhook link in  #scheduler-extensions section

### CODE REVIEW

**Comment by Sea-n** [comment]
Nice catch! But we need you to sign CLA first so that we can move on.

感謝貢獻，不過要麻煩您先簽署授權協議，我們才能進一步 review 這個 PR

https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/34638/#/?version=2

**Review by Sea-n — COMMENTED** [review]
/lgtm

**Comment by jihoon-seo** [comment]
/remove-language en es fr ja ko pt

**Pull request closed without merging**
