### PR TITLE
KEP-2681 PodHostIPs in downward API to stable

### PR DESCRIPTION
**Pull request by danwinship**
Just updating the text that was added for alpha, #42153. I think this is all that's needed.

/assign @wzshiming

### CODE REVIEW

**Comment by tengqm** [comment]
/approve

Need to ensure that the upstream code change has been merged before lifting the hold.

/hold

**Comment by danwinship** [comment]
/hold cancel
(code PR merged)
(still need lgtm here)

**Comment by wzshiming** [comment]
/lgtm

Thank you

**Pull request merged**
