### PR TITLE
typo

### PR DESCRIPTION
**Pull request by WisWang**
there is a typo in kubeadm-upgrade-1-11.md

### CODE REVIEW

**Comment by neolit123** [comment]
thanks

/sig cluster-lifecycle
/lgtm

**Comment by neolit123** [comment]
/lgtm cancel

actually @WisWang please [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your commits. there is no need to have 3 commits for a single word typo fix.
thanks

**Comment by mistyhacks** [comment]
It will get squashed on merge.

/approve

**Pull request merged**
