### PR TITLE
Add missing Portuguese strings

### PR DESCRIPTION
**Pull request by sftim**
:warning: I don't speak much Portugeuse at all

I used a mixture of guesswork and Google translate to fill in some missing localized strings.

I hope this work is useful, but it might need a tweak or two.

/language pt

### CODE REVIEW

**Review by irvifa — COMMENTED** [review]
/lgtm
/approve

**Comment by sftim** [comment]
@kubernetes/sig-docs-pt-reviews was this change OK?

**Comment by devlware** [comment]
Yes!
Thank you @sftim. Sorry I could not review it before.

**Pull request merged**
