### PR TITLE
Update web-ui-dashboard.md

### PR DESCRIPTION
**Pull request by sysnet4admin**
In my humble view, it may need to update dashboard/v2.3.1 from v2.2.0

Refer to below 
https://github.com/kubernetes/dashboard#install

### CODE REVIEW

**Comment by sysnet4admin** [comment]
Please let it review for further movement. :) 
/assign @sftim

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-29316--kubernetes-io-main-staging.netlify.app/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui

**Pull request merged**
