### PR TITLE
Replace Digital Ocean with DigitalOcean

### PR DESCRIPTION
**Pull request by armando-migliaccio**
The latter is the official spelling, but both spellings have been
used throughout the docs. This commit replaces the occurrences of
the unofficial spelling with the official one.

### CODE REVIEW

**Comment by sftim** [comment]
> The former is the official spelling
I think maybe the _latter_ is the official spelling?

**Comment by armando-migliaccio** [comment]
> > I think maybe the _latter_ is the official spelling?

Yes, that's what I meant...I crossed my mental wires, edited. Thanks!

**Comment by bradtopol** [comment]
Verified that the updated spelling is the correct spelling as shown on the DigitalOcean site.
Great job!
/lgtm
/approve

**Comment by armando-migliaccio** [comment]
@bradtopol: thanks for the prompt feedback. Would you recommend that I follow up with the other translations. I am not 100% if the fix applies automatically over to other languages.

**Pull request merged**
