### PR TITLE
fix indents in code fences

### LINKED ISSUE #8961: Issue with k8s.io/docs/setup/independent/high-availability/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Wrong markdown formatting for "bash cat >config.yaml < ..." command inside "Run kubeadm init on master0" header.
It is really hard to understand the content of this config. Fix it, please... Thank you.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/#kubeadm-init-master0

### PR DESCRIPTION
**Pull request by makocchi-git**
closes #8961

### CODE REVIEW

**Comment by makocchi-git** [comment]
check url is here
https://deploy-preview-9021--kubernetes-io-master-staging.netlify.com/docs/setup/independent/high-availability/

**Comment by ajaeger** [comment]
thanks, looks fine - but has a merge conflict. @makocchi-git , could you rebase, please?

**Comment by ajaeger** [comment]
thanks, looks fine - but has a merge conflict. @makocchi-git , could you rebase, please?

Also, https://github.com/kubernetes/website/pull/9020 touches the same problem...

**Comment by Bradamant3** [comment]
/hold

@makocchi-git you might as well hold off on rebasing -- we have multiple PRs in flight against this file, plus, as comments in #9020, other work planned for it. 

Reviewers, please don't add any more commands until I've had a chance to look through the PRsl and merge in order.

**Comment by Bradamant3** [comment]
@makocchi-git sorry to take so long to finish this one up, but we need to close unmerged bc the fix is already in, in PR #8663. Thanks for understanding, and for all your other great help!

**Pull request closed without merging**
