### PR TITLE
Updated and added translation for starter page

### PR DESCRIPTION
**Pull request by alexzimmer96**
This PR translates some headlines on the german starter page as mentioned in #19791. I've also updated the list of recent events and switched to the personal salutation.

### CODE REVIEW

**Comment by sftim** [comment]
Thanks for this @alexzimmer96 !

**Comment by sftim** [comment]
@kubernetes/sig-docs-de-reviews could you take a look at these changes?

**Comment by mkorbi** [comment]
Thank you @alexzimmer96 
Could you please squash the commit so we have one clean commit? 
/lgtm

**Comment by alexzimmer96** [comment]
Hi @mkorbi 
i just squashed the commits. Excuse the delay.

**Comment by mkorbi** [comment]
thank you
/lgtm
/approve

**Pull request merged**
