### PR TITLE
WIP: docs updates for KEP-4193: bound service account token improvements

### PR DESCRIPTION
**Pull request by munnerz**
Placeholder PR for KEP-4193: bound service account token improvements

* https://github.com/kubernetes/enhancements/issues/4193
* https://github.com/kubernetes/enhancements/pull/4141
* https://github.com/kubernetes/kubernetes/pull/120780

### CODE REVIEW

**Comment by katcosgrove** [comment]
Hi, @munnerz! v1.29 Docs Lead here. Please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday 14th November 2023. Thank you!

**Comment by katcosgrove** [comment]
Hi, @munnerz! Just dropping by to remind you that the deadline for docs PRs to be ready for review is tomorrow, November 14. Is there anything we can help you with to get this PR ready?

**Comment by enj** [comment]
I have opened #43958 since I cannot edit this PR.

**Comment by liggitt** [comment]
/close

in favor of https://github.com/kubernetes/website/pull/43958

**Pull request closed without merging**
