### PR TITLE
Rebuild docs to reflect new guide changes

### PR DESCRIPTION
**Pull request by castrojo**
Move docs out of an imported directory and into the root because we
don't want the imported/ string to be user-visible in the URL.
Correct missing reference to KEP files inside community.yml because the file moved.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7210)

### CODE REVIEW

**Comment by tengqm** [comment]
Please help check and fix the CI errors.
Everything else looks good to me though I have a question regarding the contents.
Were the contents "imported" from the community project?
Should we avoid replicate these guides by referencing the "master copy"?
Keeping things synced across projects would be difficult.

**Comment by chenopis** [comment]
@castrojo Make sure there is a `title` in the front matter of all of the imported docs. Also, Update `/_data/imported.yml` to reflect the updated doc paths.

**Comment by castrojo** [comment]
Ok I'll need to PR the existing documents and then reimport and then come back to this. Thanks!

**Comment by heckj** [comment]
/cc chenopis - not sure why it didn't assign earlier from @Bradamant3 comment
@castrojo looks like there's still a pending merge conflict, so stashing a /hold on this as well. Any reviewer please remove when there's no merge conflict

/hold

**Comment by chenopis** [comment]
@castrojo Do you need help w/ this, or was this taken care of in a different PR?

**Comment by castrojo** [comment]
Sorry I don't have any more time to commit to this.

**Pull request closed without merging**
