### PR TITLE
[pt-br] Add docs/reference/using-api/client-libraries.md

### PR DESCRIPTION
**Pull request by daniso123**
fixes the issue that looks like it was abandoned: [pt-br] Translate client-libraries.md #36016

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by MrErlison** [comment]
Hi @daniso123 

I just spotted a slightly elder PR that translated the same file, which means that this PR is a duplicate of #36016

In my opinion it would be great for us to merge the prior one (to honor and to respect the first contributor).

---

Acabei de ver um PR um pouco mais velho que traduziu a mesma página, o que significa que este PR é uma duplicata de #36016 

Seria ótimo para nós mesclarmos o anterior (para honrar e respeitar o primeiro colaborador).

**Comment by daniso123** [comment]
I'm having problems signing the CLA but I'm already in contact with support

**Comment by stormqueen1990** [comment]
/retitle [pt-br] Add docs/concepts/workloads/pods/init-containers.md

**Comment by stormqueen1990** [comment]
/retitle [pt-br] Add docs/reference/using-api/client-libraries.md

**Comment by stormqueen1990** [comment]
Hi there, @daniso123 👋

Could you please remove the `init-containers.md` file from this PR, since we already have a dedicated PR for that file? (#39193)

Thanks in advance!

**Pull request closed without merging**
