### PR TITLE
[hi] Localize /en/docs/reference/glossary/pod-disruption.md

### PR DESCRIPTION
**Pull request by Aayush987**
Signed-off-by: Aayush <aayushsharma47163@gmail.com>

Fixes: #37536
Please review and suggest any changes if needed.

### CODE REVIEW

**Comment by bishal7679** [comment]
Hey @Aayush987 your test checking are getting failed for wrong commit message where `[]` is not allowed to use
push one empty commit by this command
```bash
git commit --allow-empty -m "your message"
```

**Comment by Aayush987** [comment]
> Hey @Aayush987 your test checking are getting failed for wrong commit message where `[]` is not allowed to use. You can try below method which might fix this issue push one empty commit by this command
> 
> ```shell
> git commit --allow-empty -m "your message"
> ```

Hi @bishal7679 , I have done as you mentioned but the tests are still failing.

**Comment by divya-mohan0209** [comment]
Hey @Aayush987 , I can still see the previous commit. Please could you squash both your commits & retry with a fresh commit message?

**Comment by Aayush987** [comment]
> Hey @Aayush987 , I can still see the previous commit. Please could you squash both your commits & retry with a fresh commit message?

I am closing this pr and opening a new one , as it gets some error on my local system.

**Pull request closed without merging**
