### PR TITLE
Move sass OWNERS to source instead of output

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR iterates on #10198 by moving OWNERS from `resources/` to `assets/sass/`.

The reason for the move is that `resources/` holds the output generated from source files in `assets/sass`. Better to make and approve fixes upstream!

/assign @lucperkins 
/cc @alexcontini

### CODE REVIEW

**Comment by zacharysarah** [comment]
@alexcontini 👋 Are you currently a member of the K8s organization? It doesn't look like you're [showing up](https://github.com/orgs/kubernetes/people?utf8=%E2%9C%93&query=alexcontini).

**Comment by tengqm** [comment]
/lgtm

Pending approval based on org membership checking.

**Comment by zacharysarah** [comment]
**Note:** I'm using repo admin permissions to merge this PR. This is a rare case and shouldn't be common, _especially_ when it's my own PR.

This PR has been [reviewed and approved](https://github.com/kubernetes/website/pull/10215#issuecomment-419456472), but the changes in permissions across folders with different inheritance in `OWNERS`hip make this PR difficult to merge via Prow.

**Pull request merged**
