### PR TITLE
Fix a missing markdown syntax to enable external link

### PR DESCRIPTION
**Pull request by gurrpi**

### CODE REVIEW

**Comment by gurrpi** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

CLA signed.

**Comment by pjhwa** [comment]
@gurrpi 컨트리뷰션 감사합니다!

타겟 브랜치를 master 가 아닌 dev-1.18-ko.8 로 변경해주시기 바랍니다.
dev-1.18-ko.8에서 fix하고 금주안에 master로 merge 하면 될 것 같습니다.

**Comment by gurrpi** [comment]
@pjhwa 타겟 브랜치 변경하였습니다.

소스 브랜치 리베이스 하는 도중에 붙은 엉뚱한 label들이 몇개있네요..:)

**Comment by pjhwa** [comment]
감사합니다!

/lgtm

**Pull request merged**
