### PR TITLE
Fixed a typo in word container

### PR DESCRIPTION
**Pull request by adriancuadrado**

### CODE REVIEW

**Comment by adriancuadrado** [comment]
I signed it

**Review by Arhell — COMMENTED** [review]
more info about CLA, check please
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by RA489** [comment]
> I signed it

/check-cla

**Comment by adriancuadrado** [comment]
I signed it

**Comment by kbhawkey** [comment]
Hi @adriancuadrado .
All contributors need a valid CLA? Have you checked if your credentials match?

**Comment by adriancuadrado** [comment]
@kbhawkey I am trying to sign the contributor license agreement again because I am not sure I did back then, but I am having trouble resending the CLA email:

https://identity.linuxfoundation.org/projects/cncf

image

Once I click the "Send message" button this happens:

image

How do I contact the site administrator?

**Comment by adriancuadrado** [comment]
You can see in the green rectangle a message stating that A Contributor License Agreement has been sent to my email address, but I have nothing in my inbox.

**Comment by adriancuadrado** [comment]
Besides, in the "Edit" tab I can confirm that my email is correct and the same used in all my commits:

image

**Comment by adriancuadrado** [comment]
According to this I logged in with my GitHub account, I don't understand what the problem could be:

image

**Comment by jimangel** [comment]
Hey there! @adriancuadrado, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by adriancuadrado** [comment]
> Hey there! @adriancuadrado, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

@jimangel I tried following the instructions from that link.
1. I click in the individual signup link here:

image

2. Then I press this link:

image

3. I press the "Log in with Github" button (even though I already have sign up):

image

4. I enter my credentials...

image

5. And then I get this "Access denied" screen, which I guess is because I laready signed up with my github account earlier:

image

6. When I return to the screen in step 2, I see this:

image

7. When I check my inbox, I see no email there (not even in the spam folder) so I can't sign the CLA.

**Comment by kbhawkey** [comment]
Hi @adriancuadrado .
I suggest you reach out to CNCF about the CLA.
I plan on closing this PR. You can reopen this PR at any time or open a new PR.
/close

**Pull request closed without merging**
