### PR TITLE
fix typo that is semantically important

### PR DESCRIPTION
**Pull request by regentov**
tag => PullPolicy is:

use "latest" => "Always"
use nothing => "Always"
use any but "latest" => "IfNotPresent"

and if it is so - this string should be corrected

### CODE REVIEW

**Comment by regentov** [comment]
> CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify
Registered. Replying. Please verify.

**Comment by sftim** [comment]
/check-cla

If this doesn't work, make sure that the email address that represents you as a CLA signatory matches your committer email address and your email address as known to GitHub.

**Comment by jihoon-seo** [comment]
It makes sense. 😊
/lgtm

**Comment by regentov** [comment]
So what can I do for this request to become approved?

**Pull request merged**
