### PR TITLE
Docs update for k8s 1.31 regarding Service trafficDistribution

### PR DESCRIPTION
**Pull request by gauravkghildiyal**
Previews:

- https://deploy-preview-46973--kubernetes-io-main-staging.netlify.app//docs/concepts/services-networking/service/#trafic-distribution
- https://deploy-preview-46973--kubernetes-io-main-staging.netlify.app//docs/reference/networking/virtual-ips/#traffic-distribution
- https://deploy-preview-46973--kubernetes-io-main-staging.netlify.app//docs/reference/command-line-tools-reference/feature-gates/

Code changes for promotion to beta: https://github.com/kubernetes/kubernetes/pull/125838
KEP: https://github.com/kubernetes/enhancements/issues/4444

/sig network

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [WIP] Docs update for k8s 1.31 regarding Service trafficDistribution

**Comment by Princesso** [comment]
Hello @gauravkghildiyal :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday July 16th 2024 18:00 PST. Thank you!

**Comment by Princesso** [comment]
Hi @gauravkghildiyal, a gentle reminder that tomorrow is the deadline for having your Docs PR ready for review. Please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before tomorrow, Tuesday, July 16th, 2024 18:00 PST.

**Comment by gauravkghildiyal** [comment]
This is ready for review!

**Comment by tengqm** [comment]
/approve
/hold
Please confirm that the feature-gates file is the only file that needs a change following this upgrade to Beta, and then lift the hold.

**Comment by tengqm** [comment]
@gauravkghildiyal Please provide the link to the upstream code change, thanks.

**Comment by gauravkghildiyal** [comment]
> @gauravkghildiyal Please provide the link to the upstream code change, thanks.

Hi @tengqm, updated the PR description with the same. Also, here's the requested links:

Code changes for promotion to beta: https://github.com/kubernetes/kubernetes/pull/125838
KEP: https://github.com/kubernetes/enhancements/issues/4444

**Comment by gauravkghildiyal** [comment]
Confirming https://github.com/kubernetes/website/pull/46973#issuecomment-2229590879

/unhold

**Pull request merged**
