### PR TITLE
Update install-kubectl-linux.md

### PR DESCRIPTION
**Pull request by yashwanth-mannem**
Issue:
sudo apt-get update
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.
Fix:
Replace https://apt.kubernetes.io/ in "Add the Kubernetes apt repository:" section with http://packages.cloud.google.com/apt/
Get:1 http://packages.cloud.google.com/apt kubernetes-xenial/main amd64 kubectl amd64 1.23.3-00 [8929 kB]
Fetched 8929 kB in 2s (4545 kB/s)
Selecting previously unselected package kubectl.
(Reading database ... 28645 files and directories currently installed.)
.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/website/pull/31776#issuecomment-1043174794

**Comment by divya-mohan0209** [comment]
@yashwanth-mannem : Any update on signing the CLA?

**Comment by zacharysarah** [comment]
@yashwanth-mannem 👋🏻 Please feel free to `/reopen` when you're ready to continue.

/close

**Pull request closed without merging**
