### PR TITLE
TLS is Transport Layer Security; not level

### PR DESCRIPTION
**Pull request by crquan**
See https://en.wikipedia.org/wiki/Transport_Layer_Security

### CODE REVIEW

**Comment by ericchiang** [comment]
/lgtm
/approve

You'll need to sign the CLA though

**Comment by crquan** [comment]
ok,

**Comment by makoscafee** [comment]
Hi @crquan care to sign CLA so this can be merged?

**Comment by crquan** [comment]
> Hi @crquan care to sign CLA so this can be merged?

ok; sure

**Comment by crquan** [comment]
No; the signing CLA process does not work, see the picture it does not take any valid names /cc @makoscafee @ericchiang

image

**Comment by nikhita** [comment]
@crquan is it the username that's shown as invalid?

cc @idvoretskyi

**Comment by nikhita** [comment]
@crquan Linux Foundation Helpdesk should be able to help you here - https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting

**Comment by tengqm** [comment]
@crquan Please try follow instructions [here](https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting) to debug your CLA status if you have already signed it.

**Comment by crquan** [comment]
No, that troubleshooting site recommend to login to report issues, but the issues is unable to login

I am seeing different issues when trying to login on different days, today this is a different one

image

I am asking is there an easy and alternative way to sign the paperwork?   like something traditionally, sign a paper document, scan and email it to an email address?

**Comment by crquan** [comment]
is there an easy and alternative way to sign the paperwork? like something traditionally, sign a paper document, scan and email it to an email address?

I think it's this site ( https://identity.linuxfoundation.org ) never worked, it is BROKEN

**Comment by sftim** [comment]
Looks like this is ready for approval.

**Pull request merged**
