### PR TITLE
Fix Bengali localization strings

### PR DESCRIPTION
**Pull request by sftim**
* Ensure that `i18n/bn.toml` is really a symlink
* Start out with an empty (commented out) list of strings. This will fall back to the English original.

### CODE REVIEW

**Comment by sftim** [comment]
GitHub doesn't show it, but there is a typechange to `i18n/bn.toml` as part of this PR. Check the changes out locally if you want to confirm that.

**Comment by mitul3737** [comment]
Tracking issue : #31677

**Pull request merged**
