### PR TITLE
Add Garbage Collection to Glossary

### PR DESCRIPTION
**Pull request by daminisatya**
#5993

### CODE REVIEW

**Comment by zparnold** [comment]
Yep, this will be great once GarbageCollection docs are merged. @daminisatya are they already merged? I'd like to merge this second so that we don't have a pointer to nothing on the website 😄

**Comment by Rajakavitha1** [comment]
/close 
@daminisatya Please feel free to open this PR after the PR for Garbage Collection docs are merged.

**Comment by daminisatya** [comment]
@Rajakavitha1 Sure!! Thank you :) @zparnold

**Pull request closed without merging**
