### PR TITLE
Update cheatsheet.md

### PR DESCRIPTION
**Pull request by mdsowmya**
Have added command to scale the existing replicaset

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@mdsowmya 
Pls sign the CLA in order for the PR to be reviewed.

**Comment by bradtopol** [comment]
Thank you @mdsowmya for your contribution. Please sign the CLA so we can accept your PR for review.
/assign

**Review by Aut0R3V — APPROVED** [review]

**Comment by kbhawkey** [comment]
:wave:  @mdsowmya .
Would you verify that your GitHub account username/email matches your CLA information?

**Comment by kbhawkey** [comment]
Hi @mdsowmya .
Can you sign the CLA or do you have questions about the CLA?

**Comment by kbhawkey** [comment]
Hi @mdsowmya .
I am closing this pull request.
You can reopen this PR to continue to work on the changes.
Reach out if you need help to sign the CLA.
/close

**Pull request closed without merging**
