### PR TITLE
Signposting added in /docs/home to redirect users to /training

### PR DESCRIPTION
**Pull request by divya-mohan0209**
Signposting added in /docs/home to redirect users to /training.

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
@sftim : Please could you review and see if this is what you had in mind?

**Comment by divya-mohan0209** [comment]
@sftim : Have made the changes as requested to training. Do let me know if there's anything else amiss.

**Comment by sftim** [comment]
The markdown looks fine. Since this was my suggestion I'll let someone else review the overall change.

**Pull request merged**
