### PR TITLE
[bn] Update OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by asem-hamid**
joining the sig-docs-bn reviewer and approver team.

/cc @a-mccarthy

### CODE REVIEW

**Comment by a-mccarthy** [comment]
@Imtiaz1234 @mitul3737 @rajibmitra If you are around, please also review this PR for adding @asem-hamid as a review/approver for the Bengali localization 🚀

**Review by rajibmitra — APPROVED** [review]

**Review by mitul3737 — APPROVED** [review]

**Review by Imtiaz1234 — APPROVED** [review]

**Comment by mitul3737** [comment]
@asem-hamid  kindly refer to @sftim . Only he can approve this one.

**Comment by asem-hamid** [comment]
@sftim  Please approve this PR .

**Comment by sftim** [comment]
> @asem-hamid kindly refer to @sftim . Only he can approve this one.

I don't think that's right.

**Comment by sftim** [comment]
I am _one_ of the people who can approve this. However, let's check something. @asem-hamid are you joining as a reviewer or an approver? (there's a difference)

**Comment by asem-hamid** [comment]
@sftim both

**Comment by asem-hamid** [comment]
@sftim both

**Review by sftim — COMMENTED** [review]
Reasonable to do this

/approve

**Pull request merged**
