### PR TITLE
[zh] remove content/zh/docs/tasks/debug-application-cluster/audit.md

### PR DESCRIPTION
**Pull request by JarHMJ**
content/zh/docs/tasks/debug-application-cluster/audit.md has moved to content/zh/docs/tasks/debug/debug-cluster/audit.md

### CODE REVIEW

**Comment by tengqm** [comment]
MOVE the file, rather than DELETE it, please

**Comment by howieyuen** [comment]
https://github.com/kubernetes/website/pull/33372/files

**Comment by JarHMJ** [comment]
> we have done some work duplicated... https://github.com/kubernetes/website/pull/33372/files

oh, your pr is better than me! Please review this pr https://github.com/kubernetes/website/pull/33372/files @tengqm 
and I will close my pr

**Pull request closed without merging**
