### PR TITLE
fix table content

### PR DESCRIPTION
**Pull request by Arhell**
issue #22157 & #21795

### CODE REVIEW

**Comment by Arhell** [comment]
review pages
https://deploy-preview-22167--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kube-apiserver/
https://deploy-preview-22167--kubernetes-io-master-staging.netlify.app/docs/setup/release/notes/

**Comment by kbhawkey** [comment]
The rendered pages look corrected. I'll look at the source changes in a bit.

**Comment by tengqm** [comment]
At first sight, the change is wary. However, I cannot recall a case where we don't what table cells to be wrapped... so
/lgtm

**Comment by celestehorgan** [comment]
/approve 

Thanks for your great work on web stuff, @Arhell 🎉

**Pull request merged**
