### PR TITLE
[ja] fix the translation of the word container.

### LINKED ISSUE #37097: [ja] fix the translation of the word container.
**This is a Feature Request**

**What would you like to be added**

In Japanese guideline, "container" should be translated to "コンテナ", but some translations are "コンテナー".
Consistent translations are desirable.
(This is commented in #36853)

**Why is this needed**
The translations of container are not consistent.

**Comments**
Currently, the following should be fixed.
```
$ grep -r "コンテナー" ./website --include="*.md"
./website/content/ja/docs/tasks/run-application/run-replicated-stateful-application.md:`mysql:5.7`イメージを使って一時的なコンテナーを実行 し、`mysql`クライアントバイナリーを実行します。
./website/content/ja/docs/concepts/architecture/garbage-collection.md:{{<glossary_tooltip text="kubelet" term_id="kubelet">}}は未使用のイメージに対して5分ごとに、未使用のコンテナーに対して1分ごとにガベージコレクションを実行します。
./website/content/ja/docs/concepts/architecture/garbage-collection.md:未使用のコンテナーとイメージのガベージコレクションのオプションを設定 するには、[設定ファイル](/docs/tasks/administer-cluster/kubelet-config-file/)を使用してkubeletを調整し、[`KubeletConfiguration`](/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration)リソースタイプを使用してガベージコレクションに 関連するパラメーターを変更します。
./website/content/ja/docs/concepts/architecture/garbage-collection.md:  * `MaxContainers`: クラスターが持つことができるデッドコンテナーの最大数。`0`未満に設定すると無効化されます。
./website/content/ja/docs/concepts/architecture/garbage-collection.md:`MaxPerPodContainer`と`MaxContainer`は、Podごとのコンテナーの最大数(`MaxPerPodContainer`)を保持すると、グローバルなデッドコンテナの許容合計(`MaxContainers`)を超える状況で、互いに競合する可能性があります。
./website/content/ja/docs/concepts/architecture/garbage-collection.md:この状況では、kubeletは`MaxPodPerContainer`を調整して競合に対処します。最悪のシナリオは、`MaxPerPodContainer`を1にダウングレードし、最も古いコンテナーを削除することです。
./website/content/ja/docs/concepts/workloads/controllers/deployment.md:Deploymentのロールアウトは、DeploymentのPodテンプレート(この場合`.spec.template`)が変更された場合にのみトリガーされます。例えばテンプレートのラベルもしくはコンテナーイメージが更新された場合です。Deploymentのスケールのような更新では、ロールアウトはトリガーされません。
./website/content/ja/docs/concepts/workloads/controllers/deployment.md:設定ファイルの利用に関する情報は[アプリケーションのデプロイ](/ja/docs/tasks/run-application/run-stateless-application-deployment/)を参照してください。コンテナーの設定に関しては[リソースを管理するためのkubectlの使用](/ja/docs/concepts/overview/working-with-objects/object-management/)を参照してください。
./website/content/ja/docs/concepts/workloads/controllers/deployment.md:`.spec.minReadySeconds`はオプションのフィールドで、新しく作成されたPodが利用可能となるために、最低どれくらいの秒数コンテナーがクラッシュすることなく稼働し続ければよいかを指定するものです。デフォルトでは0です(Podは作成されるとすぐに利用可能と判断されます)。Podが利用可能と判断された場合についてさらに学ぶために[Container Probes](/ja/docs/concepts/workloads/pods/pod-lifecycle/#container-probes)を参照してください。
./website/content/ja/docs/concepts/configuration/secret.md:コンテナーはSecretのデータをSSH接続を確立するために使用することができます。
./website/content/ja/docs/concepts/configuration/manage-resources-containers.md:そのコンテナに4GiBの`メモリー`制限を設定すると、kubelet(お よび{{< glossary_tooltip text="コンテナランタイム" term_id="container-runtime" >}}) が制限を適用します。ランタイムは、コンテナーが設定済み のリソース制限を超えて使用するのを防ぎます。例えば、コンテナ内のプロセスが、許容量を超えるメモリを消費しようとすると、システムカーネルは、 メモリ不足(OOM)エラーで、割り当てを試みたプロセスを終了します。
./website/content/ja/docs/concepts/configuration/manage-resources-containers.md:制限は、違反が検出されるとシステムが介入するように事後的に 、またはコンテナーが制限を超えないようにシステムが防ぐように強制的に、実装できます。
./website/content/ja/docs/concepts/storage/persistent-volumes.md:Podにrawブロックデバイスを追加する場合は、マウントパスの代わりにコンテナ  でデバイスパスを指定します。
./website/content/ja/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md:In-treeボリュームプラグインに関連付けられたコードは、コアKubernetesコードベースの一部として提供されます。In-treeボリュームプラグインのデプロイでは、追加のスクリプトをインストールしたり、個別のコンテナ化されたプラグインコンポーネントをデプロイしたりする必要はありません。これらのプラグインは、ストレージバックエンドでのボリ ュームのプロビジョニング/プロビジョニング解除とサイズ変更、Kubernetesノードへのボリュームのアタッチ/アタッチ解除、Pod内の個々のコンテナーへのボリュームのマウント/マウント解除を処理できます。次のIn-treeプラグインは、Windowsノードをサポートしています。:
./website/content/ja/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md:| オーバーレイ(KubernetesのWindows用のオーバ ーレイネットワークは *アルファ* 段階です) | コンテナには、外部のvSwitchに接続されたvNICが付与されます。各オーバーレイネットワークは、カスタムIPプレフィックスで定義された独自のIPサブネットを取得します。オーバーレイネットワークドライバーは、VXLANを使用してカプセル化します。 | 外 部ヘッダーでカプセル化されます。 | [Win-overlay](https://github.com/containernetworking/plugins/tree/master/plugins/main/windows/win-overlay)、Flannel VXLAN (win-overlayを使用) | win-overlayは、仮想コンテナーネットワークをホストのアンダーレイから分離する必要がある場合に使用する必要があります(セキュリティ上の理由など)。データセンター内のIPが制限されている場合に、(異なるVNIDタグを持つ)異なるオーバーレイネットワーク でIPを再利用できるようにします。このオプションには、Windows Server 2019で[KB4489899](https://support.microsoft.com/help/4489899)が必要です 。|
./website/content/ja/docs/reference/_index.md:* [kubelet](/docs/reference/command-line-tools-reference/kubelet/) - 各ノード上で動作する最も重要なノードエージェントです。kubeletは一通りのPodSpecを受け取り、コンテナーが実行中で正常であることを確認します。
```

/language ja
/assign

### PR DESCRIPTION
**Pull request by s-kawamura-w664**
This PR changes "コンテナー" to "コンテナ".
The Japanese guideline is [here](https://kubernetes.io/ja/docs/contribute/localization/#%E9%A0%BB%E5%87%BA%E5%8D%98%E8%AA%9E).

Fixes #37097

### CODE REVIEW

**Review by t-inu — APPROVED** [review]
/lgtm

**Comment by s-kawamura-w664** [comment]
Thank you for review and lgtm.
/assign @inductor

**Comment by nasa9084** [comment]
good, thank you!
/assign
/approve

**Pull request merged**
