### PR TITLE
Update kubelet-config.v1beta1.md

### PR DESCRIPTION
**Pull request by tu1h**
Clean outdated links and point them to the correct place.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@tu1h  It appears that this PR includes changes to files across multiple languages English and Chinese. However, docs follows different processes for each localization, and we typically don't accept pull requests that impact multiple languages simultaneously. I would recommend modify only the primary website content (which means only English content) initially with this PR. After the merge of the English content, we could create separate pull request for the remaining language(s). I hope this suggestion is helpful.

**Comment by dipesh-rawat** [comment]
Explicit hold until this PR only covers one language
(Ok to unhold once that's done)
/hold

**Comment by sftim** [comment]
Also: watch out in case you update an [automatically generated](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#auto-generated-edit-notice) page.

**Comment by tengqm** [comment]
Please note that this page is auto-generated from the upstream source code. The expected fix should be proposed to the upstream kubernetes/kubernetes project, otherwise the change here will be overridden next time.
Please check the [guidelines here](https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/).

/close

**Pull request closed without merging**
