### PR TITLE
fix some spelling mistakes in ./data/announcements/scheduled.yaml

### PR DESCRIPTION
**Pull request by CKchen0726**
```release-notes
fix some spelling mistakes in ./data/announcements/scheduled.yaml
```

### CODE REVIEW

**Review by irvifa — COMMENTED** [review]
/approve

**Review by irvifa — COMMENTED** [review]
/approve

**Comment by kbhawkey** [comment]
Hi @CKchen0726 .
This data file (announcement) is not active right now. The change requires approval by a steering committee member.

Could I get a review/approval by a steering comm. member?
/cc @kubernetes/steering-committee

**Review by nikhita — APPROVED** [review]
/approve

**Pull request merged**
