### PR TITLE
Customize sidebar tree style

### PR DESCRIPTION
**Pull request by tengqm**
This PR tweaks the sidebar navigator:

- slightly decrease font size by 10% for page links
- indent each level of list by 6px
- disallow title wrapping
- allow the list to be scrolled horizontally

This file is copied from Docsy source with customization lines highlighted with "/* website customization */".

### CODE REVIEW

**Comment by tengqm** [comment]
Visual effect illustrated:

image

**Comment by kbhawkey** [comment]
The nav. tree does not render as expected:
https://deploy-preview-28582--kubernetes-io-main-staging.netlify.app/docs/home/

**Comment by tengqm** [comment]
@kbhawkey Did you click and expand the section titles?

**Comment by jihoon-seo** [comment]
A screenshot of mine:
image

**Comment by tengqm** [comment]
Abandoned, since the problem has been addressed by #28521 in a different way.

**Pull request closed without merging**
