### PR TITLE
Fixes Issue with the header nav under Documentation tab

### LINKED ISSUE #12826: Issue with the header nav under Documentation tab
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Navigate from the home page of the website to Documentation which will land you over here. 

screen shot 1940-12-06 at 8 03 16 pm

One can observe extra padding under the navigation tabs. But it's the not same when you navigate to the Setup/ any other tab other than Home. Refer the below screenshot. 

screen shot 1940-12-06 at 8 03 34 pm

**Proposed Solution:**

Navbar padding (Home tab) must be consistent with other tabs. 

**Page to Update:**
https://kubernetes.io/docs/home/

### PR DESCRIPTION
**Pull request by Sai-Adarsh**
Fixes kubernetes#12826, Updates the SASS.

* Checked the documentation tab along with other tabs like blog, partners, case study. works fine.
* Checked padding both in mobile and desktop view. works fine.

It is seen that netlify doesn't reflect the changes in the preview. @lucperkins is fixing it with the Netlify team.

### CODE REVIEW

**Comment by Sai-Adarsh** [comment]
@xiangpengzhao @Rajakavitha1 thoughts?

**Comment by xiangpengzhao** [comment]
Sorry for delay :)
/cc @lucperkins

**Comment by tfogo** [comment]
Looks like this is similar to #12840. @Sai-Adarsh could you please take a look at what @kbhawkey said in that PR?

/cc @kbhawkey

**Comment by tengqm** [comment]
Looks like this has been addressed by #14807. Feel free to reopen if that is not the case.

**Pull request closed without merging**
