### PR TITLE
need to add minikube ip in host file

### PR DESCRIPTION
**Pull request by rrajadevops**
need to add minikube ip in host file instead of ingress ip
example: 192.168.99.100 hello-world.info

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by DanyC97** [comment]
@rrajadevops can you please sign the CLA first ?

**Comment by bradtopol** [comment]
Hi @rrajadevops Thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by Rajakavitha1** [comment]
Hi @rrajadevops Thank you for your contribution. Please sign the CLA so we can accept your PR for review. https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by cody-clark** [comment]
Hi @rrajadevops. Thanks for your PR! Since we're not getting any responses, I'm going to go ahead and close this PR. Please reopen it once you've signed the CLA, and I'll be happy to review it.

> 📝 Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

/close

**Pull request closed without merging**
