### PR TITLE
Add jihoon-seo to sig-docs-ko-reviews

### PR DESCRIPTION
**Pull request by jihoon-seo**
I'd like to apply for sig-docs-ko-reviews role.
I've met the [requirements for reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer):

* 20+ PRs merged: https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Ajihoon-seo
* 5+ PRs reviewed: https://github.com/kubernetes/website/pulls?q=type%3Apr+reviewed-by%3Ajihoon-seo
* Member of Kubernetes for 3+ months

Thanks!

/assign @seokho-son 
(According to the steps in https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/#becoming-a-reviewer)

### CODE REVIEW

**Comment by seokho-son** [comment]
Welcome @jihoon-seo :)

As the SIG-Docs Korean l10n lead, I am happy to approve this PR.
/lgtm

@jimangel please check this PR. (I am not an approver of this file)
@jihoon-seo is very active Korean l10n contributor.

**Comment by sftim** [comment]
/hold
Happy with this to happen, but please first make this change to https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml, and then apply the equivalent update here.

**Comment by seokho-son** [comment]
@jihoon-seo Please check https://github.com/kubernetes/org/issues/1190 
@sftim we would better to update the procedure becoming a reviewer written here. https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/#becoming-a-reviewer

**Comment by seokho-son** [comment]
@jihoon-seo kubernetes/org#1190 is a wrong reference. (it is for becoming org member)

https://github.com/kubernetes/org/pull/2399 seems the appropriate reference. 
@jihoon-seo could you open similar PR ? :)

**Comment by jihoon-seo** [comment]
@sftim @seokho-son 
I posted a PR: https://github.com/kubernetes/org/pull/2830

FYI: Force-push: Updated the order (ABC ascending), syncing with https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml

PTAL! 😊

**Comment by seokho-son** [comment]
/hold cancel
@jihoon-seo has been added in https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml as a sig-docs-ko-reviews
This PR looks good to go :)

**Comment by jihoon-seo** [comment]
@seokho-son @sftim Thank you all ! :)

**Pull request merged**
