### PR TITLE
added feature  hindi community page

### PR DESCRIPTION
**Pull request by harish343**
Fixes : https://github.com/kubernetes/website/issues/39497
New feature has been added communtiy page in hindi please review it and ping me if any changes had to be made on this repository.

### CODE REVIEW

**Comment by amolmote** [comment]
Look like issue is raised for particular community page, why you have made changes in too many files @harish343

**Comment by harish343** [comment]
I added community page for a particular language 
what changes can I made to fix this

**Comment by amolmote** [comment]
> I added community page for a particular language what changes can I made to fix this

content of this `content/hi/community/code-of-conduct.md` you have kept as it is.

**Comment by amolmote** [comment]
you have added some unwanted files too in this PR @harish343

**Comment by harish343** [comment]
okay I will remove some unwanted files.

**Comment by jihoon-seo** [comment]
The author of this PR opened other PRs #39663 & #39672 to resolve the issue, so let me close this one.
/close

**Pull request closed without merging**
