### PR TITLE
promote GRPCContainerProbe to beta

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
/sig node
KEP https://github.com/kubernetes/enhancements/issues/2727

No changes in the feature itself so far. Just promotion to beta

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
It took me a while to trace this to KEP and related issues in hope to find whether the upstream code has been changed. It turned out to be no.

**Comment by tengqm** [comment]
/hold cancel
Great that the upstream code is in.

**Comment by reylejano** [comment]
Code in PR https://github.com/kubernetes/kubernetes/pull/108522 has merged
/lgtm

**Pull request merged**
