### PR TITLE
Consolidate YAML files [part-13]

### PR DESCRIPTION
**Pull request by tengqm**
This PR deals with YAML files referenced by the following two topics:
- concepts:object management
- concepts:service networking

When scanning references to the YAML files to be moved, some trivial
editings were applied to the markdown files. None of this editing should
break the build or ruin the doc otherwise.

### CODE REVIEW

**Comment by tengqm** [comment]
Links to previews:

- https://deploy-preview-9377--kubernetes-io-master-staging.netlify.com/docs/concepts/overview/object-management-kubectl/declarative-config/
- https://deploy-preview-9377--kubernetes-io-master-staging.netlify.com/docs/concepts/overview/working-with-objects/kubernetes-objects/
- https://deploy-preview-9377--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
- https://deploy-preview-9377--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/connect-applications-service/
- https://deploy-preview-9377--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/dns-pod-service/
- https://deploy-preview-9377--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/ingress/

**Comment by steveperry-53** [comment]
@tengqm I was trying to fix a merge conflict in examples_test.go, and I got the file messed up. I've seen this type of error before, but I've never understood it. Can you see what's wrong? And can you fix the merge conflict? Thanks.

test/examples_test.go:563:3: missing ',' before newline in composite literal
test/examples_test.go:566:14: missing ',' in composite literal
test/examples_test.go:570:3: missing ',' before newline in composite literal
test/examples_test.go:573:4: missing ',' before newline in composite literal
test/examples_test.go:575:69: missing ',' before newline in composite literal
test/examples_test.go:577:11: missing ',' in composite literal
test/examples_test.go:578:2: expected operand, found 'for'
test/examples_test.go:584:4: missing ',' in composite literal
test/examples_test.go:585:7: missing ',' in composite literal
test/examples_test.go:586:5: expected operand, found 'if'
test/examples_test.go:587:6: expected operand, found 'if'

**Comment by tengqm** [comment]
@steveperry-53 I'm onto it.

**Pull request merged**
