### PR TITLE
WIP: [KEP-1748]: Add capacity planning documentation

### PR DESCRIPTION
**Pull request by dgrisonnet**
Placeholder PR for https://github.com/kubernetes/enhancements/issues/1748.

### CODE REVIEW

**Comment by tengqm** [comment]
@dgrisonnet Where are we now?

**Comment by dgrisonnet** [comment]
I am still working on the doc and should be done with it soon

**Comment by mickeyboxell** [comment]
@dgrisonnet As a friendly reminder, tomorrow is the **Docs complete — All PRs reviewed and ready to merge** deadline. Please do what you can to get your doc merged by the end of the day tomorrow.

**Comment by dgrisonnet** [comment]
Hey @mickeyboxell, I've been swamped for the last couple of weeks and won't be able to deliver that doc and get the reviews on time. How do you advise proceeding?

**Comment by dgrisonnet** [comment]
This feature doesn't have a gate, so it should not confuse the users: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1748-pod-resource-metrics/README.md#feature-enablement-and-rollback

Pushing the documentation to a later date should only make that feature less visible to the users.

**Pull request closed without merging**
