### PR TITLE
Merged master release 1.16

### PR DESCRIPTION
**Pull request by daminisatya**

### CODE REVIEW

**Comment by zacharysarah** [comment]
@daminisatya It looks like the conflict resolution broke the PR.

**Comment by daminisatya** [comment]
@jimangel Do you have any idea on how I can fix this error? 

```
11:20:54 PM: Error: Error building site: "/opt/build/repo/content/zh/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md:436:6": failed to extract shortcode: shortcode "capture" has no .Inner, yet a closing tag was provided

````

**Comment by zacharysarah** [comment]
@daminisatya 
> Do you have any idea on how I can fix this error?

That looks like an error in Chinese content, specifically:
[`content/zh/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md`](https://github.com/kubernetes/website/blob/master/content/zh/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md)

@kubernetes/sig-docs-zh-owners ☝️

**Comment by xichengliudui** [comment]
According to pr #17341 ，the contents of this file [mysql-wordpress-persistent-volume.md](https://github.com/kubernetes/website/blob/master/content/zh/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md)  should be copied directly from English.

**Comment by kbhawkey** [comment]
It looks like an extra (?) capture was added on line 427. Look at the diff of the file.

**Comment by daminisatya** [comment]
Another error

```
Error: Error building site: "/opt/build/repo/content/en/docs/tasks/federation/set-up-placement-policies-federation.md:26:1": failed to render shortcode "capture": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/code.html:14:16": execute of template failed: template: shortcodes/code.html:14:16: executing "shortcodes/code.html" at <readFile $filename>: error calling readFile: runtime error: invalid memory address or nil pointer dereference
````

**Comment by kbhawkey** [comment]
> 
> 
> Another error
> 
> ```
> Error: Error building site: "/opt/build/repo/content/en/docs/tasks/federation/set-up-placement-policies-federation.md:26:1": failed to render shortcode "capture": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/code.html:14:16": execute of template failed: template: shortcodes/code.html:14:16: executing "shortcodes/code.html" at <readFile $filename>: error calling readFile: runtime error: invalid memory address or nil pointer dereference
> ```

Either the file (arg to shortcode) does not exist any more or the shortcode should be changed from `code` to `codenew`.

**Comment by Colstuwjx** [comment]
@daminisatya  Just one note about this PR, you may need to also carry this PR #17976 since we need to update the HUGO_VERSION in netlify.toml as well.

**Comment by daminisatya** [comment]
@Colstuwjx sure!

**Pull request closed without merging**
