### PR TITLE
edit in index.html

### PR DESCRIPTION
**Pull request by 12ahmedhamdy**
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7216)

### CODE REVIEW

**Comment by tengqm** [comment]
@12ahmedhamdy need CLA signing for merge.

**Comment by Bradamant3** [comment]
/hold
@12ahmedhamdy did you forget to add something to this PR? It looks incomplete, or as though you possibly added text in the wrong place on the page, or maybe didn't mean to push this particular commit. Please take a look -- right now it adds unneeded content o the heading on the k8s.io landing page.

**Comment by heckj** [comment]
hi @12ahmedhamdy - I'm assuming this is you learning how to make a pull request. I'm going to go ahead and close this, please re-open if you make updates that we can merged to improve the docs!

**Pull request closed without merging**
