### PR TITLE
typo: windwos

### PR DESCRIPTION
**Pull request by MittWillson**

### CODE REVIEW

**Comment by MittWillson** [comment]
done

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by MittWillson** [comment]
> Pls sign the CLA in order for the PR to be reviewed.
> 
> more info
> 
> https://github.com/kubernetes/community/blob/master/CLA.md

any possible to use the Github privacy email? or it be sure the real email for commits

**Comment by jimangel** [comment]
Hey there! @MittWillson, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by MittWillson** [comment]
> Hey there! @MittWillson, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

Hi, So sorry reply you so late, this commit pushed with github private email, maybe that's way can't verify CLA, is there a way to bind private email to CLA?

**Comment by tengqm** [comment]
@MittWillson I'm closing this one. Please try submit the PR using the email you used for CLA and see if things will work.

**Pull request closed without merging**
