### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by akanshujamwal**
I update the license, in my changing I highlight the section part in the license which is helpful to user to read.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@akanshujamwal
Pls sign the CLA in order for the PR to be reviewed.

**Comment by akanshujamwal** [comment]
> @akanshujamwal
> Pls sign the CLA in order for the PR to be reviewed.

- [ I sign up in your portal please help me to how I sign CLA ]

**Review by Arhell — COMMENTED** [review]
@akanshujamwal  You can make your emails match up in one of two ways:

1. Login to the [CLA site](https://identity.linuxfoundation.org/projects/cncf) and change it to match what you use as your default email address on your GitHub account
2. Change your default email address on your GH account to the same one you used to sign the CLA.

**Comment by akanshujamwal** [comment]
> @akanshujamwal You can make your emails match up in one of two ways:
> 
> 1. Login to the [CLA site](https://identity.linuxfoundation.org/projects/cncf) and change it to match what you use as your default email address on your GitHub account
> 2. Change your default email address on your GH account to the same one you used to sign the CLA.

I done all this changes. I login using github account

**Comment by sftim** [comment]
@akanshujamwal, once you've signed the CLA we'll be very happy to review this proposed change! Welcome.

**Comment by mrbobbytables** [comment]
We are not participating in hacktoberfest
/close

**Pull request closed without merging**
