### PR TITLE
Format invalid date in blog posts

### LINKED ISSUE #8860: blog article missing date
Some articles miss `date` header, so we get `0001-01-01` articles as below:

invalid-date-on-blog

### PR DESCRIPTION
**Pull request by tnir**
Closes #8860

### CODE REVIEW

**Comment by tnir** [comment]
While 1 post without date remains in this PR (see below), it should be fixed by #8866.

## before
invalid-date-on-blog

## after
invalid-date-on-blog-5-fixes

**Comment by MasayaAoyama** [comment]
/triage duplicate #8830 #8833
https://github.com/kubernetes/website/pull/8830
https://github.com/kubernetes/website/pull/8833

**Pull request merged**
