### PR TITLE
Update device-plugins.md

### PR DESCRIPTION
**Pull request by xuhz**
add link to Xilinx FPGA device plugin

### CODE REVIEW

**Comment by jaredbhatti** [comment]
Please sign the CLA

**Comment by xuhz** [comment]
Our company(Xilinx) has e-signed the CLA. 
Will the CLA check be passed automatically or anything else from my side required?

**Comment by bradtopol** [comment]
@xuhz Thank you for your contribution. Please sign the CLA so we can accept your PR for review.

**Comment by Rajakavitha1** [comment]
@xuhz Thanks for your PR. Please see: https://github.com/kubernetes/community/blob/master/CLA.md#how-do-i-sign for instructions in case your company has already signed a CLA.

**Comment by xuhz** [comment]
I assigned it (actually Xilinx signed it) already

Username | First Name | Last Name | E-mail | Roles | Member since |  
-- | -- | -- | -- | -- | -- | --
songc-xil | Chuck | Song | songc@xilinx.com | organization manager | 2 weeks 5 days ago | edit remove
xuhz | Brian | Xu | brianx@xilinx.com | organization manager | 2 weeks 5 days ago | edit remove

**Comment by Rajakavitha1** [comment]
> I assigned it (actually Xilinx signed it) already
> 
> Username	First Name	Last Name	E-mail	Roles	Member since	 
> songc-xil	Chuck	Song	[songc@xilinx.com](mailto:songc@xilinx.com)	organization manager	2 weeks 5 days ago	edit remove
> xuhz	Brian	Xu	[brianx@xilinx.com](mailto:brianx@xilinx.com)	organization manager	2 weeks 5 days ago	edit remove

Can you please check if you received an email https://github.com/kubernetes/community/blob/master/CLA.md#5-look-for-an-email-indicating-successful-signup if not is suggest you check: https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting

**Comment by xuhz** [comment]
I think I know what the issue is.
I tried to sign the CLA twice -- In the first one, I assigned myself as the signer on behalf of our company, then I figured out I couldn't that. Then in the second one, our VP e-signed on behalf of the company and I was assigned as one of the manager to manage the group.

I can't delete the first one -- which is still pending and should be deleted. That's why you think I still need to e-sign the CLA.

How to delete the first one?

First Name: 
Brian
Last Name: 
Xu
Full Name: 
Brian Xu
Groups: 
CNCF - Xilinx Inc.
CNCF - Xilinx Inc
History
Site user for
3 weeks 21 min

**Comment by Rajakavitha1** [comment]
> I think I know what the issue is.
> I tried to sign the CLA twice -- In the first one, I assigned myself as the signer on behalf of our company, then I figured out I couldn't that. Then in the second one, our VP e-signed on behalf of the company and I was assigned as one of the manager to manage the group.
> 
> I can't delete the first one -- which is still pending and should be deleted. That's why you think I still need to e-sign the CLA.
> 
> How to delete the first one?
> 
> First Name:
> Brian
> Last Name:
> Xu
> Full Name:
> Brian Xu
> Groups:
> CNCF - Xilinx Inc.
> CNCF - Xilinx Inc
> History
> Site user for
> 3 weeks 21 min

Thank you @xuhz !!!
Could you please log an issue here: https://sso.linuxfoundation.org/login?state=g6Fo2SBpeFNJYUlLcHp0X3NMOURkWG5WSWROWGlCRDFrd2Z4aaN0aWTZIDBaVk1IRVpZR2RiVjdlakEyY2J3X1F3Q2xINkNFM25to2NpZNkgNE1iTWxDcFhvb0RvTlEwMlRvUXY5eXB3Tk96aWY1MTY&client=4MbMlCpXooDoNQ02ToQv9ypwNOzif516&protocol=samlp

 If you encounter any problems signing the CLA, log a ticket with the Linux Foundation ID group through the Linux Foundation Support Site.

Should you have any issues using the LF Support Site, send a message to the backup e-mail support address login-issues@jira.linuxfoundation.org

Someone from the CNCF will respond to your ticket to help.

**Comment by xuhz** [comment]
The e-sign takes effect now.
Please recheck it,
thanks!

**Comment by Rajakavitha1** [comment]
Thanks for your PR @xuhz!!!!
/approve

**Pull request merged**
