### PR TITLE
[wip] networking(windows): kernelspace proxy mode

### PR DESCRIPTION
**Pull request by profnandaa**
- see discussion details here https://github.com/kubernetes/website/pull/38243
- this is WIP to document the specific inner details of the kernelspace mode for kube-proxy.

### CODE REVIEW

**Comment by sftim** [comment]
Great, this is a good starting point. Feel free to either amend the latest commit or to add another one - either is fine.

**Comment by sftim** [comment]
How's this going @profnandaa ?

**Comment by profnandaa** [comment]
@sftim -- I've not been able to have much progress on it yet, give me one more week to report back.

**Comment by jsturtevant** [comment]
@profnandaa Is this still on your radar?

**Comment by divya-mohan0209** [comment]
Hello @profnandaa , thank you so much for taking up the initiative to document this. We sincerely appreciate your efforts.  However, since there has been a lack of activity on the PR from your side since February, I'll be closing off the PR. If you do find the bandwidth to work on this, please feel free to resume by issuing a /reopen command. We can pick this up right where you left it off.
/close

**Comment by profnandaa** [comment]
Noted, thanks. Sorry I couldn't get substantial information but will keep watching the issue and re-open in case I get the info.

**Pull request closed without merging**
