### PR TITLE
[zh] doc: fix typo

### PR DESCRIPTION
**Pull request by kylinxiang70**
modify "成为" to "称为"

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/28974#issuecomment-881296137

**Comment by reylejano** [comment]
Hi @kylinxiang70 , this PR has been open for over 50 days with no action to [sign the CLA](https://github.com/kubernetes/website/pull/28974#issuecomment-881296137). If there's no action within 7 days, a PR wrangler may close this PR.

**Comment by reylejano** [comment]
Hi @kylinxiang70 , since there has been no action to sign the CLA, I'm closing this PR.
Feel free to re-open when you have signed the CLA

/close

**Pull request closed without merging**
