### PR TITLE
Fix broken link in fr/docs/concepts/services-networking/ingress/

### LINKED ISSUE #31535: [fr] Broken link in docs/concepts/services-networking/ingress/
Hi. 

On this section of the french Ingress documentation, https://kubernetes.io/fr/docs/concepts/services-networking/ingress/#la-ressource-ingress, there seems to be a dead link at _la specification de la ressource ingress_. 

French version seems outdated in comparaison with the english one. 

Cheers 🇫🇷

### PR DESCRIPTION
**Pull request by praveenrewar**
Update the link at _la specification de la ressource ingress_ in `fr/docs/concepts/services-networking/ingress/`

Fixes #31535

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hello @praveenrewar , please could you sign the CLA?

**Comment by praveenrewar** [comment]
Hi @divya-mohan0209, I have signed the CLA as a corporate member, and I am  currently waiting for approval from my organisation.

**Comment by divya-mohan0209** [comment]
@praveenrewar : Please ping when the CNCF CLA has been signed. Will sign off

**Comment by praveenrewar** [comment]
I signed it

**Comment by praveenrewar** [comment]
> I signed it

cc @divya-mohan0209

**Review by anubha-v-ardhan — COMMENTED** [review]
LGTM
unholding this PR (https://github.com/kubernetes/website/pull/31539#issuecomment-1023232152)
/remove-hold
Thankyou @praveenrewar :)

**Pull request merged**
