### PR TITLE
Moving windows containers user guide out of /setup/production-environment/

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

Part of #31428 

/hold 
We want to merge changes related to #31428 at the same time.

### CODE REVIEW

**Comment by RA489** [comment]
@marosset Please rebase your PR.

**Comment by marosset** [comment]
/hold
We want all the PRs that break up /modify https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/
See https://github.com/kubernetes/website/pull/31851#issuecomment-1079162797

**Comment by nate-double-u** [comment]
Hi @marosset, I don't think this PR should target `dev-1.24`

**Comment by marosset** [comment]
/close
I will squash the commits and create a single PR with all of the related changes targeting main.

**Pull request closed without merging**
