### PR TITLE
Merged main into dev 1.24

### PR DESCRIPTION
**Pull request by nate-double-u**
Week 3 update to bring main into dev-1.24 branch.

### CODE REVIEW

**Comment by nate-double-u** [comment]
Errors relate to the EasyCLA — Missing CLA Authorization.

/cc @JamesLaverack, FYI
/cc @jlbutler @sftim @reylejano

**Comment by JamesLaverack** [comment]
> Errors relate to the EasyCLA — Missing CLA Authorization.
> 
> /cc @JamesLaverack, FYI /cc @jlbutler @sftim @reylejano

EasyCLA seems happy enough? Am I misunderstanding?

**Comment by nate-double-u** [comment]
Commit [15bc0c7](https://github.com/kubernetes/website/pull/31490/commits/15bc0c762152e8ea881f74774d3c8656a04c7409) has an error X on it, relating to the EasyCLA. It's not an error we generally need to concern ourselves with as EasyCLA is a work in progress, but it _is_ an error, so I bring it up so folks know why it's failing.

**Comment by nate-double-u** [comment]
If there were other kinds of errors then we may need to take action to correct them.

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
