### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by ptux**
- put describtion of controller in the same paragraph
- keep consistency with subtitle (Extension Patterns)

Releated PR:

https://github.com/kubernetes/website/pull/30337

### CODE REVIEW

**Comment by tengqm** [comment]
Thanks.
/lgtm
/approve

**Comment by ptux** [comment]
@chenrui333
@tengqm 

Could you guys be my sponsors to get the membership of Kubernetes?
Here are my contributions:

https://github.com/kubernetes/website/commits/main?author=ptux

**Comment by tengqm** [comment]
@ptux Yes, I can sponsor you, but I hope you can focus on contributing more rather than obtaining the membership.

**Comment by ptux** [comment]
@tengqm 

I think I could review PRs for fixing typos, minor changes.
That's why I want to become a member. (:

**Pull request merged**
