### PR TITLE
Update notes.md

### PR DESCRIPTION
**Pull request by stewart-yu**
fix the ugly yaml format

### CODE REVIEW

**Comment by MengZn** [comment]
I am not sure what's different with #10670

**Comment by MengZn** [comment]
In addition to fixing the disgusting yaml format

**Comment by stewart-yu** [comment]
/assign @Bradamant3 
PTAL thanks

**Comment by Bradamant3** [comment]
sorry, @stewart-yu, we've merged `dev-1.13` to master for the release, with squash, so this PR probably needs to be closed and reopened. If you can rebase, great -- either way!

**Pull request closed without merging**
