### PR TITLE
add Squarespace case study

### PR DESCRIPTION
**Pull request by alexcontini**
*I am going to remove all the extra css files and just consolidate all css for case studies into one file (style_case_studies.css). Once this file is live I will update the rest of the case study html files and remove the css files

### CODE REVIEW

**Comment by bradtopol** [comment]
Hi @zacharysarah I'm not sure what our process is for reviewing use cases.  Thoughts?

**Comment by zacharysarah** [comment]
@bradtopol Great question. We don't really handle them, so I'm not sure what we can provide apart from smoke testing the netlify build to make sure everything looks more or less right. 

@alexcontini What's your preferred workflow here?

@kbarnard10, @SarahKConway, @natekartchner, any thoughts? 👆

**Comment by zacharysarah** [comment]
@alexcontini Bump 👆

**Comment by alexcontini** [comment]
@zacharysarah sorry for the delay! missed this before. 

So we have been reviewing them internally (@SarahKConway has been approving them) and then I have been adding them here, I always review the preview page and will fix if there are any issues, but this one - https://deploy-preview-8124--kubernetes-io-master-staging.netlify.com/case-studies/squarespace/ looks good to me, so I would say merge if there are no issues on your end?

(sorry if I misunderstood the question at all)

**Comment by chenopis** [comment]
The [preview](https://deploy-preview-8124--kubernetes-io-master-staging.netlify.com/case-studies/squarespace/) looks good to me, but doesn't it need to be added to the [case studies landing page](https://deploy-preview-8124--kubernetes-io-master-staging.netlify.com/case-studies/)?

**Pull request closed without merging**
