### PR TITLE
Feature Blog Post 2nd of april

### PR DESCRIPTION
**Pull request by mkorbi**
This PR includes the feature blog post for the 2nd of April, publishing at 10 AM PT.

Authors are @robscott @cmluciano 

/hold
/assign @karenhchu

### CODE REVIEW

**Comment by mkorbi** [comment]
Hey @castrojo @mrbobbytables maybe you can have already a look at this blog which should be released tomorrow.

Thanky you!

**Comment by mrbobbytables** [comment]
From a technical standpoint, everything looks good -- we'll need to adjust dates based on when https://github.com/kubernetes/website/pull/19987 lands.

**Comment by castrojo** [comment]
Ok so the schedule is delayed a day, everything looks good, can you adjust the publishing date to this Friday, 3 April, and then we'll lgtm/approve? Thanks for your patience!

**Comment by karenhchu** [comment]
With the Topography Manager blog being delayed two days at this point, we're going to have to double-up on blogs one of the days this week (we have a total of 4). Can we keep this scheduled for Thursday? I'm working with Claudia on publishing the Serverside Apply 2 blog today.

**Comment by castrojo** [comment]
Sounds good to me, I'll be standing by!

**Comment by mkorbi** [comment]
I'm good to go

**Pull request merged**
