### PR TITLE
Switch StatefulSet tutorial to HTTP manifest source

### PR DESCRIPTION
**Pull request by sftim**
`kubectl` can apply manifests direct from the web; let's teach that.

Split out from PR https://github.com/kubernetes/website/pull/42767

[original](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/)
[preview](https://deploy-preview-43984--kubernetes-io-main-staging.netlify.app/docs/tutorials/stateful-application/basic-stateful-set/)

### CODE REVIEW

**Review by kumarankit999 — COMMENTED** [review]
have fixed now, What others say!!!

**Comment by sftim** [comment]
> have fixed now, What others say!!!

???

I don't understand this comment, I'm afraid.

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/lgtm

[Preview Page](https://deploy-preview-43984--kubernetes-io-main-staging.netlify.app/docs/tutorials/stateful-application/basic-stateful-set/)

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks for this fix, @sftim !
/approve

**Pull request merged**
