### PR TITLE
Update content/en/docs/concepts/extend-kubernetes/_index.md

### LINKED ISSUE #37607: Broken link on Extending Kubernetes page
**Problem:**
The text [FlexVolume](https://kubernetes.io/docs/concepts/storage/volumes#flexvolume) on [link](https://kubernetes.io/docs/concepts/extend-kubernetes/#storage-plugins) is not working, it should point to these https://kubernetes.io/docs/concepts/storage/volumes/#flexvolume-deprecated
Check the page [Extending Kubernetes](https://kubernetes.io/docs/concepts/extend-kubernetes/#storage-plugins) for the problem.

**Page to Update:**
https://kubernetes.io/docs/concepts/extend-kubernetes/#storage-plugins

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the link on the text **FlexVolume** to https://kubernetes.io/docs/concepts/storage/volumes/#flexvolume-deprecated and not to this [link](https://kubernetes.io/docs/concepts/storage/volumes/#flexvolume).

/kind document
/assign
/language en

### PR DESCRIPTION
**Pull request by kadtendulkar**
Fixes #37607

Updated page [Extending Kubernetes](https://kubernetes.io/docs/concepts/extend-kubernetes/#storage-plugins)

### CODE REVIEW

**Review by Rishit-dagli — APPROVED** [review]
/lgtm

**Comment by windsonsea** [comment]
Another solution is to provide an anchor to:
```
### flexVolume (deprecated)  {#flexvolume}
```
in the file
```
content/en/docs/concepts/storage/volumes.md
```
In which 22 similar anchors have been added.

**Pull request merged**
