### PR TITLE
Update service.md

### PR DESCRIPTION
**Pull request by liu-xuewen**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@liu-xuewen 
Pls sign the CLA in order for the PR to be reviewed.

**Comment by tanjunchen** [comment]
I signed it
/retest
/check-cla

**Review by tanjunchen — COMMENTED** [review]
@liu-xuewen
Pls sign the CLA in order for the PR to be reviewed.

**Comment by baiyutang** [comment]
this PR can be close

**Pull request closed without merging**
