### PR TITLE
Update components.md the length should be all to keep consisdence

### PR DESCRIPTION
**Pull request by cyy8**
### Issue

Closes: #

### CODE REVIEW

**Comment by laoji2333** [comment]
666

**Comment by utkarsh-singh1** [comment]
Thanks @cyy8 for the PR, can you edit description to explain the changes to the PR.

**Comment by MoonShadowV** [comment]
> Thanks @cyy8 for the PR, can you edit description to explain the changes to the PR.

I don't think this is a proper change。It will change the render content of the doc。https://github.com/kubernetes/website/pull/47414/files
image

And there is no need to render a full definition.

**Comment by utkarsh-singh1** [comment]
@cyy8 @MoonShadowV , don't think there is too much change.

**Comment by utkarsh-singh1** [comment]
Changed ->

**Comment by utkarsh-singh1** [comment]
Original ->

Screenshot_20240809_142259

**Comment by utkarsh-singh1** [comment]
Also @cyy8 we have whole section on cloud-controller-manager, and this page is introductory.

**Comment by utkarsh-singh1** [comment]
https://kubernetes.io/docs/concepts/architecture/cloud-controller/

**Comment by MrNocole** [comment]
> Original ->
> 
> Screenshot_20240809_142259

She's just trying make some unnecessary PR.and make it widely known to earn benefits.I just found her announcing.
also see: https://github.com/kubernetes/website/pull/47399

**Comment by TommY1ng** [comment]
不是吧，又提了一个。。

**Comment by gracefullliam** [comment]
初学就别来影响人家维护者了 @cyy8 ，好好沉淀沉淀吧

**Comment by boris1993** [comment]
> 初学就别来影响人家维护者了 @cyy8 ，好好沉淀沉淀吧

她并不是“初学者”，她就一蹭流量的，看她小红书主页就知道了。

**Comment by FZUGGMU** [comment]
> https://kubernetes.io/docs/concepts/architecture/cloud-controller/

No need to check any merge request from her. She is just a joker who wants to write something on Little Red Book
(like twitter) and let people to browse her blog. In fact, she never write even one lane code in the past.

**Comment by natalisucks** [comment]
This PR and the following conduct is unnecessary – this PR will be closed
/close

**Comment by grubwithu** [comment]
好似

**Comment by jieqiyue** [comment]
人家小仙女刚学k8s，提了个pr，你们为什么要这样说他啊，你们这些郭楠

**Comment by mango-svip** [comment]
Please don't mention meaningless PR by looking at someone's share please

**Comment by natalisucks** [comment]
@cyy8 I understand that you're looking to contribute to Kubernetes for the first time, which is great! However, from the comments here and the unfriendly conduct from other users, I've chosen to close this PR. We have reported the behaviour by others in this thread to our Code of Conduct committee for further review by them, to try and stop this kind of behaviour by others on work like yours in the future.

I'd recommend you take a read of the [contributing guide for Kubernetes documentation](https://kubernetes.io/docs/contribute/docs/), which also looks at the idea of [trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits), and why we generally refrain from accepting them. Take your time to look at a whole page and check for improvements, rather than relatively "trivial" additions like this one. If you can't find any other improvements, that's also fine to state in your reasoning!

There should also be information in the PR descriptions so that reviewers like myself can understand why you made the change. This is good open source etiquette and you can see a lot of examples of this in current open PRs across the project.

Please feel free to join us in the [Kubernetes Slack](https://slack.k8s.io/) over in #sig-docs and ask any questions that you might have.

**Pull request closed without merging**
