### PR TITLE
feat: turn nodelocaldns image to svg

### PR DESCRIPTION
**Pull request by bweston92**
Converted image from JPG to SVG as suggested by @sftim  https://github.com/kubernetes/website/pull/17944/files#r353917193

How it looks in browser.

Screenshot 2020-05-29 at 10 28 03

### CODE REVIEW

**Comment by bweston92** [comment]
I apologise it seems trailing spaces have been removed, do you want me to add them back?

**Comment by bweston92** [comment]
Link to section: https://deploy-preview-21289--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/nodelocaldns/#architecture-diagram

**Comment by sftim** [comment]
Hi @bweston92 
You asked in https://github.com/kubernetes/website/pull/21289#issuecomment-635878386 about trailing spaces

Could you add those back? I recommend not to touch whitespace except in a commit specifically for revising it.

The SVG preview looks good to me.

**Pull request merged**
