### PR TITLE
update file

### PR DESCRIPTION
**Pull request by 4change**

### CODE REVIEW

**Comment by kundan2707** [comment]
@4change  sign CLA

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by utkarsh-singh1** [comment]
Related Doc - https://kubernetes.io/zh-cn/docs/tasks/configmap-secret/managing-secret-using-kubectl/

**Comment by sftim** [comment]
@4change, would you be willing to sign the CLA?

See https://github.com/kubernetes/website/pull/38115#issuecomment-1342549096

**Comment by tengqm** [comment]
CLA not signed and the author is not responding.
/close

Feel free to reopen when CLA issue is resolved first.

**Pull request closed without merging**
