### PR TITLE
Install kubectl command error document modification

### PR DESCRIPTION
**Pull request by opencmit2**
Modify the error document for installing kubectl command

image

### CODE REVIEW

**Review by aj11anuj — CHANGES_REQUESTED** [review]
1. Thank you for raising a PR, and welcome to K8s. Before your PR can get reviewed, make sure you have signed CLA.
2. Unfortunately, we can't proceed further with your PR, because it's a duplicate of #43464. Make sure you read contributors guidelines properly.

**Comment by utkarsh-singh1** [comment]
@opencmit2 , same PR as #43393, #43464 and #43430

**Comment by utkarsh-singh1** [comment]
@opencmit2 , PR #43393 is already under review process, however if you want to contribute you can find open issues in https://github.com/kubernetes/website/issues.

**Comment by tengqm** [comment]
/close
dup

**Pull request closed without merging**
