### PR TITLE
fixing the correct word from "anda" to "kamu"

### PR DESCRIPTION
**Pull request by wahyuni-pj**
Fixing word for first try to contributed from workshop in Openinfra Day Surabaya, Indonesia

/language id
/cc @girikuncoro

### CODE REVIEW

**Comment by girikuncoro** [comment]
Thank you for your very first contribution to Kubernetes, congrats and welcome to community! 🎉 

/lgtm
/approve

**Comment by wahyuni-pj** [comment]
I signed it

**Comment by wahyuni-pj** [comment]
"I signed it"

**Comment by girikuncoro** [comment]
@wahyuni-pj thanks for figuring this out, congrats on your first contribution!

**Pull request merged**
