### PR TITLE
[zh] sync docs/tasks/run-application/horizontal-pod-autoscale.md

### PR DESCRIPTION
**Pull request by howieyuen**
fix https://github.com/kubernetes/website/issues/24803

### CODE REVIEW

**Comment by howieyuen** [comment]
@tengqm sorry, I delete the source branch by mistake, and cannot reopen the original pr with the same branch name, so I have to open a new PR instead. If there is a solution without opening a new PR, please let me know, thank you.

**Comment by tengqm** [comment]
/approve

Your PR is still on the website repo, so you could have recovered it easily:

[hint 1](https://garrytrinder.github.io/2020/05/recover-pr-after-accidentally-deleting-source-branch)
[hint 2](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally)

**Comment by howieyuen** [comment]
> /approve
> 
> Your PR is still on the website repo, so you could have recovered it easily:
> 
> [hint 1](https://garrytrinder.github.io/2020/05/recover-pr-after-accidentally-deleting-source-branch)
> [hint 2](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally)

**Comment by howieyuen** [comment]
> > /approve
> > Your PR is still on the website repo, so you could have recovered it easily:
> > [hint 1](https://garrytrinder.github.io/2020/05/recover-pr-after-accidentally-deleting-source-branch)
> > [hint 2](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally)

thanks, looks like easily to recover, but there are two same PR existing...

**Comment by howieyuen** [comment]
@tanjunchen

**Review by tanjunchen — COMMENTED** [review]
/lgtm

**Pull request merged**
