### PR TITLE
Reference glossary definitions in “Connect a Front End to a Back End Using a Service” 

### PR DESCRIPTION
**Pull request by sftim**
Add references from https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/ to relevant glossary definitions

Whilst I'm at it: mark shell snippets as shell

~Relevant to #12554~

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@sftim Thanks for the PR. This still does not address #12554. There is another relevant https://github.com/kubernetes/website/issues/12639 that might help the developers with the link to the .yaml files.

**Comment by Rajakavitha1** [comment]
@sftim also providing a reference to glossary definitions for every occurrence of the term defies the purpose of a glossary list. and makes the terms quite repetitious.

"In writing, especially professional documents, you will be using words that are unfamiliar with your reader. If an unfamiliar word in your text is used a minimal amount of times you can describe the meaning right next to the usage. When you use unfamiliar words throughout the entire text, you must place a definition in the glossary because it can get quite repetitious to continue to state the definition throughout the entire text. In professions, ie: the sciences, your readers may not understand the definition to fancy scientific terms. Using a glossary enables you to provide a definition that readers can easily locate if they need to."

**Comment by sftim** [comment]
The way I see it, this project has indeed placed the definition in a glossary. Hence, referring to it.

I'd like to understand more about the disadvantages of adding these tooltips / hyperlinks, so that I can make sure the changes I suggest are worthwhile.

**Comment by Rajakavitha1** [comment]
> 
> 
> The way I see it, this project has indeed placed the definition in a glossary. Hence, referring to it.
> 
> I'd like to understand more about the disadvantages of adding these tooltips / hyperlinks, so that I can make sure the changes I suggest are worthwhile.

I am sure it is always nice to have a tooltip for the terms that have definitions. However, adding a tooltip to all occurrences of the term in the entire documentation may be a very tedious task.

**Comment by Rajakavitha1** [comment]
@zparnold  Please take a look at this PR.

**Comment by Rajakavitha1** [comment]
> 
> 
> The way I see it, this project has indeed placed the definition in a glossary. Hence, referring to it.
> 
> I'd like to understand more about the disadvantages of adding these tooltips / hyperlinks, so that I can make sure the changes I suggest are worthwhile.

Some of the disadvantages of using tooltips extensively:
a. The text will be readable with the flow which is not favorable in this context because the content of the hint interrupts the flow of the information and data displayed in the main content.
b. From accessibility point of view - Tooltips do not usually appear on mobile operating systems, because there is no cursor, unless you have a touch screen with a fancy digital pen which allows for hover to be triggered, you won’t be able to see the hint inside the tooltip.

**Pull request merged**
