### PR TITLE
WIP: KEP-4193: placeholder

### PR DESCRIPTION
**Pull request by munnerz**
https://github.com/kubernetes/enhancements/issues/4193#issuecomment-2192409543

### CODE REVIEW

**Comment by a-mccarthy** [comment]
@munnerz Hello, just following up, it looks like this is a docs PR for 1.31?  

cc: @Princesso

**Comment by a-mccarthy** [comment]
Hello @munnerz can you give an update on how this PR is coming along? I'm not sure if its a blog or docs PR. In either case, it should have content added as soon as possible so that it can get through the review process before the release. thanks!

cc: @Princesso

**Comment by Princesso** [comment]
Hello @munnerz this PR is way past every deadline. It has not received any response or activity after numerous prompts from several teams. It is now at risk for Doc freeze. Please let us know if it is a doc or a blog. Thank you!

**Comment by sftim** [comment]
We **need** docs for the enhancement; a blog article is optional.

@kubernetes/sig-auth-leads - please do staff this work, it's part of what needs to happen to land the improvements in v1.31

**Comment by liggitt** [comment]
/close

in favor of https://github.com/kubernetes/website/pull/47283

**Pull request closed without merging**
