### PR TITLE
fix: update deprecated command in code example

### PR DESCRIPTION
**Pull request by Ananya2001-an**
Updated deprecated command to `kubectl exec [POD] -- [COMMAND]`

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please re-puch commit for restart netlify

**Comment by Shubham82** [comment]
Thanks @Ananya2001-an 
The preview looks good to me: https://deploy-preview-43115--kubernetes-io-main-staging.netlify.app/docs/tasks/debug/debug-application/get-shell-running-container/

/lgtm

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
