### PR TITLE
Translate glossary for PersistentVolume into Bahasa

### PR DESCRIPTION
**Pull request by habibrosyad**
/cc @girikuncoro @ariscahyadi

### CODE REVIEW

**Comment by habibrosyad** [comment]
Preview: https://deploy-preview-24088--kubernetes-io-master-staging.netlify.app/id/docs/reference/glossary/?storage=true#term-persistent-volume

**Review by ariscahyadi — COMMENTED** [review]
Thanks @habibrosyad for continous contribution! It is a very good translation.
/lgtm

**Pull request merged**
