### PR TITLE
Revise body of patch request in StatefulSet tutorial

### PR DESCRIPTION
**Pull request by PrashantDesale2004**
fixed body of patch request in StatefulSet tutorial
which was
kubectl patch statefulset web -p '{"spec":{"updateStrategy":{"type":"OnDelete"}}}'
To
kubectl patch statefulset web -p '{"spec":{"updateStrategy":{"type":"OnDelete","rollingUpdate":null}}}'
because most newbie of k8s will use minikube

### CODE REVIEW

**Review by PranitRout07 — COMMENTED** [review]
Hey can you explain what the updated command does and how it is different from the previous command ?

**Comment by PrashantDesale2004** [comment]
> Hey can you explain what the updated command does and how it is different from the previous command ?

it shows an error like  spec.updateStrategy.rollingUpdate field in the create step,in the case of a server like minikube. this command will resolve the error who use minikube in k8s and they can suffer same issue

**Comment by sftim** [comment]
Why is this the right change to make? I haven't seen evidence to convince me that it is.

We could maybe add a _second_ command that people should use when they use `minikube`. Without that context, people will wonder why they are setting `.spec.updateStrategy.rollingUpdate` and we aren't telling them.

**Comment by PrashantDesale2004** [comment]
> Why is this the right change to make? I haven't seen evidence to convince me that it is.
> 
> We could maybe add a _second_ command that people should use when they use `minikube`. Without that context, people will wonder why they are setting `.spec.updateStrategy.rollingUpdate` and we aren't telling them.

should keep old commmand as it is and add new command for minikube user?

**Comment by Ritikaa96** [comment]
> Why is this the right change to make? I haven't seen evidence to convince me that it is.
> 
> We could maybe add a _second_ command that people should use when they use `minikube`. Without that context, people will wonder why they are setting `.spec.updateStrategy.rollingUpdate` and we aren't telling them.

This sounds about right. I Agree with addition of a short note along with this updated command.
/remove lgtm

**Comment by reylejano** [comment]
I agree with another reviewer that a short note is better versus changing the command that is specific to minikube.
Although many people learning Kubernetes may use minikube, the docs are not specific to minikube
@PrashantDesale2004 , if you feel otherwise, feel free to reopen the PR with `/reopen` in a comment
/close

**Pull request closed without merging**
