### PR TITLE
Update CNCF Community Code of Conduct v1.3

### PR DESCRIPTION
**Pull request by ydFu**
The current upstream CNCF Code of Conduct has been updated to version 1.3. 
Therefore, in this pull request, we have incorporated the updates based on [CNCF Community Code of Conduct v1.3](https://github.com/cncf/foundation/blob/c79711b5127e2d963107bc1be4a41975c8791acc/code-of-conduct.md).

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Thanks

If you've got capacity for it, https://www.kubernetes.dev/community/code-of-conduct/ needs an update too.

**Review by divya-mohan0209 — COMMENTED** [review]
As Tim suggested, it'd be great to make the changes to the Kubernetes code of conduct, if you have the bandwidth.
/lgtm

**Comment by ydFu** [comment]
> Thanks
> 
> If you've got capacity for it, https://www.kubernetes.dev/community/code-of-conduct/ needs an update too.
Certainly, it would be my pleasure to assist with updating the information related to the Code of Conduct (COC). May I inquire about the specific repository path for the project?

**Review by sftim — COMMENTED** [review]
Thanks

/approve

**Pull request merged**
