### PR TITLE
feature added for issue #16771

### LINKED ISSUE #16771: Use tabs for “view your changes locally” in contributor guide
**This is a Feature Request**

**What would you like to be added**
Rewrite https://kubernetes.io/docs/contribute/intermediate/#view-your-changes-locally to put the two options (Hugo in a container / Hugo locally) in [tabs](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#tabs).

**Why is this needed**
Low-priority enhancement to make the documentation easier to read.

/kind feature

### PR DESCRIPTION
**Pull request by r4zorgeek**
Fixes #16771

### CODE REVIEW

**Comment by sftim** [comment]
This is for issue #16771

**Comment by r4zorgeek** [comment]
- Yea i'll fix it.

**Comment by sftim** [comment]
@r4zorgeek you can follow these very instructions to preview the changes locally and make sure that both tabs render OK

**Comment by r4zorgeek** [comment]
@sftim Hey I have fixed the issue and also previewed locally the tabs are rendering ok. Can you please review it.

**Comment by zacharysarah** [comment]
@r4zorgeek Thanks for the PR! ✨ 

/lgtm
/approve

**Pull request merged**
