### PR TITLE
[hi] Add content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md

### PR DESCRIPTION
**Pull request by arsheelsheikh**
Localizes
`[hi] Add content/hi/docs/setup/production-environment/windows/user-gu…`

### CODE REVIEW

**Comment by arsheelsheikh** [comment]
@anubha-v-ardhan

**Comment by anubha-v-ardhan** [comment]
/retitle [hi] Add content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md

**Comment by anubha-v-ardhan** [comment]
@arsheelsheikh Seems like some commits not related to this PR have crept in. Can you fix it

**Comment by arsheelsheikh** [comment]
> @arsheelsheikh Seems like some commits not related to this PR have crept in. Can you fix it
I don't know how did they come?!! How do I fix it

**Comment by arsheelsheikh** [comment]
@anubha-v-ardhan I think by mistake I have created normal PR and not the Draft PR, Is it OK or should I make a new one again

**Comment by anubha-v-ardhan** [comment]
Its okay, no need to make draft PRs anymore as we have the dev branch now.

**Comment by anubha-v-ardhan** [comment]
@arsheelsheikh Did you rebased against local `main` instead of `dev-1.22-hi.1`. Please refer [This thread](https://kubernetes.slack.com/archives/C1J0BPD2M/p1631535983093300) and implement either of the two solution proposed by @sftim or make a complete new fresh PR. Whichever is easier for you.

**Comment by divya-mohan0209** [comment]
@arsheelsheikh Are you still working on this PR? Or have you opened a new one to address comments by @anubha-v-ardhan ?

**Comment by divya-mohan0209** [comment]
@arsheelsheikh Could you please confirm if you're still working on the PR?

**Comment by arsheelsheikh** [comment]
@divya-mohan0209 yeah I'm so here my brach is already into `dev-1.22-hi.1` so what further needs to be done can you please guided me

**Review by habibrosyad — COMMENTED** [review]
@arsheelsheikh since this PR is for HI content I don't think you should include changes for EN and ID. You can remove changes in `content/en/docs/reference/kubectl/overview.md` and `content/id/docs/concepts/containers/runtime-class.md` from your PR.

**Comment by arsheelsheikh** [comment]
@habibrosyad  Thank You.
I have deleted `content/en/docs/reference/kubectl/overview.md` and `content/id/docs/concepts/containers/runtime-class.md` from the PR.

**Comment by anubha-v-ardhan** [comment]
Unfortunately, just deleting the files won't do. Please go through  https://github.com/kubernetes/website/pull/29684#issuecomment-918180101.

**Comment by habibrosyad** [comment]
@arsheelsheikh deleting files still count as changes. As you can [here](https://github.com/kubernetes/website/pull/29684/files), there are still 3 file changes. What I mean by removing changes was excluding those 2 unrelated changes (ID and EN) to your PR. At the end there should only 1 file changed (HI). Maybe you could just follow what @anubha-v-ardhan suggest.

**Comment by arsheelsheikh** [comment]
okay, I will make a new PR and tag you.

**Comment by habibrosyad** [comment]
I think this PR can be closed in favor of the new [PR](https://github.com/kubernetes/website/pull/29848).

**Comment by anubha-v-ardhan** [comment]
/close
in favour of #29848

**Pull request closed without merging**
