### PR TITLE
[zh]Sync content/zh/case-studies/squarespace

### PR DESCRIPTION
**Pull request by kinzhi**

### CODE REVIEW

**Comment by tengqm** [comment]
There is only an icon?

**Comment by kinzhi** [comment]
> There is only an icon?

Yes, the Icon is missing for the English document

**Comment by howieyuen** [comment]
> There is only an icon?

the icon is used to link the case study content, now cannot see "squarespace"  in [case study](https://kubernetes.io/zh/case-studies/) page.

**Comment by kinzhi** [comment]
I see. Thank you

**Comment by tengqm** [comment]
Then the ICON image is useless?

**Comment by howieyuen** [comment]
> Then the ICON image is useless?

only to redirect content, if icon is missed, we cannot see it in the arranged list

**Pull request merged**
