### PR TITLE
Remove extra wording

### PR DESCRIPTION
**Pull request by leo8a**

### CODE REVIEW

**Comment by mtardy** [comment]
This removes the typo with the double "the" in [k8s.io/docs/concepts/architecture/nodes](https://kubernetes.io/docs/concepts/architecture/nodes/#:~:text=the%20status%20of-,the%20the,-evicted%20pods%20as).

Thanks!
/lgtm

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by leo8a** [comment]
signed, thxs!

**Review by sftim — COMMENTED** [review]
Thanks

/approve

**Pull request merged**
