### PR TITLE
[ja] Updated Internal Load Balancer annotation for GCP

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/41091/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Comment by atoato88** [comment]
@Arhell 
This PR needs rebase. Could you do that?

**Review by Arhell — COMMENTED** [review]
@atoato88  done

**Review by nasa9084 — COMMENTED** [review]
/approve

**Pull request merged**
