### PR TITLE
Update and format the content

### PR DESCRIPTION
**Pull request by shavidissa**
- Added an intro to the `mysql-pv.yaml` file.
- Formatted the note.
- Added content on how to exit the MySQL client.
- Added a "for more information.." section under Updating and linked to [1] so that can get this info if they want to know how to update.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
> Help editing and submitting pull requests:  https://deploy-preview-9510--kubernetes-io-master-staging.netlify.com/docs/contribute/start/#submit-a-pull-request.
> Help choosing which branch to use, see
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by shavidissa** [comment]
Sorry, forgot to remove the "Please delete this note.." section before creating the PR.

**Comment by Bradamant3** [comment]
Nice changes! First-time contributors should not have to deal with BlackFriday markdown issues (additions to numbered list items), so I'll fix those up in the next day or two.

**Comment by zparnold** [comment]
@Bradamant3 , anything new here? Can I assist in any way?

**Comment by Hartmarken348** [comment]
9935

**Pull request closed without merging**
