### PR TITLE
[WIP] Update docs around CEL for Admission Control

### PR DESCRIPTION
**Pull request by cici37**

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [WIP] Update docs around CEL for Admission Control
Relevant to https://github.com/kubernetes/enhancements/issues/3488

**Comment by sftim** [comment]
This'd be where we document the changes for beta, including https://github.com/kubernetes/kubernetes/pull/119215

**Comment by cici37** [comment]
An update for doc team: I will be OOO hence @jiahuif and @alexzielenski will be updating the doc for KEP-3488 in separate PRs. 
Thank you!

**Comment by jpbetz** [comment]
/close
This is superseded by other docs PRs

**Comment by jiahuif** [comment]
included in #42220

**Pull request closed without merging**
