### PR TITLE
[ko] translate the glossary term cAdvisor

### PR DESCRIPTION
**Pull request by tonyhan18**
Glossary Term
cAdvisor

### CODE REVIEW

**Review by sftim — CHANGES_REQUESTED** [review]
There seem to be some unrelated commits in this PR. I recommend limiting the change to just the cAdvisor glossary entry.

**Comment by tonyhan18** [comment]
> Contributor

got it i'm gonna figure out

**Review by tonyhan18 — COMMENTED** [review]
It's done

**Comment by seokho-son** [comment]
Hi @tonyhan18 

This PR has two individual commits. (eviction, Advisor) I think the commit about eviction is a mistake. Please remove the commit from this PR. Also, #35899 is a similar case.

[[ko] translate the glossary term eviction](https://github.com/kubernetes/website/pull/35901/commits/538573343ce76199fc7a4b979261e364a8f811cb)

[[ko] translate the glossary term cAdvisor](https://github.com/kubernetes/website/pull/35901/commits/4e1d2bd0871905d656c76d42e247def6d80d00f0)

**Pull request closed without merging**
