### PR TITLE
Graduate efficient watch resumption to GA

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/enhancements/issues/1904

/assign @sftim

### CODE REVIEW

**Comment by sftim** [comment]
/unassign

I'm happy for to SIG Release Docs team and SIG API Machinery to collaborate on getting this one reviewed. My role so far was just to point out that an update was needed.

**Comment by tengqm** [comment]
/approve
The upstream change (kubernetes/kubernetes#10694) is now in.

**Pull request merged**
