### PR TITLE
Fix SVG text for blog article

### PR DESCRIPTION
**Pull request by mplzik**
This PR removes any stroke width configuration for the letters, making
it much thinner and easier to read.

See also: https://github.com/kubernetes/website/pull/43436

Signed-off-by: Milan Plzik <milan.plzik@grafana.com>

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
You might like to make the topmost line of text bold (and still drop the stroke width).

Even better: convert text to curves. That way it displays the same on every computer, pretty much.

**Comment by sftim** [comment]
/retitle Fix SVG text for blog article

**Comment by mplzik** [comment]
@sftim I made the image heading bold. As for transforming the font into curves, can do that but I'm slightly concerned about any kind of accessibility/machine readability of the image. Let me know what is your opinion.

**Comment by sftim** [comment]
For now, making the text into curves is what we want. We'll have the commit history if we find a better way and want to support improved accessibility.
(there are tools that can support both things well, but we don't use them yet)

**Comment by mplzik** [comment]
@sftim PTAL

**Comment by mplzik** [comment]
Also, looking at the raw XML, there's still `aria-label` attribute that retains the text; looks like the information can be recovered quite easily.

**Review by sftim — APPROVED** [review]
Thanks

/lgtm
/approve

**Pull request merged**
