### PR TITLE
Update README-fr.md

### PR DESCRIPTION
**Pull request by rmzturkmen**
On line 34, command install is written twice. It should be fixed as follows. "choco install make"

 Hi,
On line 34, the command 'install' is written twice. It should be fixed as follows. "choco install make"
Regards,
Ramazan

### CODE REVIEW

**Comment by rmzturkmen** [comment]
On line 34, command install is written twice. It should be fixed as follows. "choco install make"

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by rmzturkmen** [comment]
"I signed it"

**Comment by rmzturkmen** [comment]
/approve
/language tr (Turkish)
this is the translation of the English text into Turkish. It is not about your French text.

**Comment by rmzturkmen** [comment]
close #27513

**Comment by kbhawkey** [comment]
Hi @rmzturkmen .
Thanks for translating the site's README file to Turkish; however, we do not have a Turkish localization team.
If you would like to contribute the updates to the French README, the French localization team can review
the changes.
You can read more about localizing the Kubernetes documentation at https://kubernetes.io/docs/contribute/localization/.
Would you remove the Turkish README from this PR (perhaps you can save the changes for another PR) or open a new PR with the updates to the French README?

**Comment by jimangel** [comment]
@rmzturkmen echoing what @kbhawkey said, your work is appreciated and we'd be happy to help you start a localization team. However, there isn't a Turkish docs team. In that case, I would suggest removing the new `README-tr.md` from the PR and leaving the typo from the French `README-fr.md`.

If no action is taken within a reasonable amount of time, a docs wrangler might close this PR.

**Pull request closed without merging**
