### PR TITLE
Mark scheduler pod resource metrics as beta

### PR DESCRIPTION
**Pull request by smarterclayton**
They will be part of 1.21 as beta stability as of https://github.com/kubernetes/enhancements/issues/1748

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/lgtm
/hold

Waiting on the metrics to get marked as beta in k/k (they are currently alpha).

**Comment by ehashman** [comment]
/hold cancel

Apparently we decided to axe [beta stability labels](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/kubernetes-control-plane-metrics-stability.md#beta-stability-level) so I guess this isn't necessary!

**Comment by savitharaghunathan** [comment]
Hi @smarterclayton  👋  Can you change the target branch to `dev-1.21`? 
cc: @reylejano 

/hold

Cancel hold once you have changed the target branch.

**Comment by smarterclayton** [comment]
Closed in favor of https://github.com/kubernetes/website/pull/26805 which is correct branch

**Pull request closed without merging**
