### PR TITLE
Fix link to cosConfigureHelper script.

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

Fixes:  #11818

### CODE REVIEW

**Comment by tao12345666333** [comment]
Do we have a way to try `deploy/netlify` job again?

/retest

**Comment by tengqm** [comment]
@tao12345666333 try a rebase of your branch onto master (fetch the head) and "git push -f". We are kinda trapped by netlify again.

**Comment by tao12345666333** [comment]
@tengqm  Thanks. It works now. :+1:

**Comment by tengqm** [comment]
/lgtm
/approve
Thanks for the patience.

**Pull request merged**
