### PR TITLE
doc: update volume health monitoring doc with metrics content

### PR DESCRIPTION
**Pull request by fengzixu**

### CODE REVIEW

**Comment by PI-Victor** [comment]
@fengzixu thanks for opening this! also please change the target branch to 1.24

/assign
/sig-storage
/milestone 1.24

**Comment by tengqm** [comment]
and ... please squash the commits when the PR is ready.

**Comment by reylejano** [comment]
@fengzixu please take a look at @xing-yang 's [comment](https://github.com/kubernetes/website/pull/32683/files#r840071179)

**Comment by mehabhalodiya** [comment]
enhancement ref:https://github.com/kubernetes/enhancements/issues/1432

**Comment by fengzixu** [comment]
> @fengzixu thanks for opening this! also please change the target branch to dev-1.24
> 
> /assign /sig-storage /milestone 1.24

so, you mean I should create another PR to dev-1.24 branch

**Comment by PI-Victor** [comment]
@fengzixu you don't have to create a new PR, you can edit this PR and change the target branch to `dev-1.24`. please do that, since it already has the comments in it.

**Comment by fengzixu** [comment]
@PI-Victor done

**Pull request merged**
