### PR TITLE
reformat kubeadm upgrade page

### PR DESCRIPTION
**Pull request by jimangel**
Fixes: https://github.com/kubernetes/website/issues/20942

A few things I've noticed:
- Goldmark doesn't like indented notes / tabs in capture statements
- Goldmark doesn't like line breaks inside `code` tags
  - fixed with a dash :/

Since removing indents breaks numbered lists, I converted them to bullets. Once we resolve some of these problems we could add them back in.

/cc @neolit123 @sftim

### CODE REVIEW

**Comment by jimangel** [comment]
Looks like netlify issues...

```
9:29:48 AM: Failed to upload file: id/docs/concepts/storage/volumes/index.html
9:30:00 AM: Failing build: Failed to deploy site
9:30:29 AM: Failed during stage 'deploying site': Failed to execute deploy: &{0 } (*models.Error) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface
9:31:10 AM: Failed to inform the API about a failed build, please retry the build or contact support
9:31:10 AM: Finished processing build request in 26m39.386456393s
```

Rebuilding now.

**Comment by jimangel** [comment]
Preview: https://deploy-preview-20975--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by neolit123** [comment]
preview looks fine!
/lgtm

**Comment by sftim** [comment]
/approve
/hold

@jimangel just in case you had more you wanted to do

**Comment by sftim** [comment]
Feel free to /unhold

**Comment by jimangel** [comment]
Thanks @sftim! I think this is better than the current state. I will leave touchups for a future PR if needed.

/hold cancel

**Pull request merged**
