### PR TITLE
Fix minor typos and misspells detected using misspell

### PR DESCRIPTION
**Pull request by aerostitch**
Ran misspell on the markdown files. Found some issues. This PR fixes them.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7313)

### CODE REVIEW

**Comment by aerostitch** [comment]
As per ci-bot's request:
/assign @steveperry-53

**Comment by steveperry-53** [comment]
@aerostitch Thanks for doing this.

We don't make direct edits to generated reference docs. Instead, we update the source files and then regenerate the docs. The process is documented [here](https://kubernetes.io/docs/home/contribute/generated-reference/kubernetes-components/).

So please remove these two files from this PR:

* docs/reference/generated/kube-apiserver.md
* docs/reference/generated/kubelet.md

**Comment by aerostitch** [comment]
Thanks @steveperry-53, sorry for that.
Commit updated.

Joseph

**Comment by aerostitch** [comment]
Thanks a lot! :)

**Pull request merged**
