### PR TITLE
Update psp doc add allowedFlexyVolumes

### PR DESCRIPTION
**Pull request by wanghaoran1988**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6562)

### CODE REVIEW

**Comment by php-coder** [comment]
CC @liggitt @tallclair

**Comment by liggitt** [comment]
No need to open against master. When 1.9 is released, the 1.9 docs will be merged to master

**Comment by php-coder** [comment]
> No need to open against master. When 1.9 is released, the 1.9 docs will be merged to master

PSP docs in the master were fully rewritten, while they're still of the old version in 1.9 branch. Maybe we should port this change too? Otherwise the merge could be painful.

**Comment by liggitt** [comment]
If that's the case we should first update the 1.9 branch to match master for this file before making any changes

@kubernetes/sig-docs-maintainers I thought master was occasionally merged to the release branches to resolve this sort of issue

**Comment by zacharysarah** [comment]
@liggitt Master was merged into `release-1.9` multiple times last week. I just merged it again now. Apologies for any slowness; most of us are at KubeCon.

**Pull request closed without merging**
