### PR TITLE
lang-id: Broken Link

### PR DESCRIPTION
**Pull request by butuzov**
This fix solves 404 page at next URLs
(See link with text "otorisasi Node")

https://kubernetes.io/id/docs/concepts/architecture/
https://kubernetes.io/id/docs/concepts/architecture/node/

### CODE REVIEW

**Comment by girikuncoro** [comment]
@butuzov thanks for your contribution to docs-id!

/lgtm
/approve

**Comment by butuzov** [comment]
@girikuncoro that was the fastest  "lgtm" I got in this repository. Any chancese the Indonesian team wants to review a few more deadlinks themselves? Currently there a few more broken URLs in the Indonesian docs.

**Comment by tanjunchen** [comment]
@girikuncoro  too fast

**Comment by girikuncoro** [comment]
@butuzov @tanjunchen sure we can take this into our community backlog, any helper scripts you use for checking broken URLs?

**Comment by girikuncoro** [comment]
cc @kubernetes/sig-docs-id-reviews

**Pull request merged**
