### PR TITLE
Fix error on Russian language

### PR DESCRIPTION
**Pull request by DanSu93**
Issue with k8s.io/ru/docs/concepts/overview/kubernetes-api/

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/28976#issuecomment-881322970

**Comment by jimangel** [comment]
Hey there! @DanSu93, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by divya-mohan0209** [comment]
Hey there, @DanSu93 ! Thank you for your PR. Please note that you're required to sign the CLA before we/the Russian localization starts reviewing your PR. However this has had no activity since the time it was opened and will therefore be closed. Please note that you can reopen a fresh PR to k/website once you're ready :)

**Pull request closed without merging**
