### PR TITLE
Tweak documentation for Pod & container stats from CRI

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by reylejano** [comment]
Since this is for 1.26, please target the `dev-1.26` branch
Thank you

**Comment by sftim** [comment]
/retitle Tweak documentation for Pod & container stats from CRI

**Review by sftim — COMMENTED** [review]
We should document the kubelet's behavior for metrics on its own page and not just in the list of configurable feature gates.

For example, add a new page into https://kubernetes.io/docs/reference/instrumentation/

The new page does not have to be long; for an alpha feature, 50 words might be enough. We can add more detail once this graduates to beta.

For extra credit, update https://kubernetes.io/docs/reference/node/ to link to the new page.

**Comment by krol3** [comment]
@haircommander is this a PR relevant for this [KEP](https://github.com/kubernetes/enhancements/issues/3063) ?

**Comment by haircommander** [comment]
> @haircommander is this a PR relevant for this [KEP](https://github.com/kubernetes/enhancements/issues/3063) ?

No this is relevant to [this one](https://github.com/kubernetes/enhancements/issues/2371) though

**Comment by krol3** [comment]
Hi @haircommander! This PR needs a doc review by **Mon Nov 28th** to get this into the release. Please reach out to required SIGs to get their review. Thank you!

**Comment by haircommander** [comment]
@sftim it's not clear to me whether your note is blocking. I could update the docs in the future but I won't have time this evening.

**Comment by sftim** [comment]
Whenever there is behavior that end users might want to know about it - and this includes alpha features - we should document the behavior. It's rarely enough just to mention the behavior on the feature gates page.

I don't have enough context to be able to say "no end users would want to know about the behavior here"; if that is the case, please explain why and then we can merge this without documenting any behavior.

**Comment by sftim** [comment]
The reason I filed https://github.com/kubernetes/website/issues/33509 was because the behavior for this aspect of Kubernetes _didn't_ seem to be documented.

**Review by krol3 — APPROVED** [review]
/lgtm

**Pull request merged**
