### PR TITLE
Update GMSA credspec specification to refer to pod spec fields instead of annotations

### PR DESCRIPTION
**Pull request by ddebroy**
Update GMSA credspec specification to refer to pod spec fields instead of annotations

### CODE REVIEW

**Comment by zacharysarah** [comment]
@kubernetes/sig-windows-bugs 👋 Thanks in advance for your review!

**Comment by sftim** [comment]
@wk8 did you intend to `/approve` or `/lgtm` as well?

**Comment by wk8** [comment]
Indeed, thanks @sftim ! /lgtm

**Comment by zacharysarah** [comment]
@wk8 👋 Thanks for the review! For future reference, the `/lgtm` only works if it's on a new line.

**Comment by wk8** [comment]
Damn it, sorry. Trying again :)

/lgtm

**Comment by simplytunde** [comment]
@ddebroy Please take a look at the review so that we can get this in soon.

**Comment by ddebroy** [comment]
I think this is ready from the tech review perspective. Need approval from owner: @jaredbhatti

**Pull request merged**
