### PR TITLE
Correcting a typo

### PR DESCRIPTION
**Pull request by nicolasholanda**
Word "gerêncai" was supposed to be "gerencia".

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by utkarsh-singh1** [comment]
Hi @nicolasholanda, 

please sign EasyCLA first, which will allow us to review your PR and accept the contribution.

You can find about EasyCLA here - https://docs.linuxfoundation.org/lfx/easycla

and the steps to sign EasyCLA are here - https://docs.linuxfoundation.org/v2/easycla/contributors/individual-contributor

You can start your signing EasyCLA from here - https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38056/#/?version=2

**Comment by utkarsh-singh1** [comment]
Thanks, @nicolasholanda, for raising this PR.

Related doc - https://kubernetes.io/pt-br/docs/concepts/overview/working-with-objects/kubernetes-objects/#especifica%C3%A7%C3%A3o-e-status-do-objeto

**Comment by Sea-n** [comment]
Fixed by PR #38265.

/close

**Pull request closed without merging**
