### PR TITLE
update dev-1.24 config.toml for release 1.24

### PR DESCRIPTION
**Pull request by nate-double-u**
Updated config.toml for release v1.24

Versions were updated based on [latest patch releases](https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md)

No hold needed, this is targeting dev-1.24

### CODE REVIEW

**Comment by PI-Victor** [comment]
checks out when cross ref with https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
