### PR TITLE
Remove redundant text from "Administer a Cluster" page

### LINKED ISSUE #43237: Administer a Cluster page is having redundant text under sub menu "Configure a kubelet image credential provider"
**This is a Bug Report**
**Problem:**
Sub section "[Configure a kubelet image credential provider](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/) under [Administer a Cluster](https://kubernetes.io/docs/tasks/administer-cluster/) is having a redundant text(sub section name is repeating as a normal text).

image

**Proposed Solution:**
    Remove the text that present under "Configure a kubelet image credential provider".
**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/

### PR DESCRIPTION
**Pull request by steve-hardman**
This will fix #43237

Problem shown below
image

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The result of these changes looks good to me.
Thanks!
/lgtm

[Original Page](https://kubernetes.io//docs/tasks/administer-cluster/) |  [Preview Page](https://deploy-preview-43257--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/)

**Review by aj11anuj — APPROVED** [review]
lgtm too, 👍

**Comment by windsonsea** [comment]
The [preview](https://deploy-preview-43257--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/) looks good.
/lgtm

**Pull request merged**
