### PR TITLE
Documentation on lowercasing kubeadm init apiserver SANs

### PR DESCRIPTION
**Pull request by liztio**

### CODE REVIEW

**Comment by liztio** [comment]
Requested by @zparnold (https://github.com/kubernetes/kubernetes/pull/64718#issuecomment-396969512)

**Comment by steveperry-53** [comment]
To get the Netlify preview working, I cherry picked the shortcode fix by @Bradamant3.

Preview: https://deploy-preview-9059--kubernetes-io-vnext-staging.netlify.com/docs/reference/setup-tools/kubeadm/kubeadm-init/

**Pull request merged**
