### PR TITLE
Update diagram docs/tutorials/kubernetes-basics/public/images/module_01_cluster.svg

### PR DESCRIPTION
**Pull request by jailton**
Update diagram docs/tutorials/kubernetes-basics/public/images/module_01_cluster.svg to to use the "control plane" terminology.

Fix:  #26640
Ref: #21621

Preview: https://d33wubrfki0l68.cloudfront.net/283cc20bb49089cb2ca54d51b4ac27720c1a7902/34424/docs/tutorials/kubernetes-basics/public/images/module_01_cluster.svg

/language en

### CODE REVIEW

**Comment by sftim** [comment]
@jailton, we need to fix the text at the same time as the diagram.

If you look at https://deploy-preview-26644--kubernetes-io-master-staging.netlify.app/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/ you'll see the diagram mentions a “control plane” but the page text refers to a “Master”.

You can:
- open another PR to fix the page text, and we can octopus-merge that along with this one
  (fiddly, but possible)
- revise this PR to also reword the page text
  (easier)

Would you be willing to do one one those choices?

/hold
for now

**Comment by jailton** [comment]
@sftim, I've already corrected the text in PR #26645.

**Pull request merged**
