### PR TITLE
Removed extra space in search.js

### PR DESCRIPTION
**Pull request by Pushpa-Mali**
Removed extra space from line 36

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @Pushpa-Mali, Please sign EasyCLA.

/easycla

**Comment by utkarsh-singh1** [comment]
follow these guides to sign easycla,

You can find about EasyCLA here - https://docs.linuxfoundation.org/lfx/easycla

and the steps to sign EasyCLA are here - https://docs.linuxfoundation.org/v2/easycla/contributors/individual-contributor

You can start your signing EasyCLA from here - https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38056/#/?version=2

**Review by dipesh-rawat — COMMENTED** [review]
Hi @Pushpa-Mali, and this looks like this falls under [trivial edit](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits)

Since we try to follow the [Trivial Edits guidelines](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) as much as we can, I kindly ask you to find more things you can improve in the same document (or any other around you went through recently). Having a PR with several minor fixes makes more sense and we'll be more likely to merge it.

**Comment by sftim** [comment]
This really is trivial, and merging it would make work for our many localization teams.
The change is also, I'm afraid, unhelpful overall - that whitespace looks like it was intended.

As a project, We can afford to serve the extra bytes.

With that in mind, I'm going to reject it. 

/close

**Pull request closed without merging**
