### PR TITLE
Minor corrections in init container readme and Service readme

### PR DESCRIPTION
**Pull request by nehagup**

### CODE REVIEW

**Comment by ryanmcginnis** [comment]
/approve

unless @nehagup wants to create two PRs.

**Comment by nehagup** [comment]
@sftim  @ryanmcginnis I have no problem creating 2 PRs. Shall I do now?
We can close this.

**Comment by sftim** [comment]
Congratulations @nehagup - these changes are already merged. No need to create separate PRs here.

**Comment by nehagup** [comment]
Okay, Thanks!

**Pull request merged**
