### PR TITLE
Fix broken links to replicaset examples

### PR DESCRIPTION
**Pull request by plumenator**

### CODE REVIEW

**Comment by DanyC97** [comment]
@plumenator you sure the existing links/ urls are broken? i've tried one of them and it works.

Also please note that `k8s.io` does redirect to `kubernetes.io` domain so i'm a bit confused

**Comment by Rajakavitha1** [comment]
> @plumenator you sure the existing links/ urls are broken? i've tried one of them and it works.
> 
> Also please note that `k8s.io` does redirect to `kubernetes.io` domain so i'm a bit confused

Thanks for the PR @plumenator !!!! I checked all the links/urls and all work. Did you intend to make it https:// instead of http:// similar to the URLs in https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/

**Comment by plumenator** [comment]
Strange. Opening the links in the browser does work. With `curl`, I see this:
```shell
$ curl http://k8s.io/examples/pods/pod-rs.yaml
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
$ curl http://kubernetes.io/examples/pods/pod-rs.yaml
Redirecting to https://kubernetes.io/examples/pods/pod-rs.yaml
$ curl https://kubernetes.io/examples/pods/pod-rs.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    tier: frontend
spec:
  containers:
  - name: hello1
    image: gcr.io/google-samples/hello-app:2.0

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    tier: frontend
spec:
  containers:
  - name: hello2
    image: gcr.io/google-samples/hello-app:1.0
$ 
```
I think the `https://kubernetes.io/` links are more useful.

**Comment by Rajakavitha1** [comment]
Checked $ curl https://kubernetes.io/examples/pods/pod-rs.yaml 
/lgtm
/approve

**Pull request merged**
