### PR TITLE
"First this user must have [a] certificate issued..."

### PR DESCRIPTION
**Pull request by jonassteinberg1**
Added 'a' to the sentence "First this user must have certificate issued..." from the subsection "Normal Users"

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/29727#issuecomment-920897083

**Comment by mehabhalodiya** [comment]
LGTM!

**Pull request merged**
