### PR TITLE
Merge main branch into dev 1.31

### PR DESCRIPTION
**Pull request by Princesso**
This PR syncs the dev-1.30 branch with the main branch to keep the dev-1.30 branch up to date.

cc: @chanieljdan @salaxander @MaryamTavakkoli

### CODE REVIEW

**Comment by reylejano** [comment]
Looked at several commits with failed checks like `bfea01` which merged in PR https://github.com/kubernetes/website/pull/46312 after a rebase to resolve merge conflicts. All the ones with failed checks due to merge conflicts were later resolved and merged 
Other examples are the following:
- commit `7aaf34` in https://github.com/kubernetes/website/pull/46495
- commit `936c036` in https://github.com/kubernetes/website/pull/46301
- commit `44669d5` in https://github.com/kubernetes/website/pull/45009
/approve

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/lgtm

**Comment by dipesh-rawat** [comment]
> [Bot's comment](https://github.com/kubernetes/website/pull/46495#issuecomment-2125581553)
Needs approval from an approver in each of these files:
[data/announcements/OWNERS](https://github.com/kubernetes/website/blob/dev-1.30/data/announcements/OWNERS)

This appears to also require approval from @kubernetes/steering-committee _(As this sync contains the changes to add KubeCon China banner added as part of PR https://github.com/kubernetes/website/pull/46431)_

/committee steering

**Comment by BenTheElder** [comment]
PRs this large kinda break github, I'm having difficulty confirming the content of `data/announcements`.

We should probably consider approaches like letting automation perform a fast-forward similar to the release branches in github.com/kubernetes/kubernetes, or serving 1.30 from the main branch without forking until later or ...

At 1463 commits there's no way anyone is actually reviewing and verifying the changes in this PR, if there's no manual changes then moving the sync to a robot / CI where we can inspect the code and logs for the robot instead of the commits de-risks the chance that someone submits one of these PRs and actually (intentionally or otherwise) includes some other, manual changes.

I think SIG release could probably help with that.

If it *is* expected to be manual, we should come up with a way to reduce the size (maybe more frequent PRs?)

**Comment by BenTheElder** [comment]
(I'm inclined to assume that this PR is fine, but we have processes to review and verify for a reason, mistakes happen)

https://github.com/kubernetes/website/pull/46495.patch gets around the particular problem of loading the diff for the announcements changes.

/approve
for data/announcements

**Comment by BenTheElder** [comment]
P.S. Thank you for working on the docs!

**Pull request merged**
