### PR TITLE
Docs home page card layout is now consistent

### LINKED ISSUE #43147: Poor alignment for tiles on home page for docs
**This is a Feature Request**

**What would you like to be added/enhanced?**
As it can be clearly seen at [/docs/home/ page](https://kubernetes.io/docs/home/) that the layout of this page is looking somewhat inconsistent due to this visible big-small difference in 'Cards' at 2nd and 3rd row.

Screenshot (773)
Screenshot (774)
 
**Solution:**
I think this issue can be easily resolved by replacing the 'Card' of (3rd Column, 2nd Row) with (1st Row, 3rd Column) like this:-

Screenshot (771)

Screenshot (772)

As 'Cards' of 2nd row are all vertically tall and 'Cards' of 3rd row are all vertically small. So, replacing these 2nd 'Cards' with each other will possibly solve the problem.

By Card, i mean that whole thing inside yellow line (Heading, description, hyperlinks and button)

### PR DESCRIPTION
**Pull request by Gauravpadam**
Closes #43147

This PR improves the overall aesthetics of the Kubernetes docs home page
I've made some changes to the Front matter fields for consistency ; The SCSS changes aim to improve the overall aesthetic of the cards.

### CODE REVIEW

**Review by aj11anuj — COMMENTED** [review]
Can you share a deploy preview?

**Comment by Gauravpadam** [comment]
> Can you share a deploy preview?

Sure, I'll add it in the PR description once it's generated

**Comment by sftim** [comment]
Now that fits!

/lgtm
/approve

**Comment by sftim** [comment]
BTW, I recommend making CSS and content changes in separate commits.

**Comment by Gauravpadam** [comment]
> BTW, I recommend making CSS and content changes in separate commits.

Okay, But it's already merged(?)
Should I make separate PRs again?

**Comment by Gauravpadam** [comment]
Thanks, I'll proceed to make separate PRs now

**Comment by sftim** [comment]
I actually approved this in error and have reverted it in #43165. Please do make a new PR.

**Pull request merged**
