### PR TITLE
Add HPA as aka for Horizontal Pod Autoscaler

### PR DESCRIPTION
**Pull request by gedimitr**

### CODE REVIEW

**Comment by sftim** [comment]
(not sure why this didn't preview, the code change _looks_ fine)

**Comment by sftim** [comment]
I'm trying to work out what about this PR is causing trouble.

**Comment by prankul88** [comment]
@sftim I think it's working as expected now right? Don't see the tests failing

**Comment by sftim** [comment]
Seems to be happier now.
/approve

**Pull request merged**
