### PR TITLE
[hi] Localize glossary tag display names into Hindi

### PR DESCRIPTION
**Pull request by Babapool**
This PR:

- Adds translation (localization) for glossary tag display names in Hindi. These changes were enabled after the merging of 
PR #37966 

File changed: [hi.toml](https://github.com/kubernetes/website/blob/main/data/i18n/hi/hi.toml)

Signed off by : Vitthal Kaul vitthalsai2001@gmail.com

### CODE REVIEW

**Comment by Babapool** [comment]
Page deployment preview: https://deploy-preview-38252--kubernetes-io-main-staging.netlify.app/hi/docs/reference/glossary/?fundamental=true

**Review by sftim — COMMENTED** [review]
Please keep the keys in `data/i18n/hi/hi.toml` collated according to the English sort order

**Comment by divya-mohan0209** [comment]
@sftim Would we want to amend them in the original and change them accordingly here?

**Comment by Babapool** [comment]
>@sftim Would we want to amend them in the original and change them accordingly here?

@sftim has opened an issue (#38257) to sort the keys in the original. I am happy to sort the keys according to the English sort order in `hi.toml`. Should I sort before reviewing of the PR or after the PR is reviewd?

**Comment by divya-mohan0209** [comment]
I think once the EN one is merged, it'd make more sense for you to work on this PR + get it reviewed.

**Comment by divya-mohan0209** [comment]
@Babapool : Gentle reminder.

**Comment by anubha-v-ardhan** [comment]
> Sorry on missing out on this PR for months. I will push a new PR with the required changes by this weekend. Thanks

@Babapool, any updates on the new PR. Should we close this one?

**Comment by Babapool** [comment]
@anubha-v-ardhan I am completely sorry this PR got swept under my radar 😅. I will push a new commit for this PR by this weekend. Thanks

**Comment by Babapool** [comment]
@anubha-v-ardhan @divya-mohan0209 , I have rearranged the tags in alphabetical order. PTAL. Thanks

**Comment by Babapool** [comment]
@anubha-v-ardhan I think this is a good idea. There is a PR #38681 to localize some of the tags. I will put in a PR to localize any other terms which are not covered by this PR. Thanks

**Comment by divya-mohan0209** [comment]
Hello @Babapool , I think that's a good idea. I will close this PR in favour of #38631 .
/close

**Pull request closed without merging**
