### PR TITLE
Fixing release timing link.

### PR DESCRIPTION
**Pull request by Wdrwoman**
Fixing release timing link. Issue #16806

### CODE REVIEW

**Comment by sftim** [comment]
@Wdrwoman if you can [sign the CLA](https://kubernetes.io/docs/contribute/start/#sign-the-cla), this will be ready for review.

**Comment by bradtopol** [comment]
Hi @Wdrwoman Thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by tfogo** [comment]
Hi @Wdrwoman, I'm going to close this since the CLA wasn't signed. Please feel free to re-open this PR in the future if you're able to sign the CLA.

/close

**Pull request closed without merging**
