### PR TITLE
Component reference for 1.21

### PR DESCRIPTION
**Pull request by tengqm**
Related: #27478

### CODE REVIEW

**Comment by sftim** [comment]
Previews are linked from https://deploy-preview-27479--kubernetes-io-master-staging.netlify.app/docs/reference/config-api/
/approve

**Comment by reylejano** [comment]
Thank you @tengqm , (informal) lgtm. 
@kbhawkey , can you confirm if these generated ref docs are good?

**Comment by kbhawkey** [comment]
Page previews:
https://deploy-preview-27479--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/
https://deploy-preview-27479--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-init/
https://deploy-preview-27479--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-alpha/
https://deploy-preview-27479--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase/
https://deploy-preview-27479--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kube-apiserver/
https://deploy-preview-27479--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kubelet/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

**Comment by kbhawkey** [comment]
The changes look good.
We'll need to review the changes to the generator (modules, packaging) and
investigate if the build script can be used to generate the files.
Thanks @tengqm .
/lgtm

**Pull request merged**
