### PR TITLE
Drop DynamicAuditing

### PR DESCRIPTION
**Pull request by tengqm**
The dynamic auditing feature is dropped in 1.19.

Ref1: https://groups.google.com/forum/#!topic/kubernetes-sig-auth/aV_nXpa5uWU
Ref2: kubernetes/kubernetes#91502

Closes: #21695

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
Deploy preview: https://deploy-preview-22544--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/
https://deploy-preview-22544--kubernetes-io-vnext-staging.netlify.app/docs/tasks/debug-application-cluster/audit/

**Comment by liggitt** [comment]
/lgtm

from sig-auth perspective

**Pull request merged**
