### PR TITLE
Move “Resource Bin Packing” into Scheduling & Eviction section

### LINKED ISSUE #22534: Move “Resource Bin Packing” into Scheduling & Eviction section
**This is a Feature Request**

**What would you like to be added**
Migrate the content from https://kubernetes.io/docs/concepts/configuration/resource-bin-packing/ into somewhere inside https://kubernetes.io/docs/concepts/scheduling-eviction/

**Why is this needed**
https://kubernetes.io/docs/concepts/configuration/resource-bin-packing/ is not about configuration in the way that ConfigMap and Secret are; instead, it's much more about scheduling.

**Comments**
/language en
/kind cleanup

Initially, a straightforward cut-and-paste would be fine, so I'll mark this as:
/good-first-issue

### PR DESCRIPTION
**Pull request by JubayerJoy**
Signed-off-by: Jubayer Abdullah Joy <jubayerjoy98@gmail.com>

### PR discription
- [x] Moved `resource-bin-packing.md`  from `/concepts/configuration/` to `/concepts/scheduling-eviction/`
- [x] Added redirect from `/docs/concepts/configuration/resource-bin-packing/` to `/docs/concepts/scheduling-eviction/resource-bin-packing/`

#### Note for Reviewer:
In `/static/_redirects` maintained alphabetic order to add the redirect.

### CODE REVIEW

**Comment by JubayerJoy** [comment]
I signed it

**Comment by tengqm** [comment]
/lgtm
This page is safe to move because references to it is very limited.

**Review by sftim — COMMENTED** [review]
Hello @JubayerJoy 

As well as this change, could you also revise [`/static/_redirects`](https://github.com/kubernetes/website/blob/master/static/_redirects) so that anyone who visits the old URL gets to see the page they wanted?

**Comment by JubayerJoy** [comment]
> Hello @JubayerJoy
> 
> As well as this change, could you also revise [`/static/_redirects`](https://github.com/kubernetes/website/blob/master/static/_redirects) so that anyone who visits the old URL gets to see the page they wanted?

Hi @sftim, made changes as you suggested 👍 
In `/static/_redirects` maintained alphabetic order to add the redirect.

**Comment by JubayerJoy** [comment]
Hi @tengqm,
Made a change in this PR. Review please!

**Pull request merged**
