### PR TITLE
Fix persistentVolumeClaim link

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
CLA signed

**Comment by geoand** [comment]
CFNF site seems to have me under authorized contributors as seen here:

 cncf

**Comment by mistyhacks** [comment]
/approve

FYI, this anchor should have been automatic and probably doesn't need to be explicitly set.

**Comment by geoand** [comment]
Thanks for pointing that out @mistyhacks

**Pull request merged**
