### PR TITLE
Fix healthz-bind-address default

### PR DESCRIPTION
**Pull request by jsoref**
This matches the documentation for:

```
--bind-address 0.0.0.0     Default: 0.0.0.0
```

### CODE REVIEW

**Comment by jsoref** [comment]
>       <td colspan="2">--metrics-bind-address 0.0.0.0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Default: 127.0.0.1:10249</td>
should also be fixed..., but that's outside the scope of the branch name -- sorry

**Comment by sftim** [comment]
@jsoref this page is a web version of the documentation for the kube-proxy component itself.

The default value is rendered by processing the actual code and to me it looks correct.
See https://github.com/kubernetes/kubernetes/blob/3ae1b0ce8061788bd82587e54f1f3bb2529a9f7f/pkg/proxy/apis/config/v1alpha1/defaults.go#L47 for where that value is calculated.

However I can also see that it's a bit weird to have a “default bind address” command line argument that also includes a port. It seems to me that any feedback about the naming, or the way that the default value is generated, is best directed at the kube-proxy code itself in [k/kubernetes](https://github.com/kubernetes/kubernetes/).

Would you like to log an issue against Kubernetes instead?

**Comment by jsoref** [comment]
@sftim : it sounds like you understand how `--healthz-bind-address` and `--metrics-bind-address` are confusingly rendered in context to `--bind-address`. I suspect you'd be better suited to explain this to [k/kubernetes](https://github.com/kubernetes/kubernetes) than I am.

Could you possibly do it?

**Comment by sftim** [comment]
I'm not sure that the documentation is wrong; instead, the current code's behavior is (I think unintentionally) confusing.

**Comment by sftim** [comment]
@jsoref is it OK to /close this?

**Comment by jsoref** [comment]
Yes, the code is confusing. It'd be helpful if it were reported somewhere where someone could address it. Preferably by someone whose report would be listened to.

My experience making requests hasn't been particularly positive. Mostly things get closed by bots.

Obviously you can close it, and if you don't, I'm sure a bot eventually will. It's pointless for me to fight this. I acknowledge that I misdirected the report.

**Comment by sftim** [comment]
See https://github.com/kubernetes/kubernetes/issues/88443 - I already reported it.

**Pull request closed without merging**
