### PR TITLE
add v1.18 api ref to redirects

### PR DESCRIPTION
**Pull request by kbhawkey**
- Add redirect for v1.18 API reference
- Remove v1.18 API reference directory from `website/static`
- Minor cleanup in _redirects file

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page [preview](https://deploy-preview-23794--kubernetes-io-master-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.18/).

**Comment by kbhawkey** [comment]
Hi @irvi Do you have time to review these changes?
Thanks!

**Comment by irvifa** [comment]
@kbhawkey my id is @irvifa by the way sure I’ll review it. Sorry for the confusion.

**Review by irvifa — COMMENTED** [review]
Thanks!
/approve

**Pull request merged**
