### PR TITLE
WIP - CRD v1 docs

### PR DESCRIPTION
**Pull request by jpbetz**
Placeholder PR for CRD v1 API . This API is being promoted from v1beta1 to v1 in 1.16.

Key changes:

- [ ] CRD v1: promote to v1
- [ ] CRD v1: require validation schemas
- [ ] CRD v1: structural schema: require structural schema
- [ ] CRD v1: prevent invalid type attributes in schema
- [ ] CRD v1: only allow default attributes in schema via v1
- [ ] ConversionReview: promote types to v1
- [ ] ConversionReview: allow dispatcher to speak v1
- [ ] ConversionReview: in v1, verify response.uid, kind, apiVersion are set in responses

### CODE REVIEW

**Comment by jpbetz** [comment]
@liggitt If you already opened a placeholder for CRD v1 docs let me know and I'll close this as a dup. Just wanted to get the placeholder up before the deadline.

**Comment by liggitt** [comment]
https://github.com/kubernetes/website/pull/15982 was already open by sttts

**Comment by sttts** [comment]
Have done https://github.com/kubernetes/website/pull/15982. Please open PRs against that.

**Pull request closed without merging**
