### PR TITLE
Fix issues in generated config API references

### PR DESCRIPTION
**Pull request by tengqm**
This PR fixes some issues caused by the bad format in source code comments that confuse the reference generator. Problems are related to the use of `*` in comment text as literal string rather than emphasis.

Related: #41035

### CODE REVIEW

**Comment by sftim** [comment]
I don't think it's fair to say that the source code has a bad format - it's more like undefined behavior and a best-effort generator which tries hard to guess the right Markdown equivalent.

Anyway

/approve

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by kbhawkey** [comment]
Preview:
https://deploy-preview-41036--kubernetes-io-main-staging.netlify.app/

**Pull request merged**
