### PR TITLE
[ja]Fix an invalid link in contribute/_index.md

### PR DESCRIPTION
**Pull request by atorik**
Since the "participating" in current path does not seem to exist, modified it to "participate".

I linked to the Japanese page, but there were some places in contribute/_index.md where the links were to the English version of the page.

I changed all the links to the Japanese version for the consistency.
How do you think?

### CODE REVIEW

**Comment by atorik** [comment]
Sorry for duplicating #37860.
I recreated PR since I misconfigured my email address when I committed locally and could not pass EasyCLA.

**Review by Arhell — COMMENTED** [review]
/assign @atoato88

**Review by t-inu — APPROVED** [review]
/lgtm
Thank you for creating this PR!

**Comment by atoato88** [comment]
/lgtm
It's nice to update the links to the ja contents.
Actually, we have updated en links to ja links on other pages.

**Comment by nasa9084** [comment]
great, thank you for your contribution!!
/approve

**Pull request merged**
