### PR TITLE
Grammar fix for README-ko.md.

### PR DESCRIPTION
**Pull request by revi**
REAMDE-ko.md has space where space is not desired. This PR fixes these minor grammatical errors.

### CODE REVIEW

**Comment by gochist** [comment]
I heard that Zach is in the vacation.
/assign @steveperry-53

**Comment by gochist** [comment]
Please take a look from upstream. There's an issue #14008 that l10n team does not have permission to approve the README-ko.md. 

As a native Korean speaker, it looks good to me, too.

**Comment by gochist** [comment]
@revi, could you please change the base branch to `master`? I'm sorry that I missed that the base branch of this PR is `dev-1.15-ko.5`.  The language team branch, `dev-1.15-ko.5` is supposed to handle changes under `content/ko` only.  Or, it will need another upstream's approval when the branch is merged to the master.

/hold

**Comment by revi** [comment]
Hmm whoops. I probably messed up somewhere in the middle of fixing stuff.

Changing it blindly to the master in GitHub UI doesn't work, since it introduces one commit in dev-ko not in master. Will close and recreate with base as master.

**Pull request closed without merging**
