### PR TITLE
Update garbage-collection.md

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
Fix document formatting errors

image

### CODE REVIEW

**Comment by ZP-AlwaysWin** [comment]
PLTA
/assign @xichengliudui

**Comment by xichengliudui** [comment]
i don't think it needs updating

**Comment by xichengliudui** [comment]
there is usually no space between Chinese characters.

**Comment by ZP-AlwaysWin** [comment]
> there is usually no space between Chinese characters.

Hello, you can have a look at this page. The format is wrong. You need space to display it correctly.

https://kubernetes.io/zh/docs/concepts/workloads/controllers/garbage-collection/#%E6%98%BE%E5%BC%8F%E7%BA%A7%E8%81%94%E5%88%A0%E9%99%A4
**ERROR：**
image
**RIGHT:**
image

**Comment by ZP-AlwaysWin** [comment]
> there is usually no space between Chinese characters.

hi @xichengliudui  
Does this makdown format need to be resolved?

**Pull request closed without merging**
