### PR TITLE
Empty dev-1.13 PR docs for server dry-run

### PR DESCRIPTION
**Pull request by apelisse**

### CODE REVIEW

**Comment by apelisse** [comment]
@tfogo

**Comment by tfogo** [comment]
Hi @apelisse, same here. Can you please complete this PR as soon as you can? The docs deadline is approaching fast and we want to start reviews ASAP.

**Comment by npentrel** [comment]
@jennybuckley are you working on this one?

**Comment by apelisse** [comment]
Replace by #11140

**Pull request closed without merging**
