### PR TITLE
Fix broken link on Writing a new topic Page

### LINKED ISSUE #37605: Broken link on Writing a new topic page
**Problem:**
The text [**FlexVolume**](https://kubernetes.io/docs/concepts/storage/volumes#flexvolume) on [link](https://kubernetes.io/docs/contribute/style/write-new-topic/#embedding-code-in-your-topic) is not working, it should point to these https://kubernetes.io/docs/concepts/storage/volumes/#flexvolume-deprecated
Check the page [Writing a new topic](https://kubernetes.io/docs/contribute/style/write-new-topic/#embedding-code-in-your-topic) for the problem.

**Page to Update:**
https://kubernetes.io/docs/contribute/style/write-new-topic/#embedding-code-in-your-topic

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the link on the text **FlexVolume** to https://kubernetes.io/docs/concepts/storage/volumes/#flexvolume-deprecated and not to this [link](https://kubernetes.io/docs/concepts/storage/volumes/#flexvolume).

/kind document
/assign
/language en

### PR DESCRIPTION
**Pull request by kadtendulkar**
Fixes #37605

Updated page [Writing a new topic](https://kubernetes.io/docs/contribute/style/write-new-topic/#embedding-code-in-your-topic)

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Review by Pradumnasaraf — APPROVED** [review]
Looks good!

/approve

**Comment by windsonsea** [comment]
In my opinion, this change is not very elegant. The website repo has nearly ten links with `/docs/concepts/storage/volumes/#flexvolume`, which means we need to modify it nearly ten times.

image

One suggestion is to add an anchor like:
```
### flexVolume (deprecated)     {#flexvolume}
```
in 
```
content/en/docs/concepts/storage/volumes.md
```

**Pull request merged**
