### PR TITLE
[id] Fix mismatch in Labels and Selectors concept page

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/39205/files
/assign @girikuncoro

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
LGTM makes sense.

/lgtm

**Comment by girikuncoro** [comment]
@Arhell any idea why the checks are failing?

**Comment by Arhell** [comment]
> @Arhell any idea why the checks are failing?

Nope, but i re-push commit

**Review by Arhell — COMMENTED** [review]
@girikuncoro  build is fine

**Review by habibrosyad — APPROVED** [review]

**Pull request merged**
