### PR TITLE
List all pods that use a specific Secret

### PR DESCRIPTION
**Pull request by alkallio**
A command that retrieves all pods that use a specific Secret.  
`jq` is used to search the json output.

### CODE REVIEW

**Comment by alkallio** [comment]
Signed CLA

**Comment by alkallio** [comment]
Hi @sftim!

>  I do have Pods that mount the default service account token for this namespace as a Secret volume.

You're right. I should have mentioned that the command above is only for secrets that are used to populate an environment variable. I haven't accounted for secrets that are mounted as volumes.  
I'll update the description to highlight this fact.

Do you think that something like "List pods that use a specific Secret to populate an environment variable" better captures what the command does? Happy to hear any other suggestions.  

Also thanks for raising the mounted volume case. I'll try to see if it's easy to include it in the command or if it's better to add another.

**Comment by sftim** [comment]
My gut feeling is that it's going to be hard to make a concise command that does what the comment says. I also think that narrowing the comment isn't the right fix, I'm afraid.

If I'm right about there not being a concise fixed version, what could possibly work better is a blog post that lists several shell snippets and why they're useful. Bonus marks for including a PowerShell snipper for the SIG Windows people.

**Comment by bradtopol** [comment]
@sftim @alkallio I tried this as well and had difficulty getting it to work.  It needs be more clear on how it works or how it is used. otherwise its frustrating.
/assign

**Comment by alkallio** [comment]
As discussed, closing this PR. A blog post is better suited in order to avoid potential frustration and confusion.  
Thank you for your feedback!

**Pull request closed without merging**
