### PR TITLE
update content/zh/docs/concepts/services-networking/dual-stack.md

### PR DESCRIPTION
**Pull request by ydcool**
Update zh docs for release-1.18

### CODE REVIEW

**Comment by ydcool** [comment]
@tengqm @tanjunchen @markthink 
Incorrect reviewers assigned before, please take a look , thanks!

**Comment by lachie83** [comment]
FYI - I also have these changes up for review on 1.18 in the English docs. https://github.com/kubernetes/website/pull/20656

**Comment by ydcool** [comment]
@lachie83 Thank you, I'd push an additional commit to follow your changes as soon as your PR get merged.

**Comment by ydcool** [comment]
/hold
Waiting for #20656

**Pull request merged**
