### PR TITLE
#13332 No diagram on /concepts/overview/components/

### PR DESCRIPTION
**Pull request by SupriyaSirbi**
Added Components of Kubernetes image for better understanding

### CODE REVIEW

**Comment by sftim** [comment]
@SupriyaSirbi thanks for this!

**Comment by SupriyaSirbi** [comment]
> @SupriyaSirbi thanks for this!



> This [page](https://deploy-preview-17157--kubernetes-io-master-staging.netlify.com/docs/concepts/overview/components/) seems (to me) better _with_ the added diagram than without it. The diagram is broadly accurate; you don't _have_ to deploy Kubernetes to the cloud and use cloud-controller-manager.
> 
> /lgtm

Hello @sftim Should I update the diagram as per the above comments?

**Comment by sftim** [comment]
I've added a “Looks good to me” label: the diagram is technically accurate. Next step is for an approver to approve this change.

**Comment by tengqm** [comment]
The diagram is clear and beautiful. Can you check in the source from which the PNG file was generated? That will help when change requests come.

**Comment by SupriyaSirbi** [comment]
> The diagram is clear and beautiful. Can you check in the source from which the PNG file was generated? That will help when change requests come.

Hello @tengqm you mean the .svg file source for the image?

**Comment by tfogo** [comment]
@SupriyaSirbi, yes an SVG would be great, thanks!

**Comment by tfogo** [comment]
@SupriyaSirbi, this diagram looks great by the way!

**Comment by SupriyaSirbi** [comment]
Hello All,

Added svg file for the components-of-kubernetes.png.
Please review the same.

Thanks

**Comment by tengqm** [comment]
@SupriyaSirbi  Thanks.
/approve

**Comment by SupriyaSirbi** [comment]
Thanks @tengqm. Could anyone please add lgtm label as well?

**Comment by sftim** [comment]
Relevant to #13332
/retitle No diagram on /concepts/overview/components/

**Pull request merged**
