### PR TITLE
Revise use of jsonpath in AppArmor tutorial

### PR DESCRIPTION
**Pull request by tengfei86**
this is a  better way to use jsonpath

### CODE REVIEW

**Comment by Sea-n** [comment]
It seems reasonable!

But could you provide some evidence about why `{"\n"}` is the recommended way over `$'\n'` in this scenario?

**Review by sftim — COMMENTED** [review]
LGTM (but I didn't test it)

**Comment by sftim** [comment]
This change is getting JSONpath to do all the work I think, rather than having the shell do some of it.

**Comment by tengfei86** [comment]
> It seems reasonable!
> 
> But could you provide some evidence about why `{"\n"}` is the recommended way over `$'\n'` in this scenario?

i think my way is more convenient ,we just use the jsonpath to write it .

**Review by sftim — COMMENTED** [review]
The existing code gets _your shell_ to render a newline, and relies on features that aren't in POSIX. If we can get the jsonpath template to render the newline, this will work for all readers that use a POSIX-compatible shell.

I haven't tested the change, but I do agree with the intent and will be happy to approve once this gets an LGTM.

**Comment by sftim** [comment]
/retitle Revise use of jsonpath in AppArmor tutorial

**Comment by jimangel** [comment]
Tested.

```
# before
$ kubectl get nodes -o=jsonpath=$'{range .items[*]}{@.metadata.name}: {.status.conditions[?(@.reason=="KubeletReady")].message}\n{end}'
node1: kubelet is posting ready status. AppArmor enabled
node2: kubelet is posting ready status. AppArmor enabled
node3: kubelet is posting ready status. AppArmor enabled
node4: kubelet is posting ready status. AppArmor enabled
node5: kubelet is posting ready status. AppArmor enabled
node6: kubelet is posting ready status. AppArmor enabled

# after
$ kubectl get nodes -o=jsonpath='{range .items[*]}{@.metadata.name}: {.status.conditions[?(@.reason=="KubeletReady")].message}{"\n"}{end}'
node1: kubelet is posting ready status. AppArmor enabled
node2: kubelet is posting ready status. AppArmor enabled
node3: kubelet is posting ready status. AppArmor enabled
node4: kubelet is posting ready status. AppArmor enabled
node5: kubelet is posting ready status. AppArmor enabled
node6: kubelet is posting ready status. AppArmor enabled
```

Seems reasonable.
/approve

**Pull request merged**
