### PR TITLE
Split paid and free courses

### PR DESCRIPTION
**Pull request by 927589452**
Split the list into two based on wether they are paid or free, to help users learning on their own without company backing to easily find the free ressources to get a quick start into kubernetes.

### CODE REVIEW

**Comment by 927589452** [comment]
I signed it

**Comment by sftim** [comment]
Hi @927589452 

Thanks for suggesting these changes. Could you write a description for the pull request that explains what you're changing and why? (especially the _why_ part - I can guess, but it helps to be clear).

**Comment by 927589452** [comment]
> /check-cla

Ups, only registered the account there and just realized I would have to connect a mailing adress publicly with this account so this is a show stopper for me.

Sorry, but maybe someone will pick up my idea

**Pull request closed without merging**
