### PR TITLE
[ru] add some translate files

### PR DESCRIPTION
**Pull request by mshalmanov**

### CODE REVIEW

**Comment by mshalmanov** [comment]
Hello all.
I don't understand why show errors.
In the git i'm beginers.
Please hep me.
Thanks.

**Comment by kbhawkey** [comment]
Hi @mshalmanov . Would you limit the changes in this pull request to one localization?
/cc @kubernetes/sig-docs-ru-reviews

**Comment by kbhawkey** [comment]
Hi @mshalmanov .
The PR is marked as `ru`, but you have added `ko` changes.
Would you split this pull request into two pull requests: one pull request for the `ru` changes and a second pull request for the `ko` changes.
Thanks.

**Comment by mshalmanov** [comment]
Hello @kbhawkey how i can split my PR. I have not had to deal with this. Please help me. Thanks.

**Comment by kbhawkey** [comment]
> 
> 
> Hello @kbhawkey how i can split my PR. I have not had to deal with this. Please help me. Thanks.

Hi @mshalmanov .
You should have two pull requests for these changes; separate out the `ko` and `ru` changes. For example, remove the `ru` changes from this pull request and push the changes to a new pull request.

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de en es fr hi id it ja ko pl pt uk vi zh
/remove-sig release

**Pull request closed without merging**
