### PR TITLE
Add kr8s to community Python libraries list

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Added [`kr8s`](https://github.com/kr8s-org/kr8s) to the community Python libraries list. The list looked to be alphabetical so I tried to insert it at the right position, but let me know if the order should be different.

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Add kr8s to community Python libraries list

**Comment by jacobtomlinson** [comment]
Thanks for the review @sftim. I've committed your suggestion.

**Review by sftim — COMMENTED** [review]
/lgtm

**Pull request merged**
