### PR TITLE
Fix broken link to metrics-server

### PR DESCRIPTION
**Pull request by bl-ue**
From the issue:
>metrics server url is wrong.
>"https://github.com/kubernetes-sings/metrics-server" => "https://github.com/kubernetes-sigs/metrics-server".
>"kubernetes-sings" => "kubernetes-sigs"

### CODE REVIEW

**Comment by tengqm** [comment]
@bl-ue pls do not include issue number in your original PR title or message.

**Comment by bl-ue** [comment]
@tengqm Okay.  Is that our general custom or is it specific to this PR/issue?  Because I did the same thing over at #25428.  Would you like to to fix it there, too?

**Comment by tengqm** [comment]
@bl-ue There are prows and bots running behind the gates. They do not like mentioning issue numbers **in the commit title or message**. However, you can still mention the issue that should be auto-closed when raising your PR, i.e. you can put for example "closes: #issuenumber" in your PR message. But, do NOT do this in your own commit title or message.

**Comment by bl-ue** [comment]
@tengqm Gotcha! Thank you very much for the information!

**Pull request merged**
