### PR TITLE
Update controller.md

### PR DESCRIPTION
**Pull request by jackThomass**
Design 翻译

### CODE REVIEW

**Comment by Tej-Singh-Rana** [comment]
@jackThomass It's your first pull request but before that you have to sign CLA to proceed ahead.

**Review by Arhell — COMMENTED** [review]
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Review by jackThomass — COMMENTED** [review]
c2b4beacca50305bdb8d1a98a14309b94ab18293

**Review by jackThomass — COMMENTED** [review]
c2b4beacca50305bdb8d1a98a14309b94ab18293

**Comment by tengqm** [comment]
Closing due to CLA check failure for over a month. Feel free to reopen when CLA is signed.
/close

**Pull request closed without merging**
