### PR TITLE
Fix Typo in user-guide.md

### LINKED ISSUE #36554: Typo on Guide for scheduling Windows containers in Kubernetes page
The spelling of the **functionality** i.e funcationality is wrong, I'm attaching the screenshot for the same.
May I open a new PR correcting the spelling?
Typo

### PR DESCRIPTION
**Pull request by akankshakumari393**
Fixes #36554

### CODE REVIEW

**Comment by UtkarshMishra12** [comment]
This is not fair I was working on this issue, and You should have asked before submitting it. @divya-mohan0209 Please look into it.

**Comment by akankshakumari393** [comment]
> This is not fair I was working on this issue, and You should have asked before submitting it. @divya-mohan0209 Please look into it.
Hi @UtkarshMishra12 I have politely mentioned the reason why I raised the PR in the issue, and now I have closed it too. Is that not ok with you?

**Comment by UtkarshMishra12** [comment]
It's ok, thanks for understanding. @akankshakumari393 😊

**Comment by reylejano** [comment]
@UtkarshMishra12, SIG Docs has a "don't lick cookies" policy meaning that anyone can open a PR and there is no "ownership" of an issue
I'm re-opening this PR

**Comment by reylejano** [comment]
/retitle Fix typo on Guide for scheduling Windows containers in Kubernetes page

**Pull request merged**
