### PR TITLE
[WIP] Finding a way to integrate downloadkubernetes.com as hugo shortcode

### PR DESCRIPTION
**Pull request by jimangel**
This is an early preview, I didn't want to get too far into this before getting feedback. There's 1,000 different ways to generate this page but I want to do what makes the most sense.

Feedback welcome, specifically on the content presentation via the most impactful way to display rows & columns. "Live" filtering is complex without nasty JS code, but we can rearrange / format almost anything on the page.

Right now, I'm thinking we cover the most popular URLs on the page and provide links or additional help at the bottom about finding the more obscure components.

I also tried using tabs, so each version was it's own tab but the markdown tables lost their format. This is fixable with CSS work but I didn't have the spare cycles to make it work. Happy to collaborate with someone on this branch!

Direct preview: https://deploy-preview-29448--kubernetes-io-main-staging.netlify.app/releases/download/

/hold
/sig docs
/assign @saschagrunert @puerco 
/cc @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — COMMENTED** [review]
Thank you for working on this @jimangel! :pray: 

How about keeping the filtering out of scope for now and just provide a structured way, like:

---

### v1.22.0

#### Linux

| Binary | amd64 | arm64 | … |
|----------|----------|----------|----------|
| apiextensions-apiserver   | [link]()  |  [link]()    |  …   |
| kube-aggregator  |  [link]()  |  [link]()  |  …  |
| … | … | … |

#### Windows
#### macOS

### v1.21.4

#### Linux
#### Windows
#### macOS

### v1.20.10

#### Linux
#### Windows
#### macOS

### v1.19.4

#### Linux
#### Windows
#### macOS

--- 

This way we can keep the tables small. Do you have thoughts on that?

**Comment by puerco** [comment]
@jimangel when you say:
> "Live" filtering is complex without nasty JS code
is this because of restrictions on using JS on the website?

**Comment by jimangel** [comment]
> is this because of restrictions on using JS on the website?

It's more about the implementation complexity and fact that folks sometimes have JS disabled (and handling that effectively). The tech debt generally isn't worth it compared to the size / skillset of docs maintainers.

Things like mermaidJS are implemented via a CDN and we have a shortcode to handle when JS disabled, but it's a strait-forward use case w/ little tech debt.

I'm open to the idea if someone can demo how it's implemented and maintained.

**Comment by sftim** [comment]
- Originally https://downloadkubernetes.com/ was a 3rd party project. Is it now an in-project website? I'd want to be sure before doing that shortcode.
- I'm tempted to make this a layout not a shortcode. [I assume that] only specific pages will use the layout (or shortcode) and we know which they are.

**Comment by sftim** [comment]
To get the tabs to work, I'd be tempted to generate HTML similar to the shortcodes for tabs. That'd mean moving the generation of HTML tables into the page layout.

**Comment by sftim** [comment]
Another option is to include a (new and) special version of https://downloadkubernetes.com/ via an iframe, similar to how we integrate with the CNCF landscape.

Could that work?

**Comment by puerco** [comment]
@sftim Re:
> Originally https://downloadkubernetes.com/ was a 3rd party project. Is it now an in-project website? I'd want to be sure before doing that shortcode.
Yes, the author donated it to the project via SIG Release, and we are now exploring ways to maintain it :)

**Comment by sftim** [comment]
Where's the repo? I can file an issue there about adding an embed mode.

**Comment by puerco** [comment]
It is this one:
https://github.com/kubernetes-sigs/downloadkubernetes

**Comment by jimangel** [comment]
> I'm tempted to make this a layout not a shortcode. [...] I'd be tempted to generate HTML similar to the shortcodes for tabs.

@sftim are you interested in owning / PR'ing the above solutions? Happy to hand it off if so. My plan was really a quick and simple way to get things merged and then iterate from there. Going beyond "the solution is functioning using a shared data file and providing >=90% value of downloadkubernetes.com" was out-of-scope. 😅

> Another option is to include a (new and) special version of https://downloadkubernetes.com/ via an iframe

I would strongly encourage us not to use iframes. Mainly because there's not many active maintainers in `kubernetes-sigs/downloadkubernetes` so the burden falls on SIG-Release (or nobody). When it breaks, it requires cycles to fix. By leveraging the data file that SIG Release and SIG Docs own, we can reduce tech debt and incubate or drop the `downloadkubernetes` repo.

**Comment by sftim** [comment]
> the solution is functioning using a shared data file

Do we have a data source for these download URLs (ie, that shared data file) that we can rely on? If so, I think I can help rally effort to use that data on the page.

**Comment by jimangel** [comment]
> Do we have a data source for these download URLs (ie, that shared data file) that we can rely on?

The URLs would be created dynamically based on existing release information. Some examples:

```
VERSION=v1.22.0

# darwin / mac
https://dl.k8s.io/{{ VERSION }}/bin/darwin/amd64/kubectl
# checksum
https://dl.k8s.io/{{ VERSION }}/bin/darwin/amd64/kubectl.sha256

# linux
https://dl.k8s.io/release/{{ VERSION }}/bin/linux/amd64/kubectl
# checksum
https://dl.k8s.io/release/{{ VERSION }}/bin/linux/amd64/kubectl.sha512

# windows
https://dl.k8s.io/{{ VERSION }}/bin/windows/386/kubectl.exe
# checksum
https://dl.k8s.io/{{ VERSION }}/bin/windows/386/kubectl.exe.sha256

# bonus URLs
https://dl.k8s.io/release/{{ VERSION }}/SHA512SUMS
https://dl.k8s.io/release/stable.txt

# review downloadkubernetes for more URLs / binaries
```

@sftim do you have cycles to get a MVP example opened before going on holiday or have someone lined up I could work with? I'm keen on getting something in place ASAP. Thanks!

**Comment by sftim** [comment]
> The URLs would be created dynamically based on existing release information.

That sounds like a slightly fragile interface, but would do for now. I might make some of those details be a data lookup and make SIG Release the owners there.

I _think_ I can prototype that later today.

**Comment by sftim** [comment]
@jimangel it looks like I made a start on that (it's a while ago so I have kinda forgotten myself).
Did you get a chance to take a look?

**Comment by jimangel** [comment]
This fell off my plate too @sftim. I'm hoping to pick this back up over the holiday break. Thanks for the alt MVP examples!

**Pull request closed without merging**
