### PR TITLE
Update ValidatingAdmissionPolicy examples to v1

### PR DESCRIPTION
**Pull request by tao12345666333**
since v1.30 ValidatingAdmissionPolicy graduate to GA https://github.com/kubernetes/kubernetes/pull/123405

### CODE REVIEW

**Comment by tao12345666333** [comment]
@drewhagen should we merge this to dev-1.30?

**Comment by drewhagen** [comment]
@tao12345666333 Yeah, let's merge this in `dev-1.30` branch.

In the future, we want to try to get this in before Doc Freeze, like it should have been with this PR:
https://github.com/kubernetes/website/pull/45249

Thanks!

**Comment by tao12345666333** [comment]
Ok, thank you for the quick reply @drewhagen  I have changed the base branch to `dev-v1.30`.

**Review by sftim — COMMENTED** [review]
/approve

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!

/lgtm

**Pull request merged**
