### PR TITLE
Update FlexVolume casing

### PR DESCRIPTION
**Pull request by jpreese**
I signed it

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
There are also some such cases in other places of the repo. We might need to change them as well.

/cc @msau42

**Comment by jpreese** [comment]
Makes sense to me! I just stumbled upon this one, but didn't go through the entire docs repository.

**Comment by sftim** [comment]
@jpreese would you be willing to log an issue about fixing all the case mismatches, so that's tracked?

**Comment by jpreese** [comment]
@sftim issue opened at #15984

**Pull request merged**
