### PR TITLE
[pt-pt] Add minimum required content for European Portuguese localization

### PR DESCRIPTION
**Pull request by ricardoamaro**
Moved to https://github.com/kubernetes/website/pull/45894

### CODE REVIEW

**Comment by ricardoamaro** [comment]
@falsovsky feel free to review and make comments

**Comment by falsovsky** [comment]
As a native Portuguese I can confirm that the translation looks OK to me.
Nice job @ricardoamaro !

**Comment by sftim** [comment]
Thanks

We avoid issue references in commit messages, so:
/retitle [pt-pt] Add minimum required content for European Portuguese localization

**Comment by holgers66** [comment]
I would like to help with this localization (pt-pt). I am already a member of the kubernetes org.

**Comment by ricardoamaro** [comment]
Moved to https://github.com/kubernetes/website/pull/45894

**Pull request closed without merging**
