### PR TITLE
Fix mismatched API groups in ValidatingAdmissionPolicy page

### PR DESCRIPTION
**Pull request by MeenuyD**
The page about ValidatingAdmissionPolicy uses a mixture of API groups: now it will use only admissionregistration.k8s.io/v1beta1 to maintain consistency.
#42876

### CODE REVIEW

**Comment by MeenuyD** [comment]
But I have doubt because on the
 https://k8s.io/docs/reference/access-authn-authz/validating-admission-policy/ 
page, there is one more example that uses the admissionregistration.k8s.io/v1alpha1 API should I change that also?

**Comment by sftim** [comment]
/retitle Fix mismatched API groups in ValidatingAdmissionPolicy page

**Review by vaibhav2107 — COMMENTED** [review]
/lgtm

**Pull request merged**
