### PR TITLE
Change restore volume from snapshot feature status to beta

### PR DESCRIPTION
**Pull request by xing-yang**
This PR marks restore volume from snapshot feature to beta.

Fixes: #19480

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-19484--kubernetes-io-master-staging.netlify.com/docs/concepts/storage/persistent-volumes/

**Comment by kbhawkey** [comment]
@msau42 , Would you have time to review this pull request?

**Comment by msau42** [comment]
/lgtm
from tech

**Pull request merged**
