### PR TITLE
Branch sync for dev-1.21: primary branch changes, latest API reference

### PR DESCRIPTION
**Pull request by sftim**
Incorporate changes into the _dev-1.21_ branch for:
- latest changes from [master](https://github.com/kubernetes/website/tree/master) branch
- API reference update from PR #27248

I reverted merge commit a2f0abd8474ff7ecc76e0ed51812e8d99a2629b9 because the new API reference was certain to overwrite it, then selected the same changes in the merge commit that I manually revised.

I have locally tested that the resulting merge will merge cleanly into _master_.
/milestone 1.21
Cc: @reylejano

### CODE REVIEW

**Comment by sftim** [comment]
Sync will update PR #26153

**Comment by sftim** [comment]
Previews:
- [front page](https://deploy-preview-27438--kubernetes-io-vnext-staging.netlify.app/)
- [API reference](https://deploy-preview-27438--kubernetes-io-vnext-staging.netlify.app/docs/reference/kubernetes-api/)

**Comment by PI-Victor** [comment]
all the concerns from my previous sync attempt have been addressed. i also see the build process is passing and there are no failed commits for this sync.

/lgtm

**Comment by reylejano** [comment]
Thank you @sftim 
/approve

**Pull request merged**
