### PR TITLE
Added hover effect on buttons

### PR DESCRIPTION
**Pull request by Rituraj-13**
Added Hover Effect on buttons to enhance user experience.

Fixes Issue - #43173 

https://github.com/kubernetes/website/assets/90104572/688d4803-3601-4d6b-a26d-8efab65dff65

### CODE REVIEW

**Comment by Rituraj-13** [comment]
@onlydole please review this PR and let me know if I need to change something.
Thanks !

**Review by onlydole — APPROVED** [review]
Howdy, @Rituraj-13 - thank you for your contribution, I think this looks great!

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/lgtm

[Preview Page](https://deploy-preview-43175--kubernetes-io-main-staging.netlify.app/)

**Comment by Rituraj-13** [comment]
> Howdy, @Rituraj-13 - thank you for your contribution, I think this looks great!

Thank You !! 😀

**Pull request merged**
