### PR TITLE
Revise pull request template

### PR DESCRIPTION
**Pull request by sftim**
I suggest switching to a new pull request template:

```html
<!-- 🛈

 Hello!

 Remember to ADD A DESCRIPTION and delete this note before submitting
 your pull request. The description should explain what will change,
 and why.

 If you're documenting an existing feature, you don't need to change
 the Base Branch; “master” is selected by default.

 For pull requests on 1.18 Features, set Milestone to:
  1.18
 and Base Branch to:
  dev-1.18

 For pull requests to a collaborative localization, set Base Branch to:
  dev-1.17-<language code>.<latest team milestone>

 If localizing and there is no dev-1.17-<language code>.<team milestone>
 branch, but dev-1.16-<language code>.<team milestone> exists, use that.

 If you want help on choosing which branch to use, visit:
  https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use


 For overall help on editing and submitting pull requests, visit:
  https://kubernetes.io/docs/contribute/start/#improve-existing-content

-->
```

### CODE REVIEW

**Comment by sftim** [comment]
If contributors leave the PR description as-is, it will show as blank. I think that makes it clearer that something has been left out.

What do other people think?

**Comment by sftim** [comment]
Also see #18800

**Comment by sftim** [comment]
Revised as per discussion in last SIG Docs meeting.

**Comment by zacharysarah** [comment]
@sftim Thanks for updating with feedback! ✨ 

/lgtm
/approve

**Comment by zacharysarah** [comment]
@celestehorgan 👋 Raising visibility for impact on #18920

**Pull request merged**
