### PR TITLE
merge main onto dev-1.23

### PR DESCRIPTION
**Pull request by jlbutler**
Merge 'main' onto dev-1.23 integration branch.

### CODE REVIEW

**Comment by reylejano** [comment]
Build error with commit 9d5769e, fixed in the same PR https://github.com/kubernetes/website/pull/29626 with commit 6fe1e16

**Comment by PI-Victor** [comment]
unfortunately i lost my super powers and can't approve anymore, but LGTM!

**Comment by sftim** [comment]
Ah, that's a tiny bit annoying.
/committee steering

for the announcement changes.

**Pull request merged**
