### PR TITLE
WIP: Add cephfs CSI migration details to doc

### PR DESCRIPTION
**Pull request by humblec**
https://github.com/kubernetes/enhancements/issues/2924

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
Cc @xing-yang

**Comment by mehabhalodiya** [comment]
The v1.24 milestone no longer tracks the KEP that this PR supports. Thanks for your effort on this documentation; I recommend saving this work for a future release.

/close

If you feel that this PR has been closed in error, please feel free to reopen it against another branch.
Thank you!

**Pull request closed without merging**
