### PR TITLE
update links on kubeadm add windows nodes page for kube-proxy and fla…

### PR DESCRIPTION
**Pull request by reylejano**
Fixes issue https://github.com/kubernetes/website/issues/29149 and https://github.com/kubernetes/website/issues/29459

This PR updates links for flannel-host-gw.yml and kube-proxy.yml

### CODE REVIEW

**Comment by reylejano** [comment]
@kubernetes/sig-windows-misc and @kubernetes/sig-windows-leads please review this PR if the correct manifests for kube-proxy.yml and flannel-host-gw.yml are used

**Comment by reylejano** [comment]
Preview of updated page 
https://deploy-preview-29755--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

**Comment by perithompson** [comment]
these look correct to me @reylejano! Thanks for correcting them! Unless @kubernetes/sig-windows-leads feel like we should be locking to a release rather than master, I think this is good to go.  

FWIW It looks like there used to be a release tag but since the nightly builds were added for containerd builds, the flannel and kube-proxy manifests got removed.  @marosset should we add them back?

**Comment by perithompson** [comment]
this is raised in https://github.com/kubernetes/website/issues/29708

**Comment by perithompson** [comment]
This is mentioned in https://github.com/kubernetes/website/issues/29708 as well

**Comment by marosset** [comment]
I fixed the existing links by switching the new releases in sig-windows-tools repo to release.

I'd prefer not to have the URLs point to the master branch.
Maybe we can introduce a new tag (like kubeadm-latest-release) that we use for each release and then move that each time there is a new release or something and reference that if we run into this issue again.
@jsturtevant  thoughts?

**Comment by reylejano** [comment]
@marosset Thank you for fixing the links, I'll close this PR and close related issues

/close

**Pull request closed without merging**
