### PR TITLE
Fix broken link in topology-aware-routing.md

### PR DESCRIPTION
**Pull request by chrono**

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@chrono Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: https://git.k8s.io/community/CLA.md

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Comment by dipesh-rawat** [comment]
Explicit hold  to avoid accidental merges until the CLA is signed (Refer https://github.com/kubernetes/website/pull/46667#issuecomment-2148183836).
/hold

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by Shubham82** [comment]
/unhold
as EasyCLA is s signed now.

**Comment by Shubham82** [comment]
@dipesh-rawat could you please approve this PR?

Thanks!

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for the fix!
Congrats on your first PR 🎉
/approve

**Pull request merged**
