### PR TITLE
Improve Hindi readme Readability and user friendliness

### PR DESCRIPTION
**Pull request by pojith**

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @pojith please can you let us know how this improves readability?

**Comment by pojith** [comment]
I have a doubt for uploading readme file 
Is this location were want to upload
/area localization
/language hi

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @pojith, thank you for your contribution.

As you mentioned in the previous comment, this PR doesn't introduce any changes related to those goals. 

These are not trivial/typo edits. Please read the [Kubernetes Contributor Guide](https://kubernetes.io/docs/contribute/) before making your next contribution. We've outlined the answers and provided an in-depth guide on how contributors can contribute, irrespective of their experience level. 

We are excited to see you around. However, I shall close this PR since it doesn't add value.

/close

**Pull request closed without merging**
