### PR TITLE
fixed a typo in docs/concepts/configuration/pod-priority-preemption.md

### PR DESCRIPTION
**Pull request by stszap**
"Pod may by scheduled" > "Pod may be scheduled"

### CODE REVIEW

**Comment by stszap** [comment]
Signed a CLA.

**Comment by stszap** [comment]
I signed it

**Comment by zparnold** [comment]
Hey there! @stszap, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by stszap** [comment]
For some reason I didn't get an email when I first tried to sign the CLA a week ago but now it worked (got the pdf).

**Pull request merged**
