### PR TITLE
blog: disable owners inheritance for blog subproject

### PR DESCRIPTION
**Pull request by idealhack**
address https://github.com/kubernetes/website/pull/16135#issuecomment-562714349

### CODE REVIEW

**Comment by onlydole** [comment]
Thank you, @idealhack!

**Comment by kbarnard10** [comment]
Thanks @idealhack! We previously removed this because it was causing blockers in PR review. For example, any release branch that touched the blog repo required our approval. Even small typo fixes and link changes. 

We removed it so that SIG-Docs approvers, especially the weekly PR wranglers could move more quickly to review and approve things that don't really need our sign off. 

My preference is to leave the permissions as is and we'll provide more training to SIG-Docs approvers on this process. 

Full details on the blog process can be found here for those following: https://github.com/kubernetes/community/tree/master/sig-docs/blog-subproject

**Comment by idealhack** [comment]
@kbarnard10 thanks for the explanation!

**Pull request closed without merging**
