### PR TITLE
[zh] Resync docs/setup/production-environment/container-runtimes.md

### PR DESCRIPTION
**Pull request by ydcool**
closes: #24788

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
@ydcool There is another ongoing PR changing the upstream file (#24780). Let's wait until that one is merged.
Thanks.

**Comment by tengqm** [comment]
/hold cancel
#24780 is in.

**Comment by tengqm** [comment]
Overall looks good.
Not sure if changes made in #24780 has been accommodated. 
/lgtm

**Comment by tengqm** [comment]
/lgtm cancel
Seems that changes in #24780 is not incorporated. Please rebase.

**Comment by ydcool** [comment]
rebase done

**Comment by ydcool** [comment]
rebase done

**Comment by tengqm** [comment]
thanks, @ydcool 
/lgtm
/approve

**Pull request merged**
