### PR TITLE
rkatz stepping down from pt approvers

### PR DESCRIPTION
**Pull request by rikatz**
I would like to step down as a Portuguese approvers/reviewers. I've not been able recently to focus on it. @stormqueen1990 @devlware @edsoncelio and @MrErlison are doing a great work here, and I hope they can keep doing this amazing work.

Thank you all for the trust, I am still around if you need something from me

/cc @divya-mohan0209 @natalisucks @jimangel

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
Thank you @rikatz for all the hard work!

/lgtm

**Comment by divya-mohan0209** [comment]
Assigning the correct co-chair since Jim's now emeritus.
/assign @reylejano

**Comment by tengqm** [comment]
@rikatz As another contributor from the other side of the planet, I can understand what you were saying in that email. However, I have a different perceiption about community work. What I had experienced is much more unacceptable than your case. There are people seeing you through a colored glasses. There are cases where people believe the world center is the 5th Avenue. Those are all fine.

Community contribution is about contribution, period. It is about working with folks from other corners of the planet to make something better, rather than being promoted, recognized or awarded. The only person who can judge you is you yourself. Do what you believe is the right thing, while be open-minded when different opinions appear. Keep leading a happy life is more important than anything else. You may want to reward yourself for doing something useful to others, for example, some fresh beers?

**Comment by reylejano** [comment]
Thank you @rikatz , your contributions have made adopting and using Kubernetes easier by the global community
/approve

**Pull request merged**
