### PR TITLE
Translate configuration/taint-and-toleration.md in Korean

### LINKED ISSUE #20251: Translate configuration/taint-and-toleration.md in Korean
**This is a Feature Request**

**What would you like to be added**

Translate concepts/configuration/taint-and-toleration.md in Korean.

**Why is this needed**

There is no document with concepts/configuration/taint-and-toleration.md file in Korean.

**Comments**

Page to update: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

### PR DESCRIPTION
**Pull request by pjhwa**
This fixes #20251 .
There is a broken link in the original document on the Line 13.
I’ve suggested the fix as #20256 for this issue. So, this translation depends on #20256 .

This PR is created newly to fix broken PR #20258 .
This PR is reflected on reviewer's comments from PR #20258 .

### CODE REVIEW

**Comment by pjhwa** [comment]
Preview: https://deploy-preview-20404--k8s-dev-ko.netlify.app/ko/docs/concepts/configuration/taint-and-toleration/

**Comment by ysyukr** [comment]
@pjhwa 감사합니다 :)
/lgtm

**Pull request merged**
