### PR TITLE
optimize a link for connect-applications-service

### PR DESCRIPTION
**Pull request by niuzhenguo**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by windsonsea** [comment]
hmmm, the current link works well while `/docs/concepts/services-networking/connect-applications-service/` is redirected to `/docs/tutorials/services/connect-applications-service/`

However, this redirect is not friendly to localization. I think this change is ok.

/lgtm

**Review by sftim — COMMENTED** [review]
/kind cleanup
/lgtm
/approve

Thanks

**Pull request merged**
