### PR TITLE
Fix date for “Spotlight on SIG Docs” article

### PR DESCRIPTION
**Pull request by sftim**
Change filename to match publication date. Article is https://kubernetes.io/blog/2022/08/02/sig-docs-spotlight-2022/

/kind cleanup
/area blog

### CODE REVIEW

**Comment by Sea-n** [comment]
I think it's even better to move it out of directory.

`content/en/blog/_posts/2022-08-02-sig-docs-spotlight/` only contains one `index.md` file.

**Comment by sftim** [comment]
I'm happy with the simple tidying.

**Comment by mk46** [comment]
Preview looks fine.
/lgtm

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks Tim for these changes!
/approve

**Pull request merged**
