### PR TITLE
Fix Invalid link in readme section

### PR DESCRIPTION
**Pull request by Arhell**
Hello!

Issue [link](https://github.com/kubernetes/website/issues/19177)

### CODE REVIEW

**Comment by sftim** [comment]
/language ru

If someone from the Russian localization team can /lgtm this it'll be good for approval.

**Comment by sftim** [comment]
Actually, I'll add
/lgtm

because I can see that the change is valid. Would still like someone from the Russian localization to give this a nod of approval before this merges.

**Comment by php-coder** [comment]
@Arhell thank you!

/lgtm

**Comment by php-coder** [comment]
@sftim PTAL I feel that this can be merged :)

**Pull request merged**
