### PR TITLE
[de] Update hello-minikube.md

### PR DESCRIPTION
**Pull request by mab**
Replace depreacted heapster plugin by the metrics-server

### CODE REVIEW

**Comment by mab** [comment]
I need to clarify if the company signs the CLA or I sign the CLA.

**Comment by RA489** [comment]
> I need to clarify if the company signs the CLA or I sign the CLA.

if you are contributing on behalf of your company then company needs to sign your CLA and if if you are contributing as individual contributor the you need to sign your CLA by yourself.

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by mab** [comment]
The preview under https://deploy-preview-29865--kubernetes-io-main-staging.netlify.app/docs/tutorials/hello-minikube/ does not show the changes. Have I done something wrong?

**Pull request closed without merging**
