### PR TITLE
Update KubeletConfig doc to reference the release-1.9 code base

### PR DESCRIPTION
**Pull request by cimomo**
The API version has been bumped up to v1beta1 in the master branch.

### CODE REVIEW

**Comment by mtaufen** [comment]
Lol this is something like the fifth one of these I've had to comment on... the changes were already made on the `release-1.10` branch in #7561 and will be released alongside the official Kubernetes release.

**Comment by cimomo** [comment]
@mtaufen LOL, so that you won't have to comment on more of these, how about we point this to release-1.9 to fix the broken reference that's on the live document site. It will be updated to v1beta1 with your change when v1.10 gets released and the doc always stays consistent.

**Comment by mtaufen** [comment]
That sgtm.

**Comment by mtaufen** [comment]
Please also update the PR title/text and squash commits.

**Comment by cimomo** [comment]
@mtaufen Sure ... updated the PR message and squashed the commits.

**Comment by mtaufen** [comment]
@tengqm should this merge to `master` or to the `release-1.9` branch?

**Comment by tengqm** [comment]
@mtaufen I believe this (link fix) should go to the master branch.

**Comment by cimomo** [comment]
@zacharysarah Please approve. Thanks!

**Pull request merged**
