### PR TITLE
use note short tags

### PR DESCRIPTION
**Pull request by makocchi-git**
Use `{{< note >}}` tag under `tasks/access-application-cluster/` pages.

### CODE REVIEW

**Comment by makocchi-git** [comment]
check urls are here
https://deploy-preview-9023--kubernetes-io-master-staging.netlify.com/docs/tasks/access-application-cluster/list-all-running-container-images/
https://deploy-preview-9023--kubernetes-io-master-staging.netlify.com/docs/tasks/access-application-cluster/load-balance-access-application-cluster/

**Comment by GuessWhoSamFoo** [comment]
Are all instances of `**Note:**` to be wrapped in the shortcode?

There are also variations like `Note:` and `**Note**:` that can be addressed in a different PR

**Pull request merged**
