### PR TITLE
Fixes the IP addresses shown in the ip-masq diagram at k8s.io/docs/tasks/administer-cluster/ip-masq-agent/

### LINKED ISSUE #13917: Issue with k8s.io/docs/tasks/administer-cluster/ip-masq-agent/
**This is a Bug Report**

The IP address in the example diagram needs to represent correct ip4 address.  The PodA,PodB are given 10.1.1.1.2. 

**Problem:**
The IP address in the example diagram needs to represent correct ip4 address.  The PodA,PodB are given 10.1.1.1.2. Four dots in address space.
**Proposed Solution:**
Change to correct ip address format
**Page to Update:**
k8s.io/docs/tasks/administer-cluster/ip-masq-agent/ diagram

### PR DESCRIPTION
**Pull request by palnabarun**
Fixes #13917 

The Pod IP addresses shown in the `ip-masq` diagram were wrong. They have been corrected with this PR.

There are also some minor improvements to the diagram. The `draw.io` editable diagram is also embedded with the image.

I tried to compress the image for size reduction, but the embedded diagram gets lost and is unreadable after compression.

### CODE REVIEW

**Comment by palnabarun** [comment]
cc: @sftim

**Comment by sftim** [comment]
Nice work @palnabarun 

Do you know how to amend a commit? The reason I ask is that if you do, I'd suggest that you change the wording on the commit (527ff3ac2b08e559fba200f6165a0422fef95fb9) to mention that the image is editable in draw.io

If you're not sure how to do that, not to worry - we can give advice or maybe tweak it on your behalf. The visible changes are fine as they are!

**Comment by palnabarun** [comment]
@sftim Sure. Let me edit the commit.

**Comment by palnabarun** [comment]
Changed the commit message. Let me know if any more changes are required.

**Comment by sftim** [comment]
OK, nice.
/lgtm

**Pull request merged**
