### PR TITLE
Add MP Interactive Tutorial to Stateless Section

### PR DESCRIPTION
**Pull request by mbroz2**
This provides the previously discussed/socialized and demoed Interactive Tutorial for configuring Java microservices in Kubernetes.

There will be two PRs of which only one should be accepted.
The [first one](https://github.com/kubernetes/website/pull/21268) which places the tutorial under the "Configuration" (`/configuration`) section in the ToC.
The second PR (this one) has the exact same content, but places it under "Stateless Applications" (`/stateless-application`) section in the ToC.

Please note that (in both PRs) the Katacoda tutorial is hosted at `data-katacoda-id="jamiecoleman/kubeconfig"` and not at `kubernetes-bootcamp` so that will likely need an action to be moved/migrated in Katacoda, and then the PR updated to point at the location in `kubernetes-bootcamp`

### CODE REVIEW

**Comment by mbroz2** [comment]
I followed what the bot instructed and assigned @xiangpengzhao to this PR, and @makoscafee to the [second PR](https://github.com/kubernetes/website/pull/21269) which have the exact same content (as per the description in the first comment), but are just in a different location.  Likely only one person should be assigned to both PRs (and only one PR should be approved).

**Comment by sftim** [comment]
I reviewed #21268
/assign

**Comment by kbhawkey** [comment]
Hi @mbroz2 .
Just following up on this PR. Are you actively working on these changes?

**Comment by kbhawkey** [comment]
Hello @mbroz2 .
I am closing this pull request.
At any time, you can reopen this PR to resume work. 
/close

**Comment by mbroz2** [comment]
Hi, yes, was planning on having an update before the end of this week, just coordinating the changes to both the interactive tutorial (katacoda) and the text for the site. I'll reopen the PR when I have those updates ready.

**Comment by mbroz2** [comment]
Thank you for taking the time to provide the detailed feedback, we've been working on incorporating all of it into the Katacoda tutorial and PR for the tutorial page.

The Katacoda environment has been updated to reflect all the comments, with the exception of the HTTP basic auth being used. HTTP was purposefully used as it is not uncommon (especially in private cloud/kubernetes deployments) to terminate TLS at the proxy to reduce processing overhead and it simplifies the example in the tutorial and avoids complexities regarding trusting/managing self-signed certs. In other words, we were avoiding additional complexity and overhead of HTTPS. However, if you believe this is an issue and needs to be addressed, then we can change the environment to support HTTPS.

The tutorial topic page has also been changed to better match the other content under the "Configuration" (and Stateles/Stateful Applications) section, for example the "Configuring Redis using a ConfigMap" and "Example: Deploying PHP Guestbook application with Redis" with the main difference that instead of the instructions being placed on the page, the page instead links out the Katacoda Interactive Tutorial environment. Like the other examples, a light overview of the concepts is provided first, followed by the example section where the user goes more in-depth with the subject, in a hand-on approach. The Kubernetes topics have been moved to the beginning of the section and expanded on, while the Java/MP topics have been moved down and shortened.

Regarding the above comment "At any time, you can reopen this PR to resume work." is that possible, or do I need to open a new PR?

**Comment by kbhawkey** [comment]
Yes:
```
/reopen
```

**Comment by zacharysarah** [comment]
This also looks like an unintentional `/reopen`. ☝️ 

/close

**Comment by mbroz2** [comment]
Hi @zacharysarah it was meant to be reopened and waiting for a review and approval/feedback, but I missed the bots instruction to assign @sftim.  Reopening and assigning sftim, please see [my previous comment](https://github.com/kubernetes/website/pull/21269#issuecomment-671600931) for details.

/reopen
/assign @sftim

**Comment by sftim** [comment]
@mbroz2 this is marked as work in progress; if that's not what you want, you can edit the PR title to remove the “[WIP]”

**Comment by kbhawkey** [comment]
Hi @mbroz2 .
I don't think it makes sense to keep two PRs open for the same tutorial.
I left several comments in PR #21268.
Please select one PR to close.
Thanks!

**Comment by mbroz2** [comment]
Hi @kbhawkey,

I'm happy to close this PR and just continue the conversation in PR #[21268](https://github.com/kubernetes/website/pull/21268).  The reason 2 were open was to get feedback whether this guide should go into the Config section (#[21268](https://github.com/kubernetes/website/pull/21268)) or the Stateless App section ([this PR](https://github.com/kubernetes/website/pull/21269)), and each PR hosts the content under each of those categories.  
If it's instead decided that the Stateless App section is a better place for this content then the Config section, then I'll just reopen this PR and close the other one.

**Pull request closed without merging**
