### PR TITLE
Fix issue with k8s.io/ko/docs/concepts/overview/components.md

### LINKED ISSUE #22230: Issue with k8s.io/ko/docs/concepts/overview/components.md
**This is a Bug Report**

**Problem:**
Description에 대한 번역이 없습니다.
description: >
  A Kubernetes cluster consists of the components that represent the control plane
  and a set of machines called nodes.

**Proposed Solution:**
번역이 필요합니다.

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/overview/components/

### PR DESCRIPTION
**Pull request by woopyoung**
Fix #22230

### CODE REVIEW

**Comment by gochist** [comment]
@woopyoung 감사합니다!
/lgtm
/approve

**Comment by gochist** [comment]
@woopyoung PR을 처리하기 위해서 [CLA 서명](https://github.com/kubernetes/community/blob/master/CLA.md)을 부탁드립니다.

/hold

**Comment by gochist** [comment]
@woopyoung 감사합니다!
/hold cancel

**Comment by pjhwa** [comment]
Congratulations for your first contribution to kubernetes/website, @woopyoung !

**Pull request merged**
