### PR TITLE
Translate tutorials/.../configure-java-microservice-interactive/ into Korean

### LINKED ISSUE #24983: Translate tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/ into Korean
**This is a Feature Request**

**What would you like to be added**

Translate tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/ into Korean.

**Why is this needed**

There is no document of tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/ which is translated into Korean.

**Comments**

Page to translate: https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

/language ko

### PR DESCRIPTION
**Pull request by pjhwa**
Translate tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/ into Korean

Closes #24983 

This PR depends on #24980 which has _index.md file.

### CODE REVIEW

**Comment by pjhwa** [comment]
Preview page: https://deploy-preview-24984--k8s-dev-ko.netlify.app/ko/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

**Comment by seokho-son** [comment]
Thank you !
/approve

**Pull request merged**
