### PR TITLE
added correct link for slack channel

### LINKED ISSUE #42248: incorrect link Installing Kubernetes with kOps
**This is a Bug Report**

**Page Link** : https://kubernetes.io/docs/setup/production-environment/tools/kops/

 Incorrect Link in[ Whats Next](https://kubernetes.io/docs/setup/production-environment/tools/kops/#what-s-next) 
At Point
Follow kOps community discussions on Slack: [community discussions.](https://github.com/kubernetes/kops#other-ways-to-communicate-with-the-contributors)

**What would you like to be added**
Change Link :https://github.com/kubernetes/kops#other-ways-to-communicate-with-the-contributors to https://kubernetes.slack.com/archives/C3QUFP0QM

**Why is this needed**
This change will help readers to find relevant Slack Channel

### PR DESCRIPTION
**Pull request by deepak4566**
FIXES #42248

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @deepak4566, this PR is already raised here #42295.

**Comment by utkarsh-singh1** [comment]
Hi @deepak4566, thanks for the PR, but please try to investigate the issue and assign the issue before you raise a new PR, the issue #42248 is already assigned to somebody else.

**Comment by dipesh-rawat** [comment]
Changes already addressed as part of another PR [#42295](https://github.com/kubernetes/website/pull/42295/files)
/close

**Pull request closed without merging**
