### PR TITLE
Replace social_sprite.png with font icons.

### PR DESCRIPTION
**Pull request by supersam654**
Previously, social icons in the header and footer were displayed as sprites in `social_sprite.png`. After [asking in Slack](https://kubernetes.slack.com/messages/C1J0BPD2M/convo/C1J0BPD2M-1562161688.202100/) how to update the list of images, I discovered that there is no known process for updating this image and the last change was done by hand in Photoshop.

This PR:

* Deletes the existing `social_sprite.png` image
* Adds a custom icon font with just the icons we need
* Updates the references in the header and footer to use the new icon font.

After this gets merged, I think https://github.com/kubernetes/website/issues/10226 will be much easier to accomplish.

## Testing

* I looked at the icons in the footer when the browser was desktop-sized, tablet-sized, and phone-sized.
* I looked at the icons in header when the browser was tablet-sized and phone-sized.

I checked this in the latest version of Chrome and Firefox ESR. I don't easily have access to other browsers.

## Things I'm particularly looking for feeback on

* Has anyone used IcoMoon before? It's my first time doing something like this and it looked like a good tool for making small icon fonts with the added state file for easier sharing
* Did I put a bunch of new files in reasonable places?
  * In particular, is there a good spot for `font-icons.md`? I didn't think it belonged in the main contributing guide but I couldn't find a similar file to copy from either.

### CODE REVIEW

**Comment by sftim** [comment]
I had a look at the deploy preview's front page. When I looked, the new (font based) icons were vertically off-centre inside the blue rounded square, whereas the old (sprite based) icons were centred OK.

This was on mobile (Firefox 68.0b14 on Android 32-bit). On desktop (Firefox 68.0canonical-002 on Ubuntu x86_64), both the live site and deploy preview have the icons centred vertically.

On both platforms, this change alters the spacing between the blue rounded squares.

**Comment by sftim** [comment]
@supersam654 hope this feedback is useful&mdash;eg for separating desired and undesired impact.

**Comment by supersam654** [comment]
@sftim thanks for the feedback!

 I tweaked the icon size a bit so it should be closer to vertically centered on mobile (I think it's a pixel rounding issue and not actually off-centered so I don't know how to "officially" fix it).

In particular, the email icon looks a bit low but I think that's just the font. On mobile, if you look at the icons in the right nav menu, all of the icons look to be properly aligned. I'd also rather not add custom padding to a single icon for future maintainability reasons.

And I had noticed that the icons are a bit "smaller" in the blue squares. As I scaled the font up and down, I could never seem to make the icons match pixel-for-pixel with what they currently look like.

With all of that said, I think these small changes are acceptable. However, please let me know if either one of those points are really bothering you (or anyone else reading this).

**Comment by sftim** [comment]
Although I haven't checked this comprehensively, informally: looks good to me.

**Comment by sftim** [comment]
What more needs to happen to get this merged?

**Comment by supersam654** [comment]
I'm significantly biased and perhaps unqualified to say this, but I think it's ready to go :)

**Comment by supersam654** [comment]
Friendly ping. Is there anything else I can do to help this get merged?

**Comment by sftim** [comment]
@supersam654 I'm going to close this based on its age
However, please do feel free to open a new PR based on the same branch
/close

**Comment by sftim** [comment]
(I'd like to see these changes merged, and will be happy to take a look at a revised PR)

**Pull request closed without merging**
