### PR TITLE
[es] remove podpreset

### PR DESCRIPTION
**Pull request by earth429**
Remove podpreset.md from es.
The podpreset feature was removed from alpha.

Related: https://github.com/kubernetes/website/pull/25238 https://github.com/kubernetes/kubernetes/pull/94090

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @earth429, please sign EasyCLA first.

/easycla

**Comment by utkarsh-singh1** [comment]
@earth429, You can find about EasyCLA here - https://lfx.linuxfoundation.org/tools/easycla

**Comment by earth429** [comment]
@utkarsh-singh1  I wanted to inform you that I have completed the signing process for EasyCLA. Thank you!

**Review by ramrodo — APPROVED** [review]
/lgtm

**Pull request merged**
