### PR TITLE
Fix examples test

### PR DESCRIPTION
**Pull request by tengqm**
There is a newly added YAML not covered by the test case. This PR adds it to the test case.

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
@tengqm Thank you for the PR. Is there a link where I can preview this? I'm sorry if this comes across as a stupid question.

**Comment by tengqm** [comment]
> @tengqm Thank you for the PR. Is there a link where I can preview this? I'm sorry if this comes across as a stupid question.

There is no preview for this. You can check the https://github.com/kubernetes/website/blob/main/content/en/examples/README.md file and run the test case.
Basically, the test case is there to ensure all example YAML files can be validated against the APIs provided by the current k8s release.

**Comment by sftim** [comment]
Thanks

/approve

**Comment by ydFu** [comment]
thanks
/lgtm

**Pull request merged**
