### PR TITLE
Add new task on how to debug running apps

### PR DESCRIPTION
**Pull request by bettyjunod**
This is a page to show an example of how to debug running kubernetes applications with the squash open source project.

### CODE REVIEW

**Comment by bettyjunod** [comment]
CLA signed

**Comment by bettyjunod** [comment]
Hi @sftim I modeled it after other examples like below which show using other tools with Kubernetes. LMK if the way this is written is what needs to change - happy to make adjustments 

https://kubernetes.io/docs/tasks/debug-application-cluster/local-debugging/
https://kubernetes.io/docs/tasks/debug-application-cluster/falco/

**Comment by sftim** [comment]
Essentially, if SIG Docs adopts a policy around documenting a minimum to run in-tree Kubernetes, pages such as https://kubernetes.io/docs/tasks/debug-application-cluster/falco/ might go, or be subject to a special exception process (probably the former).

How important is it to provide this documentation as part of the Kubernetes website? For example, could you have a page on the Squash website instead?

**Comment by kbhawkey** [comment]
Hello @bettyjunod , What do you think about converting your content to a blog post?

**Comment by bettyjunod** [comment]
ok will do

**Pull request closed without merging**
