### PR TITLE
typo

### PR DESCRIPTION
**Pull request by custa**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.9 Features: set Milestone to `1.9` and Base Branch to `release-1.9`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: Please check the “Allow edits from maintainers” box (see image below) to
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.
>
> NOTE: After opening the PR, please *un-check and re-check* the "Allow edits from maintainers" box. This is a temporary workaround to address a known issue with GitHub.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6670)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@custa  please sign the CLA & resolve the conflict
your PR LGTM

**Comment by custa** [comment]
done

**Comment by custa** [comment]
@zhangxiaoyu-zidif  @tengqm 
pls merge

**Comment by xiangpengzhao** [comment]
@custa please resolve the conflicts and squash the commits. A `Merge branch 'master' into patch-1` commit is kinda a noise in the commit history :)

**Comment by custa** [comment]
@xiangpengzhao 
pls merge

**Pull request merged**
