### PR TITLE
Use Kubernetes colors in state diagram for pod scheduling readiness

### LINKED ISSUE #38432: Wrong colors in diagram for Pod Scheduling Readiness
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/ has a diagram, but it doesn't use Kubernetes colors.

**Proposed Solution:**
Copy the `classDef` colors from an example in https://kubernetes.io/docs/contribute/style/diagram-guide/ and then apply those colors to the items in the diagram.

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/

/priority backlog

### PR DESCRIPTION
**Pull request by tan-i-ham**
### Description
improve stateDiagram's style in pod-scheduling-readiness page
fix #38432

### Approach
Use the same method as #33971
Generated the SVG file from [mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor)

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Use Kubernetes colors in state diagram for pod scheduling readiness 

This is for #38432

**Review by divya-mohan0209 — COMMENTED** [review]
Do we still want to leave the dot at the end in the non-Kubernetes colour or is the previous colour retained intentionally?

**Comment by sftim** [comment]
Ah, good spot. The final stage of the diagram could also be Kubernetes blue.

**Comment by tan-i-ham** [comment]
> Ah, good spot. The final stage of the diagram could also be Kubernetes blue.

Unfortunately, mermaid, for now, does not provide styling for end stage

According to this page, https://mermaid.js.org/syntax/stateDiagram.html#styling-with-classdefs

>> Cannot be applied to start or end states

**Comment by sftim** [comment]
If you manually recolor the terminator to blue, I won't mind that the source doesn't reflect this.

/lgtm

**Comment by tan-i-ham** [comment]
> If you manually recolor the terminator to blue, I won't mind that the (Mermaid) source doesn't reflect this.
> 
> /lgtm

Thanks, good idea.
I have changed the color manually to the svg.

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Comment by sftim** [comment]
Thanks

/approve

**Pull request merged**
