### PR TITLE
Update replicaset.md

### PR DESCRIPTION
**Pull request by BruiserT**

### CODE REVIEW

**Comment by zparnold** [comment]
@BruiserT thanks for your contribution! 🎉 We really would love to have it, unfortunately to continue we need to have your (or your company's) signature on a CLA! For now I'm going to close this, but fret not! You can re-open whenever you have a chance. Thanks!

**Comment by celestehorgan** [comment]
Hey there! @BruiserT, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by celestehorgan** [comment]
Hey there! @BruiserT, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jimangel** [comment]
@BruiserT :wave: given the length this PR has gone with no activity, I'm going to close it. 

Feel free to reopen the PR once the CLA issue is resolved or reach out if we can help! Thanks!

/close

**Pull request closed without merging**
