### PR TITLE
More Online Learning

### PR DESCRIPTION
**Pull request by Chazzledazzle1**
Can you please add this course to the list? Please & thank you! 

* [Certified Kubernetes Administrator Preparation Course (LinuxAcademy.com)](https://linuxacademy.com/linux/training/course/name/certified-kubernetes-administrator-preparation-course)

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
> Help editing and submitting pull requests:  https://deploy-preview-9510--kubernetes-io-master-staging.netlify.com/docs/contribute/start/#submit-a-pull-request.
> Help choosing which branch to use, see
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by bradtopol** [comment]
@Chazzledazzle1 Thank you for your contribution. Please sign the CLA so we can accept your pull request for review.

**Comment by xiangpengzhao** [comment]
@Chazzledazzle1 Guess your CLA status is still not verified.

**Comment by Chazzledazzle1** [comment]
[individual-cla.pdf](https://github.com/kubernetes/website/files/2289004/individual-cla.pdf)

Here is the individual version of CLA! :)

**Comment by xiangpengzhao** [comment]
The bot will confirm the CLA status if it's ready. But seems like the CLA status is not ready yet. I'm not sure why. Could you please check if you sign CLA using the same email address with what you use on Github?

BTW, you don't need to attach in the comment with your CLA file which includes your private information :)

**Comment by Chazzledazzle1** [comment]
Hey Peter,

I absolutely used the same email on the CLA as my Github account. Anyway
you could help me, or should I retry all over again?

Thank you,




*Chaz Wallace. *Partnerships & Event Manager.

125 Bear Creek Pkwy. Keller. TX 76248
<https://maps.google.com/?q=125+Bear+Creek+Pkwy.+Keller.+TX+76262&entry=gmail&source=g>

________________________________

*We support others in their mission to learn and grow.*
*We are committed to changing the world by changing lives.*
*We believe in the curiosity to learn, the vulnerability to try, the
persistence to succeed, and the strength of community.*
*We put our students' futures first.*
*We dedicate ourselves to pushing the boundaries of online learning.*
________________________________

*LinuxAcademy.com <http://linuxacademy.com/>*
Facebook <https://www.facebook.com/linuxacademycom/> | LinkedIn
<https://www.linkedin.com/company/linuxacademy> | Twitter
<https://twitter.com/linuxacademyCOM?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
 | YouTube <https://www.youtube.com/user/pineheadtv>

**Comment by zacharysarah** [comment]
@Chazzledazzle1 👋 Please feel free to reopen this PR once you've [resolved the CLA](https://github.com/kubernetes/website/pull/9838#issuecomment-418565863). ☝️

**Pull request closed without merging**
