### PR TITLE
Add a term project to glossary

### PR DESCRIPTION
**Pull request by hezhizhen**

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
@hezhizhen I believe the existing wording is more appropriate.

In the existing page “project” is used to infer a specific use for a namespace: isolation between projects.

It's OK to reword; however, let's try to retain the original sense around isolation between different groups of people and the resources that those groups can use inside a shared cluster.

**Comment by hezhizhen** [comment]
> @hezhizhen I believe the existing wording is more appropriate.
> 
> In the existing page “project” is used to infer a specific use for a namespace: isolation between projects.
> 
> It's OK to reword; however, let's try to retain the original sense around isolation between different groups of people and the resources that those groups can use inside a shared cluster.

Sounds reasonable. Maybe we can add a little explanation to the concept `project`?

**Comment by sftim** [comment]
> Maybe we can add a little explanation to the concept project?

Sure, feel free to amend the PR!

**Comment by hezhizhen** [comment]
How about it? @sftim

**Comment by sftim** [comment]
@hezhizhen, I'm afraid that I don't think that the proposed new glossary entry matches how the Kubernetes community actually uses that term.
Essentially, the English word “project” has no special meaning within a Kubernetes context that differs from how other IT communities might use it.

**Comment by hezhizhen** [comment]
@sftim I'll leave a [link](https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/projects_and_users.html#projects) here and close the PR

**Pull request closed without merging**
