### PR TITLE
[zh-cn] resync: some file's commented English texts and indentation

### PR DESCRIPTION
**Pull request by hs0210**
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>

### CODE REVIEW

**Comment by howieyuen** [comment]
/hold

谢谢贡献。根据[指南](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87)约定，我们会拒绝对页面的部分修改。部分修改针对的是对应页面的英文上游还有其他改动需要同步的情况。
一旦我们合并了此 PR，将来就无法根据文件的最后更改时间来判断是否有其他上游变更尚未同步。请理解。

请使用下面脚本，补充未同步的变更：

```bash
./scripts/lsync.sh content/zh-cn/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice.md 

./scripts/lsync.sh content/zh-cn/docs/reference/access-authn-authz/psp-to-pod-security-standards.md
```

**Comment by hs0210** [comment]
> ./scripts/lsync.sh content/zh-cn/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice.md

@howieyuen I didn't change this file in this PR. And it seem that this file has been synced.

>   ./scripts/lsync.sh content/zh-cn/docs/reference/access-authn-authz/psp-to-pod-security-standards.md

I have compared the differences, and the parts that need to be synchronized have been modified in this PR

**Comment by howieyuen** [comment]
> > ./scripts/lsync.sh content/zh-cn/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice.md
> 
> @howieyuen I didn't change this file in this PR. And it seem that this file has been synced.
> 
> > ./scripts/lsync.sh content/zh-cn/docs/reference/access-authn-authz/psp-to-pod-security-standards.md
> 
> I have compared the differences, and the parts that need to be synchronized have been modified in this PR

sorry, I copy paste to the wrong PR...Now I correct it

**Comment by Sea-n** [comment]
The first file `content/zh-cn/docs/concepts/scheduling-eviction/node-pressure-eviction.md` is okay.

The second file `content/zh-cn/docs/concepts/workloads/controllers/job.md` have to other paragraph didn't synced.

Hold is still valid until fully synced, and I'm going to remove LGTM label.
/lgtm cancel

**Comment by hs0210** [comment]
> The second file content/zh-cn/docs/concepts/workloads/controllers/job.md have to other paragraph didn't synced.

@Sea-n It seems that the other paragraph has been synced by https://github.com/kubernetes/website/pull/35738.

**Comment by Sea-n** [comment]
You're right, the file have been synced by @windsonsea.

Then please rebase onto `kubernetes:main` and force-push this PR.

It's dirty to have previous commit assuming the later one will do the sync.

**Comment by hs0210** [comment]
> Then please rebase onto kubernetes:main and force-push this PR.
It's dirty to have previous commit assuming the later one will do the sync.

@Sea-n Done. PTAL.

**Comment by Sea-n** [comment]
Thanks for quick fix!

I think this PR is ready for merge. 😊
/unhold
/lgtm

**Pull request merged**
