### PR TITLE
[zh] Resync `certificates.md`

### PR DESCRIPTION
**Pull request by LittleAaron**
update certificates follow en doc.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@LittleAaron Please sign the CLA! (Ref: https://github.com/kubernetes/website/pull/31513#issuecomment-1021855298)

/retitle [zh] Resync `certificates.md`

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by jimangel** [comment]
Hey there! @LittleAaron, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by natalisucks** [comment]
Hey again, @LittleAaron! We're still needing you to sign the CLA in order to review and eventually merge this PR. More information can be found here: https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by howieyuen** [comment]
@LittleAaron You may need to double check your CLA email and commit email, make sure they are the same

**Comment by reylejano** [comment]
Hi @LittleAaron , since the EasyCLA has not been signed, I'm closing this PR
Feel free to reopen this PR with `/reopen` when you have signed the [EasyCLA](https://github.com/kubernetes/community/blob/master/CLA.md)
/close

**Pull request closed without merging**
