### PR TITLE
Fix URL in Redis Config Map tutorial

### PR DESCRIPTION
**Pull request by dougireton**
s/k8s.io/kubernetes.io in config map URL

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.11 Features: set Milestone to 1.11 and Base Branch to release-1.11
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by dougireton** [comment]
Creating a config map from file doesn't support URLs I'm fixing this to `wget` the file first, then create the config map

**Comment by tengqm** [comment]
@dougireton So ... this PR is still a WIP, not ready for review. Please add `[WIP]` to the PR title then.

**Comment by bradtopol** [comment]
@dougireton Thanks for your contribution. For some reason it is saying you still need to sign the CLA.  Not sure what happened there but please sign this so we can accept the PR.

**Comment by dougireton** [comment]
ok, I'll work on fixing that.

**Comment by dougireton** [comment]
@bradtopol I had to amend one of my commits so the Author name matched the Linux foundation username.

**Comment by tengqm** [comment]
This PR is no longer valid due to substantial changes already made to the related file.
/close

**Pull request closed without merging**
