### PR TITLE
Branch sync - Merge master with dev 1.19

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Sync master with dev-1.19

cc: @zacharysarah @jimangel @kbarnard10

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @savitharaghunathan ,
The changes look good except for this change (that shows an X):
https://github.com/kubernetes/website/pull/21073/commits/f1929c87ea9026546e456eba5f4a465dd4aefd8d

**Comment by sftim** [comment]
I'm not sure why https://github.com/kubernetes/website/pull/21073#issuecomment-631179373 / https://app.netlify.com/sites/kubernetes-io-master-staging/deploys/5ec42918bba0b0000785a9a1 is a problem - that merge seems valid to me.

@kbhawkey do you have a theory about why GitHub shows that as a failed commit?

**Comment by kbhawkey** [comment]
Hi. Nothing stands out in that pull request.
Look like the changes did not deploy. What happens if you "hit redeploy" in this pull request?
@savitharaghunathan , did you build your branch locally before sending in the PR?

**Comment by savitharaghunathan** [comment]
Hi @kbhawkey, do you mean building it locally with hugo? If so, No I did not.

**Comment by kbhawkey** [comment]
> 
> 
> Hi @kbhawkey, do you mean building it locally with hugo? If so, No I did not.

Yes, did you build your branch locally with the correct version of Hugo (extended version).

**Comment by savitharaghunathan** [comment]
> > Hi @kbhawkey, do you mean building it locally with hugo? If so, No I did not.
> 
> Yes, did you build your branch locally with the correct version of Hugo (extended version).

@kbhawkey No, I did not.

I followed the guide from docs role handbook -https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/docs#maintain-the-current-and-upcoming-dev-branch. If building with hugo locally is required, @jimangel or I could add this to the role handbook. 

Do I need to build locally and fore push this PR?

**Comment by jimangel** [comment]
> The changes look good except for this change (that shows an X):
f1929c8
>
> https://app.netlify.com/sites/kubernetes-io-master-staging/deploys/5ec42918bba0b0000785a9a1

`Failed during stage 'deploying site': Failed to execute deploy: Error: deploy timed out while waiting to enter states: prepared,ready`

I almost wonder if this was just a blip in Netlify rather than a specific failure to the PR. I saw some funky time outs on 5/14 that I added more details on [slack](https://kubernetes.slack.com/archives/C1J0BPD2M/p1589467624094000).

> did you build your branch locally with the correct version of Hugo (extended version)?

Since this PR is a merge from `master` to sync the `dev-x.Xy` branch (no new content) what would the purpose be of testing a local build?

If it fails, it would mean there's issues in `master` with no clear ownership for repairing and if the merge fails, we'll see that in the open PR.

I am open to including the step in the handbook, but I want to be sure I understand the value.

**Comment by kbhawkey** [comment]
Hi. I was not asking to change the handbook or challenge the process
Just thought that I would check my branch locally before pushing (because I do).
Regarding,
`I almost wonder if this was just a blip in Netlify rather than a specific failure to the PR. I saw some funky time outs on 5/14 that I added more details on slack.`
I too think that this is probably a Netlify error. Can we just hit the `redeploy` button and see if this "blip" resolves itself? In the past, I think we have given the go ahead and pushed the changes.
I think it would be good practice to figure out how to get a green line (every time).

**Comment by sftim** [comment]
Does Netlify test every commit? I didn't think it did.

**Comment by jimangel** [comment]
> Can we just hit the redeploy button and see if this "blip" resolves itself? 

I like this idea! Just kicked off again.

> I think it would be good practice to figure out how to get a green line (every time).

Agreed.

**Comment by jimangel** [comment]
It looks like redeploying builds from the latest state not that specific commit / PR. That might answer the question from @sftim ...

**Comment by kbhawkey** [comment]
This looks good now

**Pull request merged**
