### PR TITLE
grammar fixes for guaranteed-scheduling-critical-addon-pods.md

### PR DESCRIPTION
**Pull request by mukunda-**
Just a couple of nitpicks. Sorry. 😀

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
Thanks.
/lgtm

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Review by ydFu — APPROVED** [review]
it's typo,thanks.
/lgtm

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM, Thanks :+1:

**Pull request merged**
