### PR TITLE
[vi] Replace deprecated fullversion shortcode

### PR DESCRIPTION
**Pull request by rolfedh**
Fixes https://github.com/kubernetes/website/issues/41488

### CODE REVIEW

**Comment by rolfedh** [comment]
Preview of the "Cài đặt và cấu hình kubectl" topic: https://deploy-preview-41494--kubernetes-io-main-staging.netlify.app/vi/docs/tasks/tools/install-kubectl/

**Comment by rolfedh** [comment]
Related to https://github.com/kubernetes/website/issues/41005

**Review by sftim — COMMENTED** [review]
/lgtm

**Review by huynguyennovem — APPROVED** [review]
/lgtm
/approve

Thanks for the fix :)

**Pull request merged**
