### PR TITLE
[zh] Fix the output of "kubectl get deployment"

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

en PR https://github.com/kubernetes/website/pull/17351
/assign @tengqm
PTAL, thanks.

### CODE REVIEW

**Comment by fenggw-fnst** [comment]
Please note that, although following command shows a diff, actually this has already been updated in zh page.
```
$ ./scripts/lsync.sh content/zh/docs/reference/kubectl/docker-cli-to-kubectl.md
diff --git a/content/en/docs/reference/kubectl/docker-cli-to-kubectl.md b/content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
index ac7b7a49f..9c148702b 100644
--- a/content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
+++ b/content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
@@ -265,7 +265,7 @@ nginx-app    1/1     1            1           2m
 ``
 
 ``shell
-kubectl get po -l run=nginx-app
+kubectl get po -l app=nginx-app
 ``
 ``
 NAME                         READY     STATUS    RESTARTS   AGE
@@ -279,7 +279,7 @@ deployment "nginx-app" deleted
 ``
 
 ``shell
-kubectl get po -l run=nginx-app
+kubectl get po -l app=nginx-app
 # Return nothing
 ``
```

So this PR will also resync the docker-cli-to-kubectl.md.

**Comment by tengqm** [comment]
Thanks for the effort. Please run the following comand on the 'main' branch to find out other changes that need to be syned.

```
./scripts/lsync.sh content/zh/docs/reference/kubectl/docker-cli-to-kubectl.md
```

**Comment by fenggw-fnst** [comment]
Thanks for the review.

I have run the command one the newest 'main' branch and it shows:
```
$ ./scripts/lsync.sh content/zh/docs/reference/kubectl/docker-cli-to-kubectl.md
diff --git a/content/en/docs/reference/kubectl/docker-cli-to-kubectl.md b/content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
index ac7b7a49f..9c148702b 100644
--- a/content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
+++ b/content/en/docs/reference/kubectl/docker-cli-to-kubectl.md
@@ -265,7 +265,7 @@ nginx-app    1/1     1            1           2m
 ``
 
 ``shell
-kubectl get po -l run=nginx-app
+kubectl get po -l app=nginx-app
 ``
 ``
 NAME                         READY     STATUS    RESTARTS   AGE
@@ -279,7 +279,7 @@ deployment "nginx-app" deleted
 ``
 
 ``shell
-kubectl get po -l run=nginx-app
+kubectl get po -l app=nginx-app
 # Return nothing
 ``
```

But these changes have already been updated by https://github.com/kubernetes/website/commit/2c3ece825f7017cee38bc85dc9d7d1f2f2fea4b6

**Comment by tengqm** [comment]
@fenggw-fnst thanks for the confirmation.
/lgtm
/approve

**Pull request merged**
