### PR TITLE
index.html

### PR DESCRIPTION
**Pull request by zabi017**
Make a video from the script within minutes

### CODE REVIEW

**Review by Pradumnasaraf — COMMENTED** [review]
Hey, Sign the CLA fist. You can follow this message - https://github.com/kubernetes/website/pull/40031#issuecomment-1470531080

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by ydFu** [comment]
@zabi017 ,thank you for your contribution.

You must sign the CLA for teams of kubernetes/website to do code reiview.

Please click on the red button `NOT COVERED` line in the first comment.

If you don't know how to do it, here is[the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Comment by natalisucks** [comment]
PR Wrangler note: This contribution doesn't add value and seems to replicate a similar pattern across other open source projects from this user, as seen in [Flutter](https://github.com/flutter/website/pull/8396).

@zabi017 It's great that you wish to contribute, so I'd suggest that you read through our [docs contribution guidelines](https://kubernetes.io/docs/contribute/) to understand what you can do and where you can get started. You can also join the Kubernetes Slack community and ask any questions you have there.

/close

**Pull request closed without merging**
