### PR TITLE
Updating 1.9 navigation

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR fixes some 1.9 navigation elements overlooked by #9071: 
- Propagates fixes to `.travis.yml` added in #9357 
- Removes 1.6 navigation to comply with the docs standard of current+4

### CODE REVIEW

**Comment by zacharysarah** [comment]
See https://github.com/kubernetes/website/pull/9357#issuecomment-404303765 for discussion about Travis failing.

**Comment by tengqm** [comment]
This looks like the same problem #9423 is fixing.

**Comment by zacharysarah** [comment]
@tengqm It is, for `release-1.9`. Do I need to update this PR with the fix from #9423?

**Comment by tengqm** [comment]
@zacharysarah At least the `k8s.io/kubernetes/pkg/scheduler/api/latest` path needs a change. It has been relocated upstream.

**Comment by tengqm** [comment]
@zacharysarah Please try modify line 52 of test/examples_test.go from 
`schedulerapilatest "k8s.io/kubernetes/pkg/scheduler/api/latest"`
to
`schedulerapilatest "k8s.io/kubernetes/plugin/pkg/scheduler/api/latest"`

**Comment by zacharysarah** [comment]
@tengqm I changed too many things in `examples_test.go` at once--I'll regress and try them one at a time.

**Comment by zacharysarah** [comment]
@tengqm Looks like you fixed it! Feel free to lgtm/approve if you like it otherwise. 👍

**Pull request merged**
