### PR TITLE
docs deploy-intro, updated link to github

### LINKED ISSUE #8658: Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
**This is a...** 
- [ ] Feature Request
- [ x] Bug Report

**Problem:**

The link to the github repository at the bottom appears broken. I.e. this link isn't working: https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics

**Proposed Solution:**

This link is working and is probably the one that is intended: https://github.com/kubernetes/website/tree/master/content/en/docs/tutorials/kubernetes-basics

**Page to Update:**

https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### LINKED ISSUE #8659: Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The [Github link](https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics) shows 404.

**Proposed Solution:**

Replace the link URL with a working one. I could not find the correct one.

**Page to Update:**
https://kubernetes.io/...

### LINKED ISSUE #8678: Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics does not exist

**Proposed Solution:**
Update the URL to point to the proper location

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### LINKED ISSUE #8720: Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
**This is a...** 

- [ ] Feature Request
- [ X ] Bug Report

**Problem:**
Looks like the link to github is broken. This is given a 404 on github: https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

### PR DESCRIPTION
**Pull request by juanpabloaj**
(EDITED 6/6/18 by @zacharysarah to include issue links)

fixes #8658 
fixes #8659 
fixes #8678 
fixes #8720

### CODE REVIEW

**Comment by zacharysarah** [comment]
@juanpabloaj Please sign the CLA in order to continue.

**Comment by zacharysarah** [comment]
@tengqm That's a possible solution, but it seems like the scope of a different PR.

**Comment by zacharysarah** [comment]
I'm willing to approve this PR once the CLA has been signed.

**Comment by tengqm** [comment]
Looks like this PR has become empty after the back merge?

**Comment by lucperkins** [comment]
This PR seems to have been an umbrella PR. I'm going to close it for now.

@juanpabloaj Please feel free to re-open if there are other changes that you'd like to make here.

**Pull request closed without merging**
