### PR TITLE
Update quick-reference.md

### PR DESCRIPTION
**Pull request by vardanaloyan**
Correct remove annotation command

### CODE REVIEW

**Comment by stmcginnis** [comment]
Thanks, this looks good, but all contributions need to be under a signed CLA. Can you follow the link in the first comment to get the CLA signed? We are unable to accept the patch until that is done. Thanks!

**Comment by vardanaloyan** [comment]
> Thanks, this looks good, but all contributions need to be under a signed CLA. Can you follow the link in the first comment to get the CLA signed? We are unable to accept the patch until that is done. Thanks!

Done

**Comment by stmcginnis** [comment]
/lgtm

Thanks!

**Comment by Ritikaa96** [comment]
I am wondering why the console output for removing annotations is 
'pod/<pod-name> annotated`
and not annotation removed.

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by vardanaloyan** [comment]
> lgtm

Could you please approve the PR

**Comment by Arhell** [comment]
> > lgtm
> 
> Could you please approve the PR

https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES#L25

**Pull request merged**
