### PR TITLE
Update outdated documentation about secret key validation.

### PR DESCRIPTION
**Pull request by af-inet**
Fixes an issue with k8s.io/docs/concepts/configuration/secret/ regarding secret key validation

see: https://github.com/kubernetes/website/issues/7674, https://github.com/kubernetes/kubernetes/issues/59516

### CODE REVIEW

**Comment by steveperry-53** [comment]
/approve (for writing)
Still need `/lgtm` for technical accuracy.
/cc @caesarxuchao 
/cc @huangjiuyuan

**Comment by heckj** [comment]
/lgtm

(verified)

**Pull request merged**
