### PR TITLE
Fix memory request limit exmaples use the default namespace

### PR DESCRIPTION
**Pull request by nashasha1**
Specify the namespace to `mem-example`. So, users can copy the yaml and run the task directly.

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6979)

### CODE REVIEW

**Comment by nashasha1** [comment]
ping @a-mccarthy

**Comment by heckj** [comment]
Hi @nashasha1  - this looks like it’s actually setting the examples to use a `mem-example` namespace rather than the default namespace, but the title of this pull request seems to imply otherwise. Is this update intended?

**Comment by heckj** [comment]
@nashasha1 same here - would you constrain these updates to the english content only please? Would  love to have the same content applied to kubernetes/kubernetes-docs-cn, but needs to be in a separate PR and to another repository. 

/assign

**Comment by nashasha1** [comment]
@heckj  Done. Thanks for your reply.

**Pull request merged**
