### PR TITLE
Update deployment.md

### PR DESCRIPTION
**Pull request by aelejota**
Modified kubectl get deployment command outputs to adapt them to the new output format introduced in v1.11

### CODE REVIEW

**Comment by lojies** [comment]
@aelejota, it's better to squash this into one commit.

**Comment by aelejota** [comment]
Thanks @lojies 
Should I close this PR and create a new one?

**Comment by lojies** [comment]
@aelejota, you can reset your commit to HEAD~1, modify and commit --amend, then push force.

**Comment by sftim** [comment]
@aelejota https://kubernetes.io/docs/contribute/intermediate/#work-from-a-local-clone covers squashing

**Comment by aelejota** [comment]
Thanks to you all for your help. It seems that droids did the job and both commits were combined

**Pull request merged**
