### PR TITLE
[zh-cn] Update images.md 

### PR DESCRIPTION
**Pull request by Eason1118**
Optimize the description of the mirror concept in the Chinese document content
`/zh-cn/docs/concepts/containers/images.md
`

### CODE REVIEW

**Comment by howieyuen** [comment]
we don't accept partly updage, please run following script to get full changes:

```sh
./scripts/lsync.sh content/zh-cn/docs/concepts/containers/images.md
```

and you will see following:
```sh
diff --git a/content/en/docs/concepts/containers/images.md b/content/en/docs/concepts/containers/images.md
index fb7113a3ce..6ea5d0d622 100644
--- a/content/en/docs/concepts/containers/images.md
+++ b/content/en/docs/concepts/containers/images.md
@@ -214,7 +214,7 @@ behalf of the two different Pods, when parallel image pulls is enabled.

 ### Maximum parallel image pulls

-{{< feature-state for_k8s_version="v1.27" state="alpha" >}}
+{{< feature-state for_k8s_version="v1.32" state="beta" >}}

 When `serializeImagePulls` is set to false, the kubelet defaults to no limit on the
 maximum number of images being pulled at the same time. If you would like to
```

**Comment by Eason1118** [comment]
Thanks for the reminder, I'll pay attention next time

**Comment by tengqm** [comment]
Another hint ... after making changes to your existing PR, do `git commit --amend`
and then `git push -f`. You will have a single commit for your PR.

**Comment by Eason1118** [comment]
Thanks. Multiple commits have been merged

**Comment by tengqm** [comment]
Thanks.
/lgtm
/approve

**Pull request merged**
