### PR TITLE
[WIP] Document OpenAPI v3 (beta) support

### PR DESCRIPTION
**Pull request by Jefftree**

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [WIP] Document OpenAPI v3 (beta) support
/sig api-machinery

**Comment by mehabhalodiya** [comment]
enhancement ref: https://github.com/kubernetes/enhancements/issues/2896

**Comment by mehabhalodiya** [comment]
@Jefftree Reminder that **tomorrow (Tue April 5)** is the deadline for **1.24 Docs Ready for Review**. Please push your docs content for this enhancement and remove the `work-in-progress` label when ready for review.

We have a tight turnaround to getting docs reviewed and approved for the release, and we’re hoping to have all docs in for review by tomorrow. Thank you!

**Comment by sftim** [comment]
Closing in favor of #32784

(fine to reopen if that's not right)
/close

**Pull request closed without merging**
