### PR TITLE
[ko] Apply 1.21-ko.8 enhancement to 1.22-ko.3

### PR DESCRIPTION
**Pull request by seokho-son**
Apply 1.21-ko.8 enhancement to 1.22-ko.3

https://github.com/kubernetes/website/pull/30415#discussion_r747900855
https://github.com/kubernetes/website/pull/30416#issuecomment-968253340
https://github.com/kubernetes/website/pull/30417#discussion_r748826137
https://github.com/kubernetes/website/pull/30417#discussion_r747906293
https://github.com/kubernetes/website/pull/30418#discussion_r747909021
https://github.com/kubernetes/website/pull/30418#issuecomment-968255837

### CODE REVIEW

**Comment by seokho-son** [comment]
/retitle [ko] Apply 1.21-ko.8 enhancement to 1.22-ko.3

**Comment by seokho-son** [comment]
PTAL @pjhwa 
1.21-ko.8에서 주신 의견을 그대로 1.22-ko.3에 반영하였습니다.. ^^

**Comment by pjhwa** [comment]
수고 많으셨습니다. 감사합니다.

/lgtm

**Pull request merged**
