### PR TITLE
[zh] unify the translation of the same sentence

### PR DESCRIPTION
**Pull request by yulng**
【zh】 unify the translation of the same sentence
“Don't apply any changes; just output what would be done”
Unify the above sentence translation

### CODE REVIEW

**Comment by windsonsea** [comment]
This may cause many conflicts with other PR if only search and replace.

**Comment by windsonsea** [comment]
When you run `./scripts/lsyn.ch` on your local `main` branch, these files are in sync, which is the reason why not covered in issue #39987:

```
$ ./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md is still in sync
$ ./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md is still in sync
$./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_all.md 
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_all.md is still in sync
$ ./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md is still in sync
$ ./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md is still in sync
$ ./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-certs.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-certs.md is still in sync
$ ./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md is still in sync
$ ./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset.md is still in sync
$ ./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node.md is still in sync
$ ./scripts/lsync.sh content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_remove-etcd-member.md
content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_remove-etcd-member.md is still in sync
```

You may need to run `diff` command to check these files line by line. That's a reason: don't suggest to search and replace a term or a clause in batch unless you confirmed those files are synced with en line by line.

**Comment by yulng** [comment]
https://github.com/kubernetes/website/issues/39987 task is basically completed
Rebase passed, there was no conflict, and pushed again
Thanks

**Comment by yulng** [comment]
@tengqm 
hi, tengqm
I have applied for kubernetes membership. Could you give me +1
https://github.com/kubernetes/org/issues/4194
Thank you very much

**Pull request merged**
