### PR TITLE
removed duplicate token controller in service-accounts-admin.md

### LINKED ISSUE #39438: Clean up ServiceAccount reference page
With #31847 closed, we now have a consolidated spot for ServiceAccount concepts. We should clean up other docs that have the same or similar conceptual info and link instead to those sections in the [ServiceAccount page](https://kubernetes.io/docs/concepts/security/service-accounts/).

Page to investigate:

* https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/
    * Remove the "user accounts vs service accounts" section if the info is duplicated or obsolete because of the SA concept
    * Think about whether to move concepts in "bound service account token volume projection" to the [projectedvolume concept page](https://kubernetes.io/docs/concepts/storage/projected-volumes/#serviceaccounttoken) and instructions into [Configure Service Accounts for Pods](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#serviceaccount-token-volume-projection)
    * Think about deleting [Manual Secret management for ServiceAccounts](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#manual-secret-management-for-serviceaccounts) and merging any relevant content into the SA concept.
    * Freshen up the [Control plane details](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#control-plane-details) section for the current state. Consider linking to it from the SA concept. There are duplicate sections for control plane details on this page.

Use this issue to discuss whether each of the changes listed here are sensible and if yes, how to proceed (ideally, small PRs for each change as opposed to a big overall PR)

### PR DESCRIPTION
**Pull request by AmarNathChary**
removed duplicate section in control plane details https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/ and moved ServiceAccount Controller 
partially fixes #39438

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @AmarNathChary . 
The heading is duplicated (`Control plane details`) on the page, and some of the content overlaps.
It is not clear whether the first `Control plane details` heading should be a sub-heading under this section, https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#manual-secret-management-for-serviceaccounts

Original page:
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/

**Comment by AmarNathChary** [comment]
Hi @kbhawkey 
The duplicate content in `Control plane details` which is `Token controller` has been removed and `ServiceAccount controller` has been guided under control plane details. of the first `Control Plane details`.  it will be glad if u can say exactly what content looks like overlaps u suggest if any changes can be made.

**Review by dipesh-rawat — COMMENTED** [review]
These changes are duplicate of PR https://github.com/kubernetes/website/pull/40235/

/triage duplicate

**Comment by dipesh-rawat** [comment]
Marking as duplicate and closing this as PR https://github.com/kubernetes/website/pull/40235 with same changes has been merged

/close

**Pull request closed without merging**
