### PR TITLE
[fix]  wrong selector behavior explanation

### PR DESCRIPTION
**Pull request by myminseok**
correcting  in selector Behavior explanation
thanks.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by makoscafee** [comment]
@myminseok the changes look good. would you mind signing [CLA]( https://git.k8s.io/community/CLA.md#the-contributor-license-agreement )  so your changes can be merged.

**Comment by bradtopol** [comment]
@myminseok Thank you for your contribution. Please sign the CLA so we can accept your PR for review.

**Comment by tfogo** [comment]
Hi @myminseok, thanks for the PR. Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA so that we can merge this PR, thanks!

**Comment by Rajakavitha1** [comment]
/close
Hi @myminseok closing this PR for now. Please reopen the PR after you sign the CLA https://git.k8s.io/community/CLA.md#the-contributor-license-agreement

**Pull request closed without merging**
