### PR TITLE
Typo in 'What's next' section

### PR DESCRIPTION
**Pull request by cimes-isi**
'Lean' should be 'Learn'

### CODE REVIEW

**Comment by cimes-isi** [comment]
CLA signature should be complete now.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-23796--kubernetes-io-master-staging.netlify.app/docs/concepts/workloads/pods/#what-s-next

**Comment by kbhawkey** [comment]
Thanks @cimes-isi .
/lgtm

**Pull request merged**
