### PR TITLE
Merged master dev 1.19

### PR DESCRIPTION
**Pull request by annajung**
/assign @savitharaghunathan

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
@annajung 👋  Thanks for the PR 🎉 Can you change the target to `dev-1.19` instead of `master`?

**Comment by annajung** [comment]
@savitharaghunathan thank you for catching that! yes, it's been changed now

**Comment by kbhawkey** [comment]
This is the weekly master to dev-1.19 branch sync.

**Comment by annajung** [comment]
Hi @yakirch Thank you for catching that! I just pushed a fix for it, please take a look again when you get a chance

**Pull request merged**
