### PR TITLE
Update quick-reference.md

### PR DESCRIPTION
**Pull request by chee-zaram**
This PR corrects a sentence, making it grammatically correct.

### CODE REVIEW

**Comment by T-Lakshmi** [comment]
Hi @chee-zaram,
Thanks for your contribution,
This is a [trival edit](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits), Can you please go through the complete page and fix if there is any other fixes required like broken links, grammatical errors, formatting..etc,
So that we can fix complete page at once.

**Comment by chee-zaram** [comment]
> Hi @chee-zaram,
> Thanks for your contribution,
> This is a [trival edit](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits), Can you please go through the complete page and fix if there is any other fixes required like broken links, grammatical errors, formatting..etc,
> So that we can fix complete page at once.

Sure. Will do. Thanks.

**Comment by chee-zaram** [comment]
Hey @T-Lakshmi,
I have gone through the whole page looking for things that could be improved and everything looks good enough to me as is.
Thanks.

**Review by Princesso — COMMENTED** [review]
Hi Chee-zaram, thanks again for your contribution. 
You can go ahead to close this PR since you didn't find anything else to fix on the page. 
There are some other issues you could pick from on the issue tracker.

**Pull request closed without merging**
