### PR TITLE
Propose stormqueen1990 as a reviewer for the pt-br docs localization

### PR DESCRIPTION
**Pull request by stormqueen1990**
I have been doing drive-by reviews for a few months, in addition to my contributions to the pt-br localization. Therefore, I would like to propose making my role as a reviewer official within the pt-br localization.

/language pt
/cc @rikatz @edsoncelio @devlware

### CODE REVIEW

**Comment by edsoncelio** [comment]
/lgtm
Mauren is doing a great job helping to maintain the Portuguese docs and onboard the new contributors :)

**Comment by rikatz** [comment]
/lgtm
/approve
Mauren is doing an amazing job and practically onboarding all new contributors and providing helpful feedback!

Thanks @stormqueen1990 for all the work so far :D

**Comment by rikatz** [comment]
/assign @onlydole @sftim @divya-mohan0209 @jimangel 

for who arrives first :)

**Comment by divya-mohan0209** [comment]
/approve
Thank you @stormqueen1990 for the PR & welcome!

**Pull request merged**
