### PR TITLE
update zh translation content/zh/docs/reference/kubectl/docker-cli-to…

### PR DESCRIPTION
**Pull request by tanjunchen**

### CODE REVIEW

**Comment by thockin** [comment]
I can't review this - who deals with translations?

**Comment by tanjunchen** [comment]
@xichengliudui

**Comment by markthink** [comment]
@tanjunchen 需要解决一下文件冲突

**Comment by tanjunchen** [comment]
@chenopis

**Comment by tanjunchen** [comment]
@markthink   I have fix this  conflict

**Pull request merged**
