### PR TITLE
Update crictl.md

### PR DESCRIPTION
**Pull request by ptux**
- Delete the unneeded line.
 
※ duplicate with line 70.

### CODE REVIEW

**Comment by bradtopol** [comment]
Hi @mrunalp Can you serve as the technical reviewer for this? Just add a /lgtm if you are okay with the change and I'll take care of the rest.

**Comment by ptux** [comment]
@bradtopol 

Because they duplicate with line 70.

**Comment by tengqm** [comment]
I'd suggest we leave the lines as is because it helps clarify the situation per-scenario.

**Comment by reylejano** [comment]
I think these lines should stay, as they describe for different tasks/scenarios: Run a pod sandbox, Create a container
I'm closing this PR as I agree with @tengqm that the lines should not be removed

Feel free to reopen this PR if you feel that the lines should be removed and we can continue the discussion
/close

**Pull request closed without merging**
