### PR TITLE
[zh] Add an example for restoring etcd cluster

### PR DESCRIPTION
**Pull request by h4ghhh**
Be consistent with En.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @tengqm

**Comment by tengqm** [comment]
Thanks for the sync.
/lgtm
/approve

**Comment by tengqm** [comment]
Thanks for the sync.
/lgtm
/approve

**Comment by tengqm** [comment]
Thanks for the sync.
/lgtm
/approve

**Pull request merged**
