### PR TITLE
[ja] fix links and full-width symbols in /ja/docs/concepts/overview/kubernetes-api/

### PR DESCRIPTION
**Pull request by thekuwayama**
- fix broken links
    - related to #30401 
- improvement links using ja-links
- modify full-width symbols to half-width symbols; parenthesis and colon
    - reference to [翻訳スタイルガイド-基本方針](https://kubernetes.io/ja/docs/contribute/localization/#%E5%9F%BA%E6%9C%AC%E6%96%B9%E9%87%9D)

### CODE REVIEW

**Comment by ptux** [comment]
@thekuwayama 

Have you created an issue for this PR?
And why do you want to merge this PR to the `kubernetes:dev-1.19-ja.2` branch instead of the main branch?

**Comment by thekuwayama** [comment]
@ptux Thank you for your comments.

I sent this PR for issue #30401 .
I think that the latest milestone branch is `kubernetes:dev-1.19-ja.2`, so I sent this PR to that ccording to the [localization](https://kubernetes.io/ja/docs/contribute/localization/#%E6%97%A2%E5%AD%98%E3%81%AE%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AE%E8%AA%A4%E5%AD%97%E8%84%B1%E5%AD%97%E3%82%84%E5%8F%A4%E3%81%84%E8%A8%98%E8%BF%B0%E3%82%92%E4%BF%AE%E6%AD%A3%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88%E3%81%AE%E6%89%8B%E9%A0%86).
It would be better if I sent this to `main`?

**Comment by ptux** [comment]
@thekuwayama 

According to the guide, I think you are right.
I didn't know that.

**Comment by nasa9084** [comment]
Thank you for  your contribution~!
/approve

**Comment by tengqm** [comment]
This needs a lgtm. It has been dangling for too long.

**Comment by bells17** [comment]
/lgtm
👍 1

**Pull request merged**
