### PR TITLE
[zh] translate task/Install and Set Up kubectl on Windows

### LINKED ISSUE #27483: [zh] translate "tasks/Install and Set Up kubectl on Windows"
** This is a Feature Request **
translate content/docs/tasks/tools/install-kubectl-windows.md into Chinese

** What would you like to be added **
content/zh/docs/tasks/tools/install-kubectl-windows.md

/assign
/language zh

### PR DESCRIPTION
**Pull request by zhiguo-lu**
translate /docs/tasks/tools/install-kubectl-windows.md into Chinese.

close #27483

### CODE REVIEW

**Comment by tengqm** [comment]
/close
close and reopen in hope to restart the CI jobs.

**Comment by tengqm** [comment]
@zhiguo-lu Can you help rebase this onto master?

**Comment by zhiguo-lu** [comment]
Something wrong, let me submit a new one

**Pull request closed without merging**
