### PR TITLE
Update zh trans kubeadm_upgrade_plan.md

### PR DESCRIPTION
**Pull request by jiazxjason**
Update zh trans kubeadm_upgrade_plan.md

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
please base your translation on the English source file: https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md

**Comment by jiazxjason** [comment]
@tengqm I got your point and corrected it, please review

**Comment by tengqm** [comment]
Thanks.
/lgtm
/approve

**Pull request merged**
