### PR TITLE
Add onlydole to EN sections, remove duplicate entry

### PR DESCRIPTION
**Pull request by onlydole**
Adding myself to the EN owner and reviewer roles, and cleaning up a duplicate entry under the blog section.

### CODE REVIEW

**Comment by zacharysarah** [comment]
Thanks for wrangling PRs, @onlydole! I forgot one thing--would you please PR yourself into https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml#L16 and the reviews section for English (line 37) as well?

**Comment by onlydole** [comment]
Absolutely, coming right up!

**Pull request merged**
