### PR TITLE
declare ipvs proxier beta

### PR DESCRIPTION
**Pull request by stewart-yu**
ipvs alpha version -> beta version

cc @m1093782566 

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6524)

### CODE REVIEW

**Comment by m1093782566** [comment]
@a-mccarthy @steveperry-53

It's very import to IPVS proxier beta work, please take a look when you have a chance. Thanks!

**Comment by m1093782566** [comment]
We want to declare IPVS proxier beta in v1.9

**Comment by m1093782566** [comment]
@jaredbhatti

**Comment by tengqm** [comment]
adding do-not-merge because https://github.com/kubernetes/kubernetes/pull/56623 is still not in. Docs should be updated *only* when the implementation is in place.

removing critical-urgent because ... cannot feel the urgency

**Comment by m1093782566** [comment]
@tengqm 

>  Docs should be updated only when the implementation is in place.

implementation is already in place!

**Comment by tengqm** [comment]
@m1093782566 it is not yet officially announced as beta, so please hold doc changes.

**Comment by tengqm** [comment]
kubernetes/kubernetes#56623 is in now... this one is good to go.
@m1093782566 Please rebase this to the release-1.9 branch. Thanks.

**Comment by stewart-yu** [comment]
Does need commit another PR to `release-1.9` branch? This PR just compare with `master` branch. @tengqm

**Comment by tengqm** [comment]
@stewart-yu Yes. A commit to release-1.9 is needed. Look, the process of merging documentation is a little bit different from that for a code repo. If a doc PR is targeting Master and it is merged, the content is published on k8s.io/docs immediately. Commiting to release-1.9 will help ensure that v1.9 specific contents are only online when it is officially released.

**Comment by tengqm** [comment]
Closing this for merging #6558 into release-1.9.

**Pull request closed without merging**
