### PR TITLE
[en] fix meetup link

### PR DESCRIPTION
**Pull request by Arhell**
/assign @sftim

### CODE REVIEW

**Comment by sftim** [comment]
I think this allocation of an Urchin / Google Analytics identifier should be checked by someone from the CNCF or from the Kubernetes marketing folks.

@LexiNadolski @kbarnard10 I'm not sure who is the right person to ask; can either of you help us work that out?

**Comment by sftim** [comment]
@Arhell if you can show another page that uses the same link, that's another strong hint that the fix is the right one.

**Comment by Arhell** [comment]
@sftim 
No, this is the only link

**Pull request merged**
