### PR TITLE
Add missing space

### PR DESCRIPTION
**Pull request by doug-fish**
The space is missing.

### CODE REVIEW

**Comment by doug-fish** [comment]
signed cla

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by doug-fish** [comment]
Pretty sure I did the cla. Do I need to comment again to trigger a recheck?

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-24819--kubernetes-io-master-staging.netlify.app/docs/concepts/services-networking/network-policies/#what-you-can-t-do-with-network-policies-at-least-not-yet

Thanks @doug-fish 
/approve

**Pull request merged**
