### PR TITLE
 Improve diagrams for Virtual IPs and Service Proxies

### PR DESCRIPTION
**Pull request by sftim**
I adapted one of the commits from https://github.com/kubernetes/website/pull/38455 as a way to address https://github.com/kubernetes/website/issues/38165

- You can compare the [original page](https://k8s.io/docs/reference/networking/virtual-ips/) to the [preview](https://deploy-preview-38542--kubernetes-io-main-staging.netlify.app/docs/reference/networking/virtual-ips/)

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
For the ipvs diagram, would we benefit from retaining the virtual server labelling since we have stated that the backend pods are on the real server? This otherwise LGTM, thanks!

**Comment by sftim** [comment]
> For the ipvs diagram, would we benefit from retaining the virtual server labelling since we have stated that the backend pods are on the real server?

I think it's misleading and helpful in equal measure, and that's why I omitted it. There's still room to improve on these diagrams but I think they're better than what we have now.

**Review by divya-mohan0209 — COMMENTED** [review]
Agreed, @sftim ! LGTM from my side :) 
/lgtm

**Comment by nate-double-u** [comment]
Thanks for these @sftim! I agree, these are clearer and more legible than the previous set. Let's merge this in and if we need to make further changes those can be in a separate PR.

/approve

**Pull request merged**
