### PR TITLE
Update web-ui-dashboard.md

### PR DESCRIPTION
**Pull request by benyko**
Update dashboard version from v2.6.1 to v2.7.0

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hello @benyko please sign the CLA so that we can review your PR.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by ydFu** [comment]
@benyko ,thank you for your contribution.

You must sign the CLA for teams of kubernetes/website to do code reiview.

Please click on the red button `NOT COVERED` line in the first comment.

If you don't know how to do it, here is[the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Comment by benyko** [comment]
Thanks for the reminder! I signed the CLA.

**Comment by shu-mutou** [comment]
@benyko Thanks for this!
/lgtm

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Pull request merged**
