### PR TITLE
Backport "layouts/docs/release-info.html" to release-1.24

### PR DESCRIPTION
**Pull request by dipesh-rawat**
Addressing issue #42812

Copied layouts/docs/release-info.html from main branch to update release-1.24 docs

Initial PR to add the layout: #41370

PR to refine the layout: #42835

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks @dipesh-rawat
/lgtm

**Comment by jihoon-seo** [comment]
The preview seems different from the live version of `main` and `1.24`. I am not sure whether this is the right & intended result.

[Preview]
https://deploy-preview-42814--k8s-v1-24.netlify.app/releases/
image

---

[The live version of 1.24 docs]
https://v1-24.docs.kubernetes.io/releases/
image

---

[The live version of `main`]
https://kubernetes.io/releases/
image

**Comment by dipesh-rawat** [comment]
> The preview seems different from the live version of `main` and `1.24`. I am not sure whether this is the right & intended result.

@jihoon-seo The output is as expected. The objective for us is to only display release information for current latest version of http://k8s.io/, not older ones. The conditional layout changes were merged after the v1.28 release, and this pull request extends it to older supported versions (v1.27, v1.26,v1.25,v1.24) to hide the release information (eg [preview](https://deploy-preview-42814--k8s-v1-24.netlify.app/releases/)).

**Pull request merged**
