### PR TITLE
Removes merge conflicts for branch dev-1.15

### PR DESCRIPTION
**Pull request by makoscafee**
This PR aims to update dev-1.15 with content from master branch while resolving all merging conflicts.

### CODE REVIEW

**Comment by makoscafee** [comment]
cc @jimangel

**Comment by tengqm** [comment]
Let's kick this in and iterate.
/lgtm
/approve

**Comment by tengqm** [comment]
@makoscafee Let's solve the conflict and try again? :)

**Comment by makoscafee** [comment]
> @makoscafee Let's solve the conflict and try again? :)

Sure let me work on resolving these conflicts

**Comment by jimangel** [comment]
/hold

I think this might be done wrong, since it's pulling in 605 commits (and multiple languages). Comparing to our 1.14 (dev-1.14) release, there was only 50 commits: https://github.com/kubernetes/website/pull/13174/commits

/cc @kubernetes/sig-docs-maintainers thoughts?

**Comment by chenrui333** [comment]
It might be good to directly merge from master (which consists bug fixes) into dev-1.15 (which consists of the feature work) before doing the final release.

**Comment by makoscafee** [comment]
Ok Let me close this and try creating to see how it turns out..

**Pull request closed without merging**
