### PR TITLE
README-tr.md

### PR DESCRIPTION
**Pull request by AdemCanCertel**
Can you add it?

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/29747#issuecomment-922458247

**Comment by jihoon-seo** [comment]
[Further suggestion]
https://github.com/kubernetes/website/blob/main/README.md

[As-is]
```
## Localization `README.md`'s

| Language                   | Language                   |
| -------------------------- | -------------------------- |
| [Chinese](README-zh.md)    | [Korean](README-ko.md)     |
| [French](README-fr.md)     | [Polish](README-pl.md)     |
| [German](README-de.md)     | [Portuguese](README-pt.md) |
| [Hindi](README-hi.md)      | [Russian](README-ru.md)    |
| [Indonesian](README-id.md) | [Spanish](README-es.md)    |
| [Italian](README-it.md)    | [Ukrainian](README-uk.md)  |
| [Japanese](README-ja.md)   | [Vietnamese](README-vi.md) |
```

[To-be]
```
## Localization `README.md`'s

| Language                   | Language                   |
| -------------------------- | -------------------------- |
| [Chinese](README-zh.md)    | [Polish](README-pl.md)     |
| [French](README-fr.md)     | [Portuguese](README-pt.md) |
| [German](README-de.md)     | [Russian](README-ru.md)    |
| [Hindi](README-hi.md)      | [Spanish](README-es.md)    |
| [Indonesian](README-id.md) | [Turkish](README-tr.md)    |
| [Italian](README-it.md)    | [Ukrainian](README-uk.md)  |
| [Japanese](README-ja.md)   | [Vietnamese](README-vi.md) |
| [Korean](README-ko.md)     |  |
```

**Comment by jimangel** [comment]
Hey there! @AdemCanCertel, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by sftim** [comment]
We need a signed CLA to accept proposed changes, including to review them.

I can say that we don't yet have a Turkish localization team so there would be a second barrier after the CLA as well.

@AdemCanCertel if you wanted to start a Turkish localization, SIG Docs can help you. A localization team is always a minimum of two people.

/close

**Pull request closed without merging**
