### PR TITLE
Fix rendering error in k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/ 

### LINKED ISSUE #20130: Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/
UI issues with page
image

### LINKED ISSUE #20483: Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/
**This is a Bug Report**

**Problem:**
Powershell markdown code block in `{{ note }}` block doesn't render correctly
**Proposed Solution:**
Move markdown code block out of `{{ note }}` block or change code block to inline code snippet
**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

[Code Link](https://github.com/kubernetes/website/blame/master/content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md#L124)

Attached Screenshot of issue
image

### PR DESCRIPTION
**Pull request by KnotGud**
It seems removing the tabbing in the codeblocks fix the rendering
issues. Also added backticks to files to file names for emphasis.

Fixes #20130
Fixes #20483

### CODE REVIEW

**Comment by KnotGud** [comment]
Signed CLA using github oauth

**Comment by KnotGud** [comment]
cla check

**Comment by bradtopol** [comment]
Great job!
/lgtm
/approve

**Pull request merged**
