### PR TITLE
Fix dead links and apply template

### LINKED ISSUE #9470: Issue with k8s.io/docs/setup/pick-right-solution/
**This is a URL bug** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
On the page https://kubernetes.io/docs/setup/pick-right-solution/, on the Turnkey Cloud Solution, I'v got a 404 Error when I click on AWS, Azure or GCE link

**Proposed Solution:**
Replace the url to the link

**Page to Update:**
https://kubernetes.io/docs/setup/pick-right-solution/

### PR DESCRIPTION
**Pull request by makocchi-git**
closes #9470

* fix dead links to `getting-started-guides/*`
* apply `templates/concept` template
* add note shortcodes

### CODE REVIEW

**Comment by makocchi-git** [comment]
[preview is here](https://deploy-preview-9476--kubernetes-io-master-staging.netlify.com/docs/setup/pick-right-solution/)
[original](https://kubernetes.io/docs/setup/pick-right-solution/)

**Comment by tengqm** [comment]
Changes look good to me. Pls fix the conflict.

**Comment by makocchi-git** [comment]
OK, I will rebase this soon.

**Pull request merged**
