### PR TITLE
Virtual IPs and Service Proxies page images replacement

### PR DESCRIPTION
**Pull request by tamilselvan1102**
Virtual IPs and Service Proxies page images replacement
link: #38165

### CODE REVIEW

**Review by divya-mohan0209 — CHANGES_REQUESTED** [review]
@tamilselvan1102 I think you have extra commits and this might need a proper rebase. Could you do that please?

**Comment by tamilselvan1102** [comment]
@divya-mohan0209 
 **Only required 3 files has been modified. please check**

image

**Comment by sftim** [comment]
Have a look at https://github.com/kubernetes/website/pull/38755/commits - also, see https://www.k8s.dev/blog/2022/12/12/prow-and-tide-for-kubernetes-contributors/#back-to-squashing for some tips

**Comment by tamilselvan1102** [comment]
do I have to rebase again?

**Pull request closed without merging**
