### PR TITLE
Added missing "the"

### PR DESCRIPTION
**Pull request by adriancuadrado**

### CODE REVIEW

**Comment by adriancuadrado** [comment]
I signed it

**Comment by RA489** [comment]
> I signed it

/check-cla

**Review by Arhell — COMMENTED** [review]
more info about CLA, check please
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by adriancuadrado** [comment]
I signed it

**Comment by kbhawkey** [comment]
Hello @adriancuadrado . Thanks for contributing.
Would you review your credentials used to sign the CLA?
The changes look good but this PR cannot move forward until you have a verified CLA.
/close

**Comment by adriancuadrado** [comment]
> Hello @adriancuadrado . Thanks for contributing.
> Would you review your credentials used to sign the CLA?
> The changes look good but this PR cannot move forward until you have a verified CLA.
> /close
> 

@kbhawkey I reviewed them and they are ok, I don't understand why I still don't have my CLA verified.

**Pull request closed without merging**
