### PR TITLE
[zh] Add Link for "Operator White Paper"

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/website/pull/28625

### CODE REVIEW

**Comment by sftim** [comment]
Thanks for this PR @npu21 - sorry it's taking a while to find a reviewer.

**Comment by tengqm** [comment]
The MetaController link has been changed as well, pls sync:

```
-* [Metacontroller](https://metacontroller.app/) along with WebHooks that
+* [Metacontroller](https://metacontroller.github.io/metacontroller/intro.html) along with WebHooks that
```

**Comment by reylejano** [comment]
/retitle [zh] Add Link for "Operator White Paper"

**Comment by reylejano** [comment]
Hi @npu21 , this PR needs to rebase

**Pull request closed without merging**
