### PR TITLE
[zh] remove unnecessary \ character and update the translation of "a …

### PR DESCRIPTION
**Pull request by Polyipnus**
…pair"

- 1. delete unnecessary \ character, <code></code> stops it from escaping;
- 2. "a pair" will be better to translate into "一对", but not "耦对";

### CODE REVIEW

**Comment by Polyipnus** [comment]
> /close

why not leave some reason for the close ?

**Comment by tengqm** [comment]
@Polyipnus Both of the "fixes" have been discussed before. The "\" is a convenience for some editor such as vim. It is not hurting anyone. The translation of "pair" has been discussed as well.
Please find something more meaningful to work on.

**Comment by Polyipnus** [comment]
> @Polyipnus Both of the "fixes" have been discussed before. The "" is a convenience for some editor such as vim. It is not hurting anyone. The translation of "pair" has been discussed as well.
> Please find something more meaningful to work on.

thanks so much, I'll double check issues before PR next time.

**Pull request closed without merging**
