### PR TITLE
Official 1.18 Release Docs

### PR DESCRIPTION
**Pull request by VineethReddy02**
🛑 DO NOT MERGE 🛑 UNTIL KUBERNETES 1.18 IS RELEASED
Target Date: 24-03-2020

## Release deadlines
From [sig-release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.18):

| Date | Description |
| --- | --- |
| FEB 28 | Open placeholder PRs |
| MAR 09 | PRs ready for review |
| MAR 16 | All PRs reviewed and ready to merge |

## More information
Contact @savitharaghunathan @sethmccombs @irvifa @iheanyi1 @jimangel @zacharysarah  
w/ any questions.

### CODE REVIEW

**Comment by VineethReddy02** [comment]
do-not-merge/hold

**Comment by sftim** [comment]
https://deploy-preview-19116--kubernetes-io-master-staging.netlify.com/docs/reference/using-api/api-overview/#api-versioning doesn't yet have v1.18 API documentation.

That's a known thing / intentional, right?

I looked at a few other things and everything else looks OK to me.

**Comment by kbhawkey** [comment]
I see several recent `X`s. Should I be worried?
I created the ref doc PRs off the master branch.

**Comment by sftim** [comment]
> I see several recent Xs. Should I be worried?

**Comment by kbhawkey** [comment]
I wonder if the problem is that the merge is blocked?

**Comment by sftim** [comment]
I tried doing a local merge into _master_ and that looks fine too.

**Comment by jimangel** [comment]
/lgtm
/approve
🎉

**Pull request merged**
