### PR TITLE
Fixed broken links in ObjectMeta

### PR DESCRIPTION
**Pull request by AmarNathChary**
This PR will partially fixes issue #40367

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @AmarNathChary, This is an auto generated page from upstream kubernetes so it can not be fixed lcally here in kubernetes/website repo.

**Comment by AmarNathChary** [comment]
Hi @utkarsh-singh1 Thanks for the information. I would like to know more about this auto generated pages. what could be the other ways to fix?

**Comment by divya-mohan0209** [comment]
Hello @AmarNathChary , this documentation is generated from the code in kubernetes/kubernetes repository. Kindly make the relevant changes in the files by referring to our [contributor docs](https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-api/)

**Comment by divya-mohan0209** [comment]
That being said, I shall be closing out this PR.
/remove-lifecycle stale
/close

**Pull request closed without merging**
