### PR TITLE
Remove orphaned content

### PR DESCRIPTION
**Pull request by zacharysarah**
💚 MERGE OK 💚 

**UPDATE:** #13279 has merged. This PR is free to merge!

This PR removes orphaned content in `content/en/docs/getting-started-guides/`. 

We've been talking about it for over a year; someone needs to pull the trigger and do it. I anticipate a lively discussion.

**Note:** This PR affects at least one open PR, #13279. There's a [Slack thread](https://kubernetes.slack.com/archives/C1J0BPD2M/p1552936278153400?thread_ts=1552936038.153000&cid=C1J0BPD2M) about suggested replacement paths, specifically `content/en/docs/setup/`, with an update to `pick-right-solution.md`. 

It's worth noting that any replacement path will be temporary, given our intention to revamp the Setup section by the end of Q2.

/cc @jaredbhatti @Bradamant3 @kubernetes/sig-docs-en-owners 
/sig docs
/kind documentation

### CODE REVIEW

**Comment by stewart-yu** [comment]
seems just deletein this PR?  IMO, we should move and delete done in one PR

**Comment by michmike** [comment]
@zacharysarah  how is this PR going to impact our sig-windows docs PR?

**Comment by zacharysarah** [comment]
@michmike There's a note in the issue description about specific impacts to the Windows docs. I talked with @craiglpeters in today's SIG Docs meetings, and we agreed to migrate Windows docs to `/content/en/docs/setup/` to boost their visibility. I'm happy to help on that PR.

**Comment by zacharysarah** [comment]
/hold

🛑 **Do not merge** 🛑  until #12929 merges.

**Comment by michmike** [comment]
> @michmike There's a note in the issue description about specific impacts to the Windows docs. I talked with @craiglpeters in today's SIG Docs meetings, and we agreed to migrate Windows docs to `/content/en/docs/setup/` to boost their visibility. I'm happy to help on that PR.

thanks. Craig and i talked. we will ask if we need help. (i will try to do the migration after an in-flight PR right now)

**Comment by michmike** [comment]
> > @michmike There's a note in the issue description about specific impacts to the Windows docs. I talked with @craiglpeters in today's SIG Docs meetings, and we agreed to migrate Windows docs to `/content/en/docs/setup/` to boost their visibility. I'm happy to help on that PR.
> 
> thanks. Craig and i talked. we will ask if we need help. (i will try to do the migration after an in-flight PR right now)
@zacharysarah should we create a sig-windows directory in there?

**Comment by zacharysarah** [comment]
@michmike 
> should we create a sig-windows directory in there?

Yes. I would set it up like this: `/content/en/docs/setup/windows/`. It's SIG Windows content, yes, but the filepath won't make obvious sense to visitors who aren't already familiar with the Kubernetes SIG model.

Be aware that adding a directory requires you to add page weights to new files and adjust page weights in the front matter of other files. (You can see an example of the `weight:` attribute in the raw file for [Building Large Clusters](https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/setup/cluster-large.md):
```md
---
reviewers:
- davidopp
- lavalamp
title: Building Large Clusters
weight: 80
---
```
I'm offering help specifically to help untangle page weights, if you need it. One of Hugo's few less-than-charming features...

**Comment by michmike** [comment]
> @michmike
> 
> > should we create a sig-windows directory in there?
> 
> Yes. I would set it up like this: `/content/en/docs/setup/windows/`. It's SIG Windows content, yes, but the filepath won't make obvious sense to visitors who aren't already familiar with the Kubernetes SIG model.
> 
> Be aware that adding a directory requires you to add page weights to new files and adjust page weights in the front matter of other files. (You can see an example of the `weight:` attribute in the raw file for [Building Large Clusters](https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/setup/cluster-large.md):
> 
> ```lisp
> ---
> reviewers:
> - davidopp
> - lavalamp
> title: Building Large Clusters
> weight: 80
> ---
> ```
> 
> I'm offering help specifically to help untangle page weights, if you need it. One of Hugo's few less-than-charming features...
> 
> EDIT: More info in the [K8s style guide](https://kubernetes.io/docs/contribute/style/content-organization/#page-order).

@zacharysarah  PTAL at this PR for the updates. https://github.com/kubernetes/website/pull/13279

**Comment by zacharysarah** [comment]
/hold cancel

@cody-clark This PR is ready for review/merge!

**Comment by michmike** [comment]
you are merging directly into k8s master. if you remove the getting-started guide now (for windows for example), you are removing something that people link to all the time. should we not remove all these in the dev1.14 branch so that it all goes live on the same day?

**Comment by zacharysarah** [comment]
@michmike It's too late to add a PR to `dev-1.14`, but that's a good point--this can wait until after 1.14 releases.

**Comment by zacharysarah** [comment]
This needs merge conflicts resolved--it may be easier to close this PR and start a new one after 1.14 releases. I'm leaving a note for myself to revisit this PR at the end of March 2019.

**Comment by michmike** [comment]
fyi , in 1.14, i already removed all the windows content, so i cleaned it up already :)

**Pull request closed without merging**
