### PR TITLE
Update install-minikube.md

### PR DESCRIPTION
**Pull request by ChloeAcheampong**
Include example for starting minikube with a specific vm

### CODE REVIEW

**Comment by ChloeAcheampong** [comment]
Hi,

I have signed the CLA.

Thanks,

Chloe

**Comment by ChloeAcheampong** [comment]
I signed

**Comment by RA489** [comment]
> I signed

/check-cla

**Comment by jimangel** [comment]
Hi @ChloeAcheampong!

There may be a problem with your git commit author email address and the email address you used to sign the CLA.

If the robot cannot verify your CLA status, the PR will not merge. If you cannot correct this problem, please close and re-open a new PR with the correct commit / author.

**Comment by sftim** [comment]
/check-cla

@ChloeAcheampong would you like any advice on getting a CLA signed and checked?

**Comment by zacharysarah** [comment]
@ChloeAcheampong 👋 Please sign the contributor agreement in order to continue.

/close

**Pull request closed without merging**
