### PR TITLE
Remove outdated install-minikube.md file

### PR DESCRIPTION
**Pull request by ryokotmng**
Issue https://github.com/kubernetes/website/issues/26504

What I did
- removed tool/install-minikube.md file
- updated some files with a link to the removed install-minikube page
  - It seems like no Japanese translated page for ["minikube Get Started! Guide"](https://minikube.sigs.k8s.io/docs/start/) but I'll fix the url if exists

### CODE REVIEW

**Comment by ryokotmng** [comment]
Thanks for your review in advance☺️
/assign @nasa9084

**Comment by inductor** [comment]
@ryokotmng conflictしてしまったので、rebaseおねがいしてもよいでしょうか 🙇

**Comment by ryokotmng** [comment]
🙆🏻‍♀️ 少々お待ちを〜

**Comment by ryokotmng** [comment]
あれ、既に同じ作業を誰かがしてしまっているような感じがします💦 このPR閉じますね！

**Pull request closed without merging**
