### PR TITLE
Update configure-liveness-readiness-startup-probes.md with french vocabulary corrections

### PR DESCRIPTION
**Pull request by d3vpasha**

### CODE REVIEW

**Comment by d3vpasha** [comment]
I signed it

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by d3vpasha** [comment]
Hey guys, the process to be able to make a PR is really painful. Someone here can help me ? I followed each step but it doesn't work

**Comment by remyleone** [comment]
@d3vpasha have you fill up the cla with the same email that you signed your commit with?

**Comment by tengqm** [comment]
No response from the author for a long time.
Please feel free to reopen it when time permits.
/close

**Pull request closed without merging**
