### PR TITLE
[hi] [test] Merge Hindi localization dev-1.22-hi.1 to main

### PR DESCRIPTION
**Pull request by Garima-Negi**
This PR merges Hindi Localization branch to the main branch

Test PR in relation to [https://github.com/kubernetes/website/pull/29679](https://github.com/kubernetes/website/pull/29679)

### CODE REVIEW

**Comment by sftim** [comment]
The PR description says this PR is a test - is that right @Garima-Negi ?

**Comment by sftim** [comment]
The source branch is wrong; it is your own branch and not the `dev-1.22-hi.1` branch in this repo @Garima-Negi.

However, that might help me work out how to resolve merge conflicts. I can make a new PR to merge in Hindi, based on this work.

/hold
because this PR does not do what it says it intends to.

**Comment by Garima-Negi** [comment]
> The source branch is wrong; it is your own branch and not the `dev-1.22-hi.1` branch in this repo @Garima-Negi.
> 
> However, that might help me work out how to resolve merge conflicts. I can make a new PR to merge in Hindi, based on this work.
> 
> /hold because this PR does not do what it says it intends to.

correct this is a test , the 2 files that had conflicts are config.toml and static/_redirects
final test we need:
1.```[languages.hi]
title = "Kubernetes"
description = "प्रोडक्शन-ग्रेड कंटेनर ऑर्केस्ट्रेशन"
languageName = "हिन्दी"
languageNameLatinScript = "Hindi"
weight = 12
contentDir = "content/hi"
languagedirection = "ltr"```

2. /pt/*         /pt-br/:splat  302!
/zh/*         /zh-cn/:splat  302!

**Comment by Garima-Negi** [comment]
This was a test PR to uncover some merge conflicts

The original hindi localization branch merge PR is now successfully merged. 

Closing this down. Thanks everyone.

**Pull request closed without merging**
