### PR TITLE
glossary: translate applications and cgroup into Bahasa

### PR DESCRIPTION
**Pull request by habibrosyad**
xref #24347

/cc @ariscahyadi @girikuncoro

### CODE REVIEW

**Review by ariscahyadi — COMMENTED** [review]
@habibrosyad  I believe you have already addressed my comment based on previous comment!
I think it is good to go!
But, try to increase the glossaries per PR, maybe 5 ;-)

/lgtm

**Comment by irvifa** [comment]
Thanks!
/approve

**Comment by irvifa** [comment]
Do you opened an issue for this? A checklist will help wdyt @ariscahyadi ?

**Comment by habibrosyad** [comment]
> @habibrosyad I believe you have already addressed my comment based on previous PR!
> I think it is good to go!
> But, try to increase the glossaries per PR, maybe 5 ;-)

Yes, basically this just the same as is #24347, just smaller. will do 5 for the rest...

**Comment by habibrosyad** [comment]
> Do you opened an issue for this? A checklist will help wdyt @ariscahyadi ?

Haven't made one yet, I will create one in a moment...

**Comment by ariscahyadi** [comment]
> Do you opened an issue for this? A checklist will help wdyt @ariscahyadi ?

@irvifa yes, it will be good to track all the glossary which has been translated!

**Comment by irvifa** [comment]
Thanks, it’s been hard to track lots of things lately so I really appreciate the effort.

**Comment by ariscahyadi** [comment]
Yes... also still trying to reduce the notifications :)

**Pull request merged**
