### PR TITLE
update training page

### PR DESCRIPTION
**Pull request by Arhell**
this PR https://github.com/kubernetes/website/pull/24014

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-24892--kubernetes-io-master-staging.netlify.app/training/
add shortcode
/assign @inductor

**Comment by bells17** [comment]
/lgtm
/hold

But it seems this PR need to change the base branch to dev-1.18-ja.2.
(dev-1.18-ja.2 branch will be created soon)

**Pull request merged**
