### PR TITLE
add nate-double-u as a blog editor

### PR DESCRIPTION
**Pull request by nate-double-u**
I've been taking part in the blog team as a reviewer for about 6 months, and have also been a docs team release lead.

I'd like to step forward as a blog editor.

/cc @onlydole
/cc @mrbobbytables
/cc @sftim

I'll update https://github.com/kubernetes/community/tree/master/sig-docs/blog-subproject if accepted.

### CODE REVIEW

**Comment by sftim** [comment]
+1 from me on having Nate as a blog editor

**Comment by onlydole** [comment]
It'd be wonderful to have you at the helm, @nate-double-u! 

/approve

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
