### PR TITLE
chore: fix links and names for ii.nz

### PR DESCRIPTION
**Pull request by BobyMCbobs**
- fixes broken links to ii.nz site
- use _ii.nz_ instead of _ii-Team_

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@BobyMCbobs It appears that this PR includes changes to files across multiple languages ([English](https://github.com/kubernetes/website/blob/c186bb576674adea34759528d8a21f491bd5d4fb/content/en/blog/_posts/2023-10-05-sig-architecture-conformance-spotlight.md), [Chinese](https://github.com/kubernetes/website/blob/c186bb576674adea34759528d8a21f491bd5d4fb/content/zh-cn/blog/_posts/2023-10-05-sig-architecture-conformance-spotlight.md)). However, docs follows different processes for each localization, and and we typically don't accept pull requests that impact multiple languages simultaneously. I would recommend modify only the primary website content (which means only English content) initially with this PR. After the merge of the English content, we could create separate pull request for the remaining languages. I hope this suggestion is helpful.

**Comment by dipesh-rawat** [comment]
Hold until this PR only targets only one language.
/hold

_(Okay to unhold once thats done)_

**Review by sftim — COMMENTED** [review]
Thanks
/lgtm
/approve

**Comment by sftim** [comment]
Oops, I didn't see the 2nd language.
/lgtm cancel
/approve cancel

**Comment by kbhawkey** [comment]
👋 @BobyMCbobs 
Can you limit this pull request to one language?
Thanks

**Comment by BobyMCbobs** [comment]
> 👋 @BobyMCbobs Can you limit this pull request to one language? Thanks

@kbhawkey, I'm back at work now and I've updated the PR. Ready for review, cheers!

**Review by sftim — COMMENTED** [review]
/lgtm

**Comment by BobyMCbobs** [comment]
Thank you @reylejano, @sftim!

**Pull request merged**
