### PR TITLE
KubeCon Docs Sprint: Update page weights for content/en/docs/concepts/scheduling-eviction

### PR DESCRIPTION
**Pull request by haosdent**
contributes to https://github.com/kubernetes/website/issues/35093

Updates page weights in content/en/docs/concepts/scheduling-eviction

Before my changes:
image
After my changes:
image

cc @nate-double-u

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@haosdent Please perform a rebase.
/label tide/merge-method-squash

**Comment by sftim** [comment]
/remove-label tide/merge-method-squash

This will need a merge or rebase I'm afraid. A rebase against _main_ is better. @haosdent if you'd like, one of the website maintainers can do that rebase and update _this_ PR with those changes.

Should we do that?

**Comment by haosdent** [comment]
@sftim sure!

**Comment by nate-double-u** [comment]
Hi @haosdent, could you resolve the merge conflicts on this before we merge it in?

**Comment by nate-double-u** [comment]
Actually, looking closer, it seems like this work was done in a prior PR.

I'm going to close this as complete. Thanks for participating in the docs sprint @haosdent!

**Comment by haosdent** [comment]
Noted, thanks @nate-double-u

**Pull request closed without merging**
