### PR TITLE
Fix default value of the annotation aws-load-balancer-internal

### LINKED ISSUE #15771: misleading annotation for aws internal load balancer
**Problem:**
The annotation for internal load balancers on AWS has the value 0.0.0.0/0 for no apparent reason. A cidr range is not required nor supported as a value in this annotation. This is quite confusing.

The implementation at [aws.go](https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/cloudprovider/providers/aws/aws.go#L3324) makes internal load balancers for every value except "false", so "true" has the same effect as 0.0.0.0/0 but is much more intuitive.

**Proposed Solution:**
Change
`service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` to `service.beta.kubernetes.io/aws-load-balancer-internal: "true"`

Due to the CLA, I cannot create a merge request myself.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer

### PR DESCRIPTION
**Pull request by ameukam**
Closes #15771.

/area cloudprovider
/sig aws

### CODE REVIEW

**Comment by sftim** [comment]
Hi @ameukam 

Different language teams have their own review process. You should [limit PRs to a single language](https://kubernetes.io/docs/contribute/intermediate/#working-with-localized-content) to make reviewing straightforward.

Would you be willing to revise this PR, limiting the changes to English, and then submit followup PRs to fix the other localizations?

**Comment by ameukam** [comment]
@sftim Done. Thank you for the tip. 

/remove-language id
/remove-language zh

**Comment by xiangpengzhao** [comment]
This change LTGM, but I'd like to ping @mcrute for accurate tech review :)

**Comment by jsafrane** [comment]
/lgtm
from tech side

**Comment by xiangpengzhao** [comment]
/assign @shavidissa @zacharysarah 
for approval :)

**Comment by zacharysarah** [comment]
@xiangpengzhao Weird, your approval should work.

/approve

**Pull request merged**
