### PR TITLE
Fixing link on Contributing to Kubernetes Documentation in kubernetes / website github repository page

### LINKED ISSUE #36288: Broken link on Contributing to Kubernetes Documentation in kubernetes / website github repository page
**Problem:**
The text [**these instructions to create a documentation pull request against the kubernetes.io repository**](http://kubernetes.io/docs/home/contribute/create-pull-request/). on [link](https://github.com/kubernetes/website/blob/main/CONTRIBUTING.md) is redirecting to [this](https://kubernetes.io/docs/contribute/) , it should point to these https://kubernetes.io/docs/contribute/new-content/open-a-pr/
Check the github repository page [Contributing to Kubernetes Documentation](https://github.com/kubernetes/website/blob/main/CONTRIBUTING.md) for the problem.

**Page to Update:**
https://github.com/kubernetes/website/blob/main/CONTRIBUTING.md

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the link on the text **these instructions to create a documentation pull request against the kubernetes.io repository** to https://kubernetes.io/docs/contribute/new-content/open-a-pr/ and not to this [link](https://kubernetes.io/docs/contribute/).

/kind document
/assign
/language en

### PR DESCRIPTION
**Pull request by kadtendulkar**
Fixes #36288

Updated page [Contributing to Kubernetes Documentation](https://github.com/kubernetes/website/blob/main/CONTRIBUTING.md) of kubernetes / website github repository page

### CODE REVIEW

**Comment by Rishit-dagli** [comment]
The checks seem to be failing due to "Build exceeded maximum allowed runtime"

\retest

**Comment by kadtendulkar** [comment]
Hello @reylejano  since tests are failing, I've raised new PR #36394

**Comment by reylejano** [comment]
Closing in favor of https://github.com/kubernetes/website/pull/36394
/close

**Pull request closed without merging**
