### PR TITLE
Avoid confusing term in API Priority and Fairness concept

### PR DESCRIPTION
**Pull request by NitishKumar06**
Fix: #36393

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Avoid confusing term in API Priority and Fairness concept

**Review by MikeSpreitzer — CHANGES_REQUESTED** [review]
The term "isolation class" appears twice, both occurrences should be replaced.

**Comment by NitishKumar06** [comment]
I'll be raising a new PR for this.

**Comment by NitishKumar06** [comment]
The following PR (https://github.com/kubernetes/website/pull/36607) solves this issue

**Pull request closed without merging**
