### PR TITLE
update training page

### PR DESCRIPTION
**Pull request by Arhell**
this PR https://github.com/kubernetes/website/pull/24014

### CODE REVIEW

**Comment by Arhell** [comment]
review page 
https://deploy-preview-24939--kubernetes-io-master-staging.netlify.app/ko/training/
/assign @fabriziopandini
/assign @mattiaperi

**Comment by tengqm** [comment]
The review page should be
https://deploy-preview-24939--kubernetes-io-master-staging.netlify.app/it/training/

**Comment by Arhell** [comment]
> The review page should be
> https://deploy-preview-24939--kubernetes-io-master-staging.netlify.app/it/training/

Thanks, changed

**Review by irvifa — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
