### PR TITLE
Update ID Docs Setup Page

### PR DESCRIPTION
**Pull request by WilliamChang80**
Update page in https://kubernetes.io/id/docs/setup/ from latest EN version, as mentioned in issue #24090

### CODE REVIEW

**Review by girikuncoro — COMMENTED** [review]
Looking good @WilliamChang80 thanks for doing this! This is one of our oldest pages that we translated, so some words might not what we want, can you fix them when you get time? There are 4 things:
1. Change the italic style from html "< i >" to markdown style with underscore. 
2. Cluster -> klaster. 
3. Deploy -> menggelar. 
4. Cloud doesn't have to be on italic. 

Thanks!

**Comment by WilliamChang80** [comment]
> Looking good @WilliamChang80 thanks for doing this! This is one of our oldest pages that we translated, so some words might not what we want, can you fix them when you get time? There are 4 things:
> 
> 1. Change the italic style from html "< i >" to markdown style with underscore.
> 2. Cluster -> klaster.
> 3. Deploy -> menggelar.
> 4. Cloud doesn't have to be on italic.
> 
> Thanks!

I've updated it, you can check it again

**Comment by girikuncoro** [comment]
Thanks @WilliamChang80, great work, hope you learned something from this

/lgtm
/approve

**Pull request merged**
