### PR TITLE
Update resource-metrics-pipeline.md

### LINKED ISSUE #32183: Clarify Metrics API as Beta
**This is a Feature Request**

**What would you like to be added**

[Metrics API](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/#metrics-api) section describes the Metrics API. It should be designated as `beta`.

This PR can be pushed using one of two possible options:

1. Add a sentence after the second to last paragraph on the page indicating that the Metrics API is beta. 

2. Encapsulate this sentence using the Hugo {{< note >}} shortcode. An example using this short code is shown at the bottom of  the page. 

**Why is this needed**

Beta K8s APIs should be explicitly noted as beta in the K8s docs.

### PR DESCRIPTION
**Pull request by PriyanshuAhlawat**
This pr adds a note to inform that Metrics API is beta.
closes #32183

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
LGTM. 
@piosz @fgrzadkowski please review.

**Comment by reylejano** [comment]
Preview of updated page:
https://deploy-preview-32373--kubernetes-io-main-staging.netlify.app/docs/tasks/debug-application-cluster/resource-metrics-pipeline/

Metrics API targets 1.25 for GA/stable per [Enhancement tracking issue 3048](https://github.com/kubernetes/enhancements/issues/3048)

/approve

**Comment by reylejano** [comment]
Preview of updated page:
https://deploy-preview-32373--kubernetes-io-main-staging.netlify.app/docs/tasks/debug-application-cluster/resource-metrics-pipeline/

Metrics API targets 1.25 for GA/stable per [Enhancement tracking issue 3048](https://github.com/kubernetes/enhancements/issues/3048)

/approve

**Comment by reylejano** [comment]
/approve cancel

Looks like there is a merge conflict
This PR may need a rebase

**Comment by PriyanshuAhlawat** [comment]
@reylejano #32467 is the new pr for the same🙂

**Pull request closed without merging**
