### PR TITLE
Update dev-1.29 branch to sync with main

### PR DESCRIPTION
**Pull request by sftim**
Fix a merge conflict provoked by PR #42823

### CODE REVIEW

**Comment by sftim** [comment]
/approve

given the time constraints. A second approval would be nice.

**Comment by sftim** [comment]
Oops. https://github.com/kubernetes/website/pull/44286#event-11201373628 fixes a stylesheet needed for the v1.29 metrics.

**Review by Arhell — COMMENTED** [review]
/lgtm

**Pull request merged**
