### PR TITLE
Fix link to 'Node heartbeats' section

### LINKED ISSUE #46275: [Node Lease objects] url is wrong
**This is a Bug Report**
The link provided for [Node Lease objects] is wrong

**Problem:**
The provided link is navigating to top of the page not to corresponding sub section.

**Proposed Solution:**
URL link should be https://kubernetes.io/docs/concepts/architecture/nodes/#node-heartbeats

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/leases/#node-heart-beats

### PR DESCRIPTION
**Pull request by tamilselvan1102**
Fixes #46275

### CODE REVIEW

**Comment by tamilselvan1102** [comment]
Preview: https://deploy-preview-46276--kubernetes-io-main-staging.netlify.app/docs/concepts/architecture/leases/#node-heart-beats

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Review by dipesh-rawat — APPROVED** [review]
Thanks for fixing the link!

/approve

**Comment by dipesh-rawat** [comment]
/retitle Fix link to 'Node heartbeats' section

**Pull request merged**
