### PR TITLE
fix the link to [KubeletConfiguration 结构] in configmap document of chinese is 404

### PR DESCRIPTION
**Pull request by kingeasternsun**
fix the link to [KubeletConfiguration 结构] to  the configmap document of chinese is 404 error

because `configmap` and  `secret` has many common parts, So I checked the  document of `secret`, 
fix this with the same content in the  `secret` .

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/website/pull/31045#issuecomment-998441483

**Comment by shuaijinchao** [comment]
Please synchronize all the contents of the English document corresponding to the document after signing the CLA.

---

请在签署CLA后同步文件对应的英文文件的所有内容。

**Comment by shuaijinchao** [comment]
/hold

根据[指南](https://kubernetes.io/zh/docs/contribute/localization_zh/#更新译文)约定，我们会拒绝对页面的部分修改。部分修改针对的是对应页面的英文上游还有其他改动需要同步的情况。一旦我们合并了此 PR，将来就无法根据文件的最后更改时间来判断是否有其他上游变更尚未同步。请理解。

请在 main 分支上执行以下命令查看上游尚未同步的更改：

```bash
./scripts/lsync.sh  content/zh/docs/concepts/configuration/configmap.md
```

**Comment by tengqm** [comment]
No CLA, no response to feedbacks, incomplete sync.
/close

**Pull request closed without merging**
