### PR TITLE
Remove redundant closing spaces

### PR DESCRIPTION
**Pull request by tico88612**
- `ingress.md` remove redundant closing spaces

### CODE REVIEW

**Comment by stmcginnis** [comment]
Good clean up. But this is pretty trivial, so if you see anything else that can be cleaned up while you are at it, that would be great to include it in this PR.

/lgtm

**Comment by ricardoamaro** [comment]
also /lgtm

**Comment by tico88612** [comment]
@stmcginnis I found this by accident, and I'm not sure if this is the case with other documents.

**Comment by stmcginnis** [comment]
/lgtm

Thanks!

**Pull request merged**
