### PR TITLE
Remove accidentally-included API reference files

### PR DESCRIPTION
**Pull request by sftim**
Fixup for PR #27438

Based on PR #27482 by @feloy, and simplified to ensure an easy merge. #27482 can still land later.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @sftim .
Did these changes override/remove the recently generated 1.21 API reference pages?

**Comment by sftim** [comment]
This is a fix for the incorrect merge in https://github.com/kubernetes/website/pull/27438

**Comment by kbhawkey** [comment]
Page previews:
https://deploy-preview-27485--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container
https://deploy-preview-27485--kubernetes-io-master-staging.netlify.app/docs/reference/kubernetes-api/workload-resources/pod-v1/#NodeAffinity

**Pull request merged**
