### PR TITLE
Remove rewrite annotation from minikube ingress example

### PR DESCRIPTION
**Pull request by robert-cronin**
Solves #46546

/sig docs

[Before](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/)
[After](https://deploy-preview-46603--kubernetes-io-main-staging.netlify.app/docs/tasks/access-application-cluster/ingress-minikube/)

### CODE REVIEW

**Comment by robert-cronin** [comment]
Relevant part of the run through:

```
➜  website git:(improve-dual-stack-docs) ✗ minikube tunnel & 
[1] 2895226
➜  website git:(improve-dual-stack-docs) ✗ ✅  Tunnel successfully started

📌  NOTE: Please do not close this terminal as this process must stay alive for the tunnel to be accessible ...

❗  The service/ingress example-ingress requires privileged ports to be exposed: [80 443]
🔑  sudo permission will be asked for it.
🏃  Starting tunnel for service example-ingress.
curl --resolve "hello-world.example:80:127.0.0.1" -i http://hello-world.example
HTTP/1.1 200 OK
Date: Fri, 31 May 2024 08:56:56 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 60
Connection: keep-alive

Hello, world!
Version: 1.0.0
Hostname: web-56bb54ff6d-nxjkl
➜  website git:(improve-dual-stack-docs) ✗ 
```

**Comment by mengjiao-liu** [comment]
/sig network

/cc @bowei @thockin

Need tech review from the ingress side.

**Comment by kundan2707** [comment]
Starting in Version 0.22.0, ingress definitions using the annotation nginx.ingress.kubernetes.io/rewrite-target are not backwards compatible with previous versions. In Version 0.22.0 and beyond, any substrings within the request URI that need to be passed to the rewritten path must explicitly be defined in a capture group.
As this is simple ingress example so no rewrite example is needed

**Comment by divya-mohan0209** [comment]
@kubernetes/sig-network-pr-reviews : PTAL

**Comment by reylejano** [comment]
Duplicate of PR https://github.com/kubernetes/website/pull/46761

**Pull request closed without merging**
