### PR TITLE
Remove OutOfDisk from node condition

### PR DESCRIPTION
**Pull request by lojies**
OutOfDisk is no longer in node contidtion.Remove it from the doc.

### CODE REVIEW

**Comment by zparnold** [comment]
@lojies What version of Kubernetes did this go live?

**Comment by lojies** [comment]
> @lojies What version of Kubernetes did this go live?

This is the changelog from 1.16

- The deprecated node condition type `OutOfDisk` has been removed. Use the `DiskPressure` condition instead. ([#72420](https://github.com/kubernetes/kubernetes/pull/72420), [@Pingan2017](https://github.com/Pingan2017))

**Comment by lojies** [comment]
@dchen1107 @caesarxuchao

**Pull request merged**
