### PR TITLE
[WIP] Add blog article to announce OpenAPI V3 Beta support

### PR DESCRIPTION
**Pull request by Jefftree**

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [WIP] Add blog article to announce OpenAPI V3 Beta support

**Review by sftim — CHANGES_REQUESTED** [review]
The blog articles that are for publication after the v1.24 release should target _main_ (and not _dev-1.24_).

Please change the base branch for this PR; it will save you time if you can do that before you start work.

**Comment by mickeyboxell** [comment]
@Jefftree is there another PR opened for this blog?

**Comment by mickeyboxell** [comment]
@Jefftree following up on my previous message - is there another PR opened for this blog? @sftim have you see another PR?

**Comment by sftim** [comment]
I didn't see another PR.
@Jefftree was your intent here to opt out of a blog announcement for this feature?

**Pull request closed without merging**
