### PR TITLE
[ja] fixed installation guide in using CoreDNS for Service Discovery …

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/44733/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The fix looks good and link update is inline with 'en' PR https://github.com/kubernetes/website/pull/44733/files

/lgtm

[Preview Page](https://deploy-preview-44928--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/administer-cluster/coredns/#installing-coredns)

**Comment by atoato88** [comment]
The target page on the deploy preview site:
- https://deploy-preview-44928--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/administer-cluster/coredns/#installing-coredns

**Pull request merged**
