### PR TITLE
update website docs to add new labels for the job controller

### PR DESCRIPTION
**Pull request by kannon92**
With https://github.com/kubernetes/kubernetes/issues/113714 we are deprecated the unprefixed labels for the job controller.  We should add a deprecated note in the website and update examples with the new labels.

### CODE REVIEW

**Comment by sftim** [comment]
Hi. This should target the branch _dev-1.27_.

**Review by sftim — COMMENTED** [review]
I think you'd also need to update https://kubernetes.io/docs/reference/labels-annotations-taints/ to register the new labels @kannon92

**Comment by kannon92** [comment]
> I think you'd also need to update https://kubernetes.io/docs/reference/labels-annotations-taints/ to register the new labels @kannon92

Nice call out!  Yea I will add that as part of this.

**Comment by kannon92** [comment]
I messed this up.  Going to redo this with using dev-1.27 as my base.

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language es fr hi id ja pl pt ru uk vi zh
/remove-sig release

**Pull request closed without merging**
