### PR TITLE
Small Typo Fix

### PR DESCRIPTION
**Pull request by zou-weidong**
Small Typo Fix

### CODE REVIEW

**Review by bishal7679 — COMMENTED** [review]
@zou-weidong Thanks for raising a PR ✨ 
It is always recommended to first open an issue and then make a necessary PR for that (even it's a small one)
follow this approach for your next contribution
I hope you understand :)

**Review by bishal7679 — APPROVED** [review]
LGTM!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Sea-n** [comment]
Nice Catch!
/lgtm

**Comment by howieyuen** [comment]
thanks
/approve

**Pull request merged**
