### PR TITLE
[zh] fix typo of expose-intro.html

### LINKED ISSUE #28985: Fix Typo: expose-intro.html
"惟一" is a wrong expression, "唯一" is right.

### PR DESCRIPTION
**Pull request by xeathen**
Which issue(s) this PR fixes:

Fixes #28985

### CODE REVIEW

**Comment by xeathen** [comment]
please verify again, thanks!

**Comment by tengqm** [comment]
Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). To find out what are the upstream changes to be synced, do this **on the main branch**:

```shell
./scripts/lsync.sh content/zh/docs/concepts/scheduling-eviction/taint-and-toleration.md
```

/hold

**Comment by xeathen** [comment]
> Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). To find out what are the upstream changes to be synced, do this **on the main branch**:
> 
> ```shell
> ./scripts/lsync.sh content/zh/docs/concepts/scheduling-eviction/taint-and-toleration.md
> ```
> 
> /hold

Sorry, didn't notice this before.

**Comment by mayocream** [comment]
```bash
$ ./scripts/lsync.sh content/zh/docs/tutorials/kubernetes-basics/expose/expose-intro.html
content/zh/docs/tutorials/kubernetes-basics/expose/expose-intro.html is still in sync
```
This file is in sync now.
cc @tengqm

**Pull request merged**
