### PR TITLE
[WIP] Improve the multilingual setup

### PR DESCRIPTION
**Pull request by bep**
Do not merge.

I was asked by @zacharysarah to improve the multilingual configuration and setup of this site to lay the ground for merging of more Chinese content and other languages.

To make it simpler to verify these changes, I will add Norwegian as a test language, which can be toggled of when merged into master.

The current game plan is listed below. I will work fast on this, and plan to be done by the end of tomorrow. We can take discussions/questions then, but if you have any big concerns with the overall plan, shout.

- [x] Add Norwegian as a new test language. Can be toggled on and off.
- [x] Make the "toggle menu" into a proper Hugo menu that can be translated
- [x] Extract UI strings into language bundles
- [x] Verify glossary handling for multiple languages
- [ ] Handle user journey for multiple languages
- [x] Add a `language_alternatives` setting to language config
- [x] Use `language_alternatives` in /blog to fill in untranslated blog content
- [x] Use `language_alternatives` in /docs. This is related to the user journey etc. above, but also applies to the section menu.
~~- [ ] Use `language_alternatives` in /community~~
~~- [ ] Use `language_alternatives` in /partners~~
- [x] Use `language_alternatives` in /case-studies

There are probably some missing pieces in the above, but this should at least give a solid foundation to work from.

### CODE REVIEW

**Comment by bep** [comment]
For people tracking this; the ambition to get this done by end of Friday obviously went south, but I will wrap this up during this week.

**Comment by bep** [comment]
I have found a related Hugo bug that I need to fix before I can complete this. An odd one, but there seem to be some kind of race when "borrowing" content from other languages.

**Comment by bep** [comment]
Note that the added Norwegian translation is not a ready-to-publish translation, but a demo-translation to make it easier to see how a new language will look like.

See: https://deploy-preview-9481--kubernetes-io-master-staging.netlify.com/no/

* All the menus are now dynamic and controlled by content.
* All the UI strings in layouts outside /content are pulled out into i18n bundles
* language_alternatives is added per language (if needed), which in short says: Fill in missing content from these languages in this order.
* language_alternatives (an ordered slice of language codes) is used in blog, glossary, case studies, documentation browser and side-menu

Some notes about the "language_alternatives":

Your "Case studies" section, is basically one big handcrafted HTML that links in the different case studies. This construct makes it very hard to maintain any translation without copying the entire folder and start over...

In my quick outline for a new Case studies section: https://deploy-preview-9481--kubernetes-io-master-staging.netlify.com/no/case-studies/

Here I have created a layout with a loop instead (which is missing some logic to make it the same as today) and converted some of the case-studies into Hugo bundles to make them easier to translate: As in the Blackrock example below: I only need to translate the content file, images and other resources are inherited:

https://github.com/bep/website-1/tree/i18n-b1/content/no/case-studies
https://github.com/bep/website-1/tree/i18n-b1/content/no/case-studies/blackrock
https://github.com/bep/website-1/tree/i18n-b1/content/en/case-studies/blackrock

If you look at the docs section:

Browser: https://deploy-preview-9481--kubernetes-io-master-staging.netlify.com/no/docs/home/?path=users&persona=app-developer&level=foundational
One translated docs file with left nav: https://deploy-preview-9481--kubernetes-io-master-staging.netlify.com/no/docs/home/contribute/ -- here you can also see the glossary tooltips handled for languages.

A note to the first: I have not translated the user journey. It's doable, of course, but it's a fair amount of work, and the approach isn't obvious.

* But both the docs browser and the left side tree menu fills in with links to other languages for missing translations. I have marked the articles in a foreign language with their language code and they open up in a new browser window.
* The glossary is a Hugo bundle, making it easy to add translations as you go. This also uses the language_alternatives list. I have added one Norwegian translation https://github.com/bep/website-1/tree/i18n-b1/content/no/docs/reference/glossary -- that gets merged with the English glossary terms in https://deploy-preview-9481--kubernetes-io-master-staging.netlify.com/no/docs/reference/glossary/?fundamental=true

All of this works, but some of it is a little conceptual (case studies etc.) and needs to be finished once we agree that this is a way to approach this. I wish Hugo language merge queries could be a little simpler (I will probably create some helper functions once I see how that should look like) -- and Hugo will probably eventually get better "content merge support", but this is what Hugo can do today.

**Comment by zacharysarah** [comment]
@mistyhacks @cody-clark 👋 PTAL

/cc @chenopis

**Comment by mistyhacks** [comment]
I looked at the preview for Norwegian and I guess it looks fine. Not really sure how to validate this overall, though.

**Comment by bep** [comment]
This is replaced by smaller PRs.

**Pull request closed without merging**
