### PR TITLE
Fix link to CRI installation instructions page

### PR DESCRIPTION
**Pull request by falzm**

### CODE REVIEW

**Comment by falzm** [comment]
CLA signed.

**Comment by falzm** [comment]
Signed CLA.

**Comment by zparnold** [comment]
@falzm I'm going to close this in favor of https://github.com/kubernetes/website/pull/10435

**Comment by falzm** [comment]
@zparnold but it doesn't fix the problem I've fixed 🤔

**Comment by falzm** [comment]
You probably meant https://github.com/kubernetes/website/pull/10438

**Pull request closed without merging**
