### PR TITLE
[WIP] All Enhancement proposals in single webpage | KEPs

### PR DESCRIPTION
**Pull request by shekhar-rajak**
This PR is for https://github.com/kubernetes/enhancements/issues/2095 and we want a KEP webpage to find out about specific kep and its metadata easily.

Actual Plan:

1. [TODO] We will have `kep_data.yaml` generated in the repo: https://github.com/kubernetes/enhancements  - somewhere in data folder - This can be done by CI when new KEP is merged in the repo, it will automatically generate the kep_data.yaml file using the query `go run ./cmd/kepctl/main.go query --output yaml > data/kep_data.yaml`
2. `kep_data.yaml` will be used in this repo `website` to put in `/keps` webpage  [Currently I have pushed the dump into data folder but in future we want to take it directly from the `enhancements` repo]
3. `/keps` page will display the content in table and we will have search column [TODO] wise like kep-number, sig-group, kep name, etc.

### CODE REVIEW

**Comment by shekhar-rajak** [comment]
Currently it is showing the details in `/keps` page in table with kep-name, kep-number, sig-group name. If anyone want to work on filtering based on columns like kep-number, kep-name,kep-sig and overall search, then feel free to join and commit in the branch.

**Comment by Rahul-D78** [comment]
Hi @shekhar-rajak  I want to work on this can you please provide some resources and what to do  in a brief.

**Comment by shekhar-rajak** [comment]
HI @Rahul-D78 , 

- Get familiar with Hugo and this repo development version - setup it locally and try out how it works
- Clone this PR branch and check how keeps page is added
- Try to improve the UI and use already existing way to beautify it 
- Try out how we can add filter column wise/overall search in this new kep page to find out the enhancement proposals/filter, ..

**Comment by Rahul-D78** [comment]
Thanks @shekhar-rajak

**Comment by shekhar-rajak** [comment]
Search by keyword, filter by sig-group added. Now need to work on CSS part.

**Comment by shekhar-rajak** [comment]
Bootstrap CSS used to beautify the content: https://deploy-preview-28295--kubernetes-io-master-staging.netlify.app/keps

**Review by sftim — COMMENTED** [review]
Hello @shekhar-rajak 

I think KEP list would actually have a better home in https://k8s.dev/ (https://github.com/kubernetes/contributor-site).

Would you like help with adapting this PR to target that other website?

/hold
(I'm open to persuasion about targeting https://kubernetes.io/ rather than https://k8s.dev/ - but I do think that https://k8s.dev/ is the obvious best home).

**Comment by jberkus** [comment]
Agreed that k8s.dev is the right place, this is information-by-and-for-contributors.  How much would have to be redone to move it there?

**Comment by kbhawkey** [comment]
> 
> 
> Hello @shekhar-rajak
> 
> I think KEP list would actually have a better home in https://k8s.dev/ (https://github.com/kubernetes/contributor-site).
> 
> Would you like help with adapting this PR to target that other website?
> 
> /hold
> (I'm open to persuasion about targeting https://kubernetes.io/ rather than https://k8s.dev/ - but I do think that https://k8s.dev/ is the obvious best home).

Hi @shekhar-rajak . Yes, I agree with @sftim. Would you open a PR in the `kubernetes/contributor-site` repository? I think the content belongs in the k8s.dev site. Thanks!

**Comment by shekhar-rajak** [comment]
Thanks @sftim , @berkus, kbhawkey for checking the PR and suggestion. I will work on it .

**Comment by shekhar-rajak** [comment]
Created the PR: https://github.com/kubernetes/contributor-site/pull/222

**Comment by berkus** [comment]
@shekhar-rajak hi, you probably meant @jberkus not me.

**Comment by shekhar-rajak** [comment]
Oops , wrong mention. Sorry!

**Comment by jberkus** [comment]
Oh, hey @berkus, we meet again!

**Comment by berkus** [comment]
@jberkus yep, all the time :)

**Pull request closed without merging**
