### PR TITLE
[es] Shortcode fixes

### PR DESCRIPTION
**Pull request by craigbox**
Hugo v0.111.x will throw an error if calling a shortcode within a fenced code block. (https://github.com/gohugoio/hugo/issues/10819)
This PR brings fixes this issue for the es locale.

### CODE REVIEW

**Comment by electrocucaracha** [comment]
@craigbox this changes \lgtm , but I noticed the reference [seems](https://deploy-preview-39946--kubernetes-io-main-staging.netlify.app/es/docs/tasks/tools/install-kubectl-windows/) to be broken. This is the [Spanish menu (preview)](https://deploy-preview-39946--kubernetes-io-main-staging.netlify.app/es/docs/tasks/tools/)

I'll try to take a look later.

**Comment by craigbox** [comment]
The same is true in the current site: https://kubernetes.io/es/docs/tasks/tools/ links to English pages.
(Or is the site doing something because my browser is in an English locale?)

**Comment by electrocucaracha** [comment]
ok, let's move this forward

/approve

**Comment by craigbox** [comment]
I don't think your `/lgtm` counted because it started life as an `\lgtm` [🙂](https://pbs.twimg.com/media/CvOSYNzVMAAgXh_.jpg)

**Comment by craigbox** [comment]
@electrocucaracha can you `/lgtm` again please?

**Pull request merged**
