### PR TITLE
Improve diagram for “Reserve Compute Resources for System Daemons”

### PR DESCRIPTION
**Pull request by JornShen**
fix https://github.com/kubernetes/website/issues/24398
page at https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/, ASCII-art diagram
 
svg look like this,

image

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
https://deploy-preview-24519--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/reserve-compute-resources/ looks good to me. Thanks @JornShen 

If you wanted to, you could use white text on Kubernetes `#326ce5` blue for the “allocatable” section.
/lgtm

**Comment by JornShen** [comment]
changed

/cc @sftim

**Comment by sftim** [comment]
Ah, one more change please: the allocatable box should use *white* text.

**Comment by JornShen** [comment]
> Ah, one more change please: the allocatable box should use _white_ text.

ok, updated.

**Pull request merged**
