### PR TITLE
Update outdated Korean contents in `release-1.23`

### PR DESCRIPTION
**Pull request by Kid-Chang**
This PR is about Outdated Korean contents in the dev-1.23-ko.3

#33473

### CODE REVIEW

**Comment by seokho-son** [comment]
/retitle Update outdated Korean contents in `release-1.23`

**Comment by seokho-son** [comment]
Hi @Kid-Chang 
Thank you for this contribution to manage Korean contents in the release branch `release-1.23` (previous version).

I found `Some checks were not successful`, but I think this issue needs to be resolved by another PR.
Could you help resolve this issue ? @jihoon-seo

**Comment by jihoon-seo** [comment]
/close
for testing (by opening another PR)

**Comment by jihoon-seo** [comment]
I opened another PR (#36797) for testing but the same error occurred and I cannot find the reason.
So let's reopen this one.
/reopen

I googled the error message and found this thread (but not sure whether this is relevant or not):
https://answers.netlify.com/t/new-builds-fail-with-error-fetching-branch-but-clear-cache-deploy-site-succeeds/14582

**Comment by seokho-son** [comment]
Since maintaining release-1.23 for Korean is not easy, I'd like close this PR so that we can focus on the latest release.

/close

**Pull request closed without merging**
