### PR TITLE
[ja] Update `/content/ja/docs/contribute/localization.md`

### LINKED ISSUE #44183: [ja] Update `/content/ja/docs/contribute/localization.md`
**This is a Feature Request**

**What would you like to be added**

Update `/content/ja/docs/contribute/localization.md`

**Why is this needed**

1. In the Japanese localization, milestones are no longer used.
2. The default branch for kubernetes/website is now 'main' instead of 'master'.

**Comments**

### PR DESCRIPTION
**Pull request by Okabe-Junya**
close #44183 

## Change List

- Update `/content/ja/docs/contribute/localization.md`
    - Removal of descriptions related to milestones.

## Reference

- Related Slack post: https://kubernetes.slack.com/archives/CAG2M83S8/p1689762652870329

### CODE REVIEW

**Comment by atoato88** [comment]
The target page on the deploy preview:
- https://deploy-preview-44184--kubernetes-io-main-staging.netlify.app/ja/docs/contribute/localization

**Review by atoato88 — COMMENTED** [review]
Please check comment.

**Comment by nasa9084** [comment]
really thank you~ :bow:
/approve

**Pull request merged**
