### PR TITLE
WIP:Fix table overlap issue in kubectl command reference

### PR DESCRIPTION
**Pull request by brianpursley**
Add css rule to prevent flags table from overlapping example column on narrow displays.

Fixes https://github.com/kubernetes/website/issues/19519

### CODE REVIEW

**Comment by brianpursley** [comment]
Still some overlap on very narrow displays... I'm going to try to address that.
https://deploy-preview-19540--kubernetes-io-master-staging.netlify.com/docs/reference/generated/kubectl/kubectl-commands

/hold

**Comment by sftim** [comment]
/retitle [WIP] Fix table overlap issue in kubectl command reference
(to mark this as work in progress)
/unhold

**Comment by brianpursley** [comment]
OK, ready for someone to take a look now.

https://deploy-preview-19540--kubernetes-io-master-staging.netlify.com/docs/reference/generated/kubectl/kubectl-commands

/assign rajakavitha1

**Comment by jimangel** [comment]
This fix looks great! However, the `kubectl` docs are generated each release cycle.

- Generation instructions: https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/
- Generation repo: https://github.com/kubernetes-sigs/reference-docs

It's possible these fixes are needed elsewhere.

/cc @tengqm @kbhawkey for tech lgtm

**Comment by brianpursley** [comment]
@jimangel thanks for the info about how those are generated.  I figured the HTML was generated based on how it looked but wasn't sure from where.  I'll take a look at the generator and see what I can do there

**Comment by kbhawkey** [comment]
:eyes:

**Comment by brianpursley** [comment]
Update on this... after some research, I found that I need to update the [brodocs](https://github.com/pwittrock/brodocs) repo. I’ve got a PR to that repo, and then will need to update the [reference-docs](https://github.com/kubernetes-sigs/reference-docs) repo which uses that, and then finally the actual kubectl reference can be regenerated.

**Comment by kbhawkey** [comment]
> Update on this... after some research, I found that I need to update the [brodocs](https://github.com/birdrock/brodocs) repo. I’ve got a PR to that repo, and then will need to update the [reference-docs](https://github.com/kubernetes-sigs/reference-docs) repo which uses that, and then finally the actual kubectl reference can be regenerated.

Hello @brianpursley .
Check out https://github.com/kubernetes-sigs/reference-docs/pull/132.
The `brodocs` code has not been active for a very long time and is difficult to maintain.
I took a quick look at your changes. The changes to the UI look nice, though, I would be in favor of
moving away from using brodocs (and Marked) to generate the `kubectl command ref`.

**Comment by brianpursley** [comment]
@kbhawkey wow thanks, I wasn’t aware of that work being done.

I agree that brodocs seems to add extra complexity and is another dependency which makes layout changes take more effort.

I hadn’t intended to get so far down this path to fix the table overlapping, but at least I learned quite a bit about how the docs get generated, so that’s good.

In light of this other PR, maybe I should just close this PR to avoid duplicating effort.  I’m fine with doing that.  What do you think?  If you want I can review and comment on your PR with respect to the original issue of tables overlapping on mobile display.

**Comment by brianpursley** [comment]
Or maybe I should move ahead with this change and then your PR can replace it later, when it is ready?  I don’t want to rush your PR.

Anyone else have an opinion on this?

**Comment by brianpursley** [comment]
After more though...

I wasn’t really intending on replacing brodocs with this change.

Personally, I think it looks fine... I like the three column display on wide enough screens like slate does, or like stripes api docs.  It just needed some tweaks for other screen sizes to be a little more workable.

I’m ok if it is decided brodocs needs to be replaced in the future, but I still think this change would be ok even if just for a while until something else comes along and replaces it.

Sorry if I misunderstood your point,  I’m relatively new to the kubernetes team and to working on the docs... sos till trying to get a feel for the workflow.

**Comment by kbhawkey** [comment]
Hi @brianpursley .
I very briefly looked at the changes (brodocs).
I think you have made some nice improvements to the existing UI.
Typically, this reference is updated as part of a release and the next release should be happening quite soon (within days or by end of this month).
Would it be possible to use the existing brodocs code to generate the reference and just update the stylesheet? There are other changes to the kubectl commands that are needed for this release (not UI related, https://github.com/kubernetes-sigs/reference-docs/pull/133). Your version of stylesheet.css could be added to kubernetes-sigs/reference-docs as a stop gap and incorporated into building the kubectl command reference. 
Besides the UI, the reference has some other known issues (formatting of links and text).
/cc @zacharysarah @sftim

**Comment by brianpursley** [comment]
@kbhawkey Not sure if my changes will be through in time for the upcoming release or not.  I guess we will see.  It is fine to use the existing reference though, although I know it has some issues.  I'm guessing we can re-gen the docs as needed to fix them.

**Comment by brianpursley** [comment]
I did go ahead and make the brodocs changes (merged in their repo) and have a [PR open for reference-docs](https://github.com/kubernetes-sigs/reference-docs/pull/140) to use the new brodocs and also fix a couple other minor bugs (fix < > escaping and added missing font files).

I realize this may be replaced soon, and will have no hard feelings if it is, or if it even never makes it all the way to prod, so I don't want to halt any other progress being made on an alternative reference, but for now this should hopefully be a stop gap to fix some display issues in the kubectl reference docs

I'm leaving this PR as WIP until the reference-docs can be changed.

**Pull request closed without merging**
