### PR TITLE
KubeCon Docs Sprint: Update Weights for Setup and Subfolders

### PR DESCRIPTION
**Pull request by cailynse**
This PR updates duplicated weights in the setup folder and it sub folders.

Related # https://github.com/kubernetes/website/issues/35093

### CODE REVIEW

**Comment by nate-double-u** [comment]
Thanks @cailynse!

/lgtm
/approve

**Comment by nate-double-u** [comment]
@reylejano @natalisucks deploy preview fail... could you take a look?

**Review by Rishit-dagli — COMMENTED** [review]
Seems like a simple rerun of the tests should do it.
/retest

**Comment by sftim** [comment]
I'm afraid that Prow doesn't know how to trigger another build attempt by Netlify. Not yet.

**Comment by cailynse** [comment]
I reduced a weight that was 30 above to be only 20 above in order to trigger the netlify build again

**Pull request merged**
