### PR TITLE
Merge main branch into dev-1.32

### PR DESCRIPTION
**Pull request by hacktivist123**
This PR syncs the dev-1.32 branch with the main branch to keep the dev-1.32 branch up to date.

cc: @chanieljdan @AnshumanTripathi @rdalbuquerque @spurin @michellengnx

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
/lgtm

**Comment by dipesh-rawat** [comment]
[Bot's comment](https://github.com/kubernetes/website/pull/48938#issuecomment-2515078675)
> Needs approval from an approver in each of these files:
[data/announcements/OWNERS](https://github.com/kubernetes/website/blob/dev-1.30/data/announcements/OWNERS)

This appears to also require approval from @kubernetes/steering-committee _(As this `dev-1.32` branch sync contains the changes to add KubeCon India banner already approved added to `main` branch as part of PR https://github.com/kubernetes/website/pull/48862)_

/committee steering

**Comment by BenTheElder** [comment]
/approve
[given we already approved this banner collectively we don't need the full group to re-evaluate]

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by chanieljdan** [comment]
/assign @tengqm 

Hi @tengqm could we get your final approval on the branch sync for this week?

**Pull request merged**
