### PR TITLE
Update client-libraries.md

### PR DESCRIPTION
**Pull request by jaxzon**
Pykube is archived and not maintained anymore.

### CODE REVIEW

**Comment by jaxzon** [comment]
CLA done

**Comment by jaxzon** [comment]
I signed it

**Comment by jaxzon** [comment]
I signed it

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-28125--kubernetes-io-master-staging.netlify.app/docs/reference/using-api/client-libraries/

**Comment by kbhawkey** [comment]
Thanks for contributing @jaxzon .
/lgtm

**Pull request merged**
