### PR TITLE
markup fixes and clarify `router-id` role

### PR DESCRIPTION
**Pull request by anguslees**
Fix some markup rendering issues in the OpenStack cloud.conf docs, in particular a table was previously completely mis-rendered and illegible.

Also, expand the `[Router]` section with references to kubenet.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6140)

### CODE REVIEW

**Comment by anguslees** [comment]
Ah, I see this duplicates some of #6138 - happy to rebase this after that gets merged.

**Comment by xsgordon** [comment]
The table fixup in #6138 is merged now. Fire when ready.

**Comment by steveperry-53** [comment]
@anguslees Ready for rebase.

**Comment by zacharysarah** [comment]
@anguslees 👋 Please resolve the branch conflicts so we can merge this PR.

**Comment by zacharysarah** [comment]
GitHub seems not to be sending anything to Travis. screen shot 2017-11-29 at 2 21 30 pm

I'm going to try some things to restart the pipeline.

**Comment by zacharysarah** [comment]
Closing in favor of #6491

**Pull request closed without merging**
