### PR TITLE
Tweak kubeadm-upgrade page for indentation nits

### PR DESCRIPTION
**Pull request by tengqm**
The indentation on the page is "messy". We don't encourage implicit code blocks (4-space indentations). The nesting of contents are not properly expressed either.

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
Thanks. This seems fine given we don't loose content and the order is preserved, but probably better to receive review from sig docs / markdown experts.

**Comment by Sea-n** [comment]
Hey @neolit123,

It's over 5 weeks ago, could you recommend someone suitable to review this? Thanks. 🙏

**Comment by neolit123** [comment]
/lgtm
(But like i've mentioned i don't know the markdown corectness)
/assign @reylejano
PTAL for approval if you get a minute.

**Comment by reylejano** [comment]
The changes in this PR look good
Preview of updated page:
https://deploy-preview-33252--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

/approve

**Pull request merged**
