### PR TITLE
[ja] attached correct link

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/42353/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Comment by deepak4566** [comment]
@Arhell thanks for the pr  I think u removed the chineese link ,added japaneese link

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/lgtm

**Comment by atoato88** [comment]
LGTM.

**Pull request merged**
