### PR TITLE
fix: container-runtime full_link 404

### PR DESCRIPTION
**Pull request by HongjiangHuang**
fix: https://github.com/kubernetes/website/issues/28284
The corresponding content has not been translated, link to English content first.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @HongjiangHuang .
In the future, for changes that involve multiple languages, we recommend that you open a pull request for each localization.
/cc @kubernetes/sig-docs-fr-reviews @kubernetes/sig-docs-ru-reviews @kubernetes/sig-docs-it-reviews

**Comment by HongjiangHuang** [comment]
OK, Thanks for your remind.

**Comment by fabriziopandini** [comment]
/lgtm
for the Italian localisation

**Comment by HongjiangHuang** [comment]
OK, Thanks for your remind. @sftim

**Pull request closed without merging**
