### PR TITLE
remove SEE ALSO section from command include files

### PR DESCRIPTION
**Pull request by kbhawkey**
- For further information, see issue #16998.
- Regenerated files using,
  kubernetes/website/update-imported-docs/update-imported-docs
- Pending fix in component generation

### CODE REVIEW

**Comment by neolit123** [comment]
@kbhawkey 
/lgtm
/hold

feel free to remove the hold but ideally @tengqm should confirm if the generator can skip generating these sections for 1.17.

**Comment by tengqm** [comment]
Thanks for getting this fixed.
/lgtm
/approve

**Pull request merged**
