### PR TITLE
Update update-api-object-kubectl-patch.md

### PR DESCRIPTION
**Pull request by praveen-kg**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by praveen-kg** [comment]
This PR is related to the documentation error in Update API Objects in Place Using kubectl patch.
https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/
The example command  kubectl patch deployment patch-demo --patch "$(cat patch-file.yaml)"  provided in document referrers to patch-file.yaml, it should patch-file.json as just before this example says create patch-file.json file and has json syntax. 
If we execute   kubectl patch deployment patch-demo --patch "$(cat patch-file.yaml)"  will throw error, it should be   kubectl patch deployment patch-demo --patch "$(cat patch-file.json)"

**Comment by makoscafee** [comment]
Hi @praveen-kg care to sign CLA for these changes to be merged?

**Comment by xiangpengzhao** [comment]
@praveen-kg good catch! Thanks for the contribution! Please sign your CLA before we can merge this change as @makoscafee mentioned :)

**Comment by praveen-kg** [comment]
I have signed the CLA

**Pull request merged**
