### PR TITLE
fixed tabulation in an example

### PR DESCRIPTION
**Pull request by tomklino**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by bradtopol** [comment]
@tomklino Thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by tfogo** [comment]
Hi @tomklino, thanks for the PR! Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA so that we can review this PR, thanks!

**Comment by tengqm** [comment]
Closing due to 30+ days of CLA check failure.

**Pull request closed without merging**
