### PR TITLE
Remove shortcodes in favor of layout partials

### PR DESCRIPTION
**Pull request by celestehorgan**
/hold

Closes issue https://github.com/kubernetes/website/issues/21609.
Blocked by https://github.com/kubernetes/website/pull/22563.

This PR removes unused shortcodes, as the functionality is now implemented using layout partials, `/partials/announcement.html` and `partials/deprecation-warning.html`.

This requires PR https://github.com/kubernetes/website/pull/22563 is merged before it can be reviewed and merged. 

----

Suggested testing criteria:

0. Ensure the site still builds
1. View a page with an announcement (at this time, all pages). Ensure that announcements are showing correctly. 
2. View a page with a deprecation warning, i.e. an old version. Ensure that the deprecation warning still shows. 
3. Do steps 1-2 for all translations (viewing just the index is fine, I suspect).

### CODE REVIEW

**Comment by celestehorgan** [comment]
rebuild it

**Comment by sftim** [comment]
@celestehorgan to get this to preview OK you might need to rebase it against _master_

**Comment by celestehorgan** [comment]
Thanks @sftim :D

**Comment by onlydole** [comment]
I cleared the cache and rebuilt on Netlify, looks like it's kicking this build back with a...

```
Error: Error building site: "/opt/build/repo/content/es/_index.html:7:1": failed to extract shortcode: template for shortcode "deprecationwarning" not found
```

**Comment by celestehorgan** [comment]
_hisses_

I've opened https://github.com/kubernetes/website/pull/22652 to address any remaining shortcodes.

**Pull request merged**
