### PR TITLE
Fix a broken link in /docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha/

### PR DESCRIPTION
**Pull request by takonomura**
This pull request fixes a broken link in https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha/.

### CODE REVIEW

**Comment by neolit123** [comment]
/lgtm
thanks for the fix!

**Comment by timothysc** [comment]
@kubernetes/sig-docs-pr-reviews  this one is ready to go. 
/assign @Bradamant3  
/approve

**Comment by mistyhacks** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
