### PR TITLE
zh-trans: task-tutorial-prereqs.md

### PR DESCRIPTION
**Pull request by peibingit**
zh-trans: task-tutorial-prereqs.md

### CODE REVIEW

**Comment by markthink** [comment]
@peibingit 方便的话，建议把原始的英文加上..
参考： https://github.com/k8smeetup/k8s-official-translation

**Comment by xichengliudui** [comment]
Ref: `https://github.com/k8smeetup/k8s-official-translation`

**Comment by chenrui333** [comment]
@peibingit 麻烦把原文加上，这样好 review 好一些。

**Comment by chenrui333** [comment]
duplicate of https://github.com/kubernetes/website/pull/12895
/close

**Pull request closed without merging**
