### PR TITLE
Fix typo words in pod describe

### PR DESCRIPTION
**Pull request by yanggangtony**
fix typo words in pod describe.

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @yanggangtony, could you please only include one language in a single PR? For example, you can open a PR only including en language firstly.

**Comment by yanggangtony** [comment]
> Hi @yanggangtony, could you please only include one language in a single PR? For example, you can open a PR only including en language firstly.

Thanks for suggestion.
Will rebased.

**Comment by sftim** [comment]
/retitle Fix typo words in pod describe

**Review by Arhell — COMMENTED** [review]
/lgtm

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Comment by yanggangtony** [comment]
Thanks

**Pull request merged**
