### PR TITLE
January 2018 monthly site maintenance

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR updates links causing 404s. It needs more work on upstream sources:

Area | Who | Description | Done
---|---|---|---
kubectl | @steveperry-53 | All of the terms under [See Also](https://kubernetes.io/docs/reference/generated/kubectl/kubectl/) point to markdown files instead of site paths. See [this comment](https://github.com/kubernetes/website/pull/6924#issuecomment-356765067) for more information. | 
kubeadm | @fabriziopandini | Some kubeadm files point to a markdown file (`/docs/tasks/administer-cluster/kubelet-config-file.md`) instead of a site path. Specifically: `/docs/reference/setup-tools/kubeadm/kubeadm-init/` and `/docs/reference/setup-tools/kubeadm/kubeadm-join/` | ✔️ 

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6924)

### CODE REVIEW

**Comment by zacharysarah** [comment]
## kubectl

@steveperry-53, for reference: 
screen shot 2018-01-10 at 4 40 06 pm
screen shot 2018-01-10 at 4 43 41 pm

**Comment by fabriziopandini** [comment]
@zacharysarah 
Links in `docs/reference/setup-tools/kubeadm/kubeadm-init/` and `/docs/reference/setup-tools/kubeadm/kubeadm-join/` can be fixed directly in the website without the need of any intervention upstream (both of them are manually maintained files; all the generated files for kubeadm are in a separated `/generated`  subfolder)

**Comment by zacharysarah** [comment]
@fabriziopandini Thanks! 👍🏻

**Comment by zacharysarah** [comment]
@chenopis Ready for review!

**Comment by zacharysarah** [comment]
**Note:** Finding the upstream source will take some deeper investigation, so for now, updates to `kubectl.md` are manual fixes to a generated file.

**Comment by zacharysarah** [comment]
Got a review from @steveperry-53: reverted manual changes, LGTM.

**Pull request merged**
