### PR TITLE
delete duplicate "the"

### PR DESCRIPTION
**Pull request by kondr57**

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
@kondr57, Thanks for the PR. Can you sign the CLA so that it can be reviewed?

**Comment by kondr57** [comment]
Hi Savitha,

Unfortunately, I cannot sign the CLA: I'm using the account with my private
(not corporate) email address and I see neither of the following options -
"add second email address to the account", "sign CLA with the private
address". I'll really appreciate if you have any recommendations for this
case (or else please just ignore the PR).

- Vladimir

сб, 13 июн. 2020 г. в 01:33, Savitha Raghunathan <notifications@github.com>:

**Comment by tengqm** [comment]
So ... this PR will not work because it is from an email address that cannot sign CLA.
Please raise a different PR using a working email if you are still interested in this.
Thanks.
/close

**Pull request closed without merging**
