### PR TITLE
Pod preset retirement

### PR DESCRIPTION
**Pull request by jlsong01**
for issue: https://github.com/kubernetes/website/issues/24038

### CODE REVIEW

**Comment by sftim** [comment]
/hold
@jlsong01 I realized there's a detail the issue this did not mention. Sorry about that. The change for this needs to target the v1.20 branch.

Do you know how to revise this change to apply to the branch _dev-1.20_ rather than _master_? If you're not sure, I can make time to explain.

/milestone 1.20

**Comment by tengqm** [comment]
Right. The PodPreset resource was deprecated but its eventual removal is in 1.20.
Please retarget this.

**Comment by jlsong01** [comment]
@sftim @tengqm  Hi, I just retargeted it to dev-1.20. If anything else needed, please let me know. thanks.

**Comment by sftim** [comment]
Hi. Can you [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) this to keep _just_ the relevant commits: a03c82a0913d3f926095a25f879c9fc7f714a43f and 0d5a8bd3ebc51c3bc2a052c42527a77371f626e1.

Ideally, squash those two into a single commit.

If you're not sure what this is about, don't worry. We are keen to help out (especially as it's my incomplete explanation that put you in this situation).

**Comment by jlsong01** [comment]
> Hi. Can you [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) this to keep _just_ the relevant commits: [a03c82a](https://github.com/kubernetes/website/commit/a03c82a0913d3f926095a25f879c9fc7f714a43f) and [0d5a8bd](https://github.com/kubernetes/website/commit/0d5a8bd3ebc51c3bc2a052c42527a77371f626e1).
> 
> Ideally, squash those two into a single commit.
> 
> If you're not sure what this is about, don't worry. We are keen to help out (especially as it's my incomplete explanation that put you in this situation).

hi @sftim, I know how to squash, but not sure about rebase a branch of my repo from another branch of remote repo（k8s/website）. Coud you give me some guide to follow? Thanks

**Comment by tengqm** [comment]
looks like you local dev-1.20 branch is not new. You need to rebase your local `dev-1.20` to the `upstream/dev-1.20` first, and then rebase your PR to your local `dev-1.20`.

**Comment by sftim** [comment]
> rebase

If your [remote](https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) for https://github.com/kubernetes/website is called _kubernetes_, try:
```bash
git fetch kubernetes dev-1.20
git checkout podPreset-retirement
git rebase kubernetes/dev-1.20 # stop if this doesn't work
git push --force-with-lease
```

Those steps are likely to get this PR into a state where it's OK to merge, I think.

**Comment by annajung** [comment]
I think it might be because your branch is based on `master` instead of `dev-1.20`. 1.20 release team is completing a `master` sync tomorrow and I think after that if you rebase, I think it should work.

I can let you know once it's been completed or it might be easier to reset your branch to upstream dev-1.20 and re-commit your changes.

**Comment by sftim** [comment]
@jlsong01 if you want to open a brand new PR that starts from the _dev-1.20_ branch, that's OK too.

**Pull request closed without merging**
