### PR TITLE
Removing merge conflicts for branch dev1.15 

### PR DESCRIPTION
**Pull request by makoscafee**
This PR has updated content in dev1.15 in reference to master branch. Content from dev1.15 was chosen to be to date hence selected over those in master.

steps as described [here](https://gist.github.com/jimangel/288a1a442ba52566ff825bfd828d0a00)

### CODE REVIEW

**Comment by makoscafee** [comment]
cc @jimangel 
/assign @jimangel

**Comment by jimangel** [comment]
Reverting PR as it did not resolve merge conflicts...

**Pull request merged**
