### PR TITLE
[FR] replace all references to `storage.googleapis.com/kubernetes-release` with `dl.k8s.io`

### PR DESCRIPTION
**Pull request by 9bany**
fixes: https://github.com/kubernetes/website/issues/41069 in France

### CODE REVIEW

**Comment by rjsadow** [comment]
@kubernetes/sig-docs-fr-owners It looks like there's an issue with the unit testing. 

/assign @kubernetes/sig-docs-fr-owners

**Comment by rjsadow** [comment]
Hey @9bany 

The CI seems broken, it may need to be pushed again.
```
git commit -s  --amend
git push ..... --force
```

**Comment by 9bany** [comment]
Okey, let me fix it

**Comment by 9bany** [comment]
@rjsadow pls check again

**Comment by 9bany** [comment]
@sftim just done

**Pull request merged**
