### PR TITLE
Fix incorrect code quote in headlines

### PR DESCRIPTION
**Pull request by fanzhangio**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
> Help editing and submitting pull requests:  https://deploy-preview-9510--kubernetes-io-master-staging.netlify.com/docs/contribute/start/#submit-a-pull-request.
> Help choosing which branch to use, see
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
Milestone 
1.12
release
1.12

### CODE REVIEW

**Comment by tengqm** [comment]
pls propose this to the release-1.12 branch

**Comment by fanzhangio** [comment]
PR https://github.com/kubernetes/website/pull/10324

@tengqm Thanks !

**Comment by tengqm** [comment]
@fanzhangio, wait a minute. I was suggesting you to propose this particular PR to the release-1.12 branch. I made  that suggestion based on the comment you left in the commit:

```
Milestone
1.12
release
1.12
```
When I am now looking closer into the PR itself, I'm wondering why this has to be part of release 1.12. Can you help explain?

**Comment by fanzhangio** [comment]
> @fanzhangio, wait a minute. I was suggesting you to propose this particular PR to the release-1.12 branch. I made that suggestion based on the comment you left in the commit:
> 
> ```
> Milestone
> 1.12
> release
> 1.12
> ```
> When I am now looking closer into the PR itself, I'm wondering why this has to be part of release 1.12. Can you help explain?

This is a small bug fix for the incorrect code quote in headlines on page `scale-stateful-set.md`. This fix can improve readability. Since it is not a feature request but a small bug fix, I think it could be merged in release-1.12. Please let me know your ideas. Thanks

**Comment by Bradamant3** [comment]
Sorry, @fanzhangio but this PR is superseded by already merged #10099, so closing unmerged.

**Pull request closed without merging**
