### PR TITLE
edit content/id/docs/concepts/cluster-administration/logging.md

### PR DESCRIPTION
**Pull request by lanandra**
change file to berkas at line 55

### CODE REVIEW

**Comment by girikuncoro** [comment]
/lgtm
/approve

please sign the CLA @lanandra

**Comment by lanandra** [comment]
> /lgtm
> /approve
> 
> please sign the CLA @lanandra

thanks @girikuncoro . I have signed the CLA sign
Please let me /check-cla again to check the pull request

**Comment by girikuncoro** [comment]
thanks @lanandra for your contribution, welcome to kubernetes! 🎉 

#24932

**Comment by lanandra** [comment]
fix #24932

Section docs/concepts/cluster-administration/logging.md

**Pull request merged**
