### PR TITLE
[zh-cn]Resync job.md

### PR DESCRIPTION
**Pull request by yanrongshi**
A min change about zh-cn
Preview:https://github.com/kubernetes/website/pull/35290/files?short_path=9e76853#diff-9e7685352516243d51fb7e00e4c6ec0b45dbe060e85e535891ea2413da30b273

### CODE REVIEW

**Comment by windsonsea** [comment]
A more impressive internet-image of you might come from your daily traces and efforts except for frequent trival changes. 😺

**Comment by yanrongshi** [comment]
> A more impressive internet-image of you might come from your daily traces and efforts except for frequent trival changes. 😺

You are my role model and strength, hats off to the big guy

**Pull request merged**
