### PR TITLE
Updated config.toml 1.17 url fix

### PR DESCRIPTION
**Pull request by VineethReddy02**
fix the URL for v1.17

### CODE REVIEW

**Comment by kbhawkey** [comment]
👀 Still trying to piece together the `pushAssets` change.

**Comment by kbhawkey** [comment]
@VineethReddy02 , OK. Small fixup on v1.16.x.
Preview:
https://deploy-preview-19855--k8s-v1-16.netlify.com/

Version 1.17 does not load from the version drop down list.
Dependent on: https://github.com/kubernetes/website/pull/19838 ?

**Comment by VineethReddy02** [comment]
@kbhawkey The URL was wrong just fixed it.

**Comment by kbhawkey** [comment]
Looks better.
https://deploy-preview-19855--k8s-v1-16.netlify.com/
/lgtm

**Comment by VineethReddy02** [comment]
@jimangel I think we need one more approve label here. Can you help me here?  :)

**Pull request merged**
