### PR TITLE
Update Azure disk feature gates for 1.19 beta

### PR DESCRIPTION
**Pull request by msau42**
Docs for https://github.com/kubernetes/enhancements/issues/1490

### CODE REVIEW

**Comment by msau42** [comment]
cc @andyzhangx

**Comment by savitharaghunathan** [comment]
Preview: https://5f1086c3eb857f0009b001a4--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/
https://5f1086c3eb857f0009b001a4--kubernetes-io-vnext-staging.netlify.app/docs/concepts/storage/volumes/

**Pull request merged**
