### PR TITLE
Fix 404

### PR DESCRIPTION
**Pull request by guettli**
Fix broken internal link.

### CODE REVIEW

**Comment by Sea-n** [comment]
Thanks for your patient, the new one is right. 😊
/lgtm

The file was moved by #32823.
- #32823

**Comment by Sea-n** [comment]
You could fix `content/en/docs/tasks/debug/debug-application/debug-service.md` within this PR too.

```diff
-[Slack](/docs/tasks/debug/overview/#slack) or
+[Slack](/docs/tasks/debug/#slack) or
-Visit the [troubleshooting overview document](/docs/tasks/debug/overview/)
+Visit the [troubleshooting overview document](/docs/tasks/debug/)
```

**Comment by reylejano** [comment]
Thank you for the fix
/lgtm
/approve

**Pull request merged**
