### PR TITLE
Update OWNERS_ALIASES for oussemos

### PR DESCRIPTION
**Pull request by sieben**

### CODE REVIEW

**Comment by zacharysarah** [comment]
@sieben It looks like @oussemos needs to [join the Kubernetes org](https://github.com/kubernetes/org/issues/new/choose) before this PR can merge.

**Comment by oussemos** [comment]
Hello @zacharysarah, I created an issue https://github.com/kubernetes/org/issues/508 to join the org.

**Comment by oussemos** [comment]
I've already joined the org, a kind reminder for this PR :)

**Pull request merged**
