### PR TITLE
Change back cronjob timezone note to UTC

### PR DESCRIPTION
**Pull request by lightlace**

### CODE REVIEW

**Comment by prankul88** [comment]
@lightlace Please ensure that you have signed CLA
Thanks

**Comment by prankul88** [comment]
Looks good now.

**Comment by sftim** [comment]
@lightlace, can you explain why you're making this change?

(At the time of writing, the commit message didn't explain this and the PR description is blank).
If there's an issue you're fixing, please mention it as well.

**Comment by sftim** [comment]
I'm going to assume that this is a fix for https://github.com/kubernetes/website/issues/18579

**Comment by sftim** [comment]
#19269 will revert this

**Pull request merged**
