### PR TITLE
Set the dockershim state to deprecation.

### PR DESCRIPTION
**Pull request by ystkfujii**
Remove the section on dockershim

see : https://github.com/kubernetes/website/issues/30953

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm
Will await another sig docs reviewer to approve before merge.

**Review by sftim — COMMENTED** [review]
dockershim is deprecated but still supported (for one more release)

I think we should:

- leave this in
- mark it deprecated (use the `feature-state` shortcode)
- link to `/dockershim` for more details on the deprecation

and
- open a separate PR against the _dev-1.24_ branch that makes **this** removal

Does that sound right?

**Comment by sftim** [comment]
We want people to find these docs, _and_ we want to steer them towards the deprecation & migration pages.

**Comment by divya-mohan0209** [comment]
That sounds right, @sftim. Maybe, the issue is assigned to the team responsible for removing it as part of the 1.24 release then? Instead of marking at as a good first issue?

**Comment by sftim** [comment]
@celestehorgan you wrote:

_Do not replace or indicate with a warning. The best way to discourage users from using deprecated functionality is to remove it from the docs so they don't even know it's there._

You sure about that? I'm open to being convinced.

This particular page is relevant to someone who wants to try a different container runtime for just part of their workload (leaving everything else on their old runtime).

**Comment by sftim** [comment]
/lgtm

This change does what it sets out to. I'm not 100% sure it's the right change (see earlier discussion).

**Comment by ystkfujii** [comment]
> /lgtm
> 
> This change does what it sets out to. I'm not 100% sure it's the right change (see earlier discussion).

Thanks !

I hope you will review this issue https://github.com/kubernetes/website/pull/30979  as well.

**Comment by ystkfujii** [comment]
> /lgtm
> 
> This change does what it sets out to. I'm not 100% sure it's the right change (see earlier discussion).

thanks !

**Comment by ystkfujii** [comment]
@divya-mohan0209 
Are you okay with this response?

- mark it deprecated (this issue)
- make it removal in the dev-1.24 ( https://github.com/kubernetes/website/pull/30979 )

**Comment by sftim** [comment]
/approve

but also
/hold

as there is disagreement over the right thing to document here

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/31503 is a similar PR.

**Comment by sftim** [comment]
@ystkfujii we're now leaning towards marking this deprecated for the (live) v1.23 docs, and then for the v1.24 docs removing the mention of `dockershim` on that page.

**Comment by sftim** [comment]
I'm happy to remove the hold. I'll wait a bit of time to see if there are objections. Another approver is welcome to /unhold sooner than that.

**Comment by jihoon-seo** [comment]
If this PR gets merged, will it be great to apply this change to the `dev-1.24` branch too?

(For everyone's information: https://github.com/kubernetes/website/pull/30979/files )

**Pull request merged**
