### PR TITLE
Translate contribute/style/index into Japanese

### LINKED ISSUE #23212: Translate contribute/style into Japanese
**This is a Feature Request**

**What would you like to be added**

Translate [contribute/style](https://kubernetes.io/docs/contribute/style) into Japanese.

**Why is this needed**

This page has not been translated.

**Comments**

/language ja
/assign

### PR DESCRIPTION
**Pull request by shuuji3**
Closes #23212.

### CODE REVIEW

**Comment by shuuji3** [comment]
/assign @inductor

Page preview: https://deploy-preview-23213--kubernetes-io-master-staging.netlify.app/ja/docs/contribute/style/

**Review by oke-py — APPROVED** [review]
lgtm, too.

**Pull request merged**
