### PR TITLE
ADD content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md

### PR DESCRIPTION
**Pull request by YouthLab**
dev-1.13分支上pr时已审阅。请直接合并。
Already Pass Review，Merge Directly.

### CODE REVIEW

**Comment by tengqm** [comment]
please
1. double check if release-1.12 has anything different from dev-1.13, and
2. rebase your PR to new release-1.12

**Comment by YouthLab** [comment]
> please
> 
> 1. double check if release-1.12 has anything different from dev-1.13, and
> 2. rebase your PR to new release-1.12

Hi~
1. Already Checked the diff between 1.12 and 1.13 on the original language/en md file. They are the same.
2. I just re-forked the official repository just few days ago，my pr is base release-1.12 already. did i need do something else?

**Comment by tengqm** [comment]
@YouthLab Your PR is from a branch named '`release-1.12`', this is dangerous. It means you won't be able to commit two PRs at the same time for review.  What I will do is something like follows, suppose I have a fork of  the kubernetes/website repo (one remote called `upstream` pointing to the upstream):

```
git checkout master
git fetch upstream
# switch to the HEAD of the branch I want to propose against
git checkout release-1.12
# make sure my origin/release-1.12 is in sync with the upstream
git rebase upstream/release-1.12
git push
# now create a branch for work
git checkout -b trans-kubeadm-init
... (working on this branch locally)

git add .
git commit
# push my local branch to my local repo because I don't have privilege to push to the upstream
# and I'm not supposed to do so even I do have such a permission
git push -u origin trans-kubeadm-init
```

Now on my fork of website, I got a branch named `trans-kubeadm-init`. I will use github web UI to propose a PR against the `release-1.12` branch in the upstream.

When I found conflicts I will go back to my local repo and do:

```
git fetch upstream
git checkout release-1.12
git rebase upstream/release-1.12
git push
git checkout trans-kubeadm-init
git rebase release-1.12
# there could be conflicts in the previous step.
# Now reuse the same commit ID and do a commit
git commit --amend
# force push to my local repo, with will automatically trigger an update to my PR
git push -f
```

There are many helps you can browse, e.g. https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by YouthLab** [comment]
> @YouthLab Your PR is from a branch named '`release-1.12`', this is dangerous. It means you won't be able to commit two PRs at the same time for review. What I will do is something like follows, suppose I have a fork of the kubernetes/website repo (one remote called `upstream` pointing to the upstream):
> 
> ```
> git checkout master
> git fetch upstream
> # switch to the HEAD of the branch I want to propose against
> git checkout release-1.12
> # make sure my origin/release-1.12 is in sync with the upstream
> git rebase upstream/release-1.12
> git push
> # now create a branch for work
> git checkout -b trans-kubeadm-init
> ... (working on this branch locally)
> 
> git add .
> git commit
> # push my local branch to my local repo because I don't have privilege to push to the upstream
> # and I'm not supposed to do so even I do have such a permission
> git push -u origin trans-kubeadm-init
> ```
> Now on my fork of website, I got a branch named `trans-kubeadm-init`. I will use github web UI to propose a PR against the `release-1.12` branch in the upstream.
> 
> When I found conflicts I will go back to my local repo and do:
> 
> ```
> git fetch upstream
> git checkout release-1.12
> git rebase upstream/release-1.12
> git push
> git checkout trans-kubeadm-init
> git rebase release-1.12
> # there could be conflicts in the previous step.
> # Now reuse the same commit ID and do a commit
> git commit --amend
> # force push to my local repo, with will automatically trigger an update to my PR
> git push -f
> ```
> There are many helps you can browse, e.g. https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Thank You for your friendly and patient reply! (*￣︶￣)

**Comment by YouthLab** [comment]
Duplicate of #11377

**Pull request closed without merging**
