### PR TITLE
Add directory comparison script for multilingual content

### PR DESCRIPTION
**Pull request by RifeWang**
### Description

Add a script to compare the differences between files in the multilingual directory and their English versions.

### Issue

Closes: #

### CODE REVIEW

**Comment by tengqm** [comment]
Did you try `scripts/lsync.sh content/zh-cn/docs/concepts` for example?

**Comment by RifeWang** [comment]
> Did you try `scripts/lsync.sh content/zh-cn/docs/concepts` for example?

I have tried it. `lsync.sh` uses the existing files in other language directories as the comparison baseline and then compares git diff, while the new script uses the files in the English directory as the baseline, with the intention of finding missing or additional files in other language directories.

lsync.sh:
```
> ./scripts/lsync.sh content/ja/docs/concepts 
18      2       content/en/docs/concepts/configuration/overview.md
96      44      content/en/docs/concepts/configuration/configmap.md
9       22      content/en/docs/concepts/configuration/secret.md
96      20      content/en/docs/concepts/configuration/manage-resources-containers.md
2       2       content/en/docs/concepts/configuration/liveness-readiness-startup-probes.md
**removed**     content/en/docs/concepts/security/overview.md
2       3       content/en/docs/concepts/security/cloud-native-security.md
6       0       content/en/docs/concepts/security/secrets-good-practices.md
16      2       content/en/docs/concepts/security/pod-security-admission.md
...
```

diff_content_dir.sh:
```
> ./scripts/diff_content_dir.sh content/ja/docs/concepts
Comparing content/ja/docs/concepts with content/en/docs/concepts :
Added in ja: cluster-administration/cluster-administration-overview.md
Added in ja: cluster-administration/manage-deployment.md
Added in ja: extend-kubernetes/extend-cluster.md
Added in ja: overview/working-with-objects/kubernetes-objects.md
Added in ja: security/overview.md
Added in ja: services-networking/connect-applications-service.md
Missing in ja: architecture/mixed-version-proxy.md
Missing in ja: cluster-administration/cluster-autoscaling.md
Missing in ja: cluster-administration/coordinated-leader-election.md
Missing in ja: cluster-administration/flow-control.md
Missing in ja: cluster-administration/kube-state-metrics.md
Missing in ja: cluster-administration/node-shutdown.md
Missing in ja: cluster-administration/system-metrics.md
Missing in ja: cluster-administration/system-traces.md
...
Comparison complete.
```

**Comment by RifeWang** [comment]
I think these two scripts can be used together. The new script can more conveniently find those files that are not translated in the localized language directory.

**Comment by tengqm** [comment]
So ... in summary ...

1. we are adding a new script which covers a smaller scope than an existing one
2. we are adding something new rather than improving the existing one
3. we do know there is another script doing something similar (written in Python) and we don't like it either

?

**Comment by RifeWang** [comment]
ok, draft first

**Pull request closed without merging**
