### PR TITLE
Update 1.17 config.toml for release 1.20

### PR DESCRIPTION
**Pull request by annajung**
Updated config.toml for release v1.20
Versions were updated based on [latest patch releases](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md)

/hold until 1.20 release day

### CODE REVIEW

**Review by savitharaghunathan — COMMENTED** [review]
lgtm 

will leave the actual `/lgtm` for sig-docs leads

**Comment by kbhawkey** [comment]
Thanks @annajung 
/lgtm

**Comment by celestehorgan** [comment]
/approve

Checked this against the patch release list, loaded the netlify preview to check the drop-down worked correctly.

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
