### PR TITLE
[ja] Fix "DIY: Create Your Own Cloud with Kubernetes (Part 1)"

### PR DESCRIPTION
**Pull request by b1gb4by**
## Issue

- Fix https://github.com/kubernetes/website/pull/46686

## Change. List

- Fixed invalid links in the documentation.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @Okabe-Junya

**Review by Okabe-Junya — APPROVED** [review]
Thanks!

/lgtm
/assign bells17 
for approval

**Comment by Okabe-Junya** [comment]
(I'm not a approver, so please wait for approval)

**Pull request merged**
