### PR TITLE
fixed broken link

### LINKED ISSUE #6744: Link to kubeadm reference guide broken
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Link to kubeadm reference guide broken.

In step (2/4) Initializing your master, the link here is broken:
"Please refer to the kubeadm reference guide if you want to read ..."

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
backed by:
docs/setup/independent/create-cluster-kubeadm.md

### PR DESCRIPTION
**Pull request by dungeonmaster18**
fixes #6744

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6756)

### CODE REVIEW

**Comment by tengqm** [comment]
This one is fine, although detlify is unhappy.

**Comment by dungeonmaster18** [comment]
Hey @tengqm I think the netlify is broken because it's failing on master branch as well. Even checked for some other PRS as well it has same error.

**Comment by tengqm** [comment]
@dungeonmaster18 master failure has been fixed.

**Pull request merged**
