### PR TITLE
add baidu cloud provider information

### PR DESCRIPTION
**Pull request by m3ngyang**
Add details about cloud provider node name computation and internal LoadBalancer annotation of Baidu cloud.

### CODE REVIEW

**Comment by m3ngyang** [comment]
I've signed the CLA.

**Comment by hello2mao** [comment]
> I've signed the CLA.

@m3ngyang Maybe you're using a different email address when signing the CLA.  -_-

**Comment by Rajakavitha1** [comment]
Checked the updates on: https://deploy-preview-12738--kubernetes-io-master-staging.netlify.com/docs/concepts/cluster-administration/cloud-providers/
and
https://deploy-preview-12738--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/service/

nit: Should there be a space between Baidu and Cloud in the tab that reads BaiduCloud?

**Comment by m3ngyang** [comment]
@Rajakavitha1 thanks for your review, "Baidu Cloud" is better.

**Comment by Rajakavitha1** [comment]
Checked the updates on: https://deploy-preview-12738--kubernetes-io-master-staging.netlify.com/docs/concepts/cluster-administration/cloud-providers/
and
https://deploy-preview-12738--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/service/

/lgtm
/approve

**Pull request merged**
