### PR TITLE
Fix a broken link in the kueue blog

### PR DESCRIPTION
**Pull request by yuanchen8911**
Fix a broken link in the [Introducing Kueue blog](https://kubernetes.io/blog/2022/10/04/introducing-kueue): [API concepts documentation](https://sigs.k8s.io/kueue/docs/concepts).

Issue: https://github.com/kubernetes/website/issues/45050

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@yuanchen8911 Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Review by dipesh-rawat — COMMENTED** [review]
@yuanchen8911 Also, it appears that this PR includes changes to files across multiple languages _(i.e. English and Chinese)_. However, docs follows different processes for each localization, and and we typically don't accept pull requests that impact multiple languages simultaneously. I would recommend modify only the primary website content (which means only English content) initially with this PR. After the merge of the English content, we could create separate pull request for the remaining languages. I hope this suggestion is helpful.

**Comment by dipesh-rawat** [comment]
@yuanchen8911  I see that the EasyCLA bot has flagged an [error](https://github.com/kubernetes/website/pull/45052#issuecomment-1930565756)) stating that the **_email address_** for the commit (https://github.com/kubernetes/website/commit/ea617c4193371225c932e270c6b75c57f9f605a2) isn't linked to the GitHub account, which might be causing the EasyCLA check to fail. If it's simpler, perhaps consider closing this PR and opening a new one.

[Commit](https://github.com/kubernetes/website/pull/45052/commits) reads: `YUAN Chen authored and yuanchen8911 committed`

> ❌ The email address for the commit (https://github.com/kubernetes/website/commit/ea617c4193371225c932e270c6b75c57f9f605a2) is not linked to the GitHub account, preventing the EasyCLA check. Consult [this Help Article](https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=86641302) and [GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve. (To view the commit's email address, add .patch at the end of this PR page's URL.) For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

**Review by Gauravpadam — COMMENTED** [review]
Thanks @yuanchen8911
As per our policy, we don't maintain articles older than a year.

/remove-lgtm

**Comment by yuanchen8911** [comment]
> @yuanchen8911 Also, it appears that this PR includes changes to files across multiple languages _(i.e. English and Chinese)_. However, docs follows different processes for each localization, and and we typically don't accept pull requests that impact multiple languages simultaneously. I would recommend modify only the primary website content (which means only English content) initially with this PR. After the merge of the English content, we could create separate pull request for the remaining languages. I hope this suggestion is helpful.

Reverted the change to the Chinese version.

**Comment by yuanchen8911** [comment]
> Thanks @yuanchen8911 As per our policy, we don't maintain articles older than a year.
> 
> /remove-lgtm
but it's the latest web page.

**Comment by Gauravpadam** [comment]
> The current web page is based on this doc.

What web page are we talking about @yuanchen8911?

**Comment by yuanchen8911** [comment]
> > The current web page is based on this doc.
> 
> 
> 
> What web page are we talking about @yuanchen8911?
> 
> 
> 
> 

[Introducing Kueue blog](https://kubernetes.io/blog/2022/10/04/introducing-kueue/): the link to "API concepts documentation".

Please see the details in issue https://github.com/kubernetes/website/issues/45050

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by Gauravpadam** [comment]
> [Introducing Kueue blog](https://kubernetes.io/blog/2022/10/04/introducing-kueue/): the link to "API concepts documentation".

That is indeed an older blog which falls out of our maintenance duration @yuanchen8911,
I'll be closing this PR
/close

**Pull request closed without merging**
