### PR TITLE
ZH-trans: update kubeadm_reset.md

### PR DESCRIPTION
**Pull request by xichengliudui**
ZH-trans: update kubeadm_reset.md

### CODE REVIEW

**Comment by xichengliudui** [comment]
image

**Comment by xichengliudui** [comment]
[original address](https://v1-12.docs.kubernetes.io/zh/docs/reference/setup-tools/kubeadm/kubeadm-reset/)
[preview the address](https://5c2de02ceedd7f0009a6e8b0--k8s-v1-12.netlify.com/zh/docs/reference/setup-tools/kubeadm/kubeadm-reset/)

**Comment by tengqm** [comment]
/lgtm
/approve
Thanks.

**Pull request merged**
