### PR TITLE
[es] fix links to ephemeral volume types

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/33565/files
/assign @electrocucaracha

### CODE REVIEW

**Comment by electrocucaracha** [comment]
@Arhell this PR looks good, I'm just wondering why you marked as drafted.

**Comment by Arhell** [comment]
> @Arhell this PR looks good, I'm just wondering why you marked as drafted.

I'm sorry, I had to check something

**Comment by Arhell** [comment]
@electrocucaracha  I have noticed this from time to time tests fail in netlify. Have to make a new push commit

**Pull request merged**
