### PR TITLE
[hi] Move "what-is-kubernetes" to "Overview" page

### PR DESCRIPTION
**Pull request by abhay-raj19**
Ref : #42844 

As suggested by @aj11anuj I had updated up those changes .

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/retitle [hi] Move "what-is-kubernetes" to "Overview" page

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for your contribution! It appears that there are some incomplete or inaccurate changes in the PR, as the [Netlify build](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6553fb73f49ffb000840f0f5) preview is encountering following error :

> 10:58:25 PM: Start building sites …
> 10:58:25 PM: hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
> 10:59:32 PM: ERROR 2023/11/14 22:59:32 [hi] REF_NOT_FOUND: Ref "/docs/concepts/overview/what-is-kubernetes": "/opt/build/repo/content/hi/_index.html:1:1": page not found
> 10:59:35 PM: Error: Error building site: logged 1 error(s)
> 10:59:35 PM: Total in 70181 ms
> 10:59:35 PM: make: *** [Makefile:43: deploy-preview] Error 255

Please address these build errors before the PR can be deemed ready for review and merging.

**Comment by dipesh-rawat** [comment]
/hold
Explicit hold to avoid accidental merges.
_(Ok to unhold once the build errors are rectified)_

**Review by aj11anuj — COMMENTED** [review]
This build error can be resolved by following options:-
1. Revert it to normal state, then 1st make a PR for changing title key-value pair only. Let that PR merged and then make another PR for renaming the file.
2. Revert it to normal state, then make a commit for a new file with updated key-value pair and name as `_index.md` inside `/hi/docs/concepts/overview/` directory, after that make another commit for deleting whole `what-is-kubernetes.md` file.

Both of the above options are high likely to resolve this issue, choose whichever you find convenient.

**Review by dipesh-rawat — COMMENTED** [review]
If I interpret the build error correctly, it seems that the renaming of the file may require a corresponding change in [/content/hi/_index.html](https://github.com/kubernetes/website/blob/main/content/hi/_index.html)

> 10:59:32 PM: ERROR 2023/11/14 22:59:32 [hi] REF_NOT_FOUND: Ref "/docs/concepts/overview/what-is-kubernetes": "/opt/build/repo/content/hi/_index.html:1:1": page not found
> 10:59:35 PM: Error: Error building site: logged 1 error(s)


@abhay-raj19 Please navigate to [Line 11](https://github.com/kubernetes/website/blob/main/content/hi/_index.html#L11) in [/content/hi/_index.html](https://github.com/kubernetes/website/blob/main/content/hi/_index.html) and consider changing following text _(deleting 'what-is-kubernetes' text from file)_ :
````diff
- {{< relref "/docs/concepts/overview/what-is-kubernetes" >}}
+ {{< relref "/docs/concepts/overview/" >}}
````
Check if the above change resolves the error and allows for further progress. I hope this suggestion proves helpful.

**Comment by abhay-raj19** [comment]
> If I interpret the build error correctly, it seems that the renaming of the file may require a corresponding change in [/content/hi/_index.html](https://github.com/kubernetes/website/blob/main/content/hi/_index.html)
> 
> > 10:59:32 PM: ERROR 2023/11/14 22:59:32 [hi] REF_NOT_FOUND: Ref "/docs/concepts/overview/what-is-kubernetes": "/opt/build/repo/content/hi/_index.html:1:1": page not found
> > 10:59:35 PM: Error: Error building site: logged 1 error(s)
> 
> @abhay-raj19 Please navigate to [Line 11](https://github.com/kubernetes/website/blob/main/content/hi/_index.html#L11) in [/content/hi/_index.html](https://github.com/kubernetes/website/blob/main/content/hi/_index.html) and consider changing following text _(deleting 'what-is-kubernetes' text from file)_ :
> 
> ```diff
> - {{< relref "/docs/concepts/overview/what-is-kubernetes" >}}
> + {{< relref "/docs/concepts/overview/" >}}
> ```
> 
> Check if the above change resolves the error and allows for further progress. I hope this suggestion proves helpful.

sure sure will do that

**Pull request closed without merging**
