### PR TITLE
Get Extend Kubernetes section into left nav.

### PR DESCRIPTION
**Pull request by steveperry-53**
This PR creates an **Extending Kubernetes** section in the left nav.
Addresses part of #8275.

Preview: https://deploy-preview-8530--kubernetes-io-master-staging.netlify.com/docs/concepts/extend-kubernetes/extending/

### CODE REVIEW

**Comment by Bradamant3** [comment]
@steveperry-53 I might have merged something else that's causing the merge conflict -- sorry! Ping me after you fix and I'll get this one merged.

**Comment by steveperry-53** [comment]
Started again in new PR #8569/

**Pull request closed without merging**
