### PR TITLE
docs(ingress) updating Kong Ingress links

### PR DESCRIPTION
**Pull request by subnetmarco**
Updating link for the Kong Ingress Controller.

### CODE REVIEW

**Comment by subnetmarco** [comment]
I just signed the CLA.

**Comment by subnetmarco** [comment]
@bprashanth @Rajakavitha1 It's the first time I opened a PR here. Is something else required from me or should I just wait?

**Comment by bradtopol** [comment]
@subnetmarco Thank you for your contribution. I am reviewing it now

**Comment by bradtopol** [comment]
Updates look great! Typo fixed and all updated links work. Great job!!
/lgtm
/approve

**Pull request merged**
