### PR TITLE
Fix kind delete cluster commands

### PR DESCRIPTION
**Pull request by CodingCanuck**
The name flag requires two leading dashes, not one.

### CODE REVIEW

**Comment by annajung** [comment]
Thank you!
/lgtm

**Comment by CodingCanuck** [comment]
Thanks, @annajung ! I think I also need your approval in order to merge this. (Same with #31161 )

**Comment by annajung** [comment]
Hi @CodingCanuck, another reviewer will approve after reviewing. thanks!

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Comment by divya-mohan0209** [comment]
Taking lgtm from [this comment](https://github.com/kubernetes/website/pull/31184#issuecomment-1004389020) by @annajung and approving it.
/approve

**Pull request merged**
