### PR TITLE
[zh-cn] sync 1.25 persistent-volume-claim-v1.md and persistent-volume…

### PR DESCRIPTION
**Pull request by jzhupup**
Updated `alpha` to `beta`

```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1.md
```
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
```

### CODE REVIEW

**Comment by windsonsea** [comment]
The second file has a tip of: `is still in sync` by running `./scripts/lsync.sh`. Please ensure you have found all changes from the en upstream, thanks.
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
```

**Comment by Sea-n** [comment]
Hey @jzhupup,

It's been a while since the last update, would you like to address issues in the previous comments so that we can move forward?

**Comment by jzhupup** [comment]
@windsonsea I have run `./scripts/lsync.sh`. Looks like there is no need to sync

image

**Pull request merged**
