### PR TITLE
specify Pod not to display redundant messages

### PR DESCRIPTION
**Pull request by oke-py**

### CODE REVIEW

**Comment by sftim** [comment]
Nice fix
/lgtm

**Comment by stewart-yu** [comment]
I'm not sure about it. In the first step, we get the pod until no longer running, should we can get the specify pod in the secondary step?

**Comment by oke-py** [comment]
@stewart-yu You might be right.

I thought other pods output could be a hindrance and so it could be tough to find the target information. What's more, given the pod name `termination-demo` is specified in the step 4, it should also be specified in the step 3 in my opinion.

However, there might be some reason for not specifying the pod name in the step 3. Otherwise, step 2 could have `-o yaml` option.

**Comment by steveperry-53** [comment]
I agree that it's good to include the Pod name in both commands.

/approve
/lgtm

**Pull request merged**
