### PR TITLE
translate this page into Chinese: https://kubernetes.io/blog/2022/01/…

### PR DESCRIPTION
**Pull request by lishuai-hw**
…10/meet-our-contributors-india-ep-01/

### CODE REVIEW

**Comment by Sea-n** [comment]
/hold

Please add space between Chinese and English words just like [existing blog posts](https://kubernetes.io/zh/blog/).

For example: `他目前是Kubernetes 1.23版本团队的CI Signal经理。`
Should be: `他目前是 Kubernetes 1.23 版本团队的 CI Signal 经理。`

You can refer to [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines) for further reason and examples.

**Comment by lishuai-hw** [comment]
#32893

**Comment by lishuai-hw** [comment]
> /hold
> 
> Please add space between Chinese and English words just like [existing blog posts](https://kubernetes.io/zh/blog/).
> 
> For example: `他目前是Kubernetes 1.23版本团队的CI Signal经理。` Should be: `他目前是 Kubernetes 1.23 版本团队的 CI Signal 经理。`
> 
> You can refer to [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines) for further reason and examples.

Thanks for your review. I have already add one space between Chinese and English words. Pls check again.

**Review by howieyuen — APPROVED** [review]
/lgtm

**Pull request merged**
