### PR TITLE
[hi] Localize content/hi/docs/reference/glossary/applications.md

### PR DESCRIPTION
**Pull request by amolmote**
Signed-off-by: Amol Mote <amolmote201@gmail.com>

FIxex #35600

### CODE REVIEW

**Comment by bishal7679** [comment]
part of #35600

**Review by bishal7679 — COMMENTED** [review]
@Babapool Is it appropriate to use अनुप्रयोग for `applications` or transliteration would be good!

**Comment by Babapool** [comment]
@bishal7679 I personally prefer to transliterate the word `application` as people can easily associate with it as compared to `अनुप्रयोग`.

**Comment by amolmote** [comment]
I had doubt in other words I think we need to keep those terms also as it is. I am planning to prepare spreadsheet for those words soon when I will get bandwidth.

**Comment by Babapool** [comment]
@amolmote IMO it is better to have a discussion on which words that could be transliterated on the slack channel . After a consensus is reached on those words, they can then be added to the reference spreadsheet (which is already there) for the reference of other contributors. Thanks.

**Comment by kundan2707** [comment]
@amolmote  I Already opens a PR for the same which is yet to be reviewed.
https://github.com/kubernetes/website/pull/38326

**Comment by amolmote** [comment]
Hi kundan, I had open it on 27th aug but due to some issue I have reopened it please check this https://github.com/kubernetes/website/pull/36350

**Comment by kundan2707** [comment]
@amolmote  thanks for update. I am closing mine one

**Pull request closed without merging**
