### PR TITLE
misspell gigibytes into gigabytes

### PR DESCRIPTION
**Pull request by macvek**

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
Hi @macvek, and thank you for your fix!

Few things:

- Could you please sign the CLA before your PR can be reviewed. For steps to sign the CLA please refer: https://github.com/kubernetes/community/blob/master/CLA.md

- We try to follow the [Trivial Edits guidelines](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) as much as we can. I kindly ask you to find more things you can improve in the same document or any other page you went through recently so that one PR can cover more improvements.

**Review by Arhell — COMMENTED** [review]
/easycla

**Review by sftim — CHANGES_REQUESTED** [review]
I looked at https://github.com/kubernetes/website/pull/39675#pullrequestreview-1315001221

That manifest _does_ specify 10 [gibibytes](https://physics.nist.gov/cuu/Units/binary.html) of storage. The original text is correct.

I don't think there's anything to fix.

**Comment by macvek** [comment]
Wow; you are right; My total mistake; should have checked before; thx for review ;) closing

**Pull request closed without merging**
