### PR TITLE
Revise annual report blog article: typo fixes, image

### PR DESCRIPTION
**Pull request by sftim**
Revise https://blog.k8s.io/2021/06/28/announcing-kubernetes-community-group-annual-reports/ (scheduled article):

- fix invalid Markdown
- fix a spelling error
- add an [image](https://github.com/kubernetes/website/blob/7f6a77efe896cf9af77d6b8cdeefac9fb655da58/content/en/blog/_posts/2021-06-28-announcing-kubernetes-community-group-annual-reports/k8s_annual_report_2020.svg)

@divya-mohan0209  FYI
@onlydole could I ask that you take a look at this one

/kind cleanup
/area blog
/language en
/priority important-soon

### CODE REVIEW

**Comment by sftim** [comment]
BTW you might need to pull this locally to preview it - I'm not sure if Netlify previews for future articles are working how we'd expect.

**Comment by sftim** [comment]
I've made an image because:
- I think it looks better
- we always have at least one image in the blog I edit for work

If it's not a popular suggestion, I'm happy to drop that commit and just keep the fixes.

**Comment by mrbobbytables** [comment]
> BTW you might need to pull this locally to preview it - I'm not sure if Netlify previews for future articles are working how we'd expect.

It works for previews as long as `--build-future` is passed 👍 
/lgtm
/approve

**Comment by sftim** [comment]
Thanks for the review

**Pull request merged**
