### PR TITLE
Fix a typo in Deployments

### PR DESCRIPTION
**Pull request by danrot**
There was a typo in the word Deployments.

### CODE REVIEW

**Comment by danrot** [comment]
Created a CLA.

**Comment by danrot** [comment]
I signed it

**Comment by danrot** [comment]
I have no idea why the CLA is not working... I have created it, and I am currently logged in using GitHub on the linux foundation website:

image

**Comment by danrot** [comment]
@tengqm I have checked, and the email address in the git config matches the main one from my github profile. I've also ammended the commit and pushed it again, but the CLA check still seems to fail...

**Comment by jimangel** [comment]
/check-cla
(testing to see if it's resolved)

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by natalisucks** [comment]
Hey there @danrot - given there are still issues with the CLA and you've tried the listed suggestions, I think the next step is to log a ticket with the LFX Helpdesk: https://support.linuxfoundation.org/. Sorry that this isn't resolved, but hopefully that ticket can help clear things so that folks can review/approve this PR

**Comment by danrot** [comment]
@natalisucks Created a ticket, I'll let you know as soon as the issue is resolved.

**Comment by danrot** [comment]
Finally! 😄

**Comment by reylejano** [comment]
@danrot , 
Thank you for fixing the typo and I'm glad the CLA issue is resolved

/lgtm
/approve

**Pull request merged**
