### PR TITLE
Remove duplicate example yaml

### PR DESCRIPTION
**Pull request by Harmeet25**

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @Harmeet25, Try to follow PR template as it will help reviewers to inspect your changes.

**Comment by utkarsh-singh1** [comment]
Also seems like there is Netlify build timeout, use these commands to trigger rebuild-

```bash
git reset
git commit --amend --no-edit
git push --force-with-lease
```

**Comment by Harmeet25** [comment]
@utkarsh-singh1 it is my first contribution can you please explain me in simple terms  so I can understand what to do

**Comment by utkarsh-singh1** [comment]
Hi @Harmeet25, There is a note before submitting PR you can read it through to gain insight what is needed, Take a look again here - 

```
 Hello!

 Remember to ADD A DESCRIPTION and delete this note before submitting
 your pull request. The description should explain what will change,
 and why.

 PLEASE title the FIRST commit appropriately, so that if you squash all
 your commits into one, the combined commit message makes sense.
 For overall help on editing and submitting pull requests, visit:
  https://kubernetes.io/docs/contribute/suggesting-improvements/

 Use the default base branch, “main”, if you're documenting existing
 features in the English localization.

 If you're working on a different localization (not English), see
 https://kubernetes.io/docs/contribute/new-content/overview/#choose-which-git-branch-to-use
 for advice.

 If you're documenting a feature that will be part of a future release, see
 https://kubernetes
```

**Comment by utkarsh-singh1** [comment]
You can also follow this example PR template - 

```
Description (bold):
Issue discription

Proposed Solution (bold):
Propose solution for the issue.

Page to update (in bold):
link to web-page

fixes: issue-link that is being fixed

**Comment by utkarsh-singh1** [comment]
@Harmeet25, seems like this PR can help solve important issue, can you try to raise another PR or above solution provided.

**Comment by utkarsh-singh1** [comment]
You can try to rebase your current commit.

**Comment by utkarsh-singh1** [comment]
Also, if you are struggling to get started in Kubernetes, You can follow this guide -
 - https://kubernetes.io/docs/contribute/
 - https://kubernetes.io/docs/contribute/style/style-guide/

**Comment by utkarsh-singh1** [comment]
Also seems like the issue #40224 has been resolved by PR - #40230, you can close this issue.

**Comment by kbhawkey** [comment]
Hello @Harmeet25 .
Since there has been no activity on this pull request, I plan to close it.
You can always reopen your pull request and continue to add changes to it.
/close

**Pull request closed without merging**
