### PR TITLE
Change "a" to "an" in docs

### PR DESCRIPTION
**Pull request by douglasnaphas**

### CODE REVIEW

**Comment by sftim** [comment]
Hi @douglasnaphas. If you can [sign the CLA](https://github.com/kubernetes/website/pull/29213#issuecomment-892299195), we can review your PR.

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by bradtopol** [comment]
Hi @douglasnaphas you are still having cla issues. Please sign the cla so we can accept your PR for review. Thank you for your contribution!
/assign

**Comment by douglasnaphas** [comment]
The CLA site said it would send me an email, but it never came. I’ll try again soon.

**Comment by RA489** [comment]
> The CLA site said it would send me an email, but it never came. I’ll try again soon.

Please rebase your PR.
/check-cla

**Comment by douglasnaphas** [comment]
This was fixed by https://github.com/kubernetes/website/commit/a130f6b8b9d82d1be62ab63b341d9ebf40fda592, closing.

**Pull request closed without merging**
