### PR TITLE
Remove kompose up and down command doc

### PR DESCRIPTION
**Pull request by afoster**
Further to https://github.com/kubernetes/website/pull/30690 - remove more references to `kompose up` and `kompose down`.

### CODE REVIEW

**Review by cdrage — APPROVED** [review]
LGTM!

**Comment by reylejano** [comment]
Typically PRs should be only for localization
Changes to the English site are to be merged first before opening PRs to localizations to make the same change
Since this has approvals from the fr and zh owners
/approve

**Pull request merged**
