### PR TITLE
[fix]: fix translation error in README-zh.md

### PR DESCRIPTION
**Pull request by HustCoderHu**
### Issue

Closes: #

### CODE REVIEW

**Review by jgao1025 — COMMENTED** [review]
It still feel a bit unclear.  How about "这些是原始的 gist 链接，现在它们会链接到我的 gist。"??

**Review by ox01024 — APPROVED** [review]

**Comment by ox01024** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: *<a href="https://github.com/kubernetes/website/pull/47432#pullrequestreview-2231825432" title="Approved">ox01024</a>*
> **Once this PR has been reviewed and has the lgtm label**, please assign [natalisucks](https://github.com/natalisucks) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubernetes%2Fwebsite).
> 
> <details open>
> Needs approval from an approver in each of these files:
> 
> - **[OWNERS](https://github.com/kubernetes/website/blob/main/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment
> Approvers can cancel approval by writing `/approve cancel` in a comment
> </details>
> 

/approve cancel

**Review by ox01024 — COMMENTED** [review]
原来的有什么问题？？

**Comment by HustCoderHu** [comment]
> It still feel a bit unclear. How about "这些是原始的 gist 链接，现在它们会链接到我的 gist。"??

sounds good,  appreciate your improved translation  ^_^

**Pull request merged**
