### PR TITLE
removed the docker logo

### PR DESCRIPTION
**Pull request by RayAsh37**
I have read all the guidelines and have tried my best to adhere to them. As mentioned in issue #30948  I have updated the visual representation for a container without reference to the original docker logo. Since it was an image, I had to replace the entire file

This is my first time making a PR so any feedback and suggestions/criticism are very much welcome/appreciated.

### CODE REVIEW

**Comment by sftim** [comment]
Please follow the advice in https://github.com/kubernetes/website/pull/30978#issuecomment-994732862 @RayAsh37

**Comment by RayAsh37** [comment]
> Please follow the advice in [#30978 (comment)](https://github.com/kubernetes/website/pull/30978#issuecomment-994732862) @RayAsh37

Thank you, I have done the required. Is there anything else I need to do on my part to get my PR reviewed or just wait for the project owners to review?

**Comment by sftim** [comment]
@RayAsh37 you're all set!

**Comment by celestehorgan** [comment]
@RayAsh37 - can you open this commit against the `dev-1.24` branch instead? I'd like to make sure we keep all dockershim-related changes to that branch so we can keep track of them :) 

Once that's done, I'm happy to approve.

**Comment by RayAsh37** [comment]
@celestehorgan - I have changed the base branch of my PR to `dev-1.24`

Please correct me in case I was wrong and that was not what you intended. I am very happy to learn

**Comment by sftim** [comment]
/hold

There are lots of commits that we wouldn't want to apply to `dev-1.24` as part of this merge.

**Comment by sftim** [comment]
@RayAsh37 do you know how to rebase this against the new base branch? If not, that's OK - say so and we can recommend a course of action.

**Comment by RayAsh37** [comment]
@sftim hey, I did a little research and this is what I came up with. If it's still wrong then I will take up on your offer, please recommend a course of action that and I will try my best.

Thank you for being so patient with me :)

**Comment by RayAsh37** [comment]
@sftim is this rebase?

**Comment by championshuttler** [comment]
@RayAsh37 yeah  it  is but it seems file is still here, you can follow these  steps

```
1. rm -rf static/images/docs/4c.png
2. git add static
3. git commit --amend --no-edit
4. git push origin overview_to_remove_docker_logo -f
```

Let me know  if you  still face some issues

**Comment by RayAsh37** [comment]
@championshuttler I just need a little clarification. Do you mean I need to delete the actual file that i modified in the local repository?

**Comment by championshuttler** [comment]
> @championshuttler I just need a little clarification. Do you mean I need to delete the actual file that i modified in the local repository?

Sorry @RayAsh37 my bad, no you dont need to delete whole file, I read the issue differently by mistake, it looks good to me, one thing which is mentioned in issue is that it would  be great to have svg file so something we can edit it later on if needed

**Comment by RayAsh37** [comment]
Ahh yeah I am working on that, facing a bit of a hiccup. Will add to the same branch once done :)

**Comment by RayAsh37** [comment]
@nate-double-u @celestehorgan I have done the required changes and also included the SVG file. Please review.

Thank you

**Comment by nate-double-u** [comment]
Looking at the commit log, I'm not sure why the "Tracking commit for v1.24 docs" commit is there. The dev-1.24 branch has been updated, perhaps we need a rebase?

**Comment by RayAsh37** [comment]
Hey, @nate-double-u I tried rebasing but that commit isn't going away. As far as my knowledge, I don't remember that particular commit and I checked in GitHub, that commit has zero changes to the codebase. Maybe I messed up during rebase because I didn't know to rebase properly until recently. Should I make a new PR ?

**Comment by nate-double-u** [comment]
This is a pretty good write up about interactive rebasing that may help: https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d

**Comment by RayAsh37** [comment]
@nate-double-u  I think I messed up beyond repair this time. Thanks for your support. Yeah, I am learning Git. I am a bit slow-learner and I have no regret going a bit extra as it has always provided me opportunities to learn. But fixing this, I am not really sure.

**Comment by shannonxtreme** [comment]
Just chiming in to say that sometimes Git has a bad day and takes it out on
you and that's okay, you're doing great and help is coming 😊

**Comment by RayAsh37** [comment]
hey @nate-double-u , I tried but it was too difficult to fix. This #31338 is my new PR. Is this satisfactory?

Also thank you @shannonxtreme but I won't back down that easily :)

**Comment by nate-double-u** [comment]
Closing in favour of https://github.com/kubernetes/website/pull/31338

/close

**Comment by nate-double-u** [comment]
> hey @nate-double-u , I tried but it was too difficult to fix. This #31338 is my new PR. Is this satisfactory?

Thanks for trying, I've given the new PR an LGTM, and am closing this one.

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language fr ja ko pt ru zh
/remove-sig release

**Pull request closed without merging**
