### PR TITLE
kubeadm: remove general output from "kubeadm init" 

### PR DESCRIPTION
**Pull request by neolit123**
Leave only the message:
  "Your Kubernetes control-plane has initialized..."
and the details bellow it.

/sig cluster-lifecycle

### CODE REVIEW

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/ could also use an update as part of this PR.

**Comment by sftim** [comment]
> https://github.com/kubernetes/website/pull/24907#issuecomment-725567369

Assuming that #24990 is OK, _this_ PR only needs to fix the label / taint details.

**Comment by neolit123** [comment]
@sftim @annajung 
in today's kubeadm meeting we decided that we should not add notes about the change in 1.20 on the kubeadm pages for "creating a cluster" or "implementation details".
the change should be made on a later stage.

but in the meantime we decided to update the page for "creating a cluster" to simplify the output a little.
so i'm going to retitle this PR, but you can remove it from feature tracking for 1.20 WRT linking to https://github.com/kubernetes/enhancements/issues/2067

**Comment by neolit123** [comment]
this was discussed during the last kubeadm office hours and we agreed that the change is desired.
ready for docs review.

**Comment by annajung** [comment]
page preview: https://5fb2e6e3152eec0007599863--kubernetes-io-vnext-staging.netlify.app/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

/lgtm

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
