### PR TITLE
NodeOutOfServiceVolumeDetach feature update to beta

### PR DESCRIPTION
**Pull request by YuikoTakada**
Upstream: https://github.com/kubernetes/kubernetes/pull/111380
KEP: https://github.com/kubernetes/enhancements/pull/3320

### CODE REVIEW

**Comment by xing-yang** [comment]
@YuikoTakada There are other places in the doc where we need to update the feature gate.  See this earlier doc PR: https://github.com/kubernetes/website/pull/32406

**Comment by YuikoTakada** [comment]
@xing-yang This file `content/en/docs/reference/command-line-tools-reference/feature-gates.md` also needs to be updated because the doc `content/en/docs/reference/labels-annotations-taints/_index.md` which has been updated by https://github.com/kubernetes/website/pull/32406 is about `taint` and this doesn't describe about that which k8s version `NodeOutOfServiceVolumeDetach` feature gate is enabled.

**Comment by xing-yang** [comment]
@YuikoTakada I assume you'll be updating the feature state status on this page as well?
https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown

**Comment by YuikoTakada** [comment]
@xing-yang Sorry, I misunderstood what you said. I updated `content/en/docs/concepts/architecture/nodes.md` also, PTAL.

**Comment by xing-yang** [comment]
/lgtm

@YuikoTakada Can you remove WIP?

**Comment by YuikoTakada** [comment]
> /lgtm
> 
> @YuikoTakada Can you remove WIP?

done. Thanks.

**Comment by tengqm** [comment]
/hold
This one should target `dev-1.26` branch rather than `main`.

**Comment by xing-yang** [comment]
/lgtm cancel
Please address this comment: https://github.com/kubernetes/website/pull/37374#issuecomment-1308785305

**Comment by YuikoTakada** [comment]
@tengqm @xing-yang Done, thanks.

**Comment by sftim** [comment]
Thanks

/approve

**Pull request merged**
