### PR TITLE
Adjusting Main README-pt.md

### PR DESCRIPTION
**Pull request by femrtnz**

### CODE REVIEW

**Comment by mistyhacks** [comment]
/unassign

This needs a reviewer who speaks Portuguese, I believe.

**Comment by devlware** [comment]
@jcjesus Can you take a look at this PR?

**Comment by femrtnz** [comment]
/assign @mistyhacks
Hi @mistyhacks, none of us Portuguese speakers are from `sig-docs-en` group.

As they already accepted my translation, can you approve this PR?

Thank you

**Pull request merged**
