### PR TITLE
Update Docsy to v0.2.0

### PR DESCRIPTION
**Pull request by sftim**
Bump and pin [Docsy](https://www.docsy.dev/) to its latest release, [v0.2.0](https://github.com/google/docsy/releases/tag/v0.2.0).

/area web-development

Looks to me like it previews OK. Notable features include a new localization (of Docsy) into Ukrainian, and 100% coverage for Russian.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by reylejano** [comment]
I'm neutral to bump Docsy to v0.2.0 before or after the v1.24 release
The v1.24 release is delayed to May 3 (from April 19)
@divya-mohan0209 @natalisucks @tengqm @kbhawkey , thoughts?

**Comment by divya-mohan0209** [comment]
I'd like to understand if there'd be any breaking changes we're subjecting the website to before commenting further @sftim ?

**Comment by sftim** [comment]
I'm neutral on it too. No breaking changes that I can see. I'd prefer to see a positive comment from the Release Docs team before going ahead, just in case this does add effort for the release-related changes.

**Comment by reylejano** [comment]
cc: @nate-double-u

**Comment by sftim** [comment]
/hold
Checking with Release Docs folks

Unhold if this is OK to go.

**Comment by nate-double-u** [comment]
I don't see any issues with this either, with the release postponed I'm fairly comfortable having this merged in beforehand. I'm planning on doing a maintenance PR for the release branch today--I can hold off on that till this is merged in.

/lgtm

**Pull request merged**
