### PR TITLE
Update container-environment.md with fix about service environment variables not being cluster-wide

### PR DESCRIPTION
**Pull request by MichaelWasher**
Update container-environment.md with mention that injected service list is limited to the current namespace

### CODE REVIEW

**Comment by MichaelWasher** [comment]
Fixes #26650

**Review by sftim — COMMENTED** [review]
Thanks @michaelwasher 

I've suggested another way to write it. We wouldn't accept using the term “master” to describe the Kubernetes control plane.

**Comment by MichaelWasher** [comment]
I have resolved this now. 

For reference the mistaken naming convention for master-services was taken from the below, incase these can be amended also: 
https://kubernetes.io/blog/2018/08/03/out-of-the-clouds-onto-the-ground-how-to-make-kubernetes-production-grade-anywhere/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

Let me know if there's anything further that you require to be changed.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-26652--kubernetes-io-master-staging.netlify.app/docs/concepts/containers/container-environment/#cluster-information

**Comment by kbhawkey** [comment]
👋 @MichaelWasher . Thanks for contributing!
/lgtm

**Review by sftim — COMMENTED** [review]
Oops, sorry about the missing suggestion.

/approve

**Pull request merged**
