### PR TITLE
Add system:cluster-autoscaler role

### PR DESCRIPTION
**Pull request by kgolab**
Accompanies [PR 64503](https://github.com/kubernetes/kubernetes/pull/64503) from kubernetes/kubernetes.

### CODE REVIEW

**Comment by liggitt** [comment]
/hold
this likely will end up as a role defined in the cluster autoscaler repo, not as a core bootstrap role

**Comment by zacharysarah** [comment]
@liggitt Should we keep this PR open or close it?

**Comment by liggitt** [comment]
> @liggitt Should we keep this PR open or close it?

let's close it. the corresponding PR is being reworked to make the role definition part of the addon/deployment, not a bootstrap role

/close

**Pull request closed without merging**
