### PR TITLE
internal-load-balancer section indentation alignment fix

### PR DESCRIPTION
**Pull request by Zeeshan50522**

### CODE REVIEW

**Comment by Zeeshan50522** [comment]
spaces was not align in 

[Default](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-0)
[GCP](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-1)
[AWS](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-2)
[Azure](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-3)
[IBM Cloud](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-4)
[OpenStack](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-5)
[Baidu Cloud](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-6)
[Tencent Cloud](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-7)
[Alibaba Cloud](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-8)
[OCI](https://kubernetes.io/docs/concepts/services-networking/service/#service-tabs-9) 

in section, with this fix all the spaces are align now

**Comment by ktvargo-ms** [comment]
LGTM

**Pull request merged**
