### PR TITLE
update default config for Openstack Cloud Controller Manager since v1.17.0 version release

### PR DESCRIPTION
**Pull request by vincenthcui**
update default config for OpenStack Cloud Controller Manager since v1.17.0 version release

OpenStack CCM change its default behavior since version 1.17.0 release, synchronously update
documents here avoid confusing and misunderstand.

### CODE REVIEW

**Comment by vincenthcui** [comment]
@chenrui333 @steveperry-53 would you like have a look here and review the changes, plz :)

**Comment by jimangel** [comment]
@vincenthcui would the change be better in parentheses instead of quoted reply (`>`) markdown? (or is below the intended change?)

image

**Comment by vincenthcui** [comment]
@jimangel sure, quoted reply looks not so much important, it has been removed now. thx.

**Comment by zacharysarah** [comment]
@vincenthcui 👋 Thanks for the update! In the future, please limit PRs to [one language per PR](https://kubernetes.io/docs/contribute/new-content/overview/#languages-per-pr).

/lgtm
/approve

**Pull request merged**
