### PR TITLE
content/docs,blog: fix deprecated links

### PR DESCRIPTION
**Pull request by jtagcat**
Docs were pointing to a deprecated link,
went ahead and followed the ambiguous redirects.

The blog entries could be left untouched, but it doesn't hurt, thus
while at it, updated links for related deprecations as well.

Reopen of #29820

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by jimangel** [comment]
@jtagcat are you still working on this? SIG Docs limits PRs to only a [single language localization](https://kubernetes.io/docs/contribute/new-content/#languages-per-pr) and almost never retroactively patch blog posts (unless extreme circumstances like security for example). I would recommend updating opening up a PR focusing on one language and removing the blog entries.

Given that this hasn't had a lot of action since 9/30/21, I'm going to close it, but feel free to open it with the above changes. Let me know if you have any questions! Thanks!

/close

**Pull request closed without merging**
