### PR TITLE
Update kops.md

### PR DESCRIPTION
**Pull request by vyask**
kops uses DNS for discovery, both inside the cluster and outside so that you can reach the kubernetes API server
from clients.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by bradtopol** [comment]
@vyask Thank you for your contribution. Please sign the CLA so we can accept your PR for review.

**Comment by vyask** [comment]
Hi,
I did sign CLA last week, either on Fri or Sat.
thanks
Vyas

**Comment by bradtopol** [comment]
@justinsb can you serve as the technical reviewer for this PR? Just add a /lgtm when you feel the PR is technically correct. Thanks
/cc @justinsb

**Comment by Rajakavitha1** [comment]
/assign @justinsb
Hi  @justinsb can you serve as the technical reviewer for this PR? Just add a /lgtm when you feel the PR is technically correct. Thanks

**Comment by Rajakavitha1** [comment]
/assign @sftim 
@sftim  can you serve as the technical reviewer for this PR? Just add a /lgtm when you feel the PR is technically correct.

**Pull request merged**
