### PR TITLE
fix example error when use kubectl get -f 

### LINKED ISSUE #25076: Issue with k8s.io/docs/reference/kubectl/overview/
Example: kubectl get pod -f ./pod.yaml
error: when paths, URLs, or stdin is provided as input, you may not specify resource arguments as well

The example should be "kubectl get  -f ./pod.yaml".

### PR DESCRIPTION
**Pull request by zhaojizhuang**
fix #25076
fix example error when use `kubectl get -f`

### CODE REVIEW

**Comment by zhaojizhuang** [comment]
area/kubectl

**Comment by zhaojizhuang** [comment]
cc @soltysh

**Review by AWKIF — APPROVED** [review]

**Review by soltysh — APPROVED** [review]
lgtm

**Comment by kbhawkey** [comment]
👋 @zhaojizhuang
You should limit changes in a pull request to one language.
Each localization team decides when and how to follow-up on any updates.

**Comment by zhaojizhuang** [comment]
> 👋 @zhaojizhuang
> You should limit changes in a pull request to one language.
> Each localization team decides when and how to follow-up on any updates.

@kbhawkey ok, then I change in en firstly

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-25113--kubernetes-io-master-staging.netlify.app/docs/reference/kubectl/overview/#syntax

**Comment by kbhawkey** [comment]
Thanks @zhaojizhuang !
/lgtm

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
