### PR TITLE
typo in StateFulSet docs

### PR DESCRIPTION
**Pull request by pnordahl**

### CODE REVIEW

**Comment by pnordahl** [comment]
check CLA

**Comment by pnordahl** [comment]
check CLA again

**Comment by tengqm** [comment]
LGTM. Please rebase to solve the conflicts.

**Comment by warmchang** [comment]
It seems that there is a problem with the rebase operation, introducing a lot of wrong commits.

@pnordahl Just fetch the latest upstream repo and rebase it again.

**Comment by pnordahl** [comment]
Not quite sure why; I just did a usual fetch and rebase. I think it might be easier to close this PR and make a fresh one off master.

Thoughts?

**Comment by pnordahl** [comment]
Yeah, this makes no sense. I'm closing and opening a new PR.

**Pull request closed without merging**
