### PR TITLE
update ol ul li bullet to disc

### PR DESCRIPTION
**Pull request by kbhawkey**
- update ol ul li bullet to disc
- move note out of list so that list numbers are correct
- fix typo

### CODE REVIEW

**Comment by kbhawkey** [comment]
@Bradamant3, would you look at line 473 in high-availability.md. I fixed the typo, but I am not sure if the join command is correct. Thanks.

**Comment by kbhawkey** [comment]
preview link:
https://deploy-preview-10714--kubernetes-io-master-staging.netlify.com/docs/setup/independent/high-availability/

**Comment by Rajakavitha1** [comment]
@kbhawkey could you please resolve the conflicts.

**Pull request merged**
