### PR TITLE
Add screenshot of GitHub showing link to Netlify preview

### PR DESCRIPTION
**Pull request by sftim**
Help reviewers understand where to see a preview for a pull request to this repo.

Update https://k8s.io/docs/contribute/review/reviewing-prs/ to show a screenshot of the part of the GitHub page that links to a Netlify preview.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-31053--kubernetes-io-main-staging.netlify.app/docs/contribute/review/reviewing-prs/#review-process

**Comment by chrisnegus** [comment]
I think this is ready to merge.
/cc @jimangel

**Comment by chrisnegus** [comment]
I think this is ready to merge.
/assign @jimangel

**Comment by kbhawkey** [comment]
Thanks @sftim .
/lgtm

**Pull request merged**
