### PR TITLE
Revise “Container runtimes” page in Getting Started section

### PR DESCRIPTION
**Pull request by sftim**
Revise https://kubernetes.io/docs/setup/production-environment/container-runtimes/:

- Reword page introduction;
   - remove feature-state shortcode, as Kubernetes' CRI support is now very much stable.
- Match headings to contents; before, headings were sometimes followed
  first by unrelated text and then, with no clear divider, text that did
  not relate to the heading..
- `apt` lets you write GPG keyrings into a file per trusted source, inside `/etc/apt/trusted.gpg.d`. Recommend that approach.
- List container runtimes in alphabetical order;
   - add warning about 3rd party content.
- Remove Fracti link (not in line with content guide).

### CODE REVIEW

**Comment by sftim** [comment]
3rd party warning might be relevant to issues such as #24658

**Review by irvifa — COMMENTED** [review]
/lgtm

**Comment by karras** [comment]
@irvifa @sftim If I am not mistaken this PR removed some previous content changes that fixed outdated instructions. For example the changes made in #24605 are no longer in the master version of this file. Were the changes in this PR maybe done against an older version and not `HEAD`, i.e. not rebased on master?

Let me know how to proceed, I can also create a PR to add #24605 again. :)

**Comment by sftim** [comment]
Ah, I think I missed a bit when fixing a merge conflict. Sorry about that. :facepalm: 

If fixing this, please consider also changing the fragment identifier for https://kubernetes.io/docs/setup/production-environment/container-runtimes/#systemd (eg to `#containerd-systemd`). I'll be happy to review.

**Comment by karras** [comment]
No worries, thanks for the fast reply. I'm on it and will also add some newer instructions for Ubuntu 18.04/20.04 in a separate PR. :)

**Comment by karras** [comment]
@sftim Done, see #24687

**Pull request merged**
