### PR TITLE
[ja] add searchbar to index page

### PR DESCRIPTION
**Pull request by Arhell**
/assign @t-inu
/assign @nasa9084

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The proposed change of adding searchbar looks in sync with main website ('en') [homepage](https://kubernetes.io/).
LGTM

[Preview Japanese Homepage](https://deploy-preview-43677--kubernetes-io-main-staging.netlify.app/ja/)

**Review by t-inu — COMMENTED** [review]
en PR https://github.com/kubernetes/website/pull/42299/files
/lgtm

**Review by kakts — APPROVED** [review]
LGTM

**Pull request merged**
