### PR TITLE
Promote SuspendJob to GA

### PR DESCRIPTION
**Pull request by tengqm**
xref: kubernetes/kubernetes#108129
KEP: https://github.com/kubernetes/enhancements/issues/2232

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
@tengqm planning to close this?

**Comment by tengqm** [comment]
> @tengqm planning to close this?

Either one can be closed. My PR contains some format tweaks, in addition to the main topic.

**Comment by reylejano** [comment]
Code PR in https://github.com/kubernetes/kubernetes/pull/108129 is merged
/approve

**Pull request merged**
