### PR TITLE
Add link to Scaleway CCM

### PR DESCRIPTION
**Pull request by jtherin**
Add link to Scaleway CCM

### CODE REVIEW

**Comment by zacharysarah** [comment]
@jtherin As of [today](https://github.com/kubernetes/enhancements/pull/1327), it's official that the docs disallow third-party vendor content. We'll be gradually working through all of the documentation, including these pages, to remove all vendor information.

On that basis, this PR is closed.

/close

**Comment by remyleone** [comment]
@zacharysarah Is this page concerned by this policy: https://github.com/kubernetes/website/pull/21206/files ?

**Comment by zacharysarah** [comment]
@remyleone Yes it is, good catch. I'll take action.

**Pull request closed without merging**
