### PR TITLE
Update generated reference API docs

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Update generated reference API docs with tag 1.19.0-rc.4

/hold

cc: @kbhawkey @tengqm @jimangel

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
@kbhawkey 👋 , do you know why the generated folder `static/docs/reference/generated/kubernetes-api/v/* ` does not have `v1.19` but has only `v` in the path? Is this because I used `rc` tag while generating the references?

**Comment by kbhawkey** [comment]
> 
> 
> @kbhawkey 👋 , do you know why the generated folder `static/docs/reference/generated/kubernetes-api/v/* ` does not have `v1.19` but has only `v` in the path? Is this because I used `rc` tag while generating the references?

Yes, I'll look. Did you run the script without changing the configuration (reference.yml)?

**Comment by savitharaghunathan** [comment]
> Yes, I'll look. Did you run the script without changing the configuration (reference.yml)?

I did. I just passed the version with the tag via the command line.
`python3 update-imported-docs.py reference.yml 1.19.0-rc.4` is the command I used.

**Comment by kbhawkey** [comment]
> > Yes, I'll look. Did you run the script without changing the configuration (reference.yml)?
> 
> I did. I just passed the version with the tag via the command line.
> `python3 update-imported-docs.py reference.yml 1.19.0-rc.4` is the command I used.

OK. I just ran the script with:
`python3 update-imported-docs.py reference.yml 1.19.0-rc.4`
and the directory was created.

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_generate-csr.md
	../content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_preflight.md
	../static/docs/reference/generated/kubernetes-api/v1.19/
```
Did you see any error/warning messages in the output when the `copyapi` target was run?

**Comment by savitharaghunathan** [comment]
> Did you see any error/warning messages in the output when the `copyapi` target was run?
> I guess the `APIDST` variable is not set correctly.

I am seeing the following error in my console i/o. Do I need to set `APIDST` somewhere?
``` Updating swagger.json for release v1.19.0-rc.4
cd /tmp/tmp_3999bm6/src/k8s.io/kubernetes && git show "v1.19.0-rc.4:api/openapi-spec/swagger.json" > /private/tmp/tmp_3999bm6/src/github.com/kubernetes-sigs/reference-docs/gen-apidocs/config/v/swagger.json
sudo rm -f main
Password:
sudo rm -rf /tmp/tmp_3999bm6/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/includes
sudo rm -rf /tmp/tmp_3999bm6/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/build
sudo rm -rf /tmp/tmp_3999bm6/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/manifest.json
cut: illegal option -- -
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...]
go run gen-kubectldocs/main.go --kubernetes-version v
Failed to read yaml file gen-kubectldocs/generators/v/toc.yaml: open gen-kubectldocs/generators/v/toc.yaml: no such file or directorypanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x23f05e9]

goroutine 1 [running]:
github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators.WriteCommandFiles.func1(0xc000132c90, 0x2c, 0x0, 0x0, 0x2a45720, 0xc000a8eff0, 0x2c, 0x1)
	/tmp/tmp_3999bm6/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/gen.go:186 +0x29
path/filepath.Walk(0xc000132c90, 0x2c, 0x2872bf0, 0xc000132c90, 0x2c)
	/usr/local/Cellar/go/1.14.5/libexec/src/path/filepath/path.go:404 +0x6a
github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators.WriteCommandFiles(0xc000a8b980, 0x0, 0x0, 0x0, 0xc000a8e2d0, 0x1, 0x1)
	/tmp/tmp_3999bm6/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/gen.go:185 +0x2c7
github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators.GenerateFiles()
	/tmp/tmp_3999bm6/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/gen.go:76 +0x3c5
main.main()
	/tmp/tmp_3999bm6/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/main.go:26 +0x75
exit status 2
make: *** [cli] Error 1
```

**Comment by kbhawkey** [comment]
Looks like you do not have the `cut` program

**Comment by savitharaghunathan** [comment]
> Looks like you do not have the `cut` program or have `cut` but the flags are different than the ones working for me (Ubuntu).

I am using macOS Catalina. 

> export K8S_RELEASE=1.19.0-rc.4
> `echo $K8S_RELEASE | cut --characters 1-4`

```echo $K8S_RELEASE | cut --characters 1-4
cut: illegal option -- -
usage: cut -b list [-n] [file ...]
       cut -c list [file ...]
       cut -f list [-s] [-d delim] [file ...] 
```
is what I get

**Comment by kbhawkey** [comment]
Does this work for you: `echo $K8S_RELEASE | cut -c 1-4`

**Comment by savitharaghunathan** [comment]
> echo $K8S_RELEASE | cut -c 1-4

That works. 
```
$ echo $K8S_RELEASE | cut -c 1-4
1.19
```

**Comment by kbhawkey** [comment]
Good. Updated the command, https://github.com/kubernetes-sigs/reference-docs/pull/170

**Comment by savitharaghunathan** [comment]
Thank you for the quick response and help, @kbhawkey :)

**Comment by savitharaghunathan** [comment]
@kbhawkey 👋  Thanks for all your help :) Folder structure and files look good to me now. PTAL when you are available for a quick review :)

**Comment by kbhawkey** [comment]
👀

**Comment by kbhawkey** [comment]
Hi @savitharaghunathan .
I looked at the pages.
Some of the non-generated kubeadm pages are not rendering correctly -- the pages (some or all) seem to be missing some front matter. Also, the main pages could use the `what's next` heading shortcode.
There is an  _index page in the `generated` directory; this directory is
showing as the first link on this page, https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/setup-tools/kubeadm/. This page previously used the `toc_hide` parameter.
So, these things should be fixed on the master branch. I can do this now?

Some Page previews:
https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.19/

https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/cloud-controller-manager/

https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/kube-apiserver/

https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/kube-proxy/

https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubectl/kubectl-commands

https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/kubectl/kubectl/

```
# verified links work from this page
```
https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubectl/kubectl-commands#get

https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-config/

https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase/
https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/setup-tools/kubeadm/

**Comment by savitharaghunathan** [comment]
Hi @kbhawkey 👋 So these changes needs to go into `master` first? Then I need to sync them to `dev-1.19` and update my local branch for this PR and re-generate the files?

**Comment by savitharaghunathan** [comment]
> Hi @savitharaghunathan .
> I looked at the pages.
> Some of the non-generated kubeadm pages are not rendering correctly -- the pages (some or all) seem to be missing some front matter. Also, the main pages could use the `what's next` heading shortcode.
> There is an _index page in the `generated` directory; this directory is
> showing as the first link on this page, https://deploy-preview-23018--kubernetes-io-vnext-staging.netlify.app/docs/reference/setup-tools/kubeadm/. This page previously used the `toc_hide` parameter.
> So, these things should be fixed on the master branch. I can do this now?
Yes, please. Can I help in any way?

**Comment by kbhawkey** [comment]
See #23048 .


> 
> 
> Hi @kbhawkey 👋 So these changes needs to go into `master` first? Then I need to sync them to `dev-1.19` and update my local branch for this PR and re-generate the files?

Yes, the changes should go into master and then sync the changes to the `dev-1.19` branch. No, the files are **not** generated.

I noticed that some of the kubeadm pages display generated content in the tabs component. The font sizing seems odd, though, probably related to styling of tab.
Also, I think there is a missing newline after the `Options` section and before the `Options inherited from parents command` heading. This can be fixed easily before the release.

**Comment by savitharaghunathan** [comment]
> See #23048 .
> 
> > Hi @kbhawkey 👋 So these changes needs to go into `master` first? Then I need to sync them to `dev-1.19` and update my local branch for this PR and re-generate the files?
> 
> Yes, the changes should go into master and then sync the changes to the `dev-1.19` branch. No, the files are **not** generated.
>
Okay. Thank you for the clarification :) 
> I noticed that some of the kubeadm pages display generated content in the tabs component. The font sizing seems odd, though, probably related to styling of tab.
> Also, I think there is a missing newline after the `Options` section and before the `Options inherited from parents command` heading. This can be fixed easily before the release.

I will make a note to fix this before the release.

**Comment by savitharaghunathan** [comment]
Hi @kbhawkey 👋 , I synced the changes from the primary branch into dev-1.19 and updated this PR. PTAL. Thanks

**Comment by kbhawkey** [comment]
:eyes:

**Comment by kbhawkey** [comment]
Hi @savitharaghunathan .The changes look good.
Note: The table of contents (right hand list of links) does not display for most of the component tool pages.
This is not a problem with the generated pages. I have logged an [issue](https://github.com/kubernetes/website/issues/23132) and will follow-up on it.
Thanks! :tada:

**Comment by savitharaghunathan** [comment]
@kbhawkey Thanks for taking another look at the PR :) I think this is ready for review now. If you think its all good, can you review it, please? 

/hold cancel

**Comment by kbhawkey** [comment]
Hi @savitharaghunathan .
Sure, do you want these changes to merge now and then update if another release candidate is created?
/lgtm

**Comment by savitharaghunathan** [comment]
> Hi @savitharaghunathan .
> Sure, do you want these changes to merge now and then update if another release candidate is created?
@kbhawkey That sounds good to me. Can you approve? Thanks!

**Pull request merged**
