### PR TITLE
added community page in hindi language

### PR DESCRIPTION
**Pull request by harish343**
New feature has been added communtiy page in hindi please review it and ping me if any changes had to be made on this repository

### CODE REVIEW

**Comment by Babapool** [comment]
Hi @harish343 , can you please sign the CLA before your PR is reviewed.

On steps to sign the CLA please visit/see: https://github.com/kubernetes/community/blob/master/CLA.md

Thanks.

**Comment by harish343** [comment]
> 
I sucessfully sign up with cla but still missing id on commit.
clf

**Pull request closed without merging**
