### PR TITLE
Fix Typo in the deprecation warning

### LINKED ISSUE #13460: Typo in the deprecation warning
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

There's a typo in the deprecation warning:

Screen Shot 2019-03-26 at 12 49 16 PM

**Proposed Solution:**

1. Update the deprecation warning text so that it ends, `"see the "`.
    - Fix this line: https://github.com/kubernetes/website/blob/master/i18n/en.toml#L4
2. Notify localization stakeholders in the PR.
    - In the initial PR description, add mentions to `sig-docs-**-owners` for every current localization.

**Page to Update:**

https://github.com/kubernetes/website/blob/master/i18n/en.toml#L4

### PR DESCRIPTION
**Pull request by anshulahuja98**
Fixes #13460

### CODE REVIEW

**Comment by anshulahuja98** [comment]
I signed it

**Comment by anshulahuja98** [comment]
@tengqm I can't understand why these checks are failing?

**Comment by xiangpengzhao** [comment]
/lgtm
Thanks @anshulahuja98

**Comment by tfogo** [comment]
/approve
Thank you @anshulahuja98

**Comment by tengqm** [comment]
@anshulahuja98 Can you help rebase this one to the current master? It looks like we are hitting some transient issues in the "master" you used.

**Pull request merged**
