### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by grant-he**

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@grant-he Thanks for the contribution. 

Since we try to follow the [Trivial Edits guidelines](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) as much as we can, I kindly ask you also look for further improvement in same page so that one PR can cover more improvements. For eg. fixing other Grammatical errors or correcting broken links etc.

**Review by nate-double-u — COMMENTED** [review]
Hi @grant-he, I agree with @dipesh-rawat's comment about trivial edits, please take some time to see if there is anything else you can help fix on this page.

Since this is your first PR, welcome! I'd also invite you to read "[Do you want to start contributing to open source and need help figuring out where to begin?](https://contribute.cncf.io/contributors/getting-started/)" as it's got a lot of good resources for someone starting out in open source.

**Comment by grant-he** [comment]
Thanks for the warm welcome. Excited to contribute more! I have gone through the doc to spruce it up.

**Comment by kbhawkey** [comment]
Thanks @grant-he .

/approve

**Pull request merged**
