### PR TITLE
Align pre-footer with Proper Spacing

### LINKED ISSUE #9719: Misaligned pre-footer (Create an issue, Edit this page, commit history section)
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The pre footer is not aligned correctly, it should be in the centre or at least have some spacing from left and bottom.

screenshot from 2018-08-02 10-56-18

**Proposed Solution:**
To have some proper CSS which is missing?

**Page to Affected:**
Almost all the sections,
example:
https://kubernetes.io/docs/concepts/

### PR DESCRIPTION
**Pull request by akshay196**
Fixes #9719
Add proper spacing from left and bottom for pre-footer.

Signed-off-by: Akshay Gaikwad <akgaikwad001@gmail.com>

### CODE REVIEW

**Comment by mistyhacks** [comment]
In your preview, I don't see what visually changed: https://deploy-preview-9766--kubernetes-io-master-staging.netlify.com/docs/test/

**Comment by akshay196** [comment]
I can see the change on my local server. I am running hugo version `0.46`. I see that there are auto generated changes in following files when I start hugo server:
```
resources/_gen/assets/sass/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.content
resources/_gen/assets/sass/sass/styles.sass_cb957da2191fde4902dd41b139c8069d.json
``` 
Do I need to push these files as well?

**Comment by zparnold** [comment]
@akshay196 I don't think you'd need to push those files, since browsers don't use them to render CSS (unless something I don't know about has changed.) @mistyhacks mayhaps you have a browser cache to invalidate? I know that gets me like all the time on frontend dev.

**Comment by akshay196** [comment]
@mistyhacks @zacharysarah We can now see changes in the preview. :smiley:

**Comment by cody-clark** [comment]
Thanks so much for following up, @akshay196; the new padding looks great! 

It's a super nit, but could you possibly align the pre-footer with the main body content or the left edge of the Twitter icon? Right now, it's just floating between the left nav and main content area.

screencapture-deploy-preview-9766-kubernetes-io-master-staging-netlify-docs-tasks-tools-install-minikube-2018-11-08-14_40_35

**Comment by akshay196** [comment]
@cody-clark Thanks for suggestion. PR is now update to align pre-footer with the content of doc.

**Comment by mistyhacks** [comment]
Sorry for the merry-go-round, but please rebase to fix the conflict. 👼

**Comment by zacharysarah** [comment]
@akshay196 Please feel free to re-open when you're ready to rebase. We're ready to act quickly to prevent any further merge conflicts. Thanks in advance for your patience!

**Pull request closed without merging**
