### PR TITLE
kubeadm-alpha: remove redundant list of links

### PR DESCRIPTION
**Pull request by angao**
- hugo markdown engine can auto generate catalog rather than manually generated

### CODE REVIEW

**Comment by angao** [comment]
compare the follow link:
- [fix version](https://deploy-preview-8793--kubernetes-io-master-staging.netlify.com/docs/reference/setup-tools/kubeadm/kubeadm-alpha/)
- [office website](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/)

**Comment by neolit123** [comment]
/lgtm

it does seem like the list of links (catalogue) is auto-generated and redundant for such pages.
thanks for the change.

**Comment by neolit123** [comment]
i would change the commit message and the title of this PR, though:
`Fix catalog: the catalog is repeat`
to something like:
`kubeadm-alpha: remove redundant list of links`

**Comment by angao** [comment]
ok, i will do it

**Comment by angao** [comment]
@neolit123 please check it, thanks!

**Comment by neolit123** [comment]
/lgtm

thanks!

**Pull request merged**
