### PR TITLE
Added source location for kube-up.sh

### PR DESCRIPTION
**Pull request by hpandeycodeit**
https://kubernetes.io/docs/tasks/tools/install-kubectl/#verifying-kubectl-configuration

In the above section, `kube-up.sh` doesn't have any reference to the source file. Added the github location for this file.

### CODE REVIEW

**Comment by raelga** [comment]
Thanks @hpandeycodeit!

/lgtm
/approve

**Comment by raelga** [comment]
@remyleone Can you check the french content?

**Comment by remyleone** [comment]
@raelga LGTM

**Comment by zparnold** [comment]
/approve
(from the EN side)

**Pull request merged**
