### PR TITLE
[zh] Update quota-memory-cpu-namespace.md

### PR DESCRIPTION
**Pull request by yinyanlu**
只改之

### CODE REVIEW

**Comment by yinyanlu** [comment]
cla 已签署

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/website/pull/30687#issuecomment-982304402

**Comment by jimangel** [comment]
Hey there! @yinyanlu, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
@yinyanlu You may want to try commit this again using the email you used for CLA. CLA check still fails atm.

**Comment by annajung** [comment]
closing the PR as the author has [not signed the CLA for two weeks](https://kubernetes.io/docs/contribute/participate/pr-wranglers/#when-to-close-pull-requests).
Please feel free to reopen after signing the CLA.

/close

**Pull request closed without merging**
