### PR TITLE
Fix note shortcodes in Deployment concept

### PR DESCRIPTION
**Pull request by sftim**
Similar to fixes in PR #20903

Revise https://k8s.io/docs/concepts/workloads/controllers/deployment/ [[preview](https://deploy-preview-20920--kubernetes-io-master-staging.netlify.app/docs/concepts/workloads/controllers/deployment/)] to render note shortcodes and code blocks as expected.

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Fix note shortcodes in Deployment concept

This *isn't* perfect, but I think it makes the page less broken than it was.

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/pull/19907

**Comment by sftim** [comment]
Potentially a partial fix for #20912

**Comment by zacharysarah** [comment]
@sftim Nice! ✨ I appreciate upgrading a note to a caution. 

/lgtm
/approve

**Pull request merged**
