### PR TITLE
[zh-cn] Update common-parameters.md

### PR DESCRIPTION
**Pull request by Yanping-io**
image

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
Good catch.

While checked the [en history](https://github.com/kubernetes/website/commits/main/content/en/docs/reference/kubernetes-api/common-parameters/common-parameters.md), [some content is insynced](https://github.com/kubernetes/website/commit/7b39e9a9ec5bbb6aa89fb50c25aec3f394366393#diff-e082b80a203a67c71427bd433397284946dc9271c6887e1b0c720066984f209f) with en upstream, would you like to include those content into this PR?

**Comment by Yanping-io** [comment]
> Good catch.
> 
> While checked the [en history](https://github.com/kubernetes/website/commits/main/content/en/docs/reference/kubernetes-api/common-parameters/common-parameters.md), [some content is insynced](https://github.com/kubernetes/website/commit/7b39e9a9ec5bbb6aa89fb50c25aec3f394366393#diff-e082b80a203a67c71427bd433397284946dc9271c6887e1b0c720066984f209f) with en upstream, would you like to include those content into this PR?

I checked the en content and found that the current content is synchronized with the en content. What should I do?

**Comment by Yanping-io** [comment]
Thanks for your help. I found some differences in format, but the content is consistent between en and zh. Perhaps I missed something.

**Review by windsonsea — APPROVED** [review]
Thanks.
/lgtm

**Pull request merged**
