### PR TITLE
Code snippets shouldn't include the command prompt

### PR DESCRIPTION
**Pull request by iamneha**
Fixes:  #12739 
Code snippets shouldn't include the command prompt and Separate commands from output
I'm using [this](https://kubernetes.io/docs/contribute/style/style-guide/#code-snippet-formatting) guide for code snippet formatting and separate commands from output

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Hi @iamneha , @DanyC97 , @sftim  The best approach would be to first create a PR with the details and guidelines in the [style guide](https://kubernetes.io/docs/contribute/style/style-guide/#code-snippet-formatting)

**Comment by Rajakavitha1** [comment]
@iamneha I am closing this PR for now. After the guidelines are approved in the Style Guide please feel free to open this PR.

**Comment by zacharysarah** [comment]
@Rajakavitha1 Out of curiosity, what are the missing style guidelines that should be addressed first? For context, see #12739 and the [current style guide](https://kubernetes.io/docs/contribute/style/style-guide/#don-t-include-the-command-prompt) for command prompts.

This PR looks like a work in progress (there are more files to fix before this PR truly "fixes" the list in https://github.com/kubernetes/website/issues/12739#issuecomment-465593264), so I'd like to reopen it.

**Comment by Rajakavitha1** [comment]
> 
> 
> @Rajakavitha1 Out of curiosity, what are the missing style guidelines that should be addressed first? For context, see #12739 and the [current style guide](https://kubernetes.io/docs/contribute/style/style-guide/#don-t-include-the-command-prompt) for command prompts.
> 
> This PR looks like a work in progress (there are more files to fix before this PR truly "fixes" the list in [#12739 (comment)](https://github.com/kubernetes/website/issues/12739#issuecomment-465593264)), so I'd like to reopen it.

@zacharysarah  based on the discussion between @iamneha @DanyC97 and @sftim in https://github.com/kubernetes/website/issues/12739 my understanding was they they had to coordinate before picking on the pages they wanted to fix. Also because we were awaiting a conclusion on the discussion in https://github.com/kubernetes/website/pull/12783 so that all are clear about the guidelines before making the fixes.

**Comment by zacharysarah** [comment]
@Rajakavitha1 That makes sense. Thanks for providing clarity. 🙇

Closing.

**Comment by iamneha** [comment]
@Rajakavitha1 @zacharysarah as per the discussion on the issue #12739 
I reopened this PR and pushed the rest of the changes.
Please review it

**Comment by DanyC97** [comment]
@iamneha fyi i already created a PR yesterday which does the same thing https://github.com/kubernetes/website/pull/12901 on entire code base

is waiting for final review / approve from a core reviewer 

so maybe you want to close this one and we keep the effort in the other PR ?

**Comment by iamneha** [comment]
@DanyC97 I really like the effort you put.
As I remember the issue is assigned to me and I started this PR the day it is assigned to me.
I am not sure what confusion happened here and as per the discussion this PR was closed because we were awaiting a conclusion on the discussion in #12783 

Let @zacharysarah @Rajakavitha1 @sftim decide what should be done here now.

**Comment by DanyC97** [comment]
no need for an arbiter @iamneha , closed mine in favor of yours, hopefully it will get in soon

**Comment by zacharysarah** [comment]
@iamneha Good work. ✨ 

/lgtm
/approve

**Pull request merged**
