### PR TITLE
fix the yaml link in high-availability

### LINKED ISSUE #8637: Issue with k8s.io/docs/admin/high-availability/building/
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
The links below of yaml files are not valid: go the message "404 Page not found":
- etcd.yaml: https://kubernetes.io/docs/admin/high-availability/etcd.yaml
- kube-apiserver.yaml : https://kubernetes.io/docs/admin/high-availability/kube-apiserver.yaml
- kube-scheduler.yaml: https://kubernetes.io/docs/admin/high-availability/kube-scheduler.yaml
- kube-controller-manager.yaml: https://kubernetes.io/docs/admin/high-availability/kube-controller-manager.yaml
**Proposed Solution:**
put a valid links of the yaml files

**Page to Update:**
https://kubernetes.io/docs/admin/high-availability/building/

1.10

### LINKED ISSUE #8677: Issue with k8s.io/docs/admin/high-availability/building/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The links under section "Master elected components", to kube-scheduler.yaml and kube-controller-manager.yaml are hitting 404.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/admin/high-availability/building/

### PR DESCRIPTION
**Pull request by xlgao-zju**
Fix the broken yaml link in https://kubernetes.io/docs/admin/high-availability/building/

close #8637 
close #8677
Signed-off-by: Xianglin Gao <xianglin.gxl@alibaba-inc.com>

### CODE REVIEW

**Comment by Bradamant3** [comment]
This PR should be against the master branch, not the 1.10 branch. But this content also looks to be seriously out of date. It isn't included in any content structure that appears in the TOC because we're assessing the state of stale content.

@rdodev wdyt of yanking this page altogether?

**Comment by Bradamant3** [comment]
/hold

pending discussion about whether we should even keep this content.

**Comment by xlgao-zju** [comment]
@mistyhacks PTAL

**Comment by rdodev** [comment]
Sorry @Bradamant3 apparently I wasn't in the repo when you tagged me. I'll 👀 now.

**Comment by rdodev** [comment]
FWIW, this looks like it's one of the older pages in the site and don't think adds any new information. Feels like just one more guide on the same topic other guides cover that can confuse users. Would support pruning/culling.

**Comment by mistyhacks** [comment]
Looks like this is still against the wrong branch. Also please address the other feedback. Putting a hold on this until it is based against the correct branch so it doesn't get in by mistake.

/hold

**Comment by xlgao-zju** [comment]
In favor of #8769. And we can discuss this there.

**Pull request closed without merging**
