### PR TITLE
Merged main dev 1.23

### PR DESCRIPTION
**Pull request by jlbutler**
Merge main back to the dev-1.23 integration branch.

### CODE REVIEW

**Comment by sftim** [comment]
/approve

We do want this!

**Comment by jlbutler** [comment]
Only question I had was around some explicit references to K8s version in `tasks/configure-pod-container/create-hostprocess-pod.md`. Passages on `main` referred to 1.22, and in `dev-1.23` they rightly refer to 1.23. Taking the forward diff, this will result in the `release-1.22` branch docs referring to 1.23.

Is that correct? This can't be the only place, but was the only conflict so far that brought it to my attention.

**Comment by sftim** [comment]
We should cut the `release-1.22` branch from `main` at the point just before we merge `dev-1.23` into `main`. That ought to be fine.

**Pull request merged**
