### PR TITLE
Update persistent-volumes.md

### PR DESCRIPTION
**Pull request by kvsl0**

### CODE REVIEW

**Comment by harshitasao** [comment]
Please sign the CLA

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by utkarsh-singh1** [comment]
Hi @pieterdd, You can find about EasyCLA here - https://docs.linuxfoundation.org/lfx/easycla

and the steps to sign EasyCLA are here - https://docs.linuxfoundation.org/v2/easycla/contributors/individual-contributor

You can start your signing EasyCLA from here - https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38056/#/?version=2

**Comment by utkarsh-singh1** [comment]
Related doc - https://kubernetes.io/zh-cn/docs/concepts/storage/persistent-volumes/

**Comment by tengqm** [comment]
CLA not signed and the author is not responding to signing requests.
/close

**Pull request closed without merging**
