### PR TITLE
Clarify sentence

### PR DESCRIPTION
**Pull request by network-charles**
This PR improves the existing sentence for clarity.

### CODE REVIEW

**Comment by stmcginnis** [comment]
That does read better.

/lgtm

**Comment by Ritikaa96** [comment]
Hi @network-charles , considering our  [Trivial changes](https://kubernetes.io/docs/contribute/review/reviewing-prs/#other) policy ,  please check this page for other improvements so that more changes can be added.

**Comment by network-charles** [comment]
Ah, I see, @Ritikaa96. Thanks, I'll review other parts of the document.

**Review by nate-double-u — COMMENTED** [review]
Thanks for this @network-charles!

/approve

**Pull request merged**
