### PR TITLE
Replace redirect links of install kubectl

### PR DESCRIPTION
**Pull request by atoato88**
`/docs/tasks/tools/install-kubectl/` is redirected to `/docs/tasks/tools/` set at [here](https://github.com/kubernetes/website/blob/master/static/_redirects#L279)
This PR replaces the redirect links for installing kubectl with direct links.

### CODE REVIEW

**Comment by atoato88** [comment]
/assign @kbhawkey
Could you review this?

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-27055--kubernetes-io-master-staging.netlify.app/docs/tasks/tools/

**Comment by YuikoTakada** [comment]
Thank you for your PR. Looks good to me.

**Comment by atoato88** [comment]
Thank you for quick response! :smile:

**Pull request merged**
