### PR TITLE
Fixes a small typo in topology aware hints page

### PR DESCRIPTION
**Pull request by kenaniah**

### CODE REVIEW

**Comment by kenaniah** [comment]
CLA signed

**Comment by robscott** [comment]
Thanks @kenaniah! This LGTM once you're able to get the CLA check to pass.

**Comment by kenaniah** [comment]
I signed it

**Comment by jimangel** [comment]
Hey there! @kenaniah, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
