### PR TITLE
Expand glossary entry for Container

### LINKED ISSUE #37428: Add Abbreviation for "containerized applications" in Glossary page and provide Hyperlink for the same in Components page.
**This is a Feature Request**

**What would you like to be added**

Add Abbreviation of **`containerized applications`** in [Glossary](https://kubernetes.io/docs/reference/glossary/?all=true#) as this word mentioned in [Components](https://kubernetes.io/docs/concepts/overview/components/). 

**Why is this needed**
This change will help to understand about **containerized applications** for the people who are unfamiliar with `container concepts`.

**Comments**
kind/feature

### PR DESCRIPTION
**Pull request by T-Lakshmi**
Fixes #37428 

Added about "containerization" and "containerized applications" under term "container" in Glossary page.

### CODE REVIEW

**Comment by T-Lakshmi** [comment]
Hi @reylejano ,
Thanks for your suggestion.
Updated the container term with your suggestion applying.

**Comment by T-Lakshmi** [comment]
Hi @reylejano ,
Can you please take a look into updated commit.

**Comment by sftim** [comment]
This PR implements the change that https://github.com/kubernetes/website/issues/37428 calls for. Should we make the change? I've added a [comment ](https://github.com/kubernetes/website/issues/37428#issuecomment-1318181440)to ask that we check that SIG Docs is happy with the intent here.

/lgtm

/hold
OK to unhold once issue 37428 is triaged accepted.

**Comment by reylejano** [comment]
/approve
Issue https://github.com/kubernetes/website/issues/37428 has `triage/accepted`
/unhold

**Pull request merged**
