### PR TITLE
[zh] concept of owners and dependents

### LINKED ISSUE #30036: [zh] translate concept Owners and Dependents
doc: https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/

### PR DESCRIPTION
**Pull request by mayocream**
Fix #30036

### CODE REVIEW

**Comment by mayocream** [comment]
Preview: https://deploy-preview-30325--kubernetes-io-main-staging.netlify.app/zh/docs/concepts/overview/working-with-objects/owners-dependents/

**Comment by tengqm** [comment]
This is a beautiful translation.  Thanks.
/approve

**Pull request merged**
