### PR TITLE
[hi] Translate English link text

### LINKED ISSUE #35929: [hi] Translate "version skew policy"
Some minor instances of English words showing up in Hindi translation https://github.com/kubernetes/website/pull/29679#issuecomment-1210551182

### PR DESCRIPTION
**Pull request by rolfedh**
Fixes #35929

### CODE REVIEW

**Comment by Babapool** [comment]
I believe that `Version skew policy` can better be translated to `संस्करण की स्क्यू नीति` . Thoughts @divya-mohan0209 @anubha-v-ardhan @Garima-Negi @verma-kunal ? Thanks

**Comment by rolfedh** [comment]
> I believe that `Version skew policy` can better be translated to `संस्करण की स्क्यू नीति` . Thoughts @divya-mohan0209 @anubha-v-ardhan @Garima-Negi @verma-kunal ? Thanks

Thanks for the suggestion, @Babapool. I've updated the PR accordingly. Would appreciate your review and approval, @divya-mohan0209 @anubha-v-ardhan @Garima-Negi @verma-kunal ?

**Comment by Babapool** [comment]
@rolfedh : The changes LGTM as of now (I am not a official `hi` localization approver/reviewer). Thanks

**Review by anubha-v-ardhan — APPROVED** [review]
/lgtm
/approve
/assign
Thank you @rolfedh :)

**Pull request merged**
