### PR TITLE
Fix k8s logo in Blog

### LINKED ISSUE #9112: Kubernetes logo disappears in Blog
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Kubernetes' logo disappears in Blog after scrolling down

**Proposed Solution:**
Changes in CSS

**Page to Update:**
https://kubernetes.io/blog/

### PR DESCRIPTION
**Pull request by chandankumar4**
- Modify `style.css` and add `id` for Blog
- fixes #9112 

Signed-off-by: chandan kumar <chandan.kr404@gmail.com>

### CODE REVIEW

**Comment by stewart-yu** [comment]
where it have a effect on?

**Comment by chandankumar4** [comment]
@stewart-yu It's affect on kubernetes blog logo after scrolling (https://kubernetes.io/blog/)

**Comment by zacharysarah** [comment]
@chandankumar4 Thanks for the fix.

/lgtm
/approve

**Pull request merged**
