### PR TITLE
added shortcode 

### LINKED ISSUE #42348: Restrict a Container: Example section — incorrect code separation
> https://kubernetes.io/docs/tutorials/security/apparmor/#example
> 
> ```bash
> kubectl create -f /dev/stdin <<EOF
> ```
> 
> ```yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   name: hello-apparmor-2
>   annotations:
>     container.apparmor.security.beta.kubernetes.io/hello: localhost/k8s-apparmor-example-allow-write
> spec:
>   containers:
>   - name: hello
>     image: busybox:1.28
>     command: [ "sh", "-c", "echo 'Hello AppArmor!' && sleep 1h" ]
> EOF
> pod/hello-apparmor-2 created
> ```

<br>

The code block is split into two blocks, but it is a single command and so it should be written as one code block like this:

```bash
kubectl create -f /dev/stdin <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: hello-apparmor-2
  annotations:
    container.apparmor.security.beta.kubernetes.io/hello: localhost/k8s-apparmor-example-allow-write
spec:
  containers:
  - name: hello
    image: busybox:1.28
    command: [ "sh", "-c", "echo 'Hello AppArmor!' && sleep 1h" ]
EOF
```

Output:
```bash
pod/hello-apparmor-2 created
```

### PR DESCRIPTION
**Pull request by deepak4566**
fixes  #42348

### CODE REVIEW

**Comment by tengqm** [comment]
@deepak4566 You have to understand how the `code` is used and where the snippets are supposed to be placed to be able to make such a PR.

**Review by dipesh-rawat — COMMENTED** [review]
@deepak4566 Thank you for your contribution! The current implementation does not look right; I recommend reading the documentation ([link](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#source-code-files:~:text=containerPort%3A%2080-,When,-adding%20a%20new)) for guidance on properly utilizing the `code` shortcode to embed file contents.

**Comment by tengqm** [comment]
/close
This PR doesn't make sense: incorrect use of `code` snippet, incorrect placement of the sample YAML etc. It provides no value.

**Pull request closed without merging**
