### PR TITLE
Add content/hi/docs/concepts/_index.md

### PR DESCRIPTION
**Pull request by nikhilchauhangithub**

### CODE REVIEW

**Comment by nikhilchauhangithub** [comment]
@anubha-v-ardhan Kindly look into it

**Comment by vaibhav2107** [comment]
The PR #39569 is also referencing the same issue

**Comment by vaibhav2107** [comment]
Ref: #39568

**Comment by anubha-v-ardhan** [comment]
/close

duplicate, PR #39569 is already open for the same.

**Pull request closed without merging**
