### PR TITLE
[zh] 1.27 resync page kube-controller-manager

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
This PR resyncs page `content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md`.

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
Sorry.
Fixes coming in. 
https://github.com/kubernetes/website/pull/41213

**Comment by Zhuzhenghao** [comment]
Got it.

**Comment by Zhuzhenghao** [comment]
> /hold Sorry. Fixes coming in. #41213

The fix is in page `content/en/docs/reference/config-api/kube-controller-manager-config.v1alpha1.md`,

and I sync page `content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md`.

/unhold

**Pull request merged**
