### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by yanghaichao12**

### CODE REVIEW

**Comment by stewart-yu** [comment]
IMO， this file are auto-generated

**Comment by yanghaichao12** [comment]
@stewart-yu hi， is it correct？i'm little confused now.....

**Comment by tengqm** [comment]
This file is auto generated. Please fix it in the upstream source code.

**Comment by yanghaichao12** [comment]
@tengqm hi， how to figure out which one is auto generated？

**Comment by yanghaichao12** [comment]
@tengqm i really don't know which one is  auto generated. could you help?

**Comment by tengqm** [comment]
@yanghaichao12 Files auto-generated can be found in the 'https://github.com/kubernetes/website/tree/master/update-imported-docs' directory.

BTW, I have noticed that you are passionate in contributing to k8s docs, however your contributions so far have mostly been on typo fixes: https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Ayanghaichao12

Please try propose something more useful if you can. Typo fixes are always welcomed, but:

- when you are contributing typo fixes only, all the time, there could be something wrong as I see it;
- as also can be seen from the PRs, you are not a native speaker so you made quite a few mistakes in some PRs by fixing something not supposed to be changed;
- higher commit numbers mean nothing, but valuable commits do mean a lot, ... please stop attempting to make this a game.

**Comment by yanghaichao12** [comment]
@tengqm  i'll try to contribute something more useful as you say. thanks for your suggestion

**Pull request closed without merging**
