### PR TITLE
Correct description of Knitter CNI plugin

### PR DESCRIPTION
**Pull request by sammcj**
The existing description of Knitter didn't make sense.

Replaced with [upstream](https://github.com/ZTE/Knitter/) description.

### CODE REVIEW

**Comment by sammcj** [comment]
CLA signed.

**Comment by sftim** [comment]
/check-cla

If Prow (the CI tool for this repository) doesn't see things as OK, @sammcj, feel free to ask for advice.

**Comment by sammcj** [comment]
Hmm, re-signed up lets see if that fixes it...

/check-cla

**Comment by sammcj** [comment]
Looks like commenting with /check-cla didn't trigger another CI run.

**Comment by sftim** [comment]
@sammcj you're confident that the CLA is signed with the email address that GitHub lists for you?

**Comment by sammcj** [comment]
@sftim indeed, I just went through the process again (did the esign etc...) and got the conformation email.

screenshot 2020-02-06 at 10 21 11 am

**Pull request merged**
