### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@fujitsu.com>

### CODE REVIEW

**Comment by reylejano** [comment]
We typically don't update blogs over a year old. This PR fixes typos and misspelling in a number of blog articles, I'll lgtm for now and request a blog approver to review
/lgtm

@kubernetes/sig-docs-blog-owners , please take a look

**Comment by reylejano** [comment]
@fenggw-fnst , the build failed
You can push an empty commit to restart the build

**Comment by nate-double-u** [comment]
> We typically don't update blogs over a year old. This PR fixes typos and misspelling in a number of blog articles, I'll lgtm for now and request a blog approver to review /lgtm

In this case, these corrections are good ones. I think if we didn't approve them at some point, someone else would go through the trouble of making these corrections again - despite our policy of not updating blog entries older than a year old. I'm inclined to approve this PR if @fenggw-fnst can restart the build with an empty commit.

**Review by Arhell — COMMENTED** [review]
/retest

**Comment by fenggw-fnst** [comment]
Understood. Thanks for the review!

**Pull request merged**
