### PR TITLE
Fix the codenew shortcode where site.Params.githubWebRow is null

### PR DESCRIPTION
**Pull request by DanyC97**
Fixes https://github.com/kubernetes/website/issues/12639

### CODE REVIEW

**Comment by DanyC97** [comment]
@tengqm fyi

**Comment by DanyC97** [comment]
@tengqm does this need to be cherry picked into 1.13 branch too? 
Or that is not required ? (still getting my head around, so excuse my silly question)

**Comment by tengqm** [comment]
@DanyC97 Cherrypick to 1.13 should be desirable since it is a bug fix.

**Pull request merged**
