### PR TITLE
 [hi] docs/concepts/architecture/leases.md

### PR DESCRIPTION
**Pull request by KumareshSingha97**
hello!

 I have changed the `docs/concepts/architecture/leases.md` page from English to Hindi.

preview : [`docs/concepts/architecture/leases.md`](https://deploy-preview-39026--kubernetes-io-main-staging.netlify.app/hi/docs/concepts/architecture/leases/)

### CODE REVIEW

**Comment by reveurguy** [comment]
Things to do before passing this PR for a review:
- Sign the CLA

Putting this PR on hold. Feel free to unhold once you're done signing the CLA.
/hold

**Comment by KumareshSingha97** [comment]
Hi @reveurguy can you help to solve this issue. this is my forth time but I don't
know how sign cla please help sir..

**Comment by bishal7679** [comment]
Hey @KumareshSingha97 cla means contributor license agreement which u have to sign first in order to contribute to k8s. So you just click the above lfx cla red marked link and follow all the process there and sign successfully! Then this issue will be resolved!!!

**Comment by reveurguy** [comment]
@KumareshSingha97 yeah just like @bishal7679 mentioned.

**Comment by KumareshSingha97** [comment]
@bishal7679 sir, there is two option one is individual contributor and another is corporate  contributor,So what should i choose.

**Comment by reveurguy** [comment]
@KumareshSingha97 individual contributor

**Comment by reveurguy** [comment]
@KumareshSingha97 you can refer to this if you face any issue:
https://github.com/kubernetes/community/blob/master/CLA.md

**Pull request closed without merging**
