### PR TITLE
Update kube-scheduler.md

### PR DESCRIPTION
**Pull request by xtreme-sameer-vohra**
Fix grammar typo

### CODE REVIEW

**Comment by bradtopol** [comment]
@xtreme-sameer-vohra Thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by tfogo** [comment]
Hi @xtreme-sameer-vohra, thanks for the PR! Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA so that we can review this PR, thanks!

**Comment by xtreme-sameer-vohra** [comment]
I signed it

**Comment by xtreme-sameer-vohra** [comment]
Hey @tfogo , sorry it took so long, but its done now

**Comment by Rajakavitha1** [comment]
Thanks for the PR @xtreme-sameer-vohra !
/lgtm
/approve

**Pull request merged**
