### PR TITLE
Add document for KEP Kubernetes Metrics Overhaul

### PR DESCRIPTION
**Pull request by danielqsj**
/milestone 1.14
/hold
/sig instrumentation
/cc @brancz

### CODE REVIEW

**Comment by danielqsj** [comment]
@brancz @jimangel does this look good ?

**Comment by brancz** [comment]
I'm not sure user facing documentation should have instructions on how to add a new metric to Kubernetes. I was more thinking to document the metric changes happening as a whole as part of the metrics overhaul KEP.

**Comment by danielqsj** [comment]
@brancz I don't know the best place to record our KEP implementation in website. 
@jimangel @zacharysarah : can you give some advices?

**Comment by brancz** [comment]
Yeah I'd like to hear some advice as well, I'm also perfectly happy with documenting it in the KEP itself.

**Comment by jimangel** [comment]
@danielqsj @brancz this does appear to be a developer centric doc that would be more suitable as a markdown doc in a sig-instrumentation repo. I don't think it should live in the KEP, since they aren't really designed to be doc repos. Who is the intended audience here?

**Comment by brancz** [comment]
I think generally what was started in this PR is not really what I imagined. What we need is cluster administrator facing docs informing them about the upcoming changes in metrics, as they are done as part of the metrics overhaul KEP. I guess my question is whether any actionable thing people need to do is fine to be in the KEP itself or whether we need docs on kubernetes.io for that?

**Comment by brancz** [comment]
Agreed. I think a release note theme is probably the best fit.

**Comment by danielqsj** [comment]
Thanks @brancz @jimangel . As conclusion is the release note is enough. I will close this PR.
/close

**Pull request closed without merging**
