### PR TITLE
Merged main dev-1.22 to keep in sync

### PR DESCRIPTION
**Pull request by chrisnegus**
/cc @PI-Victor @ritpanjw @ashnehete @carlisia 
Sync dev-1.22 with main on July 9, 2021.

### CODE REVIEW

**Comment by chrisnegus** [comment]
Commit https://github.com/kubernetes/website/pull/28883/commits/5eb9ded91ab4d1c934c87f0f3f74d95f71ccab78 was fixed by https://github.com/kubernetes/website/pull/28883/commits/57d21c697551571c6c1474a19c6aef96c0a6924f

**Comment by kbhawkey** [comment]
Hi @chrisnegus .
Does this sync represent a month of commits from main? Or, is the sync supposed to occur weekly?

**Comment by PI-Victor** [comment]
> Hi @chrisnegus .
> Does this sync represent a month of commits from main? Or, is the sync supposed to occur weekly?

Hi @kbhawkey, technically it's supposed to be done weekly but it doesn't always pan out like that due to availability, the last sync was done here: https://github.com/kubernetes/website/pull/28569

**Pull request merged**
