### PR TITLE
Cluster architecture diagram update

### PR DESCRIPTION
**Pull request by UnCommitted**
Added 2 new 3D representations of control plane and cloud controller diagrams.
Updated all base architecture links from old diagram to the new version.
Updated Cloud Controller specific docs to reference the expanded diagram, which is distinct from the base architecture.

I've split the original diagram into 2 versions, the first is only Kubernetes without the cloud underlay, the second brings in the cloud for the Cloud Controller context.

I've tried to keep the colours in line with existing palette, but let me know if they need updating.

Included .jpg format images as the .png versions are probably too large, happy to update if this is required.

### CODE REVIEW

**Comment by Sea-n** [comment]
BTW, I think it's not a good practice to make `.svg` and `.jpg` file inconsistent.

Maybe `components-of-kubernetes-3d.jpg` or so would be better.

**Comment by UnCommitted** [comment]
No problems, I'll update and re-push

**Comment by UnCommitted** [comment]
OK, fixed I think?

**Comment by Babapool** [comment]
/remove language ja ko pl pt ru zh

**Comment by tengqm** [comment]
We prefer SVG over JPG because 1. SVG scales better when zoomed; 2. SVG has "source code" which can be revised but JPG only has binary.

**Comment by Sea-n** [comment]
Thanks for quick fix! 😋
/unhold

Remove language tags accordingly.
/remove-language ja ko pl pt ru zh

**Comment by UnCommitted** [comment]
> We prefer SVG over JPG because 1. SVG scales better when zoomed; 2. SVG has "source code" which can be revised but JPG only has binary.

On point (1), I can re-render in PNG which isn't lossy and should scale, but it is large. I can also turn up the resolution of the image in jpg to afford more clarity.

On (2), I understand the preference, but for these architectural images and especially the headline ones where new users first land, it may be worth the sacrifice?

**Comment by chrismetz09** [comment]
Hey @UnCommitted, great figures!! Quick inputs:

1.  Diagrams needed. Tx for doing these!!
2. Use SVG if you can. 
3. Thinking down the road, what if a new contributor wants to modify these diagrams? Is your drawing tool open source and is there a way to load up the diagram source to make changes?

**Comment by UnCommitted** [comment]
Hi @chrismetz09, unfortunately the 3d format is not compatible with SVG. The source is from Blender, which is open source, and I'm happy to include the file is that helps?

**Comment by UnCommitted** [comment]
Hi @celestehorgan @dianaabv , just wanting to politely enquire as to a timeframe for having this PR reviewed please? Cheers.

**Comment by reylejano** [comment]
I agree with others that svg is preferred

**Comment by sftim** [comment]
@UnCommitted, what do you see as the benefit from switching the diagram to 3D? Once that's clear, we can try to steer this PR towards being mergeable.

**Comment by UnCommitted** [comment]
Hi @sftim @reylejano , I've always found the existing architectural diagrams on the main pages difficult to parse, especially for people new Kubernetes as a project and platform. Specifically for the main landing pages from searches, I think there is a case for clearer depictions, and I have found people respond to the 3D imagery more readily.

**Comment by UnCommitted** [comment]
No problems, if it doesn't fit with what the project requires, let's close this one off.

**Pull request closed without merging**
