### PR TITLE
Fix kubectl top for memory-demo pod

### PR DESCRIPTION
**Pull request by nihanthd**
Fixed command for accessing metrics(top) for memory-demo pod.

### CODE REVIEW

**Comment by nihanthd** [comment]
I have signed the CLA. Thanks

**Comment by Rajakavitha1** [comment]
@nihanthd Thanks for the update. Could you please sign the CLA following the instructions listed at  https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by mistyhacks** [comment]
If you're having trouble signing the CLA, or you have signed it and it's not
working correctly, see https://github.com/cncf/servicedesk for more info. You
can also contact #sig-contribex on Slack. We cannot accept this contribution until the checks are working
correctly. Thanks!

**Comment by zparnold** [comment]
@nihanthd Just a friendly reminder to sign the CLA when you are able.

**Comment by nihanthd** [comment]
@Rajakavitha1 @zparnold Completed signing the CLA.

**Pull request merged**
