### PR TITLE
Cloud Controller Manager: fix a broken link

### LINKED ISSUE #25748: Issue with k8s.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/
Out of tree developing instructions are now out of date. 

main.go reference leads to a 404.

### PR DESCRIPTION
**Pull request by oke-py**
closes #25748

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-25914--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/developing-cloud-controller-manager/

**Review by sftim — COMMENTED** [review]
/sig api-machinery
/lgtm

**Comment by kbhawkey** [comment]
Thanks for the update @oke-py .
/approve

**Pull request merged**
