### PR TITLE
Powershell note for kubectl patch command

### PR DESCRIPTION
**Pull request by manishbansal8843**
This command does not work in Powershell. A specific note would help the developers to take care of the same.

### CODE REVIEW

**Comment by manishbansal8843** [comment]
I have signed the corporate cla. I have tried forcing the bot to re-check the CLA but still its not working. Can anyone please help on this?
/check-cla

**Comment by manishbansal8843** [comment]
/check-cla
Forcing cla check

**Comment by zacharysarah** [comment]
@manishbansal8843 👋 Thanks for your patience. This is a useful clarification! 

Instead of a note, I'd prefer to see it formatted with a [shortcode for multiple tabs](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#tabs). Please feel free to ask in [#sig-docs](https://app.slack.com/client/T09NY5SBT/C1J0BPD2M) if you have any questions about formatting.

**Comment by manishbansal8843** [comment]
@zacharysarah I have made the changes. However, i am not able to add a note in `PowerShell` tab to explain the reason for removing quotes around command substitution. If this is acceptable, then kindly approve it. Anyway, i have posted a query on slack. Will update the PR if there is any way to do that.

**Comment by zacharysarah** [comment]
@manishbansal8843 Thanks for the changes! ✨ 
> However, i am not able to add a note in PowerShell tab to explain the reason for removing quotes around command substitution.

The idea of multiple tabs is hopefully to make the necessary difference self-explanatory. In this case, I think it works great.

/lgtm
/approve

**Pull request merged**
