### PR TITLE
zh-trans: update daemonset.md

### PR DESCRIPTION
**Pull request by mysunshine92**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by mysunshine92** [comment]
cc @markthink 
please add /approve ,thanks.

**Comment by markthink** [comment]
@mysunshine92  参考：https://github.com/k8smeetup/k8s-official-translation

**Comment by mysunshine92** [comment]
> 
> 
> @mysunshine92 参考：https://github.com/k8smeetup/k8s-official-translation
好的，谢谢，我来看看。

**Pull request merged**
