### PR TITLE
Fix typo volume-snapshots.md

### PR DESCRIPTION
**Pull request by sunminjeon**
fix typo /concepts/storage/volume-snapshots.md

32 line
before : These attibutes may differ among snapshots taken from the same volume on the storage system and therefore cannot be expressed by using the same StorageClass of a PersistentVolumeClaim.

after : These attributes may differ among snapshots taken from the same volume on the storage system and therefore cannot be expressed by using the same StorageClass of a PersistentVolumeClaim.

Just fix **attibutes -> attributes**

### CODE REVIEW

**Comment by sunminjeon** [comment]
@rajeshdeshpande02  Thanks for your review!

**Comment by gochist** [comment]
@sunminjeon Recently, there is a case where PR cannot be processed because it is stuck in Netlify. Although it's workaround, it seems like you can retry the check by adding a little change and pushing it again, for example a commit message change.

**Comment by sunminjeon** [comment]
Thanks @sftim
:-)

**Pull request merged**
