### PR TITLE
Updated ingress address in Single Service Ingress

### PR DESCRIPTION
**Pull request by divya-mohan0209**
Replaced 107.178.254.228 with a documentation IP address 203.0.113.123 so as to not use a pre-allocated IPv4 IP.

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Please review the CLA agreement

**Comment by divya-mohan0209** [comment]
@sftim : This one, as well if it's okay. Sorry for the extra spam :)

**Comment by sftim** [comment]
This is for #19507

**Pull request merged**
