### PR TITLE
Bump Hugo to v0.120.3

### LINKED ISSUE #43671: Bump Hugo version
**This is a Feature Request**

**What would you like to be added**
Update Hugo to [v0.119.0](https://github.com/gohugoio/hugo/releases/tag/v0.119.0) (or later), by editing `netlify.toml`

*Update 2024-01-01:* v0.121.1 would be ideal.

**Why is this needed**
There are some security fixes for Go that we might want to pull in.

**Comments**
/sig security
/sig docs

### PR DESCRIPTION
**Pull request by Gauravpadam**
Closes #43671

The change is tested locally, Website container builds on v0.120.3 now

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The upgrade to the newer Hugo version looks good. 

Few observations in the [Netlify deployment logs](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6537cb1d1a7a6e0008d8aa53), which might be unrelated or require attention (perhaps @sftim or any other tech lead could provide some guidance/insights):

- The utilization of Go version 1.10 during Initializing (expected to see the use of more recent Go version), might be due to caching.

> 2:48:31 PM: Installing Go version 1.10 (requested 1.10)
> 2:48:38 PM: go version go1.10 linux/amd64
> 2:48:38 PM: Using PHP version 8.0
> 2:48:38 PM: Installing Hugo 0.119.0

- There are few deprecation warnings, specifically:

    - A deprecation warning about the use of "Kind" as "taxonomyterm" in the "disableKinds" configuration. 
    
    > 2:48:45 PM: WARN  DEPRECATED: Kind "taxonomyterm" used in disableKinds is deprecated, use "taxonomy" instead.


    - Another deprecation warnings concerning languages and their custom parameters.

> 2:48:45 PM: WARN  config: languages.id.description: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.id.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
> 2:48:45 PM: WARN  config: languages.id.languagenamelatinscript: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.id.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
> 2:48:45 PM: WARN  config: languages.ru.description: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.ru.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
> 2:48:45 PM: WARN  config: languages.ru.languagenamelatinscript: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.ru.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120

**Comment by sftim** [comment]
Netlify doesn't compile Hugo, so the version of Go that's available there isn't important.

The things that are marked as deprecated are good to learn IMO.

**Comment by Gauravpadam** [comment]
Thanks for pointing these out @dipesh-rawat, I've been seeing these in local builds too. I'll try some tinkering

**Comment by nate-double-u** [comment]
Sorry i haven’t had a chance to test this locally myself yet. At this point should we hold till after KubeCon?

**Comment by dipesh-rawat** [comment]
Hugo [v0.120.3 (released 1 Nov)](https://github.com/gohugoio/hugo/releases/tag/v0.120.3) became available few days ago, so we could also consider upgrading to it as part of this PR instead of going for version [v0.119.0 (released Sep 24)](https://github.com/gohugoio/hugo/releases/tag/v0.119.0). Just wanted to suggest this as a potential option.

**Review by divya-mohan0209 — COMMENTED** [review]
LGTM, thank you @Gauravpadam for your contribution!

For the deprecation warning, I reckon we'll need to amend the hugo.toml configuration per [this guideline](https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120). Since this is not affecting the rendering of the localized documentation, I'll open up a separate issue referencing this PR so that contributors can pick up on that.

/approve

**Pull request merged**
