### PR TITLE
Change virtual machine for docker - from experimental to preferred.

### PR DESCRIPTION
**Pull request by TrishaChetani**
Virtual machine as docker is preferred by Minikube maintainers

### CODE REVIEW

**Comment by TrishaChetani** [comment]
@medyagh : Could please help me how to run this automated checks.

**Comment by TrishaChetani** [comment]
@medyagh, @tstromberg: How to resolve label? I will appreciate your help

**Comment by prasadkatti** [comment]
@TrishaChetani - The PR is waiting for **_lgtm_** ("looks good to me") and _**approved**_ labels. Once the OWNERs of the project review and add those labels, a bot will automatically merge the PR.

**Comment by TrishaChetani** [comment]
@medyagh: I still see the not mergeable options enabled  https://i.imgur.com/L9No4vF.png

**Pull request merged**
