### PR TITLE
Update description on affinity and anti-affinity

### PR DESCRIPTION
**Pull request by augustovictor**
Isn't *preferred* a soft definition already?

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @augustovictor, please sign EasyCLA first, which will allow us to review your PR and accept the contribution.

You can find about EasyCLA here - https://docs.linuxfoundation.org/lfx/easycla

and the steps to sign EasyCLA are here - https://docs.linuxfoundation.org/v2/easycla/contributors/individual-contributor

You can start your signing EasyCLA from here - https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38056/#/?version=2

**Comment by utkarsh-singh1** [comment]
Related Doc - https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by divya-mohan0209** [comment]
Hello @augustovictor due to no response from your end, we'll be closing the PR. Please feel free to open the PR by issuing the /reopen command when you've signed the CLA.
/close

**Pull request closed without merging**
