### PR TITLE
missing closing double quotes

### PR DESCRIPTION
**Pull request by dewijones92**

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
There is already a PR #40484 which is addressing this same issue.

**Comment by dipesh-rawat** [comment]
Duplicated by PR #40484 
/triage duplicate

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by Shubham82** [comment]
closing this PR. as this issue is resolved in the following PR: #40484
/close

**Pull request closed without merging**
