### PR TITLE
[zh] Replace codenew with code for 5 files in content/zh-cn/docs/tasks/inject-data-application/

### PR DESCRIPTION
**Pull request by asa3311**
sync:
content/zh-cn/docs/tasks/inject-data-application/define-command-argument-container.md; 
content/zh-cn/docs/tasks/inject-data-application/define-environment-variable-container.md; 
content/zh-cn/docs/tasks/inject-data-application/define-interdependent-environment-variables.md; 
content/zh-cn/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md; 
content/zh-cn/docs/tasks/inject-data-application/environment-variable-expose-pod-information.md;

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
/approve

**Comment by mengjiao-liu** [comment]
/hold

Wait for the outcome of the discussion https://github.com/kubernetes/website/issues/42203#issuecomment-1691439368.

**Comment by mengjiao-liu** [comment]
/hold cancel

`code` shortcode is being replaced by `code_sample` 
https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#source-code-files

Please resync the latest main branch. @asa3311

**Comment by tengqm** [comment]
ping @asa3311

**Pull request closed without merging**
