### PR TITLE
Fix API reference issue due to js versions

### PR DESCRIPTION
**Pull request by tengqm**

### CODE REVIEW

**Comment by kbhawkey** [comment]
OK, the branch has changed 👀

**Comment by jihoon-seo** [comment]
For the record:
the "Example" button is now working in the [preview](https://deploy-preview-39719--k8s-v1-25.netlify.app/docs/reference/generated/kubernetes-api/v1.25/#container-v1-core).

(cf. [the one in prod website](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#container-v1-core) is not working for now.)

**Comment by jihoon-seo** [comment]
@tengqm This PR has 2 commits, where the second one (['Backport cve-feed shortcode'](https://github.com/kubernetes/website/pull/39719/commits/a93ae8f1a19f21368fab93b86a2554a2ddec7518)) seems not related to this PR or the first one.
Is the inclusion of second commit to this PR intentional or unintended?

**Comment by tengqm** [comment]
> @tengqm This PR has 2 commits, where the second one (['Backport cve-feed shortcode'](https://github.com/kubernetes/website/pull/39719/commits/a93ae8f1a19f21368fab93b86a2554a2ddec7518)) seems not related to this PR or the first one. Is the inclusion of second commit to this PR intentional or unintended?

It is intended. Without that second commit, the website build fails.

**Comment by tengqm** [comment]
As for the live website, I'll fix it in a separate PR (not the same target branch anyway).

**Pull request merged**
