### PR TITLE
Remove Open vSwitch from “How to implement the Kubernetes networking model”

### PR DESCRIPTION
**Pull request by ixodie**
Open vSwitch is in no way required for Kubernetes to function.  Kubernetes is not mentioned once on this project's website, nor are there any instructions for how you might use this in a k8s environment.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-30094--kubernetes-io-main-staging.netlify.app/docs/concepts/cluster-administration/networking/#third-party-content-disclaimer

**Comment by ixodie** [comment]
@kbhawkey @thockin @sftim 

Any thing needed here to get this complete?

**Comment by ixodie** [comment]
@kbhawkey @thockin @sftim Waiting.

**Comment by ixodie** [comment]
I rebased this, still waiting for approval.

**Comment by ixodie** [comment]
This PR was submitted a month ago, is there some reason it is not getting any attention?

@kbhawkey @thockin

**Pull request merged**
