### PR TITLE
Fix link to LimitRanger design document

### LINKED ISSUE #35656: Broken link in ja/docs/concepts/policy/limit-range/
**This is a Bug Report**

**Problem:**
Link to LimitRanger design document in https://kubernetes.io/ja/docs/concepts/policy/limit-range/ is broken.
F) https://git.k8s.io/community/contributors/design-proposals/resource-management/admission_control_limit_range.md
T) https://git.k8s.io/design-proposals-archive/resource-management/admission_control_limit_range.md

**Proposed Solution:**
fix link in doc

**Page to Update:**
https://kubernetes.io/ja/docs/concepts/policy/limit-range/

### PR DESCRIPTION
**Pull request by YuikoTakada**
Fix #35656
This PR fix Link to LimitRanger design document in https://kubernetes.io/ja/docs/concepts/policy/limit-range/

### CODE REVIEW

**Review by Sea-n — COMMENTED** [review]
Checked by `./scripts/lsync.sh content/ja/docs/concepts/policy/limit-range.md`.
/lgtm

**Comment by jihoon-seo** [comment]
Netlify build failed with no particular reason.
@YuikoTakada please (force-)push again, then a new Netlify build will be triggered.

**Review by chrisnegus — COMMENTED** [review]
The new link works.
/lgtm

**Pull request merged**
