### PR TITLE
Fixed some punctuation.

### PR DESCRIPTION
**Pull request by dsbos**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by aimeeu** [comment]
Hi @dsbos - thanks for submitting a pull request! In order for this PR to be processed, please sign the Contributor License Agreement mentioned in a previous comment. Feel free to ping the Kubernetes Slack #sig-docs channel if you have questions about submitting PRs for kubernetes/website. We look forward to more contributions from you!

**Comment by jimangel** [comment]
Hey there! @dsbos, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by cody-clark** [comment]
Hi @dsbos! Thanks for the contribution. Have you had a chance to [sign the CLA](https://github.com/kubernetes/community/blob/master/CLA.md#how-do-i-sign) yet? Once you sign it, we can start the review process.

**Comment by dsbos** [comment]
> Have you had a chance to sign the CLA yet? Once you sign it, we can start the review process.

I've now gotten a chance to try, but can't yet proceed.

On the "Authorize Linux Foundation ID" page for associating my (previously existing) GitHub account with my newly created Linux Foundation ID, the "Authorize linuxfoundation" button looks disabled and clicking on it doesn't do anything.

(Also, the down caret on the "Personal user data" line doesn't do anything (except display a small dotted-outline box around the  down caret (as if menu items are missing?). I've tried with two versions of Firefox and one version of SeaMonkey.)

I have tried e-mailing login-issues@jira.linuxfoundation.org about that, but haven't gotten any reply yet.

Daniel

**Comment by dsbos** [comment]
Okay; signed CLA.

**Comment by zacharysarah** [comment]
@dsbos Feel free to `/reopen` this PR when you're ready to respond to feedback.

/close

**Pull request closed without merging**
