### PR TITLE
[hi] Localize content/en/docs/reference/glossary/cluster-architect.md 

### PR DESCRIPTION
**Pull request by Shivaniiiiiiiiiii**
Fixes #35600 

Signed-off-by: shivani tiwari <shivanitiwari.1702@gmail.com>

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
More info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Shivaniiiiiiiiiii** [comment]
hello @mittalyashu 
I completed EasyCLA Authorization many times since yesterday but still it is not showing here

**Comment by Sea-n** [comment]
Hey @Shivaniiiiiiiiiii,

Not sure why, but the committer is mapping to another GitHub user @Shivanii17.

Maybe you can check the email you used for this account and local git client.

**Comment by RA489** [comment]
> I completed EasyCLA Authorization many times since yesterday but still it is not showing here

/easycla

**Comment by RA489** [comment]
hey @shivani could you please click on non covered tab and follow the given instruction to get your cla signed.

**Comment by Shivaniiiiiiiiiii** [comment]
@RA489 I did it so many times but unable to see any changes.

**Comment by rolfedh** [comment]
@Shivaniiiiiiiiiii and others: Thanks for trying to work through the CLA process. I'm looking into whether this might take a few days to be approved. Will report back here soon.

**Comment by bradtopol** [comment]
Hi @Shivaniiiiiiiiiii are you sure that you signed the commit with the same email you used to sign up for easy cla?  When you do a git log on. your commit, what do you see?

**Comment by Shivaniiiiiiiiiii** [comment]
@bradtopol yes I signed the commit with the same email which I used in sign up for easy cla

**Comment by RA489** [comment]
@Shivaniiiiiiiiiii You may join kubernetes slack #github-management channel ask for help if you're still facing issues related to CLA on your PR

**Comment by Sea-n** [comment]
I'm repeating my [previous comment](https://github.com/kubernetes/website/pull/35867#issuecomment-1214199643):

The committer was mapping to another GitHub user @Shivanii17.
Please check the email you used for this account and local git client.

**Comment by Sea-n** [comment]
Seems like you deleted that GitHub account.

The email used for commit this PR is not binding to your GitHub account, so the CLA validation won't pass.

Please goto GitHub Settings > Access > Emails > Add email address:
https://github.com/settings/emails

**Pull request closed without merging**
