### PR TITLE
Fix numbering in the "Parallel Jobs" section

### PR DESCRIPTION
**Pull request by AdamGS**
Just a quick fix to the numbering in this section, nothing else to it

### CODE REVIEW

**Comment by AdamGS** [comment]
I signed it

**Comment by tengqm** [comment]
The fix is incorrect.

**Comment by AdamGS** [comment]
As far as I can tell the numbering does make sense this way, do you think the bullet points should also be moved to the right?

**Comment by AdamGS** [comment]
OK, I read the style guide more carefully, I will try and fix it

**Comment by AdamGS** [comment]
Should be good now, @tengqm thank you for the quick review!

**Comment by tengqm** [comment]
/lgtm
/approve
Thanks!

**Comment by sftim** [comment]
Relevant to issue #20335

**Pull request merged**
