### PR TITLE
init arabic language

### PR DESCRIPTION
**Pull request by selaamimech**
Introduce arabic language and contribute to documentation translation effort. 

I added a CSS customisation because of an issue in the logo when switching to arabic language. The issue is described in the capture below :

image

Related Open Issues : 
#22726

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hello @selaamimech , good day! Thank you for your PR and your subsequent comments. I'd highly recommend before you start with the idea of a localization, you read through the [contributor's guide](https://kubernetes.io/docs/contribute/) of our documentation; especially the parts around [localization](https://kubernetes.io/docs/contribute/localization/). I see that you have already joined the sig-docs-localizations channel & posted about this, however there are several procedures outlined in the localization document which would set you up for success.

Also, P.S. If you do have concerns about the leadership or anything else, please do feel free to join our monthly localization and regular bi-weekly meetings and raise them. This is an open source project & work is done by voluntary contributors across the globe, not paid staff.

**Comment by selaamimech** [comment]
You are not 100% open and free. You should say open when no companies are
contributing. I know companies pay their salaries to contribute to the
open. Is this open? If so fuck your openness.

**Comment by selaamimech** [comment]
You should be open and not kill Muslims. This is true openness.you assigned
a German hitler to work with him.  @sftim this little man should learn how
to be gentleman. Being white is not sufficient

**Comment by selaamimech** [comment]
And fuck you also Indian girls. When in your country you stop killing
Muslims then I will accept your point of view.

Indian with millions of people is a consumer of white technologies. Build
your own technologies and fuck Kubernetes.

Open and they sell events and courses in thousand of dollars. Sincerely
fuck your openness

**Comment by sftim** [comment]
The Kubernetes project expects and requires all contributors to follow our [code of conduct](https://www.kubernetes.dev/community/code-of-conduct/). I'm afraid in this case we have had to intervene.

However, as a project we absolutely would like to see work done to localize Kubernetes documentation to all languages, including Arabic.

**Pull request closed without merging**
