### PR TITLE
Fix a typo.

### PR DESCRIPTION
**Pull request by yusheng-guo**
### Description

There is a typo, it should be "以下" instead of "一下".

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/47398/#/?version=2)
> 
> * [❌](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/47398/#/?version=2) - login: @yushengguo557 / name: Yusheng Guo . The commit ([f872513](https://github.com/kubernetes/website/commit/f8725138e2c5c23f7d115a3c4da29dc63908c90c)) is not authorized under a signed CLA. [Please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/47398/#/?version=2). For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

Thanks for the catch! Please also sign the CLA according to the comment above.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by yushengguo557** [comment]
> @yushengguo557, Thanks you for your PR first contribution. Could you please sign the CLA before the PR can be reviewed. Follow the steps to sign CLA: https://git.k8s.io/community/CLA.md

Thank you very much for your enthusiastic response. I have signed the CLA. If there are any other questions, please feel free to contact me. Thank you! 😊

**Review by mengjiao-liu — COMMENTED** [review]
/approve
Thanks!

**Pull request merged**
