### PR TITLE
Fix: Update service.md (nginx image not found)

### PR DESCRIPTION
**Pull request by adeniyistephen**
I fixed an imagepulling error in the service.md example on the website. nginx:11.14.2 is no longer on Nginx docker hub:  https://hub.docker.com/_/nginx?tab=tags&page=1&name=11.14.2 so I changed the image tag to the latest. please let me know if the latest tag is not the right image to use or if I'm wrong.

### CODE REVIEW

**Comment by kaworu** [comment]
Ran into the same issue today.

Although I couldn't find confirmation from the [dockerhub image description](https://hub.docker.com/_/nginx?tab=description), `stable` might be a safer tag than `latest` here.

**Comment by adeniyistephen** [comment]
> Ran into the same issue today.
> 
> Although I couldn't find confirmation from the [dockerhub image description](https://hub.docker.com/_/nginx?tab=description), `stable` might be a safer tag than `latest` here.

Sure, I'll change that.

**Comment by Sea-n** [comment]
Not sure why GitHub said this branch has conflicts, maybe you would like to rebase onto `kubernetes:main` and do the force push. 😊

**Comment by Sea-n** [comment]
Thanks for your patient,  this PR looks good to me! 👍
/lgtm

**Review by divya-mohan0209 — APPROVED** [review]
@adeniyistephen: The reason why you were getting a rebase error is because the version number was changed to 1.14.2 from 11.14.2. The earlier version was a typo and we just merged the changes yesterday against an issue.
I don't have a problem merging these changes. However, for future reference please open an issue and an associated PR instead of directly opening a PR with the changes. This will help avoid duplicate work being done by multiple contributors.

**Comment by adeniyistephen** [comment]
> @adeniyistephen: The reason why you were getting a rebase error is because the version number was changed to 1.14.2 from 11.14.2. The earlier version was a typo and we just merged the changes yesterday against an issue. I don't have a problem merging these changes. However, for future reference please open an issue and an associated PR instead of directly opening a PR with the changes. This will help avoid duplicate work being done by multiple contributors.

Cool.

**Pull request merged**
