### PR TITLE
Merged main dev 1.30

### PR DESCRIPTION
**Pull request by drewhagen**
This PR syncs the dev-1.30 branch with main to keep the dev-1.30 branch up to date.

cc: @Princesso @Vyom-Yadav @chanieljdan @celestehorgan

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
/lgtm

**Comment by dipesh-rawat** [comment]
> ([Reference](https://github.com/kubernetes/website/pull/44955#issuecomment-1917667305))
Needs approval from an approver in each of these files:
[data/announcements/OWNERS](https://github.com/kubernetes/website/blob/dev-1.30/data/announcements/OWNERS)

This appears to also require approval from @kubernetes/steering-committee
/committee steering

**Review by Princesso — COMMENTED** [review]
/lgtm

**Comment by pacoxu** [comment]
/lgtm

The KubeCon 2024 EU Banner is already approved in https://github.com/kubernetes/website/pull/44828

**Comment by pohly** [comment]
> The KubeCon 2024 EU Banner is already approved in https://github.com/kubernetes/website/pull/44828

Agreed. So let's unblock the PR on behalf of steering:

/approve

**Pull request merged**
