### PR TITLE
add responsive table on blog

### PR DESCRIPTION
**Pull request by Arhell**
issue #21209

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-21217--kubernetes-io-master-staging.netlify.app/blog/

**Comment by sftim** [comment]
@Arhell, can you explain the difference in site behavior that comes about by merging this PR? What tests could a reviewer do to decide if this is the right fix?

**Comment by Arhell** [comment]
@sftim Hi of course
This fix allows you to create any tables that are or will be on the site, this will improve the interaction of the response if someone is watching from mobile devices, and there is no horizontal scroll bar

**Pull request merged**
