### PR TITLE
Correct kubectl spelling

### PR DESCRIPTION
**Pull request by syxunion**

### CODE REVIEW

**Comment by vaibhav2107** [comment]
@syxunion Please sign CLA first

**Comment by reylejano** [comment]
/lgtm cancel
CLA should be signed before the PR is reviewed

**Review by Arhell — COMMENTED** [review]
/easycla

**Review by Princesso — COMMENTED** [review]
Hi @syxunion, any updates on signing the CLA? If you have any questions or need any clarity, you can put them in the comments, that way, we can assist in getting it sorted.

**Comment by windsonsea** [comment]
This will be closed due to no response to CLA in weeks. You are free to re-open it when you are available.
/close

**Pull request closed without merging**
