### PR TITLE
StatefulSetAutoDelete documentation

### PR DESCRIPTION
**Pull request by mattcary**
Currently this is a placeholder PR.

[KEP 1847](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/1847-autoremove-statefulset-pvcs)

[Implementation PR #99728](https://github.com/kubernetes/kubernetes/pull/99728)

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
:information_source: Please only change the English documentation here. The release docs team don't know how to resolve merge conflicts in any other language and so we couldn't accept a PR documenting an upcoming release that changes any downstream localization.

I think what you need to do @mattcary is an interactive rebase against _dev-1.23_ and then you'll only be making English-language changes. You could also hard-reset to _dev-1.23_ and then cherry pick commit 11103c7c5cfd61d29c288e96ef45cd82ca02cc63.

**Comment by sftim** [comment]
@mattcary actually I see the problem. This PR is trying to merge _dev-1.23_ into _main_. You need to merge a docs branch from your fork into _dev-1.23_

/hold

**Comment by nate-double-u** [comment]
@mattcary, reminder that tomorrow Nov 23rd is the deadline for 1.23 Docs Ready for Review. Please correct the branch issues that @sftim highlighted, and push your docs content for this enhancement and remove the work-in-progress label when ready for review.

We have a tight turnaround to getting docs reviewed and approved for the release, and we’re hoping to have all docs in for review by EOB tomorrow. Thank you!

**Comment by mattcary** [comment]
> @mattcary actually I see the problem. This PR is trying to merge main into dev-1.23. You need to merge a docs branch from your fork into dev-1.23

Ack, you're right, I'm not sure how I managed to get this sideways. Let me see if I can connect the branch from my fork to this PR.

**Comment by mattcary** [comment]
Hmm, I can change the base branch, but it doesn't look like I can change the branch the PR is coming from. I'll have to recreate it.

**Comment by mattcary** [comment]
Created #30597

**Pull request closed without merging**
