### PR TITLE
Enable volume limit feature by default

### PR DESCRIPTION
**Pull request by warmchang**
Enable volume limit feature by default.

ref: https://github.com/kubernetes/kubernetes/pull/69225

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
LGTM
/cc @gnufied

**Comment by steveperry-53** [comment]
@gnufied If this looks good to you, please comment with `/lgtm`. Thanks

**Comment by gnufied** [comment]
Yep. thanks
/lgtm

**Pull request merged**
