### PR TITLE
fix grammar mistakes

### PR DESCRIPTION
**Pull request by jonyhy96**
fix grammar mistakes

```release-note
None
```

### CODE REVIEW

**Comment by zacharysarah** [comment]
/lgtm
/approve
/hold
/assign @Bradamant3 

Feel free to remove the `/hold` once docs thaw after 1.10. ❄️

**Comment by bgrant0607** [comment]
This is not a fix. "facilitates" refers to Kubernetes, which is singular

**Comment by jonyhy96** [comment]
@bgrant0607 
Thnaks for your correct 
I still feel confused about whether there should be a "," before that.
Please help me about this

**Pull request closed without merging**
