### PR TITLE
kubeadm: Document new v1beta2 config format

### PR DESCRIPTION
**Pull request by rosti**
Update the docs for kubeadm's new v1beta2 config format.
Ref kubernetes/enhancements#970 kubernetes/kubeadm#1439

### CODE REVIEW

**Comment by neolit123** [comment]
@rosti 
also this file need changes:
https://github.com/kubernetes/website/blob/4aa977cb27084309fc7e499e03a9366aac979a59/content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md

BTW, it might be easier for me to manage these changes in the PRs i added here:
https://github.com/kubernetes/kubeadm/issues/1577

the idea was that those PRs touch the separate docs paths.

**Comment by rosti** [comment]
@neolit123 I'll offload this from you and, instead, rely on your review. Also, this is more like a placeholder ATM. I'll probably finish it on Friday.

**Comment by rosti** [comment]
@neolit123 updated with kubeadm init docs. PTAL

**Comment by tengqm** [comment]
@rosti Please help resolve the conflict?

**Comment by makoscafee** [comment]
Hi, @rosti  can merge conflicts be resolved so that this can be approved and merged?? We are looking to have all PR for release 1.15 merged by June 10th. Let me know if there is anything docs team can assist.

**Comment by neolit123** [comment]
@rosti 

might be a good idea to link to v1beta2 from the link in:
> For more details on each field in the configuration you can navigate to our API reference pages.

under `content/en/docs/setup/independent/control-plane-flags.md`

someone mentioned that they had problems navigating from the internal config godocs to v1beta2.

**Comment by rosti** [comment]
PR rebased, added suggestion by @neolit123

**Pull request merged**
