### PR TITLE
[ja] Fix link on Storage Capacity page

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/36618/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Comment by Sea-n** [comment]
There are many changes with this file, but you only pick a tiny URL replacement, and the old link still works.

image

Could you give us some insight about the value of this PR?

**Review by Arhell — COMMENTED** [review]
I'm not a Japanese translator, I help in every way I can, little by little.

**Comment by nasa9084** [comment]
Although we recommend updating the whole file if a contributor can, a very small fix is also welcome!
/approve

**Review by ydFu — APPROVED** [review]
/lgtm

**Pull request merged**
