### PR TITLE
delete redundant "。"

### PR DESCRIPTION
**Pull request by atrn0**
"。" was redundant. so removed it.

### CODE REVIEW

**Comment by atrn0** [comment]
signed CLA

**Comment by inductor** [comment]
@atrn0 Thank you for the PR.
As described in https://kubernetes.io/ja/docs/contribute/localization/ , we maintain the documentation with our work branch.
Could you change the base branch and the PR target branch to our work branch? The current branch is `dev-1.17-ja.3`.
We are most likely merging it to master very soon (hopefully within a few weeks) so your contribution will be applied to the upstream then.

**Comment by inductor** [comment]
You need rebase on your local branch! 🙏

**Pull request merged**
