### PR TITLE
Fix broken link in "Container Lifecycle Hooks"

### PR DESCRIPTION
**Pull request by scraly**
Fix feature gate link to "/docs/reference/command-line-tools-reference/feature-gates/"

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/retitle Fix broken link in "Container Lifecycle Hooks"

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for fixing the link!
/lgtm

[Preview Page](https://deploy-preview-44383--kubernetes-io-main-staging.netlify.app/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-implementations)

**Review by kumarankit999 — APPROVED** [review]
Thanks for Contributing, looking fixed now!!!

**Pull request merged**
