### PR TITLE
client-libraries.md: adding C client library link

### PR DESCRIPTION
**Pull request by juchem**
This PR changes the `client-libraries.md` document with a link to the official C client library

### CODE REVIEW

**Review by Sea-n — COMMENTED** [review]
In the k/website repo, we sort list in lexicographic order. Please move this item accordingly.

I wonder should we add Ruby, Perl in [kubernetes-client/*](https://github.com/orgs/kubernetes-client/repositories) too?

**Comment by juchem** [comment]
@Sea-n sorted

**Comment by juchem** [comment]
@Sea-n I went ahead and added the Perl and Ruby libraries, and fixed the formatting so all grids are equally spaced in source form

**Comment by reylejano** [comment]
Looks good according to [SIG API Machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery) client owners lists
/approve

**Pull request merged**
