### PR TITLE
Fix journalctl command on kubeadmin page

### PR DESCRIPTION
**Pull request by ZhiFeng1993**
This PR is to fix: https://github.com/kubernetes/website/issues/21769

Update the journalctl command in the kubeadmin page.

### CODE REVIEW

**Comment by neolit123** [comment]
thanks
/sig-cluster-lifecycle
/lgtm

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-21781--kubernetes-io-master-staging.netlify.app/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

**Pull request merged**
