### PR TITLE
[WIP] Documentation for PodHealthyPolicy

### PR DESCRIPTION
**Pull request by mortent**
Placeholder PR

Enhancement issue: https://github.com/kubernetes/enhancements/issues/3017
Kubernetes PR: https://github.com/kubernetes/kubernetes/pull/108233

### CODE REVIEW

**Comment by tengqm** [comment]
what's happening to the other gates in the table?

**Comment by mortent** [comment]
@tengqm Yeah, I was wondering the same thing. I will figure it out.

**Comment by mehabhalodiya** [comment]
The v1.24 milestone no longer tracks the KEP that this PR supports. Thanks for your effort on this documentation; I recommend saving this work for a future release.

/close

If you feel that this PR has been closed in error, please feel free to reopen it against another branch.
Thank you!

**Comment by mehabhalodiya** [comment]
The v1.24 milestone no longer tracks the KEP that this PR supports. Thanks for your effort on this documentation; I recommend saving this work for a future release.

/close

If you feel that this PR has been closed in error, please feel free to reopen it against another branch.
Thank you!

**Pull request closed without merging**
