### PR TITLE
[vi] Remove exec permission on markdown files

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Related PR: #28447 (Remove exec permission on markdown files)

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@sftim Could you check these PRs, and do `lgtm` and `approve` if they seems good? 😊
- #28550
- #28551 
- #28557 
- #28561 (This PR)

**Comment by tengqm** [comment]
This needs an approval from the localization team. It has been dangling for too long.

**Review by huynguyennovem — APPROVED** [review]
/lgtm

**Review by huynguyennovem — COMMENTED** [review]
/approve

**Pull request merged**
