### PR TITLE
Update taint-and-toleration.md

### PR DESCRIPTION
**Pull request by AndySongTech**

### CODE REVIEW

**Comment by ydFu** [comment]
@AndySongTech 
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Review by SataQiu — COMMENTED** [review]
Thanks @AndySongTech !
Please sign CLA https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement

**Pull request closed without merging**
