### PR TITLE
solved issue #26274

### PR DESCRIPTION
**Pull request by shahincsejnu**
solved issue #26274, updated the missing descriptions in DaemonSet Taints and Tolerations table.

### CODE REVIEW

**Comment by ydFu** [comment]
@shahincsejnu
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
/approve

Need a tech lgtm

**Review by ydFu — APPROVED** [review]

**Pull request merged**
