### PR TITLE
Translate tasks/administer-cluster/enabling-endpointslices.md in Japa…

### PR DESCRIPTION
**Pull request by hase1128**
I translate in Japanese. Would you please check it?  
original issue is here(#18140)

### CODE REVIEW

**Comment by sftim** [comment]
One thing puzzles me: this is documentation updated for **v1.17** targeting a branch named “_dev-1.16-ja.1_”. Is that right?

**Comment by inductor** [comment]
ah actually this is my fault. Can you hold on a second? :bowing_man:

**Comment by hase1128** [comment]
@inductor 
How should I address this issue?
(I am not familiar with local rules for Japanese document....)

I heard that there is the slack channel where we can discuss about Japanese document.
but I forgot the URL of this channel...

**Comment by inductor** [comment]
@hase1128 
https://slack.k8s.io/ and join kubernetes-docs-ja channel :)

**Comment by inductor** [comment]
Update: this PR will be merged in 1.17 milestone!

**Comment by inductor** [comment]
@hase1128 can you rebase your branch to `dev-1.17-ja.1` ? 🙏

**Comment by hase1128** [comment]
> @hase1128 can you rebase your branch to `dev-1.17-ja.1` ?

@inductor 
OK, but I don't know how to rebase, so I will close this PR and create new PR based on `dev-1.17-ja.1`

**Comment by inductor** [comment]
@hase1128 you can do `git rebase upstream/dev-1.17-ja.1`

If you add remote kubernetes/website as upstream

**Comment by hase1128** [comment]
> @hase1128 you can do `git rebase upstream/dev-1.17-ja.1`
> 
> If you add remote kubernetes/website as upstream

@inductor 
Merge conflict was occurred when I tried to rebase and I could not resolve, so I close this PR, and create new PR. thanks.

**Pull request closed without merging**
