### PR TITLE
[zh] Optimize some zh text about Registry

### PR DESCRIPTION
**Pull request by chengxiangdong**
`注册表` can be confusing, and in most cases `仓库` is appropriate, so fix them by the scene.

### CODE REVIEW

**Comment by windsonsea** [comment]
/retitle [zh] Optimize some zh text about Registry

**Comment by windsonsea** [comment]
Another question is:

You can run `./scripts/lsync.sh` to check any inconsistency with en before you open a PR.

image

Especially three relatively big files are included in this PR:
```
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume.md
```

因为某些 contributor 像你这个 PR 一样，只更改了部分内容，使得 `./scripts/lsync.sh` 无法准确检测出与 en 的不一致。所以不建议仅更改部分内容，需要全文检查，发现所有不一致的内容。

也就是说，这 3 个提示 `still in sync` 的大文件不适合放在这个 PR，人工发现几千行中的不一致对于 author 和  reviewer 都是一个比较大的工作。

**Comment by chengxiangdong** [comment]
> 

I am sorry for the inappropriate description, and now I got it.

**Comment by chengxiangdong** [comment]
> /retitle [zh] Optimize some zh text about Registry
> 
> Hi, we shall avoid to use bad, terrible, ugly, and some similar words to bring negative feeling to contributors herein.

I am sorry for the inappropriate description, and now I got it.

**Comment by chengxiangdong** [comment]
> Another question is:
> 
> You can run `./scripts/lsync.sh` to check any inconsistency with en before you open a PR.
> 
> image
> 
> Especially three relatively big files are included in this PR:
> 
> ```
> content/zh-cn/docs/concepts/containers/images.md
> content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
> content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/volume.md
> ```
> 
> 因为某些 contributor 像你这个 PR 一样，只更改了部分内容，使得 `./scripts/lsync.sh` 无法准确检测出与 en 的不一致。所以不建议仅更改部分内容，需要全文检查，发现所有不一致的内容。
> 
> 也就是说，这 3 个提示 `still in sync` 的大文件不适合放在这个 PR，人工发现几千行中的不一致对于 author 和 reviewer 都是一个比较大的工作。

学习到了，感谢指导！
我先将这三个文件去掉了，这三个文档的修复将在另外 PR 中提交。

**Review by howieyuen — COMMENTED** [review]
/lgtm

**Comment by windsonsea** [comment]
Thanks.
/lgtm

**Pull request merged**
