### PR TITLE
Topology manager remove

### PR DESCRIPTION
**Pull request by tukwila**
Move feature gates TopologyManager to  feature-gates-removed page
Ref: https://github.com/kubernetes/kubernetes/pull/121252

### CODE REVIEW

**Comment by tukwila** [comment]
> Please limit your change to English only, in this PR. Do not touch other localization files.

yes, i restored.

**Comment by sftim** [comment]
/retitle Mark TopologyManager feature gate as removed in v1.29

**Comment by reylejano** [comment]
this probably should have been to the `dev-1.29` branch

**Comment by tengqm** [comment]
Oops, my bad.

**Comment by tengqm** [comment]
With the revert PR merged, we need a new one that targets dev-1.29.

**Pull request merged**
