### PR TITLE
small typo

### PR DESCRIPTION
**Pull request by harinder-jabal**
small typo

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/29115#issuecomment-886263402

**Review by anubha-v-ardhan — APPROVED** [review]

**Comment by bradtopol** [comment]
@harinder-jabal Thank you for your contribution. Please sign the CLA so we can review your PR.

**Comment by reylejano** [comment]
Hi @harinder-jabal , since there is no action on signing the CLA and this PR needs a rebase, I'm closing the PR.
Feel free to re-open when you have signed the CLA and rebased
/close

**Pull request closed without merging**
