### PR TITLE
Update replicaset.md for Issue #12205 with k8s.io/docs/concepts/workloads/controllers/replicaset/ 

### PR DESCRIPTION
**Pull request by SupriyaSirbi**
This Patch updates the Replicaset.md based on the review comment

### CODE REVIEW

**Comment by SupriyaSirbi** [comment]
Hello @zparnold I have closed the previous pull request and made the changes you have suggested. Please merge this pull request.

**Comment by Rajakavitha1** [comment]
Checked the review comments in : https://github.com/kubernetes/website/pull/12352
The review comments are incorporated in this PR.

/lgtm
/approve

**Pull request merged**
