### PR TITLE
Graduate JobTrackingWithFinalizers to beta

### PR DESCRIPTION
**Pull request by alculquicondor**
Update feature state

### CODE REVIEW

**Comment by tengqm** [comment]
I believe the `content/en/docs/reference/command-line-tools-reference/feature-gates.md` file needs an update as well.

**Review by soltysh — APPROVED** [review]
> I believe the content/en/docs/reference/command-line-tools-reference/feature-gates.md file needs an update as well.

yes it does, when it's fixed it lgtm

**Comment by alculquicondor** [comment]
Oops, feature gate details updated.

**Comment by chrisnegus** [comment]
@alculquicondor Thanks for filing this PR!

**Pull request merged**
