### PR TITLE
List JunperContrail CNI as Pod networking provider.

### PR DESCRIPTION
**Pull request by dineshb-jnpr**
This change is to list JuniperContrail/TungstenFabric as a provider
of Pod networking for a Kubernetes cluster.

Juniper's CNI solution has been available as a open source product
for couple of years now. It is a mature solution that has been
deployed in live clusters.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

### CODE REVIEW

**Comment by dineshb-jnpr** [comment]
dineshb-jnpr has been register as member of CNCF - Juniper

**Comment by dineshb-jnpr** [comment]
/assign @tengqm 
Hi @tengqm, assigning this review to you per comment by bot. Thanks.

**Comment by neolit123** [comment]
this PR adds JunperContrail as a pod networking plugin.
@kubernetes/sig-cluster-lifecycle-pr-reviews , has this been tested by anyone else before?

/hold

**Comment by dineshb-jnpr** [comment]
HI @neolit123,

Just wanted to drop in a few notes, to help this case.
JuniperContrail has had a CNI/networking plugin implementation for close to two years now. 
The code is opensource: https://github.com/Juniper/contrail-controller/tree/master/src/container
JuniperContrail is certified with Openshift and is also deployed in production environments.
It is listed as a third party plugin in CNI documentation: https://github.com/containernetworking/cni
Here are some deployment wikis: https://tungstenfabric.github.io/website/
Please feel free to reach out to me for any more info, that might help.

Good day & Thank you,
Dinesh

**Comment by neolit123** [comment]
@dineshb-jnpr 

thanks Dinesh, it's seems viable to add this.
waiting on sig-cluster-lifecycle members to confirm.

**Pull request merged**
