### PR TITLE
Resource name constraints (4)

### PR DESCRIPTION
**Pull request by tengqm**
xref: #17969, #19099, #18746

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
Pending #19106

**Comment by kbhawkey** [comment]
Page previews:
https://deploy-preview-19121--kubernetes-io-master-staging.netlify.com/docs/concepts/workloads/controllers/replicationcontroller/
https://deploy-preview-19121--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/endpoint-slices/
https://deploy-preview-19121--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/service/
https://deploy-preview-19121--kubernetes-io-master-staging.netlify.com/docs/concepts/configuration/secret/
https://deploy-preview-19121--kubernetes-io-master-staging.netlify.com/docs/concepts/architecture/nodes/
https://deploy-preview-19121--kubernetes-io-master-staging.netlify.com/docs/concepts/policy/resource-quotas/

**Pull request merged**
