### PR TITLE
Update addons.md

### PR DESCRIPTION
**Pull request by techiescamp**
Removed Weave Net as it points to a 404 page.

### CODE REVIEW

**Comment by kundan2707** [comment]
@techiescamp  Please sign cncf-cla first.

**Comment by kundan2707** [comment]
@techiescamp  deleting a link is not a good idea. it is also good to check other links first then only delete.

**Comment by kundan2707** [comment]
https://docs.cilium.io/en/latest/installation/cni-chaining-weave/
https://github.com/weaveworks/weave
above links clould be used for the same.

**Comment by jihoon-seo** [comment]
The PR #45445 updated the link to point https://github.com/rajch/weave#using-weave-on-kubernetes instead.
I am going to close this PR.
If you have another suggestion, then please feel free to reopen this PR or open a new issue/PR.
/close

**Pull request closed without merging**
