### PR TITLE
Add English-Korean translation glossary

### PR DESCRIPTION
**Pull request by gochist**
Contents are migrated from [한글화팀 용어집](https://docs.google.com/spreadsheets/d/1BWKq_HYmt_p1RKzQJoPfCb4ZgBgxH_q3_mf9ujCmniw)

### CODE REVIEW

**Comment by ianychoi** [comment]
/lgtm

Minor note for future discussion: The term on the table should start with a capital letter, a small letter would be fine, or it would not matter at all?

**Comment by gochist** [comment]
> Minor note for future discussion: The term on the table should start with a capital letter, a small letter would be fine, or it would not matter at all?

@ianychoi We did not discuss about it ever. Following issue or PR will be welcomed.

**Comment by seokho-son** [comment]
@ianychoi  Since this PR already got LGTM, I hope to approve this PR to follow dev-1.16-ko.3 schedule. 
@gochist @ianychoi Thank you for your contribution and review !
/approve

**Pull request merged**
