### PR TITLE
Replace `Spec.SourceVolumeMode` with `spec.sourceVolumeMode`

### PR DESCRIPTION
**Pull request by atoato88**
This PR replaces `Spec.SourceVolumeMode` with `spec.sourceVolumeMode`.

/kind cleanup

### CODE REVIEW

**Comment by sftim** [comment]
Is there a problem using the name VolumeSnapshots? We often use plural for APIs (Deployments, Pods, Jobs, Nodes etc) and Kubernetes makes this possible.

**Comment by atoato88** [comment]
Thank you for the response.

I found some places which use following style:
```
`<kind>`s
```
e.g. [here](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#persistentvolumeclaimresize) uses same style.
```
`PersistentVolumeClaim`s
```

But your comment is correct and I can find some places use "\<kinds\>" style.
So I cancel my suggest about "\<kind\>s" style.

Just single update:
-  change "Spec.SourceVolumeMode" wth "spec.sourceVolumeMode"

**Comment by atoato88** [comment]
/retitle Replace `Spec.SourceVolumeMode` with `spec.sourceVolumeMode`

**Review by sftim — COMMENTED** [review]
/approve

**Comment by atoato88** [comment]
Thank you for qiuck review and detailed comments!

**Pull request merged**
