### PR TITLE
[WIP] Adding multilingual support to the Kubernetes Docs website.

### PR DESCRIPTION
**Pull request by anvithks**
This is a WIP for adding multilingual support to the K8s docs site.  
The issue we are trying to address is to add a language switcher and allow the user to switch between the language of her/his choice. Currently work is on in the Chinese translation and we will use the same for our development purposes.  
Some of the points to be noted:  

- The content here is not updated. This will be taken care of before raising the actual PR.
- There are some bugs and lots of missing content as this is still a WIP.  

Please find my notes below into the process / steps I followed and my findings so far.  

- Created a basic jekyll site from scratch. Using the actual repository was not working out. I created a new site and then used the configurations from the the existing site. Some of the configs are still to be put into place.  
- Moved the index.html file and css/, images/, js/, folders into a common assets folder. This did not work.  
- Moving to assets folder breaks everything. Need to find url redirection method. Currently the files get duplicated inside the respective language folders.  
- Moved the _inlcudes and _layouts folder.  
- Home page is up with kubernetes website theme.  
- Added a working language switcher.  
- Added chinese and english language keys.  
- Inserted the translation keys in the index.html file.  
- Added docs and docs/home folder and the tutorials and kubernetes basics folders.  
- Served all of the above in the demo site.  
- The site was generated in cn and en.  
- Missing some assets served from the SCSS files.  
- The multilingual plugin takes care of the URLS for the most part but changes need to be made at file level. All the files in the root directory need to be modified and some front matter added. The contents for the same will have to be placed in the respective language folders. ( _i18n/en or _i18n/cn )  
- Served the documentation home page from the language files.  
- Assets are now being copied in to the generated language folders. Need to explore how to retain only one assets folder.  
- Served the partners page from the language bundle.  
- Trying to move the files from the current kubernetes site one by one.  
- Checked the functioning of the polyglot plugin.  
- The polyglot plugin works in a different manner. All files have to be in the root directory 
For every language support the file names have to be appended with the language code.
This does not seem like the best approach.  
- Currently facing some issue with serving the website pages if they are in nested folders.  
- The format of the pages needs to be changed in some instances.  
- Exploring the option of dropping the files in place as is and serving them.  

### Current method of translating a file.
- Keep a file in the site root folder. Usually {site.url}  
- Keep the translated files or content in the /<lang_folder>/<path_to_file>/ . Usually  {site.url} / {site.baseurl}  

### Steps to run this installation.
- Install Jekyll and Bundler. Will need to have all the dependencies that are needed to run the k8s docs site.
- clone the repo.  
- checkout the i18n branch.  
- To serve the site locally I have added two extra config parameters in the _config.yml file. 
- host: localhost  set this to the IP address you want to serve it off or the localhost
- port: 7200  The port you want to serve it.  
- run the command to serve the site. (make build serve or jekyll serve depending on you use the make file or not)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7033)

### CODE REVIEW

**Comment by dhilipkumars** [comment]
cc: @chenopis @zacharysarah

**Comment by chenopis** [comment]
There is a Travis error:
> **The command "go get -t -v k8s.io/website/test" failed and exited with 1 during .**
>
> [0K$ go get -t -v k8s.io/website/test
Fetching https://k8s.io/website/test?go-get=1
Parsing meta tags from https://k8s.io/website/test?go-get=1 (status code 404)
package k8s.io/website/test: unrecognized import path "k8s.io/website/test" (parse https://k8s.io/website/test?go-get=1: no go-import meta tags ())

**Comment by chenopis** [comment]
...And a Netlify error:
> 11:38:45 AM: ruby_dep-1.5.0 requires ruby version >= 2.2.5, which is incompatible with the
11:38:45 AM: current version, ruby 2.1.2p95
11:38:45 AM: Error during gem install
11:38:45 AM: Build complete: exit code: 1
11:38:45 AM: Error running command: Build script returned non-zero exit code: 1
11:38:45 AM: Failing build: Failed to build site
11:38:45 AM: failed during stage 'building site': Build script returned non-zero exit code: 1

**Comment by dhilipkumars** [comment]
@anvithks PTAL.

**Comment by anvithks** [comment]
@dhilipkumars @chenopis I have fixed the netlify errors and the preview site is now deployed.
I am not able to figure out the travis build error. 
I fixed the previous travis error, in that the /test folder is now available. 
 Request you to please help with identifying the issue.

**Comment by anvithks** [comment]
@chenopis Is this a code issue or an environment issue?

> `Fetching https://k8s.io/kubernetes/plugin/pkg/scheduler/api/latest?go-get=1
Parsing meta tags from https://k8s.io/kubernetes/plugin/pkg/scheduler/api/latest?go-get=1 (status code 200)
get "k8s.io/kubernetes/plugin/pkg/scheduler/api/latest": found meta tag main.metaImport{Prefix:"k8s.io/kubernetes", VCS:"git", RepoRoot:"https://github.com/kubernetes/kubernetes"} at https://k8s.io/kubernetes/plugin/pkg/scheduler/api/latest?go-get=1
get "k8s.io/kubernetes/plugin/pkg/scheduler/api/latest": verifying non-authoritative meta tag
package k8s.io/kubernetes/plugin/pkg/scheduler/api/latest: cannot find package "k8s.io/kubernetes/plugin/pkg/scheduler/api/latest" in any of:
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/k8s.io/kubernetes/plugin/pkg/scheduler/api/latest (from $GOROOT)
	/home/travis/gopath/src/k8s.io/kubernetes/plugin/pkg/scheduler/api/latest (from $GOPATH)
`

**Comment by chenopis** [comment]
@anvithks It looks like an upstream change in our testing toolchain. I'll try to track it down.

**Comment by dhilipkumars** [comment]
Hi! @chenopis , @anvithks has picked up a minor re-work to simplify this PR we could close this PR once we get that in.

**Comment by zacharysarah** [comment]
Closing in favor of Hugo migration.

**Pull request closed without merging**
