### PR TITLE
[pt-br] Fixed "Show the app in the terminal" URL

### PR DESCRIPTION
**Pull request by craigcomstock**
The app is listening on port 8080 so that must be included otherwise port 80 (default) is used and the curl request will fail.

Issue: 41259

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/hold
For en PR #41929 to get merged first.

**Comment by stormqueen1990** [comment]
/retitle [pt-br] Fixed "Show the app in the terminal" URL

**Review by stormqueen1990 — APPROVED** [review]
/lgtm

**Pull request merged**
