### PR TITLE
Issue with kubernetes.io/case-studies/chinaunicom/ 

### LINKED ISSUE #15180: Issue with kubernetes.io/case-studies/chinaunicom/
**This is a Bug Report**

**Problem:**

In this article, link to rancher is wrong at last section.

```
Plus, "companies can use the managed services offered by companies like Rancher, because they have already customized this technology," says Jia. "You can easily leverage this technology."
```

Link for "Rancher" above is `https://www.docker.com/`.

**Proposed Solution:**

Change link for "Rancher" `https://www.docker.com/` with `https://rancher.com/`.

**Page to Update:**
https://kubernetes.io/case-studies/chinaunicom/

### PR DESCRIPTION
**Pull request by medmedchiheb**
/cc @atoato88 

Fixes #15180

### CODE REVIEW

**Comment by atoato88** [comment]
LGTM for me.
Thank you for fast catching :tada:

**Comment by poothia** [comment]
lgtm

**Pull request merged**
