### PR TITLE
Define other usage monitoring solutions and fix for issue

### PR DESCRIPTION
**Pull request by thecrudge**
Define more resource usage monitoring solutions

### CODE REVIEW

**Comment by thecrudge** [comment]
Also provides fix for #13746

**Comment by Bradamant3** [comment]
@thecrudge thanks for your PR! Can you please take the fix for issue 13831 out of this PR, so that we can review content for one issue at a time? 13831 also needs additional triage, so if you could wait on a PR for it, that would also help. Thanks for understanding!

/hold

**Pull request merged**
