### PR TITLE
Fix a typo in blog "Introducing PodTopologySpread"

### LINKED ISSUE #23884: blog: typo in PodTopologySpread post
https://github.com/kubernetes/website/blob/5632ae93ea209d0849d702f25e1a13e4f8842980/content/en/blog/_posts/2020-05-05-introducing-podtopologyspread.md#L89

The specs should say `key: env`, not `key: type`

/sig scheduling
/cc @Huang-Wei @alculquicondor

### PR DESCRIPTION
**Pull request by Huang-Wei**
There is a typo in the image "advanced-usage-1.png" of blog [Introducing PodTopologySpread](https://kubernetes.io/blog/2020/05/introducing-podtopologyspread/): `key: type` (in the left bottom yaml snippet) should be corrected to `key: env`.

Fixes #23884.

### CODE REVIEW

**Comment by adtac** [comment]
LGTM

**Comment by sftim** [comment]
Preview: https://deploy-preview-23886--kubernetes-io-master-staging.netlify.app/blog/2020/05/introducing-podtopologyspread/

**Comment by sftim** [comment]
As it's a one-line fix:
/approve

**Comment by Huang-Wei** [comment]
Thanks @sftim !

@adtac Could you /lgtm?

**Comment by adtac** [comment]
/lgtm

But I don't have the permission to /lgtm things, as the bot would say right after my comment :)

**Pull request merged**
