### PR TITLE
Clean up duplicated SASS and CSS

### LINKED ISSUE #10643: Duplicated selectors in SASS
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

There are duplicated selectors in SASS.

**Proposed Solution:**

Remove Duplicated selectors from SASS and CSS.

**Page to Update:**

n/a

### PR DESCRIPTION
**Pull request by tnir**
This PR fixes duplicated selectors in SASS as well as CSS.

Closes #10643

Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

### CODE REVIEW

**Comment by Bradamant3** [comment]
@tnir can you fix merge conflicts please?

/assign @lucperkins

**Comment by lucperkins** [comment]
@tnir Make sure to resolve the merge conflict in `sass/_base.sass` and then regenerate the CSS using `make sass-build`.

**Comment by mistyhacks** [comment]
Closing because the conflicts have not been addressed for 23 days. If you get a chance to fix them, please reopen this PR.

**Pull request closed without merging**
