### PR TITLE
KEP-2436 Leader Migration: to beta

### PR DESCRIPTION
**Pull request by jiahuif**
This PR updates docs as a result of https://github.com/kubernetes/enhancements/issues/2436 graduating to beta. 

Implementation: https://github.com/kubernetes/kubernetes/pull/103533

### CODE REVIEW

**Comment by PI-Victor** [comment]
please make sure you open one PR, this could've been addressed in https://github.com/kubernetes/website/pull/28816
/assign @chrisnegus

**Comment by PI-Victor** [comment]
hello @jiahuif, is this PR ready for review, the deadline for PRs ready for review is tomorrow, if it is, could you please change the title, if not, please make sure it's ready before the deadline. Thank you!

**Comment by jiahuif** [comment]
Hello @PI-Victor This PR is now complete and ready for review. Note that the scope is now more than changing heading because new features have been added during beta graduation.

**Comment by jiahuif** [comment]
For technical reviews:

/assign @jpbetz @cheftako

**Comment by PI-Victor** [comment]
LGTM! i will defer the LGTM command to someone that can provide the tech review

**Comment by jpbetz** [comment]
Looks good technically

/lgtm

**Pull request merged**
