### PR TITLE
Add description on concept overview ID page 

### PR DESCRIPTION
**Pull request by WilliamChang80**
I've added some description in page https://kubernetes.io/id/docs/concepts/overview/ based on main page in https://kubernetes.io/docs/concepts/overview/. I also removed object management part on /overview directory because currently, its not used on main site

### CODE REVIEW

**Comment by irvifa** [comment]
Why there’s lots of deleted pages there?

**Comment by WilliamChang80** [comment]
> Why there’s lots of deleted pages there?

Because for object management session its not used on en page for now and its not exist on the https://kubernetes.io/docs/concepts/overview/

**Comment by danninov** [comment]
> > Why there’s lots of deleted pages there?
> 
> Because for object management session its not used on en page for now and its not exist on the https://kubernetes.io/docs/concepts/overview/
> 
> Or should i keep it instead of deleting it?

All pages in `concept/overview/object-management-kubectl` is moved to `tasks/manage-kubernetes-objects/` in this PR #14481. Please move those pages to task folder and fix links in related pages.

**Comment by irvifa** [comment]
Before deleting a document I think it’s encouraged to check whether the docs is moved into different link or not. 🙂 Please fix this accordingly.

**Comment by WilliamChang80** [comment]
I see, thank you for the reminder. I'll fix it soon

**Comment by WilliamChang80** [comment]
I've updated it, feel free to drop comments if there are any suggestion or mistakes 😃

**Comment by WilliamChang80** [comment]
Is there any update on this PR?

**Review by irvifa — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
