### PR TITLE
Add KubeCon 2021 banner, April 30 - May 7 2021

### PR DESCRIPTION
**Pull request by celestehorgan**
Signed-off-by: Celeste Horgan <celeste@cncf.io>

Adds a banner for KubeCon 2021 to help with registration. This also adds the `/static/announcements` directory, so that any images that go with announcements can be kept somewhere tidy :) 

cc: @kubernetes/steering-committee for approval.

### CODE REVIEW

**Comment by kbhawkey** [comment]
@celestehorgan . The banner looks great!
Aside, the banner sub-text on the "Partners" and "CaseStudies" pages is styled differently.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-27844--kubernetes-io-master-staging.netlify.app/blog/
/approve

**Comment by kbhawkey** [comment]
Whoops, forgot this content requires special approval.

**Comment by celestehorgan** [comment]
@kbhawkey – @liggitt's already signed off, so I think you're good to merge!

**Comment by mrbobbytables** [comment]
/approve
👍

**Pull request merged**
