### PR TITLE
Update labels.md

### PR DESCRIPTION
**Pull request by zdxgs**
As shown in the picture:
标签错误
Correct the syntax error shown in the picture

### CODE REVIEW

**Comment by windsonsea** [comment]
It would be better if you can check this file through.

**Comment by zdxgs** [comment]
> It would be better if you could check this file through.

OK, I'll check the whole file

**Comment by zdxgs** [comment]
> It would be better if you could check this file through.

Hello,I checked the whole file and found no other obvious spelling mistakes.

**Comment by windsonsea** [comment]
/lgtm

Thanks.

Next time, you can have a try to compare the en version and find some upstream changes if any.

For example, we normally run the command in the k8s folder to find differences:
```
./scripts/lsync.sh content/zh-cn/docs/concepts/overview/working-with-objects/labels.md
```

**Comment by zdxgs** [comment]
> For example, we normally run the command in the k8s folder to find differences:

OK, thanks. I'll try it next time

**Pull request merged**
