### PR TITLE
[ru] Updated ru.toml

### PR DESCRIPTION
**Pull request by shurup**
The Russian TOML file is now up-to-date with the original (English) version. New translations have been added, small fixes for the old ones provided, and the resorting made (so now it uses alphabetical order).

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hello @kubernetes/sig-docs-ru-owners & @kubernetes/sig-docs-ru-reviews , PTAL. I am not trying to overstep and impose here and I realize that the cadence in localizations is fairly slower for approvals & reviews. However, if the lack of approvers/reviewers is a challenge in moving PRs forward and merits a discussion in the localization subproject meeting, please voice out. Alternately, please feel free to reach out to the localization or docs leads privately if you're unable to or aren't comfortable bringing it up in the meeting.

**Comment by shurup** [comment]
@kirkonru @Arhell can you, please, have a quick look at it?

**Review by Arhell — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
