### PR TITLE
Trim whitespaces in manifests

### PR DESCRIPTION
**Pull request by makocchi-git**

### CODE REVIEW

**Comment by makocchi-git** [comment]
[preview is here](https://deploy-preview-25344--kubernetes-io-master-staging.netlify.app/docs/concepts/policy/pod-security-policy/)
[original](https://kubernetes.io/docs/concepts/policy/pod-security-policy/)

**Review by sftim — COMMENTED** [review]
Thanks
/lgtm

**Comment by kbhawkey** [comment]
Thanks @makocchi-git 
/label tide/merge-method-squash

**Comment by kbhawkey** [comment]
Since there is a hold until the release is out, would you rebase your changes to a single commit?
/remove-tide/merge-method-squash

**Comment by kbhawkey** [comment]
Still trying out the commands 😕 
/remove-tide merge-method-squash

**Comment by makocchi-git** [comment]
@kbhawkey (cc @sftim)
Thank you for your comments. I squashed.

**Comment by kbhawkey** [comment]
Trying this again,
/remove-label tide/merge-method-squash

**Pull request merged**
