### PR TITLE
Fix errors in the kcm config API

### PR DESCRIPTION
**Pull request by tengqm**
For some unknown reason, the API group wasn't parsed correctly.

### CODE REVIEW

**Comment by shannonxtreme** [comment]
This is just regenerating the file right? 

/lgtm

**Comment by tengqm** [comment]
> This is just regenerating the file right?
> 
> /lgtm

yes.

**Review by sftim — COMMENTED** [review]
/approve

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
