### PR TITLE
Merge release-1.12 to release-1.13

### PR DESCRIPTION
**Pull request by chenrui333**
Capture the contributors' commits during the release migration
relates to https://github.com/kubernetes/website/pull/14014

- PR from `release-1.12` to `release-1.13`
- Resolve conflicts
- Filter out the non-zh contents

cc @fleeto @markthink

### CODE REVIEW

**Comment by chenrui333** [comment]
I will try to update this PR tomorrow, relates to #14143

**Comment by zhangxiaoyu-zidif** [comment]
@chenrui333 
1. Do not includes other translation languages' files. if you want to modify them, just send other PRs.
2. Resolve the conflicts.

Many thanks :)

**Comment by tengqm** [comment]
My gut feeling is that we are wasting our lives doing this cherry-picking. For many PRs to be cherry-picked, there are changes to multiple languages. We will have to distinguish very carefully which file should be included and which one should not. If you look closer into the files being checked in, you can find many files are broken by the git diff marks, i.e. "<==", "=====>". 

We are doing this simply to preserve the commit history, right?

My observation is that we as a community focus on getting things done right rather than maintaining a good record of contributions. I'm not saying that contribution history or review comments are not useful. I'm trying to understand whether we can just get the contents copied and merged if we cannot preserve the commit log.

**Comment by chenrui333** [comment]
@zhangxiaoyu-zidif @tengqm 

I realize if I continue work on this PR, the work would pollute the release-1.12 branch (the original PR has some issue). So I follow the strategy and create a new PR (https://github.com/kubernetes/website/pull/14171) instead.

**Pull request closed without merging**
