### PR TITLE
[ja] remove redundant modifier 

### PR DESCRIPTION
**Pull request by iterable-company**
In the Japanese translation for the description of MaxPerPodContainer, the phrase 'the maximum number of dead containers each Pod can have' was translated as 'the maximum number of dead containers each Pod **pair** can have'.
It's presumed that the word 'Per' in 'MaxPerPodContainer' led to the addition of the word "pair" in the translation. 
I've removed the unnecessary "pair" from the Japanese description.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @nasa9084

**Review by t-inu — COMMENTED** [review]
Thanks!
/lgtm

**Review by nasa9084 — COMMENTED** [review]
Thanks

/approve

**Comment by atoato88** [comment]
Nice catch!!
LGTM :smile:

**Pull request merged**
