### PR TITLE
fix double bullet styling

### PR DESCRIPTION
**Pull request by cstoku**
fix double bullet styling.

There is sass code, but I seemed to edit the CSS directly from that moment, so I edited the CSS directly.

### CODE REVIEW

**Comment by cstoku** [comment]
[sample preview](https://deploy-preview-9480--kubernetes-io-master-staging.netlify.com/docs/setup/on-premises-vm/cloudstack/)
[corresponding original page](https://kubernetes.io/docs/setup/on-premises-vm/cloudstack/)

**Comment by steveperry-53** [comment]
/hold
@cstoku Thank for your pull request. We don't wan to accept this, because we have chosen a different approach to fixing the double bullet problem in page TOCs. See #9149. The fix involves putting topics into the proper templates. We done all the topic under Tasks, Tutorials, and Concepts, but we haven't yet done the topics under Setup.

**Comment by zacharysarah** [comment]
Thanks, @cstoku and @steveperry-53. Closing this PR.

**Pull request closed without merging**
