### PR TITLE
adding missing close parenthesis

### PR DESCRIPTION
**Pull request by PK1312**
Just fixing a simple typo, a missing close parenthesis in the storage class docs.

### CODE REVIEW

**Comment by Krishnamohan-Yerrabilli** [comment]
:ok for me

**Review by Shubham82 — CHANGES_REQUESTED** [review]
[AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html)).

**Comment by PK1312** [comment]
@Shubham82 Done!

**Comment by Krishnamohan-Yerrabilli** [comment]
> Hi @PK1312 you have to put a close parenthesis before dot `.` like this:
> 
> (maximum supported by AWS, see [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html)).

Thanks for your thoughts on that Shubham :clap:

**Review by onlydole — APPROVED** [review]
LGTM, thank you for this edit, @PK1312! 

/lgtm

**Pull request merged**
