### PR TITLE
Fix KubeCon banner

### PR DESCRIPTION
**Pull request by sftim**
- match event theme
  background color copied from https://github.com/cncf/artwork/blob/master/examples/other.md
- fix broken logo link

/priority important-soon

@zacharysarah FYI

### CODE REVIEW

**Comment by kbhawkey** [comment]
Yes, to fixing the broken link (noticed in a local build). Not sure if the color needs to be switched out.

**Comment by kbhawkey** [comment]
Hold for review
/hold

**Comment by sftim** [comment]
I copied the color from the official conference logo. Seems like that's the right one to use.

**Pull request merged**
