### PR TITLE
[pt-br] add content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md

### PR DESCRIPTION
**Pull request by DonatoHorn**

### CODE REVIEW

**Comment by windsonsea** [comment]
Please remove the zh-cn file. You only need to cover the pt-br version in this PR, thanks.

**Comment by stormqueen1990** [comment]
Hi there!

It seems something went wrong with the rebase in this branch. If you need
any help to fix this, please don't hesitate to reach out on the
#kubernetes-docs-pt channel.

/hold for branch correction

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-kind bug feature support
/remove-language de en es fr hi id it ja ko pl ru uk vi zh
/remove-sig release

**Comment by stormqueen1990** [comment]
Hi there, @DonatoHorn! 👋 

I'm putting the hold back on this one because there are many conflicts that must be solved on the `content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md` file, and the changes to the following files must be reverted before this PR can be merged:
* `content/pt-br/includes/task-tutorial-prereqs.md`
* `content/zh-cn/docs/tasks/configure-pod-container/assign-pods-nodes.md`

If you need any help please don't hesitate to reach out on Slack. 😃 

/hold

**Pull request closed without merging**
