### PR TITLE
spelling fix prepration for misspell check tool

### PR DESCRIPTION
**Pull request by charrywanganthony**
fix typos: misspell check will error out in 1.10 becourse of these typos 

ref: #7651

### CODE REVIEW

**Comment by bradtopol** [comment]
The commit message on this is not very detailed.  Can you please add more detail on the types of cleanup you are doing to prepare for the misspell tool and what assumptions this tool will be making so that it works properly?

**Comment by Bradamant3** [comment]
Also, is there a reason to target the 1.10 release? We deploy continually to master, and there's nothing here I see that's 1.10 specific. It seems to me that there's no reason not to merge to master, after we understand the cleanup and the tool better. If I'm missing something, please clarify.

**Comment by CaoShuFeng** [comment]
> What I'm not so sure is about the cherry-pick step. Maybe it is okay to propose the same patch to both branches?

The 1.10 branch will become master branch in the future?
I am not very sure either.

**Comment by charrywanganthony** [comment]
These typos are all fixed in master at defferent PR already.

**Comment by Bradamant3** [comment]
If these typos are all fixed at master in a different PR, we do not need this PR. The 1.10 branch merges to master on release (it isn't published yet). And changes to master are merged back to the 1.10 branch as of today. So closing as unneeded.

**Pull request closed without merging**
