### PR TITLE
[wip] testing mermaid generated svg

### PR DESCRIPTION
**Pull request by kbhawkey**
Investigating mermaid live editor and plugin options to generate SVG files from mermaid code.
Here is an SVG generated from the mermaid code in PR #23283 .
Thinking:
create a directory in repo for mermaid source files
generate SVGs from mermaid source and link SVG to page include location
save SVGs in static/images/docs/mermaid
include SVG image on page

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page which includes mermaid generated SVG file:
/docs/concepts/services-networking/ingress/

**Comment by kbhawkey** [comment]
👋 @sftim, Any thoughts?

**Comment by Mythyo1** [comment]
Closed.

**Comment by sftim** [comment]
The generated diagram looks OK to me @kbhawkey 

(and it's fine to tidy it further up later)

**Comment by kbhawkey** [comment]
Testing the sizing/resizing of the generated image compared to dynamically generated
image on the page.
/close

**Pull request closed without merging**
