### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by andrei-matei**
Fix typo in text.

### CODE REVIEW

**Comment by DanyC97** [comment]
@andrei-matei thank you for the fix.

before we can review and approve it , can you please sign the CLA ?

**Comment by cody-clark** [comment]
I think it's okay as is. Typically "an" precedes a vowel sound which is the case in the acronym SSH (pronounced es-es-aitch, not a librarian's "shh!").

**Comment by andrei-matei** [comment]
@cody-clark Ah, OK, I thought it's always an before a vowel and a before everything else. But you might me right. I can delete this, it seems I did not have CLA so I can delete this PR. Is that OK?

**Comment by Guaris** [comment]
> @cody-clark Ah, OK, I thought it's always "an" before a vowel and "a" before everything else. But you might be right. I can delete this, it seems I did not have CLA so I can delete this PR. Is that OK?

In this case, "an ssh" is the correct use.

**Comment by rlenferink** [comment]
As agreed above, `an SSH` will be kept.

/close

**Pull request closed without merging**
