### PR TITLE
Small french translation rule enhancement

### PR DESCRIPTION
**Pull request by Raphux**
French rule says "s'il", not "si il"
https://www.projet-voltaire.fr/regles-orthographe/si-il-fait-beau-ou-sil-fait-beau/

### CODE REVIEW

**Comment by zacharysarah** [comment]
@Raphux 👋 Welcome to Kubernetes! It looks like you're trying to merge to an outdated dev branch (`dev-1.15`) instead of `master`. Please change the base of the PR before proceeding.

In case you have not already met, please allow me to introduce you to @remyleone, who leads the French localization project.

/hold
/assign @remyleone

**Comment by remyleone** [comment]
@Raphux pas de soucis pour merger une fois qu'un rebase est fait :)

**Comment by jimangel** [comment]
Hey there! @Raphux, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jimangel** [comment]
Given the lack of activity since a month ago and no CLA signed, I will close this issue. Feel free to open it back up after the CLA is signed! Thanks!

/cc @remyleone

**Pull request closed without merging**
