### PR TITLE
[ID] Rename "Job" Concept page.

### PR DESCRIPTION
**Pull request by ariscahyadi**
Rename Job page name and update respective page contains Job links as mentioned in #28772 

/language id
@kubernetes/sig-docs-id-reviews

### CODE REVIEW

**Review by habibrosyad — COMMENTED** [review]
Thanks @ariscahyadi 
/lgtm

need approval for `static/_redirects` cc @irvifa.

**Review by sftim — COMMENTED** [review]
LGTM!

I would group redirects by localization @ariscahyadi - mainly so that people working on redirects for one localization don't trigger merge problems for another localization.

(future enhancement) we might be able to get Hugo to render the redirection list out, covering multiple localizations.

**Comment by ariscahyadi** [comment]
I think somebody need to approve it @kubernetes/sig-docs-id-owners @kubernetes/sig-docs-id-reviews

**Comment by habibrosyad** [comment]
> I think somebody need to approve it @kubernetes/sig-docs-id-owners @kubernetes/sig-docs-id-reviews

In @kubernetes/sig-docs-id-owners only @irvifa can do this, she has wider approval scope, while we are only limited to sig docs id. Or maybe someone from sig docs, @sftim could you help us for approving this one since you seemed already done a review for this PR?

**Review by irvifa — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
