### PR TITLE
[zh] fix The problem of missing translation

### LINKED ISSUE #25114: submodule google/docsy need to update
**This is a Bug Report**

**Problem:**

Submodule `google/docsy` need to update，current version lack of i18n translation for `Create child page`

Upgrade of `google/docsy` can solve this problem, see it in https://github.com/google/docsy/tree/master/i18n

image

### PR DESCRIPTION
**Pull request by zhaojizhuang**
**Why:**
fix #25114, Submodule `google/docsy` need to update，current version lack of i18n translation for `Create child page`
image

**Resolve:**

update submodule `google/docsy` to latest for fixing  i18n lack

**From** `Commit | 0f6717470e74b274e9f554a5ebf2465f2123d6a9` **To**  `Commit | 239c501278c7252ec0517acb5984cef76b85a478 ` (latest version of master,`Commit Message	Merge pull request #374 from google/LisaFC-patch-2 Small update to print docs`)

### CODE REVIEW

**Comment by zhaojizhuang** [comment]
assign @sftim

**Comment by kbhawkey** [comment]
Hold for review
/hold

**Comment by kbhawkey** [comment]
@zhaojizhuang , Can you explain what is "lacking in i18n"? I'd like to understand why it is important
to update docsy now. Thanks!

**Comment by sftim** [comment]
I suggest @zhaojizhuang you could use this PR description:
> Update `docsy` theme submodule to more recent Docsy release to address missing localization for Chinese.
> See issue #25114 for screenshot of bug.

**Comment by zhaojizhuang** [comment]
> I suggest @zhaojizhuang you could use this PR description:
> > Update `docsy` theme submodule to more recent Docsy release to address missing localization for Chinese.
> > See issue #25114 for screenshot of bug.

thanks @sftim , @kbhawkey you can see this issue #25114 for screenshot of bug.

**Comment by tengqm** [comment]
@zhaojizhuang Thanks for the contribution. I just noticed that problem also. I don't know though if we have a better way to solve this and I don't understand why Docsy has its own i18n subdirectory. Does it mean we will have to watch two i18n directories for string localizations?

**Comment by zhaojizhuang** [comment]
> @zhaojizhuang Thanks for the contribution. I just noticed that problem also. I don't know though if we have a better way to solve this and I don't understand why Docsy has its own i18n subdirectory. Does it mean we will have to watch two i18n directories for string localizations?

@tengqm For This `page mete link` is defined in the hugo  theme `Docsy`,  maybe update is the best way to solve this problem. see https://github.com/google/docsy/blob/master/layouts/partials/page-meta-links.html#L25

**Comment by tengqm** [comment]
@zhaojizhuang Don't take me wrong. I'm not questioning this PR. I'm thinking loudly about the appropriate process in the future.

**Comment by zhaojizhuang** [comment]
@tengqm Yes, Maybe it is more appropriate to maintain one i18n directory in the future.

**Comment by kbhawkey** [comment]
Yes , I noticed that the "Create child page" was added to the theme.
I am not sure how important this feature is for a page.
I am not against upgrading the theme now, just want to make sure that the site needs/wants to update the theme.
As a site, we can override the text for this component.

**Comment by zhaojizhuang** [comment]
> Yes , I noticed that the "Create child page" was added to the theme.
> I am not sure how important this feature is for a page.
> I am not against upgrading the theme now, just want to make sure that the site needs/wants to update the theme.
> As a site, we can override the text for this component.

@kbhawkey Yes, I don't think you object to this PR. And you mention （`we can override the text for this component.`）is worth considering. But I have no idea about it now ,can you point out how to override?

**Comment by kbhawkey** [comment]
@zhaojizhuang . 
Have a look at `website/i18n/zh.toml`. The theme also has a file with the same name.
The theme provides localized strings for the main UI components.
You can change the strings by adding the same field with a different value to `website/i18n/zh.toml`.
/hold cancel

**Comment by zhaojizhuang** [comment]
> @zhaojizhuang .
> Have a look at `website/i18n/zh.toml`. The theme also has a file with the same name.
> The theme provides localized strings for the main UI components.
> You can change the strings by adding the same field with a different value to `website/i18n/zh.toml`.
> /hold cancel

@kbhawkey Done!     cc @tengqm @sftim

**Comment by zhaojizhuang** [comment]
Page preview
https://deploy-preview-25116--kubernetes-io-master-staging.netlify.app/zh/docs/reference/kubectl/overview/

**Comment by tengqm** [comment]
This looks like a cleaner and viable fix.
/lgtm

**Comment by kbhawkey** [comment]
Thanks @zhaojizhuang .
/approve

**Pull request merged**
