### PR TITLE
[pt-br] Cleanup Portuguese localization reviewers sections

### PR DESCRIPTION
**Pull request by stormqueen1990**
### Changes

* Remove empty reviewers sections and reviewers sections that contain reviewers who are not reviewers for the Portuguese localization.

/cc @jcjesus @edsoncelio @devlware
/kind cleanup

### CODE REVIEW

**Comment by jcjesus** [comment]
> ### Changes
> * Remove empty reviewers sections and reviewers sections that contain reviewers who are not reviewers for the Portuguese localization.
> 
> /cc @jcjesus @edsoncelio @devlware /kind cleanup

Why not look on github to see who did the translation?
We can keep track of the translators' history.

**Comment by stormqueen1990** [comment]
> Why not look on github to see who did the translation? We can keep track of the translators' history.

Reviewers are restricted to people who are a part of the org, so not every person that edited a page is eligible to be a reviewer.
Blunderbuss also tries to determine reviewers based on past changes, do you consider that to be insufficient? Relevant docs: https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/#blunderbuss-selection-mechanism

**Comment by jcjesus** [comment]
> 
Hi @stormqueen1990 !
I understood now, so, I think we can go to remove, I will go ahead with my review and approve.
Thanks for the explanation.

**Review by jcjesus — APPROVED** [review]
Thanks, well done @stormqueen1990!

**Comment by jcjesus** [comment]
@stormqueen1990 can you resolve this conflict and let me now after, please?

**Comment by stormqueen1990** [comment]
> @stormqueen1990 can you resolve this conflict and let me now after, please?

@jcjesus sure, will do!

**Pull request merged**
