### PR TITLE
Add redirect to /docs/home/ for Hindi

### PR DESCRIPTION
**Pull request by sftim**
Ensure that https://k8s.io/hi/docs/ redirects to https://k8s.io/hi/docs/home/

/language hi

### CODE REVIEW

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/29353

**Review by Arhell — COMMENTED** [review]
/assign @anubha-v-ardhan

**Comment by anubha-v-ardhan** [comment]
/lgtm
Thank you @sftim :)

**Pull request merged**
