### PR TITLE
Changed the redisslave version from v1 to v3.

### LINKED ISSUE #14160: Got an error "crashloopbackoff" when run redis slave in Guestbook example app
**Problem:**
Got an error "crashloopbackoff" when run this step "Apply the Redis Slave Deployment from the redis-slave-deployment.yaml file".

**Proposed Solution:**
Problem resolved when I change the image version to v3:
gcr.io/google_samples/gb-redisslave:v3

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/guestbook/#start-up-the-redis-slaves

**Kubernetes Version:**
v1.14.0

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
Fixes #14160 

**Changes**
- Changed the version of redisslave from v1 to v3

### CODE REVIEW

**Comment by gochist** [comment]
@rajvaibhavdubey Thank you! Could you please open separate PRs for each language? There's a [guideline](https://kubernetes.io/docs/contribute/intermediate/#working-with-localized-content) limiting PRs to a single language.

**Comment by cdrage** [comment]
Otherwise, LGTM on my end :)

**Comment by rajvaibhavdubey** [comment]
Yeah Sure :+1:

**Comment by oussemos** [comment]
cc @kubernetes/sig-docs-en-owners @kubernetes/sig-docs-ko-owners @kubernetes/sig-docs-ja-owners

**Pull request merged**
