### PR TITLE
Fix example tests

### PR DESCRIPTION
**Pull request by tengqm**
This PR updates the go.mod file so that tests of the example manifests
are run against the 1.20 branch. The missing test cases for newly added
examples are also added. To perform tests on your local machine, run the
following command on the root of your local clone:
    
```
go test k8s.io/website/content/en/examples
```

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
This PR depends on #26027

**Comment by celestehorgan** [comment]
Tested locally,

/lgtm

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
