### PR TITLE
[zh] synchronize remove highly-available-master.md

### PR DESCRIPTION
**Pull request by shuaijinchao**
/language zh

### CODE REVIEW

**Comment by tengqm** [comment]
Is it possible this page is moved somewhere? We may want to move the file rather than delete and retranslate the content.

**Comment by shuaijinchao** [comment]
> Is it possible this page is moved somewhere? We may want to move the file rather than delete and retranslate the content.

What do you recommend? Seeing that this document does not have a global reference, the English document has also deleted the document file.

---

你有什么建议吗？我看到这个文件在全局中已经没有了任何引用，且英文文档中已经将该文件移除。

**Comment by tengqm** [comment]
It's fine to drop the file since it was removed in the English site anyway.

**Pull request merged**
