### PR TITLE
Generate reference doc for 1.22

### PR DESCRIPTION
**Pull request by PI-Victor**
Generated API Reference docs for 1.22 release.

/assign @jimangel @irvifa @sftim 

/cc @reylejano 

/hold till release day

p.s.: This should be merged right after the official 1.22 branch is cut, for the time being it's built on an rc tag.

### CODE REVIEW

**Comment by PI-Victor** [comment]
maybe i mixed these up while following the docs handbook, maybe this is the PR that's supposed to be merged: https://github.com/kubernetes/website/pull/28635. can anyone shed some light?

**Comment by PI-Victor** [comment]
i got this error while building these ref docs:
```
mkdir -p gen-compdocs/build
make -C gen-compdocs
make[1]: Entering directory '/tmp/tmp9xx4ofar/src/github.com/kubernetes-sigs/reference-docs/gen-compdocs'
go run main.go build kube-apiserver
go: k8s.io/kubernetes@v0.0.0 requires
	github.com/Azure/azure-sdk-for-go@v55.0.0+incompatible: missing go.sum entry; to add it:
	go mod download github.com/Azure/azure-sdk-for-go
make[1]: *** [Makefile:2: all] Error 1
make[1]: Leaving directory '/tmp/tmp9xx4ofar/src/github.com/kubernetes-sigs/reference-docs/gen-compdocs'
make: *** [Makefile:69: comp] Error 2
```
maybe someone can shed some light into this, i'm not sure how this impacts the docs.

**Comment by kbhawkey** [comment]
Hi @PI-Victor .
The reference docs build (Makefile + dependencies) changed last release. I don't think you can build the reference docs with a release candidate tag. There are several pages/references to build:
- component tool pages
- kubectl reference
- one-page API reference (HTML)
- API reference pages (Markdown)

**Comment by tengqm** [comment]
I'll take a look at the `azure-sdk-for-go` issue.

**Comment by PI-Victor** [comment]
> Hi @PI-Victor .
> The reference docs build (Makefile + dependencies) changed last release. I don't think you can build the reference docs with a release candidate tag. There are several pages/references to build:
> 
>     * component tool pages
> 
>     * kubectl reference
> 
>     * one-page API reference (HTML)
> 
>     * API reference pages (Markdown)

@kbhawkey  i'm using the process described in the release handbook:
https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#generate-the-reference-documentation

if this is no longer used, i can close this PR in favor of https://github.com/kubernetes/website/pull/28635

**Comment by sftim** [comment]
I don't think #28635 covers all the changes we need. It's just the API reference; we also need other generated reference documentation.

I think we need this PR _and_ #28635 _and_ another PR to update generated docs for components such as `kube-apiserver`.

**Comment by sftim** [comment]
We definitely want this once it's technically correct
/approve

**Comment by PI-Victor** [comment]
i've regenerated this from the 1.22 tag that was just cut.

**Comment by kbhawkey** [comment]
👀

**Comment by kbhawkey** [comment]
Did this PR merge accidentally?

**Pull request merged**
