### PR TITLE
[hi] Fix wrong code highlighting

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/40437/files
/assing @divya-mohan0209

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Comparing with corresponding 'en' PR, the proposed set of changes LGTM. Thanks!

/lgtm

**Comment by kundan2707** [comment]
Comparing both outlook.
new one looks better

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Pull request merged**
