### PR TITLE
Update kubespray.md

### PR DESCRIPTION
**Pull request by lushndm**
Rename hosts.ini to inventory.ini

### CODE REVIEW

**Comment by DanyC97** [comment]
@lushndm can you please sign the CLA ?

**Comment by bradtopol** [comment]
@lushndm Thank you for your contribution. Please sign the CLA so we can accept your PR for review.

**Comment by lushndm** [comment]
I signed it

**Comment by bradtopol** [comment]
@Atoms can you review this change for technical accuracy?  Simply add a /lgtm if it is correct and I can take it from there.  Thanks! 
/cc @Atoms

**Comment by Rajakavitha1** [comment]
Hi @bradtopol ,

I checked https://github.com/kubernetes-sigs/kubespray/pull/4447/files.
As per https://github.com/kubernetes-sigs/kubespray/pull/4447/files the updated made by @lushndm seems technically correct.

Please state your approval.

/lgtm

**Pull request merged**
