### PR TITLE
Added Bosnian language

### PR DESCRIPTION
**Pull request by hajro92**

### CODE REVIEW

**Comment by hajro92** [comment]
Cannot sign CLA,  because I am not receiving e-mail verification from linuxfoundation to my e-mail address.

**Comment by sftim** [comment]
Would you like any help with the contributor licence agreement @hajro92 ?

**Comment by hajro92** [comment]
> Would you like any help with the contributor licence agreement @hajro92 ?

Yes please, I registered on linuxfoundation website in order to sign CLA, but I never received confirmation email from linuxfoundation to verify my account.

**Comment by sftim** [comment]
[Troubleshooting](https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting) lists some steps you can follow: mainly, these are about letting the Linux Foundation know that you've run into problems.

**Pull request closed without merging**
