### PR TITLE
Formatting fixes

### PR DESCRIPTION
**Pull request by stevencorrea**
"```sh ... ```" blocks are currently displayed in the documentation. Render these into code blocks 
by removing indentation.

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for the fix
/sig cluster-lifecycle

current:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

vs this fix:
https://deploy-preview-16626--kubernetes-io-master-staging.netlify.com/docs/setup/production-environment/tools/kubeadm/high-availability/

/lgtm

**Comment by stewart-yu** [comment]
Thanks @stevencorrea 
/lgtm
/approve

**Pull request merged**
