### PR TITLE
Implementation of the Link Decorator function for processing localised links 🈂️

### PR DESCRIPTION
**Pull request by Andygol**
### Description

I'm pleased to introduce the Link Decorator feature, which automatically transforms links in localised documents if the referenced documents have been localised. This feature eliminates the need to manually add language codes to links.

This was also inspired by the https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/_markup/render-link.html template, which is already included in Hugo.

### The logic is as follows

```mermaid
graph LR;

src_link("Link in a doc…")


src_link-->none_localized_link("… is not localized\n starts with `/…`")-->
check_for_localization{"if a localized\ndoc exists"}-- "yes, it is" -->add_lng_prefix("Add lang-code\nprefix to the link")

src_link-->indoc_link("… is in the same doc\nstarts with`#` symbol")
src_link-->already_localized_link("… is already localized\n starts with\n`/lang-code/…`")
src_link-->ext_link("…is an external link\nstarts with protocol\n [https:|mailto:|…] ")

ext_link & already_localized_link & indoc_link ---> asis("Keep it as is")
check_for_localization-- "no, it isn't" -->asis
```

The current approach fully implements the logic of link decoration by adding a language prefix to localised documents where it is not explicitly specified. Links with a hard-coded https://kubernetes.io/ or https://k8s.io/ are considered external and processed as such, even if there are localised versions of the link in the documentation. Handling such cases significantly complicates the code and processing time, and it is easier to correct such links directly in the text of documents.

I hope that the adoption of this PR will significantly improve the usability of the documentation and simplify the work of translators to maintain it.

### Issue

This effort was inspired by a previous discussion about adding language code manually when localising documents. — https://github.com/kubernetes/website/issues/18403

/hold Depends on: PR https://github.com/kubernetes/website/pull/47612 — Fixed flag deprecations and updated Hugo version to latest

/cc @sftim as per your request in [Slack](https://kubernetes.slack.com/archives/C1J0BPD2M/p1724247542463049?thread_ts=1724226266.705639&cid=C1J0BPD2M).

### CODE REVIEW

**Comment by tengqm** [comment]
Some clarifications:

- This code automagically works without having to revise any existing English pages, right?
- The existing language prefix added by localization teams still works with this code, right?
- The fallback to English page is transparent, right?
- Any statistics about the build time after introducing this code?

**Comment by Andygol** [comment]
> Some clarifications:
> 
> - This code automagically works without having to revise any existing English pages, right?
> - The existing language prefix added by localization teams still works with this code, right?
> - The fallback to English page is transparent, right?
> - Any statistics about the build time after introducing this code?
> 

@tengqm 
Absolutely, all already localized links works; in case you've referred translated documents but do not add language prefix explicitly, it will be added by decorator; if there's absent localized link, language code won't be added. After merging this PR  manual addition of language codes will be deprecated. You may check Chinese test page https://deploy-preview-47620--kubernetes-io-main-staging.netlify.app/zh-cn/docs/test/.

See netlify response above to find build log.

**Comment by sftim** [comment]
/area web-development

Nice to see this arrive!

**Comment by Andygol** [comment]
As PR #47612 has been merged, feel free to approve this on as well🙏

**Comment by Andygol** [comment]
Re-run test to engage new build with updated Hugo
/test all

**Comment by sftim** [comment]
(aside) This repo does not really use Prow's `/test` command.

**Comment by Andygol** [comment]
> (aside) This repo does not really use Prow's `/test` command.

🙄 It would be great to re-engage netlify build process somehow to streamline review.

**Comment by tengqm** [comment]
The only concern from me is about the build time overhead (supposing that all conversions are done during build time). However, as a standalone processor, we can easily disable it if it goes wrong.
/approve

**Comment by Andygol** [comment]
@Tengqm thank you for your approval, however, here needs the approval of someone from sig-docs-website-owners 🛎️

**Comment by sftim** [comment]
> It would be great to re-engage netlify build process somehow to streamline review.

PRs welcome (from anyone)! But it's not a priority.

**Pull request merged**
