### PR TITLE
add improvement as per issue 28427

### PR DESCRIPTION
**Pull request by AndrewTtofi**
Add improvement for documentation per [issue](https://github.com/kubernetes/website/issues/28427)

### CODE REVIEW

**Comment by AndrewTtofi** [comment]
@tengqm checks seems to be failing (timeout). do I need to retrigger the checks with a dummy commit?

**Review by ydFu — APPROVED** [review]
/lgtm

**Comment by tengqm** [comment]
> @tengqm checks seems to be failing (timeout). do I need to retrigger the checks with a dummy commit?

Yes. Please.

**Comment by AndrewTtofi** [comment]
should I re-raise the PR? checks seems to fail.

> 12:51:32 PM: Build exceeded maximum allowed runtime

**Pull request merged**
