### PR TITLE
Fix issue of broken links to translated docs

### LINKED ISSUE #22102: Issue of broken links to translated docs
**This is a Bug Report**

**Problem:**
There are tons of translated docs contains broken links to the translated docs in content/ko/docs directory.

**Proposed Solution:**
Fix these broken links to the translated docs.

**Page to Update:**
https://kubernetes.io/...

/language ko

### PR DESCRIPTION
**Pull request by pjhwa**
Closes #22102 

This PR contains the following translated docs which has the broken links.
- content/ko/docs/concepts/architecture/nodes.md
- content/ko/docs/concepts/cluster-administration/addons.md
- content/ko/docs/concepts/cluster-administration/cluster-administration-overview.md
- content/ko/docs/concepts/configuration/overview.md
- content/ko/docs/concepts/containers/images.md
- content/ko/docs/concepts/containers/runtime-class.md
- content/ko/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
- content/ko/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
- content/ko/docs/concepts/extend-kubernetes/extend-cluster.md
- content/ko/docs/concepts/overview/components.md
- content/ko/docs/concepts/overview/working-with-objects/field-selectors.md
- content/ko/docs/concepts/policy/limit-range.md
- content/ko/docs/concepts/policy/pod-security-policy.md
- content/ko/docs/concepts/policy/resource-quotas.md
- content/ko/docs/concepts/services-networking/connect-applications-service.md
- content/ko/docs/concepts/services-networking/endpoint-slices.md
- content/ko/docs/concepts/services-networking/ingress.md
- content/ko/docs/concepts/services-networking/service.md
- content/ko/docs/concepts/storage/persistent-volumes.md
- content/ko/docs/concepts/storage/storage-classes.md
- content/ko/docs/concepts/storage/volume-snapshots.md
- content/ko/docs/concepts/storage/volumes.md
- content/ko/docs/concepts/workloads/controllers/daemonset.md
- content/ko/docs/concepts/workloads/controllers/deployment.md
- content/ko/docs/concepts/workloads/controllers/replicaset.md
- content/ko/docs/concepts/workloads/controllers/replicationcontroller.md
- content/ko/docs/contribute/_index.md
- content/ko/docs/contribute/new-content/open-a-pr.md
- content/ko/docs/contribute/participating.md
- content/ko/docs/contribute/review/reviewing-prs.md
- content/ko/docs/contribute/style/write-new-topic.md
- content/ko/docs/reference/glossary/cni.md
- content/ko/docs/reference/glossary/device-plugin.md
- content/ko/docs/reference/glossary/minikube.md
- content/ko/docs/reference/kubectl/cheatsheet.md
- content/ko/docs/reference/tools.md
- content/ko/docs/reference/using-api/api-overview.md
- content/ko/docs/setup/_index.md
- content/ko/docs/setup/best-practices/multiple-zones.md
- content/ko/docs/setup/production-environment/tools/kops.md
- content/ko/docs/tasks/_index.md
- content/ko/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume.md
- content/ko/docs/tasks/access-application-cluster/web-ui-dashboard.md
- content/ko/docs/tasks/administer-cluster/change-default-storage-class.md
- content/ko/docs/tasks/administer-cluster/cluster-management.md
- content/ko/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- content/ko/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md
- content/ko/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
- content/ko/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md
- content/ko/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
- content/ko/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace.md
- content/ko/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md
- content/ko/docs/tasks/administer-cluster/network-policy-provider/romana-network-policy.md
- content/ko/docs/tasks/configure-pod-container/assign-memory-resource.md
- content/ko/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity.md
- content/ko/docs/tasks/configure-pod-container/configure-pod-initialization.md
- content/ko/docs/tasks/configure-pod-container/static-pod.md
- content/ko/docs/tasks/debug-application-cluster/determine-reason-pod-failure.md
- content/ko/docs/tasks/debug-application-cluster/resource-metrics-pipeline.md
- content/ko/docs/tasks/inject-data-application/define-command-argument-container.md
- content/ko/docs/tasks/manage-gpus/scheduling-gpus.md
- content/ko/docs/tasks/manage-kubernetes-objects/declarative-config.md
- content/ko/docs/tasks/manage-kubernetes-objects/imperative-command.md
- content/ko/docs/tasks/manage-kubernetes-objects/imperative-config.md
- content/ko/docs/tasks/manage-kubernetes-objects/kustomization.md
- content/ko/docs/tasks/network/validate-dual-stack.md
- content/ko/docs/tasks/run-application/delete-stateful-set.md
- content/ko/docs/tasks/run-application/horizontal-pod-autoscale.md
- content/ko/docs/tasks/tools/install-minikube.md
- content/ko/docs/tutorials/stateful-application/zookeeper.md
- content/ko/docs/tutorials/stateless-application/expose-external-ip-address.md
- content/ko/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md
- content/ko/docs/tutorials/stateless-application/guestbook.md

### CODE REVIEW

**Comment by gochist** [comment]
@pjhwa 감사합니다! 혹시 작업을 위한 자동화 툴이나 스크립트를 사용하셨나요?
/lgtm

**Comment by gochist** [comment]
제가 저자와 같은 회사 소속이라 다른 승인자께서 승인해주시면 좋겠습니다.

/unassign
/assign @ianychoi

**Comment by pjhwa** [comment]
> @pjhwa 감사합니다! 혹시 작업을 위한 자동화 툴이나 스크립트를 사용하셨나요?

그냥 다 뒤지는 허접한 스크립트로 돌렸습니다. ^^; 뭐 수작업이 반이지만요. 찾아주는게 어딘가 하고 돌렸습니다. ㅎㅎ

**Comment by gochist** [comment]
Held for the same reason with https://github.com/kubernetes/website/pull/22270#issuecomment-653452369

**Comment by pjhwa** [comment]
링크 수정은 Bug fix라 생각하여 master를 타겟으로 했었습니다. 브랜치를 현재 작업 브랜치로 변경하겠습니다.

**Comment by gochist** [comment]
@pjhwa 감사합니다. 내용은 LGTM입니다. 하나의 커밋으로 squash 가능하실까요?

**Comment by gochist** [comment]
git remote의 origin이 pjhwa님의 fork, upstream이 kubernetes 조직의 저장소로 설정되어 있다면(`git remote -v`로 확인), 

```
$ git remote -v
origin	git@github.com:pjhwa/website (fetch)
origin	git@github.com:pjhwa/website (push)
upstream	git@github.com:kubernetes/website (fetch)
upstream	git@github.com:kubernetes/website (push)
```

다음과 같이 하나의 커밋으로 squash 하실 수 있습니다.

```
git fetch upstream dev-1.18-ko.7
git fetch origin fix-22102
git checkout upstream/dev-1.18-ko.7 -b fix-22102-squash
git merge --squash origin/fix-22102
git commit
git push --force origin fix-22102-squash:fix-22102
```

**Comment by pjhwa** [comment]
@gochist 자세한 설명 감사합니다! 스쿼시 작업 완료했습니다.

**Comment by gochist** [comment]
/lgtm
@ianychoi PTAL

**Pull request merged**
