### PR TITLE
[ko] Update task tookls and network in dev-1.21-ko.2

### PR DESCRIPTION
**Pull request by seokho-son**
Related issue: #27764

Update outdated translation for following Korean doc.

1. [ ] M32.  `content/en/docs/tasks/network/validate-dual-stack.md`  | 7(+XS) 4(-)
1. [ ] M33.  `content/en/docs/tasks/tools/install-kubectl-linux.md`  | 1(+XS) 2(-)
1. [ ] M34.  `content/en/docs/tasks/tools/install-kubectl-macos.md`  | 25(+S) 10(-)
1. [ ] M35.  `content/en/docs/tasks/tools/install-kubectl-windows.md`  | 1(+XS) 30(-)

### CODE REVIEW

**Review by pjhwa — COMMENTED** [review]
@seokho-son 오타 하나 있어 의견남깁니다~ ^^

**Comment by seokho-son** [comment]
@pjhwa 리뷰 감사합니다! 업데이트 및 스쿼싱 처리 완료하였습니다.. ^^

**Comment by seokho-son** [comment]
PTAL @kubernetes/sig-docs-ko-owners

**Pull request merged**
