### PR TITLE
Fix zh content

### PR DESCRIPTION
**Pull request by Yxnt**
1. 去除段落中出现的冗余 "节点" 内容 
2. 英文单词后增加空格以保证阅读美观

### CODE REVIEW

**Comment by Yxnt** [comment]
I signed it, but i signed with wrong email :(

**Review by Arhell — COMMENTED** [review]
/assign @tengqm

**Comment by tengqm** [comment]
CLA is still a failure after over a month, and the PR is a trivial one.
/close
Please feel free to reopen and resolve the issues.

**Pull request closed without merging**
