### PR TITLE
fix some links with 404 error

### PR DESCRIPTION
**Pull request by SataQiu**
Fix some links with 404 error.
I have checked the validity of all links started with "https://godoc.org"!

### CODE REVIEW

**Comment by neolit123** [comment]
/hold
@SataQiu thanks!

please remove the kubeadm* releated changes because it duplicates with my PR here:
https://github.com/kubernetes/website/pull/10283

the minikube changes are fine!

**Comment by neolit123** [comment]
> please remove the kubeadm* releated changes because it duplicates with my PR here:
#10283

LGTM, thanks

**Comment by SataQiu** [comment]
Thanks！I have removed the kubeadm* releated changes. @neolit123

**Comment by neolit123** [comment]
thanks
/hold cancel

**Pull request merged**
