### PR TITLE
Update pod-security-standards-hostprocess-state

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

Updating the feature status of `HostProcess` pods/containers on https://kubernetes.io/docs/concepts/security/pod-security-standards/ to reflect that feature is in beta and on-by-default

/assign @liggitt

### CODE REVIEW

**Comment by zacharysarah** [comment]
@marosset 👋🏻 Thanks for the update. Can you please re-work this PR to implement the [feature state shortcode](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#feature-state)? Thanks in advance.

**Comment by marosset** [comment]
The changes look OK to me.
/hold cancel
/label tide/merge-method-squash

https://deploy-preview-34264--kubernetes-io-main-staging.netlify.app/docs/concepts/security/pod-security-standards/#baseline (changes are right below this anchor)

**Pull request merged**
