### PR TITLE
Fixing markdown to patch error on K8 website

### PR DESCRIPTION
**Pull request by bigorangemachine**
Showing up with triple ticks 'shell' on website

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

Trying to fix a [small rendering issue](https://i.imgur.com/lb2Rrl6.png) on the docs site

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by bigorangemachine** [comment]
I re-requested they send the CLA and its not working.  

I'm pretty sure I completed the sign up process. I don't know why that check is failing.

**Comment by bigorangemachine** [comment]
@jaredbhatti

I don't know why the CLA check is failing?

**Comment by tfogo** [comment]
Hi @bigorangemachine, sorry for the difficulties. Did you sign the CLA using the same email address that's connected to your GitHub account? Could you try signing again?

**Comment by bigorangemachine** [comment]
@tfogo

Yup! I signed up using my GH account and the main email associated with that account. I already gave a Google contributions via the CLA on the same account :/

**Comment by Rajakavitha1** [comment]
Hi @bigorangemachine please check the troubleshooting section here: https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting.
If you are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/

**Comment by Rajakavitha1** [comment]
/close

Hi @bigorangemachine !!!
Closing this PR for now. Please feel free to reopen after you sign the CLA.

**Pull request closed without merging**
