### PR TITLE
Update single-page API reference for 1.28

### PR DESCRIPTION
**Pull request by tengqm**
This PR refreshes the generated API reference for v1.28, reproduced with the tuned generator.

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
Let's see if it works as expected.

**Comment by tengqm** [comment]
/hold cancel
Things worked as intended.

**Comment by sftim** [comment]
LGTM
/approve

https://deploy-preview-43139--kubernetes-io-main-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.28/ looks like an API reference

**Comment by windsonsea** [comment]
The [preview](https://deploy-preview-43139--kubernetes-io-main-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.28/) looks so beautiful with a switch between dark and light.
/lgtm

**Pull request merged**
