### PR TITLE
Generate Reference Documentation for kubectl Commands

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
Signed-off-by: zhuzhenghao <zhenghao.zhu@daocloud.io>

/kind bug

Generate Reference Documentation for kubectl Commands 

FIX issue https://github.com/kubernetes/website/issues/38626

### CODE REVIEW

**Comment by tengqm** [comment]
dup of #38697

**Comment by Zhuzhenghao** [comment]
> dup of #38697

See this line :
https://github.com/kubernetes/website/blob/c43f71161e586b5f9da7f178d6b90eb01758e895/static/docs/reference/generated/kubectl/kubectl-commands.html#L1749

This pr fix issue https://github.com/kubernetes/website/issues/38626.

It seems that we have different purposes?

**Comment by tengqm** [comment]
@Zhuzhenghao My bad. I wasn't rebasing the generator. Please check #38697 again.

**Review by sftim — CHANGES_REQUESTED** [review]
Please don't commit `static/docs/reference/generated/kubectl/node_modules` - that path doesn't look right to me.

**Comment by Zhuzhenghao** [comment]
@tengqm Thanks for checking. I has closed this pr. See u later

**Pull request closed without merging**
