### PR TITLE
[ar] Fix website building issues in the AR localization

### PR DESCRIPTION
**Pull request by mboukhalfa**
When building the website locally I have noticed these issues. They are blocking serving the website locally !

### CODE REVIEW

**Comment by adowair** [comment]
Thanks for catching this @mboukhalfa. Could you please share the steps to build/test locally? I think we on the team (myself included) aren't aware of this!

**Comment by mboukhalfa** [comment]
> Thanks for catching this @mboukhalfa. Could you please share the steps to build/test locally? I think we on the team (myself included) aren't aware of this!

### Clone the repo and checkout the branch 
```
git clone https://github.com/kubernetes/website.git
cd website
git checkout dev-1.29-ar.1
```
### Fetch submodule dependencies
```
make module-init
```
### Run the website using a container
```
make container-serve
```
For more details of if you are not on linux then check https://github.com/kubernetes/website?tab=readme-ov-file#prerequisites

**Comment by adowair** [comment]
Confirming that this fixes the build issues on branch
```console
$ make container-image
$ make container-serve
```

/approve

**Review by adowair — APPROVED** [review]

**Pull request merged**
