### PR TITLE
updated valid frontend image

### PR DESCRIPTION
**Pull request by kundan2707**
Fixes: #44224 
previous image was nonexistent so example was not working

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Comment by divya-mohan0209** [comment]
@kundan2707 Please refer to [this comment](https://github.com/kubernetes/website/issues/44224#issuecomment-1844145822). We'd prefer if you make the changes across all English website files excepting the Blog ones on this PR in order to reduce the approval/reviewing churn.

/remove-lgtm

**Comment by divya-mohan0209** [comment]
For clarity, these are the additional files requiring the image changes

```
content/en/examples/application/guestbook/frontend-deployment.yaml
20:        image: gcr.io/google_samples/gb-frontend:v5

content/en/docs/concepts/workloads/controllers/replicaset.md
103:    Image:        gcr.io/google_samples/gb-frontend:v3

```

**Comment by kundan2707** [comment]
@divya-mohan0209  i will make these change and push these changes again

**Comment by kbhawkey** [comment]
👋 @kundan2707 .
Are you able to locate and add the other files to this pull request?
Thanks

**Comment by kundan2707** [comment]
@kbhawkey I have identified changes and push changes by tomorrow

**Comment by kundan2707** [comment]
@divya-mohan0209  added all files. Please review

**Comment by sftim** [comment]
Thanks for the PR. As a reviewer, how can I validate that this change is appropriate to make?

(as well as verifying that the old page is wrong, I need to check that the new page is right)

**Comment by kundan2707** [comment]
@sftim  it can be checked by creating deployment using updated yaml if it succeed and then inspecting deployment detail and confirm.

**Comment by sftim** [comment]
> It can be checked by creating deployment using updated yaml if it succeed and then inspecting deployment detail and confirm.

Cool. And, you've done this?

**Comment by kundan2707** [comment]
> > It can be checked by creating deployment using updated yaml if it succeed and then inspecting deployment detail and confirm.
> 
> Cool. And, you've done this?

@sftim yes i have done.

**Review by dipesh-rawat — COMMENTED** [review]
The updated image looks good to me, especially since it now aligns with the [original tutorial ](https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook) on which k8s.io is based. Additionally, based on the author's confirmation of validation of the changes in https://github.com/kubernetes/website/pull/44225#issuecomment-1891191795

/lgtm

**Comment by kundan2707** [comment]
> As per [#44999 (comment)](https://github.com/kubernetes/website/pull/44999#discussion_r1477634648), maybe you forgot that you already had raised a PR for it.

sorry i missed that your one was also  for same file.

**Comment by kundan2707** [comment]
I found more appropriate image on dockerhub which is in sync with previous image 
https://github.com/Doublemine/gcr.io-mirror/blob/master/google-samples.md
updated all such image in en files

**Comment by reylejano** [comment]
Hi @kundan2707 , since this PR has needed a rebase for over a month, I'm closing this PR.
When you have time to work on this PR and rebase it, you can reopen the PR with a `/reopen` in a comment
/close

**Pull request closed without merging**
