### PR TITLE
[zh] update examples with test case

### PR DESCRIPTION
**Pull request by tengqm**
Sync changes to example and example test cases.

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
Pending #28452

**Comment by jihoon-seo** [comment]
Hello @tengqm

[[Netlify Deploy log](https://app.netlify.com/sites/kubernetes-io-master-staging/deploys/60cbf90875d50c0008f0b7ff)]
> Error building site: "/opt/build/repo/content/zh/docs/tasks/network/validate-dual-stack.md:318:1": failed to render shortcode "codenew": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/codenew.html:14:16": execute of template failed: template: shortcodes/codenew.html:14:16: executing "shortcodes/codenew.html" at <readFile $filename>: error calling readFile: stat /opt/build/repo/content/zh/examples/service/networking/dual-stack-ipv6-lb-svc.yaml: no such file or directory

PTAL! 😊

**Comment by jihoon-seo** [comment]
[[Another Netlify Deploy log](https://app.netlify.com/sites/kubernetes-io-master-staging/deploys/60cbfdb3d461cb0007e93acb)]

> Error building site: "/opt/build/repo/content/zh/docs/tutorials/stateless-application/guestbook.md:94:1": failed to render shortcode "codenew": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/codenew.html:14:16": execute of template failed: template: shortcodes/codenew.html:14:16: executing "shortcodes/codenew.html" at <readFile $filename>: error calling readFile: stat /opt/build/repo/content/zh/examples/application/guestbook/mongo-deployment.yaml: no such file or directory

PTAL! 😊

**Comment by tengqm** [comment]
The English change has been merged.
/hold cancel

**Review by chenrui333 — APPROVED** [review]
/approve

**Pull request merged**
