### PR TITLE
[ko] Restructure release directory and docs for Korean

### PR DESCRIPTION
**Pull request by seokho-son**
Path for release note has been changed in EN.

This PR restructures release directory and docs for Korean.

This PR also fix following outdated files. (#28079)

 R2. R096 content/en/docs/setup/release/version-skew-policy.md -> content/en/releases/version-skew-policy.md
 D1. content/en/docs/setup/release/_index.md
 D2. content/en/docs/setup/release/notes.md

### CODE REVIEW

**Comment by pjhwa** [comment]
수고하셨습니다~

/lgtm

**Comment by seokho-son** [comment]
PTAL: @kubernetes/sig-docs-ko-owners 
ko.3의 일정을 고려하여 빠른 처리를 부탁드립니다..^^

**Pull request merged**
