### PR TITLE
Choisir la bonne solution link updated!

### PR DESCRIPTION
**Pull request by hh**
Should fix https://github.com/kubernetes/website/issues/14475

Co-Authored-By: Cheikh Rouhou <CheikhRouhouInes94@gmail.com>
Co-Authored-By: Gergey Csatari <gergely.csatari@nokia.com>

### CODE REVIEW

**Comment by hh** [comment]
@icheikhrouhou would you mind updating the link on https://kubernetes.io/fr/docs/concepts/cluster-administration/ ?

**Comment by hh** [comment]
I invited you to edit on github with me on this branch.
Here is the link to directly make the change:

https://github.com/hh/website/edit/patch-1/content/fr/docs/concepts/cluster-administration/cluster-administration-overview.md

**Comment by sethmccombs** [comment]
Looks good! Thanks for taking this on! 
/lgtm

**Comment by hh** [comment]
This was the sharing.io style doc we created together today:

https://github.com/ii/k8s-conformance-docs/blob/master/contributing-cncf.org#steps

**Pull request merged**
