### PR TITLE
Update Ubuntu guide index page

### PR DESCRIPTION
**Pull request by tvansteenburgh**

### CODE REVIEW

**Comment by KodacMac1** [comment]
What do I do from here

**Comment by zacharysarah** [comment]
@tvansteenburgh 👋I'm closing this PR. We're declining to make further changes to Getting Started Guides because we're starting to migrate all platform-specific documentation away from kubernetes.io and linking instead to platforms' own docs.

I encourage you to make improvements to Ubuntu's docs instead, and think about where you'd like to point the link that will eventually replace this document on kubernetes.io. Thanks in advance!

**Comment by tvansteenburgh** [comment]
@zacharysarah Ah, good to know, thanks.

**Comment by tvansteenburgh** [comment]
@zacharysarah Hey, can you link me to the source for "We're declining to make further changes to Getting Started Guides because we're starting to migrate all platform-specific documentation away from kubernetes.io and linking instead to platforms' own docs." please?

I've been trying to find where this decision was made but can't find it. Thanks!

**Comment by xiangpengzhao** [comment]
@tvansteenburgh FYI: https://docs.google.com/document/d/1Ds87eRiNZeXwRBEbFr6Z7ukjbTow5RQcNZLaSvWWQsE/edit

Find the text "`Docs proposal: Move away from hosting Operating System/platform-specific and link to it instead` in the doc.

**Pull request closed without merging**
