### PR TITLE
Add a logo JSON-LD meta information about Kubernetes

### PR DESCRIPTION
**Pull request by remyleone**
https://developers.google.com/search/docs/data-types/logo

### CODE REVIEW

**Comment by remyleone** [comment]
@sftim can I get approve here?

**Comment by sftim** [comment]
I'd like this one to get an /lgtm first.

**Comment by sftim** [comment]
@remyleone you can find the current PR wrangler from https://github.com/kubernetes/website/wiki/PR-Wranglers

**Comment by remyleone** [comment]
@gochist :)

**Comment by gochist** [comment]
@sftim @remyleone I'm sorry for the delay. It took me a while to get used to the improved notification feature on GitHub. The wiki page seems to differ from the actual Wrangler. The most accurate seems to be the [Minutes Document] (https://docs.google.com/document/d/1ddHwLK3kUMX1wVFIwlksjTk0MsqitBnWPe1LRa1Rx5A/edit).

/assign @jimangel

**Pull request merged**
