### PR TITLE
Update footer navigating options

### PR DESCRIPTION
**Pull request by Abhik1998**

### CODE REVIEW

**Comment by philips** [comment]
What are you trying to do with this change?

**Comment by Abhik1998** [comment]
Actually we need to update 2 files 1 css file and the index file, this is for only html file and the other  PR is on process

**Comment by Rajakavitha1** [comment]
@Abhik1998  could you please commit all the files that need to changed in one PR and also please resolve the conflicts.

**Comment by tfogo** [comment]
Hi @Abhik1998, looks like you could put this change in #12842. Going to close this one.

/close

**Pull request closed without merging**
