### PR TITLE
an offense against the style guide.

### PR DESCRIPTION
**Pull request by ptux**
Evidence:
> Use code style for object field names

### CODE REVIEW

**Comment by ptux** [comment]
This is just a friendly reminder.

**Comment by Bradamant3** [comment]
@ptux please be patient. Reviewers get to PRs as they can, and often wait for the PR wrangler to handle small changes. Pinging us or adding vague comments won't make things move faster.

/lgtm
/approve

**Comment by ptux** [comment]
@Bradamant3 

Thank you for your review and advice.

I should be patient and I will be.

**Pull request merged**
