### PR TITLE
[ja]Remove content/ja/examples/admin/resource/cpu-constraints-pod-3.yaml

### PR DESCRIPTION
**Pull request by kinzhi**

### CODE REVIEW

**Comment by bells17** [comment]
It looks like content/ja/examples/admin/resource/cpu-constraints-pod-3.yaml is no longer in use.
(https://github.com/kubernetes/website/blob/release-1.23/content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md has not been translated into Japanese)

Therefore, I think it's okay to delete this file.
@nasa9084 @inductor What's your opinion on this?

**Comment by nasa9084** [comment]
消しちゃって良いと思います！

**Comment by Sea-n** [comment]
There are no `content/ja/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md` translated file, maybe it's better to remove the unused file.

**Comment by bells17** [comment]
@nasa9084 @Sea-n Thank you.

@kinzhi Would you remove this file?

**Comment by kinzhi** [comment]
> @nasa9084 @Sea-n Thank you.
> 
> @kinzhi Would you remove this file?

Thank you. I'd love to get the job done

**Comment by bells17** [comment]
@kinzhi Thank you.
/lgtm

**Comment by bells17** [comment]
@nasa9084 Would you approve this?

**Pull request merged**
