### PR TITLE
Apply templates to all concepts and tasks to fix double bullets in TOC

### PR DESCRIPTION
**Pull request by steveperry-53**
I created this PR to serve as a prototype for fixing the double bullet problem. This PR can also serve as a point of discussion for TOC and bullet issues.

This PR takes a free-form topic and converts it to a template-based topic.

Before the change, the TOC at the top of the page looked like this:

```
* * What is a node?
  * Node Status
    * Addresses
    * Condition
    * Capacity
    *Info
  * Management
    * Node Controller
    * Self-Registration of Nodes
    * Manual Node Administration
    *Node capacity
  * API Object
```

After changing to a template-based topic, the TOC at the top of the page looks like this:

```
* Node Status
* Management
* API Object
```

So the double bullet problem is gone, and things are working as designed by Hugo.

Topic preview: https://deploy-preview-9149--kubernetes-io-master-staging.netlify.com/docs/concepts/architecture/nodes/

The down side is that we no longer get subheadings in the TOC, We get only the level-2 headings. My understanding is that this just the way it is with Hugo. Maybe there's a way to get subheadings in a template-based topic in Hugo, but if there is, I don't know about it.

It's my view that all topics under Tasks, Tutorials, and Concepts should be based on a template. That is, we should not have free-form topics in those sections.

### CODE REVIEW

**Comment by steveperry-53** [comment]
Related PR: #9082

**Comment by mistyhacks** [comment]
I used the following type of command to find all of the concepts and tasks that don't have a content_template set:

```
$ grep -rL 'content_template' * | grep md |grep -v _index
```

**Concepts**:
```
architecture/cloud-controller.md
architecture/master-node-communication.md
architecture/nodes.md
cluster-administration/manage-deployment.md
cluster-administration/kubelet-garbage-collection.md
cluster-administration/networking.md
cluster-administration/logging.md
cluster-administration/certificates.md
cluster-administration/addons.md
overview/working-with-objects/names.md
overview/working-with-objects/namespaces.md
overview/working-with-objects/labels.md
overview/kubernetes-api.md
policy/resource-quotas.md
policy/pod-security-policy.md
storage/storage-classes.md
storage/persistent-volumes.md
workloads/pods/pod.md
workloads/controllers/cron-jobs.md
workloads/controllers/daemonset.md
workloads/controllers/jobs-run-to-completion.md
```

**Task**:
```
access-application-cluster/configure-cloud-provider-firewall.md
access-application-cluster/web-ui-dashboard.md
access-application-cluster/access-cluster.md
access-application-cluster/configure-dns-cluster.md
administer-cluster/cluster-management.md
administer-cluster/configure-multiple-schedulers.md
administer-cluster/namespaces-walkthrough.md
administer-cluster/reserve-compute-resources.md
administer-cluster/out-of-resource.md
administer-cluster/highly-available-master.md
administer-cluster/configure-upgrade-etcd.md
administer-cluster/developing-cloud-controller-manager.md
administer-cluster/static-pod.md
administer-cluster/guaranteed-scheduling-critical-addon-pods.md
administer-cluster/cpu-management-policies.md
administer-cluster/running-cloud-controller.md
administer-federation/secret.md
administer-federation/events.md
configure-pod-container/configure-service-account.md
configure-pod-container/translate-compose-kubernetes.md
debug-application-cluster/debug-application.md
debug-application-cluster/core-metrics-pipeline.md
debug-application-cluster/troubleshooting.md
debug-application-cluster/debug-application-introspection.md
debug-application-cluster/debug-cluster.md
debug-application-cluster/debug-pod-replication-controller.md
debug-application-cluster/logging-stackdriver.md
debug-application-cluster/audit.md
debug-application-cluster/resource-usage-monitoring.md
debug-application-cluster/events-stackdriver.md
debug-application-cluster/monitor-node-health.md
debug-application-cluster/logging-elasticsearch-kibana.md
debug-application-cluster/debug-service.md
federation/set-up-cluster-federation-kubefed.md
federation/federation-service-discovery.md
inject-data-application/podpreset.md
job/coarse-parallel-processing-work-queue.md
job/fine-parallel-processing-work-queue.md
job/parallel-processing-expansion.md
manage-gpus/scheduling-gpus.md
run-application/rolling-update-replication-controller.md
run-application/horizontal-pod-autoscale-walkthrough.md
run-application/horizontal-pod-autoscale.md
tls/managing-tls-in-a-cluster.md
```

**Comment by zacharysarah** [comment]
@steveperry-53 👋 
- I'm OK with requiring/enforcing templates on all content in Concepts/Tasks/Tutorials. 👍 

    Thanks to @mistyhacks, we have an exact inventory of files to change. 🙇 

- I'm OK with having only two levels of subheadings in a TOC. 

    Three-layer deep content that's extensive enough for a TOC restriction to be a genuine loss may be a sign that the page needs to be reorganized. 

TL,DR: 👍

**Comment by Bradamant3** [comment]
So ... stumbled on this PR this morning: https://github.com/kubernetes/website/pull/9164

Which looks as though it's trying to fix the TOC issue with the wrong approach. Could someone else take a look since I'm not feeling completely confident about my assessment? Or I'll revisit later today.

**Comment by mistyhacks** [comment]
Concepts are done. I'm about to do the tasks now.

**Comment by Bradamant3** [comment]
Point of clarification about the TOC and heading levels: because the page content starts at heading 2, we effectively have only one level of TOC atm. The kubadm HA topic is a case in point, and one where one more level would help users better understand at a glance just how much is involved in the setup.

**Comment by mistyhacks** [comment]
I'm carefully checking each file I modified and I'm down to `administer-cluster/highly-available-master.md` but need to stop for the day. I'll finish up tomorrow. There have definitely been some lessons learned.

**Comment by mistyhacks** [comment]
I checked all of the tasks, and this PR doesn't regress anything and improves most of them. It's not perfect, but I think it's ready.

/lgtm

**Pull request merged**
