### PR TITLE
Snyk fix 7935271cd8065bfe56c8b58b439345d5

### PR DESCRIPTION
**Pull request by Filipmoldovan**

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@Filipmoldovan Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by dipesh-rawat — COMMENTED** [review]
@Filipmoldovan It appears that this PR includes changes to files across multiple languages ([French](https://github.com/kubernetes/website/blob/7b5f5335ad97eec3a5b18d8301e1035e9d780b74/content/fr/examples/minikube/Dockerfile), [Chinese](https://github.com/kubernetes/website/blob/7b5f5335ad97eec3a5b18d8301e1035e9d780b74/content/zh-cn/examples/service/access/Dockerfile)) . However, docs follows different processes for each localization, and and we typically don't accept pull requests that impact multiple languages simultaneously. Modify and break this up into multiple PRs, where we have a single PR per language that would be great.  I hope this suggestion is helpful.

**Comment by dipesh-rawat** [comment]
/hold

Explicit hold till the PR targets single language.
_(OK to unhold when thats done)_

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by chenrui333** [comment]
yeah, it should be break down into language specific PRs. Also to me, I think it would be better to just sync from the en source, rather than change directly?

**Comment by Ritikaa96** [comment]
Hi @Filipmoldovan Are you willing to address the above suggestions?
It is recommended to do One PR per localisation rather than doing multiple localisation change in one PR.
> yeah, it should be break down into language specific PRs. Also to me, I think it would be better to just sync from the en source, rather than change directly?

**Comment by Ritikaa96** [comment]
Also please sign the CLA . for contribution related queries Please refer to [our developer guide](https://k8s.dev)

**Comment by divya-mohan0209** [comment]
@Filipmoldovan We'll be closing the PR since the CNCF CLA hasn't been signed for ~2 months.
/close

**Pull request closed without merging**
