### PR TITLE
[zh] sync scheduling-gpus.md

### PR DESCRIPTION
**Pull request by SSmallMonster**
Sync text with en:
```
content/zh-cn/docs/tasks/manage-gpus/scheduling-gpus.md
```

See [preview](https://deploy-preview-40075--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/manage-gpus/scheduling-gpus/) please.

### CODE REVIEW

**Comment by howieyuen** [comment]
@SSmallMonster 
please sign the CLA: https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by SSmallMonster** [comment]
> @SSmallMonster please sign the CLA: https://github.com/kubernetes/community/blob/master/CLA.md
> 
> After that, `/easycla` will work

@howieyuen Thank you for the reminder. The CLA has been signed, but for some reason, `/easycla` is not working. I am currently investigating the reason why.

**Comment by howieyuen** [comment]
how about make a force push ?

**Comment by SSmallMonster** [comment]
> how about make a force push ?

I have pushed again but not worked.

**Pull request merged**
