### PR TITLE
fixed typo in the docs

### LINKED ISSUE #38646: Typo in the command: The command should be kubeadm init rather than kubeadmin init
reference:  https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#start-a-kubelet-process-configured-via-the-config-file

### PR DESCRIPTION
**Pull request by akash-mohanto**
update `kubeadmin init` to `kubeadm init`
fixes #38646

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks!
/lgtm

**Review by neolit123 — COMMENTED** [review]
please add

```
fixes #38646
```

in the PR description to close the linked issue.

**Pull request merged**
