### PR TITLE
updated readme.md

### PR DESCRIPTION
**Pull request by deveshgoyal1000**
Hello!
Added (Read this in other languages:) line and mentioned all languages. 
where different-different languages can be easily visible and more approachable.
Thank you

<!-- ℹ️

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
I don't think this particularly adds value over the current format that we have. Could you please clarify what exactly is problematic with the tabular format using the same links currently?

**Comment by deveshgoyal1000** [comment]
> I don't think this particularly adds value over the current format that we have. Could you please clarify what exactly is problematic with the tabular format using the same links currently?

If you think so then okay.
-But for example:- if someone who don't understand english then how he will understand the meaning of [Localization ReadMes] and the tabular format is in the last of the page and possibilities of scrolling down is very less 
potential contributor may leave the page due to language differences.

-My change is more easy to understand and someone who doesn't know English can easily understand that this readme is available in different- different languages.

Thank you!

**Comment by natalisucks** [comment]
@deveshgoyal1000 I agree with @divya-mohan0209 – given you've listed the languages in English (as opposed to their own language or script), this change counteracts what you're trying to achieve. I believe the original version/format still works as intended.

**Comment by reylejano** [comment]
@deveshgoyal1000 , I agree with @natalisucks and @divya-mohan0209 comments
I'm closing this PR but feel free to reopen this PR if you feel otherwise and we can discuss further here on this PR
/close

**Pull request closed without merging**
