### PR TITLE
Branch sync - Merge master with dev 1.19

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Sync master with dev-1.19

cc: @zacharysarah @jimangel @kbarnard10

### CODE REVIEW

**Comment by spiffxp** [comment]
Commenting now that the PR that seems to have tripped up prow has been retitled https://github.com/kubernetes/website/pull/21428#issuecomment-641592295

**Comment by spiffxp** [comment]
closing/reopening to see if the message will come back, ref:
https://github.com/kubernetes/test-infra/blob/e7bfd2549148cf37e13f1709d949d79f73954583/prow/plugins/invalidcommitmsg/invalidcommitmsg.go#L157-L168

**Comment by spiffxp** [comment]
@zacharysarah @sftim @savitharaghunathan 
People with write or admin access to this repo can work around the problem described in https://github.com/kubernetes/test-infra/issues/17893 by manually removing the `do-not-merge/invalid-commit-message` label, as it's only applied if the code changes.

I'm removing it once again if you'd like to merge this branch as-is.  If the intent is to keep this open as a long running PR, we may want to consider a different approach

**Comment by zacharysarah** [comment]
@spiffxp Thanks for the help.
> If the intent is to keep this open as a long running PR, we may want to consider a different approach

This PR contributes to a long-running branch: `dev-1.19`, which may resurface the problem in #20785.

**Comment by zacharysarah** [comment]
All other commits pass/look valid, so I feel comfortable approving. Let's monitor #20785 to see whether the invalid commit message reappears.

/lgtm
/approve

**Pull request merged**
