### PR TITLE
Add "Ephemeral Container" to French glossary

### PR DESCRIPTION
**Pull request by bcheronn**

### CODE REVIEW

**Comment by sftim** [comment]
Please rebase this pull request against _master_ to bring in a work-around for issue #22222.

**Comment by sftim** [comment]
@bcheronn this PR has 37 (!) commits. Can you rebase it against _master_ from [k/website](https://github.com/kubernetes/website)

/hold
due to number of commits

**Comment by bcheronn** [comment]
@sftim Thanks for the feedback. I would appreciate a pointer on how to rebase properly. 1st time I have to do it.

**Comment by sftim** [comment]
Sorry, have not had time as yet. I hope someone (maybe me) can provide that help.

**Comment by kbhawkey** [comment]
Hello @bcheronn . Thanks for opening this PR.
In most cases, you should work toward one commit per pull request (and target one language).
The docs `Contribute` section has information about working with a local clone and [rebasing your work](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#merge-conflicts-and-rebasing).
If it is easier, you can take the relevant change from this PR and create a new PR.

**Comment by sftim** [comment]
On the command line, you could try:
```bash
git checkout master
git remote add upstream https://github.com/kubernetes/website.git # skip if you already have this set up
git fetch upstream master
git reset --hard upstream/master
git cherry-pick d75446eb68a07dc2786e595e2f861fd4d24c908b
git push origin master --force-with-lease
```

**Comment by kbhawkey** [comment]
Hello @bcheronn .
I am closing this pull request.
At any time, you can reopen this PR and resume work.
/close

**Pull request closed without merging**
