### PR TITLE
Add `batch.kubernetes.io/cronjob-scheduled-timestamp` annotation information to CronJob page

### PR DESCRIPTION
**Pull request by janetkuo**
### Description
Add `batch.kubernetes.io/cronjob-scheduled-timestamp` annotation information to CronJob page
 
### Issue
[kubernetes/enhancements#4026](https://github.com/kubernetes/enhancements/issues/4026)

### CODE REVIEW

**Comment by janetkuo** [comment]
I don't have access to edit https://github.com/kubernetes/website/pull/48498, so I created this PR to make sure it doesn't slip @chanieljdan

**Comment by chanieljdan** [comment]
Tech LGTM was given in https://github.com/kubernetes/website/pull/48498#issuecomment-2454610636

This PR cleans up a couple of nits

**Comment by reylejano** [comment]
If the annotation is not in the [well known labels, annotations, taints page](https://kubernetes.io/docs/reference/labels-annotations-taints/) then it should be added -- non-blocking

/approve

**Comment by soltysh** [comment]
Thanks Janet!

**Pull request merged**
