### PR TITLE
Run minikube docker-env in a shell-independent way

### PR DESCRIPTION
**Pull request by trishankatdatadog**

### CODE REVIEW

**Comment by gochist** [comment]
Thank you @trishankatdatadog . Please sign the CLA for further processing.

**Comment by trishankatdatadog** [comment]
@gochist Thank you! I did sign the CLA, I think, but not sure why it's not working...

**Comment by trishankatdatadog** [comment]
I signed it

**Comment by trishankatdatadog** [comment]
I filed a support ticket with Linux Foundation, as I can't figure out what's going on with the limited time I have

**Comment by trishankatdatadog** [comment]
I signed it

**Comment by trishankatdatadog** [comment]
@gochist Done, thanks!

**Pull request merged**
