### PR TITLE
add Dynatrace Kubernetes monitoring

### PR DESCRIPTION
**Pull request by ghaydtner**

### CODE REVIEW

**Comment by tengqm** [comment]
@ghaydtner Pls sign the CLA for this to be merged.

**Comment by jimangel** [comment]
Does Dynatrace fit on this list?

It looks like it's all opensource solutions with an asterisk for google (stackdriver being included with a deployment on GCE / GKE). If we do merge this, it would be helpful to update the opening line: "... Prometheus and Google Cloud Monitoring are two of the most popular." since Dynatrace would be a 3rd option.

Maybe a solution would be to have a section for OSS and a section for SaaS / paid for solutions.

**Comment by mistyhacks** [comment]
/assign @zacharysarah 

(for the concerns raised above)

**Comment by kminehart** [comment]
Is this really a good place for SaaS vendors to plug their products?

**Comment by zacharysarah** [comment]
@kminehart +1, that section shouldn't have passed editorial review. I'm willing to approve a PR to remove it.

**Comment by ghaydtner** [comment]
@zacharysarah @kminehart As @jimangel suggested, would it be a solution to have a section for OSS and a section for SaaS / paid for solutions? Google Cloud Monitoring ("Stackdriver") is also a SaaS/paid for solution.

**Pull request merged**
