### PR TITLE
Add option to install kubectl on Windows via scoop

### PR DESCRIPTION
**Pull request by goostleek**

### CODE REVIEW

**Comment by goostleek** [comment]
Thx @Rajakavitha1, your suggestion is now applied.

**Comment by goostleek** [comment]
I had to remove the first item 
> 1. Run the installation command:
It seems the list numbering is not continued but restarted from 1 if the previous list item contains tabs. Take a look 
image

Now it seems to look fine https://deploy-preview-12359--kubernetes-io-master-staging.netlify.com/docs/tasks/tools/install-kubectl/#install-on-windows-using-chocolatey-or-scoop.

**Comment by Rajakavitha1** [comment]
Checked  https://deploy-preview-12359--kubernetes-io-master-staging.netlify.com/docs/tasks/tools/install-kubectl/#install-on-windows-using-chocolatey-or-scoop. and it looks fine to me.
/lgtm
/approve

**Pull request merged**
