### PR TITLE
fix link in Kubernetes blog

### PR DESCRIPTION
**Pull request by neha-viswanathan**
Related to https://github.com/kubernetes/website/pull/24583#discussion_r505406175

### CODE REVIEW

**Comment by bboreham** [comment]
Did you want me to point out all the times this happened?

**Review by bboreham — APPROVED** [review]
Looks great, thanks!

**Comment by castrojo** [comment]
/lgtm

Thanks for your attention to detail!

**Review by sftim — COMMENTED** [review]
/lgtm

**Pull request merged**
