### PR TITLE
[WIP] Default Topology Spread constraints

### PR DESCRIPTION
**Pull request by alculquicondor**
Temporary placeholder

Enhancement issue: kubernetes/enhancements#1258

### CODE REVIEW

**Comment by makoscafee** [comment]
Hi @alculquicondor. I think this is supposed to be opened against [`dev-1.17`](https://github.com/kubernetes/website/tree/dev-1.17) and not master as it for that release.
Thanks.
/milestone 1.17

**Comment by daminisatya** [comment]
Thank you @makoscafee for helping out :D ✨

**Comment by daminisatya** [comment]
@alculquicondor 

This is a kind reminder since we're approaching the deadline for PR to be "Ready for Review" by Nov 15, 2019. Kindly update this PR.

**Comment by alculquicondor** [comment]
Hi @daminisatya, we are moving the enhancement to 1.18. Cloud you please clear the milestone?

**Comment by daminisatya** [comment]
Done! Thank you for the update!

**Comment by sftim** [comment]
@alculquicondor I see this feature is targeting an alpha in v1.18
Is it OK to /close this PR and start a similar one that targets the _dev-1.18_ branch?

If you prefer, you can change the base branch for this PR and revise it.

**Comment by alculquicondor** [comment]
/close

I'll reopen when we are ready to rebase. This is currently blocked by #85737

**Pull request closed without merging**
