### PR TITLE
Merge changes from dev-1.17-it.1 to dev-1.18-it.1

### PR DESCRIPTION
**Pull request by Fale**
As title. This substitute #19788

### CODE REVIEW

**Comment by sftim** [comment]
given the nature of this change (updating a branch), and the history of https://github.com/kubernetes/website/pull/19788
/lgtm
/approve

**Comment by sftim** [comment]
If you want branch _dev-1.18-it.1_ to have a Netlify preview @Fale that's also possible, I think.

**Comment by Fale** [comment]
@sftim I think that would help, thanks a lot :-)

**Comment by sftim** [comment]
Actually, the preview for PR #20538 provides this now.

**Pull request merged**
