### PR TITLE
Merged main into dev 1.30

### PR DESCRIPTION
**Pull request by drewhagen**
This PR syncs the dev-1.30 branch with main to keep the dev-1.30 branch up to date.

##### Note for new SIG Release Docs Shadows
This is called a branch sync, and we will be doing this twice a week throughout the release cycle as [described in the hanbook here.](https://github.com/kubernetes/sig-release/blob/b51237ddb556bb6d24e43d7424e55cb9e66694d5/release-team/role-handbooks/docs/Release-Timeline.md#%EF%B8%8F-periodically-merge-main-into-dev-future-release)
If you are a new SIG Release docs shadow and are curious about this, we'll be going over it soon! 😄 

cc: @katcosgrove @Princesso @Vyom-Yadav @chanieljdan @celestehorgan

### CODE REVIEW

**Review by Princesso — COMMENTED** [review]
I didn't find the Netlify deployment preview for this, but generally it /lgtm

**Review by Princesso — COMMENTED** [review]
/lgtm

**Comment by sftim** [comment]
> I didn't find the Netlify deployment preview for this PR. Also, I was thinking the commits were going to be squashed. If that doesn't apply here, then it generally looks good

- We haven't yet set up deployment previewing (the release docs team will request it from SIG Docs soon, I expect)
- We don't squash this kind of merge; we preserve the commits we're merging in so that Git can tell where they came from.

**Comment by katcosgrove** [comment]
/assign @divya-mohan0209 

> * We haven't yet set up deployment previewing (the release docs team will request it from SIG Docs soon, I expect)

@sftim I wasn't aware this was a thing. There isn't a handbook item directing the Docs lead to request this from SIG Docs, and I didn't request it last cycle, either. If that's something that that the Docs lead should be coordinating with y'all on, we'll need to get it added to the handbook.

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks for this!
/approve

**Pull request merged**
