### PR TITLE
Add label when data/i18n/**/*.toml is updated

### PR DESCRIPTION
**Pull request by Okabe-Junya**
following up to #42206

### Description

- `area/localization` label is added when `data/i18n/**/*.toml` is fixed

### Issue

Closes: #

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by Okabe-Junya** [comment]
/assign divya-mohan0209
for approval

/cc sftim 
as the author of 42206

**Review by sftim — COMMENTED** [review]
/lgtm

**Comment by sftim** [comment]
/retitle Add label when data/i18n/**/*.toml is updated

**Review by mengjiao-liu — COMMENTED** [review]
/lgtm

**Comment by Okabe-Junya** [comment]
/assign natalisucks
for approval

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Pull request merged**
