### PR TITLE
[en] fix incorrect pod-template-hash labels in deployment.md

### LINKED ISSUE #40751: Incorrect output of `pod-template-hash` label in `kubernetes.io/docs/concepts/workloads/controllers/deployment`
**This is a Bug Report**

**Page:** https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment

**Problem:**

> 5. To see the ReplicaSet (`rs`) created by the Deployment, run `kubectl get rs`. The output is similar to this:
>
> ```
> NAME                          DESIRED   CURRENT   READY   AGE
> nginx-deployment-75675f5897   3         3         3       18s
> ```

> 6. To see the labels automatically generated for each Pod, run `kubectl get pods --show-labels`. The output is similar to:
>
>    ```
>    NAME                                READY     STATUS    RESTARTS   AGE       LABELS
>    nginx-deployment-75675f5897-7ci7o   1/1       Running   0          18s       app=nginx,pod-template-hash=3123191453
>    nginx-deployment-75675f5897-kzszj   1/1       Running   0          18s       app=nginx,pod-template-hash=3123191453
>    nginx-deployment-75675f5897-qqcnn   1/1       Running   0          18s       app=nginx,pod-template-hash=3123191453
>    ```
>
>    The created ReplicaSet ensures that there are three `nginx` Pods.

In the later paragraph above, the pods' `pod-template-hash` label should be corresponding to their replicaSets', which is `75675f5897`. The output of pods' `NAME` correctly contains their pod-template-hash `75675f5897`, but the output of `LABELS` is incorrect. 

**Proposed Solution:**

Maybe the output of `pod-template-hash` label in `kubectl get pods --show-labels` should be `pod-template-hash=75675f5897` instead of `pod-template-hash=3123191453`.

### PR DESCRIPTION
**Pull request by YiNNx**
This PR fixes issue #40751 

Change the output of `pod-template-hash` label in `kubectl get pods --show-labels` from `pod-template-hash=3123191453` to `pod-template-hash=75675f5897`.

### CODE REVIEW

**Review by T-Lakshmi — COMMENTED** [review]
Looking good to me.

Deploy preview: https://deploy-preview-40752--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/deployment/

**Comment by mengjiao-liu** [comment]
/lgtm

https://github.com/kubernetes/website/issues/40751#issuecomment-1521240972

**Comment by YiNNx** [comment]
@tengqm Could you please take a look and check if it can be approved? Thank you in advance for your help.

**Pull request merged**
