### PR TITLE
[ru] Update KubeCon dates for 2023-2024

### PR DESCRIPTION
**Pull request by Arhell**
/assign @shurup

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Proposed update of the Kubecon dates looks in sync with 'en' PR https://github.com/kubernetes/website/pull/43589/files

LGTM

[Preview Page](https://deploy-preview-44111--kubernetes-io-main-staging.netlify.app/ru/) | [Original Page](https://kubernetes.io/ru/)

**Review by kumarankit999 — COMMENTED** [review]
looks Updated Now for Kubecon!

**Review by Arhell — COMMENTED** [review]
cc @shurup

**Comment by shurup** [comment]
Hi @Arhell! Since my #44158 is merged now, let's reflect these changes in your PR here please?

**Comment by Arhell** [comment]
@shurup done

**Comment by shurup** [comment]
@Arhell thank you! One small issue is still here, though :-) The KubeCon NA 2024 link should lead [here](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america-2024/) since the original URL (with no year) will bring you to the KubeCon NA **2023** website.

**Comment by Arhell** [comment]
@shurup done

**Comment by shurup** [comment]
Perfect, thanks! Let's finally merge it :sweat_smile: 

/lgtm
/approve

**Pull request merged**
