### PR TITLE
Fix typo in Control CPU Management Policies on the Node

### PR DESCRIPTION
**Pull request by NitishKumar06**
Fix: #37556

### CODE REVIEW

**Review by bishal7679 — APPROVED** [review]
/lgtm

**Review by Pradumnasaraf — APPROVED** [review]
The changes look good.

/approve

**Comment by sftim** [comment]
/retitle Fix typo in Control CPU Management Policies on the Node

@NitishKumar06, have you seen our project policy on [trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits)?

**Review by sftim — COMMENTED** [review]
/approve

**Comment by NitishKumar06** [comment]
> /retitle Fix typo in Control CPU Management Policies on the Node
> 
> @NitishKumar06, have you seen our project policy on [trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits)?

Thanks for mentioning it here - I'd be going through the complete file once again to find if any such typos/broken links exist.

**Pull request merged**
