### PR TITLE
Follow-up PR for ID Localization for Service Topology 

### PR DESCRIPTION
**Pull request by ariscahyadi**
Follow-up PR from previous closed PR #20229

### CODE REVIEW

**Comment by irvifa** [comment]
@ariscahyadi can you please rebase this first?

**Comment by ariscahyadi** [comment]
> @ariscahyadi can you please rebase this first?

Just did it and upload new commit.

**Comment by ariscahyadi** [comment]
> > @ariscahyadi can you please rebase this first?
> 
> Just did it and upload new commit.

Just completed to fix it.

**Comment by girikuncoro** [comment]
@ariscahyadi looking good, thanks for this follow up PR! sorry for the delay

/lgtm
/approve

**Pull request merged**
