### PR TITLE
[pt-br] Added persistant-volume.md file

### PR DESCRIPTION
**Pull request by rkmdCodes**
Added the persistant-volume.md file to upgrade the documentation .

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Hi, thanks for your contribution, the translation itseft don't seems to idiomatic, can your reword this?

**Comment by stormqueen1990** [comment]
Hi there, @rkmdCodes!

Thanks for your contribution. In addition to what @yagonobre mentioned, this glossary entry is also not appearing in the Brazilian Portuguese glossary, because the file name is incorrect. Could you please also take a look at that?

Thanks again!

**Comment by rkmdCodes** [comment]
Hey! Thanks so much for the review! I've tried correcting the issue as pointed out. Please let me know if anything else need to be changed! Thanks so much :)

**Comment by MrErlison** [comment]
Hi @rkmdCodes Thanks for your contribution!

I open an issue #39092 for that term with some instructions. See there is something that can help you.

resolve #39092

**Review by stormqueen1990 — COMMENTED** [review]
Hi there, @rkmdCodes! 👋 

In your previous iteration, this file was in the correct path (`content/pt-br/docs/reference/glossary`) but with the incorrect filename. Could you please revert the path and correct the filename?
The file name must match the English version, which is `persistent-volume.md` (see https://github.com/kubernetes/website/blob/999f3130eaad86b4103d531e877875db25597202/content/en/docs/reference/glossary/persistent-volume.md).

Another point is that the text is still not very idiomatic. If you need any help with that, please feel free to reach out to the Brazilian Portuguese localization team in the Kubernetes Slack `#kubernetes-docs-pt` channel. 😃

**Pull request closed without merging**
