### PR TITLE
blog: a brief introduction about the Curp consensus protocol

### PR DESCRIPTION
**Pull request by GTwhy**
Submitting blog post

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@GTwhy Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by GTwhy** [comment]
> @GTwhy Thanks you for your contribution. Could you please sign the CLA before the PR can be reviewed. You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

Hi, I am contacting our company's CLA manager. Please wait for a moment.

**Comment by sftim** [comment]
/close

We require copyright licensing before we can review articles.

**Comment by divya-mohan0209** [comment]
Per above comments, closing off this PR.
/close

**Pull request closed without merging**
