### PR TITLE
add CSIInlineVolume feature flag to kube-apiserver

### PR DESCRIPTION
**Pull request by sozercan**
adds `CSIInlineVolume` feature flag to kube-apiserver

### CODE REVIEW

**Comment by tengqm** [comment]
Since which version `CSIInlineVolume` was introduced? It is not documented in the feature-gates doc anyway.

**Comment by sozercan** [comment]
@tengqm it's introduced in v1.15, you can find it in feature gates doc here: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by zacharysarah** [comment]
@sozercan Thanks for this fix. Because this is a change to generated documentation, your changes will be overwritten the next time we generate reference docs. 

See the [docs contribution guide](https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-api/) for guidance on how to update reference docs.

/close

**Pull request closed without merging**
