### PR TITLE
Improve Extensions Definition

### PR DESCRIPTION
**Pull request by wiggitywhitney**
Hello!  ₍˄·͈༝·͈˄₎ฅ˒˒ 

First time contributor here!  Eek!

I have been learning Kubernetes by studying the glossary and I found the Extensions definition to be unclear and inconsistent.  

I've made some improvements to the copy.  

We may want to double-check the Chinese translation.  

(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧  
Thanks so much!  I'm so excited to be here!

### CODE REVIEW

**Comment by tengqm** [comment]
@wiggitywhitney Please separate the changes to different languages instead of mixing them in a single PR. You may want to propose one PR to the English site and a follow-up PR with changes to the zh localization.

**Comment by wiggitywhitney** [comment]
> @wiggitywhitney Please separate the changes to different languages instead of mixing them in a single PR. You may want to propose one PR to the English site and a follow-up PR with changes to the zh localization.

This is done!  ✷(ꇐ‿ꇐ)✷

**Comment by reylejano** [comment]
Thank you @wiggitywhitney 
/approve

**Pull request merged**
