### PR TITLE
Update mysql-wordpress-persistent-volume.md

### PR DESCRIPTION
**Pull request by yar2001**
Improve translation.

In english version, *this deployment* emphasis *this*. While in the previous chinese version, the meaning is distorted which  expands the scope to *all deployment*.

### CODE REVIEW

**Comment by yar2001** [comment]
I just want to improve a little translation and the PR requirements is so complicated, maybe I'll take a look in the future.

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/29995#issuecomment-939270169

**Comment by yar2001** [comment]
OK, I sign the CLA

**Comment by tengqm** [comment]
@yar2001 Your CLA is not working. Please check if you are using the same email in your PR and recommit this change if needed.

**Comment by jimangel** [comment]
Hey there! @yar2001, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
CLA is still failing. No response from contributor.
/close

**Pull request closed without merging**
