### PR TITLE
Add case study: Booz Allen

### PR DESCRIPTION
**Pull request by alexcontini**

### CODE REVIEW

**Comment by sftim** [comment]
@alexcontini is it OK if I add "case study" to the PR title?

**Comment by sftim** [comment]
I think this is based on https://www.cncf.io/case-study/boozallen/

**Comment by alexcontini** [comment]
@sftim  ah yes definitely! sorry about that

**Comment by bradtopol** [comment]
/assign @zacharysarah 
Hi @zacharysarah what is the process for reviewing case studies?

**Comment by zacharysarah** [comment]
@bradtopol Normally case studies go to @alexcontini for review. Since she’s the author in this case, feel free to approve as normal.

**Comment by kbhawkey** [comment]
Hi @alexcontini .
I briefly read the text on the two pages.
Check: On the actual case study page for `booz-allen`, there is text leftover from `adidas`?
`There is no competitive edge over our competitors like Puma or Nike ...`

Page previews:
https://deploy-preview-20689--kubernetes-io-master-staging.netlify.app/case-studies/booz-allen/

https://deploy-preview-20689--kubernetes-io-master-staging.netlify.app/case-studies/

**Comment by alexcontini** [comment]
@kbhawkey thank you very much for catching that!! 

I am just going to do a thorough review and will comment once it's ready to merge

**Pull request merged**
