### PR TITLE
Clean up after the 10th birthday

### PR DESCRIPTION
**Pull request by sftim**
Remove the special banner support added in https://github.com/kubernetes/website/pull/46684, leaving some scaffolding in place.

/kind cleanup

---

Alternative: someone (ideally, not me) has capacity and makes time to tidy that support up a bit more, so we can show a less prominent message every project birthday if wanted. I'll be delighted if that happens; if not, we should merge this.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/approve

**Comment by Shubham82** [comment]
This PR needs approval required from [sig-docs-website-owner](https://github.com/kubernetes/website/blob/dev-1.31/OWNERS_ALIASES#L11)

**Comment by sftim** [comment]
@kubernetes/sig-docs-leads PTAL (not urgent)

**Pull request merged**
