### PR TITLE
zh-trans: website/content/zh/docs/user-journeys/users/cluster-operator/intermediate.md

### PR DESCRIPTION
**Pull request by zhangx501**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by zhangx501** [comment]
/assign @zacharysarah
The PR is not approved. Could you approve that file, please?

**Comment by zacharysarah** [comment]
@zhangx501 Please work with the Chinese localization team for Chinese language PRs.

/unassign
/assign @xiangpengzhao

**Comment by zhangx501** [comment]
/assign @xiangpengzhao
The PR is not approved. Could you approve that file, please?

**Comment by chenrui333** [comment]
@zhangx501 thanks for your contribution, can you please rebase the base branch to release-1.14?

This is what is in the PR template:

> For pull requests on Chinese localization, set Base Branch to release-1.14

Thanks!!

**Comment by zhangx501** [comment]
/assign @xiangpengzhao
The PR is not approved. Could you approve that file, please?

**Comment by zhangx501** [comment]
@chenrui333
I‘ve changed it to release-1.14 already.

**Comment by xiangpengzhao** [comment]
@zhangx501 you were thinking of just translating and merging the single file `website/content/zh/docs/user-journeys/users/cluster-operator/intermediate.md`, right? I see that there are lots of unrelated commits and files are included in this PR. Please resolve the conflicts before we can review and merge it :)

**Comment by markthink** [comment]
@zhangx501  冲突需要解决一下..

**Comment by chenrui333** [comment]
@zhangx501 如果是 不太熟悉rebase 的话，也可以把这个 PR 直接关掉，再开一个 PR。这样子会更容易操作一些。

**Comment by chenrui333** [comment]
@zhangx501 if it is too difficult to create another PR, feel free to contact me. Happy to help.

**Pull request closed without merging**
