### PR TITLE
Update PULL_REQUEST_TEMPLATE URL

### PR DESCRIPTION
**Pull request by baijunyao**

### CODE REVIEW

**Comment by baijunyao** [comment]
I signed it

**Comment by baijunyao** [comment]
QQ20200511-234701@2x

**Comment by kbhawkey** [comment]
Hello @baijunyao . Thanks for opening this pull request.
Would you verify that your CLA is signed? Thanks!
/check cla

**Comment by baijunyao** [comment]
I signed it

**Comment by baijunyao** [comment]
@kbhawkey  Thanks you very much, I signed it.

**Pull request merged**
