### PR TITLE
add content_type param, kubeadm pages

### PR DESCRIPTION
**Pull request by kbhawkey**
- Add content_type parameter to kubeadm pages
- Clean up spaces, headings
- Add `no_list` and `toc_hide` to `kubeadm/generated/_index.md`
- Add `no_list` to `kubeadm/_index.md`
- Add heading shortcode for literal H2 "What's next"
- Remove `toc-hide` in front matter from several pages

### CODE REVIEW

**Comment by kbhawkey** [comment]
@savitharaghunathan If you have the time, would you review? Thanks!

**Comment by kbhawkey** [comment]
Some previews:
https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/
https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/
https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-join-phase/

**Comment by savitharaghunathan** [comment]
@kbhawkey Overall it looks good to me. However, I noticed a lot of white space between `Implementation details` & `Feedback` sections in - https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/ . And there is also some extra space in the side nav. 
Screen Shot 2020-08-09 at 17 10 38

**Comment by kbhawkey** [comment]
Yes. That is interesting. I am looking at it.

**Comment by kbhawkey** [comment]
@sftim, Would you have the time to review?
Notes: These changes involve clean up as well as some finagling of the section index.
I cleaned up a bunch of files that had a `toc-hide` parameter in the front matter.
To hide the kubeadm/generated directory from the left sidebar tree, I added `toc_hide: true`.
However, I was unable to find a quick way to select one page from appearing in the section list.
Instead, I set `no_list` for the kubeadm directory.
Ideally, we'd like the section list to match what appears in the left sidebar tree.

**Comment by sftim** [comment]
Before this change, https://kubernetes.io/docs/reference/setup-tools/kubeadm/ has a relevant-looking list of topics
After this change the main pane of https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/ is blank.

I recommend migrating https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/ to https://kubernetes.io/docs/reference/setup-tools/kubeadm/
and adding a redirect.

**Comment by kbhawkey** [comment]
> 
> 
> Before this change, https://kubernetes.io/docs/reference/setup-tools/kubeadm/ has a relevant-looking list of topics
> After this change the main pane of https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/ is blank.
> 
> I recommend migrating https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/ to https://kubernetes.io/docs/reference/setup-tools/kubeadm/
> and adding a redirect.

@sftim, Yes, excluding the `setup-tools/kubeadm` directory from the section index prevents the `generated` directory
from displaying. I can migrate the contents of the "kubeadm overview" page, though, I was hoping to minimize the changes.
If I create a redirect, I assume the kubeadm links on the docs home page will continue to work, else I will need to update the `card` fields as well.

**Comment by sftim** [comment]
There's more than one way to do it! On a mobile device especially, [`/docs/reference/setup-tools/kubeadm/`](https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/) is blank / will be blank after a merge.

So long as there's _something_ relevant there, I think that deals with my concern - and then further tidying can move to a different PR.

**Comment by kbhawkey** [comment]
More previews:
https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/home/
https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/
https://deploy-preview-23048--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/

**Pull request merged**
