### PR TITLE
[pl] Mention kubernetes/websites everywhere in the same way

### PR DESCRIPTION
**Pull request by MaxymVlasov**
Related to https://kubernetes.slack.com/archives/C0191RDKHU1/p1680549820387879

### CODE REVIEW

**Review by Pradumnasaraf — COMMENTED** [review]
/lgtm

**Comment by mfilocha** [comment]
@MaxymVlasov I'm not very happy with this change because:
- https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/_index.md?plain=1#L79 has the same abbreviation
- this change very likely will break the flowchart, making some boxes too wide

**Comment by MaxymVlasov** [comment]
@mfilocha https://github.com/kubernetes/website/pull/40493

**Comment by mfilocha** [comment]
@MaxymVlasov The commit above (https://github.com/kubernetes/website/pull/40493) refers to different files.

**Comment by MaxymVlasov** [comment]
Oh, it was accidentally in excluded files during replacement. Tnx to mentioned it, I'll fix it right now

**Comment by mfilocha** [comment]
@MaxymVlasov - The upstream English file is still not changed. Should we keep this PR open?

**Comment by MaxymVlasov** [comment]
@mfilocha yeah. EN reviewers could do better ¯\\\_(ツ)_/¯ So let's wait.

**Review by nvtkaszpir — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
