### PR TITLE
Remove user-journeys legacy content #18615

### PR DESCRIPTION
**Pull request by ShivangGoswami**
Deleted the user journeys under en/docs to remove orphaned content on the website

### CODE REVIEW

**Comment by gavinfish** [comment]
Ref #18615

/cc @zacharysarah

**Comment by zacharysarah** [comment]
@ShivangGoswami Thanks for this PR, and welcome to Kubernetes!

/lgtm
/approve

**Comment by ShivangGoswami** [comment]
@zacharysarah Thank you for approving my PR.

**Pull request merged**
