### PR TITLE
Remove all hyperlinks in Upgrading kubeadm clusters page

### PR DESCRIPTION
**Pull request by bishal7679**
Fixes :- #36969
This PR is for v1.22 Upgrading kubeadm clusters page

### CODE REVIEW

**Comment by reylejano** [comment]
/hold
Issue https://github.com/kubernetes/website/issues/36969 is on the release-1.21 docs
Although the description states this is for 1.22 but this PR is to main which is currently the 1.25 docs
The links are currently working on the 1.25 docs

**Comment by sftim** [comment]
/retitle Remove all hyperlinks in Upgrading kubeadm clusters page

**Comment by divya-mohan0209** [comment]
Hello @bishal7679 - Please can you action on the comments made by @reylejano ?

**Comment by reylejano** [comment]
If this PR is intended for the release-1.22 docs then you must change the base branch to `release-1.22` instead of `main`, at this moment, `main` is the 1.25 docs
Here's a doc on how to change the base branch of a pull request: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by mehabhalodiya** [comment]
@bishal7679 any updates on this as per the Rey's last comment?

**Comment by tengqm** [comment]
/close
Wrong branch.

**Pull request closed without merging**
