### PR TITLE
[zh-cn] Fix a wrong translation

### PR DESCRIPTION
**Pull request by handyson**
[zh-cn] Fix a wrong translation

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Change looks good!.

Screenshot for [en docs](https://github.com/kubernetes/website/blob/f3a652eaf5274df36381f8350413b32e625cc2d7/content/en/docs/reference/using-api/_index.md?plain=1#L61) ref

Screenshot from 2022-10-27 01-12-16

/approve

**Comment by windsonsea** [comment]
thanks.

/lgtm

**Pull request merged**
