### PR TITLE
Remove reference to deprecated image

### PR DESCRIPTION
**Pull request by nikitakalyanov**
The #20553 changed the deprecated hello-node image to echoserver image. However, there is a reference to the old image later in the text. Point 5 implies that there will be a 'Hello World' message. This probably was true for the hello-node image but the echoserver does not print this (it echoes back the request with all of its params). This may be misleading, so change the text to a generic 'app's response'.

### CODE REVIEW

**Comment by nikitakalyanov** [comment]
I signed it

**Comment by nikitakalyanov** [comment]
Changed the other "simple 'Hello World' Node.js app" references to "sample app" - they call it like that in minikube documentation.

**Comment by tengqm** [comment]
/lgtm
Not 100% sure about whether the article still flows after the removal of the prerequisites, so deferring approval to other set of eyes.

**Comment by nikitakalyanov** [comment]
@tengqm  Seems like 'prerequisites' are required for the template to render correctly, so I've returned the section back (but without the source code). The preview does not show error now.
Should I delete the 'minikube/server.js' and 'minikube/Dockerfile' files? It seems they were only referenced here in prerequisites, but I am not 100% sure it won't break something in a subtle way.

**Comment by nikitakalyanov** [comment]
I have removed the unused files and squashed the commits together.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-20788--kubernetes-io-master-staging.netlify.app/docs/tutorials/hello-minikube/

**Comment by Rajakavitha1** [comment]
/lgtm
checked https://deploy-preview-20788--kubernetes-io-master-staging.netlify.app/docs/tutorials/hello-minikube/

**Pull request merged**
