### PR TITLE
Corrected the link  and grammar in hi docs 

### PR DESCRIPTION
**Pull request by Vikash-8090-Yadav**
Corrected one link redirection. and some grammar in Hindi docs. 
Thanks!

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @divya-mohan0209

**Comment by Babapool** [comment]
The link change part of this PR LGTM. 

Coming to the grammar part writing  control can be written either as कंट्रोल or कंट्रोल. They both are the same IMO.  @Vikash-8090-Yadav I would suggest you to look for other grammatical changes in this file. Thoughts @divya-mohan0209?

**Comment by Vikash-8090-Yadav** [comment]
> The link change part of this PR LGTM.
> 
> Coming to the grammar part writing control can be written either as कंट्रोल or कंट्रोल. They both are the same IMO. @Vikash-8090-Yadav I would suggest you to look for other grammatical changes in this file. Thoughts @divya-mohan0209?

Thanks for the prompt reply,
and I chnaged `कण्ट्रोल` this to `कंट्रोल` only. Please check once.
Thanks!

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @Vikash-8090-Yadav , thank you for suggesting the change. I'd recommend that you go through the contributor documentation & our policy on trivial edits before making a contribution next time.
/approve

**Comment by Vikash-8090-Yadav** [comment]
Of this pr is ok. Then please add LGTM label. Thanks

**Review by aj11anuj — APPROVED** [review]
This PR is ready to get merged, green flag from myside

However its of no use as this docs "Container Runtime" page in hindi is outdated by 80+ lines, and merging this PR or closing it makes no difference at all. I will make a new PR updating whole "Container Runtime" page.

**Comment by Babapool** [comment]
Thanks!
/lgtm

**Pull request merged**
