### PR TITLE
[zh]The output is incorret.

### PR DESCRIPTION
**Pull request by yuandongx**
# The fact is.
image

# Should be
image

### CODE REVIEW

**Comment by tengqm** [comment]
do we need a fix to the English upstream?

**Comment by yuandongx** [comment]
> do we need a fix to the English upstream?

I don't think we need a fix to the English upstream.It is right!
image

**Comment by tengqm** [comment]
Thanks for the confirmation.
/lgtm
/appove

**Review by tanjunchen — COMMENTED** [review]
/lgtm

**Review by tanjunchen — COMMENTED** [review]
/approve
/retest

**Pull request merged**
