### PR TITLE
Update labels.md

### PR DESCRIPTION
**Pull request by tramplpf**
为了让语句更加的通畅

### CODE REVIEW

**Comment by tengqm** [comment]
@tramplpf Please sign the CLA in order for the PR to be reviewed.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by reylejano** [comment]
@tramplpf, please sign the CLA
https://github.com/kubernetes/community/blob/master/CLA.md

A PR Wrangler may close this PR if the CLA is not signed

**Comment by tengqm** [comment]
/close
Closing due to missing CLA for a long time. Feel free to reopen.

**Pull request closed without merging**
