### PR TITLE
docs: Update custom-resource-definition-versioning.md

### PR DESCRIPTION
**Pull request by dimabru**
CRD kind is not camelCased, but PascalCased. Changed the documentation to reflect that

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/29288#issuecomment-894816389

**Comment by dimabru** [comment]
I signed it

**Comment by tengqm** [comment]
Thanks.
/lgtm
/approve

**Pull request merged**
