### PR TITLE
Fix the score value in docs/concepts/scheduling-eviction/resource-bin-packing.md

### PR DESCRIPTION
**Pull request by Alpenbelieve**
Hi, The maximum value of score should be 10 instead of 100, right? :D

### CODE REVIEW

**Comment by Alpenbelieve** [comment]
Sorry, I've signed the CLA just now.

**Comment by Alpenbelieve** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

10 min have passed...

**Comment by Alpenbelieve** [comment]
There should be no problem this time.

**Comment by tengqm** [comment]
Thanks.
/lgtm

**Review by tanjunchen — COMMENTED** [review]
/approve

**Comment by sftim** [comment]
/sig scheduling

@tengqm you're happy to have these changes land in the 3 localizations listed?

@kubernetes/sig-docs-ko-reviews is this combined PR OK with you?

**Comment by tengqm** [comment]
@sftim

I don't like having a single PR touching more than one localization. The reason is that each localization (may) have their own change tracking protocol. Eventually, the upstream change should be limited to English. Let the localization team decide when and how to sync this change.

**Comment by seokho-son** [comment]
@sftim 
In case of Korean l10n, we can follow up changes in English contents when we move to next milestone (Koean dev branch).
However, minor chnages such as bug-fix or link-change are acceptable in master branch.

We prefer individual PR for l10n. However, since it is a simple fix, combined PR is also ok for us if the change for English is acceptable.

/approve
for the change in Ko doc.

From now on, this PR is up to En approver. :)

**Comment by sftim** [comment]
/approve

Thanks all

**Pull request merged**
