### PR TITLE
zh-trans: add docs/reference/federation/_index.html

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by Bradamant3** [comment]
@chenrui333 is this PR against the wrong directory? I see `en` not just in the PR label but also in the file path, but there's localized content in the file itself.

/hold

**Comment by chenrui333** [comment]
@Bradamant3 For Chinese localization, we always use `release-1.12` as base branch.

**Comment by tengqm** [comment]
/lgtm
/approve

The PR doesn't have to include a change to the English content. Please avoid this next time.

**Pull request merged**
