### PR TITLE
Fix up 2023 SIG Instrumentation spotlight article

### PR DESCRIPTION
**Pull request by sftim**
Correct a minor capitalization issue in upcoming article https://blog.k8s.io/2023/02/03/sig-instrumentation-spotlight-2023/

(fixing up https://github.com/kubernetes/website/pull/39204)

Equivalent to https://github.com/kubernetes/contributor-site/pull/372

### CODE REVIEW

**Review by imnmo — APPROVED** [review]

**Comment by imnmo** [comment]
@stim thanks a lot for finding minor details that my eyes missed. I approved it. Hope it should be fine.

**Review by chrisnegus — COMMENTED** [review]
/lgtm

**Pull request merged**
