### PR TITLE
fix for issue #17068

### PR DESCRIPTION
**Pull request by shubham-asati**
removed extra test in line no 80

### CODE REVIEW

**Comment by shub-asa1** [comment]
@rajeshdeshpande02

**Comment by bradtopol** [comment]
@rajeshdeshpande02 I am confused by your comment. The issue says that the output is not matching what the docs say the output should look like. Hence the fix.  I didn't see where this PR changed the selector. Instead it was just changing how it was expected to be displayed to match what was being displayed in https://github.com/kubernetes/website/issues/17068

**Comment by Rajakavitha1** [comment]
@rajeshdeshpande02 could you please clarify @bradtopol 's review comment.

**Comment by sftim** [comment]
Links to issue #17068

**Comment by sftim** [comment]
Here's how things look to me:
```bash
#1
kubectl apply -f https://kubernetes.io/examples/controllers/frontend.yaml
```
```
replicaset.apps/frontend created
```
<br />

```bash
#2
kubectl describe rs/frontend
```
```
Name:         frontend
Namespace:    default
Selector:     tier=frontend
Labels:       app=guestbook
              tier=frontend
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{},"labels":{"app":"guestbook","tier":"frontend"},"name":"frontend",...
Replicas:     3 current / 3 desired
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  tier=frontend
  Containers:
   php-redis:
    Image:        gcr.io/google_samples/gb-frontend:v3
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  9s    replicaset-controller  Created pod: frontend-gvb5d
  Normal  SuccessfulCreate  9s    replicaset-controller  Created pod: frontend-94xts
  Normal  SuccessfulCreate  9s    replicaset-controller  Created pod: frontend-6np2k
```

**Comment by sftim** [comment]
That's with a v1.15 cluster though. If it changed only in recent versions then this merge was in error.

**Pull request merged**
