### PR TITLE
KEP-3325: Promote SelfSubjectReview to GA

### PR DESCRIPTION
**Pull request by nabokihms**
Documentation for:
  - [x] KEP (`k/enhancements`) update PR(s): https://github.com/kubernetes/enhancements/pull/3971
  - [x] Code (`k/k`) update PR(s): https://github.com/kubernetes/kubernetes/pull/117713
  - [ ] Docs (`k/website`) update(s): https://github.com/kubernetes/website/pull/40956

### CODE REVIEW

**Comment by tengqm** [comment]
Is this for v1.28? Please target the dev-1.28 branch rather than main if so.
/hold

**Comment by nabokihms** [comment]
Rebased, thanks

**Review by sftim — COMMENTED** [review]
Thanks.

I'd tweak this slightly.

**Pull request merged**
