### PR TITLE
Fix cri-o's links to match English docs

### PR DESCRIPTION
**Pull request by ping035627**
Fix cri-o's links to match English docs.

### CODE REVIEW

**Comment by markthink** [comment]
@ping035627 分支提交错误，[参考](https://github.com/k8smeetup/k8s-official-translation)

**Comment by ping035627** [comment]
@markthink  release-1.16中还没有content/zh/docs/setup/independent/install-kubeadm.md文件，这个bug没法提交到release-1.16.

**Comment by markthink** [comment]
@ping035627  可以按 en 目录创建对应的 zh 子目录

**Pull request closed without merging**
