### PR TITLE
update storage version to v1

### PR DESCRIPTION
**Pull request by zouyee**
/cc @ahmetb 
> NOTE: After opening the PR, please *un-check and re-check* the "Allow edits from maintainers" box. This is a temporary workaround to address a known issue with GitHub.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6057)

### CODE REVIEW

**Comment by ahmetb** [comment]
You need to update non-CN file too (there are 2 in this repo with the same name unfortunately #6055)

**Comment by steveperry-53** [comment]
@ahmetb I added the non-CN file with the change from v1beta1 to v1. Is it OK to merge this now?

**Comment by ahmetb** [comment]
@steveperry-53 if I understand correctly statefulset is still v1beta2 in 1.8 (and not v1 yet), so this should not be merged right away.

**Comment by ahmetb** [comment]
My bad ignore that. Looks like this is for StorageClass type.
/lgtm

**Pull request merged**
