### PR TITLE
fix heading level

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/kubernetes/website/issues/24850

### CODE REVIEW

**Comment by sftim** [comment]
@Arhell would you be willing to close this PR and leave that fix for someone else who has not yet worked on their first issue?

I'm keen to build up a pool of good-first-issue issues before Kubecon.

The actual changes?
/lgtm

**Comment by Arhell** [comment]
@sftim understood, but already opened, I will keep in mind.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-24865--kubernetes-io-master-staging.netlify.app/docs/concepts/services-networking/network-policies/#what-you-can-t-do-with-network-policies-at-least-not-yet

I agree that it would be helpful to hold off on issues marked for first time contributors.
Thanks @Arhell.

**Pull request merged**
