### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anilkarela**
made headings look  better

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/29911#issuecomment-933000415

**Comment by divya-mohan0209** [comment]
@anilkarela : Please can you let us know which issue under k/website this fixes?
Also, if you need your PR to be reviewed please sign the CLA.

**Comment by jimangel** [comment]
Hey there! @anilkarela, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by divya-mohan0209** [comment]
@anilkarela : Thank you for the PR. However since there has been no response on this PR from your end for ~ 2 months, we will be closing it off. Kindly consider reopening it if & when you feel ready to contribute. 

Please note: Kindly sign CLA before you start contributing since it helps with expediting the review process.

**Pull request closed without merging**
