### PR TITLE
Fixed malformed sentence

### PR DESCRIPTION
**Pull request by mbongard**
Fixed malformed sentence.

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Comment by divya-mohan0209** [comment]
Hello @mbongard , please could you sign the CLA?

**Comment by divya-mohan0209** [comment]
Till the CLA is signed.

/lgtm cancel

**Comment by mbongard** [comment]
> Till the CLA is signed.
> 
> /lgtm cancel

Hi @divya-mohan0209, CLA is signed now.

**Comment by divya-mohan0209** [comment]
@mbongard : The CNCF CLA hasn't been signed and is the authoritative one in this case. Please could you sign it and check?

**Review by sftim — COMMENTED** [review]
Thanks
/lgtm
/approve

**Pull request merged**
