### PR TITLE
Fix spelling mistake in french language

### PR DESCRIPTION
**Pull request by John361**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@John361
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by nasa9084** [comment]
You need to rebase onto `kubernetes:dev-1.21` branch not to include other than your changes

**Comment by bradtopol** [comment]
Hi @John361 thank you for your contribution. Please sign the CLA so we can accept your PR for review. Please also create one PR for each language type.  A single PR should not attempt to update content across multiple languages.

**Comment by reylejano** [comment]
@John361 , I'm the release docs lead for 1.21, please review @bradtopol 's comment about signing the CLA, and creating a PR for changes in each language
/assign
/cc @sftim

**Comment by tengqm** [comment]
I'd assume such kind of PRs goes to the master branch first.

**Comment by sftim** [comment]
We can't formally review this change until we have CLA signoff. However, looking at the labels and target branch:
/hold

**Pull request closed without merging**
