### PR TITLE
Update safely-drain-node.md

### PR DESCRIPTION
**Pull request by ilboud**
Small typo endure -> ensure

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
more info about CLA, check please
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
Hi @ilboud .
Thanks for contributing!
Have you signed the CLA?

**Comment by kbhawkey** [comment]
Hi @ilboud .
I am closing this pull request. You can reopen this PR at any time.
/close

**Pull request closed without merging**
