### PR TITLE
Removed the  pipe symbol in dockercfg-secret.yaml

### PR DESCRIPTION
**Pull request by priyanshsao**
# Which problem is this PR solving?
- solves-#48533

# Description of the changes

- removed pipe symbol in dockercfg-secret.yaml from  content/en/examples/secret/

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
Explicit hold until this PR only covers one language.
_(Ok to unhold once that's done)_
/hold

**Comment by priyanshsao** [comment]
Thanks for the suggestion! I'll make a new commit that updates only the English content.

**Comment by sftim** [comment]
@priyanshsao we don't see that there is anything to fix here

**Pull request closed without merging**
