### PR TITLE
remove feature-gate NewVolumeManagerReconstruction

### PR DESCRIPTION
**Pull request by carlory**
k/k: https://github.com/kubernetes/kubernetes/pull/126775
/hold

### CODE REVIEW

**Comment by tengqm** [comment]
This should target the `dev-1.32` branch rather than `main`.

**Comment by carlory** [comment]
@tengqm updated.

**Comment by Shubham82** [comment]
The changes look good to me.
/lgtm
Thanks @carlory for the fix

Merge it once upstream PR merges.

**Comment by carlory** [comment]
/hold cancel

upstream is merged

**Pull request merged**
