### PR TITLE
Fixed a typo on page "Create an External Load Balancer"

### PR DESCRIPTION
**Pull request by able8**
Fixed a typo by replacing `_NumNodes` with `NumNodes`

### CODE REVIEW

**Review by aj11anuj — COMMENTED** [review]
LGTM, 👍🏼

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-43634--kubernetes-io-main-staging.netlify.app/docs/tasks/access-application-cluster/create-external-load-balancer/#caveats-and-limitations-when-preserving-source-ips

**Pull request merged**
