### PR TITLE
adding how-to for making glossary tooltips 

### PR DESCRIPTION
**Pull request by heckj**
to include docs for contribution, because I keep forgetting and I'm hoping that writing this will encourage me to remember it :-)

(relevant page to see for this PR: https://deploy-preview-7014--kubernetes-io-master-staging.netlify.com/docs/home/contribute/includes/#glossary)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7014)

### CODE REVIEW

**Comment by heckj** [comment]
@abiogenesis-now would you mind giving this a look over? I was reviewing some of your user-journeys content and embarrassed that I wasn't using glossary entries, so wrote this into our guides...

**Comment by heckj** [comment]
👋 @abiogenesis-now - I'd love your eyes on this for accuracy please

**Comment by heckj** [comment]
/assign @bradtopol 

@bradtopol - would you give this a review as well please?

**Comment by bradtopol** [comment]
Very impressive.  @heckj these improvements are extremely helpful!
/lgtm

**Pull request merged**
