### PR TITLE
Clarify meaning of group

### PR DESCRIPTION
**Pull request by tabbysable**
Reword the description of "group", per a question @inductor asked on Slack.

### CODE REVIEW

**Comment by tabbysable** [comment]
ping to pick up my CLA

**Comment by tabbysable** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> memo **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
>     * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
>     * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> 
>     * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> 
>     * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

Ping to validate my CLA

**Comment by inductor** [comment]
Thank you!

Note: The question was on https://kubernetes.slack.com/archives/C0EN96KUY/p1595333369018500 in #sig-auth channel.

**Comment by sftim** [comment]
/lgtm cancel

(CLA not signed)
@tabbysable - you need to [sign the CLA](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement) before we can formally review this.

/check-cla

**Comment by tabbysable** [comment]
Second time's a charm, the robot sees my CLA now :tada:

**Pull request merged**
