### PR TITLE
Merged master release 1.16

### PR DESCRIPTION
**Pull request by VineethReddy02**

### CODE REVIEW

**Comment by tengqm** [comment]
@VineethReddy02 @daminisatya 
The Chinese localization team is actively working on the release-1.16 branch. AFAICT, conflicts will be expected in the content/zh directory. The only thing we can do, as I see it, is to merge this kind of merge PRs ASAP if possible.

**Comment by tfogo** [comment]
Hi @VineethReddy02, it looks like two of the commits here aren't correctly tied to your GitHub account. Probably the email that has been associated with the commit isn't the same email that you use on GitHub. This is causing the CLA check to fail. Can you please amend or squash the commits to update the email?

**Comment by sftim** [comment]
@VineethReddy02 is this OK to close?

**Comment by VineethReddy02** [comment]
@sftim Yes we can close this.
/close

**Pull request closed without merging**
