### PR TITLE
Cluster tooltip update

### PR DESCRIPTION
**Pull request by jhbiggs**
Hi,

This pull request is in reference to issue #14151.  I'm hopeful it contains only this issue resolution as was suggested in another issue.

### CODE REVIEW

**Comment by jhbiggs** [comment]
Not sure if this is what the bot is telling me to do...

/assign @steveperry-53

**Comment by rlenferink** [comment]
Hi @jhbiggs, what the bot suggested to you and how you used that information is correct :)

However, it still seems this PR contains a couple of commits that don't need to be there because they're already merged back. What you probably want to do is a `git rebase` and drop the commits we want to remove from this PR (we only need to keep b9827f9eca4cfefba73f3a0c50a576269588df58).

Some information on rebasing and dropping a commit: https://jwiegley.github.io/git-from-the-bottom-up/1-Repository/8-interactive-rebasing.html

What you probably want to do:
```bash
git checkout cluster-tooltip-update
git rebase -i HEAD~5

# Then delete the lines which commits we want to drop. Only keep b9827f9eca4cfefba73f3a0c50a576269588df58

# Save and quit

git push -f
```

If done correct, the pull request will be automatically updated 😃

**Comment by jhbiggs** [comment]
Ok, I think I did it.  Thanks for your help.  I rebased (hopefully not too far back) and force-pushed onto my fork.

**Comment by tengqm** [comment]
Can we separate this to two PRs: one for English and the other for German?

**Comment by rlenferink** [comment]
@jhbiggs you rebase was correct :) can we drop the “Update index.md” commit as well which updates the German the localization? This won’t affect the k8s master branch as the German change was already merged in #14685.

**Comment by jhbiggs** [comment]
Ok, rebased without the German changes.

**Comment by rlenferink** [comment]
@jhbiggs Perfect :) Thanks for doing so

@tengqm this is ready for review now.

**Comment by rlenferink** [comment]
/assign @cody-clark
as PR wrangler for this week

**Pull request merged**
