### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by masanetes**
Seems to be typo in L. 23 of content/ja/docs/concepts/services-networking/endpoint-slices.md

/sig docs
/language ja

### CODE REVIEW

**Review by irvifa — COMMENTED** [review]
/approve

**Comment by inductor** [comment]
@irvifa Hello, Japanese approvers had not seen it yet... Could you just give a LGTM from next time? 🙇

**Comment by irvifa** [comment]
@inductor Sure 🙇

**Pull request merged**
