### PR TITLE
Add October patch releases to the releases calendar

### PR DESCRIPTION
**Pull request by Checksumz**
Add October patch releases to the releases calendar

### CODE REVIEW

**Comment by jimangel** [comment]
> It looks like this is your first PR to [kubernetes/website](https://github.com/kubernetes/website) 🎉

Congrats @Checksumz 🙌  hopefully the first of many! Once you [sign the CLA](https://kubernetes.io/docs/contribute/new-content/#sign-the-cla), this looks good!

/cc @kubernetes/release-managers

**Comment by xmudrii** [comment]
@Checksumz We also had 1.25.14 and might have 1.25.15, can you please add these two patch releases as well?

**Comment by Checksumz** [comment]
@xmudrii done, let me know if that looks good

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by xmudrii** [comment]
This looks good to me, but you need to figure out the CLA stuff before we can formally approve and merge this 😕

**Comment by xmudrii** [comment]
/check-cla
Please see this message for more details: https://github.com/kubernetes/website/pull/43113#issuecomment-1725949419

**Comment by palnabarun** [comment]
The committer/author email for this commit https://github.com/kubernetes/website/pull/43113/commits/01babbe21b58dba92a45c16b24650252b9233ce1 might be the reason.

**Comment by Checksumz** [comment]
@xmudrii @palnabarun looks like it was the first commit that was an issue, fixed it now

**Comment by Checksumz** [comment]
Let me know if there's anything still pending on my end

**Review by xmudrii — APPROVED** [review]
Thank you and congrats on your first contribution to the Kubernetes project! ✨ 
/lgtm
/approve

**Pull request merged**
