### PR TITLE
Updating Release Note Link

### PR DESCRIPTION
**Pull request by danielcgithub**

### CODE REVIEW

**Comment by danielcgithub** [comment]
Signed CLA

**Comment by RA489** [comment]
> Signed CLA

/check-cla

**Comment by jimangel** [comment]
Hi @danielcgithub!

There may be a problem with your git commit author email address and the email address you used to sign the CLA.

If the robot cannot verify your CLA status, the PR will not merge. If you cannot correct this problem, please close and re-open a new PR with the correct commit / author.

**Pull request merged**
