### PR TITLE
WIP: Immutability documentation

### PR DESCRIPTION
**Pull request by apelisse**
Documentation for immutability feature: kubernetes/enhancements#1101

### CODE REVIEW

**Comment by sftim** [comment]
@apelisse would you be OK to mention https://github.com/kubernetes/enhancements/issues/1101 in the description of this issue? (it'd make the connection clear)

**Comment by apelisse** [comment]
done!

**Comment by daminisatya** [comment]
@apelisse 

This is a kind reminder since we're approaching the deadline for PR to be "Ready for Review" by Nov 15, 2019. Kindly update this PR.

**Comment by apelisse** [comment]
We missed the deadline for the feature, we'll re-create the PR on the 1.18 doc branch, thanks!

**Pull request closed without merging**
