### PR TITLE
reformat kubelet ref page

### PR DESCRIPTION
**Pull request by kbhawkey**
Adapt the `Options` HTML table to the CommonMark spec.
Tested with Hugo 0.69.0.

### CODE REVIEW

**Comment by bradtopol** [comment]
Assigning @jimangel since @kbhawkey already asked him to review.
/assign @jimangel

**Comment by kbhawkey** [comment]
> 
> 
> @kbhawkey the preview turns command line flags like `--version version[=true]` into: `–version version[=true]` (similar to issue #20623)
> 
> I don't see anything wrong with this PR itself however you might like to bear in mind that this effect is present.

Yes, just saw that issue. This file is not auto generated (known problem with flags).
I will look at the double hyphen conversion in this file.
/hold

**Comment by tengqm** [comment]
/hold
Let's see we can fix the Hugo behavior with #20629.

**Comment by kbhawkey** [comment]
These changes depend on what happens with #19907.
Will rebase to keep the page current.

**Comment by zacharysarah** [comment]
@kbhawkey #19907 is merged, please rebase when ready to proceed. 👍

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-20599--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kubelet/

**Pull request merged**
