### PR TITLE
Fix Nginx Ingress namespace

### PR DESCRIPTION
**Pull request by guoqiao**
The correct namespace is ingress-nginx, not kube-system.

### CODE REVIEW

**Comment by guoqiao** [comment]
I signed it

**Comment by guoqiao** [comment]
I signed it

**Comment by jihoon-seo** [comment]
Hello @guoqiao

The PR #28154 and #28355 are also suggesting this change.

/hold

**Comment by guoqiao** [comment]
Hi @jihoon-seo  , thanks for letting me know, I will close PR then.

**Pull request closed without merging**
