### PR TITLE
chore: fix an invalid location.hash

### PR DESCRIPTION
**Pull request by oke-py**
The correct link is https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

### CODE REVIEW

**Comment by oke-py** [comment]
https://deploy-preview-26750--kubernetes-io-master-staging.netlify.app/docs/tutorials/stateless-application/guestbook/#creating-the-frontend-service

**Comment by kbhawkey** [comment]
Thanks @oke-py !
/approve

**Pull request merged**
