### PR TITLE
Fix sticky footer issue

### PR DESCRIPTION
**Pull request by lucperkins**
On pages like the [404 page](https://kubernetes.io/404.html) there's an issue where the footer doesn't stick to the bottom of the page the way that it should. In addition, on pages like the home page there's a band of whitespace at the bottom. This PR fixes both of those issues using Flexbox.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@lucperkins For devices below 1100px it doesn't look promising. Especially for mobile devices. I can fix it up for mobile screens :+1:

**Comment by lucperkins** [comment]
@jamesgeorge007 What's the issue that you're seeing on mobile?

**Comment by Bradamant3** [comment]
@lucperkins what's the status of this PR? Does it just need merge conflicts fixed, or is there more work needed for better mobile support?

**Comment by lucperkins** [comment]
@Bradamant3 I just fixed the merge conflicts. I'm still not sure which mobile issues were being referred to above, so I consider this good to go.

**Comment by Rajakavitha1** [comment]
@Bradamant3 Please Take a Look.

**Comment by zparnold** [comment]
@lucperkins We hit the unfortunate issue where there's another conflict. I can help if you want

**Comment by Rajakavitha1** [comment]
Hi @lucperkins !!!!Looks like there are merge conflicts on this PR. Could you please resolve them?

**Comment by lucperkins** [comment]
@Rajakavitha1 Done

**Comment by Rajakavitha1** [comment]
@kbarnard10 could you please take a look and state your approval.

**Comment by zparnold** [comment]
@lucperkins Looks good to me!
/lgtm
/approve

**Pull request merged**
