### PR TITLE
ko-trans: add case-studies/...

### PR DESCRIPTION
**Pull request by xichengliudui**
copy content/en/case-studies/ to content/ko/case-studies/

### CODE REVIEW

**Comment by gochist** [comment]
@xichengliudui , Thank you! We are having a build error. Please resolve it. And is there any criteria for you selection? I think all content under `content/en/case-studies` can be just copied to `content/ko/case-studies` to treat them impartially. What do you think?

```
june@jump:~/website$ make docker-serve
docker run --rm --interactive --tty --volume /home/june/website:/src -p 1313:1313 kubernetes-hugo hugo server --watch --bind 0.0.0.0
Building sites … ERROR 2018/11/27 03:31:25 Case Studies: Missing logo for IBM. Put a PNG with the word 'logo' in the filename into "case-studies/ibm/"
```

**Comment by xichengliudui** [comment]
Ok, no problem.
/hold

**Comment by xichengliudui** [comment]
@gochist How do you feel now?

**Comment by gochist** [comment]
Thank you for your update!

/hold cancel
/lgtm
/approved

**Pull request merged**
