### PR TITLE
Updating Kubernetes architectural diagram

### PR DESCRIPTION
**Pull request by dkypuros**
This PR updates the "Kubernetes architectural diagram" graphic image, located in Kubernetes Documentation > Concepts > Overview > Kubernetes Components [reference URL](https://kubernetes.io/docs/concepts/overview/components/)

This PR is part of an effort to improve consistency between Kubernetes icons and diagrams on the official Kubernetes Docs website. Several of us have been commenting and collaborating, on the image/png file changed here via a [Google Draw document](https://docs.google.com/drawings/d/11P-yXzso7zapqyqP3ulnIsQ1UE7IbzEi-7kp5jNebLM/edit?usp=sharing). This effort still has an outstanding [SoW for CNCF](https://docs.google.com/document/d/1D94DyIb7CjSYjR7CXs7TgihiMHVrvzGoIUK1ZMdZKgE/edit?usp=sharing), that will work to add even more updates soon.

### CODE REVIEW

**Comment by dkypuros** [comment]
I signed it

**Comment by sftim** [comment]
@dkypuros once Prow sees that you've signed the CLA, we can review these suggested changes

**Comment by dkypuros** [comment]
I'm going to close and re-open this.

**Comment by sftim** [comment]
The diagram at https://kubernetes.io/docs/concepts/overview/components/ came about because of really useful work on this and other PRs.

Thank you @dkypuros !

**Pull request closed without merging**
