### PR TITLE
WIP - [es] Add concepts/storage/persistent-volumes.md

### PR DESCRIPTION
**Pull request by gamba47**
Adding new content to concepts/storage/persistent-volumes.md

Work still in progress but it's huge!

Related to https://github.com/kubernetes/website/issues/13948#issuecomment-1007875517

### CODE REVIEW

**Review by krol3 — COMMENTED** [review]
@electrocucaracha agregar los reviewers va a ser el default para todas las nuevas traducciones?

**Comment by divya-mohan0209** [comment]
Hello @gamba47 , are you comfortable continuing with this effort? The last activity for this was ~7 months ago, which is why I'm checking in.

**Comment by gamba47** [comment]
Hi @divya-mohan0209 !! i'm sorry this is a huge text and i always start again and try to mantain the appropiatted words but is not easy.

Please don't close it i will start writing again in a few days.

Sorry!

**Comment by divya-mohan0209** [comment]
@gamba47 , please don't be sorry! I know the efforts that go into translation, so it's all good :)

**Comment by Sea-n** [comment]
Hey @gamba47, thanks for contributing!
Just take your time to resume the translation when you feel comfortable.

Prevent the bot to close this PR.
/remove-lifecycle stale

**Comment by divya-mohan0209** [comment]
Hey @gamba47 , just checking in. Have you gotten any cycles to continue work on this?

**Comment by gamba47** [comment]
I'm not working at this moment but i will finish this translation if you let me continue with this.

I will try to make some changes this week and finish this for october if i can. It's really big and i have to start again every time i got some time to write.

**Comment by divya-mohan0209** [comment]
Hey @gamba47 , we've been following up for quite some time & understand that you're busy. Please feel free to reopen this PR whenever you're comfortable PRing this change in. For now, I shall be closing it.
/close

**Pull request closed without merging**
