### PR TITLE
Fix the grammar by using the verb "set up" where appropriate instead of the noun "setup"

### PR DESCRIPTION
**Pull request by wsteinford**
This PR fixes some grammatical mistakes in the English documentation where the noun "setup" is used where the correct verb is the two-word phrasal verb "set up".

This PR does not change incorrect usage in blog posts.

( See this page for more explanation: https://grammarist.com/spelling/set-up-vs-setup/ )

### CODE REVIEW

**Comment by wsteinford** [comment]
This pull request incorporates the suggestions in the closed https://github.com/kubernetes/website/pull/35179 by being shorter and only including the grammar corrections that were not controversial.

**Review by chrisnegus — COMMENTED** [review]
Those all look like appropriate changes from "setup" to "set up" to me.
/lgtm

**Comment by annajung** [comment]
Thanks for the helpful link to setup vs set up and making changes to the doc
/approve

**Pull request merged**
