### PR TITLE
Change Anda to Kamu in manage deployment

### PR DESCRIPTION
**Pull request by mufti1**
Hello, 

I found `Anda` in manage deployment page, I change it into `Kamu`

/language id

### CODE REVIEW

**Comment by irvifa** [comment]
Hi thank you for contributing, can you please sign the CLA first? @mufti1

**Comment by mufti1** [comment]
I signed it

**Comment by irvifa** [comment]
Hmm do you signed it with the same email you used to push your commit? 🤔

**Comment by girikuncoro** [comment]
Looking good, thank you so much for your first contribution! Welcome to kubernetes 🎉 

/lgtm
/approve

**Pull request merged**
