### PR TITLE
[zh-cn]Fix nits in markdown links & update page weight in page upgrading-windows-nodes.md

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
Fix nits in markdown links  refer to https://github.com/kubernetes/website/pull/38276/files#diff-3f8cc51cd9b3a78161b92a57110394aefd20284bc1e75252f9600d9f871403da.

Update page weight by the way.

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi, when syncing a file with en, you can have a try to run this command below to find and sync each differences:

```
./scripts/lsync.sh content/zh-cn/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
```
image

BTW: provide a clear title to be easily identified by each zh contributor when they are searching for in the PR list, which can avoid possible conflicts.

**Comment by Zhuzhenghao** [comment]
@windsonsea 是说当前英文 diff 之后有三处不同，那中文应该也出现这三处，是这么理解吗？

**Comment by windsonsea** [comment]
> @windsonsea 是说当前英文 diff 之后有三处不同，那中文应该也出现这三处，是这么理解吗？

目前不接受仅部分修改，确认把所有 diff 改完就好 👍

**Comment by Zhuzhenghao** [comment]
@windsonsea 嗯嗯，明白了🫡，已更新。感谢

**Pull request merged**
