### PR TITLE
optimize doc translation

### PR DESCRIPTION
**Pull request by eatjeff**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by eatjeff** [comment]
> Pls sign the CLA in order for the PR to be reviewed.
> more info
> https://github.com/kubernetes/community/blob/master/CLA.md

I already signed, but commit with wrong github user, so...

**Comment by jimangel** [comment]
Hey there! @eatjeff, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Pull request closed without merging**
