### PR TITLE
Reword commits that cause Prow warnings

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR rewords commits that cause Prow to apply `do-not-merge/invalid-commit-message` labels to #17958. 

I brought my local fork current with upstream/master:
```
$ git fetch upstream
$ git merge upstream/master
$ git push
```
I looked at the repo's commit history to find how far back I needed to edit. Then, in interactive mode, I reworded the commit messages for #17888 and #17889:
```
$ git rebase -i HEAD~36
```
Specifically, I removed magic words from the commit messages and reduced them to a single line instead of multiple lines.

This PR includes many files and commits because I didn't `squash` the other commits; I did this to avoid unduly destructive history changes.

UPDATE: This PR uses different hashes for each commit, compared to the current history in k/website. For example, the current branch tip for k/website is c26806c69ed3ca8b40602d8d5b43b3bd40f16f7e. This PR changes that hash to 5e730a39f167e8832650f9586cb109ecb71bfd41. Because this PR alters the earlier (and therefore subsequent) PR commit history, it makes sense to generate new hashes. Reviewers, please verify that commits from each PR apply changes correctly:

- [Current `master` hashes](https://github.com/kubernetes/website/commits/master)
- [This PR's hashes](https://github.com/kubernetes/website/pull/17960/commits)

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Hi @zacharysarah I reviewed all the files in English and the changes look good to me.

**Comment by gochist** [comment]
@zacharysarah I don't understand how this PR can fix the commits already merged. If this PR is squashed and merged, it will become a single commit on the original commit history like this,  https://github.com/gochist/website/commit/ec5b784993d874b3aa6ed4c894661d306e8d200c .

**Comment by zacharysarah** [comment]
@gochist Good point. Can you recommend a way to reword older commits?

**Pull request closed without merging**
