### PR TITLE
Merged main dev 1.27

### PR DESCRIPTION
**Pull request by mickeyboxell**
Maintain the current and upcoming dev branch for Kubernetes 1.27 release

### Release deadlines

From [sig-release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.27#timeline):

Date | Description
-- | --
March 16 | Open Placeholder PRs
March 24 | PRs ready for review
April 4 | All PRs reviewed and ready to merge

### For more information
cc: 1.27 Docs Team: Mickey Boxell ([@mickeyboxell](https://github.com/mickeyboxell) / Slack: @Mickey) Jackline Mutua ([@katmutua](https://github.com/katmutua) / Slack: @jacklinem), Lukonde Mwila ([@LukeMwila](https://github.com/LukeMwila) / Slack: @Lukonde Mwila), Rishit Dagli ([@Rishit-dagli](https://github.com/Rishit-dagli) / Slack: @Rishit Dagli), Tania Duggal ([@taniaduggal](https://github.com/taniaduggal) / Slack: @Tania Duggal)

### CODE REVIEW

**Comment by reylejano** [comment]
Deploy failed for commit [138fc4f](https://github.com/kubernetes/website/pull/40407/commits/138fc4fba17ef17e64f7545ee4aa4b7b611e153e) which is in merged PR https://github.com/kubernetes/website/pull/40205

**Review by Rishit-dagli — APPROVED** [review]
\lgtm

**Pull request merged**
