### PR TITLE
Update socks5-proxy-access-api.md

### PR DESCRIPTION
**Pull request by fjammes**
If using `localhost` in KUBECONFIG, instead of <API_SERVER_IP_ADRESS>, you get a certificate error:
```
kubectl get pods
I0520 16:29:08.178277   41261 versioner.go:58] Get https://localhost:6443/version?timeout=5s: dial tcp 127.0.0.1:6443: connect: connection refused
Unable to connect to the server: x509: certificate is valid for ccqserv225, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not localhost
```

Please also note that I have a warning message if I unset the `https_proxy` env variable:
```
 ⚙ kubectl get pods 
I0520 16:35:27.955076   43865 versioner.go:56] Remote kubernetes server unreachable
NAME                     READY   STATUS    RESTARTS   AGE
hub-54c6457f66-vlq2l     1/1     Running   0          4h27m
proxy-7b5b8dfb9d-dxrkz   1/1     Running   0          4h27m
# Whereas with the https_proxy variable:
 ⚙ export https_proxy=socks5://localhost:1080     
 ⚙ kubectl get pods                          
NAME                     READY   STATUS    RESTARTS   AGE
hub-54c6457f66-vlq2l     1/1     Running   0          4h28m
proxy-7b5b8dfb9d-dxrkz   1/1     Running   0          4h28m
```
Any idea is welcome here.

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey, according to [Netlify build log](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6287a8060bf94a0008bf068c#L129), it's failed caused by previous broken commit.

Could you rebase onto `kubernetes:main` then force push? It should be fix the CI/CD and we can move forward.

**Comment by zacharysarah** [comment]
@fjammes 👋🏻 Please feel free to `/reopen` when you're ready to rebase and respond to feedback.

/close

**Comment by fjammes** [comment]
> @fjammes Thanks for rebasing. Some nits for clarity, otherwise LGTM

Thanks for your suggestions, I have accepted both. May you merge the PR then?

**Pull request merged**
