### PR TITLE
[zh-cn] Fix some punctuation errors on reference/glossary page

### LINKED ISSUE #36099: change punctuation on https://kubernetes.io/zh-cn/docs/reference/glossary
Hello, I noticed some punctuation errors on https://kubernetes.io/zh-cn/docs/reference/glossary page。

/language zh

### PR DESCRIPTION
**Pull request by syxunion**
as title fix #36099

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
@syxunion please retitle the PR.

**Comment by syxunion** [comment]
Okay. Thank you.

**Comment by bishal7679** [comment]
@syxunion Always try to make a new local branch and then make necessary commit from that branch. And try to avoid to raise a PR from main branch. 
I hope you understand :)

**Comment by Sea-n** [comment]
/retitle [zh-cn] Fix some punctuation errors on reference/glossary page

**Pull request merged**
