### PR TITLE
Add comments to shell snippets in StatefulSet tutorial

### PR DESCRIPTION
**Pull request by sftim**
Use POSIX-compatible comments to explain the context and expectations to the person following the [tutorial](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/) for StatefulSets.

Part of PR #42767

### CODE REVIEW

**Comment by stmcginnis** [comment]
/lgtm

Great to have the additional context and guidance!

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-44390--kubernetes-io-main-staging.netlify.app/docs/tutorials/stateful-application/basic-stateful-set/

**Review by dipesh-rawat — COMMENTED** [review]
Thank you for the thoughtful improvement!

/lgtm

**Pull request merged**
