### PR TITLE
Adding SC blog post for 2023 election

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Adding blog post for Steering Committee 2023 election.

/cc @kaslin @dims

### CODE REVIEW

**Comment by kaslin** [comment]
Looks good to me! Holding for @sftim's review if he can give it.
/lgtm
/approve
/hold

**Review by sftim — COMMENTED** [review]
A couple of nits - sorry.

1. This should ideally have https://k8s.dev/blog/ as its canonical home (and be mirrored to the main blog)
2. We could open placeholder article PRs ahead of results day, allowing for most of the review to happen earlier. Also gives the blog team notice of the result articles.

**Comment by bridgetkromhout** [comment]
> A couple of nits - sorry.
> 
> 1. This should ideally have https://k8s.dev/blog/ as its canonical home (and be mirrored to the main blog)
> 2. We could open placeholder article PRs ahead of results day, allowing for most of the review to happen earlier. Also gives the blog team notice of the result articles.

Thanks - I am noting both of these items on the retro doc in https://docs.google.com/document/d/1aXWbQYaYSktvSfu7uvvcnoOhMiET8NROoWsAomlM3AM/edit.

**Comment by bridgetkromhout** [comment]
> This should ideally have https://k8s.dev/blog/ as its canonical home (and be mirrored to the main blog)

@sftim should I PR in this change? (I didn't realize we had this other blog location but I'm happy to correct this.)

**Comment by sftim** [comment]
@bridgetkromhout sure, please do
https://github.com/kubernetes/contributor-site/tree/master/content/en/blog

The two sites are both Hugo but have slightly different conventions for blog front matter just to make things ~simple~ complicated.
See https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2023-07-20-sig-cli-spotlight.md?plain=1 for an example of what the mirrored article ought to look like (`canonicalUrl` in the front matter).

The original of that article is https://github.com/kubernetes/contributor-site/blob/master/content/en/blog/2023/sig-cli-spotlight.md?plain=1

**Pull request merged**
