### PR TITLE
Fix nits in air-gapped cluster blog article

### PR DESCRIPTION
**Pull request by sftim**
Fixups for https://github.com/kubernetes/website/pull/42726

@TheFutonEng FYI

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Taking a quick glance at the [file's content](https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2023-10-12-bootstrap-an-air-gapped-cluster-with-kubeadm/index.md) and [preview](https://deploy-preview-43342--kubernetes-io-main-staging.netlify.app/blog/2023/10/12/bootstrap-an-air-gapped-cluster-with-kubeadm/), there are a few more improvements we could make.

- There are [two consecutive periods](https://deploy-preview-43342--kubernetes-io-main-staging.netlify.app/blog/2023/10/12/bootstrap-an-air-gapped-cluster-with-kubeadm/#:~:text=and%20widely%20available-,..,-You%20can%20execute) in [Line 145](https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2023-10-12-bootstrap-an-air-gapped-cluster-with-kubeadm/index.md?plain=1#L145) that need correction.
- Instead of [absolute links](https://deploy-preview-43342--kubernetes-io-main-staging.netlify.app/blog/2023/10/12/bootstrap-an-air-gapped-cluster-with-kubeadm/#:~:text=be%20found%20at-,pkgs.k8s.io.,-This%20blog%20post), we could use relative links in [Line 147](https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2023-10-12-bootstrap-an-air-gapped-cluster-with-kubeadm/index.md?plain=1#L147).
- The phrase "[.. common methods or air gap ..](https://deploy-preview-43342--kubernetes-io-main-staging.netlify.app/blog/2023/10/12/bootstrap-an-air-gapped-cluster-with-kubeadm/#:~:text=some%20common%20methods%20or%20air%20gap%20software%20delivery)" might need correction to ".. common methods of air gap .." to convey the intended meaning in the sentence on [Line 695](https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2023-10-12-bootstrap-an-air-gapped-cluster-with-kubeadm/index.md?plain=1#L695).

**Comment by sftim** [comment]
I'll tweak the absolute link. The other two things don't need a fix, IMO.

**Comment by Affan-7** [comment]
LGTM

**Review by Gauravpadam — COMMENTED** [review]
Thanks, lgtm

**Review by dipesh-rawat — COMMENTED** [review]
It's an improvement!

/lgtm

**Pull request merged**
