### PR TITLE
Translate concepts/storage/persistent-volumes.md  in Korean.

### PR DESCRIPTION
**Pull request by yjw113080**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For Chinese localization, base branch to release-1.14
>
> For Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
From #14402

### CODE REVIEW

**Comment by nasa9084** [comment]
I think this PR should change just inside ko dir

**Comment by tengqm** [comment]
A rebase is needed, or else this PR cannot be reviewed.

**Comment by seokho-son** [comment]
@yjw113080 Thank you for your contribution. 
Thank you @tengqm, @raelga for the comments.

This PR seems related to Korean l10n team. 
Since this PR only related to Korean localization, I will remove following labels.
/remove-language de
/remove-language en
/remove-language es
/remove-language fr
/remove-language id
/remove-language ja
/remove-language zh
/remove-area blog

@yjw113080. In order to fulfill the requirements of a Pull request, please check [following guilds](https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-ko.md?fbclid=IwAR11Cv9Nh3U28D4O1jS8M7uV2aZxnzY2XWpB-Bg3hXxu2fPy7dCWCb1qTKE
).

There is a [nice video](https://www.youtube.com/watch?v=OTl8HBjxIhc) to guide the whole procedures to contribute to Korean localization of Kuberentes documents. Take a look and try to follow the guidance.
Also, come to kubernetes-docs-ko Slack channel and get help.

**Comment by tengqm** [comment]
@yjw113080 I'm closing this PR because the CLA status check has not been resolved for over a month, the change needs a rebase to contain only the relevant changes proposed and the gate is not happy of the current PR. Please

- feel free to reopen this if you are still working on it, and
- try follow instructions [here](https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting) to debug your CLA status if you have already signed it.

**Pull request closed without merging**
