### PR TITLE
Debugging DNS has been moved to a separate article.

### LINKED ISSUE #7115: DNS debugging article should be extracted from DNS configuration doc
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
This article contains two topics which I think should be separate:
- Customizing DNS service
- Debugging DNS

These two are not necessarily related.
 
**Proposed Solution:**

Move Debugging DNS into a separate article. 

**Page to Update:** https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

### PR DESCRIPTION
**Pull request by scriptonist**
As pointed out in #7115 Debugging DNS has been moved to a separate article.

Updated page: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
New page: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7436)

### CODE REVIEW

**Comment by heckj** [comment]
This looks good to me, but I’d love another set of editor eyes on it for a review - @Bradamant3 would you mind taking a look (I suspect it may be a quick overview) - if you’re happy with it, drop a `/lgtm` comment on the PR...

/assign @Bradamant3

**Comment by ahmetb** [comment]
@scriptonist Pro tip: Type `Closes #7115` in your commit or PR description next time to auto-close issues you're addressing.

**Comment by scriptonist** [comment]
@ahmetb I thought I put in a comment and hence not visible in PR description. Will make sure to double check that next time.

**Pull request merged**
