### PR TITLE
[ja] Update container-runtimes.md and related links

### LINKED ISSUE #39125: [ja] Update setup/production-environment/container-runtimes translation
**This is a Feature Request**

**What would you like to be added**

Update https://kubernetes.io/docs/setup/production-environment/container-runtimes Japanese translation

**Why is this needed**

**Comments**

ref. https://github.com/kubernetes/website/pull/39085#discussion_r1089581460

/language ja

### PR DESCRIPTION
**Pull request by grainrigi**
Update container-runtimes.md and related links.
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

This closes #39125.

### CODE REVIEW

**Review by t-inu — COMMENTED** [review]
I left some comments. Please check.

**Comment by grainrigi** [comment]
@t-inu Thank you! I applied your suggestions.

**Review by t-inu — APPROVED** [review]
/lgtm

**Comment by nasa9084** [comment]
/approve
Thank you~

**Pull request merged**
