### PR TITLE
Removed duplicate bullet item on nginx version 1.7.9

### PR DESCRIPTION
**Pull request by dnoland1**

### CODE REVIEW

**Comment by DanyC97** [comment]
@dnoland1 thank you for the fix, can you please sign the CLA and we'll review it?

**Comment by bradtopol** [comment]
@dnoland1 Thank you for your contribution.  Please sign the CLA so we can accept your PR for review

**Comment by Rajakavitha1** [comment]
@dnoland1 Thank you for your contribution. Please sign the CLA so we can accept your PR for review. See: https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by dnoland1** [comment]
@DanyC97 @bradtopol @Rajakavitha1 I've signed the CLA.

**Comment by DanyC97** [comment]
@dnoland1 many thanks for your contribution and for signing the CLA
/lgtm

**Comment by Rajakavitha1** [comment]
Thanks for your PR @dnoland1 !!!
Checked the preview : https://deploy-preview-14124--kubernetes-io-master-staging.netlify.com/docs/concepts/workloads/controllers/deployment/

/lgtm
/approve

**Pull request merged**
