### PR TITLE
Update components.md

### PR DESCRIPTION
**Pull request by anois**
This is a small space issues

### CODE REVIEW

**Comment by tengqm** [comment]
@anois Please sign the CLA in order for the PR to be reviewed.

**Comment by anois** [comment]
> @anois Please sign the CLA in order for the PR to be reviewed.

How to restart ci audit？

**Comment by tengqm** [comment]
@anois Commit your PR using the email account you used for CLA signing. Set user name with "git config" and then "git commit --reset-author --amend".

**Review by tanjunchen — COMMENTED** [review]
/approve
```
$ scripts/lsync.sh  content/zh/docs/concepts/overview/components.md
content/zh/docs/concepts/overview/components.md is still in sync
```

**Review by tanjunchen — COMMENTED** [review]
/cc @tengqm

**Comment by tengqm** [comment]
Thanks.
/lgtm

**Pull request merged**
