### PR TITLE
Fix minor grammatical error

### PR DESCRIPTION
**Pull request by banjoh**
Fix minor grammatical error found [here](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1/#SelfSubjectAccessReview)

### CODE REVIEW

**Comment by banjoh** [comment]
> Hi @banjoh Thank you for your contribution! We have different processes followed within different localisations of the project. Therefore, I'd request you to make changes to ONLY the main website i.e. the _English_ language with this PR and then raise a separate PR for other languages.

Thanks @dipesh-rawat for your feedback. Would removing the changes in `zh-cn` translation be sufficient or do I need to recreate the PR again?

**Comment by T-Lakshmi** [comment]
Hi @banjoh,

> Would removing the changes in zh-cn translation be sufficient or do I need to recreate the PR again?

That is sufficient, no need to recreate PR.
If you want to work on other translations, you can work and create a separate PR for that.
So what we follow here is one PR per one language.

**Review by T-Lakshmi — COMMENTED** [review]
Hey @banjoh,
This file is auto-generated from the Go source code of the component using a generic
[generator](https://github.com/kubernetes-sigs/reference-docs/). It’s not allowed to fix the issues directly on docs page for [auto generated pages](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1/#auto-generated-edit-notice).

See below mentioned link for the code related to this page which can help you.
https://github.com/kubernetes/website/blob/main/api-ref-assets/api/swagger.json

image

**Comment by banjoh** [comment]
> 

I see. So this change would need to end up [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/authorization/types.go#L40).

I was not aware of that. I'll close the PR then.

**Comment by banjoh** [comment]
> Hey @banjoh, This file is auto-generated from the Go source code of the component using a generic [generator](https://github.com/kubernetes-sigs/reference-docs/). It’s not allowed to fix the issues directly on docs page for [auto generated pages](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1/#auto-generated-edit-notice).
> 
> See below mentioned link for the code related to this page which can help you. https://github.com/kubernetes/website/blob/main/api-ref-assets/api/swagger.json
> 
> image

I see. So this change would need to end up [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/authorization/types.go#L40).

I was not aware of that. I'll close the PR then.

**Pull request closed without merging**
