### PR TITLE
update reference.yml for 1.20 reference docs

### PR DESCRIPTION
**Pull request by kbhawkey**
- Remove cloud-controller-manager component (not building)
- Add copy of kubectl cmd package

### CODE REVIEW

**Comment by kbhawkey** [comment]
@annajung , I retested these changes. I think the kubectl command pages look okay.

**Comment by annajung** [comment]
Hi @kbhawkey I tested the changes and I do not see any error running the following command
```
python update-imported-docs.py reference.yml 1.20.0-rc.0
```

For me, these are the files that were changed/created as a result. Could you compare with your result and see if this looks correct?
```
        modified:   content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
        modified:   content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
        modified:   content/en/docs/reference/command-line-tools-reference/kube-proxy.md
        modified:   content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
        modified:   content/en/docs/reference/kubectl/kubectl.md
        modified:   content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_kubeconfig_user.md
        modified:   content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_certs_generate-csr.md
        modified:   content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
        modified:   content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
        modified:   content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md
        modified:   content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_scheduler.md
        modified:   content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-certs.md
        new file:   static/docs/reference/generated/kubernetes-api/v1.20/index.html
        new file:   static/docs/reference/generated/kubernetes-api/v1.20/js/navData.js
```

**Comment by sftim** [comment]
/approve
/hold

@kbhawkey please unhold at will

**Comment by kbhawkey** [comment]
@annajung , I don't see the kubectl command reference in the list of generated pages.
PR #25355 generated 31 files?

**Comment by kbhawkey** [comment]
You may want to remove the cloud-controller-manager page (v1.19) in the same PR when you regenerate the files?
I am not sure if a decision was made about this component.
https://kubernetes.io/docs/reference/command-line-tools-reference/cloud-controller-manager/

**Comment by annajung** [comment]
Ran it again and I actually must have missed this the first time, but I am getting the following error

```
cp gen-kubectldocs/generators/build/index.html /Users/antheaj/workspace/website/static/docs/reference/generated/kubectl/kubectl-commands.html
cp: gen-kubectldocs/generators/build/index.html: No such file or directory
make: *** [copycli] Error 1
```

I don't have the `gen-kubectldocs/generators/build/index.html` file to be copied over.
Any tips on what could be missing?

I created a branch out of `dev-1.20` and made changes to `reference.yml` file based on changes in this PR. Then ran the python command.

**Comment by annajung** [comment]
>You may want to remove the cloud-controller-manager page (v1.19) in the same PR when you regenerate the files?
I am not sure if a decision was made about this component.
https://kubernetes.io/docs/reference/command-line-tools-reference/cloud-controller-manager/

There is a discussion going on in slack https://kubernetes.slack.com/archives/C0EG7JC6T/p1606929363248600. I'm waiting to hear back from SIG api machinery and will take action based on the outcome of the discussion :)

**Comment by kbhawkey** [comment]
There must have been more errors. The kubectl command build failed.
I would double check your version of reference.yml. You can copy the raw version of the file to your clone.
You can check the temporary install (build sandbox) to see if the kubectl cmd package was copied over (line 21).

**Comment by annajung** [comment]
- I confirmed that `src/k8s.io/kubernetes/pkg/kubectl/` is there
- `reference.yml` was copied using a raw version of the file
- No other errors that I can see... I could have missed something, attaching the whole [output.txt](https://github.com/kubernetes/website/files/5637442/scratch.txt) if you want to take a look

I will try again with a fresh repo!

**Comment by kbhawkey** [comment]
I looked. Can you check if there are files generated under /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/includes and /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/build/

I am wondering if the docker command failed (UI) or the build of the files?

```
go run gen-kubectldocs/main.go --kubernetes-version v1_20
docker run -v /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/includes:/source -v /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/build:/build -v /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/:/manifest brianpursley/brodocs:latest
navData.js saved!
index.html saved!
cp gen-kubectldocs/generators/build/index.html /Users/antheaj/workspace/website/static/docs/reference/generated/kubectl/kubectl-commands.html
cp: gen-kubectldocs/generators/build/index.html: No such file or directory
make: *** [copycli] Error 1
```

**Comment by annajung** [comment]
Both `/tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/includes` and `/tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/build/` do contain multiple `.md` files 

are you thinking the docker command must have failed? `docker run -v /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/includes:/source -v /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/build:/build -v /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/:/manifest brianpursley/brodocs:latest`

**Comment by annajung** [comment]
oh wait! SORRY, bad copy/paste

```
/tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/build/
```

build directory does not exist for me

**Comment by annajung** [comment]
```
sudo rm -f main
Password:
sudo rm -rf /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/includes
sudo rm -rf /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/build
sudo rm -rf /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/manifest.json
go run gen-kubectldocs/main.go --kubernetes-version v1_20
docker run -v /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/includes:/source -v /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/build:/build -v /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/:/manifest brianpursley/brodocs:latest
navData.js saved!
index.html saved!
cp gen-kubectldocs/generators/build/index.html /Users/antheaj/workspace/website/static/docs/reference/generated/kubectl/kubectl-commands.html
cp: gen-kubectldocs/generators/build/index.html: No such file or directory
make: *** [copycli] Error 1
```

so there is a command here 
```
sudo rm -rf /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/build
```
but I assume 
```
go run gen-kubectldocs/main.go --kubernetes-version v1_20
```
should create the directory again(?) 

but I am guessing `go run gen-kubectldocs/main.go --kubernetes-version v1_20` is failing for me

**Comment by kbhawkey** [comment]
OK. Your includes directory is empty?
```
/tmp/tmpbi795jq3/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/includes$ ls
_app_management.md                                 _generated_cluster-info.md  _generated_exec.md          _generated_replace.md
_generated_alpha.md                                _generated_completion.md    _generated_explain.md       _generated_rollout.md
_generated_annotate.md                             _generated_config.md        _generated_expose.md        _generated_run.md
_generated_api-resources.md                        _generated_cordon.md        _generated_get.md           _generated_scale.md
_generated_api-versions.md                         _generated_cp.md            _generated_kustomize.md     _generated_set.md
_generated_apply.md                                _generated_create.md        _generated_label.md         _generated_taint.md
_generated_attach.md                               _generated_debug.md         _generated_logs.md          _generated_top.md
_generated_auth.md                                 _generated_delete.md        _generated_options.md       _generated_uncordon.md
_generated_autoscale.md                            _generated_describe.md      _generated_patch.md         _generated_version.md
_generated_category_cluster_management.md          _generated_diff.md          _generated_plugin.md        _generated_wait.md
_generated_category_kubectl_settings_and_usage.md  _generated_drain.md         _generated_port-forward.md  _getting_started.md
_generated_certificate.md                          _generated_edit.md          _generated_proxy.md         _working_with_apps.md
```

**Comment by annajung** [comment]
`includes/` directory is there but my content looks different than yours.
I also have the `manifest.json` just not `build/`

```
(base) /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators/includes (master ✘)✹✭ (minikube) ᐅ ls
_app_management.md                         _generated_category_kubectl_settings_and_usage.md  _generated_describe.md   _generated_logs.md          _generated_set.md
_generated_alpha.md                        _generated_certificate.md                          _generated_diff.md       _generated_options.md       _generated_taint.md
_generated_annotate.md                     _generated_cluster-info.md                         _generated_drain.md      _generated_patch.md         _generated_top.md
_generated_api-resources.md                _generated_completion.md                           _generated_edit.md       _generated_plugin.md        _generated_uncordon.md
_generated_api-versions.md                 _generated_config.md                               _generated_exec.md       _generated_port-forward.md  _generated_version.md
_generated_apply.md                        _generated_cordon.md                               _generated_explain.md    _generated_proxy.md         _generated_wait.md
_generated_attach.md                       _generated_cp.md                                   _generated_expose.md     _generated_replace.md       _getting_started.md
_generated_auth.md                         _generated_create.md                               _generated_get.md        _generated_rollout.md       _working_with_apps.md
_generated_autoscale.md                    _generated_debug.md                                _generated_kustomize.md  _generated_run.md
_generated_category_cluster_management.md  _generated_delete.md                               _generated_label.md      _generated_scale.md
```

```
(base) /tmp/tmpn3fyfb6k/src/github.com/kubernetes-sigs/reference-docs/gen-kubectldocs/generators (master ✘)✹✭ (minikube) ᐅ ls
Dockerfile  includes       read_cmd.go   types.go  v1_12  v1_14  v1_16  v1_18  v1_20  v1_6  v1_8
gen.go      manifest.json  templates.go  v1_11     v1_13  v1_15  v1_17  v1_19  v1_5   v1_7
```

**Comment by kbhawkey** [comment]
If the includes directory contains files, then I would check Docker.

**Comment by kbhawkey** [comment]
I think this change can go in.
/hold cancel

**Comment by kbhawkey** [comment]
@annajung , Would you LGTM/approve this PR? I think the changes work.

**Pull request merged**
