### PR TITLE
[zh-cn] update configure-pod-container/enforce-standards-namespace-labels.md

### PR DESCRIPTION
**Pull request by yanrongshi**

### CODE REVIEW

**Comment by tengqm** [comment]
/retitle [zh-cn] update tasks/configure-pod-container/enforce-standards-namespace-labels.md

**Comment by jihoon-seo** [comment]
The commit message is not mached with the change this PR suggests.

**Comment by howieyuen** [comment]
I see you open two PRs to complete the short code replacing. The En PR(https://github.com/kubernetes/website/pull/34189), update 11 files in single PR, I recommend you to do like that

**Pull request merged**
