### PR TITLE
[pt] Fix kubectl auto complete

### PR DESCRIPTION
**Pull request by Arhell**
en PR  https://github.com/kubernetes/website/pull/37368/files
/assign @stormqueen1990

### CODE REVIEW

**Comment by MrErlison** [comment]
Thank you!

/lgtm

**Comment by edsoncelio** [comment]
Looks good; @Arhell, could you send another commit just to rerun the Hugo deploy? To fix (I hope) the timeout error.

**Comment by stormqueen1990** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
