### PR TITLE
Going emeritus, remove myself from WGs and SIGs

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR removes myself as an approver/reviewer in SIG Docs.

It's been a wonderful four years...and now it's time for something different. ❤️ 

Related PRs:
- https://github.com/kubernetes/community/pull/5733
- https://github.com/kubernetes/org/pull/2649

so-long

### CODE REVIEW

**Comment by kbhawkey** [comment]
👋 @zacharysarah .
Good luck with your next adventure!

/lgtm

Hold for review 😃 
/hold

**Comment by sftim** [comment]
Farewell @zacharysarah / thanks so much!

**Comment by jimangel** [comment]
@zacharysarah you carved a welcoming path for new k8s contributors, myself included, that enabled many future successes. From leadership to documentation architecture, your dedication and love for docs is admirable.

Best of luck in future endeavors! Cheers! 🎉 💙 

image

/approve
/pony
/honk
/woof
/meow
/this-is-not-fine

**Pull request merged**
