### PR TITLE
Fix inconsistent docs for .spec.ipFamilies field

### LINKED ISSUE #40728: Inconsistent docs for whether `.spec.ipFamilies` field is immutable for Service
In concept docs (https://kubernetes.io/docs/concepts/services-networking/dual-stack/):

> _Note_: The `.spec.ipFamilies` field is immutable because the `.spec.ClusterIP` cannot be reallocated on a Service that already exists. If you want to change `.spec.ipFamilies`, delete and recreate the Service.

but in API docs (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#servicespec-v1-core):

> This field is conditionally mutable: it allows for adding or removing a secondary IP family, but it does not allow changing the primary IP family of the Service.

It's also a bit unclear what "primary IP family" means. My first thought was the primary IP family is what's used for `.spec.ClusterIP` (as opposed to `.spec.ClusterIPs` which includes *all* IP families, not just the primary). Is that interpretation correct? If so, it might be better to avoid that terminology because there's also this text in the concept docs which makes "primary" overloaded:

> The field `.spec.ClusterIPs` is the primary field, and contains both assigned IP addresses; `.spec.ClusterIP` is a secondary field with its value calculated from `.spec.ClusterIPs`.

### PR DESCRIPTION
**Pull request by taniaduggal**
Fixes #40728

### CODE REVIEW

**Comment by taniaduggal** [comment]
I just changed the 111 line to mutable, but other changes automatically happened in my vs code when i saved the file

**Comment by sftim** [comment]
/retitle Fix inconsistent docs for .spec.ipFamilies field

**Comment by NitishKumar06** [comment]
> I just changed the 111 line to mutable, but other changes automatically happened in my vs code when i saved the file

I think your IDE is configured with 2/4 tabs.

**Comment by taniaduggal** [comment]
@NitishKumar06 how can i resolve this?

**Comment by NitishKumar06** [comment]
> @NitishKumar06 how can i resolve this?

Look over your IDE you're using and try to look there.

**Comment by kbhawkey** [comment]
👋 @taniaduggal 
If you are not actively working on this pull request can you close it?
You can always open a new PR with updated changes.
Thanks

**Pull request closed without merging**
