### PR TITLE
Creacion documentacion sobre validate-dual-stack en networking

### PR DESCRIPTION
**Pull request by jheimar**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by T-Lakshmi** [comment]
@jheimar,
EasyCLA is mandatory to move your PR forward.
Can you please sign CLA using [this link](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/45465/#/?version=2).

**Comment by krol3** [comment]
@jheimar puedes validar el link del comentario anterior  `please sign CLA using` [this link](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/45465/#/?version=2).

**Comment by reylejano** [comment]
@jheimar , I'm closing this PR since the CLA has not been signed.
When you have signed the CLA, you can reopen this PR with `/reopen` in a comment
/close

**Pull request closed without merging**
