### PR TITLE
[ko] Update 'Distribute Credentials Securely Using Secrets' (M188)

### PR DESCRIPTION
**Pull request by jihoon-seo**
Related comment: https://github.com/kubernetes/website/issues/41631#issuecomment-1608836600

> ### 1 file to be modified
> * [ ]  **M188.**  `content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md`  | **149(+L) 59(-)**

### CODE REVIEW

**Comment by sftim** [comment]
/area localization

@jihoon-seo this is just waiting on review, right?

**Comment by jongwooo** [comment]
> 영문 변경사항이 모두 반영된 것을 확인했습니다!

고생하셨습니다:)
/lgtm

**Pull request closed without merging**
