### PR TITLE
Remove "basic" from supported API auth methods

### PR DESCRIPTION
**Pull request by drigz**
This was removed in v1.19.

### CODE REVIEW

**Review by RinkiyaKeDad — COMMENTED** [review]
LGTM but we're gonna need an approval from someone from SIG Auth before we can merge this. Can you please also link to where it's documented that "HTTP basic auth" is no longer supported? Thanks!

**Comment by drigz** [comment]
Thanks for taking a look!

> we're gonna need an approval from someone from SIG Auth before we can merge this

Do I need to tag SIG Auth here, or should I just wait? (please excuse my inexperience, I've only sent a couple of PRs and was never sure when I should be pinging people)

> Can you please also link to where it's documented that "HTTP basic auth" is no longer supported?

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#:~:text=Support%20for%20basic%20authentication

**Comment by RinkiyaKeDad** [comment]
> https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#:~:text=Support%20for%20basic%20authentication

Thanks!

I've applied the sig label so we should wait for a few days for them to take a look at this. If not then please feel free to ping in the #sig-auth channel on the [Kubernetes slack](https://slack.k8s.io/) for a review :)

/sig auth

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-30288--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/authentication/#authentication-strategies

**Comment by kbhawkey** [comment]
For review, /cc @liggitt @deads2k

**Pull request merged**
