### PR TITLE
Replace localization symbolic links with soft link TOML files

### PR DESCRIPTION
**Pull request by PranitRout07**
**ISSUE DETAILS**

_I tried to host the kubernetes website locally on my windows 11 by following the README.md file. But when i run the command_ "hugo.exe server --buildFuture --environment development" it gives the error : 

error_faced

**WHAT I HAVE DONE?**

I found out that the error is related with the syntax of .toml files in i18n directory(path : website
/i18n/).
So i updated the each .toml file. in this format :

correct way

correct way1

After correcting the .toml files then  i am able to host the website.

error_solved

### CODE REVIEW

**Review by aj11anuj — COMMENTED** [review]
Hey, Changing multiple localization files in a single PR is not recommended, remove other localization file changes and only commit to original 'en' PR. If that's gets merged then it will be syncd to other localizations.

/hold 
(Ok, to unhold when you will remove other localization changes)

**Comment by sftim** [comment]
Check that this doesn't conflict with the fix proposed in (merged) PR https://github.com/kubernetes/website/pull/43211

Please don't unhold until that check is done and confirmed.

**Comment by sftim** [comment]
/retitle Replace localization symbolic links with soft link TOML files

**Comment by Gauravpadam** [comment]
There's a reason #43211 does not change the existing symbolic links; Breaking changes

image

And this

image

It would be as good as deleting the i18n symbolic link directory

**Pull request closed without merging**
