### PR TITLE
fix indent video block

### PR DESCRIPTION
**Pull request by Arhell**
issue https://github.com/kubernetes/website/issues/24022
remove br for fix indent
en [PR](https://github.com/kubernetes/website/pull/22595)
/area web-development

### CODE REVIEW

**Comment by Arhell** [comment]
before
https://kubernetes.io/id/#video
after (review page)
https://deploy-preview-24050--kubernetes-io-master-staging.netlify.app/id/#video
/assign @irvifa

**Comment by dougsland** [comment]
tested locally, make sense +1

**Comment by irvifa** [comment]
Thank you 🎉 
/lgtm
/approve

**Pull request merged**
