### PR TITLE
Update docs to reference container image registry registry.k8s.io

### PR DESCRIPTION
**Pull request by ameukam**
k8s.gcr.io is deprecated in favor of registry.k8s.io. The kubernetes
codebase have been updated with the new endpoint.

Ref: https://github.com/kubernetes/k8s.io/issues/3411

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @dims 
/assign @jimangel @shannonxtreme

**Comment by sftim** [comment]
Should we do this switchover

- on the day of the v1.25 release?
- earlier?
- later?

**Comment by ameukam** [comment]
> Should we do this switchover
> 
> * on the day of the v1.25 release?
> * earlier?
> * later?

I would be interested to do it the day of the release but I think we need to talk to current release doc team.

**Comment by sftim** [comment]
> I would be interested to do it the day of the release but I think we need to talk to current release doc team.

For that, check in with `#release-comms` / `#release-docs` on Kubernetes Slack. You would also target a different Git branch: _dev-1.25_.

We can backport this change to the docs for older releases; does that sound like a good idea?

**Comment by sftim** [comment]
/retitle Update docs to reference container image registry registry.k8s.io

**Comment by sftim** [comment]
/hold

A rebase (against _dev-1.25_) should sort this. Once the PR is down to 1 commit, feel free to unhold.

**Comment by Sea-n** [comment]
It seems wrong to have 83 rebased commits.

Hold until git issue solved.
/hold

**Comment by Sea-n** [comment]
Hey @ameukam,

It's been days since the last update, would you like to solve the git problem and move forward?

**Comment by ameukam** [comment]
> Hey @ameukam,
> 
> It's been days since the last update, would you like to solve the git problem and move forward?

Replaced by https://github.com/kubernetes/website/pull/35803.
/close

**Pull request closed without merging**
