### PR TITLE
Move "Object management using kubectl"

### PR DESCRIPTION
**Pull request by tengqm**
The section contains four articles which fit better under concepts.

Closes: #4178

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6815)

### CODE REVIEW

**Comment by heckj** [comment]
@tengqm looks like the underlying files have changed - this PR needs a rebase at a minimum. That said, a tremendous amount of the content within those pages is "how to" - and seems more relevant to tutorial and tasks than concepts. The concept of declarative management is certainly warranted under concepts, but perhaps this is better achieved with breaking up these existing articles into separate files - one for the concept, and the remaining under tasks.

**Comment by tengqm** [comment]
@heckj Will revise, thanks.

**Comment by zhangxiaoyu-zidif** [comment]
@tengqm you may forget this PR. =)

**Comment by tengqm** [comment]
@zhangxiaoyu-zidif Occupied by other tasks these days. Will catch up.
I didn't do a "quick fix" because this needs some further thoughts. The issue was complaining that the articles are better categorized as "concepts", while @heckj is suggesting this could still be "tutorials" or "tasks". So ... how to make both groups of people happy is a challenge.

**Comment by heckj** [comment]
@tengqm don't worry about all the refactoring I'm talking about, better to rebase because this is all forward motion regardless. docs team probably ought to have some serious talks about how to break up some of these boulders (and if we want to) as we continue to evolve into the concepts/tasks/reference structure.

**Pull request merged**
