### PR TITLE
rerun scripts/releng/update-release-info.sh and add two necessary image

### PR DESCRIPTION
**Pull request by howieyuen**
related issue: https://github.com/kubernetes/website/issues/34048

### CODE REVIEW

**Comment by howieyuen** [comment]
Could you please help to take a look here? this pr is hanged for 7 days...
@sftim

**Review by rolfedh — APPROVED** [review]

**Comment by ameukam** [comment]
cc @kubernetes/sig-release-leads

**Review by saschagrunert — APPROVED** [review]
/lgtm
/unhold

**Pull request merged**
