### PR TITLE
Move bootstrap-4.3.1.min.js and jquery-3.2.1.min.js to kubernetes-api/v1.18/js dir

### PR DESCRIPTION
**Pull request by Cweiping**
bootstrap-4.3.1.min.js and jquery-3.2.1.min.js  is kubernetes-api include file，the `kubernetes-api/v1.18` dirs use
https://github.com/kubernetes-sigs/reference-docs to generated.
 
Fix Issue：https://github.com/kubernetes/website/issues/22041 、https://github.com/kubernetes/website/issues/22064
Mention Issue: https://github.com/kubernetes/website/issues/22024

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
This is NOT the right move.
We should instead keep the js files under `static/js` as shared assets and have API references reference them from a known location.
We are about to move all css files, font files and js files out of the `static/docs/reference/generated/kubernetes-api/<version>` directory and place them under `static/css`, `static/fonts` and `static/js` directory.
For each new release in the future (hopefully, 1.19 included), we only copy the `index.html` and `navData.js` files from the generator.

**Comment by Cweiping** [comment]
OK,so these two problems don't hold up. Try to close it:
 https://github.com/kubernetes/website/issues/22041 、https://github.com/kubernetes/website/issues/22064
@tengqm

**Comment by tengqm** [comment]
see #22357

**Pull request closed without merging**
