### PR TITLE
Added Kubevious to Cluster Administration Addons

### PR DESCRIPTION
**Pull request by rubenhak**
Kubevious is an application-centric visualizer for Kubernetes.

Kubevious improves Kubernetes usability by identifying configuration errors, enforcing best practices, time machine, and other capabilities to make configuration more obvious and safe.

### CODE REVIEW

**Comment by rubenhak** [comment]
I signed it

**Comment by rubenhak** [comment]
@kbhawkey, @jimangel, please see the link below for your reference:
[https://deploy-preview-22068--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/addons/](https://deploy-preview-22068--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/addons/)

**Comment by rubenhak** [comment]
@sftim, thanks for reviewing. I checked the content guide, it says "Docs can link to third-party open source software (OSS) outside the Kubernetes project only if it's necessary for Kubernetes to function." While Kubevious is an OSS project. Its necessity for Kubernetes to function is same as with other two visualization tools (Dashboard and WeaveScope) listed in [Visualization & Control](https://kubernetes.io/docs/concepts/cluster-administration/addons/#visualization-amp-control)

**Comment by sftim** [comment]
Hi @rubenhak 

Can you add some extra detail about how https://kubevious.io/ is necessary for Kubernetes to function? For example: if I have a cluster and remove that tool, what are the symptoms?

**Comment by rubenhak** [comment]
> Hi @rubenhak
> 
> Can you add some extra detail about how https://kubevious.io/ is necessary for Kubernetes to function? For example: if I have a cluster and remove that tool, what are the symptoms?

@sftim, while Kubernetes will continue to operate after removing Kubevious, it would be very hard for Kubernetes operators to manage application deployments and function efficiently.

In that regards it is similar to WeaveScope. While WeaveScope provides visualization of operational state of apps, Kubernetes provides visualization of configuration of apps. WeaveScope and Kubevious are complementing and together provide best experience to Kubernetes.

**Comment by sftim** [comment]
> WeaveScope

There's an open issue to remove links like that - see https://github.com/kubernetes/website/issues/20232

**Comment by rubenhak** [comment]
> > WeaveScope
> 
> There's an open issue to remove links like that - see #20232

Understood. Thanks for reviewing.

**Comment by sftim** [comment]
I'm minded to close this PR. @rubenhak I hope I've explained why this PR falls outside the content guidelines.

**Comment by rubenhak** [comment]
@sftim, sure, please do

**Comment by sftim** [comment]
/close

Proposed change is out of line with website content guide.

**Pull request closed without merging**
