### PR TITLE
Changed the instructed master/slave to primary/seconday

### PR DESCRIPTION
**Pull request by pranav-pandey0804**
Fixed issue #41284 
Replaced 
`labels: app: guestbook tier: backend role: master` and `labels: app: guestbook tier: backend role: slave` 
with
`labels: app: guestbook tier: backend role: primary` and `labels: app: guestbook tier: backend role: secondary`

### CODE REVIEW

**Comment by shannonxtreme** [comment]
This is a snippet of a code sample here: https://github.com/kubernetes/examples/tree/master/guestbook/ 

However we have a more current example hosted in k/website: https://github.com/kubernetes/website/tree/main/content/en/examples/application/guestbook

I suggest the following:

* Change the link in the intro paragraph to the k/website example
* Update the YAML snippets to match the k/website example (which uses "follower" and "leader" instead of "master/slave"

**Comment by pranav-pandey0804** [comment]
Hi @shannonxtreme , thanks for the link and the suggestions.
They seem valid, I'll change them to match the more recent examples.

**Comment by pranav-pandey0804** [comment]
@shannonxtreme i think the [guestbook example](https://github.com/kubernetes/examples/tree/master/guestbook/) link under [Using labels effectively](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#using-labels-effectively) section also need to be changed to the link you provided of the most recent examples. 
Please let me know if i should change it?

**Review by smerik — COMMENTED** [review]
The example result for `kubectl get pods` still contains the roles master/slave.
Also the example command & results for `kubectl get pods -lapp=guestbook,role=slave` should be updated.

**Comment by shannonxtreme** [comment]
@pranav-pandey0804 sorry for the long response time, yes, the link should be changed. and +1 to @smerik  to change the Pod command and output

**Comment by pranav-pandey0804** [comment]
Hi @shannonxtreme sorry for the late response, thanks for the patience as well, let's solve this issue, just one thing i wanted to discuss.
> The example result for kubectl get pods still contains the roles master/slave.

@smerik the pods in this example are created from [this](https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml) file, what do you guys suggest i should do about it ?

the [link](https://github.com/kubernetes/website/tree/main/content/en/examples/application/guestbook) that @shannonxtreme provided doesn't contain that type of file, it's a multi-source yaml file.

Would it be right to change the original link or should i modify the original yaml file labels instead?

**Comment by reylejano** [comment]
Hi @pranav-pandey0804 , this PR has a merge conflict and needs rebase therefore I'm closing this PR.
If you have time to rebase, feel free to reopen the PR with `/reopen` in a comment
/close

**Pull request closed without merging**
