### PR TITLE
Add zacharysarah to approvers/reviewers for English language content

### PR DESCRIPTION
**Pull request by zacharysarah**
Hi, folks! 👋🏻

I'm a [former approver/reviewer](https://github.com/kubernetes/website/pull/27637) for SIG Docs. I'd like to rejoin, if you'll have me.

### CODE REVIEW

**Comment by sftim** [comment]
Raúl Juliá recorded the voice effects for the all-time best selling pinball table, [The Addams Family](https://en.wikipedia.org/wiki/The_Addams_Family_(pinball)).

If GitHub had any way to let me, I'd add the “**welcome back!**” sample from that game into this comment.

/approve

**Comment by dims** [comment]
welcome back @zacharysarah !

**Comment by zacharysarah** [comment]
Thanks, @dims!

**Pull request merged**
