### PR TITLE
Fix #15161 - Fix card alignments in kubernetes baiscs tutorial page.

### LINKED ISSUE #15161: Improvement for k8s.io/docs/tutorials/kubernetes-basics/
the section #kubernetes-basics-modules is useful in the sense that there are links and accompanying graphics that link off to their respective pages, but it's not obvious that's what it is. Visually, it should look more like an index, and the user interface should make it more obvious. As it is, it looks like an overly bare-bones overview.

### PR DESCRIPTION
**Pull request by miteshskj**
Fixes #15161 

The _index.html did not have stylesheet links causing incorrect layout. Included them for all languages which had _index.html files.

### CODE REVIEW

**Comment by miteshskj** [comment]
fix_1561_en

fix_1561_fr

fix_1561_ja

**Comment by kbhawkey** [comment]
Hi @miteshskj .
Thanks for looking into the styling of the tutorial pages and the blog base layout.
- My version of the page preview shows the layout differently -- the font sizing is not correct
and the layout appears to be flattened out.
- Since all language versions of the tutorial use the same CSS files, it would be good
to include these files in a single CSS file.
- Is styles.css outdated? 

https://deploy-preview-17051--kubernetes-io-master-staging.netlify.com/docs/tutorials/kubernetes-basics/

**Comment by miteshskj** [comment]
Thanks for reviewing @kbhawkey 
Updated the PR, removed all other css and just included styles.css and it fixed the issues you reported. No need to update styles.css.

Please review again.

**Comment by kbhawkey** [comment]
Hi @miteshskj. I reviewed the changes and preview again.
Many of the tutorials link to en/docs/tutorials/kubernetes-basics/public/css/styles.css. However, the pages that include this file, appear to alter the font size in the header and footer. I think this change needs further investigation.
/hold

**Comment by kbhawkey** [comment]
For further information, see https://github.com/kubernetes/website/issues/17108.

**Comment by kbhawkey** [comment]
@miteshskj , I created a PR (#17177) to fix the styling of the tutorial pages.
With your last commit, did you remove the update of bootstrap.min.css in layouts/blog/baseof.html? I don't see this change anymore.

**Comment by chenrui333** [comment]
Thanks!

**Comment by miteshskj** [comment]
Thanks @kbhawkey ! Yes I reverted the blog file as the bootstrap css was not needed in index.html so didn't see the need to upgrade the version in blog.

**Comment by kbhawkey** [comment]
> 
> 
> Thanks @kbhawkey ! Yes I reverted the blog file as the bootstrap css was not needed in index.html so didn't see the need to upgrade the version in blog.

OK. If this information is in the commit message, would you remove the comment about updating the blog file?

**Comment by miteshskj** [comment]
Commit message was updated, I have updated the PR description to remove the blog file info.

**Comment by kbhawkey** [comment]
@miteshskj , The English version of the page, for the multi-step graphics, looks okay now.

**Comment by miteshskj** [comment]
Thank you @kbhawkey

**Pull request merged**
