### PR TITLE
Update container-runtimes.md

### PR DESCRIPTION
**Pull request by anwesh-b**
Added few lines to help people understand the procedure

### CODE REVIEW

**Comment by anwesh-b** [comment]
I signed the Contributor License Agreement (CLA).
The test still shows red cross on the test. Is there anything more to be done?

**Comment by anwesh-b** [comment]
I signed the Contributor License Agreement (CLA).

**Review by bart0sh — APPROVED** [review]

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-24780--kubernetes-io-master-staging.netlify.app/docs/setup/production-environment/container-runtimes/

**Pull request merged**
