### PR TITLE
RuntimeClass documentation

### PR DESCRIPTION
**Pull request by tallclair**
RuntimeClass documentation.

For https://github.com/kubernetes/features/issues/585

/milestone v1.12

### CODE REVIEW

**Comment by zparnold** [comment]
Thanks @tallclair! When you have a moment, could I please have you flesh out this documentation a bit?

**Comment by justaugustus** [comment]
@tallclair -- is this good to go for 1.12? Docs are overdue. Please let us know ASAP what the status is.

**Comment by tallclair** [comment]
Sorry for the delay (I was OOO), this is ready for review. The feature is good to go for 1.12.

**Comment by zparnold** [comment]
/lgtm
/approve
@tallclair for bonus points, if you have an End-To-End (setting up a CRI on a node, adding the RuntimeClass...) example for this that could be documented in the tasks section, it would be amazing!

**Pull request merged**
