### PR TITLE
Update Hugo to 0.64.0

### LINKED ISSUE #18406: Incorrect comment format display
**This is a Bug Report**

**Problem:**
The page incorrect with the comment, such as: `https://kubernetes.io/zh/docs/concepts/services-networking/ingress/#%E4%B8%93%E7%94%A8%E6%9C%AF%E8%AF%AD`. It was correct in my mac, and the version of hugo is `Hugo Static Site Generator v0.62.1/extended darwin/amd64`.

**Proposed Solution:**
Update hugo in server.

**Page to Update:**
https://kubernetes.io/zh/docs/concepts/services-networking/ingress/#%E4%B8%93%E7%94%A8%E6%9C%AF%E8%AF%AD.

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR updates the website's Hugo version to the most recent bug-fix release.

This PR fixes #18406. 

This PR also updates k/website for the latest version of Goldmark support.

/sig docs
/kind cleanup
/assign @kbarnard10

### CODE REVIEW

**Comment by gavinfish** [comment]
This upgrade may introduce some break changes, refer to https://deploy-preview-19028--kubernetes-io-master-staging.netlify.com/docs/concepts/configuration/pod-overhead/.

**Comment by Colstuwjx** [comment]
Hi @zacharysarah ,

It will be appreciated If you could share with us about the reason why we need this PR.

**Comment by gavinfish** [comment]
@Colstuwjx, this upgrade will fix #18406.

**Comment by sftim** [comment]
@zacharysarah would you like any help with the breaking-changes aspect of this PR?

**Comment by zacharysarah** [comment]
@Colstuwjx Apart from fixing #18406 (description updated), this is mostly to capture the latest iterations of Goldmark support. 

@gavinfish That's one heck of a breaking change! 
@sftim Yes, help would be lovely. 🙏

**Comment by sftim** [comment]
I'll take a look. It might also take me a while to do that.

**Comment by jimangel** [comment]
@zacharysarah I was playing around with updating the site to Hugo 67.0 and discovered a few (related) bugs.

The `feature-state` [partial template](https://github.com/kubernetes/website/blob/master/layouts/partials/templates/feature-state.html) not loading properly is because Hugo v0.60.0+ disables inline HTML in markdown.

See this [Hugo v0.60.0 release post](https://gohugo.io/news/0.60.0-relnotes/) from @bep.

It can ignored by adding the following to `config.toml`:
```
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```

> We might do this to **temporarily** avoid heartburn, but it would be great to remove all unsafe inline HTML.
> 
> Why it was disabled by default: https://github.com/gohugoio/hugo/issues/6581

After the change is made in `config.toml` the feature state button loads fine, but the feature state is expanded by default. For example:



I saw that @kbhawkey had some experience modifying the template script (in PR [#9994](https://github.com/kubernetes/website/pull/9994)). Any suggestion on the best way to resolve this would be appreciated!

## Other things discovered

### Pygments is [removed as highlighter](https://github.com/gohugoio/hugo/issues/4491).

We might need to update our `config.toml` to be more inline with https://gohugo.io/getting-started/configuration-markup#highlight


### Plain HTML documents are not supported

This causes issues with any files that are 100% HTML. As of now, the only files Hugo errors about are:

```
content/de/includes/user-guide-migration-notice.md
content/en/includes/user-guide-migration-notice.md
content/fr/includes/user-guide-migration-notice.md
content/ja/includes/user-guide-migration-notice.md
content/zh/includes/user-guide-migration-notice.md

# you can easily delete them with: 

find content/ -name "*user-guide-migration-notice.md" -exec git rm {} \;

# otherwise convert them to markdown if they are needed
```

### We should probably delete blackfriday `config.toml` references

```
#[blackfriday]
#hrefTargetBlank = true
#fractions = false
```

## Next steps

Let me know if you want to continue out of this PR or want me to open up a new one.

- [ ] Update `netlify.toml` to `0.67.0`
- [ ] Delete or fix (convert to markdown) offending `user-guide-migration-notice.md` files in each localization
- [ ] Decide if it's worth back-filling old releases (release-x.xx)
- [ ] Remove blackfriday stuff in `config.toml`

## Considerations

- Kubernetes `v1.18` it tentative to be released on **Tuesday, March 24, 2020** which involves a lot of docs work.
- Does this impact the current work being done to update our theme?
- Removing all unsafe html should not fall off our radar.
- Does goldmark / commonmark do anything else unknown to our existing docs?

## Other
I found the [CommonMark markdown spec](https://spec.commonmark.org/0.29/) useful to answer any formatting / HTML questions. CommonMark is the spec replacing the currently used Blackfriday spec.

Lastly, I encourage folks to read the [release notes](https://gohugo.io/categories/releases) from **0.59.1** -> **v0.67.0**

/cc @kbarnard10 @bradtopol @kbhawkey @sftim @lucperkins

**Comment by tengqm** [comment]
This summary is nice!

**Comment by kbhawkey** [comment]
👎 Markdown pages that include HTML (all or nearly all kubeadm tool pages),
https://deploy-preview-19028--kubernetes-io-master-staging.netlify.com/docs/reference/setup-tools/kubeadm/kubeadm-init/

**Comment by zacharysarah** [comment]
@jimangel 👋Thanks for the excellent summary! 
> Let me know if you want to continue out of this PR or want me to open up a new one.

Go ahead and open a new one, I'll close this one now.

/close

**Pull request closed without merging**
