### PR TITLE
Made additions in "Why use Kubernetes, what can it do" section

### PR DESCRIPTION
**Pull request by aj11anuj**
I had made some addition of points in docs Why we need Kubernetes and what can it do section. I had added these points:-

`"Scheduling flexiblity and Auto-Scaling"`
`"Monitoring"`
Whenever we learn Kubernetes through some tutorials, they usually point out these points while explaining why kubernetes is popular, why we need it, what was the problem while managing the conatiners etc etc. Well these 2 points `Scheduling flexiblity and Auto-Scaling`, `Monitoring` are indirectly written there but i thought of explicitly mentioning these points for more clarity.

Refer: #43047 (Sorry for messing there while squashing commits)

### CODE REVIEW

**Comment by kbhawkey** [comment]
👋 @aj11anuj 
Does it makes sense to keep the original text?
I don't think the colons add value.
Thanks

**Comment by aj11anuj** [comment]
1. See this below preview, The main highlighted points are submerged like common sentences, there is a need of colons to separate highlighted points from its descriptive explaination.

Screenshot_2023-09-15-18-21-51-422_com android chrome

2. I don't know, what you meaned by "Is keeping original text makes sense" can you clarify it? I haven't kept any original text, just made additions of those 2 points with there explanation, which was completely referenced from my previous PR that was ready for lgtm label but messed somehow while squashing commits.

**Comment by windsonsea** [comment]
Seems adding `:` can provide a consistent style similar to line 41-63 in previous section.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-43061--kubernetes-io-main-staging.netlify.app/docs/concepts/overview/

**Comment by kbhawkey** [comment]
@aj11anuj 
I missed the existing colons on the page.

**Comment by reylejano** [comment]
I agree with @kbhawkey on this PR that the original text is preferred
I also don't agree to add the following from this PR:
> **Scheduling flexibility and auto-scalability:**
  Kubernetes provides you with the flexiblity to schedule the containers
  without writing manual scripts for getting metrices, tracing metrics,
  and supports different environments such as development, production, testing and staging.
  Moreover, Kubernetes facilitates seamless scaling by automatically replicating pods across nodes
  or environments to meet your specific needs.
> **Monitoring:**
  With Kubernetes, monitoring a large number of container becomes hassle-free.
  In the event of a container or pod failure, Kubernetes promptly self-heals or replaces them,
  notifying you about their health status by communicating with the API server.
  This eliminates the requirement of writing numerous manual scripts

Although somewhat true, it is not hassle-free for monitoring and you need something additional for monitoring and auto-scaling can be understood for cluster autoscaler (https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler)

/close

**Pull request closed without merging**
