### PR TITLE
Fix minor typo in StatefulSets docs

### PR DESCRIPTION
**Pull request by cognifloyd**
`s/tpycally/typically/`

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@cognifloyd 
Pls sign the CLA in order for the PR to be reviewed.

**Comment by cognifloyd** [comment]
I signed the CLA

**Comment by cognifloyd** [comment]
I signed it

**Comment by kbhawkey** [comment]
Hi @cognifloyd .
Would you check that your CLA account data (email) matches your GitHub account email?

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-24643--kubernetes-io-master-staging.netlify.app/docs/concepts/workloads/controllers/statefulset/#stable-network-id

Thanks @cognifloyd

**Pull request merged**
