### PR TITLE
Remove Poseidon page

### PR DESCRIPTION
**Pull request by tengqm**
The [Poseidon project](https://github.com/kubernetes-sigs/poseidon/commits/master) is virtually dead:

- No PRs coming in since Dec 2019
- No PRs in pipeline for review
- PRs related to code changes date back to April 2019.

By removing this page, we can save folks' effort on localizing the content, i.e. #22265.

### CODE REVIEW

**Comment by sftim** [comment]
Part of https://github.com/kubernetes/website/issues/20232

**Comment by sftim** [comment]
/hold
as this is a third-party content removal.

/lgtm

**Comment by tengqm** [comment]
@sftim Any reason we hold for removal of 3rd party content?

**Comment by sftim** [comment]
@tengqm
> we're giving stakeholders until the 1.19 release deadline for docs, July 9th, 2020 to re-home any content slated for removal

from https://kubernetes.io/blog/2020/05/third-party-dual-sourced-content/

We should find the original authors (or other likely stakeholders) and notify them about this PR.

**Comment by tengqm** [comment]
@sftim Fair enough and fine with me. Thanks.

**Comment by sftim** [comment]
/approve cancel
I LGTMd it.

**Comment by sftim** [comment]
D'oh!

**Comment by sftim** [comment]
(happy to see it merge - just not quite the right process for a whole-page removal)

**Pull request merged**
