### PR TITLE
Merged master to release 1.17

### PR DESCRIPTION
**Pull request by VineethReddy02**
As a part of docs, release teamwork syncing up branches between master and release-1.17
@jimangel @zacharysarah

### CODE REVIEW

**Comment by sftim** [comment]
I'll take a look in about 6 hours

**Comment by VineethReddy02** [comment]
HI, @zacharysarah @sftim I would appreciate it if we can merge this.
As it a already week old. I am looking forward to another sync in the upcoming week.

Thanks!

**Comment by sftim** [comment]
Oh, sorry about the wait!

**Comment by VineethReddy02** [comment]
@sftim no worries Tim! It was just a reminder. Take your time. I wanted to remind that the upcoming week will have one more sync up. :)

**Pull request merged**
