### PR TITLE
Fix VolumeSubpathEnvExpansion feature gate

### PR DESCRIPTION
**Pull request by daminisatya**

### CODE REVIEW

**Comment by daminisatya** [comment]
@kbhawkey please review

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-18033--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/feature-gates/

LGTM, though, this PR is blocked?

**Comment by daminisatya** [comment]
Yes, I removed the block. I think you can apply the lgtm label now

**Comment by daminisatya** [comment]
@kbhawkey

**Pull request merged**
