### PR TITLE
fix typo, iff -> if

### PR DESCRIPTION
**Pull request by panli889**

### CODE REVIEW

**Comment by tengqm** [comment]
@panli889 Thanks for the contribution but this fix is incorrect. We are supposed to regenerate the reference docs out of the upstream source code rather than manually fix typos directly.
Please refer to https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/ if you want to help out.
/close

**Comment by panli889** [comment]
> @panli889 Thanks for the contribution but this fix is incorrect. We are supposed to regenerate the reference docs out of the upstream source code rather than manually fix typos directly. Please refer to https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/ if you want to help out. /close

Thanks for your reply! I will check the upstream source code!

**Pull request closed without merging**
