### PR TITLE
[zh] corrected port designation in get service output

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/27009

### CODE REVIEW

**Comment by Arhell** [comment]
cc @tengqm

**Comment by tengqm** [comment]
Another change on line 256 and 259 has to be changed as well. It is about a link target.

**Comment by Arhell** [comment]
> Another change on line 256 and 259 has to be changed as well. It is about a link target.

`./scripts/lsync.sh content/zh/docs/tasks/debug-application-cluster/debug-service.md
content/zh/docs/tasks/debug-application-cluster/debug-service.md is still in sync
`

**Pull request closed without merging**
