### PR TITLE
update generated api-reference docs for 1.10

### PR DESCRIPTION
**Pull request by Bradamant3**
Also updated the _data/reference.yml file, in addition to the generated docs.

It looks as though the issue with the make copyapi -- or possibly with cp, haven't checked that far -- is that it does not like to create directory names with punctuation in them. Or least, not with either dashes or periods. Not fully tested yet, not sure what to recommend going forward. Will ponder later. Thanks for all your help.

Addendum: the previous is not correct. Or at least, it does not appear to be an issue with the generated kubectl docs. 

/assign @steveperry-53

### CODE REVIEW

**Comment by zacharysarah** [comment]
/lgtm
/approve
/hold
@Bradamant3 Please feel free to remove the `/hold` when you're ready.

**Comment by steveperry-53** [comment]
@Bradamant3 Initial pass: It doesn't seem right that we have several cases of "File renamed without changes". I'll look a little deeper.

**Comment by Bradamant3** [comment]
@steveperry-53 you've been through this before, so I'll defer to you. But when I saw those "File renamed without changes" diffs, I also noticed that they are all css/js files for presenting the content. They aren't content files themselves. So I'd sort of expect them to remain the same.

**Comment by steveperry-53** [comment]
```
new file:   docs/reference/generated/kubernetes-api/v1.10/index.html
        new file:   docs/reference/generated/kubernetes-api/v1.10/navData.js
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/bootstrap/dist/css/bootstrap.min.css
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/font-awesome/css/font-awesome.css
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/font-awesome/css/font-awesome.css.map
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/font-awesome/css/font-awesome.min.css
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/font-awesome/fonts/FontAwesome.otf
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/font-awesome/fonts/fontawesome-webfont.eot
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/font-awesome/fonts/fontawesome-webfont.svg
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/font-awesome/fonts/fontawesome-webfont.ttf
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/font-awesome/fonts/fontawesome-webfont.woff
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/font-awesome/fonts/fontawesome-webfont.woff2
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/highlight.js/styles/default.css
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/jquery.scrollto/jquery.scrollTo.min.js
        new file:   docs/reference/generated/kubernetes-api/v1.10/node_modules/jquery/dist/jquery.min.js
        new file:   docs/reference/generated/kubernetes-api/v1.10/scroll.js
        new file:   docs/reference/generated/kubernetes-api/v1.10/stylesheet.css
        new file:   docs/reference/generated/kubernetes-api/v1.10/tabvisibility.js
```

**Comment by Bradamant3** [comment]
hrm. OK, running various things again. bc kubectl docs also messed up.

**Comment by steveperry-53** [comment]
@Bradamant3 Given that you deleted the 1.9 files, I think this PR is correct.
/approve

**Pull request merged**
