### PR TITLE
[Re-open][ko] Matching reference page as its language

### PR DESCRIPTION
**Pull request by dangen-effy**
Update href value

### CODE REVIEW

**Comment by pjhwa** [comment]
@dangen-effy Ooops. Something wrong, I think.
You should create a NEW PR. Please clone your forked branch again and fix the issue, then push it. 
Please try this again. 👍

**Comment by pjhwa** [comment]
@dangen-effy For your information, the dev-1.19-ko.2 working branch for Korean Team will be frozen by today(9/21). 
So, if you want to merge this PR into dev-1.19-ko.2 branch, please open a NEW PR for this issue by today.
And your CLA signing still have issue. Please re-check your CLA signing status.

The following email addresses must be the same:
- registered on GitHub
- registered on Linux Foundation
- registered on https://github.com/cncf/gitdm
- local git email address configuration (for example: git config --global user.email "user@email.com")

Thank you.

**Comment by dangen-effy** [comment]
@pjhwa Got it!

**Pull request closed without merging**
