### PR TITLE
Fix broken links identified by linkchecker

### LINKED ISSUE #20923: Tracking issue: fix broken internal links identified by linkchecker
Related: #20607

Correct the initial swath of broken links identified when configuring and using the https://github.com/wjdp/htmltest link checker. This ensures any potential new users have a good first time experience.

### PR DESCRIPTION
**Pull request by celestehorgan**
Related/parent issue: #20607

Closes #20923 

---

This PR closes all links found using the initial configuration of https://github.com/wjdp/htmltest #20606. It can be closed independently.

---

todo:

- [x] Figure out where `#frameworkhandle` on [this page](https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/#permit) is supposed to link to: Per [discussion on slack](https://kubernetes.slack.com/archives/C1J0BPD2M/p1589309435062200), these were redirected either to the KEP or removed.

### CODE REVIEW

**Comment by celestehorgan** [comment]
Preview links (currently being edited to include the full list, check back in 10 mins):
https://deploy-preview-20924--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/flow-control/ (yikes this has some problems – fix in another PR, perhaps..?)
https://deploy-preview-20924--kubernetes-io-master-staging.netlify.app/docs/concepts/extend-kubernetes/operator/
https://deploy-preview-20924--kubernetes-io-master-staging.netlify.app/docs/concepts/scheduling-eviction/scheduling-framework/

**Comment by kbhawkey** [comment]
Hi @celestehorgan .
I looked through the changes. Seems fine.
Would you squash your commits into a single commit?
In your note about some pages not rendering, this page
was updated recently, 
https://deploy-preview-20924--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/flow-control/

**Comment by sftim** [comment]
Sorry about the mixed messaging here. It sounds like there's a difference of opinion on how many commits is right for this PR. The _actual_ work? Looks great.

**Comment by kbhawkey** [comment]
@celestehorgan , Are you still working on this PR?

**Pull request merged**
