### PR TITLE
Official 1.26 Release Docs

### PR DESCRIPTION
**Pull request by krol3**
🛑 DO NOT MERGE 🛑 UNTIL KUBERNETES 1.26 IS RELEASED
---
Target Date: 2022-12-06

Release deadlines
From [sig-release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.26#timeline):

Date | Description
-- | --
November 10 | Open Placeholder PRs
November 15 | PRs ready for review
November 29 | All PRs reviewed and ready to merge

cc 1.26 Docs Team: @cathchu  @mickeyboxell @katmutua @Rishit-dagli 
cc @reylejano 
/hold

### CODE REVIEW

**Comment by onlydole** [comment]
Thank you, @krol3! 

/lgtm

**Review by Operate1 — APPROVED** [review]

**Pull request merged**
