### PR TITLE
Translation modification

### PR DESCRIPTION
**Pull request by gaoguangze111**
Storage classes documentation page modification

### CODE REVIEW

**Comment by xichengliudui** [comment]
Is it something on the list?
```
https://github.com/k8smeetup/website-tasks/issues
```

**Comment by msau42** [comment]
Unfortunately I do not understand Chinese. 
/assign @jingxu97 
to help review

**Comment by gaoguangze111** [comment]
@xichengliudui Sry I haven't check on the issue list. Do I have to solve an issue for my PR?

**Comment by xichengliudui** [comment]
@gaoguangze111 可以解决任何问题
```
https://github.com/k8smeetup/website-tasks/issues
```
为什么创建这个 pr，以及 #19252 ，如果是一个 `bug` 你可以引用一个 `issue`，来让其他人更好的理解。

**Comment by gaoguangze111** [comment]
好的，明白了。下次先提issue

**Comment by tanjunchen** [comment]
/cc @xichengliudui
how about this now?

**Comment by xichengliudui** [comment]
/hold cancel
@gaoguangze111  thanks!

**Pull request merged**
