### PR TITLE
update link

### PR DESCRIPTION
**Pull request by lovebaby979**

### CODE REVIEW

**Comment by mittalyashu** [comment]
@lovebaby979 Can you update other links from `http://` to `https://`?

**Comment by mittalyashu** [comment]
> I hope I am at-mentioning the correct person.

@jimangel When we started the localisation of docs in Hindi language, I think we didn't look much into the links and most of the links in Hindi language docs, link back to english docs.

Do we need to update the links to something like: `https://kubernetes.io/hi/`?

Or the user will be automatically redirected based on the language selected?

**Comment by kbhawkey** [comment]
This change seems fine.
@mittalyashu , perhaps you can create new PR to update the other links?
/lgtm

**Review by irvifa — APPROVED** [review]
/approve

**Pull request merged**
