### PR TITLE
Updating DelegateFSGroupToCSIDriver feature to beta

### PR DESCRIPTION
**Pull request by verult**
Enhancement issue: https://github.com/kubernetes/enhancements/issues/2317

### CODE REVIEW

**Comment by ramrodo** [comment]
/lgtm
cc @jlbutler

**Comment by xing-yang** [comment]
@verult I think the feature state should be updated to "beta" for this page as well:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#delegating-volume-permission-and-ownership-change-to-csi-driver

**Comment by verult** [comment]
This change updates that page but for the 1.23 dev branch. I think it will be updated once 1.23 is released - @jlbutler @inductor please let me know if that's not the case. Thanks!

**Pull request merged**
