### PR TITLE
Update configure-persistent-volume-storage.md

### PR DESCRIPTION
**Pull request by RainorshineGW**
吉比特看起来感觉非常奇怪，更改为GB

### CODE REVIEW

**Comment by RainorshineGW** [comment]
'吉比特' looks very strange, changed to GB

**Comment by RainorshineGW** [comment]
'吉比特' looks very strange, changed to GB

**Comment by markthink** [comment]
@RainorshineGW 请参考：https://github.com/k8smeetup/k8s-official-translation 完成 cla 协议的签署..

**Comment by tengqm** [comment]
pending there too long, no CLA, conflict not solved.
/close

**Pull request closed without merging**
