### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by michielvangendt**
Add root slash to CSI ephemeral volumes link.

### CODE REVIEW

**Comment by irvifa** [comment]
@michielvangendt Have you signed the CLA?

**Comment by kbhawkey** [comment]
@michielvangendt , Would you check that your GitHub account data (email) matches the email used to sign your CLA?
To move these changes forward would you rebase?

**Comment by michielvangendt** [comment]
Closed this one in favor of https://github.com/kubernetes/website/pull/25292.

**Pull request closed without merging**
