### PR TITLE
Correct a term used in a recently published blog post

### PR DESCRIPTION
**Pull request by davidhadas**
The post uses wrongly the term `Analysis` instead of using the term `Analytics`
"Security Behavior Analytics" should be used rather than "Security Behavior Analysis"

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Correct a term used in a recently published blog post

**Review by sftim — COMMENTED** [review]
Did you want to change the article slug as well? I'm assuming you'd rather leave this as-is (to avoid making it look like a new article in feeds).

**Comment by davidhadas** [comment]
> Did you want to change the article slug as well? I'm assuming you'd rather leave this as-is (to avoid making it look like a new article in feeds).

To avoid affecting other systems and links, let's leave everything as is apart from this one-word change in the content.

**Pull request merged**
