### PR TITLE
Correcting the example given in `jobs/rabbitmq`

### LINKED ISSUE #15651: Issue with k8s.io/docs/tasks/job/coarse-parallel-processing-work-queue/
**This is a Bug Report**

**Problem:**
The content of https://kubernetes.io/examples/application/job/rabbitmq/worker.py is incorrect.
**Proposed Solution:**
print("Processing " + sys.stdin.lines())  
===>
print("Processing " + sys.stdin.readlines()[0])
**Page to Update:**
https://kubernetes.io/...

### PR DESCRIPTION
**Pull request by vishakhanihore**
Fixes #15651

### CODE REVIEW

**Comment by sftim** [comment]
@vishakhanihore can you explain _why_ this commit is the right change to make?

(I looked at the commit message, and I still wasn't sure I understood).

**Comment by mrbobbytables** [comment]
Going by the comments in the parent issue,  I don't think this should actually be changed. `sys.stdin.readlines()` is valid python3 (tested it quick myself).

**Comment by vishakhanihore** [comment]
Should it be closed @mrbobbytables

**Comment by mrbobbytables** [comment]
@vishakhanihore I think so. Sorry for the confusion on the issue.

**Comment by vishakhanihore** [comment]
> @vishakhanihore I think so. Sorry for the confusion on the issue.

No worries, I will be back with a new PR. Thanks

**Pull request closed without merging**
