### PR TITLE
Link to Baidu's CCM implementation

### PR DESCRIPTION
**Pull request by hello2mao**
**What this PR does / why we need it:**
[BaiduCloud Container Engine](https://cloud.baidu.com/product/cce.html) is a high-performance and scalable container application management service using Kubernetes.
As the gold member of CNCF, we create this PR to add a link to Baidu's CCM implementation.

**Related:**
- [Baidu Joins Cloud Native Computing Foundation As Gold Member](https://www.cncf.io/announcement/2017/12/06/baidu-joins-cloud-native-computing-foundation-gold-member/)
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/providers/0022-cloud-provider-baiducloud.md

### CODE REVIEW

**Comment by hello2mao** [comment]
cc @tizhou86

**Comment by idealhack** [comment]
FWIW, I think you're referring to Baidu as a gold member of CNCF instead of Kubernetes community ;)

**Comment by hello2mao** [comment]
> FWIW, I think you're referring to Baidu as a gold member of CNCF instead of Kubernetes community ;)

Yep, thanks for your remind. More detail in this announcement: [Baidu Joins Cloud Native Computing Foundation As Gold Member](https://www.cncf.io/announcement/2017/12/06/baidu-joins-cloud-native-computing-foundation-gold-member/)

**Comment by Rajakavitha1** [comment]
Checked: https://deploy-preview-12480--kubernetes-io-master-staging.netlify.com/docs/concepts/architecture/cloud-controller/

/lgtm
/approve

**Pull request merged**
