### PR TITLE
[pt-br] Move Portuguese localization files to pt-br folder

### PR DESCRIPTION
**Pull request by stormqueen1990**
### Changes

* Rename the former "pt" folder to "pt-br" in order to keep consistency across the website data.
* Update the symbolic link to point to the file in the renamed folder.
* Remove obsolete `data/i18n/pt/pt.toml` file.

/language pt
/cc @devlware @edsoncelio @rikatz

### CODE REVIEW

**Comment by jimangel** [comment]
Apologies if I missed the context, but the language codes / URLs are based off of the ISO 639-1 Language Code (for example: [Portuguese](https://www.loc.gov/standards/iso639-2/php/langcodes-keyword.php?SearchTerm=portuguese&SearchType=ALL) from the Library of Congress).

I would prefer to see `pt-br` URLs become `pt`, unless there's a compelling reason not to!

I'll leave approvals for current SIG Docs chairs:
/lgtm

**Comment by stormqueen1990** [comment]
> I would prefer to see `pt-br` URLs become `pt`, unless there's a compelling reason not to!

Hi there, @jimangel! I believe this change was enacted via #27413 a while back due to issues with Hugo shortcodes that require the full locale, rather than just the language code. This folder I am changing now appears to have been leftover from that previous refactoring.

**Comment by sftim** [comment]
I thought that the issue we had is compatibility with Docsy, which uses country-specific codes for some languages.

The other thing we have is that our Portuguese localization is mainly in Brazilian Portuguese and not in the Portuguese spoken in Portugal.

I see that we label the `en` localization as `en` not `en-us`; however, that does match Docsy which is also localized to American rather than British English.

**Comment by sftim** [comment]
@stormqueen1990 would you be willing to put this on the agenda for the next SIG Docs meeting? (mostly for visibility)

**Comment by stormqueen1990** [comment]
Hello there, @sftim! Sure, I can do that.
Just to check I'm following the discussion correctly: do we want to discuss whether `pt` or `pt-br` should be used?

**Comment by sftim** [comment]
I think just to check there aren't any objections or outstanding concerns.

**Comment by jihoon-seo** [comment]
Ref: the Chinese case ('zh' to 'zh-cn')
https://github.com/kubernetes/website/pull/34215
> We believe renaming the language is the right thing to do, because this move can make room for other variants of Chinese language, such as 'zh-tw', 'zh-sg' etc.

**Comment by stormqueen1990** [comment]
> @stormqueen1990 do you think you can help word this into a standard we can reference later on? I was thinking of adding some context about this to our localization docs, https://kubernetes.io/docs/contribute/localization/, but i couldn't think of a good way to write it this up in a meaningful way. I'm always more inclined to write down our decisions/standards so we remember later on. If you feel there is something we should add please let me know! thanks!

Hello there, @a-mccarthy! Sure thing, I'll make a draft and create a PR so we can move discussion over there. Is it alright if I create an issue for that specific piece of documentation, so we don't lose track of it?

**Comment by a-mccarthy** [comment]
>Is it alright if I create an issue for that specific piece of documentation, so we don't lose track of it?

@stormqueen1990 definitely, creating an issue is a great idea! thanks for helping with this

**Comment by stormqueen1990** [comment]
Created PR #38453 to discuss the best way of documenting this specificity.

**Pull request merged**
