### PR TITLE
Config toml 1.26

### PR DESCRIPTION
**Pull request by krol3**
update release-1.25 config.toml for new release 1.26

### CODE REVIEW

**Comment by reylejano** [comment]
According to the title and description, this PR should be a single file change just for config.toml
This PR looks like it is also syncing `main` into the `dev-1.26` branch
I think we should keep a sync PR separate from the config.toml change

**Comment by sftim** [comment]
> According to the title and description, this PR should be a single file change just for config.toml This PR looks like it is also syncing `main` into the `dev-1.26` branch I think we should keep a sync PR separate from the config.toml change

/hold

**Comment by krol3** [comment]
Closing in favor of https://github.com/kubernetes/website/pull/36928

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de en es fr hi id ja ko pl pt vi zh
/remove-sig release

**Pull request closed without merging**
