### PR TITLE
Update curlpod.yaml

### PR DESCRIPTION
**Pull request by huanghuangzym**
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7236)

### CODE REVIEW

**Comment by tengqm** [comment]
In apps/v1, the selector must match the labels. Please revise.

**Comment by chenopis** [comment]
@tengqm Does this PR need a rebase?

**Comment by tengqm** [comment]
@chenopis Still need a rebase to check if CI is happy with it.

**Comment by zacharysarah** [comment]
@huanghuangzym 👋 We've migrated the site's framework to Hugo. Please re-open this PR with changes to files in their post-migration location (`/content/en/docs/...`).

**Pull request closed without merging**
