### PR TITLE
Fix typo in control-plane-flags

### PR DESCRIPTION
**Pull request by jimmymccrory**
`ClusteConfiguration` should be `ClusterConfiguration`

### CODE REVIEW

**Comment by jimmymccrory** [comment]
signed CLA

**Review by neolit123 — COMMENTED** [review]
thanks

/lgtm
/sig cluster-lifecycle
/check-cla

**Comment by tengqm** [comment]
"commit missing GitHub user" ...

please try run 'git config user.email' followed by 'git commit --reset-author --amend; git push'.

**Comment by jimmymccrory** [comment]
Thanks, fixed that

**Comment by kbhawkey** [comment]
Thanks @jimmymccrory .
/approve

**Pull request merged**
