### PR TITLE
[hi] Localize content/hi/docs/reference/glossary/cncf.md

### PR DESCRIPTION
**Pull request by amolmote**
Signed-off-by: amolmote <amolmote201@gmail.com>
Re-open pull request due to some conflicts. please review and merge it
Fixes #35600

### CODE REVIEW

**Review by rolfedh — APPROVED** [review]
Looks good to me. I recommend asking a reviewer who is proficient in Hindi to review as well.

**Comment by NitishKumar06** [comment]
/lgtm

@anubha-v-ardhan Would you like to add something?

**Review by anubha-v-ardhan — APPROVED** [review]
/assign
/approve

Thank you @amolmote

**Comment by amolmote** [comment]
thank you @rolfedh , @anubha-v-ardhan and @NitishKumar06

**Pull request merged**
