### PR TITLE
Update assign-pod-node.md

### PR DESCRIPTION
**Pull request by cgiogkarakis**
Small fix for inconsistency between examples' yaml and narrative explanation, for Node affinity and Nod affinity weight sections.

### CODE REVIEW

**Comment by yanrongshi** [comment]
I don't think there's anything wrong with the original，see #32646

**Comment by kbhawkey** [comment]
Related to #34967

**Comment by kbhawkey** [comment]
Hello @cgiogkarakis .
PR https://github.com/kubernetes/website/pull/32646/ recently updated the example spec file and content page.
Does this PR address a different issue? Thanks.

**Comment by natalisucks** [comment]
Hello @cgiogkarakis – do you mind addressing @kbhawkey's comment so we can move forward with this PR? Thanks for your contribution so far 🙂

**Comment by Sea-n** [comment]
Hey @cgiogkarakis,

Thanks for purposing this PR. But since you didn't respond for a while, we have to close this PR now.
/close

Feel free to `/reopen` when you are ready to move forward.
(Note that please don't push anything while PR closed, or you won't be able to reopen it.)

**Pull request closed without merging**
