### PR TITLE
[WIP] KEP-4191: Split Image Filesystem add blog post about the feature

### PR DESCRIPTION
**Pull request by kwilczynski**
- One-line PR description: Add a blog post to introduce and showcase the [KEP-4191](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4191-split-image-filesystem/README.md) "Split Image Filesystem"

- Issue link: https://github.com/kubernetes/enhancements/issues/4191

- Other comments:

A placeholder for now.

Related:

- https://github.com/kubernetes/website/pull/43971

### CODE REVIEW

**Comment by sftim** [comment]
I recommend closing this PR @kwilczynski 

You can open it again (or make a new PR) if you want to blog about this feature for a future release.

**Comment by kwilczynski** [comment]
> I recommend closing this PR @kwilczynski
> 
> You can open it again (or make a new PR) if you want to blog about this feature for a future release.

@sftim, sounds good!

**Pull request closed without merging**
