### PR TITLE
Pick right solution

### PR DESCRIPTION
**Pull request by tonglil**
Clean up of this page.

IMO the table doesn't really make sense to be ordered this way anymore without any result showing test results, and should just be alphabetically sorted/by support level.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6604)

### CODE REVIEW

**Comment by heckj** [comment]
@tonglil - looks like this needs a rebase at this point
/assign

**Comment by heckj** [comment]
:wave: @tonglil - reminder that this PR is pending a rebase, and I'm afraid I can't do that for you on this one.

**Comment by chenopis** [comment]
@tonglil Ping. This PR just needs a rebase. Thx

**Comment by zacharysarah** [comment]
👋 We've migrated the site's framework to Hugo. Please re-open this PR with changes to files in their post-migration location (`/content/en/docs/...`).

**Pull request closed without merging**
