### PR TITLE
Add Vitthal Sai Kaul as Hindi Reviewer

### PR DESCRIPTION
**Pull request by anubha-v-ardhan**
We at Hindi localization would like to add @Babapool as an official reviewer for Hindi as discussed [here on slack](https://kubernetes.slack.com/archives/CJ14B9BDJ/p1670247355517609).
Vitthal has been contributing to Hindi l10n for some time now and helped us localizing more docs and review PRs.

see https://github.com/kubernetes/org/pull/3898
cc @Babapool @divya-mohan0209

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Thank you @anubha-v-ardhan for this PR!
Welcome @Babapool :)

**Comment by Babapool** [comment]
Thank you so much, looking forward to working with everyone 🙏 🤝 
Also, thank you @anubha-v-ardhan for the PR :)

**Comment by ydFu** [comment]
/lgtm
keep contributing！

**Pull request merged**
