### PR TITLE
Update links in page kubeadm-init-phase.md

### PR DESCRIPTION
**Pull request by gaoguangze111**
Update non localized links in page content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
Page updated: https://kubernetes.io/zh/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/

Issue: https://github.com/kubernetes/website/issues/25274

### CODE REVIEW

**Comment by howieyuen** [comment]
thanks for the contribution, but this doc is fully synced here https://github.com/kubernetes/website/pull/25275
Since the v1.20 is coming soon, would you like to work more with doc contribution?
see issue here https://github.com/kubernetes/website/issues/25247, you will find quite a lot syncing job need to be done.
we are very happy if you can join us to make this release more fluently~

**Comment by tengqm** [comment]
@howieyuen What do you think? Since you are working on resyncing these pages, I am leaning towards integrating these changes to your resync work.

**Comment by howieyuen** [comment]
> @howieyuen What do you think? Since you are working on resyncing these pages, I am leaning towards integrating these changes to your resync work.

Yes, that's also my idea too, and these changes already synced in my PR here https://github.com/kubernetes/website/pull/25275

**Comment by tengqm** [comment]
@gaoguangze111 Thank you for filing the issue and raising this PR. Awesome work.
I am gonna close this one in favor of #25275 for several reasons:

- #25275 was committed earlier than this one;
- #25275 has a more complete sync for the page in question, rather than just link fixes.
  (**NOTE**: we have some [new guidelines for tracking page changes](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87))
- Rebasing #25275 onto this one would be unnecessary and difficult.

Please keep watching issues filed and PRs raised.
/close

**Pull request closed without merging**
