### PR TITLE
Fixed number of parameters in api.listPodForAllNamespaces and minor typo

### PR DESCRIPTION
**Pull request by aregnier42**
Fixed number of "null" parameters in api.listPodForAllNamespaces() call from 8 to the required 9
Fixed minor typo on System.out.Println call to make code work

### CODE REVIEW

**Comment by sftim** [comment]
@aregnier42 you will need to sign a contributor license agreement so that we can review your pull request.

Are you OK to sign the CLA?

**Comment by aregnier42** [comment]
> @aregnier42 you will need to sign a contributor license agreement so that we can review your pull request.
> 
> Are you OK to sign the CLA?

Yes I just did.

**Comment by aregnier42** [comment]
I signed the CLA.

**Comment by sftim** [comment]
@brendandburns / @mbohlool / @yue9944882 would one of you like to tech-review this?

**Comment by sftim** [comment]
I'm not sure why the Netlify build failed @aregnier42 

If you can amend the commit (eg change only the timestamp) and force-push it, that should wake up Netlify.

**Comment by aregnier42** [comment]
> I'm not sure why the Netlify build failed @aregnier42
> If you can amend the commit (eg change only the timestamp) and force-push it, that should wake up Netlify.

do you know how to do it from github web UI?

**Comment by aregnier42** [comment]
> I'm not sure why the Netlify build failed @aregnier42
> 
> If you can amend the commit (eg change only the timestamp) and force-push it, that should wake up Netlify.

@sftim I got access to my laptop and did what you suggested directly from git and it looks like this time Netlify worked fine.

**Comment by aregnier42** [comment]
@sftim and @yue9944882 is there anything else that I need to do? thanks

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-21188--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/access-cluster-api/

**Pull request merged**
