### PR TITLE
clean up analytics in footer

### PR DESCRIPTION
**Pull request by kbhawkey**
See issue #22819 .

### CODE REVIEW

**Comment by tengqm** [comment]
At this stage, if the link target is not working properly, commenting the link out might be the best option.
/lgtm

**Comment by kbhawkey** [comment]
I'd like more information about the purpose of this pixel with regard to the site analytics.

**Comment by tengqm** [comment]
@kbhawkey, I may be wrong but my theory is that this link is used to count page visits. On the link target, you can sum up the visits by checking the page referrer.

**Comment by sftim** [comment]
/approve

/hold
Feel free to /unhold

Is this the tool in use? https://github.com/igrigorik/ga-beacon

**Comment by kbhawkey** [comment]
I don't know about the "ga-beacon" tool, but the description of the tool fits.
Could investigate updating the tool to Go 1.12+ or find another way/tool?

**Comment by shuuji3** [comment]
It seems that this update has already done on June 24 by this PR: igrigorik/ga-beacon/pull/69. So just fetching source code and redeploy it to App Engine is enough?

**Comment by sftim** [comment]
@celestehorgan do you have any context about that beacon and its operation?

**Comment by kbhawkey** [comment]
> 
> 
> It seems that this update has already done on June 24 by this PR: [igrigorik/ga-beacon/pull/69](https://github.com/igrigorik/ga-beacon/pull/69). So just fetching source code and redeploy it to App Engine is enough?

Great! @zacharysarah @jimangel @kbarnard10 do you have insight into updating the docs code to GAE?

**Comment by celestehorgan** [comment]
@sftim no I don't, unfortunately. Judging by its position (not in the footer but specifically in `.issue-button-container`) I wonder if this is specifically tracking click-through's to GitHub? 

I don't have access to the Analytics so I can't say more.

**Comment by jimangel** [comment]
I went deep down this rabbit hole... It looks like something that was implemented around [2015](https://github.com/kubernetes/kubernetes/pull/6826) as a way to track analytics of GitHub markdown files (the literal files when viewed on GitHub). You can read more about ga-beacon in the [repo](https://github.com/igrigorik/ga-beacon) linked above. Also, looking at the file's git history and following it back to the earliest file, it came over as part of the Jekyll migration.

From everything I can find, this was somewhat an early attempt at gaining analytics that are not commonly known on GitHub.

Given that we still implement the Google Analytics JS over the entire site and the fact that this GAE app is broken (and not intended to improve the website). I think it's safe to remove.

I would prefer the entire section gets deleted vs. commented out.

/cc @zacharysarah

**Comment by celestehorgan** [comment]
+1 to removing this completely. Thanks for the research, @jimangel!

**Comment by kbhawkey** [comment]
That's fine. I will update.

**Pull request merged**
