### PR TITLE
Fix shell misquote.

### PR DESCRIPTION
**Pull request by fossilet**
Fix shell misquote.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
/lgtm
@fossilet Please sign the CLA!
( https://github.com/kubernetes/website/pull/30543#issuecomment-972486999 )

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by sftim** [comment]
We're switching CLA systems @fossilet - https://github.com/kubernetes/website/pull/30543#issuecomment-972486999 is the one that matters I'm afraid.

**Comment by kbhawkey** [comment]
Thanks @fossilet .
/approve

**Pull request merged**
