### PR TITLE
zh-trans：add 2018-12-05-new-contributor-shanghai.md 

### PR DESCRIPTION
**Pull request by ZhangJanes**
zh-trans：add 2018-12-05-new-contributor-shanghai.md

### CODE REVIEW

**Comment by DanyC97** [comment]
@ZhangJanes was this PR meant to cover only `zh` lang? if so would you mind removing the other languages like `en` ?

**Comment by markthink** [comment]
@ZhangJanes 有大量的变更，需要重新提交

**Comment by chenrui333** [comment]
这个 PR submit 有问题吧？
base branch 有问题？

**Comment by xichengliudui** [comment]
@ZhangJanes  This file has been merged.

**Pull request closed without merging**
