### PR TITLE
Fix the kubectl subcommands links.

### PR DESCRIPTION
**Pull request by warmchang**
Fix the kubectl subcommands links.

Issue: https://github.com/kubernetes/website/issues/10080

### CODE REVIEW

**Comment by warmchang** [comment]
cc @zhangxiaoyu-zidif @xiangpengzhao

**Comment by stewart-yu** [comment]
IMO, this is auto-generated file
/cc @zacharysarah @steveperry-53

**Comment by tengqm** [comment]
@warmchang This PR looks good to me because the current reference doc for kubectl is a mix of materials from different sources. Please disassociate this PR from the issue #10520 because this PR is not fixing that issue.

**Comment by CaoShuFeng** [comment]
FYI: https://github.com/kubernetes/website/issues/10080

**Comment by warmchang** [comment]
@tengqm thank your for reminding, I'll fix the https://github.com/kubernetes/website/issues/10520

**Pull request merged**
