### PR TITLE
Fix issues in content

### PR DESCRIPTION
**Pull request by mooncak**
Signed-off-by: mooncake <xcoder@tenxcloud.com>

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.13 Features: set Milestone to 1.13 and Base Branch to dev-1.13
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
Fix typos issues in content directory:

1. content/en/docs/concepts/policy/pod-security-policy.md
2. content/en/docs/tasks/extend-kubectl/kubectl-plugins.md
3. content/en/docs/tasks/run-application/horizontal-pod-autoscale.md
4. content/zh/docs/concepts/architecture/master-node-communication.md

### CODE REVIEW

**Comment by Bradamant3** [comment]
@mooncak can you please split this into two PRs, one for English and one for Chinese? We have different sets of reviewers and approvers for each. Thanks!

**Comment by mooncak** [comment]
> @mooncak can you please split this into two PRs, one for English and one for Chinese? We have different sets of reviewers and approvers for each. Thanks!

ok, this one English, #10947 for Chinese

**Comment by mooncak** [comment]
/language/zh  cancel

**Pull request merged**
