### PR TITLE
Translate concepts/configuration/assign-pod-node/ in Japanese

### LINKED ISSUE #15552: Translate concepts/configuration/assign-pod-node/ in Japanese
# Translate concepts/configuration/assign-pod-node/ in Japanese

**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No concepts/configuration/assign-pod-node/ in Japanese.

**Proposed Solution:**
Translate concepts/configuration/assign-pod-node/ in Japanese.
Copy from en content and Update `{{ content/ja/docs/concepts/configuration/assign-pod-node.md }}`.

**Page to Update:**
{{ https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ }}

### PR DESCRIPTION
**Pull request by SatoruItaya**
Close #15552

### CODE REVIEW

**Comment by SatoruItaya** [comment]
I signed it

**Comment by nasa9084** [comment]
過去の変更点がむやみに入ってしまっているので、
kubernetes:dev-1.15-ja.1にrebaseしてもらえますか？

**Comment by jimangel** [comment]
Hey there! @SatoruItaya, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by SatoruItaya** [comment]
regenerated

**Pull request closed without merging**
