### PR TITLE
changing image to nginx because game.example/demo-game does not exist

### PR DESCRIPTION
**Pull request by ldynia**
docker pull game.example/demo-game results with Error response from daemon: Get https://game.example/v2/: dial tcp: lookup game.example: no such host.
Therefore is better to change image to nginx

### CODE REVIEW

**Comment by tengqm** [comment]
This example didn't meant to use a real image. If we decide to use nginx, maybe we want to change the ConfigMap contents to something meaningful.

**Comment by ldynia** [comment]
You are right. I edited the commit, I changed image from nginx to alpine. This way this example have a generic context.

**Pull request merged**
