### PR TITLE
updated examples appearance in k8s api concept

### PR DESCRIPTION
**Pull request by AmarNathChary**
Updated appearance of examples in k8s API concepts.
Now it comes with user-friendly colors for better comprehension.

### CODE REVIEW

**Comment by AmarNathChary** [comment]
This PR fixes #43449

**Comment by AmarNathChary** [comment]
Now it comes with user-friendly colors for better comprehension.

**Comment by tengqm** [comment]
No. The enclosed text are not JSON or YAML.
They are just console text outputs.
I don't think this PR should be merged.

**Comment by AmarNathChary** [comment]
> No. The enclosed text are not JSON or YAML. They are just console text outputs. I don't think this PR should be merged.

Hi @tengqm I thought coloring would give a more user-friendly comprehension.
If coloring may not be a proper thing to fix. can we make the text dark black in color as it can be more user-friendly than before
WDYT?

**Comment by tengqm** [comment]
> > No. The enclosed text are not JSON or YAML. They are just console text outputs. I don't think this PR should be merged.
> 
> Hi @tengqm I thought coloring would give a more user-friendly comprehension. If coloring may not be a proper thing to fix. can we make the text dark black in color as it can be more user-friendly than before WDYT?

Yup. If there are stylesheet defects to fix, please do propose one.

**Comment by AmarNathChary** [comment]
> > > No. The enclosed text are not JSON or YAML. They are just console text outputs. I don't think this PR should be merged.
> > 
> > 
> > Hi @tengqm I thought coloring would give a more user-friendly comprehension. If coloring may not be a proper thing to fix. can we make the text dark black in color as it can be more user-friendly than before WDYT?
> 
> Yup. If there are stylesheet defects to fix, please do propose one.

Just like image 2 provided in issue #43449 the console could be dark in color.

**Comment by AmarNathChary** [comment]
Removed the previous changes of coloring as they are examples of console outputs.

**Comment by AmarNathChary** [comment]
I have made some changes, Made the examples of the console output appearance dark to have a clear view.
and changed the appearance coloring of one example of JSON as it was colored according to the yaml.

**Comment by AmarNathChary** [comment]
@tengqm Can u PTAL..!

**Comment by tengqm** [comment]
@AmarNathChary From the following screenshot, you can see how a invalid JSON confused the parser.

image

**Comment by tengqm** [comment]
Please squash your PR into a single commit?
/approve

**Comment by AmarNathChary** [comment]
> Please squash your PR into a single commit? /approve

squashed into single commit PTAL!

**Comment by tengqm** [comment]
/lgtm
Thanks.

**Pull request merged**
