### PR TITLE
Update service.md

### PR DESCRIPTION
**Pull request by jamarior**
Fix spacing in load balancer rules table

### CODE REVIEW

**Comment by sftim** [comment]
Hi @jamarior 

If you can sign the CLA - see https://github.com/kubernetes/website/pull/27435#issuecomment-814332137 - then we'll be happy to review this proposed fix.

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by jimangel** [comment]
Hey there! @jamarior, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
I'm closing this due to CLA issue open for too long. Please feel free to reopen when the agreement is signed.
/close

**Pull request closed without merging**
