### PR TITLE
Translate contribute/suggesting-improvements.md into Korean

### LINKED ISSUE #20997: Translate contribute/suggesting-improvements.md into Korean
**This is a Feature Request**

**What would you like to be added**

Translate contribute/suggesting-improvements.md into Korean.

**Why is this needed**

There is no document of contribute/suggest-improvements/ which translated into Korean.

**Comments**

Page to translate: https://kubernetes.io/docs/contribute/suggest-improvements/

/language ko

### PR DESCRIPTION
**Pull request by pjhwa**
Closes #20997 .

### CODE REVIEW

**Comment by pjhwa** [comment]
Deploy preview: https://deploy-preview-21001--k8s-dev-ko.netlify.app/ko/docs/contribute/suggest-improvements/

**Comment by ysyukr** [comment]
@seokho-son 님께서 리뷰가 어려우신듯하여 제가 대신하겠습니다.
/unassign @seokho-son
/assign @ysyukr 

/lgtm

**Pull request merged**
