### PR TITLE
fix words spelling issue 群集 -> 集群

### PR DESCRIPTION
**Pull request by TerryWang9112**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by SataQiu** [comment]
Thanks, Please sign CLA first. @TerryWang9112

**Comment by markthink** [comment]
@TerryWang9112  参考[翻译指引](https://github.com/k8smeetup/k8s-official-translation)

**Comment by chenrui333** [comment]
/close

Due to CLA missing and lack of communications on this PR.

**Pull request closed without merging**
