### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ystkfujii**

### CODE REVIEW

**Comment by AmarNathChary** [comment]
It's a small fix there could be more on the page. It is likely there are more in that file, you can make your Pull Request count by checking the formatting, checking for broken links, fixing errors, and then submitting all the fixes at once to that file.

**Comment by AmarNathChary** [comment]
though
/lgtm

**Comment by stmcginnis** [comment]
/lgtm

This is a pretty minor edit. If there are any other typos or improvements you can find in this file, that would be great to include that in this PR.

**Comment by ystkfujii** [comment]
I have found a broken link which I have corrected.
No other corrections were found.

**Comment by stmcginnis** [comment]
Preview looks good: https://deploy-preview-45514--kubernetes-io-main-staging.netlify.app/blog/2024/03/12/kubernetes-1-30-upcoming-changes/

Thanks!

/lgtm

**Comment by reylejano** [comment]
Partial duplicate of PR https://github.com/kubernetes/website/pull/45517

**Comment by reylejano** [comment]
Although this is a partial duplicate of a merged PR https://github.com/kubernetes/website/pull/45517, this offers an additional fix 
/approve

**Pull request merged**
