### PR TITLE
For word 'dari' to 'daripada' in Indonesian

### PR DESCRIPTION
**Pull request by hartomo1**
Fixing word in Kubernetes workshop for learning purpose

/language id
/cc hartomo1

### CODE REVIEW

**Comment by girikuncoro** [comment]
Thank you for being first time contributor, congrats and welcome to Kubernetes! 🎉 

/lgtm
/approve

**Comment by irvifa** [comment]
@hartomo1 Please sign the CLA first https://identity.linuxfoundation.org/projects/cncf

**Comment by tfogo** [comment]
Hi @hartomo1, thanks for the PR! Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA so that we can review this PR, thanks!

**Comment by irvifa** [comment]
@hartomo1 hello any update on this one? 👋

**Comment by hartomo1** [comment]
Halo, ditutup saja.
Thanks.

**Pull request merged**
