### PR TITLE
Fix High availability Kubernetes diagram image link error

### PR DESCRIPTION
**Pull request by chenyb4**
Signed-off-by: Yuanbin.Chen <cybing4@gmail.com>

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.11 Features: set Milestone to 1.11 and Base Branch to release-1.11
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by fabian4** [comment]
Wait for approve

**Comment by chenyb4** [comment]
@zacharysarah 
Thanks,  Change done!

**Comment by chenyb4** [comment]
@tengqm
Change done!

**Comment by Bradamant3** [comment]
@chenyb4 the image still does not appear in the Netlify preview. Reviewers (and contributors), please check the Netlify preview before your reviews. Just looking at the markdown changes is not sufficient. I'm not sure what the problem is -- the path looks correct. Try the .png file instead? If we can't get a reliable fix in, we'll have to think about removing until we can solve the problem.

/lgtm cancel

**Comment by neolit123** [comment]
@Bradamant3 could be a Netlify issue?
the image can be seen using the Github Markdown:
https://github.com/chenyb4/website/blob/a174325b23b1c9672d24e774d7db41d5def8c110/content/en/docs/admin/high-availability/building.md

**Comment by chenyb4** [comment]
@Bradamant3 
Markdown see right.

https://github.com/chenyb4/website/blob/a174325b23b1c9672d24e774d7db41d5def8c110/content/en/docs/admin/high-availability/building.md

**Comment by Bradamant3** [comment]
Direct link to Netlify preview page: https://deploy-preview-8795--kubernetes-io-master-staging.netlify.com/docs/admin/high-availability/building/

**Comment by chenyb4** [comment]
It looks my change error.
The k8s doc web display right.
https://kubernetes.io/docs/admin/high-availability/building/

This PR will close.

**Pull request closed without merging**
