### PR TITLE
Fix issue with tasks/administer-cluster/out-of-resource/

### LINKED ISSUE #24296: Issue with tasks/administer-cluster/out-of-resource/
**This is a Bug Report**

**Problem:**
There is a broken link to script in tasks/administer-cluster/out-of-resource.md file.
At 44 line:
```
root node. This [script](/docs/tasks/administer-cluster/memory-available.sh)
```

**Proposed Solution:**
Move the script file to examples directory.

```
root node. This [script](/examples/admin/resource/memory-available.sh)
```

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

/language en

### PR DESCRIPTION
**Pull request by pjhwa**
Closes #24296

**Problem:**
There is a broken link to script in tasks/administer-cluster/out-of-resource.md file. So, the script downloading is failing.
At 44 line:
```
root node. This [script](/docs/tasks/administer-cluster/memory-available.sh)
```

**Proposed Solution:**
Move the script file to examples directory.

```
root node. This [script](/examples/admin/resource/memory-available.sh)
```

### CODE REVIEW

**Comment by pjhwa** [comment]
Preview page: https://deploy-preview-24297--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/out-of-resource/#eviction-signals

**Comment by celestehorgan** [comment]
From a pure organization perspective, I'm going to give this a LGTM.

@sftim – the change is purely moving a file location. I don't know if we need sig-node?

/lgtm

**Pull request merged**
