### PR TITLE
fix typo in romana-network-policy.md

### PR DESCRIPTION
**Pull request by mysunshine92**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by poothia** [comment]
lgtm

**Comment by DanyC97** [comment]
/lgtm

@@zhangxiaoyu-zidif please help review and approve

**Comment by sftim** [comment]
This PR touches two languages. It would be more typical to change just the English localization and then let localization teams pick up the updates.

**Comment by mysunshine92** [comment]
> 
> 
> This PR touches two languages. It would be more typical to change just the English localization and then let localization teams pick up the updates.

@sftim thanks for your suggestion, i have modified it.

**Comment by Rajakavitha1** [comment]
Thanks for your PR @mysunshine92 !!!

/approve

**Pull request merged**
