### PR TITLE
Rename zones on dns-pod-service page

### PR DESCRIPTION
**Pull request by rmarcum**
Fixes Issue with k8s.io/docs/concepts/services-networking/dns-pod-service/ - cluster.local 
#14386

### CODE REVIEW

**Comment by sftim** [comment]
Hi @rmarcum and congratulations on your first docs pull request.

I think you'll need to correct [`/content/en/examples/service/networking/custom-dns.yaml`](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/service/networking/custom-dns.yaml) as well.

**Comment by sftim** [comment]
Some [parts](https://github.com/kubernetes/website/pull/14672/files#diff-e40fbb48de49222482b6631b1ebfa50cR237) of this page are still referring to `cluster.local.`
(also eg on [line 246](https://github.com/kubernetes/website/pull/14672/files#diff-e40fbb48de49222482b6631b1ebfa50cR246)).

Once those are all updated I think this would be good to merge.

**Comment by tddorgtfo** [comment]
fixed #14386

**Pull request merged**
