### PR TITLE
Change formatting of example-ingress.yaml

### PR DESCRIPTION
**Pull request by drejmar**
https://github.com/kubernetes/website/issues/16544

### CODE REVIEW

**Comment by drejmar** [comment]
https://github.com/kubernetes/website/issues/16544

**Comment by drejmar** [comment]
I signed it

**Comment by sftim** [comment]
@drejmar If you've signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Could that be what's happened?

**Comment by tengqm** [comment]
CLA okay now.
/lgtm
/approve

**Pull request merged**
