### PR TITLE
Modify apparmor.md based on PR - Fix site build (#16531) 

### PR DESCRIPTION
**Pull request by aimeeu**
Embed contents of deny-write.profile into apparmor.md and delete deny-write.profile to enable the site to build with Hugo 0.57.2. Could not cherry pick PR 16531 because the Korean translation was added in 1.14.  See PRs #16104 and #16151. 

PRs in this "cherry pick" group: #16645, #16646, #16647, #16648, #16650

zh/docs/reference/setup-tools/kubeadm/generated/README.md updated to fix 'invalid YAML delimiter' compile error caused by HTML comment.

Preview page: https://deploy-preview-16650--k8s-v1-12.netlify.com/docs/tutorials/clusters/apparmor/#example

### CODE REVIEW

**Comment by zacharysarah** [comment]
@aimeeu Why does this PR delete a Chinese README?

**Comment by aimeeu** [comment]
@zacharysarah it does not delete the README.md file. It removes the HTML comment at the top of the file, which was causing causing an 'invalid YAML delimiter' compile error. Note that the README.md in question does not exist in [1.13](https://github.com/kubernetes/website/tree/release-1.13/content/zh/docs/reference/setup-tools/kubeadm/generated)

**Comment by zacharysarah** [comment]
@aimeeu Ah, i see now. Thanks!

/lgtm
/approve

**Pull request merged**
