### PR TITLE
No page content for /kubectl-cmds/

### PR DESCRIPTION
**Pull request by jlsong01**
This PR is to address issue: https://github.com/kubernetes/website/issues/24133

### CODE REVIEW

**Comment by sftim** [comment]
https://deploy-preview-25157--kubernetes-io-master-staging.netlify.app/docs/reference/kubectl/kubectl-cmds/ _isn't_ redirecting. I don't see, right now, why that is.

/hold
(pending investigation)

**Comment by kbhawkey** [comment]
The command reference is connected by a link to static pages. Not sure if this is the problem.
Instead, what do you think about:
- removing the `kubectl-cmds.md` file
- add the link from `kubectl-cmds.md` to "docs/reference/kubectl/_index.md" page as follows:

```
---
title: "kubectl CLI"
weight: 60
content_type: concept
#no_list: true
---

<!-- kubectl command reference -->
### [kubectl Command Reference](/docs/reference/generated/kubectl/kubectl-commands/)
```

**Comment by kbhawkey** [comment]
Hi @jlsong01 .
Checking if you need help to move this PR forward?

**Comment by sftim** [comment]
@jlsong01 I'd like to rebase this PR against the `master` branch and try a couple of things out.
(If you're not sure what that means, it's OK. I'm a tech lead for Kubernetes SIG Docs and I'm happy to assure you that a rebase won't be harmful here).

Would it be OK to make that change to see if it helps?

**Pull request closed without merging**
