### PR TITLE
WIP Blog Integration

### PR DESCRIPTION
**Pull request by tehut**
Added:
Updated config.yaml to include paginate gem
160 + blog posts from blog.kubernetes.io
Updated link on header file to point to jekyll blog instead of Blogger
Set column width on footer to 12

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7144)

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
cc @kubernetes/sig-docs-maintainers

**Comment by zacharysarah** [comment]
@tehut 👋 It looks like the build failed for reasons unrelated to the PR. Let's run Travis again and see what happens.

/retest

**Comment by zacharysarah** [comment]
@tehut It also looks like there's a merge conflict to resolve.

**Comment by zacharysarah** [comment]
Closing in favor of #7247

**Pull request closed without merging**
