### PR TITLE
[ko] Update install-kubectl-windows.md

### PR DESCRIPTION
**Pull request by caputdraconis050630**
[Korean Docs Localization]
Correcting a typo caused by a Git conflict

### CODE REVIEW

**Review by jongwooo — COMMENTED** [review]
@caputdraconis050630 오류를 잘 찾아주셨네요! 감사합니다:)

**Comment by sftim** [comment]
Given https://github.com/kubernetes/website/pull/42173#issuecomment-1648135025

/lgtm

**Comment by seokho-son** [comment]
Hello @caputdraconis050630,

Thank you so much for your valuable contribution!
We currently have two PRs that resolve the same bug, but are targeted towards different branches.

#41994 (targeting main)
#42173 (targeting Ko dev branch)

The Ko dev branch would be the ideal target for Korean localization PRs. However, considering that this bug fix needs to be quickly applied to our live website, the main branch becomes an appropriate target in this instance.

On this occasion, I see it fit to approve both PRs.

/approve

**Pull request merged**
