### PR TITLE
Fix wrong "kubectl expose deployment" command

### PR DESCRIPTION
**Pull request by radeksm**
The same error in all all conetnts' translations.

Essentially that's the entire change:

`-kubectl expose deployment/my-nginx`
`+kubectl expose deployment my-nginx`

### CODE REVIEW

**Comment by sftim** [comment]
@radeksm could you revise this to just change the English localization? That means we don't need every localization team for the touched pages to approve this PR.

**Comment by sftim** [comment]
@radeksm I have a question though

What's wrong with `kubectl expose deployment/my-nginx`? It works.

**Comment by radeksm** [comment]
> @radeksm I have a question though
> 
> What's wrong with `kubectl expose deployment/my-nginx`? It works.

Both commands works but the one with the slash `kubectl expose deployment/my-nginx` is a little bit confusing.
In general looks like most of the commands can have two forms:
`kubectl describe service my-nginx`
`kubectl describe service/my-nginx`
but the second format seems to be not documented. And for newbies (like I am) it's kind of confusing :)

**Comment by jimangel** [comment]
@radeksm will you update this PR to only fix the English document? Each localization team has their own branching / merging strategy that could be impacted by merging all docs into master.

/hold

**Comment by radeksm** [comment]
> @radeksm will you update this PR to only fix the English document? Each localization team has their own branching / merging strategy that could be impacted by merging all docs into master.
> 
> /hold

@sftim, @jimangel done, reverted from all translations except English.

**Pull request closed without merging**
