### PR TITLE
fix typo in quick-reference.md

### PR DESCRIPTION
**Pull request by HesamKorki**
It fixes a small typo on the Kubectl cheat sheet page.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Appreciate the minor fix here, and it looks good to me.

In the future, it would be great if you could strive to follow the [Trivial Edits guidelines](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) whenever feasible. In addition to the small modification, it would be more beneficial to improve the same page by addressing any other grammatical errors or fixing broken links. Thank you for your valuable contribution.

/lgtm

Deploy Preview: https://deploy-preview-47570--kubernetes-io-main-staging.netlify.app/docs/reference/kubectl/quick-reference

**Comment by HesamKorki** [comment]
> Appreciate the minor fix here, and it looks good to me.
> 
> In the future, it would be great if you could strive to follow the [Trivial Edits guidelines](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) whenever feasible. In addition to the small modification, it would be more beneficial to improve the same page by addressing any other grammatical errors or fixing broken links. Thank you for your valuable contribution.
> 
> /lgtm
> 
> Deploy Preview: https://deploy-preview-47570--kubernetes-io-main-staging.netlify.app/docs/reference/kubectl/quick-reference

Thanks for the info. It makes absolute sense, I try to keep that in mind for future contributions.

**Review by sftim — COMMENTED** [review]
Thanks for this PR, and welcome to SIG Docs.

/approve

**Pull request merged**
