### PR TITLE
Update tutorial/server.js due to outdated source. #8855

### PR DESCRIPTION
**Pull request by ClaudiaJKang**
Fix to #8855. 

**Problem:**  
**In repository [tutorials/server.js](https://github.com/kubernetes/website/blob/master/content/en/docs/tutorials/server.js) is seems to be outdated.** 
This is the latest source : [gcr.io/google-samples/kubernetes-bootcamp:v1 image](https://gcr.io/google-samples/kubernetes-bootcamp:v1)'s server.js.

**Proposed Solution:**  
**[tutorials/server.js](https://github.com/kubernetes/website/blob/master/content/en/docs/tutorials/server.js)  should be updated to the [latest source(gcr.io/google-samples/kubernetes-bootcamp:v1)](https://gcr.io/google-samples/kubernetes-bootcamp:v1)'s server.js.**

### CODE REVIEW

**Comment by mistyhacks** [comment]
/unassign

/assign @zacharysarah 

(Hopefully Zach knows who should review this -- not sure why the system nominated me)

**Comment by zacharysarah** [comment]
@ClaudiaJKang Thanks for opening this PR. The tutorials are maintained by Katacoda, so I've flagged them here to review it.

**Comment by ClaudiaJKang** [comment]
@mistyhacks @zacharysarah Thank you for reviewing this PR!

**Comment by ClaudiaJKang** [comment]
@BenHall , I'm still waiting for your review and guide.

**Comment by BenHall** [comment]
The https://github.com/kubernetes/website/blob/master/content/en/docs/tutorials/server.js is referenced by https://kubernetes.io/docs/tutorials/hello-minikube/ and not the interactive tutorials as I previously thought.


The code for the kubernetes-bootcamp image does need to be updated. It's handled by https://github.com/kubernetes/kubernetes-bootcamp/pull/71 however I don't have permissions to merge.

**Comment by ClaudiaJKang** [comment]
@BenHall Thank you for reviewing this PR. I think so. It seems to not be a managed repository. 
Could you know another method to update this code?

**Comment by BenHall** [comment]
The code/PR could be committed to the Website repo if you know a good location for it.

**Comment by zacharysarah** [comment]
@BenHall It sounds like this PR may belong to a different repo. I'll go ahead and close it; please feel free to reopen if it becomes relevant to k/website in the future.

**Pull request closed without merging**
