### PR TITLE
fix readme markdown

### PR DESCRIPTION
**Pull request by Arhell**
fix readme markdown
#19577
/language vi

### CODE REVIEW

**Comment by onlydole** [comment]
Thank you for your contribution, @Arhell!

/lgtm 

/assign @daminisatya 
/assign @zparnold

**Comment by kbhawkey** [comment]
LGTM
Ping @kubernetes/sig-docs-vi-owners

**Comment by truongnh1992** [comment]
/lgtm
/approve
Thank for your great work.

**Pull request merged**
