### PR TITLE
ja: replace "Kubenretes" with "Kubernetes"

### PR DESCRIPTION
**Pull request by fujipi270**
Fixed "kube**nr**etes" to kube**rn**etes

### CODE REVIEW

**Comment by cstoku** [comment]
@fujipi270 Could you please sign CLA and change base branch to `dev-1.15-ja.1` ?

**Comment by inductor** [comment]
Please fix the conflicts and unnecessary commits

**Comment by cstoku** [comment]
Please start from `dev-1.15-ja.1` and cherry-pick this PR.
Sorry to bother you again.

**Comment by fujipi270** [comment]
Sorry for the late response. 
I am in an environment where I cannot work now. So we will resume working after 5 hours

**Comment by fujipi270** [comment]
Sorry for the late response.
I am in an environment where I cannot work now. So I will resume working after 5 hours

**Pull request closed without merging**
