### PR TITLE
Update advice on pinning output version of 'kubectl get'

### PR DESCRIPTION
**Pull request by bboreham**
`--output-version` is deprecated.
Advice paraphrased from https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get

### CODE REVIEW

**Comment by bboreham** [comment]
I disagree that is more readable.

How about:
> Fully-qualify the version.  For example, `jobs.v1.batch/myjob`.  If you don't do this, kubectl will use a version of its choosing, which may change over time.

I don't think the digression into `-o name` is valuable here.

**Comment by Rajakavitha1** [comment]
@bboreham  Yes, I agree that digressing to -o name does not add any value.
How about?
To ensure that kubectl does not use a random version of an API that changes over time. Fully-qualify the version. For example, jobs.v1.batch/mayjob.

**Comment by chenopis** [comment]
@bboreham @Rajakavitha1 Have you settled on the wording?

**Comment by mistyhacks** [comment]
Any updates on addressing the feedback?

**Comment by bboreham** [comment]
Sorry, I forgot about this PR.  I'll update it tomorrow.

**Comment by bboreham** [comment]
OK, I took another look and updated the wording.  Let me know what you think.

**Pull request merged**
