### PR TITLE
Fix some more spelling issues

### PR DESCRIPTION
**Pull request by madhuri-rai07**
This patch fixes some more spelling mistakes in our docs

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6771)

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
The Travis CI build failed but seems like not due to the change.

/retest

**Comment by xiangpengzhao** [comment]
@madhuri-rai07 can you squash the commits?

**Comment by madhuri-rai07** [comment]
@xiangpengzhao Done. Thanks!

**Comment by tengqm** [comment]
According to the CI log, you still need a rebase upon master.

**Comment by zhangxiaoyu-zidif** [comment]
@madhuri-rai07 
please squash commits and rebase.

**Pull request merged**
