### PR TITLE
localization for subscribe button

### PR DESCRIPTION
**Pull request by Arhell**
issue #20950
en [PR ](https://github.com/kubernetes/website/pull/20878)

/language uk

### CODE REVIEW

**Comment by Arhell** [comment]
Review page
https://deploy-preview-20951--kubernetes-io-master-staging.netlify.app/uk/#kubeweekly

**Comment by MaxymVlasov** [comment]
/assign sftim
Hi @sftim !
Please, approve this PR

**Comment by sftim** [comment]
@MaxymVlasov you can add “/approve” if you're happy to approve this change.

**Comment by sftim** [comment]
SIG Docs tech leads and chairs are happy to echo approvals where needed to keep Prow happy.
/approve

**Pull request merged**
