### PR TITLE
Add a missing '-' to names.md

### PR DESCRIPTION
**Pull request by yanwei2019**
Add a missing '-' to names.md

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by yanwei2019** [comment]
ok

**Comment by xichengliudui** [comment]
@yanwei2019 you need to sign the `CNCF agreement`.

**Comment by markthink** [comment]
@yanwei2019 参考[翻译指引](https://github.com/k8smeetup/k8s-official-translation)

**Comment by yanwei2019** [comment]
ok

**Comment by yanwei2019** [comment]
I have already signed the CLA

**Comment by yanwei2019** [comment]
hi

**Comment by RA489** [comment]
@yanwei2019 do you have any issue while signing the CLA.

**Comment by yanwei2019** [comment]
> @yanwei2019 do you have any issue while signing the CLA.

I have already signed the CLA.Thanks.

**Comment by RA489** [comment]
> > @yanwei2019 do you have any issue while signing the CLA.
> 
> I have already signed the CLA.Thanks.

/check-cla

**Comment by yanwei2019** [comment]
how can I to make this PR to be continued?

**Comment by yanwei2019** [comment]
I signed it

**Comment by yanwei2019** [comment]
check-cla

**Pull request merged**
