### PR TITLE
[ko] Minor Fix in Korean docs fixed : Fix 02

### PR DESCRIPTION
**Pull request by NitishKumar06**
Fix: #34909

The 2nd suggestion has been applied.

### CODE REVIEW

**Comment by Sea-n** [comment]
Is it intended to touch 6 languages in one PR?

Feel free to `/unhold` once the git issue is solved.
/hold

**Comment by NitishKumar06** [comment]
How do I push only single committ of mine to dev -1.24 branch then?

**Comment by sftim** [comment]
@NitishKumar06 for help with using Git, you could ask in the #sig-docs channel on Slack, or to https://softwareengineering.stackexchange.com/

**Comment by seokho-son** [comment]
Hi @NitishKumar06 

Please take a look on my previous comment regarding the base branch.
https://github.com/kubernetes/website/pull/34932#issuecomment-1184814596

And please use (retitle) understandable title for a PR :)
You can change the title by using `/retitle [ko]xxxxx` command. (`[language code]` is a convention for a localization PR)

**Comment by NitishKumar06** [comment]
@seokho-son I think that's what I've done:


First of all, I made changes to a new branch I just created. Ater that, I pushed the changes and in the Github UI , I changed the base branch to dev-1.24 instead of main. Anything wrong in it?

**Comment by NitishKumar06** [comment]
/retitle Minor Fix in Korean docs fixed : Fix 02

**Comment by seokho-son** [comment]
/retitle [ko] Minor Fix in Korean docs fixed : Fix 02

**Comment by seokho-son** [comment]
> First of all, I made changes to a new branch I just created. Ater that, I pushed the changes and in the Github UI , I changed the base branch to dev-1.24 instead of main. Anything wrong in it?

In order to work in a different branch other than main branch (like this PR), 

When you create your new (local) development branch, the base of the new branch should be `dev-1.24-ko.2`.
It seems .. current base of your development branch `NitishKumar06:Nitish/Korean` is `main` branch which is a wrong base branch for this PR.

(following commands are just example to checkout to a different branch other than main branch)
- git fetch upstream
- git checkout upstream/dev-1.24-ko.2
- git checkout -b yourlocaldev

(If this comment is hard to understand for you, I also recommend you to check Git related contents suggested by above comments.)

**Comment by NitishKumar06** [comment]
@seokho-son Correct me if I'm wrong:

First of all I'll have to checkout the _dev-1.24_ branch using _git checkout dev-1.24_ and from that branch I'll have to create a new branch whichever I want. After committing the changes, I'll have to push the changes using the command _git push origin <branch name i created>_ . Once done I'll have to change the base branch in the Github UI to dev-1.24, right?

**Comment by NitishKumar06** [comment]
I'm closing this PR since the following PR resolves this issue:https://github.com/kubernetes/website/pull/35248

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de en es fr id it ja pt vi zh
/remove-sig release

**Pull request closed without merging**
