### PR TITLE
Fix links for k/design-proposals-archive

### LINKED ISSUE #33893: Broken link to “Inter-pod topological affinity and anti-affinity” design doc
This is regarding this section in this page: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity

`See the [design doc](https://git.k8s.io/community/contributors/design-proposals/scheduling/podaffinity.md) for many more examples of Pod affinity and anti-affinity.`

The link to https://git.k8s.io/community/contributors/design-proposals/scheduling/podaffinity.md is dead.

### LINKED ISSUE #34165: Links to design-proposals are broken
[Kubernetes Protobuf serialization](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf.md) link is broken

### LINKED ISSUE #34182: Update broken link on Cluster Networking page.
**Problem:**
The link https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network/networking.md is dead.
see the text '[networking design document](https://git.k8s.io/community/contributors/design-proposals/network/networking.md).' on the [Link](https://kubernetes.io/docs/concepts/cluster-administration/networking/) to know more about the issue.

**Proposed Solution:**
This issue has been resolved by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/networking/
Update the link https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network/networking.md to https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/cluster-administration/networking.md

/kind document
/assign
/help
/language en

### LINKED ISSUE #34203: The link 'Kubernetes Protobuf serialization' is broken
Link [Kubernetes Protobuf serialization](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf.md) from this page (https://kubernetes.io/docs/concepts/overview/kubernetes-api/) returns 404

### PR DESCRIPTION
**Pull request by Sea-n**
The old links are totally unavailable now.
- https://github.com/kubernetes/community/pull/6591

This PR intentionally leave one file unchanged since PR #34145 is already working on it.

As @jihoon-seo's [suggestion](https://github.com/kubernetes/website/pull/34155#issuecomment-1152431386), this PR also changes all https://github.com/kubernetes/repo/blob/master/file.md to https://git.k8s.io/repo/file.md for better consistency.

Fixes #33893
Fixes #34165
Fixes #34182
Fixes #34203

### CODE REVIEW

**Comment by jihoon-seo** [comment]
This PR closes #34165.

**Comment by jihoon-seo** [comment]
I checked and confirm that all the links updated are working.
/lgtm

**Comment by jihoon-seo** [comment]
@Sea-n Like you said in https://github.com/kubernetes/website/pull/34145#discussion_r890845334,
I think that it would be great to use `https://git.k8s.io/` link for Kubernetes GitHub repos, for consistency and so on.

[L1024 in [`concepts/storage/persistent-volumes.md`](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/storage/persistent-volumes.md?plain=1)]
```diff
-* Read the [Persistent Storage design document](https://github.com/kubernetes/design-proposals-archive/blob/main/storage/persistent-storage.md).
+* Read the [Persistent Storage design document](https://git.k8s.io/design-proposals-archive/storage/persistent-storage.md).
```

@Sea-n What do you think about also include this change in this PR? 😊

**Comment by jihoon-seo** [comment]
@Sea-n Thank you for your hard work!
/lgtm

**Comment by Sea-n** [comment]
/cc @zacharysarah

It's been many issues and PRs opened against this one recently, could you help this move forward? Thanks. 🙇‍♂️

**Comment by zacharysarah** [comment]
@Sea-n Thanks for this. ✨ 

/approve

**Pull request merged**
