### PR TITLE
Translate Events Calendar

### PR DESCRIPTION
**Pull request by Ksmith30**
Events calendar was asked to be translated to Korean here (#18319). I used Google Translate to translate this so may not be the most accurate translate. Open to change if necessary. Thanks!
image

### CODE REVIEW

**Comment by sftim** [comment]
I don't speak Korean well enough to review this change. Happy to approve if necessary once a competent Korean speaker adds /lgtm.
/language ko
/uncc

**Comment by Ksmith30** [comment]
Thanks for the quick reply @sftim

**Comment by kbhawkey** [comment]
hello @Ksmith30 , I _think_ it is not acceptable to use machine translation for localizing the documentation.

**Comment by Ksmith30** [comment]
Ok @kbhawkey. Should I close this PR?

**Comment by gochist** [comment]
Thank you @Ksmith30 . As a native Korean speaker, LGTM.

/lgtm

**Comment by kbhawkey** [comment]
hello @Ksmith30 , I suppose it is best to let the Korean docs team decide. In the past, there was an issue with doc pages created from machine translations.

**Comment by sftim** [comment]
My opinion: reviewers should not accept machine translations, and large PRs based on machine translations are likely to be more effort than it's worth to review.

A small PR like this seems helpful, especially mentioning a caveat so that a reviewer can double check.

**Comment by sftim** [comment]
Also, thanks @gochist

**Pull request merged**
