### PR TITLE
Reference doc for kube-components (release-1.11)

### PR DESCRIPTION
**Pull request by tengqm**

### CODE REVIEW

**Comment by steveperry-53** [comment]
Hmm, I expected to see a preview here:
https://deploy-preview-9045--kubernetes-io-vnext-staging.netlify.com/

**Comment by steveperry-53** [comment]
Previews

* [cloud-controller-manager](https://deploy-preview-9045--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/cloud-controller-manager/)

* [kube-api-server](https://deploy-preview-9045--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/kube-apiserver/)

* [kube-controller-manager](https://deploy-preview-9045--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/kube-controller-manager/)

* [kube-proxy](https://deploy-preview-9045--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/kube-proxy/)

* [kube-scheduler](https://deploy-preview-9045--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/kube-scheduler/)

* [kubelet](https://deploy-preview-9045--kubernetes-io-vnext-staging.netlify.com/docs/reference/command-line-tools-reference/kubelet/)

* []()

**Comment by steveperry-53** [comment]
It would be nice to remove the short TOC that appears at the top of each ref page. But I would rather save that for later.

**Comment by steveperry-53** [comment]
Holding for approval by @mistyhacks.
/hold
/lgtm

**Comment by mistyhacks** [comment]
This could use some CSS love in a follow-up. Several of the table columns would be more readable in fixed width font, and it's not ideal to have CSS clauses sprinkled into the table HTML -- a separate CSS file would be ideal here. But this is good enough for now.

/approve
/hold cancel

**Pull request merged**
