### PR TITLE
Added Chinese README file and fixed changeless HTML lang tag

### PR DESCRIPTION
**Pull request by f0rb1d**
Added Chinese README file and a few lines about Chinese language in main README file just like Korean language does.

Also, this commit changes the HTML lang tag that would always be 'en' to other languages depending on the one the viewer chooses.

BTW, I accidentally updated some Chinese translations in master branch. But when I open this pull request, I found out it was already translated in 'release-1.12' so I reverted them. Should I open another pull request for master branch too? First time here, sorry for the inconvenience.

### CODE REVIEW

**Comment by tengqm** [comment]
@f0rb1d 1) pls sign the CLA for your PR to be mergeable; 2) pls keep each PR single purposed rather than mixing changes to different things in the same PR.

**Comment by zparnold** [comment]
Hey there! @f0rb1d, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by zparnold** [comment]
Hey there! @f0rb1d, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Bradamant3** [comment]
/close

@f0rb1d Thanks for your PR, but I'm closing it since you haven't addressed earlier comments. If you want to open a new PR, please address the comments first:
- sign the CLA
- I suggest you consult @hanjiayao about contributing to anything related to the Chinese translation

**Pull request closed without merging**
