### PR TITLE
Update to Hugo 0.53 and remove all .Site references

### PR DESCRIPTION
**Pull request by lucperkins**
Hugo version [0.53](https://gohugo.io/news/0.53-relnotes/) offers up a new global `site` variable that enables us to remove all of the awkward acrobatics of accessing site-level config in shortcodes and other contexts. Thus, no more `$.Page.Site` or `$p.ctx.Page.Site` and all other such shenanigans.

### CODE REVIEW

**Comment by tengqm** [comment]
@lucperkins You will need to update .travis.yml file as well.

**Comment by lucperkins** [comment]
@tengqm There's a PR open to streamline the versioning thing but for now I've made the change 👍

**Comment by kbarnard10** [comment]
@lucperkins Can you resolve the merge conflicts?

**Comment by lucperkins** [comment]
@kbarnard10 Done

**Pull request merged**
