### PR TITLE
[no] Update list of versions to match English

### PR DESCRIPTION
**Pull request by ricardoamaro**
Align https://kubernetes.io/es/docs/home/supported-doc-versions/ with https://kubernetes.io/docs/home/supported-doc-versions/

/language no

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Initially, the Norwegian language was included for testing purposes (As seen in this commit: [1b5ff98](https://github.com/kubernetes/website/commit/1b5ff98a4473be60d94d35e330d9801640d6f58d#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77)). However, it is currently inactive and disabled in [hugo.toml](https://github.com/kubernetes/website/blob/44669d56d7329c0a12eeaac31318f3025a91e51e/hugo.toml#L37), with no designated formal reviewers or approvers. Additionally, please note that localization leads are planning to remove this test language content soon. Given this information, it seems appropriate to proceed with closing this PR.

**Comment by ricardoamaro** [comment]
Sounds good!

**Review by dipesh-rawat — COMMENTED** [review]
Closing this PR _(Refer https://github.com/kubernetes/website/pull/46358#pullrequestreview-2053209429 https://github.com/kubernetes/website/pull/46358#issuecomment-2108640820)_

/close

**Pull request closed without merging**
