### PR TITLE
docs: CRD v1

### PR DESCRIPTION
**Pull request by sttts**
TODO:

- [x] CRDs v1 (kubernetes/enhancements#95)
- [x] CRD v1: require validation schemas
- [x] CRD v1: structural schema: require structural schema
- [ ] ~~CRD v1: prevent invalid type attributes in schema~~ bugfix
- [x] CRD v1: only allow default attributes in schema via v1
- [x] ConversionReview: promote types to v1
- [x] ConversionReview: allow dispatcher to speak v1
- [x] ConversionReview: in v1, verify response.uid, kind, apiVersion are set in responses
- [x] CRD subresources (kubernetes/enhancements#571)
- [x] CRD defaulting/pruning (kubernetes/enhancements#575)
- [x] CRD webhook conversion (kubernetes/enhancements#598)

### CODE REVIEW

**Comment by liggitt** [comment]
This will include docs for the following aspects:
- [ ] CRDs v1 (https://github.com/kubernetes/enhancements/issues/95)
- [ ] CRD subresources (https://github.com/kubernetes/enhancements/issues/571)
- [ ] CRD defaulting/pruning (https://github.com/kubernetes/enhancements/issues/575)
- [ ] CRD webhook conversion (https://github.com/kubernetes/enhancements/issues/598)

**Comment by VineethReddy02** [comment]
@sttts Is this PR ready or review? As today i.e 3rd Sept is the deadline for docs to be in ready for review state.

**Comment by liggitt** [comment]
remaining items added in https://github.com/sttts/website/pull/1

**Comment by liggitt** [comment]
preview links at:
* https://deploy-preview-15982--kubernetes-io-vnext-staging.netlify.com/docs/concepts/extend-kubernetes/api-extension/custom-resources/
* https://deploy-preview-15982--kubernetes-io-vnext-staging.netlify.com/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/
* https://deploy-preview-15982--kubernetes-io-vnext-staging.netlify.com/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

**Comment by liggitt** [comment]
@VineethReddy02 this is ready for review

**Comment by simplytunde** [comment]
@liggitt can I get a technical lgtm on this if its good to go?

**Pull request merged**
