### PR TITLE
[ja] Remove ^H character

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

The ^H character (ASCII code 08 Backspace) will break the format of the content in some environments, so drop it.

### CODE REVIEW

**Comment by s-kawamura-w664** [comment]
I know that control codes are displayed incorrectly.
This is good update.
/lgtm
@s-kawamura-w664

**Comment by inductor** [comment]
I think I have to address this to other old branches, please let me check before merging this

**Pull request merged**
