### PR TITLE
Fix typo in installing kubeadm

### PR DESCRIPTION
**Pull request by steve-hardman**
Removed the repetitive word 'to' in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

This will fix https://github.com/kubernetes/website/issues/42708

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/lgtm

Deploy Preview: [deploy-preview-42709-kubeadm/install-kubeadm](https://deploy-preview-42709--kubernetes-io-main-staging.netlify.app/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)

**Comment by dipesh-rawat** [comment]
@steve-hardman Can you kindly add the issue number to the description of the pull request as well?

**Comment by steve-hardman** [comment]
@dipesh-rawat done..have updated the description

**Review by Arhell — COMMENTED** [review]
lgtm

**Pull request merged**
