### PR TITLE
Fix the russian description about namespaces (themselves are not in namespaces)

### PR DESCRIPTION
**Pull request by muxx**
Fix the russian description that namespaces resources are not themselves in a namespace.

Unfortunatelly branch `dev-1.17-ru.1` too old and there isn't branch for newer versions. That's why I've created PR for `master`.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/27922#issuecomment-835802204

**Comment by muxx** [comment]
I signed it

**Comment by muxx** [comment]
Hm, it's strange but I'll check again

**Comment by muxx** [comment]
I've checked my email in https://identity.linuxfoundation.org and in commit. They are the same but cla  check is not successful :(

**Comment by jimangel** [comment]
Hey there! @muxx, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by muxx** [comment]
> Hey there! @muxx, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

Hi @jimangel! I've logged in Linux Foundation ID Portal with GitHub and confirmed email address http://ds.retailcrm.tech/s/1622563788.png but can't understand what I have to do else (

**Comment by RA489** [comment]
> I signed it

/check-cla

**Comment by tengqm** [comment]
I'm closing this due to CLA issue open for too long. Please feel free to reopen when the agreement is signed.
/close

**Pull request closed without merging**
