### PR TITLE
ZH-trans: add examples/

### PR DESCRIPTION
**Pull request by xichengliudui**

### CODE REVIEW

**Comment by xichengliudui** [comment]
[source code](https://github.com/kubernetes/website/tree/release-1.12/content/en/examples)

**Comment by chenrui333** [comment]
I think we should focus on the release-1.12, if the issue exists in v-1.12, we can fix there and then later it would be PR into the master branch and get fixed.

**Comment by xichengliudui** [comment]
@tengqm  @chenrui333 ok, thanks

**Comment by tengqm** [comment]
I put an hold on this because I'm not sure the examples test case code will be triggered by the gate.

**Comment by Hartmarken348** [comment]
11009

**Pull request closed without merging**
