### PR TITLE
Add site search to home page

### LINKED ISSUE #21867: Add site search to main page
**This is a Feature Request**

**What would you like to be added**
Add a facility to search the website to the main page, https://kubernetes.io/

**Why is this needed**
Let's say someone arrives at https://kubernetes.io/ and wants to find the download page. Well, the top 3 results on https://kubernetes.io/search/?q=downloads look pretty relevant.
The trouble is there's no form on https://k8s.io/ to do that search, and it's not obvious that navigating round the site will reveal that search.

**Comments**
Consider both desktop and mobile browser use cases. The main page is some readers' first impression of Kubernetes, so it's important to make a good one.

Most people known how to use Google _(other search products exist)_ so fixing this need not be a priority.

### PR DESCRIPTION
**Pull request by dipesh-rawat**
Resolves #21867 

**_Brief summary of changes in this PR:_**

* A search bar has been added to the navigation bar on the home page.
* Corresponding CSS and script have also been added.
* Screenshots have been below to show how the search bar looks on desktop and mobile devices.

_Search on Desktop_

K8s-desktop-nav

K8s-desktop-searchbar

_Search on Mobile_

K8s-mobile-nav

K8s-mobile-searchbar

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
For review and feedback as requestor for this feature.

/cc @sftim

**Comment by sftim** [comment]
I'm not keen on the way that the navigation jumps between the main and other pages. How about either:
- moving the search form outside of the page header
- rendering the magnifying glass search on _every_ page

?

**Comment by dipesh-rawat** [comment]
@sftim Thanks for feedback will look into this. 
Also, one more thing about rendering search option on every pages, looking at the feature description #21867 below; I was under the assumption it was meant to be only for the homepage.

> Add a facility to search the website to the main page, https://kubernetes.io/

**Comment by dipesh-rawat** [comment]
@sftim I suggest expanding scope of this feature by adding a search option in the navbar for all pages, as it offers more convenience and flexibility to users than a search input field solely on the homepage. Although we already have a search field in the sidebar for pages, having the search option in the navbar means users can access it easily from any page, improving the user experience and making the website more user-friendly. Moreover, having the search option in the navbar ensures users can quickly find what they're looking for, regardless of the page they're on.

**Comment by sftim** [comment]
> I suggest expanding scope of this feature by adding a search option in the navbar for all pages, as it offers more convenience and flexibility to users than a search input field solely on the homepage. Although we already have a search field in the sidebar for pages, having the search option in the navbar means users can access it easily from any page, improving the user experience and making the website more user-friendly. Moreover, having the search option in the navbar ensures users can quickly find what they're looking for, regardless of the page they're on.

OK, here's how to make that work:
1. File a new issue about having a site search in the website header
2. Close _this_ PR
3. Open a PR that adds that site search. Ideally, copy as much as is feasible from upstream Docsy.
4. Leave the site search in the sidebar; it's not a problem to have multiple ways for readers to search.

**Comment by dipesh-rawat** [comment]
Closing this PR in favour of new issue to expand the scope of this feature by adding a search option for all pages. 

/close

**Pull request closed without merging**
