### PR TITLE
Fix "visible" translation in static-pod.md

### PR DESCRIPTION
**Pull request by buptliuwei**
The translation of visible is wrong in the Chinese document, easily misleading

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@buptliuwei  You can make your emails match up in one of two ways:

1. Login to the [CLA site](https://identity.linuxfoundation.org/projects/cncf) and change it to match what you use as your default email address on your GitHub account
2. Change your default email address on your GH account to the same one you used to sign the CLA.

**Comment by buptliuwei** [comment]
> sign

**Review by plutach — APPROVED** [review]

**Pull request merged**
