### PR TITLE
Use monospace for HostFolder and VM in japanese Minikube setup guide

### PR DESCRIPTION
**Pull request by lightlace**
Use monospace for HostFolder and VM in the japanese Minikube setup guide.

### CODE REVIEW

**Comment by inductor** [comment]
Hi, Thanks for contributing!

Maybe adding the reference to the original issue in English would be nice @lightlace

**Comment by inductor** [comment]
Nevermind.

Ref: https://github.com/kubernetes/website/pull/18748

**Comment by inductor** [comment]
/hold

We will wait until the English PR is merged

**Comment by nasa9084** [comment]
LGTM if en version is merged

**Comment by inductor** [comment]
Hi,

as https://github.com/kubernetes/website/pull/18748 has been closed, this issue shall be closed as well.

**Pull request closed without merging**
