### PR TITLE
AWS recently added a new feature

### PR DESCRIPTION
**Pull request by jithindevasia**

### CODE REVIEW

**Comment by irvifa** [comment]
Hey @jithindevasia could you please sign the CLA first? Thanks!

**Review by Arhell — COMMENTED** [review]
About CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
👋 @jithindevasia .
Can you verify that you have signed the CLA?
Reach out if you need help. After the CLA is signed, this PR can be reviewed.

**Pull request closed without merging**
