### PR TITLE
Update create-cluster-kubeadm.md

### PR DESCRIPTION
**Pull request by bitas-guoliang**
+“概述”测试

### CODE REVIEW

**Comment by tengqm** [comment]
@bitas-guoliang pls sign the CLA for this to be reviewed. Thanks.

**Comment by celestehorgan** [comment]
Hey there! @bitas-guoliang, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by celestehorgan** [comment]
Hey there! @bitas-guoliang, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jimangel** [comment]
:wave: @bitas-guoliang given the length this PR has gone with no activity I'm going to close it. 

Feel free to reopen the PR once the CLA issue is resolved or reach out if we can help! Thanks!

/close

**Pull request closed without merging**
