### PR TITLE
Get the updated Yarn Debian key (#26539)

### LINKED ISSUE #26539: Yarn Debian key expiry date updated
**This is a Bug Report**

**Problem:**

The Yarn Debian key has expired for the script in [Ubuntu, Debian or HypriotOS](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#k8s-install-0). I got the following error message when I ran `sudo apt-get update`:
```
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
```

**Proposed Solution:** 

As mentioned in [yarnpkg/yarn](https://github.com/yarnpkg/yarn/issues/7866), to get the updated key, run this: 
```curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -``` 

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#k8s-install-0

### PR DESCRIPTION
**Pull request by AaronLuo3296**
`Fixes #26539`: Get the updated Yarn Debian key.

### CODE REVIEW

**Comment by neolit123** [comment]
hi, you'd have to sign the CLA (see above) to contribute to k8s.

i'm going to put a hold on it and comment on the original ticket:
https://github.com/kubernetes/website/issues/26539

because it's not clear if this is the right thing to do.
/hold

**Comment by neolit123** [comment]
please add `Fixes #26539` in your PR description.

**Comment by AaronLuo3296** [comment]
> hi, you'd have to sign the CLA (see above) to contribute to k8s.
> 
> i'm going to put a hold on it and comment on the original ticket:
> #26539
> 
> because it's not clear if this is the right thing to do.
> /hold

Hi, I'v already signed the CLA.

**Comment by AaronLuo3296** [comment]
> please add `Fixes #26539` in your PR description.

Updated the PR description.

**Comment by inductor** [comment]
Please remove the quote(\`\`) to activate the Issue link.

**Review by sftim — CHANGES_REQUESTED** [review]
This looks incorrect to me. @AaronLuo3296 could you explain why you recommend making this change?

**Comment by justaugustus** [comment]
ref: https://github.com/kubernetes/website/issues/26539#issuecomment-780058862

/close

**Pull request closed without merging**
