### PR TITLE
Fix minikube image 'project:hello-minikube-zero-install' has been suspended.

### PR DESCRIPTION
**Pull request by lou-lan**
See #20530, the description for pull image 'project:hello-minikube-zero-install' seems wrong, and this PR is going to fix this.

### CODE REVIEW

**Comment by mfilocha** [comment]
Waiting for approval of English version of https://github.com/kubernetes/website/issues/20530.

**Comment by lou-lan** [comment]
> Waiting for approval of English version of #20530.

English version has been merged.
https://github.com/kubernetes/website/blob/master/content/en/docs/tutorials/hello-minikube.md

**Pull request merged**
