### PR TITLE
Partner page updates

### PR DESCRIPTION
**Pull request by kbarnard10**
New listings for the kubernetes.io/partner page.

### CODE REVIEW

**Comment by zacharysarah** [comment]
@kbarnard10 👋 Please make sure you've got your CLA squared away. (Did you change the email address associated with your GH account?)

**Comment by kbarnard10** [comment]
@zacharysarah Nope - not sure what's going on so I will have to reach out to helpdesk.

**Comment by kbarnard10** [comment]
Going to close and re-submit to fix this CLA issue

**Pull request closed without merging**
