### PR TITLE
[zh-cn]Fix add anchors to all Chinese titles

### PR DESCRIPTION
**Pull request by javadoors**
[zh-cn]Fix add anchors to all Chinese titles

### CODE REVIEW

**Review by Sea-n — COMMENTED** [review]
I think it's better to add all the link anchors instead of opening a PR with only one line change.

**Comment by Sea-n** [comment]
Hum.. It's no need to close this PR either. 😅

I think it would be great if you could reopen this and then add other link anchors within this PR. 😊

**Comment by javadoors** [comment]
> Hum.. It's no need to close this PR either. 😅
> 
> I think it would be great if you could reopen this and then add other link anchors within this PR. 😊

Great,I will open the pr again.-_-

**Review by Sea-n — COMMENTED** [review]
Thanks!

/lgtm

**Pull request merged**
