### PR TITLE
Update manage-resources-containers.md

### PR DESCRIPTION
**Pull request by wuyongpeng**
修改内存资源单位的描述：”证书“改为”整数“

### CODE REVIEW

**Comment by windsonsea** [comment]
Please sign a [CLA](https://github.com/kubernetes/community/blob/master/CLA.md) before a reviewer jumps in.

**Comment by Sea-n** [comment]
Hey @wuyongpeng,

You have to sign the CLA so that we can review this PR and move forward.
Just click on the red NOT COVERED button in the first comment.
哈囉，你需要先簽署 CLA 貢獻者授權協議，我們才能 Review 並合併這個 PR
請點擊上方第一個留言的紅色 NOT COVERED 按鈕，並依網站指示操作

After signing the CLA, you may use this command to refresh the status:
/easycla

If you have any problem, please take a look at [the CLA tutorial](https://git.k8s.io/community/CLA.md).
如果用起來還有問題，可以先看看 [這篇教學](https://git.k8s.io/community/CLA.md) 的操作截圖

**Comment by windsonsea** [comment]
Looks good to me as the first PR.
/lgtm

**Comment by ydFu** [comment]
Nice catch, keep contributing
/lgtm

**Review by Sea-n — COMMENTED** [review]
Thanks, looking forward for more contribution from you. 😊
/approve

**Pull request merged**
