### PR TITLE
kubeadm: add note about a bug in the PublicKeysECDSA feature gate

### PR DESCRIPTION
**Pull request by SequoiaGod**
Add note about that in the FG section of the kubeadm init doc.
xref https://github.com/kubernetes/website/issues/46799

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/sig cluster-lifecycle
/triage accepted
/assign @sftim
/label tide/merge-method-squash

**Comment by Shubham82** [comment]
preview looks good to me.
https://deploy-preview-46881--kubernetes-io-main-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-init/#feature-gates

/lgtm

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by sftim** [comment]
/remove-label tide/merge-method-squash

not needed; keeping a note of the merge base is handy

/approve

**Pull request merged**
