### PR TITLE
update KubeletPluginsWatcher feature gate

### PR DESCRIPTION
**Pull request by charrywanganthony**
KubeletPluginsWatcher feature is beta in 1.12 release
xref: [kubernetes/kubernetes#68200](https://github.com/kubernetes/kubernetes/pull/68200)

### CODE REVIEW

**Comment by charrywanganthony** [comment]
/assign @steveperry-53
PTAL

**Comment by tengqm** [comment]
This should go to release-1.12 branch.

**Comment by charrywanganthony** [comment]
@tengqm I saw the commits before were merged to master branch, should i change it to release1.12 ?

**Pull request merged**
