### PR TITLE
making wording clearer on extra in impersonation

### PR DESCRIPTION
**Pull request by mlbiam**
*should* implies that an `extra` can be mixed case.  but really it can't because a mixed case `extra` will mismatch on an RBAC `ClusterRole` once the header is canonicalized.

### CODE REVIEW

**Comment by sftim** [comment]
The names of HTTP headers are not case sensitive. If Kubernetes expects a particular case for that header name, I think that's a Kubernetes bug (that needs fixing), and not a detail to document.

My understanding is that Kubernetes should coerce the `( extra name )` to a consistent case.

/sig auth
/hold

**Comment by mlbiam** [comment]
I opened this PR after running into an issue with the client-go SDK cannonicalizing the extra attribute `remoteAddr` to the HTTP header `Impersonate-Extra-Remoteaddr` (notice that the `R` is now capitalized and the `a` is now lower-case).  I brought the issue up on sig-auth where @enj said:

> Extra keys must be lower case
> Because header keys are case insensitive and canonicalized

given that the client-go sdk won't work with camel case, and I'm pretty sure based on my own developement that golang would canonicalize a camel-case extra too, the wording should say *must* instead of *should*

**Comment by sftim** [comment]
Let's document that Kubernetes canonicalizes the extra key to lower case, but you can use whatever capitalization you like at the HTTP level.

**Comment by sftim** [comment]
(Also, we don't assume that developers are writing their API clients in Go).

**Comment by mlbiam** [comment]
this is according to the code https://github.com/kubernetes/kubernetes/blob/555623c07eabf22864f6147736fa191e020cca25/staging/src/k8s.io/apiserver/pkg/authentication/user/user.go#L31-L41

> 	// In order to faithfully round-trip through an impersonation flow, these keys
	// MUST be lowercase.

shouldn't the code's comment's expectations match in the documentation so the user's excpectations and the dev's expectations match?

**Comment by mlbiam** [comment]
(also, going to update this PR with a note about including usage specific suffix per the same docs)

**Comment by sftim** [comment]
The audience for code comments is a lot different from the audience for docs. I won't object to someone improving the comment in the code, but I also wouldn't insist on it.

**Comment by mlbiam** [comment]
ok, so there's a gap here between the expectations of the code and what's being presented to users.  You're saying that this is a bug in k8s, not something that should be addressed in documentation?

**Comment by sftim** [comment]
Here's the situation how I see it:
- You can impersonate when invoking the Kubernetes API
- When you impersonate, you can set extra data
  - extra data is key/value pairs
  - the keys are lower-case strings
  - the values are strings
- you set extra data when impersonating using an HTTP header
  - the name of the HTTP header is `"Impersonate-Extra-"` with the key string appended
  - at the HTTP level, you can use any case for the key string
  - within Kubernetes, the key string is coerced to lowercase

If you have an RBAC rule
```yaml
- apiGroups: ["authentication.k8s.io"]
  resources: ["userextras/scopes"]
  verbs: ["impersonate"]
  resourceNames: ["lowercaseexample","PascalCaseExample", "camelCaseExample"]
```
and you try to set that using an HTTP header: `Impersonate-Extra-camelCaseExample`
then it doesn't work, because the `resourceName` _camelCaseExample_ should have been written as _camelcaseexample_ in that rule, to match the internal coercion to lowercase.

With the same rule, if you use an HTTP header: `Impersonate-Extra-LOWERCASEEXAMPLE` then it works fine. The extra key from the HTTP header is coerced to `lowercaseexample`, which matches.

I don't think the new wording makes that clear; instead, readers might think that **at the HTTP level**, the case they use matters.

**Comment by sftim** [comment]
Any change that clarifies things is welcome!

**Comment by kbhawkey** [comment]
> I see your point that the HTTP header's name doesn't need to be lower case, it's the `ClusterRole`'s `rules[].resources` that must be lowercase and that part of the docs is talking specifically about HTTP headers.
> 
> What if I switched **must** back to **should**, but add a sentence to the section on defining the `ClusterRole` that says the `resources` must be lowercase?

Hi @mlbiam . Yes, I like your suggestion. Do you have time to add the clarification? Thanks!

**Pull request merged**
