### PR TITLE
Update blog content files to move author details in front-matter

### PR DESCRIPTION
**Pull request by dipesh-rawat**
This PR extends the changes made in PR https://github.com/kubernetes/website/pull/45865 and implements those changes to all the blog files as per the recommendation in https://github.com/kubernetes/website/pull/45865#issuecomment-2054036103. The primary change involves relocating author details into the metadata within the front matter.

_**Edit**: I'll split this into several PRs each focusing on a single year blog._

- [x]  Changes merged for 2024 blogs
- [x]  Changes merged for 2023 blogs
- [x]  Changes merged for 2022 blogs
- [x]  Changes merged for 2021 blogs
- [x]  Changes merged for 2020 blogs
- [x]  Changes merged for 2019 blogs
- [x]  Changes merged for 2018 blogs
- [x]  Changes merged for 2017 blogs
- [x]  Changes merged for 2016 blogs

#### Useful Link
[Preview Blog Summary Page](https://deploy-preview-45957--kubernetes-io-main-staging.netlify.app/blog)

### CODE REVIEW

**Review by Gauravpadam — COMMENTED** [review]
/lgtm

Since this will standardize the format, Thanks @dipesh-rawat

**Review by sftim — COMMENTED** [review]
To make this easier to review, I recommend splitting it by the year of the article.

Would you do that @dipesh-rawat?

**Comment by ricardoamaro** [comment]
I agree with @sftim 
Impressive work btw!!

**Comment by dipesh-rawat** [comment]
> To make this easier to review, I recommend splitting it by the year of the article.

Sure, I've done that now.

**Comment by dipesh-rawat** [comment]
Reviewing over 350+ files will be a substantial task for this PR. To tackle this efficiently, I'll be breaking down the pull request into individual ones _(each focusing on a single year)_, starting from this year’s blogs and progressing in descending order.

**Comment by dipesh-rawat** [comment]
I've streamlined the PR to focus specifically on 2015 blog updates. All other years blog updates has been merged separately, making this PR ready for review again.

**Comment by sftim** [comment]
(nit) Why two commits?

**Comment by dipesh-rawat** [comment]
> (nit) Why two commits?

Opps! My bad, missed squashing in splitting commits.

**Comment by nate-double-u** [comment]
Thanks for doing all this @dipesh-rawat!

/approve

**Pull request merged**
