### PR TITLE
[zh] Remove ^H character

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

The ^H character (ASCII code 08 Backspace) will broke the format of the content in some environments, so drop it.

### CODE REVIEW

**Comment by mayocream** [comment]
Sync changes from upstream.
```bash
./scripts/lsync.sh content/zh/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md 

 Kubeadm allows you to use a custom image repository for the required images.
-See [Using custom images](docs/reference/setup-tools/kubeadm/kubeadm-init#custom-images)
+See [Using custom images](/docs/reference/setup-tools/kubeadm/kubeadm-init#custom-images)
 for more details.
 
 ### Initializing your control-plane node
```

**Comment by fenggw-fnst** [comment]
@mayocream Thanks for the review, I think the update has already been done by #30383
I just did the check, and it shows "still in sync".

```
$ ./scripts/lsync.sh content/zh/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/zh/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md is still in sync
```

**Comment by fenggw-fnst** [comment]
Could you please fetch the newest version and confirm again? Thanks!

**Comment by mayocream** [comment]
@fenggw-fnst Sorry for it! I apologize. orz
/unhold
/lgtm

**Pull request merged**
