### PR TITLE
add video to case study index page

### PR DESCRIPTION
**Pull request by alexcontini**

### CODE REVIEW

**Comment by zacharysarah** [comment]
@alexcontini 👋 It looks like you need to update your local fork with today's changes. I recommend closing this PR, updating your local fork, then opening a new PR based on the refactored results.

To update your local fork of k/website:
```bash
git checkout master
git fetch upstream
git merge upstream/master
git push
```

**Comment by alexcontini** [comment]
@zacharysarah  thank you and sorry about that! so I see that it's been updated and is set up differently than before, I have been asked to add a video directly below the 4 featured case studies on the case study index page (https://www.youtube.com/embed/2RmJ32VqX3U) and can't quite understand how to/if this is possible to add? 

are you or anyone on your team able to embed that video directly above the box video by any chance?

**Comment by zacharysarah** [comment]
@alexcontini 👋 I'm at a conference this week, thanks for being patient. Are you trying to replace the "Kubernetes at Box" video?

**Comment by kbarnard10** [comment]
@alexcontini - Sorry, just saw this. Let's chat more about this tomorrow!

**Comment by zacharysarah** [comment]
@kbarnard10 I'm interested in knowing more, also--I can see the `video:` param in `content/en/case-studies/box/index.html`, but it looks like the logic in `layouts/case-studies/list.html` may populate the video player based on the fact that there's only one case study with a `video:` attribute.

@bep, any input?

**Pull request closed without merging**
