### PR TITLE
Subscribe button on the home page is not aligned. #13672

### PR DESCRIPTION
**Pull request by SupriyaSirbi**
Align Subscribe Button in the Home Page

### CODE REVIEW

**Comment by SupriyaSirbi** [comment]
Hello @Rajakavitha1 and @zhangxiaoyu-zidif 

Any updates on this issue? Thanks

**Comment by Rajakavitha1** [comment]
Checked: https://deploy-preview-14175--kubernetes-io-master-staging.netlify.com/

Subscribe button is now aligned.

/lgtm
/approve

**Pull request merged**
