### PR TITLE
Remove /static/images/community_logos

### LINKED ISSUE #22094: Remove /static/images/community_logos
Umbrella issue: #22024

Remove the `/static/images/community_logos` directory and files.

They aren't used anywhere, so this is a fairly easy change.

### PR DESCRIPTION
**Pull request by habibrosyad**
/kind cleanup

Remove unused /static/images/community_logos

Fix #22094

### CODE REVIEW

**Comment by celestehorgan** [comment]
To test this I:

- Did a keyword search in both `org:kubernetes` and `org:cncf` for one of the logo files (`appformix.png`). 
- Looked on all pages that use customer logos in any way ([case studies](https://deploy-preview-23052--kubernetes-io-master-staging.netlify.app/case-studies/), [community](https://deploy-preview-23052--kubernetes-io-master-staging.netlify.app/community/), [partners](https://deploy-preview-23052--kubernetes-io-master-staging.netlify.app/partners/), [training](https://deploy-preview-23052--kubernetes-io-master-staging.netlify.app/training/)) to verify that all pages had all images working. 
- Checked blog posts (i.e. [this one](https://deploy-preview-23052--kubernetes-io-master-staging.netlify.app/blog/2016/03/appformix-helping-enterprises/)) associated with the company logos in question to ensure that no broken images appeared here either.


All of the above are verified as working and okay. As such I'll LGTM this and wait for the weekly approver to approve.

/lgtm

**Comment by sftim** [comment]
/approve

Thanks @habibrosyad

**Pull request merged**
