### PR TITLE
Remove raw tag from shell snippet for terminated container status

### PR DESCRIPTION
**Pull request by ZAlfonse**
Deleting this `{% raw %}` tag as it was screwing up the formatting for the rest of this page and it didn't seem to be accomplishing anything.

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@ZAlfonse Could you please sign the CLA. 
Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

memo Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

**Comment by ZAlfonse** [comment]
Not sure what's going on with the CLA, I'll try to fix it soon.

**Comment by mistyhacks** [comment]
First, feedback on your change: The raw tags are needed because the Go template code also looks like Hugo template code (because of the double curly braces) and does need the raw tags.

Second, if you're having trouble signing the CLA, or you have signed it and it's not
working correctly, see https://github.com/cncf/servicedesk for more info. You
can also contact #sig-contribex on Slack. Please reopen this PR when it is all
sorted out, as we cannot accept this code until the checks are working
correctly. Thanks!

**Pull request closed without merging**
