### PR TITLE
[zh] sync reference/using-api/client-libraries.md

### PR DESCRIPTION
**Pull request by zhaojizhuang**
[zh]sync Add 3rd party content warning to Ingress Controllers concept
sync #25003 for chinese

[zh]sync 3rd warning in `content/en/docs/reference/using-api/client-libraries.md` #23107

### CODE REVIEW

**Comment by tengqm** [comment]
Please refer to the new guideline [here](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87) and propose a "complete sync" to these pages.

For example,

```
$ ./scripts/lsync.sh content/zh/docs/reference/using-api/client-libraries.md
diff --git a/content/en/docs/reference/using-api/client-libraries.md b/content/en/docs/reference/using-api/client-libraries.md
index 1531b2c5d..c14f0fa9c 100644
--- a/content/en/docs/reference/using-api/client-libraries.md
+++ b/content/en/docs/reference/using-api/client-libraries.md
@@ -12,20 +12,20 @@ API from various programming languages.
 
 
 <!-- body -->
-To write applications using the [Kubernetes REST API](/docs/reference/using-api/api-overview/),
+To write applications using the [Kubernetes REST API](/docs/reference/using-api/),
 you do not need to implement the API calls and request/response types yourself.
 You can use a client library for the programming language you are using.
 
 Client libraries often handle common tasks such as authentication for you.
 Most client libraries can discover and use the Kubernetes Service Account to
 authenticate if the API client is running inside the Kubernetes cluster, or can
-understand the [kubeconfig file](/docs/tasks/access-application-cluster/authenticate-across-clusters-kubeconfig/)
+understand the [kubeconfig file](/docs/tasks/access-application-cluster/configure-access-multiple-clusters/)
 format to read the credentials and the API Server address.
 
 ## Officially-supported Kubernetes client libraries
 
-The following client libraries are officially maintained by [Kubernetes SIG API
-Machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery).
+The following client libraries are officially maintained by
+[Kubernetes SIG API Machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery).
 
 
 | Language | Client Library | Sample Programs |
@@ -40,6 +40,8 @@ Machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery
 
 ## Community-maintained client libraries
 
+{{% thirdparty-content %}}
+
 The following Kubernetes API client libraries are provided and maintained by
 their authors, not the Kubernetes team.
 
@@ -60,6 +62,7 @@ their authors, not the Kubernetes team.
 | PHP                  | [github.com/allansun/kubernetes-php-client](https://github.com/allansun/kubernetes-php-client) |
 | PHP                  | [github.com/maclof/kubernetes-client](https://github.com/maclof/kubernetes-client) |
 | PHP                  | [github.com/travisghansen/kubernetes-client-php](https://github.com/travisghansen/kubernetes-client-php) |
+| PHP                  | [github.com/renoki-co/php-k8s](https://github.com/renoki-co/php-k8s) |
 | Python               | [github.com/eldarion-gondor/pykube](https://github.com/eldarion-gondor/pykube) |
 | Python               | [github.com/fiaas/k8s](https://github.com/fiaas/k8s) |
 | Python               | [github.com/mnubo/kubernetes-py](https://github.com/mnubo/kubernetes-py) |
```

**Comment by zhaojizhuang** [comment]
> Please refer to the new guideline [here](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87) and propose a "complete sync" to these pages.
> 
> For example,
> 
> ```
> $ ./scripts/lsync.sh content/zh/docs/reference/using-api/client-libraries.md
> diff --git a/content/en/docs/reference/using-api/client-libraries.md b/content/en/docs/reference/using-api/client-libraries.md
> index 1531b2c5d..c14f0fa9c 100644
> --- a/content/en/docs/reference/using-api/client-libraries.md
> +++ b/content/en/docs/reference/using-api/client-libraries.md
> @@ -12,20 +12,20 @@ API from various programming languages.
>  
>  
>  
> -To write applications using the [Kubernetes REST API](/docs/reference/using-api/api-overview/),
> +To write applications using the [Kubernetes REST API](/docs/reference/using-api/),
>  you do not need to implement the API calls and request/response types yourself.
>  You can use a client library for the programming language you are using.
>  
>  Client libraries often handle common tasks such as authentication for you.
>  Most client libraries can discover and use the Kubernetes Service Account to
>  authenticate if the API client is running inside the Kubernetes cluster, or can
> -understand the [kubeconfig file](/docs/tasks/access-application-cluster/authenticate-across-clusters-kubeconfig/)
> +understand the [kubeconfig file](/docs/tasks/access-application-cluster/configure-access-multiple-clusters/)
>  format to read the credentials and the API Server address.
>  
>  ## Officially-supported Kubernetes client libraries
>  
> -The following client libraries are officially maintained by [Kubernetes SIG API
> -Machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery).
> +The following client libraries are officially maintained by
> +[Kubernetes SIG API Machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery).
>  
>  
>  | Language | Client Library | Sample Programs |
> @@ -40,6 +40,8 @@ Machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery
>  
>  ## Community-maintained client libraries
>  
> +{{% thirdparty-content %}}
> +
>  The following Kubernetes API client libraries are provided and maintained by
>  their authors, not the Kubernetes team.
>  
> @@ -60,6 +62,7 @@ their authors, not the Kubernetes team.
>  | PHP                  | [github.com/allansun/kubernetes-php-client](https://github.com/allansun/kubernetes-php-client) |
>  | PHP                  | [github.com/maclof/kubernetes-client](https://github.com/maclof/kubernetes-client) |
>  | PHP                  | [github.com/travisghansen/kubernetes-client-php](https://github.com/travisghansen/kubernetes-client-php) |
> +| PHP                  | [github.com/renoki-co/php-k8s](https://github.com/renoki-co/php-k8s) |
>  | Python               | [github.com/eldarion-gondor/pykube](https://github.com/eldarion-gondor/pykube) |
>  | Python               | [github.com/fiaas/k8s](https://github.com/fiaas/k8s) |
>  | Python               | [github.com/mnubo/kubernetes-py](https://github.com/mnubo/kubernetes-py) |
> ```

done @tengqm

**Pull request merged**
