### PR TITLE
Fix sample command output for “Hello Minikube”

### PR DESCRIPTION
**Pull request by sftim**
https://kubernetes.io/docs/tutorials/hello-minikube/ has sample output marked as code (POSIX shell).

Fix that

/kind cleanup

### CODE REVIEW

**Comment by ryanmcginnis** [comment]
unassigning myself for this week's wrangler handle this request.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-18077--kubernetes-io-master-staging.netlify.com/docs/tutorials/hello-minikube/

**Pull request merged**
