### PR TITLE
content/_posts: point to correct changelog link (v1.15)

### PR DESCRIPTION
**Pull request by danishprakash**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@danishprakash
Pls sign the CLA in order for the PR to be reviewed.

**Comment by bradtopol** [comment]
Hi @danishprakash Thank you for your contribution. Please sign the CLA so we can accept your PR for review.
/assign

**Comment by danishprakash** [comment]
@Arhell @bradtopol sorry about this, having some issues with the CLA form, in touch with support from TLF, will update this once it's resolved.

**Comment by danishprakash** [comment]
I signed it

**Pull request merged**
