### PR TITLE
sync-zh-files-from-1.12

### PR DESCRIPTION
**Pull request by fleeto**

### CODE REVIEW

**Comment by chenrui333** [comment]
as discussed, it would be best that we dont lose any commit history of the migrations between the versions.

**Comment by tengqm** [comment]
@chenrui333 Are you talking about cherry-picking all those PRs to "release-1.14" branch? That will be a daunting task.

@fleeto Shall we target "master" or "release-1.14"?

**Comment by chenrui333** [comment]
@tengqm not cherry-picking. Two additional commits to merge the branch `release-1.12` to branch `release-1.14`.

In this way, our commit history would be potentially captured when we ultimately moved to master branch.

**Comment by chenrui333** [comment]
I am mostly thinking of this PR merge practice in terms of contribution credit.

**Pull request closed without merging**
