### PR TITLE
[ja] Update ja/docs/concepts/scheduling-eviction/kube-scheduler.md to fix the weight and some links

### LINKED ISSUE #32677: [ja] Update /ja/docs/concepts/scheduling-eviction/kube-scheduler.md to fix the weight and some links
**This is a Feature Request**

**What would you like to be added**

Update ja/docs/concepts/scheduling-eviction/kube-scheduler.md to fix the weight and some links.

**Why is this needed**
- The weight value has changed on the current English page.
- One of the links on this page does not work.
- Update to other links.

**Comments**

/language ja
/assign

### PR DESCRIPTION
**Pull request by 196Ikuchil**
Resolves #32677

### CODE REVIEW

**Comment by nasa9084** [comment]
ah~ sorry, the document is old, we are accepting PRs to main branch actually because we have only a few active member (too few to manage branch for each version)
so unless you actually want to contribute 1.19 document, you can make a PR for main

**Comment by 196Ikuchil** [comment]
@nasa9084 
ok, I change it toward the main.

**Pull request merged**
