### PR TITLE
update tab component, remove jquery-ui

### PR DESCRIPTION
**Pull request by kbhawkey**
- Update tabs shortcode to use bootstrap library+styles for tab functionality instead of jquery-ui.
- Remove jquery-ui css/js references from css.html and head.html partials.
- Remove jquery-ui JS library and CSS file(s). Check if there other related CSS files to remove.

### CODE REVIEW

**Comment by kbhawkey** [comment]
See issue #21922

**Comment by kbhawkey** [comment]
Check for removal:
static/images/jquery-ui/ui-icons*
static/css/jquery-ui.theme.min.css

**Comment by kbhawkey** [comment]
Page previews:
https://deploy-preview-24234--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-alpha/

https://deploy-preview-24234--kubernetes-io-master-staging.netlify.app/docs/reference/access-authn-authz/extensible-admission-controllers/#service-reference

https://deploy-preview-24234--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-join-phase/#cmd-join-phase-control-plane-prepare

https://deploy-preview-24234--kubernetes-io-master-staging.netlify.app/docs/contribute/style/hugo-shortcodes/#tabs

**Comment by tengqm** [comment]
Great.
/lgtm

**Comment by sftim** [comment]
Echoing LGTM from https://github.com/kubernetes/website/pull/24234#issuecomment-701066476
/lgtm

/approve

Thanks @kbhawkey

**Pull request merged**
