### PR TITLE
fix broken field on the main page in the video block

### PR DESCRIPTION
**Pull request by Arhell**
issue #19728
/language ru

### CODE REVIEW

**Comment by sftim** [comment]
@Arhell this file is shared across localizations
/remove-language ru

**Comment by kbhawkey** [comment]
Hello @Arhell .
I reviewed the change for the text display of the `#desktopKCButton` on the `https://kubernetes.io/ru` page. I tested your change as well as changing,
```
#desktopKCButton->position: absolute
```
The `ru` button text displays within the page space.

**Comment by Arhell** [comment]
Hi @kbhawkey
Thanks! Great solution, corrected.

**Pull request merged**
