### PR TITLE
Re-enabling the it translation and put all current translation in draft

### PR DESCRIPTION
**Pull request by Fale**
Re-enabling the it translation and put all current translation in draft mode. As the work on #18383 will progress those will be promoted to final.

This will allow us to:
1. Greatly simplify the review process
2. Not have translations that have not yet been reviewed on the website

### CODE REVIEW

**Comment by jnardiello** [comment]
+1 on this as it looks the correct way to go. Count on me for reviews on the translations

**Comment by sftim** [comment]
Oh, another thing sorry @Fale 
The language name is wrong in https://github.com/kubernetes/website/pull/18436/files#diff-618063036395fe9ee107f22b46c9eadeR188-R189
(should be Italiano, right?)

You can take a look at https://deploy-preview-18436--kubernetes-io-master-staging.netlify.com/it/ and see if you're happy with the preview.

**Comment by Fale** [comment]
@sftim I think I've addressed all your points with the last commit

**Comment by sftim** [comment]
@Fale are you happy that https://deploy-preview-18436--kubernetes-io-master-staging.netlify.com/it/ looks ready to merge?

**Comment by fabriziopandini** [comment]
Getting preview available will greatly help the translation work, so I'm +1

**Comment by Fale** [comment]
I agree with @fabriziopandini 
This PR will help a lot in speeding up the following PRs, so I think that even if is not perfect it will improve very quickly thanks to this PR

**Comment by sftim** [comment]
If the main aim is to have working previews for pull requests, how about enabling Italian _on a new localization branch_, and then collaborating on that branch until it's ready to merge to `master`.

Would that be OK? At the moment, merging this looks like it'd add lots of links to https://k8s.io/it/ only for readers who follow those links to see a very incomplete translation.

**Comment by sftim** [comment]
There's now a new _dev-1.17-it.1_ branch.
@Fale would you be happy to change this PR to target that branch? If so, please do.

**Comment by rlenferink** [comment]
@sftim I think we're still good to go on merging this one. And then from the dev-1.17-it.1 make the further improvements.

@Fale to answer your question on slack: the workflow of reviewing / approving is the same as on the master branch.

**Comment by sftim** [comment]
@rlenferink, to confirm: the [preview](https://deploy-preview-18436--kubernetes-io-master-staging.netlify.com/it/) represents what you're happy to go live?

(To me, that seems like it's not ready).

**Comment by sftim** [comment]
I'm very happy to see work shift to _dev-1.17-it.1_, because that doesn't break the live site.

**Comment by rlenferink** [comment]
Ah, didn’t check the preview :s This indeed doesn’t look ready to be re-enabled again on the _master_ branch. Moving to separate branch is the best way to go then!

**Comment by Fale** [comment]
Thanks for opening the branch for the Italian translation. I've changed the base branch so it should now be mergeable

**Comment by sftim** [comment]
Cool.
Any of:
    - @fabriziopandini
    - @mattiaperi
    - @micheleberardi
    - @rlenferink

**Comment by sftim** [comment]
Actually, you know what? “Cerca” is fine, it's the only translation change. Approved.
/lgtm
/approve

**Pull request merged**
