### PR TITLE
[ko] update outdated korean files in dev-1.24-ko.3 (M1-M5)

### PR DESCRIPTION
**Pull request by having-dlrow**
Partially close https://github.com/kubernetes/website/issues/35802.

> - [ ]  M1. content/en/_index.html | 3(+XS) 3(-)
> - [ ]  M2. content/en/docs/concepts/architecture/control-plane-node-communication.md | 1(+XS) 1(-)
> - [ ]  M3. content/en/docs/concepts/architecture/nodes.md | 9(+XS) 14(-)
> - [ ]  M4. content/en/docs/concepts/cluster-administration/_index.md | 48(+M) 28(-)
> - [ ]  M5. content/en/docs/concepts/configuration/manage-resources-containers.md | 5(+XS) 1(-)

The task from M1 to M5 were worked.
M2 (content/en/docs/concepts/architecture/control-plane-node-communication.md) has a lot of changes due to auto-trim space issue.
M1 ~ M5 까지의 변경사항들을 반영하였습니다 ( M2에 띄어쓰기 이슈로 수정사항이 많습니다 )

/language ko

### CODE REVIEW

**Review by seokho-son — COMMENTED** [review]
@having-dlrow 꼼꼼하게 잘 처리해주셨네요! 감사합니다.

outdated 갱신에 누락된 사항이 하나 있어서 공유 드립니다. :)

content/ko/docs/concepts/configuration/manage-resources-containers.md 
334 라인에 

```diff
- E, P, T, G, M, K와 같은 접미사 중 하나를 사용하여 스토리지를 일반 정수 또는 고정 소수점 숫자로 표현할 수 있다.
+ E, P, T, G, M, k와 같은 접미사 중 하나를 사용하여 스토리지를 일반 정수 또는 고정 소수점 숫자로 표현할 수 있다.
```
K --> k 로 수정되어야 할 것 같습니다.

관련 PR: https://github.com/kubernetes/website/pull/34941

**Comment by having-dlrow** [comment]
@seokho-son 님 리뷰 감사드립니다. 수정 완료하였습니다 ^^

**Comment by seokho-son** [comment]
감사합니다! :)
/lgtm

**Pull request merged**
