### PR TITLE
[ko] Update namespaces.md to align with en site

### PR DESCRIPTION
**Pull request by serithemage**
Delete content that doesn't exist in the English version.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/website/pull/31734#issuecomment-1038912700

**Comment by ianychoi** [comment]
Thank you for the reporting! It is due to updating from old translation to sync with updated English content - https://github.com/kubernetes/website/issues/30000

@serithemage  Would you sign in CLA? See https://kubernetes.io/ko/docs/contribute/new-content/#sign-the-cla regarding the context of why CLA is required.

**Comment by reylejano** [comment]
Hi @serithemage ,

Please sign the EasyCLA
https://github.com/kubernetes/community/blob/master/CLA.md

If this PR has no traction, a PR Wrangler may close this PR

**Comment by jimangel** [comment]
Hey there! @serithemage, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by serithemage** [comment]
Hi Angel,
I'm sorry for the delay in responding. I completed the requested CLA.
Please Check it.

Thank you.

2022년 4월 28일 (목) 오후 11:14, Jim Angel ***@***.***>님이 작성:

**Comment by jihoon-seo** [comment]
영문 링크: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#:~:text=not%20a%20requirement.-,kube%2Dnode%2Dlease,-This%20namespace%20holds

감사합니다!

/lgtm
/approve

**Pull request merged**
