### PR TITLE
Blog Post: Out of the Clouds onto the Ground: How to Make Kubernetes Production Grade Anywhere

### PR DESCRIPTION
**Pull request by kbarnard10**
Adding blog post.

### CODE REVIEW

**Comment by neolit123** [comment]
FYI all, i will submit a copy edit commit for this later today.

**Comment by neolit123** [comment]
@kbarnard10 
Github tells me that i don't have push access to the `kbarnard10:blog` branch.

if you still want me to help with the edits, you need to grant me permission for the branch:
https://help.github.com/articles/enabling-branch-restrictions/

though, i need to leave in a couple of hours and i can do the rest on Sunday or Monday. :+1:

**Comment by cantbewong** [comment]
@neolit123 thanks for the edits, all your changes LGTM

**Comment by kbarnard10** [comment]
@neolit123 I made your suggested edits for time's sake. But will add you to future blog posts.

**Comment by neolit123** [comment]
@kbarnard10 awesome, thanks.

**Pull request merged**
