### PR TITLE
remove images from dashboard blog page

### PR DESCRIPTION
**Pull request by kbhawkey**
Temporarily remove images in blog page.
The site if failing to build the page with image processing (large images).

### CODE REVIEW

**Comment by kbhawkey** [comment]
See issue #26974.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-26975--kubernetes-io-master-staging.netlify.app/blog/2021/03/09/the-evolution-of-kubernetes-dashboard/

Did this PR build successfully in preview before merging?
I removed the images (temporarily) until we can sort out the image processing (or sizing) of the image files.

/cc @onlydole

**Review by onlydole — APPROVED** [review]
/lgtm 

Thank you, @kbhawkey!

**Comment by sftim** [comment]
This updates the article published via https://github.com/kubernetes/website/pull/26668

**Comment by floreks** [comment]
I'd love to restore them eventually as the text suggests their existence.

**Pull request merged**
