### PR TITLE
Fixed broken link rendering

### PR DESCRIPTION
**Pull request by uthark**
Fixed broken link rendering

### CODE REVIEW

**Comment by DanyC97** [comment]
thank you for the fix @uthark !
/lgtm

**Comment by uthark** [comment]
ping @zhangxiaoyu-zidif

**Comment by uthark** [comment]
@tengqm Hi! Do you know why tide says it is not mergeable, but [Details](https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes%2Fwebsite+author%3Authark+head%3Apatch-1) says it is good to be merged? What should I do?

**Comment by rlenferink** [comment]
> @tengqm Hi! Do you know why tide says it is not mergeable, but [Details](https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes%2Fwebsite+author%3Authark+head%3Apatch-1) says it is good to be merged? What should I do?

I've asked sig-testing about this. 
https://kubernetes.slack.com/archives/C09QZ4DQB/p1553709338842000

I'll follow up.

**Comment by uthark** [comment]
@rlenferink thank you for the update. I also joined #sig-testing channel, same handle as on github.

**Pull request merged**
