### PR TITLE
Fix awkward sentences

### PR DESCRIPTION
**Pull request by frogred8**

### CODE REVIEW

**Comment by bradtopol** [comment]
@frogred8 Thank you for your contribution. Please sign the CLA so we can accept your PR for review.
Assigning @jimangel as it is making lots of different changes.  @jimangel may suggest this being broken up into multiple PRs
/assign @jimangel

**Comment by jimangel** [comment]
/unassign
/assign @gochist
For Korean content review. Thanks!

**Comment by frogred8** [comment]
I just signed CLA. Thanks.

**Comment by gochist** [comment]
@frogred8 Thank you! I changed the base branch from `dev-1.16-ko.4` to `master` which might be the base branch you worked on. Please match the working branch and base branch for your next PR. 

/lgtm
/approve

**Pull request merged**
