### PR TITLE
Hyperlink to support period details

### PR DESCRIPTION
**Pull request by samnoon1971**
- Added hyperlink to support period details
- Updated https://kubernetes.io/releases/ 
- Updated https://kubernetes.io/docs/home/supported-doc-versions/

### CODE REVIEW

**Review by sftim — CHANGES_REQUESTED** [review]
I know you mentioned that this is relevant to #32930 @samnoon1971 - however, please write a description for this PR.

**Comment by samnoon1971** [comment]
> I know you mentioned that this is relevant to #32930 @samnoon1971 - however, please write a description for this PR.

Thank you, I wrote the description now.

**Comment by NitishKumar06** [comment]
Hey @samnoon1971 , Is this issue resolved now?

**Review by sftim — COMMENTED** [review]
This change looks good to me.
/lgtm

A second LGTM will be handy: as I'm an approver and this change would affect the live site, I don't want to both approve and LGTM the PR. If someone else marks this LGTM, I can then approve it!

**Pull request merged**
