### PR TITLE
Update weave-network-policy.md -- fixing typo.

### PR DESCRIPTION
**Pull request by natebwangsut**
Fix typo.

### CODE REVIEW

**Comment by bboreham** [comment]
It's not a typo - `po` is the abbreviation for `pods`.

I would accept an argument that `pods` is easier to read and hardly any more difficult to type in.

`get pod` seems wrong to me when requesting a list, although it appears to work.  Do you have any reference to back up its validity?

**Comment by natebwangsut** [comment]
Apologising for that, I didn't know that it was intended. I did not know that it was an abbreviation.

Still, `po` for me is harder to read. As an abbreviation there should be at least notes specifying that it is possible to use the shorter alternative. Doing either of modification (add `po` as a comment or change from `po` in command to `pods` while adding the comment to specify the shortcut) would be great. This change would improve the visibility and clarity of the docs.

**Comment by natebwangsut** [comment]
@bboreham What do you think ?

**Comment by bradtopol** [comment]
If you are willing to update this to be get pods I am willing to approve this. I agree with @bboreham

**Comment by natebwangsut** [comment]
Updated to `get pods` and added note on abbreviation.

**Comment by Rajakavitha1** [comment]
@natebwangsut thanks for the update!
/lgtm

**Comment by zacharysarah** [comment]
In the interest of clarity, I think it's best to remove the note about the abbreviation. Otherwise LGTM.

**Comment by zacharysarah** [comment]
Thanks @natebwangsut! ✨

**Pull request merged**
