### PR TITLE
flow control metrics: switch to snake_case for labels

### PR DESCRIPTION
**Pull request by adtac**
Fixes https://github.com/kubernetes/website/issues/24895

/cc @MikeSpreitzer

### CODE REVIEW

**Comment by adtac** [comment]
ref PR in k/k: https://github.com/kubernetes/kubernetes/pull/96236

**Review by sftim — COMMENTED** [review]
I recommend adding a note callout (`{{< note >}}` &hellip; `{{< note >}}`) on line 333 or thereabouts to tell readers that these metric labels have changed case in release v1.20

and that readers running older versions of Kubernetes should switch to the documentation for the version that they are running.

**Comment by sftim** [comment]
/hold
https://github.com/kubernetes/kubernetes/pull/96236 is not yet merged

**Comment by adtac** [comment]
@sftim added a note about k8s < v1.20. Also, https://github.com/kubernetes/kubernetes/pull/96236 has been merged, so:

/hold cancel

**Review by MikeSpreitzer — APPROVED** [review]
/LGTM
Thanks!

**Comment by MikeSpreitzer** [comment]
@sftim : I think this is ready for you to take another look and approve.

**Comment by lavalamp** [comment]
Tech LGTM here.

@sftim is there any reason to wait on this longer? I think it's good to go.

**Review by sftim — COMMENTED** [review]
/approve

**Comment by sftim** [comment]
D'oh. This should have been on the _dev-1.20_ branch, right?

**Comment by lavalamp** [comment]
Oh yes, probably. Sorry!

**Comment by sftim** [comment]
I'll get it reverted - can we get another PR opened that targets the _dev-1.20_ branch instead?

**Comment by adtac** [comment]
I understand why I'd need to create a new PR targeting dev-1.20, but can I know why the merge into master needs to be reverted? As far as I understand, we'd still need the same changes in 1.21 and beyond. Not too familiar with the release cut process, sorry.

**Comment by sftim** [comment]
We shouldn't tell readers
> If you're running Kubernetes versions v1.19 and earlier, you should refer to the documentation for your version.

if they _are_ looking at the v1.19 docs - it's unhelpfully recursive.

**Comment by sftim** [comment]
BTW the _master_ branch is docs for the current release

**Comment by MikeSpreitzer** [comment]
@sftim : Please help me understand what you are saying about the `master` branch.  Are you saying that right now the `master` branch is docs for release 1.19 and that when 1.20 is released the `master` pointer (in the sense that a branch is just a pointer to a commit) will be switched to point to the same commit as `dev-1.20`?

**Comment by sftim** [comment]
The Kubernetes website uses a continuous deployment process. This table should explain how we use branches.


| Scenario | Branch |
| ------------- | ------------- |
| Existing or new English language content for the current release of Kubernetes | _master_ (pending future rename) |
| (English) content for a feature change release | The branch which corresponds to the major and minor version the feature change is in, using the pattern dev-\<version\>. For example, if a feature changes in the v1.20 release, then add documentation changes to the _dev-1.20_ branch. |
|  Content in other languages (localizations) | Use the localization's convention. |

**Comment by sftim** [comment]
We will merge the _dev-1.20_ branch into _master_ by approving PR #24138; this happens as part of the release process. At that point, Netlify will see a change to _master_ and will deploy the updated website.

**Pull request merged**
