### PR TITLE
Added AWS eks

### PR DESCRIPTION
**Pull request by mastrolinux**
Improve doc to add aws eks

> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.9 Features: set Milestone to `1.9` and Base Branch to `release-1.9`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: Please check the “Allow edits from maintainers” box (see image below) to
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.
>
> NOTE: After opening the PR, please *un-check and re-check* the "Allow edits from maintainers" box. This is a temporary workaround to address a known issue with GitHub.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6568)

### CODE REVIEW

**Comment by zacharysarah** [comment]
@mastrolinux 👋 Please sign the CLA so we can proceed.

**Comment by mastrolinux** [comment]
@zacharysarah I did but apparently your bot does not find it. What else can I do? Just contact the linuxfoundation helpdesk?

**Comment by zacharysarah** [comment]
@mastrolinux Gotcha--looks like it just took the CI some time to reflect the update. LGTM, I'll flag this for merge.

/approve

**Comment by zacharysarah** [comment]
Manually squashing and merging due to PR age.

**Pull request merged**
