### PR TITLE
Image optimization for smaller file sizes without sacrificing quality

### PR DESCRIPTION
**Pull request by Rajpratik71**
Images are optimized for the images to load faster.

Faster pages have higher conversion rates, lower bounce rates, and happier users. 

And of course, smaller images reduce bandwidth costs for both the visitors and service provider

### CODE REVIEW

**Comment by sftim** [comment]
@Rajpratik71 are you having any CLA-related trouble? If so, would you like some help?

**Comment by Rajpratik71** [comment]
> @Rajpratik71 are you having any CLA-related trouble? If so, would you like some help?

yes , i think i am facing issue , although i signed the CLA according to the [guide](https://git.k8s.io/community/CLA.md#the-contributor-license-agreement)  , after that i initiated /check-cla to verify . Now it showing authorized but 1 other problem is still there regarding "do-not-merge/invalid-commit-message"

**Comment by Rajpratik71** [comment]
@jcjesus @jaredbhatti @chenopis @Lion-Wei requesting review

**Comment by jimangel** [comment]
@Rajpratik71 It appears that you have signed the CLA but there is still some problems with the CI check:

image

I personally haven't seen this before, and the link takes me to a page that doesn't help much: https://identity.linuxfoundation.org/projects/cncf

I imagine there is an issue with the author in the commits for this PR. I'm going to close this PR for now, feel free to open it again to see if it fixes the CLA problem.

https://git.k8s.io/community/CLA.md#the-contributor-license-agreement

Let me know if you have any questions!

/cc @zacharysarah @kbarnard10 
/close

**Pull request closed without merging**
