### PR TITLE
fix wrong argument order for apt-key

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/website/pull/24770

### CODE REVIEW

**Comment by tengqm** [comment]
pls don't do this. This page has been changed drastically.
Please instead propose a thorough fix.
See issue #24788
/hold

**Comment by sftim** [comment]
I'm not sure if this fix is still needed.

**Comment by sftim** [comment]
@npu21, could you rebase this change against _master_ (if it's still needed)?

**Comment by sftim** [comment]
@npu21 I am going to close this. However, please feel free to open a new PR that fixes any outstanding issues 
/close

**Pull request closed without merging**
