### PR TITLE
Updated Internal Load Balancer annotation for GCP

### LINKED ISSUE #41067: Update Internal Load Balancer annotation for GCP in accordance with Google Cloud Kubernetes Engine doc
Screenshot 2023-05-10 at 1 12 29 PM

Please update the details as per https://cloud.google.com/kubernetes-engine/docs/concepts/service-load-balancer#load_balancer_types.

`networking.gke.io/load-balancer-type: "Internal"` (GKE 1.17 and later)
`cloud.google.com/load-balancer-type: "Internal"` (versions earlier than 1.17)

### PR DESCRIPTION
**Pull request by pran2711**
Made changes as per requirement.

Fixes #41067

### CODE REVIEW

**Comment by Shubham82** [comment]
corresponding issue: #41067
JFYI: @pran2711 Please mention the related issue like Fixes <#Issue No.> under the above description so that it will be easy for the reviewers to look at what this PR is for, and the issue will close automatically soon after the PR merge.

**Comment by Shubham82** [comment]
It seems good to me.
/lgtm

**Comment by reylejano** [comment]
I reviewed the google cloud docs and confirmed
/approve

**Pull request merged**
