### PR TITLE
Add kubelet credentialprovider API reference

### PR DESCRIPTION
**Pull request by tengqm**
This is a followup of #30859.

/hold
until #30859 is in.

### CODE REVIEW

**Review by Bezzo100-lab — APPROVED** [review]

**Comment by reylejano** [comment]
Preview of updated pages:
- https://deploy-preview-30860--kubernetes-io-main-staging.netlify.app/docs/reference/
- https://deploy-preview-30860--kubernetes-io-main-staging.netlify.app/docs/reference/config-api/kubelet-credentialprovider.v1alpha1/
- https://deploy-preview-30860--kubernetes-io-main-staging.netlify.app/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/

Related enhancement issue https://github.com/kubernetes/enhancements/issues/2133 and [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2133-kubelet-credential-providers)

Can we get a @kubernetes/sig-node-pr-reviews review on the proposed [Kubelet CredentialProvider (v1alpha1) page](https://deploy-preview-30860--kubernetes-io-main-staging.netlify.app/docs/reference/config-api/kubelet-credentialprovider.v1alpha1/)

/sig node

**Pull request merged**
