### PR TITLE
Made try-kubernetes button appear more pretty 

### PR DESCRIPTION
**Pull request by jamesgeorge007**
This is PR is a fix for #10526

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
I have signed signed the CLA. But, still ```cla/linuxfoundation``` status hasn't been updated.

**Comment by jamesgeorge007** [comment]
@steveperry-53 Kindly review the PR :smile:

**Comment by jamesgeorge007** [comment]
@Rajakavitha1 @steveperry-53 @stewart-yu Kindly review the PR :smile:

**Comment by tengqm** [comment]
LGTM. Please try a rebase and see if the conflict can be solved.

**Comment by jamesgeorge007** [comment]
@tengqm I had made the forks even :+1:

**Comment by stewart-yu** [comment]
not familar with `css`, but change seems resonable

**Comment by jamesgeorge007** [comment]
Any updates?

**Pull request closed without merging**
