### PR TITLE
Fix broken link of content/ja/docs/contribute/_index.md

### PR DESCRIPTION
**Pull request by EigoOda**
`tag: release-1.26` has [content/ja/docs/contribute/new-content/overview.md](https://github.com/kubernetes/website/blob/release-1.26/content/ja/docs/contribute/new-content/overview.md),
But `tag: main` has no [content/ja/docs/contribute/new-content/overview.md](https://github.com/kubernetes/website/blob/main/content/ja/docs/contribute/new-content/overview.md)

Close:https://github.com/kubernetes/website/issues/44645

### CODE REVIEW

**Comment by atoato88** [comment]
The target page on deploy preveiw site:
- https://deploy-preview-44652--kubernetes-io-main-staging.netlify.app/ja/docs/contribute/

**Comment by atoato88** [comment]
/lgtm
Thank you for creating this PR.
Nice catch!

**Comment by EigoOda** [comment]
@atoato88 
I resolved the conflict, so can you review again, please?

**Comment by atoato88** [comment]
/lgtm

Sorry for the late review.

**Pull request merged**
