### PR TITLE
[zh-cn] sync self-subject-review api

### PR DESCRIPTION
**Pull request by my-git9**
content/zh-cn/docs/reference/kubernetes-api/authorization-resources/role-v1.md
content/zh-cn/docs/reference/kubernetes-api/authentication-resources/self-subject-review-v1beta1.md -> content/zh-cn/docs/reference/kubernetes-api/authentication-resources/self-subject-review-v1.md

### CODE REVIEW

**Comment by tengqm** [comment]
This combination is weird? Why are you syncing role-v1 together with SelfSubjectReview?
It looks like the v1beta1 version of SelfSubjectReview has graduated to v1.
If you sync that two different versions of the same file in a single PR, you can save
a lot of efforts in translation. But if you are removing the v1beta1 version in this PR,
a later sync for the v1 version would need to work from scratch.

**Comment by my-git9** [comment]
> This combination is weird? Why are you syncing role-v1 together with SelfSubjectReview? It looks like the v1beta1 version of SelfSubjectReview has graduated to v1. If you sync that two different versions of the same file in a single PR, you can save a lot of efforts in translation. But if you are removing the v1beta1 version in this PR, a later sync for the v1 version would need to work from scratch.

OK, I will sync v1 version in this PR later~

**Review by ydFu — APPROVED** [review]
/approve 
It is sync.

**Pull request merged**
