### PR TITLE
Grammatical improvements in nodes.md

### PR DESCRIPTION
**Pull request by nitinpuranik**
Improved sentences grammatically and corrected minor errors.

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hey @nitinpuranik, please sign the CLA so that we can review this further.

**Review by Arhell — COMMENTED** [review]
CLA info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Sea-n** [comment]
Hey @nitinpuranik,

You have to sign the CLA so that we can review this PR and move forward.
Just click on the red NOT COVERED button in the first comment.

After signing the CLA, you may use this command to refresh the status:
/easycla

If you have any problem, please take a look at [the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Comment by Sea-n** [comment]
Hey @nitinpuranik,

Since you didn't sign the CLA agreement, we cannot review this PR and move forward.

I'm closing this PR now, but feel free to `/reopen` once you are ready to sign CLA. ([tutorial here](https://git.k8s.io/community/CLA.md))
/close

**Pull request closed without merging**
