### PR TITLE
Update configure-upgrade-etcd.md

### PR DESCRIPTION
**Pull request by taherbohari**
Updated etcd port number from invalid 12380 to valid 2380.

### CODE REVIEW

**Comment by DanyC97** [comment]
thanks for the PR @taherbohari 
/lgtm

**Comment by cody-clark** [comment]
Attempting to redeploy on Netlify

**Comment by cody-clark** [comment]
Redeploying worked!

Preview: https://deploy-preview-13505--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/configure-upgrade-etcd/#replacing-a-failed-etcd-member

/approve

**Pull request merged**
