### PR TITLE
[zh] fix contenst for zh-cn/2023-01-05-retroactive-default-storage-class.md

### PR DESCRIPTION
**Pull request by yanggangtony**
Like [en fix docs](https://github.com/kubernetes/website/pull/40469).
raise a separate PR for the 'cn'..

### CODE REVIEW

**Review by Zhuzhenghao — COMMENTED** [review]
Please sync the English block at the same time for future changes tracking.

**Comment by Zhuzhenghao** [comment]
/retitle fix contenst for zh-cn/2023-01-05-retroactive-default-storage-class.md

**Comment by Zhuzhenghao** [comment]
/retitle [zh] fix contenst for zh-cn/2023-01-05-retroactive-default-storage-class.md

**Comment by yanggangtony** [comment]
mistake the md 's review.. 
Its not the view on github , but on the online-docs web . 
close it..

**Pull request closed without merging**
