### PR TITLE
flow control metrics: switch to snake_case for labels

### PR DESCRIPTION
**Pull request by adtac**
Copy of https://github.com/kubernetes/website/pull/24905 but this time targetting the `dev-1.20` branch.

/cc @lavalamp @sftim 
/sig api-machinery
/sig instrumentation

### CODE REVIEW

**Comment by lavalamp** [comment]
/lgtm

Tech LGTM

**Review by irvifa — COMMENTED** [review]
/approve

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Pull request merged**
