### PR TITLE
Add glossary entry for disruption

### PR DESCRIPTION
**Pull request by sftim**
Relevant to #5993

Add a glossary entry to define “disruption”
[Preview](https://deploy-preview-16292--kubernetes-io-master-staging.netlify.com/docs/reference/glossary/?all=true#term-disruption)

### CODE REVIEW

**Comment by steveperry-53** [comment]
/approve
@sftim One suggestion: Change "A disruption will have consequences" to "A disruption has consequences".

**Comment by sftim** [comment]
Amended.

**Pull request merged**
