### PR TITLE
Matching reference page as its language

### PR DESCRIPTION
**Pull request by dangen-effy**
Update href value

### CODE REVIEW

**Comment by dangen-effy** [comment]
I signed it

**Comment by pjhwa** [comment]
@dangen-effy Thank you for your contribution!!! 👍 

/lgtm

**Comment by pjhwa** [comment]
@dangen-effy Can you re-check your CLA sign?

**Comment by pjhwa** [comment]
/lgtm cancel

One thing, please change the target branch for this PR to dev-1.19-ko.2.

**Comment by dangen-effy** [comment]
@pjhwa i verified CLA signup email. Also checked my GitHub's primary email account, they are same.

Then i commented `I signed it` here.

k8s-ci-bot may check my CLA status again soon...

**Comment by pjhwa** [comment]
@dangen-effy In the GitHub Settings > Emails, is your email address "Visible in emails"?

**Comment by dangen-effy** [comment]
@pjhwa I missed it! it was invisible. Thanks.

**Comment by dangen-effy** [comment]
I signed it

**Comment by pjhwa** [comment]
@dangen-effy Then, please rebase the target branch from master to dev-1.19-ko.2. Thanks. :-)

**Comment by pjhwa** [comment]
@dangen-effy During the rebase target branch, GitHub added some other huge number of commits to this PR. 
So, could you open a new PR for this issue? (you can close this PR)

**Comment by dangen-effy** [comment]
@pjhwa I Re-opened PR [here](https://github.com/kubernetes/website/pull/24001) :)

**Pull request closed without merging**
