### PR TITLE
Fix typo in k8s.io/ko/docs/contribute/new-content/new-content/

### PR DESCRIPTION
**Pull request by jihoon-seo**
From #21970

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Direct link to the change preview: https://deploy-preview-21975--k8s-dev-ko.netlify.app/ko/docs/contribute/new-content/new-content/#%EC%BB%A4%EB%B0%8B-%EC%8A%A4%EC%BF%BC%EC%8B%9C%ED%95%98%EA%B8%B0

**Comment by pjhwa** [comment]
@jihoon-seo 컨트리뷰션 감사합니다!

/lgtm

**Comment by gochist** [comment]
@jihoon-seo 감사합니다!
/approve

**Pull request merged**
