### PR TITLE
update README-ko.md

### PR DESCRIPTION
**Pull request by lovebaby979**

### CODE REVIEW

**Comment by kbhawkey** [comment]
Reaching out to the `ko` localization team for a review:
/cc @kubernetes/sig-docs-ko-reviews

**Comment by seokho-son** [comment]
This PR fixes an outdated link in README-ko.md.
The title of the link needs to be updated. However, Korean l10n team would like to fix this in another PR.
So, for this PR.
/lgtm

**Comment by kbhawkey** [comment]
Thanks for the review @seokho-son 
/approve

**Pull request merged**
