### PR TITLE
docs: fix chinese typo in service.md

### PR DESCRIPTION
**Pull request by smartczy**
This PR is going to fix typo problem in chinese.
update service.md for zh.
/language zh

### CODE REVIEW

**Comment by smartczy** [comment]
I signed it

**Comment by tengqm** [comment]
@smartczy pls check if you need to reset the author info ... https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by smartczy** [comment]
> @smartczy pls check if you need to reset the author info ... https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

I have reset the author info. But the problem is I didn't get the email agreement to sign and I can't find the way to make linxufoudation.org resent cla email to me. @tengqm

**Comment by smartczy** [comment]
close this pr because of CLA problem

**Pull request closed without merging**
