### PR TITLE
Release interview blog post for 1.16

### PR DESCRIPTION
**Pull request by craigbox**
Part 3, after

* https://kubernetes.io/blog/2018/07/16/how-the-sausage-is-made-the-kubernetes-1.11-release-interview-from-the-kubernetes-podcast/
* https://kubernetes.io/blog/2019/05/13/cat-shirts-and-groundhog-day-the-kubernetes-1.14-release-interview/

### CODE REVIEW

**Comment by mrbobbytables** [comment]
lgtm from a tech perspective 👍 
/assign @kbarnard10

**Comment by craigbox** [comment]
This isn't showing up on the blog even though it was merged?

/cc @zacharysarah

**Comment by zacharysarah** [comment]
@craigbox Thanks for raising visibility. It’s due to an unrelated issue; it’s easy to fix, so give us a couple of hours to get things working again. Thanks in advance for your patience.

**Comment by craigbox** [comment]
np. #17973 updates the date on the post to today.


________________________________

**Comment by zacharysarah** [comment]
@craigbox The fix is in, the post is up. I'll review #17973 shortly.

**Pull request merged**
