### PR TITLE
Update certificates.md

### PR DESCRIPTION
**Pull request by sagrityanin**
Wrong bash command

the curl command is specified twice in the bash command
"curl -LO curl -LO https://dl.k8s.io/easy-rsa/easy-rsa.tar.gz"

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @sagrityanin, Please sigh EasyCLA first.

**Comment by shurup** [comment]
Good catch, thank you! This typo seems to be affecting Russian localisation only and was introduced in #40815. After the CLA is signed, I'm happy to approve this change.

**Review by Arhell — COMMENTED** [review]
Yes, my bad
/lgtm

**Comment by reylejano** [comment]
Thank you for the fix
/approve

**Pull request merged**
