### PR TITLE
FIX : Learn Kubernetes Basics button difficult to read when hovered

### LINKED ISSUE #43396: Learn Kubernetes Basics button difficult to read when hovered
**This is a Bug Report**

**Problem:** On the home page of website I found that the Learn Kubernetes Basics button needs to be edited as when we hover upon it the words are not clearly visible.

**Proposed Solution:** We can make this button same as the buttons in other pages of the website like for example, under the documentation tab we have View Concepts and View Tutorial buttons.

**Page to Update:**
https://kubernetes.io/

I would like to work upon this issue if you assign it to me. Thankyou.

### PR DESCRIPTION
**Pull request by Sakhi29**
fixes #43396 
I have made necessary hovering and transition changes to the button.
image
On hover:
image

@thisisharrsh kindly review my PR.

### CODE REVIEW

**Review by aj11anuj — CHANGES_REQUESTED** [review]
1. You are making changes to 2 different files, and i don't think removing that json file has anything to do with this Issue and PR. So, please remove that deletion of json file from this PR.
2. These changes are working fine for "Learn Kubernetes basics" button, but it is causing problem to other blue buttons of docs/home page when they are hovered.

Screenshot_2023-10-10-22-55-05-613_com android chrome
Screenshot_2023-10-10-22-55-19-072_com android chrome

**Comment by Sakhi29** [comment]
Okay, I'll fix this.

**Review by Gauravpadam — CHANGES_REQUESTED** [review]
We need to make some changes before this can be merged:

- A JSON file is modified, We can revert that
- I would target the button with a specific `id` attribute, Try modifying the custom assets rather the base assets
- Try to keep the hover effect consistent as other buttons

**Comment by thisisharrsh** [comment]
Deploy preview: https://deploy-preview-43422--kubernetes-io-main-staging.netlify.app/

**Comment by Sakhi29** [comment]
@thisisharrsh fixed necessary changes. Please review it.

**Review by aj11anuj — COMMENTED** [review]
You have made some mistakes while commiting to this PR, and now this PR is ruined with unnecessary commits. It's Ok, learn  and practice git more and remove these unnecessary commits from this PR. Feel free to ask here or in [K8s slack channel](https://kubernetes.slack.com/?redir=%2Fmessages%2Fsig-docs) if you face any issue.

**Comment by Sakhi29** [comment]
Can I send a new non conflicting PR?

**Comment by aj11anuj** [comment]
Ya, surely you can but if you will do that then you will still face git related problems later on. So, it's better to learn git properly in this PR. Don't worry about its merge, just focus on your learning.

**Comment by thisisharrsh** [comment]
> @thisisharrsh fixed necessary changes. Please review it.

Hi @Sakhi29, This PR has fixed the issue that we are addressing, but there are a lot of new issues that originated from the commits we have made.
As @aj11anuj  has suggested that this is full of unnecessary commits, it will be better if we could close this PR and try to fix the issue on a new one.

**Comment by Sakhi29** [comment]
Okay, then I will close this PR and send a new one, if it is okay with you.

**Comment by thisisharrsh** [comment]
> Okay, then I will close this PR and send a new one, if it is okay with you.

Yes, you can.

**Pull request closed without merging**
