### PR TITLE
add @bells17 as sig-docs-ja reviewer

### PR DESCRIPTION
**Pull request by nasa9084**
add @bells17 as a new member of sig-docs-ja reviewer!

Ref: 
https://github.com/kubernetes/website/pulls?q=is%3Apr++is%3Aclosed+bells17+label%3Alanguage%2Fja+

### CODE REVIEW

**Comment by inductor** [comment]
+1

He's been working hard!

**Comment by sftim** [comment]
Looks like this PR introduced a commit message that is problematic for sync PR https://github.com/kubernetes/website/pull/21604

**Comment by sftim** [comment]
I'm not sure what invalid thing happened TBH.

**Comment by nasa9084** [comment]
the bot is saying the commit made by this PR contains `@` but seems not, `@` is only in PR title so (by my eyes) no problem, maybe?
it seems strange for me...

**Comment by kbhawkey** [comment]
> 
> 
> I'm not sure what invalid thing happened TBH.

I wonder if "closed" was picked up in the commit message?
Why is this problem flagged later on (subsequent merge) instead of at the time of PR creation?

**Comment by nasa9084** [comment]
ah... maybe this merge commit?
https://github.com/kubernetes/website/commit/53db74cd4604ac73a7d3e900231b36ff51d90be5
this contains `@` from PR title in commit message of body?
at the time of merge, my commit is not containing `@` so no problem, but merge commit contains `@` so causing problem on subsequent merge

**Comment by nasa9084** [comment]
I won't contains `@` in the future but I'm not sure what to do in this time...

**Comment by sftim** [comment]
So it's the PR title?
Prow is happy to merge the PR, only to find that the merged PR breaks its own guidelines.

**Comment by inductor** [comment]
This looks tricky

**Comment by zacharysarah** [comment]
It probably won't work, but it may be worth trying:

/retitle add bells17 as sig-docs-ja reviewer

**Pull request merged**
