### PR TITLE
Adding the FQDN for DockerHub to the example.

### PR DESCRIPTION
**Pull request by dddigitalglobe**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.9 Features: set Milestone to `1.9` and Base Branch to `release-1.9`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: Please check the “Allow edits from maintainers” box (see image below) to
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.
>
> NOTE: After opening the PR, please *un-check and re-check* the "Allow edits from maintainers" box. This is a temporary workaround to address a known issue with GitHub.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6254)

### CODE REVIEW

**Comment by dddigitalglobe** [comment]
adding a little info...

**Comment by chenopis** [comment]
@dddigitalglobe FYI, the Travis CI error has been fixed. Please rebase or update the branch. Thx!

**Comment by steveperry-53** [comment]
@vishh @Random-Liu @tallclair Can one of you take a look at this small change? Is https://index.docker.io/v1/ a fully qualified domain name (FQDN)? Or is it a domain name plus path? And are the docs correct in saying that <your-registry-server> should be an FQDN? Thanks.

**Comment by steveperry-53** [comment]
ping @vishh @Random-Liu @tallclair

**Comment by steveperry-53** [comment]
@dddigitalglobe Please sign the CLA.

**Comment by heckj** [comment]
@dddigitalglobe need you to sign the CLA for this to be merged...

**Comment by chenopis** [comment]
This looks stale.

**Pull request closed without merging**
