### PR TITLE
New slack icon

### PR DESCRIPTION
**Pull request by Harshagarwal19**
Modified the old slack icon.

### CODE REVIEW

**Comment by Harshagarwal19** [comment]
@jimangel reason behind docker version update was issue number
https://github.com/kubernetes/kubeadm/issues/1372

**Comment by kbhawkey** [comment]
Hello @Harshagarwal19, is this the only page where the icon is used?
https://deploy-preview-12438--kubernetes-io-master-staging.netlify.com/community/

Probably a separate issue, but the last two icons appear dropped or lower than the first two icons.

**Comment by ryanmcginnis** [comment]
thanks for updating the image.

/lgtm

**Comment by neolit123** [comment]
@jimangel 
this PR merged a change that we need to revert (modified docker)
https://github.com/kubernetes/website/pull/12438/files#diff-9b5d940e9fc0e3fab81c81aad0dc300fR23

it was decided to keep 18.06 as the default and add 18.09 at the end of the list.
https://github.com/kubernetes/kubeadm/issues/1372

> Version 18.06 is recommended, but 1.11, 1.12, 1.13, 17.03, 18.09 are known to work as well.

@Harshagarwal19 do you want to send a new PR for that?

**Comment by Harshagarwal19** [comment]
@jimangel Yes I will do that

**Comment by neolit123** [comment]
@Harshagarwal19 thanks. please ping me on the PR.

**Comment by daminisatya** [comment]
`Probably a separate issue, but the last two icons appear dropped or lower than the first two icons.`

@kbhawkey I added a fix for this over here :) It's just an alignment issue. https://github.com/kubernetes/website/pull/12507

**Pull request merged**
