### PR TITLE
Remove reconfig node kubelet live cluster page

### LINKED ISSUE #31585: Remove page “Reconfigure a Node's Kubelet in a Live Cluster”
**This is a Cleanup Request**

**What would you like to be removed**
Remove https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/

**Why is this needed**
v1.24 of Kubernetes will remove the dynamic kubelet config feature (deprecated since Kubernetes v1.22)

**Comments**
/sig node
/language en
/milestone 1.24

### PR DESCRIPTION
**Pull request by AndiZ23**
Resolves #31585.
* Removed https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/ page from the English pages
* Cleaned up all referring links to the affected page.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@AndiZ23 Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: https://git.k8s.io/community/CLA.md

**Comment by AndiZ23** [comment]
@dipesh-rawat Thanks for the reply! I've submitted the CLA form and the request has been sent to my org's CLA manager. Now it's pending their approval.

**Review by Arhell — COMMENTED** [review]
to check `/easycla`

**Comment by sftim** [comment]
Per https://github.com/kubernetes/website/pull/41854#issuecomment-1618461504, please sign the CLA @AndiZ23

**Comment by reylejano** [comment]
Hi @AndiZ23 ,
This PR is failing the CLA check and has a merge conflict so it requires rebase
It's been sometime since this PR saw traction so I'm closing this PR
When you have signed the CLA and ready to rebase, you can reopen this PR with a `/reopen` in a comment
/close

**Pull request closed without merging**
