### PR TITLE
Merge master into dev 1.21 - 1/29/21

### PR DESCRIPTION
**Pull request by PI-Victor**
Merge master into dev-1.21 to keep in sync - SIG-Release 1.21 Docs team 1/29/21

/cc @reylejano  @mvortizr @tengqm @ChandaniM123

### CODE REVIEW

**Comment by reylejano** [comment]
Looks like bbc1194 was resolved by commit 74ecaf1 in the same PR https://github.com/kubernetes/website/pull/26216

**Comment by reylejano** [comment]
Preview: https://deploy-preview-26292--kubernetes-io-vnext-staging.netlify.app/

/lgtm

**Comment by jimangel** [comment]
/approve
🎉

**Comment by reylejano** [comment]
/assign @parispittman 
Hi @parispittman, it looks like we need an approval from someone in the steering committee. This PR synchronizes the k/website `dev-1.21` branch with k/website `master`. During the release, PRs continue to merge into `master` and we synchronize the `dev-1.21` branch weekly until the release of 1.21 (target date of April 8) to avoid merge conflicts on release day.

**Comment by PI-Victor** [comment]
> /assign @parispittman
> Hi @parispittman, it looks like we need an approval from someone in the steering committee. This PR synchronizes the k/website `dev-1.21` branch with k/website `master`. During the release, PRs continue to merge into `master` and we synchronize the `dev-1.21` branch weekly until the release of 1.21 (target date of April 8) to avoid merge conflicts on release day.

@parispittman i believe this is because of changes in `data/announcements/scheduled.yaml`. 

thank you!

**Review by ydFu — APPROVED** [review]

**Comment by nikhita** [comment]
> Hi @parispittman, it looks like we need an approval from someone in the steering committee. This PR synchronizes the k/website dev-1.21 branch with k/website master.

Approving for the steering committee.
/approve

**Pull request merged**
