### PR TITLE
[ja] add docs for leases

### LINKED ISSUE #38837: [ja] Translate concepts/architecture/leases into Japanese
**This is a Feature Request**

**What would you like to be added**

Translate https://kubernetes.io/docs/concepts/architecture/leases/ into Japanese

**Why is this needed**

**Comments**

/language ja
/assign

### PR DESCRIPTION
**Pull request by FeLvi-zzz**
Add desrtiption of leases.
https://kubernetes.io/docs/concepts/architecture/leases/

close #38837

### CODE REVIEW

**Review by t-inu — COMMENTED** [review]
I reviewed and left comments.

**Comment by atoato88** [comment]
I have no comment as a reviewer. :smiley: 
Please see the comments from other reviewers.

**Comment by atoato88** [comment]
/lgtm
Thank you for updating.

**Comment by FeLvi-zzz** [comment]
/assign @nasa9084 
Please check them when you have the time.

**Review by nasa9084 — COMMENTED** [review]
/approve
Thank you~

**Pull request merged**
