### PR TITLE
[WIP] New reference docs for kubectl

### PR DESCRIPTION
**Pull request by tengqm**
This is collection of kubectl reference docs generated in the same way
as we do for kube-apiserver, kubelet, kubeadm etc. This is different
from the way we do today for kubectl (see #9080). Sending this to get
comments from reviewers.

### CODE REVIEW

**Comment by tengqm** [comment]
@steveperry-53 This is the other option (may be your preferred one?). Let's see if this approach works.

**Comment by steveperry-53** [comment]
@tengqm Thanks for doing this. It will be good to have this for discussion.

**Comment by steveperry-53** [comment]
@mistyhacks This PR is for preview and discussion purposes only.

**Comment by zacharysarah** [comment]
@tengqm @steveperry-53 👋 Please feel free to reopen this PR if it's still relevant to preview/discussion.

**Comment by tfogo** [comment]
@tengqm Awesome! Is your proposal that we then remove this version of the kubectl documentation? https://5b232a7711b73b3d64fc79b6--kubernetes-io-vnext-staging.netlify.com/docs/reference/generated/kubectl/kubectl-commands

**Comment by tengqm** [comment]
@tfogo Yes.

**Comment by tfogo** [comment]
Cool. So where are we at with regards to a decision on this? It looks like this was discussed at the sig meeting on June 19, but there wasn't any clear outcome.

**Comment by zacharysarah** [comment]
@tengqm 👋 Please feel free to reopen this PR when you're ready to address feedback. ☝️

**Pull request closed without merging**
