### PR TITLE
Move DNS debugging page back to cluster administration

### PR DESCRIPTION
**Pull request by tengqm**
DNS resolution is a task in the control plane rather than application layer.

closes: #21930

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-21933--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by kbhawkey** [comment]
Hi @tengqm .
This page is reverting this change?
https://github.com/kubernetes/website/pull/21166/

**Comment by tengqm** [comment]
@kbhawkey Partially revert. It is not reverting the tweaking to the text. It is moving the page back to the directory to which it belongs.

**Comment by kbhawkey** [comment]
I just read through the comments in issue #21930.
Here are the current pages:
https://kubernetes.io/docs/tasks/access-application-cluster/
https://kubernetes.io/docs/tasks/administer-cluster/

I suggest to look at the current pages under each folder and decide if the folders help categorize the task pages (for the reader). Do most pages under `administer-cluster` focus on administration?
What kind of tasks are represented by `access-application-cluster`? I find this name less obvious.

**Comment by tengqm** [comment]
@kbhawkey Indeed. For example, the page https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/ doesn't look like an administration task, and it should go to the other directory.

**Comment by sftim** [comment]
I'd probably group cluster networking tasks and DNS tasks into one section. How does that sound?

**Comment by kbhawkey** [comment]
Going forward, I suggest to:
- move this page to administer_cluster so that DNS pages are located under the same folder and the failing links are corrected.
- log an issue to investigate whether there should be a new folder created specifically for DNS and cluster networking tasks
- log an issue to possibly move the other DNS task page from `tasks/access-application-cluster`

/lgtm

**Comment by kbhawkey** [comment]
If there is still more to discuss, feel free to hold this PR.

**Comment by tengqm** [comment]
@kbhawkey @sftim Consolidating networking and DNS into a subgroup is a good idea. Let's ensure we add redirect entries in such PRs. We are seeing some broken links from some "downstream" projects.

**Comment by kbhawkey** [comment]
Is this good to move forward and log an issue to create a new folder/sub-folder?

**Comment by sftim** [comment]
If I get time I will also check for redirects that now need to be undone.

**Pull request merged**
