### PR TITLE
Update broken links to Ansible in kubespray.md

### PR DESCRIPTION
**Pull request by marekhanus**

### CODE REVIEW

**Comment by atoato88** [comment]
@marekhanus 
This PR includes multiple language files. 
We limits fixes to a single language per PR, please [see here](https://kubernetes.io/docs/contribute/new-content/overview/#languages-per-pr).
And also see [this PR which is in same situation](https://github.com/kubernetes/website/pull/27139#pullrequestreview-619146137).

**Comment by marekhanus** [comment]
@atoato88 Fixed.

**Comment by atoato88** [comment]
@marekhanus 
Thank you to update.
I remove language tag except for `en` because tihs PR includes `en` contents only.

/remove-language fr
/remove-language ja
/remove-language ko
/remove-language zh

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-27473--kubernetes-io-master-staging.netlify.app/docs/setup/production-environment/tools/kubespray/#2-5-compose-an-inventory-file

**Comment by kbhawkey** [comment]
Thanks @marekhanus .
/lgtm

**Pull request merged**
