### PR TITLE
KubeCon Docs Sprint: Update Weights for reference/k8s-api/cluster-res…

### PR DESCRIPTION
**Pull request by cailynse**
This PR updates the weights to be spaced by 10 in case of added pages in the future.

Note: This PR changes auto-generated pages, we will also be updating the generator to weight pages by 10s here: https://github.com/kubernetes/website/issues/37486
Related # https://github.com/kubernetes/website/issues/35093

### CODE REVIEW

**Comment by sftim** [comment]
@cailynse, could you mention in the PR description about why this update to an auto-generated page is OK?

**Comment by sftim** [comment]
/hold
I'd prefer to have the PR description explain why we're updating auto-generated content; normally we'd update the generator instead.

**Comment by cailynse** [comment]
@sftim - Are we ok to remove the hold now that the description is updated?

**Comment by sftim** [comment]
We should hold this until either:
- https://github.com/kubernetes/website/issues/37486 is fixed
- https://github.com/kubernetes/website/issues/37486 is not fixed, but we're confident a fix is imminent.

The way I see it, a delay in merging _this_ PR shouldn't be too much of a chore. It's the right change.

**Comment by kbhawkey** [comment]
👋 @cailynse .
Has the generator been updated to correct the weights of the pages?
I'll close this pull request, but you can reopen if you have questions or want to continue to work on the changes.

/close

**Pull request closed without merging**
