### PR TITLE
[ja] Translate setup/best-practices/cluster-large/ into japanese

### LINKED ISSUE #30352: [ja] Translate setup/best-practices/cluster-large/ into Japanese
**This is a Feature Request**

**What would you like to be added**

Translate [setup/best-practices/cluster-large/](https://kubernetes.io/ja/docs/setup/best-practices/cluster-large/) into Japanese.

**Why is this needed**

This page has not been translated.

**Comments**

/language ja
/assign

### PR DESCRIPTION
**Pull request by moguraion**
This PR setup/best-practices/cluster-large and reference/glossary/addons into Japanese.
The later is refered by the former.

/close #30352

### CODE REVIEW

**Comment by reylejano** [comment]
/retitle [ja] Translate setup/best-practices/cluster-large/ into japanese

**Comment by nuka137** [comment]
@moguraion 

#30352 has been assigned to me and almost finished the first work.
https://github.com/nuka137/website/blob/pr-1/content/ja/docs/setup/best-practices/cluster-large.md

But I found this PR.
Should I discard my change?

**Comment by moguraion** [comment]
@nuka137 
Give priority to yours.
Thank you for teaching. Please close this PR.

**Comment by nuka137** [comment]
@moguraion 

Thanks for your kind consideration.

Because of the lack of auth, I could not close your PR.
I think you can close this PR by yourself with clicking `Close pull request` button next to `Comment` button.

**Comment by moguraion** [comment]
r

**Pull request closed without merging**
