### PR TITLE
Fix spelling mistake in kube scheduler

### PR DESCRIPTION
**Pull request by alexis974**
This PR aims to fix a spelling mistake in the Kubernetes Scheduler documentation.

An 's' was missing. I checked the rest of the file and did not find any other spelling mistake. No broken link found.

Link to doc: https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/

### CODE REVIEW

**Review by Princesso — COMMENTED** [review]
Hi @alexis974, thanks for your contribution. 
We usually consider PRs like this one [trivial edits](https://kubernetes.io/docs/contribute/review/reviewing-prs/#other). 
Could you go through the page to check if there are any other issues you can fix on this page?

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by alexis974** [comment]
> Hi @alexis974, thanks for your contribution. We usually consider PRs like this one [trivial edits](https://kubernetes.io/docs/contribute/review/reviewing-prs/#other). Could you go through the page to check if there are any other issues you can fix on this page?

please take another look @Princesso

**Comment by alexis974** [comment]
Hello @kbhawkey, can you take a look ?

**Comment by stmcginnis** [comment]
/lgtm

Great clean up - thanks!

**Review by kumarankit999 — COMMENTED** [review]
lgtm!

**Review by divya-mohan0209 — COMMENTED** [review]
Thank you @alexis974 for these changes!
/approve

**Pull request merged**
