### PR TITLE
windows docs updates for 1.14

### PR DESCRIPTION
**Pull request by michmike**
these are additional windows node updates for 1.14 release

### CODE REVIEW

**Comment by cody-clark** [comment]
Preview: https://5c9123ec0f7e060008a039d6--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/windows/#storage

**Comment by michmike** [comment]
@kbhawkey PTAL at the updates for a TOC :)
https://5c913e56648ab800082f5a51--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/windows/

one question i had is - can you only do one level of TOC, and not sub-levels?

**Comment by michmike** [comment]
@jimangel  can you please review?

**Comment by michmike** [comment]
what's missing now

**Comment by craiglpeters** [comment]
/lgtm

TODO 
1 Figure out how to fix numbering that is munged because '{{ < note > }}' tags don't seem to nest properly, and 
2 Finishing up recoding the tables

**Comment by kbhawkey** [comment]
> 
> 
> @kbhawkey PTAL at the updates for a TOC :)
> https://5c913e56648ab800082f5a51--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/windows/
> 
> one question i had is - can you only do one level of TOC, and not sub-levels?

@michmike, Has this page been updated to a new location?
If possible, you could break down the single page to multiple pages? There is a lot of information here 😃  .
I believe the top level toc is created from the level 2 headers. Could you make a list of links in a section that references other sections on the page?

**Comment by michmike** [comment]
> > @kbhawkey PTAL at the updates for a TOC :)
> > https://5c913e56648ab800082f5a51--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/windows/
> > one question i had is - can you only do one level of TOC, and not sub-levels?
> 
> @michmike, Has this page been updated to a new location?
> If possible, you could break down the single page to multiple pages? There is a lot of information here 😃 .
> I believe the top level toc is created from the level 2 headers. Could you make a list of links in a section that references other sections on the page?

yes, we moved this to the new location (you can see that in the previews from netlify)
https://5c914f680410ed000aeebc2e--kubernetes-io-vnext-staging.netlify.com/docs/setup/windows/add-windows-nodes/

sure, we can see about breaking this down :( (more work)

**Comment by kbhawkey** [comment]
> 
> 
> > > @kbhawkey PTAL at the updates for a TOC :)
> > > https://5c913e56648ab800082f5a51--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/windows/
> > > one question i had is - can you only do one level of TOC, and not sub-levels?
> > 
> > 
> > @michmike, Has this page been updated to a new location?
> > If possible, you could break down the single page to multiple pages? There is a lot of information here 😃 .
> > I believe the top level toc is created from the level 2 headers. Could you make a list of links in a section that references other sections on the page?
> 
> yes, we moved this to the new location (you can see that in the previews from netlify)
> https://5c914f680410ed000aeebc2e--kubernetes-io-vnext-staging.netlify.com/docs/setup/windows/add-windows-nodes/
> 
> sure, we can see about breaking this down :( (more work)

Looks good 👍

**Comment by kbhawkey** [comment]
> 
> 
> /lgtm
> 
> TODO
> 1 Figure out how to fix numbering that is munged because '{{ < note > }}' tags don't seem to nest properly, and
What line(s) are causing trouble? You probably need to add/subtract a line or make further indentations.


> 2 Finishing up recoding the tables

**Comment by cody-clark** [comment]
@craiglpeters 

This [style guide entry](https://kubernetes.io/docs/contribute/style/style-guide/#common-shortcode-issues) might help with the ordered lists

**Comment by michmike** [comment]
> > > > @kbhawkey PTAL at the updates for a TOC :)
> > > > https://5c913e56648ab800082f5a51--kubernetes-io-vnext-staging.netlify.com/docs/getting-started-guides/windows/
> > > > one question i had is - can you only do one level of TOC, and not sub-levels?
> > > 
> > > 
> > > @michmike, Has this page been updated to a new location?
> > > If possible, you could break down the single page to multiple pages? There is a lot of information here 😃 .
> > > I believe the top level toc is created from the level 2 headers. Could you make a list of links in a section that references other sections on the page?
> > 
> > 
> > yes, we moved this to the new location (you can see that in the previews from netlify)
> > https://5c914f680410ed000aeebc2e--kubernetes-io-vnext-staging.netlify.com/docs/setup/windows/add-windows-nodes/
> > sure, we can see about breaking this down :( (more work)
> 
> Looks good 👍

@kbhawkey
PTAL now. split into 3 pages
https://5c9168ebe521720009d58e1e--kubernetes-io-vnext-staging.netlify.com/docs/setup/windows/intro-windows-in-kubernetes/

**Comment by cody-clark** [comment]
Previews:
[Intro to Windows support in Kubernetes](https://deploy-preview-13279--kubernetes-io-vnext-staging.netlify.com/docs/setup/windows/intro-windows-in-kubernetes/)
[Guide for scheduling Windows containers in Kubernetes](https://deploy-preview-13279--kubernetes-io-vnext-staging.netlify.com/docs/setup/windows/user-guide-windows-containers/)
[Guide for adding Windows Nodes in Kubernetes](https://deploy-preview-13279--kubernetes-io-vnext-staging.netlify.com/docs/setup/windows/user-guide-windows-nodes/)

**Comment by zacharysarah** [comment]
@michmike @craiglpeters Thank you for all of your work here. ✨🌟:sparkles:
 

Thanks for switching the content path and for adjusting weights. I think readers will be much happier with the discoverability for this launch--and it's a great start from which to iterate. 

@kbhawkey Thank you for your reviews here. On point! 🎯 

@cody-clark Thanks for wrangling. 💛 

/lgtm

Leaving `/approve` for @jimangel 👋

**Comment by kbhawkey** [comment]
Great work! 👍 😃

**Comment by michmike** [comment]
tables have been converted from HTML to MD. thanks

**Comment by jimangel** [comment]
Really great work here @michmike @craiglpeters!

@kbhawkey @zacharysarah @cody-clark thanks for helping with review!

/lgtm
/approve

**Pull request merged**
