### PR TITLE
Fix description of RWO

### PR DESCRIPTION
**Pull request by kfox1111**
Fix the description of the access pattern restrictions of the newly created PVC in the example.

### CODE REVIEW

**Comment by sftim** [comment]
:thought_balloon: I wonder if it'd help to switch the example to use the `ReadWriteOncePod` access mode.

**Comment by kfox1111** [comment]
> thought_balloon I wonder if it'd help to switch the example to use the `ReadWriteOncePod` access mode.

I kind of wondered that too. Though ReadWriteOnce has more compatibility still then ReadWriteOncePod I think?

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Pull request merged**
