### PR TITLE
Add "CLA" to improve SEO for this page

### PR DESCRIPTION
**Pull request by rolfedh**
I had trouble finding this page when Googled "CNCF CLA". Hopefully adding CLA within the link text with improve the ranking of this page in search results.

### CODE REVIEW

**Comment by sftim** [comment]
@rolfedh actually we probably don't want this to be the top match! Instead, let's try to boost https://www.kubernetes.dev/docs/ or a page within it - maybe linking there?

**Comment by rolfedh** [comment]
> @rolfedh actually we probably don't want this to be the top match! Instead, let's try to boost https://www.kubernetes.dev/docs/ or a page within it - maybe linking there?

Good point. How setting the initialism in about both places, so the change doesn't favor one topic over the other?

**Comment by sftim** [comment]
Eventually we'd move the whole contributing-to-the-website section over to https://k8s.dev/ - the blocker is that https://k8s.dev/ is currently just in English. So I definitely want to favor https://www.k8s.dev/ in terms of any search engine ranking outcome.

My take on this is that we should hyperlink to https://www.k8s.dev/docs/contributor-cheatsheet/#submitting-a-contribution and really help readers discover that there's a whole section on CLA signing help ready for them to read if they want.

**Comment by rolfedh** [comment]
Thanks. We should probably close this PR, then.

**Pull request closed without merging**
