### PR TITLE
Clean up case study images

### LINKED ISSUE #22086: Clean up case study images
Umbrella issue: https://github.com/kubernetes/website/issues/22024

This is a **big** issue, but should be relatively easy to do using search-and-replace.

## Context

There are a number of images in the `/static/images/` directory that are used on case study pages. On the whole, these are prefixed with `CaseStudy_`, for example: `CaseStudy_adform_banner1.jpg`.

These images are then referenced in the individual case study pages. For example, `CaseStudy_adform_banner1.jpg` is referenced on `/content/en/adform/index.html`: 

```
<div class="banner1 desktop" style="background-image: url('/images/CaseStudy_adform_banner1.jpg')">
```

## What to do (for each image)

1. Move each set of case study images into their own directory under `/static/images/case-studies`. 
2. Change the referenced image URLs in the relevant case study pages to match the new locations.
3. Test test test!

For example: 

1. Move `/static/images/CaseStudy_adform_banner1.jpg` to `/static/images/case-studies/adforms/CaseStudy_adform_banner1.jpg`
2. Change the URL on `/content/en/adform/index.html`: 

```
<div class="banner1 desktop" style="background-image: url('`/static/images/case-studies/adforms/images/CaseStudy_adform_banner1.jpg')">
```

Note: there are case studies in the translation folders, but you should limit your changes to the `/en` translation. The TL teams will catch up soon enough, and it's best to let them manage those changes :)

### PR DESCRIPTION
**Pull request by shuuji3**
Closes #22086
☔ Umbrella issue: #22024

**What is changed**

- Rename the pre-existing `case_studies` directory to `case-studies`
- Move `/images/CaseStudy_<company-name>_<banner-name> to /images/case-studies/<company-name>/<banner-image-file>`
- Move `/images/<compnay-name><banner-image-file> to /images/case-studies/<company-name>/<banner-image-file>`
- Rewrite reference to the images on each index.html an stylesheets

I also rename some banner image files to be consistent.

**How I tested**

- Open http://localhost:1313/case-studies/
- Click each company logo to visit each case study page
- Check if I can see the banner images
- Check if the number of banner images equals to the number of image files in `/images/case-studies/<company-name>/`

### CODE REVIEW

**Comment by shuuji3** [comment]
Thank you for reviewing.

**Comment by celestehorgan** [comment]
/approve

I looked through every case study to check that images still worked correctly.

Thank you for taking this on!!

**Pull request merged**
