### PR TITLE
Describe clusters, the control plane node, and the worker node

### PR DESCRIPTION
**Pull request by 911432**
[issue #40554 ](https://github.com/kubernetes/website/issues/40554)
Looking at the  [Kubernetes Components](https://v1-26.docs.kubernetes.io/docs/concepts/overview/components/) description, the word worker node was unfamiliar to me, so I wanted to change it.
However, worker nodes and control plane nodes are not defined, so they are defined.
Accordingly, the control plane description was changed to manage the nodes as well as this worker nodes.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@911432 Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Comment by ydFu** [comment]
@911432 
thank you for your contribution.

You must sign the CLA for teams of kubernetes/website to do code reiview.

Please click on the red button `NOT COVERED` line in the first comment.

If you don't know how to do it, here is[the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Comment by T-Lakshmi** [comment]
@911432,
Deploy got failed, you need to re trigger deploy with empty command. can you execute following command?
**git commit --amend --no-edit && git push -f**

**Comment by 911432** [comment]
I did it

> @911432, Deploy got failed, you need to re trigger deploy with empty command. can you execute following command? **git commit --amend --no-edit && git push -f**

**Comment by 911432** [comment]
> @911432, Deploy got failed, you need to re trigger deploy with empty command. can you execute following command? **git commit --amend --no-edit && git push -f**
I think EasyCLA didn't approve me.

**Comment by 911432** [comment]
> @911432, Deploy got failed, you need to re trigger deploy with empty command. can you execute following command? **git commit --amend --no-edit && git push -f**
@T-Lakshmi  I think EasyCLA didn't approve me.

**Comment by 911432** [comment]
Why is it delayed?

**Comment by 911432** [comment]
Why is it delayed?

**Pull request closed without merging**
