### PR TITLE
Update networkpolicy.yaml - match yaml code formatting

### PR DESCRIPTION
**Pull request by mhash17**
Harmonizing indent of the yaml to be equal in formatting to other code examples in network-policies.md

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Review by PranitRout07 — COMMENTED** [review]
I think there is no need of changes .

**Comment by mhash17** [comment]
See my explanation:
https://github.com/kubernetes/website/pull/44502#issuecomment-1869087114

**Comment by mhash17** [comment]
If i sign EasyCLA it becomes 'covered' afther some time again 'uncovered'. I do not understand why..

**Review by Gauravpadam — COMMENTED** [review]
Thanks

I would prefer the indentations because
1. They improve code readability in larger code samples (like this one)
2. Both cases are correct in terms of linting

**Comment by divya-mohan0209** [comment]
Thank you for these changes!
/approve

**Pull request merged**
