### PR TITLE
Update multi-tenancy.md

### PR DESCRIPTION
**Pull request by zdxgs**
As shown in the figure,：
错误
correct some errors

### CODE REVIEW

**Comment by Michelle951** [comment]
This file is out of sync with its en version. Would you please help make it in sync?

Run 
```
./scripts/lsync.sh content/zh-cn/docs/concepts/security/multi-tenancy.md 
```
to find out the diff and update it.

Don't be afraid. Most changes are cuased by word wrap.

**Comment by zdxgs** [comment]
> This file is out of sync with its en version. Would you please help make it in sync?
> 
> Run
> 
> ```
> ./scripts/lsync.sh content/zh-cn/docs/concepts/security/multi-tenancy.md 
> ```
> 
> to find out the diff and update it.
> 
> Don't be afraid. Most changes are cuased by word wrap.

OK, I'll try it

**Comment by zdxgs** [comment]
> > This file is out of sync with its en version. Would you please help make it in sync?
> > Run
> > ```
> > ./scripts/lsync.sh content/zh-cn/docs/concepts/security/multi-tenancy.md 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to find out the diff and update it.
> > Don't be afraid. Most changes are cuased by word wrap.
> 
> OK, I'll try it

I updated the whole file with the method you provided me. Thanks for your suggestions.

**Comment by tengqm** [comment]
/hold
The upstream English page is badly formatted. I'm fixing it.

**Comment by Sea-n** [comment]
PR #36623 has been merged.

Please rebase into `main` branch and sync again.

**Comment by Sea-n** [comment]
Hey @zdxgs,

It's been a while since the last update, would you like to address issues in the previous comments so that we can move forward?

**Comment by shixiuguo** [comment]
> Hey @zdxgs,
> 
> It's been a while since the last update, would you like to resync this page so that we can move forward?

Sorry I didn't notice, I'll sync it

**Comment by tengqm** [comment]
@zdxgs Pls help resolve the conflicts?

**Comment by Sea-n** [comment]
The page is synced by PR #37050.
- #37050

/close

**Pull request closed without merging**
