### PR TITLE
Update replicaset.md

### PR DESCRIPTION
**Pull request by mkr1481**
When updates are required i hope Deployment would be better choice than ReplicaSet

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/27888#issuecomment-833253295

**Comment by jimangel** [comment]
Hey there! @mkr1481, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
I'm closing this due to CLA issue open for too long. Please feel free to reopen when the agreement is signed.
/close

**Pull request closed without merging**
