### PR TITLE
Apply content template in "docs/reference/command-line-tools-reference/"

### PR DESCRIPTION
**Pull request by makocchi-git**
This PR contains following changes.

* apply template (and remove double bullets in TOC)
* change `Synopsis` words to `Overview`
* fix dead links
* change titles
  * from `Kubelet authentication/authorization` to `kubelet authentication/authorization`
  * from `TLS bootstrapping` to `kubelet TLS bootstrapping`

* change page weight in `Command line tools reference`

before
```
Command line tools reference
  Feature Gates
  kubelet
  kube-apiserver
  kube-controller-manager
  kube-proxy
  kube-scheduler
  cloud-controller-manager
  federation-apiserver
  federation-controller-manager
  Kubelet authentication/authorization
  TLS bootstrapping
```

after
```
Command line tools reference
  Feature Gates
  kubelet
  kubelet authentication/authorization
  kubelet TLS bootstrapping
  kube-apiserver
  kube-controller-manager
  kube-proxy
  kube-scheduler
  cloud-controller-manager
  federation-apiserver
  federation-controller-manager
```

### CODE REVIEW

**Comment by mistyhacks** [comment]
/hold

@steveperry-53 can you weigh in here? Some of these are generated files so they will just get reverted the next time we generate them, right?

**Comment by steveperry-53** [comment]
@makocchi-git, Thank you for your pull request, but we cannot accept most of what you have done here. The following pages are automatically generated, so we don't change them manually.

* cloud-controller-manager.md
* federation-apiserver.md
* federation-controller-manager.md
* kube-apiserver.md
* kube-controller-manager.md
* kube-proxy.md
* kube-scheduler.md
* kubelet.md

**Comment by makocchi-git** [comment]
@steveperry-53 @mistyhacks Thank you for your comments.
I understood that command-line-tools-reference pages are generated automatically.
I close this PR.

**Pull request closed without merging**
