### PR TITLE
update package.json

### PR DESCRIPTION
**Pull request by kbhawkey**
- Cleaned up package.json
- Created postcss.config.js

### CODE REVIEW

**Comment by kbhawkey** [comment]
See issue #22308

**Comment by zacharysarah** [comment]
Nice! ✨ 
```
3:10:39 PM: Finished processing build request in 3m33.856080234s
```

**Comment by kbhawkey** [comment]
There is this:
```
6:07:39 PM: Installing NPM modules using NPM version 6.14.4
6:07:42 PM: npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
6:07:44 PM: npm notice created a lockfile as package-lock.json. You should commit this file.
6:07:44 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
6:07:44 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6:07:44 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
6:07:44 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6:07:44 PM: removed 591 packages and audited 118 packages in 4.302s
6:07:44 PM: 8 packages are looking for funding
6:07:44 PM:   run `npm fund` for details
6:07:44 PM: found 1 low severity vulnerability
6:07:44 PM:   run `npm audit fix` to fix them, or `npm audit` for details
6:07:44 PM: NPM modules installed
```

**Comment by kbhawkey** [comment]
I did create a package-lock.json. Does fix the warnings, locally.

**Comment by zacharysarah** [comment]
@kbhawkey This looks like it's headed in the right direction, so I'll approve it.

Holding for explicit review and LGTM by tech leads. @sftim @onlydole 

/approve
/hold

**Comment by sftim** [comment]
/lgtm

@kbhawkey feel free to /unhold at will

**Comment by kbhawkey** [comment]
Thanks!
/unhold

**Pull request merged**
