### PR TITLE
[hi]Localize content/en/docs/reference/glossary/cidr.md

### PR DESCRIPTION
**Pull request by taniaduggal**
fixes #36118

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
I agree with the comment by @Babapool that we need to maintain a consistence wording for CIDR or its transliterated version. 

@taniaduggal - Please could you either keep it as CIDR OR सीआईडीआर across the whole document?

**Comment by divya-mohan0209** [comment]
Any update on this @taniaduggal ?

**Comment by taniaduggal** [comment]
@divya-mohan0209 check again please:)

**Review by Babapool — COMMENTED** [review]
Thanks!
/lgtm

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Pull request merged**
