### PR TITLE
Fix markdown for a mermaid graph

### PR DESCRIPTION
**Pull request by bentito**
Fixes the markdown for the embedded Mermaid graph so it works.

### CODE REVIEW

**Review by sftim — CHANGES_REQUESTED** [review]
https://deploy-preview-33100--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/ingress/ doesn't look right to me, @bentito 

You can follow [preview your changes locally](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#preview-locally) to see if a proposed change has fixed the issue.

In this case, I think you were trying to fix #31960

A fix for that is very welcome, but it has to work.

**Comment by bentito** [comment]
> https://deploy-preview-33100--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/ingress/ doesn't look right to me, @bentito
> 
> You can follow [preview your changes locally](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#preview-locally) to see if a proposed change has fixed the issue.
> 
> In this case, I think you were trying to fix #31960
> 
> A fix for that is very welcome, but it has to work.

Not sure what's up with that preview, because when I go to edit the page for it, the source doesn't reflect the change made in the PR?

I made the same changes to the source and it seems to render okay here: https://github.com/bentito/scratch/blob/main/README.md

**Comment by sftim** [comment]
Ah!
@bentito when you edit pages in GitHub, you're seeing how _GitHub_ renders those pages. However when you visit https://k8s.io/docs/ you see the pages rendered by _Hugo_, using our custom styling and the third-party Docsy theme.

As you can imagine, https://kubernetes.io/docs/concepts/services-networking/ingress/ and https://github.com/kubernetes/website/blob/919c6a07fd96d43db3ff9272c6e57e566992af52/content/en/docs/concepts/services-networking/ingress.md are connected, but they are not the same page when you look at them. We're aiming to improve how https://kubernetes.io/docs/concepts/services-networking/ingress/ looks; the appearance of https://github.com/kubernetes/website/blob/919c6a07fd96d43db3ff9272c6e57e566992af52/content/en/docs/concepts/services-networking/ingress.md isn't important.

**Comment by bentito** [comment]
Ah okay but ultimately it needs to render properly on Github where people
are seeing it, right? Currently I just see a JS syntax error graphic
instead of the Mermaid graph.That's what the PR is trying to fix. I think
the changes in the PR accomplish the fix on Github?

Brett Tofel
he/him/his
Sr. Software Engineer
Red Hat (OpenShift Operator Portfolio Enablement  / OLM)

**Comment by sftim** [comment]
/hold

The intent (“fix” how GitHub renders the docs) seems to misunderstand how the Kubernetes project publishes its documentation. https://github.com/kubernetes/website/ does have a link to the actual docs website.

**Comment by bentito** [comment]
Oh thanks for explaining. And, it does actually render on kubernetes.io/docs fine for me on Firefox right now. Closing this due to that.

**Pull request closed without merging**
