### PR TITLE
Fix typo in workloads/controllers/daemonset

### PR DESCRIPTION
**Pull request by ystkfujii**

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Fixes made here look good.

**Deploy Preview Link:** [deploy-preview-40117](https://deploy-preview-40117--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/daemonset/)

**Comment by dipesh-rawat** [comment]
@ystkfujii Thanks for the fix. Changes look good to me.

/lgtm

**Comment by seokho-son** [comment]
Hi @ystkfujii 
Thank you for the contribution ! :)
/lgtm

Please try to provide a better PR title next time. 
A proper title will help the community prevent duplicated contributions.

**Pull request merged**
