### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by prrajput1199**
What type of PR is this?
/Fixing typo

What this PR does / why we need it:
Fixes the documentation.

Which issue(s) this PR fixes:
Fixes #

Special notes for your reviewer:

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @prrajput1199, Thanks for the PR, can you share the link to the doc that is related to this PR.

**Comment by prrajput1199** [comment]
@utkarsh-singh1 https://github.com/kubernetes/website/blob/main/README.md

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @prrajput1199 , this PR is a trivial edit and is the third in a series of PRs you seem to have raised with similar type of changes. We understand that you're enthusiastic about contributing to Kubernetes and open source. However, I'd request you to go through our contribution guide and especially, our policy on trivial edits before submitting a PR.

**Comment by prrajput1199** [comment]
@divya-mohan0209 ok . I will take care of this before submitting next PR.

**Comment by reylejano** [comment]
Hi @prrajput1199 ,
As another reviewer mentioned, this is a trivial edit (see [policy on trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits)) and there hasn't been traction on the PR. I'm closing this PR, feel free to reopen this PR when you have reviewed the [policy on trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) and add more to this PR
/close

**Pull request closed without merging**
