### PR TITLE
Fix doc link

### PR DESCRIPTION
**Pull request by inductor**
### Description

Fix doc link typo in blog release in #47248

### Issue

N/A

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@inductor It appears that this PR includes changes to files across multiple languages [English](https://github.com/kubernetes/website/blob/637f850bbc5a68c617d0d59752ea08633def202a/content/en/blog/_posts/2024-08-23-kubeadm-v1beta4.md) and [Chinese](https://github.com/kubernetes/website/blob/637f850bbc5a68c617d0d59752ea08633def202a/content/zh-cn/blog/_posts/2024-08-23-kubeadm-v1beta4.md). However, docs follows different processes for each localization, and we typically don't accept pull requests that impact multiple languages simultaneously. I would recommend modify only the primary website content (which means only English content) initially with this PR. After the merge of the English content, we could create separate pull request for the remaining language(s). I hope this suggestion is helpful.

**Comment by dipesh-rawat** [comment]
Explicit hold until this PR only covers one language
_(Ok to unhold once that's done)_
/hold

**Comment by inductor** [comment]
@dipesh-rawat I do understand the *typical* rule, as I'm also an owner of localization. This time I made this PR combined as the author of both articles appeared to be the same. Should I still separate the PRs? 🤔

**Comment by sftim** [comment]
Please @kohei; partly because precedents can have long term costs, and partly because a _single commit_ should try not to touch multiple localizations, especially not English + a downstream localization.

**Comment by sftim** [comment]
Keeping them separate allows localization teams to revert if required without getting approval from another localization.

**Comment by inductor** [comment]
@sftim done

**Comment by pacoxu** [comment]
/lgtm
thanks

**Pull request merged**
