### PR TITLE
Update content/es/docs/concepts/workloads/pods/podspreset.md

### PR DESCRIPTION
**Pull request by leeyspaul**
Spanish translation of content/es/docs/concepts/workloads/pods/podspreset.md

### CODE REVIEW

**Comment by leeyspaul** [comment]
I signed it

**Comment by raelga** [comment]
Hello @leeyspaul, thank you very much for the PR!

/check-cla

**Comment by leeyspaul** [comment]
Hey Rael! I tried the CLA command, and the bots being a bit unresponsive. Not sure if the command is broken and needs fixing or if there's something else going on in the background.

**Comment by leeyspaul** [comment]
Hi Rael, the content seemed to already have been translated, I just re-organized the content and changed some syntactical items. Please let me know if there is something I am missing!

**Comment by raelga** [comment]
The CLA issues are usually related to a difference between the email used for GitHub and the mail used for signing the CLA, are you sure that both are the same?

**Comment by leeyspaul** [comment]
I signed it

**Comment by leeyspaul** [comment]
I made sure both locally and on the website the email was the same. Either way, I went ahead and filed a ticket, we'll see what they say. Thanks Rael

**Comment by leeyspaul** [comment]
I signed it

**Comment by raelga** [comment]
> I signed it

🎉 🎉 🎉 

The CLA looks good now!

**Comment by raelga** [comment]
/lgtm
/approve

Thanks for the PR @leeyspaul and welcome to kubernetes!

**Pull request merged**
