### PR TITLE
kubeadm-certs: add notes about different external CA approaches

### PR DESCRIPTION
**Pull request by neolit123**
There are multiple ways to prepare the credentials for use with "external CA" mode:
- manual
- using kubeadm CSRs
- using kubeadm phases

fixes https://github.com/kubernetes/kubeadm/issues/3016

### CODE REVIEW

**Comment by sftim** [comment]
@kubernetes/sig-security-pr-reviews does this look OK?

**Comment by sftim** [comment]
/unassign

I'm happy for anyone to review this.

**Comment by neolit123** [comment]
> Once this PR has been reviewed and has the lgtm label, please assign [tengqm](https://github.com/tengqm)

/assign @tengqm

**Pull request merged**
