### PR TITLE
Fix malformed sentence in "Pods" concept page

### PR DESCRIPTION
**Pull request by sjong13**
### Description
Fixed a grammar issue dividing one long malformed sentence into two better-formed sentences capturing the intent of the documentation.

### Issue

Closes: #

### CODE REVIEW

**Comment by shannonxtreme** [comment]
@sjong13 pls sign the CLA :)

**Comment by shannonxtreme** [comment]
This is a trivial edit but first time contributor so

/lgtm

**Review by kundan2707 — COMMENTED** [review]
very small change but looksmore correct

**Comment by network-charles** [comment]
Thanks for your contribution, @sjong13! 
/approve

**Comment by dipesh-rawat** [comment]
/retitle Fix malformed sentence in "Pods" concept page

_(Shortened and clarified the title for better readability)_

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for the fix!
Please be careful to [avoid trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) in the future.

/approve

**Pull request merged**
