### PR TITLE
[WIP] Translate the introduction of the concept, PV

### PR DESCRIPTION
**Pull request by JonghunBok**
I translated the introduction of the concept Persistent Volume.
The rest of the documents stays the same with the English document. 
Should I create a pull request after I finish translating the whole page?

### CODE REVIEW

**Comment by JonghunBok** [comment]
Sorry.
I think I forked the wrong branch.
I'll close it and create pr again.

Before I close it,
it would be nice if you tell me I can create pr with partial translation. 

Many thanks.
Jonghun.

**Comment by gochist** [comment]
@JonghunBok 감사합니다! 페이지 전체를 현지화하는 것을 원칙으로 하고 있습니다. 다만, PR Title에 WIP를 붙여주시면 중간 리뷰를 할 수 있겠습니다.

**Comment by jimangel** [comment]
/retitle [WIP] Translate the introduction of the concept, PV

@gochist do you need assistance resolving the CLA issue?

**Comment by gochist** [comment]
@JonghunBok Please sign a CLA following the instruction at https://github.com/kubernetes/website/pull/19069#issuecomment-584524351

**Comment by gochist** [comment]
@JonghunBok I'm closing this PR as dev-1.17-ko.4 is outdated team milestone branch. Please reopen this PR after signing CLA and rebasing onto current Korean l10n team milestone branch. 

/close

**Pull request closed without merging**
