### PR TITLE
I18n TOML File Key Standardization change

### PR DESCRIPTION
**Pull request by tamilselvan1102**
Following keys has been updated.

link #38459

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TAMILS~1.T/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TAMILS~1.T/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

From | To
-- | --
layouts_blog_pager_prev | layout_blog_pager_prev
layouts_blog_pager_next | layout_blog_pager_next
layouts_case_studies_list_tell | layout_case_studies_list_tell
layouts_docs_glossary_aka | layout_docs_glossary_aka
layouts_docs_glossary_click_details_after | layout_docs_glossary_click_details_after
layouts_docs_glossary_click_details_before | layout_docs_glossary_click_details_before
layouts_docs_glossary_description | layout_docs_glossary_description
layouts_docs_glossary_deselect_all | layout_docs_glossary_deselect_all
layouts_docs_glossary_filter | layout_docs_glossary_filter
layouts_docs_glossary_select_all | layout_docs_glossary_select_all
layouts_docs_partials_feedback_improvement | layout_docs_partials_feedback_improvement
layouts_docs_partials_feedback_issue | layout_docs_partials_feedback_issue
layouts_docs_partials_feedback_or | layout_docs_partials_feedback_or
layouts_docs_partials_feedback_problem | layout_docs_partials_feedback_problem
layouts_docs_partials_feedback_thanks | layout_docs_partials_feedback_thanks
layouts_docs_search_fetching | layout_docs_search_fetching

</body>

</html>

### CODE REVIEW

**Comment by tamilselvan1102** [comment]
@divya-mohan0209 
All the above keys are tagged in the layout files, layout files are common for all language.
if only do the change in en.toml file, it will impact other lang pages

**Comment by akshat5302** [comment]
Hey @tamilselvan1102 if you need any help with this issue I'm up to working on it

**Comment by stormqueen1990** [comment]
@divya-mohan0209 @tamilselvan1102 perhaps this change could be done in steps?

For example:
1. Duplicate all keys in the English i18n TOML file, then open issues for each localization to also duplicate in their i18n TOML files.
2. After each localization has updated their TOML files, update the files that consume those keys in a separate PR.
3. Remove the duplicates in the English i18n TOML file and open issues for each localization to also remove the duplicates.

This way the change could be done in separate PRs without breaking the website.

**Comment by tamilselvan1102** [comment]
@stormqueen1990 
Thank you for the steps to follow. I will do the same

**Comment by tamilselvan1102** [comment]
@akshat5302
if you want to work on it, please create a pull request as per @stormqueen1990 comments

**Pull request closed without merging**
