### PR TITLE
change default enabled plugin from PersistentVolumeLabel to PersistentVolumeClaimResize

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

Fixes: #11526

### CODE REVIEW

**Comment by bradtopol** [comment]
hi @tengqm were you able to run this for 1.13 and verify that PersistentVolumeLabel is now PersistentVolumeClaimResize?

**Comment by tengqm** [comment]
@bradtopol Yes, I can confirm.

**Comment by bradtopol** [comment]
Thanks @tengqm!
/lgtm
/approve

**Pull request merged**
