### PR TITLE
kubeadm: add ControlPlaneKubeletLocalMode FG descriptions

### PR DESCRIPTION
**Pull request by chrischdi**
Action items

- [ ] add ControlPlaneKubeletLocalMode FG docs:
  - k/k PR: https://github.com/kubernetes/kubernetes/pull/125582

Part of:
- https://github.com/kubernetes/enhancements/issues/4471

cc @neolit123 @pacoxu

### CODE REVIEW

**Comment by chrischdi** [comment]
Also cc: @SataQiu @carlory

**Review by neolit123 — COMMENTED** [review]
thanks
/lgtm
/sig cluster-lifecycle
/triage accepted

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!

/approve

**Pull request merged**
