### PR TITLE
Add H3C AD-DC description

### PR DESCRIPTION
**Pull request by pedh**
Adding description on H3C AD-DC network solution integrated with Kubernetes.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-22799--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/networking/

**Comment by kbhawkey** [comment]
Looking into whether adding new content is honoring the third party content [KEP](https://github.com/kubernetes/enhancements/pull/1327).
See third party content umbrella issue #20232 for more details.

**Comment by sftim** [comment]
We discussed this in a Kubernetes SIG Docs weekly meeting and resolved that this PR doesn't meet the content guidelines, so won't be accepted.

/close

**Pull request closed without merging**
