### PR TITLE
[zh] Sync cheatsheet.

### PR DESCRIPTION
**Pull request by yuandongx**
I think "cheatsheet" also needs to be synchronized.

### CODE REVIEW

**Comment by howieyuen** [comment]
Could you please make sure this is a full sync of cheetsheet.md?
if so, it's lgtm

**Comment by yuandongx** [comment]
> Could you please make sure this is a full sync of cheetsheet.md?
> if so, it's lgtm
Yes, that's all.
image

**Comment by howieyuen** [comment]
thanks 👍 
/lgtm

**Pull request merged**
