### PR TITLE
Update garbage-collection.md

### PR DESCRIPTION
**Pull request by WisWang**
The old way may lead misunderstanding.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/lgtm

If I'm honest I'm not sure about the new _or_ the old wording, but let's bias in favor of revision.

**Comment by kbhawkey** [comment]
Hi @WisWang .
This note was recently updated in preparation for the 1.20 release.
Here is the recent commit, https://github.com/kubernetes/website/commit/8d96fcb42354b6cd70594f828ae4af7c4881a04b
Do you think this change is needed for the current page?

/cc @liggitt Would you have time to review?

Page preview:
https://deploy-preview-24739--kubernetes-io-master-staging.netlify.app/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents

**Comment by liggitt** [comment]
I would leave this alone for the next couple weeks in favor of the new content coming with the release of 1.20

**Comment by WisWang** [comment]
> Hi @WisWang .
> This note was recently updated in preparation for the 1.20 release.
> Here is the recent commit, [8d96fcb](https://github.com/kubernetes/website/commit/8d96fcb42354b6cd70594f828ae4af7c4881a04b)
> Do you think this change is needed for the current page?
> 
> /cc @liggitt Would you have time to review?
> 
> Page preview:
> https://deploy-preview-24739--kubernetes-io-master-staging.netlify.app/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents
Hi @kbhawkey,
I think this change is needed. Thank you for your contribution.

**Comment by sftim** [comment]
@WisWang it looks like you deleted your fork of [k/website](https://github.com/kubernetes/website).
Do you still hope to make the change you suggested?

**Comment by WisWang** [comment]
> @WisWang it looks like you deleted your fork of [k/website](https://github.com/kubernetes/website).
> Do you still hope to make the change you suggested?

@sftim Yes, I want to make the change. I deleted my fork by mistake. I don't know there is way to fix this.

**Comment by sftim** [comment]
> @sftim Yes, I want to make the change. I deleted my fork by mistake. I don't know there is way to fix this.

If you still have the branch locally, try these steps:
- create a new fork
- `git checkout master`
- `git pull --ff-only`
- `git switch --create <name-of-new-branch>`
- `git cherry-pick f3624a59f9c68d32fb5b2ad8137796e4988a4c8e # should “just work”
- `git push -u <name-of-remote-for-your-fork> <name-of-new-branch>:<name-of-new-branch>`

The GitHub service replies including the URL you can use to create a new pull request. Open that pull request, link it back to this one by mentioning “#24739” in a comment, then close this PR.

Maybe that advice helps? Otherwise, you can create a brand new pull request after starting from scratch; that also works.

**Pull request closed without merging**
