### PR TITLE
Broken links

### PR DESCRIPTION
**Pull request by butuzov**
This fix resolve
- broken links in documentation (Indonesian and Korean)
- misplaced markdown braces (that was generated web errors)
- fix a few links in the blog (English)

### CODE REVIEW

**Comment by butuzov** [comment]
It will be great to have "hacktoberfest" labels =)

**Comment by sftim** [comment]
Hi @butuzov 

Thanks for submitting this.

This pull request touches several different parts of the website. Would you be willing to resubmit this as different pull requests?
Ttypically: a change to the blog posts would be separate from non-blog changes, and each pull request should only cover a single localization (eg Bahasa Indonesia).

**Comment by butuzov** [comment]
Hi @sftim  

No problem. 

Can I combine blog related changes in one PR?

**Comment by sftim** [comment]
>  combine blog related changes in one PR?
That should be fine!

**Comment by butuzov** [comment]
It can be closed, in favor of that bunch of PRs. On other points - there are a lot of 404 at the website.. like 267 only for local links. Where can I share this info?

I rather kill myself than create an issue for each URL (which I am investigating manually)? Or should I create PR in auto mode (it shouldn't be hard using scripting).

**Comment by irvifa** [comment]
I think this is related to #16642

**Comment by butuzov** [comment]
yes! also related to 
- #16640
- #16641
- #16643 

And I have no idea what to do with the rest of the broken links I have found.

image

**Comment by irvifa** [comment]
Since you already selarate it into new PRs may be you can close this PR in favor of that other PRs? Cheers!

**Comment by butuzov** [comment]
oh. sure.

**Comment by sftim** [comment]
@butuzov there are two ways you can help further (if you're interested):
1. Log an [issue](https://github.com/kubernetes/website/issues/new?labels%5B%5D=kind%2Fbug&template=bug-report.md) about the remaining list of broken links.
2. Take a look at automating the reporting / checking; see issue #15893

**Comment by butuzov** [comment]
@sftim I will try to back asap, maybe with some automated aproach. at least it's nice to [develop](https://github.com/butuzov/deadlinks) own link checking tool and test it with kubernetes website.

**Pull request closed without merging**
