### PR TITLE
Sync code of conduct from cncf upstream

### PR DESCRIPTION
**Pull request by Sea-n**
The content in https://kubernetes.io/community/code-of-conduct/ is out-of-date. This PR also moved `master` branch to `main` branch for links.

We can check [upstream file](https://github.com/cncf/foundation/blob/main/code-of-conduct.md) and [diff for upstream](https://github.com/cncf/foundation/compare/214585e..71b12a2#diff-f1a69a41a835b5265e1c58e11395a894ac30fc6b0afe1ca834738955261d2ec5) to verify this PR. The modification mainly from this PR:
- https://github.com/cncf/foundation/pull/194

Netlify preview: https://deploy-preview-34310--kubernetes-io-main-staging.netlify.app/community/code-of-conduct/

### CODE REVIEW

**Comment by dims** [comment]
/hold

cc @kubernetes/code-of-conduct-committee

**Review by sftim — COMMENTED** [review]
Thanks

/lgtm

**Review by karenhchu — COMMENTED** [review]
/lgtm

**Pull request merged**
