### PR TITLE
[zh] update invalid web page link for api group

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/26333

### CODE REVIEW

**Comment by tengqm** [comment]
The file `content/zh/docs/reference/kubectl/cheatsheet.md` is out of sync.

**Comment by Arhell** [comment]
> The file `content/zh/docs/reference/kubectl/cheatsheet.md` is out of sync.
@tengqm 
remove cheatsheet.md from RP

**Comment by Arhell** [comment]
cc @tengqm

**Comment by tengqm** [comment]
/lgtm
/approve
thanks.

**Pull request merged**
