### PR TITLE
Update dns-pod-service.md

### PR DESCRIPTION
**Pull request by frontalnh**
Fix pod's DNS address

### CODE REVIEW

**Comment by Bradamant3** [comment]
@kubernetes/sig-network-pr-reviews PTAL and lgtm if OK? thanks!

**Comment by andreykaipov** [comment]
Is this correct? I just tried the included example on GKE v1.11.7 and

```busybox-1.default-subdomain.my-namespace.pod.cluster.local```

doesn't resolve, but

```busybox-1.default-subdomain.my-namespace.svc.cluster.local```

does.

**Comment by tottoto** [comment]
Me too. I tried example the example on v1.13 deployed by kubeadm.

```
dummy@kubeadmMaster01:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

The cluster.

```
dummy@kubeadmMaster01:~$ kubectl get nodes
NAME              STATUS   ROLES    AGE   VERSION
kubeadmmaster01   Ready    master   ZZd   v1.13.3
kubeadmnode01     Ready    <none>   ZZd   v1.13.0
kubeadmnode02     Ready    <none>   ZZd   v1.13.0
```

The example that I used.

```
dummy@kubeadmMaster01:~$ cat example.yaml
apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: busybox
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    name: busybox
spec:
  hostname: busybox-1
  subdomain: default-subdomain
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    name: busybox
spec:
  hostname: busybox-2
  subdomain: default-subdomain
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
```

Apply.

```
dummy@kubeadmMaster01:~$ kubectl apply -f example.yaml
service/default-subdomain created
pod/busybox1 created
pod/busybox2 created
```

Confirm.

```
dummy@kubeadmMaster01:~$ kubectl get all
NAME           READY   STATUS    RESTARTS   AGE
pod/busybox1   1/1     Running   0          10s
pod/busybox2   1/1     Running   0          10s

NAME                        TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
service/default-subdomain   ClusterIP   None         <none>        1234/TCP   10s
service/kubernetes          ClusterIP   10.96.0.1    <none>        443/TCP    ZZd
```

Tests.

```
dummy@kubeadmMaster01:~$ kubectl exec -it busybox2 sh
/ # ping -c 1 busybox-1.default-subdomain.default.pod.cluster.local
ping: bad address 'busybox-1.default-subdomain.default.pod.cluster.local'

/ # ping -c 1 busybox-1.default-subdomain.default.svc.cluster.local
PING busybox-1.default-subdomain.default.svc.cluster.local (10.244.1.87): 56 data bytes
64 bytes from 10.244.1.87: seq=0 ttl=62 time=0.315 ms

--- busybox-1.default-subdomain.default.svc.cluster.local ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.315/0.315/0.315 ms
```

The cluster IP of busybox1 Pod.

```
dummy@kubeadmMaster01:~$ kubectl get pods busybox1 -o jsonpath="{.status.podIP}"
10.244.1.87
```

**Pull request merged**
