### PR TITLE
[zh-cn] Add horizontal-pod-autoscaler-v2beta2.md chinese version

### PR DESCRIPTION
**Pull request by zhangxyjlu**
related: https://github.com/kubernetes/website/issues/34733 HPA-v2beta2
Add horizontal-pod-autoscaler-v2beta2.md chinese version

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @zhangxyjlu,

As said in [previous comment](https://github.com/kubernetes/website/pull/35125#issuecomment-1191273929), please don't use `fixes: #xxx` for umbrella issue.

**Comment by zhangxyjlu** [comment]
> Hey @zhangxyjlu,
> 
> As said in [previous comment](https://github.com/kubernetes/website/pull/35125#issuecomment-1191273929), please don't use `fixes: #xxx` for umbrella issue.

I have revised it, thanks for your guidance

**Comment by windsonsea** [comment]
/lgtm

The preview is good.

**Pull request merged**
