### PR TITLE
First Japanese l10n work for release-1.19

### PR DESCRIPTION
**Pull request by inductor**
First Japanese l10n work for release-1.19.

<details>
    <summary><b>Change List</b></summary>
    <ul>
    <li>ja: Make docs/concepts/architecture/controller.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/26948" target="_blank">#26948</a>)</li>
    <li>Delete some dirty code from several files in ja (<a href="https://github.com/kubernetes/website/pull/26977" target="_blank">#26977</a>)</li>
    <li>[ja] Update docs/concepts/workloads/pods/pod-lifecycle.md 1.18 to 1.19 (<a href="https://github.com/kubernetes/website/pull/26990" target="_blank">#26990</a>)</li>
    <li>ja:Make docs/concepts/architecture/nodes.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27000" target="_blank">#27000</a>)</li>
    <li>ja: Make docs/concepts/cluster-administration/ follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27001" target="_blank">#27001</a>)</li>
    <li>make docs/home/_index.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27005" target="_blank">#27005</a>)</li>
    <li>Update the outdated file ja/docs/concepts/scheduling-eviction/assign-pod-node.md (<a href="https://github.com/kubernetes/website/pull/27033" target="_blank">#27033</a>)</li>
    <li>Remove content/ja/docs/concepts/cluster-administration/cloud-providers.md (<a href="https://github.com/kubernetes/website/pull/27035" target="_blank">#27035</a>)</li>
    <li>Update ja/docs/concepts/cluster-administration/networking.md (<a href="https://github.com/kubernetes/website/pull/27036" target="_blank">#27036</a>)</li>
    <li>Update ja/docs/concepts/services-networking/service to v1.19 (<a href="https://github.com/kubernetes/website/pull/27039" target="_blank">#27039</a>)</li>
    <li>[ja] Fix: content/ja/docs/concepts/workloads/controllers/replicaset.md Issue #26899 (<a href="https://github.com/kubernetes/website/pull/27046" target="_blank">#27046</a>)</li>
    <li>Update: ja/docs/concepts/workloads/controllers/deployment.md (<a href="https://github.com/kubernetes/website/pull/27049" target="_blank">#27049</a>)</li>
    <li>[ja] Update: ja/docs/concepts/workloads/pods/init-containers.md (<a href="https://github.com/kubernetes/website/pull/27050" target="_blank">#27050</a>)</li>
    <li>[ja] Update docs/concepts/workloads/controllers/daemonset.md to follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27052" target="_blank">#27052</a>)</li>
    <li>update ja/docs/concepts/overview/what-is-kubernetes.md (<a href="https://github.com/kubernetes/website/pull/27079" target="_blank">#27079</a>)</li>
    <li>Make docs/contribute/_index.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27081" target="_blank">#27081</a>)</li>
    <li>[ja] Add setHostnameAsFQDN field to dns-pod-service.md (<a href="https://github.com/kubernetes/website/pull/27107" target="_blank">#27107</a>)</li>
    <li>update ja docs/concepts/containers/container-lifecycle-hooks.md v1.19 (<a href="https://github.com/kubernetes/website/pull/27156" target="_blank">#27156</a>)</li>
    <li>Update ja/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md (<a href="https://github.com/kubernetes/website/pull/27165" target="_blank">#27165</a>)</li>
    <li>ja: Make docs/concepts/extend-kubernetes/_index.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27176" target="_blank">#27176</a>)</li>
    <li>ja: Make docs/concepts/extend-kubernetes/api-extension/custom-resources.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27183" target="_blank">#27183</a>)</li>
    <li>Update: ja/docs/concepts/architecture/cloud-controller.md (<a href="https://github.com/kubernetes/website/pull/27210" target="_blank">#27210</a>)</li>
    <li>updated_text (<a href="https://github.com/kubernetes/website/pull/27256" target="_blank">#27256</a>)</li>
    <li>ja: Make docs/concepts/configuration/manage-resources-containers.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27267" target="_blank">#27267</a>)</li>
    <li>[ja] Update: ja/docs/concepts/scheduling-eviction/taint-and-toleration.md (<a href="https://github.com/kubernetes/website/pull/27305" target="_blank">#27305</a>)</li>
    <li>[ja] modify: ja/docs/concepts/overview/working-with-objects/namespaces.md (<a href="https://github.com/kubernetes/website/pull/27306" target="_blank">#27306</a>)</li>
    <li>Update: ja/docs/concepts/extend-kubernetes/operator.md (<a href="https://github.com/kubernetes/website/pull/27316" target="_blank">#27316</a>)</li>
    <li>Fixed broken links in ja/docs/tutorials/stateful-application/basic-st… (<a href="https://github.com/kubernetes/website/pull/27319" target="_blank">#27319</a>)</li>
    <li>ingress.md follows v1.19 (<a href="https://github.com/kubernetes/website/pull/27328" target="_blank">#27328</a>)</li>
    <li>Update: /ja/docs/concepts/storage/persistent-volumes.md (<a href="https://github.com/kubernetes/website/pull/27340" target="_blank">#27340</a>)</li>
    <li>Update ja/docs/concepts/extend-kubernetes/extend-cluster.md (<a href="https://github.com/kubernetes/website/pull/27367" target="_blank">#27367</a>)</li>
    <li>Fix content/ja/docs/concepts/scheduling-eviction/kube-scheduler.md (<a href="https://github.com/kubernetes/website/pull/27380" target="_blank">#27380</a>)</li>
    <li>Fix the position of the abbreviation text "CNCF" on the page /ja/docs/home/ (<a href="https://github.com/kubernetes/website/pull/27399" target="_blank">#27399</a>)</li>
    <li>Update Japanese localization on concepts/overview/working-with-objects/labels.md (<a href="https://github.com/kubernetes/website/pull/27427" target="_blank">#27427</a>)</li>
    <li>Update content/ja/docs/concepts/overview/components.md (<a href="https://github.com/kubernetes/website/pull/27431" target="_blank">#27431</a>)</li>
    <li>Update content/ja/docs/concepts/services-networking/dual-stack.md (<a href="https://github.com/kubernetes/website/pull/27433" target="_blank">#27433</a>)</li>
    <li>Remove the link to the unused page in the side menu (<a href="https://github.com/kubernetes/website/pull/27508" target="_blank">#27508</a>)</li>
    <li>Update Japanese localization on concepts/overview/working-with-object… (<a href="https://github.com/kubernetes/website/pull/27563" target="_blank">#27563</a>)</li>
    <li>Update ja/docs/concepts/workloads/pods/_index.md (<a href="https://github.com/kubernetes/website/pull/27582" target="_blank">#27582</a>)</li>
    <li>Update: ja/docs/concepts/services-networking/network-policies.md (<a href="https://github.com/kubernetes/website/pull/27588" target="_blank">#27588</a>)</li>
    <li>ja: Make docs/concepts/services-networking/ingress-controllers.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27591" target="_blank">#27591</a>)</li>
    <li>Change the page title from "Secrets" to "Secret" (<a href="https://github.com/kubernetes/website/pull/27592" target="_blank">#27592</a>)</li>
    <li>ja: Make docs/concepts/security/overview.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27593" target="_blank">#27593</a>)</li>
    <li>Update ja/docs/concepts/overview/kubernetes-api.md (<a href="https://github.com/kubernetes/website/pull/27605" target="_blank">#27605</a>)</li>
    <li>ja: Make docs/concepts/configuration/secret.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27611" target="_blank">#27611</a>)</li>
    <li> Update the Japanese translation of the concepts/workloads/ (<a href="https://github.com/kubernetes/website/pull/27626" target="_blank">#27626</a>)</li>
    <li>ja: Make docs/concepts/storage/dynamic-provisioning.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27641" target="_blank">#27641</a>)</li>
    <li>Update Japanese localization on concepts/containers/runtime-class.md (<a href="https://github.com/kubernetes/website/pull/27655" target="_blank">#27655</a>)</li>
    <li>Update Japanese localization on concepts/containers/images.md (<a href="https://github.com/kubernetes/website/pull/27656" target="_blank">#27656</a>)</li>
    <li>Update Japanese localization on concepts/configuration/configmap.md (<a href="https://github.com/kubernetes/website/pull/27659" target="_blank">#27659</a>)</li>
    <li>update ja/docs/concepts/policy/resource-quotas.md (<a href="https://github.com/kubernetes/website/pull/27662" target="_blank">#27662</a>)</li>
    <li>Fix a markup error on concepts/workloads/controllers/garbage-collection (<a href="https://github.com/kubernetes/website/pull/27698" target="_blank">#27698</a>)</li>
    <li>ja: Make docs/concepts/services-networking/endpoint-slices.md follow v1.19 of the original text (<a href="https://github.com/kubernetes/website/pull/27777" target="_blank">#27777</a>)</li>
    </ul>
</details>
<br>

Co-authored-by: @RyuSA
Co-authored-by: @hayato1226
Co-authored-by: @shimodatkh
Co-authored-by: @junox365
Co-authored-by: @shuuji3
Co-authored-by: @s-kawamura-w664
Co-authored-by: @KobayashiD27
Co-authored-by: @r-kgy
Co-authored-by: @s-ito-ts
Co-authored-by: @JIIOryo
Co-authored-by: @himanshu007-creator
Co-authored-by: @inductor
Co-authored-by: @translucens
Co-authored-by: @vaibhav2107
Co-authored-by: @yu-kasuya
Co-authored-by: @takaf04
Co-authored-by: @dragoneena12
Co-authored-by: @hase1128
Co-authored-by: @arisgi
Co-authored-by: @rkmathi
Co-authored-by: @katsuhisa91

### CODE REVIEW

**Comment by atoato88** [comment]
There are 2 conflict files.
I paste output of `git diff` on local environment.

## `content/ja/docs/concepts/policy/resource-quotas.md`
```
diff --cc content/ja/docs/concepts/policy/resource-quotas.md
index 4258a2035,e9381ce89..000000000
--- a/content/ja/docs/concepts/policy/resource-quotas.md
+++ b/content/ja/docs/concepts/policy/resource-quotas.md
@@@ -20,8 -20,8 +20,13 @@@ weight: 1
  リソースクォータは下記のように働きます。
  
  - 異なる名前空間で異なるチームが存在するとき。現時点ではこれは自主的なものですが、将来的にはACLsを介してリソースクォータの設定を強制するように計画されています。
++<<<<<<< HEAD
 +- 管理者は各名前空間で1つのResourceQuotaを作成します。
 +- ユーザーが名前空間内でリソース(Pod、Serviceなど)を作成し、クォータシステムがResourceQuotaによって定義されたハードリソースリミットを超えないことを保証するために、リソースの使用量をトラッキングします。
++=======
+ - 管理者は各名前空間で1つの`ResourceQuota`を作成します。
+ - ユーザーが名前空間内でリソース(Pod、Serviceなど)を作成し、クォータシステムが`ResourceQuota`によって定義されたハードリソースリミットを超えないことを保証するために、リソースの使用量をトラッキングします。
++>>>>>>> master
  - リソースの作成や更新がクォータの制約に違反しているとき、そのリクエストはHTTPステータスコード`403 FORBIDDEN`で失敗し、違反した制約を説明するメッセージが表示されます。
  - `cpu`や`memory`といったコンピューターリソースに対するクォータが名前空間内で有効になっているとき、ユーザーはそれらの値に対する`requests`や`limits`を設定する必要があります。設定しないとクォータシステムがPodの作
成を拒否します。 ヒント: コンピュートリソースの要求を設定しないPodに対してデフォルト値を強制するために、`LimitRanger`アドミッションコントローラーを使用してください。この問題を解決する例は[walkthrough](/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/)で参照できます。
```
`master` brach has markdown qualification by \`(backquote). 


## `i18n/ja.toml`
```
diff --cc i18n/ja.toml
index b10019242,6b08e1f22..000000000
mode 100644,120000..100644
--- a/i18n/ja.toml
+++ b/i18n/ja.toml
```

No diffs looks here.
We can ignore this? :thinking:

**Comment by inductor** [comment]
@atoato88 Thanks for pointing it out.
ja.toml recently changed in order to make it possible to be handled by localization owners themselves, so we had to replace it with symbolic link

**Comment by atoato88** [comment]
/lgtm
Great work by everyone on Japanese localization :tada:

**Comment by inductor** [comment]
/approve

since i got 2 lgtms from local team

**Pull request merged**
