### PR TITLE
Mention API extensibility as a front-page feature

### PR DESCRIPTION
**Pull request by sftim**
Kubernetes has really good options for extending and customizing its behavior. Mention these right on the front page.

/sig api-machinery
/language en

This will change the rendered content of https://kubernetes.io/ [[preview](https://deploy-preview-27392--kubernetes-io-master-staging.netlify.app/)]
/hold
for extra review.

### CODE REVIEW

**Comment by sftim** [comment]
@kubernetes/sig-docs-leads FYI

**Comment by kbhawkey** [comment]
@sftim, The text changes look good. Is it possible to add this description to the first column?

**Comment by sftim** [comment]
> Is it possible to add this description to the first column?

Sorry, I'm not following. You'd like the new card about API extensibility to appear in the left column instead?

**Comment by kbhawkey** [comment]
> 
> 
> > Is it possible to add this description to the first column?
> 
> Sorry, I'm not following. You'd like the new card about API extensibility to appear in the left column instead?

Right. Can the new card appear in the left column?

**Comment by sftim** [comment]
I think when this merges the columns will be balanced (I can rebase to make sure we preview that it does). I'm not sure how the assignment of cards to columns works.

**Review by irvifa — COMMENTED** [review]
/approve

**Comment by sftim** [comment]
With https://github.com/kubernetes/website/pull/27392#pullrequestreview-632449348 in mind
/hold cancel

@kbhawkey the layout looks better now, right?

**Comment by jimangel** [comment]
Great add @sftim!

/lgtm
/approve

**Comment by kbhawkey** [comment]
Looks great!

**Pull request merged**
