### PR TITLE
remove the md flag as current server not support.

### PR DESCRIPTION
**Pull request by xuhuilong**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5895)

### CODE REVIEW

**Comment by abiogenesis-now** [comment]
@xuhuilong I think  `{: .warning}` would actually work, there must've been a typo

**Comment by steveperry-53** [comment]
Yes, please change to {: .warning}.

**Comment by xuhuilong** [comment]
In fact, I tested the syntax {: .warning}. But it is not work as expect. 
Also I found {: .note} is also not work.

**Comment by xuhuilong** [comment]
Check the deploy preview, it worked like magic. 
thanks for the help.

**Comment by xiangpengzhao** [comment]
verified.

image

**Pull request merged**
