### PR TITLE
Adding Learn More Links to Partner Page

### PR DESCRIPTION
**Pull request by kbarnard10**
Adding links to learn more about each program.

### CODE REVIEW

**Comment by kbarnard10** [comment]
cc // @dankohn - what do you think of this for the learn more links?

**Comment by dankohn** [comment]
Could you please do it as:

"Interested in becoming a [KCSP](link)?"
"Interested in becoming [Certified Kubernetes](link)?"
"Interested in becoming a [KTP](link)?"

I think it reads better than "Learn More". Thanks.

**Comment by kbarnard10** [comment]
@dankohn Yeah I like that better. Updated.
/hold cancel

**Comment by dankohn** [comment]
LGTM

**Pull request merged**
