### PR TITLE
[zh] sync Resource metrics pipeline of task section

### PR DESCRIPTION
**Pull request by JarHMJ**
…trics-pipeline.md

### CODE REVIEW

**Comment by tengqm** [comment]
The upstream file has been relocated.

**Comment by JarHMJ** [comment]
> The upstream file has been relocated.

是的，我移动了文件的位置，并且进行了sync

**Comment by tengqm** [comment]
@JarHMJ There are conflicts to be resolved.

**Comment by JarHMJ** [comment]
> @JarHMJ There are conflicts to be resolved.

done

**Comment by howieyuen** [comment]
please squash these two commits into one

**Comment by JarHMJ** [comment]
> please  squash these two commits into one

done

**Comment by howieyuen** [comment]
/retitle [zh] sync Resource metrics pipeline of task section

**Pull request merged**
