### PR TITLE
[ja] add ja section

### PR DESCRIPTION
**Pull request by makocchi-git**

### CODE REVIEW

**Comment by cstoku** [comment]
@makocchi-git Please rebase or merge `dev-1.13-ja.1` .

**Comment by cstoku** [comment]
:+1: 
/unhold
/lgtm

**Comment by Bradamant3** [comment]
@cstoku did you try adding the approve label? According to my investigations of the OWNERS_ALIASES and OWNERS files in the repo, you should have permissions. lmk if you really don't, and we'll ask the bot experts.

**Comment by cstoku** [comment]
OK.
/approve

**Comment by cstoku** [comment]
@Bradamant3  Sorry, I've tried it but it didn't work.

**Comment by Bradamant3** [comment]
@cstoku gah, I should have paid more attention to the location of the file in the PR. It's at the root of the repo, and sig-docs-ja-owners, which you are a member of, has approver rights only over the /content directory. We should discuss in a sig-docs meeting, or on Slack, because this issue will come up again. In the meantime, I'll go ahead and approve (because atm only sig-docs-en-owners are listed in the OWNERS file at the root of the repo).

/approve

**Comment by cstoku** [comment]
@Bradamant3 thanks!!

**Pull request merged**
