### PR TITLE
    zh: Fix HTML table content(kube-controller-manager, kube-scheduler, kubectl) was incorrectly set to pre-formatted code

### PR DESCRIPTION
**Pull request by neargle**
Fix the doc in follow links:
1.  https://kubernetes.io/zh/docs/reference/command-line-tools-reference/kube-controller-manager/
2.  https://kubernetes.io/zh/docs/reference/command-line-tools-reference/kube-scheduler/
3.  https://kubernetes.io/zh/docs/reference/kubectl/kubectl/

image

See more infomation in ref. https://github.com/kubernetes/website/pull/21491. 
(Accept and thank the suggestion of Arhell)

### CODE REVIEW

**Comment by neargle** [comment]
I signed the CLA and recheck it again and again with the gmail address which is used in my github account setting and in my commit log, it does not work.

**Comment by markthink** [comment]
@neargle 请参考[翻译指引](https://github.com/k8smeetup/k8s-official-translation) 签署CLA协议..

**Comment by tengqm** [comment]
@neargle sorry to hear that. You may try close this one and recreate a new PR and see if that works?

**Comment by zparnold** [comment]
@neargle thanks for your contribution! 🎉 We really would love to have it, unfortunately to continue we need to have your (or your company's) signature on a CLA! For now I'm going to close this, but fret not! You can re-open whenever you have a chance. Thanks!
/close

**Pull request closed without merging**
