### PR TITLE
Update web-ui-dashboard.md

### PR DESCRIPTION
**Pull request by liuyanjie**
wrong

```sh
$ kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
error: unable to read URL "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml", server reported 404 Not Found, status code=404
```

right

```sh
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml
```

github page

```sh
https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended/kubernetes-dashboard.yaml
```

Closes: #11832

### CODE REVIEW

**Comment by tengqm** [comment]
Is this related to #11837 ?

**Comment by liuyanjie** [comment]
Closes: #11832

**Pull request merged**
