### PR TITLE
[ru] "image" word translation correction

### PR DESCRIPTION
**Pull request by Tri0L**
The correct translation of the word `image` is "образ".

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
@shurup @Arhell : Please could one of you take a look at this PR since it has been lying inactive & has gone stale multiple times without a review?

**Comment by shurup** [comment]
Thank you for mentioning, Divya! I missed it somehow.

This document needs a general overhaul (e.g., some English parts are not translated), but this specific mistake is so horrid that I'm happy to merge it ASAP.

Thank you, @Tri0L!

/retitle [ru] "image" word translation correction
/lgtm
/approve

**Pull request merged**
