### PR TITLE
[zh] fix typo in `content/zh-cn/docs/concepts`

### PR DESCRIPTION
**Pull request by HeavenTonight**
[zh] fix typo in `content/zh-cn/docs/concepts`

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @HeavenTonight , could you check any more differences from the en upstream by running this command on your `main` branch:

```
./scripts/lsync.sh content/zh-cn/docs/concepts/architecture/garbage-collection.md
```
The output may be similar to:
```diff
--- a/content/en/docs/concepts/architecture/garbage-collection.md
+++ b/content/en/docs/concepts/architecture/garbage-collection.md
@@ -139,7 +139,7 @@ until disk usage reaches the `LowThresholdPercent` value.
 
 #### Garbage collection for unused container images {#image-maximum-age-gc}
 
-{{< feature-state for_k8s_version="v1.29" state="alpha" >}}
+{{< feature-state feature_gate_name="ImageMaximumGCAge" >}}
```

**Comment by HeavenTonight** [comment]
> Hi @HeavenTonight , could you check any more differences from the en upstream by running this command on your `main` branch:
> 
> ```
> ./scripts/lsync.sh content/zh-cn/docs/concepts/architecture/garbage-collection.md
> ```
> 
> The output may be similar to:
> 
> ```diff
> --- a/content/en/docs/concepts/architecture/garbage-collection.md
> +++ b/content/en/docs/concepts/architecture/garbage-collection.md
> @@ -139,7 +139,7 @@ until disk usage reaches the `LowThresholdPercent` value.
>  
>  #### Garbage collection for unused container images {#image-maximum-age-gc}
>  
> -{{< feature-state for_k8s_version="v1.29" state="alpha" >}}
> +{{< feature-state feature_gate_name="ImageMaximumGCAge" >}}
> ```

Ok,thanks,i will check again.

**Review by windsonsea — COMMENTED** [review]
/lgtm

**Review by howieyuen — COMMENTED** [review]
/approve

**Pull request merged**
