### PR TITLE
Update service.md

### PR DESCRIPTION
**Pull request by bxavi**
Service type LoadBalancer has a property for clusterIP which should be loadBalancerIP for service type LoadBalancer.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@bxavi Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: https://git.k8s.io/community/CLA.md

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Comment by tengqm** [comment]
No. This is not how a LB service works.
The ClusterIP's scope is for inside the cluster.
The LB IP is not supposed to be specified when you create a Service, it is
filled by the Service controller when an external load balancer is created.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by network-charles** [comment]
Hi @bxavi, thanks for opening this PR. The `loadBalancerIP ` field Is [deprecated](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer).

However, you can sign the CLA so you can open new PRs in the future.

**Comment by T-Lakshmi** [comment]
> Note:
The.spec.loadBalancerIP field for a Service was deprecated in Kubernetes v1.24.

/hold
Changes in this PR are not valid.

**Comment by divya-mohan0209** [comment]
@bxavi Please note that as mentioned above, the CLA requirements must be met before proceeding with the review. Since there has been no response from your end and as mentioned in the comments above, the change is invalid, we will close the PR. 
/close

**Pull request closed without merging**
