### PR TITLE
Update building-from-source.md

### PR DESCRIPTION
**Pull request by VineethReddy02**
Update the page to be consistent with the concepts template.

### CODE REVIEW

**Comment by VineethReddy02** [comment]
screenshot 50

Updated the page to be consistent.

**Comment by VineethReddy02** [comment]
/assign zhangxiaoyu-zidif
Please review the changes i made at: https://deploy-preview-12577--kubernetes-io-master-staging.netlify.com/docs/setup/release/building-from-source/ and let me know if any changes need to be made.

**Comment by zparnold** [comment]
@VineethReddy02 Hey there! 👋 thanks for the contribution. On first glance, it's a little hard for me to tell what you are achieving here. Is it just to change the look/feel? It seems like some language is also changed here

**Comment by VineethReddy02** [comment]
Hi Zach! 
In This PR Building from Source is repetitive, would like to update it to Building a release.  Considering better understanding and eliminating redundancy in docs! :)

**Comment by zparnold** [comment]
Yep! Makes more sense. Thanks! 
/lgtm
/approve

**Pull request merged**
