### PR TITLE
Update pull-image-private-registry.md

### PR DESCRIPTION
**Pull request by samirspatel**
`-d` does not work on mac, `--decode` should work cross platform

### CODE REVIEW

**Comment by stewart-yu** [comment]
IMO, `-d` equal to `--decode`.  Could you paste the output about `base64 --help` command?

**Comment by samirspatel** [comment]
`--decode` is supported everywhere. Mac is `-D` not `-d`

```
base64 --help
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
```

**Comment by samirspatel** [comment]
@stewart-yu can you +1?

**Comment by stewart-yu** [comment]
Have'n use those command cross platform, but if like you say, seems reasonable
/lgtm
/cc @tengqm  @zacharysarah 
for approve

**Comment by tengqm** [comment]
We have received similar issue report before. It turned out that neither `-d` nor `-D` is portable. So `--decode` is a safer option.

/lgtm
/approve

**Pull request merged**
