### PR TITLE
ZH-trans: add kubeadm_alpha_phase_certs_apiserver

### PR DESCRIPTION
**Pull request by xichengliudui**
ZH-trans: add kubeadm_alpha_phase_certs_apiserver-etcd-client.md

### CODE REVIEW

**Comment by chenrui333** [comment]
@xichengliudui Sorry, I just want to say our current base branch is release-1.12.

If you find not fixed there, we need to fix in v1.12 first. 
After that we can have a zh-i18n v1.12 release.

Thanks!

**Comment by chenrui333** [comment]
looks like the base branch is not originally from release-1.12, a new PR might be required

**Comment by Hartmarken348** [comment]
11960

**Pull request merged**
