### PR TITLE
Typo in nodes.md

### PR DESCRIPTION
**Pull request by dedronek**
Fixing abnormal new line char
image

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by utkarsh-singh1** [comment]
Hi @dedronek, 

please sign EasyCLA first, which will allow us to review your PR and accept the contribution.

You can find about EasyCLA here - https://docs.linuxfoundation.org/lfx/easycla

and the steps to sign EasyCLA are here - https://docs.linuxfoundation.org/v2/easycla/contributors/individual-contributor

You can start your signing EasyCLA from here - https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38056/#/?version=2

**Comment by utkarsh-singh1** [comment]
Thanks for this PR @dedronek, 

related doc - https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown

**Comment by divya-mohan0209** [comment]
@dedronek : Please sign the CLA & consider reopening the PR whenever you're ready. We're closing the PR due to a lack of response from your end.
/close

**Pull request closed without merging**
