### PR TITLE
[zh-cn] unified namespace translation

### LINKED ISSUE #42699: 关于中文文档对于namespace的翻译文件
中文文档中关于namespace的翻译有多种，有时候叫命名空间。有时候叫名字空间，建议统一一下。

### PR DESCRIPTION
**Pull request by leslie-tsang**
Resolve #42699

### CODE REVIEW

**Comment by tengqm** [comment]
It is hard, is possible at all, to make sure everyone agrees to the same term.
I'd argue that "名字空间" is the right choice. It is a space of "names", just like it is a space for a "problem" when we call it "问题空间". We never call it "提问空间”.
"命名空间" 对应的是 "naming space"，"name" 作“命名”解的时候，只能是动词，和 "space" 无法形成一个有效的复合词。
现有很多文档使用了“命名空间”的说法，是习惯使然，我们不强行纠正而已。

**Comment by leslie-tsang** [comment]
> It is hard, is possible at all, to make sure everyone agrees to the same term. I'd argue that "名字空间" is the right choice. It is a space of "names", just like it is a space for a "problem" when we call it "问题空间". We never call it "提问空间”. "命名空间" 对应的是 "naming space"，"name" 作“命名”解的时候，只能是动词，和 "space" 无法形成一个有效的复合词。 现有很多文档使用了“命名空间”的说法，是习惯使然，我们不强行纠正而已。

LGTM, let's leave this PR here to see how the community reacts. :)

**Comment by xichengliudui** [comment]
这是一个具有争议的 pr ref: https://github.com/kubernetes/website/pull/37665

**Pull request closed without merging**
