### PR TITLE
Document the AllowedHostPaths policy

### LINKED ISSUE #6205: AllowedHostPaths PSP policy not documented.
**This is a...** 

- [X ] Feature Request
- [ ] Bug Report

**Problem:**
The `AllowedHostPaths` policy for PSP is not documented.
Ref: kubernetes/kubernetes#50212 

**Proposed Solution:**
Docuement it.

**Page to Update:**
http://kubernetes.io/...

### PR DESCRIPTION
**Pull request by tengqm**
Closes #6205

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6206)

### CODE REVIEW

**Comment by tengqm** [comment]
@jhorwit2 @smarterclayton

**Comment by zacharysarah** [comment]
Updated OP from "fixes" to "closes" for automation

**Comment by steveperry-53** [comment]
@jhorwit2 @smarterclayton Can one of you give tech approval for this? Thanks.

**Pull request merged**
