### PR TITLE
node: graduate the podresources API endpoint to GA

### PR DESCRIPTION
**Pull request by carlory**
Graduate the kubelet podresources endpoint to GA

KEP: https://github.com/kubernetes/enhancements/issues/606
enhancement: https://github.com/kubernetes/enhancements/issues/3743

reopen https://github.com/kubernetes/website/pull/39959 for 1.28

### CODE REVIEW

**Comment by ffromani** [comment]
> /cc @ffromani

thanks a ton! I planned to to this later! appreciated!

**Comment by ffromani** [comment]
from my side I just need to doublecheck if we need to advertise the feature as GA elsewhere in the docs, and then LGTM

**Review by sftim — COMMENTED** [review]
Would we also need to make any change to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#monitoring-device-plugin-resources ?

**Comment by ffromani** [comment]
> Would we also need to make any change to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#monitoring-device-plugin-resources ?

we do. We need to change  labels here and there (beta -> stable). I'll do a pass and issue PRs later, we have plenty of time luckily

**Review by pacoxu — APPROVED** [review]

**Review by pacoxu — COMMENTED** [review]
/lgtm
Since https://github.com/kubernetes/kubernetes/pull/116525 was already merged.

**Pull request merged**
