### PR TITLE
Add support for Gitpod

### PR DESCRIPTION
**Pull request by pawlean**
Hey folks! Pauline from Gitpod here. 👋🏼

This PR adds support for Gitpod.io allowing you to provision ready-to-code development environments in the cloud accessible through your browser. 

To quickly test and this for yourself, you can prefix this PR URL with `https://gitpod.io/#`. We hope that this will allow folks in the community to start contributing to Kubernetes website. :)

If you have any questions, happy to help and answer any!

### CODE REVIEW

**Comment by kbhawkey** [comment]
👋 @pawlean . Thanks for contributing.
Can you describe how this addition fits with the Kubernetes docs?

**Comment by pawlean** [comment]
Absolutely! It doesn’t really add to the documentation itself, but Gitpod
allows anyone wanting to contribute to the docs to easily do it without
having to set up their development environment on their local machine. It’s
as easy as just clicking a button or prefixing the URL [image: 😊] I hope
that answered your question!


*PAULINE P. NARVAS*
@paulienuh <http://twitter.com/paulienuh> / pnarvas
<https://www.linkedin.com/in/pnarvas/> / pawlean.com / paulinenarvas.com

Sent via Superhuman iOS ***@***.***>

**Comment by reylejano** [comment]
I don't think the changes in this PR fall under "What's Allowed" in the [Kubernetes Content Guide](https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed):

> Kubernetes docs allow content for third-party projects only when:
> - Content documents software in the Kubernetes project
> - Content documents software that's out of project but necessary for Kubernetes to function
> - Content is canonical on kubernetes.io, or links to canonical content elsewhere

cc @kubernetes/sig-docs-en-reviews for additional feedback

**Comment by reylejano** [comment]
Typically a k/website PR has changes for a single localization. Changes to multiple localizations are typically done in multiple PRs

**Comment by kbhawkey** [comment]
> 
> 
> I don't think the changes in this PR fall under "What's Allowed" in the [Kubernetes Content Guide](https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed):
> 
> > Kubernetes docs allow content for third-party projects only when:
> > 
> > * Content documents software in the Kubernetes project
> > * Content documents software that's out of project but necessary for Kubernetes to function
> > * Content is canonical on kubernetes.io, or links to canonical content elsewhere
> 
> cc @kubernetes/sig-docs-en-reviews for additional feedback

Yes, I agree.
/close

**Pull request closed without merging**
