### PR TITLE
Removing cni-ipvlan-vpc-k8s

### PR DESCRIPTION
**Pull request by ixodie**
This only works within AWS.  It is not necessary for k8s to run/function properly (in project).

### CODE REVIEW

**Comment by bradtopol** [comment]
Assigning @mdlinville since he originally approved this content.  @mdlinville could you please review this content. Simply add a /lgtm if you feel it is technically correct and I'll take care of the rest.
/assign @mdlinville 
/assign

**Comment by bradtopol** [comment]
/assign @jimangel 
Hey Jim, thoughts on deleting content like this?  It seems like the page represents multiple vendors already.

**Review by sftim — CHANGES_REQUESTED** [review]
https://github.com/lyft/cni-ipvlan-vpc-k8s looks like a network plugin to me. It's a network plugin even if it has specific requirements for the kind of network you're using.

Network plugins _are_ [necessary for Kubernetes to function properly](https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content). @ixodie, I am confident this change wouldn't be acceptable.

/hold

Rather than removing the entry, you might like eg to remove the last sentence (not needed as part of the description). A rewording could be acceptable; a removal isn't.

I realise that https://kubernetes.io/docs/concepts/cluster-administration/networking/#third-party-content-disclaimer doesn't explicitly discuss reading the content guide before proposing a removal, but you should nonetheless familiarize yourself with that guide and its context. If we were to remove details one network plugin for not being essential, I can only see that we would also need to remove all the others.

**Comment by ixodie** [comment]
> https://github.com/lyft/cni-ipvlan-vpc-k8s looks like a network plugin to me. It's a network plugin even if it has specific requirements for the kind of network you're using.

Tim, I'm not sure I agree with you here. According to the description of this plugin:

"networking stack for Kubernetes within Amazon Virtual Private Cloud (VPC) environments by making use of Amazon Elastic Network Interfaces (ENI)"

So this plugin is used ONLY when using the Amazon VPC ENIs.  K8s Getting Started page makes no mention of requiring AWS.  In fact, I can install k8s on any linux machine.  Following the instructions for standing up k8s, I was able to get it running without registering for AWS.  Does AWS get preferential treatment here in this CNCF project?

Would a small mom-and-pop cloud operator be able to submit their own CNI to this page if it only works with their service?

**Comment by sftim** [comment]
It's definitely a network plugin @ixodie

> Would a small mom-and-pop cloud operator be able to submit their own CNI to this page if it only works with their service?

Yes, because that would also be a network plugin. We don't judge network plugins by the commercial success of the cloud provider they work with. As much as is feasible, we apply _only_ the tests listed in the content guide to decide whether content is permitted.

If you're somehow unconvinced, you can get more context from https://kubernetes.io/blog/2020/05/third-party-dual-sourced-content/


As there is strong enough consensus that these details should **not** be removed:
/close

**Pull request closed without merging**
