### PR TITLE
Update kubectl install docs to refer to packaged versions of binary

### PR DESCRIPTION
**Pull request by jonmosco**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.10 Features: set Milestone to 1.10 and Base Branch to release-1.10
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by jonmosco** [comment]
Should I correct the merge conflict?  What are the next steps necessary for this PR?

**Comment by Bradamant3** [comment]
@jonmosco apologies for the delay -- yes, if you could fix the merge conflicts we'll get this into the doc build right away. Thanks!

**Comment by jonmosco** [comment]
No problem, thank you for getting back to me.  Merge conflict resolved.

**Pull request merged**
