### PR TITLE
[hi] Fix sha256 url missing '/release/' to download kubectl

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/43100/files
/assing @divya-mohan0209

### CODE REVIEW

**Review by aj11anuj — COMMENTED** [review]
LGTM, 👍

**Review by kundan2707 — COMMENTED** [review]
/lgtm
Thank you

**Review by Babapool — COMMENTED** [review]
Thanks!
/lgtm

**Comment by Babapool** [comment]
Assigning @divya-mohan0209 for approval.
/assign @divya-mohan0209

**Pull request merged**
