### PR TITLE
Official 1.13 Release Docs

### PR DESCRIPTION
**Pull request by jimangel**
🛑 DO NOT MERGE 🛑 UNTIL KUBERNETES 1.13 IS RELEASED
Target Date: 12-03-2018

## Release deadlines
From [sig-release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.13):

| Date | Description |
| --- | --- |
| NOV 8 | Open placeholder PRs |
| NOV 19 | PRs ready for review |
| NOV 27 | All PRs reviewed and ready to merge |

## More information
Contact @tfogo @jimangel @zparnold @npentrel @MAKOSCAFEE w/ any questions. 👍

### CODE REVIEW

**Comment by Bradamant3** [comment]
hrm. how have we wound up with multiple languages in this PR? The standard is now to submit separate PRs for each localized directory, but I'm not sure what's happened here.

**Comment by zacharysarah** [comment]
@Bradamant3 @jimangel How we handle L10n release content is a good subject for the postmortem. This is our first time handling L10n content in a release; we're approaching it one way (#11453, #11454) for 1.13, but there's probably a better way to approach it next time. 

My suspicion is that yes, we should continue limiting content to one language per PR.

**Pull request merged**
