### PR TITLE
Fix punctuation

### PR DESCRIPTION
**Pull request by paulgear**
Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7022)

### CODE REVIEW

**Comment by heckj** [comment]
thanks for the tweak/fix @paulgear  - sign the CLA and we'll get this merged

**Comment by heckj** [comment]
Hi @paulgear :wave:  - will you be able to sign the CLA so we can merge this? We don't really have a policy about this, but the PR's been open for 20 days now ready to go - if you won't or can't sign the CLA, then perhaps it would be better if we closed this PR.

**Comment by paulgear** [comment]
Hi @heckj - sorry, I haven't got around to reading the CLA carefully enough to be comfortable signing it.  And to be honest, I don't really think I should have to in order to delete one incorrect apostrophe.  I just noticed the problem when trying to learn about k8s, and thought I'd try to be helpful. Perhaps it might be better not to make the page editing function so attractive and seemingly straightforward? :-)

**Comment by heckj** [comment]
Thanks @paulgear  - totally understand, and while I appreciate your perspective, anything going into Kubernetes follows the same CLA process, even typo fixes. I do appreciate your willingness to help out there!

I'll go ahead and close this for now

**Pull request closed without merging**
