### PR TITLE
Add sftim as a blog editor

### PR DESCRIPTION
**Pull request by sftim**
I've been taking part in the blog team as a review for a while, and I'm also a tech lead for SIG Docs.

I suggest I also step forward as a blog editor.

/cc @onlydole
/cc @mrbobbytables

I'll update https://github.com/kubernetes/community/tree/master/sig-docs/blog-subproject if accepted.

### CODE REVIEW

**Comment by reylejano** [comment]
@sftim has conducted the majority of blog reviews for at least this past year (as I recall)
not sure if my vote counts but big +1 from me
/lgtm

**Comment by sftim** [comment]
Thanks @reylejano

**Comment by nate-double-u** [comment]
+1, thanks for stepping forward @sftim

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by divya-mohan0209** [comment]
A big lgtm from my side too!

Thank you for all that you do @sftim & thank you for stepping up!

**Comment by jlbutler** [comment]
Tim's done a lot of critical and quality work with blog editorial and technical reviews. His willingness to formalize his contributions is great for the project and the community. Big +1.

**Comment by sftim** [comment]
@onlydole / @mrbobbytables happy with this change?

**Comment by onlydole** [comment]
Let's make it so! Thank you so much, @sftim! It'll be great to have your help in this capacity :tada:
 
 /approve

**Review by onlydole — APPROVED** [review]

**Comment by sftim** [comment]
Thanks folks

**Pull request merged**
