### PR TITLE
Make minor changes on en/docs/tasks/network/validate-dual-stack

### PR DESCRIPTION
**Pull request by shuuji3**
This PR modifies several minor points such as removing unneeded space, quoting object names, and inserting a new line.

📄 Page preview: https://deploy-preview-27709--kubernetes-io-master-staging.netlify.app/docs/tasks/network/validate-dual-stack/

### CODE REVIEW

**Review by bridgetkromhout — APPROVED** [review]
LGTM.

**Comment by reylejano** [comment]
Confirmed the updated commands work.
/lgtm

**Comment by bridgetkromhout** [comment]
@reylejano would you like to approve as well?

**Comment by shuuji3** [comment]
Thank you! 🙂

**Pull request merged**
