### PR TITLE
Document PodAndContainerStatsFromCRI feature

### PR DESCRIPTION
**Pull request by haircommander**
There will be docs... one day
issue: kubernetes/enhancements#2371

### CODE REVIEW

**Comment by jlbutler** [comment]
@haircommander Reminder that tomorrow Nov 23rd is the deadline for 1.23 Docs Ready for Review. Please push your docs content for this enhancement and remove the work-in-progress label when ready for review.

We have a tight turnaround to getting docs reviewed and approved for the release, and we're hoping to have all docs in for review by EOB tomorrow. Thank you!

**Comment by haircommander** [comment]
sorry for the noise, forgot which branch this was targeted at

**Comment by bobbypage** [comment]
LGTM for docs, I also suggest we add note of which container runtimes (i.e. containerd, CRI-O) support the new endpoints. For containerd, this will be containerd 1.6+

**Comment by haircommander** [comment]
> LGTM for docs, I also suggest we add note of which container runtimes (i.e. containerd, CRI-O) support the new endpoints. For containerd, this will be containerd 1.6+

Added!

**Comment by jlbutler** [comment]
I see a few terms we typical capitalize/stylize, but I think in context this works. Thanks!

/lgtm

**Pull request merged**
