### PR TITLE
Fix bugs in setup/release/notes.md (#27606)

### LINKED ISSUE #27606: Bugs in setup/release/notes.md
**This is a Bug Report**

**Problem:**
There exist bugs in [setup/release/notes.md](https://github.com/kubernetes/website/blob/master/content/en/docs/setup/release/notes.md).

[Part number 1]
```Markdown
## Changelog since v1.20.0

# Release notes for v1.21.0-rc.0

[Documentation](https://docs.k8s.io/docs/home)

# Changelog since v1.20.0

## What's New (Major Themes)

### Deprecation of PodSecurityPolicy
```

[Part number 2]
```Markdown
## Dependencies

### Added
...

### Changed
...

### Removed
...

## Dependencies <!-- Duplicate -->

### Added <!-- Duplicate -->
...

### Changed <!-- Duplicate -->
...

### Removed <!-- Duplicate -->
...
```

**Proposed Solution:**
[Part number 1]
```Markdown
## Changelog since v1.20.0

## What's New (Major Themes)

### Deprecation of PodSecurityPolicy
```

[Part number 2]
```Markdown
## Dependencies

### Added
...

### Changed
...

### Removed
...
```

**Page to Update:**
https://kubernetes.io/docs/setup/release/notes/

/assign

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Resolves #27606

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Direct link to the preview: https://deploy-preview-27609--kubernetes-io-master-staging.netlify.app/docs/setup/release/notes/

**Comment by kbhawkey** [comment]
Thanks @jihoon-seo .
/lgtm

**Pull request merged**
