### PR TITLE
[zh] Fix spelling errors

### PR DESCRIPTION
**Pull request by guidao**
Fix spelling errors

### CODE REVIEW

**Comment by tengqm** [comment]
@guidao pls check your CLA status.

**Review by Arhell — COMMENTED** [review]
@guidao
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by guidao** [comment]
@tengqm  @Arhell  
Because my github is set up with a deprecated email address, I don't receive any emails when I try to log in. Even if I change the github email address, the problem still exists. Do you have any suggestions?

**Comment by tengqm** [comment]
@guidao You can still update your github settings using your new email address. Make sure you are using a valid email for signing the CLA and then commit (or recommit) your PRs using that same email.

**Comment by tengqm** [comment]
Thanks.
/lgtm
/approve

**Pull request merged**
