### PR TITLE
Update authentication.md

### PR DESCRIPTION
**Pull request by mkontani**
Now OIDC provider Dex's docs has moved, so I updated correct link like below.
```
s/https:\/\/github\.com\/dexidp\/dex\/blob\/master\/Documentation\/kubernetes\.md/https:\/\/dexidp.io\/docs\/kubernetes\//g
```

### CODE REVIEW

**Comment by Cweiping** [comment]
Wecome @mkontani. Please sign the CLA license of CNCF as prompted.
https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement

**Comment by mkontani** [comment]
I signed it

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
