### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by chughsaatvik**

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
Hi @chughsaatvik, and thank you for your fix! 

Few things:

- Could you please sign the CLA before your PR can be reviewed. For steps to sign the CLA please refer: https://github.com/kubernetes/community/blob/master/CLA.md

- We try to follow the [Trivial Edits guidelines](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) as much as we can. I kindly ask you to find more things you can improve in the same document or any other page you went through recently so that one PR can cover more improvements.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by bradtopol** [comment]
Thanks @chughsaatvik  for your contribution. Please sign the CLA so we can accept this for review.
/assign

**Comment by natalisucks** [comment]
@chughsaatvik This is another friendly ping about signing the CLA, as well as a reference back to @dipesh-rawat's note about trivial edits. Please note that if the CLA isn't signed, a PR Wrangler might close this PR. Thanks!

**Comment by divya-mohan0209** [comment]
Hello @chughsaatvik , with reference to previous comments, I'm closing this PR out since
1. You haven't signed the CLA
2. This is a trivial edit. 

Please consider reading our policy on trivial edits & when you feel ready to contribute to the K8s documentation, please sign the CLA & check out the issues reported in this GitHub repository.

/close

**Pull request closed without merging**
