### PR TITLE
update static _redirects, release-1.15

### PR DESCRIPTION
**Pull request by kbhawkey**
- Clean up entries in `static/_redirects` related to Netlify redirect bug fix.
- For further information see issue #19737 .
- Comments, reviews, questions, updates very welcome.
- Did not make any extra cleanup.

### CODE REVIEW

**Comment by onlydole** [comment]
This is approved! We might need your GH powers, @kbhawkey :smile:

**Comment by kbhawkey** [comment]
I am not sure if I can, but with permission will try.
/approve

**Pull request merged**
