### PR TITLE
Update hello-minikube.md

### PR DESCRIPTION
**Pull request by arun-meena**
Closes: #14436

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Thanks for your PR @arun-meena !!!! Please sign the CLA before we take a look at it. https://git.k8s.io/community/CLA.md#the-contributor-license-agreement

**Comment by tengqm** [comment]
@arun-meena Pls sign the CLA in order for this to be merged.

**Comment by palnabarun** [comment]
One thing should be noted here that the fix suggested in this PR will only work for linux distros having `apt`. For other operating systems, it will fail.

**Comment by cody-clark** [comment]
Hi @arun-meena. Thanks for your PR! Please sign the CLA, and I'll be happy to review it.

> 📝 Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

**Comment by tengqm** [comment]
Closing due to CLA issue for over 30 days. Feel free to reopen when CLA is ready. Thanks.

**Pull request closed without merging**
