### PR TITLE
Added new reviwer to the pt-BR team members

### PR DESCRIPTION
**Pull request by devlware**
New reviewer and admin for the portuguese, pt-BR team.

### CODE REVIEW

**Comment by zacharysarah** [comment]
@devlware @femrtnz 👋 Prow should have warned you not to approve this PR, but it didn't. 
 
To be clear, approvers *must* be members of the Kubernetes org before they can be approvers.

This matters because #15656 is throwing an error due to this PR. The associated commit is too old to revert, so I'm creating a new PR to remove @devlware as an approver. To re-add @devlware as an approver:

1. @devlware must [create an issue](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) in k/org requesting Kubernetes membership.
2. Once a PR is created to close the membership issue, create a new PR re-adding @devlware as an approver.

**Comment by zacharysarah** [comment]
@kubernetes/sig-testing 👋 This PR should have received a warning about an invalid OWNERS file. Do we need to adjust any settings for k/website to make sure that Prow adds appropriate warnings?

**Comment by cblecker** [comment]
@zacharysarah This PR happened during a period where that particular verification wasn't enabled. It's been fixed since July 18.

**Comment by devlware** [comment]
Thank you all for your effort to solve this issue.

**Pull request merged**
