### PR TITLE
Add arm64, ppc64le and s390x platforms for calico

### PR DESCRIPTION
**Pull request by ping035627**
Calico suppor tarm64, ppc64le and s390x platforms except amd64.

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@ping035627  you should change your target branch from master to release-xxx, this will trace the release version and make translation follow by its original EN version.

**Comment by zhangxiaoyu-zidif** [comment]
image
here should be update.

**Comment by ping035627** [comment]
* 'master'/en okay
'master'/zh wrong
* 'release-1.12'/en wrong
* 'release-1.12'/zh wrong

**Comment by tengqm** [comment]
@ping035627 Thanks for the check. Please retarget your PR to release-1.12 then.

**Comment by ping035627** [comment]
@tengqm ok, I have modified in branch release-1.12.  #12666

**Pull request closed without merging**
