### PR TITLE
WIP: Translate contribute/intermediate in french

### PR DESCRIPTION
**Pull request by AWKIF**

### CODE REVIEW

**Comment by lledru** [comment]
@AWKIF firstly you have to sign the CLA :)

**Comment by zparnold** [comment]
Hey there! @AWKIF, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by AWKIF** [comment]
i signed it

**Comment by AWKIF** [comment]
i signed it

**Pull request closed without merging**
