### PR TITLE
Remove duplicate version-check

### PR DESCRIPTION
**Pull request by iamhesir**
原先的有重复，节选如下：

```
您的 Kubernetes 服务器版本必须不低于版本 v1.12. 要获知版本信息，请输入 kubectl version.

你的集群必须运行 CoreDNS 插件。 文档迁移到 CoreDNS 解释了如何使用 kubeadm 从 kube-dns 迁移到 CoreDNS。

您的 Kubernetes 服务器版本必须不低于版本 v1.12. 要获知版本信息，请输入 kubectl version.
```

### CODE REVIEW

**Comment by iamhesir** [comment]
I signed it

**Comment by iamhesir** [comment]
I signed it

**Review by Arhell — COMMENTED** [review]
more info about CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
@iamhesir Have you tried recommit your change using the CLA email, i,e. `git commit --amend --reset-author --no-edit; git push -f`?

**Pull request merged**
