### PR TITLE
[de][es][fr][id][it][ja][ko][ru][uk][vi] Change footer l10n from Home to Documentation

### LINKED ISSUE #43068: Correction needs to be done at footer across all localized K8s site
**This is a Feature Request**

**What would you like to be added?**
As due to a recent PR merged #42962, now all localized K8s sites need to make this updation by changing the word "Home" at footer to "Documentation" across all pages. See below Original K8s site:

Screenshot (681)

### PR DESCRIPTION
**Pull request by lyzlisa**
Addresses outstanding l10n strings described in #43068

### CODE REVIEW

**Review by Gauravpadam — COMMENTED** [review]
This PR makes changes across all localisations,
We normally try to target a single localisation in a PR

**Comment by Gauravpadam** [comment]
@lyzlisa Thanks for the PR, However, Please limit your changes to a single localisation. Sync PRs usually work this way

**Comment by lyzlisa** [comment]
@Gauravpadam thanks for the input. I'll split them up and submit separate PRs. We can close this one.

**Review by dipesh-rawat — COMMENTED** [review]
Hold till the PR addresses changes only related to a single language.
_(OK to unhold once that's corrected)_
/hold

**Comment by Gauravpadam** [comment]
> We can close this

Sure, if you want to.

I'd suggest keeping a single change for this and reserving the others for different PRs

**Comment by lyzlisa** [comment]
#43882
#43883
#43884
#43885
#43886
#43887
#43888
#43889
#43890
#43890

**Pull request closed without merging**
