### PR TITLE
Update and rename 2016-09-00-Kubernetes-1-4-Making-It-Easy-To-Run-On-…

### PR DESCRIPTION
**Pull request by abhigyadufare**
…Kuberentes-Anywhere.md to 2016-09-00-Kubernetes-1-4-Making-It-Easy-To-Run-On-Kubernetes-Anywhere.md

typo fix Kuberentes >> Kubernetes

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@abhigyadufare Thank you for your contribution!

It looks like this PR contains modifications to files in multiple languages ('en' & 'vi'). However, our documentation follows separate procedures for each localization, and we typically don't accept PRs that impact multiple languages simultaneously. I recommend dividing this into multiple pull requests, each concentrating on a single language.

**Review by dipesh-rawat — COMMENTED** [review]
Normally, we don't usually make updates to blog posts that are over a year old. This PR proposes a typo fix in the link text, while the link itself is functioning correctly as intended. 

I will let the @kubernetes/sig-docs-blog-owners  to review it and share their feedback.

**Comment by abhigyadufare** [comment]
@dipesh-rawat Thank you so much for your review. I'll keep this in mind during future contributions 🙂

**Pull request closed without merging**
