### PR TITLE
typo fix: useable->usable

### PR DESCRIPTION
**Pull request by AdamDang**
Line 16: "to keep kubeadm useable"
useable->usable

### CODE REVIEW

**Comment by bradtopol** [comment]
I would view usable as more preferable than useable even though useable is defined in most dictionaries as an acceptable alternative spelling.
/lgtm
/approve

**Comment by heckj** [comment]
@bradtopol heh - wish I could help here, but I'm not the blog owners list to approve...

/assign @bobsky @kbarnard10 @natekartchner @sarahkconway @zacharysarah

**Comment by zacharysarah** [comment]
@adamdang Please bundle small changes into larger pull requests rather than submitting them individually.

**Comment by AdamDang** [comment]
@zacharysarah
OK. Got it! I will put small changes together.

**Pull request closed without merging**
