### PR TITLE
add a misspell check

### PR DESCRIPTION
**Pull request by CaoShuFeng**
Note this requires go environment
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.10 Features: set Milestone to 1.10 and Base Branch to release-1.10
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
We need to solve this before merge this pull request:

./verify-docs-format.sh
case-studies/blackrock.html:27:916: "scaleable" is a misspelling of "scalable"
case-studies/blackrock.html:68:437: "scaleable" is a misspelling of "scalable"
cn/docs/concepts/overview/what-is-kubernetes.md:94:32: "Controll" is a misspelling of "Control"
docs/tasks/administer-cluster/reconfigure-kubelet.md:335:45: "configuraiton" is a misspelling of "configuration"
docs/tasks/administer-cluster/running-cloud-controller.md:28:7: "availabilty" is a misspelling of "availability"
docs/update-user-guide-links.py:15:27: "desinations" is a misspelling of "destinations"
docs/update-user-guide-links.py:38:8: "desinations" is a misspelling of "destinations"

**Comment by CaoShuFeng** [comment]
> We need to solve this before merge this pull request:
```
./verify-docs-format.sh
case-studies/blackrock.html:27:916: "scaleable" is a misspelling of "scalable"
case-studies/blackrock.html:68:437: "scaleable" is a misspelling of "scalable"
cn/docs/concepts/overview/what-is-kubernetes.md:94:32: "Controll" is a misspelling of "Control"
docs/tasks/administer-cluster/reconfigure-kubelet.md:335:45: "configuraiton" is a misspelling of "configuration"
docs/tasks/administer-cluster/running-cloud-controller.md:28:7: "availabilty" is a misspelling of "availability"
docs/update-user-guide-links.py:15:27: "desinations" is a misspelling of "destinations"
docs/update-user-guide-links.py:38:8: "desinations" is a misspelling of "destinations"
```

@charrywanganthony will take care of this.

**Comment by bradtopol** [comment]
Dropping a /hold on this pending fix of the ./verify-docs-format.sh issue mentioned above
/hold

**Comment by tengqm** [comment]
@CaoShuFeng can you include the spelling fix in this patch as well?

**Comment by CaoShuFeng** [comment]
> @CaoShuFeng can you include the spelling fix in this patch as well?

@charrywanganthony is working on this.

https://github.com/kubernetes/website/pull/7654

**Comment by zacharysarah** [comment]
@CaoShuFeng Normally, changes to tooling and automation are proposed to the SIG, reviewed in a weekly meeting, then implemented if approved. 

Can you provide some more context about this automation proposal? Specifically:

1. Why are you proposing this change? I understand that the ostensible purpose is to provide a spellchecking bot, but why is a bot necessary and/or desirable?

2. Who do you propose will maintain this functionality on an ongoing basis?

3. Are you able to attend a weekly SIG meeting (Tuesdays, 10:30am Pacific) to talk more about the changes you're proposing?

@tengqm: Any insight here?

/cc @kubernetes/sig-docs-maintainers

**Comment by CaoShuFeng** [comment]
> Why are you proposing this change? I understand that the ostensible purpose is to provide a spellchecking bot, but why is a bot necessary and/or desirable?

1. This tool has already found 7 typos and it will prevent typos in the future.
2. This tool is also used by kubernetes and community project:
https://github.com/kubernetes/kubernetes/blob/master/hack/verify-spelling.sh
https://github.com/kubernetes/community/blob/master/hack/verify-spelling.sh
3. kubernetes/website also needs this tool more as a document.

> Who do you propose will maintain this functionality on an ongoing basis?

I volunteer. I have work in kubernetes community for more than one year. And I will contribute to kubernetes community at least in year 2018, as far as I know.

> Are you able to attend a weekly SIG meeting (Tuesdays, 10:30am Pacific) to talk more about the changes you're proposing?

It's 2:30 am in my time zone.  If we can make an agreement here, I'd prefer not wake up at such time.  :rofl:

**Comment by steveperry-53** [comment]
@heckj Can you chime in on this? I'm not a golang expert, but it seems odd to me to check a bunch of dependencies into a vendor folder. Thanks.

**Comment by tengqm** [comment]
Echo to what @steveperry-53 has mentioned, introducing dependencies is always scary. Is there a possibility we do `go get` in the script (check if go environment is there would be a plus) instead?
It is a tough decision to make whether to pin to a specific version of the package used ...
If we don't cache it, the tool change may accidentally break our gate which may take long to recover;
on the other hand, if we cache it, we are about to maintain it if there are upstream fixes.
That brings us back to @zacharysarah 's question: how much value this tool is bringing us?

**Comment by Bradamant3** [comment]
I took a look at the comment history for the spellcheck PR against k8s/k8s, which looks like the original effort. It's [here](https://github.com/kubernetes/kubernetes/pull/59463), for anyone interested.
(The k8s/community PR mostly refers to the k8s/k8s PR.)  

Folks raise a few important issues in those comments that I'm also concerned about, in particular breaking the build for these errors. The k8s/k8s folks seem to think they've solved the problem by excluding a bunch o' files and directories. But the k8s/k8s PR also talks about presubmit builds. (If I understand the code workflow, it seems like it’s also possible to circumvent the spellcheck). But k8s/website does not typically require or expect presubmit builds, nor do we have a test suite that folks run before submitting. So if we’re talking about build breaks, we’re talking about breaks per PR.

All this means that if we do integrate this tool, I'd recommend against breaking the build. Instead, do something like log spelling errors as warnings, concatenate them regularly (once per week?) and file an issue per concatenation.

IFF we think that integrating a spellcheck is the way to go. I'd rather see us encourage spellchecking in a local environment (which seems basically like what k8s/k8s does).

If the idea is to run a tool to fix a large number of typos in a single PR, that also seems like something that could be run locally using the spellchecker of the committer’s choice.

(Note also that vendoring is apparently required for a blocking presubmit, according to the comments at l24 in the k8s/k8s PR. Which suggests a different workflow from what’s proposed here for docs.)

Final note: I am perplexed by the argument that we need a spellchecker to avoid small typos PRs. Folks who want to submit PRs against typos should be encouraged to submit said PRs in bulk. Especially for docs — I can’t say it often enough — we cannot automate correcting spelling errors because false positives occur at a pretty high rate. This is true for any spellchecker, and by the author’s own admission true for the one that’s proposed here. This isn’t a ding against spellcheckers, but a caution against applying them in automated fashion.

**Comment by CaoShuFeng** [comment]
> This isn’t a ding against spellcheckers, but a caution against applying them in automated fashion.

Right!

Maybe I can encourage spell checking in  this page:
https://kubernetes.io/docs/home/contribute/style-guide/
?

**Comment by CaoShuFeng** [comment]
@Bradamant3 
Thanks very much for your detailed explanation

**Comment by zacharysarah** [comment]
@CaoShuFeng 👋 
> Maybe I can encourage spell checking in this page:

Please feel free to open a PR with proposed changes!

**Pull request closed without merging**
