### PR TITLE
Add Docker Desktop as local option

### PR DESCRIPTION
**Pull request by mpanthofer**
Docker Desktop for Mac and Windows 10 now includes Kubernetes. Over a million Docker for Desktop users just need to check the enable Kubernetes box.

### CODE REVIEW

**Comment by tengqm** [comment]
@mpanthofer Please sign the CLA for this PR to be mergeable.

**Comment by bradtopol** [comment]
@mpanthofer Thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by mpanthofer** [comment]
CLA Signed...

**Comment by zacharysarah** [comment]
@mpanthofer 👋 Please feel free to reopen when you've resolved the merge conflict.

**Pull request closed without merging**
