### PR TITLE
Fixup reference problems

### PR DESCRIPTION
**Pull request by it2911**
Fixup reference folder lost _index files problem.
But some files are so old that need be deleted.
To be confirming with the Chinese work team.

If the request to be pass, suggest merging to master branch.

### CODE REVIEW

**Comment by xichengliudui** [comment]
/lgtm
/approve
/hold
`_index.md source?`

**Comment by it2911** [comment]
@xichengliudui 

I copied those files from release-1.14 branch.
I got the information that the newest code is managed on release-1.12 and release1.14 branch.
https://github.com/k8smeetup/k8s-official-translation

For forbidding the menu structure broken. I try to merge the release-1.14 code into release 1.15, release1.16 and master branch.

Of course, before I commit I will check the relation en version documents.

If you think it no problem, please approved #16439 too. Thank you.

**Pull request merged**
