### PR TITLE
Update feature-gates description for TopologyManager

### PR DESCRIPTION
**Pull request by mysunshine92**
Update feature-gates description for TopologyManager

| `TopologyManager` | `false` | Alpha | 1.16 | 1.17 |
| `TopologyManager` | `true` | Beta | 1.18 | |

### CODE REVIEW

**Comment by mysunshine92** [comment]
cc @tengqm

**Comment by tengqm** [comment]
@mysunshine92 Any reference to upstream PR or release notes entry for this?

**Comment by mysunshine92** [comment]
@tengqm https://github.com/kubernetes/kubernetes/pull/87650/files

**Comment by tengqm** [comment]
@mysunshine92 Thanks.
/lgtm

**Comment by mysunshine92** [comment]
cc @celestehorgan please help add approved label, thanks.

**Comment by mysunshine92** [comment]
cc @sftim please help add approved label, thanks.

**Comment by tengqm** [comment]
Hi, @mysunshine92 Is there any reason you are pushing so hard to get this merged?

**Comment by mysunshine92** [comment]
cc @tengqm can help to add approved label, thanks.

**Comment by tengqm** [comment]
@mysunshine92 I'd only approve things I'm 100% sure. For this one, it would be good to have another pair of eyes to review. Please be patient.

**Comment by mysunshine92** [comment]
@tengqm ok, thanks.

**Comment by mysunshine92** [comment]
cc @daminisatya please help to add /approve label, thanks.

**Comment by sftim** [comment]
/approve

Thanks @mysunshine92 

BTW if you need to nudge the current SIG Docs [PR wrangler](https://github.com/kubernetes/website/wiki/PR-Wranglers), the schedule is public. Best way if you have an urgent fix is to mention the PR in https://kubernetes.slack.com/messages/sig-docs

**Pull request merged**
