### PR TITLE
Remove white spaces from the user journey page.

### PR DESCRIPTION
**Pull request by shavidissa**
The user journey (foundation) page has too many white spaces. Removed the spaces by adjusting the margin top and padding values.

### CODE REVIEW

**Comment by shavidissa** [comment]
I had not set my email on the git commit. Added it to my computer now. Not sure if that fixes it here.

**Comment by shavidissa** [comment]
/assign @chenopis 

I am waiting for the Netlify preview. Will confirm the changes soon as it comes in.

**Comment by zparnold** [comment]
Hey there! @shavidissa, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by shavidissa** [comment]
Hi @zparnold,

I have already signed the CLA. Not sure why it is giving the notification that I have not signed it.

**Comment by shavidissa** [comment]
Oppz :( . I have closed it by mistake. Opening it again ...

**Comment by zparnold** [comment]
Hey there! @shavidissa, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Bradamant3** [comment]
/close

@shavidissa -- in an effort to clean up the PR queue which has gotten monstrous big this week, I'm closing this PR since your effort to add your email didn't work properly. Can you please submit a new PR? Seems like probably the quickest/easiest fix for the CLA issue at this point. LMK if you want to discuss further. Thanks!

**Pull request closed without merging**
