### PR TITLE
don't make table-cell font-size smaller

### PR DESCRIPTION
**Pull request by ryan-williams**
partly addresses #12806

### CODE REVIEW

**Comment by ryan-williams** [comment]
hm I don't see this change reflected at https://deploy-preview-12807--kubernetes-io-master-staging.netlify.com/docs/concepts/extend-kubernetes/api-extension/custom-resources/

I see `font-size: 0.85em` in [(compiled?) CSS](https://github.com/kubernetes/website/blob/99a52da77fc26c500b81a9ce73d483b1ce7b4ccb/static/css/styles.css#L1). Maybe I need to regenerate those?

**Comment by kbhawkey** [comment]
> 
> 
> hm I don't see this change reflected at https://deploy-preview-12807--kubernetes-io-master-staging.netlify.com/docs/concepts/extend-kubernetes/api-extension/custom-resources/
> 
> I see `font-size: 0.85em` in [(compiled?) CSS](https://github.com/kubernetes/website/blob/99a52da77fc26c500b81a9ce73d483b1ce7b4ccb/static/css/styles.css#L1). Maybe I need to regenerate those?

Hello @ryan-williams. Currently you need to generate the CSS and commit these files to this PR.
What font size are you setting for the table cell text? Also, there are tables that have code markup.

**Comment by sftim** [comment]
This needs a rebase / merge conflicts fixing.
(Prow doesn't _seem_ to have noticed).

**Comment by ryanmcginnis** [comment]
hello! could we please resolve the conflicts or close this PR?

**Comment by xiangpengzhao** [comment]
Hi @ryan-williams , are you still working on this? :)

**Comment by ryan-williams** [comment]
I'll resurrect this this wknd, thanks

**Pull request closed without merging**
