### PR TITLE
[WIP] Document deprecation & likely future removal of kubelet RunOnce mode

### PR DESCRIPTION
**Pull request by HirazawaUi**

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [WIP] Document deprecation & likely future removal of kubelet RunOnce mode

**Comment by sftim** [comment]
/hold

pending merge of:
- https://github.com/kubernetes/enhancements/pull/4736 (or an equivalent PR)
- k/k code to add the new feature gate, and disable using the kubelet's RunOnce mode if said gate is forcibly disabled.

**Comment by hacktivist123** [comment]
Hello @HirazawaUi :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday, July 16th, 2024 18:00 PST. Thank you!

**Comment by hacktivist123** [comment]
Hello, @HirazawaUi 👋 your PR is close to being at risk for Doc freeze. please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday, July 16th, 2024 18:00 PST. Thank you!

**Comment by hacktivist123** [comment]
Hello @HirazawaUi  :wave:! I'm reaching out from the Docs team. Just checking in as we approach Docs Freeze on Tuesday July 30th 18:00 PDT. This documentation appears to still be under review. To meet the Docs Freeze, this PR must have a technical review as well as lgtm and approve labels applied, without any unaddressed comments or concerns from SIG Docs. The status of this enhancement is marked as at risk for docs freeze. Thank you!

**Pull request closed without merging**
