### PR TITLE
[zh] Update authentication.md

### PR DESCRIPTION
**Pull request by my-git9**
Update authentication.md

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
请在 `main` 分支运行下面的命令,同步此文件其他未同步的部分:
```
./scripts/lsync.sh content/zh/docs/reference/access-authn-authz/authentication.md
```

**Comment by tengqm** [comment]
@my-git9 Next time when you commit a revision to your PR, please do `git commit --amend`, followed by `git push -f`. Otherwise you are always creating more than one commit in your PR.

**Pull request merged**
