### PR TITLE
  Merge master into dev 1.21 - 4/7/21

### PR DESCRIPTION
**Pull request by reylejano**
Merge master into dev-1.21 to keep in sync - SIG-Release 1.21 Docs team 4/7/21

/cc @mvortizr @tengqm @PI-Victor @ChandaniM123 @sftim

### CODE REVIEW

**Comment by reylejano** [comment]
There was a merge conflict with the zh localization of the feature-gates.
I accepted both changes as the `master` branch had one additional feature-gate of `Sysctls` added and the `dev-1.21` had additional changes

**Comment by PI-Victor** [comment]
/lgtm
do we need an approval from zh localization group?

**Comment by annajung** [comment]
No, @PI-Victor not necessary for sync

/approve

**Pull request merged**
