### PR TITLE
Zpages docs

### PR DESCRIPTION
**Pull request by richabanker**
### Description

Docs for Kubernetes z-pages 

### Issue

https://github.com/kubernetes/enhancements/issues/4827
https://github.com/kubernetes/enhancements/issues/4828

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/remove-language bn de es fr hi id it ja ko pt pl ru uk zh
/remove-area release-eng 
/remove-area localization

**Comment by rdalbuquerque** [comment]
Hello @richabanker  :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday November 19th 2024 18:00 PST. Thank you!

**Comment by rdalbuquerque** [comment]
Hi @richabanker , just a friendly reminder to get you PR ready for review before Tuesday November 19th, thanks!

**Comment by rdalbuquerque** [comment]
Hi @richabanker , just a friendly reminder to get you PR ready for review before Tuesday November 19th, thanks!

**Comment by richabanker** [comment]
Accidentally ended up closing this PR. I have now created https://github.com/kubernetes/website/pull/48760 in its place, is this still ok?

**Pull request closed without merging**
