### PR TITLE
AdvancedAuditing is now GA

### PR DESCRIPTION
**Pull request by tengqm**
xref: kubernetes/kubernetes#65862

`AdvancedAuditing` feature is GA in 1.12. This PR adjusts the relateddocs.

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
Hi thanks, I am working on advanced audit doc here:
https://github.com/kubernetes/website/pull/9953

Still waiting https://github.com/kubernetes/kubernetes/pull/65763 get merged.

**Comment by zparnold** [comment]
@CaoShuFeng is this still waiting on #9953?

**Comment by zparnold** [comment]
@tengqm Would you be able to take a look at this merge conflict for me please?

**Comment by tengqm** [comment]
rebased on #9953

**Pull request merged**
