### PR TITLE
Update copy

### PR DESCRIPTION
**Pull request by guillenotfound**

### CODE REVIEW

**Comment by NitishKumar06** [comment]
Please mention the issue number you're solving in the PR description & sign the CLA before we can review it.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by ramrodo** [comment]
@guillenotfound could you sign the CLA, please?

https://contributor.easycla.lfx.linuxfoundation.org/#/cla/project/d8cead54-92b7-48c5-a2c8-b1e295e8f7f1/user/e0464991-7640-4832-826f-093a51a607bf

**Comment by NitishKumar06** [comment]
Feel free to unhold once you sign the CLA and provide the PR description.
/hold

**Comment by electrocucaracha** [comment]
@guillenotfound si tienes alguna duda, puedes contactarnos a través del canal de `#kubernetes-docs-es` en el Workspace de [Stack](https://kubernetes.slack.com/)

**Comment by natalisucks** [comment]
@guillenotfound This is another friendly ping to please sign the CLA. Future PR Wranglers may close this PR if the CLA isn't signed. Thanks!

**Comment by reylejano** [comment]
Closing this PR as the CLA is not signed by the PR author
@guillenotfound , you can reopen this PR with a `/reopen` in a comment but please sign the CLA first
/close

**Pull request closed without merging**
