### PR TITLE
Updates for file README-uk.md

### PR DESCRIPTION
**Pull request by Andygol**
Update to README-uk.md

With intention to reignite work on translation docs into Ukrainian, I updated README-uk.md with up-to-date content.

Now the content in Ukrainian corresponds to the content in English

PS. This PR must be CLA-compatible (no automations in commits)

closes: https://github.com/kubernetes/website/pull/45017

/language uk

### CODE REVIEW

**Comment by Andygol** [comment]
@MaxymVlasov 🛎️

**Review by sftim — COMMENTED** [review]
Дякую!

This will need a Ukrainian reviewer to provide LGTM (I'm not fluent).

**Review by Arhell — COMMENTED** [review]
В цілому.
/lgtm

**Review by MaxymVlasov — COMMENTED** [review]
Не маючи англ відповідника перед очима це неможливо ревьювати, і так як в процесі буде дріфт з англ, то відповідно буде складно зрозуміти що де змінилось.
Поки нема Transifex абощо, будь ласкавий дотримуватись діючих інструкцій з локалізації


https://kubernetes.io/uk/docs/contribute/localization_uk/#%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%BA%D0%BB%D0%B0%D0%B4%D1%83

**Comment by Andygol** [comment]
🇺🇦 Сподіваюсь, що в недалекому майбутньому все ж таки процес підтримки актуальності перекладів стане біль сучасним у порівнянні з тим, що є зараз. Використання спеціально призначених для цього систем значною мірою сприятиме розбудові спільноти, не тільки української, а й глобальної загалом.

🇬🇧 I hope that in the near future, the process of maintaining the relevance of translations will become more modern compared to what it is now. The use of specially designed systems for this purpose will greatly contribute to the development of the community, not only Ukrainian but also globally in general.

**Comment by Arhell** [comment]
> Oops, late nightly commits lead to this. I added documentation translations to the branch used in this pull request, so it seems like the PR title needs to be changed. Or, any other suggestions on how to handle this case? 🤔

As it is convenient for you, you can change or roll back the changes git reset --soft head~1 and force push to make the commit you need, but the translations may be lost if you do not save them.

**Comment by Andygol** [comment]
@Arhell thanks for suggestion. I've moved my translated materials to other branch and left here only original commit. 

Feel free to re-review and merge.

**Comment by sftim** [comment]
This will need a Ukrainian reviewer to provide LGTM and approval. Once that's in place, the website admins can confirm approval.

Ukrainian approvers: please /approve this if you're happy with it.
@Andygol, if you know how to use a rebase to turn this into a single squashed commit, then please do that.

**Comment by Arhell** [comment]
In general, I checked the original + translation, there are no questions from me.
@MaxymVlasov take a look when you have time

**Comment by sftim** [comment]
@andygol, you're asserting that you're the sole author of all this work?

**Comment by Andygol** [comment]
Yes. I am the only translator who translates into Ukrainian.

**Comment by Arhell** [comment]
@sftim  https://github.com/kubernetes/website/pull/45019#issuecomment-2107907800

**Comment by sftim** [comment]
@Arhell did you mean to ask @kubernetes/sig-docs-leads for a review? It's better to reference the role than a role holder (especially after they [step back](https://groups.google.com/g/kubernetes-sig-docs/c/lzUKjN_i8cA) :wink:).

**Comment by Arhell** [comment]
> @Arhell did you mean to ask @kubernetes/sig-docs-leads for a review? It's better to reference the role than a role holder (especially after they [step back](https://groups.google.com/g/kubernetes-sig-docs/c/lzUKjN_i8cA) 😉).

If I understand correctly, then yes, because I + https://github.com/kubernetes/website/pull/45019#pullrequestreview-2052934891

gave /approve
Here is mine https://github.com/kubernetes/website/pull/45019#issuecomment-1954745411

But we can’t merge it into a branch.

**Comment by Andygol** [comment]
cc @nate-double-u @niranjandarshann

**Comment by nate-double-u** [comment]
It looks like @Arhell's approve wasn't accepted. I'll try and see if my approve will help get this in.

/approve

**Comment by nate-double-u** [comment]
OK, that didn't work. I'll ping the @kubernetes/sig-docs-leads.

**Comment by nate-double-u** [comment]
Because the file being changed is in the website repo's root folder, it needed `sig-docs-website-owners` approval, not just localization folks approval.

**Pull request merged**
