### PR TITLE
Revise style of site front page

### PR DESCRIPTION
**Pull request by sftim**
On the front page of the site, the first paragraph was actually a heading. Replace that with a text paragraph that has a similar style.

(I checked that this does not regress other localizations).

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @sftim .
Just looked at the front page. What is the advantage of adding custom sizing for this paragraph?
The rendering is nearly identical.

**Comment by sftim** [comment]
The existing rendering is a bit less accessible because the first paragraph is not really a heading.

Some screen readers might insist on reading the whole thing, for example (I haven't checked).
Also if you hover over it you get offered a permalink that's not really needed.

**Comment by kbhawkey** [comment]
OK. There are other anchors on the home page, "Planet Scale", "Never Outgrow", "Run Anywhere".
The "Kubernetes Features" is not a heading. Should the home page have any headings/anchors?
Is there a way to turn off auto heading for a single page?

**Comment by sftim** [comment]
> "Planet Scale", "Never Outgrow", "Run Anywhere"

IMO, those count as are headings enough to not change the Markdown. We could look at using custom CSS for that page that will hide / not generate the links though.

**Comment by bradtopol** [comment]
Assigning @jimangel for this type of change.

**Pull request merged**
