### PR TITLE
Remove CI/CD Pipeline section in content/ja/docs/tutorials/_index.md

### PR DESCRIPTION
**Pull request by habibrosyad**
Part of #23167 for JA

### CODE REVIEW

**Review by inductor — COMMENTED** [review]
/approve

**Comment by habibrosyad** [comment]
/kind cleanup

Could you /lgtm @inductor? thanks...

**Comment by inductor** [comment]
@habibrosyad Hello. I will leave it to other Japanese reviewers. Our merging policy is basically getting lgtm by two or more people.

**Comment by habibrosyad** [comment]
Oh ok, thanks for letting me know @inductor 👍

**Pull request merged**
