### PR TITLE
Moving windows resource management to separate page

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

Moving windows resource management topics to a separate page.

Part of #31428

/label refactor
/sig windows

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
How about combining this information into https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ ?

Although Kubernetes started out as Linux only, Windows support is now GA and a cluster with only Windows nodes is a supported configuration.

**Comment by marosset** [comment]
> How about combining this information into https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ ?
> 
> Although Kubernetes started out as Linux only, Windows support is now GA and a cluster with only Windows nodes is a supported configuration.

I don't think clusters with only Windows nodes is a supported configuration.
Most of the control plane components can at least compile on Windows but we do not test or advocate running any of them on Windows nodes (AFAIK)

I will try to merge information in this PR into the existing manage-resources-containers page.

**Comment by sftim** [comment]
> I don't think clusters with only Windows nodes is a supported configuration.

I think it actually is, because you can run the control plane on Linux on, eg, bare metal with only the _nodes_ running Windows. We recommend running the control plane in containers but you don't actually have to.

**Comment by jihoon-seo** [comment]
Preview: https://deploy-preview-31850--kubernetes-io-vnext-staging.netlify.app/docs/concepts/configuration/windows-resource-management/

**Comment by marosset** [comment]
> > I don't think clusters with only Windows nodes is a supported configuration.
> 
> I think it actually is, because you can run the control plane on Linux on, eg, bare metal with only the _nodes_ running Windows. We recommend running the control plane in containers but you don't actually have to.

I think this depends on the definition of supported :)

I'll try to get these updates merged into the existing resource management page today or tomorrow.

**Comment by tengqm** [comment]
I see no blocking issues on the PR. Let's move this forward.
/lgtm
/approve

**Pull request merged**
