### PR TITLE
Fix ordering for localizable strings (in upstream English data)

### PR DESCRIPTION
**Pull request by Choon38**
…be placed much earlier and i had also sorted alphabetically.

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @Choon38 , please could you sign the CLA so that we can review this further?

**Comment by Choon38** [comment]
> Hello @Choon38 , please could you sign the CLA so that we can review this further?

hello @divya-mohan0209 
I just signed on to  the CLA.

**Comment by sftim** [comment]
/retitle Fix ordering for localizable strings (in upstream English data)

**Comment by kbhawkey** [comment]
👋 @Choon38 
The changes have been merged in PR #39013.
I'll close this pull request. If you have questions, you can reopen the PR.
/close

**Pull request closed without merging**
