### PR TITLE
Remove the inaccurate description 

### PR DESCRIPTION
**Pull request by cici37**
The escape is pending due to the cel nature: https://github.com/kubernetes/kubernetes/pull/121299
Remove the inaccurate description before the PR merged.

### CODE REVIEW

**Comment by jiahuif** [comment]
/lgtm

We can always take this section back once we have a properly escaping implementation for ValidatingAdmissionPolicy.

**Review by kumarankit999 — APPROVED** [review]
lgtm

**Comment by reylejano** [comment]
Thank you @cici37 
/approve

**Pull request merged**
