### PR TITLE
update mobile version - docs

### PR DESCRIPTION
**Pull request by alexcontini**
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7175)

### CODE REVIEW

**Comment by tengqm** [comment]
/unassign
/assign @chenopis 

Not familiar with css setting myself.

**Comment by Bradamant3** [comment]
@alexcontini I hate to nit, but can we get more padding at the bottom of this panel?
image
(It's OK at larger widths, but shrinks to the point where we lose text as the window gets smaller ...)

**Comment by alexcontini** [comment]
@Bradamant3 definitely! sorry for my many commits, I just added a fix for the spacing there and some other padding fixes for mobile, so ignore all prs before my last one. Thank you!

**Comment by Bradamant3** [comment]
fixed in #7200 
/close
confirmed with acontini

**Pull request closed without merging**
