### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by SR-Lut3t1um**
fixed type in https://kubernetes.io/de/docs/concepts/containers/images/

### CODE REVIEW

**Comment by SR-Lut3t1um** [comment]
I signed it

**Comment by rlenferink** [comment]
Thanks for fixing! 

/lgtm
/approve

**Comment by rlenferink** [comment]
Btw, if you signed the CLA and this keeps saying _CLA not signed_ can you check with Linux foundation support?

**Comment by rlenferink** [comment]
Thanks for fixing @SR-Lut3t1um ! :tada:

Next time won’t be this hard since the CNCF CLA is already in place!

**Pull request merged**
