### PR TITLE
remove dead link

### PR DESCRIPTION
**Pull request by josephgardner**
This heading was removed as part of https://github.com/kubernetes/website/pull/39501

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@josephgardner  Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by divya-mohan0209** [comment]
@josephgardner : Please sign the CLA before you begin contributing to the Kubernetes project. Since there has been no action on this PR taken from your end, we'd be closing this off.

Thanks!
/close

**Pull request closed without merging**
