### PR TITLE
storage capacity: beta

### PR DESCRIPTION
**Pull request by pohly**
After the promotion to beta in 1.21, enabling the feature is easier
and mostly just depends on the CSI driver deployment.

### CODE REVIEW

**Comment by pohly** [comment]
/hold 

The actual promotion hasn't happened yet. See https://github.com/kubernetes/kubernetes/pull/99641 for that.

**Comment by reylejano** [comment]
/milestone 1.21
/assign @tengqm 
/sig storage
hold until kubernetes/kubernetes#99641 merges and target branch is changed to `dev-1.21`

**Comment by pohly** [comment]
> Can you change the target branch to dev-1.21?

Yes, but only by creating a new PR. See PR #26800 

/close

**Comment by reylejano** [comment]
@pohly You can change the target branch by clicking on Edit on this PR and change from the dropdown 
Documentation is [here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request)

**Comment by pohly** [comment]
Oh, good to know. I wasn't aware of that feature. Sorry for the noise.

**Pull request closed without merging**
