### PR TITLE
[ja] Translate reference/glossary/app-container.md & application-architect.md & application-developer.md & applications.md & approver.md into Japanese

### PR DESCRIPTION
**Pull request by kujiraitakahiro**
This is a Feature Request

What would you like to be added

Translate following files into Japanese.
https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-app-container
https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-application-architect
https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-application-developer
https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-applications
https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-approver

Why is this needed
This page has not been translated.

Comments

/language ja
/assign

### CODE REVIEW

**Comment by kujiraitakahiro** [comment]
@t-inu 
レビュー、ありがとうございます！

**Review by t-inu — COMMENTED** [review]
/lgtm

**Comment by nasa9084** [comment]
Looks good, thank you~!
/approve

**Pull request merged**
