### PR TITLE
Remove duplicate text block, fix typo

### PR DESCRIPTION
**Pull request by thapakazi**
**Changes Made**
- [x] Remove Duplicates text block
- [x] typo

### CODE REVIEW

**Comment by thapakazi** [comment]
i just signed the cncf/cla

**Comment by kbhawkey** [comment]
👋 @thapakazi .
This change is ready for review. Would you rebase your changes? Thanks!

**Comment by sftim** [comment]
This change is ready for review. Would you be willing to rebase these changes?

(if you'd like advice on that, we can help; if you'd prefer to close this PR and open a brand new one, that's also OK).

**Comment by kbhawkey** [comment]
Hi @thapakazi .
I plan on closing this pull request.
When you are ready to work on these changes, feel free to reopen this PR. Thanks!
/close

**Pull request closed without merging**
