### PR TITLE
[zh-cn]Fixed a word in deploy-intro.html

### PR DESCRIPTION
**Pull request by popeng007**
a clerical error.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @tengqm

**Comment by popeng007** [comment]
i have updated the comment, please check again.

**Comment by tengqm** [comment]
@popeng007 Please recommit this PR. There was a transient netlify issue.

**Comment by popeng007** [comment]
> @popeng007 Please recommit this PR. There was a transient netlify issue.

Ok, thanks.

**Pull request closed without merging**
