### PR TITLE
Fix CCM implementation link error

### PR DESCRIPTION
**Pull request by hello2mao**
**What this PR does / why we need it:**
This pr fix CCM implementation link error according to https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/architecture/cloud-controller.md

### CODE REVIEW

**Comment by hello2mao** [comment]
@idealhack hi,  deploy failed but how to retry? Thanks.

**Comment by tengqm** [comment]
Let's try if we can trigger the netlify again by closing it.

**Comment by tengqm** [comment]
@hello2mao pls try rebase this to the HEAD of master and see if the netlify issue is solved.

**Comment by hello2mao** [comment]
> @hello2mao pls try rebase this to the HEAD of master and see if the netlify issue is solved.

Thanks for your advice. But I rebase failed with wrong cmd. I'll close and make a new one.

**Pull request closed without merging**
