### PR TITLE
Fixed multiple language jump about 'Running the website locally using Hugo' in README

### PR DESCRIPTION
**Pull request by xieyanker**
Fixed multiple language jump about `Running the website locally using Hugo` in README

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hello @xieyanker , I would rather have the individual localization teams update the text, even though the change is updating a reference to an existing link. Each team should have an opportunity to
review the changes in order for this pull request to be `approved`.

**Comment by sftim** [comment]
@xieyanker would you be able to revise in line with https://github.com/kubernetes/website/pull/19086#issuecomment-585251297 ?

**Comment by xieyanker** [comment]
@sftim What should I do? In my opinion, they will be updated by each individual localization team. Or I can commit mutiple PRs for each language.

**Comment by tengqm** [comment]
@xieyanker please submit separate PRs for different languages.

**Comment by xieyanker** [comment]
@tengqm OK, I will do it.

**Comment by xieyanker** [comment]
Most of them have been fixed and merged as follows:
https://github.com/kubernetes/website/pull/19219
https://github.com/kubernetes/website/pull/19271
https://github.com/kubernetes/website/pull/19329
https://github.com/kubernetes/website/pull/19441
https://github.com/kubernetes/website/pull/19589
https://github.com/kubernetes/website/pull/19635
https://github.com/kubernetes/website/pull/19204

Only the md about pl not, I open a pr:
https://github.com/kubernetes/website/pull/19914

**Comment by mfilocha** [comment]
https://github.com/kubernetes/website/pull/19914 was a duplicate of https://github.com/kubernetes/website/pull/19546.

**Comment by xieyanker** [comment]
@mfilocha OK, I will close this.

**Pull request closed without merging**
