### PR TITLE
[ja]move HostAliases page to tasks

### PR DESCRIPTION
**Pull request by chenxuc**
related PR: #28631

fix issue: #28630

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Optionally: add a redirect from the old to the new page.

**Comment by chenxuc** [comment]
> Optionally: add a redirect from the old to the new page.

As discussed in https://github.com/kubernetes/website/pull/28730#discussion_r662089797, we decided to not flood the redirect with the localization entries since it's very unlikely someone bookmarks that url.

**Comment by t-inu** [comment]
I compared with en page, and also confirmed this PR is the same modification as zh and ko.
/lgtm

**Pull request merged**
