### PR TITLE
Master translation optimization4

### PR DESCRIPTION
**Pull request by Ghosgt**
update zh translate

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
more info about CLA, check please
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jimangel** [comment]
Hey there! @Ghosgt, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
CLA not signed for over two months. Please feel free to reopen when it is ready.
/close

**Pull request closed without merging**
