### PR TITLE
Bump up deployment version in tutorials/clusters folder

### PR DESCRIPTION
**Pull request by nashasha1**
I will create a bunch of PRs for bumping up deployment version.  A pr contains all changes in a folder.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7321)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@nashasha1 This file is no longer used in the docs. Please use this PR to delete it:

docs/tutorials/clusters/my-scheduler.yaml

**Comment by nashasha1** [comment]
@steveperry-53  Done! Thanks for your help!

**Pull request merged**
