### PR TITLE
fix some errors

### PR DESCRIPTION
**Pull request by fancc**

### CODE REVIEW

**Comment by sftim** [comment]
Please rebase this pull request against _master_ to bring in a work-around for issue #22222.

**Comment by fancc** [comment]
> Please rebase this pull request against _master_ to bring in a work-around for issue #22222.

OK

**Comment by tengqm** [comment]
I'm gonna close this because the author is not responding to any feedbacks. The PR is not passing CI gate because of a transient error which can be solved only by a rebase.
/close

**Pull request closed without merging**
