### PR TITLE
Updated Helm Chart repository link to Artifact hub as issued #26470

### PR DESCRIPTION
**Pull request by OmkarPh**
Signed-off-by: Omkar Phansopkar <omkarphansopkar@gmail.com>

Changed link from Helm chart repository to Artifact Hub and modified display text accordingly.

### CODE REVIEW

**Comment by OmkarPh** [comment]
Verify CLA

**Comment by OmkarPh** [comment]
I signed up on CLA website with same email, not verified here ...
Can somebody help me out?

**Comment by irvifa** [comment]
@OmkarPh I think you should type: `I signed it` as mentioned on https://identity.linuxfoundation.org/projects/cncf

**Comment by OmkarPh** [comment]
I signed it

**Review by Arhell — COMMENTED** [review]
About CLA, check please
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by OmkarPh** [comment]
I signed it

**Comment by irvifa** [comment]
@OmkarPh Did you use the same email for pushing the commit and signing the CLA?

**Comment by OmkarPh** [comment]
Yes, I had set same user.email and even changed user.name to Official GitHub Username.
Nothing helped :(

**Comment by irvifa** [comment]
@OmkarPh may be you could try to type
/check-cla

**Comment by tengqm** [comment]
@OmkarPh Have you tried to recommit this PR using your CLA account ?

**Comment by OmkarPh** [comment]
I used the same email for Git GitHub CLA

**Comment by OmkarPh** [comment]
I signed it

**Comment by OmkarPh** [comment]
Can you merge it without CLA?

**Comment by tengqm** [comment]
@OmkarPh You have to sign the CLA in order for this PR to be reviewed/merged.
If you have done so, maybe you need to do `git commit --amend --reset-author` and then `git push -f` again.

**Comment by OmkarPh** [comment]
Is there a way to check CLA manually for you?

**Pull request closed without merging**
