### PR TITLE
Fix iptable s word errors

### PR DESCRIPTION
**Pull request by Cweiping**
iptable s  word error ，should be iptables

### CODE REVIEW

**Comment by tengqm** [comment]
@Cweiping pls sign the CLA in order for the PR to be reviewed.

**Comment by Cweiping** [comment]
I signed it

**Comment by Cweiping** [comment]
I signed it

**Comment by Cweiping** [comment]
> @Cweiping pls sign the CLA in order for the PR to be reviewed.

thx,i already sign CLA,but the bot not check me. @ten

**Comment by Cweiping** [comment]
I signed it

**Comment by tengqm** [comment]
@Cweiping you may want to check the account you used to sign the CLA and the one you used to raise the PR and see if they match.

**Comment by Cweiping** [comment]
I signed it

**Comment by Cweiping** [comment]
I signed it

**Comment by Cweiping** [comment]
> @Cweiping you may want to check the account you used to sign the CLA and the one you used to raise the PR and see if they match.

very thx,company email can not sign CLA, change to Personal‘s email. its working. 0.0....

**Pull request merged**
