### PR TITLE
Added new bangla localization

### PR DESCRIPTION
**Pull request by falconcode16**
I have added a new localization in bangla language which is important for the bangla minority using kubernetes.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/29804#issuecomment-927001069

**Comment by anubha-v-ardhan** [comment]
@falconcode16 You can go through [Localizing Kubernetes Documentation](https://kubernetes.io/docs/contribute/localization/) for requirements and steps to start a new localization.

**Comment by jimangel** [comment]
Hey there! @falconcode16, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by anubha-v-ardhan** [comment]
/close
@falconcode16 Closing this PR due to inactivity for long. Feel free to reopen if needed :)
Also, seems like the aim was to start a new localization. It's recommended to go through [Localizing Kubernetes Documentation](https://kubernetes.io/docs/contribute/localization/) for requirements and steps for it.

**Pull request closed without merging**
