### PR TITLE
Fix  command-line-tools-reference errors

### PR DESCRIPTION
**Pull request by pierreilki**
Hello K8S Community !

This PR corrects some errors in the "command-line-tools-reference".

Some CLI args were wrong, so i corrected it.  ("_" separator was used instead of "-")

Have a nice day :)

### CODE REVIEW

**Comment by pierreilki** [comment]
Hi @kbarnard10 

/assign @kbarnard10

**Comment by kbhawkey** [comment]
@tengqm Did the rendering of the flags change?

**Comment by tengqm** [comment]
@kbhawkey I'm checking.

**Comment by tengqm** [comment]
@kbhawkey The generator fix is proposed https://github.com/kubernetes-sigs/reference-docs/pull/231, with regenerated reference proposed https://github.com/kubernetes/website/pull/27817.

**Comment by kbhawkey** [comment]
@pierreilki , Thanks for opening this PR. 😃 
The files are generated by a docs tool and should be regenerated by the tool (after the tool is updated).

**Comment by pierreilki** [comment]
Hi all,

I see that the files have been generated by regenerated by the tool generator. So i close this PR. Thanks !

**Pull request closed without merging**
