### PR TITLE
Fix a minor type

### PR DESCRIPTION
**Pull request by halindrome**
There were two minor typos.  First, e.g., usually has a comma after it.  Second, it said "because the master has networking problem" instead of "because the master has a networking problem".

### CODE REVIEW

**Comment by php-coder** [comment]
Just to mention that usage of "e.g." isn't recommended: https://kubernetes.io/docs/contribute/style/style-guide/#avoid-latin-phrases

**Comment by bradtopol** [comment]
Hi @halindrome thanks for your contribution. If we are going to fix this we should fix properly and remove the e.g. per the style guidelines.  
https://kubernetes.io/docs/contribute/style/style-guide/#avoid-latin-phrases
Can you please address that as well? Thanks!

**Comment by sftim** [comment]
@halindrome would you be willing to fix the use of “e.g.”?

Alternatively, make this a two-character fix that simply adds “a ” before “networking problem” &ndash; in my view, that change is also OK to merge.

**Comment by kbarnard10** [comment]
@halindrome I'm going to close this for now because there hasn't been any movement in a while. Please feel free to reopen when you have a chance to address the comments. Thank you!

**Pull request closed without merging**
