### PR TITLE
Clean PodPreset docs, examples and links

### PR DESCRIPTION
**Pull request by tengqm**
Closes: #25942
Closes: #25939
Closes: #23285

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Thanks @tengqm 
/sig service-catalog
(but OK for anyone to LGTM it)

/kind cleanup
/approve

**Comment by sftim** [comment]
PR #26079 is similar

**Comment by deads2k** [comment]
can you remove the podpreset specific bits of content/en/examples/examples_test.go  ?

lgtm otherwise .

**Comment by tengqm** [comment]
@deads2k will do.

**Comment by kbhawkey** [comment]
Thanks @tengqm .
/lgtm

**Comment by irvifa** [comment]
@tengqm I notice that referenced PR is merged already

**Pull request merged**
