### PR TITLE
Update announcing-etcd-3.4.md

### PR DESCRIPTION
**Pull request by jingyih**
Remove mentioning of using concurrent read in compaction. The original PR https://github.com/etcd-io/etcd/pull/11021 was superseded by https://github.com/etcd-io/etcd/pull/11034, which no long uses concurrent read in compaction.

/cc @gyuho

### CODE REVIEW

**Comment by kbhawkey** [comment]
hello @jingyih .
The build/deploy preview appears to be stalled. Could you try to post an empty commit or rebase the PR? Thanks.

**Comment by jingyih** [comment]
> hello @jingyih .
> The build/deploy preview appears to be stalled. Could you try to post an empty commit or rebase the PR? Thanks.

Rebased.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-16205--kubernetes-io-master-staging.netlify.com/blog/

/lgtm

**Pull request merged**
