### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by nilsmartel**
for verification, see here: https://dict.leo.org/german-english/welches

### CODE REVIEW

**Comment by bene2k1** [comment]
Hello @nilsmartel 👋 
Can you please sign the CLA? I will approve your PR then.

**Comment by nilsmartel** [comment]
I signed the contribution document now, how can. I rerun the CLA test?

**Comment by bene2k1** [comment]
Thanks. The test runs automatically :) 
/lgtm
/approved

**Pull request merged**
