### PR TITLE
Update cheatsheet.md - added missing --v=9 option

### PR DESCRIPTION
**Pull request by wibobm**
Missing the untruncated output option on Verbosity.

> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6997)

### CODE REVIEW

**Comment by heckj** [comment]
thanks for the update @wibobm! if you could sign the CLA, we'll get this merged

**Comment by wibobm** [comment]
CLA has been signed.  Thanks.

**Pull request merged**
