### PR TITLE
Updated kube-dns to coredns equivalent on samples

### PR DESCRIPTION
**Pull request by bugre**
Some of the code samples for CoreDNS, where using the kube-dns app name
Added a CoreDNS sample for get endpoint sample code.

### CODE REVIEW

**Comment by bugre** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

signed

**Comment by jimangel** [comment]
@bugre it appears that the labels you've added don't exist for coreDNS by default, however the `k8s-app: kube-dns` labels persist in coreDNS (on Kubeadm deployed clusters).

How have you came to this solution?

/hold

**Comment by bugre** [comment]
@jimangel, thanks for checking my suggestion.
 I'm learning k8s and we've created two clusters, one with kubeadm and the other with the typhoon (k8s distribution/install bootstrap). 

We've selected to install CoreDNS and on both the labels are coredns, and haven't done any manual customisation on the labels.

And as i was following the tutorial to explore some dns problems we had, found that selecting with 'kube-dns' didn't list our dns pods.

Example of one of the clusters:
```
~ $ kubectl get pods -A --show-labels |grep dns
kube-system      coredns-fffcf5449-pdwg8                                   1/1     Running             0          9d      k8s-app=coredns,pod-template-hash=fffcf5449,tier=control-plane
kube-system      coredns-fffcf5449-pn597                                   1/1     Running             1          9d      k8s-app=coredns,pod-template-hash=fffcf5449,tier=control-plane
kube-system      coredns-fffcf5449-sq475                                   1/1     Running             0          42h     k8s-app=coredns,pod-template-hash=fffcf5449,tier=control-plane
```

Please, ignore this PR if our install is somewhat not standard

Have a nice day.

**Comment by bugre** [comment]
Hi @jimangel , 
i'll close this PR, as it is wrong. 

Found out that we've indeed changed the labels on our installs to show 'coredns' and not 'kube-dns' as k8s-app label.

I'm sorry to have wasted your time with this, and thanks for your patience and attention in verifying it.

have a nice week.

**Pull request closed without merging**
