### PR TITLE
fix typo in ja expose-intro.html

### PR DESCRIPTION
**Pull request by TatsuyaYamamoto**
Replace "Sercice" with "Service".

### CODE REVIEW

**Comment by stewart-yu** [comment]
/lgtm
/approve
need CLA

**Comment by tnir** [comment]
@TatsuyaYamamoto Thanks for you for your contribution.

Could you check https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA?

Kubernetesプロジェクトへのコントリビューションに必要なLinux FoundationのCLAのご確認をお願いします。

**Comment by TatsuyaYamamoto** [comment]
/check-cla

@tnir sorry for my late required action. I  signed the CLA.

**Comment by nasa9084** [comment]
/chack-cla
is this not working properly?

**Comment by nasa9084** [comment]
@TatsuyaYamamoto CLAにサインしたemailと、commitに紐付いているemailが同じか確認してもらってもいいでしょうか。

**Comment by tengqm** [comment]
@TatsuyaYamamoto I'm closing this PR because the CLA status check has not been resolved for over a month. Please

- feel free to reopen this if you are still working on it, and
- try follow instructions [here](https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting) to debug your CLA status if you have already signed it.

**Comment by inductor** [comment]
This is fixed in https://github.com/kubernetes/website/commit/46f21284df0c6792a92ffea14b4f985735143ac4

**Pull request closed without merging**
