### PR TITLE
Merged main into dev 1.24

### PR DESCRIPTION
**Pull request by nate-double-u**
Week 8 update to bring `main` into `dev-1.24` branch.

### CODE REVIEW

**Comment by nate-double-u** [comment]
Errors on commits https://github.com/kubernetes/website/pull/31974/commits/73e258aac8798e428a0150991a3287fb19d1ec7a & https://github.com/kubernetes/website/pull/31974/commits/ca53f4a5fc7ccb26047c992a3e16089f6dd50266 look like they are a part of an un-squashed set from PR https://github.com/kubernetes/website/pull/31436. Preview built successfully.

/cc @JamesLaverack, FYI
/cc @jlbutler @sftim @reylejano

**Comment by kbhawkey** [comment]
Yes, it looks like the two errors were fixed.
/lgtm

**Comment by reylejano** [comment]
Agree that the errors were fixed
/approve

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
