### PR TITLE
Guslcho/bug/v0.1

### PR DESCRIPTION
**Pull request by guslcho**
https://github.com/kubernetes/website/issues/19973
https://github.com/kubernetes/website/issues/19974

Documentation > reference In the Korean menu
Kubernetes Issues and Security , In this menu, both Korean and English coexist.
So I left the Korean menu and deleted the English menu

### CODE REVIEW

**Comment by ClaudiaJKang** [comment]
Thank you for contributing localization team.
But, you need to sign the CLA before the review steps.

**Comment by ysyukr** [comment]
Request a CLA signing and a rebase to dev-1.18-ko.3.

If there is no response, this PR is forced to close by [guide](https://kubernetes.io/docs/contribute/advanced/#when-to-close-pull-requests).

**Comment by ysyukr** [comment]
@guslcho
This PR did not allow authors to sign the CLA for more than two weeks.
Also, this PR is 'close' because there has been no feedback on the reviewer's comments for two weeks.
The author can sign the CLA and open it with a different PR.

/close

**Pull request closed without merging**
