### PR TITLE
add deprecation warning for docker in container runtime section

### PR DESCRIPTION
**Pull request by brandonJY**
add deprecation warning for docker in container runtime section

### CODE REVIEW

**Comment by shannonxtreme** [comment]
I'm not sure this is necessary, because the mention of Docker in the glossary entry will be removed in #31282. 

Maybe @sftim has a more informed opinion though

**Comment by afbjorklund** [comment]
docker is not deprecated, dockershim is

**Comment by shannonxtreme** [comment]
This PR is no longer required, since recently merged changes removed docker
from the examples listed here. Appreciate the effort @brandonJY

/close

**Pull request closed without merging**
