### PR TITLE
Use masked white logo for ancestry

### LINKED ISSUE #10532: Missing Ancestry's company logo on their case study
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

You will miss Ancestry's company logo on https://kubernetes.io/case-studies/ancestry/

**Proposed Solution:**

Fix CSS for logo.

**Page to Update:**

- https://kubernetes.io/case-studies/ancestry/

### PR DESCRIPTION
**Pull request by tnir**
Closes #10532 

This PR fixes the following two problems:

- to avoid the external resource (as well as all other case study logos)
    - https://c.mfcreative.com/i/logo/ancestry-on-dark.svg
- to use white mono-color logo image (as well as all other case study logos)
    - cf. [ING's case study](https://kubernetes.io/case-studies/ing/)

---

### image

The image was generated from the existing logo with low resolutions 😭  ([content/en/case-studies/ancestry/ancestry_logo.png](https://github.com/kubernetes/website/blob/master/content/en/case-studies/ancestry/ancestry_logo.png)).

### before

https://kubernetes.io/case-studies/ancestry/

ancestry_case_study_before

### after

https://deploy-preview-10544--kubernetes-io-master-staging.netlify.com/case-studies/ancestry/

ancestry_case_study_after

Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

### CODE REVIEW

**Comment by tnir** [comment]
@kbarnard10 Do you have Ancestry's high quality logo image file for this? https://www.ancestrycdn.com/ui-static/i/logo/ancestry.svg will be one of them, but I don't think we can use it without any permission from them.

/assign @kbarnard10

**Comment by zacharysarah** [comment]
@tnir Thanks for tackling the external resource issue. Agreed, this PR needs a higher-quality image file before it can merge.

@kbarnard10 :wave: Any guidance with the logo asset?

/hold

**Comment by kbarnard10** [comment]
@tnir That logo should be fine. They would've approved the case study with permission for us to use the logo.

**Pull request merged**
