### PR TITLE
[ja] Translate title and linkTitle for Blogs page

### PR DESCRIPTION
**Pull request by Saliha067**
Improvement suggestions for the following

- Blogs --> Kubernetesブログ
- The preview page: [Link](https://deploy-preview-39650--kubernetes-io-main-staging.netlify.app/ja/blog/)

Screenshot 2023-02-24 at 2 36 41 PM

Screenshot 2023-02-24 at 2 37 12 PM

### CODE REVIEW

**Comment by sftim** [comment]
LGTM

**Review by t-inu — COMMENTED** [review]
Thank you. This is a good point of view.

**Comment by t-inu** [comment]
I tested where these fields are used.
```
---
title: Kubernetesブログ(title)
linkTitle: ブログ(linkTitle)
menu:
  main:
    title: "ブログ(title-in-main)"
    weight: 40
    post: >
       <p>Kubernetesやコンテナ全般に関する最新ニュースを読んで、技術的なハウツーをいち早く入手しましょう。</p>
---
```
image

image

image

I don't know where the `title` field in the `main` is used, but it would be good to keep it the same as the original file.

**Comment by t-inu** [comment]
/retitle [ja] Translate title and linkTitle for Blogs page

**Comment by Saliha067** [comment]
@t-inu may can you recheck?

**Comment by t-inu** [comment]
I seem the modified file is fine.
We'd like to solve Netlify's deploy failed.
The following comment may be helpful to you.
https://github.com/kubernetes/website/pull/39528#issuecomment-1449197631

**Review by t-inu — COMMENTED** [review]
The error no longer occurs.
Currently, the modifications can be checked on the preview site.
/lgtm

**Review by nasa9084 — COMMENTED** [review]
/approve

**Pull request merged**
