### PR TITLE
Add instructions for staging site using Docker

### PR DESCRIPTION
**Pull request by tfogo**
Adds a condensed version of the Docker instructions in the README to the Create a PR doc page.

### CODE REVIEW

**Comment by tfogo** [comment]
/hold
The instructions depend on https://github.com/kubernetes/website/pull/9216 as they use `make docker-serve` instead of `make stage`.

**Comment by tfogo** [comment]
/hold cancel
#9216 has now been merged so these instructions are now correct. I probably should have included these changes in #9216 but I forgot I had this PR open. 😅

@bradtopol could you please take a look? Thanks 😀

**Comment by tfogo** [comment]
#9510 refactored the contributor guide. I rebased and added the docker instructions to the new guide.

**Comment by zacharysarah** [comment]
@tfogo 👋 Thanks for your patience. 

@lucperkins Would you mind reviewing this, please? Thanks in advance! 🙇

**Comment by lucperkins** [comment]
@tfogo Could you update the `make` commands you added to use backtick-bounded code blocks, to conform with the rest of the document?

**Comment by tfogo** [comment]
@lucperkins will do

**Pull request merged**
