### PR TITLE
Fix a small typo in the docs

### PR DESCRIPTION
**Pull request by NavidZ**

### CODE REVIEW

**Comment by NavidZ** [comment]
I signed it

**Comment by tengqm** [comment]
@NavidZ Thanks for the contribution. Please check your CLA status and fix it.

**Comment by NavidZ** [comment]
I signed it

**Comment by NavidZ** [comment]
> @NavidZ Thanks for the contribution. Please check your CLA status and fix it.

Thanks. I thought I did it the first. But apparently not. It is resolved now.

**Review by savitharaghunathan — COMMENTED** [review]
Thanks for the PR, @NavidZ 

/lgtm

**Pull request merged**
