### PR TITLE
Update intro-windows-in-kubernetes.md - minor grammatical correction

### PR DESCRIPTION
**Pull request by BusiPlay**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.13-ko.<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by bradtopol** [comment]
@BusiPlay Thank you for your contribution. Please sign the CLA so we can accept your PR for review.

**Comment by Rajakavitha1** [comment]
@BusiPlay Thanks for your PR. Please sign the CLA https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by BusiPlay** [comment]
I have signed CLA

**Comment by Rajakavitha1** [comment]
checked : https://deploy-preview-13750--kubernetes-io-master-staging.netlify.com/docs/setup/windows/intro-windows-in-kubernetes/

/lgtm
/approve

**Pull request merged**
