### PR TITLE
[WIP] document endpointslice 'serving' and 'terminating' conditions

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>

Placeholder docs for KEP https://github.com/kubernetes/enhancements/issues/1672 and https://github.com/kubernetes/enhancements/issues/1669

EPSlice updates:
* add a `Conditions` section to the EndpointSlices doc
* add sections for all conditions `Ready`, `Serving` and `Terminating`.

External Load Balancer updates:
* adds a section "Handling of Terminating Endpoints"

### CODE REVIEW

**Comment by andrewsykim** [comment]
PR for KEP 1672: https://github.com/kubernetes/kubernetes/pull/92968

Working on the PR for KEP-1669.

**Comment by annajung** [comment]
Hey @andrewsykim please change the base to `dev-1.20` branch

**Comment by kcmartin** [comment]
Hi @andrewsykim 
Friendly reminder that the deadline for having docs ready for review is coming up on Nov 23rd, right after Kubecon NA. We would appreciate it if you could provide some/all docs content for this feature early so that it can be reviewed by Sig Docs before Kubecon and other events in November.

**Comment by annajung** [comment]
k/k pr merged

keeping /hold until the base is changed to `dev-1.20`

**Comment by annajung** [comment]
Hi @andrewsykim 

This doc was for both KEP 1672 and KEP-1669
Even though KEP 1672 k/k pr was merged, KEP-1669 k/k was not merged https://github.com/kubernetes/kubernetes/pull/96371 in time. 

KEP 1669 was removed from the 1.20 release, see https://github.com/kubernetes/enhancements/issues/1669#issuecomment-726530900 for details

/hold 
Please change the title and description of the pr to only reflect KEP 1672. Thank you!

**Comment by kcmartin** [comment]
Hi @andrewsykim 

A friendly reminder that Docs "Ready for Review" Deadline is this Monday, Nov. 23rd for the 1.20 release.

Please reach out if you have any questions.

**Comment by robscott** [comment]
@andrewsykim I'm working on a PR that will likely conflict with this (https://github.com/kubernetes/website/pull/24935). I think everything you have already is safe, but the enabling EndpointSlices page seems like it could get messy. For that reason, I think it might be simplest if I cover both new feature gates in my PR (`EndpointSliceNodeName` and `EndpointSliceTerminating`). Let me know if that makes sense to you. If not, I'm happy to pull that part out of mine.

**Comment by kcmartin** [comment]
@andrewsykim -- What do you think about Rob's comment above? Do you want him to cover both features gates in his [PR](https://github.com/kubernetes/website/pull/24935) and do a review?

Also, please let us know if this PR is no longer necessary, we can close it out. Thanks!

**Comment by robscott** [comment]
I think what's scoped here is still necessary, I just documented the feature gates that correspond with what's being documented here. Now that my PR is merged in, feel free to change any part of the feature gate docs as well.

**Comment by annajung** [comment]
Exception requested/granted. PR will be ready for review by EOD Wednesday the 25th

**Comment by andrewsykim** [comment]
> I think what's scoped here is still necessary, I just documented the feature gates that correspond with what's being documented here. Now that my PR is merged in, feel free to change any part of the feature gate docs as well.

Makes sense, I'll leave out anything with feature gates and only focus on documenting the new conditions. Thanks @robscott!

**Comment by andrewsykim** [comment]
Closing in favor of https://github.com/kubernetes/website/pull/25229

**Pull request closed without merging**
