### PR TITLE
Update outdated files in the dev-1.19-ko.2 branch

### LINKED ISSUE #23818: Outdated files in the dev-1.19-ko.2 branch
# This is a Bug Report
## Problem
Outdated files in the upstream/dev-1.19-ko.2 branch.

### 29 files to be modified 
1. [ ] content/en/docs/concepts/cluster-administration/addons.md 1 file changed, 2 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/concepts/cluster-administration/networking.md 1 file changed, 4 insertions(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/configuration/configmap.md 1 file changed, 6 insertions(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/configuration/secret.md 1 file changed, 34 insertions(+), 31 deletions(-)
1. [ ] content/en/docs/concepts/containers/_index.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/scheduling-eviction/kube-scheduler.md 1 file changed, 4 insertions(+), 7 deletions(-)
1. [ ] content/en/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md 1 file changed, 4 insertions(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/services-networking/dual-stack.md 1 file changed, 1 insertion(+)
1. [ ] content/en/docs/concepts/services-networking/endpoint-slices.md 1 file changed, 2 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/concepts/services-networking/ingress.md 1 file changed, 1 deletion(-)
1. [ ] content/en/docs/concepts/services-networking/service.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/storage/volumes.md 1 file changed, 1 insertion(+), 2 deletions(-)
1. [ ] content/en/docs/concepts/workloads/pods/_index.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/home/supported-doc-versions.md 1 file changed, 4 insertions(+), 22 deletions(-)
1. [ ] content/en/docs/reference/command-line-tools-reference/feature-gates.md 1 file changed, 1 insertion(+), 4 deletions(-)
1. [ ] content/en/docs/reference/glossary/cloud-provider.md 1 file changed, 1 deletion(-)
1. [ ] content/en/docs/reference/using-api/client-libraries.md 1 file changed, 2 insertions(+)
1. [ ] content/en/docs/setup/best-practices/certificates.md 1 file changed, 2 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/setup/learning-environment/minikube.md 1 file changed, 5 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/setup/production-environment/container-runtimes.md 1 file changed, 6 insertions(+), 1 deletion(-)
1. [ ] content/en/docs/tasks/administer-cluster/declare-network-policy.md 1 file changed, 1 insertion(+), 5 deletions(-)
1. [ ] content/en/docs/tasks/network/validate-dual-stack.md 1 file changed, 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/stateful-application/basic-stateful-set.md 1 file changed, 2 insertions(+), 2 deletions(-)

### 1 files to be renamed  
1. [ ] R100 content/en/docs/concepts/configuration/resource-bin-packing.md -> content/en/docs/concepts/scheduling-eviction/resource-bin-packing.md

### 2 files to be deleted 
1. [ ] content/en/docs/concepts/cluster-administration/cloud-providers.md
1. [ ] content/en/docs/setup/production-environment/on-premises-vm/_index.md

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `upstream/dev-1.19-ko.2` branch.

For example:
```
# checkout `upstream/dev-1.19-ko.2`
...
# check what is updated in the upstream 
git diff upstream/dev-1.19-ko.1 upstream/dev-1.19-ko.2 -- content/en/docs/concepts/cluster-administration/addons.md
# apply changes to content/ko
vi content/ko/docs/concepts/cluster-administration/addons.md
...
# commit and push
...
# make PR to `upstream/dev-1.19-ko.2`
```

/language ko

### PR DESCRIPTION
**Pull request by pjhwa**
Closes #23818 

Update the following outdated files in the upstream/dev-1.19-ko.2 branch.

27 files are updated
- [x] content/en/docs/concepts/cluster-administration/addons.md 1 file changed, 2 insertions(+), 2 deletions(-)
- [x] content/en/docs/concepts/cluster-administration/networking.md 1 file changed, 4 insertions(+), 3 deletions(-)
- [x] content/en/docs/concepts/configuration/configmap.md 1 file changed, 6 insertions(+), 3 deletions(-)
- [x] content/en/docs/concepts/configuration/secret.md 1 file changed, 34 insertions(+), 31 deletions(-)
- [x] content/en/docs/concepts/containers/_index.md 1 file changed, 1 insertion(+), 1 deletion(-)
- [x] content/en/docs/concepts/scheduling-eviction/kube-scheduler.md 1 file changed, 4 insertions(+), 7 deletions(-)
- [x] content/en/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md 1 file changed, 4 insertions(+), 1 deletion(-)
- [x] content/en/docs/concepts/services-networking/dual-stack.md 1 file changed, 1 insertion(+)
- [x] content/en/docs/concepts/services-networking/ingress.md 1 file changed, 1 deletion(-)
- [x] content/en/docs/concepts/services-networking/service.md 1 file changed, 1 insertion(+), 1 deletion(-)
- [x] content/en/docs/concepts/storage/volumes.md 1 file changed, 1 insertion(+), 2 deletions(-)
- [x] content/en/docs/home/supported-doc-versions.md 1 file changed, 4 insertions(+), 22 deletions(-)
- [x] content/en/docs/reference/command-line-tools-reference/feature-gates.md 1 file changed, 1 insertion(+), 4 deletions(-)
- [x] content/en/docs/reference/glossary/cloud-provider.md 1 file changed, 1 deletion(-)
- [x] content/en/docs/reference/using-api/client-libraries.md 1 file changed, 2 insertions(+)
- [x] content/en/docs/setup/best-practices/certificates.md 1 file changed, 2 insertions(+), 2 deletions(-)
- [x] content/en/docs/setup/learning-environment/minikube.md 1 file changed, 5 insertions(+), 5 deletions(-)
- [x] content/en/docs/setup/production-environment/container-runtimes.md 1 file changed, 6 insertions(+), 1 deletion(-)
- [x] content/en/docs/tasks/administer-cluster/declare-network-policy.md 1 file changed, 1 insertion(+), 5 deletions(-)
- [x] content/en/docs/tasks/network/validate-dual-stack.md 1 file changed, 1 deletion(-)
- [x] content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
- [x] content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
- [x] content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
- [x] content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
- [x] content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
- [x] content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
- [x] content/en/docs/tutorials/stateful-application/basic-stateful-set.md 1 file changed, 2 insertions(+), 2 deletions(-)

1 file is renamed
- [x] content/en/docs/concepts/configuration/resource-bin-packing.md -> content/en/docs/concepts/scheduling-eviction/resource-bin-packing.md

2 files are deleted
- [x] content/en/docs/concepts/cluster-administration/cloud-providers.md
- [x] content/en/docs/setup/production-environment/on-premises-vm/_index.md

2 files are already updated in Korean documents
- [x] content/en/docs/concepts/services-networking/endpoint-slices.md 1 file changed, 2 insertions(+), 2 deletions(-)
- [x] content/en/docs/concepts/workloads/pods/_index.md 1 file changed, 1 insertion(+), 1 deletion(-)

### CODE REVIEW

**Comment by gochist** [comment]
@pjhwa 감사합니다! 되도록이면 제출자와 소속 회사가 다른 분이 승인해주시면 좋겠습니다.
/lgtm
/unassign

**Comment by pjhwa** [comment]
/assign @seokho-son 
해당 PR 승인 부탁드립니다.

**Comment by seokho-son** [comment]
감사합니다.. ^^
/approve

**Pull request merged**
