### PR TITLE
Fix dead links and remove double bullets in TOC

### PR DESCRIPTION
**Pull request by makocchi-git**
* Fix dead links
* Apply a template (remove double bullets in TOC)

### CODE REVIEW

**Comment by makocchi-git** [comment]
[preview url is here](https://deploy-preview-9176--kubernetes-io-master-staging.netlify.com/docs/reference/tools/)
[original](https://kubernetes.io/docs/reference/tools/)

**Comment by Rajakavitha1** [comment]
@makocchi-git Thanks for the update.
/lgtm

**Comment by Bradamant3** [comment]
bot what is with you?

/approve

**Pull request merged**
