### PR TITLE
[WIP] Document pod priority based graceful node shutdown

### PR DESCRIPTION
**Pull request by mrunalp**
Placeholder PR for 
Enhancement: https://github.com/kubernetes/enhancements/issues/2712

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [WIP] Document pod priority based graceful node shutdown

**Comment by jlbutler** [comment]
@mrunalp Reminder that tomorrow Nov 23rd is the deadline for 1.23 Docs Ready for Review. Please push your docs content for this enhancement and remove the work-in-progress label when ready for review.

We have a tight turnaround to getting docs reviewed and approved for the release, and we're hoping to have all docs in for review by EOB tomorrow. Thank you!

**Comment by bobbypage** [comment]
We have a PR here for docs for this feature: https://github.com/kubernetes/website/pull/30611

**Pull request closed without merging**
