### PR TITLE
Git clone command updated > Docs article "Opening a pull request"

### PR DESCRIPTION
**Pull request by dkypuros**
Description:
The PR updates the git clone command required to follow along the documentation article "Opening a pull request". Yes, this is a PR to correct how to perform a PR. :-)
 
The command: ```git clone git@github.com/<github_username>/website```
...no longer works. 

See example error message: "fatal: repository 'git@github.com/dkypuros/website' does not exist"

This is the correct "git clone" command: ```git clone https://github.com/<github_username>/website```

### CODE REVIEW

**Comment by dkypuros** [comment]
I signed it

**Comment by bradtopol** [comment]
/assign
Hi @dkypuros did you check out the CLA troubleshooting tips in the CLA description link? They are here:
https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

**Comment by bradtopol** [comment]
Hi @dkypuros  Also, you may want to make sure the git commit has the proper email address associated with it doing something like the following:

git commit -s --amend --author="Author Name <email@address.com>"
git push -f

**Comment by dkypuros** [comment]
Waiting on "login-issues@jira.linuxfoundation.org"

My account is locked for some reason. https://support.linuxfoundation.org/

https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Comment by perret34** [comment]
Hello,
Excuse me for this way of contacting you, I don't think it was a coincidence that I contacted you. It is good after several days of intense prayer that I do it is that the Holy Spirit guided me towards you by the grace of God. I donate my goods to an honest and needy person of French origin and I live in France. I suffer from a serious illness which condemns me to certain death, it is throat cancer, and I have a sum of 700,000 euros which I would like to make a donation to a person of trust and honest so let him make good use of it in order to help his family and start a new life in happiness and peace. I donate these funds for free to change your life. I donate this because after all the love of neighbor is the basis of all my Christian life.
I would then like to know if you can benefit from this donation?
Contact by email for the procedures to obtain 700,000 euros for free.

Mail: Perretgerome@gmail.com

God bless you.

**Pull request closed without merging**
