### PR TITLE
Official v1.29 Release Docs

### PR DESCRIPTION
**Pull request by katcosgrove**
## 🛑 DO NOT MERGE 🛑 UNTIL KUBERNETES 1.29 IS RELEASED
Target Date: 2023-12-13

### Release deadlines
From [sig-release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.29#timeline):

| Description                                         | Date                       |
|-----------------------------------------------------|----------------------------|
| Docs deadline — Open placeholder PRs                | Thursday 19th October 2023 |
| Docs deadline — PRs ready for review                | Tuesday 14th November 2023 |
| Docs complete — All PRs reviewed and ready to merge | Tuesday 28th November 2023 |
| **v1.29.0 released**                                | Wednesday 13th December 2023  |

### For More Information, reach out to the Docs team:
cc: @taniaduggal @drewhagen @harshitasao 

/hold

### CODE REVIEW

**Comment by tengqm** [comment]
This needs a rebase.

**Comment by sftim** [comment]
> This needs a rebase.

(BTW) we don't rebase the dev branches for upcoming releases.

**Pull request merged**
