### PR TITLE
Update validate-dual-stack.md

### PR DESCRIPTION
**Pull request by jiaj12**
update zh content to match en master

### CODE REVIEW

**Comment by howieyuen** [comment]
I think you have already done a full sync of this file, right?

**Comment by tengqm** [comment]
中文译文中不要使用“您”尊称，参考 https://kubernetes.io/zh/docs/contribute/localization_zh/

**Comment by jiaj12** [comment]
applied new changes

**Comment by tengqm** [comment]
@howieyuen I think so.

@jiaj12 Your latest change is not committed.

**Comment by jiaj12** [comment]
it works this time

**Comment by tengqm** [comment]
请养成 `git commit --amend` `git push -f` 的习惯。不然会造成一个 PR 多个 commits 的情况。

**Comment by howieyuen** [comment]
please squash commits

**Comment by tengqm** [comment]
Reapprove
/lgtm
/approve

**Pull request merged**
