### PR TITLE
Blog on Chaos Engineering for Kubernetes: Hands-on with LitmusChaos 2.0

### PR DESCRIPTION
**Pull request by neelanjan00**
## Blog Description
This blog covers the most fundamental aspects of LitmusChaos 2.0, a CNCF Sandbox project for performing Cloud-Native Chaos Engineering using a Kubernetes-Native approach, which was recently made GA. The blog provides step-by-step instructions on how to install LitmusChaos 2.0, how to execute a chaos workflow using the Chaos Center Web UI, and how to view the workflow analytics using the built-in Analytics Dashboard.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/29497#issuecomment-902948798

**Comment by neelanjan00** [comment]
@Arhell I have signed the CLA now, can you please verify?

**Comment by sftim** [comment]
Thanks for signing the CLA @neelanjan00. It's nice to see a new way to inject chaos into a Kubernetes cluster in a controlled way rather than, say, a misplanned control plane upgrade :wink:.

Looking at this article I think it would be a better fit for https://dev.to/t/litmuschaos/ or https://litmuschaos.io/ than for https://kubernetes.io/blog/ - the article seems to be about setting up LitmusChaos more than it is about Kubernetes.

If you'd like an analogy: there's lots of software that runs on Ubuntu (or Windows); most of those products blog about hands-on tutorials and the like on their own page, not on the Ubuntu blog / Windows blog.

/hold
because of a concern about fit.

**Comment by prithvi1307** [comment]
@sftim The idea was to have a blog around Chaos Engineering for Kubernetes, something similar to this blog: https://kubernetes.io/blog/2018/09/18/hands-on-with-linkerd-2.0/  featuring LinkerD. If there are any changes that can be done to the blog to make it relevant, please suggest the same. Other than that we tried following the guidelines as suggested and wrote the blog in accordance to the LinkerD blog already published.

**Comment by sftim** [comment]
We actually revised our content guidelines since https://kubernetes.io/blog/2018/09/18/hands-on-with-linkerd-2.0/ was published.

**Comment by reylejano** [comment]
[Content guide](https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed) states:
> Kubernetes docs allow content for third-party projects only when:
> - Content documents software in the Kubernetes project
> - Content documents software that's out of project but necessary for Kubernetes to function
> - Content is canonical on kubernetes.io, or links to canonical content elsewhere

I agree with @sftim 's [comment](https://github.com/kubernetes/website/pull/29497#issuecomment-904838914) that this blog is a better fit for https://dev.to/t/litmuschaos/ or https://litmuschaos.io/ and this blog does not fit the content guide quoted above.

/close

If others in SIG Docs disagree, feel free to re-open the PR

**Pull request closed without merging**
