### PR TITLE
Placeholder PR for KEP 1847

### PR DESCRIPTION
**Pull request by mattcary**
[KEP 1847](https://github.com/kubernetes/enhancements/issues/1847)

[k/k API change PR](https://github.com/kubernetes/kubernetes/pull/99378)
[k/k implementation PR](https://github.com/kubernetes/kubernetes/pull/99728)

### CODE REVIEW

**Comment by PI-Victor** [comment]
this has been removed from the milestone, closing for now, but if there's an exception granted, please re-open it
/close

**Comment by tengqm** [comment]
This is dilemma ... we have kubernetes/kubernetes#99378 merged, which introduced a new feature gate (visible to users), but we have kubernetes/kubernetes#99728 pending approval and now removed from the milestone.

What would we say to the users?

**Comment by mattcary** [comment]
Thanks for opening up this question! I've replied over on the other thread https://github.com/kubernetes/enhancements/issues/1847#issuecomment-878565288

**Pull request closed without merging**
