### PR TITLE
Update ingress-controllers.md

### PR DESCRIPTION
**Pull request by iyangsj**
Add BFE (CNCF sandbox project) ingress controller

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hello @iyangsj did you manage to fix the CLA issue?

**Comment by reylejano** [comment]
@iyangsj , did you receive the verification email?
Also check if your git config is using the same email

**Comment by clarinette9** [comment]
Sijie, I've add this information via PR-30374 https://github.com/kubernetes/website/pull/30374 . 
I think this PR can be discard.

**Comment by reylejano** [comment]
Closing this PR as merged PR https://github.com/kubernetes/website/pull/30374 duplicates the change in this PR
and this PR needs to rebase probably because of merged PR https://github.com/kubernetes/website/pull/30374
/close

**Pull request closed without merging**
