### PR TITLE
fix readme pl link

### PR DESCRIPTION
**Pull request by Arhell**
#19527
/language pl

### CODE REVIEW

**Comment by mfilocha** [comment]
@Rajakavitha1

**Comment by mfilocha** [comment]
@Arhell We need someone with approve rights for top level of k/website.

**Comment by sftim** [comment]
@kubernetes/sig-docs-pl-owners - please add an /approve to record that you're happy to see this merged.

**Comment by mfilocha** [comment]
@sftim We did it already (@nvtkaszpir and me).

**Comment by sftim** [comment]
Ah, sorry - I missed https://github.com/kubernetes/website/pull/19546#issuecomment-598783184

/approve

**Pull request merged**
