### PR TITLE
Fix network ingress and egress link error

### PR DESCRIPTION
**Pull request by chenyb4**
Issues record: #9748

Signed-off-by: Yuanbin.Chen <cybing4@gmail.com>

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

### CODE REVIEW

**Comment by chenyb4** [comment]
@xiangpengzhao Can you help me review this patch ?

**Comment by xiangpengzhao** [comment]
This change LGTM. But I'm not sure if it's OK to modify the file directly. Seems like its generated from some file else.
/cc @chenopis @zacharysarah

**Comment by zparnold** [comment]
@chenyb4 It looks like the file you modified is in the generated docs section, meaning this would not be the ideal place to make that fix. I believe there is a way to make this update/fix in https://git.k8s.io/kubernetes but I don't know it off-hand

**Comment by tengqm** [comment]
This is an incorrect way to fix the problem.

**Pull request closed without merging**
