### PR TITLE
Update install-kubectl-windows.md

### PR DESCRIPTION
**Pull request by Kheiden**
Minor documentation update to address:
https://github.com/kubernetes/website/issues/45468

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@Kheiden Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Review by Arhell — COMMENTED** [review]
Please re-push commot for restart netlify

**Review by rudrakshkarpe — COMMENTED** [review]
Thank you, this change looks good!

**Review by sftim — COMMENTED** [review]
Cool.

/lgtm
/merge

**Comment by ydFu** [comment]
/lgtm 
Thanks

**Comment by T-Lakshmi** [comment]
Hi @Kheiden,
Could you try to trigger the PR build again by pushing empty commit to restart netlify.
run below command:
**git commit --amend --no-edit && git push --force-with-lease**

**Pull request merged**
