### PR TITLE
kubeadm upgrade to the latest patch release, not the latest stable

### PR DESCRIPTION
**Pull request by silenceshell**
to fix a review comment in [29746](https://github.com/kubernetes/website/pull/29746/files#r711796974):
kubeadm upgrade to the latest patch release, not the latest stable

### CODE REVIEW

**Comment by silenceshell** [comment]
@sftim would you help to review this PR? Thanks a lot.

**Review by neolit123 — COMMENTED** [review]
/lgtm
The new text is more accurate. Thanks.

**Review by RinkiyaKeDad — APPROVED** [review]
/lgtm

**Comment by reylejano** [comment]
Thank you, this is a follow-up to a comment in PR https://github.com/kubernetes/website/pull/29746#discussion_r711796974

/approve

**Pull request merged**
