### PR TITLE
Update nodes.md to correct descriptions

### PR DESCRIPTION
**Pull request by copileft**
To correct descriptions of Node Condition like MemoryPressure and DiskPressure.

### CODE REVIEW

**Comment by xichengliudui** [comment]
Can you add the original English to the changes you have made? convenient for examination and approval of

**Comment by copileft** [comment]
How do i add the original english to my commit? Another patch for a new PR? I'm a github novice.

original english:
https://github.com/copileft/kubernetes-website/blob/release-1.14/content/en/docs/concepts/architecture/nodes.md

**Comment by xichengliudui** [comment]
Instead of opening a new pr, use markdown's syntax below or above your changes.
eg:
```
<--  content...  -->
```

**Comment by copileft** [comment]
I have added the original english by a new commit.

**Comment by xichengliudui** [comment]
cool
/lgtm
/approve

**Pull request merged**
