### PR TITLE
[zh]Update registry address

### PR DESCRIPTION
**Pull request by kinzhi**

### CODE REVIEW

**Comment by tengqm** [comment]
The `content/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md` file is out of sync. The prerequisites section misses an item. Please resync manually.

**Comment by Sea-n** [comment]
Hey @kinzhi,

Would you like to address the previous issue?
Please let us know what you think about it using the comment function.

**Comment by Sea-n** [comment]
Thanks for purposing this PR. But since you didn't respond for a while, we have to close this PR now.
/close

Feel free to `/reopen` when you are ready to move forward.
(Note that please don't push anything while PR closed, or you won't be able to reopen it.)

**Pull request closed without merging**
