### PR TITLE
Fix typo of the contents

### PR DESCRIPTION
**Pull request by PARKINHYO**
Fix the typo in kubernetes-api.md and update-api-object-kubectl-patch.md

intionally -> intentionally

### CODE REVIEW

**Comment by Sea-n** [comment]
Nice catch! Oh, that was my typo in PR #35700. 😅

Could you also change the remaining two occurrences in the following file?
```
content/en/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
```

Note: Please don't change files in `content/zh-cn/` and `content/pl/`, let the native speakers do this after your PR merged.

**Comment by PARKINHYO** [comment]
Ahh it was there, too. 😀
I fixed it!

**Comment by reylejano** [comment]
re-applying lgtm from @Sea-n in [comment](https://github.com/kubernetes/website/pull/37030#issuecomment-1258048941)
/lgtm

/approve

**Pull request merged**
