### PR TITLE
[WIP] Placeholder for Structured Logging Enhancement

### PR DESCRIPTION
**Pull request by serathius**
Placeholder for https://github.com/kubernetes/enhancements/issues/1602

### CODE REVIEW

**Comment by serathius** [comment]
Topic for future: I think it would make sense to split `logging.md` into separate files one describing logging of applications running on K8s, second one describing logging of kubernetes components? 
I will try to propose file names/locations, but suggestions would be appreciated.

**Comment by sftim** [comment]
I'll mark this as WIP so that Prow notices too
/retitle [WIP] Placeholder for Structured Logging Enhancement

**Comment by savitharaghunathan** [comment]
Hi @serathius , Thank you for creating the placeholder PR. 
This PR is raised against master. However, it needs to be raised against dev-1.19 branch. Can you make the appropriate changes, please? TIA

**Comment by serathius** [comment]
Sure, Closing for https://github.com/kubernetes/website/pull/21202

**Pull request closed without merging**
