### PR TITLE
Fix discovery document link in kubernetes-api.md

### PR DESCRIPTION
**Pull request by prabhakhar**
Removed an extra "v" in the link to fix the broken link.

### CODE REVIEW

**Review by stmcginnis — COMMENTED** [review]
Looks good. Can you sign the CLA?

This is also very minor. Any other clean up or improvements you can see in this document while you're at it?

**Comment by prabhakhar** [comment]
Modified one more broken anchor.

**Comment by stmcginnis** [comment]
/lgtm

Thanks!

**Review by dipesh-rawat — APPROVED** [review]
Thanks for fix!
Congrats on your first PR 🎉

/approve

**Pull request merged**
