### PR TITLE
Update minikube.md

### PR DESCRIPTION
**Pull request by caddyshake**

### CODE REVIEW

**Comment by yuswift** [comment]
please sign the cla.

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by RA489** [comment]
@caddyshake pls sign the cla to get this PR reviewed.

/check-cla

**Comment by reylejano** [comment]
Hi @caddyshake , since there has been no action to sign the CLA, I'm closing this PR.
Feel free to re-open this PR when you have signed the CLA

**Pull request closed without merging**
