### PR TITLE
[zh] Switch liveness image to multi-arch agnhost container image

### PR DESCRIPTION
**Pull request by spurin**
zh-cn equivalent for https://github.com/kubernetes/website/pull/45837

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/retitle [zh] Switch liveness image to multi-arch agnhost container image

**Comment by dipesh-rawat** [comment]
/hold
Wait until the equivalent English PR https://github.com/kubernetes/website/pull/45837 has been merged first.

**Comment by spurin** [comment]
/unhold

Referenced PR https://github.com/kubernetes/website/pull/45837 has now been merged

**Review by mengjiao-liu — COMMENTED** [review]
/lgtm
/approve
Thanks!

**Pull request merged**
