### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by wawa0210**
fix typo and remove `_voilà_ `

### CODE REVIEW

**Comment by mrbobbytables** [comment]
voilà is actually a word -- 
https://en.wiktionary.org/wiki/voil%C3%A0
It's like an exclamation -- of There! It's done!  or 'That's it!'

**Comment by sftim** [comment]
There is a tiny grammar issue; not sure it's worth fixing for a blog post:
> the CPU manager will assign exclusive CPUs to each of container in the pod

**Comment by wawa0210** [comment]
Learn a new word 👍 👍   I'd like to close this pr

**Pull request closed without merging**
