### PR TITLE
[zh-cn]Update architecture/controller.md

### PR DESCRIPTION
**Pull request by TJKkking**
Delete a word to make the sentence smoother

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @TJKkking , thanks for your contribution. Though this file has some differences from the en upstream. You can run the following command on your `main` branch to check it out:

```
./scripts/lsync.sh content/zh-cn/docs/concepts/architecture/controller.md
```
```diff
diff --git a/content/en/docs/concepts/architecture/controller.md b/content/en/docs/concepts/architecture/controller.md
index b89f6a077c..9eae9ff42a 100644
--- a/content/en/docs/concepts/architecture/controller.md
+++ b/content/en/docs/concepts/architecture/controller.md
@@ -165,6 +165,6 @@ controller does.
 * Discover some of the basic [Kubernetes objects](/docs/concepts/overview/working-with-objects/)
 * Learn more about the [Kubernetes API](/docs/concepts/overview/kubernetes-api/)
 * If you want to write your own controller, see
-  [Extension Patterns](/docs/concepts/extend-kubernetes/#extension-patterns)
-  in Extending Kubernetes.
+  [Kubernetes extension patterns](/docs/concepts/extend-kubernetes/#extension-patterns)
+  and the [sample-controller](https://github.com/kubernetes/sample-controller) repository.
```

**Comment by TJKkking** [comment]
> Hi @TJKkking , thanks for your contribution. Though this file has some differences from the en upstream. You can run the following command on your `main` branch to check it out:
> 
> ```
> ./scripts/lsync.sh content/zh-cn/docs/concepts/architecture/controller.md
> ```
> 
> ```diff
> diff --git a/content/en/docs/concepts/architecture/controller.md b/content/en/docs/concepts/architecture/controller.md
> index b89f6a077c..9eae9ff42a 100644
> --- a/content/en/docs/concepts/architecture/controller.md
> +++ b/content/en/docs/concepts/architecture/controller.md
> @@ -165,6 +165,6 @@ controller does.
>  * Discover some of the basic [Kubernetes objects](/docs/concepts/overview/working-with-objects/)
>  * Learn more about the [Kubernetes API](/docs/concepts/overview/kubernetes-api/)
>  * If you want to write your own controller, see
> -  [Extension Patterns](/docs/concepts/extend-kubernetes/#extension-patterns)
> -  in Extending Kubernetes.
> +  [Kubernetes extension patterns](/docs/concepts/extend-kubernetes/#extension-patterns)
> +  and the [sample-controller](https://github.com/kubernetes/sample-controller) repository.
> ```

I updated it

**Comment by windsonsea** [comment]
Please [squash your commits into a single one](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits).

**Comment by TJKkking** [comment]
> Please [squash your commits into a single one](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits).

ok

**Comment by TJKkking** [comment]
I did it.

**Pull request merged**
