### PR TITLE
fix PR #11649 comments

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by tengqm** [comment]
public IP address 公开 IP 地址

**Comment by chenrui333** [comment]
Sure, will adopt the suggestion now.

**Comment by chenrui333** [comment]
@tengqm Updated! 👍

**Comment by tengqm** [comment]
@chenrui333 Thanks for the patience.
/lgtm
/approve

**Comment by chenrui333** [comment]
@tengqm Thanks a lot for your help!

**Pull request merged**
