### PR TITLE
Promote feature gate StableLoadBalancerNodeSet to GA

### PR DESCRIPTION
**Pull request by carlory**
k/k:  https://github.com/kubernetes/kubernetes/pull/122961 (merged)
kep: https://github.com/kubernetes/enhancements/issues/3458

### CODE REVIEW

**Comment by kundan2707** [comment]
@carlory  there are other places also when it should be updated.
i.e 
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by kundan2707** [comment]
Here is complete list for to updated.
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by sftim** [comment]
Responding to https://github.com/kubernetes/website/pull/45236#issuecomment-1955895826:

> - https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
> - https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
> - https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
> - https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/

These are automatically generated with no change needed in this PR.

> - https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

This is automatically generated, and this PR includes the relevant changes.

**Review by sftim — APPROVED** [review]
/approve

**Pull request merged**
