### PR TITLE
[WIP] Placeholder PR for In-Place Pod Vertical Scaling feature

### PR DESCRIPTION
**Pull request by vinaykul**
This is a placeholder PR for [In-Place Pod Vertical Scaling ](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20181106-in-place-update-of-pod-resources.md) feature.

A new md file for this work is justified. I might also need to modify some existing md files as well. I'll try to get to that as soon as I can.

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [WIP] Placeholder PR for In-Place Pod Vertical Scaling feature
/milestone 1.19

**Comment by kbhawkey** [comment]
Hello @vinaykul .
Checking whether you plan to continue to work on these changes?
Thanks!

**Comment by savitharaghunathan** [comment]
@kbhawkey - This enhancement has been moved into 1.20 milestone. Thanks for your comment. Sorry for not clearing the milestone.
/milestone clear

**Comment by vinaykul** [comment]
> Hello @vinaykul .
> Checking whether you plan to continue to work on these changes?
> Thanks!

yes - for 1.20, but we may be looking at changing the API a little. discussions are going on here https://github.com/kubernetes/enhancements/pull/1883/files

**Comment by jimangel** [comment]
If this is going into 1.20, do we want to close this PR since it will need to be based against dev-1.20?

**Comment by sftim** [comment]
You can change the base branch for PRs. However, I would close this one and, @vinaykul, when you come to open a new PR you can reference this one to track the link between them.

**Comment by vinaykul** [comment]
@jimangel @sftim sure. i'll close this and reference it in 1.20 dev.

**Pull request closed without merging**
