### PR TITLE
docs: added internal load balancer service annotations for Oracle Cloud (OCI)

### PR DESCRIPTION
**Pull request by hyder**
Added tab and sample code describing how to use annotations to create an internal load balancer instance in Oracle Cloud Infrastructure (OCI). 

Reviewed-by: Avi Miller <avi.miller@oracle.com>
Signed-off-by: Ali Mukadam <ali.mukadam@oracle.com>

### CODE REVIEW

**Comment by bradtopol** [comment]
Hi @hyder thank you for your contribution.   Except under special circumstances,  PRs should not go across multiple localizations.  Please break up your PR into one per language.  Thanks!

**Comment by hyder** [comment]
> Hi @hyder thank you for your contribution. Except under special circumstances, PRs should not go across multiple localizations. Please break up your PR into one per language. Thanks!

Hi, 

I was not aware of this, my apologies.  I've removed the doc changes in languages other than English. Once this PR is approved, I'll submit similar changes in separate PRs for other languages

**Comment by jihoon-seo** [comment]
@hyder This PR is still adding a newline to [`content/fr/docs/concepts/services-networking/service.md`](https://github.com/kubernetes/website/pull/32743/files#diff-695707ada9dc920d592cb5d7fca1bd5fe76f8fa3ccb2cf15d8aecdf1f6b62ec2) and [`content/id/docs/concepts/services-networking/service.md`](https://github.com/kubernetes/website/pull/32743/files#diff-1a9bb7936a39dccf5492ca4eb80f02dc12814dd12e3417472bde7f8d0ffd1854).

Please exclude these changes, and squash your commits into one commit as well! 😊

/remove-language es fr id ja ko zh

**Comment by hyder** [comment]
Hi @bradtopol, @jihoon-seo,

Thanks for reviewing. I've made the changes as requested.

**Comment by hyder** [comment]
Hi @chenrui333, @electrocucaracha,

Can I please trouble you to review this?

Thanks.

**Comment by zacharysarah** [comment]
@hyder Thanks for your patience. This looks good to me, so I'm willing to approve.

@jihoon-seo 👋🏻 It looks like your [feedback](https://github.com/kubernetes/website/pull/32743#issuecomment-1088254774) was addressed, so I'm willing to move this forward.

/lgtm
/approve

**Comment by hyder** [comment]
Thank you @zacharysarah

**Pull request merged**
