### PR TITLE
[zh] sync endpoint-slices,persistent-volumes,topology-aware-hints

### PR DESCRIPTION
**Pull request by asa3311**
Related to task-3 of issue https://github.com/kubernetes/website/issues/39985.

content/en/docs/concepts/services-networking/endpoint-slices.md
content/zh-cn/docs/concepts/storage/persistent-volumes.md
content/en/docs/concepts/services-networking/topology-aware-hints.md

### CODE REVIEW

**Comment by windsonsea** [comment]
You shall learn to [squash your commits](https://ndx.gitpages.daocloud.io/product/doc-template/zh/quickstart/rebase.html#squash-commits) or you can read [my notes](https://ndx.gitpages.daocloud.io/product/doc-template/zh/quickstart/rebase.html#squash-commits).

**Comment by asa3311** [comment]
thanks @windsonsea ,I learn your  notes.Now I squash commits in [c9ef980](https://github.com/kubernetes/website/pull/40016/commits/c9ef9806ac1adbb1b27581c9a8d9262defcd9ad8)。
Is that right?

**Comment by windsonsea** [comment]
No. The number of commits shall be 1.

image

**Comment by asa3311** [comment]
@windsonsea ,Thanks,Now I squash commits to one,Is that right? please review.
Also, I would like to ask if there are any groups in this community? Can I join and learn?

**Comment by windsonsea** [comment]
Thanks. You can join the slack channel by reading our [contribution guide](https://kubernetes.io/zh-cn/docs/contribute/style/content-guide/) on [kubernetes.io](https://kubernetes.io/), especially:

- [中文本地化指南](https://kubernetes.io/zh-cn/docs/contribute/localization/)
- [Roles and responsibilities](https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/)

**Comment by windsonsea** [comment]
/lgtm after checked each file by running `./scripts/lsync.sh`

Congrats!

**Comment by windsonsea** [comment]
/lgtm

Congrats!

**Comment by asa3311** [comment]
@howieyuen done

**Review by howieyuen — COMMENTED** [review]
/approve

**Pull request merged**
