### PR TITLE
[ja] Shortcode fixes

### PR DESCRIPTION
**Pull request by craigbox**
Hugo v0.111.x will throw an error if calling a shortcode within a fenced code block. (https://github.com/gohugoio/hugo/issues/10819)
This PR brings fixes this issue for the ja locale.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
please re-push to restart netlify

**Comment by craigbox** [comment]
bump!

**Review by t-inu — COMMENTED** [review]
Thank you!
/lgtm

**Pull request merged**
