### PR TITLE
fix deployment apiversion error

### PR DESCRIPTION
**Pull request by cleverhu**
fix deployment apiversion error

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi, this behavior is not encouraged. You only need to handle a language in a PR, such as zh.

If you handle this file for zh-cn, you can run the command below to check difference from en:
```
./scritps/lsync.sh content/zh-cn/docs/concepts/cluster-administration/manage-deployment.md
```
If this command doesn't work, you can try to use 'diff' or `vimdiff`.

**Comment by Sea-n** [comment]
Please see [the above comment](https://github.com/kubernetes/website/pull/37712#issuecomment-1303558543) and remove changes for other languages.

/hold

**Comment by Sea-n** [comment]
Hey @cleverhu, are you still interesting in contributing `kubernetes/website`?

**Comment by cleverhu** [comment]
> Hey @cleverhu, are you still interesting in contributing `kubernetes/website`?

I'm sorry for late.It's a little complicated. I'll try to modify it. If I need to modify too much, I'll close the pr.

**Comment by cleverhu** [comment]
the result of 
```
./scripts/lsync.sh /Users/daocloud-cleverhu/GolandProjects/qy-master/website/content/zh-cn/docs/concepts/cluster-administration/manage-deployment.md         
```
is
```                                                              
/Users/daocloud-cleverhu/GolandProjects/qy-master/website/content/zh-cn/docs/concepts/cluster-administration/manage-deployment.md is still in sync
```

**Pull request merged**
