### PR TITLE
Fix casing issues and standardize keyword capitalization in the docum…

### PR DESCRIPTION
**Pull request by yelog**
Simple changes: Fix the issue of inconsistent casing for the same keywords on the current page.

### CODE REVIEW

**Comment by niranjandarshann** [comment]
Hey @yelog , Its  Thank you for your contribution. It looks good to me. Can you check the Whole Page  if having same issue?

**Comment by yelog** [comment]
> Hey @yelog , Its Thank you for your contribution. It looks good to me. Can you check the Whole Page if having same issue?

Thanks for the response. The Whole page has been checked for this issue, and the issue exists only in the two lines I adjusted and submitted in the pull request.

**Comment by Gauravpadam** [comment]
@yelog this is a trivial change. While we appreciate any and all sorts of improvements, we encourage you to find any typos, missing line wrapping, grammatical errors, missing references etc. to make this PR more substantial.

**Comment by AmarNathChary** [comment]
Thanks for the contribution
Refer to [Trivial Edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) you can read the entire page and if you can find more. it's appreciated if you could raise a PR for all at once

**Comment by windsonsea** [comment]
You can find more differences by running this command on your `main` branch:

```
./scripts/lsync.sh content/zh-cn/docs/concepts/overview/components.md
```
The output may be similar to:
```diff
diff --git a/content/en/docs/concepts/overview/components.md b/content/en/docs/concepts/overview/components.md
index 28b633c141..177354fa47 100644
--- a/content/en/docs/concepts/overview/components.md
+++ b/content/en/docs/concepts/overview/components.md
@@ -31,7 +31,7 @@ as well as detecting and responding to cluster events (for example, starting up
 `{{< glossary_tooltip text="replicas" term_id="replica" >}}` field is unsatisfied).
 
 Control plane components can be run on any machine in the cluster. However,
-for simplicity, set up scripts typically start all control plane components on
+for simplicity, setup scripts typically start all control plane components on
 the same machine, and do not run user containers on this machine. See
 [Creating Highly Available clusters with kubeadm](/docs/setup/production-environment/tools/kubeadm/high-availability/)
 for an example control plane setup that runs across multiple machines.
@@ -150,4 +150,4 @@ Learn more about the following:
    * Etcd's official [documentation](https://etcd.io/docs/).
    * Several [container runtimes](/docs/setup/production-environment/container-runtimes/) in Kubernetes.
    * Integrating with cloud providers using [cloud-controller-manager](/docs/concepts/architecture/cloud-controller/).
-   * [kubectl](/docs/reference/generated/kubectl/kubectl-commands) commands.
\ No newline at end of file
+   * [kubectl](/docs/reference/generated/kubectl/kubectl-commands) commands.
```

**Comment by yelog** [comment]
Appreciate the feedback from @Gauravpadam @AmarNathChary.  I'm currently thoroughly reviewing the entire document. And I'll be documenting all encountered any typos, missing line wrapping, grammatical errors, missing references issues. These will be consolidated and addressed in this PR.

Many thanks to @3 for providing the inspection method. I'll execute the script to check the modifications after submission.

**Comment by windsonsea** [comment]
Ping @yelog

**Comment by windsonsea** [comment]
3 months passed and this PR only includes small typos, so this PR will be closed. Feel free to re-open it if you are available to fix more issues like https://github.com/kubernetes/website/pull/45024#issuecomment-1946014297

/close

**Pull request closed without merging**
