### PR TITLE
German version 404 issue resolution

### PR DESCRIPTION
**Pull request by jhbiggs**
Hello,

I've resolved an issue with a 404 error on the German version of the site.  It tags to issue #14473 .  This pull request marks my first in this arena.  Thanks for your patience as I learn to swim.

### CODE REVIEW

**Comment by jhbiggs** [comment]
Hello, I also pushed changes for issue #14151 here.  Any advice is appreciated on what to do when I have more than one issue to which to commit changes.

**Comment by rlenferink** [comment]
Hi @jhbiggs i had a look at this PR and your previous PR. It seems that this PR includes changes that were already merged in #14685.

If you can rebase this PR and drop the first 3 commits (the German ones which you've already fixed), and only keep https://github.com/kubernetes/website/pull/14926/commits/b9827f9eca4cfefba73f3a0c50a576269588df58 that would be great. After that, we can change the scope of this PR to only fix #14151 

Best thing to do when fixing multiple issues is to keep the different localizations separated in separate pull requests.

**Comment by jhbiggs** [comment]
Ok, I believe I "cherry picked" the #14151 commit and pushed it back to my fork.  It's not showing in this thread, though.  Could you please tell me if I need to do something more here?

**Comment by rlenferink** [comment]
_Closing this PR in favor of #14967_ 

/close

**Pull request closed without merging**
