### PR TITLE
update static _redirects, release-1.16

### PR DESCRIPTION
**Pull request by kbhawkey**
- Clean up entries in `static/_redirects` related to Netlify redirect bug fix.
- For further information see issue #19736 .
- Comments, reviews, questions, updates very welcome.
- Did not tidy the redirect entries (for the most part).

### CODE REVIEW

**Comment by kbhawkey** [comment]
@sftim, When you have a second, I would appreciate your review. Thanks!

**Comment by sftim** [comment]
Ah. Should we backport approver lists?

**Comment by kbhawkey** [comment]
> 
> 
> Ah. Should we backport approver lists?

Good question. I do not know the answer.

**Comment by zacharysarah** [comment]
@sftim 
> Ah. Should we backport approver lists?

Hopefully this is the only time we'll have to do something like this, so I think we're OK. Let these not be famous last words... 😓

**Comment by zacharysarah** [comment]
Closes #19736. 

/approve

**Pull request merged**
