### PR TITLE
[ko] replaced {{< codenew ... >}} with {{% codenew ... %}}

### PR DESCRIPTION
**Pull request by andreygoran**
This is a continuation of PR https://github.com/kubernetes/website/pull/42180 (Replace {{< codenew ... >}} with {{% codenew ... %}})
Fixes https://github.com/kubernetes/website/issues/42179 (Copy To Clipboard breaks YAML format)

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@andreygoran please re-push commit for the build to pass
Unfortunately this happens from time to time.

**Comment by andreygoran** [comment]
> @andreygoran please re-push commit for the build to pass
> Unfortunately this happens from time to time.

Done

**Comment by seokho-son** [comment]
Hi @andreygoran 
Thank you for the contribution!

Korean localization team accepts PRs to sync Korean content with English content, but please note that our current Korean localization is on a separate development branch (current Korean localization dev branch is: [dev-1.27-ko.1](https://github.com/kubernetes/website/tree/dev-1.27-ko.1)). Submitting a PR directly to the main branch may cause merge conflicts later on. 
Could you update this PR to target the correct target branch, or open a new PR targeting the Korean localization development branch.

Thank you.

**Comment by andreygoran** [comment]
Hi @seokho-son 

I created new PR https://github.com/kubernetes/website/pull/42278 based on branch [dev-1.27-ko.1](https://github.com/kubernetes/website/tree/dev-1.27-ko.1)

**Comment by jihoon-seo** [comment]
The merged PR #42278 supercedes this one.
/close

**Pull request closed without merging**
