### PR TITLE
Remove/hide cluster operator advanced user journey

### LINKED ISSUE #7482: Bad content on "user journey"
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
https://kubernetes.io/docs/user-journeys/users/cluster-operator/advanced/

Actual content is missing.

**Proposed Solution:**
N/A

**Page to Update:**
https://kubernetes.io/docs/user-journeys/users/cluster-operator/advanced/

### PR DESCRIPTION
**Pull request by chenopis**
closes #7482

### CODE REVIEW

**Comment by zacharysarah** [comment]
@chenopis Looks like Travis [chokes](https://travis-ci.org/kubernetes/website/builds/349494961?utm_source=github_status&utm_medium=notification) on a file without a ToC entry. Maybe delete the file entirely until we're ready to add content?

**Comment by zacharysarah** [comment]
@chenopis It looks like `_advanced.md` needs to be renamed back to `advanced.md`.

**Comment by chenopis** [comment]
Oops. I need to make it match in `skip_toc_check.txt`.

**Comment by chenopis** [comment]
@zacharysarah Should be good now.

**Pull request merged**
