### PR TITLE
Change version selector to retain current page when switching versions (for website v1.15)

### PR DESCRIPTION
**Pull request by brianpursley**
Fixes https://github.com/kubernetes/website/issues/19340 for version 1.15 of the website
(Additional PRs will be issued for other versions)

### CODE REVIEW

**Comment by brianpursley** [comment]
Hi @sftim, it looks like you gave approval 7 days ago, but this never got the approved label, maybe because k8s-ci-robot wasn't looking for it yet.

**Comment by sftim** [comment]
It's because although I'm a tech lead the 1.15 branch doesn't know this.

**Comment by sftim** [comment]
@kubernetes/sig-docs-en-owners?

**Comment by zacharysarah** [comment]
@brianpursley Normally we don’t accept PRs for historical branches, but I think this makes a worthy exception. 

/lgtm
/approve

**Pull request merged**
