### PR TITLE
Remove trailing spaces from ko documents(#16742)

### PR DESCRIPTION
**Pull request by furukawa3**
This PR removes trailing spaces from "ko" doc.  Following command are used.
```
sed -i 's/[ ]*$//' $(find content/ko -type f -not -name "*.png" -not -name "*.jpg" -not -name "*.svg" -not -name "*.gif")
```

### CODE REVIEW

**Comment by seokho-son** [comment]
@furukawa3 Thank you for your contribution.
/lgtm

@gochist Could you approve this PR ?

**Comment by gochist** [comment]
@seokho-son I'll approve it after #16787

**Comment by gochist** [comment]
@furukawa3 Regarding https://github.com/kubernetes/website/pull/16787#issuecomment-580519144, I'm closing this PR. 

/close

**Pull request closed without merging**
