### PR TITLE
[zh] Sync tutorial scale-intro and reformat.

### PR DESCRIPTION
**Pull request by 1000Delta**
Sync with en: content/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html

Dependent on #43873 , include format fix ups from en.

### CODE REVIEW

**Comment by 1000Delta** [comment]
See [Preview](https://deploy-preview-43878--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro/).

**Comment by 1000Delta** [comment]
This PR now can be review.

**Review by ydFu — APPROVED** [review]
/approve

**Review by chenrui333 — APPROVED** [review]
/lgtm
/approve

**Comment by windsonsea** [comment]
Hi @1000Delta, you need to run the following commands to trigger CI again:

```
git reset
git commit --amend --no-edit
git push -f 
```

**Pull request merged**
