### PR TITLE
Update Calico to v3.7

### PR DESCRIPTION
**Pull request by caseydavenport**

### CODE REVIEW

**Comment by tengqm** [comment]
@caseydavenport Is this for 1.14 or 1.15?

**Comment by caseydavenport** [comment]
@tengqm it applies to both really

**Comment by neolit123** [comment]
@caseydavenport 
thanks for the PR.
LGTM on the kubeadm side, but i think sig-docs explicitly said that single PRs should not touch multiple languages.

/sig cluster-lifecycle
/lgtm

**Comment by sftim** [comment]
@caseydavenport would it be OK if someone made new PRs for the English-language original and its localizations?

**Comment by caseydavenport** [comment]
> @caseydavenport would it be OK if someone made new PRs for the English-language original and its localizations?

Sorry for the delay, was OOO - yes that would be great, thank you!

**Pull request merged**
