### PR TITLE
[pt-br] Add docs/contribute/style/content-guide.md

### PR DESCRIPTION
**Pull request by stormqueen1990**
### Changes
* Add the Brazilian Portuguese translation for the content guide.

### CODE REVIEW

**Comment by MrErlison** [comment]
Hi @stormqueen1990!

Thank you very much for your beautiful contribution! 🎉

/lgtm

/cc @edsoncelio

**Comment by edsoncelio** [comment]
Thanks!
/lgtm

**Comment by edsoncelio** [comment]
@ stormqueen1990 I've approved the last pending PR; we can remove the hold for this PR.

**Comment by stormqueen1990** [comment]
Thanks @edsoncelio! 🎉

/unhold

**Pull request merged**
