### PR TITLE
Format markdown on the ingress-minikube page

### PR DESCRIPTION
**Pull request by tengqm**
This PR adjusts the indentation and line-wrapping on the ingress-minikube page.

### CODE REVIEW

**Review by nanthakumaran-s — COMMENTED** [review]
LGTM

**Comment by kbhawkey** [comment]
Preview:
https://deploy-preview-38273--kubernetes-io-main-staging.netlify.app/docs/tasks/access-application-cluster/ingress-minikube/

**Comment by kbhawkey** [comment]
Does this task need to be updated (uses Katacoda)?
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-a-minikube-cluster

**Comment by tengqm** [comment]
The 'katacoda' part can be left to a future cleanup.

**Pull request merged**
