### PR TITLE
Update Azure Container Service to managed clusters

### PR DESCRIPTION
**Pull request by gsacavdm**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6955)

### CODE REVIEW

**Comment by steveperry-53** [comment]
@gsacavdm Please sign the CLA.

**Comment by heckj** [comment]
/hold
@steveperry-53 looks like this needs a rebase - was jamming up the queue for merging other PR’s, so I tacked a /hold on it - please remove it whenever you’re good with the rebase, hoping that will pause tide on this PR and let it merge in the others that are pending

**Comment by heckj** [comment]
Erp, @gsacavdm sorry - should have addressed you directly. Could you give this a rebase and resolve against the current master? Totally good with letting it go in, but there’s a conflicting file right now that doesn’t merge cleanly (`/docs/setup/pick-right-solution.md`)

**Comment by gsacavdm** [comment]
@heckj , done. Should be good to merge now, right?

**Pull request merged**
