### PR TITLE
Update data type presentation in component reference

### PR DESCRIPTION
**Pull request by tengqm**
Instead of putting "stringSlice" or "mapStringString" as data type for
flag data type, we can show more user friendly data type description
that is not GoLang specific.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page previews:
https://deploy-preview-26976--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kube-apiserver/
https://deploy-preview-26976--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kube-scheduler/
https://deploy-preview-26976--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kube-proxy/
https://deploy-preview-26976--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kube-controller-manager/

**Comment by celestehorgan** [comment]
Hi @tengqm, 

I like this change but I'm concerned that we lose a bit of precision by changing `float32` to `float` in this case. I'm going to ask maybe @onlydole @zparnold or @sftim to comment here: is there a loss of data/accuracy by doing this?

**Comment by sftim** [comment]
We should link to the code change to the generator that achieves this.
/approve

**Pull request merged**
