### PR TITLE
For namespace walkthrough, switch example manifests to YAML

### PR DESCRIPTION
**Pull request by bishal7679**
Signed-off-by: Bishal Das <bishalhnj127@gmail.com>

Fixes :- #37160

Closes:- #37160

`Json` manifest has changed into `yaml` manifest in namespace walkthrough

Filelink:- https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/#create-new-namespaces

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Preview: https://deploy-preview-37529--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/namespaces-walkthrough/#create-new-namespaces
/lgtm

**Review by Pradumnasaraf — APPROVED** [review]
/approve

**Review by ydFu — APPROVED** [review]
/lgtm

**Comment by sftim** [comment]
/retitle For namespace walkthrough, switch example manifests to YAML

**Review by sftim — COMMENTED** [review]
Thanks

/approve

**Pull request merged**
