### PR TITLE
fix translation

### PR DESCRIPTION
**Pull request by uutest74**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info https://github.com/kubernetes/website/pull/29069#issuecomment-884680268

**Comment by uutest74** [comment]
> 
> 
> Pls sign the CLA in order for the PR to be reviewed.
> more info [#29069 (comment)](https://github.com/kubernetes/website/pull/29069#issuecomment-884680268)
No time for this bull***. close. goodluck

**Comment by Arhell** [comment]
@Potapy4
Close please https://github.com/kubernetes/website/pull/29069#issuecomment-885385895

**Pull request closed without merging**
