### PR TITLE
Fix: typo in assign-pods-nodes.md (Chinese version)

### PR DESCRIPTION
**Pull request by chendotjs**
An omitted space is making the web page look abnormal. 

For example:
https://kubernetes.io/zh/docs/tasks/configure-pod-container/assign-pods-nodes/
https://v1-14.docs.kubernetes.io/zh/docs/tasks/configure-pod-container/assign-pods-nodes/

### CODE REVIEW

**Comment by xichengliudui** [comment]
@chendotjs , Thanks for the fix, but please fix the rest of this article.
/lgtm
/approve
/hold
Please tell me the preview link...

**Comment by xichengliudui** [comment]
eg:
image

**Comment by chendotjs** [comment]
The rest is fixed.  This is the [preview link]( https://5d6b6df7c3cf9f0009c7b408--k8s-v1-14.netlify.com/zh/docs/tasks/configure-pod-container/assign-pods-nodes/).

/assign @xichengliudui

**Comment by xichengliudui** [comment]
/lgtm
thanks

**Pull request merged**
