### PR TITLE
Add languagedirection in config.toml

### LINKED ISSUE #22732: Set languagedirection for localizations
**This is a Feature Request**

**What would you like to be added**
In [`config.toml`](https://github.com/kubernetes/website/blob/master/config.toml), set `languagedirection` for all localizations. The value will be `rtl` for languages usually written right-to-left, or `ltr` for languages usually written left-to-right.

**Why is this needed**
This is part of #22730

**Comments**
/kind feature
/area web-development
/good-first-issue
/priority backlog

### PR DESCRIPTION
**Pull request by SaiHarshaK**
This PR adds languagedirection field to the localizations in config.toml.

Fixes #22732

### CODE REVIEW

**Comment by sftim** [comment]
I think you need to use `"ltr"` (and `"rtl"`) inside quotes.

**Comment by sftim** [comment]
That was commendably fast @SaiHarshaK !

**Comment by SaiHarshaK** [comment]
> I think you need to use `"ltr"` (and `"rtl"`) inside quotes.

I just noticed and updated.

**Comment by sftim** [comment]
LGTM (will wait for preview before reviewing formally)

**Comment by SaiHarshaK** [comment]
@sftim Will this be approved along with the parent issue?

**Comment by sftim** [comment]
@SaiHarshaK this change does look good to me. If one of the approvers agrees, this can merge (approvers are mostly volunteers, so although we try to review changes promptly, getting a change merged can take a while).

**Comment by makoscafee** [comment]
thanks @SaiHarshaK 
/LGTM
/approve

**Pull request merged**
