### PR TITLE
[ja] fixed broken link in intro-windows-in-kubernetes.md

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/29955/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Preview: https://deploy-preview-30354--kubernetes-io-main-staging.netlify.app/ja/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#kubernetesのwindowsコンテナ

**Comment by atoato88** [comment]
LGTM too :grinning:

**Pull request merged**
