### PR TITLE
[ar] Merge main into `dev-1.29-ar.1`

### PR DESCRIPTION
**Pull request by mboukhalfa**
Update `dev-1.29-ar.1` branch by merging main changes

I created a branch from  `dev-1.29-ar.1` then I ran : 
`git merge -Xtheirs main`

### CODE REVIEW

**Comment by sftim** [comment]
Why is merging this PR a good idea @mboukhalfa? Can you clarify that?

**Comment by mboukhalfa** [comment]
> Why is merging this PR a good idea @mboukhalfa? Can you clarify that?

To sync with main! Avoid alot of troubles when we merge our branch into main

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by network-charles** [comment]
Hi, @mboukhalfa from your previous PR, you signed the CLA, but it hasn't been reflected here. Could you re-sign the CLA?

**Comment by sftim** [comment]
@network-charles at least _one_ of the commits (out of the 3268) isn't from someone who has signed the CLA; the missing signature might not be from @mboukhalfa.

**Comment by network-charles** [comment]
Ok

- Charles Uneze

**Comment by mboukhalfa** [comment]
> @network-charles at least _one_ of the commits (out of the 3268) isn't from someone who has signed the CLA; the missing signature might not be from @mboukhalfa.

Thanks @sftim what is the action point for me here

**Comment by Okabe-Junya** [comment]
Is this PR still being worked on? If not, please `/close` and create another one when needed, thank you :)

**Comment by mboukhalfa** [comment]
@Okabe-Junya This needed for our Branch ar localization we are waiting for the community to help approve and merge this

**Comment by Okabe-Junya** [comment]
I am not sure whether you should move this PR forward, but if you do, I think you need to resolve the CLA before getting approval from the maintainers

FYI: Out of approximately 27,000 merged PRs, only 11 have had the CLA check skipped. I'm not sure if this PR falls under those exceptions, but it’s better to resolve it.

- https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+label%3A%22cncf-cla%3A+no%22+

**Comment by Okabe-Junya** [comment]
IMHO, re-opening is easier than moving foward with this PR

**Comment by mboukhalfa** [comment]
> IMHO, re-opening is easier than moving foward with this PR

Why so ? I have already fixed conflict on this PR should I restart from scratch ?

**Comment by Okabe-Junya** [comment]
I'm sorry for the delayed response.

My concern is not about the conflict, but the CLA. Although this PR is not directed at the main branch, it's generally not preferable to keep a PR open for long if it fails the CLA. 

FYI: https://kubernetes.io/docs/contribute/participate/pr-wranglers/#helpful-github-queries-for-wranglers

> Remind the contributor to sign the CLA. If both the bot and a human have reminded them, close the PR and remind them that they can open it after signing the CLA.

If you need support from the community or maintainers, I suggest reaching out to them. - In any case, it should be handled promptly, thanks.

**Comment by reylejano** [comment]
Hi @mboukhalfa , I'm closing this PR since it's been open for several months and missing CLA authorization with an unsigned CLA. This PR won't pass branch protections without a signed CLA
Once the CLA is resolved, you can reopen this PR with `/reopen` in a comment
/close

**Pull request closed without merging**
