### PR TITLE
CentOS Repo for 1.15

### LINKED ISSUE #15503: Issue with k8s.io/docs/setup/production-environment/container-runtimes/
**This is a Bug Report**

Incorrect CRIO yum repository for Centos/RHEL

**Problem:**
CRI-O section for Centos/RHEL 7.4+ tab has incorrect yum repository to match Kubernetes 1.15 version.

**Proposed Solution:**
Update the Centos/RHEL 7.4+ tab under the CRI-O section with the correct yum repository with a supported & working version of CRIO 1.15 rpms for Kubernetes 1.15 version.

**Page to Update:**
https://kubernetes.io/...

1.15

### PR DESCRIPTION
**Pull request by thecrudge**
Corrected link for centos repo

### CODE REVIEW

**Comment by zacharysarah** [comment]
@thecrudge 👋 Prow gets cranky if you include GitHub magic words ("update") in commit messages. Please amend and/or rebase as needed so we can proceed. 👍

**Comment by nikhita** [comment]
:wave: btw `update` in commit messages is fine, but the words `fixes #XXXX` where #XXXX is an issue number makes prow sad :grimacing:

**Comment by thecrudge** [comment]
Darn it, I thought it was only in the title that it made Prow mad, not the commit message.

**Pull request merged**
