### PR TITLE
the sentence does not make sense

### PR DESCRIPTION
**Pull request by proth1**
I've attempted to have it make more sense by removing the word 'is'.  Optionally, depending on the intended meaning, the sentence could read differently by leaving the word 'is' alone and changing the word 'through' to 'though'.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.13-ko.<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Thanks for the PR @proth1!!!Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

memo Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

**Comment by proth1** [comment]
I signed the CLA. Thanks

**Comment by zparnold** [comment]
Hey there! @proth1, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by proth1** [comment]
sorry. I thought I had signed but now I have definitely signed the CLA.
Thanks,

**Comment by Rajakavitha1** [comment]
Thanks for the PR @proth1 !!!!
I checked the update on https://deploy-preview-12673--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/ingress/

I guess the intent was: An optional host. In this example, no host is specified, so the rule applies to all inbound HTTP traffic though the IP address is specified.

@zparnold could you please take a look at this PR.

**Comment by Rajakavitha1** [comment]
@chenopis could you please take a look at this PR and confirm the intent.

**Comment by stewart-yu** [comment]
IMO， the fix is wrong

**Comment by Bradamant3** [comment]
It looks to me as though the original indeed does not make sense, as the author points out, but the fix doesn't clear anything up, either. I don't know enough about Ingress to suggest the right fix, but page context suggests that without the optional host, traffic is routed through the default backend. With or without the fix, the doc as is also suggests that the HTTP IP address (specified in the Service spec?) is used in place of the optional host.

**Comment by jimangel** [comment]
@proth1 @stewart-yu would it be more technically accurate if it was "the rule applies to all inbound HTTP traffic through the Kubernetes node"?

**Comment by mistyhacks** [comment]
/hold

until feedback is addressed

**Comment by tengqm** [comment]
/hold cancel
/lgtm
/approve
This fix is correct.

**Pull request merged**
