### PR TITLE
[ja] Translate reference/access-authn-authz/admission-controllers into Japanese

### LINKED ISSUE #30527: [ja] Translate reference/access-authn-authz/admission-controllers into Japanese
# This is a Feature Request

## What would you like to be added

Translate [reference/access-authn-authz/admission-controllers](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/)  into Japanese.

## Why is this needed

This page has not been translated.

## Comments

/language ja
/assign

### PR DESCRIPTION
**Pull request by ptux**
fix #30527

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hey @ptux , would you be able to continue work on this PR? This has been pending in draft status for a really long time.

**Comment by Sea-n** [comment]
Hey @ptux,

It would be sad if the bot close this PR automatically.

If you are still interested in translating this, please use `/remove-lifecycle stale` to tell bot not to.

**Comment by divya-mohan0209** [comment]
Hey @ptux, I'll be closing the PR due to inactivity. Please feel free to reopen whenever you have some cycles to work on it :) 
/close

**Pull request closed without merging**
