### PR TITLE
Re-add kubefed to setup tools reference

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR:
- re-adds kubefed docs to setup tools reference
- cleans up nav weights for setup tools, including kubefed and kubeadm

### CODE REVIEW

**Comment by steveperry-53** [comment]
@zacharysarah The kubeadm docs have already been done. So they should not be in this PR.

**Comment by steveperry-53** [comment]
The kubefed portion of this PR looks good.

**Comment by zacharysarah** [comment]
@steveperry-53 
> The kubeadm docs have already been done. So they should not be in this PR.

All I did with the kubeadm docs was add weights to the front matter. The goal was to make them appear in the same order as [v1.10 docs](https://v1-10.docs.kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/). It looks like the bot took that as an opportunity to trim trailing whitespaces.

**Pull request merged**
