### PR TITLE
[ko] Translate the glossary term Developer into Korean

### LINKED ISSUE #35438: [ko] Translate the glossary term 'Developer' into Korean
This is a Feature Request

What would you like to be added

Translate the glossary term 'Developer' into Korean

- link to en entry: https://kubernetes.io/docs/reference/glossary/?all=true#term-developer
- link to ko entry: https://kubernetes.io/ko/docs/reference/glossary/?all=true#term-developer

Why is this needed
Not translated into Korean yet.

Comments

/language ko
/assign

### PR DESCRIPTION
**Pull request by yuzin9712**
Signed-off-by: yuzin9712 <dbwls97@ajou.ac.kr>

fix #35438

### CODE REVIEW

**Comment by seokho-son** [comment]
This PR is WIP. :)
I am sure the contributor will update the PR and review can be initiated once the contributor update WIP contests.

**Comment by seokho-son** [comment]
@yuzin9712 
Please update this PR with a complete localization :)

**Comment by yuzin9712** [comment]
해당 이슈에대해  PR을 새로 만들어 올리게 되어 Close 하였습니다!!
https://github.com/kubernetes/website/pull/35874

**Pull request closed without merging**
