### PR TITLE
add a missing step in kubeadm-upgrade flow.

### PR DESCRIPTION
**Pull request by youyongsong**
In case of external etcd, we should also modify `kubeadm-config.yaml` to set `api.advertiseAddress` to the local node's IP address.

### CODE REVIEW

**Comment by Bradamant3** [comment]
@chuckha @detiber ping, please?

**Comment by chuckha** [comment]
@Bradamant3 sorry, this one slipped under the radar, i can run through these instructions when i run through the 1.12 => 1.13 upgrade scenario as well in the next few days.

**Comment by chuckha** [comment]
/approve

thanks for fixing the omission

**Pull request merged**
