### PR TITLE
Fix ordered list with nested unordered list items

### PR DESCRIPTION
**Pull request by kbhawkey**

### CODE REVIEW

**Comment by stewart-yu** [comment]
rebase the commit, and check the preview https://deploy-preview-10677--kubernetes-io-master-staging.netlify.com

**Comment by kbhawkey** [comment]
I will try to rebase the commit.

**Comment by kbhawkey** [comment]
closing, rebase did not go so well.

**Comment by Bradamant3** [comment]
@kbhawkey I took a look at the preview anyway (sorry for the delay), and while this PR gets rid of the ordered list styling for unordered list children of ordered listitems, it doesn't apply any bulleted formatting. It's still a better solution than numbers, but it's not quite complete. If you open a new PR, please assign to me (again!) and I'll try to look sooner. And maybe note whether you address the bullets issue? (OK if you don't, but we should keep tracking.) Thanks!

**Comment by kbhawkey** [comment]
@Bradamant3, sure no problem. We could have updated this PR with bullets for the inner unordered list items. I will open a new PR instead.

**Pull request closed without merging**
