### PR TITLE
[ja]Fix invalid Japanese words

### PR DESCRIPTION
**Pull request by YuikoTakada**
This PR fixes invalid Japanese words "アーキテクチャー" to "アーキテクチャ".
This fix is based on the [guideline](https://kubernetes.io/ja/docs/contribute/localization/#%E9%A0%BB%E5%87%BA%E5%8D%98%E8%AA%9E).
This PR fixes: https://kubernetes.io/ja/docs/tasks/administer-cluster/nodelocaldns/

### CODE REVIEW

**Comment by atoato88** [comment]
LGTM

**Review by Arhell — COMMENTED** [review]
lgtm

**Review by nasa9084 — COMMENTED** [review]
/assign
/approve

Thank you~

**Pull request merged**
