### PR TITLE
Update scheduling-hugepages

### PR DESCRIPTION
**Pull request by jakspok**
The addition of the documentation in Spanish is made

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by bradtopol** [comment]
hi @jakspok thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by divya-mohan0209** [comment]
hi @jakspok thank you for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by Sea-n** [comment]
Thanks for your contribution! It seems like you updated the `content/en/docs/` rather than `content/es/docs/` by mistake, could you fix it and use `/unhold` command to let others know it's ready for review? 😊
/hold

**Comment by Sea-n** [comment]
Hey @jakspok,

Do you need help with moving the document? You can contact us on `#sig-docs` channel of [Kubernetes Slack](https://slack.k8s.io).

Feel free to `/reopen` this PR when you are ready to move forward.
/language es
/close

**Pull request closed without merging**
