### PR TITLE
[zh]fix guestbook.md: 原文："面向生产的" 斜体未生效

### PR DESCRIPTION
**Pull request by gaffeyQiu**

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
Thanks for catch!

/lgtm

**Comment by gaffeyQiu** [comment]
@mengjiao-liu @tengqm The problem appear again

**Comment by mengjiao-liu** [comment]
It looks like it was updated in commit f32c674f40d00aeaf99d9e6459befe0ddef0eb51
```diff
-本教程向您展示如何使用 Kubernetes 和 [Docker](https://www.docker.com/) 构建和部署
-一个简单的 _(非面向生产的)_ 多层 web 应用程序。本例由以下组件组成：
+本教程向你展示如何使用 Kubernetes 和 [Docker](https://www.docker.com/)
+构建和部署一个简单的**(非面向生产的)**多层 web 应用程序。本例由以下组件组成：
```
I have tested that `**` followed by punctuation will cause rendering to fail.
Add a space before and after the `**` to fix the problem. Modify as follows：
```
本教程向你展示如何使用 Kubernetes 和 [Docker](https://www.docker.com/)
构建和部署一个简单的 **(非面向生产的)** 多层 web 应用程序。本例由以下组件组成：
```

**Pull request merged**
