### PR TITLE
[zh-cn]: Batch replace "取回" of Chinese documents with "获取"

### PR DESCRIPTION
**Pull request by Eason1118**
Uniformly modify the "取回" contained in the Chinese document to "获取" to make it more friendly
please review

### CODE REVIEW

**Comment by tengqm** [comment]
@Eason1118 Please make sure you have checked the each and every file your are changing in this PR using the `scripts/lsync.sh` script. We cannot merge PRs with partial updates.

**Comment by Eason1118** [comment]
Thank you for your reminder. I have executed the script and there are no exceptions.
image

**Comment by windsonsea** [comment]
If the script doesn't work, you can compare [the en and zh history](https://github.com/kubernetes/website/commits/main/content/zh-cn/docs/concepts/cluster-administration/flow-control.md) one by one.

**Comment by windsonsea** [comment]
/hold
until all in-synced content are confirmed.

**Comment by Eason1118** [comment]
> 如果脚本不起作用，您可以逐一比较英文和中文历史记录（例如[此链接）。此过程可能需要一些时间，这就是为什么我们不在单个 PR 中包含许多文件的原因。](https://github.com/kubernetes/website/commits/main/content/zh-cn/docs/concepts/cluster-administration/flow-control.md)

@windsonsea 那我先关闭当前合并，对需要修改的单个文件所有内容进行中英比对，是否存在其他需要修改内容，最后以单个文件形式进行提交PR，对吗？

**Comment by windsonsea** [comment]
Yes, sir. That would be fine. Or, you can open an issue to discuss and arrange.

**Comment by Eason1118** [comment]
Thank you for your suggestion, I will abide by this rule and move forward

**Pull request closed without merging**
