### PR TITLE
Fix typo in documentation: TLS secrets

### PR DESCRIPTION
**Pull request by nfelger**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/28022#issuecomment-842969525

**Comment by nfelger** [comment]
Have signed the CLA now.

**Comment by kbhawkey** [comment]
Thanks @nfelger . The changes look good.
/lgtm

**Pull request merged**
