### PR TITLE
fix bad request for community file

### PR DESCRIPTION
**Pull request by charrywanganthony**

### CODE REVIEW

**Comment by Bradamant3** [comment]
/assign @castrojo 

Or do we want to link to the new contributor site instead?

**Comment by castrojo** [comment]
Contributor site won't be launching soon so I recommend going with the full URL. 

Contribex has a style guide for links but we've not gone through and back-fixed existing URLs: https://github.com/kubernetes/community/blob/master/sig-contributor-experience/markdown-link-style-guide.md

**Comment by charrywanganthony** [comment]
So i maintain the commit status quo for consistency in one file?

**Pull request merged**
