### PR TITLE
add Ygrene case study

### PR DESCRIPTION
**Pull request by alexcontini**
@kbarnard10 @KimMcMahon here is the new case study for review!

### CODE REVIEW

**Comment by alexcontini** [comment]
@kbarnard10 @zacharysarah  here is the PR to add Ygrene and Adform, I know everything is set up differently now, can you check if this correct and merge as soon as you can? thank you very much!


@KimMcMahon

**Comment by zacharysarah** [comment]
Hooray!

**Comment by apsega** [comment]
Any ETA when Adform Case Study will be published on the website?

**Comment by alexcontini** [comment]
@apsega the PR for adform is here: https://github.com/kubernetes/website/pull/10092#issuecomment-416262812 - are you able to merge when you have a chance?

**Comment by apsega** [comment]
@alexcontini I'm not a contributor, so I do not have any rights.

**Pull request merged**
