### PR TITLE
Fixed footer text that goes beyond the screen

### PR DESCRIPTION
**Pull request by Arhell**
issue #20157

### CODE REVIEW

**Comment by kbhawkey** [comment]
@Arhell , I just minimized my desktop browsers, Firefox and Chrome, and did not see the blank area.
What mobile platform/browser did you test? I will try Android+Chrome.
Viewed, https://kubernetes.io/de/docs/home/.

**Comment by tengqm** [comment]
/lgtm
Cannot reproduce this either. But from pure CSS perspective, cutting the overflow footer is not a bad idea.

**Comment by Arhell** [comment]
@kbhawkey 
I used chrome on my mobile, went to the site and swiped right.
I have a resolution of 375px
And to fully see the problem, you can through the developer panel in chrome on the PC, as indicated in the screenshot in issue

**Comment by kbhawkey** [comment]
@Arhell ,
This is a very _minor_ issue.
To reproduce: View a `de` page  (for example: https://kubernetes.io/de/) on a small screen or minimized desktop. So far, I have only been able to see the problem with the `de` localization.
Go to the bottom of the page. There will be a scrollbar to handle viewing the page with a small screen. You only see the extra space if you actually scroll. Otherwise, the area is hard to notice.
I question whether the change should be made in the footer section of _base.sass not _case-studies.sass.

**Comment by Arhell** [comment]
@kbhawkey 
Moved to the appropriate directory

**Comment by kbhawkey** [comment]
I retested this change, locally.
The overflow seems to only affect the footer when viewing the *case-studies` page.
There is a small right hand strip running from top to bottom of the page.
I strip is visible (for me, chrome+minimized desktop) for pages, `ja/case-studies`, `de-case-studies`.
You could re-title this PR to indicate that the issue is related to the case-studies pages and overflow in the footer.
I have not thoroughly tested this change.
/lgtm

**Pull request merged**
