### PR TITLE
[WIP] Update v1.18 OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by sftim**
Update `OWNERS_ALIASES` for v1.18 to include recent changes.

~I did this using a cherry-pick; if that should be a merge instead, I can do that.~

/cc @VineethReddy02

### CODE REVIEW

**Comment by VineethReddy02** [comment]
@sftim LGTM. Can you rebase the PR? We can go ahead with getting this done.

**Comment by VineethReddy02** [comment]
👋 Please rebase this PR on `dev-1.18` in order to avoid merge conflicts.

Feel free to `/hold cancel` after you've rebased.

/hold

**Comment by sftim** [comment]
I'm going to /close this one.

**Pull request closed without merging**
