### PR TITLE
Doc old version banner update

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=beOHaf0)

Fix: https://github.com/kubernetes/website/issues/38412

'Doc for old version' banner is missing for v1.25 docs . Updated that.

### CODE REVIEW

**Comment by SaumyaBhushan** [comment]
> /hold This doesn't look right to me. If this is merged to the 'main' branch which is live on the website instantly, what will happen?
> 
> This sounds something to go to the `release-1.25` branch if the fix is needed.

Yes it should be merged to `release-1.25` branch

**Comment by sftim** [comment]
@SaumyaBhushan - see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request for an explanation of how you can change the base branch based on @tengqm's advice.

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/38442#event-8023736964 shows that you did, _but_ GitHub seems confused. You may need to make the change again.

**Comment by SaumyaBhushan** [comment]
> ~[#38442 (comment)](https://github.com/kubernetes/website/pull/38442#event-8023736964) shows that you did, _but_ GitHub seems confused. You may need to make the change again.~
> 
> You changed it: [#38442 (comment)](https://github.com/kubernetes/website/pull/38442#event-8023732908) - but then I see that you changed it back.

Yes @sftim I have changed it again . Actually there were some conflicts , that's why I had changed it back to `main` . Please let me know if something else need to be changed from my side .

**Comment by reylejano** [comment]
This PR does not look right
If this PR is to add the banner/box that states the user is viewing the v1.25 docs and that it is no longer maintained then this PR should only update 1 file, the config.toml in the release-1.25 branch
I'm closing this PR as it is updating 208 files when it should only update 1
Feel free to fix reopen this PR if you disagree with `/reopen` in a comment
/close

**Comment by reylejano** [comment]
I made a replacement PR https://github.com/kubernetes/website/pull/39238

**Pull request closed without merging**
