### PR TITLE
Regenerate kubeadm reference doc

### PR DESCRIPTION
**Pull request by tengqm**
Reformat kubeadm reference doc for better readability.

### CODE REVIEW

**Comment by bradtopol** [comment]
@tengqm I'm confused.  Aren't these generated files?  Did you go in and edit them by hand?

**Comment by tengqm** [comment]
@bradtopol These are autogenerated docs. 

- Generator is located here: https://github.com/kubernetes-incubator/reference-docs/ 
- Guide on using the generator: https://kubernetes.io/docs/home/contribute/generated-reference/kubernetes-components/

The PR reworks the options for the kubeadm tool. Previously, the options are shown as verbatim text, very difficult to read thus barely useful. In this PR, the options are generated into nested tables so you can resize the web page freely and still read the options easily.

**Comment by tengqm** [comment]
Oh, forgot to mention, the revised generator is pushed for review as well. https://github.com/kubernetes-incubator/reference-docs/pull/47

**Comment by bradtopol** [comment]
Thanks for the clarification @tengqm! I'm assigning this to @steveperry-53 since I believe he is the expert on this.

**Comment by chenopis** [comment]
@bradtopol FYI, these are auto-generated and fed into the kubeadm docs as includes. For example,

https://deploy-preview-8115--kubernetes-io-master-staging.netlify.com/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_addon_all/

ends up here

https://deploy-preview-8115--kubernetes-io-master-staging.netlify.com/docs/reference/setup-tools/kubeadm/kubeadm-alpha/#cmd-phase-addon

/lgtm
/approve

**Pull request merged**
