### PR TITLE
[ja] Update page weights under content/ja/docs/reference.

### PR DESCRIPTION
**Pull request by s-kawamura-w664**
This PR updates the page weights under content/ja/docs/reference.
This updates the page order.

Related: #37717

Only the following file was already set in #29847.
- content/ja/docs/reference/kubectl/cheatsheet.md

### CODE REVIEW

**Comment by s-kawamura-w664** [comment]
content/ja/docs/reference/kubenet/overview.md was removed from en.
But there are still left in ja.
The page's contents would need to be moved to _index.md.
This PR is purpose to update weights, so another PR is needed.
Related: #29847

**Review by t-inu — COMMENTED** [review]
/lgtm

**Comment by s-kawamura-w664** [comment]
/assign @nasa9084 @inductor 
Could you confirm for approval.

**Pull request merged**
