### PR TITLE
assign inductor as sig-docs-ja approver

### PR DESCRIPTION
**Pull request by nasa9084**
@inductor helps us many time and I think @cstoku is busy recent days.

### CODE REVIEW

**Comment by inductor** [comment]
Thank you :D

**Comment by inductor** [comment]
@zacharysarah I think you made a typo :P

**Comment by inductor** [comment]
@zacharysarah ping

**Comment by zacharysarah** [comment]
@inductor Sorry, autocorrect is awful 😆 

/approve

**Pull request merged**
