### PR TITLE
Provide more pixels for Learn Kubernetes Basics

### PR DESCRIPTION
**Pull request by kbhawkey**
See issue #10309.

### CODE REVIEW

**Comment by kbhawkey** [comment]
@zparnold, do you know if I need to commit the generated sass .content, .json files under resources? 
I tested locally and all seemed well, but the deploy preview is not showing the change?

**Comment by kbhawkey** [comment]
The preview does not look as expected. Still questioning if the sass resources files are correct.

**Comment by Bradamant3** [comment]
@lucperkins can you please take a look, as the Knower of All Things Sass here?

**Comment by kbhawkey** [comment]
See PR #10353. I had to do some fix-ups of the resources files. Have a look at the new PR. Thanks.

**Comment by kbhawkey** [comment]
I am closing this as the resource files were not correct. See PR #10353 instead.

**Pull request closed without merging**
