### PR TITLE
[ja] Fix link to 'Node heartbeats' section

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/46276/files

### CODE REVIEW

**Review by Okabe-Junya — APPROVED** [review]
Thank you!!

This PR looks good to me, but the link doesn’t seem to be working properly. (The node page needs to be updated)

/lgtm
/hold
/assign bells17
for approval

FYI: [Deploy preview](https://deploy-preview-46939--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/architecture/leases/)

**Comment by Okabe-Junya** [comment]
Opened #46940. once this PR merged, feel free to unhold :) Thank you!

**Comment by Arhell** [comment]
> Opened #46940. once this PR merged, feel free to unhold :) Thank you!

Thanks

**Review by Arhell — COMMENTED** [review]
https://github.com/kubernetes/website/pull/46940 merge

**Pull request merged**
