### PR TITLE
Rename "Scheduling" concept as "Scheduling and Eviction"

### PR DESCRIPTION
**Pull request by adambkaplan**
* en, ja, zh, ko: move "scheduling" to "scheduling-eviction"
* en: rename "Scheduling" to "Scheduling and Eviction"
* Add redirects
* Replace "scheduling" links with "scheduling-eviction"

Part of proposal #19081

Signed-off-by: Adam Kaplan <adam.kaplan@redhat.com>

### CODE REVIEW

**Comment by sftim** [comment]
@adambkaplan I like this idea, _but_ it will be hard to review as-is.
Please separate this PR into an English localization change followed by separate changes for each downstream localization. The redirects should mean that downstream localizations don't have to change in lock step.

See https://kubernetes.io/docs/contribute/intermediate/#working-with-localized-content

**Comment by kbhawkey** [comment]
Hi @adambkaplan ,
Would you have time to split out the localized content from this pull request and rebase?
Thanks!

**Comment by adambkaplan** [comment]
@kbhawkey @sftim @bradtopol took me a while to get around to this. Rebased and only included the English localization.

**Comment by sftim** [comment]
@adambkaplan looks like this needs another rebase. Could you rebase this again?

/remove-language fr
/remove-language ja
/remove-language ko
/remove-language pl
/remove-language zh

**Comment by adambkaplan** [comment]
@sftim rebased again - ptal

**Comment by sftim** [comment]
/lgtm
Thanks @adambkaplan

**Comment by zacharysarah** [comment]
@adambkaplan Nice, thanks for this! ✨ 

/approve

**Comment by alculquicondor** [comment]
`scheduling-eviction` doesn't read well to me. Is having `-and-` in the path against any guidance?

**Comment by sftim** [comment]
`scheduling-and-eviction` would also be a valid name.

**Comment by alculquicondor** [comment]
@Hsiny would you mind fixing this?

**Comment by Hsiny** [comment]
@alculquicondor  ok, I will create a PR for renaming the link from `scheduling-eviction` to `scheduling-and-eviction`

**Pull request merged**
