### PR TITLE
Added Verification Scenario for a Pod that Uses a PVC in Terminating State

### PR DESCRIPTION
**Pull request by pospispa**
Documentation for PR:
https://github.com/kubernetes/kubernetes/pull/55873

Target release: 1.10

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7164)

### CODE REVIEW

**Comment by Bradamant3** [comment]
@pospispa also please resubmit for merge to the 1.10 docs branch. Thanks!

**Comment by pospispa** [comment]
@Bradamant3 done.

**Comment by msau42** [comment]
Err did this also need docs review too?

**Comment by pospispa** [comment]
Yeap, the docs review is needed.
@zhangxiaoyu-zidif @xiangpengzhao @Bradamant3 please, will you do docs review after the PR was prematurely merged?

**Comment by zhangxiaoyu-zidif** [comment]
@pospispa  this PR was merged 15 hours ago.

**Comment by msau42** [comment]
From my understanding, all docs changes need a tech review and a docs review.  The process used to be that you could lgtm a tech review, and then it would get docs review, and be manually merged.  But looks like auto merge is now enabled, so it seems like we need to change the process to be able to handle both tech + docs review before the change gets merged.

**Comment by msau42** [comment]
I spoke to @bradamant3 and have added it to the [spreadsheet](https://docs.google.com/spreadsheets/d/17bZrKTk8dOx5nomLrD1-93uBfajK5JS-v1o-nCLJmzE/edit#gid=0), so it won't be forgotten about.

Also they are working on fixing all the approvers, so hopefully this issue shouldn't happen again.

**Pull request merged**
