### PR TITLE
Add API reference for v1.31

### PR DESCRIPTION
**Pull request by tengqm**
### Issue

Closes: #

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Linking the issue opened up to flag that API reference for v1.31 wasn't generated

**Comment by tengqm** [comment]
preview: https://deploy-preview-47530--kubernetes-io-main-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.31/

**Comment by dims** [comment]
@tengqm is https://github.com/kubernetes/website/blob/main/README.md#building-the-api-reference-pages still the process you follow?

I remember trying it but that needed updates to the following files... should they be checked in too? if not can we get the README.md updated with latest steps?

- api-ref-assets/config/fields.yaml
- api-ref-assets/config/toc.yaml

**Comment by tengqm** [comment]
> @tengqm is https://github.com/kubernetes/website/blob/main/README.md#building-the-api-reference-pages still the process you follow?
> 
> I remember trying it but that needed updates to the following files... should they be checked in too? if not can we get the README.md updated with latest steps?
> 
>     * api-ref-assets/config/fields.yaml
> 
>     * api-ref-assets/config/toc.yaml

No. The `api-ref-assets/*` files are used by `https://github.com/kubernetes-sigs/reference-docs/tree/master/gen-resourcesdocs`. The generated reference is published at https://kubernetes.io/docs/reference/kubernetes-api/. This generator produces Markdown files so that the look-and-feel is closer to the rest of the website.

This PR adds the single-page reference at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/. The single-page version is a huge HTML page.

**Comment by dims** [comment]
@tengqm thanks for the detail, specific question as i am a bit confused still. if i had to generate this myself what would the steps be?

> This PR adds the single-page reference

How do i do ^^^ myself?

**Comment by tengqm** [comment]
> @tengqm thanks for the detail, specific question as i am a bit confused still. if i had to generate this myself what would the steps be?
> 
> > This PR adds the single-page reference
> 
> How do i do ^^^ myself locally?

In the https://github.com/kubernetes-sigs/reference-docs project, do `make api`, that's all.

**Comment by dims** [comment]
> In the https://github.com/kubernetes-sigs/reference-docs project, do `make api`, that's all.

Ah! i totally missed that. can we put it in the README somewhere? https://github.com/kubernetes-sigs/reference-docs/blob/master/README.md or other place?

thanks @tengqm

**Comment by sftim** [comment]
I recommend adding a PR description; however, I know what's intended here.

/approve

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!

/lgtm

**Pull request merged**
