### PR TITLE
Blog post: Hugo migration

### PR DESCRIPTION
**Pull request by zacharysarah**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.11 Features: set Milestone to 1.11 and Base Branch to release-1.11
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by jaredbhatti** [comment]
Looks good to me :)

**Comment by zacharysarah** [comment]
@kbarnard10 👋 We'd like this to publish more or less simultaneously with the site cutover to Hugo. (We're considering later today, so ~4-9 hours.) Does that work for you?

**Comment by kbarnard10** [comment]
@zacharysarah Just remove the hold when you're ready

**Pull request closed without merging**
