### PR TITLE
[wip]testing 1.20 reference docs build

### PR DESCRIPTION
**Pull request by kbhawkey**
Testing reference generation for 1.20
Do not merge

### CODE REVIEW

**Comment by kbhawkey** [comment]
I am testing the build configuration file (reference.yml).

**Comment by kbhawkey** [comment]
Some preview pages:
https://deploy-preview-25355--kubernetes-io-master-staging.netlify.app/docs/reference/kubectl/kubectl/
https://deploy-preview-25355--kubernetes-io-master-staging.netlify.app/docs/reference/generated/kubectl/kubectl-commands
https://deploy-preview-25355--kubernetes-io-master-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-join/
https://deploy-preview-25355--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kube-proxy/

The API reference needs further updates
https://deploy-preview-25355--kubernetes-io-master-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.20/

**Comment by annajung** [comment]
Thank you @kbhawkey! Once https://github.com/kubernetes-sigs/reference-docs/pull/180 merges, I can try it out to see if I can get the same results.

you mentioned
> The API reference needs further updates
https://deploy-preview-25355--kubernetes-io-master-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.20/

Is that something that's not solved by https://github.com/kubernetes-sigs/reference-docs/pull/180 ? Can you clarify what other work needs to be done?

**Comment by kbhawkey** [comment]
I included updates to reference.yml, though, some of the changes should be reverted once the
updates are permanently made in reference-docs.

**Comment by kbhawkey** [comment]
Hi @annajung . I updated the file `update-imported-docs/reference.yml` and retested.
When you have time, would you try to use this file to generate the reference docs? Copy the file to your local website repository. There is a pending update to the API reference (you'll see a warning about a missing resouce, but the build should complete).
Let me know how you get on. Thanks!

**Comment by kbhawkey** [comment]
Related to #25374 .
/close

**Pull request closed without merging**
