### PR TITLE
Fixes typo

### PR DESCRIPTION
**Pull request by rileyL6122428**

### CODE REVIEW

**Review by christomas1 — APPROVED** [review]

**Review by Arhell — COMMENTED** [review]
@rileyL6122428  You can make your emails match up in one of two ways:

1. Login to the [CLA site](https://identity.linuxfoundation.org/projects/cncf) and change it to match what you use as your default email address on your GitHub account
2. Change your default email address on your GH account to the same one you used to sign the CLA.

**Comment by rileyL6122428** [comment]
@Arhell I finished the CLA, sorry for the wait.

**Pull request merged**
