### PR TITLE
Fix feature state for ExpandCSIVolumes

### PR DESCRIPTION
**Pull request by miteshskj**
ExpandCSIVolumes feature is GA since 1.24

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/lgtm
/approve

**Comment by miteshskj** [comment]
Thanks @sftim 
Any idea how to address the deploy failures? The build is timing out after 35 minutes, doesn't look like related to this change.

**Comment by sftim** [comment]
Try rebasing against _main_ - we applied some fixes recently.

**Comment by sftim** [comment]
I'll also trigger Netlify to try that build again.

**Pull request merged**
