### PR TITLE
Translate clc.md

### PR DESCRIPTION
**Pull request by yixin21**
zh-trans clc.md

ref:k8smeetup/website-tasks#3283

### CODE REVIEW

**Comment by jimangel** [comment]
@yixin21 @markthink should this PR be against release-1.16? It also appears these edits are on the English content instead of Chinese. Thanks!

/cc @tengqm

**Comment by tengqm** [comment]
Ya. Looks this is targeting the wrong branch, and it is adding files to an incorrect path.

**Pull request closed without merging**
