### PR TITLE
Remove /security/ alias for ko translation

### LINKED ISSUE #18129: k8s.io/security short link is now redirecting to the Security page in Korean
**What happened**: The short link [https://k8s.io/security](https://k8s.io/security) is now redirecting to the Kubernetes Security and Disclosure Information page in Korean at [https://kubernetes.io/ko/docs/reference/issues-security/security/](https://kubernetes.io/ko/docs/reference/issues-security/security/) by default

**What you expected to happen**: It used to redirect to the page in English at [https://kubernetes.io/docs/reference/issues-security/security/](https://kubernetes.io/docs/reference/issues-security/security/)

**How to reproduce it (as minimally and precisely as possible)**: Click on [https://k8s.io/security](https://k8s.io/security)

**Anything else we need to know?**: I hadn't checked the link since August and I'm not sure how long it's been doing that.

**Environment**: It is doing this in Chrome, Firefox and Safari on a Mac.

### PR DESCRIPTION
**Pull request by cblecker**
This will need to be cherry picked back to 1.16/1.17
fixes #18129

### CODE REVIEW

**Comment by cblecker** [comment]
@kubernetes/sig-docs-ko-owners @zacharysarah

**Comment by zacharysarah** [comment]
Preview looks good.

https://deploy-preview-18132--kubernetes-io-master-staging.netlify.com/docs/reference/issues-security/security/

/lgtm
/approve

**Comment by zacharysarah** [comment]
@cblecker Thanks for this fix! ✨ For the duration of the 1.17 release, PRs to `master` fix 1.17 content. If you open The same PR against `release-1.16`, I’m happy to approve it also.

**Comment by cblecker** [comment]
@zacharysarah Done! Opened #18134

**Pull request merged**
