### PR TITLE
[ja]Update alpha or beta feature gates

### PR DESCRIPTION
**Pull request by YuikoTakada**
This PR updates alpha or beta feature gates list.
This PR updates below web page:
https://kubernetes.io/ja/docs/reference/command-line-tools-reference/feature-gates/

FYI: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

### CODE REVIEW

**Comment by atoato88** [comment]
For all reviews.

Link to the page on the preview site:
https://deploy-preview-38037--kubernetes-io-main-staging.netlify.app/ja/docs/reference/command-line-tools-reference/feature-gates/

**Comment by atoato88** [comment]
I checked that [`AlphaまたはBetaのフィーチャーゲート`](https://deploy-preview-38037--kubernetes-io-main-staging.netlify.app/ja/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features) section equals to EN content.
But what do you think about [`フィーチャーゲート`](https://deploy-preview-38037--kubernetes-io-main-staging.netlify.app/ja/docs/reference/command-line-tools-reference/feature-gates/#%E3%83%95%E3%82%A3%E3%83%BC%E3%83%81%E3%83%A3%E3%83%BC%E3%82%B2%E3%83%BC%E3%83%88) section?

**Comment by YuikoTakada** [comment]
I just updated [AlphaまたはBetaのフィーチャーゲート](https://deploy-preview-38037--kubernetes-io-main-staging.netlify.app/ja/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features) section.
About other sections in the same page, I'm planning to update it in other PRs because there are huge updates in this page.
Thanks!

**Comment by atoato88** [comment]
/lgtm
Thank you for response.
It's reasonable for updating and reviewing, so I'll wait the next PR.

**Comment by tengqm** [comment]
/retitle [ja]Update alpha or beta feature gates

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by atoato88** [comment]
/assign @nasa9084 
Could you review this?
This PR has updated just the [AlphaまたはBetaのフィーチャーゲート](https://deploy-preview-38037--kubernetes-io-main-staging.netlify.app/ja/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features) section which is a part of this page.
Other part of this page will be updated on other PR.

**Comment by nasa9084** [comment]
Thank you for your hard working...!
/approve

**Pull request merged**
