### PR TITLE
[zh] translate Concepts/Pod Priority and Preemption

### LINKED ISSUE #28224: [zh] translate concepts/Pod Priority and Preemption
**This is a Feature Request**
translate /docs/concepts/scheduling-eviction/pod-priority-preemption.md into Chinese

**What would you like to be added**
/zh/docs/concepts/scheduling-eviction/pod-priority-preemption.md

/language zh
/assign

### PR DESCRIPTION
**Pull request by zhiguo-lu**
translate /docs/concepts/scheduling-eviction/pod-priority-preemption.md into Chinese.

close #28224

### CODE REVIEW

**Comment by tengqm** [comment]
A dup of #28351?

**Comment by zhiguo-lu** [comment]
> A dup of #28351?

Oh，dup！How to deal with it? Should I close this one?

**Comment by tengqm** [comment]
@zhiguo-lu this is a happy accident. One of you have to abandon the PR.

**Comment by howieyuen** [comment]
oops...looks like we make a duplicated [PR](https://github.com/kubernetes/website/pull/28351)

**Comment by howieyuen** [comment]
> > A dup of #28351?
> 
> Oh，dup！How to deal with it? Should I close this one?

sorry, I skipped making issue step and run into PR making directly. 
since @tengqm has already reviewed my PR and comment with "approved", so I sincerely invite you to review my work, ok? 🍭

**Comment by zhiguo-lu** [comment]
> > > A dup of #28351?
> > 
> > 
> > Oh，dup！How to deal with it? Should I close this one?
> 
> sorry, I skipped making issue step and run into PR making directly.
> since @tengqm has already reviewed my PR and comment with "approved", so I sincerely invite you to review my work, ok? 🍭

sure, glad to

**Pull request closed without merging**
