### PR TITLE
Tweak extensible admission controllers page

### PR DESCRIPTION
**Pull request by tengqm**
This PR removes outdated information about `admissionregistration.v1beta1` API groups which are no longer supported in 1.24. Additional notes are added to avoid confusion when parsing the examples.

closes: #34575

### CODE REVIEW

**Comment by tengqm** [comment]
Preview: https://deploy-preview-34740--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/extensible-admission-controllers/

**Review by Sea-n — COMMENTED** [review]
I think it would be better to split commit into formatting and rewording.

Anyway, the changes looks good to me!
/lgtm

**Pull request merged**
