### PR TITLE
Remove extra space from yaml files

### PR DESCRIPTION
**Pull request by dhanraj322**
Fix: [issues/34447](https://github.com/kubernetes/website/issues/34447)

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jihoon-seo** [comment]
I think that your suggestion in this PR cannot fix #34447.

**Comment by dhanraj322** [comment]
@jihoon-seo I ran this website locally using a container, it seems to be working for me. Let me know if there is anything else I can do to make sure.

**Comment by jihoon-seo** [comment]
@dhanraj322 
- I checkouted this PR in my dev environment (Ubuntu 18.04 desktop amd64),
- pulled submodules (`git submodule update --init --recursive --depth 1`),
- and ran the website using a container (`make container-serve`).

After doing those steps, I checked and confirm that the issue #34447 is reproducible and persists in my local container preview.
(Ubuntu 18.04 desktop amd64, Firefox 101.0.1 (64-bit))

**Comment by dhanraj322** [comment]
@jihoon-seo Right, I got it now. My bad.

**Pull request closed without merging**
