### PR TITLE
[KEP-2681] Docs update for Beta PodHostIPs

### PR DESCRIPTION
**Pull request by wzshiming**
ref: https://github.com/kubernetes/enhancements/issues/2681

### CODE REVIEW

**Comment by harshitasao** [comment]
Hi @wzshiming , Please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before **Tuesday 14th November 2023**. 
Thank you!

**Comment by harshitasao** [comment]
Hi, @wzshiming  ! Kubernetes v1.29 Docs Shadow here. **Just a reminder that the deadline to have this PR reviewed and merged is Tuesday, 28 November**. Let me know if you need any help!

**Comment by wzshiming** [comment]
This PR is ready to review

/cc sig-docs-en-reviews

**Pull request merged**
