### PR TITLE
[en] Fixes typo in documentation

### PR DESCRIPTION
**Pull request by DhritiShikhar**

### CODE REVIEW

**Comment by Shubham82** [comment]
@DhritiShikhar, It seems this PR includes changes to files across multiple languages i.e. English and Chinese. The documentation process varies for each localization. So you have to make changes in the Primary website content which is English content with this PR. Once English content PR is merged, you can raise PR for other languages.

**Comment by Shubham82** [comment]
hold until this PR only covers one language (en)

/hold

remove the hold label once the PR is modified to one language

**Comment by DhritiShikhar** [comment]
> @DhritiShikhar, It seems this PR includes changes to files across multiple languages i.e. English and Chinese. The documentation process varies for each localization. So you have to make changes in the Primary website content (English content) with this PR. Once English content PR is merged, you can raise PR for other languages.

I have removed other changes. Now, this PR fixes typo in English documentation only. I will raise another one for Chinese documentation changes. Can you please take a look again @Shubham82 ?

**Comment by Shubham82** [comment]
Thanks, @DhritiShikhar for this fix
The preview looks good to me.
https://deploy-preview-47060--kubernetes-io-main-staging.netlify.app/docs/concepts/cluster-administration/flow-control/#recursive-server-scenarios

/lgtm

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for the fix!
Congrats on your first PR 🎉

/approve

**Pull request merged**
