### PR TITLE
Revise API reference for v1.29

### PR DESCRIPTION
**Pull request by tengqm**
This PR also includes a version bump of the bootstrap css files.

---

Fixes https://github.com/kubernetes/website/issues/44375

### CODE REVIEW

**Comment by sftim** [comment]
/lgtm

Thank you.
Should we use the same CSS file for the older API references too?

**Comment by tengqm** [comment]
> /lgtm
> 
> Thank you. Should we use the same CSS file for the older API references too?

I'll go through the reference to other versions and clear them when possible.
I'm not inclined to rebuild the reference for older versions and push the new js/css there. It will work but we gain nothing from it.

**Comment by adityasamant25** [comment]
It would be great if this PR is approved quickly as there are more issues being raised for the broken links
#44385 
#44387

**Comment by sftim** [comment]
This PR is ready for approval.

**Pull request merged**
