### PR TITLE
fix a typo, cronjob ->cron job

### PR DESCRIPTION
**Pull request by siliangxifeng1988**
fix a typo, cronjob ->cron job in line 38, line 46 and line 54.

### CODE REVIEW

**Comment by stewart-yu** [comment]
seems reasonable,  waitting others for review
/approve

**Comment by tengqm** [comment]
If wanted, 'cronjob' can be changed to 'CronJob', but not 'cron job'.

**Comment by cody-clark** [comment]
@tengqm It looks like we're not completely consistent. [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) and [Running Automated Tasks with a CronJob](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/) both use CronJob and Cron Job with a space. 

Should we change every instance in our documentation to CronJob or could there be semantic reasons to use both? Either way, I'll be happy to add a style guide entry. 

cc: @Bradamant3 @chenopis

**Comment by chenopis** [comment]
If the documentation is referring to the Kubernetes resource specifically, it should be *CronJob*. However, the more general notion of a [cron job](https://en.wikipedia.org/wiki/Cron) has been around in Unix for a long time. So, if the content is referring to being to schedule jobs, then *cron job* is acceptable. It should never be the case that it's capitalized with a space, *Cron Job*.

IMHO, I think it should be rewritten to avoid the confusion and mostly focus on CronJob. For example:

> You can use the CronJob resource to run automated tasks on a time-based schedule, similar to  cron jobs on a Linux or UNIX system.
>
> CronJob can be useful for creating periodic and recurring tasks, like running backups or sending emails. It can also schedule individual tasks for a specific time, such as if you want to schedule a job for a low activity period.

**Comment by cody-clark** [comment]
Hi, @siliangxifeng1988, I'm going to close this per @chenopis' comment. 
/close

**Pull request closed without merging**
