### PR TITLE
Update kubespray.md for link to ansible doc

### PR DESCRIPTION
**Pull request by tocado**
update link to playbook variables in ansible

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/lgtm

Thanks @tocado

**Comment by sftim** [comment]
Ah, oops. You do need a  signed CLA before we can _formally_ review this.

**Comment by tocado** [comment]
> Ah, oops. You do need a signed CLA before we can _formally_ review this.

/check-cla

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-27366--kubernetes-io-master-staging.netlify.app/docs/setup/production-environment/tools/kubespray/

**Comment by kbhawkey** [comment]
Thanks @tocado .
/approve

**Pull request merged**
