### PR TITLE
Change incorrect string raw to block

### LINKED ISSUE #12925: Wrong string for raw block volumes
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
The documentation says that you should set `volumeMode` to `raw` for a raw block device. In reality you should set it to `block`.

**Proposed Solution:**
Change `raw` to `block`

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes

### PR DESCRIPTION
**Pull request by bswartz**
Correct a typo in the volumeMode documentation.

Fixes #12925

### CODE REVIEW

**Comment by zacharysarah** [comment]
@bswartz Is this PR for the 1.14 release? If so, it needs to base on `dev-1.14`. 

/cc @jimangel

**Comment by bswartz** [comment]
@msau42 PTAL

**Pull request merged**
