### PR TITLE
Localize content/en/docs/reference/glossary/cgroup.md in hindi

### PR DESCRIPTION
**Pull request by taniaduggal**
Signed-off-by: Tania Duggal <103496926+taniaduggal@users.noreply.github.com>

fixes #36185

### CODE REVIEW

**Comment by taniaduggal** [comment]
@divya-mohan0209

**Comment by divya-mohan0209** [comment]
Please update your fork @taniaduggal and sync changes to the branch.

**Comment by taniaduggal** [comment]
@divya-mohan0209 how to do this? I tried but it doesn't show here, maybe i did something wrong

**Comment by NitishKumar06** [comment]
> @divya-mohan0209 how to do this? I tried but it doesn't show here, maybe i did something wrong

1. Reset the last commit you made
2. Sync your forked branch with upstream and pull the changes to your local branch.
3. Push the changes  (using `-f`)

**Pull request closed without merging**
