### PR TITLE
Minor text changes to the index of tasks/debug/debug-cluster

### PR DESCRIPTION
**Pull request by Rajdeep1311**
Documentation Changes

- fixed some typos in the docs
- makes the sentences in the website grammatically correct

### CODE REVIEW

**Comment by windsonsea** [comment]
It would be better to provide:

- a specific title
- some description to tell why this is needed

/retitle Minor text changes to the index of tasks/debug/debug-cluster

**Comment by utkarsh-singh1** [comment]
Try to add description of the PR  @Rajdeep1311. U can use given PR template.

**Review by kumarankit999 — COMMENTED** [review]
Thanks for Contributing @Rajdeep1311, Looking Now Fixed!!

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @Rajdeep1311 , please note that this is a [trivial edit](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) per our policy since this doesn't significantly improve the quality of our documentation. We'd request you to batch them instead of contributing one or two commas/periods/articles. 

I'll be approving this for now, however, please be mindful of this policy in the future.

/approve

**Comment by Rajdeep1311** [comment]
@divya-mohan0209 Okay ma'am. Noted!

**Pull request merged**
