### PR TITLE
Update network-policies.md

### PR DESCRIPTION
**Pull request by anldzd**
“The entities that a Pod can communicate with” 翻译由 “Pod 可以通信的 Pod ” 改为 “Pod 可以通信的实体”

### CODE REVIEW

**Comment by reylejano** [comment]
@anldzd Please sign the [CLA](https://github.com/kubernetes/community/blob/master/CLA.md) for this PR to be reviewed

**Comment by celestehorgan** [comment]
Hi @anldzd,

Do you need help signing the CLA?

**Comment by tengqm** [comment]
@anldzd Pls feel free to reopen this when you are back to this. Be sure to get the CLA issue fixed first though.
/close

**Pull request closed without merging**
