### PR TITLE
Fix links to ephemeral volume types

### LINKED ISSUE #33564: Links to some ephemeral volume types are wrong
**This is a Bug Report**

**Problem:**
Links to some ephemeral volume types are wrong.

**Proposed Solution:**
In https://kubernetes.io/docs/concepts/storage/volumes/ , update links as follows:
- `/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volume`
  → `/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes`
- `/docs/concepts/storage/ephemeral-volumes/#csi-ephemeral-volume`
  → `/docs/concepts/storage/ephemeral-volumes/#csi-ephemeral-volumes`

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volumes/

/language en
/assign

### PR DESCRIPTION
**Pull request by jihoon-seo**
Closes #33564

### CODE REVIEW

**Comment by Sea-n** [comment]
Looks good to me!
/lgtm

**Comment by zacharysarah** [comment]
@tengqm Weird, it looks like Prow missed your approval. Trying again:

/approve
/kind cleanup

**Pull request merged**
