### PR TITLE
Update minikube.md

### PR DESCRIPTION
**Pull request by Magro28**
Fix linking in same document for preventing 404 errors because the url parts get duplicated now.
e.g: https://kubernetes.io/docs/setup/minikube/docs/setup/minikube/#interacting-with-your-cluster
fix would be: https://kubernetes.io/docs/setup/minikube/#interacting-with-your-cluster

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by kbhawkey** [comment]
Thanks for this PR.
/lgtm

**Comment by Rajakavitha1** [comment]
Thanks for this PR
/approve

**Comment by tddorgtfo** [comment]
Fixes #14623

**Pull request merged**
