### PR TITLE
Fix outdated content in feature gates

### PR DESCRIPTION
**Pull request by tengqm**
Also applied some line wrapping, reordering of items.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-26144--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates/

**Comment by kbhawkey** [comment]
The tables render without errors.
Generally, the changes look good to me. Thanks!

**Comment by bradtopol** [comment]
Assigning @kbhawkey since she is already engaged on this.
/assign @kbhawkey

**Pull request merged**
