### PR TITLE
Update languageName = "हिन्दी" in config.toml to implement recent cha…

### LINKED ISSUE #35783: [hi] Update `languageName = "हिन्दी"` in config.toml to implement recent changes in the language name standard.
**This is a Bug Report**

**Problem:**

`config.toml` in `dev-1.22-hi.1` contains `languageName = "हिन्दी"`
`config.toml` in `main` contains  `languageName = "हिन्दी (Hindi)"`, which conforms to recent changes in the recent [language name standard](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/localization.md#modify-the-site-configuration). Also see #31657

**Proposed Solution:**

- We should update this line in `dev-1.22-hi.1` so it is the same as `main`.

**Page to Update:**

`config.toml`

### PR DESCRIPTION
**Pull request by rolfedh**
…nges in the language name standard.

Fixes #35783

### CODE REVIEW

**Comment by sftim** [comment]
@rolfedh Please avoid referencing issues in:
- branch names
- commit messages
- PR titles
  (mentioning in PR _descriptions_ is not just OK, I recommend it)

Could you open a similar PR but with a different branch name and a different commit message?

/language hi
/hold

The reason we've historically avoided this is in case of forks: we get noise when forks of Kubernetes duplicate or reference these commits.

**Comment by rolfedh** [comment]
/assign @Garima-Negi
/assign @divya-mohan0209 
Please review and approve for merge.

**Comment by rolfedh** [comment]
Also see https://github.com/kubernetes/website/pull/29679/files#r939666948

**Comment by rolfedh** [comment]
> Could you open a similar PR but with a different branch name and a different commit message?

Sure, no problem! I'll check with you for guidance on the conventions this repo follows.

**Comment by rolfedh** [comment]
Close in favor of https://github.com/kubernetes/website/pull/35898, @xzyangNB

**Pull request closed without merging**
