### PR TITLE
Remove "Running Kubernetes on CenturyLink Cloud"

### LINKED ISSUE #17514: Dated content in “Running Kubernetes on CenturyLink Cloud”
**Problem:**
[Running Kubernetes on CenturyLink Cloud](https://kubernetes.io/docs/setup/production-environment/turnkey/clc/) is very dated; it talks about “minions” rather than nodes, which means that Kubernetes has moved on quite a lot since that page was last accurate.

**Proposed Solution:**
Either:
- delete the page, and justify that deletion
- review the page and update it to be current.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/turnkey/clc/

**Notes:**
[KEP #1327](https://github.com/kubernetes/enhancements/pull/1327) “3rd party content in documentation” may be relevant here.

/kind cleanup
/language en
/priority backlog

### PR DESCRIPTION
**Pull request by prasadkatti**
Fixes #17514

### CODE REVIEW

**Comment by sftim** [comment]
/lgtm

/sig cloud-provider
/sig cluster-lifecycle

(I think those are appropriate)

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-21155--kubernetes-io-master-staging.netlify.app/docs/setup/

**Comment by kbhawkey** [comment]
Changes are within the guidelines of the [KEP](https://github.com/kubernetes/enhancements/pull/1327) and https://github.com/kubernetes/website/issues/20232.
LGTM

**Pull request merged**
