### PR TITLE
Update outdated files in the dev-1.20-ko.4 branch (1)

### PR DESCRIPTION
**Pull request by jmyung**
Fixes the part of #26284

This PR contains updates for the following files:

- [ ]  M1. content/en/docs/concepts/architecture/controller.md | 1(+XS) 1(-).   <-- this doesn't need to be fixed in Korean.
- [x]  M2. content/en/docs/concepts/cluster-administration/system-metrics.md | 1(+XS) 0(-)
- [x]  M3. content/en/docs/concepts/configuration/secret.md | 11(+S) 2(-)
- [x]  M4. content/en/docs/concepts/containers/container-lifecycle-hooks.md | 1(+XS) 1(-)
- [x]  M5. content/en/docs/concepts/containers/runtime-class.md | 5(+XS) 12(-)
- [x]  M6. content/en/docs/concepts/extend-kubernetes/extend-cluster.md | 2(+XS) 2(-)
- [x]  M7. content/en/docs/concepts/services-networking/ingress-controllers.md | 2(+XS) 1(-)
- [x]  M8. content/en/docs/concepts/services-networking/ingress.md | 1(+XS) 1(-)

### CODE REVIEW

**Comment by seokho-son** [comment]
@ianychoi 리뷰 가능하실까요 ~ ? ^^

/assign @ianychoi

**Comment by jmyung** [comment]
Sorry for being late all the time. 😿

**Comment by seokho-son** [comment]
@jmyung Not at all :) We always appreciate with your contributions ! 
I think it is hard to keep contributing continuously. Let's make contribution activity enjoyable !
(FYI: I am also working on updating outdated contents ;) )

**Comment by seokho-son** [comment]
@jmyung Thank you !! It looks nice.
/lgtm
/approve

**Pull request merged**
