### PR TITLE
Update typo in documentation

### PR DESCRIPTION
**Pull request by lvthanh03**
### Description

Should be _Validation Ratcheting_ instead of _Validation Racheting_.

### CODE REVIEW

**Comment by stmcginnis** [comment]
Thanks @lvthanh03. Are you able to sign the CLA? That will need to be done before any changes can be accepted.

Also, please update this to only update the `en` file to start. After that merges then any other languages can be updated as a follow on.

**Comment by lvthanh03** [comment]
> Thanks @lvthanh03. Are you able to sign the CLA? That will need to be done before any changes can be accepted.
> 
> Also, please update this to only update the `en` file to start. After that merges then any other languages can be updated as a follow on.

Hey @stmcginnis, thanks for the quick look. Signed the CLA as well updated PR so that it only includes changes in the EN docs.

**Comment by stmcginnis** [comment]
/lgtm

Thanks!

**Comment by lvthanh03** [comment]
@dipesh-rawat for approval. Thanks!

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!

/approve

**Pull request merged**
