### PR TITLE
Add systems:master mention to the Authz reference page

### LINKED ISSUE #48546: Mention `system:masters` in authz page
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/docs/reference/access-authn-authz/authorization/ to mention the special group `system:masters`

**Why is this needed**
Kubernetes has special hard coded treatment for `system:masters`, but this detail is poorly documented.

**Comments**
/sig auth security docs

### PR DESCRIPTION
**Pull request by mrgiles**
Adds a paragraph describing the `systems:master` group to the Authorization reference page

Fixes #48546

### CODE REVIEW

**Comment by mrgiles** [comment]
What do you think @sftim?

**Comment by mrgiles** [comment]
Ping PR Wrangler @salaxander for an approve label. Thanks!

**Comment by sftim** [comment]
@mrgiles you can also assign to one of the [nominated](https://github.com/kubernetes/website/pull/48600#issuecomment-2448804905) approvers

At the time of writing, that read:


> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: **Once this PR has been reviewed and has the lgtm label**, please assign [sftim](https://github.com/sftim) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubernetes%2Fwebsite).
> Needs approval from an approver in each of these files:
> 
>     * **[content/en/docs/OWNERS](https://github.com/kubernetes/website/blob/main/content/en/docs/OWNERS)**
> 
> 
> Approvers can indicate their approval by writing `/approve` in a comment Approvers can cancel approval by writing `/approve cancel` in a comment

**Comment by sftim** [comment]
/sig auth security
for visibility

/approve

**Pull request merged**
