### PR TITLE
fix kubectl proxy output

### PR DESCRIPTION
**Pull request by xieyanker**

### CODE REVIEW

**Comment by sftim** [comment]
Hi @xieyanker 
This can be reviewed, _but_ because it touches several localizations it needs multiple approvals.

(as per https://kubernetes.io/docs/contribute/intermediate/#working-with-localized-content)

**Comment by xieyanker** [comment]
@sftim Thanks for your reply, I open 3 new PRs, once them are accepted, I will close this.

**Comment by xichengliudui** [comment]
please close this pr as you have opened a new one.

**Pull request closed without merging**
