### PR TITLE
Fix broken link of Install Docker Engine - Enterprise on Windows Servers

### LINKED ISSUE #29764: Adding Windows nodes
The link for installing Docker Engine on Windows server is broken. It should be https://docker-docs.netlify.app/install/windows/docker-ee/

### LINKED ISSUE #30101: Adding Windows nodes - Link Broken for Docker EE installation
The following link seems to be broken for docker ee installation on [Adding Windows nodes page] (https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/#install-wins-kubelet-and-kubeadm)

https://hub.docker.com/editions/enterprise/docker-ee-server-windows

You might want to update the link to this

https://docker-docs.netlify.app/install/windows/docker-ee/

### PR DESCRIPTION
**Pull request by sandipanpanda**
This PR fixes #30101 and fixes #29764

### CODE REVIEW

**Comment by marosset** [comment]
> @brasmith-ms Can you take a look at this?
> 
> I thought that the DockerMsftProvider is not the recommended way to installed Docker EE for Windows. Are there plans to update the docs in this PR? Should the docs point directly to Mirantis hosted installation instructions?
> 
> /hold

Or maybe we should link here https://docker-docs.netlify.app/install/windows/docker-ee/ ?

**Comment by sftim** [comment]
https://docker-docs.netlify.app/install/windows/docker-ee/ looks like the wrong link / unstable (I'd expect to see Docker using their own domain name in a durable hyperlink).

**Comment by sftim** [comment]
Microsoft folks: if https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker is out of date, I'm personally fine with holding off a few weeks until that page is fixed and then linking there.

We usually don't link to vendor docs, but OS docs are a good exception: you won't get very far deploying a Kubernetes cluster without involving a operating system.

**Comment by sftim** [comment]
Oh, also: those Windows docs are editable; see https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/set-up-environment.md

**Comment by sftim** [comment]
> Hi @sftim, sorry I could not understand this clearly. Did you mean that I should only fix the broken links in en and keep the broken links in ko and zh as it is, or did you mean I should open separate PRs for fixing the ko and zh docs?

Leave this PR just making changes to English (keep the broken links in ko and zh as it is). Once it merges, localization teams for other localizations (Korean and Chinese) can decide how they want to address that drift. Each localization team picks its own way to manage their backlog and to avoid / accept / whatever the merge issues that might come from accepting hot-fix PRs.

You would be very welcome to open two new PRs, one for Chinese and one for Korean. If you do, bear in mind that the target might change (for example, to https://docs.microsoft.com/ko-kr/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker)

**Comment by marosset** [comment]
> Microsoft folks: if https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker is out of date, I'm personally fine with holding off a few weeks until that page is fixed and then linking there.
> 
> We usually don't link to vendor docs, but OS docs are a good exception: you won't get very far deploying a Kubernetes cluster without involving a operating system.

@brasmith-ms  Can you take ownership of getting the docs here updated?

**Comment by brasmith-ms** [comment]
> > Microsoft folks: if https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker is out of date, I'm personally fine with holding off a few weeks until that page is fixed and then linking there.
> > We usually don't link to vendor docs, but OS docs are a good exception: you won't get very far deploying a Kubernetes cluster without involving a operating system.
> 
> @brasmith-ms Can you take ownership of getting the docs here updated?

@marosset Yup! I will get those docs updated and fix the broken links here afterwards.

**Comment by jihoon-seo** [comment]
This PR seems to be okay to
/unhold

**Pull request merged**
