### PR TITLE
kubectl-overview

### PR DESCRIPTION
**Pull request by chenhonggc**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/5982)

### CODE REVIEW

**Comment by chenhonggc** [comment]
$ kubectl get pod pod1 $ kubectl get pods pod1 $ kubectl get po pod1

TO:

      $ kubectl get pod pod1
      $ kubectl get pods pod1
      $ kubectl get po pod1

**Comment by xiangpengzhao** [comment]
Thanks for the fix! This LGTM.
Since you are touching this doc, could you please try to fix the bad format in the table of section `Operations` ?

**Comment by xiangpengzhao** [comment]
e.g., the below line should be a row of the table but it doesn't. I think the reason is that the `|` in the command is parsed to be a md symbol.

`annotate`    | `kubectl annotate (-f FILENAME | TYPE NAME | TYPE/NAME) KEY_1=VAL_1 ... KEY_N=VAL_N [--overwrite] [--all] [--resource-version=version] [flags]` | Add or update the annotations of one or more resources.

**Comment by chenhonggc** [comment]
@xiangpengzhao Thanks, But the line is a row of the table.

[kubectl-overview](https://kubernetes.io/docs/user-guide/kubectl-overview/)

**Comment by xiangpengzhao** [comment]
I just found it a bad format by clicking `view` button in the file of this PR. Seems like it's ok in the final page.  Interesting...

**Pull request merged**
