### PR TITLE
[ko] modify error in certificates.md

### PR DESCRIPTION
**Pull request by ariesliuwei**
modify error in certificates.md

### CODE REVIEW

**Comment by ClaudiaJKang** [comment]
@ariesliuwei Thank you!

/assign
/lgtm

**Comment by ClaudiaJKang** [comment]
@ariesliuwei Could you change the base branch `main` to `dev-1.21-ko.5` branch? 

Korean Team's current working branch is `dev-1.21-ko.5`!

**Comment by sftim** [comment]
(feel free to hold this because of the base branch issue)

**Comment by seokho-son** [comment]
@ariesliuwei whereas Korean localization team has development branch, we accept PRs into the main branch for minor bug fix :) 
Thank you for the contribution.

/approve

**Pull request merged**
