### PR TITLE
doc:containerd alpha in 1.17

### PR DESCRIPTION
**Pull request by PatrickLang**
Windows is adding alpha support for CRI-ContainerD in 1.17. https://github.com/kubernetes/enhancements/issues/1001

This is a placeholder for the setup instructions and updates to the list of known issues.

/hold work-in-progress
/milestone v1.17

### CODE REVIEW

**Comment by pgburt** [comment]
Hi @PatrickLang. I'm a Docs shadow for the 1.17 release. I'm writing with a reminder that the deadline for PRs to be "Ready for Review" is by Nov 15, 2019 (this Friday!).

**Comment by PatrickLang** [comment]
/milestone v1.18
This didn't make it into 1.17

**Comment by sftim** [comment]
@PatrickLang did you want to target _dev-1.18_ instead?

**Comment by sftim** [comment]
I'm going to close this, as v1.17 is already released.
@PatrickLang it would be great to see this feature in a future Kubernetes release, and I hope that you can use this documentation branch for that if it's useful.

/close

**Pull request closed without merging**
