### PR TITLE
Update echoserver image in "Hello Minikube" tutorial for multiarch

### PR DESCRIPTION
**Pull request by mtardy**
Should fixes https://github.com/kubernetes/website/issues/36732 and https://github.com/kubernetes/website/pull/37361.

Preview available [here](https://deploy-preview-37383--kubernetes-io-main-staging.netlify.app/docs/tutorials/hello-minikube/#create-a-deployment).

I took the liberty to open a new PR because the author of [the one we worked on](https://github.com/kubernetes/website/pull/36731) was not answering anymore.

The previous version of the image did not support arm64. This one supports amd64, arm, arm64, ppc64le, s390x on Linux, and amd64 on multiple Windows versions.

More information and context in this PR https://github.com/kubernetes/website/pull/36731 and the discussion that lead to this solution [available here](https://kubernetes.slack.com/archives/CCK68P2Q2/p1666183862561759).

It works on amd64, to test the image on different architectures you can do:
```bash
docker run -p 8080:8080 registry.k8s.io/e2e-test-images/agnhost:2.39 netexec --http-port=8080
curl localhost:8080
# do not do the following if you have anything else running on your computer with docker
# because it will stop and remove every container
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
```

~However, the curl step failed with a LUA panic when I curled on the ARM Linux of a colleague. I got "empty reply from the server" on the curl side and `PANIC: unprotected error in call to Lua API (bad light userdata pointer)` in the server logs. So maybe sig testing people can help us on that topic.
I'll just hold in the meantime because it requires more testing on an architecture I don't personally have.~

EDIT: changed to `agnhost` image, now it works.

/hold

Unrelated: note that the `minikube service hello-node` in the browser step of the tutorial does not work on my intel mac but if I `minikube ssh` and `curl` directly the service, it works.

/cc @sftim
/sig testing

### CODE REVIEW

**Comment by sftim** [comment]
LGTM in spirit

**Comment by mtardy** [comment]
I tried with the new image that is currently maintained and it worked on my colleague's arm64 and my amd64 computer.

```bash
# from
kubectl create deployment hello-node --image=registry.k8s.io/e2e-test-images/echoserver:2.5
# to
kubectl create deployment hello-node --image=registry.k8s.io/e2e-test-images/agnhost:2.39 -- /agnhost netexec --http-port=8080
```

It's a bit more complex but this is a maintained image by sig-testing that is multi-arch and works!

On the `/` endpoint by default it returns the hour under the form of:
```console
NOW: 2022-10-19 16:27:33.905885166 +0000 UTC m=+24.356195679
```

And there is an ['/echo'](https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/netexec/netexec.go#L84) endpoint but I don't think it will be necessary.

**Comment by natalisucks** [comment]
@kubernetes/sig-testing-pr-reviews Howdy folks, looking for a tech review on this PR, thanks!

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
Thank you and thanks @mtardy. This image is much more maintainable for SIG Testing.

**Pull request merged**
