### PR TITLE
Update cheatsheet.md

### PR DESCRIPTION
**Pull request by oteichmann**
Add syntax how to remove labels

### CODE REVIEW

**Comment by geoffcline** [comment]
I tested this on my cluster and it works. It is a reasonable addition to the guide.

/lgtm

**Comment by reylejano** [comment]
I retried the preview on Netlify and the build finished successfully
Preview of updated page:
https://deploy-preview-37710--kubernetes-io-main-staging.netlify.app/docs/reference/kubectl/cheatsheet/

**Review by ydFu — APPROVED** [review]
/lgtm

**Comment by divya-mohan0209** [comment]
The check is passing on Netlify - https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6371a958a988d64af27c7e8c

**Comment by Kartik494** [comment]
@oteichmann could you push an empty commit to run the jobs again?

**Pull request merged**
