### PR TITLE
move cloud-controller-manager kube-apiserver kube-controller-manager kube-proxy kube-scheduler kubelet  to docs/reference/generated directory

### PR DESCRIPTION
**Pull request by wackxu**
move cloud-controller-manager kube-apiserver kube-controller-manager kube-proxy kube-scheduler kubelet  to docs/reference/generated directory

/assign @steveperry-53

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6323)

### CODE REVIEW

**Comment by wackxu** [comment]
@steveperry-53 This PR is moving the file that you point to me. PTAL

**Comment by wackxu** [comment]
@steveperry-53 Fix conflict, PTAL

**Comment by steveperry-53** [comment]
@wackxu Thanks, but now there's a conflict again, because I merged one of your other PRs.

**Comment by wackxu** [comment]
@steveperry-53 Done, PTAL

**Pull request merged**
