### PR TITLE
Merge master into dev-1.20 to keep in sync

### PR DESCRIPTION
**Pull request by annajung**
Merge `master` into `dev-1.20` to keep in sync
Final sync before the release

### CODE REVIEW

**Comment by annajung** [comment]
@jimangel @irvifa @sftim @kbhawkey 
So, I made a commit to this branch to change the `config.toml` file to reflect the latest patch version for the past releases and this accidentally got merged. 

I wanted to surface it since it didn't get a proper review from sig docs. 

There were no other build errors than the (issue blocking) and I think the master sync looks good, so I don't think there's no action needs to be taken to revert. 

However, this should have not happened, so just wanted to raise awareness and thoughts on if anything needs to be done.

**Comment by kbhawkey** [comment]
@annajung , Why did this PR automatically merge?

**Comment by annajung** [comment]
I'm not sure exactly what happened. I opened up the PR then I realized that `config.toml` for `dev-1.20` branch should also be updated. So, I made the changes locally and pushed by typing `git push`.

```
origin	https://github.com/annajung/website.git (fetch)
origin	https://github.com/annajung/website.git (push)
upstream	https://github.com/kubernetes/website.git (fetch)
upstream	https://github.com/kubernetes/website.git (push)
```

`origin` is set to point to my personal fork of the website, `upstream` set to `k/website`.
It must have somehow pushed `upstream` rather than `origin`, but I don't know how that could have been because everything is set to push to `origin`.

For example, I used the same command to sync the `master` into my `dev-1.20` branch and was able to successfully NOT pushed to upstream and make this PR.

**Comment by annajung** [comment]
Once I pushed (`git push`), this PR automatically merged. -- that's why I think I accidentally pushed upstream without knowing.

**Comment by jimangel** [comment]
I haven't had the time to full dive into this, but curious if you used `--tracking` when checking out the branch? I wonder if that could have caused something. One habit I've been trying to get into is:

```
git clone git@github.com:jimangel/website.git
cd /website
git remote add upstream https://github.com/kubernetes/website.git
git remote set-url --push upstream no_push
```

In any event, I've accidentally pushed (and erased) dev branches. Things like this happen... I'm curious more about how it happened though so we can avoid next release.

Lastly, this was done after you were given the elevated maintainer permissions (open PR merged)?

**Comment by annajung** [comment]
```
git remote set-url --push upstream no_push
```

this is such a helpful command! I'm going to add this into the doc role handbook! I think highlighting this command can help prevent anyone from pushing upstream in the future. 

> but curious if you used --tracking when checking out the branch?

I didn't use the `--tracking` command as far as I know, I normally just change branches by typing `git checkout dev-1.20`.

> Lastly, this was done after you were given the elevated maintainer permissions (open PR merged)?

Yes, this was done after I was given the write access.

**Comment by annajung** [comment]
I made an update to the docs role handbook to add both 
- missing step to update the `config.toml` for the future release branch
- explicit call out to set no push to upstream 

https://github.com/kubernetes/sig-release/pull/1376

**Comment by tengqm** [comment]
> git remote set-url --push upstream no_push

I'm aware of this command but sometimes I just forget to run it. Running it now on all my git work, 😃

**Pull request merged**
