### PR TITLE
Promote EphemeralContainers to beta in website

### PR DESCRIPTION
**Pull request by verb**
KEP: http://kep.k8s.io/277

Blocking PRs
* kubernetes/kubernetes#103372
* kubernetes/kubernetes#105293
* kubernetes/kubernetes#105405

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Early review: make sure to also update https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/ in this PR.

**Comment by verb** [comment]
ummm.....

/retest

?

**Comment by verb** [comment]
Ok, well maybe the netlify jobs will fix themselves.

In the meantime, these files still have reference to alpha:
* http://kubernetes.io/docs/reference/command-line-tools-reference
* http://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1

@jlbutler Any idea how these pages are generated? It would save me some digging.

**Comment by sftim** [comment]
I manually triggered a retry. Your other options are:
- force-push a different but equivalent commit
- teach Prow how to trigger a rebuild on `/retest` then use that (trickier)

**Comment by jlbutler** [comment]
/lgtm

It looks resolved to me, is anything else needed for this?

**Pull request merged**
