### PR TITLE
Adjust width for Learn Kubernetes button

### PR DESCRIPTION
**Pull request by kbhawkey**
Testing out new sass script.

### CODE REVIEW

**Comment by zparnold** [comment]
@kbhawkey Could you please regenerate your generated css?

**Comment by zacharysarah** [comment]
@kbhawkey 👋 Please feel free to reopen this PR when you're ready to resolve the merge conflict.

**Comment by kbhawkey** [comment]
Hi @zacharysarah. This PR is no longer needed to fix issue #10309. There were several PRs trying to
fix the try-kubernetes button.

**Pull request closed without merging**
