### PR TITLE
[ru] Add RU localization - networking.md

### PR DESCRIPTION
**Pull request by kirkonru**
The following file was translated into Russian:

- [content/en/docs/concepts/cluster-administration/networking.md](https://github.com/flant/kubernetes-website/blob/main/content/en/docs/concepts/cluster-administration/networking.md)

### CODE REVIEW

**Review by shurup — CHANGES_REQUESTED** [review]
We need to make this page up to date since a prominent part of it moved to another document already.

**Comment by shurup** [comment]
@kirkonru very little is left here to merge it as well.

/remove-lifecycle stale

**Comment by divya-mohan0209** [comment]
@shurup : There has been no update on the PR since last September. Keeping in mind PR hygiene & project health, I shall be closing this PR.  The submitter, @kirkonru , can choose to reopen it if they have the bandwidth to accommodate your feedback by issuing the /reopen command. 
/close

**Comment by kirkonru** [comment]
@shurup this PR is ready for merging.  :pray: :sunglasses:

**Comment by shurup** [comment]
Perfect! 
/lgtm
/approve

**Pull request merged**
