### PR TITLE
Remove useless tips

### PR DESCRIPTION
**Pull request by yeqiugt**

### CODE REVIEW

**Comment by yeqiugt** [comment]
I have just signed the CLA, would this check pass automaticly?

**Review by stmcginnis — COMMENTED** [review]
/easycla
/lgtm

Looks like that title anchor was removed (or never existed on this page) so looks good.

**Comment by stmcginnis** [comment]
The commit has:

> Signed-off-by: liu lijin <253954033@qq.com>

So they would need to sign the CLA.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by yeqiugt** [comment]
CLA check always failed, I will try a new pr.

**Pull request closed without merging**
