### PR TITLE
Bump all cniVersion mentions to at least 0.4.0

### LINKED ISSUE #35310: Minimal supported CNI version is 0.4.0, while the documentation provides examples with `"cniVersion": "0.3.0"`
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/ says the minimal supported CNI interface version is 0.4.0 and specification-version 1.0.0 is recommended.  Neverthesless the same webpage contains two examples with `"cniVersion": "0.3.0"`.

### PR DESCRIPTION
**Pull request by bishal7679**
## Fixes #35310 

All cniVersion mentioned in the issue is changed into latest "0.4.0"
It is required that minimal "0.4.0" cniVersion latest but in two json file there was cniVersion "0.3.0"

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Comment by divya-mohan0209** [comment]
@kubernetes/sig-network-pr-reviews : Could you please provide a technical signoff on this?

**Comment by sftim** [comment]
/retitle Bump all cniVersion mentions to at least 0.4.0

**Comment by sftim** [comment]
@bishal7679 you will make it easier for people to review if you explain, in the PR description itself, why the change is appropriate.

The current text:

> Fixes #35310
> 
> All CniVersion is changed into latest "0.4.0"

explains _what_ you are changing, but a reviewer then has to go to read a different thing to work out _why_. Also, there is a capitalization issue with `cniVersion` in the description. A reviewer might decide to hold off until they have a bit more time to review this, based on that kind of context.

**Comment by bishal7679** [comment]
@sftim Thank you so much
I will keep it in mind for the next time

**Comment by dilyanpalauzov** [comment]
Will `1.0.0` also work and if yes, what is the rationale to use `0.4.0` instead?

1.0.0 is recommended.  If it works, it shall be used.

**Comment by sftim** [comment]
> 1.0.0 is recommended. If it works, it shall be used.

I like this suggestion.

**Comment by dilyanpalauzov** [comment]
For me it is unclear, why the examples show now `0.4.0`, while at the same time `1.0.0` is recommended version.  Doesn’t `1.0.0` work?

**Pull request merged**
