### PR TITLE
Fix guestbooks tutorial

### PR DESCRIPTION
**Pull request by tengqm**
This PR fixes the guestbooks tutorial. Issue is related to #8689 which attempted to fix the incorrectly rendered commands.

### CODE REVIEW

**Comment by Bradamant3** [comment]
@tengqm 
My error. This should not have been merged. Ordered lists do not behave as expected in Hugo/BlackFriday markdown when code blocks or other intervening elements are included in a listitem. Specifically, list numbering fails to continue. See the discussions and examples in #8663 and #8699

**Comment by Bradamant3** [comment]
Argh, sorry I should not have used GH UI which did not behave as expected. lmk how best to proceed, thank you!

**Comment by zacharysarah** [comment]
@tengqm 👋 Any thoughts about how to proceed here and in #8689? 

cc @mistyhacks

**Comment by tengqm** [comment]
@zacharysarah The fix needs a rework, will jump onto it when not so busy.

**Pull request merged**
