### PR TITLE
Update generated reference API docs

### PR DESCRIPTION
**Pull request by annajung**
- Update generated reference API docs with tag 1.20.0-rc.0
- Remove cloud controller manager reference doc

/hold for feedback from @kbhawkey @tengqm @sftim

### CODE REVIEW

**Comment by tengqm** [comment]
Glad to know that things went well.
This update is supposed to happen after the 1.20 release is out.
Given what we can produced on v1.20.0-rc.0, I'm confident we will have another smooth release this time.

**Comment by annajung** [comment]
I thought it was done twice, once before the release and once after the release?

If not, should I close out this PR and create a new one on the release day?

**Comment by tengqm** [comment]
> should I close out this PR and create a new one on the release day?

My understanding is that a new one needs to be created shortly *after* the release day. We will have a exact tag to reference after the release is cut.
I don't have a strong opinion whether we need to create one *before* the release. Maybe we should?

**Comment by annajung** [comment]
My knowledge just comes from what was written in the [handbook](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#generate-the-reference-documentation) and this might be outdated. 

Maybe @savitharaghunathan (1.19 release lead) can chime in?

**Comment by kbhawkey** [comment]
With the last release, the reference docs were generated just before the release day so that there is a complete
set of content. This seemed to work out well.
I specifically updated the generation script to build the reference pages from a release candidate version.
If there are any last minute changes, another build can be created after the release.

**Comment by kbhawkey** [comment]
Page previews:
https://deploy-preview-25386--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.20/#-strong-api-overview-strong-

https://deploy-preview-25386--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubectl/kubectl-commands

https://deploy-preview-25386--kubernetes-io-vnext-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-token/
https://deploy-preview-25386--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/kube-apiserver/
https://deploy-preview-25386--kubernetes-io-vnext-staging.netlify.app/docs/reference/command-line-tools-reference/kube-scheduler/

https://deploy-preview-25386--kubernetes-io-vnext-staging.netlify.app/docs/reference/kubectl/kubectl/

**Comment by kbhawkey** [comment]
@annajung , Check the files you generated to the files generated in,
https://github.com/kubernetes/website/pull/25355/files (31 files)
I think my build generated more kubeadm files?

**Comment by kbhawkey** [comment]
> 
> 
> @annajung , Check the files you generated to the files generated in,
> https://github.com/kubernetes/website/pull/25355/files (31 files)
> I think my build generated more kubeadm files? Was there a prior update to the kubeadm files on the dev-1.20 branch?

@annajung , Looks like @neolit merged updates to the generated `kubeadm` files in this PR https://github.com/kubernetes/website/pull/24410.

**Pull request merged**
