### PR TITLE
[WIP] Increase base font size to 16x

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR increases base font size from 14px to 16px.

### CODE REVIEW

**Comment by zacharysarah** [comment]
The preview doesn't show any change. Thoughts?
@chenopis @mistyhacks 

https://deploy-preview-12368--kubernetes-io-master-staging.netlify.com/docs/home/

**Comment by mistyhacks** [comment]
The font size for those links is being set for `#encyclopedia`. Probably you need to remove the specific 14px rule from there. I figured it out by inspecting one of the links and going to the Computed tab. You can expand the `font-size` rule there and see where it's coming from.

**Comment by zacharysarah** [comment]
@mistyhacks The more I investigate, the more I agree. The work required for a seemingly straightforward font size change is extensive enough to merit its own dedicated investment.

Closing.

**Comment by Sai-Adarsh** [comment]
> The font size for those links is being set for `#encyclopedia`. Probably you need to remove the specific 14px rule from there. I figured it out by inspecting one of the links and going to the Computed tab. You can expand the `font-size` rule there and see where it's coming from.

did that work @zacharysarah ?

**Pull request closed without merging**
