### PR TITLE
fix kubelet flag description

### PR DESCRIPTION
**Pull request by liuxu623**
https://github.com/kubernetes/kubernetes/pull/98869

### CODE REVIEW

**Comment by liuxu623** [comment]
> @liuxu623 Please consider split this PR into two, each dedicated to one language. Preferably, hold the zh PR till the en PR is reviewed and merged.

@tengqm done

**Comment by SergeyKanzhelev** [comment]
are those reference files auto-generated? Since PR is merged to k/k, is there anything special to review?

**Comment by tengqm** [comment]
@SergeyKanzhelev Yes, they are augo-generated.

**Pull request merged**
