### PR TITLE
fix typo in max surge description

### PR DESCRIPTION
**Pull request by sppakal**
fix typo in https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-surge

### CODE REVIEW

**Comment by zacharysarah** [comment]
@sppakal 👋 Please sign the [CLA](https://identity.linuxfoundation.org/projects/cncf) in order to continue.

**Comment by sppakal** [comment]
I signed it

**Comment by zacharysarah** [comment]
@sppakal Please make sure the email you used to sign the CLA matches the email associated with your GitHub ID.

**Comment by kbhawkey** [comment]
@sppakal 👋 . I plan to close this PR.
Feel free to reopen this PR when you have resolved your account information and CLA.
/close

**Pull request closed without merging**
