### PR TITLE
update adding windows node page

### LINKED ISSUE #30510: Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/
The page links to some documentation on installing Docker Engine on Windows. It links to this page, which gives a 404: https://hub.docker.com/editions/enterprise/docker-ee-server-windows

This guide seems to utilize a feature released via MicrosoftDockerProvider, which is discontinued as of Sept 2021 per [this documentation ](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker) published by Microsoft. So I suspect this guide needs to be reassessed to see if there's a different way to get Docker Engine on Windows without using a paid license product such as Docker Desktop.

### PR DESCRIPTION
**Pull request by RA489**
update adding windows node page
fixes #30510

### CODE REVIEW

**Comment by RA489** [comment]
Looking for Lgtm!

**Comment by perithompson** [comment]
Hi @RA489 looks like you need a rebase but the new link lgtm

**Comment by marosset** [comment]
/close

This was addressed with https://github.com/kubernetes/website/pull/30105

**Pull request closed without merging**
