### PR TITLE
ko: fix corrupt date in glossary/static-pod

### PR DESCRIPTION
**Pull request by yoonian**

### CODE REVIEW

**Comment by gochist** [comment]
@yoonian Please separate this PR for each language. If this PR is merged, docs-en-owner's approval will be required again when the branch `dev-1.15-ko.4` is merged to the `master`. And the current [contribution guide](https://kubernetes.io/docs/contribute/start/) is limiting pull requests to one language.

**Comment by yoonian** [comment]
/remove-language/en

**Pull request merged**
