### PR TITLE
Fix link `scale subresource`

### PR DESCRIPTION
**Pull request by dbenque**
add leading / in link

### CODE REVIEW

**Comment by sftim** [comment]
Oops. @dbenque you'll need to sign a Contributor License Agreement before this is reviewable / ready for approval.

**Comment by dbenque** [comment]
> Oops. @dbenque you'll need to sign a Contributor License Agreement before this is reviewable / ready for approval.

Done.

**Comment by gochist** [comment]
@sftim I'm an approver limited to the `content/ko`, `i18n/*` and `README-ko.md`.
/unassign
/assign @steveperry-53

**Comment by sftim** [comment]
Ah, sorry. Prow maybe doesn't know all the details of who can approve what.

**Pull request merged**
