### PR TITLE
[en] Fix Markdown formats

### PR DESCRIPTION
**Pull request by Sea-n**
### Main Changes
- Change `` `hello,` world `` to `` `hello`, world ``
- Use correct `codenew` statement

### Related PR
- #32907
- #32908
- Pending: `id`, `fr`, `es`, `pt-br`, `de`

### CODE REVIEW

**Comment by sftim** [comment]
@Sea-n Please [limit pull requests to a single localization](https://kubernetes.io/docs/contribute/localization/#suggest-changes), since pull requests that change content in multiple localizations are difficult to review.

I suggest that you start with just the English changes that you wanted to make, and then open a separate PR for each localization that you want to update. We want separate PRs partly to allow sharing out the work, but mostly because I think we don't have any reviewers who speak all 13 languages that we've localized the docs into.

**Comment by sftim** [comment]
/hold
OK to /unhold once this PR only touches one localization.

**Comment by Sea-n** [comment]
Thanks very much for point out my mistake in the original PR! I have break it down to 8 separated branch for different language.

Here is PR for `en`, `zh`, `it`.
For `id`, `fr`, `es`, `en`, `pt-br`, `de`, I will open PR after your think it's okay.

CC @sftim

**Comment by jihoon-seo** [comment]
/unhold
/remove-language de es fr id it zh

**Comment by tengqm** [comment]
This is clean.
/kind cleanup
/lgtm
/approve

**Pull request merged**
