### PR TITLE
ru/examples/minikube/Dockerfile: modify CMD to use exec form

### PR DESCRIPTION
**Pull request by php-coder**
Replicate https://github.com/kubernetes/website/pull/18618

/language ru

### CODE REVIEW

**Comment by php-coder** [comment]
PTAL @kubernetes/sig-docs-ru-reviews

**Comment by sftim** [comment]
/hold
because this depends on upstream localization change
OK to add /lgtm and /approve; once #18618 is merged, also OK to /unhold

**Comment by sftim** [comment]
It merged (and I forgot)
/unhold

**Pull request merged**
