### PR TITLE
Apply content_template and follow the style guide

### PR DESCRIPTION
**Pull request by makocchi-git**

### CODE REVIEW

**Comment by makocchi-git** [comment]
[preview is here](https://deploy-preview-12759--kubernetes-io-master-staging.netlify.com/docs/setup/multiple-zones/)
[original](https://kubernetes.io/docs/setup/multiple-zones/)

**Comment by DanyC97** [comment]
cheers @makocchi-git , lgtm (although i know my review doesn't count at this stage )

**Comment by makocchi-git** [comment]
ping @@zhangxiaoyu-zidif

**Pull request merged**
