### PR TITLE
Tweak network policies

### PR DESCRIPTION
**Pull request by tengqm**
closes: #38596 

The problem reported by the issue can be easily detected if the manifest is extracted to a standalone YAML file, which then can be validated using the example test cases.

This PR contains two commits. The first commit improves the network-policies.md file by splitting out an example into an out-of-band example file (bugs in it fixed and validated using `go test k8s.io/website/content/en/examples`). The second commit reformats the concept pages for long lines that are supposed to be wrapped when appropriate. No substantial changes are introduced in the second commit.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Thanks

LGTM
/approve

**Comment by sftim** [comment]
Does this fix _both_ of the issues that https://github.com/kubernetes/website/issues/38596 reports?

(my guess was that of the two things reported, the first was an invalid report and the second one is an accurate observation)

**Comment by tengqm** [comment]
> Does this fix _both_ of the issues that #38596 reports?
> 
> (my guess was that of the two things reported, the first was an invalid report and the second one is an accurate observation)

Yes. I believe so. I scanned the whole file for other occurrences of `policyTypes`.

**Pull request merged**
