### PR TITLE
Note MicroK8s

### PR DESCRIPTION
**Pull request by jglick**
Ideally this page would list all major laptop-oriented Kubernetes implementations, but at least mentioning the existence of MicroK8s seems like a good start.

### CODE REVIEW

**Comment by jglick** [comment]
Hoping https://github.com/cncf/gitdm/pull/83 will fix the CLA issue. Maybe need to refresh the PR to redo the check?

**Comment by cody-clark** [comment]
Hi, @jglick, thanks for taking steps to make sure the CLA is signed. Have you tried the [contact email here](https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting)?

**Comment by jglick** [comment]
> Have you tried the [contact email here](https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting)?

Thanks for the tip, just sent mail.

**Comment by jglick** [comment]
Still working on finding out who in my company is actually authorized to add me to the corporate CLA.

**Comment by zparnold** [comment]
Hey there! @jglick, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jglick** [comment]
I am still trying to find out who in my company owns the CCLA.

**Comment by jglick** [comment]
I signed it

**Comment by Rajakavitha1** [comment]
I checked the update on: https://deploy-preview-11985--kubernetes-io-master-staging.netlify.com/docs/setup/minikube/

The Additional Links sections contains more information about the goals and non-goals, build/test, add a new dependency, and add a new addon for Minikube. The alternatives for local cluster deployments are listed at: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cluster-lifecycle/local-cluster-ux.md

**Pull request merged**
