### PR TITLE
[ja] Update Chained selectors shell command to follow the English version

### PR DESCRIPTION
**Pull request by zamataku**
Let me propose change to follow the English version
https://github.com/kubernetes/website/blame/79c1ab1fd2836726379c3debef18e955faeedbb2/content/en/docs/concepts/overview/working-with-objects/field-selectors.md#L46

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@zamataku 
Pls sign the CLA in order for the PR to be reviewed.

**Comment by zamataku** [comment]
@Arhell 
Thank you for your kindly support.
I signed the CLA. When you have time, please take a look at the PR.

**Comment by inductor** [comment]
Huh, this has been outdated in the first place. Thank you for noticing!

/approve

**Pull request merged**
