### PR TITLE
Update authorization.md

### PR DESCRIPTION
**Pull request by qqbuby**

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@qqbuby Thanks for the update. Just a minor suggestion: Please remove the word below at the end of the sentence.

**Comment by qqbuby** [comment]
@Rajakavitha1 I have deleted the word 'below'.

**Comment by Rajakavitha1** [comment]
I checked the out put on :https://deploy-preview-12471--kubernetes-io-master-staging.netlify.com/docs/reference/access-authn-authz/authorization/
/lgtm
/approve

**Pull request merged**
