### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by adevjoe**
群集 => 集群

### CODE REVIEW

**Comment by adevjoe** [comment]
already ClA

**Comment by adevjoe** [comment]
already ClA

**Comment by adevjoe** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please email the CNCF helpdesk: [helpdesk@rt.linuxfoundation.org](mailto:helpdesk@rt.linuxfoundation.org)

already CLA

**Comment by xichengliudui** [comment]
@adevjoe  Thank you for your initial contribution.
please sign the cla agreement, if you have signed, you can try typing `I signed`.

**Comment by xichengliudui** [comment]
Now that the pr is built, all you need to do is sign the cla agreement.

**Comment by adevjoe** [comment]
I signed

**Comment by xichengliudui** [comment]
obviously you need to sign the cla `https://identity.linuxfoundation.org/projects/cncf`.

**Pull request merged**
