### PR TITLE
[WIP] start serverside-apply documentation

### PR DESCRIPTION
**Pull request by kwiesmueller**
Add documentation for the serverside-apply alpha feature

/milestone 1.14

### CODE REVIEW

**Comment by kbhawkey** [comment]
@kwiesmueller, you indeed to add one commit, right?

**Comment by kwiesmueller** [comment]
Yeah, I added one to at least have the PR open.
I guess when switching to the dev-1.14 branch i failed to rebase first. Let me check.

**Comment by kwiesmueller** [comment]
Okay that made it even worse.
Sorry, it's my first PR to the website repo and I wasn't which branch to select.
Is dev-1.14 correct for this?

**Comment by kbhawkey** [comment]
> 
> 
> Okay that made it even worse.
> Sorry, it's my first PR to the website repo and I wasn't which branch to select.
> Is dev-1.14 correct for this?

Yes, dev-1.14 is the correct branch, cc @jimangel

**Comment by jimangel** [comment]
@kwiesmueller it looks like you might have combined some docs from other branches. I would recommend fixing them and force pushing back to this branch. Alternately, you can close this PR and open a new one with your changes if it's easier.

Either way, there is a "ready for review" deadline tomorrow (Monday) and it would be great to not have this at risk due to merge conflicts :)

Thanks!

**Comment by kwiesmueller** [comment]
closed in favor of https://github.com/kubernetes/website/pull/13077

**Pull request closed without merging**
