### PR TITLE
Redirect deadlinks

### PR DESCRIPTION
**Pull request by irvifa**
Redirect deadlinks for:

- https://ai.google/research/pubs/pub43438
- https://docs.docker.com/engine/admin/volumes/

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hello @irvifa ,
Thanks for fixing the links. It is good practice to create a pull request per localization.
/cc @kubernetes/sig-docs-fr-reviews @kubernetes/sig-docs-ko-reviews @kubernetes/sig-docs-zh-reviews @kubernetes/sig-docs-vi-reviews @kubernetes/sig-docs-uk-reviews

**Comment by seokho-son** [comment]
/lgtm
for the changes to /ko
(Contents in Korean are based on English contents. Considering this PR got lgtm from sig-docs-en-owners, Ko contents in this PR can be approved from ko-owners. However, we would postpone approval until an sig-docs-en-owner confirms the changes.)

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-20988--kubernetes-io-master-staging.netlify.app/docs/concepts/storage/volumes/

@irvifa , Would you squash your commits into a single commit (rebase and squash).
https://kubernetes.io/docs/contribute/new-content/new-content/#squashing-commits
Thanks!

**Comment by girikuncoro** [comment]
looks great for the changes to id

/lgtm

**Comment by Potapy4** [comment]
LGTM for RU, UK

/lgtm

**Comment by huynguyennovem** [comment]
Look good for VI. But I see this PR still has conflicts. Please resolve it!

**Comment by tengqm** [comment]
@irvifa pls resolve the conflicts then we can get this merged.

**Comment by irvifa** [comment]
It's rebased and squashed

**Comment by Arhell** [comment]
/lgtm
for uk

**Comment by tengqm** [comment]
/lgtm
/approve

This is really a reapproval.

**Pull request merged**
