### PR TITLE
Update kubectl reference for v1.25

### PR DESCRIPTION
**Pull request by tengqm**

### CODE REVIEW

**Comment by reylejano** [comment]
Preview looks good
https://deploy-preview-36946--kubernetes-io-main-staging.netlify.app/docs/reference/generated/kubectl/kubectl-commands

/approve

**Comment by Sea-n** [comment]
Is that intended to include the `static/docs/reference/generated/kubectl/node_modules/font-awesome/fonts/` directory?

I think it's a mistake. If not, maybe it would be better to describe it briefly.

**Comment by sftim** [comment]
The comment in https://github.com/kubernetes/website/pull/36946#issuecomment-1253970326 looks like good feedback.

LGTM otherwise.

**Comment by tengqm** [comment]
It is a long history. Let me try removing font-awesome together.

**Comment by tengqm** [comment]
Looks like the missing css doesn't hurt much. We can postpone the improvement to the conversion tool to future.

**Comment by windsonsea** [comment]
Thanks.

/lgtm

**Pull request merged**
