### PR TITLE
Update link controlling-access

### PR DESCRIPTION
**Pull request by gaoguangze111**
Update link in Chinese page controlling-access.md, which direct to English version page. Page updated: https://kubernetes.io/zh/docs/reference/access-authn-authz/controlling-access/

### CODE REVIEW

**Comment by howieyuen** [comment]
I don't have approve permission.
/cc @tengqm

**Comment by tengqm** [comment]
```
$ ./scripts/linkchecker.py -l zh -f /docs/reference/access-authn-authz/controlling-access.md
Language: zh
File: content/zh/docs/reference/access-authn-authz/controlling-access.md
    /docs/user-guide/accessing-the-cluster: Link using redirect records, should use /docs/tasks/access-application-cluster/access-cluster/ instead
    /docs/tasks/configure-pod-container/configure-service-account/: Link not using localized page
    /docs/admin/authentication/: Link using redirect records, should use /docs/reference/access-authn-authz/authentication/ instead
    /docs/admin/authorization: Link using redirect records, should use /docs/reference/access-authn-authz/authorization/ instead
    /docs/admin/admission-controllers/: Link using redirect records, should use /docs/reference/access-authn-authz/admission-controllers/ instead
```

**Comment by gaoguangze111** [comment]
Updated more links

**Review by markthink — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
