### PR TITLE
Update hello-minikube.md

### PR DESCRIPTION
**Pull request by dahuins**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by seokho-son** [comment]
@dahuins Thank you for your contribution !!
In order to merge this PR, you need to sign a Contributor License Agreement (CLA).
Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

**Comment by tengqm** [comment]
@dahuins Please try follow instructions [here](https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement) to debug CLA status if you have signed it.

**Comment by xiangpengzhao** [comment]
ping @dahuins :)

**Comment by jimangel** [comment]
Hey there! @dahuins, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tfogo** [comment]
Hi @dahuins, I'm going to close this since the CLA wasn't signed. Please feel free to re-open this PR in the future if you're able to sign the CLA.

**Pull request closed without merging**
