### PR TITLE
[ID] remove task template to sync with EN

### PR DESCRIPTION
**Pull request by ariscahyadi**
This PR address issue in #26955

/cc @kubernetes/sig-docs-id-reviews

### CODE REVIEW

**Comment by ariscahyadi** [comment]
But we need to create another task or PR for this:
- adding `content/en/docs/contribute/style/write-new-topic.md`
- modifying `content/en/docs/setup/_index.md`

**Comment by habibrosyad** [comment]
> But we need to create another task or PR for this:
> 
> * adding `content/en/docs/contribute/style/write-new-topic.md`
> * modifying `content/en/docs/setup/_index.md`

For additional tasks like this do we want it to be part of M6 or the next milestone? I think the chance to forgot these tasks are quite high if we left them here 🤔

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
