### PR TITLE
added another way to create secret from 'kubectl create'; added some Q…

### PR DESCRIPTION
**Pull request by YAMLcase**
…OL improvements for linux users

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jimangel** [comment]
Hey there! @YAMLcase, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
Hi @YAMLcase .
Would you check that you have signed the CLA?

**Comment by YAMLcase** [comment]
sorry about the wait, I had to recover my linux foundation account.  signed it.

**Comment by natalisucks** [comment]
Heya @YAMLcase! Thanks a bunch for this contribution. I'm of the opinion that these contributions don't belong in the main docs, given we try not the document external tools of any kind. However, I can totally see this working as a blog post specifically for Linux folks. What do you think?

Tagging @celestehorgan and @jimangel for your thoughts/opinions here.

**Comment by celestehorgan** [comment]
@natalisucks Thanks for the tag! I agree with this; I'm not sure it's appropriate for the main documentation. @YAMLcase, here's some documentation on submitting a blog post if you need it https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/

**Comment by kbhawkey** [comment]
👋 @YAMLcase .
I plan to close this pull request.
At any time, you can reopen this PR. 
/close

**Pull request closed without merging**
