### PR TITLE
[zh] Update pod-lifecycle.md

### PR DESCRIPTION
**Pull request by sineycoder**

### CODE REVIEW

**Comment by reylejano** [comment]
/retitle [zh] Update pod-lifecycle.md

@sineycoder please sign the [CLA](https://github.com/kubernetes/community/blob/master/CLA.md)

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/website/pull/32430#issuecomment-1075887530

**Comment by tengqm** [comment]
/close
Closing due to missing CLA for a long time. Feel free to reopen.

**Pull request closed without merging**
