### PR TITLE
[ru] Fixed typo in update-intro.html

### PR DESCRIPTION
**Pull request by askarsyzdykov**
Fixed typo

> Плавающие обновления позволяет -> Плавающие обновления позволяют

### CODE REVIEW

**Comment by ydFu** [comment]
@askarsyzdykov ,thank you for your contribution.

You must sign the CLA for teams of kubernetes/website to do code reiview.

Please click on the red button `NOT COVERED` line in the first comment.

If you don't know how to do it, here is[the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Comment by shurup** [comment]
Hi @askarsyzdykov, and thank you for your fix!

Since we try to follow the [Trivial Edits guidelines](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) as much as we can, I kindly ask you to find more things you can improve in the same document (or any other around you went through recently). Having a PR with several minor fixes makes more sense and we'll be more likely to merge it.

**Comment by shurup** [comment]
I guess no more fixes are expected, so let's merge this correction.

/lgtm
/approve

**Pull request merged**
