### PR TITLE
[id] Fix link to Huawei cloud provider security

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/42353/files
/assign @habibrosyad

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [id] Fix link to Huawei cloud provider security

**Review by sftim — COMMENTED** [review]
/lgtm

The link is to a page in English, but it does request Bahasa Indonesia where available.

**Review by ariscahyadi — COMMENTED** [review]
Hi @Arhell … thank you for your contribution.

**Pull request merged**
