### PR TITLE
Mount propagation update to include docker config

### PR DESCRIPTION
**Pull request by vladimirvivien**
Update the volumes documentation to include mount propagation updates.

### CODE REVIEW

**Comment by Bradamant3** [comment]
/assign

@jsafrane @thockin can you give this one an /lgtm in the next hour or so? Otherwise @vladimirvivien please rebase to point to master and I'll get it in after we merge docs for the release. Too many moving parts today.

**Comment by heckj** [comment]
/assign
/hold

(Dropping the hold while we have the docs freeze in place, implies nothing about the PR, just don’t want to mess up @Bradamant3 efforts)

**Comment by heckj** [comment]
/lgtm
/approve

(@Bradamant3 remove the hold when you’re ready for this - verified the /lgtm from @lpabon who’s involved in the CSI effort, even if not a kubernetes.org member)

**Pull request merged**
