### PR TITLE
add eg for stable level api overview

### PR DESCRIPTION
**Pull request by hagridaaron**
Adding an e.g. to the stable level API overview.

### CODE REVIEW

**Comment by ajaeger** [comment]
@hagridaaron 
Please read https://kubernetes.io/docs/home/contribute/style-guide/#content-best-practices - "Avoid Latin phrases". I suggest to use "example: " instead of e.g.

**Comment by bradtopol** [comment]
@hagridaaron Thank you for your contribution. Pleas sign the CLA so we can accept your PR.
Please also review our style guide:  https://kubernetes.io/docs/home/contribute/style-guide/#patterns-to-avoid
Latin phrases such as e.g. are to be avoided

**Comment by tengqm** [comment]
@hagridaaron Please sign the CLA for this PR to be acceptable.

**Comment by tengqm** [comment]
em.. CLA check still fails

**Comment by chenopis** [comment]
@hagridaaron Make sure that the email address you used to sign the CLA is the same one associated w/ your git commits.

**Comment by bradtopol** [comment]
@hagridaaron Thank you for your contribution. Per @chenopis suggestion please make sure that the email address you used to sign the CLA is the same one associated w/ your git commits.

**Comment by mistyhacks** [comment]
We can't accept your work until you sign the CLA and our testing is able to detect it. It is possible you signed the CLA with a different email address. Please contact the CNCF (see https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting) to get your address on the CLA updated properly. Then please reopen this PR after the CLA is signed. Thanks!

**Pull request closed without merging**
