### PR TITLE
[zh] Update what-is-kubernetes.md

### PR DESCRIPTION
**Pull request by KolinHuang**
"可观察性不仅可以显示操作系统级别的信息和指标，还可以显示应用程序的运行状况和其他指标信号。" -> "可观察性：不仅可以显示操作系统级别的信息和指标，还可以显示应用程序的运行状况和其他指标信号。"

### CODE REVIEW

**Comment by KolinHuang** [comment]
I have signed CLA.

**Comment by RA489** [comment]
> I have signed CLA.

/check-cla

**Comment by sftim** [comment]
/check-cla

If this check doesn't pass, please make sure that the email address representing you as a CLA signer matches the email address that you committed with. See https://github.com/kubernetes/website/pull/29067#issuecomment-884664870 for more details.

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by mayocream** [comment]
https://github.com/kubernetes/website/blob/9154816796f58d1b233163384cf0e68e8c05948e/content/zh/docs/concepts/overview/what-is-kubernetes.md?plain=1#L110
```
* Observability not only surfaces OS-level information and metrics, but also application health and other signals.
```
原文没有冒号…

**Comment by jimangel** [comment]
Hey there! @KolinHuang, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by divya-mohan0209** [comment]
Hey there, @KolinHuang  ! Thank you for your PR. Please note that you're required to sign the CLA before we/the localization team start reviewing your PR. However this has had no activity since 22nd July and will therefore be closed. Please note that you can reopen a fresh PR to k/website once you're ready :)

**Comment by tengqm** [comment]
CLA is okay, but the change is meaningless.
/close

**Pull request closed without merging**
