### PR TITLE
Documentation: link to stackoverflow to configure elasticsearch

### PR DESCRIPTION
**Pull request by davidgfolch**
I was reading kubernetes tutorials and get stacked this this problem, I've finally solved and put it in an stackoverflow question.  And added a link to this documentation.

### CODE REVIEW

**Comment by inductor** [comment]
@davidgfolch Please rebase

**Comment by davidgfolch** [comment]
> @davidgfolch Please rebase

Do you want me to rebase my repo with master branch?

**Comment by davidgfolch** [comment]
/help Please I need help with cla/linuxfundation, I dont understand why documentation is telling me I'm using a different user.

**Comment by VineethReddy02** [comment]
👋 Please rebase this PR on `dev-1.18` in order to avoid merge conflicts.

Feel free to `/hold cancel` after you've rebased.

/hold

**Comment by jimangel** [comment]
It appears this PR contains more than just the intended change. I will close for now, @davidgfolch feel free to re-open after resolving issues. Thanks!

/close

**Pull request closed without merging**
