### PR TITLE
Update install-kubectl.md

### PR DESCRIPTION
**Pull request by ghanbari**
we need run `source /etc/bash_completion` command after `source <(kubectl completion bash)` in linux

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
> we need run source /etc/bash_completion command after source <(kubectl completion bash) in linux

In ubuntu 16.04, I don't need to run `source /etc/bash_completion`.
Which linux do you use?

**Comment by ghanbari** [comment]
I am using ubuntu 14.04 D;

**Comment by Bradamant3** [comment]
@ghanbari @CaoShuFeng can you sort out whether the command is required, whether we should specify the version of ubuntu, whether we should specify multiple ubuntu versions and their individual requirements? Thanks!

**Comment by zacharysarah** [comment]
@ghanbari 👋 Please feel free to reopen this PR with information about affected versions.

**Pull request closed without merging**
