### PR TITLE
Update link to Kublr website

### PR DESCRIPTION
**Pull request by uthark**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.13-ko.<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by DanyC97** [comment]
@uthark am i missing something or both `https://kublr.com` & `https://kublr.com/kubernetes.io/setup-hosted-solution` are showing the same page ?

if so, why the change ?

**Comment by uthark** [comment]
Hi Dani,

We are getting a fair amount of traction from kubernetes.io and would love
to better understand user behavior. A separate link, will enable us to do
that.

Regards,
   Oleg.

**Comment by mistyhacks** [comment]
This feels like you are manipulating the link in our docs to enable analytics on your end, and that's not in the spirit of what our docs are about. You should be able to do the analysis on your end by looking at the referer when a visitor accesses your page, instead.

/close

**Pull request closed without merging**
