### PR TITLE
Broken link in authentication.md

### PR DESCRIPTION
**Pull request by rarean**
issue #16916
fix broken link to UAA setup instructions
propose change to dex setup instructions

### CODE REVIEW

**Comment by bradtopol** [comment]
Hi @rarean Thank you for oyour contribution. Please sign the CLA so we can accept your PR for review

**Comment by tfogo** [comment]
Hi @rarean , thanks for the PR! Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA so that we can review this PR, thanks!

It looks like the commit in this PR is not associated with your GitHub user. Please make sure the email address on your commits match an address associated with your GitHub account. Otherwise the CLA check will fail.

**Comment by tengqm** [comment]
@rarean Please help resolved the conflicts?

**Comment by rarean** [comment]
Looks like someone beat me to the fix, which is already in master. :) resolving the conflict was to basically take master.

**Pull request closed without merging**
