### PR TITLE
[zh] Update garbage-collection.md

### PR DESCRIPTION
**Pull request by jintaiyong**
多了一个‘的’字

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/website/pull/32402#issuecomment-1074662982

**Comment by reylejano** [comment]
/retitle [zh] Update garbage-collection.md

@jintaiyong  please sign the EasyCLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
/close
Closing due to missing CLA for a long time. Feel free to reopen.

**Pull request closed without merging**
