### PR TITLE
fix broken links in user-journeys docs

### PR DESCRIPTION
**Pull request by jhernandezb**
Fix broken links in cluster-operator user journey, due to relative paths was pointing to wrong URL.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7171)

### CODE REVIEW

**Comment by tengqm** [comment]
@jhernandezb Please sign the CLA for this to be merged.
/lgtm

**Comment by jhernandezb** [comment]
I've already signed for some reason wasn't showing the right status.

**Comment by heckj** [comment]
@jhernandezb thank you for the fixes! Did you have to do anything to get the CLA marker switched, or did it fix itself? It’s accepted as I’m looking at it now... so kind of curious.

/lgtm

**Comment by jhernandezb** [comment]
@heckj  I signed like 8 hours ago but seems like the bot didn't get the update until @tengqm  marked it as lgtm that triggered the check .

**Pull request merged**
