### PR TITLE
Change "--experimental-control-plane" with "---control-plane"

### PR DESCRIPTION
**Pull request by ejez**
Change "--experimental-control-plane" with "---control-plane" in the kubeadm command output example

### CODE REVIEW

**Comment by vharsh** [comment]
I signed it

**Comment by neolit123** [comment]
/check-cla
if the CLA check still fails `cla/linuxfoundation — ejez needs CLA` please contact the CNCF help desk.

**Comment by tengqm** [comment]
@ejez Please try follow instructions [here](https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement) to debug CLA status if you have signed it.

**Comment by zacharysarah** [comment]
@ejez 👋 Please feel free to `/reopen` when you're ready to continue.

/close

**Pull request closed without merging**
