### PR TITLE
[ko]: Fixes wrong link in assign-pod-node.md

### LINKED ISSUE #29164: [ko] Fix wrong link in assign-pod-node.md
**This is a Bug Report**

**Problem:** In [scheduling-eviction/assign-pod-node korean page](https://kubernetes.io/ko/docs/concepts/scheduling-eviction/assign-pod-node), there is worng link related to labels-annotations-taints.

**Proposed Solution:**
Change link `[잘 알려진 레이블, 어노테이션 및 테인트](/docs/reference/labels-annotations-taints/)` to `[잘 알려진 레이블, 어노테이션 및 테인트](/ko/docs/reference/labels-annotations-taints/)` on [assign-pod-node.md](https://github.com/kubernetes/website/blob/dev-1.21-ko.7/content/ko/docs/concepts/scheduling-eviction/assign-pod-node.md)

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/scheduling-eviction/assign-pod-node

**Note**
Set base branch `Korean Team working branch`!
> Currently the working branch of Korean Team is `dev-1.21-ko.7`.

/language ko

### PR DESCRIPTION
**Pull request by anushkamittal20**
This PR fixes #29164

### CODE REVIEW

**Comment by ClaudiaJKang** [comment]
/assign

@anushkamittal20 

Thank you for your contribution! 

/lgtm
/approve

**Comment by ClaudiaJKang** [comment]
/approve cancel

@anushkamittal20 

As k8s-ci-robot has mentioned, Kubernetes/website doesn't allow commits with specific keywords that can automatically close issues.
https://github.com/kubernetes/website/pull/29169#issuecomment-889937832

Could you change the commit message and retry again?

**Comment by anushkamittal20** [comment]
Hey @ClaudiaJKang, thank you so much!! I have fixed the commit message. Could you please review again. Thank you!

**Comment by ClaudiaJKang** [comment]
@anushkamittal20 Thank you! 

/lgtm
/approve

**Pull request merged**
