### PR TITLE
Fix incorrect example in ingress pattern matching

### PR DESCRIPTION
**Pull request by 2003Aditya**
closes : #47276

There was an incorrect match given in the ingress examples table (https://kubernetes.io/docs/concepts/services-networking/ingress/#examples).

Screenshot from 2024-07-26 14-11-56

I changed this in all the language.

### CODE REVIEW

**Comment by T-Lakshmi** [comment]
@2003Aditya,
Thank you for your contribution.
It seems that this PR includes changes to files across multiple languages. However, sig docs follows different processes for each localization, and we generally don't accept PRs that impact multiple languages simultaneously. I would recommend modify only the primary website content (only English content) initially with this PR. After the merge of the English content, we could create separate pull request for the remaining languages.

**Comment by Ritikaa96** [comment]
> [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.
> 
> **The list of commits with invalid commit messages**:
> 
> * [faa8efc](https://github.com/kubernetes/website/commits/faa8efc0f6a721c9ec7750dd4986809420001e7f) fix: [Ingress documentation misleading example #47276](https://github.com/kubernetes/website/issues/47276)
> * [1115801](https://github.com/kubernetes/website/commits/1115801789b1c0a8c8449a4e556c681b46d81db3) fix: [Ingress documentation misleading example #47276](https://github.com/kubernetes/website/issues/47276)

Hey @2003Aditya Please look at this comment and change the commit message and description. as per this no hastags or `@` should be there in commit message. 
Please check [guideline](https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines) section for understanding the policy and your future work.

**Comment by T-Lakshmi** [comment]
[@2003Aditya](https://github.com/2003Aditya) ,
Also please look at [this comment](https://github.com/kubernetes/website/pull/47278#issuecomment-2252419860) and change the commit message and description accordingly. 
as per this no hastags or @ should be there in commit message.

Please check [guideline](https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines) section for understanding the policy and your future work.

**Comment by stmcginnis** [comment]
/retitle Fix incorrect example in ingress pattern matching

**Comment by stmcginnis** [comment]
Commits should ideally also be squashed when retitling/rewording them.

**Comment by network-charles** [comment]
Hi, @2003Aditya, thanks for opening this PR! You can read more about the localization issue @T-Lakshmi suggested [here](https://kubernetes.io/docs/contribute/localization/#suggest-changes).

@stmcginnis, there may not be a need to squash the commit.

@2003Aditya, you can revert the commits and push your changes, this will close the PR. Afterwards, push a new commit focusing your changes on the English content alone. Then reopen the PR.

**Pull request closed without merging**
