### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by dankohn**
Signed-off-by: Dan Kohn <dan@dankohn.com>

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-21919--kubernetes-io-master-staging.netlify.app/docs/home/
https://deploy-preview-21919--kubernetes-io-master-staging.netlify.app/community/

Hello @dankohn , Do you see the typo in the website?
There is another "Youtube" variable that is localized in the `i18n` directory.

**Comment by dankohn** [comment]
Yes, the broken link is the YouTube icon at the bottom left of https://kubernetes.io/. GitHub search says that I fixed the only occurrence of `youtbue`.

**Comment by kbhawkey** [comment]
Thanks @dankohn 
/approve

**Pull request merged**
