### PR TITLE
[ko] Fix link

### PR DESCRIPTION
**Pull request by KoditkarVedant**
#31744 - Update hyperlinks present in Korean locals pages to point to main branch

### CODE REVIEW

**Comment by seokho-son** [comment]
@KoditkarVedant Thank you for the contribution. 
In case of Korean localization, we are using own development branch [dev-1.23-ko.2](https://github.com/kubernetes/website/tree/dev-1.23-ko.2). So, base and targer branches are need to be [dev-1.23-ko.2](https://github.com/kubernetes/website/tree/dev-1.23-ko.2)

Could you rebase it to the dev-1.23-ko.2 branch ?

**Comment by KoditkarVedant** [comment]
@seokho-son I've rebase my branch with `dev-1.23-ko.2` and also updated the target branch.

**Comment by seokho-son** [comment]
/lgtm

@KoditkarVedant Could you squash the commits ? 
https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

**Comment by KoditkarVedant** [comment]
@seokho-son I've squashed my commits.

**Comment by jihoon-seo** [comment]
@KoditkarVedant Thank you!
/approve

**Pull request merged**
