### PR TITLE
fix broken link in kops.md

### PR DESCRIPTION
**Pull request by Rahu2000**
fix broken link in kops.md

### CODE REVIEW

**Comment by bradtopol** [comment]
@Rahu2000 Thank you for your contribution. Please sign the CLA so we can accept your PR for review.

**Comment by tfogo** [comment]
Hi @Rahu2000, thanks for the PR! Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA so that we can review this PR, thanks!

**Comment by Rahu2000** [comment]
Hi @tfogo, I signed the CLA. Please review this PR. thank you.

**Comment by Rajakavitha1** [comment]
Thanks for the PR @Rahu2000 !!!
Checked https://deploy-preview-17292--kubernetes-io-master-staging.netlify.com/docs/setup/production-environment/tools/kops/

**Pull request merged**
