### PR TITLE
Update cheatsheet.md

### PR DESCRIPTION
**Pull request by shakti-mishra**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Review by shakti-mishra — COMMENTED** [review]
Hi ,
Any update required , Please help

**Comment by jimangel** [comment]
Hey there! @shakti-mishra, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
I'm closing this due to CLA issue open for too long. Please feel free to reopen when the agreement is signed.
/close

**Pull request closed without merging**
