### PR TITLE
Update website/update-imported-docs/update-imported-docs script for Python 3, PyYAML 5.1.2

### PR DESCRIPTION
**Pull request by aimeeu**
The current version of the script works with Python 2.7, PyYAML 3.13, Go 1.12.  `@tengqm` agreed that the script should be updated to work with Python 3. I took this opportunity to "pythonify" the code. Updating to the latest version of PyYAML required an update to the Python script to remove a deprecated function. Looking at the code, I decided it would be better to use the Python tempfile library to create the temp directory rather than `os` and `shutil` libraries.

**This script was tested on Ubuntu 18 with Python 3.7.4, go1.12.10 linux/amd64, and PyYAML 5.1.2 installed in a virtual environment.**

Current version in master for comparison: https://github.com/kubernetes/website/blob/master/update-imported-docs/update-imported-docs

- Add .py extension to update-imported-docs file
- Update shebang for Python 3
- Add script comments: software versions, what the script does, and how to run it
- Update to use argparse.ArgumentParser() for command line args
- Change work_dir from hard-coded dir to tmp dir created using the tempfile library; remove shutil.rmtree because it was throwing permission errors and also no longer needed after switching
to temp dir created with tempfile.
- Enhance error handling
- Add check for Go installation
- Enhance check for PyYAML installation
- Change deprecated PyYAML load function to full_load https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
- Modify to comply with PEP8
- Update software versions in website/content/en/docs/contribute/generate-ref-docs/kubernetes-components.md

Partial #15682 
Previous PR #16681  (ran afoul of rebase issues) 

Doc preview:  https://deploy-preview-17127--kubernetes-io-master-staging.netlify.com/docs/contribute/generate-ref-docs/kubernetes-components/

**STEPS TO TEST THE SCRIPT**
Scenario 1: All prerequisites installed
1. (Optional) Create a virtual environment with Python = 3.7.4
2. `cd` to website/update-imported-script and execute the script `$ ./update-imported-docs.py reference.yml`  

Signed-off-by: Aimee Ukasick <aimeeu.opensource@gmail.com>

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-17127--kubernetes-io-master-staging.netlify.com/docs/contribute/generate-ref-docs/kubernetes-components/

/lgtm

**Comment by aimeeu** [comment]
Still investigating what the [Fixing Links](https://deploy-preview-17127--kubernetes-io-master-staging.netlify.com/docs/contribute/generate-ref-docs/kubernetes-components/#fixing-links) switch does.

**Pull request merged**
