### PR TITLE
update storage orchestration section (vietnamese document)

### PR DESCRIPTION
**Pull request by tuantmb**
update "Storage orchestration" (điều phối lưu trữ)

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by rolfedh** [comment]
Would you to remove the language labels that don't apply to this PR?

**Comment by Sea-n** [comment]
Hey @tuantmb,

Thanks for proposing this PR. But since this PR is annoying to reviewers (involved 250 commits and 12 langs) and you didn't respond for days, we have to close this PR now.
/close

Feel free to open a new one when you solved the git problem. We still looking forward for your contribution! 🙃

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de en es fr hi id ja ko pl pt zh
/remove-sig release

**Pull request closed without merging**
