### PR TITLE
 fix link in ingress page (ko)

### PR DESCRIPTION
**Pull request by joohee**
This pr is to fix link in ingress page. 

/kind bug
/language ko

### CODE REVIEW

**Comment by joohee** [comment]
Sorry. I thought I signed a CLA. Now I did it, thanks.

**Comment by joohee** [comment]
I signed it

**Comment by joohee** [comment]
I just modified my author info and force push, 

```
git commit --amend --author="My Name <My Email Address>"
```

but still fail to pass a CLA...

https://identity.linuxfoundation.org/projects/cncf
```
7. My pull request still doesn't pass!
If you haven't yet, post a comment ("I signed it") to the PR—this is needed for the system to recheck your contribution authorization.

Each commit in the pull request needs to pass. If you have commits that didn't attribute to a Github username, or to a different user that hasn't signed the CLA, that will fail that commit and all subsequent commits.

If that does not help, please submit a support request.
```

**Comment by habibrosyad** [comment]
Just curious, did you follow the guide stated [above](https://github.com/kubernetes/website/pull/23231#issuecomment-675773167) especially this part https://github.com/kubernetes/community/blob/master/CLA.md#4-ensure-your-github-e-mail-address-matches-address-used-to-sign-cla?

**Comment by pjhwa** [comment]
@joohee By any chances, please check the following settings.
- Settings > Emails > 'Primary email address' is the same address you signed.
- And this email address should be set as "Visible in emails".

**Comment by joohee** [comment]
@habibrosyad @pjhwa 

Thank you all, I succeed to pass a CLA.

**Comment by pjhwa** [comment]
@joohee I think this looks good. 
However, to avoid conflict, it might be better to wait until merging dev-1.18-ko.10 branch to master branch.
Please wait some more time.

**Comment by pjhwa** [comment]
> @joohee I think this looks good.
> However, to avoid conflict, it might be better to wait until merging dev-1.18-ko.10 branch to master branch.
> Please wait some more time.

dev-1.18-ko.10 branch has been merged to master branch.

/lgtm

**Comment by seokho-son** [comment]
Thank you :) 
/approve

**Pull request merged**
