### PR TITLE
Merged main dev 1.31

### PR DESCRIPTION
**Pull request by hacktivist123**
This PR syncs the dev-1.31 branch with the main branch to keep the dev-1.31 branch up to date.

cc: @chanieljdan @salaxander @MaryamTavakkoli @LaurentGoderre @Princesso

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/approve

**Comment by dipesh-rawat** [comment]
This also needs official approval required from [`sig-docs-website-owner`](https://github.com/kubernetes/website/blob/dev-1.31/OWNERS_ALIASES#L11)

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks for this PR, @hacktivist123!
/approve

**Pull request merged**
