### PR TITLE
[ko] Update link href to translated page

### LINKED ISSUE #27121: [ko] Update link href to translated page
**Problem:**
In https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/#%EC%84%A4%EC%B9%98-%EB%B0%A9%EB%B2%95 ,
the link href is https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm (English).

The [Korean version](https://kubernetes.io/ko/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) of https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm is
recently added in #26837.

**Proposed Solution:**
In https://github.com/kubernetes/website/edit/master/content/ko/docs/reference/setup-tools/kubeadm/_index.md ,

Before: `kubeadm을 설치하려면, [설치 가이드](/docs/setup/production-environment/tools/kubeadm/install-kubeadm)를 참고한다.`
After: `kubeadm을 설치하려면, [설치 가이드](/ko/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)를 참고한다.`

**Page to Update:**
https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/

/assign

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Resolves #27121
- Replaces the PR #27122

> **Problem:**
> In https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/#%EC%84%A4%EC%B9%98-%EB%B0%A9%EB%B2%95 ,
> the link href is https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm (English).
> 
> The [Korean version](https://kubernetes.io/ko/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) of https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm is
> recently added in #26837.
> 
> **Proposed Solution:**
> In https://github.com/kubernetes/website/edit/master/content/ko/docs/reference/setup-tools/kubeadm/_index.md ,
> 
> Before: `kubeadm을 설치하려면, [설치 가이드](/docs/setup/production-environment/tools/kubeadm/install-kubeadm)를 참고한다.`
> After: `kubeadm을 설치하려면, [설치 가이드](/ko/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)를 참고한다.`
> 
> **Page to Update:**
> https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/

/language ko

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Direct link to the preview:
- https://deploy-preview-27134--kubernetes-io-master-staging.netlify.app/ko/docs/reference/setup-tools/kubeadm/#%EC%84%A4%EC%B9%98-%EB%B0%A9%EB%B2%95
- https://deploy-preview-27134--kubernetes-io-master-staging.netlify.app/ko/docs/reference/tools/#kubeadm
- https://deploy-preview-27134--kubernetes-io-master-staging.netlify.app/ko/docs/setup/production-environment/container-runtimes/#containerd-systemd
- https://deploy-preview-27134--kubernetes-io-master-staging.netlify.app/ko/docs/tasks/tools/#kubeadm

**Comment by seokho-son** [comment]
@jihoon-seo  제안 감사합니다.. ^^
혹시 [dev-1.20-ko.7 브랜치](https://github.com/kubernetes/website/issues/27147)를 기준으로 작업해주실 수 있을까요? 
(작업 환경에서 dev-1.20-ko.7 로 리베이스 및 PR로 push 후, PR의 target base branch를 dev-1.20-ko.7 로 변경)

**Comment by jihoon-seo** [comment]
@seokho-son 알려 주신 대로 변경을 완료했습니다!

**Comment by gochist** [comment]
@jihoon-seo @seokho-son 
Thank you!!!
/lgtm
/approve

**Pull request merged**
