### PR TITLE
Update assign-pod-node.md

### PR DESCRIPTION
**Pull request by sherief92**
Corrected the documentation to match with the yaml snippet

### CODE REVIEW

**Comment by windsonsea** [comment]
You need sign a cla before review and merge.

**Review by Arhell — COMMENTED** [review]
CLA info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by divya-mohan0209** [comment]
Hello @sherief92 , thank you for your contribution! However since there has been no response from your end, this is currently being worked upon by #34785 by another contributor. Please ensure you sign the CLA before submitting a PR the next time. It'll help us review & merge changes easily.

**Pull request closed without merging**
