### PR TITLE
[zh-cn] Modify Chinese translation

### PR DESCRIPTION
**Pull request by aimuz**
djust your priorities: 命名空间 > 名字空间

It has always been the case that namespace is translated as 命名空间

Signed-off-by: aimuz <mr.imuz@gmail.com>

### CODE REVIEW

**Comment by aimuz** [comment]
https://github.com/kubernetes/website/commit/d38315f27b32b0b356c6b5ce7c2837118cfadccb

**Comment by windsonsea** [comment]
Hi, hope you have carefully read the [en-zh localization glossary](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7).

This PR involves 125 files that may cause many conflicts. This is not encouraged. 

/hold

**Comment by windsonsea** [comment]
If you desire to change the term `namespace`, please modify the [localization style page](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/) first. One suggestion is to open an issue to discuss further.

Now the glossary shows both are acceptable:

```
namespace，名字空间，命名空间
```

**Comment by aimuz** [comment]
This is not a recommended use

/unhold

**Comment by windsonsea** [comment]
> This is not a recommended use
> 
> /unhold

Boy, if some questions exist and need more discussion there, do not simply `unhold`.....

**Comment by aimuz** [comment]
Sorry, too many files do create conflicts

**Comment by howieyuen** [comment]
The translation of namespace into "名字空间" or "命名空间" has been discussed a long time ago, and it was finally agreed that both can be used. 
I have roughly calculated that in the translations of the whole site at that time, the usage of the two was basically half and half.
So, you can use "命名空间" in your localized PR, but not to change them all.

**Comment by aimuz** [comment]
@howieyuen 
Now the information on the web is based on `命名空间`, and the `名字空间` has never been heard of, do you have a link to discuss it?

`名字空间` He is a direct translation

**Comment by aimuz** [comment]
https://www.google.com/search?q=k8s+%E5%90%8D%E5%AD%97%E7%A9%BA%E9%97%B4

According to the search, no information has ever been defined as `名字空间` except for modified documents, so why is `名字空间` prioritized before `命名空间`?

**Comment by tengqm** [comment]
“命名”一词本身是动词，赋予某物名称的意思。在英文中对应的精确表达应该是 naming。
“namespace” 中的 name 是一个纯名词，拆解来理解意味着“名字的作用域”，直接翻译为“名字空间”是更为贴切的译法。
至于在其他地方看到很多“命名空间”的说法，有些人就直接接受了，将其奉为圭臬了，我们也尊重，只是在这个语境中，为“命名”这个动作提供一个空间，还是很牵强。

/close

**Comment by aimuz** [comment]
在最早的C++中的namespace，也是翻译为命名空间，在 kubernetes 相关系列的图书中，也是称为命名空间，从未看到过名字空间的用法。

**Comment by aimuz** [comment]
本土化翻译，我认为应该切合大家的使用习惯，而不是以学术化方式，拆字解字。

**Comment by aimuz** [comment]
https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/namespaces/
https://kubernetes.io/ja/docs/concepts/overview/working-with-objects/namespaces/

不管在韩语还是日语中，他们都是命名空间

所以我们为什么要反其道而行之？

**Comment by howieyuen** [comment]
> @howieyuen Now the information on the web is based on `命名空间`, and the `名字空间` has never been heard of, do you have a link to discuss it?
> 
> `名字空间` He is a direct translation

sorry, I only remember that the discussion is under comments in one PR, because this question also bothers me earlier.

**Comment by aimuz** [comment]
@tengqm 就name词性来讲 ，naming 准确的说是现在分词，表进行的意思，而name可以是名词也可以是及物动词，不知道你是否了解

**Comment by aimuz** [comment]
This is something that can be discussed, so why just shut it close?

**Comment by anstns** [comment]
> 至于在其他地方“名字空间 ” 的奉行的话，在这个名字，在名字的中名圭臬，我们也贴贴了，译文境中，为“命名”这个动作提供了一个空间，还是很牵强。
> 
> /关

大家都是中国人我就用中文跟你说吧。你们深信服的公司就是这样总爱搞点事情，比如rancher套个壳就是你们自研发。没事监控监控员工的上网行为管理也是你们公司干的缺德事。就事论事来说，我们19年到现在都是用的命名空间，为什么要改，你们说讨论过后，麻烦说一下跟谁在讨论，是不是你们自己大脑短路自己研究的呢。

**Comment by windsonsea** [comment]
@anstns

随意蔓延攻击毫无意义，如果礼貌都不会，只知道嘲讽、怼人，就算有理也将没理。

爱护环境人人有责，请勿污染环境，谢谢。

/close

**Comment by aimuz** [comment]
@anstns 确实过了点

@windsonsea https://kubernetes.io/community/code-of-conduct/#our-standards

Being respectful of differing opinions, viewpoints, and experiences

尊重不同的意见、观点和经验，然后你们就可以随意关闭PR了？

**Comment by aimuz** [comment]
Focusing on what is best not just for us as individuals, but for the overall community

这里也提到了，觉得改成名字空间对社区友好吗？改了近两年，现在有使用名字空间吗？强行推广，来表示自己专业性？

**Comment by aimuz** [comment]
有个成语叫 矫枉过正

**Comment by Sea-n** [comment]
FYI, in Google search [名字空間](https://www.google.com/search?q=%22%E5%90%8D%E5%AD%97%E7%A9%BA%E9%96%93%22) has 300k results, and [命名空間](https://www.google.com/search?q=%22%E5%91%BD%E5%90%8D%E7%A9%BA%E9%96%93%22) has 400k results. Both are significantly used in the Chinese world.

It's great to use the "correct" one in your contribution (new files or new paragraphs). We will feel your passion for tracing correctness, which is an encouraged attitude to contributing.

---

But this PR may fall into [Trivial Edits](https://www.k8s.dev/docs/guide/pull-requests/#trivial-edits), which is not accepted by our community.

- Does this PR greatly improve the quality of the content?
- Can the term glossary be improved further?

It's better to open an issue to discuss with others first, then we can "fix" related documents if needed.

**Comment by aimuz** [comment]
In k8s, we more widely use `命名空间`, in addition if the use of `名字空间`, when referring to other materials, will make the reader confused, because the current variety of materials, including new materials, are using `命名空间`

Also, if we take value, many pr's should not be merged.

**Comment by aimuz** [comment]
https://www.google.com/search?q=k8s+%22%E5%90%8D%E5%AD%97%E7%A9%BA%E9%96%93%22
About 20,300 results

https://www.google.com/search?q=k8s+%22%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4%22
About 246,000 results

**Comment by aimuz** [comment]
As for modifying to `命名空间`, in China or other people who use Chinese, ask him about k8s namespace, I think more people will answer `命名空间`, at least around me, I asked in some technical communities, if you choose between  `名字空间` and `命名空间`, most people's answer is `命名空间`, and some people suggested`名称空间` is also good.

In the k8s ecosystem, they also all use the `命名空间`

------

Also if we are talking about value, then `命名空间` will not be changed to `名字空间`

The documentation prior to this one used `命名空间`

https://github.com/kubernetes/website/commit/d38315f27b32b0b356c6b5ce7c2837118cfadccb

**Comment by anstns** [comment]
> 让

这不是人身攻击，说的都是实话（rancher改皮是他们干的不）（上网行为管理是他们做的不），我哪里说错了？

**Comment by aimuz** [comment]
In the k8s ecosystem, they all actually use the `命名空间`

For instance, they (Includes cncf projects):

- [rancher](https://docs.ranchermanager.rancher.io/zh/how-to-guides/new-user-guides/manage-namespaces)
- [istio](https://istio.io/latest/zh/docs/tasks/security/authentication/authn-policy/#namespace-wide-policy)
- [volcano](https://volcano.sh/zh/docs/installation/#%E6%AD%A5%E9%AA%A4-1)
- [kubeEdge](https://kubeedge.io/zh/docs/setup/keadm_zh/#master)

I looked through the projects in CNCF and there is no description of `名字空间` in their documentation, there are just `命名空间` that

In addition, when I took the CKA certificate, the topic descriptions in it also used `命名空间`

**Comment by aimuz** [comment]
[名字空間](https://www.google.com/search?q=%22%E5%90%8D%E5%AD%97%E7%A9%BA%E9%96%93%22)
Click on this link and you'll actually find that his first entry is Wikipedia, titled `命名空间`

**Comment by tengqm** [comment]
> /reopen 有相关讨论地址吗？

好吧。如果这个问题对一些读者非常重要。可以去搜索一下之前的 PR（如果我没记错的话，讨论不是在一个 issue 下面进行的）。 在中文译文风格指南的 git history 里面可能也有一部分。其他 reviewer 也可以补充一些，看看我们是不是还在哪里讨论过。我印象中这个问题在过去一年中至少讨论过三次。

**Comment by aimuz** [comment]
https://github.com/kubernetes/website/pull/33179
https://github.com/kubernetes/website/issues/28459
https://github.com/kubernetes/website/issues/35798

I searched the following links, all about the controversy of why it is `名字空间` that
The controversy about why it's a `命名空间` I only saw one

https://github.com/kubernetes/website/issues/28459#issuecomment-863623927

>We had such discussions previously when drafting and reviewing the https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7 page. I personally prefer "名字空间”，because that is what namespace for ... a space for names. There are other voices arguing that "命名空间” is very popular in many articles or books.


Would there be these controversies if it were a `命名空间`？People who raise these controversies are feeling doubtful about `名字空间`

**Comment by Sea-n** [comment]
Hey @aimuz, would you like to open an issue so that we can discuss this further?

Without the issue, we would have to close this controversial PR.

**Comment by tengqm** [comment]
Those discussion history can serve a background why we don't want to invest time on this issue again. We had discussions on this and we articulated the reason why "名字空间" is acceptable, or even a better option.

When deciding how to translate a term, we consider whether a translation is good not by how it is used in other fields or contexts. We were and we are still trying to find the best Chinese word for an English word. In other words, we honor the true facts rather than how others are doing.

作为严谨的科技工作者，我们的职责不是人云亦云，不是根据事物的流行度来做判断，而是在工作中（包括社区工作中）去重新审视所有即成事实的、已被认定的事物。这一过程并不是轻松的、写意的，而是天人交战的、绞尽脑汁的。毕竟，Kubernetes 的官方文档会是很多下游社区的信息源；毕竟，大家在社区中所做的贡献都要在阳光下晾晒。

**Comment by correctzh** [comment]
I don't think that if it is correct`名字空间`, there will be so many people who have raised similar issues. If it is wrong, it is wrong. You must be humbly adjusted to accept the suggestions of the contributors. 
The discussion you are talking about is just that everyone fears you and does not continue to delve into it , just like this PR act you close other people's comments.
This is a wrong translation`名字空间`, please adjust it to be correct`命名空间`.

**Comment by tengqm** [comment]
@correctzh We never said that "名字空间" is the single translation we can accept. We were trying to elaborate two things: 1. "名字空间" could be a better choice. 2. both "名字空间" and "命名空间" are acceptable, given that the latter is also widely used. This is not a black or white question.

Just as suggested by other comments, both translations have been used in other contexts. Period.

**Comment by aimuz** [comment]
However, in the existing document, a large number of them are modified to `名字空间`, and if they are modified to `命名空间`, they will be rejected with `名字空间` priority being greater than `命名空间`.

This PR is also currently just modifying their priority.

So what's the difference between now and only using it?

**Comment by correctzh** [comment]
Kubernetes product:
1. Azure Kubernetes Service (AKS) - 命名空间
https://learn.microsoft.com/zh-cn/azure/aks/concepts-clusters-workloads#namespaces

2. Amazon EKS - 命名空间
https://docs.aws.amazon.com/zh_cn/eks/latest/userguide/sample-deployment.html

3. Red Hat OpenShift - 项目和命名空间
https://access.redhat.com/documentation/zh-cn/openshift_container_platform/4.3/html/authentication/rbac-projects-namespaces_using-rbac#doc-wrapper

---
CNCF projects:
1. rancher
https://docs.ranchermanager.rancher.io/zh/how-to-guides/new-user-guides/manage-namespaces

2. istio
https://istio.io/latest/zh/docs/tasks/security/authentication/authn-policy/#namespace-wide-policy

3. volcano
https://volcano.sh/zh/docs/installation/#%E6%AD%A5%E9%AA%A4-1

4. kubeEdge
https://kubeedge.io/zh/docs/setup/keadm_zh/#master

---
CNCF Ambassadors:
1. Jimmy Song - blog: 不同命名空间中的服务要绑定到同一个网关中的情况在实际情况下经常出现，而入口网关无法在多个命名空间中共享；
https://jimmysong.io/blog/why-gateway-api-is-the-future-of-ingress-and-mesh/

2. Lei Zhang - special column: 其解释了如何利用命名空间（Namespace）这一概念来组织 K8s 租户的资源。
https://www.infoq.cn/article/fsmwwgyknsgwpegjho4g

---
sig-docs-zh-reviews:
1. chenxuc
https://github.com/kubernetes/website/pull/37665

kubernetes Contributor:
1. yinyicao
https://github.com/kubernetes/website/pull/33179

2. linruikai
https://github.com/kubernetes/website/issues/35798
---
google search results(命名空间>名字空间):
k8s+"命名空间" - About 246,000 results
https://www.google.com/search?q=k8s+%22%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4%22

k8s "名字空间" - About 20,300 results
https://www.google.com/search?q=k8s+%22%E5%90%8D%E5%AD%97%E7%A9%BA%E9%97%B4%22

---

The first focus of localization is correctness.
This is a wrong translation(`名字空间`),please adjust it to be correct(`命名空间`).
In official commercial Kubernetes product(Azure Kubernetes Service,Amazon EKS,Red Hat OpenShift), in CNCF projects(rancher,istio,volcano,kubeEdge), in K8S experts(CNCF Ambassadors:Jimmy Song,Lei Zhang),in sig-docs-zh-reviews(chenxuc) ,in enthusiastic contributors(yinyicao,linruikai,aimuz),All are used correct(`命名空间`).
Do you have any references to prove what you said, "名字空间" could be a better choice. 

This is wrong(`名字空间`). If you continue to use it(`名字空间`), other users will continue to give you correct advice. Continuing to use the wrong one(`名字空间`) is a real waste of time.
The community isn't yours, it's all those who are willing to say a word about this project.
He should be encouraged as long as he is willing to put in the time for this project.

**Comment by salaxander** [comment]
Hi everyone - I'm from the Kubernetes code of conduct committee. We received a report on this PR, and at this time are going to lock this.

Please reach out to conduct@kubernetes.io for further questions or clarification.

**Pull request closed without merging**
