### PR TITLE
[WIP] Add blog article “Maximize pod up-time in Kubernetes by utilizing PriorityClass and PodDisruptionBudget”

### PR DESCRIPTION
**Pull request by sunnybhambhani**
Hi Team,

Hope you are doing well, I am planning to write an article on "how to maximize pod uptime by utilizing PDB and PC in conjunction".

The TOC which I am thinking is something like this: 
> - What is disruption?
> - What are PriorityClass and PodDisruptionBudget?
> - How to use PriorityClass and PodDisruptionBudget in combination to manage pod scheduling and availability?
> - Some use-cases?
> - Hands-on example?
> - Limitations and considerations?
> - Conclusion?

Motivation/Why this topic?
- One of the readers came back to me after reading this article "https://kubernetes.io/blog/2023/01/12/protect-mission-critical-pods-priorityclass/" asking if they both work together.

I thought that this may be a good subject for a piece of writing. However, since this is sort of an addition to the prior article, I'm not sure whether it would be a worthy addition from the standpoint of publishing. 

Additionally, I'm not sure if a second article will be of that much importance or if we should revise the earlier one. 

Please let me know your thoughts on this so that I can start writing something on it or should delete this PR.

Thank you,
Sunny

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
Explicit hold to avoid accidental merges.

/hold

**Comment by sftim** [comment]
/retitle [WIP] Maximize pod up-time in Kubernetes by utilizing PriorityClass and PodDisruptionBudget
/hold cancel

**Comment by sftim** [comment]
/retitle [WIP] Add blog article “Maximize pod up-time in Kubernetes by utilizing PriorityClass and PodDisruptionBudget”

**Comment by kbhawkey** [comment]
Hello @sunnybhambhani .
Are you planning to update this pull request or should I close it?

**Comment by divya-mohan0209** [comment]
Hello @sunnybhambhani , please note that since there has been no activity on this PR from ~4 months, I'm closing it.

A couple of suggestions on how you can continue work on this, if you have bandwidth in the future.

- Socialize your idea on the #sig-docs-blog Slack channel OR during one of the regular/monthly SIG meetings.
- Once you gain consensus, open a PR.

/remove-lifecycle stale
/close

**Pull request closed without merging**
