### PR TITLE
[ja] Translate tasks/administer-cluster/manage-resources into Japanese

### LINKED ISSUE #31361: [ja] Translate tasks/administer-cluster/manage-resources into Japanese
# This is a Feature Request

## What would you like to be added

Translate [tasks/administer-cluster/manage-resources](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources)  into Japanese.

## Why is this needed

This page has not been translated.

## Comments

/language ja
/assign

### PR DESCRIPTION
**Pull request by ptux**
resolve #31361

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @atoato88

**Comment by atoato88** [comment]
LGTM also. :smile:

**Pull request merged**
