### PR TITLE
Pod affinity namespaceSelector to GA

### PR DESCRIPTION
**Pull request by ahg-g**
ref: https://github.com/kubernetes/enhancements/issues/2249

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by tengqm** [comment]
/lgtm
I'm abandoning my change #32332

**Comment by sftim** [comment]
LGTM

**Comment by reylejano** [comment]
Code has merged in https://github.com/kubernetes/kubernetes/pull/108136

LGTM from SIG Scheduling tech lead and SIG Docs tech leads

/approve

**Pull request merged**
