### PR TITLE
fix typo in ccm > service controllers

### PR DESCRIPTION
**Pull request by tphummel**

### CODE REVIEW

**Comment by DanyC97** [comment]
@tphummel thank you for the fix. Before we can review/ approve it, can you please sign the CLA?

**Comment by jaredbhatti** [comment]
Please sign the CLA.

**Comment by bradtopol** [comment]
@tphummel Thank you for your contribution. Please sign the cla so we can accept your PR for review

**Comment by Rajakavitha1** [comment]
@tphummel Thanks for the PR. Please see: https://github.com/kubernetes/community/blob/master/CLA.md for instructions to sign the CLA.

**Comment by cody-clark** [comment]
Hi @tphummel. Thanks for your PR! We don't seem to be getting any response, so I'm going to close this, but please reopen this once you've signed the CLA, and I'll be happy to approve it.

> 📝 Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

/close

**Pull request closed without merging**
