### PR TITLE
remove the left bits of salt

### PR DESCRIPTION
**Pull request by charrywanganthony**
after #10192 , salt was removed, but not completely.

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@charrywanganthony  Thanks for the fix.
/lgtm

**Comment by Bradamant3** [comment]
whoops, not quite.
Some of these files should be changed in the source Chinese translation repo, not here. Please submit a separate PR against https://github.com/kubernetes/kubernetes-docs-zh for the Chinese language files (and remove them from this PR). Thanks!

/lgtm cancel

**Comment by charrywanganthony** [comment]
@Bradamant3 Modified.

**Comment by Bradamant3** [comment]
@charrywanganthony thank you so much! This has been on my mind for a while now. So good to get it taken care of :-)

/lgtm
/approve

**Pull request merged**
