### PR TITLE
fix typo: remove extra "

### PR DESCRIPTION
**Pull request by t1anz0ng**
remove redundant `"` suffix

Signed-off-by: tianyang ni <tianzong48@gmail.com>

---

current: [autoscaling](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2beta2/#HorizontalPodAutoscalerSpec)

preview: https://deploy-preview-35785--kubernetes-io-main-staging.netlify.app/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2beta2/#HorizontalPodAutoscalerSpec

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @t1anz0ng,

Thanks for contributing k8s website! In this repo, we limited to one language for each PR.
Please just update the `en` content and leave the `zh-cn` one to native speakers to change after this PR merged.

**Comment by t1anz0ng** [comment]
> Hey @t1anz0ng,
> 
> Thanks for contributing k8s website! In this repo, we limited to one language for each PR. Please just update the `en` content and leave the `zh-cn` one to native speakers to change after this PR merged.

Hi @Sea-n  Thanks for helping!
Sure, I can split this PR. 
But I was wondering if that's necessary while this change is all about URL (which is irrelevant to language).

**Comment by t1anz0ng** [comment]
I've split `zh-cn` part of this pr into: https://github.com/kubernetes/website/pull/35801  😄 @Sea-n

**Review by divya-mohan0209 — COMMENTED** [review]
Hello & thank you for your contribution! This is a generated reference doc from the k/k repo text strings & hence manually editing it here wouldn't be useful. Please

**Pull request closed without merging**
