### PR TITLE
[wip] fixup capture statements

### PR DESCRIPTION
**Pull request by kbhawkey**
Testing removal of capture statements.
Create shortcodes for common headings.
Ran cleanup script over `en` only pages to constrain changes.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Related to #20977.

**Comment by kbhawkey** [comment]
@zacharysarah , interested to get your feedback on this approach.

**Comment by sftim** [comment]
Can I help with either implementation or with testing here?

**Comment by kbhawkey** [comment]
> Can I help with either implementation or with testing here?

@sftim, I am happy to hear your ideas.
I'd like people to agree on whether,
- to remove the capture statements and template data in front matter
- are comments needed in the page body to delineate the page
- what common headings are needed on the page (for example, prerequisites, whatsnext, ...)

Removing the capture statements should make parsing easier (and faster).
The changes should be compatible with the Docsy theme.

Testing the what's next on this page,
https://deploy-preview-21253--kubernetes-io-master-staging.netlify.app/docs/concepts/architecture/controller/

**Pull request closed without merging**
