### PR TITLE
fix image display in firefox browser

### PR DESCRIPTION
**Pull request by Arhell**
issue #21923
old PR #19421

### CODE REVIEW

**Comment by Arhell** [comment]
breaks another fix

**Comment by Arhell** [comment]
review page https://deploy-preview-22548--kubernetes-io-master-staging.netlify.app/
check on firefox
/assign @sftim

**Comment by celestehorgan** [comment]
/lgtm

Firefox 77.0.1 on Mac OSX 10.14.6 (Mojave)

Thanks!

**Pull request merged**
