### PR TITLE
Added CSS height property to #oceanNodes main to fix spacing in Firefox

### PR DESCRIPTION
**Pull request by alkaliphile**
I added the height property to #oceanNodes main, only for tablet and desktop views. This makes the front page look consistent between Chrome and Firefox. Please see the before images for each browser, attached below.

Firefox:
image

Chrome:
image

### CODE REVIEW

**Comment by alkaliphile** [comment]
It's probably worth noting that the deploy preview doesn't have the changed CSS. Running the project locally did, though.

Do I need to add another step to update the CSS once the project is built?

**Comment by zparnold** [comment]
@alkaliphile Can you please fix these merge conflicts?

**Comment by alkaliphile** [comment]
@zparnold Done. I had to add the updated CSS property directly to styles.css. My original change to _tablet.sass didn't appear to work anymore, as the target in the JSON file at resources/_gen/assets/sass/sass is no longer the minified stylesheet.

**Comment by zparnold** [comment]
@zacharysarah or @lucperkins  Could you give me a quick sanity check on this one? I forgot how we were handling generated Sass?

**Comment by zacharysarah** [comment]
@zparnold Thanks for checking! This looks sane to me, based on #10373, #10464, and the current contents of `master`. 

/lgtm
/approve

**Pull request merged**
