### PR TITLE
correct the misspelling

### PR DESCRIPTION
**Pull request by forybm**
Add "t" missing  "t" in "cluster" : )

### CODE REVIEW

**Comment by forybm** [comment]
I signed

**Comment by ClaudiaJKang** [comment]
/assign

@forybm Thank you for contributing to localization content. 

However, the working branch of our team is dev-1.17-ko.4. 
Thus, could you change the base branch `master` to `dev-1.17-ko.4`. And, this work may be required to do `git rebase`. If you have any questions, you can contact Kubernetes Slack`kubernetes-docs-ko`.

**Comment by sftim** [comment]
nit:
> Add "s" missing "s" in "cluster" : )

The missing letter is “t”, I think.

**Comment by forybm** [comment]
It was reopened as #19063 :)

**Pull request closed without merging**
