### PR TITLE
Localise Gujarati GU initial commit

### PR DESCRIPTION
**Pull request by harsh4870**
Signed-off-by: Harsh Manvar harsh.manvar111@gmail.com
Localizes ``README-gu.md``  to Gujarati
Localizes ``config.toml``  to Gujarati
Localizes ``content/gu/OWNERS``  to Gujarati
Localizes ``content/gu/_common-resources/index.md``  to Gujarati
Localizes ``content/gu/_index.html``  to Gujarati
Localizes ``content/gu/case-studies/_index.html``  to Gujarati
This is an initial PR as may need some improvements!
Tracking issue: #38740

### CODE REVIEW

**Comment by sftim** [comment]
I'll mark this as a draft for now.

**Comment by sftim** [comment]
You might need to add `data/i18n/gu/gu.toml` and make `i18n/gu.toml` be a symlink to that. `data/i18n/gu/gu.toml` can start off empty.

**Comment by harsh4870** [comment]
Sure, thanks for the suggestion. Created the files with a symlink. 

Could you also please help will keep all PR as drafts OR 
can't we just create a branch in the repo for **gu** and start maintaining it instead marking PR as a draft ?  

Few other folks will be also raising the request soon, it will be like different PRs as drafts, with the single specific branch for **gu** it would start taking shape, tracking slow but sure progress.

**Comment by sftim** [comment]
How's the work going on this new localization? Any questions?

**Comment by harsh4870** [comment]
@sftim  Thanks team yes we are working on it, here is the [issue](https://github.com/kubernetes/website/issues/38740) we are tracking details here. 

Also could you please let me know if multiple people raising the MR, would it be good to keep all those to **main** branch in the draft and maintain those? 

Can't we get or manage one **feature** branch in the K8s repo so all could merge to that **feature** branch at end, we can merge that feature branch to **main** of Kubernetes.

**Comment by divya-mohan0209** [comment]
Hello @harsh4870 , wanted to check-in on the progress of the localization work. Do you need any assistance? Additionally, I'd recommend addressing the conflicts before proceeding.

**Comment by harsh4870** [comment]
Hi @divya-mohan0209  Many thanks for checking, i am on it a little slow & it goes stale. Will reach out for sure if any assistance is required.

**Comment by sftim** [comment]
How is progress?

You are welcome to work as a team towards adding a new localization; however, if there is no progress then a maintainer may close this pull request.

Even if that happens, you are welcome to continue the work and to open a new pull request if you find you have more capacity to contribute.

**Comment by harsh4870** [comment]
Hi @sftim 

i am working on it slowly and single-handedly so it may take a little longer to complete full localization.

**Comment by sftim** [comment]
Can we help you find another team member @harsh4870? Localization teams need to be two people at a minimum.

**Comment by harsh4870** [comment]
Sure, please if possible that would be helpful. Many thanks for the help i am too looking around.

**Comment by sftim** [comment]
This work has not progressed. @harsh4870 you are welcome to continue trying to form a team to localize the Kubernetes documentation into Gujurati.
Please feel free to ask for advice in Kubernetes' Slack workspace; visit https://slack.k8s.io/ for an invitation, and then talk with team `#sig-docs-localizations`.

/close

**Pull request closed without merging**
