### PR TITLE
Update 2 links in command-line-tools-reference/kubelet

### PR DESCRIPTION
**Pull request by mrVectorz**
Removing stale links, to some that are more relevant.

### CODE REVIEW

**Review by aj11anuj — COMMENTED** [review]
lgtm 👍

**Comment by windsonsea** [comment]
Try to enable your title meaningful:

/retitle Update 2 links in command-line-tools-reference/kubelet

**Comment by mrVectorz** [comment]
Thanks didn't know how precise the title should really be.
@windsonsea should I amend my commit msg too, or doesn't matter?

**Comment by aj11anuj** [comment]
If you have already committed with that message, and the message is not totally different from your commit or it isn't invalid commit message till then it doesn't matter much.

**Comment by shannonxtreme** [comment]
Your commit messages come in handy if you're doing more complex changes (for example, moving content and also modifying the moved content). Detailing what exactly changed can reduce the burden on localization teams trying to figure out what really needs to change. But in small changes like this that's no big deal 😁

**Comment by mrVectorz** [comment]
Cool thanks for the clarifications, I'll leave it as is then.

**Comment by tengqm** [comment]
Thanks.
/approve

**Pull request merged**
