### PR TITLE
[hi] Localize containerd.md

### PR DESCRIPTION
**Pull request by bishal7679**
Localizes `content/en/docs/reference/glossary/containerd.md` to Hindi `content/hi/docs/reference/glossary/containerd.md`

Fixes :- #35600
Taking ref from the PR :- #36121

### CODE REVIEW

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Review by Babapool — COMMENTED** [review]
Thanks!
/lgtm

**Comment by Babapool** [comment]
cc: @anubha-v-ardhan for approval. Thanks

**Pull request merged**
