### PR TITLE
[ja] Switch liveness image to multi-arch agnhost container image

### PR DESCRIPTION
**Pull request by spurin**
ja equivalent for https://github.com/kubernetes/website/pull/45837

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/retitle [ja] Switch liveness image to multi-arch agnhost container image

**Comment by dipesh-rawat** [comment]
/hold
Wait until the equivalent English PR https://github.com/kubernetes/website/pull/45837 has been merged first.

**Comment by spurin** [comment]
/unhold

Referenced PR https://github.com/kubernetes/website/pull/45837 has now been merged

**Comment by sftim** [comment]
LGTM

**Comment by Okabe-Junya** [comment]
Thank you!!

/cc
/lgtm
/assign nasa9084

**Pull request merged**
