### PR TITLE
[WIP] Add imported docs update to site build

### PR DESCRIPTION
**Pull request by lucperkins**
cc @zparnold

### CODE REVIEW

**Comment by lucperkins** [comment]
@zparnold One potential issue I see here is that there's already content in these various directories that gets updated by the script (rather than created by the script). This means that you can run the site locally (or look at a Netlify preview build) and see outdated versions of those docs if you don't run the script. Do you think this could be confusing for users?

**Comment by Hartmarken348** [comment]
11381

**Comment by tengqm** [comment]
Looks good.

**Comment by zparnold** [comment]
Sounds like this is good @lucperkins so if you can merge the upstream Makefile changes then we can get this in!
/remove-lifecycle stale

**Pull request closed without merging**
