### PR TITLE
Update translation in components

### PR DESCRIPTION
**Pull request by yc-zc**
This page is fallen behind. More improvements are required.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by tanjunchen** [comment]
@yc-zc Please
Thanks your jobs!!!
first: 📝 Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA. 
second:Important  see [rules](https://github.com/k8smeetup/k8s-official-translation)

**Comment by tengqm** [comment]
@yc-zc Please check your CLA status?

**Comment by markthink** [comment]
参考一下[翻译指引](https://github.com/k8smeetup/k8s-official-translation)

**Comment by yc-zc** [comment]
> @yc-zc Please check your CLA status?

Sorry, I didn't notice that I need to click the link in my email to sign the CLA, it seems the link provided had expired

**Comment by chenrui333** [comment]
@yc-zc 可以提交一个新的PR。同时需要解决一下 文件冲突的问题。

**Pull request closed without merging**
