### PR TITLE
Fix grammar in kubernetes dashboard docs

### PR DESCRIPTION
**Pull request by CodingCanuck**
Start a new sentence after a period.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/website/pull/31161#issuecomment-1003419453

**Comment by CodingCanuck** [comment]
> Please sign CLA [#31161 (comment)](https://github.com/kubernetes/website/pull/31161#issuecomment-1003419453)

Done: sorry for the delay, I had to check with my employer as to whether the individual or corporate CLA was more appropriate.

**Comment by CodingCanuck** [comment]
I signed the CNCF CLA.

**Comment by annajung** [comment]
Thank you!

/lgtm

**Review by divya-mohan0209 — APPROVED** [review]
/approve

**Pull request merged**
