### PR TITLE
[zh-cn] sync word spelling in chinese

### PR DESCRIPTION
**Pull request by lowang-bh**
rebase the change for the zh-cn version after en version is merged; see PR #41003

### CODE REVIEW

**Review by my-git9 — APPROVED** [review]
/lgtm

**Comment by my-git9** [comment]
Please commit again by the following command to trigger the checks again:

```
git commit -s --amend --no-edit
git push -f
```

**Comment by my-git9** [comment]
/rename [zh-cn] Fix: word spelling in chinese

**Comment by lowang-bh** [comment]
> Please commit again by the following command to trigger the checks again:
> 
> ```
> git commit -s --amend --no-edit
> git push -f
> ```

done

**Pull request merged**
