### PR TITLE
Placeholder KEP-4427

### PR DESCRIPTION
**Pull request by sethev**
This is a placeholder for doc updates for KEP-4427 (https://github.com/kubernetes/enhancements/issues/4427)

### CODE REVIEW

**Comment by chanieljdan** [comment]
Hi @sethev 👋 just a reminder to take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday March 12th 2024 18:00 PST. 

Thank you!

**Comment by sftim** [comment]
Hey @sethev 

This looks like it's late - would you have the time to propose the documentation updates? We need these so we can ship the feature.

**Comment by drewhagen** [comment]
👋 Hello @sethev @danwinship @thockin

 A friendly reminder that this PR needs documentation with a review complete by Doc Freeze on **_March 26th 18:00 PT_** to get this into the release. After that date, [an exception needs to be filed](https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#docs-freeze).

As a user of Kubernetes, I appreciate your contribution and the documentation to understand how to utilize your new enhancement.
 
 Thanks!

**Comment by thockin** [comment]
Ping to @sethev - deadline looming!

**Comment by drewhagen** [comment]
Just a heads up for everyone here, this KEP was just removed from the milestone.

**Comment by thockin** [comment]
Above says "March 26th 18:00 PT" - why the preemptive drop?

**Comment by thockin** [comment]
Oh, that's the drop-dead date.

**Comment by drewhagen** [comment]
/hold
@sethev Kubernetes 1.30 is releasing today.
This PR will need to be targeting the `dev-1.31` once it is available. Our team will keep you posted.

**Comment by drewhagen** [comment]
You can reopen this in the next release cycle and target `dev-1.31`. Thanks! :)

**Comment by drewhagen** [comment]
Heads up that `dev-1.31` branch is created now, if you choose to reopen this for the next release.

**Pull request closed without merging**
