### PR TITLE
Add jihoon-seo to sig-docs-ko-owners

### PR DESCRIPTION
**Pull request by jihoon-seo**
Dear folks,
I hereby open a humble PR to add myself to ko-owners.

[[Requirements](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-2)]

- [X] Reviewer of the codebase for at least 3 months
  - Became ko-reviewer [on 22 Jul 2021](https://github.com/kubernetes/website/pull/28948#issuecomment-884796537).
- [X] Primary reviewer for at least 10 substantial PRs to the codebase
  - PRs reviewed: https://github.com/kubernetes/website/pulls?q=type%3Apr+reviewed-by%3Ajihoon-seo
- [X] Reviewed or merged at least 30 PRs to the codebase
  - PRs merged: https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Amerged+author%3Ajihoon-seo
  - PRs reviewed: https://github.com/kubernetes/website/pulls?q=type%3Apr+reviewed-by%3Ajihoon-seo

And I will open a PR to make change on 
https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml soon.

PTAL! 😊

CC: @kubernetes/sig-docs-ko-owners 😊

### CODE REVIEW

**Comment by seokho-son** [comment]
As the SIG-Docs Korean l10n team lead, I am really happy with this PR !
@jihoon-seo is one of the most active contributors for Korean l10n.

**Comment by sftim** [comment]
LGTM
@seokho-son thanks for your confirmation

**Comment by sftim** [comment]
/lgtm
(also from https://github.com/kubernetes/website/pull/31206#issuecomment-1005417748)
/approve

**Comment by jihoon-seo** [comment]
@seokho-son @sftim Thank you all ! :)

**Pull request merged**
