### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by heckj**
replica/rebase of PR #7144 to work out netlify build issues...

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7416)

### CODE REVIEW

**Comment by tehut** [comment]
@heckj Thank you so much! I tried a lot of changes in the gemfile but I was certainly not going to find this awesome solution!

Would you be alright with me cherry-picking your commit to my branch or would you like to push your commit up to my remote.  I'm happy with whatever is easiest for you! Thanks again, this looks great.

**Comment by heckj** [comment]
@tehut Cherry pick away! You may have to rebase you branch on kubernetes/website ‘master’ from current for it to apply cleanly - I did that as a part of the debugging and resolution process, so it may be required to pick up the relevant updates. 

If that proves troublesome, I’ll figure out how to make a PR against your local repo to get the relevant updates nailed down

Let me know when you’ve snagged it, and I’ll close my temporary PR that I used for debugging and kill off that branch

**Comment by heckj** [comment]
I think @tehut has what she needs from this PR, so closing it down - will leave the branch for a while longer just in case.

**Pull request closed without merging**
