### PR TITLE
updating docsy theme submodule

### PR DESCRIPTION
**Pull request by Colstuwjx**
This PR is going to update docsy theme version to the latest ( [a7dc774](https://github.com/google/docsy/commit/a7dc77412c533fefc71730927350677fed35f576) ), the instructions followed [PR #23434 comment](https://github.com/kubernetes/website/pull/23434#issue-473486688).

### CODE REVIEW

**Comment by Colstuwjx** [comment]
Ping  @sftim @jimangel @kbhawkey , this PR is mainly in order to introduce [docsy print feature](https://www.docsy.dev/docs/adding-content/print/), and I'll take another PR to introduce the config change. The related context see #26808 , #26809 .

**Comment by sftim** [comment]
/area web-development
LGTM

**Comment by Colstuwjx** [comment]
Ping @kbhawkey @jimangel , could you please help me review this PR?

**Comment by kbhawkey** [comment]
👀

**Comment by kbhawkey** [comment]
Hi @Colstuwjx .
The updates look fine. The theme was updated in October.
The "print" configuration will introduce a number of changes to the site layout.
/lgtm

**Comment by kbhawkey** [comment]
The site builds with this update:
https://deploy-preview-26814--kubernetes-io-master-staging.netlify.app/
https://deploy-preview-26814--kubernetes-io-master-staging.netlify.app/blog/
https://deploy-preview-26814--kubernetes-io-master-staging.netlify.app/docs/concepts/workloads/pods/

/approve

**Comment by Colstuwjx** [comment]
image

After this PR get merged, the netlify status icon turns to "failed" :(
I'm not sure what's the root cause, netlify link: [this](https://app.netlify.com/sites/kubernetes-io-master-staging/deploys).

**Comment by Colstuwjx** [comment]
My mistake, it seems that it's staging build status 😅

**Pull request merged**
