### PR TITLE
Remove duplicated "のの" in JP NW policy doc

### PR DESCRIPTION
**Pull request by KeisukeYamashita**
Removed deplicated "のの" in th Network Policy document for Japanese.
As far as I understand, it's a typo. I would like to fix this in this PR.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
LGTM

**Comment by atoato88** [comment]
/lgtm
Nice catch! :smile:

**Comment by nasa9084** [comment]
/approve
Thank you~

**Pull request merged**
