### PR TITLE
[hi] Add content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md

### PR DESCRIPTION
**Pull request by arsheelsheikh**
localization 
`[hi] Add content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md`

### CODE REVIEW

**Comment by sftim** [comment]
@arsheelsheikh would you be willing to squash this down to 1 commit (https://kubernetes.io/docs/contribute/new-content/open-a-pr/#addressing-feedback-locally has some details, and it's OK to ask more questions too)

**Comment by arsheelsheikh** [comment]
> @arsheelsheikh would you be willing to squash this down to 1 commit (https://kubernetes.io/docs/contribute/new-content/open-a-pr/#addressing-feedback-locally has some details, and it's OK to ask more questions too)

@sftim I followed the handbook and tried squashing but it seem something is wrong!

**Comment by sftim** [comment]
This change looks reasonable, commit wise. The commit message summary “hi localization” isn't as helpful as it could be.

If you can, check out the branch you've named _arsheelsheikh_ and run `git commit --amend`. Now you can write a new commit message that more clearly summarises the change. For example:
> Localize “Guide for scheduling Windows containers in Kubernetes” into Hindi

**Review by jayesh-srivastava — CHANGES_REQUESTED** [review]
Hey, I noticed that this document contains a mixture of both `windows` and `विंडोज`. I guess we should stick to one only. Can you please take a look at other Hindi docs and make the change accordingly?

**Comment by anubha-v-ardhan** [comment]
> Hey, I noticed that this document contains a mixture of both `windows` and `विंडोज`. I guess we should stick to one only. Can you please take a look at other Hindi docs and make the change accordingly?

We're writing it as Windows, it being a trademark of Microsoft Corporation.

**Comment by jayesh-srivastava** [comment]
> > Hey, I noticed that this document contains a mixture of both `windows` and `विंडोज`. I guess we should stick to one only. Can you please take a look at other Hindi docs and make the change accordingly?
> 
> We're writing it as Windows, it being a trademark of Microsoft Corporation.

That should be it then. @arsheelsheikh can you please do the needful.

**Comment by arsheelsheikh** [comment]
All these PR mails were sent to the spam folder due to which I missed track on this PR, just checked now

**Comment by arsheelsheikh** [comment]
should I be making fresh PR now?

**Comment by sftim** [comment]
You can update this PR @arsheelsheikh; you don't need to make a new one.

**Comment by Sea-n** [comment]
Hey @arsheelsheikh, of course you can (and you should) update this PR instead of open a new one.

But before we move on, you have to sign CLA so that the check can be pass.
/easycla

**Comment by divya-mohan0209** [comment]
Hey @arsheelsheikh , you can make changes on this PR itself OR open a fresh PR whichever is comfortable for you. Could you please do it at the earliest possible since this has been pending for ~ 1 month now?

**Comment by Sea-n** [comment]
Hey @sean,

Thanks for purposing this PR. But since you didn't respond for a while, we have to close this PR now.
/close

Feel free to open a fresh one (and don't forget to mention this PR) when you are ready to move forward.

**Pull request closed without merging**
