### PR TITLE
Fix typos and grammatical errors in README.md file

### PR DESCRIPTION
**Pull request by Chiranjivee**
Summary:

Fixed grammatical errors.
Fixed spelling mistakes.

### CODE REVIEW

**Comment by Chiranjivee** [comment]
I signed it

**Comment by Chiranjivee** [comment]
I signed it

**Comment by Rajakavitha1** [comment]
@Chiranjivee thanks for your PR. Please take a look at some of the suggestions I made.

**Comment by tengqm** [comment]
what are the contributions in this PR?

**Comment by Chiranjivee** [comment]
@tengqm fixed spelling mistakes and grammatical errors.

**Comment by Chiranjivee** [comment]
@Rajakavitha1 I am not able to find your suggestions.

**Comment by Rajakavitha1** [comment]
> @tengqm fixed spelling mistakes and grammatical errors.

@Chiranjivee there are no spelling mistakes. The fix you made are better wording (site to website) :)

**Pull request merged**
