### PR TITLE
Update basic-stateful-set.md

### PR DESCRIPTION
**Pull request by whatthefrog**
Cascading Delete: fixup mixup in delete commands

Not 100% sure, if paragraphs (the diff in this PR) or if actual commands and their output should be swapped.

Thanks for the nice tutorials.

### CODE REVIEW

**Comment by whatthefrog** [comment]
I did the `cla/linuxfoundation — whatthefrog needs CLA` I believe

**Comment by sftim** [comment]
This cleanup
/lgtm

Thanks @whatthefrog

**Pull request merged**
