### PR TITLE
Remove link to empty list for k8s metrics

### PR DESCRIPTION
**Pull request by tengqm**
closes: #22624

### CODE REVIEW

**Comment by sftim** [comment]
Change LGTM

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-25778--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/system-metrics/

**Comment by kbhawkey** [comment]
Thanks @tengqm .
/approve

**Pull request merged**
