### PR TITLE
promote AWS-NLB Support from alpha to beta

### PR DESCRIPTION
**Pull request by M00nF1sh**
Promote AWS-NLB support from alpha to beta

Note:
This is just for updating the AWS-NLB feature status.
There should be future PR to enhance the doc structure. e.g. SSL support is available on both NLB & CLB, we should reorganize it to make it cleaner.

### CODE REVIEW

**Comment by MAKOSCAFEE** [comment]
> There should be future PR to enhance the doc structure. e.g. SSL support is available on both NLB & CLB, we should reorganize it to make it cleaner.

Hi, @M00nF1sh sorry! when you say future PR, are those enhancements intended to be merged in this release cycle?

**Comment by M00nF1sh** [comment]
@makoscafee 
Sorry for the late reply. only this one is intended to be merged in this release cycle.

**Comment by makoscafee** [comment]
Hi @M00nF1sh , @DanyC97 can this be approved at the state it is right now? We are looking to have all PR for release 1.15 merged by June 10th. Let me know if there is anything we can assist.

**Pull request merged**
