### PR TITLE
Official 1.17 Release Docs

### PR DESCRIPTION
**Pull request by daminisatya**
🛑 DO NOT MERGE 🛑 UNTIL KUBERNETES 1.17 IS RELEASED
----------------
Target Date: 2019-12-09

Release Deadline
---------

Date | Description
-- | --
NOV 8 | Open placeholder PRs
NOV 15 | PRs ready for review
NOV 22 | All PRs reviewed and ready to merge

More information
-------
contact: @daminisatya @irvifa @VineethReddy02 @pgburt

### CODE REVIEW

**Comment by irvifa** [comment]
@daminisatya check is failing 🤔

**Comment by zacharysarah** [comment]
@daminisatya It looks like there's a failed CLA check that's breaking the PR. The last successful build was on October 26: https://github.com/kubernetes/website/pull/17065#commits-pushed-cce1b12, which is also where it started failing. Maybe start by looking at the PRs in that commit?

I'm curious how an unsigned commit was merged into the release branch in the first place. 🤔 The relevant PR should have failed its checks...

**Comment by kbhawkey** [comment]
@daminisatya , How about:
https://github.com/kubernetes/website/pull/17065/commits/4442fd0533a2c078d8edaff7276b3f5cc2c329ec

**Comment by irvifa** [comment]
This pr looks good https://github.com/kubernetes/website/commit/4442fd0533a2c078d8edaff7276b3f5cc2c329ec no sign of cla error as well, hmm

**Comment by kbhawkey** [comment]
> 
> 
> This pr looks good [4442fd0](https://github.com/kubernetes/website/commit/4442fd0533a2c078d8edaff7276b3f5cc2c329ec) no sign of cla error as well, hmm

Not sure exactly what is going on, but this commit could be reverted?

**Comment by irvifa** [comment]
Is it save to do that? I’m not sure reverting it will fix the subsequent cla check error 🤔

**Comment by mrbobbytables** [comment]
@guineveresaenger logged a ticket with the LF cla team to give us some more information. It might not be that specific commit that is the problem.

**Comment by guineveresaenger** [comment]
Heather from the LF sent me the following:
```
There is at least one user who's commit is not properly linked to their github profile. From what I can see, it is https://github.com/kubernetes/website/pull/17065/commits/4442fd0533a2c078d8edaff7276b3f5cc2c329ec

The cla error in that commit links to the page https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user 

Kevin will need to follow the steps in that github guide to get his commit properly authored before the tool will let him pass.
```

@kevtaylor - any chance this is you? Sorry for the trouble!

**Comment by kbhawkey** [comment]
> 
> 
> Heather from the LF sent me the following:
> 
> > There is at least one user who's commit is not properly linked to their github profile.
> > From what I can see, it is
> > [4442fd0](https://github.com/kubernetes/website/commit/4442fd0533a2c078d8edaff7276b3f5cc2c329ec)
> 
> > The cla error in that commit links to the page
> > https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user
> 
> > Kevin will need to follow the steps in that github guide to get his commit
> > properly authored before the tool will let him pass.
> 
> @kevtaylor - any chance this is you? Sorry for the trouble!


Right. I noticed two email accounts. Perhaps one user/email account was used for the original commit in the PR and then another user/email account was used when rebasing this PR before merging?

**Comment by guineveresaenger** [comment]
@kbhawkey - the different email would do it if only one is cla signed.

**Comment by kevtaylor** [comment]
@guineveresaenger I changed my CLA email since that original commit

**Comment by VineethReddy02** [comment]
@kbhawkey @kbhawkey Maybe the easiest way to solve this is to sign the CLA with the other email as well.

**Comment by irvifa** [comment]
I agree with @VineethReddy02 after that let’s try to run cla check again..

**Comment by kbhawkey** [comment]
> 
> 
> @kevtaylor @kbhawkey Maybe the easiest way to solve this is to sign the CLA with the other email as well.

Hi! Since the changes are minimal (and could easily be created again), how about reverting or removing the original commit? Or is there an easier way?

**Comment by VineethReddy02** [comment]
@kbhawkey but signing the CLA would be the easiest. If that doesn't work we can revert and add the changes again.

**Comment by irvifa** [comment]
https://help.github.com/en/github/using-git/changing-author-info
Are we allowed to do this?

**Comment by kevtaylor** [comment]
@kbhawkey I cant resign with the original email because it is no longer visible to me.

**Comment by mrbobbytables** [comment]
> @kbhawkey I cant resign with the original email because it is no longer visible to me.

Looks like we'll need to revert the commit and add the changes as a new one.

**Comment by daminisatya** [comment]
Yes! Let me revert the commit. 

Commit hash - 4442fd0533a2c078d8edaff7276b3f5cc2c329ec

**Comment by mrbobbytables** [comment]
I think the PR will actually need to be rebased away instead of reverted (my bad), the revert still leaves the commit in place but undoes the changes.

**Comment by kbhawkey** [comment]
> 
> 
> I think the PR will actually need to be rebased away instead of reverted (my bad), the revert still leaves the commit in place but undoes the changes.

Yes, agreed.

**Comment by daminisatya** [comment]
I tried to rebase, and remove just 4442fd0 from the log. 

However, It is getting more complicated with many more conflicts coming in. Is there any other way to resolve this?

**Comment by guineveresaenger** [comment]
@daminisatya - I'm happy to get on a zoom chat with you if you like!

**Comment by kbhawkey** [comment]
Let me know if I can do something

**Comment by irvifa** [comment]
@jimangel is this already merged to master?

**Comment by mrbobbytables** [comment]
@irvifa we closed this PR to do some work to fix up the dev-1.17 branch. A new PR should be opened to replace it. 👍

**Pull request closed without merging**
