### PR TITLE
kubeadm: add new command line reference 

### PR DESCRIPTION
**Pull request by neolit123**
Add:
- placeholder files
- include place holder files
- add missing tabs for "alpha phase kubelet"

ref: https://github.com/kubernetes/kubeadm/blob/master/docs/updating-command-reference.md

/assign @Bradamant3 @fabriziopandini 
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Comment by neolit123** [comment]
/hold
@fabriziopandini 
either the placeholder file was not generated in `k/k` or i might have missed it. will double check on monday. thanks.

**Comment by fabriziopandini** [comment]
@neolit123 thanks!
LGTM to me
Are there something else missing or we can lift hold on this issue?

**Comment by neolit123** [comment]
@fabriziopandini 
>Are there something else missing or we can lift hold on this issue?

i don't see any other commands and i don't think we are going to add more before 1.12.

**Comment by neolit123** [comment]
@zacharysarah 

from slack:
> Do you mind if I play with `/retest` in this PR?
please, go ahead.

/assign @zacharysarah

**Comment by zacharysarah** [comment]
Performed with @neolit123's [permission](https://kubernetes.slack.com/archives/C1J0BPD2M/p1537233740000100?thread_ts=1537224334.000100&cid=C1J0BPD2M):

/retest

**Comment by neolit123** [comment]
i think we are missing a command in this PR.
double checking...

**Comment by neolit123** [comment]
@fabriziopandini 
missing command:
https://github.com/kubernetes/kubernetes/pull/68808

**Comment by neolit123** [comment]
i will update this PR later today as kubernetes/kubernetes#68808 is being merged.

**Comment by timothysc** [comment]
It's merged - round 2.

**Comment by neolit123** [comment]
ack, updating in a bit.

**Comment by zparnold** [comment]
Hi @neolit123, Could you please help me understand what the files have the line`This file is autogenerated ` are for? I don't think we're doing autogenerated docs just yet.

**Comment by neolit123** [comment]
@zparnold 
it was agreed with @Bradamant3 and @tengqm in the 1.11 cycle to include placeholder generated docs, in cases we are adding new commands, so that the preview does not have errors.

**Pull request merged**
