### PR TITLE
Add Extension to Glossary page

### PR DESCRIPTION
**Pull request by daminisatya**
#5993 

Added "Extension" in Kubernetes to Glossary terms. Please review.

### CODE REVIEW

**Comment by daminisatya** [comment]
/assign @cody-clark 
/assign @neolit123 

Please review!

**Comment by Rajakavitha1** [comment]
@daminisatya Thanks for the update. A minor suggestion: Extensions are software components that extend and deeply integrate with Kubernetes to support new types and new kinds of hardware.

**Comment by cody-clark** [comment]
Thanks so much for growing our glossary, @daminisatya!

Preview: https://deploy-preview-12470--kubernetes-io-master-staging.netlify.com/docs/reference/glossary/?all=true#term-Extensions

/approve

**Pull request merged**
