### PR TITLE
Remove deprecated Kubernetes on Mesos docs

### PR DESCRIPTION
**Pull request by rimusz**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.9 Features: set Milestone to `1.9` and Base Branch to `release-1.9`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: Please check the “Allow edits from maintainers” box (see image below) to
> [allow reviewers to fix problems](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) on your patch and speed up the review process.
>
> Please delete this note before submitting the pull request.
>
> NOTE: After opening the PR, please *un-check and re-check* the "Allow edits from maintainers" box. This is a temporary workaround to address a known issue with GitHub.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6668)

### CODE REVIEW

**Comment by heckj** [comment]
@jdef @karlkfi  - could you verify that this content is deprecated please?

**Comment by heckj** [comment]
@rimusz there are references to this page in `docs/setup/pick-right-solution.md` and `_data/setup.yml` - could you please remove/update those references with this deletion so we don't have broken links?

Also, is there a redirect location that would be relevant for people trying to find this page from external (i.e. search results) links?

**Comment by jdef** [comment]
yes, k8s-mesos has been "retired": https://github.com/kubernetes-retired/kube-mesos-framework

**Pull request merged**
