### PR TITLE
[ja] revert an incorrect fix in mysql-configmap.yaml

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/33633/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Comment by Sea-n** [comment]
It's not fully sync.
```diff
--- content/ja/examples/application/mysql/mysql-configmap.yaml	2022-06-12 09:02:26.982072931 +0800
+++ content/en/examples/application/mysql/mysql-configmap.yaml	2022-06-22 17:32:57.066612527 +0800
@@ -1,18 +1,17 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: mysql
   labels:
     app: mysql
+    app.kubernetes.io/name: mysql
 data:
   primary.cnf: |
     # Apply this config only on the primary.
     [mysqld]
     log-bin
-    datadir=/var/lib/mysql/mysql
   replica.cnf: |
     # Apply this config only on replicas.
     [mysqld]
     super-read-only
-    datadir=/var/lib/mysql/mysql
```

**Comment by Arhell** [comment]
> It's not fully sync.
> 
> ```diff
> --- content/ja/examples/application/mysql/mysql-configmap.yaml	2022-06-12 09:02:26.982072931 +0800
> +++ content/en/examples/application/mysql/mysql-configmap.yaml	2022-06-22 17:32:57.066612527 +0800
> @@ -1,18 +1,17 @@
>  apiVersion: v1
>  kind: ConfigMap
>  metadata:
>    name: mysql
>    labels:
>      app: mysql
> +    app.kubernetes.io/name: mysql
>  data:
>    primary.cnf: |
>      # Apply this config only on the primary.
>      [mysqld]
>      log-bin
> -    datadir=/var/lib/mysql/mysql
>    replica.cnf: |
>      # Apply this config only on replicas.
>      [mysqld]
>      super-read-only
> -    datadir=/var/lib/mysql/mysql
> ```

Done

**Comment by atoato88** [comment]
/lgtm

Adding `app.kubernetes.io/name: mysql` on labels is a part of this [PR](https://github.com/kubernetes/website/pull/33791).
It is needed to create PR update [other files](https://github.com/kubernetes/website/tree/main/content/ja/examples/application/mysql) to include `app.kubernetes.io/name: mysql` after merging this PR, I think.

**Pull request merged**
