### PR TITLE
[bn] Add entries into static/_redirects for Bengali localization

### PR DESCRIPTION
**Pull request by Acesif**
Signed-off-by: Asif Zubayer Palak asifpalak@gmail.com
Adds entries to `static/_redirects` for Bengali localization
This is an initial PR as may need some improvements!
Tracking issue: #31677

### CODE REVIEW

**Review by mitul3737 — APPROVED** [review]

**Comment by seokho-son** [comment]
I guess adding redirect for individual documents is not mandatory. But if there is a broken link in localized documents, we'd better add a redirect. As an initial stage, adding /bn/docs/home/ seems enough.

**Comment by seokho-son** [comment]
Hi @natalisucks 
This PR needs an approval from sig-docs-en-owners. PTAL :)

**Comment by mitul3737** [comment]
Hi @natalisucks
This PR needs an approval from sig-docs-en-owners. PTAL :)
Moreover, the previous approval was stuck due to the release of the 1.27 version ( #40601 )

**Pull request merged**
