### PR TITLE
Improvement for k8s.io/docs/concepts/overview/

### PR DESCRIPTION
**Pull request by pegasas**
user clarifies that the overview can not summarize what problem Kubernetes aims to resolve. 
After reading materials, combined with my deployment experiences and comments from @thisisharrsh and @sftim.

### CODE REVIEW

**Comment by pegasas** [comment]
try to resolve https://github.com/kubernetes/website/issues/42644

**Comment by sftim** [comment]
It's obvious to me that this pull request does not include the [suggested change](https://github.com/kubernetes/website/issues/42644#issuecomment-1685398118) from #42644.

Would you be willing to reivise this pull request to cover what I suggested was needed, @pegasas?

**Comment by pegasas** [comment]
> 对我来说很明显，这个拉取请求不包括#42644中[建议的更改](https://github.com/kubernetes/website/issues/42644#issuecomment-1685398118)。[](https://github.com/kubernetes/website/issues/42644)
> 
> 您是否愿意重新修改此拉取请求以涵盖我建议的需求，@pegasas？

Sure. @sftim .

I will close this PR and re create an new one. 
I have a few that needs to confirm with you to make sure we are on the same page.

> How I recommend fixing this: add new content at the start of https://k8s.io/docs/concepts/overview/ (before “Going back in time”)
> 
> The new content should aim to answer the questions that @theking2 didn't see answers to.
> 

I have 2 options:

- Add a new paragraph to explains deeper about kubernetes.
- Modify current paragraph to highlights some key points in kubernetes design

Which one do you prefer?

> /priority backlog /triage accepted
> 
> If working on this, consider setting a custom `linkTitle` for that page as well.

What is custom `linkTitle` stands for? 

- Refer this paragraph from other paragraph in this page.
- Refer some paragraph in this page to explains this question.
- Others

Would you minds to give more hints about it?

**Comment by tengqm** [comment]
I don't think this is adding much value to the existing text.
Feel free to reopen if there are different opinions.
/close

**Pull request closed without merging**
