### PR TITLE
[WIP] Add support to dark mode

### PR DESCRIPTION
**Pull request by tengqm**
closes: #25061

Almost working ... 

Just not sure whether we want to tweak the PRE and/or CODE tags as well.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
It looks like we're trying to build our own mechanism to decide which color scheme the user prefers.

I'd expect to see this done with [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) and then, **optionally**, build on that by adding an in-page UI element to override the user agent's preference.

**Comment by tengqm** [comment]
> It looks like we're trying to build our own mechanism to decide which color scheme the user prefers.

That is not true. This PR aims at providing the support to dark mode with minimal new code. There are two files related to the so called "colore scheme":

- File 'assets/scss/_sidebar-tree.scss' is copied from the docsy theme for overriding. The hard-coded color (e.g. `$gray-700`) is not suitable for dark mode. The sidebar tree becomes invisible if we don't change it. This PR changes it to `$gray-500`.
- File `static/css/dark-mode.css` introduces only 4 color changes and those 4 are the core color toggling proposed in this PR.

I believe what the users want is just a readable dark mode. It is not about a full-fledged color scheme. If you dive into the many style customization we have today (1. bootstrap; 2. docsy; 3. custom scss; 4. custom css), you will realize that devising a color scheme on top of it is impractical.

**Comment by sftim** [comment]
In the preview, I see an in-page control for choosing the color mode. I'd strongly prefer to make that control act as an _override_ for the standardized mechanism (`prefers-color-scheme`). I don't think we should make our own.

Either way, the issue _is_ about providing a readable “dark mode”. When a visitor sets their browser to `prefers-color-scheme: dark` (as opposed to the default which is `prefers-color-scheme: light`), let's honor that. It's likely to play well with any upstream enhancement to support the same mechanism. If we then want to add a control let users override their browser-specified preference, even better.

**Comment by tengqm** [comment]
@sftim So your primary concern is about the initial default, right? If the user has chosen dark mode as default for his/her operating system/browser, we should use that as the default.
Other than this, providing a toggle button to override the "default" is okay?

Let me check how to script that.

**Comment by sftim** [comment]
https://stuffandnonsense.co.uk/blog/redesigning-your-product-and-website-for-dark-mode explains how to write CSS (or Sass) that takes end-user preferences for dark vs. light mode into account.

I would literally do this with 2 commits: the first adding support for honoring the user preference, and the second adds overrides via JavaScript (for people with old browsers or who aren't sure how to set that preference).

Ideally, the 2nd commit is quite small because the 1st commit has anticipated this need and has used mechanisms such as [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) to make that easier.

**Comment by ntindle** [comment]
This PR isn't perfect, but I want to thank you @tengqm  as I've been using the netlify preview of this for docs reference to keep my eyes sane. Great job on this, can't wait to see you finish and get this merged.

**Comment by Wittionary** [comment]
Hey @tengqm , thanks for your work on this so far! Are you still working on the `prefers-color-scheme` portion?

**Comment by tengqm** [comment]
> Hey @tengqm , thanks for your work on this so far! Are you still working on the `prefers-color-scheme` portion?

No. No cycle to look into that yet.

**Pull request closed without merging**
