### PR TITLE
Update kubespray.md

### PR DESCRIPTION
**Pull request by Grootesque**
Grammar

### CODE REVIEW

**Comment by jimangel** [comment]
Hey there! @Grootesque, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by divya-mohan0209** [comment]
Hello @Grootesque , thank you for your contribution! Could you please sign the CLA so that we can review your PR?

**Review by chrisnegus — COMMENTED** [review]
/lgtm

**Review by divya-mohan0209 — APPROVED** [review]
Approved since this is a typo.

**Pull request merged**
