### PR TITLE
[ko] Update list of versions to match English

### PR DESCRIPTION
**Pull request by AbdelatifAitBara**
Align https://kubernetes.io/ko/docs/home/supported-doc-versions/ with https://kubernetes.io/docs/home/supported-doc-versions/

[Preview ](https://deploy-preview-46353--kubernetes-io-main-staging.netlify.app/ko/docs/home/supported-doc-versions/)of the updated page.

/language ko

### CODE REVIEW

**Comment by sftim** [comment]
LGTM

**Review by ricardoamaro — APPROVED** [review]
/lgtm

**Comment by seokho-son** [comment]
Thanks

/approve

**Review by ydFu — APPROVED** [review]
/lgtm

**Pull request merged**
