### PR TITLE
[ko] replaced {{< codenew ... >}} with {{% codenew ... %}}

### PR DESCRIPTION
**Pull request by andreygoran**
This is a continuation of PR https://github.com/kubernetes/website/pull/42180 (Replace {{< codenew ... >}} with {{% codenew ... %}})
Fixes https://github.com/kubernetes/website/issues/42179 (Copy To Clipboard breaks YAML format)

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@andreygoran Thank you for your work! This is a crucial fix.

But in [preview](https://deploy-preview-42278--k8s-dev-ko.netlify.app/ko/docs/tasks/access-application-cluster/ingress-minikube/#인그레스-생성하기), when I click the "Copy to clipboard" button and paste to somewhere else, it still has extra indentations.

```yaml
apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: example-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
  spec:
    rules:
      - host: hello-world.info
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: web
                  port:
                    number: 8080
```

Will this happen only in preview, and work without error after merged?
PTAL!

**Comment by andreygoran** [comment]
@jihoon-seo Good catch!
There was a space missing https://github.com/kubernetes/website/pull/42278/commits/2c642fbb6326f6425ec8893b2f3ec9db5f619df5#diff-d7f597eddda809e004b40949631437cac0d469a3a3f124dc9dcd58f5299fc39cL155

It looks good now in [preview](https://deploy-preview-42278--k8s-dev-ko.netlify.app/ko/docs/tasks/access-application-cluster/ingress-minikube/#%EC%9D%B8%EA%B7%B8%EB%A0%88%EC%8A%A4-%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0).

**Comment by jihoon-seo** [comment]
@andreygoran Thank you so much!
/approve
(Leaving `/lgtm` for someone other than me)

**Pull request merged**
