### PR TITLE
Kubernetes basic github deadlink

### PR DESCRIPTION
**Pull request by MasayaAoyama**
NG: https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics
OK: https://github.com/kubernetes/website/tree/master/content/en/docs/tutorials/kubernetes-basics

For example, this page contain dead link.
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

Note:
China page don't have this link.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.11 Features: set Milestone to 1.11 and Base Branch to release-1.11
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by MasayaAoyama** [comment]
Hello bradtopol.
Please approve :)
I have already checked my changes at deployed staging now.
https://deploy-preview-8738--kubernetes-io-master-staging.netlify.com/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

NG page now: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

/assign @ bradtopol

**Comment by MasayaAoyama** [comment]
I heard from mistyhacks, HUGO migration is checked by you.
Thank you for your help!

/assign @steveperry-53
/assign @Bradamant3

**Comment by Bradamant3** [comment]
Duplicate of #8616 which is already merged. So closing unmerged. Sorry, @MasayaAoyama but we can't always get to PRs fast enough to avoid this situation. Your link fixes are great!

**Pull request closed without merging**
