### PR TITLE
Update page weights in API Access Control reference section

### PR DESCRIPTION
**Pull request by a-mccarthy**
contributes to https://github.com/kubernetes/website/issues/35093
@reylejano @natalisucks @bradtopol

Updating section to have distinct page weight. (these do not appear to be auto-generated pages in the reference section)

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Update page weights in API Access Control reference section

**Review by ydFu — APPROVED** [review]
/lgtm

**Comment by nate-double-u** [comment]
Hi @a-mccarthy, looks like the deploy preview failed. Sometimes making an empty commit will kick Netlify and make it retry.

**Pull request merged**
