### PR TITLE
API reference generated for v1.31

### PR DESCRIPTION
**Pull request by tengqm**
This is based on #47661 
closes: #47635

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!

_(Also, needs an additional approval required from _`sig-docs-website-owner`_)_

/approve

**Comment by Andygol** [comment]
image
Do I understand correctly that something happened here that was not expected? Instead of deleting the strings, they were replaced with placeholders. Or something has broken and the strings have not been injected. Here and in other places.

**Pull request merged**
