### PR TITLE
Add CEL Playground link

### PR DESCRIPTION
**Pull request by matheusfm**
Hi there,

I'm proposing some changes that include adding a link to the [CEL Playground](https://playcel.undistro.io) in the following sections:

- https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/
- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

As discussed in [this GitHub issue](https://github.com/kubernetes/website/issues/41788), CEL Playground allows users to easily test expressions from their browsers and also provides some helpful examples.

Additionally, it's worth noting that all [Kubernetes CEL libraries](https://kubernetes.io/docs/reference/using-api/cel/#kubernetes-cel-libraries) are available in the playground.

Feel free to join us in improving the CEL Playground. Your contributions are welcome!

Please review these suggestions, and let me know if any further adjustments are needed.

Thank you!

Closes https://github.com/kubernetes/website/issues/41788

### CODE REVIEW

**Comment by jpbetz** [comment]
/approve

These are the most prominent uses of CEL, so this seems appropriate.

**Comment by jpbetz** [comment]
/lgtm
For technical content

**Review by sftim — COMMENTED** [review]
/approve

The external link feels like a valid exception to https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content

**Pull request merged**
