### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by PhilRW**
Link to Xilinx device plugin was incorrect.

### CODE REVIEW

**Comment by sftim** [comment]
Hi @PhilRW 

If you are willing to sign the CLA, and can do that (online), we can review this pull request.

**Comment by PhilRW** [comment]
Hi there,
I'm doing this work through my work, and it seems we are a signatory. I'm wondering how to have my GitHub account recognized.

**Comment by sftim** [comment]
Does https://github.com/kubernetes/community/blob/master/CLA.md give you enough of a clue @PhilRW? You might need to adjust your affiliation via [cncf/gitdm](https://github.com/cncf/gitdm#readme).

**Comment by PhilRW** [comment]
...Still figuring out why my employer says we're on the list but gitdm does not....

**Comment by jimangel** [comment]
:wave: @PhilRW please sign the CLA. It's possible the commit has a different email address than you registered with. You can check with `git --no-pager show -s --format='%an <%ae>' COMMIT HASH`

Once reviewed you may need to [change author info](https://help.github.com/en/github/using-git/changing-author-info) and force push.

**Comment by PhilRW** [comment]
My company did sign the CLA but we're not in gitdm yet.

**Comment by jimangel** [comment]
@PhilRW sorry that the CLA is causing grief. Given the length this PR has gone unresolved I'm going to close it. Feel free to reopen it once the CLA is signed or reach out if we can help! Thanks!

/close

**Pull request closed without merging**
