### PR TITLE
[ja] Translate `content/en/docs/reference/glossary/admission-controller.md` into Japanese

### LINKED ISSUE #44542: [ja] Translate `content/en/docs/reference/glossary/admission-controller.md` into Japanese
**This is a Feature Request**

Translate https://kubernetes.io/docs/reference/glossary/?all=true#term-admission-controller

**Why is this needed**

The page has no Japanese translation.

**Comments**

### PR DESCRIPTION
**Pull request by Okabe-Junya**
close #44542

## Change List

- translate `content/en/docs/reference/glossary/admission-controller.md` into Japanese

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
The target page on the deploy preview:

- https://deploy-preview-44544--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?all=true#term-admission-controller

**Comment by t-inu** [comment]
This file has already translated in #43641.
If you don't mind, I'll adopt that PR this time.
However, you created an issue first, so your working procedure is correct.

**Comment by Okabe-Junya** [comment]
Thank you. I searched from the issue, so I couldn't confirm if there was any duplication (perhaps I should have checked the PRs as well).

> If you don't mind, I'll adopt that PR this time.

Of course. Not a problem for me. Please adopt #43641  (and if this PR is no longer needed, feel free to close it, or I can close it myself).

---

ありがとうございます。PRまで気を回せれば良かったのですが、issueしか把握できていませんでした（以後気をつけます）

> If you don't mind, I'll adopt that PR this time.

とありましたが、全く問題ないので、もちろん #43641 の方を採用していただいて大丈夫です🙆‍♂️ （不要であればこのPRを閉じてもらって大丈夫です。あるいは後ほど自分で閉じます）

**Comment by t-inu** [comment]
Thank you for your comment. I'll close it now.
コメントありがとうございます。ではクローズしますね。
/close

**Pull request closed without merging**
