### PR TITLE
fix-up 404 urls

### PR DESCRIPTION
**Pull request by Aresforchina**
fix some 404 urls
ref:#17649
@Rajakavitha1

### CODE REVIEW

**Comment by sftim** [comment]
@Aresforchina would you be willing to squash these commits via a rebase? See https://kubernetes.io/docs/contribute/intermediate/#work-on-the-local-repository for tips.

**Comment by tanjunchen** [comment]
/cc
@tengqm

**Comment by Aresforchina** [comment]
@sftim  I'll do that. Thank you

**Pull request merged**
