### PR TITLE
Changed go doc url to new url

### PR DESCRIPTION
**Pull request by RayAsh37**
Changed instances Go Doc URL from https://godoc.org/ to https://pkg.go.dev/ as requested in the issue #31318 
Is this the expected result?

Any feedback and suggestions/criticism are very much welcome/appreciated.

### CODE REVIEW

**Comment by RayAsh37** [comment]
@inductor was this what u meant? This PR consists of only english docs updated

**Comment by inductor** [comment]
@RayAsh37 You did not create the issue before creating a PR so I believe my PR shall be merged unless you have any objection.

**Comment by RayAsh37** [comment]
Nope, no objections, you go ahead with yours :)

**Comment by jihoon-seo** [comment]
/remove-language de fr id ja ko pt ru zh

**Pull request closed without merging**
