### PR TITLE
Fix Broken Link to CustomResourceDefinition

### LINKED ISSUE #36715: Broken Link in Versions in CustomResourceDefinitions Page
The link to CustomResourceDefinitions is broken. Rather it should point to  [CustomResourceDefinitions](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#customresourcedefinition-v1-apiextensions-k8s-io)

> This page explains how to add versioning information to [CustomResourceDefinitions](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#customresourcedefinition-v1beta1-apiextensions),

### PR DESCRIPTION
**Pull request by akankshakumari393**
This PR fixes broken link to CustomResourceDefinition on [Versions in CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/) Page

Fixes #36715

### CODE REVIEW

**Comment by Rishit-dagli** [comment]
Misleading labels

/remove-language ja
/remove-language zh

**Comment by sftim** [comment]
Thanks

/approve

**Comment by windsonsea** [comment]
The preview looks good.

https://deploy-preview-36716--kubernetes-io-main-staging.netlify.app/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

/lgtm

**Pull request merged**
