### PR TITLE
add back the link to stable metrics list

### PR DESCRIPTION
**Pull request by logicalhan**
... since we have stable metrics now.

/sig instrumentation
/cc @ehashman @sftim 

ref: https://github.com/kubernetes/website/issues/24915

### CODE REVIEW

**Comment by sftim** [comment]
@logicalhan this should really be a reference page, eg a table inside https://docs.k8s.io/reference/

Here's the thing - now that the feature is stable, we set a higher bar for documentation quality.

I think it'd be OK to put a Markdown table or similar into a document on the website, and add a YAML comment into https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/testdata/stable-metrics-list.yaml to mention that you must also update the documentation. If we see a lot of changes there, we can look at automating the process of documenting it.

How does that sound?

**Comment by sftim** [comment]
Oh, one more thing. When we have stable metrics, should we document _which component_ you scrape to get that stable metric back?

**Comment by logicalhan** [comment]
> @logicalhan this should really be a reference page, eg a table inside https://docs.k8s.io/reference/
> 
> Here's the thing - now that the feature is stable, we set a higher bar for documentation quality.
> 
> I think it'd be OK to put a Markdown table or similar into a document on the website, and add a YAML comment into https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/testdata/stable-metrics-list.yaml to mention that you must also update the documentation. If we see a lot of changes there, we can look at automating the process of documenting it.
> 
> How does that sound?

I think we should probably do both. The 'canonical' list (which is linked here) is not prone to documentation rot, so any additional documentation should be accompanied with a link to the canonical list. Feel free to assign me to an issue for the additional documentation, I'll be thinking of a way to automate the generation of it in the meantime.

> Oh, one more thing. When we have stable metrics, should we document _which component_ you scrape to get that stable metric back?

Component names are prefixes on the metric names.

**Comment by sftim** [comment]
As this was prior to the v1.21 release, would you mind rebasing it @logicalhan?

It's not vital but it means the preview will be more current (Netlify doesn't keep previews in sync with the merge target).

**Comment by logicalhan** [comment]
> As this was prior to the v1.21 release, would you mind rebasing it @logicalhan?

I'm sorry but I'm a bit confused.. rebasing to what?

**Comment by logicalhan** [comment]
@sftim dev-1.21?

**Comment by sftim** [comment]
Ah sorry - could you rebase it against the current _master_ branch?

**Comment by logicalhan** [comment]
@sftim done.

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-27421--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/system-metrics/#what-s-next

**Comment by kbhawkey** [comment]
👋 @logicalhan , Would you log a new issue about creating reference content for the stable metrics?
I agree with @sftim 's suggestion to create a table or other content in the reference section.

/approve

Hold, create new issue to follow-up on link update.
/hold

**Comment by kbhawkey** [comment]
Hi. I created a follow-on issue: https://github.com/kubernetes/website/issues/27682.
Thanks @logicalhan .
/hold cancel

**Pull request merged**
