### PR TITLE
blog: followup to PR 36971 to add suggestions to third party security audit blog

### PR DESCRIPTION
**Pull request by reylejano**
This PR is a followup to PR https://github.com/kubernetes/website/pull/36971 to add suggestions
/area blog
/kind cleanup

Preview: https://deploy-preview-37156--kubernetes-io-main-staging.netlify.app/blog/2022/10/05/current-state-2019-third-party-audit/

### CODE REVIEW

**Comment by PushkarJ** [comment]
Thanks @reylejano you saved me some precious time with your quick action!

/lgtm

**Comment by reylejano** [comment]
assign @kubernetes/sig-docs-blog-owners

**Comment by nate-double-u** [comment]
Looks good, thanks @reylejano 
/approve

**Comment by sftim** [comment]
Nice work, all.

**Pull request merged**
