### PR TITLE
fix broken field on the main page in the video block

### PR DESCRIPTION
**Pull request by Arhell**
issue #22592
old PR #19837

### CODE REVIEW

**Comment by Arhell** [comment]
review page https://deploy-preview-22595--kubernetes-io-master-staging.netlify.app/

**Comment by Arhell** [comment]
I also removed 1-br so that there would be no more indentation

**Comment by sftim** [comment]
@arhell, it makes it easier for reviewers if the PR description explains what you are fixing and how to check that the PR addresses that.

(If you only include links to the issue you are adding work for reviewers to go and work that out).

**Comment by Arhell** [comment]
> @Arhell, it makes it easier for reviewers if the PR description explains what you are fixing and how to check that the PR addresses that.
> 
> (If you only include links to the issue you are adding work for reviewers to go and work that out).

Thanks, I'll keep it in mind

**Comment by Arhell** [comment]
before fix

In another language, the block went to another line
issue #22592

after fix

now everything is in one line, I also removed 1-n br to remove a large indent, so far only for the English version

**Comment by Arhell** [comment]
wish `br`  example https://deploy-preview-22595--kubernetes-io-master-staging.netlify.app/ru/
no `br` https://deploy-preview-22595--kubernetes-io-master-staging.netlify.app/
removed to reduce indentation, as I wrote above so far only for the English version

**Comment by Arhell** [comment]
/assign @sftim done
described the problem and fix for it

**Comment by zacharysarah** [comment]
Looks like it's headed in the right direction. Leaving `/lgtm` to @sftim or another reviewer.

/hold
/approve

**Pull request merged**
