### PR TITLE
Fix #17014  - Update k8s version info for etcd encryption feature in securing-a-clu…

### LINKED ISSUE #17014: Review “Securing a cluster”
**Page to review**

**What would you like to be added**
https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/ mentions Kubernetes v1.7
Review this page, removing references to Kubernetes versions that are earlier than what's [supported](https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-versions), and revising wording to suit.

**Why is this needed**
The documentation usually can and should assume that the reader is running a version of Kubernetes that is at least as new as the oldest version still supported.

**Comments**
/kind cleanup

### PR DESCRIPTION
**Pull request by miteshskj**
Fixes #17014 
The feature is in beta since [1.13](https://v1-13.docs.kubernetes.io/docs/setup/release/notes/#deprecations)

### CODE REVIEW

**Comment by destijl** [comment]
AFAIK, there's nothing that makes this Beta apart from documentation. @liggitt @immutableT should we just call it stable?

**Comment by liggitt** [comment]
this PR lgtm in the meantime while we figure that out

> AFAIK, there's nothing that makes this Beta apart from documentation. @liggitt @immutableT should we just call it stable?

@immutableT, when did the health checks, metrics, and timeouts land?

**Comment by immutableT** [comment]
[Healthz](https://github.com/kubernetes/kubernetes/pull/78540) landed on July 3rd.

**Comment by miteshskj** [comment]
@liggitt  - Please let me know if we are good to drop the "beta" wording.

**Pull request merged**
