### PR TITLE
Update configure-liveness-readiness-startup-probes.md

### PR DESCRIPTION
**Pull request by muadhib**
Hi,
Just some translate fixes in french.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jimangel** [comment]
Hey there! @muadhib, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
Hi @muadhib .
Have you signed the CLA?

**Pull request closed without merging**
