### PR TITLE
Remove CoreOS baremetal offline setup guideline

### PR DESCRIPTION
**Pull request by tengqm**
The contents in this page is very old. The links in this page points to
some repos that no longer exist. This PR removes the guideline from
website.

However, considering that there may still be valuable information in the
page and there may be desire to resurrect the guide. The content is now
moved into an attic directory. We can decide whether and when to
completely drop it later.

Related: #7785

### CODE REVIEW

**Comment by tengqm** [comment]
@errordeveloper @jeffbean @erictune @thockin

**Comment by errordeveloper** [comment]
Thanks! I also happen to encounter this page today, and surprised I've not seen it's so old earlier when I was go through all of these guides.

I've actually opened #7821 just now to delete these outdated pages.

I don't think there is a need to move this to a directory, as we can always look at git history if needed. Anything unique about this content is going to be of very little use, because it's so old! Rewriting from scratch would be far less work then trying to adopt this for anything.

Also, we don't have an attic directory right now, I wouldn't introduce it just for this one thing. It's easier to look in git, if someone wants to resurrect any information.

**Comment by errordeveloper** [comment]
/assign @heckj

@heckj do you mind to make a call on whether we should move ahead with this or #7821 instead?

**Comment by heckj** [comment]
I went ahead and approved #7821 so that should be merged and these pages removed. 
closing this one as redundant

(worked through the queue in reverse order)

**Pull request closed without merging**
