### PR TITLE
[zh-cn]sync readme.md

### PR DESCRIPTION
**Pull request by uos-ljtian**
Sync latest content

### CODE REVIEW

**Comment by windsonsea** [comment]
Those content below line 259 are different from en too. Could you please double check it again?

image

**Comment by uos-ljtian** [comment]
> 259行以下的内容也和en不一样。你能再检查一遍吗？
> 
> 图像

请查看https://github.com/kubernetes/website/pull/34974

**Comment by windsonsea** [comment]
Thanks. 
/lgtm

**Pull request merged**
