### PR TITLE
Add info about logging into shell before removing /mnt/data

### PR DESCRIPTION
**Pull request by vadasambar**
details
----------
- rm -rf should be run after logging into the node shell

### CODE REVIEW

**Comment by vadasambar** [comment]
Signed the CLA

**Comment by vadasambar** [comment]
Signed the CLA

**Comment by vadasambar** [comment]
I signed it

**Comment by vadasambar** [comment]
I have signed it

**Comment by vadasambar** [comment]
I have signed it

**Comment by sftim** [comment]
@vadasambar did you want any help with getting this pull request reviewed & merged?

**Pull request closed without merging**
