### PR TITLE
replicaset: fix ownerReferences link

### PR DESCRIPTION
**Pull request by edwargix**
This heading doesn't exist: <https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-and-dependents>

This one does: <https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents>

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@edwargix Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: https://git.k8s.io/community/CLA.md

**Review by Arhell — COMMENTED** [review]
to check `/easycla`

**Comment by edwargix** [comment]
> @edwargix Thanks you for your contribution. Could you please sign the CLA before the PR can be reviewed. You can follow the steps documented here: https://git.k8s.io/community/CLA.md

All set

**Comment by tengqm** [comment]
Thanks
/lgtm
/approve

**Pull request merged**
