### PR TITLE
Fix incorrectly displayed K8s minor versions for `release-1.21` branch

### LINKED ISSUE #31551: Old versions of “Upgrade A Cluster” report wrong version details
https://v1-21.docs.kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/ has the header "You are viewing documentation for Kubernetes version: v1.21". However the content tells "This page is about upgrading from Kubernetes 1.22 to Kubernetes 1.23. If your cluster is not currently running Kubernetes 1.22 then please check the documentation for the version of Kubernetes that you plan to upgrade to." This content seems to be the same for all versions you can select from the upper right corner.

[moved to #31583] ~~Similarly https://v1-21.docs.kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/ has the header, but contains securityContext.allowPrivilegeEscalation. I have a cluster in 1.21.7 version in AKS, but `kubectl explain Pod.spec.securityContext` does not list the field.~~

### PR DESCRIPTION
**Pull request by jihoon-seo**
- This PR is a backport of the PR #34189.
- Closes #31551.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
/hold
(See #34349)

**Comment by kbhawkey** [comment]
👋 @jihoon-seo .
Did the versioning shortcodes change?

**Comment by jihoon-seo** [comment]
Hello @kbhawkey.
It seems that the versioning shortcodes themselves did not change.

What I want to fix in this PR is as per the issue #31551:

if you visit https://v1-21.docs.kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/ ,
the header says that "You are viewing documentation for Kubernetes version: **v1.21**".

But in "Before you begin" section, the page says that "This page is about upgrading from Kubernetes **1.23** to Kubernetes **1.24**.", 
which seems wrong and should be changed to "This page is about upgrading from Kubernetes **1.20** to Kubernetes **1.21**."

This PR resolves this by replacing shortcodes with appropriate ones.

**Comment by kbhawkey** [comment]
> Hello @kbhawkey. It seems that the versioning shortcodes themselves did not change.
> 
> What I want to fix in this PR is as per the issue #31551:
> 
> if you visit https://v1-21.docs.kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/ , the header says that "You are viewing documentation for Kubernetes version: **v1.21**".
> 
> But in "Before you begin" section, the page says that "This page is about upgrading from Kubernetes **1.23** to Kubernetes **1.24**.", which seems wrong and should be changed to "This page is about upgrading from Kubernetes **1.20** to Kubernetes **1.21**."
> 
> This PR resolves this by replacing shortcodes with appropriate ones.

Hi @jihoon-seo. I wonder if the `config.toml` file is out of sync on the 1.21 release branch? I thought we created and used the correct shortcodes, but perhaps several were not correctly placed.

Would you check the `config.toml` file on the `1.21-release` branch? I quickly looked at the initial version information (there is more),

```
latest = "v1.24"

fullversion = "v1.21.12"
version = "v1.21"
githubbranch = "release-1.21"
docsbranch = "release-1.21"
```

A preview page,
https://deploy-preview-34346--k8s-v1-21.netlify.app/docs/concepts/services-networking/network-policies/#what-you-can-t-do-with-network-policies-at-least-not-yet

**Comment by jihoon-seo** [comment]
@kbhawkey 
> perhaps several were not correctly placed.

Yes, I think so too.

---

> Would you check the `config.toml` file on the `1.21-release` branch?

As you already checked,
in `release-1.21/config.toml`:
https://github.com/kubernetes/website/blob/40e3e07733887f0e01bba2172f8a0c8bef27ad86/config.toml#L141-L146

This (`latest = "v1.24"`) seems fine, because it is required that we mention `v1.24` in some pages of `v1.21` website, e.g.:
- https://v1-21.docs.kubernetes.io/releases/#:~:text=The%20Kubernetes%20project%20maintains%20release%20branches%20for%20the%20most%20recent%20three%20minor%20releases%20(1.24%2C%201.23%2C%201.22).
- https://v1-21.docs.kubernetes.io/releases/version-skew-policy/#:~:text=The%20Kubernetes%20project%20maintains%20release%20branches%20for%20the%20most%20recent%20three%20minor%20releases%20(1.24%2C%201.23%2C%201.22).

---

(And yes, there is more:
https://github.com/kubernetes/website/blob/40e3e07733887f0e01bba2172f8a0c8bef27ad86/config.toml#L180-L213
but it seems that this part is only relevant with the version selector in top navbar of the website:)
image

**Pull request merged**
