### PR TITLE
Update list of sig-docs-pr-reviewers

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR freshens OWNERS_ALIASES with a current list of contributors for @kubernetes/sig-docs-pr-reviews.

### CODE REVIEW

**Comment by steveperry-53** [comment]
@zacharysarah This looks good to me. I think we should probably not have two things with almost the same name:

* sig-docs-pr-reviewers, which you have edited in this PR
* sig-docs-pr-reviews, a GitHub [team](https://github.com/orgs/kubernetes/teams/sig-docs-pr-reviews/members)

Maybe we don't need the GitHub team any more.

**Comment by zacharysarah** [comment]
@steveperry-53 
> Is there a relationship between the list in this PR and the GitHub team?

The alias block for SIG Docs follows the same format as other teams, so my guess is that the team is required for flagging SIG Docs for PR reviews across the org.

This PR syncs the contents of OWNERS_ALIAS with membership in the GH team.

**Comment by zparnold** [comment]
/lgtm

Thanks!

**Comment by zparnold** [comment]
@zacharysarah I see a few people in here that aren't in the OWNER_ALIASES file: https://github.com/orgs/kubernetes/teams/sig-docs-pr-reviews/members

Wasn't sure if that's intentional. I'll wait to approve until then. 😄

**Comment by zacharysarah** [comment]
@zparnold Good catch--I updated both the team and this PR, so it should be ready to go now.

**Pull request merged**
