### PR TITLE
translate suggest-improvements into chinese

### PR DESCRIPTION
**Pull request by ant4ly**
I saw that suggest-improvements.md has not been translated to Chinese, so i want to try to translate it.
if you find anything wrong or weird, please let me know.

https://github.com/kubernetes/website/pull/20620/commits/8cc5749bde4058ddbcbc8756123b4051ab39f0ba

### CODE REVIEW

**Comment by tengqm** [comment]
@lexmovrx Please include the original English text in comments for review and maintenance. Thanks.
/hold

**Comment by lexmovrx** [comment]
@tengqm ok, https://kubernetes.io/docs/contribute/suggest-improvements/

**Comment by tengqm** [comment]
@lichao42 Please see how other translation embeds the original English text. E.g. https://raw.githubusercontent.com/kubernetes/website/master/content/zh/docs/tasks/access-kubernetes-api/configure-aggregation-layer.md

**Comment by lexmovrx** [comment]
> @lichao42 Please see how other translation embeds the original English text. E.g. https://raw.githubusercontent.com/kubernetes/website/master/content/zh/docs/tasks/access-kubernetes-api/configure-aggregation-layer.md

oh, i see.

**Comment by lexmovrx** [comment]
@tengqm Can I close this PR? I'll revise the document and resubmit the PR request

**Comment by lexmovrx** [comment]
/check-cla

@tengqm Hi, I just submitted a pull request, please review.

**Comment by tengqm** [comment]
/lgtm
/check-cla
Don't know why you lose your CLA signing status.

**Comment by tengqm** [comment]
/approve

CLA status checking is flaky ...

**Comment by ant4ly** [comment]
> /check-cla

I'm so sorry, I changed my email and username,so cla check failed.

**Pull request closed without merging**
