### PR TITLE
adding header config for netlify

### PR DESCRIPTION
**Pull request by jimangel**
Adding a `X-Frame-Options = "DENY"` and `X-XSS-Protection = "1; mode=block"` to prevent clickjacking. For further protection we can add Content Security Policy headers.

Fixes: https://github.com/kubernetes/website/issues/27329

/cc @celestehorgan

### CODE REVIEW

**Comment by jimangel** [comment]
I ran an online XSS scanner on the netlify build and it came back clean.

I think we could do further testing and use 1 or 2 more reviews to validate the functionality of the site remains generally intact 😄

**Comment by celestehorgan** [comment]
https://securityheaders.com/?q=https%3A%2F%2Fdeploy-preview-27344--kubernetes-io-master-staging.netlify.app%2F&followRedirects=on

It works, and nothing seems broken!

/lgtm

**Review by irvifa — COMMENTED** [review]
/lgtm

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
