### PR TITLE
Add docs for Structured Authz beta

### PR DESCRIPTION
**Pull request by ritazh**
Docs updates for KEP 3221: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3221-structured-authorization-configuration
KEP issue: https://github.com/kubernetes/enhancements/issues/3221

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
@ritazh, perhaps we should consider setting the `dev-1.30` branch as the target branch rather than the `main` branch for this pull request. Since the change is related to the feature targeting beta in 1.30.

**Comment by chanieljdan** [comment]
Hi @ritazh 👋 just a reminder to take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday March 12th 2024 18:00 PST. 

Thank you!

**Pull request merged**
