### PR TITLE
[hi]: broken link in "hello-minikube" page

### LINKED ISSUE #44147: [hi]: broken link in "hello-minikube" page
**Problem:** There are broken link in [this](https://kubernetes.io/hi/docs/tutorials/hello-minikube/#%E0%A4%A1-%E0%A4%AA-%E0%A4%B2-%E0%A4%AF%E0%A4%AE-%E0%A4%9F-%E0%A4%AC%E0%A4%A8-%E0%A4%8F) page.
1. https://kubernetes.io/hi/docs/concepts/workloads/pods/
2. https://kubernetes.io/hi/docs/concepts/workloads/controllers/deployment/

**Proposed Solution:**
`https://kubernetes.io/hi/docs/concepts/workloads/pods/` -> `https://kubernetes.io/docs/concepts/workloads/pods/`
`https://kubernetes.io/hi/docs/concepts/workloads/controllers/deployment/` -> `https://kubernetes.io/docs/concepts/workloads/controllers/deployment/`

**Page to Update:**
https://kubernetes.io/hi/docs/tutorials/hello-minikube/

### PR DESCRIPTION
**Pull request by ankur0904**
Fix #44147

### CODE REVIEW

**Review by Gauravpadam — COMMENTED** [review]
Thanks for the PR

I think instead of redirecting to the en page, We should ideally localize the pages in context

**Comment by utkarsh-singh1** [comment]
Hi @ankur0904, There is already an updated PR #43480 with these changes mentioned.

**Review by kumarankit999 — COMMENTED** [review]
Looks Fixed now!!!!

**Comment by kundan2707** [comment]
@kumarankit999 it fixed for en content only. for hi it still exits

**Review by divya-mohan0209 — CHANGES_REQUESTED** [review]
Changes will need to be made when #44241 gets merged. Once the changes reflected in PR are made here, please feel free to unhold.

/hold

**Comment by kumarankit999** [comment]
Hey @kundan2707 Should I Create another Issue/PR for hi

**Comment by kumarankit999** [comment]
Hey @kundan2707 for English it looks working!! I think it's not working in Hindi!!!

**Comment by divya-mohan0209** [comment]
@kumarankit999 : Please refer to [this comment ](https://github.com/kubernetes/website/pull/44148#pullrequestreview-1769105472) left for @ankur0904 before you jump to making another PR for the same issue.

**Comment by ankur0904** [comment]
@divya-mohan0209 @kumarankit999 
When the https://github.com/kubernetes/website/pull/44241 got merged
I will unhold the PR and make any required commit as needed. 

_Thanks_

**Comment by kumarankit999** [comment]
Thanks @divya-mohan0209 @ankur0904 for letting me know!

**Comment by kumarankit999** [comment]
I think #44241 is now been Merged, we can work on this!!

**Comment by T-Lakshmi** [comment]
@ankur0904,
See [#44148 comment](https://github.com/kubernetes/website/pull/44148#issuecomment-1833151769) for advise on how to request approval.

**Comment by divya-mohan0209** [comment]
Hello @ankur0904 : Since there have been new changes in the English docs merged as part of #44241, please could you incorporate those in this PR as well. Thanks!

**Comment by ankur0904** [comment]
@divya-mohan0209 I think this PR related to [this](https://kubernetes.io/hi/docs/tutorials/hello-minikube/#%E0%A4%A1-%E0%A4%AA-%E0%A4%B2-%E0%A4%AF%E0%A4%AE-%E0%A4%9F-%E0%A4%AC%E0%A4%A8-%E0%A4%8F) page, but the PR #44241 deals with the  this [link](https://kubernetes.io/docs/tutorials/services/source-ip/)

Please correct me if I am wrong.

Thanks

**Comment by divya-mohan0209** [comment]
My bad, thank you for correcting me.

/lgtm
/approve

**Comment by ankur0904** [comment]
> My bad, thank you for correcting me.
> 
> /lgtm /approve

@divya-mohan0209 
No problem at all!

**Pull request merged**
