### PR TITLE
ISSUE-22953: add missing information about etcd images

### LINKED ISSUE #22953: Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/
It would be VERY helpful to know, that you have to download, extract, etc... the etcd binaries. Or that etcd will run as pods. The only point where this is mentioned is in the "optional" section...

thank you!

### PR DESCRIPTION
**Pull request by Evalle**
DESCRIPTION:
- highlights that etcd images should be reachable or installed on the hosts. Fixes #22953

### CODE REVIEW

**Comment by Evalle** [comment]
The doc looks like this:
Screen Shot 2020-08-05 at 11 41 41 AM

**Comment by neolit123** [comment]
thanks @Evalle 
the new note seems fine to me.

/lgtm
/sig cluster-lifecycle

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-22974--kubernetes-io-master-staging.netlify.app/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/
/lgtm

**Comment by kbhawkey** [comment]
Hi @Evalle .
Would you update your commit message by removing the Github keyword, `fixes #xxxxx`.
See the community contributors guide for more information:
https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#do-not-use-github-keywords-or-mentions-within-your-commit-message
Thanks!

**Comment by kbhawkey** [comment]
My mistake, the commit message is fine.
/approve

**Pull request merged**
