### PR TITLE
Update installation info for kubelet and kubernetes-cni

### PR DESCRIPTION
**Pull request by ZhiFeng1993**
This PR is to fix: https://github.com/kubernetes/kubeadm/issues/2160

I've updated docs in 3 languages: English, Japanese, and Chinese. There is a French doc here that needs update too: 
https://github.com/kubernetes/website/blob/master/content/fr/docs/setup/independent/kubelet-integration.md

### CODE REVIEW

**Comment by inductor** [comment]
/lgtm

For Japanese ream

**Comment by ZhiFeng1993** [comment]
@inductor  mind approve? Thanks

**Comment by justaugustus** [comment]
/lgtm
/hold

FYI, changes should only be staged, and not merged until after the next set of patch releases goes out: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md

**Comment by neolit123** [comment]
maybe this PR should have targeted the `dev-1.19` branch?
cc @jimangel

**Comment by justaugustus** [comment]
> maybe this PR should have targeted the `dev-1.19` branch?

Well this change will be present in 1.19.0 debs/rpms, but also the next 1.16 --> 1.18 patch releases, so it probably needs to land in master and then be cherry picked all the way back to 1.16.

**Comment by markthink** [comment]
@ZhiFeng1993  需要解决一下冲突..

**Comment by ZhiFeng1993** [comment]
@markthink  done. :)

**Comment by tengqm** [comment]
@ZhiFeng1993 I can see that this PR is fixing something that has to be fixed. That is great.
However, as you can see from the review history, a PR that spans more than one language is very difficult to review/approve. We have an explicit [guideline](https://kubernetes.io/docs/contribute/new-content/overview/#languages-per-pr) on this.
Imagine how this proposal can be quickly processed if you had divided into several PRs per language? So ... pls avoid such PRs in the future.

**Pull request merged**
