### PR TITLE
use current cpu arch instead hard-coding

### PR DESCRIPTION
**Pull request by wxw-matt**

### CODE REVIEW

**Comment by wxw-matt** [comment]
I've already signed a CLA and changed my primary email. Just wondering what should I do next?

**Comment by RA489** [comment]
> I've already signed a CLA and changed my primary email. Just wondering what should I do next?

Did you click on the link signup this project as an employee?

**Comment by wxw-matt** [comment]
> > I've already signed a CLA and changed my primary email. Just wondering what should I do next?
> 
> Did you click on the link signup this project as an employee?

I signed up as an individual, is that ok?

**Review by Arhell — COMMENTED** [review]
@wxw-matt 
try git reset --soft HEAD ~ 1 and force push
Maybe the comin was the wrong email (CLA email)

**Comment by wxw-matt** [comment]
> @wxw-matt
> try git reset --soft HEAD ~ 1 and force push
> Maybe the comin was the wrong email (CLA email)
Thanks for your tip.
Just pushed, hope it works.

**Comment by jimangel** [comment]
@wxw-matt it appears your still having issues with the CLA. Can you verify the commit email matches the email you used to sign the CLA? (this might help: https://stackoverflow.com/questions/29876342/how-to-get-only-author-name-or-email-in-git-given-sha1)

**Comment by wxw-matt** [comment]
> @wxw-matt it appears your still having issues with the CLA. Can you verify the commit email matches the email you used to sign the CLA? (this might help: https://stackoverflow.com/questions/29876342/how-to-get-only-author-name-or-email-in-git-given-sha1)

Try again to fix this, please have a look again.

**Comment by natalisucks** [comment]
Hey there @wxw-matt – sorry to see you're still having issues with your CLA! If you've tried all the above-mentioned suggestions regarding your commit email matching the one you used to sign the CLA, then you may need to log a ticket with the Linux Foundation Helpdesk to get this resolved – [see here](https://support.linuxfoundation.org/). Hopefully this will have things fixed swiftly so we can review your contribution.

**Comment by kbhawkey** [comment]
Testing
/close

**Comment by kbhawkey** [comment]
@wxw-matt , Can you look into the instructions to complete the EasyCLA? Thanks.

**Comment by wxw-matt** [comment]
Hi Karen,

I have tried following the instructions and in different ways.
However, I never got any luck.
I will do it again today and hopefully it works.

Thanks

Best wishes,
Matt

**Comment by jimangel** [comment]
Hey there! @wxw-matt, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by wxw-matt** [comment]
I would like to cancel this pull request and resubmit it because I tried different approaches, however, none of them worked.

**Pull request closed without merging**
