### PR TITLE
add styling for dl, dt, dd elements

### PR DESCRIPTION
**Pull request by kbhawkey**
Testing styling of definition lists.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Page preview:
https://5e3f37943ba99c000c9d7c8c--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/ingress/#terminology

Related to PR #18968 .

**Comment by sftim** [comment]
I'm overall fine with the idea of updating the styling here.

The style guide recommends [using italics when defining or introducing new terms](https://kubernetes.io/docs/contribute/style/style-guide/#use-italics-to-define-or-introduce-new-terms) so, with that in mind, how about making the text contents of `<dt />` elements be italic?

@kbhawkey what do you think? If you want to ship this as-is, you can /unhold

/hold
/lgtm
/approve

**Comment by kbhawkey** [comment]
@sftim, I am not sure if the italics work in this case. The block style seems to be closer to the list format and the style of the [glossary](https://kubernetes.io/docs/reference/glossary/?all=true).
@Colstuwjx , What are your thoughts on the styling and the look of the definition list in the Ingress page?

**Comment by zacharysarah** [comment]
@kbhawkey 
> I am not sure if the italics work in this case. The block style seems to be closer to the list format and the style of the glossary.
I think following the glossary example is fine here, but in that case I would bullet the terms if possible.

**Comment by kbhawkey** [comment]
> 
> 
> @kbhawkey
> 
> > I am not sure if the italics work in this case. The block style seems to be closer to the list format and the style of the glossary.
> 
> I think following the glossary example is fine here, but in that case I would bullet the terms if possible. (Will this impact #18968?)
> 
> This is a much cleaner format--thanks for the improvement! ✨

@zacharysarah , I will look into adding a bullet to the terms. The glossary is created from an unordered list. Yes, PR #18968 is impacted.

**Comment by kbhawkey** [comment]
Closing this issue, unless I hear that the docs need styling for definition lists 😃 .
/close

**Pull request closed without merging**
