### PR TITLE
[ru] Update `concepts/architecture/controller.md`

### PR DESCRIPTION
**Pull request by Legomegger**
add missing letter in russian page

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Plase sign CLA
https://github.com/kubernetes/website/pull/31574#issuecomment-1025568199
for check `/check-cla`

**Comment by jimangel** [comment]
Hey there! @Legomegger, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by reylejano** [comment]
Hi @Legomegger ,

I'm closing this PR since the [EasyCLA](https://github.com/kubernetes/community/blob/master/CLA.md) has not been signed.
Feel free to reopen this PR with `/reopen` once the [EasyCLA](https://github.com/kubernetes/community/blob/master/CLA.md) has been signed

**Comment by reylejano** [comment]
Hi @Legomegger ,

I'm closing this PR since the [EasyCLA](https://github.com/kubernetes/community/blob/master/CLA.md) has not been signed.
Feel free to reopen this PR with `/reopen` once the [EasyCLA](https://github.com/kubernetes/community/blob/master/CLA.md) has been signed

/close

**Pull request closed without merging**
