### PR TITLE
Edited wights for all the pages to order them alphabetically

### PR DESCRIPTION
**Pull request by ramiyengar**
Edited weights for the pages under https://kubernetes.io/docs/tasks/ to order them alphabetically. 

Thank you, SIG-docs team for making my 1st KubeCon experience special!

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by a-mccarthy** [comment]
Related to #35093

**Review by nate-double-u — COMMENTED** [review]
Hi @ramiyengar! Thanks for participating in the docs sprint!

It looks like this PR is editing existing weights to order the pages in alphabetical order -- unfortunately that's not quite the ask made in the issue. If a page in the en locale has a weight, it should be considered correct, and if it doesn't have a weight, then we should add one such that the default order is maintained (the default is alphabetical when there are no weights set).

Between this, and the easyCLA issues, I think we should close this PR. As always, feel free to reopen it if you feel like I've made a mistake closing it here, and I hope to see more PRs from you in future! 🙂

/close

**Pull request closed without merging**
