### PR TITLE
fix secret not working

### PR DESCRIPTION
**Pull request by zhouya0**
Fixes:
https://github.com/kubernetes/kubectl/issues/772
and also
https://github.com/kubernetes/website/issues/17597

The problem is that after the change of https://github.com/kubernetes/examples/pull/176. 
It has to use `configMap` to let nginx use `tls.key` and `tls.crt`. Otherwise it will try to find `nginx.key` and `nginx.crt` which will not be found.

### CODE REVIEW

**Comment by sftim** [comment]
Nice work (but I have not yet tested this)
/kind cleanup

**Comment by tengqm** [comment]
Let's kick it in and revise later if needed.
/lgtm
/approve

**Comment by gireeshp** [comment]
Hi @zhouya0, I tested this and is working fine. However, there are couple of minor issues.

"make" command assumes the PWD as "examples/staging/https-nginx"
```
make keys KEY=/tmp/nginx.key CERT=/tmp/nginx.crt
```
But this command will fail if the PWD is "examples/staging/https-nginx".
```
kubectl create configmap nginxconfigmap --from-file=examples/staging/https-nginx/default.conf
```

It would be nice, if we can sync both.

**Comment by zhouya0** [comment]
@gireeshp Thanks, I made https://github.com/kubernetes/website/pull/17923 little PR.

**Pull request merged**
