### PR TITLE
fix formatting errors

### PR DESCRIPTION
**Pull request by xieyanker**
fix formatting errors：

image

### CODE REVIEW

**Comment by xichengliudui** [comment]
preview link?
/approve

**Comment by xieyanker** [comment]
@xichengliudui https://deploy-preview-19065--kubernetes-io-master-staging.netlify.com/zh/docs/concepts/workloads/controllers/deployment/

**Comment by xichengliudui** [comment]
/lgtm
/approve
@xieyanker thanks!

**Pull request merged**
