### PR TITLE
Ported OIR tasks to use Extended Resources.

### PR DESCRIPTION
**Pull request by ConnorDoyle**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.9 Features: set Milestone to `1.9` and Base Branch to `release-1.9`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The Opaque Integer Resources feature was marked deprecated in the v1.8 release documentation. This feature has been removed and is not usable in v1.9. The replacement for OIR is called Extended Resources which behaves in a very similar way.

This change updates the old OIR-based tasks to use the replacement Extended Resources feature, and changes the maturity include from depreated to GA.

There are other mentions of OIRs in the docs, but we can clean those up in additional PRs.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6531)

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
cc @vishh

**Comment by tengqm** [comment]
This should target relase-1.9 branch?

**Comment by ConnorDoyle** [comment]
@tengqm yes this is for v1.9.

**Comment by ConnorDoyle** [comment]
@tengqm updated _data directory.

NOTE: Need help to update the Chinese translation.

**Comment by ConnorDoyle** [comment]
cc @kubernetes/sig-scheduling-api-reviews

**Pull request merged**
