### PR TITLE
Localize “email address” placeholder on home page

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/website/issues/19415

/language it

### CODE REVIEW

**Comment by sftim** [comment]
@Fale would you be willing to take a look at this one?

**Comment by Fale** [comment]
@sftim it seems like I can not lgtm it :-D. I think it would be better to put it in the localization branch otherwise it's a messy business, but that's just my 2cc. The translation by itself is right

**Comment by sftim** [comment]
Thanks.

**Comment by Fale** [comment]
This is fixed in #20139

**Comment by sftim** [comment]
@npu21 are you happy to close this?

**Pull request closed without merging**
