### PR TITLE
Use correct `which` command instead of non-existent `where`

### PR DESCRIPTION
**Pull request by Katee**
This fixes the instructions for finding the location of the `kubectl` binary.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@Katee Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by dipesh-rawat — COMMENTED** [review]
Looks like this PR seems to affect files in various languages ('en', zh-cn'). Since each localization follows different processes, we usually don't accept PRs that impact multiple languages at once. The recommendation would be to modify only the primary website content (English) in this PR. Once the English content is merged, we can create separate PRs for the other languages.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by utkarsh-singh1** [comment]
Hi @Katee, can you confirm your status on EasyCLA, as the changes seems to be beneficial for the kubectl uninstallation documents.

**Comment by Katee** [comment]
I'm not authorized to sign a CLA. I was expecting my employer (Alphabet/Verily) to already have something on file for Kubernetes. I've reached out about it.

**Comment by reylejano** [comment]
Hi @Katee , I'm closing this PR for the following reasons:
- this PR fails the CLA check
- this PR makes changes to the English and Chinese localization

Typically PRs target one localization with the change to the English site first.
Feel free to reopen this PR with `/reopen` in a comment when you are ready to work on this PR to remove the change to the Chinese localization and when the CLA has been signed or when Linux Foundation has verified the employer has signed the CLA

/close

**Comment by reylejano** [comment]
As these instructions are for macos, `where` works
here's an output from my macos laptop for both `where` and `which`:
> $ where kubectl                                                                                               [14:30:48]
/Users/reylejano/.rd/bin/kubectl
$ which kubectl                                                                                               [14:10:55]
/Users/reylejano/.rd/bin/kubectl

**Comment by Katee** [comment]
I'm running MacOS Ventura and I don't have a `where` command. It appears to be a command on Windows, but not on MacOS: https://apple.stackexchange.com/questions/272717/macos-equivalent-of-the-where-command-used-in-a-windows-command-prompt

@reylejano does `alias where` return anything?

**Comment by reylejano** [comment]
> I'm running MacOS Ventura and I don't have a `where` command. It appears to be a command on Windows, but not on MacOS: https://apple.stackexchange.com/questions/272717/macos-equivalent-of-the-where-command-used-in-a-windows-command-prompt
> 
> @reylejano does `alias where` return anything?

`alias where` returns nothing

If `where` is not available on all macos versions then we should use `which`

/approve

**Review by dipesh-rawat — COMMENTED** [review]
Verified the change on Mac. 
Thanks!
/lgtm

**Pull request merged**
