### PR TITLE
Note that Service Cloud Installer task is Google Cloud specific

### PR DESCRIPTION
**Pull request by sftim**
Relevant to #13017.
This PR replaces #13025, which got “stuck” with a _do-not-merge/work-in-progress_ label.

### CODE REVIEW

**Comment by DanyC97** [comment]
@sftim PR #13205 got merged eventually and i see is for `zh` lang hence i'm confused by your statement _This PR replaces #13205_  

Could you please clarify if this PR is only related to #13017 ?

**Comment by sftim** [comment]
Oops, typo. Should be #13025.

This PR is a fix for #13017

**Comment by tengqm** [comment]
still not working, strange

**Pull request merged**
