### PR TITLE
Added new PHP client library

### PR DESCRIPTION
**Pull request by rennokki**

### CODE REVIEW

**Comment by kbhawkey** [comment]
@jimangel , Has there been any resolution on #21509?

**Comment by sftim** [comment]
Sorry about the wait here @rennokki

**Comment by rennokki** [comment]
@sftim Not a big deal, the package got development on hold until https://github.com/kubernetes/website/pull/21509 gets rebased so I can do that here too.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-21112--kubernetes-io-master-staging.netlify.app/docs/reference/using-api/client-libraries/

**Comment by kbhawkey** [comment]
👋 @rennokki . 
Are you actively working on this pull request?

**Comment by rennokki** [comment]
@kbhawkey Sure, the package is continuously maintained.

**Pull request merged**
