### PR TITLE
Change source for signing key to validate Debian packages

### PR DESCRIPTION
**Pull request by shalintha**
Updated the signing key in **Debian-based distribution** section under **Installing kubeadm, kubelet and kubectl** subtitle

### CODE REVIEW

**Comment by neolit123** [comment]
this seems like a valid fix, but unclear if enough to solve the GPG issues.

please see this discussion and in the linked issues / PRs in there:
https://github.com/kubernetes/website/issues/41246

**Comment by sftim** [comment]
/retitle Change source for signing key to validate Debian packages

**Comment by sftim** [comment]
/hold

SIG Release: feel free to unhold once this has an appropriate tech review
/sig release

Relevant to https://github.com/kubernetes/website/issues/41246

**Comment by sftim** [comment]
I favor the approach in #41307; let's do that unless there's an update to the contrary.

**Comment by a-mccarthy** [comment]
Based on @sftim last comment, this was already updated in https://github.com/kubernetes/website/pull/41307, and I'd recommend that we close this PR. I'm not aware of the full context here though.

**Review by sftim — COMMENTED** [review]
I'm not sure if this is still the right fix.

@shalintha if an update is needed, please rebase this pull request accordingly.

**Comment by sftim** [comment]
Actually, as https://github.com/kubernetes/website/pull/41307 merged already.

/close

**Pull request closed without merging**
