### PR TITLE
[bn] localize api group.md

### PR DESCRIPTION
**Pull request by MRH-Romit**
localize and created api group.md from content/en/docs/reference/glossary/api-group.md

from issue: #45729

### CODE REVIEW

**Comment by asem-hamid** [comment]
@MRH-Romit  , are you still working on this task? Please let me know; otherwise, I will close this PR and unassign you.

Since we now have our new working branch `dev-1.31-bn.1`, you'll need to create a fresh PR with the following details:

- **Source repo**: `kubernetes/website`
- **Source branch**: `dev-1.31-bn.1`
- **Target branch**: `dev-1.31-bn.1`

**Comment by asem-hamid** [comment]
@MRH-Romit  no pain , just let me know if you need any help.

**Comment by MRH-Romit** [comment]
@asem-hamid  hey can you unassign me from all PR? it would be helpful, sorry for unconvinced but  i have some project on going , i'm unable to focus on this, Again i'm sorry it'll take weeks to complete my works

**Pull request closed without merging**
