### PR TITLE
Fix NGINX Ingress Controller URl

### PR DESCRIPTION
**Pull request by pkbhowmick**
Fix [#26146](https://github.com/kubernetes/website/issues/26146)

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
Preview: https://deploy-preview-26148--kubernetes-io-master-staging.netlify.app/docs/concepts/services-networking/ingress-controllers/#additional-controllers

**Review by savitharaghunathan — COMMENTED** [review]
Hi, @pkbhowmick 👋  Thanks for the PR.
/lgtm

**Comment by kbhawkey** [comment]
Thanks @pkbhowmick .
/kind cleanup
/approve

**Pull request merged**
