### PR TITLE
Remove duplicated "la" word in french documentation

### PR DESCRIPTION
**Pull request by hunomina**
Remove duplicated "la" word in french documentation

### CODE REVIEW

**Comment by hunomina** [comment]
I signed it

**Comment by ydFu** [comment]
@hunomina 
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by hunomina** [comment]
@ydFu I've already created an account and achieved all the step in the documentation you've sent
That's why I commented https://github.com/kubernetes/website/pull/26289#issuecomment-769735681 (to trigger the bot)

**Comment by feloy** [comment]
Hi @hunomina, are you sure you signed the CLA with the email attached to your commit?

**Comment by hunomina** [comment]
It should be ok now. Sorry :(

**Pull request merged**
