### PR TITLE
Use code shortcode for Tutorials section

### PR DESCRIPTION
**Pull request by sftim**
Replace legacy `{{% codenew file="…" %}}` shortcode with `{{% code file="…" %}}` shortcode.

Part of https://github.com/kubernetes/website/issues/42203

This covers the Tutorials section of the English docs.
/language en
/kind cleanup

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks, @sftim
Looks good to me.
/lgtm

**Comment by tengqm** [comment]
/lgtm
/approve
Kicking this in to avoid unnecessary rebases.

**Pull request merged**
