### PR TITLE
[pt] add searchbar to index page

### PR DESCRIPTION
**Pull request by Arhell**
/assign @stormqueen1990

### CODE REVIEW

**Review by jcjesus — APPROVED** [review]
Thanks @Arhell!

**Review by dipesh-rawat — COMMENTED** [review]
This change of adding searchbar looks in sync with main website ('en') [homepage](https://kubernetes.io/).
LGTM

[Preview Portuguese Homepage](https://deploy-preview-43825--kubernetes-io-main-staging.netlify.app/pt-br/)

**Comment by dipesh-rawat** [comment]
@Arhell We do occasionally see Netlify build [failures](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6548155fabe8900008613289). Could you try to trigger the build again by force-pushing empty commit.

**Review by sftim — COMMENTED** [review]
Obrigado

/lgtm

**Pull request merged**
