### PR TITLE
Update persistent-volumes.md

### PR DESCRIPTION
**Pull request by April-Q**
fix a spelling mistake in pv protection

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tanjunchen** [comment]
/hold
see
```
git branch
* master

./scripts/lsync.sh   content/zh/docs/concepts/storage/persistent-volumes.md
diff --git a/content/en/docs/concepts/storage/persistent-volumes.md b/content/en/docs/concepts/storage/persistent-volumes.md
index 971939d88..ef46b7f99 100644
--- a/content/en/docs/concepts/storage/persistent-volumes.md
+++ b/content/en/docs/concepts/storage/persistent-volumes.md
@@ -487,7 +487,7 @@ The following volume types support mount options:
 * VsphereVolume
 * iSCSI

-Mount options are not validated, so mount will simply fail if one is invalid.
+Mount options are not validated. If a mount option is invalid, the mount fails.

 In the past, the annotation `volume.beta.kubernetes.io/mount-options` was used instead
 of the `mountOptions` attribute. This annotation is still working; however,
@@ -629,6 +629,11 @@ spec:

 PersistentVolumes binds are exclusive, and since PersistentVolumeClaims are namespaced objects, mounting claims with "Many" modes (`ROX`, `RWX`) is only possible within one namespace.

+### PersistentVolumes typed `hostPath`
+
+A `hostPath` PersistentVolume uses a file or directory on the Node to emulate network-attached storage.
+See [an example of `hostPath` typed volume](/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume).
+
 ## Raw Block Volume Support

 {{< feature-state for_k8s_version="v1.18" state="stable" >}}
```

Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87) . To find out what are the upstream changes to be synced, do this:

**Comment by tengqm** [comment]
Closing this for now due to lack of response.
Please feel free to reopen and ask for help if needed.
/close

**Pull request closed without merging**
