### PR TITLE
Remove outdated Japanese/Chinese notes in favor of default

### PR DESCRIPTION
**Pull request by saschagrunert**
The notes for the other languages seem outdated and we should stick to the default (en) version.

### CODE REVIEW

**Comment by inductor** [comment]
Thanks! Japanese one looks good!(so should be Chinese one, too)
/lgtm

**Comment by inductor** [comment]
https://github.com/kubernetes/website/blob/dev-1.16-ja.1/content/ja/docs/setup/release/building-from-source.md this page contains the link for release note for the Japanese directory. Can you also change it too?

**Comment by saschagrunert** [comment]
> @saschagrunert
> Sorry, I have favour about this.
> https://github.com/kubernetes/website/blob/master/content/ja/docs/setup/release/building-from-source.md this page contains the link for release note for the Japanese directory. Can you also change it too?
> 
> I had a look at Chinese too but on the master branch there was no reference yet!

Yes sure, I changed the link to match just `/docs/setup/release/notes/`. :+1:

**Comment by inductor** [comment]
Thanks! /lgtm

**Comment by inductor** [comment]
Thanks!

/lgtm

@kubernetes/sig-docs-zh-reviews ping

**Comment by xichengliudui** [comment]
/lgtm
/approve
from Chinese

**Comment by xichengliudui** [comment]
/lgtm cancel
/approve cancel
The Chinese team will create issue based on the English source file to update, all issues in Chinese do not need to be deleted, if Japanese needs to be deleted, please create a separate pr.
ref：https://github.com/k8smeetup/website-tasks/issues

**Comment by idealhack** [comment]
@xichengliudui Since this PR is making changes to the master branch (v1.17 / v1.18) while the Chinese one is for v1.16, I'm inclined to merge it. Then the translation task will be created anyway, right?

**Comment by saschagrunert** [comment]
Okay thank you for the notice, I now assume that this PR is fine, right?

**Comment by inductor** [comment]
@kbarnard10 ping

@sftim or can you help? :P

**Comment by jimangel** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
