### PR TITLE
fix bullet indentation in Publish CRD OpenAPI Documentation

### PR DESCRIPTION
**Pull request by roycaihw**
fix https://github.com/kubernetes/website/pull/12910#issuecomment-473427472

/cc @cody-clark

### CODE REVIEW

**Comment by roycaihw** [comment]
/hold

github markdown rendering is different from kubernetes.io preview. Waiting to see if it's fixed

**Comment by roycaihw** [comment]
/hold cancel

the indentation looks better now: https://deploy-preview-13214--kubernetes-io-vnext-staging.netlify.com/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2

compared with previously https://deploy-preview-12910--kubernetes-io-vnext-staging.netlify.com/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2

@cody-clark please take a look

**Comment by cody-clark** [comment]
@roycaihw thanks for the super quick PR! I was going to fix the indenting, but you already took care of it. Looks good.

**Pull request merged**
