### PR TITLE
Bump up deployment version in concepts/overview/object-management-kub…

### PR DESCRIPTION
**Pull request by nashasha1**
I will create a bunch of PRs for bumping up deployment version.  A pr contains all changes in a folder.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7327)

### CODE REVIEW

**Comment by steveperry-53** [comment]
In the declarative-config.md topic, this PR changes the YAML config files to say v1, but the command output shown in the topic still has v1beta1. If we're going to change the config files, we probably should run the commands and capture the new output.

**Comment by nashasha1** [comment]
@steveperry-53  Thanks for your comment. I re-run the yaml, changed the output.

**Pull request merged**
