### PR TITLE
Apply grammar fix

### PR DESCRIPTION
**Pull request by cflynn07**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.13-ko.<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Hi @cflynn07 Could you please sign the CLA.

 Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

memo Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

**Comment by cflynn07** [comment]
👍

**Comment by zparnold** [comment]
Hey there! @cflynn07, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Rajakavitha1** [comment]
Hi @cflynn07, looks like you haven't signed the CLA yet.
Closing the PR now. You can open it after signing the CLA. We can’t even review PRs whose authors have not signed the CLA!

**Comment by cflynn07** [comment]
@Rajakavitha1 Just signed it!

**Pull request merged**
