### PR TITLE
[ja] sync concepts/architecture/controller.md

### PR DESCRIPTION
**Pull request by KKtheGhost**
## PR Summary

- **EN upstream**: `content/en/docs/concepts/architecture/controller.md`
- **Sync to**: `content/ja/docs/concepts/architecture/controller.md`

Sync check by`scripts/lsync.sh` on `main` branch:
```diff
$ scripts/lsync.sh content/ja/docs/concepts/architecture/controller.md
diff --git a/content/en/docs/concepts/architecture/controller.md b/content/en/docs/concepts/architecture/controller.md
index 711cf38363..b89f6a077c 100644
--- a/content/en/docs/concepts/architecture/controller.md
+++ b/content/en/docs/concepts/architecture/controller.md
@@ -26,7 +26,7 @@ closer to the desired state, by turning equipment on or off.
 ## Controller pattern

 A controller tracks at least one Kubernetes resource type.
-These [objects](/docs/concepts/overview/working-with-objects/kubernetes-objects/#kubernetes-objects)
+These {{< glossary_tooltip text="objects" term_id="object" >}}
 have a spec field that represents the desired state. The
 controller(s) for that resource are responsible for making the current
 state come closer to that desired state.
@@ -80,7 +80,7 @@ indicate that your room is now at the temperature you set).

 ### Direct control

-By contrast with Job, some controllers need to make changes to
+In contrast with Job, some controllers need to make changes to
 things outside of your cluster.

 For example, if you use a control loop to make sure there
@@ -95,8 +95,8 @@ the current state closer in line.
 (There actually is a [controller](https://github.com/kubernetes/autoscaler/)
 that horizontally scales the nodes in your cluster.)

-The important point here is that the controller makes some change to bring about
-your desired state, and then reports current state back to your cluster's API server.
+The important point here is that the controller makes some changes to bring about
+your desired state, and then reports the current state back to your cluster's API server.
 Other control loops can observe that reported data and take their own actions.

 In the thermostat example, if the room is very cold then a different controller
@@ -159,11 +159,12 @@ You can run your own controller as a set of Pods,
 or externally to Kubernetes. What fits best will depend on what that particular
 controller does.

-
-
 ## {{% heading "whatsnext" %}}

 * Read about the [Kubernetes control plane](/docs/concepts/overview/components/#control-plane-components)
-* Discover some of the basic [Kubernetes objects](/docs/concepts/overview/working-with-objects/kubernetes-objects/)
+* Discover some of the basic [Kubernetes objects](/docs/concepts/overview/working-with-objects/)
 * Learn more about the [Kubernetes API](/docs/concepts/overview/kubernetes-api/)
-* If you want to write your own controller, see [Extension Patterns](/docs/concepts/extend-kubernetes/extend-cluster/#extension-patterns) in Extending Kubernetes.
+* If you want to write your own controller, see
+  [Extension Patterns](/docs/concepts/extend-kubernetes/#extension-patterns)
+  in Extending Kubernetes.
+
```
Sync check by`scripts/lsync.sh` on `sync/architecture-controller` branch:
```diff
$ ./scripts/lsync.sh content/ja/docs/concepts/architecture/controller.md
content/ja/docs/concepts/architecture/controller.md is still in sync
```

Thanks to the reviewers in advance.
Best Regards,

Kivinsae Fang

### CODE REVIEW

**Comment by atoato88** [comment]
For other reviewers for ease of review.
The target page on deploy preview:
- https://deploy-preview-41759--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/architecture/controller/

**Comment by KKtheGhost** [comment]
Hello @atoato88 

Could you please help check the status of this PR if you have free time slots?
Thanks so much for your help in advance.

Best Regards,

**Pull request merged**
