### PR TITLE
Update 1.28 maintenance mode date in schedule.yaml

### PR DESCRIPTION
**Pull request by reylejano**
Update 1.28 maintenance mode date
Fixes issue https://github.com/kubernetes/website/issues/42659
cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by reylejano** [comment]
cc @gracenng 
/assign @Rishit-dagli

**Review by Rishit-dagli — APPROVED** [review]
/lgtm

Thanks for fixing this, maybe we should later also add this to the [handbook](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-releases-page-the-week-before-the-release)

**Comment by sftim** [comment]
Manually merged to work around a Netlify issue

**Pull request merged**
