### PR TITLE
[ru] Update tutorials/kubernetes-basics/_index.html

### PR DESCRIPTION
**Pull request by JazzSlice**
Update missed letter in word on the main page. UI report - non critical.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by shurup** [comment]
Hi @JazzSlice, and thank you for your fix!

Since we try to follow the [Trivial Edits guidelines](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) as much as we can, I kindly ask you to find more things you can improve in the same document (or any other around you went through recently). Having a PR with several minor fixes makes more sense and we'll be more likely to merge it.

**Comment by shurup** [comment]
It doesn't seem we'll get other corrections from the author, so I suggest carrying on anyway.

/lgtm
/approve

**Pull request merged**
