### PR TITLE
Localize content/en/docs/reference/glossary/rbac.md in hindi

### PR DESCRIPTION
**Pull request by taniaduggal**
Signed-off-by: Tania Duggal <103496926+taniaduggal@users.noreply.github.com>
fixes #36727

### CODE REVIEW

**Review by Babapool — COMMENTED** [review]
Some suggestions from myside, hope you find them useful. Thanks

**Review by Babapool — COMMENTED** [review]
Thanks!
/lgtm

**Review by bishal7679 — APPROVED** [review]
Looks good!

**Review by sftim — COMMENTED** [review]
Aside: we might want to explain that RBAC is an abbreviation for _role based access control_.

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Pull request merged**
