### PR TITLE
minikube 1.19.0 is namespace changed

### PR DESCRIPTION
**Pull request by bringer1092**
Ingress namespace is minikube 1.19.0 chage the status kube-system to ingress-nginx. 

https://github.com/kubernetes/minikube/blob/master/CHANGELOG.md#version-1190-beta0---2021-04-05
https://github.com/kubernetes/minikube/pull/10879

/ assign @onlydole

### CODE REVIEW

**Comment by bringer1092** [comment]
I signed it

**Comment by jimangel** [comment]
Hey there! @bringer1092, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by jihoon-seo** [comment]
@bringer1092 Welcome and thank you for your contribution!

- Related issue: #28099
- The PR #28355 is handling the same issue.

**Comment by jihoon-seo** [comment]
/close
Because the PR #28355, which is handling the same issue, has been merged.

**Pull request closed without merging**
