### PR TITLE
Update audit-policy.yaml

### PR DESCRIPTION
**Pull request by chayte**
Hello,

I was using the example provided in documentation and faced issue with it.
After some investigations from logs,I saw that my issue comes from indent after "rules:"
I suggest the following fix.

### CODE REVIEW

**Comment by tengqm** [comment]
This change doesn't see necessary.
/hold

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by utkarsh-singh1** [comment]
Hi @chayte, The original YAML syntax is valid, you can check If YAML syntax is valid or not on code-editors or 3rd party YAML syntax checkers.

**Comment by chayte** [comment]
Hi
Ok may be an issue with my linter.
Thanks for your remark.
You can close the change request.


Le sam. 18 mars 2023 à 04:11, Utkarsh Singh ***@***.***> a
écrit :

**Comment by utkarsh-singh1** [comment]
Hi @chayte, you can close this issue using `/close` tag.

**Pull request closed without merging**
