### PR TITLE
Update service.md

### PR DESCRIPTION
**Pull request by ChenjunZou**
fix a mispelled keyword.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@ChenjunZou
Pls sign the CLA in order for the PR to be reviewed.

**Comment by ChenjunZou** [comment]
> CLA signature

CLA signature already signed, what should I do to continue the PR

**Comment by howieyuen** [comment]
> > CLA signature
> 
> CLA signature already signed, what should I do to continue the PR

need a `lgtm(looks good to me)` and `approve` label, then this PR can get merged automatically.

**Review by howieyuen — APPROVED** [review]

**Pull request merged**
