### PR TITLE
update Jintao's information

### PR DESCRIPTION
**Pull request by tao12345666333**
a tiny update

### CODE REVIEW

**Comment by tao12345666333** [comment]
Thanks 

Let me update

**Comment by tao12345666333** [comment]
updated.

**Comment by taniaduggal** [comment]
LGTM

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by AmanSarraf** [comment]
Hey @craigbox , can you please review this PR?
/assign @craigbox

**Pull request merged**
