### PR TITLE
WIP: kubectl kustomize deprecation

### PR DESCRIPTION
**Pull request by soltysh**
Ref: https://github.com/kubernetes/enhancements/issues/4706

### CODE REVIEW

**Comment by sftim** [comment]
The best place to communicate this deprecation is in the release announcement; please work with release comms to announce it clearly.

If you want to also have a blog article a few days later to repeat or expand the message, that's not a problem.

**Comment by sftim** [comment]
/hold

pending assignment of publication date (by release comms)

we'll also keep this held until the v1.31 release has happened

**Comment by soltysh** [comment]
> The best place to communicate this deprecation is in the release announcement; please work with release comms to announce it clearly.

Tim that's the plan we have. We're hoping to strengthen the message with this blog, because we've noticed that not many people read release notes. So we're planning both a tweet and this blog to make sure this message reaches more users.

**Comment by sftim** [comment]
This blog article could be mostly about how to switch to using `kustomize` as a plugin, with a preamble that repeats the deprecation message.

**Comment by soltysh** [comment]
> This blog article could be mostly about how to switch to using `kustomize` as a plugin, with a preamble that repeats the deprecation message.

That's a good suggestion, I'm still working on it :-)

**Comment by a-mccarthy** [comment]
Hi @soltysh, I'm Abbie, from the 1.31 Release comms team. I'm reaching out with a reminder that the blog ready for review deadline is July 26, 2024. Please let me know how we can help!

**Comment by soltysh** [comment]
@a-mccarthy we're be holding this work until further discussions from 1.31 release. 

/hold

**Comment by drewhagen** [comment]
This website has been frozen for 1.31 and we will release tomorrow.

Changing the milestone to 1.32.

/milestone 1.32

**Comment by drewhagen** [comment]
This was dropped from the 1.31 release.
This website has been frozen for 1.31 and we will release tomorrow.

Changing the milestone to 1.32.

/milestone 1.32

**Comment by soltysh** [comment]
See this comment https://github.com/kubernetes/enhancements/issues/4706#issuecomment-2506018548

**Pull request closed without merging**
