### PR TITLE
Fix examples test

### PR DESCRIPTION
**Pull request by tengqm**
This PR fixes the examples test so that all YAML manifests under examples directory are assured to be working under 1.25.

The content/js/examples/examples_test.go is out-dated and it is blocking the `go mod tidy` run unfortunately. So this PR removes it.

### CODE REVIEW

**Review by sftim — APPROVED** [review]
Happy with the intent of this pull request.

/approve

**Comment by kbhawkey** [comment]
Hi @tengqm. The changes look good.
@kubernetes/sig-docs-ja-reviews , this PR removes a `ja` examples test file.

**Comment by reylejano** [comment]
Thank you
/lgtm

**Pull request merged**
