### PR TITLE
[WIP] Document PodAndContainerStatsFromCRI feature

### PR DESCRIPTION
**Pull request by haircommander**
There will be docs... one day
 issue: https://github.com/kubernetes/enhancements/issues/2371

### CODE REVIEW

**Comment by sftim** [comment]
I hope it's OK to
/retitle [WIP] Document PodAndContainerStatsFromCRI feature

(more recognisable than the KEP number)

**Comment by haircommander** [comment]
of course, thank you!

**Comment by PI-Victor** [comment]
this has been removed from the milestone, closing for now, but if there's an exception granted, please re-open it
/close

**Pull request closed without merging**
