### PR TITLE
Add Linux Foundation's K8s Online Training to Online Training List

### PR DESCRIPTION
**Pull request by vanou**
This PR adds The Linux Foundation's K8s online training ( [Kubernetes Fundamentals (LFS258)](https://training.linuxfoundation.org/training/kubernetes-fundamentals/) ) to online training list of K8s website

### CODE REVIEW

**Comment by vanou** [comment]
/assign @tengqm 

Your check is very helpful. Thanks!

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-15608--kubernetes-io-master-staging.netlify.com/docs/tutorials/online-training/overview/

**Pull request merged**
