### PR TITLE
[de] Ready training section for vanilla Docsy

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/45870/files

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Change look in sync with 'en' PR https://github.com/kubernetes/website/pull/45870/files
LGTM

[Current partner section index](https://k8s.io/de/training/) | [Preview partner section index](https://deploy-preview-46079--kubernetes-io-main-staging.netlify.app/de/training/)

/area web-development

**Review by bene2k1 — APPROVED** [review]

**Pull request merged**
