### PR TITLE
Fixed typo issue in /tutorials/stateful-application/zookeeper.md

### PR DESCRIPTION
**Pull request by avidLearnerInProgress**
Applied the minor fix associated with the issue: https://github.com/kubernetes/website/issues/13975

### CODE REVIEW

**Comment by ClaudiaJKang** [comment]
/assign

@avidLearnerInProgress Thank you for your contribution. 

Your PR don't have any problem. 

But, the working branch of Korean Localization team is `dev-1.14-ko.3`. 
So, could you change the base branch `master` to `dev-1.14-ko.3`?

**Comment by avidLearnerInProgress** [comment]
> 
> 
> /assign
> 
> @avidLearnerInProgress Thank you for your contribution.
> 
> Your PR has not any problem.
> 
> But, the working branch of Korean Localization team is `dev-1.14-ko.3`.
> So, could you change the base branch `master` to `dev-1.14-ko.3` in this PR?

I can see the base branch being displayed as: dev-1.14-ko.3:

image

Is this okay or do I need to change something?

**Comment by ClaudiaJKang** [comment]
@avidLearnerInProgress 

Thank you! 

/lgtm
/approve

**Pull request merged**
