### PR TITLE
Merge master into dev-1.20 to keep in sync 12-03-20

### PR DESCRIPTION
**Pull request by kcmartin**
Merge master into dev-1.20 to keep in sync 12-03-20

### CODE REVIEW

**Comment by annajung** [comment]
commits with build errors:

https://github.com/kubernetes/website/pull/25378/commits/ad8b32ffce090cbaa04ffe86d9055c721dcd2242 https://github.com/kubernetes/website/pull/25378/commits/72fb7e4d30325e7f82dc0fdfdd77d46c4ed91064 https://github.com/kubernetes/website/pull/25378/commits/e0a2a5f4c59adc9f794c6d7877c8c255cc256e83

Nothing stands out from the logs, similar to the errors we have seen in the past. 

/lgtm

**Comment by kbhawkey** [comment]
I see this error:
```
$ git submodule update --init --recursive --depth 1 && make deploy-preview
10:35:31 PM: hugo --enableGitInfo --buildFuture -b https://deploy-preview-25244--kubernetes-io-master-staging.netlify.app
10:37:02 PM: Building sites … ERROR 2020/11/27 03:35:58 [zh] "docs/reference/glossary/controller.md": "kube-cluster" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
ERROR 2020/11/27 03:36:02 [zh] "docs/reference/glossary/dynamic-volume-provisioning.md": "储存类别（storage-class）" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
Total in 90564 ms
```

**Comment by annajung** [comment]
Thanks for double-checking @kbhawkey !
Do you know what the process is when there is a build failure like this?

**Comment by kbhawkey** [comment]
I am guessing this error was fixed in a later PR? The site builds.

**Comment by annajung** [comment]
ahh okay, so I think this happened because merge had multiple commits (https://github.com/kubernetes/website/pull/25244/commits)

So it was fixed by the last change

**Comment by kbhawkey** [comment]
Thanks @kcmartin !
/approve

**Pull request merged**
