### PR TITLE
fix auditlog feature state

### PR DESCRIPTION
**Pull request by WYFDC**

### CODE REVIEW

**Comment by tengqm** [comment]
/lgtm

Holding approval for a confirmation that the feature state change is for 1.14, not 1.15.

**Comment by tengqm** [comment]
@WYFDC Is this for 1.14 or 1.15?

**Comment by markthink** [comment]
@WYFDC 分支提交错误，建议向 1.14 分支提交

**Comment by pigletfly** [comment]
ping @WYFDC

**Comment by xiangpengzhao** [comment]
Since there is no response from @WYFDC for more than a month, I'm going to close this PR for now. @WYFDC Please feel free to reopen this PR when you have a chance to make the suggested change above :)
/close

**Pull request closed without merging**
