### PR TITLE
Update kubelet --feature-gates and add --rotate-server-certificates

### PR DESCRIPTION
**Pull request by oke-py**
* Update kubelet --feature-gates referring to [this file](https://github.com/kubernetes/kubernetes/blob/v1.13.0/pkg/features/kube_features.go)
  * some features promoted to Beta/GA
  * some features deprecated and removed
    * Accelerators https://github.com/kubernetes/kubernetes/pull/57384
    * KubeletConfigFile https://github.com/kubernetes/kubernetes/pull/58978
    * ReadOnlyAPIDataVolumes https://github.com/kubernetes/kubernetes/pull/67951
    * ServiceProxyAllowExternalIPs https://github.com/kubernetes/kubernetes/pull/67951
* Add kubelet --rotate-server-certificates
  * description derives from [this line](https://github.com/kubernetes/kubernetes/blob/v1.13.0/cmd/kubelet/app/options/options.go#L515)

### CODE REVIEW

**Comment by tfogo** [comment]
Hi @oke-py, thanks for the PR. Did you manually edit this file or generate it? This file is a generated file, so if you manually edited it, your changes will be overwritten the next time it is generated.

**Comment by oke-py** [comment]
@tfogo Oh, I edited this file manually. Is there anything I can do?
Which file, repo needs to be changed? Or it's OK only to wait for the update?

**Comment by ryanmcginnis** [comment]
i don't have enough understanding of the repo to know how to make changes to an autogenerated file... i've reassigned this PR to mistyhacks@ assuming she might know.

**Comment by zparnold** [comment]
@oke-py @tfogo Kubelet generated docs I believe live in the K/K repo. So this change probable needs to be made there, then we can regenerate the docs.

**Comment by oke-py** [comment]
@tfogo Thanks for your reply. I found the generator is [here](https://github.com/kubernetes/kubernetes/blob/v1.13.0/cmd/genkubedocs/gen_kube_docs.go#L75-L78).
`--feature-gates` probably refers to [this file](https://github.com/kubernetes/kubernetes/blob/v1.13.0/pkg/features/kube_features.go) and the file is what I referred when editing this document.
`--rotate-server-certificates` description is [here](https://github.com/kubernetes/kubernetes/blob/v1.13.0/cmd/kubelet/app/options/options.go#L515).
So, I think necessary changes have already been made.

**Comment by Rajakavitha1** [comment]
@zparnold Please take a look.

**Comment by zparnold** [comment]
@oke-py sounds good, so that means the next time the docs are generated (1.14 release) this site will be updated. @jimangel can follow up with more (he's the release lead)
/close

**Pull request closed without merging**
