### PR TITLE
Update Romana details

### PR DESCRIPTION
**Pull request by sftim**
- omit it as an example from CNI-Genie
- update the hyperlink

Follows on to https://github.com/kubernetes/website/pull/32834

As a separate piece of work, it'd be great to switch to using the CNCF Landscape for this list - see https://github.com/kubernetes/website/issues/32778

_This_ PR is not that fix.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@sftim GitHub says that this branch has conflicts that must be resolved.
Please resolve conflicts. :)

**Comment by sftim** [comment]
This is ready for review

**Review by JohnTitor — COMMENTED** [review]
/lgtm

**Comment by jihoon-seo** [comment]
@sftim You deleted the 'Contiv' line in this PR. I wonder this was what you intended, or an accidental one.

**Comment by sftim** [comment]
Hmm. I think that was an accidental removal. Oops.

**Pull request merged**
