### PR TITLE
Revise body of patch request in StatefulSet tutorial

### LINKED ISSUE #44713: Please enhance the section description at `tutorials/stateful-application/basic-stateful-set/#on-delete`
**This is a Feature Request**

**What would you like to be added**
At this section, it introduces using `OnDelete` by the command below.
```bash
kubectl patch statefulset web -p '{"spec":{"updateStrategy":{"type":"OnDelete"}}}'
``` 

But in the case of a server like `minikube`, where defaulting `spec.updateStrategy.rollingUpdate` field in the create step,
it shows an error like this.
```bash
➜  minikube kubectl patch statefulset web -p '{"spec":{"updateStrategy":{"type":"OnDelete"}}}'
The StatefulSet "web" is invalid: spec.updateStrategy.rollingUpdate: Invalid value: apps.RollingUpdateStatefulSetStrategy{Partition:0, MaxUnavailable:(*intstr.IntOrString)(nil)}: only allowed for updateStrategy 'RollingUpdate'
```

*Therefore* I recommend to change this part like this.
```bash
//As-is
kubectl patch statefulset web -p '{"spec":{"updateStrategy":{"type":"OnDelete"}}}'
//To-be
kubectl patch statefulset web -p '{"spec":{"updateStrategy":{"type":"OnDelete","rollingUpdate":null}}}'
```
I think it is important because most newbie of k8s will use `minikube` and they can suffer from similar issues.

**Comments**

I referred [this page](https://github.com/kubernetes/kubernetes/issues/100151) for debugging this error.

### PR DESCRIPTION
**Pull request by PrashantDesale2004**
fixed #44713 
from 
kubectl patch statefulset web -p '{"spec":{"updateStrategy":{"type":"OnDelete"}}}'

to
kubectl patch statefulset web -p '{"spec":{"updateStrategy":{"type":"OnDelete","rollingUpdate":null}}}'

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @PrashantDesale2004, sign EasyCLA first, it will help reviewers to review and approve your PR. 

You can find details here - 
- https://lfx.linuxfoundation.org/tools/easycla

Sign here - 
- https://contributor.easycla.lfx.linuxfoundation.org/#/cla/project/d8cead54-92b7-48c5-a2c8-b1e295e8f7f1/user/c57ec339-631b-11ec-ba90-92044a4ddd9f?redirect=https:%2F%2Fgithub.com%2Fkubernetes%2Fwebsite%2Fpull%2F43506

**Comment by utkarsh-singh1** [comment]
Also , 

> [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.
> 
> **The list of commits with invalid commit messages**:
> 
> * [31e0a17](https://github.com/kubernetes/website/commits/31e0a1789144e2a55ab364ddf3adcf0313e4a42a) fixed [Please enhance the section description at `tutorials/stateful-application/basic-stateful-set/#on-delete` #44713](https://github.com/kubernetes/website/issues/44713) Please enhance the section description at tutorials/stateful-application/basic-stateful-set/#on-delete

Update your current PR, with respect to the given message here, choose a commit message which doesn't contain - 

- Issue no. or its description  
- Do not use any hastag 

Write clear commit message, so that it can be short and understable, u can look at this [article](https://cbea.ms/git-commit/) for your next commit messages also look at this piece of [content](https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines) which will help you on your next PR.

Thanks for raising the PR for the issue #44713.

**Comment by PrashantDesale2004** [comment]
> Also ,
> 
> > [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.
> > **The list of commits with invalid commit messages**:
> > 
> > * [31e0a17](https://github.com/kubernetes/website/commits/31e0a1789144e2a55ab364ddf3adcf0313e4a42a) fixed [Please enhance the section description at `tutorials/stateful-application/basic-stateful-set/#on-delete` #44713](https://github.com/kubernetes/website/issues/44713) Please enhance the section description at tutorials/stateful-application/basic-stateful-set/#on-delete
> 
> Update your current PR, with respect to the given message here, choose a commit message which doesn't contain -
> 
> * Issue no. or its description
> * Do not use any hastag
> 
> Write clear commit message, so that it can be short and understable, u can look at this [article](https://cbea.ms/git-commit/) for your next commit messages also look at this piece of [content](https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines) which will help you on your next PR.
> 
> Thanks for raising the PR for the issue #44713

> Also ,
> 
> > [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.
> > **The list of commits with invalid commit messages**:
> > 
> > * [31e0a17](https://github.com/kubernetes/website/commits/31e0a1789144e2a55ab364ddf3adcf0313e4a42a) fixed [Please enhance the section description at `tutorials/stateful-application/basic-stateful-set/#on-delete` #44713](https://github.com/kubernetes/website/issues/44713) Please enhance the section description at tutorials/stateful-application/basic-stateful-set/#on-delete
> 
> Update your current PR, with respect to the given message here, choose a commit message which doesn't contain -
> 
> * Issue no. or its description
> * Do not use any hastag
> 
> Write clear commit message, so that it can be short and understable, u can look at this [article](https://cbea.ms/git-commit/) for your next commit messages also look at this piece of [content](https://www.kubernetes.dev/docs/guide/pull-requests/#commit-message-guidelines) which will help you on your next PR.
> 
> Thanks for raising the PR for the issue #44713.

will i have to raise PR again ?

**Comment by sftim** [comment]
/retitle Revise body of patch request in StatefulSet tutorial

**Comment by sftim** [comment]
> will i have to raise PR again ?

No. You can edit what you have sent in. However, if you are not sure how to edit an existing commit and would prefer to open a new pull request, you could do that instead.

**Pull request closed without merging**
