### PR TITLE
move obj mgmt files to tasks

### PR DESCRIPTION
**Pull request by kbhawkey**
See issue #14272.
Started a bit of cleanup.

### CODE REVIEW

**Comment by tengqm** [comment]
I like this change.
We are almost there. One suggestion I have is about adding some entries to the redirect file so users who have bookmarks won't get confused.

**Comment by kbhawkey** [comment]
@tengqm , how will the files relocations affect the localized files? I noticed that some localized files have redirect instructions in the front matter.

**Comment by tengqm** [comment]
@kbhawkey ... good question, I don't know the answer. we have some path parsing problems with localized contents already.
/lgtm
/approve

**Pull request merged**
