### PR TITLE
Update network-policies.md - harmonize yaml code

### PR DESCRIPTION
**Pull request by mhash17**
Harmonizing Ident of yaml code

### CODE REVIEW

**Review by kundan2707 — COMMENTED** [review]
Previous yamls seems good and working fine

**Comment by mhash17** [comment]
In 'network-policies.md' for sequence elements both styles are used (i don't know if it's spread over the whole docs, but at this point i stumbled over it).
It is inhomogenous and irritating. Either it should be used one style or the other.

See: 
```
...
policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
...
```
And:
```
...
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
...
```

**Comment by kundan2707** [comment]
closing as completed via #44503

**Pull request closed without merging**
