### PR TITLE
upgrade docs controller to new theme

### PR DESCRIPTION
**Pull request by crixo**
upgrade the controller documentation page to the new theme used by k8s.io

related to the issue #20957

### CODE REVIEW

**Comment by Fale** [comment]
/lgtm
remember to squash the commits ;-)

**Comment by fabriziopandini** [comment]
/approve
thanks @crixo !

**Comment by crixo** [comment]
> /approve
> thanks @crixo !

Thanks you all! With a special one to @Fale who became my git&Hugo mentor! That's so much fun writing documentation!

**Pull request merged**
