### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by jogspokoen**
Fixed broken links for the Linuxacademy courses

### CODE REVIEW

**Comment by tengqm** [comment]
@jogspokoen Thanks for the contribution. Please consider signing the CLA in order for this valuable fix to be mergeable.

**Comment by jogspokoen** [comment]
Hi @tengqm 
Sorry to bother you, but bot doesn't react on my `/check-cla` command.
I looged into https://identity.linuxfoundation.org with my github account, am I missing some step?
Could you please trigger this check for me?

**Comment by jogspokoen** [comment]
I signed it

**Comment by tengqm** [comment]
close and reopen and see if CLA check can be triggered. @jogspokoen You may have to double check the CLA status if the check still fails.

**Comment by jogspokoen** [comment]
Hi @tengqm
CLA solved

**Comment by tengqm** [comment]
@jogspokoen Thanks.
/lgtm
/approve

**Pull request merged**
