### PR TITLE
[bn] Adding  example/job  files in bn version

### PR DESCRIPTION
**Pull request by asem-hamid**
Fixes Issue : https://github.com/kubernetes/website/issues/44993
Related PR : https://github.com/kubernetes/website/pull/45009
Tracking Issue: https://github.com/kubernetes/website/issues/31677

### CODE REVIEW

**Review by mitul3737 — APPROVED** [review]

**Review by Imtiaz1234 — APPROVED** [review]
/lgtm

**Review by dipesh-rawat — COMMENTED** [review]
It seems the PR build preview is encountering following [failures](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/662f52b6db9811000754a9ab)

> 8:57:51 AM: ERROR [bn] no Resource or Page matching "static/cncf-code-of-conduct.md*".
..
..
..
..
..
..
8:58:43 AM: ERROR [bn] "docs/concepts/workloads/pods/_index.md": "sidecar-container" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
ERROR [bn] "docs/reference/glossary/init-container.md": "sidecar-container" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list

- For the error `"no Resource or Page matching "static/cncf-code-of-conduct.md*"` the issue is that in this PR's branch `adding-job-sidecar.yaml` there's no **"cncf-code-of-conduct.md"** file inside the [content/bn/community/static](https://github.com/asem-hamid/website/tree/adding-job-sidecar.yaml/content/bn/community/static).

- Regarding the error `'sidecar-container" is not a valid glossary term_id'` this problem occurs because the glossary shortcode(s) _(tooltip and description)_ relies on matching the `term_id` with glossary entry `filename` to retrieve the data. Currently, for this PR's branch [asem-hamid:adding-job-sidecar.yaml](https://github.com/asem-hamid/website/blob/adding-job-sidecar.yaml/content/bn/docs/reference/glossary/sidecar-containers.md) the `term_id` in the file reads as "**sidecar-container**" while the file name is "`sidecar-containers.md"` _(note the extra 's' in the end)_, causing the shortcode to fail in locating the necessary data.


It looks like the main [kubernetes/website/dev-1.24-bn.1](https://github.com/kubernetes/website/tree/dev-1.24-bn.1) branch already contains the necessary fixes. Rebasing your branch against this branch should pull in these changes, allowing the build to pass successfully. Additionally, consider pulling the latest changes from the dev-1.24-bn.1 branch into your fork [(here)](https://github.com/asem-hamid/website/tree/dev-1.24-bn.1) to ensure you have the most up-to-date codebase.

Hope this helps!

**Review by Imtiaz1234 — APPROVED** [review]

**Comment by asem-hamid** [comment]
@dipesh-rawat Done thank you for helping

**Pull request merged**
