### PR TITLE
Fix footer rendering

### PR DESCRIPTION
**Pull request by sftim**
The [community page](https://kubernetes.io/community/) had the wrong rendering for the page footer [[preview](https://deploy-preview-31277--kubernetes-io-main-staging.netlify.app/community/)].
Ensure that the footer is as wide as the viewport.

Also, improve how the text in the footer is laid out when the viewport is quite wide.

/area web-development

### CODE REVIEW

**Comment by jihoon-seo** [comment]
[Before]
image
image

[After]
image
image

/lgtm

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by mehabhalodiya** [comment]
@kbhawkey @tengqm Can you please approve this?

**Comment by kbhawkey** [comment]
Thanks @sftim 
/approve

**Comment by jihoon-seo** [comment]
Despite this PR has been merged, it seems that the error still exists. 🤔
CC @sftim 😊

**Comment by sftim** [comment]
@jihoon-seo, would you be willing to log an issue about that?

**Pull request merged**
