### PR TITLE
[ja] Translate content/ja/docs/setup/production-environment/tools/kubespray.md into Japanese

### LINKED ISSUE #38633: [ja] Translate content/ja/docs/setup/production-environment/tools/kubespray.md into Japanese
**This is a Feature Request**

**What would you like to be added**

Translate content/ja/docs/setup/production-environment/tools/kubespray.md into Japanese

**Why is this needed**
This file is partially translated.

**Comments**

/language ja
/assign

### PR DESCRIPTION
**Pull request by levi106**
Fixes #38633 

Preview: https://deploy-preview-38634--kubernetes-io-main-staging.netlify.app/ja/docs/setup/production-environment/tools/kubespray/

### CODE REVIEW

**Comment by t-inu** [comment]
Thanks for your first PR to the website!

It seems this page is outdated.
Compared to the original page, there are several differences.
https://kubernetes.io/docs/setup/production-environment/tools/kubespray/
How about taking this opportunity to update the contents?

If you intend to update in this PR, I will review after that.
If not, or plan to update by creating another PR, I will review only the translated parts this time.

**Comment by levi106** [comment]
@t-inu 
Thank you for your review.
I will update to the latest one in this PR.

**Comment by levi106** [comment]
Hi @t-inu,
I updated the contents. I would appreciate your review.

**Review by t-inu — COMMENTED** [review]
Thank you for updating.
There are some comments and suggestions, please check.

**Comment by levi106** [comment]
@t-inu 
Thanks for your kind review.
I merged your suggestions.

**Review by t-inu — APPROVED** [review]
/lgtm

**Review by nasa9084 — COMMENTED** [review]
/approve

**Pull request merged**
