### PR TITLE
Adding fix for #19646

### PR DESCRIPTION
**Pull request by rlenferink**
This fixes the home page button bug described in #19646 

/cc @bene2k1 @mkorbi 
/hold
holding till #19646 merges

### CODE REVIEW

**Comment by mkorbi** [comment]
please double-check @rlenferink , but this fix breaks the grid of the docs. It should be like
CorrectGrid
but it looks with the fix like that
BrokenGrid

**Comment by rlenferink** [comment]
Thanks for checking Max! That's correct. That is because the `gridpage.css` is not included. However, once #19646 merges that check is updated as well. I'll then rebase this and it should work fine then.

**Comment by rlenferink** [comment]
/hold cancel
since the dependent PR got merged.

@mkorbi can you re-check this ?

**Comment by mkorbi** [comment]
@rlenferink looks good
/lgtm
/approve

**Pull request merged**
