### PR TITLE
Added a link to the minikube installation website

### PR DESCRIPTION
**Pull request by AnirudhPenmatcha**
Hi, I was trying to install Kubernetes on my local machine and I noticed that suggestion to install Minikube did not have a hyperlink to it. So I added a link at the mention of install Minikube so it's convenient for people trying to install it on their local machine.

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Does not seems like a necessity to me as there is already mention of install minikube as tool for local kubernetes cluster.

**Comment by utkarsh-singh1** [comment]
Here it is -> https://kubernetes.io/docs/tasks/tools/#minikube

**Comment by utkarsh-singh1** [comment]
You can check This PR -> https://github.com/kubernetes/website/pull/44982 and Issue -> https://github.com/kubernetes/website/issues/44981 for the reference .

**Review by sftim — COMMENTED** [review]
Thanks
/lgtm
/approve

**Pull request merged**
