### PR TITLE
Move AWS Service annotation details to reference page

### PR DESCRIPTION
**Pull request by sftim**
https://kubernetes.io/docs/concepts/services-networking/service/ has a bunch of specific details for one cloud provider, AWS.

These belong elsewhere; there are already good homes at https://cloud-provider-aws.sigs.k8s.io/service_controller/ and https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/, so we can omit them from the Service page.

I updated https://kubernetes.io/docs/reference/labels-annotations-taints/ to list all the AWS annotations for Services, and I marked all of those as deprecated because they include `.beta.` in the subdomain part of the label key (which is a generally deprecated practice).

[Preview](https://deploy-preview-38551--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/service/) of the revised Service page.

~Open~ question, though: should we link from https://kubernetes.io/docs/concepts/services-networking/service/ to https://cloud-provider-aws.sigs.k8s.io/service_controller/ and to https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/?
- If we do, does it make sense also to link to https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/
  - and to list the deprecated annotations for Azure LB in https://kubernetes.io/docs/reference/labels-annotations-taints/?
- We can do that. It shouldn't be part of this PR though, whatever we decide.

~marking as Draft because of the open question~

### CODE REVIEW

**Comment by tengqm** [comment]
This is NICE.
/lgtm
I'm not sure the `beta` in the annotations means that they are deprecated though.

**Comment by sftim** [comment]
I understood that _all_ annotations with alpha or beta in their name were deprecated and that SIGs should look to move away.

Since I opened this PR, I found https://cloud-provider-aws.sigs.k8s.io/service_controller/ and also https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/

1. We can hyperlink to these
2. I can file enhancement issues against the AWS and Azure cloud provider code to recommend using a non-beta annotation, ideally one that doesn't use a kubernetes.io domain.

**Comment by tengqm** [comment]
My take is that most of the providers of those APIs are cautious about the "maturity level" of their technologies.
"Alpha", "Beta" are an indication of technology maturity. An "Alpha" version of something may be widely used, and a "Beta" release might be deprecated a long time ago. Similarly, a "v1" release might become EOL several years ago.
I cannot tell if a "Beta" thing is deprecated or not. If it is deprecated, we must already have a more mature thing as a replacement. That's the reason I think we may need double confirm at this.

**Comment by sftim** [comment]
I'll ask SIG Architecture how we should mark 'em.

**Comment by sftim** [comment]
Ok, I think this is ready for review.

**Comment by sftim** [comment]
I just went with marking all but one actually-deprecated annotation as beta.

**Comment by sftim** [comment]
[Changes](https://github.com/kubernetes/website/compare/bd45bb2fd9b0fa1368648aafcf56c4d40e27bce6..6144923d61ccede0a9da2cc1253769146cc7ff47) since last LGTM

**Comment by sftim** [comment]
All changes since https://github.com/kubernetes/website/pull/38551#issuecomment-1516781231 are just rebases.

**Pull request merged**
