### PR TITLE
Fixes #9787. Be explicit with page name for Hugo to find section

### LINKED ISSUE #9787: Missing Homepage Tutorial Button
The Kubernetes homepage no longer has a button to the Kubernetes basis tutorials to help users get started. 

From what I can tell from the Hugo code the block is meant to be rendered:

https://github.com/kubernetes/website/blob/master/layouts/_default/baseof.html#L16

https://github.com/kubernetes/website/blob/master/layouts/index.html#L6-L9

### PR DESCRIPTION
**Pull request by BenHall**
Fixes the homepage styling as described in #9787.

1) With the upgrade to 0.46 of Hugo, it was no longer able to find the section for the training. Including the filename solved this problem.
2) Removed `_index.md` to be consistent as I don't think it's required.
3) Moved `_index.html` in cn to be `index.md` like with en.

### CODE REVIEW

**Comment by bep** [comment]
@BenHall not sure when this happened, but I guess it is likely me to blame :-)

The above is a symptom of another issue: 

```bash
▶ ls content/en/docs/tutorials/kubernetes-basics/*index*
content/en/docs/tutorials/kubernetes-basics/_index.md  content/en/docs/tutorials/kubernetes-basics/index.html
```

There should be only one. 

To cut a long story short, what you should do is:

1) Rename `_index.md` to `_index.html`
2) Pull the content of `index.html` into `_index.html`
3. Delete `_index.html`

A footnote: In Hugo 0.45 we rewamped `.Site.GetPage` etc. so it can now be written as `{{ with .Site.GetPage "docs/tutorials/kubernetes-basics" }}`, which would make it more portable. But you should wait a little before you change to that API, because it's not backwards compatible.

**Comment by BenHall** [comment]
@bep Thanks, I'll update the PR

**Comment by BenHall** [comment]
Thank you @bep - Updated the PR with your suggestions and it removed the strange workaround of needing to specify the filename :)

**Comment by zacharysarah** [comment]
@BenHall Good to go? If so, feel free to remove the `/hold`. 👍 

/lgtm
/approve
/hold

**Pull request merged**
