### PR TITLE
replace KubeCon EU with KubeCon China on community page and homepage

### PR DESCRIPTION
**Pull request by alexcontini**

### CODE REVIEW

**Comment by alexcontini** [comment]
@kbarnard10 just tagging you here to review this PR when you have a chance!

**Comment by kbarnard10** [comment]
@alexcontini Can you change the date on the homepage to November 14-15, 2018?

**Comment by zacharysarah** [comment]
👋 We've migrated the site's framework to Hugo. Please re-open this PR with changes to files in their post-migration location (/content/en/docs/...) and reference this PR in the new PR's description.

**Pull request closed without merging**
