### PR TITLE
Update local storage capacity isolation feature to GA

### PR DESCRIPTION
**Pull request by jingxu97**
update feature to GA

### CODE REVIEW

**Comment by xing-yang** [comment]
We need to update the following section as well:
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage

**Comment by reylejano** [comment]
@jingxu97 @xing-yang , the Docs Ready for Review deadline for the 1.25 release is eod tomorrow, August 9th 2022
When this PR is ready, please change the state from Draft to Ready for Review

**Comment by xing-yang** [comment]
Here's another place that needs an update: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features

**Comment by krol3** [comment]
> Here's another place that needs an update: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features

@jingxu97 any update of this reference for the dev-1.25 release?

**Comment by jingxu97** [comment]
> Here's another place that needs an update: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features

not sure whether we should update this or not. I don't see any GA features for 1.25 or even 1.24, 1.23 got updated in this page.

**Comment by jingxu97** [comment]
this is replaced by new PR https://github.com/kubernetes/website/pull/35989

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de fr id it ja ko pt uk zh
/remove-sig release

**Pull request closed without merging**
