### PR TITLE
Update date format for bengali

### PR DESCRIPTION
**Pull request by asem-hamid**
Update date format for bengali .

 MM-DD-YYYY  to DD-MM-YYYY

### CODE REVIEW

**Comment by niranjandarshann** [comment]
@asem-hamid  May I know Why it is required to change the date format as it is accepted as universal date format. Is there is anything specific in bengali for date format. I am not getting its requirement details.

I am just enquiring to get your point of view.

**Comment by asem-hamid** [comment]
People in Bangla generally use the DD-MM-YYYY format, and sometimes the MM-DD-YYYY format becomes really confusing since we are used to the DD-MM-YYYY format.

**Comment by niranjandarshann** [comment]
> People in Bangla generally use the DD-MM-YYYY format, and sometimes the MM-DD-YYYY format becomes really confusing since we are used to the DD-MM-YYYY format.

Got it,  It is allowed in localization also to adjust the date and time according to the your local. I had seen hi and bn are mostly used to DD-MM-YYYY format.

So for me it looks good

**Comment by sftim** [comment]
Hmm, we're missing a @kubernetes/sig-docs-bn-owners team.

**Review by mitul3737 — APPROVED** [review]
LGTM

**Review by Imtiaz1234 — APPROVED** [review]
LGTM

**Review by divya-mohan0209 — COMMENTED** [review]
This LGTM.
Additionally taking previous approvals from owners of the Bengali localisation, approving this.
/approve

**Pull request merged**
