### PR TITLE
Updated service.md

### PR DESCRIPTION
**Pull request by divya-mohan0209**
Removed the Future Work section from https://kubernetes.io/docs/concepts/services-networking/service/

### CODE REVIEW

**Comment by sftim** [comment]
This is for issue #19531

**Comment by divya-mohan0209** [comment]
@sftim Sure, thank you for bringing that to my notice! Have edited the pull request now with the correct name 👍

**Comment by sftim** [comment]
@divya-mohan0209 the [list of commits](https://github.com/kubernetes/website/pull/19539/commits) still mentions #19531 when I look.

**Comment by divya-mohan0209** [comment]
@sftim Apologies, it should now be resolved. Please check and let me know, if anything else seems to be an issue?

**Pull request merged**
