### PR TITLE
Update components-of-kubernetes.svg

### PR DESCRIPTION
**Pull request by devarsh10**
Added two new Cluster Architecture. For easy understanding.

### CODE REVIEW

**Comment by sftim** [comment]
Hi

https://github.com/kubernetes/website/pull/39389/files shows that the image isn't valid - did you expect that @devarsh10 ?

**Comment by devarsh10** [comment]
No, let me check and reupload the changes.

**Comment by sftim** [comment]
I think the second image is closer to where we want to end up.

**Comment by devarsh10** [comment]
Hey @sftim, I solved the image not valid issue. Please take a look. As I have been told to solve the issue within this PR only.

Regards.

**Comment by devarsh10** [comment]
> preview: https://deploy-preview-39389--kubernetes-io-main-staging.netlify.app/docs/concepts/overview/components/ I don't like the look&feel of the new picture.

Hey @tengqm, I have added another architecture which I had created earlier. Please review it.

**Comment by reylejano** [comment]
I agree with @tengqm , I do not like the updated image proposed in this PR and prefer the original

**Comment by devarsh10** [comment]
> I agree with @tengqm , I do not like the updated image proposed in this PR and prefer the original The image proposed in this PR is harder to read than the original

Okay, let me try and create a new architecture.

**Comment by devarsh10** [comment]
Hey @reylejano, please take a look on my edited architecture. And let me know for any changes.

**Comment by tengqm** [comment]
Some feedbacks to the latest version:

- We don't need to write all text in upper case. It is okay to use Title Case.
- We don't need to wrap "Control Plane" or "Worker Node 1" or "Worker Node 2" with a box.
- The box around "Container Runtime" is confusing. It looks like some Pods are contained in a container runtime while others are not. This is not good.
- Kubectl talks to the API server, and it can only talk to the API server.
- The existing icons (with labels like 'c-c-m') can be discarded if necessary. We can use simpler boxes with text attached. Then we don't need the legend which adds burden to users.
- When we are not constrained by the icons, we can highlight that some components are optional, we can even put the add-ons into this picture.

**Comment by devarsh10** [comment]
> Some feedbacks to the latest version:
> 
> * We don't need to write all text in upper case. It is okay to use Title Case.
> * We don't need to wrap "Control Plane" or "Worker Node 1" or "Worker Node 2" with a box.
> * The box around "Container Runtime" is confusing. It looks like some Pods are contained in a container runtime while others are not. This is not good.
> * Kubectl talks to the API server, and it can only talk to the API server.
> * The existing icons (with labels like 'c-c-m') can be discarded if necessary. We can use simpler boxes with text attached. Then we don't need the legend which adds burden to users.
> * When we are not constrained by the icons, we can highlight that some components are optional, we can even put the add-ons into this picture.

Okay. I'll consider all points you said.

**Comment by devarsh10** [comment]
Hey @tengqm, I had created the architecture, by considering your points.
And here's the image of it. I'm yet to add Hyperlinks.
Once you verify the architecture I'll add them.

image

**Comment by tengqm** [comment]
Some more suggestions:

- The dash line from Cloud Controller Manager to API server is confusing. It can be interpreted as the Cloud Controller Manager may and may not talk to the API server. However, we want to show users that the cloud controller manager is optional, and the kube-proxy is optional.
- The frame for Control Plane is not necessary.
- The outer box for the whole control plane can be doted or dashed line, because it is a concept. The control plane doesn't have to be a node, and we don't want give user such an impression.
- We can reduce the height of the control plane box to save some area in the diagram. We can use the saved area to show those add-ons (DNS, logging, monitoring, web UI etc.). These add-ons are not core Kubernetes components, but they are equally important to make the cluster usable and manageable.

**Comment by sftim** [comment]
Based on that last image, I suggest having a different number of Pods between the two nodes. That should help clarify that the numbers of Pods might not match.

Also, should kube-proxy talk to the API server?

**Comment by devarsh10** [comment]
Okay, so I'll name the & clarify by mentioning pod1 & pod2. 
And make a line between kube-proxy with API server. As kube-proxy holds the IP address of the node. So, it must be connected with API server.

**Comment by devarsh10** [comment]
Update K8s_Arch. Please take a look.
k8s_Arch_png

**Comment by sftim** [comment]
Based on that last image, I suggest having a **different** number of Pods between the two nodes. Also, number them uniquely (don't use the same number / .letter for a Pod on node 1 and for a different Pod on node 2).

If we can imply that there are often _lots_ of nodes, that's even better.

**Comment by devarsh10** [comment]
Expected?

k8s_Arch

**Comment by sftim** [comment]
More help here is welcome. How about proposing a few different diagrams in #sig-docs on the Kubernetes Slack workspace, and seeing which diagram people like best?

Once we've got that, let's iterate on it. I'd like to be sure that when we replace what we have, people will mostly prefer the new diagram.

**Comment by devarsh10** [comment]
Hey @sftim, the changes have been made I guess. So, do you think, I should close this PR?
[Kubernetes Component](https://deploy-preview-39389--kubernetes-io-main-staging.netlify.app/docs/concepts/overview/components/)

**Pull request closed without merging**
