### PR TITLE
Update configure-upgrade-etcd.md

### PR DESCRIPTION
**Pull request by nzneit**
Fix typo in "Maintaining etcd clusters"

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for correction of this minor typo!
/lgtm

Deploy Preview: [deploy-preview-41649-configure-upgrade-etcd](https://deploy-preview-41649--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/configure-upgrade-etcd/)

**Review by Arhell — COMMENTED** [review]
lgtm

**Review by vaibhav2107 — COMMENTED** [review]
/lgtm

**Pull request merged**
