### PR TITLE
Document `kubectl alpha events` 

### PR DESCRIPTION
**Pull request by hpandeycodeit**
This [Draft] PR documents the alpha feature kubernetes/enhancements#1440, kubectl alpha events

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
@hpandeycodeit Can you change the target branch to `dev-1.19` from `master` ? 
/assign
/milestone 1.19
/hold

Feel free to cancel hold once you have switched the target to `dev-1.19`

**Comment by sftim** [comment]
As this is draft:
/retitle Draft PR for `kubectl alpha events` command

(@hpandeycodeit when you're ready it'll help to retitle this to something like “Document `kubectl alpha event`”)

**Comment by savitharaghunathan** [comment]
Hi @hpandeycodeit 👋 , Please rebase this PR as @sftim suggested.

**Comment by hpandeycodeit** [comment]
@sftim somehow I can't fix this PR. Shall I go ahead and create a new one?

**Comment by sftim** [comment]
@hpandeycodeit if you'd prefer to open a new PR, that's fine. Please reference the old PR in the description of the new one.

**Comment by divya-mohan0209** [comment]
Hello, @hpandeycodeit , good day! I'm one of the shadows on the Release 1.19 team and am reaching out regarding this PR requiring a rebase. Please can you ensure it is done as soon as possible so as to avoid merge conflicts. Once done, please assign the PR to @savitharaghunathan so that she can review it. Additionally, I'd also like to remind you of the upcoming docs deadline on July 16th. Do let us know if there's any help you require from our end.

**Comment by savitharaghunathan** [comment]
Hi @hpandeycodeit 👋, given that this PR is not targeted for the `1.19` release, I will close it now. If the plan is to have this land in `1.20` you may reopen this PR again targeting the new `dev-1.20` branch once created. Thanks!

/close

**Pull request closed without merging**
