### PR TITLE
Fix broken links in files in reference/setup-tools/kubefed/

### LINKED ISSUE #12207: Several broken links in files in reference/setup-tools/kubefed/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
There are several broken links in reference/setup-tools/kubefed/.
- kubefed_init.md  
- kubefed_join.md  
- kubefed_options.md  
- kubefed_unjoin.md  
- kubefed_version.md

The following link in each file causes 404 error.
```
### SEE ALSO
* [kubefed](kubefed.md)	 - kubefed controls a Kubernetes Cluster Federation
```

**Proposed Solution:**
Fix the link address for each file.
```
### SEE ALSO
* [kubefed](/docs/reference/setup-tools/kubefed/kubefed)	 - kubefed controls a Kubernetes Cluster Federation
```

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_options/
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_init/
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_join/
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_unjoin/
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_version/

### PR DESCRIPTION
**Pull request by seokho-son**
Fixes #12207.

### CODE REVIEW

**Comment by seokho-son** [comment]
I have the same question with @bradtopol. These broken links are from "Auto generated by spf13/cobra" for setup-tools/kubefed files. 
I think we can correct the broken links for the current document.
But, in the next time, the auto generation code needs to be modified to avoid generating broken links again.

The broken links in reference/setup-tools/kubefed/
#12177 
#12207

**Comment by tfogo** [comment]
These files are generated so the fix would only be temporary.

**Comment by tfogo** [comment]
I think it might be better not to make a temporary fix so that it forces us to fix the underlying issue.

**Comment by steveperry-53** [comment]
I'm going to approve this, because it doesn't hurt anything. But these changes will get overwritten the next time the ref docs are generated. The real fix needs to be in the upstream source.
/approve

**Pull request merged**
