### PR TITLE
Upgrade Mermaid to fix diagram render problem on ingress page

### PR DESCRIPTION
**Pull request by chrismetz09**
Problem:

- https://github.com/kubernetes/website/issues/27008 identified diagram render problem of mermaid pictures on https://github.com/kubernetes/website/issues/27008 using Chrome Ubuntu.

- Current version of Mermaid 8.5.0. Need upgrade to Mermaid 8.9.1.

Actions performed:

- copied contents of https://unpkg.com/mermaid@8.9.1/dist/mermaid.min.js into https://github.com/kubernetes/website/blob/master/static/js/mermaid.min.js

- updated file reference in https://github.com/kubernetes/website/blob/master/layouts/partials/head.html#L90

- tested with local Hugo server using Mac Chrome Version 88.0.4324.192 (Official Build) (x86_64)

- tested with local Hugo server using Mac Firefox Version 88.0.4324.192 (Official Build) (x86_64)

Actions needed:

- Did not test with Chrome/Ubuntu due to lack of Ubuntu. Need someone to test with Chrome/Ubuntu and report back.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Thanks for this PR.

```
$ git status                                                                                           
On branch pr-27129
nothing to commit, working tree clean
Your stash currently has 48 entries
$ git rev-parse HEAD                                                                                   
6d51ebdf60541a336a1410155415e00e3bf30b42
$ sha1sum static/js/mermaid.min.js      
6f95517a19be9b6fb6ad89020cd9660f6012dd2f  static/js/mermaid.min.js
$ curl https://unpkg.com/mermaid@8.9.1/dist/mermaid.min.js | sha1sum -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  827k    0  827k    0     0  1943k      0 --:--:-- --:--:-- --:--:-- 1943k
b7cf0808a81060c63ef68842da4ba8ed5c7c8544  -
$
```

These SHA-1 checksums are different. @chrismetz09 what's the reason for that difference? I'd like to understand the mismatch before marking this LGTM.

BTW @chrismetz09, [Docsy includes Mermaid](https://www.docsy.dev/docs/adding-content/lookandfeel/#diagrams-with-mermaid) so we might be able to rely on that instead.

**Comment by chrismetz09** [comment]
@sftim, PR comments copied contents shown above caused SHA-1 checksum mismatch. I should have replaced static/js/mermaid.min.js with https://unpkg.com/mermaid@8.9.1/dist/mermaid.min.js file.

Should I push new commit after performing this action so sha-1 checksums match?

**Comment by sftim** [comment]
It's probably OK to squash to 1 commit, or:
- first commit: matches upstream code exactly
- second commit, if needed: specific changes with an explanation in the commit message

**Comment by jimangel** [comment]
@chrismetz09 this looks ready to merge, would you mind [squashing your commits](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits)? Feel free to reach out if I can help!

As Tim mentioned, in the future (maybe quarterly review) we should evaluate switching to docsy native mermaid rendering.

/lgtm

**Comment by kbhawkey** [comment]
Hi @chrismetz09 .
Just checking if you are actively working on this PR?
Do you need help?

**Comment by chrismetz09** [comment]
Hi @karenb-
Yes, still working this. Had some issues on the git push  --force-with-lease command yielding "rejected ... stale info" error message on practice branch. Trying again today and will report progress during call today.

tx

**Comment by jimangel** [comment]
/lgtm

I know you've been working at this one for awhile @chrismetz09 and I'm happy to see it merged as-is. I did want to call out that mermaidjs is up to version `8.10.2` now 😅

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
