### PR TITLE
WIP: Init Arabic translation

### PR DESCRIPTION
**Pull request by salehmashal**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
> 
> For pull requests on Chinese localization, set Base Branch to release-1.15
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by remyleone** [comment]
@mabunemeh @AsmaaFailat @rbenzair @ineskh

**Comment by salehmashal** [comment]
@suleimanwa

**Comment by nofalx** [comment]
duplicate with https://github.com/kubernetes/website/pull/16894 ?

**Comment by remyleone** [comment]
Could it be rebased? We also need to decide whether to close this PR or this one  #16894

**Comment by sftim** [comment]
This PR also needs a CLA signing
I don't speak Arabic, I can't usefully review
/uncc

**Comment by remyleone** [comment]
@salehmashal @nofalx Could you:
- choose one pull request to move forward and close the other? It would help focus the effort
- Ensure that all CLA are signed  Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.
- rebase on top of the master branch 
- Ensure that there is no English in the PR. Only arabic.

Let me know if you need any help on those tasks :)

**Comment by sftim** [comment]
Closed in favor of PR #19758

**Pull request closed without merging**
