### PR TITLE
Create User Journeys MVP

### PR DESCRIPTION
**Pull request by chenopis**
addresses #4548

Thanks to @abiogenesis-now, @alexcontini, @Bradamant3, @heckj, and @steveperry-53 for all your hard work!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/4630)

### CODE REVIEW

**Comment by heckj** [comment]
@chenopis I'm not sure all the relevant files are in this branch at the moment. I just took it and rebased it over master, resolved the conflict, (https://github.com/heckj/kubernetes.github.io/tree/chenopis-user-journeys) and was hoping to see the layout and structure where I could poke at adding a few things in there. Either I rebased it horribly, or some of the structure is missing that we saw in the user journey's discussions.

**Comment by chenopis** [comment]
@heckj At the moment, it's in the `/user-journeys` directory, see https://github.com/heckj/kubernetes.github.io/tree/chenopis-user-journeys/user-journeys. We're in the process of porting it over to the `/docs/home/index.md` page.

**Comment by chenopis** [comment]
We are deprecating the `/user-journeys` directory, which is now `/docs/user-journeys`, so here are the canonical preview pages now:
* [/docs/home/](https://deploy-preview-4630--kubernetes-io-master-staging.netlify.com/docs/home/)
* [/docs/user-journeys/application_developer-foundational.html](https://deploy-preview-4630--kubernetes-io-master-staging.netlify.com/docs/user-journeys/application_developer-foundational.html)
* [/docs/user-journeys/application_developer-intermediate.html](https://deploy-preview-4630--kubernetes-io-master-staging.netlify.com/docs/user-journeys/application_developer-intermediate.html)
* [/docs/user-journeys/application_developer-advanced.html](https://deploy-preview-4630--kubernetes-io-master-staging.netlify.com/docs/user-journeys/application_developer-advanced.html)

**Comment by chenopis** [comment]
@zacharysarah This should be good to go. Feel free to merge it at will.

**Comment by zacharysarah** [comment]
LSGTM (Looks So Good To Me) :shipit:

/lgtm

**Pull request merged**
