### PR TITLE
Fix API reference issue due to js versions

### PR DESCRIPTION
**Pull request by tengqm**
closes: #37861

### CODE REVIEW

**Comment by tengqm** [comment]
Related: https://github.com/kubernetes-sigs/reference-docs/pull/301

**Comment by jihoon-seo** [comment]
The "Example" button is now working in the [preview](https://deploy-preview-37977--kubernetes-io-main-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.25/#container-v1-core).

**Comment by kbhawkey** [comment]
👋 @tengqm .
Was this issue fixed already?

**Comment by tengqm** [comment]
> 👋 @tengqm . Was this issue fixed already?

Not yet in 1.25.

**Comment by kbhawkey** [comment]
> > 👋 @tengqm . Was this issue fixed already?
> 
> Not yet in 1.25.

OK. Is `main` the correct branch?

**Comment by tengqm** [comment]
@kbhawkey Proposed #39719 instead.

**Pull request closed without merging**
