### PR TITLE
[WIP] Initial version - Documentation for Garbage Collection in Kubernetes

### LINKED ISSUE #4322: Better docs for garbage collection
**This is a...** 
- [X] Feature Request
- [ ] Bug Report

## Problem 

K8s docs discuss garbage collection in different articles:

- https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
- https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
- https://kubernetes.io/docs/admin/kube-controller-manager/
- https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

Multiple topics show little to no awareness of each other. 

Descriptions of garbage collection sometimes conflict. 

No single article fully describes garbage collection as a concept or comprehensively demonstrates its implementation. 

There is currently no task for garbage collection: only two concept articles and some incidental reference material.

## Proposed Solution

1. Consolidate conceptual content at https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/.

  See _Additional information_ for more details about conceptual content.

  Explain garbage collection in Kubernetes as a whole: what it is; why and how different components (kubelet, kube-controller-manager) handle it separately; and interactions and dependencies between components' garbage collection functions.

  Provide an end-to-end description of garbage collection in a typical production environment.

2. Create a new **task article**.

  Explain how to set up garbage collection in a typical production environment: 
    - Which components to configure, and in what order, for default function
    - How to assess the health of garbage collection for a pod

## Pages to update

- https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
- https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
- https://kubernetes.io/docs/admin/kube-controller-manager/

## Additional information

Different aspects of garbage collection appear to be handled by kubelet and kube-controller-manager. It's unclear from the documentation whether these components' garbage collection functions interact and the extent to which their functions are interdependent.

It's unclear which garbage control functions are available in which versions of Kubernetes:
  -  https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/:
  "Note: Garbage collection is a beta feature and is enabled by default in Kubernetes version 1.4 and later." 
  - Is garbage collection also a beta feature in kubelet and kube-controller-manager?

Different topics' descriptions of garbage collection don't match:
  - https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/ describes garbage collection as a function of kubelet.
  - https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/ describes a controller as "the Kubernetes garbage collector"
  - https://kubernetes.io/docs/admin/kube-controller-manager/ also sets some attributes for garbage collection.

Some of the most helpful material for understanding garbage collection mentions it only incidentally: 
  - https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

Multiple topics break the style guide by making statements about the future:

   - https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/: "Some kubelet Garbage Collection features in this doc will be replaced by kubelet eviction in the future."
  - https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/: "Kubernetes version 1.7 will add an admission controller that controls user access to set blockOwnerDeletion to true based on delete permissions on the owner object, so that unauthorized dependents cannot delay deletion of an owner object."

### PR DESCRIPTION
**Pull request by daminisatya**
Fix #4322 

@zacharysarah Here's the first draft based on my initial reading. I will keep updating this Pull Request as I dig deeper. As of now, I have the following questions to add more details to the document. It would be great if you can help me find answers for them while I go through the code and experiment with the setting (Checklist to keep a track of things for clear understanding :) ). 

1. How exactly does the garbage controller delete the unused objects (Algorithm/more details)
2. Does Kube-Controller-Manager work in collaboration with Kubelet to delete unowned containers? 
3. Are there any pointers on the internal working/workflow of the garbage collector control loop?
4. Are there any configuration parameters on Controller?
5. Pointers on internal workflow on how Kubelet coordinates with Kube controller manager in maintain consistency while cleaning up containers.  How the pointers are updated?
6. Eviction policy vs Garbage Collection in Kubelet and What's the future? 
7. Tuning Garbage Collection in Kubelet. Are they any configuration parameter to change the timing of Garbage Collection. 
8. What tool do we internally use to prepare visual workflows for a better understanding?

### CODE REVIEW

**Comment by zacharysarah** [comment]
@daminisatya Heya! Thanks for opening this PR. 

First: it looks like you're not yet a member of the Kubernetes GitHub org, but you've [closed enough PRs](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Adaminisatya+is%3Aclosed) to be eligible. If you'd like to become a member, I'm happy to sponsor you. You'll need an additional sponsor; feel free to ask in [SIG Docs slack](https://kubernetes.slack.com/messages/C1J0BPD2M/details/?cdn_fallback=1).

For more information, look at the [new member issue template in k/org](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E). 

To answer your questions:

> 8. What tool do we internally use to prepare visual workflows for a better understanding?

Can you please say more about what you mean by visual workflows?

> Questions 1-7

All of these are excellent questions. In this case, SIG API Machinery handles garbage collection, so we can ask them for review:

/sig api-machinery
/cc @kubernetes/sig-api-machinery-api-reviews 

**Note:** If you ever need to find which SIG owns a particular piece of functionality, searching the [kubernetes/community](https://github.com/kubernetes/community/) repository is a great way to find the owner. (That's how I found out that SIG API Machinery includes garbage collection [in its charter](https://github.com/kubernetes/community/blob/master/sig-api-machinery/charter.md)). 

Thanks again for opening this PR, and for digging in deeply. 🙇 

@nikhita 👋 Tagging you here based on your comment on the [original issue](https://github.com/kubernetes/website/issues/4322#issuecomment-395888679).
/assign @nikhita

**Comment by daminisatya** [comment]
@zacharysarah Thank you so much for recommending me to join the Kubernetes GitHub org. I would love too and will definitely raise a request for another sponsor!

Regarding,
```
1. What tool do we internally use to prepare visual workflows for a better understanding?
````

I wanted to know if there is any standard tool to prepare such images/workflows as follows. Found this over [here](https://kubernetes.io/docs/concepts/architecture/cloud-controller/), in our documentation.

screen shot 1940-11-16 at 9 04 00 pm

```
kubernetes/community repository
````

Thank you so much for pointing me towards the community repo and the SIG-APIs group. Will definitely check this out and it's very helpful (Will answer most of my questions 😄).

**Comment by zacharysarah** [comment]
@daminisatya 👋  Feel free to reopen this PR when you're ready to resume work.

**Comment by daminisatya** [comment]
sure @zacharysarah It's an ongoing work, i think it's good to be closed. I will reopen soon :D

**Comment by daminisatya** [comment]
Will reopen the issue soon and Update the PR. I have worked on it, mentioning to avoid any duplicate.

**Comment by zacharysarah** [comment]
@daminisatya 👋 
> I wanted to know if there is any standard tool to prepare such images/workflows as follows.

Sorry for taking so long to reply! We ask for images in PNG or SVG format--but there's no standard tool. Feel free to use whatever works best for you! A diagram for garbage collection would be awesome. 👍

**Pull request closed without merging**
