### PR TITLE
Translate concepts/cluster-administration/kubelet-garbage-collection into Japanese

### LINKED ISSUE #27838: Translate concepts/cluster-administration/kubelet-garbage-collection/ into Japanese
**This is a Feature Request**

**What would you like to be added**

Translate [concepts/cluster-administration/kubelet-garbage-collection/](https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/) into Japanese.

**Why is this needed**

This page has not been translated.

**Comments**

/language ja
/assign

### PR DESCRIPTION
**Pull request by shuuji3**
✅ Resolves #27838.
📄 Page preview: https://deploy-preview-27846--kubernetes-io-master-staging.netlify.app/ja/docs/concepts/cluster-administration/kubelet-garbage-collection/

### CODE REVIEW

**Comment by kakts** [comment]
Sorry for late my review.
/lgtm

**Comment by shuuji3** [comment]
@nasa9084 すみませんtypoがあるようなのでもう一度お願いします…🙏

**Pull request merged**
