### PR TITLE
Update container-runtimes.md

### PR DESCRIPTION
**Pull request by GitHanDong**
add 安装CRI-O之前，应该先更新数据源否则有可能找不到资源。

### CODE REVIEW

**Comment by GitHanDong** [comment]
I signed it

**Review by tanjunchen — COMMENTED** [review]
/retest

**Comment by tanjunchen** [comment]
I signed it
/retest
pls sign the CLA in order for the PR to be reviewed.

**Review by tanjunchen — APPROVED** [review]
/cc@tengqm

for approve

**Pull request merged**
