### PR TITLE
supported-doc-versions翻译

### PR DESCRIPTION
**Pull request by xiexiaojing**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by SataQiu** [comment]
Thanks @xiexiaojing 
Please sign the CLA first!

**Comment by xiexiaojing** [comment]
I have just signed CLA. Thank you!

**Comment by xiexiaojing** [comment]
> Thanks @xiexiaojing
> Please sign the CLA first!

I have just signed CLA. Would you leaves an /ok-to-test message for me? Thank you very much.

**Comment by SataQiu** [comment]
Your CLA check failed. I suggest you resubmit it. 
Use `rebase` to squash the commits into one, then make a force push.
The tests are automated.

**Comment by SataQiu** [comment]
Did you configure the correct email address before `git commit` ? @xiexiaojing

**Comment by xiexiaojing** [comment]
> email

Thank you for your advice.

**Comment by xiexiaojing** [comment]
> Did you configure the correct email address before `git commit` ? @xiexiaojing

Thank you for your advice.

**Comment by xiexiaojing** [comment]
> /check-cla

Thank you!

**Pull request closed without merging**
