### PR TITLE
[WIP] static policy changes for 1.30

### PR DESCRIPTION
**Pull request by Jeffwan**
this is a placeholder PR for KEP-4176 https://github.com/kubernetes/enhancements/issues/4176

/cc @celestehorgan

### CODE REVIEW

**Comment by sftim** [comment]
Is this still needed for the v1.30 docs?

**Comment by Jeffwan** [comment]
@sftim no. The PR did not get merged into v1.30 and we postpone to v1.31 release. Should I close this one or just update to latest status?

**Comment by drewhagen** [comment]
Let’s close this one in order to properly reflect the state of the 1.30 milestone. If you could please feel free to create a new PR that targets ‘dev-1.31’ (unless we don’t have that branch yet)

Thanks!
/close

**Comment by drewhagen** [comment]
Heads up that `dev-1.31` branch is created now, if you choose to reopen this for the next release.

**Pull request closed without merging**
