### PR TITLE
Followup of #19216, setting up Konnectivity service

### PR DESCRIPTION
**Pull request by caesarxuchao**
The first commit is #19216.
The second commit includes the detailed setup.

### CODE REVIEW

**Comment by sftim** [comment]
@caesarxuchao the preview [deploy](https://app.netlify.com/sites/kubernetes-io-vnext-staging/deploys/5e7546d8a0cef9000887663e) failed. This is because the sample manifests are in the wrong place.

I'd put them in a new folder `content/en/examples/controlplane` and adjust the Markdown pages to match; you can pick a different path, but it needs to work.

To preview locally that your branch builds OK:
```bash
make docker-image && \
make docker-serve
```
(you then can either ^C to abort or visit http://localhost:1313/docs/concepts/architecture/master-node-communication/ to preview the changes)

**Comment by VineethReddy02** [comment]
Hi @caesarxuchao 
As 1.18 release is tomorrow i.e 24th March. We are not accepting any more docs for the 1.18 release branch.
Can you close this PR?

**Comment by kbhawkey** [comment]
Hello @caesarxuchao.
Could this pull request be considered a follow up PR to #19216?
The release is approaching and time is running out for accepting new commits.

**Comment by sftim** [comment]
@VineethReddy02 **I think** it's OK to omit this from milestone 1.18, and leave this PR as something that can rebase against _master_ if need be.

**Comment by sftim** [comment]
@caesarxuchao you should be able to rebase this against _master_ and then update the merge base. If you do that I think it will be OK to merge (assuming that the code is in v1.18 - I didn't check that).

**Comment by caesarxuchao** [comment]
Fixed the build issue and rebased to master in #20113.

**Pull request closed without merging**
