### PR TITLE
Add "MayRunAs" value among other GroupStrategies

### PR DESCRIPTION
**Pull request by stlaz**
Related issue: https://github.com/kubernetes/kubernetes/issues/56173
Related PR: https://github.com/kubernetes/kubernetes/pull/65135

### CODE REVIEW

**Comment by tallclair** [comment]
/lgtm
/hold

Please wait to merge until after https://github.com/kubernetes/kubernetes/pull/65135 is merged.

**Comment by zparnold** [comment]
Could you please update your local branch to HEAD `release-1.12`? It's hard to determine what changed. 😄 I've also noticed that kubernetes/kubernetes#65135 hasn't merged yet so I can wait for that.

**Comment by stlaz** [comment]
@zparnold It's weird that this happened, I believe the PR appeared correct originally. It's almost as if someone force-pushed to the release-1.12 branch.
Anyway, it's fixed now :slightly_smiling_face:

**Comment by stlaz** [comment]
Umm, https://github.com/kubernetes/kubernetes/pull/65135 was not merged yet, its milestone was changed to 1.13. Should this be reverted for 1.12 and re-created against 1.13 instead?

**Comment by stlaz** [comment]
@zparnold --^

**Pull request merged**
