### PR TITLE
Fix link for zh-cn i18n file

### PR DESCRIPTION
**Pull request by tengqm**
The previous PR rendered this `i18n/zh-cn.toml` file a dangling link.
This PR fixes it.

### CODE REVIEW

**Review by Sea-n — COMMENTED** [review]
Wow, interestingly [deploy log](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/62a356550cbfe400084a07bf) for last PR have not reported any warning about missing localized strings.
/lgtm

BTW, The `README-zh.md` file is not renamed. But for `pt-br` version, it's using `README-pt.md` too.

**Comment by tengqm** [comment]
/remove-language zh

@Sea-n Configuration files are global asset rather than language-specific. Please avoid adding language labels. Some reviewers may skip other localization PRs but they still need to review this one.

**Review by sftim — APPROVED** [review]
This is an important fix

/lgtm
/approve

**Pull request merged**
