### PR TITLE
Typo fixes, grammar, style in DNS Debugging

### PR DESCRIPTION
**Pull request by nfd9001**
Just fix some typoes and style issues in the Known Issue section.

### CODE REVIEW

**Comment by RA489** [comment]
@nfd9001 Please sign the CLA to get this merge.

**Comment by nfd9001** [comment]
Will do; gotta fix up my email situation a bit for this CLA first.

**Comment by jimangel** [comment]
@nfd9001 I'm going to close this PR for now, feel free to open once you get the email situation / CLA resolved.

Let me know if you have any questions!

/close

**Comment by nfd9001** [comment]
Hope I've figured this all out...

/reopen

**Comment by nfd9001** [comment]
@jimangel Looks like it failed to reopen with the amended commit (it was a Github-masked email before); should I just write a new PR referencing this one?

**Pull request closed without merging**
