### PR TITLE
#11986 table bug issue resolved

### PR DESCRIPTION
**Pull request by Shubhanshu88**

### CODE REVIEW

**Comment by tfogo** [comment]
Hi @Shubhanshu88, thank you for your work fixing this issue. Unfortunately this particular page is automatically generated. So the table bug will come back the next time this page is generated. I'm going to close this PR for now.

If you're interested in working on the script that generates this page, let us know, we'd be happy for you to get involved 😄 

/close

**Comment by Shubhanshu88** [comment]
@tfogo It would be great to further work on this issue. Could you please guide further as to where to look for the page exactly?

**Pull request closed without merging**
