### PR TITLE
Approval permission for 1.20 Release

### PR DESCRIPTION
**Pull request by annajung**
As the 1.20 Release Docs lead, I would like to add myself to the approver list for `dev-1.20` branch

cc @jimangel @irvifa @zacharysarah

### CODE REVIEW

**Comment by annajung** [comment]
Hi @jimangel @irvifa @zacharysarah, a friendly reminder to take a look at this when you have a second! Thank you

**Comment by jimangel** [comment]
/lgtm
/approve

Sorry to leave you hanging on this! Thanks for the ping!

**Pull request merged**
