### PR TITLE
ZH-trans: Fix invalid format

### PR DESCRIPTION
**Pull request by xichengliudui**
ZH-trans: Fix invalid format

### CODE REVIEW

**Comment by xichengliudui** [comment]
83f7a34137eb92dcb1f30025f018c53

**Comment by xichengliudui** [comment]
ac277e39356947fd4399036f8f98539

**Comment by xichengliudui** [comment]
image

**Comment by xichengliudui** [comment]
Preview

**Comment by xichengliudui** [comment]
69d975469b1a3737d16dcd826bf6c6f
5cc083e3104006dd305a445a9a22433
5667f6277ba6ac489926442bdc55f64

**Comment by chenrui333** [comment]
Thanks for the PR fix!

**Pull request merged**
