### PR TITLE
[hi] Update /docs/tutorials/kubernetes-basics/ to align with English

### PR DESCRIPTION
**Pull request by Vikash-8090-Yadav**
This https://kubernetes.io/hi/docs/tutorials/kubernetes-basics/ should align with the English one https://kubernetes.io/docs/tutorials/kubernetes-basics/

Why is this needed?

https://kubernetes.io/hi/docs/tutorials/kubernetes-basics/ looks like stale.

The issue it solves: #42735

### CODE REVIEW

**Review by aj11anuj — CHANGES_REQUESTED** [review]
<html>
<body>
<div class="gE iv gt" style="font-size: 0.875rem; cursor: auto; padding: 20px 0px 0px; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

</div><div id=":nb" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="btm"></div></div><div class="" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aHl" style="margin-left: -38px;"></div><div id=":no" tabindex="-1"></div><div id=":nd" class="ii gt" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWE6cjcxNzE1MTE0MDg5NDIwNDAzNzIiLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLFtdXQ..; 4:WyIjbXNnLWE6cjc1NDQzMDc1NDYxMDUzOTA4ODQiLG51bGwsW10sbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsW10sW10sW11d" style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":nc" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div dir="auto">- Across whole K8s site "कुबेरनेट्स" is written instead of "कुबरनेटीस", both are right... but i think there isn't any problem if "कुबेरनेट्स" will be written<br><br>Line 26: Changes aren't essential<br>Line 30: Changes aren't essential<br><br>Line 44:<br>- "करने में सहायता करता है" is more appropriate here than "करने की सहायता करता है"<br>- "चलते रहे" is more appropriate here than "चलते है"<br>- "उन्हें उन्हें" is written 2 times instead of 1<br>- "होती रहे" is more appropriate here than "होती है"<br>- "अनुभवों" is more appropriate here than "अनुभव"</div></div></div></div>
</body>
</html>

**Review by aj11anuj — COMMENTED** [review]
This change will make documentation similar to the original K8s site, although this extra documentation is better for people's understanding.

**Comment by Vikash-8090-Yadav** [comment]
@aj11anuj sorry for the late reply. I will update all mentioned changes by EOD.
Thanks!

**Comment by kundan2707** [comment]
@Vikash-8090-Yadav  most of the changes are not required.
Can you summarise intent of all these changes?

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @Vikash-8090-Yadav, thank you for your contribution!

However, most of these changes aren't required and/or are incorrect. Please can you advise why these changes need to be made, according to you?

**Comment by kumarankit999** [comment]
hey @Vikash-8090-Yadav, are you still working on this issue!!

**Comment by Vikash-8090-Yadav** [comment]
> hey @Vikash-8090-Yadav, are you still working on this issue!!

Yah.

**Comment by Vikash-8090-Yadav** [comment]
Hey @kundan2707 ,@divya-mohan0209 I raise this PR because The hindi version seems to be outdated as compared to english and mentioned on the website. 

Do lmk if this a valid Contribution.

Ps: Sorry for late response.

**Comment by kundan2707** [comment]
@Vikash-8090-Yadav 
not agree with content is outdated.

**Comment by kundan2707** [comment]
closing as no change required.
Feel free to reopen if it is really necessary

**Pull request closed without merging**
