### PR TITLE
[zh] Improve blog translation of Sidecar feature

### PR DESCRIPTION
**Pull request by wilsonwu**
Improve blog translation of Sidecar feature

### CODE REVIEW

**Review by windsonsea — COMMENTED** [review]
Sidecar 的修改值得思考，原文中：

- Sidecar 1 个
- 边车 43 个

通常修改原则为`改少不改多`，另外搜索 `./content/zh-cn/docs`  也可以发现`边车`说法比较常见。

**Comment by wilsonwu** [comment]
Thanks, need more suggestions for the Sidecar feature of K8s should translate Sidecar to 边车 or just use the English Sidecar as its name in Chinese.

**Comment by wilsonwu** [comment]
So I will update all Sidecar to 边车 in main content of this blog.

**Comment by wilsonwu** [comment]
All Done.

**Comment by tengqm** [comment]
Gate issue is transient.
/lgtm
/approve

**Review by Arhell — COMMENTED** [review]
Please re-puch commit for restart netlify

**Pull request merged**
