### PR TITLE
Merged main dev 1.31

### PR DESCRIPTION
**Pull request by chanieljdan**
This PR syncs the dev-1.31 branch with the main branch to keep the dev-1.31 branch up to date.

cc: @chanieljdan @salaxander @MaryamTavakkoli @hacktivist123 @LaurentGoderre

### CODE REVIEW

**Comment by chanieljdan** [comment]
A merge conflict which was resolved, ptal:
```
git diff content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md  
diff --cc content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
index 6a0246ecb3,90ff4e92e2..0000000000
--- a/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
+++ b/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
@@@ -297,10 -296,10 +296,14 @@@ DOWNLOAD_DIR="/usr/local/bin
  sudo mkdir -p "$DOWNLOAD_DIR"
  ```
  
 -Install crictl (required for kubeadm / Kubelet Container Runtime Interface (CRI)):
 +Optionally install crictl (required for interaction with the Container Runtime Interface (CRI), optional for kubeadm):
  
  ```bash
++<<<<<<< HEAD
 +CRICTL_VERSION="v1.31.0"
++=======
+ CRICTL_VERSION="v1.30.0"
++>>>>>>> upstream/main
  ARCH="amd64"
  curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-${ARCH}.tar.gz" | sudo tar -C $DOWNLOAD_DIR -xz
  ```

```
I accepted the incoming changes (upstream/main) with `CRICTL_VERSION="v1.30.0"` as the listed latest release as of today in the [cri-tools repo](https://github.com/kubernetes-sigs/cri-tools) is 1.30.0.

**Comment by reylejano** [comment]
> content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

Since this is for the `dev-1.31` branch which will eventually become the 1.31 docs when it merges with `main` on the 1.31 release date, I believe the `dev-1.31` version for this merge conflict
See this commit to `dev-1.31` with that change https://github.com/kubernetes/website/commit/9eccaf39d29d1d16ab7ad5166bf45ccf2ae95476

**Review by Princesso — COMMENTED** [review]
/lgtm

**Comment by chanieljdan** [comment]
> > content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> 
> Since this is for the `dev-1.31` branch which will eventually become the 1.31 docs when it merges with `main` on the 1.31 release date, I believe the `dev-1.31` version for this merge conflict See this commit to `dev-1.31` with that change [9eccaf3](https://github.com/kubernetes/website/commit/9eccaf39d29d1d16ab7ad5166bf45ccf2ae95476)

Thanks @reylejano for the feedback! I created an updated PR to reflect this change: https://github.com/kubernetes/website/pull/46642

**Pull request closed without merging**
