### PR TITLE
Merge missing translations

### PR DESCRIPTION
**Pull request by bep**
This is the last batch of "language related changes" from me for now.

**Note that before this gets merged, the dummy Norwegian translation needs to be disabled in config.toml.**

It's easier to get a grasp of this PR by looking at the content tree for the Norwegian translation:

```bash
content/no
├── _common-resources
│   └── index.md
├── _index.html
├── blog
│   ├── _index.md
│   └── _posts
│       └── 2018-09-06-2018-steering-committee-election-cycle-kicks-off.md
├── case-studies
│   ├── _index.md
│   └── adform
│       └── index.html
└── docs
    ├── _index.md
    ├── contribute
    │   └── _index.md
    ├── home
    │   └── _index.md
    ├── reference
    │   ├── _index.md
    │   └── glossary
    │       ├── container.md
    │       └── index.md
    ├── setup
    │   ├── _index.md
    │   └── pick-right-solution.md
    └── tutorials
        └── kubernetes-basics
            └── _index.md
```

In summary, this is what's needed for a new language:

* The section content files (see "_index*", esp. note the home page) with its menu definitions. 
* A translation of the language bundle in /i18n
* A language configuration in config.toml

In that language configuration, you can specify an ordered list of one or more languages to fill inn missing translations from. In this PR, `no` has this set to `language_alternatives = ["en"]`.

This language merging has an effect in

* Blog. The last blog entry from `language_alternatives` will be shown on front page if not translated. Also, the archive is merged.
* Docs browser
* Docs left tree nav
* Glossary page, glossary tooltip
* Case studies

Links to "foreign language" is marked with its language and opens up in a new window.

There is certainly more to be done in this area (the glossary page contains some untranslated text, and the user journey is only available in English, to mention some examples. But think now at least it makes sense to let other languages in.)

This PR updates Hugo to 0.48. That is built with Go 1.11, which makes the relevant template constructs much simpler.

/cc @zacharysarah @chenopis

### CODE REVIEW

**Comment by bep** [comment]
There seems to be a logical flaw in the blog archive ... I will fix that tomorrow.

**Comment by bep** [comment]
Re. my comment above: I found a bug in Hugo that needs to be resolved for this PR to work 100%. I will get that into a planned released for Monday.

**Comment by bep** [comment]
I have bumped the Hugo versions to 0.49 in this PR, which has fixed the "language merge" issue on the blog archive.

/cc @zacharysarah

**Comment by zacharysarah** [comment]
@bep 👋 Thanks for your work here. Some questions:

> **Note that before this gets merged, the dummy Norwegian translation needs to be disabled in config.toml**

To disable the dummy translation, is it sufficient to remove [this block](https://github.com/kubernetes/website/blob/master/config.toml#L139-L146) from `config.toml`:
```
[languages.no]
title = "Kubernetes"
description = "Production-Grade Container Orchestration"
languageName ="Norsk"
weight = 3
contentDir = "content/no"
# A list of language codes to look for untranslated content, ordered from left to right.
language_alternatives = ["en"]
```
...or must we also remove file content: `i18n/no.toml`, `content/no/`?

I can't think of a good reason to keep the dummy files ☝️ after this PR merges, but am curious as to whether they must be removed entirely for Hugo to be happy or can simply be disabled in `config.toml`.

**Comment by bep** [comment]
@zacharysarah No, it's easier than that, see my comment in `config.toml`:

```toml
# This is currently used for testing.
# disableLanguages = ["no"]
```

The above can also be set as an OS environment variable (I will dig up the syntax if you need it), and its main motivation is to use when you're in the process of translating a new language.

**Comment by zacharysarah** [comment]
@bep 

> No, it's easier than that, see my comment in config.toml:

Cool! :sparkles: From the OP:

> Note that before this gets merged, the dummy Norwegian translation needs to be disabled in config.toml.

I  [disabled the dummy translation](https://github.com/kubernetes/website/pull/10355/commits/699be41df0e500058ecb4edc41ba007e886cf2fc) in a separate commit. It works in the preview, so let's go ahead and merge.

/cc @lucperkins 👋 You may have to resolve merge conflicts in #10373 and #10381 due to changes in Makefile.

**Pull request merged**
