### PR TITLE
update deployment sample, due to deprecated option

### PR DESCRIPTION
**Pull request by sharet-adl**
Creating a deployment using 'kubectl run' command was deprecated and is not supported anymore, starting with 1.18 version. In order to keep the example as relevant as possible, all 3 pods were kept.

Couple of changes:
- fix example to use 'kubectl create deployment' command, and scaled it up explicitly
- fix missing label for both Deployment and Service
- update label key, from 'run' to 'app', as deployments automatically add the label with this key
- update comment on how label's key could have used 'run' and 'app' values
- update pods names and internal hostnames - which are based on the replicaSet (eg. hostnames-632524106).

### CODE REVIEW

**Comment by sharet-adl** [comment]
Please have a look, /assign @sftim

**Comment by bodote** [comment]
update label key, from 'run' to 'app', as deployments automatically add the label with this key in https://deploy-preview-21065--kubernetes-io-master-staging.netlify.app/docs/tutorials/kubernetes-basics/expose/expose-interactive/  is not yet there, I'm still seeing "run" instead of "app"

**Comment by sftim** [comment]
Looking at an old comment: https://github.com/kubernetes/website/pull/21065#issuecomment-634182505

I'm not sure if there is a defect here or not. If there is, please file a new issue.

**Pull request merged**
