### PR TITLE
Removed docker logo

### PR DESCRIPTION
**Pull request by RayAsh37**
I have read all the guidelines and have tried my best to adhere to them. As mentioned in issue #30948 I have updated the visual representation for a container without reference to the original docker logo. Since it was an image, I had to replace the entire file and also created a SVG for reference to any future contributors.

This is my second PR regarding the same issue as my previous PR #30978 was a bit of a blunder on my part as I am new to Git.

Any feedback and suggestions/criticism are very much welcome/appreciated.

### CODE REVIEW

**Comment by RayAsh37** [comment]
> /kind cleanup

what do I need to do?

**Comment by nate-double-u** [comment]
Hi @RayAsh37, thanks for this! We can close the other issue as this looks like it's sorted all the git issues we were running into.

Deploy preview: https://deploy-preview-31338--kubernetes-io-vnext-staging.netlify.app/docs/concepts/security/overview/

/lgtm

**Comment by RayAsh37** [comment]
@nate-double-u thanks for being so patient with me. Due to the mistakes, I have learnt a little more about Git and contributing to Open Source as a whole.

**Comment by nate-double-u** [comment]
No problem, happy to help!

**Comment by RayAsh37** [comment]
@celestehorgan hey, I had to create a new PR (but with the same changes) since I messed up my previous one. Please review.

**Comment by sftim** [comment]
/approve

Nice cleanup

**Pull request merged**
