### PR TITLE
Fix form allignment in mobile view.

### LINKED ISSUE #16817: Fix form allignment in mobile view.
**This is a Bug Report**

**Problem:**
The alignment of the form is not proper.
Screenshot from 2019-10-11 09-00-42

**Proposed Solution:**
The alignment of the form should be proper.
**Page to Update:**
https://kubernetes.io/...

### PR DESCRIPTION
**Pull request by Utwo**
Resolve #16817

### CODE REVIEW

**Comment by Utwo** [comment]
signed

> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> memo **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
>     * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
>     * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> 
>     * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> 
>     * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

done

**Comment by Utwo** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> memo **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
>     * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
>     * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> 
>     * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> 
>     * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

done

**Comment by tfogo** [comment]
Hi @Utwo, thanks for signing the CLA. Unfortunately the commits in the PR aren't associated with your GitHub user, so the CLA check is still failing. Can you please update the authorship on the commits to make sure the email address matches an email address associated with your GitHub account? Thanks!

**Comment by Utwo** [comment]
It should be ok now. 
It's quite complicated to follow all the necessary steps in order to sign the CLA.

**Comment by kbhawkey** [comment]
Hello @Utwo . Thanks for submitting this PR.
I took a few snapshots of the changes on my desktop. Is this what you expect?

**Small screen**:

image

**Medium screen**:
image

**Comment by kbhawkey** [comment]
Ping @Utwo

**Comment by Utwo** [comment]
Should work as expected now. Thank you :)

**Comment by kbhawkey** [comment]
@Utwo , the vertical alignment is an improvement. The distance between the text area and the button is less. If you made margin-right=15px, I think the distance would be the same as the current home page. Do you think the smaller distance between the two components is better?

small size:
image

desktop size:
image

current homepage, desktop size:
image

**Comment by Utwo** [comment]
I didn't think that smaller distance between input and button will be a problem. But it's ok, I've added a new commit with a bigger margin-right.

**Comment by kbhawkey** [comment]
Thanks, @Utwo .
/lgtm

**Comment by kbhawkey** [comment]
FYI: This change alters the home page (mobile and desktop).
/cc @zacharysarah @kbarnard10

**Pull request merged**
