### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by rikust**
Fixed codes on iptables.
/assign @kbarnard10

### CODE REVIEW

**Comment by rikust** [comment]
I've sign the CLA signature, please check.
/assign @kbarnard10

**Comment by annajung** [comment]
Hi there, could you rebase to make sure the file change only contains your changes?

**Comment by kbhawkey** [comment]
Hi @rikust .
Would you rebase your changes. Is the `dev-1.18-ja.2` branch correct? I would expect to see one or two commits containing
your updates.

/cc @kubernetes/sig-docs-ja-reviews

**Pull request closed without merging**
