### PR TITLE
fix Docker file link

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/website/pull/24690

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by seokho-son** [comment]
@npu21 Thank you for the contribution.
Please squash the commits into one :)

**Comment by seokho-son** [comment]
Ping @npu21 :)

**Comment by seokho-son** [comment]
The content in this PR was applied already through https://github.com/kubernetes/website/pull/25103 for Ko dev branch management (syncing with master branch). I'd like to close this PR. Thank you for your contribution.

**Pull request closed without merging**
