### PR TITLE
[ja] sync a link with en

### PR DESCRIPTION
**Pull request by ziyi-xie**
Sync with en https://github.com/kubernetes/website/pull/39936

>  content/ja/docs/concepts/scheduling-eviction/assign-pod-node.md

### CODE REVIEW

**Review by nasa9084 — COMMENTED** [review]
/assign
/approve

**Comment by ziyi-xie** [comment]
@atoato88 @t-inu 
Could you review this PR at your convenient time please? Thanks in advance!

**Comment by atoato88** [comment]
/lgtm

Thank you!! :smile:

**Comment by ziyi-xie** [comment]
> /lgtm
> 
> Thank you!! 😄

Thank you so much for your quick response and review!

**Pull request merged**
