### PR TITLE
Update partner.ps

### PR DESCRIPTION
**Pull request by jtonello**
Update Puppet content.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6570)

### CODE REVIEW

**Comment by ahmetb** [comment]
@chenopis Do you know who's responsible for looking at Partners content?

**Comment by chenopis** [comment]
@ahmetb It's the CNCF folks. @dankohn would know. However, since it's a simple update, I think we can clear it.

**Comment by dankohn** [comment]
Yes, @kbarnard10 and @zacharysarah from CNCF manage that content.

**Comment by chenopis** [comment]
The copy and link look good in the [preview](https://deploy-preview-6570--kubernetes-io-master-staging.netlify.com/partners/), so /LGTM

**Pull request merged**
