### PR TITLE
Minor fixes in container runtime install and kubeadm install instruct…

### PR DESCRIPTION
**Pull request by naeem98**
…ions

### CODE REVIEW

**Comment by naeem98** [comment]
@tengqm please review

**Comment by neolit123** [comment]
/lgtm
repeating sudo a number of times seems redundant in comparison to a message on top of each document in the lines of "some commands require root privileges", but if this is the preference, fine by me.

**Comment by naeem98** [comment]
Updating these commands to have sudo aligns with the instructions on these and rest of the docs.

**Comment by zacharysarah** [comment]
@neolit123 My preference is to omit `sudo` from commands, but I'll defer to your judgment and @kubernetes/sig-cluster-lifecycle-pr-reviews.

**Comment by naeem98** [comment]
Thanks @zacharysarah If we decide to remove sudo then we should remove from other install instructions as well to keep them in sync. 
I find it easier to copy/paste and run commands with sudo, saves a lot of time. Also, it is not recommended to run everything with root. 
I will leave it to reviewers to make that call.

**Comment by neolit123** [comment]
i think i'm overall fine with the change.

> I find it easier to copy/paste and run commands with sudo, saves a lot of time

this seems like one of the good reasons.

> Also, it is not recommended to run everything with root.

there is also the case where a regular user login with `sudo` is mandatory, instead of a root login.

**Comment by tengqm** [comment]
> i think i'm overall fine with the change.
> 
> > I find it easier to copy/paste and run commands with sudo, saves a lot of time
> 
> this seems like one of the good reasons.
> 
> > Also, it is not recommended to run everything with root.
> 
> there is also the case where a regular user login with `sudo` is mandatory, instead of a root login.

Exactly, for most boxes I'm using in my working env, I cannot recall the root password. For some boxes, I simply don't know it. I'm pretty satisfied with a `sudoer` account. :)

**Comment by zparnold** [comment]
@naeem98 just to keep things clear, I'm going to close this, but we really do want your contribution! So if you have a chance to address the comments and rebase this PR I'd be happy to help you get this merged!

/close

**Pull request closed without merging**
