### PR TITLE
Update persistent-volumes.md

### PR DESCRIPTION
**Pull request by lushunl**

### CODE REVIEW

**Comment by tengqm** [comment]
what's the goal of this PR? Adding an example for PV?
How about adding an example YAML and referencing it from the page?

**Comment by jimangel** [comment]
Hey there! @lushunl, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
Hi @lushunl .
Any progress on signing the CLA?

**Comment by tengqm** [comment]
I'm closing this due to CLA issue open for too long. Please feel free to reopen when the agreement is signed.
/close

**Pull request closed without merging**
