### PR TITLE
remove https://kubernetes.io/docs/concepts/security/overview/

### LINKED ISSUE #36591: Update or remove https://kubernetes.io/docs/concepts/security/overview/
**This is a Refactor request**

**Problem:**
The overview page at https://kubernetes.io/docs/concepts/security/overview/ is a bit out of date:
- no reference to https://kubernetes.io/docs/concepts/security/security-checklist/
- I'm not convinced that the “Four Cs of cloud native security” model is useful for readers to learn
- **Does not align with other CNCF documents, such as https://github.com/cncf/tag-security/tree/main/security-whitepaper**

**Proposed Solution:**
Either:
- remove https://kubernetes.io/docs/concepts/security/overview/ outright
- migrate content from https://kubernetes.io/docs/concepts/security/overview/ into several destinations
  - https://kubernetes.io/docs/concepts/security/ _(keep this brief but on-point)_
  - https://kubernetes.io/docs/concepts/security/security-checklist/
  - https://kubernetes.io/docs/concepts/security/controlling-access/
  
  &hellip;and then redirect https://kubernetes.io/docs/concepts/security/overview/ to https://kubernetes.io/docs/concepts/security/

**Page to Update:**
https://kubernetes.io/docs/concepts/security/overview/

**Additional Information:**
/sig docs
/sig security
/language en

### PR DESCRIPTION
**Pull request by satyampsoni**
fixes #36591

### CODE REVIEW

**Comment by tengqm** [comment]
I don't think we will drop this page completely.
A better option would be reorg these contents to make sure they are telling a consistent story with some logic behind them.

**Comment by satyampsoni** [comment]
@sftim what's your view on it?

**Comment by sftim** [comment]
I've made https://github.com/kubernetes/website/pull/43176 - that's broadly how I'd like things to look.

**Comment by sftim** [comment]
/hold

I don't want to do the removal without at least also adding a redirect.

**Pull request closed without merging**
