### PR TITLE
Remove as reviewer/approver for it docs

### PR DESCRIPTION
**Pull request by rlenferink**
During bootstrapping of the Italian localization I helped out as reviewer/approver. Italian localization now has 3 approvers already. I wish to be removed (as non-italian).

/cc @sftim 
/assign @sftim

### CODE REVIEW

**Comment by rlenferink** [comment]
> 
> 
> /lgtm

Thanks. Can you approve as well (since I'm not root approver)? :)

**Comment by sftim** [comment]
It's best to have another person's approval for a change like this.

**Comment by sftim** [comment]
@kubernetes/sig-docs-en-owners is this OK to merge?

**Comment by kbhawkey** [comment]
I think this change is okay as long as there are three reviewers listed for the localization team.

**Comment by rlenferink** [comment]
The localization team will (after removal) still have 3 reviewers.

**Pull request merged**
