### PR TITLE
fixed CNCF Landscape iframe which  uses wrong colors

### LINKED ISSUE #44803: CNCF Landscape iframe uses wrong colors
**This is a Bug Report**

**Problem:**
https://github.com/kubernetes/website/blob/06fb191b99a1a248cc8c697cd5170aea195412cd/layouts/shortcodes/cncf-landscape.html uses the wrong background color(s); it's `#d95e00` but should be `#3371e3` (Kubernetes blue). I think the orange color was copied from https://github.com/kubernetes/website/blob/06fb191b99a1a248cc8c697cd5170aea195412cd/data/announcements/scheduled.yaml#L214 by mistake.

**Proposed Solution:**
Revise the shortcode. Consider making the color be set once and then reused (“[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)”).

**Page to Update:**
You would see the change on https://kubernetes.io/partners/

We should use blue backgrounds whether or not an announcement banner is showing.

**Additional Information:**
PR https://github.com/kubernetes/website/pull/44792 updated the shortcode.

/area web-development
/triage accepted
/priority backlog

---

If fixing this, consider also moving the iframe scroll-margin-top fix to be more general.
See https://github.com/kubernetes/website/pull/44792#discussion_r1458153262 and https://github.com/kubernetes/website/issues/29909

### PR DESCRIPTION
**Pull request by aakashdeshamne**
fixed #44803

### CODE REVIEW

**Review by Gauravpadam — COMMENTED** [review]
The preview at
https://deploy-preview-44814--kubernetes-io-main-staging.netlify.app/partners/ LGTM

/lgtm
Thanks for the PR @aakashdeshamne

**Comment by aakashdeshamne** [comment]
@Gauravpadam thanks for review

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by aakashdeshamne** [comment]
> lgtm

@Arhell Could you please approve the PR if the changes are fine?

**Comment by sftim** [comment]
Thanks

/approve

**Pull request merged**
