### PR TITLE
Add SIG Cloud Provider spotlight article.

### PR DESCRIPTION
**Pull request by fsmunoz**
SIG Cloud Provider article.

* Original PR in `contributor-site`: https://github.com/kubernetes/contributor-site/pull/477

_Please review the original PR instead of this one_; I will copy the final version of the `contributor-site` here. I will keep this as draft until the original PR is reviewed, and content synced.

### CODE REVIEW

**Comment by sftim** [comment]
/hold

pending appropriate reviews on the main article, and assignment of agreed publication date

**Comment by fsmunoz** [comment]
Synced content with `contributor-site`, changed date.

**Comment by fsmunoz** [comment]
/rename Add SIG Cloud Provider spotlight article.

**Comment by fsmunoz** [comment]
/retitle Add SIG Cloud Provider spotlight article.

**Pull request merged**
