### PR TITLE
Update daemonset.yaml

### PR DESCRIPTION
**Pull request by chrissound**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.11 Features: set Milestone to 1.11 and Base Branch to release-1.11
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
why send this PR, ds is in V1 now.

**Comment by chrissound** [comment]
https://stackoverflow.com/questions/50678799/daemonset-in-version-v1-cannot-be-handled-as-a-daemonset-no-kind-daemonset

**Comment by steveperry-53** [comment]
I'm going to close this. The person in the StackOverflow post was using an old version of Kubernetes.
DaemonSet v1 is fine.

**Comment by chrissound** [comment]
That person would be me :). What do you mean by using an old version of k8s?

**Comment by steveperry-53** [comment]
@chrissound If you're using a version of the Kubernetes API server that is earlier than 1.9, then apps/v1 DaemonSet v1 is not supported. For example, if your cluster is running version 1.8 of the Kubernetes API server, you would use apps/v1beta2 Daemonset.

The docs reflect version 1.11. When you opened this PR, the docs reflected version 1.10. In either case, the API server supports apps/v1 DaemonSet.

To check your version, enter `kubectl version`. 

Here's the same topic in the 1.8 docs:
https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/daemonset/

At any rate, my best guess is that your Kubernetes API server is version 1.8. If you are using 1.9 or later, and still having this problem, please reopen this PR.

**Comment by chrissound** [comment]
Thanks for the explanation. I was running running 1.8 indeed.

**Pull request closed without merging**
