### PR TITLE
Mark 1.25 as End-of-Life (EOL) release

### PR DESCRIPTION
**Pull request by xmudrii**
This PR marks 1.25 as End-of-Life (EOL) release. Follow up on #43576

/assign @saschagrunert @cpanato @Verolop
cc @kubernetes/release-engineering 
/hold
to be merged after 2023-10-28

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

**Review by dipesh-rawat — COMMENTED** [review]
> / hold
> to be merged after 2023-10-28

Unholding as mentioned date reached: 2023-10-28
/unhold

**Pull request merged**
