### PR TITLE
Localize “email address” placeholder on home page

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/website/issues/20571
/language hi

### CODE REVIEW

**Comment by sftim** [comment]
@kubernetes/sig-docs-hi-reviews could you take a look at this PR?

**Comment by kbhawkey** [comment]
Hello @npu21 .
This pull request has been open for some time. 
Does it make sense to add this change if the `hi` localization team is not active or close this PR?

**Comment by kbhawkey** [comment]
Hello @npu21 .
I plan on closing this pull request because the `hi` team appears to be inactive.
/close

**Pull request closed without merging**
