### PR TITLE
Updated network-policies.md for default deny all ingress and egress traffic

### PR DESCRIPTION
**Pull request by sujaypillai**
1. Updated [network-policies.md ](content/en/docs/concepts/services-networking/network-policies.md) for the section "**Default deny all ingress and all egress traffic**" to refer to the proper file.
2. Updated [network-policy-default-deny-all.yaml
](content/en/examples/service/networking/network-policy-default-deny-all.yaml) for proper formatting.

Fixes [#19047](https://github.com/kubernetes/website/issues/19047)

### CODE REVIEW

**Comment by danwinship** [comment]
/lgtm
@sujaypillai can you add "Fixes #19047" to the initial description?

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-19052--kubernetes-io-master-staging.netlify.com/docs/concepts/services-networking/network-policies/

**Pull request merged**
