### PR TITLE
Enhance Ko translation for working-with-objects/labels

### PR DESCRIPTION
**Pull request by paikwiki**
There is a word, "and" among operators. It confuses that "and" is in operators. So I translate it in Korean.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@paikwiki
Pls sign the CLA in order for the PR to be reviewed.

**Comment by paikwiki** [comment]
@Arhell 
Thanks for your quick reply. I signed the CLA now.

**Comment by pjhwa** [comment]
@paikwiki Thank you for your contribution!

/lgtm

**Pull request merged**
