### PR TITLE
Update the `PreferNominatedNode` from ALPHA to BETA

### PR DESCRIPTION
**Pull request by chendave**
xref #https://github.com/kubernetes/enhancements/issues/1923

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/lgtm

And I suppose the other cascading changes will be applied by an automation script.

**Comment by chendave** [comment]
> And I suppose the other cascading changes will be applied by an automation script.

Yes, I did that initially, pls see: https://github.com/kubernetes/website/commit/1c73213cfa1be0d0b3344497f1383f6a5a70bf19,
but that needs involvement from lots of `OWNERS`, so let's just leave that for a auto-generated PR instead.

**Comment by chendave** [comment]
/assign @tengqm 

Hi Qiming, could you pls help to approve this, we still need get this doc in 1.22 for beta, pls see: https://github.com/kubernetes/enhancements/issues/1923

**Comment by chendave** [comment]
/hold

this is already covered by https://github.com/kubernetes/website/pull/28644, will close this one when that is got merged.

**Comment by PI-Victor** [comment]
also, this shouldn't be open against main the way that it is right now, it should be open against dev-1.22. or split and add 1.21 changes to main and 1.22 changes to dev-1.22

**Comment by chendave** [comment]
> also, this shouldn't be open against main the way that it is right now, it should be open against dev-1.22. or split and add 1.21 changes to main and 1.22 changes to dev-1.22

thanks @PI-Victor , I am going to close this one,  https://github.com/kubernetes/website/pull/28644 is opened on the right code branch.

**Pull request closed without merging**
