### PR TITLE
Updating the social sharing image to proper size

### PR DESCRIPTION
**Pull request by stphnwlsh**
### Description
The current social sharing image set in the meta tags is broken and not showing the branding as it is not the correct size according the current standards.

image

### Change
This change adds a new image in the correct format and then updates the meta tags to use the new image.

### CODE REVIEW

**Comment by NitishKumar06** [comment]
Hi @stphnwlsh , It is recommended not to directly commit to the main branch. I'd recommend you to go through the basics of git-github first and raise a PR again since I observed that some of the checks are not marked. You can watch @kunal-kushwaha video on Youtube related to GIt-Github. Here's the [link](https://youtu.be/apGV9Kg7ics)

**Comment by stphnwlsh** [comment]
Thanks!! Will do

**Comment by Sea-n** [comment]
Good idea!

But I wonder are there any official branding guideline for Kubernetes?

I only found this website: https://cncf-branding.netlify.app/projects/kubernetes/
Which doesn't seems like official one.

**Comment by Sea-n** [comment]
BTW, the original image have transparent background, the new one are white background. But it just a non-blocking nitpick. 😝

**Comment by reylejano** [comment]
I believe the CNCF curates the official artwork for Kubernetes in this repository 
https://github.com/cncf/artwork/tree/master/projects/kubernetes
We may have to check with the CNCF for any updated artwork

**Comment by stphnwlsh** [comment]
> I believe the CNCF curates the official artwork for Kubernetes in this repository https://github.com/cncf/artwork/tree/master/projects/kubernetes We may have to check with the CNCF for any updated artwork

There is a stacked one but it would need to be formatted to fit the right size. Might make a PR there first.

**Comment by stphnwlsh** [comment]
> BTW, the original image have transparent background, the new one are white background. But it just a non-blocking nitpick. 😝

I did think about this but there was some reason I didn't go transparent. No idea now 🤣

**Pull request closed without merging**
