### PR TITLE
Kubernets blog: 'The Future of Cloud Providers in Kubernetes'

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

Date left out as per instructions in https://kubernetes.io/docs/contribute/start/#write-a-blog-post 

co-authored with @cheftako @mcrute

### CODE REVIEW

**Comment by kbarnard10** [comment]
@andrewsykim The preview looks good to me. I can publish this on Wednesday, does that work for you?

**Comment by andrewsykim** [comment]
Wednesday sounds good to me! Thank you @kbarnard10

**Pull request merged**
