### PR TITLE
Update define-environment-variable-container.md

### PR DESCRIPTION
**Pull request by jsonpang**
补充完整执行yaml文件后，补充命令如何查看效果

### CODE REVIEW

**Comment by jsonpang** [comment]
i signed it

**Comment by jsonpang** [comment]
i signed it

**Comment by xichengliudui** [comment]
Agreement (CLA).

**Comment by markthink** [comment]
@jsonpang 参考[翻译指引](https://github.com/k8smeetup/k8s-official-translation)

**Comment by tanjunchen** [comment]
@jsonpang
any progress?

**Comment by tanjunchen** [comment]
This pr has not been updated for a long time, I temporarily closed it for the following reasons:
1. pr has not been updated for a long time.
2. our first step is to be as consistent as possible with the en directory. If you want to add any content, you can submit pr to the upstream en first.
Thank you, if in doubt, ping me.
/close

**Pull request closed without merging**
