### PR TITLE
contents/doc: Replace every {{< param "githubbranch" >}} into --> master

### PR DESCRIPTION
**Pull request by remicres**
The documentation contains lot of dead links, at least in the FR / storage section.
I have noticed that the `{{< param "githubbranch" >}}` was in other portions of the doc, and seems outdated.
I have replaced every occurrence with "master".

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi, you may need to take several actions:
1. Sign a CLA
2. Submit only a language for a PR
3. Change a few for your first PR

**Comment by remicres** [comment]
Hi @windsonsea 

I have signed the CLA 40 min ago. The status is still not updated though.

Regarding 2. and 3. I don't understand. Do you mean that I submit one PR for one language? The fix I made applies for many languages

**Comment by windsonsea** [comment]
@remicres Yes, one PR for one language.
Try to modify and run `git commit --amend --no-edit` and `git push origin <your-branch> -f` to refresh the status if you have signed the CLA.

**Comment by remicres** [comment]
Okay its a bit complicated I guess I'll open new PR for each language

**Pull request closed without merging**
