### PR TITLE
Demo for dismissing announcement banners

### PR DESCRIPTION
**Pull request by Gauravpadam**
A demonstration for #44435

### CODE REVIEW

**Comment by Gauravpadam** [comment]
/hold

This is just for demonstration purposes

**Review by Princesso — COMMENTED** [review]
/area web-development

**Comment by sftim** [comment]
No longer needed; https://github.com/kubernetes/website/pull/44435 has been approved.

**Comment by Gauravpadam** [comment]
And this is...
/close

**Pull request closed without merging**
