### PR TITLE
Bro i am in contest for request 4 pull request can you help pleasae

### PR DESCRIPTION
**Pull request by dupatel000**

### CODE REVIEW

**Comment by sftim** [comment]
@dupatel, what kind of help would you like here?

If you'd be willing to, please consider editing the PR title to use inclusive language (removing “Bro”). The Kubernetes project believes that [inclusive is better than exclusive](https://github.com/kubernetes/community/blob/master/values.md#inclusive-is-better-than-exclusive).

**Comment by mrbobbytables** [comment]
We are not participating in hacktoberfest
/close

**Comment by amarlearning** [comment]
> @dupatel, what kind of help would you like here?
> 
> If you'd be willing to, please consider editing the PR title to use inclusive language (removing “Bro”). The Kubernetes project believes that [inclusive is better than exclusive](https://github.com/kubernetes/community/blob/master/values.md#inclusive-is-better-than-exclusive).

Hey @sftim, you mistakenly referred to wrong person. He is @dupatel000

**Comment by sftim** [comment]
Oops, sorry.

**Comment by samvdkris** [comment]
Dude if you're gonna make a spam PR, at the *very* least spell it correctly.

**Pull request closed without merging**
