### PR TITLE
Update kubespray docs.

### PR DESCRIPTION
**Pull request by mzaian**
Update kubespray.md docs for different languages based on the official documentation on kubespray.io

### CODE REVIEW

**Comment by kbhawkey** [comment]
👋 @mzaian . Thanks for contributing. We recommend that you open individual PRs for the changes in each language.
Ping the localizations teams for a review,
/cc @kubernetes/sig-docs-fr-reviews , @kubernetes/sig-docs-ja-reviews , @kubernetes/sig-docs-ko-reviews,  @kubernetes/sig-docs-zh-reviews

**Comment by jihoon-seo** [comment]
/approve
for the Korean page.

**Comment by howieyuen** [comment]
/hold
for zh-cn page, Chinese content haven't update.

**Comment by rekcah78** [comment]
/approve
for the French page.

**Comment by inductor** [comment]
/hold

Japanese concent also needs an individual update.

**Comment by mzaian** [comment]
> /hold for zh-cn page, Chinese content haven't been updated.

@howieyuen Missed on that and now updated it.

**Comment by howieyuen** [comment]
> > /hold for zh-cn page, Chinese content haven't been updated.
> 
> @howieyuen Missed on that and now updated it.

Thx

**Comment by mzaian** [comment]
> /hold
> 
> Japanese concent also needs an individual update.

@inductor Updated the jp page as well. Please check.

**Comment by nasa9084** [comment]
/approve
for Japanese page

**Comment by kbhawkey** [comment]
I think we have review/approval from the localization teams. Thank you!
/lgtm

**Pull request merged**
