### PR TITLE
[mistranslated] maxUnavailable rounds down, maxSurge rounds up.

### PR DESCRIPTION
**Pull request by aeomhs**
## summary
has been mistranslated. 🥺
`rounding down` is `내림` in Korean.
`rounding up` is `올림` in Korean.

## description
I understand by default, maxUnavailable is 25% and also maxSurge is 25%.
I wanted to know how to work when desired replica was 1.
But `반올림` is meaning [Round](https://pkg.go.dev/math#Round) in Korean.
so I can't understand that both maxUnavailable and maxSurge be 0 (in RollingUpdate strategy). 🙈

And finally I knew that has been mistranslated. 👀
in English documentation,
<image width="480" src="https://user-images.githubusercontent.com/38370792/158593410-36c06658-5231-4366-86d4-66795c7ce635.png"/>

and code said.
[deployment_util.go > maxSurge](https://github.com/kubernetes/kubernetes/blob/7152825c0695d62fe06b47cc3e1699095290d73f/pkg/controller/deployment/util/deployment_util.go#L456)
[deployment_util.go > ResolveFenceposts](https://github.com/kubernetes/kubernetes/blob/7152825c0695d62fe06b47cc3e1699095290d73f/pkg/controller/deployment/util/deployment_util.go#L849)
[util/instr.go > GetScaledValueFromIntOrPercent](https://github.com/kubernetes/kubernetes/blob/7152825c0695d62fe06b47cc3e1699095290d73f/staging/src/k8s.io/apimachinery/pkg/util/intstr/intstr.go#L146)

Thanks. 🙇‍♂️

> 리뷰를 한국분이 하시는군요 🥲
~~못하는 영어를 써가면서 .. 작성했..~~
오역이 있는 것 같아서 제보드렸습니다!
감사합니다 🙇‍♂️

> ~~커밋 메시지에 `롤링 업데이트에서 수행하는 무중단 업데이트가 이루어지지 않습니다.` 라고 작성했는데요,
생각해보니 replica=1, maxUnavailable=1, maxSurge=0 이면 중단이 발생할 수 있으니,,
무중단과는 별개의 이야기인 것 같습니다.. 😂~~
커밋 메시지를 영어로 수정했습니다.

## appendix
[올림 | Korean dictionary](https://krdict.korean.go.kr/m/eng/searchResultView?wordMatchFlag=N&currentPage=1&mainSearchWord=%EC%98%AC%EB%A6%BC&sort=&searchType=W&proverbType=&exaType=&ParaWordNo=68195&font_size=12&nationCode=6&nation=eng&viewType=A)
[반올림 | Korean dictionary](https://krdict.korean.go.kr/m/eng/searchResultView?wordMatchFlag=N&currentPage=1&mainSearchWord=%EB%B0%98%EC%98%AC%EB%A6%BC&sort=&searchType=W&proverbType=&exaType=&ParaWordNo=57172&font_size=12&nationCode=6&nation=eng&viewType=A)

### CODE REVIEW

**Comment by ianychoi** [comment]
@aeomhs Thank you for your PR - looks great.
Would you change your commit message in English, not Korean? Then I can approve

**Comment by ianychoi** [comment]
Note: usually writing commit messages in English is a great idea so that the repository with commit can be accessible to all the global people. You can definitely contain PR descriptions in Korean since there are Korean L10n Docs reviewers who understand Korean so well :)

**Comment by aeomhs** [comment]
@ianychoi 
Thanks for the advice! 😆
I lacked caring. 🥺
I fixed the commit message in english.

Please let me know if there are any additional corrections to be made.  :)

**Comment by ianychoi** [comment]
(Oh ideally reflecting to current working branch is a better idea but I already approved it - hope it is fine)

**Pull request merged**
