### PR TITLE
Fixed the Link for API compatibility and Kubelet Device Manager API Versions.

### LINKED ISSUE #38858: Invalid links
**This is a Bug Report**

**Problem:**
Links for **API compatibility** and **Kubelet Device Manager API Versions** under [Device Plugins](https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/#device-plugins) in [Upgrade A Cluster](https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade) task are Invalid. It gives a **404 Page not found** error.

**Proposed Solution:**
For **API compatibility** the link should be: `https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#api-compatibility`
For **Kubelet Device Manager API Versions** the link should be: `https://kubernetes.io/docs/reference/node/device-plugin-api-versions/`

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/

### PR DESCRIPTION
**Pull request by Shubham82**
This PR fixed the links for **API compatibility** and **Kubelet Device Manager API Versions**  in [Upgrade A Cluster](https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/) task.

Fixes #38858

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @jimangel, @reylejano
PTAL!

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Comment by Shubham82** [comment]
Yesterday PR: #38931 resolved this issue, so I have rebased my PR according to that.

**Comment by Shubham82** [comment]
PTAL!

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm

**Comment by Shubham82** [comment]
Hi @divya-mohan0209 
could you please approve this PR? So it will merge soon.

Thanks!

**Review by divya-mohan0209 — COMMENTED** [review]
This is a minor edit. Approving.
/approve

**Comment by Shubham82** [comment]
thanks @divya-mohan0209

**Pull request merged**
