### PR TITLE
add new turnkey cloud solution to setup: ICP on multiple clouds

### PR DESCRIPTION
**Pull request by bradtopol**
add new turnkey cloud solution to setup: ICP on multiple clouds

Signed-off-by: Brad Topol <btopol@us.ibm.com>

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
> Help editing and submitting pull requests:  https://deploy-preview-9510--kubernetes-io-master-staging.netlify.com/docs/contribute/start/#submit-a-pull-request.
> Help choosing which branch to use, see
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by bradtopol** [comment]
Hi @zparnold I wanted to get this PR opened and in the queue to meet your Tuesday deadline for opened PRs going into 1.12.  The only thing that might change on this is the URL it points to.  I will find out soon and update this.

**Comment by bradtopol** [comment]
Hi @zparnold this is now ready to be merged. I checked the links. This content is appropriate for both master and 1.12.  Thanks!

**Comment by stacyped** [comment]
Hi @zparnold @bradtopol, I don't see these changes on the live Kubernetes site. Can we get ICP to be listed under "Turnkey Cloud Solutions" ?

**Pull request merged**
