### PR TITLE
fix incorrect field name in event API deprecation guide

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

fix https://github.com/kubernetes/kubernetes/issues/103679

### CODE REVIEW

**Comment by sftim** [comment]
This'll need technical review. Does look correct to me.
/sig instrumentation

**Comment by dgrisonnet** [comment]
We should also update line 56 and replace `reportingComponent` by `reportingController`:

> `action`, `reason`, `reportingComponent`, and `reportingInstance` are required when creating new **events.k8s.io/v1** Events

**Review by dgrisonnet — CHANGES_REQUESTED** [review]
We should also update line 56 and replace `reportingComponent` by `reportingController`:

> `action`, `reason`, `reportingComponent`, and `reportingInstance` are required when creating new **events.k8s.io/v1** Events

**Pull request merged**
