### PR TITLE
Switch Do's and Don'ts

### PR DESCRIPTION
**Pull request by petersutter**
This PR fixes the Do's and Don'ts of the subheading `Avoid words that assume a specific level of understanding`

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
Thanks @petersutter .
/lgtm

**Pull request merged**
