### PR TITLE
Added Base64 Online Tool

### PR DESCRIPTION
**Pull request by rahulkumarsingh73690**
I noticed in docs base 64 tool is not linked. So for better understanding, I added the base 64 tool.

Please check link that I added :)

Thanks

### CODE REVIEW

**Review by sftim — CHANGES_REQUESTED** [review]
We suggest using the commonly-available `base64` program and don't recommend the site you've linked to: we don't know whether or not we can trust that website.

/hold

Not linking to a web tool is a deliberate choice:
> Use a local tool trusted by your OS to decrease the security risks of external tools.

**Comment by rahulkumarsingh73690** [comment]
@sftim I don't think the security issue with this website is because all base64 conversion is done on the client-side. 

Almost 40K users use programming tools regularly :)

I prefer you to recheck

**Comment by sftim** [comment]
See issue https://github.com/kubernetes/website/issues/17984 and PR https://github.com/kubernetes/website/pull/18002 for the existing discussion.

**Comment by divya-mohan0209** [comment]
I concur with what @sftim said in [his comment](https://github.com/kubernetes/website/pull/30670#pullrequestreview-817786256)

**Pull request closed without merging**
