### PR TITLE
[ja]Fix invalid Japanese words

### PR DESCRIPTION
**Pull request by YuikoTakada**
This is work-in-progress for reviews by Japanese developers.

This PR fixes invalid Japanese words "オペレータ" to "オペレーター".
According to [docs](https://kubernetes.io/ja/docs/contribute/localization/#%E9%A0%BB%E5%87%BA%E5%8D%98%E8%AA%9E), "オペレータ" must be unified to "オペレーター".

This PR fixes these pages:
* https://kubernetes.io/ja/case-studies/sos/
* https://kubernetes.io/ja/docs/concepts/configuration/manage-resources-containers/

### CODE REVIEW

**Review by t-inu — APPROVED** [review]
I think [WIP] mark is unnecessary.
The fixes are fine.
/lgtm

**Comment by atoato88** [comment]
/assign @nasa9084 
Could you review this?

**Review by nasa9084 — COMMENTED** [review]
/approve

別PRで良いのですが、「クラスター」「ユーザー」「スケジューラー」あたりも直してもらえると嬉しいです！

**Pull request merged**
