### PR TITLE
base64 --decode works across Linux and MacOS

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by drnic** [comment]
Generated docs are very neat. https://deploy-preview-17240--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/access-cluster-api/#without-kubectl-proxy includes change.

**Comment by nasa9084** [comment]
please create PRs for each language separately

**Comment by drnic** [comment]
I can do that; though it is a confusing request - I’m not changing any language issues - rather fixing a coding example. I’ll close this PR when I get back to creating 3? new PRs for each language.

**Comment by drnic** [comment]
I've updated this PR/commit and removed the changes to non-EN language files.

**Comment by sftim** [comment]
/remove-language fr
/remove-language ja
(if Prow will let me)

**Pull request merged**
