### PR TITLE
Update cheatsheet.md

### PR DESCRIPTION
**Pull request by mkourany92**

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @mkourany92, we were asked not to review PRs without CLA signed.

Could you follow [above instruction](https://github.com/kubernetes/website/pull/34166#issuecomment-1148847777) to sign the CLA so that we can move forward?

**Review by Arhell — COMMENTED** [review]
About CLA info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Sea-n** [comment]
Hi @mkourany92, are you still interested in contributing Kubernetes website?

Please let us know if there are any problem about signing CLA.

**Comment by zacharysarah** [comment]
@mkourany92 👋🏻 Please feel free to `/reopen` when you're ready to sign the CLA.

/close

**Pull request closed without merging**
