### PR TITLE
subscribe button translate

### PR DESCRIPTION
**Pull request by Arhell**
issue https://github.com/kubernetes/website/issues/23034

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-23035--kubernetes-io-master-staging.netlify.app/es/#kubeweekly
/language es
/assign @raelga

**Comment by sftim** [comment]
LGTM

**Comment by raelga** [comment]
Thanks @Arhell !

/lgtm
/approve

**Comment by kbhawkey** [comment]
Thanks @Arhell .
/approve

**Pull request merged**
