### PR TITLE
Update windows containers deployment

### PR DESCRIPTION
**Pull request by daxmc99**
There are two fixes in this change. First, the yaml is left justified in order to ease copying. Secondly, the selector field is added to the deployment.

### CODE REVIEW

**Comment by zacharysarah** [comment]
@daxmc99 Thanks for the PR.

@kubernetes/sig-windows-bugs 👋 Could we please get a review? Thanks in advance! 🙇

**Comment by daxmc99** [comment]
@PatrickLang  
Can you take another look at this? The previous version had 
```
pec:
  ports:
    # the port that this service should serve on
    - port: 80
    targetPort: 80
  selector:
    app: win-webserver
  type: NodePort
```
now: 
```
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: win-webserver
  type: NodePort
```
The indent on targetPort was incorrect

**Pull request merged**
