### PR TITLE
[ja] Translate `content/en/docs/tasks/debug/debug-cluster/kubectl-node-debug.md` into Japanese

### LINKED ISSUE #44987: [ja] Translate `content/en/docs/tasks/debug/debug-cluster/kubectl-node-debug.md` into Japanese
**This is a Feature Request**

**What would you like to be added**

Translate `content/en/docs/tasks/debug/debug-cluster/kubectl-node-debug.md` into Japanese

**Why is this needed**

There is no Japanese translation for this page

**Comments**

- File to translate: 
    - https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/debug/debug-cluster/kubectl-node-debug.md
- Original:
    - https://kubernetes.io/docs/tasks/debug/debug-cluster/kubectl-node-debug/

ref. Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/

/area localization
/language ja
/help

### PR DESCRIPTION
**Pull request by Okabe-Junya**
close #44987 

## Change. List

- Translate `content/en/docs/tasks/debug/debug-cluster/kubectl-node-debug.md` into Japanese

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
The target page on the deploy preview site:

- https://deploy-preview-45088--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/debug/debug-cluster/kubectl-node-debug/

**Review by nasa9084 — COMMENTED** [review]
sorry for being late...
/approve

**Comment by nasa9084** [comment]
cc @atoato88

**Comment by atoato88** [comment]
/lgtm
Sorry for my delay.

**Pull request merged**
