### PR TITLE
[zh] fix broken links in install kubectl windows page

### PR DESCRIPTION
**Pull request by niteshseram**
It seems the same issue #29570 exist in this localization as well. 
/language zh

### CODE REVIEW

**Comment by niteshseram** [comment]
Deploy preview of the modified page https://deploy-preview-29573--kubernetes-io-main-staging.netlify.app/zh/docs/tasks/tools/install-kubectl-windows/

**Review by tanjunchen — COMMENTED** [review]
thanks you pr, could you update the all link in /zh? 
see
image

**Comment by niteshseram** [comment]
> thanks for your pr, could you update the all link in /zh? @niteshseram
> /hold
> see
> image

Hi @tanjunchen, I believe you are asking me to update all the links like I did in /en. But I am think the /zh content is not exactly similar to /en and some links are missing.But I did update all the links that were present in /zh.

**Comment by tanjunchen** [comment]
@niteshseram   I have seen the translation of ko and updated the all links. The zh/  *fullversion* parameter should not affect the download url. /cc @tengqm could you help me confirm it? thanks.

**Comment by tengqm** [comment]
This PR is incomplete. We are supposed to fix all links on the page.

**Comment by tengqm** [comment]
Closing due to lack of response from author. Will propose a complete sync soon.
Thanks anyway.
/close

**Pull request closed without merging**
