### PR TITLE
[zh] Remove outdated files

### PR DESCRIPTION
**Pull request by tengqm**
This PR removes some files that no longer exist on the English site.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@tengqm Some tests fail.

[[Header rules](https://app.netlify.com/sites/kubernetes-io-master-staging/deploys/6081456bac28b600074b63f7)]
```
6:45:38 PM: ERROR 2021/04/22 09:45:38 [zh] tabs include not found for path "docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_kubelet.md"
6:45:38 PM: ERROR 2021/04/22 09:45:38 [zh] tabs include not found for path "docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_kubelet_config_enable-dynamic.md"
6:45:38 PM: ERROR 2021/04/22 09:45:38 [zh] tabs include not found for path "docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_selfhosting.md"
6:45:38 PM: ERROR 2021/04/22 09:45:38 [zh] tabs include not found for path "docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_selfhosting_pivot.md"
6:45:38 PM: ERROR 2021/04/22 09:45:38 [zh] no Resource or Page matching "generated/kubeadm_config_view.md*".
6:46:50 PM: Total in 114134 ms
6:46:50 PM: Error: Error building site: logged 5 error(s)
```

`zh/docs/reference/setup-tools/kubeadm/kubeadm-alpha.md` requires some files that this PR delete:
```Markdown
{{< tab name="kubelet" include="generated/kubeadm_alpha_kubelet.md" />}}
{{< tab name="enable-dynamic" include="generated/kubeadm_alpha_kubelet_config_enable-dynamic.md" />}}
...
{{< tab name="selfhosting" include="generated/kubeadm_alpha_selfhosting.md" />}}
{{< tab name="pivot" include="generated/kubeadm_alpha_selfhosting_pivot.md" />}}
```

`zh/docs/reference/setup-tools/kubeadm/kubeadm-config.md` requires some files that this PR delete:
```Markdown
{{< include "generated/kubeadm_config_view.md" >}}
```

**Comment by zhiguo-lu** [comment]
删掉的12个文件，我全局grep了一遍，都ok，只有api-index.md 这个文件牵扯出了另一个问题。
下面两个文件引用到了已经删掉的英文版 api-index.md ，是否需要一并修改？
/zh/docs/contribute/generate-ref-docs/kubernetes-api.md 
/en/docs/contribute/generate-ref-docs/kubernetes-api.md 


./docs/contribute/generate-ref-docs/kubernetes-api.md:`<web-base>/content/en/docs/reference/kubernetes-api/api-index.md` with the new
./docs/contribute/generate-ref-docs/kubernetes-api.md:`<web-base>/content/en/docs/reference/kubernetes-api/api-index.md`。
./docs/contribute/generate-ref-docs/kubernetes-api.md:* Open `<web-base>/content/en/docs/reference/kubernetes-api/api-index.md` for editing,
./docs/contribute/generate-ref-docs/kubernetes-api.md:* 打开并编辑 `<web-base>/content/en/docs/reference/kubernetes-api/api-index.md`，

**Comment by tengqm** [comment]
那几个文件等同步的时候再说吧。

**Review by tanjunchen — COMMENTED** [review]
@tengqm 
thanks
/approve
/lgtm

**Pull request merged**
