### PR TITLE
logs command to check etc/hosts file corrected

### PR DESCRIPTION
**Pull request by inaitgaj**
hosts file can be viewed using exec command.

### CODE REVIEW

**Comment by inaitgaj** [comment]
signed up for CLA on linuxfoundation.

**Comment by kbhawkey** [comment]
Hello @inaitgaj .
Would you recheck that you have completed your CLA (https://git.k8s.io/community/CLA.md#the-contributor-license-agreement). Thanks!

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-20798--kubernetes-io-master-staging.netlify.app/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

/approve

**Pull request merged**
