### PR TITLE
update the avoid collision link

### PR DESCRIPTION
**Pull request by akshayamadhuri**
Links for Avoiding collisions are broken in:

https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates (at ServiceIPStaticSubrange point)

issue number #41809

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@akshayamadhuri Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: https://git.k8s.io/community/CLA.md

**Comment by akshayamadhuri** [comment]
**@dipesh-rawat** done

**Comment by tengqm** [comment]
Commit 1d68a02353fdb11d6e4cff6469dcb5f6a7f560e3 breaks the link.
Please check where the contents were moved, rather than pointing the docs to a blog.

**Comment by akshayamadhuri** [comment]
@tengqm  should I remove the links of blogs but docs don't contain "Avoid Collision" concept

**Review by sftim — CHANGES_REQUESTED** [review]
This is the wrong fix. Please read https://github.com/kubernetes/website/issues/41809#issuecomment-1613927473 for advice on how to make the correct changes.

**Pull request closed without merging**
