### PR TITLE
Branch sync - Merge master with dev 1.19 

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Sync master with dev-1.19

cc: @zacharysarah @jimangel @kbarnard10

### CODE REVIEW

**Comment by kbhawkey** [comment]
I guess this fails to build/deploy because of the `pt` file.

**Comment by savitharaghunathan** [comment]
Preview: https://5f286f4465a45a0008a53438--kubernetes-io-vnext-staging.netlify.app/

**Comment by savitharaghunathan** [comment]
cc: @kbhawkey 
I merged the changes by @sftim and force pushed. The build is complete now. There is a couple of red x's in the commits, I have verified them and they got all the labels. PTAL! Thanks :)

**Comment by kbhawkey** [comment]
I don't immediately see any problems. Thanks!
/lgtm

**Comment by savitharaghunathan** [comment]
Thanks @kbhawkey :) 
@jimangel @sftim can you take a look and if everything looks good, approve this PR please? Thanks :)

**Comment by kbhawkey** [comment]
@savitharaghunathan , the two deploy issues (see red Xs) are spurious errors?
The one commit refers to a calendar shortcode error that does not appear to be related to the change.

**Comment by savitharaghunathan** [comment]
> @savitharaghunathan , the two deploy issues (see red Xs) are spurious errors?
> The one commit refers to a calendar shortcode error that does not appear to be related to the change.

@kbhawkey I was looking into the checks for those two commits and saw that it was tide related. Are these the ones you are talking about as well? 

[Update chinese page setup-extension-api-server](https://github.com/kubernetes/website/pull/22161)
[97309e4](https://github.com/kubernetes/website/pull/22932/commits/97309e46fa8d6f4b10aa22d329233d5f4c471764)

[update chinese page install-service-catalog-using-helm](https://github.com/kubernetes/website/pull/22162)
[a0e6cda](https://github.com/kubernetes/website/pull/22932/commits/a0e6cdac5963f6a5d443c2fdc91e321de58239b8) 

If so, are you looking into the build deploys?

**Comment by kbhawkey** [comment]
> 
> 
> > @savitharaghunathan , the two deploy issues (see red Xs) are spurious errors?
> > The one commit refers to a calendar shortcode error that does not appear to be related to the change.
> 
> @kbhawkey I was looking into the checks for those two commits and saw that it was tide related. Are these the ones you are talking about as well?
> 
> [Update chinese page setup-extension-api-server](https://github.com/kubernetes/website/pull/22161)
> [97309e4](https://github.com/kubernetes/website/pull/22932/commits/97309e46fa8d6f4b10aa22d329233d5f4c471764)
> 
> [update chinese page install-service-catalog-using-helm](https://github.com/kubernetes/website/pull/22162)
> [a0e6cda](https://github.com/kubernetes/website/pull/22932/commits/a0e6cdac5963f6a5d443c2fdc91e321de58239b8)
> 
> If so, are you looking into the build deploys?

At the moment, I am not looking into the build deploys, but can approve these changes unless @jimangel stamp of approval is required.

**Comment by savitharaghunathan** [comment]
@kbhawkey yes please if you have no flags. Thanks :)

**Pull request merged**
