### PR TITLE
make the example consistent with the test

### PR DESCRIPTION
**Pull request by mysunshine92**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by mysunshine92** [comment]
as we take about this pr in https://github.com/kubernetes/website/pull/13705 
we should modify the example to consistent tith the test in file :
https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/configuration/assign-pod-node.md

**Comment by mysunshine92** [comment]
@tengqm @bsalamat @Bradamant3

**Comment by DanyC97** [comment]
thanks for the fix @mysunshine92 
/lgtm

**Comment by mysunshine92** [comment]
@zparnold would you like to add approved label? thank you

**Comment by DanyC97** [comment]
/assign @bradtopol

@bradtopol can you please help out ? thank you

**Pull request merged**
