### PR TITLE
Remove "design docs" from /docs/reference sidebar

### PR DESCRIPTION
**Pull request by ahmetb**
This list on the sidebar isn't very useful:

- it's not an exhaustive list
- it's not an up-to-date list either
- design docs are not documentation (they're already stale)
- we already link to the full list from https://kubernetes.io/docs/reference/
  home page

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6410)

### CODE REVIEW

**Comment by ahmetb** [comment]
@tengqm is that fixed in a separate PR, if so I can just rebase my commit to make Travis happy.

**Comment by tengqm** [comment]
@ahmetb I'm afraid not. You may want to do it in your PR because it is your PR that makes it a dangling file . :)

**Comment by ahmetb** [comment]
@thockin I am about to remove [ovs-networking.md](https://github.com/kubernetes/website/blob/master/docs/admin/ovs-networking.md) completely, as part of removing links to design docs from `k8s.io/docs/reference`.

Do you think we should keep it somewhere else (like contrib/design-docs)? It seems untouched for about ~2 years, but if it is valuable information I can move it somewhere else.

**Comment by heckj** [comment]
@ahmetb Do you want to rebase this and remove the file that you commented on to @thockin and get this rolling again? I think the ToC checks in CI are the only real pending point... branch isn't set to updatable by a maintainer, or I might have just taken a stab at the rebase myself

**Comment by ahmetb** [comment]
I just don't know what to do with that `ovs-networking.md` file. 😟  I have no good place for it to move to. I also cannot assess if it contains information that deserve to be on the website, or should it just be deleted forever. Any ideas?

**Comment by heckj** [comment]
It's not invalid content - added two years ago and hasn't been touched since (in any real sense anyway), it only seems relevant to be a component of a "how to make your own bare-metal cluster from scratch" kind of reference effort. Kubernetes-the-hard-way is the most relevant track there- as official documentation goes, this isn't entirely helpful because it's so skimpy on end-to-end details, so I'd lean towards dropping it.

**Comment by ahmetb** [comment]
Deleted the `ovs-networking.md` and pushed again. PTAL.

**Comment by heckj** [comment]
@ahmetb the CI system is reporting:

> Error: docs/reference/design-docs/overview.md doesn't have an entry in the table of contents under _data/*.yml
> Found 1 files without entries. For how to fix it, see http://kubernetes.io/docs/home/contribute/write-new-topic/#creating-an-entry-in-the-table-of-contents

**Pull request merged**
