### PR TITLE
[hi] Localized docs/reference/tools/_index.md

### PR DESCRIPTION
**Pull request by aj11anuj**
Did [hi] localization of a file

### CODE REVIEW

**Comment by aj11anuj** [comment]
My a/c is verified and CLA signed as well. But the git of my laptop doesn't had verified label and that's not CLA signed. (Git of my laptop is associated with my brothers a/c) What to do? I already had tried resolving it but it's not working. How do i resolve it?

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by divya-mohan0209** [comment]
Hey @aj11anuj, can you retry by pushing another commit?

**Comment by divya-mohan0209** [comment]
There are two approaches:
- Close this PR & open a new one with the correct configuration.
- Amend the previous commit's sign off and config to reflect the right credentials.

**Pull request closed without merging**
