### PR TITLE
Branch sync - Merge master with dev 1.19

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Sync master with dev-1.19

cc: @zacharysarah @jimangel @kbarnard10

### CODE REVIEW

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/22218#issuecomment-651898933 comes from a localization update that was based off a stale branch.

Once we have the other details addressed we can manually remove the _invalid commit message_ label to remove the block on merge.

**Comment by sftim** [comment]
/remove-label do-not-merge/invalid-commit-message

This is a branch sync commit. The invalid commit message was created by Prow and there is an issue tracking that behavior.
It's OK to merge this even with the problem commit message.

**Comment by kbhawkey** [comment]
The only "errors" I see are related to:
https://github.com/kubernetes/website/pull/22218/commits/e5b8dd0e4d73841675fd91a0948c42d68ef47d6c
https://github.com/kubernetes/website/pull/22218/commits/d6116de8544b817bfe6f5376553c992bb3d2d6b1
https://github.com/kubernetes/website/pull/22218/commits/d8a8a62f08c984475bfe071b0747c0d0a330d30c

**Pull request merged**
