### PR TITLE
Revise the feature gate LegacyServiceAccountTokenCleanUp to stable stage

### PR DESCRIPTION
**Pull request by yt2985**
Issue: https://github.com/kubernetes/enhancements/issues/2799

### CODE REVIEW

**Comment by tengqm** [comment]
Where is the upstream code change?

**Comment by sftim** [comment]
> Where is the upstream code change?

I think it's https://github.com/kubernetes/kubernetes/pull/122635

**Comment by tengqm** [comment]
@sftim thanks for the pointer.
/approve

**Review by sftim — COMMENTED** [review]
Thanks

Please also revise the text for `kubernetes.io/legacy-token-invalid-since`; see https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetes-io-legacy-token-invalid-since

**Comment by yt2985** [comment]
Hold for the review. I wrongly synced the branch again... Let me fix it.

**Comment by yt2985** [comment]
Fixed the syncing error. The PR is good to be reviewed now:)

**Comment by Okabe-Junya** [comment]
/remove-language de es fr hi id ja ko pt ru vi zh
/remove-area blog
/remove-sig auth

**Comment by Okabe-Junya** [comment]
Sorry for my missed operation (I missed https://github.com/kubernetes/website/pull/45253#issuecomment-1969503816)

/sig auth

**Comment by aramase** [comment]
/assign liggitt

Assigned as part of SIG Auth triage meeting (03/11/2024) for review.

**Pull request merged**
