### PR TITLE
unindent code in services-networking/connect-applications-service.md 

### PR DESCRIPTION
**Pull request by debugwish**
services-networking/connect-applications-service.md , so ti can run as hoped

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tanjunchen** [comment]
see 
```
86182@LAPTOP-QMUNSEPQ MINGW64 /d/opensource/website (master)
$ ./scripts/lsync.sh    content/zh/docs/concepts/services-networking/connect-applications-service.md
content/zh/docs/concepts/services-networking/connect-applications-service.md is still in sync
```
/approve

**Comment by debugwish** [comment]
CLA signed

**Comment by tengqm** [comment]
Reapproving since CLA check is passing.
/lgtm
/approve

**Pull request merged**
