### PR TITLE
update the outdated ja tutorials/_index.md based on the v1.17 en page

### LINKED ISSUE #21368: ja: Make tutorials/_index.md follow v1.17 of the original text
**This is a Feature Request**

**What would you like to be added**
Update tutorials/_index.md to follow v1.17 of the original (Englist) text.

**Why is this needed**
content/ja/docs/tutorials/_index.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.2/content/ja/docs/tutorials/_index.md

https://kubernetes.io/ja/docs/tutorials/

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/tutorials/_index.md

https://v1-17.docs.kubernetes.io/docs/tutorials/

diff between translated and v1.17
https://gist.github.com/oke-py/7ba3b1b2940e9e852255aaf949ac7940

**Note**
Currently, we use `dev-1.17-ja.2` branch. Please open a PR targeting the branch.

ref
[How To Contribute](https://kubernetes-docs-ja.kibe.la/shared/entries/c5878aa5-ad1f-4f29-a5bb-25853cbc14ec)
[翻訳スタイルガイド](https://kubernetes-docs-ja.kibe.la/shared/entries/5efe4fa7-d2a1-4a1d-8bc3-ce7ccdc064a6)

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

### PR DESCRIPTION
**Pull request by isheik**
Closes #21368 

This PR updates tutorials/_index.md to follow v1.17 of the original (Englist) text.

### CODE REVIEW

**Comment by oke-py** [comment]
@isheik Thank you for contribution!
Please sign CLA following the instruction above.

**Comment by isheik** [comment]
@oke-py Thank you for the information. I finished signing CLA.

**Comment by isheik** [comment]
Signed CLA

**Pull request merged**
