### PR TITLE
Fix wrong appearance in "Consuming Secret Values from Environment Variables" part

### PR DESCRIPTION
**Pull request by Tony-Hu**
Fix wrong appearance in "Consuming Secret Values from Environment Variables" part

### CODE REVIEW

**Comment by Tony-Hu** [comment]
I signed it

**Comment by Tony-Hu** [comment]
I signed it

**Comment by cody-clark** [comment]
Hi @Tony-Hu, thanks for the fix! It looks like the CLA bot is acting up. Can you try closing and reopening this PR to see if that'll trigger it again? If that still doesn't work, please follow the steps at [in the troubleshooting section](https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting).

**Comment by Tony-Hu** [comment]
Hello @cody-clark , thanks for your suggestion. It works!

**Comment by cody-clark** [comment]
Awesome, thanks @Tony-Hu!

Preview: https://deploy-preview-13042--kubernetes-io-master-staging.netlify.com/docs/concepts/configuration/secret/

/approve

**Pull request merged**
