### PR TITLE
Remove exec permission on markdown files

### PR DESCRIPTION
**Pull request by tengqm**
For some unknown reasons, we have got many markdown files with exec permission. That is weird and risky.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/approve

**Review by Joshua698 — COMMENTED** [review]
image

**Review by Joshua698 — COMMENTED** [review]
I

**Comment by sftim** [comment]
I'm going to remove https://github.com/kubernetes/website/pull/28447#pullrequestreview-943847849 - it is clearly off-topic.

**Pull request merged**
