### PR TITLE
Update web-ui-dashboard.md

### PR DESCRIPTION
**Pull request by lhauspicious**
update error ui access url address

### CODE REVIEW

**Comment by tengqm** [comment]
@lhauspicious Pls sign the CLA in order for the PR to be reviewed.

**Review by Arhell — COMMENTED** [review]
CLA link https://github.com/kubernetes/website/pull/32239#issuecomment-1066044757

**Comment by reylejano** [comment]
@lhauspicious, please sign the CLA
https://github.com/kubernetes/community/blob/master/CLA.md

A PR Wrangler may close this PR in the near future if the CLA has not been signed

**Comment by tengqm** [comment]
/close
Closing due to missing CLA for one month.

**Pull request closed without merging**
