### PR TITLE
Update storage-classes.md

### PR DESCRIPTION
**Pull request by jackThomass**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/28039#issuecomment-843680706

**Comment by jackThomass** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by:
> To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tanjunchen** after the PR has been reviewed.
> You can assign the PR to them by writing `/assign @tanjunchen` in a comment when ready.
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubernetes%2Fwebsite).
> 
> Needs approval from an approver in each of these files:
> * **[content/zh/OWNERS](https://github.com/kubernetes/website/blob/master/content/zh/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment
> Approvers can cancel approval by writing `/approve cancel` in a comment

new test

**Pull request merged**
