### PR TITLE
[WIP] Add blog post "Managing Cluster API with Kluctl"

### PR DESCRIPTION
**Pull request by codablock**
Hello,

as discussed in Slack (#sig-docs-blog), here is the proposed blog post about "Managing Cluster API with Kluctl". It's a tutorial that shows an alternative way on how to manage Cluster API workload clusters. It got quite long, I hope this is still ok for blog.kubernetes.io.

I could also split the tutorial up into two parts, but that would have the risk that part 1 would leave the reader with a sense of "ok...and why is this useful?", simply because the powerful stuff comes with part 2.

I started with a placeholder commit that only points to HackMD. It was suggested to do initial review there. Here is the link: https://hackmd.io/@codablock/Hyv13tQna. When initial review is done, I will force-push with the latest draft.

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [WIP] Add blog post "Managing Cluster API with Kluctl"

**Comment by sftim** [comment]
I'm not sure we can accept this _as is_, because it's very much about one tool that is not part of Kubernetes.

You could:
- donate `kluctl` to the Kubernetes project
- reframe the article to put more emphasis on alternative ways to manage clusters, even if your conclusion is that kluctl is the best thing since sliced bread
- publish it elsewhere

**Comment by sftim** [comment]
What approach do you prefer @codablock ?

**Comment by codablock** [comment]
@sftim With donating Kluctl to Kubernetes, do you mean donating it to the CNCF? Or is "donating to Kubernetes" a completely different thing? Do you maybe have some links that explain the process and implications?

I applied for CNCF Sandbox about a year ago: https://github.com/cncf/sandbox/issues/8
I however decided to cancel the application on my own due to adoption and contributions being too low at that time. Both is getting better slowly, so I'm already considering re-applying.

**Comment by sftim** [comment]
@codablock
You can make kluctl be its own CNCF project, or you can make it be part of the existing Kubernetes project. There is some paperwork involved, and that's only one of the options you have.

For other projects within the Linux Foundation / CNCF, we treat those as formally third party - mostly to level the playing field between different projects in terms of publicity.

It might be worth switching this discussion to #sig-docs in Slack, if that works for you, and then return here to summarize what you've decided to do..?

**Comment by codablock** [comment]
I have tried to start discussions in regard to donating the project to the Kubernetes project, but I assume whatever the result of that will be, it will take quite some time until everything is done.

I'm considering going for the second option listed by you @sftim in parallel. Before I start, can you tell me your feeling abou the length of the blog post? I fear that it will get too long as I'm unsure if there are any limits in that regard.

**Comment by codablock** [comment]
@sftim I assume that there will be very limited time on your and other peoples side to pursue any of the two proposed solutions, simply because KubeCon EU is so near :)

I decided to publish this post somewhere else (my own blog) now. Thanks however for giving me the push on pursuing the donation road again :) I'll definitely follow on this in the next weeks/months.

**Pull request closed without merging**
