### PR TITLE
[zh] sync docs/concepts

### PR DESCRIPTION
**Pull request by niuzhenguo**
sync	content/zh-cn/docs/concepts/services-networking/

### CODE REVIEW

**Comment by windsonsea** [comment]
This folder in en has other changes in addition to these weights:

```
$ ./scripts/lsync.sh content/zh-cn/docs/concepts/services-networking                              
6	1	content/en/docs/concepts/services-networking/network-policies.md
1	1	content/en/docs/concepts/services-networking/endpoint-slices.md
2	2	content/en/docs/concepts/services-networking/service-traffic-policy.md
1	1	content/en/docs/concepts/services-networking/ingress-controllers.md
2	2	content/en/docs/concepts/services-networking/topology-aware-hints.md
**removed**	content/en/docs/concepts/services-networking/connect-applications-service.md
10	11	content/en/docs/concepts/services-networking/service.md
1	1	content/en/docs/concepts/services-networking/service-topology.md
1	1	content/en/docs/concepts/services-networking/windows-networking.md
1	1	content/en/docs/concepts/services-networking/ingress.md
4	2	content/en/docs/concepts/services-networking/_index.md
```

**Comment by niuzhenguo** [comment]
@windsonsea synced with content/en/docs/concepts/services-networking/

**Comment by windsonsea** [comment]
> @windsonsea synced with content/en/docs/concepts/services-networking/

No. This file is not a simply deleted. It has been changed and moved from
```
content/en/docs/concepts/services-networking/connect-applications-service.md
```
to 
```
content/en/docs/tutorials/services/connect-applications-service.md
```

That means you need to check all files one by one in this folder.

**Comment by niuzhenguo** [comment]
> > @windsonsea synced with content/en/docs/concepts/services-networking/
> 
> No. This file is not a simply deleted. It has been changed and moved from
> 
> ```
> content/en/docs/concepts/services-networking/connect-applications-service.md
> ```
> 
> to
> 
> ```
> content/en/docs/tutorials/services/connect-applications-service.md
> ```
> 
> That means you need to check all files line by line in this folder.

Seems there are some issues with the en docs about the new connect-applications-service link, maybe fix that first.

**Comment by niuzhenguo** [comment]
https://github.com/kubernetes/website/pull/37894

**Comment by windsonsea** [comment]
This PR covers 11 files.

In zh localization, part of changes in a file is not recommended. 

This is why I open #37919 again. We need check the relocated file line by line, text by text, rather than only weights here.

**Comment by tengqm** [comment]
/close

Please do this kind of sync in smaller batches, with each file carefully checked.

**Comment by niuzhenguo** [comment]
> /close
> 
> Please do this kind of sync in smaller batches, with each file carefully checked.

ok, got.

**Pull request closed without merging**
