### PR TITLE
Update install-kubeadm.md

### PR DESCRIPTION
**Pull request by Alok0587**
Made changes on line 197, So that repo URL will be valid for both x86 and ppc64le.

### CODE REVIEW

**Comment by neolit123** [comment]
hi, the PR can only be accepted if you sign the CLA.

/check-cla

**Comment by Alok0587** [comment]
> Hello @Alok0587 - can you please let us know what this change is for, what it fixes, and how it can be tested?

**Comment by Alok0587** [comment]
Hi @onlydole I have tested the "kubeadm-install.md" and found out that base url at line 197 is only for x86 but if we change it to $basearch then it will be available for different arch for example ppc64le  as well.

**Comment by onlydole** [comment]
Ah! Got it, thank you @Alok0587.

**Comment by neolit123** [comment]
@Alok0587 
i've added your change in this PR.
https://github.com/kubernetes/website/pull/20021

if you wish to contribute in the future you can still sign the CLA.

/close

**Pull request closed without merging**
