### PR TITLE
Remove deprecated getting started guides

### LINKED ISSUE #15971: Remove getting-started-guides/
### Description

The content in `content/en/docs/getting-started-guides/` has been deprecated for ~2 years. As shown in [the blame for `/static/_redirects`](https://github.com/kubernetes/website/blame/master/static/_redirects), 301 redirects have successfully pointed to `/docs/setup/`. At this point, the content in `getting-started-guides/` is thoroughly deprecated and needs to be removed.

### Proposed solution

1. `rm -rf /content/en/docs/getting-started-guides/`

2. Change `/static/_redirects#L164` to read:
```
/docs/getting-started-guides/*     /docs/setup/ 301
```

3. Remove the following from `/static/_redirects`: 

- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L165-L204
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L208
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L347-L353
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L421
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L504
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L518

### Files to change

https://github.com/kubernetes/website/tree/master/content/en/docs/getting-started-guides
https://github.com/kubernetes/website/blob/master/static/_redirects

/sig docs
/priority important-soon

### PR DESCRIPTION
**Pull request by praveensastry**
Closes #15971

### CODE REVIEW

**Comment by praveensastry** [comment]
Thank you @zacharysarah for the detailed instructions.

**Comment by zacharysarah** [comment]
@praveensastry Congratulations on your first PR to k/website! 🎉

**Pull request merged**
