### PR TITLE
KEP-4815 DRA Partitionable Devices

### PR DESCRIPTION
**Pull request by klueska**
### Description
Document the alpha feature for advertising partitionable devices in a ResourceSlice (KEP-4815)

PRs: TBD

### Issue
KEP: https://github.com/kubernetes/enhancements/issues/4815

Closes: #

### CODE REVIEW

**Comment by T-Lakshmi** [comment]
@klueska,
From logs, build failed with following error:

> 2:11:17 PM: ERROR Invalid feature gate: 'DRAPartitionableDevices' is not recognized or lacks a matching description file in 'en/docs/reference/command-line-tools-reference/feature-gates'

**Comment by T-Lakshmi** [comment]
@klueska,
Can you try to re-push the commit and see if error can fix.
Run the following commands to trigger the build again:

```
git reset
git commit --amend --no-edit
git push --force-with-lease
```

**Comment by chanieljdan** [comment]
Hello @klueska 👋!

I'm reaching out from the Docs team. Just checking in as we approach Docs Freeze on Tuesday November 26th 18:00 PDT. This documentation appears to still be under review. To meet the Docs Freeze, this PR must have a technical review as well as lgtm and approve labels applied, without any unaddressed comments or concerns from SIG Docs. 

Thank you!

**Comment by pohly** [comment]
Nothing got included in 1.32, so there's nothing to document.

/remove-milestone v1.32

**Pull request closed without merging**
