### PR TITLE
upgrade to mermaid 8.11.2

### PR DESCRIPTION
**Pull request by chrismetz09**
This PR upgrades mermaid from 8.9.1 to 8.11.2.

Description:
- [added mermaid figures to /docs/contribute section #29466 ](https://github.com/kubernetes/website/pull/29466) incorporates multiple new Mermaid diagrams in the K8s docs/contribute section. A new Mermaid feature called subgraph direction was used to create the figures. This feature is not supported in mermaid 8.9.1; this feature is supported in mermaid 8.11.2.

- Suggested by @sftim to break #29466 into two separate PRs: one to upgrade the mermaid version and the other to add the new mermaid figures using the mermaid shortcode.

- This PR upgrades to mermaid 8.11.2. This PR is a pre-requisite for #29466 

Changes:

- copied 8.11.2 mermaid.min.js into the static/js folder.

- updated comment in layouts/partials/head.html.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @chrismetz09 . Thanks for the contribution.
Do you plan to enable Mermaid using the theme's configuration,

```
[params.mermaid]
enable = true
theme = "default"
```

**Comment by chrismetz09** [comment]
> Hi @chrismetz09 . Thanks for the contribution.
> Do you plan to enable Mermaid using the theme's configuration,
> 
> ```
> [params.mermaid]
> enable = true
> theme = "default"
> ```

Hi @kbhawkey, did not include in this PR. @sftim suggested I break up #29466 into separate smaller PRs. Order is:

1. This PR so new figures support subgraph direction feature.
2. #29466 to add new figures inside mermaid shortcode.
3. Update mermaid theme support and migrate figures from shortcode to native.

This PR is prereq for #29466.

**Comment by kbhawkey** [comment]
Thanks @chrismetz09 . Sounds good.

**Review by sftim — COMMENTED** [review]
```
$ curl https://raw.githubusercontent.com/kubernetes/website/cbff3ec4eaaad7e1565c7d1ae47e4c15c6d307e1/static/js/mermaid.min.js | sha1sum
9c955bf59f9e69a866a1ff4c1d5d837e602963e5  -

$ curl https://unpkg.com/mermaid@8.11.2/dist/mermaid.min.js | sha1sum   
9c955bf59f9e69a866a1ff4c1d5d837e602963e5  -
```

Checksums match, version bump matches PR description.

/lgtm

**Comment by sftim** [comment]
https://deploy-preview-29554--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/ingress/ seems to render OK too!
/approve

**Pull request merged**
