### PR TITLE
#11431 Remove load balance access task

### PR DESCRIPTION
**Pull request by pyaillet**
As stated on a comment, I propose to simply remove this task.

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@pyaillet could you please provide a link to the comment you mentioned?

**Comment by pyaillet** [comment]
Sorry !
Here it is: https://github.com/kubernetes/website/issues/11431#issuecomment-443305900

**Comment by Bradamant3** [comment]
See issue #11431 generally. Links provided there for audit going forward (just in case ...)

/lgtm
/approve

Also thanks @pyaillet for your diligence and persistence on this one!

**Pull request merged**
