### PR TITLE
Add irvifa as lead as a preparation step for transition

### PR DESCRIPTION
**Pull request by irvifa**
As mentioned in previous meeting, there's various step needed to be taken care of as a preparation for the shadow role for chairs.

### CODE REVIEW

**Comment by irvifa** [comment]
Related to https://github.com/kubernetes/org/pull/1976

**Comment by sftim** [comment]
/lgtm

/hold
for chair approval

**Comment by sftim** [comment]
Did this change get approved?

**Comment by kbhawkey** [comment]
Is this pending or ready to merge?
/cc @kbarnard10 @jimangel

**Comment by sftim** [comment]
Congratulations @irvifa !

**Comment by irvifa** [comment]
Thanks! @sftim

**Pull request merged**
