### PR TITLE
Fix metrics stability blog post images

### PR DESCRIPTION
**Pull request by mrbobbytables**
Renames the blog post md file to index.md. Hugo will not render images otherwise unless they are included as resources.

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/assign @ehashman @logicalhan 
FYI - didn't catch that the image wasn't loading in the original PR.

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Review by sftim — COMMENTED** [review]
/lgtm
/approve

**Comment by ehashman** [comment]
Thanks @mrbobbytables and @sftim !

**Pull request merged**
