### PR TITLE
[WIP] PDB GA documentation

### PR DESCRIPTION
**Pull request by mortent**
This is a placeholder PR for the docs for the PDB to GA effort: https://github.com/kubernetes/kubernetes/pull/81571

### CODE REVIEW

**Comment by irvifa** [comment]
Hi @mortent 
I'm a docs release team shadow. This is a kind reminder since we're approaching the deadline for PR to be ready to be reviewed by Nov 15, 2019. Kindly update this PR, thanks a lot..

**Comment by sftim** [comment]
@mortent, v1.17 has shipped. What are your plans here?

**Comment by sftim** [comment]
@mortent you need to sign a CLA in order to contribute to Kubernetes
If you'd like to open a new PR with similar changes, please do feel free - you will nevertheless need to have your CLA in order I'm afraid.

/close

**Pull request closed without merging**
