### PR TITLE
Fix typo in SC blog post

### PR DESCRIPTION
**Pull request by cblecker**
Fixes a minor whitespace typo in the steering committee election blog post

### CODE REVIEW

**Comment by onlydole** [comment]
Thank you, @cblecker! This looks good to me!

/approve

**Comment by kbhawkey** [comment]
/kind cleanup
Page preview:
https://deploy-preview-30397--kubernetes-io-main-staging.netlify.app/blog/2021/11/08/steering-committee-results-2021/

**Comment by kbhawkey** [comment]
Fixes spaces. Reviewed and approved.
/lgtm

**Pull request merged**
