### PR TITLE
Correct use of "comprising" in kustomization.md

### PR DESCRIPTION
**Pull request by mick88**
verb
consist of; be made up of.
"the country comprises twenty states"

### CODE REVIEW

**Comment by mick88** [comment]
I signed it

**Comment by Arhell** [comment]
@mick88 you might need to check that the email address you're using in Git matches the email address that you signed the CLA with

**Comment by mick88** [comment]
Force-pushed with updated e-mail in the commit.

**Comment by celestehorgan** [comment]
Hey there! @mick88, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by celestehorgan** [comment]
Hey there! @mick88, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by mick88** [comment]
Yes, I signed it and updated my commit with force-push to have the same e-mail address

**Comment by jimangel** [comment]
@mick88 sorry that the CLA is causing grief. Given the length this PR has gone unresolved I'm going to close it. 

You can check which email is being used with `git --no-pager show -s --format='%an <%ae>' COMMIT HASH`

Feel free to reopen the PR once the CLA issue is resolved or reach out if we can help! Thanks!

/close

**Pull request closed without merging**
