### PR TITLE
Fixing the apt repo to use the actual lsb_release

### PR DESCRIPTION
**Pull request by quentusrex**
and not hardcoded to Ubuntu LTS release codename

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6538)

### CODE REVIEW

**Comment by quentusrex** [comment]
cncf-cla signed

**Comment by quentusrex** [comment]
May have spoke too soon. The debian stretch repo doesn't appear to have latest packages, unfortunately.
https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages
vs
https://packages.cloud.google.com/apt/dists/kubernetes-stretch/main/binary-amd64/Packages

**Comment by heckj** [comment]
👋 @quentusrex - any update on this? If we can't easily use lsb_release in the example, then perhaps the best bet would be to leave the xenial in place, even if it is hardcoded to an LTS release name

**Comment by quentusrex** [comment]
Best to leave it as Xenial as it appears there aren't reliable build jobs for the other distros. I've been testing the Xenial packages on Debian Stretch and haven't had significant issues.

**Pull request closed without merging**
