### PR TITLE
add new file content/zh/docs/user-journeys/users/application-developer/

### PR DESCRIPTION
**Pull request by tanjunchen**

### CODE REVIEW

**Comment by tanjunchen** [comment]
@markthink   what is wrong with this pl?

**Comment by tanjunchen** [comment]
@markthink

**Comment by markthink** [comment]
@tanjunchen 预览效果有问题，相关注释块不正确，需要检查一下..

https://deploy-preview-16273--k8s-v1-14.netlify.com/zh/docs/user-journeys/users/application-developer/intermediate/

**Pull request closed without merging**
