### PR TITLE
fix markdown format as shell

### PR DESCRIPTION
**Pull request by DanteMustCode**
* fix markdown format as shell
* use the same command as the one above (Line 183)

### CODE REVIEW

**Comment by tengqm** [comment]
why remove `/bin/sh` ?
Actually we should add a `--` before `/bin/sh`...

**Comment by tengqm** [comment]
> @tengqm
> 
> > why remove `/bin/sh` ? Actually we should add a `--` before `/bin/sh`...
> 
> To keep the tutorial consistent, as the same purposed command is used above (Line 183).

The correct command line should be ended with `-- /bin/sh` I believe.

**Comment by DanteMustCode** [comment]
> > @tengqm
> > > why remove `/bin/sh` ? Actually we should add a `--` before `/bin/sh`...
> > 
> > 
> > To keep the tutorial consistent, as the same purposed command is used above (Line 183).
> 
> The correct command line should be ended with `-- /bin/sh` I believe.

The same command without `-- /bin/sh` is used in [Using Source IP](https://kubernetes.io/docs/tutorials/services/source-ip/) as well, and it _works_.

I did not find a page of BusyBox on Kubernetes, but [the page on Docker](https://hub.docker.com/_/busybox/) does not provide the additional argument as well.

**Comment by dipesh-rawat** [comment]
Hey @DanteMustCode,

The Netlify build timed out resulting in failing checks.

You can try the following to trigger Netlify rebuild without losing `lgtm` label.

```
git reset
git commit --amend --no-edit
git push --force-with-lease
```

**Comment by DanteMustCode** [comment]
@dipesh-rawat 

> Hey @DanteMustCode,
> 
> The Netlify build timed out resulting in failing checks.
> 
> You can try the following to trigger Netlify rebuild without losing `lgtm` label.
> 
> ```
> git reset
> git commit --amend --no-edit
> git push --force-with-lease
> ```

Thank you very much for the tip. I was looking for a retry button for that.

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Pull request merged**
