### PR TITLE
Switch kube-scheduler config to v1beta2

### PR DESCRIPTION
**Pull request by tengqm**
This PR goes with #28839, either one needs a rebase.

### CODE REVIEW

**Comment by tengqm** [comment]
preview link: https://deploy-preview-28858--kubernetes-io-vnext-staging.netlify.app/docs/reference/config-api/kube-scheduler-config.v1beta2/

**Comment by alculquicondor** [comment]
Wow, totally missed that the component config was part of the documentation now. Thanks!

/lgtm

**Comment by kbhawkey** [comment]
👋 @tengqm , Can you rebase?

**Pull request merged**
