### PR TITLE
[WIP]TokenRequest feature documentation

### PR DESCRIPTION
**Pull request by mikedanese**
Place holder

### CODE REVIEW

**Comment by zparnold** [comment]
@mikedanese When you have some time, could you please flesh out the docs on the `TokenRequest` feature?

**Comment by justaugustus** [comment]
@mikedanese  -- removing this from the milestone per this comment: https://github.com/kubernetes/features/issues/542#issuecomment-420212071

/milestone clear

**Comment by mikedanese** [comment]
My understanding is that we have until Friday for docs. What am I missing?

**Pull request closed without merging**
