### PR TITLE
mark StableLoadBalancerNodeSet as removed

### PR DESCRIPTION
**Pull request by carlory**
k/k: https://github.com/kubernetes/kubernetes/pull/126841

/hold

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks @carlory for the PR
Changes look good to me.

/lgtm
Merge after upstream the PR merge.

**Comment by dipesh-rawat** [comment]
Looks like the upstream changes https://github.com/kubernetes/kubernetes/pull/126841 are merged.

/unhold

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!

/approve

**Pull request merged**
