### PR TITLE
Update pick-right-solution.md

### PR DESCRIPTION
**Pull request by KYamani**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.17 Features: set Milestone to 1.17 and Base Branch to dev-1.17
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by sftim** [comment]
There is no [equivalent English-locale page](https://kubernetes.io/docs/setup/pick-right-solution/)

This change is an addition to the French localised pages, and not a localisation of the original content.
/hold

**Comment by sftim** [comment]
@KYamani do you need to declare an interest here?

**Comment by KYamani** [comment]
@sftim I would like to add this cloud provider in this french page 
I just did another PR for the english equivalent page: https://github.com/kubernetes/website/pull/18421

**Comment by remyleone** [comment]
@KYamani do you work for Hidora?

**Comment by KYamani** [comment]
Hi @remyleone, I work for Hidora

**Comment by KYamani** [comment]
Hi @sftim . Any update please ?

**Comment by sftim** [comment]
This PR needs a rebase.
I'm not an approver for French.
/uncc

**Comment by sftim** [comment]
@KYamani this PR is out of date _and_ does not meet the requirements of the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/).
I'm going to close it.

/close

**Pull request closed without merging**
