### PR TITLE
[ja] Fix configuration overview example link

### LINKED ISSUE #31248: [ja] Link to configuration overview example is broken
Link to configuration overview example is broken in content/ja/docs/concepts/configuration/overview.md

### PR DESCRIPTION
**Pull request by championshuttler**
Fix configuration overview example link

Fixes #31248

### CODE REVIEW

**Comment by nasa9084** [comment]
Thank you for contributing, please file associated isssue at first and refer it in PR description.

/assign
/cc @makocchi-git

**Comment by championshuttler** [comment]
@nasa9084 Done

**Comment by nasa9084** [comment]
en: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/configuration/overview.md?plain=1#L24
/approve

**Pull request merged**
