### PR TITLE
Reflect latest patch release changes

### PR DESCRIPTION
**Pull request by saschagrunert**
We now add the information about the regression introduced in the latest
patches. The final 1.18 release is now part of the documentation, too.
Beside that, we keep the cherry-pick deadline column and add a new one
"NOTE" to add required information.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Ready for review, PTAL @kubernetes/release-engineering @kubernetes/release-team-leads

**Review by cpanato — COMMENTED** [review]
lgtm

maybe we can update the dates for the next cycle?

- also as a follow up will add the note field in the schedule-builder in k/release,

**Comment by saschagrunert** [comment]
> maybe we can update the dates for the next cycle?

I did explicitly leave this out, let's follow-up on that.

> * also as a follow up will add the note field in the schedule-builder in k/release,

Yeah thank you!

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
