### PR TITLE
Add Indonesian translation for Pod Priority and Preemption

### PR DESCRIPTION
**Pull request by phanama**
Addresses #15341 

/assign @girikuncoro

### CODE REVIEW

**Comment by irvifa** [comment]
@phanama Thank you for your effort 🎉 🎉 

By the way, do you mind sharing the resource why we need to use klaster instead of kluster?

**Comment by girikuncoro** [comment]
This is tracked in this issue: https://github.com/jk8s/sig-docs-id/issues/20

**Comment by irvifa** [comment]
Okay.. thank you for your swift response @girikuncoro

**Pull request merged**
