### PR TITLE
[en] Update _index.md

### PR DESCRIPTION
**Pull request by yanrongshi**
Fix `e.g.` to `for example`
```yaml
content\zh-cn\docs\concepts\services-networking\_index.md
```

### CODE REVIEW

**Comment by Sea-n** [comment]
Could you explain more about why this change should be accept?

I think `e.g.` is a well-known and acceptable usage.

**Comment by yanrongshi** [comment]
> 


> 你能解释一下为什么这个改变应该被接受吗？
> 
> 我认为这`e.g.`是一种用途且可以接受的用途。

I read the code tonight, and it says no Arabic ,In there [Avoid Latin phrases ]( https://kubernetes.io/docs/contribute/style/style-guide/#avoid-latin-phrases) ,Maybe I'm wrong

**Comment by Sea-n** [comment]
If you think changing `e.g.` to `for example` would be better, please take a look at other relative files too.

```
content/en/docs/concepts/services-networking/_index.md
23:   * agents on a node (e.g. system daemons, kubelet) can communicate with all
26:Note: For those platforms that support `Pods` running in the host network (e.g.

content/en/docs/concepts/services-networking/service.md
610:  `externalName` field (e.g. `foo.bar.example.com`), by returning a `CNAME` record
634:This flag takes a comma-delimited list of IP blocks (e.g. `10.0.0.0/8`, `192.0.2.0/25`)
1291:previous.  This is not strictly required on all cloud providers (e.g. Google Compute Engine does

content/en/docs/concepts/services-networking/connect-applications-service.md
203:(my-nginx), and a DNS server that has assigned a name to that IP. Here we use the CoreDNS cluster addon (application name `kube-dns`), so you can talk to the Service from any pod in your cluster using standard methods (e.g. `gethostbyname()`). If CoreDNS isn't running, you can enable it referring to the [CoreDNS README](https://github.com/coredns/deployment/tree/master/kubernetes) or [Installing CoreDNS](/docs/tasks/administer-cluster/coredns/#installing-coredns). Let's run another curl application to test this:

content/en/docs/concepts/services-networking/windows-networking.md
57:| Overlay | Containers are given a vNIC connected to an external vSwitch. Each overlay network gets its own IP subnet, defined by a custom IP prefix.The overlay network driver uses VXLAN encapsulation. | Encapsulated with an outer header. | [win-overlay](https://github.com/containernetworking/plugins/tree/master/plugins/main/windows/win-overlay), Flannel VXLAN (uses win-overlay) | win-overlay should be used when virtual container networks are desired to be isolated from underlay of hosts (e.g. for security reasons). Allows for IPs to be re-used for different overlay networks (which have different VNID tags)  if you are restricted on IPs in your datacenter.  This option requires [KB4489899](https://support.microsoft.com/help/4489899) on Windows Server 2019. |
150:  * ICMP packets directed to pass through a remote network (e.g. pod to external internet communication via ping)

content/en/docs/concepts/services-networking/ingress.md
499:(e.g. persistent sessions, dynamic weights) are not yet exposed through the
```

Note that don't use auto replace and submit PR with 200 lines changed, it would be hard for us to review.

**Comment by yanrongshi** [comment]
> If you think changing `e.g.` to `for example` would be better, please take a look at other relative files too.
> 
> ```
> content/en/docs/concepts/services-networking/_index.md
> 23:   * agents on a node (e.g. system daemons, kubelet) can communicate with all
> 26:Note: For those platforms that support `Pods` running in the host network (e.g.
> 
> content/en/docs/concepts/services-networking/service.md
> 610:  `externalName` field (e.g. `foo.bar.example.com`), by returning a `CNAME` record
> 634:This flag takes a comma-delimited list of IP blocks (e.g. `10.0.0.0/8`, `192.0.2.0/25`)
> 1291:previous.  This is not strictly required on all cloud providers (e.g. Google Compute Engine does
> 
> content/en/docs/concepts/services-networking/connect-applications-service.md
> 203:(my-nginx), and a DNS server that has assigned a name to that IP. Here we use the CoreDNS cluster addon (application name `kube-dns`), so you can talk to the Service from any pod in your cluster using standard methods (e.g. `gethostbyname()`). If CoreDNS isn't running, you can enable it referring to the [CoreDNS README](https://github.com/coredns/deployment/tree/master/kubernetes) or [Installing CoreDNS](/docs/tasks/administer-cluster/coredns/#installing-coredns). Let's run another curl application to test this:
> 
> content/en/docs/concepts/services-networking/windows-networking.md
> 57:| Overlay | Containers are given a vNIC connected to an external vSwitch. Each overlay network gets its own IP subnet, defined by a custom IP prefix.The overlay network driver uses VXLAN encapsulation. | Encapsulated with an outer header. | [win-overlay](https://github.com/containernetworking/plugins/tree/master/plugins/main/windows/win-overlay), Flannel VXLAN (uses win-overlay) | win-overlay should be used when virtual container networks are desired to be isolated from underlay of hosts (e.g. for security reasons). Allows for IPs to be re-used for different overlay networks (which have different VNID tags)  if you are restricted on IPs in your datacenter.  This option requires [KB4489899](https://support.microsoft.com/help/4489899) on Windows Server 2019. |
> 150:  * ICMP packets directed to pass through a remote network (e.g. pod to external internet communication via ping)
> 
> content/en/docs/concepts/services-networking/ingress.md
> 499:(e.g. persistent sessions, dynamic weights) are not yet exposed through the
> ```
> 
> Note that don't use auto replace and submit PR with 200 lines changed, it would be hard for us to review.

Note that don't use auto replace and submit PR with 200 lines changed, it would be hard for us to review.

**Pull request closed without merging**
