### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by tengqm**
There are 3 commits in this PR.

- The first commit updates the go module for examples test.
- The second commit adapts the example test case to 1.23 changes.
- The third one fixes errors detected by the test case:
  * The service account token one must have `serviceAccountName` specified in order to be successfully validated.
  * In the PV duplicate example, containers can only refer to existing volumes. It is okay to mount the same volume more than once for different purposes (onto different paths).

### CODE REVIEW

**Comment by sftim** [comment]
Those three commits sound logically separate. No need to squash.
/remove-label tide/merge-method-squash

**Comment by bradtopol** [comment]
Hi @tengqm is there a technical reviewer that you know of that should review this?

**Comment by tengqm** [comment]
@bradtopol Since the fixes to the examples are related to volume mounts, maybe someone from SIG storage can help validate the changes, e.g. @jsafrane  @gnufied @msau42 .

**Comment by jsafrane** [comment]
lgtm from the storage side

**Pull request merged**
