### PR TITLE
Use port number in “Use Port Forwarding to Access Applications in a Cluster”

### LINKED ISSUE #26457: Use Port Forwarding to Access Applications in a Cluster
On Forward a local port to a port on the Pod section

this
`kubectl port-forward service/redis-master 7000:redis`

should be
`kubectl port-forward service/redis-master 7000:6379`

### PR DESCRIPTION
**Pull request by jailton**
Fix #26457

Preview: https://deploy-preview-26632--kubernetes-io-master-staging.netlify.app/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

/language en

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Use port number in “Use Port Forwarding to Access Applications in a Cluster”

**Comment by sftim** [comment]
@jailton / @adthonb - I'd like to see an explanation of _why_ this change makes sense. That way, someone looking at the commit history has context to understand it.

Would either of you be willing to add that explanation? A few lines might well be enough.

**Comment by adthonb** [comment]
@sftim REMOTE_PORT of `kubectl port-forward` must be a port number, not service name to map

**Comment by jailton** [comment]
Commit 99029b9 removes the Redis examples. This page needs to be rewritten to use the MongoDB examples. I'll close this PR and create another with the new page.

**Pull request closed without merging**
