### PR TITLE
Update status of CRD-related feature gates

### PR DESCRIPTION
**Pull request by nikhita**
Someone on #kubernetes-users on slack was confused if the subresources feature was indeed beta or not.... :disappointed: 

Question: Is this list auto-generated or is it updated manually? From a quick look, I think there are some more feature gates that need update. 

/cc @sttts @mbohlool

### CODE REVIEW

**Comment by alexvanboxel** [comment]
I'm the confused user: I even have a support ticket open with Google too see if the feature is enabled and they are again pointing to that documentation page.

**Comment by nikhita** [comment]
> I even have a support ticket open with Google too see if the feature is enabled and they are again pointing to that documentation page.

@alexvanboxel Thanks for following up about it here!

**Pull request merged**
