### PR TITLE
Fix broken link on Communication between Nodes and the Control Plane page

### PR DESCRIPTION
**Pull request by kadtendulkar**
Follow up on #34899

Updated the page [Communication between Nodes and the Control Plane](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/)

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Fix broken link on Communication between Nodes and the Control Plane page

**Comment by kbhawkey** [comment]
Preview:
https://deploy-preview-34900--kubernetes-io-main-staging.netlify.app/docs/concepts/architecture/control-plane-node-communication/#node-to-control-plane

**Comment by kbhawkey** [comment]
Thanks @kadtendulkar .
/approve

**Pull request merged**
