### PR TITLE
Format code style

### PR DESCRIPTION
**Pull request by angao**

### CODE REVIEW

**Comment by Bradamant3** [comment]
@angao a couple of things:

- as with another of your PRs, now that we're working with Hugo/Blackfriday, blocks inside listitems need to be formatted differently, with careful attention to indentation, to keep list numbering correct. See https://github.com/kubernetes/website/blob/master/content/en/docs/test.md
- a lot of folks don't put much in the way of commit messages in, but you're doing a lot to help with formatting issues, so if you could specify which issue you're addressing, and how, and why, that would help speed up the review.

Thanks!

**Comment by tengqm** [comment]
@angao Please resolve the conflict and respond to the review feedbacks. Thanks.

**Comment by angao** [comment]
@tengqm ok, I have resolved this conflict

**Comment by tengqm** [comment]
@angao pls check Bradamant3's comments on getting the numbered list correctly formatted. Basically, code blocks in a list need to be indented by 6 spaces.

**Comment by tengqm** [comment]
@angao You are correct. The current version works well. Thanks.
/lgtm
/approve

**Pull request merged**
