### PR TITLE
Update create-cluster-kubeadm.md

### PR DESCRIPTION
**Pull request by Boskey**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by Bradamant3** [comment]
@Boskey can you please address the comment ^^? Thanks!

**Comment by Boskey** [comment]
This one https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml

**Comment by neolit123** [comment]
> This one https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml

could you please explain what changes does it make?
what motivates the bump?

**Comment by Boskey** [comment]
The previous version did not work on successfully deploying Flannel in a cluster created with Kubeadm, not sure why. The latest ( Pull # 1904) from the CoreOS repo worked.

**Comment by neolit123** [comment]
ok, the commit you mentioned also includes an important fix.

but, please instead of this:
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```

modify the PR to use:
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml
```

thanks.

**Comment by Boskey** [comment]
Edited PR to add kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml instead

**Comment by Rajakavitha1** [comment]
@Bradamant3 could you please take a look and state your approval.
/assign @Bradamant3

**Comment by tfogo** [comment]
`kubectl apply -f` was in there twice by accident.
/lgtm
/approve

**Pull request merged**
