### PR TITLE
modify the error word of race

### PR DESCRIPTION
**Pull request by timyinshi**
Signed-off-by: timyinshi <shiguangyin@inspur.com>

/kind bug
/sig docs

modify the error word of ‘race’

### CODE REVIEW

**Comment by tengqm** [comment]
This PR contains a file named "\"?

**Comment by mengjiao-liu** [comment]
Is this PR still being updated? @timyinshi

**Comment by tengqm** [comment]
I'm closing this due to PR has been open for too long with no updates. Please feel free to reopen when you have interest/time to continue this work.
/close

**Pull request closed without merging**
