### PR TITLE
replace http helm link with https

### PR DESCRIPTION
**Pull request by oke-py**

### CODE REVIEW

**Comment by spurin** [comment]
Non-member feedback:
/lgtm

**Comment by sftim** [comment]
The failed preview looks spurious; this change is fine.

**Comment by sftim** [comment]
@oke-py can you rebase and force-push? That should trigger a retest.

**Comment by oke-py** [comment]
I'll do it after I go back home.

**Comment by tengqm** [comment]
Netlify finally responded ...
/lgtm
/approve

**Pull request merged**
