### PR TITLE
Fix markup for tutorials

### PR DESCRIPTION
**Pull request by utkarsh-singh1**
Updated /content/en/docs/tutorials/kubernetes-basics/deploy-intro.html to update-intro.html

- Remove extra </p> tag from the docs

- Updated headings in expose-intro.html and update-intro.html

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Updated Page - https://kubernetes.io/docs/tutorials/kubernetes-basics/

**Review by PranitRout07 — COMMENTED** [review]
You have removed extra paragraph html tags from deploy-intro.md file . I would suggest to update your PR title .

**Review by sftim — COMMENTED** [review]
Thanks

/lgtm

**Comment by utkarsh-singh1** [comment]
Thanks, @sftim @reylejano, for review and approval.

**Pull request merged**
