### PR TITLE
bump version of event-exporter

### PR DESCRIPTION
**Pull request by ameukam**
upgrade version of event-exporter in the example.

### CODE REVIEW

**Comment by ameukam** [comment]
merge when https://github.com/kubernetes/kubernetes/pull/67691 will be merged.
/hold

**Comment by tengqm** [comment]
@ameukam, please help check if this is supposed to go to releases-1.12 branch rather than master. 'master' here in website means 'release-1.11'.

**Comment by ameukam** [comment]
@tengqm i will tag it for the 1.12 release.

**Pull request merged**
