### PR TITLE
[bn] Localized content/en/case-studies/_index.html

### PR DESCRIPTION
**Pull request by Imtiaz1234**
Created ``_index.html``  under ``case-studies`` for Bengali (bn) documentation as   ``content/bn /case-studies/_index.html``

Localizes ``content/bn /case-studies/_index.html`` into Bengali

Issue: #31677

### CODE REVIEW

**Comment by sftim** [comment]
@Imtiaz1234 could you update this PR to target the branch [_dev-1.23-bn.1_](https://github.com/kubernetes/website/tree/dev-1.23-bn.1)?

**Review by mitul3737 — APPROVED** [review]
/lgtm

**Review by mitul3737 — APPROVED** [review]

**Pull request merged**
