### PR TITLE
Retain page “Mapping from dockercli to crictl” (cancel planned removal)

### PR DESCRIPTION
**Pull request by JayBeale**
Could we keep this page to continue to help people to ramp up on crictl commands?

### CODE REVIEW

**Comment by sftim** [comment]
- I'm wary of keeping “Mapping from dockercli to crictl“ _indefinitely_. For example, once v1.25 is the oldest release we document, we 
- If drop the statement, should we backport that change to older docs?

---

If we decide to postpone the removal but still drop it one day, when would we remove it? Maybe we could shift the page to a blog article (with a redirect) - allowing us to stop maintaining it.

**Comment by sftim** [comment]
/retitle Retain page “Mapping from dockercli to crictl” (cancel planned removal)

**Comment by bradtopol** [comment]
Assigning @tengqm since he is already engaged on this.
/assign @tengqm

**Comment by tengqm** [comment]
Shifting this to a blog page sounds a good idea to me.

**Comment by sftim** [comment]
> Shifting this to a blog page sounds a good idea to me.

@JayBeale would you be willing to work on that? The article can be quite short (or longer if you'd like it to be).

**Review by sftim — COMMENTED** [review]
/lgtm

We should work out what to do with this page.

**Comment by JayBeale** [comment]
> > Shifting this to a blog page sounds a good idea to me.
> 
> @JayBeale would you be willing to work on that? The article can be quite short (or longer if you'd like it to be).

I'm sorry I had missed this.  I could work on such an article...  Would this still be helpful?

**Pull request merged**
