### PR TITLE
Bump up Deployment version in cn concepts/services-networking folder

### PR DESCRIPTION
**Pull request by nashasha1**
I am creating a bunch of PRs for bumping up deployment version.  A pr contains all changes in a folder.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7350)

### CODE REVIEW

**Comment by heckj** [comment]
Could you please review that recommendation and update these PRs to [include min-kubernetes-server-version in the front-matter of the various documents](https://kubernetes.io/docs/home/contribute/style-guide/#versioning-kubernetes-examples)?

**Comment by steveperry-53** [comment]
@nashasha1 Changes to the cn content are done by the translation team in the kubernetes/kubernetes-docs-cn repo. So we don't take direct changes to cn content here in the kubernetes/website repo. Thanks.

**Comment by heckj** [comment]
@nashasha1 I'm going to go ahead and close these PRs for kubernetes/website - would love to have the same content applied to kubernetes/kubernetes-docs-cn

**Pull request closed without merging**
