### PR TITLE
Add content/pt/docs/concepts/architecture/cloud-controller.md

### PR DESCRIPTION
**Pull request by femrtnz**

### CODE REVIEW

**Comment by femrtnz** [comment]
Hey @jcjesus . Could you please have a look this PR?

you can review the page here as well: https://deploy-preview-13979--kubernetes-io-master-staging.netlify.com/pt/docs/concepts/architecture/cloud-controller/

/assign @jcjesus

**Comment by jcjesus** [comment]
@femrtnz in cloud-controller.md file, you translated Service Controller to Portuguese, but Node Controller and other not. I will suggest you translate all or neither.

**Comment by jcjesus** [comment]
@femrtnz I will suggest to you translate "Design de Arquitetura" to "Projeto de Arquitetura (Design)"

**Comment by jcjesus** [comment]
Hi @femrtnz!
I will suggest to you translate "Controlador de Node" to "Controlador de Nós", to not confusing with "NodeJS", hehehe

**Comment by femrtnz** [comment]
> Hi @femrtnz!
> I will suggest to you translate "Controlador de Node" to "Controlador de Nós", to not confusing with "NodeJS", hehehe
> 
> In this file, where contains the word "Node" I think we need translate to "Nó" and keep the pattern to translation , 'cause we have "Node Controller" and "Controlador de Node" in the same file.

@jcjesus Thanks for the review. I'm just worried to translate a specific Kubernetes name where we can lose the meaning within the context. e.g, using `kubectl get nodes`

**Pull request merged**
