### PR TITLE
[hi] Localize 'concepts/architecture/*' into Hindi

### PR DESCRIPTION
**Pull request by freddie400**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
[hi] Localize content/en/docs/concepts/architecture in hindi

#### Which issue(s) this PR fixes:
Completing this feature issue fixes part of https://github.com/kubernetes/website/issues/39548

#### Does this PR introduce a user-facing change?
```docs
localize-architecture
```

Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
https://github.com/kubernetes/website/issues/39548
```docs
- [KEP]: https://github.com/kubernetes/website/issues/39548
```

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@freddie400 Thank you for your PR, but IMO we don't need to create blank files as placeholders.
Instead, we can just add localized files directly (e.g., #39550).

One more thing is that in the issue #39548, you assigned yourself despite someone else has already assigned himself first.

Considering the aspects above, I think that marking this PR as duplicate over #39550 is more appropriate.
/triage duplicate
/hold

**Comment by freddie400** [comment]
sure @jihoon-seo, pardon me for the clutter. I didn't see any PR with this issue so I thought maybe I can help out with it.
Is there anything else I can help with? I'd love to contribute.
Thanks.

**Review by dipesh-rawat — COMMENTED** [review]
@freddie400 Would you be happy to close this PR as the reviewer has marked this as duplicate of PR #39550 and the other PR is more likely to get merged.

**Review by anubha-v-ardhan — COMMENTED** [review]
Hi @freddie400, we cannot merge this PR for the reason Jihoon has mentioned above. 
Please avoid making PRs with blank files (you can make draft PRs for WIP if you wish though)

For now I'll have to close this PR.

/close

**Pull request closed without merging**
