### PR TITLE
kubeadm: remove page about self-hosting support

### PR DESCRIPTION
**Pull request by neolit123**
this is targeting dev-1.21

xref https://github.com/kubernetes/kubeadm/issues/2299

The command "kubeadm alpha self-hosting" was removed in 1.21.
Remove the page that talks about self-hosting support in kubeadm

https://github.com/kubernetes/kubernetes/pull/97627
https://github.com/kubernetes/website/pull/25935

### CODE REVIEW

**Comment by neolit123** [comment]
searched for references of the page under "content/en" and could not find any.

/sig cluster-lifecycle
/kind deprecation
/priority important-soon

**Review by sftim — COMMENTED** [review]
/approve

**Comment by neolit123** [comment]
/cc knight42 
for LGTM

**Comment by pacoxu** [comment]
1.21 kubeadm has no sub command for `kubeadm alpha`.
Need we mark `alpha` command as unsupported in this release?
```
./kubeadm  alpha --help
Kubeadm experimental sub-commands

Usage:

Flags:
  -h, --help   help for alpha

Global Flags:
      --add-dir-header           If true, adds the file directory to the header of the log messages
      --log-file string          If non-empty, use this log file
      --log-file-max-size uint   Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --one-output               If true, only write logs to their native severity level (vs also writing to each lower severity level
      --rootfs string            [EXPERIMENTAL] The path to the 'real' host root filesystem.
      --skip-headers             If true, avoid header prefixes in the log messages
      --skip-log-headers         If true, avoid headers when opening log files
  -v, --v Level                  number for the log level verbosity
[root@daocloud ~]#
```

**Review by pacoxu — APPROVED** [review]
/lgtm

**Comment by neolit123** [comment]
> 1.21 kubeadm has no sub command for kubeadm alpha.
Need we mark alpha command as unsupported in this release?

it's fine if we leave `kubeadm alpha` even if it's empty.
commented on https://github.com/kubernetes/kubernetes/pull/100511

**Pull request merged**
