### PR TITLE
Hugo: Fix kubernetes-api.md

### PR DESCRIPTION
**Pull request by ajaeger**
Fix two tables that were not parsed and thus unformatted.
Fix link for kubectl.

### CODE REVIEW

**Comment by ajaeger** [comment]
@steveperry-53 , indeed - looks like wrong index of kubectl pages ;( Let me fix this specific example...

**Comment by Bradamant3** [comment]
@ajaeger sorry, this one also needs a merge conflict resolved.

In this case (as long as you have to mess with it anyway), I'd disagree with Steve and point the kubectl link to /docs/reference/kubectl/overview/
But it's not a big deal if you're not actually in the file. I'll check back and get merged as soon as the merge conflict is fixed.

**Comment by ajaeger** [comment]
@Bradamant3 , rebased - the two tables were fixed elsewhere, so that caused the merge conflict. I added one "-" for alignment - and followed your guideance on the link.

**Pull request merged**
