### PR TITLE
[zh] fix kubelet flag description

### PR DESCRIPTION
**Pull request by liuxu623**
same as https://github.com/kubernetes/website/pull/28443

### CODE REVIEW

**Comment by PI-Victor** [comment]
/assign
@tengqm could you please take a look at this?

**Comment by PI-Victor** [comment]
ah, based on @sftim [comments](https://github.com/kubernetes/website/pull/28750#issuecomment-873481444), i'm not sure we can accept localization changes in the dev branch. 
pending clarification

/hold

**Comment by sftim** [comment]
We can have this change ready to go into _main_ just after localization, or we can merge it in before release providing we're sure there's no risk of provoking a merge conflict.

I'd favor the first approach: hold this, but cherry-pick the same work into a new PR that targets _main_, immediately post release.

**Comment by tengqm** [comment]
/hold
Let's hold this till 1.22 is out.

**Comment by tengqm** [comment]
/hold
Let's hold this till 1.22 is out.

**Comment by PI-Victor** [comment]
i'm removing this from the milestone, but it should be merged as soon as it's possible after the release into main.

/milestone clear

**Comment by tengqm** [comment]
@liuxu623 Please retarget this to "main" branch.

**Comment by liuxu623** [comment]
> @liuxu623 Please retarget this to "main" branch.

PTAL #29273

**Pull request closed without merging**
