### PR TITLE
Fixing various minor grammar typos and grammar issues

### PR DESCRIPTION
**Pull request by RiRa12621**
Apparently my IDE went wild when I plugged the website repo in and my OCD couldn't live with it, so here's a bunch of minor grammar and spelling mistakes all around the repo.

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @RiRa12621,

Thanks for contributing k8s website! In this repo, we limited to one language for each PR.
Please just update the `en` content and leave the `zh-cn` and `uk` to native speakers to change after this PR merged.

**Comment by RiRa12621** [comment]
Ok, I'll adjust the PR.

**Comment by Sea-n** [comment]
Hey @RiRa12621,

It's been a while since the last update, would you like to address issues in the previous comments so that we can move forward?

**Comment by RiRa12621** [comment]
Hey, yeah just have some private stuff that goes first and then will get to this.

**Comment by Sea-n** [comment]
Thanks for purposing this PR. But since you didn't respond for a while, we have to close this PR now.
/close

Feel free to `/reopen` when you are ready to move forward.
(Note that please don't push anything while PR closed, or you won't be able to reopen it.)

**Pull request closed without merging**
