### PR TITLE
Update cri.md as a fix for https://github.com/kubernetes/website/issues/11779

### PR DESCRIPTION
**Pull request by Rajakavitha1**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Update the document as a fix for: https://github.com/kubernetes/website/issues/11779

**Comment by bart0sh** [comment]
@Rajakavitha1 Thank you for the patch.

It's still looks confusing to me though. This:
```
# Install Docker or Docker CE
## Install Docker from Ubuntu's repository:
apt-get update
apt-get install -y docker.io

## Install prerequisites.
apt-get update && apt-get install apt-transport-https ca-certificates curl software-properties-common

```

Still looks like suggestion to install prerequisites after installing docker. I like the idea and I find current version confusing, so please continue with this PR. We need to make it clear that "Install Docker" and "Install Docker CE" are 2 alternatives and should not be done together.

**Comment by Rajakavitha1** [comment]
@bart0sh Thanks for the review comments. I updated the instructions based on https://docs.docker.com/v17.09/engine/installation/linux/docker-ce/ubuntu/ and https://docs.docker.com/v17.09/engine/installation/linux/docker-ce/centos/. Please let me know if the changes are okay?

**Comment by bart0sh** [comment]
@Rajakavitha1 Thanks for the update.

As far as I can see you removed installation from Ubuntu and CentOS repos and only left Docker CE installation. May I ask what's the reason for that?

**Comment by Rajakavitha1** [comment]
@bart0sh That is right!!! the reason I removed the instruction regarding the installation of docker (1.13.1) as listed in https://github.com/kubernetes/website/issues/11779 and updated the instructions for Docker CE (1.18.1) because the official Docker documents only have instructions for Docker CE and Docker EE as listed in https://github.com/docker/docker.github.io/blob/master/install/linux/docker-ce/ubuntu.md. It may not be a good idea to have instructions for Docker 1.13 in our documents considering that the Official Docker Install guide recommends uninstalling older versions.

**Comment by bart0sh** [comment]
@Rajakavitha1 Thanks for the explanations! Now it makes sense to me. 

/lgtm

**Comment by bart0sh** [comment]
Sorry, forgot to mention. Please, squash your 2 commits into one.

**Comment by bart0sh** [comment]
@Rajakavitha1 and provide more details in the commit message

**Comment by Rajakavitha1** [comment]
Closing this PR because I am not able to squash the 2 commits. Opening a new PR and assigning it to @bart0sh for approval.

**Pull request closed without merging**
