### PR TITLE
Update weave-network-policy.md

### PR DESCRIPTION
**Pull request by brb**
- Remove the obsolete example.
- Include support links.

/cc @bboreham 

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6960)

### CODE REVIEW

**Comment by tengqm** [comment]
@brb please sign the CLA so that we can get this merged.

**Comment by brb** [comment]
@tengqm done.

**Comment by tengqm** [comment]
wow ... after this revision, this page is too short to deserve a separate page. Seems all contents about network policy support have been removed?

**Comment by brb** [comment]
@tengqm Thanks for the review. However, I disagree with removing the page as it contains info about verifying the installation and links to the installation steps and troubleshooting. Also, the pages of other Network Policy providers are relatively small.

**Comment by tengqm** [comment]
@brb, I didn't suggest a removal of the page. I was referring to some useful information such as checking the log to confirm that network policy is working or to diagnose the problems if it is not working. I don't have a strong opinion on whether they should be kept though.

**Comment by brb** [comment]
The main reason for the removal is that the listed information is obsolete, and some users have already tripped over it. Also, Weave Network Policy implementation had quite a few changes in the past, and it will change in the future. So, to prevent from similar situations, I suggest to keep the relevant information at the single place, i.e. at the Weave Net website.

**Comment by tengqm** [comment]
@brb, okay.

**Pull request merged**
