### PR TITLE
Fix issue with concepts/storage/volumes.md

### LINKED ISSUE #20835: Issue with k8s.io/ko/docs/concepts/storage/volumes/
**This is a Bug Report**

**Problem:**
Line 73:
   * [fc (파이버 채널))](#fc)
There is extra bracket symbol in the link.

**Proposed Solution:**
Line 73:
   * [fc (파이버 채널)](#fc)

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/storage/volumes/

/language ko

### PR DESCRIPTION
**Pull request by SangshikLee**
This fixes #20835 .

This is my first work for  kubernetes korean localization. 
Thank you.

### CODE REVIEW

**Comment by SangshikLee** [comment]
Preview: https://deploy-preview-20836--k8s-dev-ko.netlify.app/docs/concepts/storage/volumes/#types-of-volumes

**Comment by pjhwa** [comment]
@SangshikLee Thank you for your first contribution!
/lgtm

**Comment by pjhwa** [comment]
> Preview: https://deploy-preview-20836--k8s-dev-ko.netlify.app/docs/concepts/storage/volumes/#types-of-volumes

https://deploy-preview-20836--k8s-dev-ko.netlify.app/ko/docs/concepts/storage/volumes/#%EB%B3%BC%EB%A5%A8-%EC%9C%A0%ED%98%95%EB%93%A4

**Comment by seokho-son** [comment]
Thank you @SangshikLee. Welcome to Kubernetes Korean localization !
/approve

**Pull request merged**
