### PR TITLE
localization for subscribe button

### PR DESCRIPTION
**Pull request by Arhell**
issue #21093
en [PR ](https://github.com/kubernetes/website/pull/20878)

/language pl

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-21103--kubernetes-io-master-staging.netlify.app/pl/#kubeweekly

**Comment by sftim** [comment]
Echoing https://github.com/kubernetes/website/pull/21103#issuecomment-631975182
/approve

**Pull request merged**
