### PR TITLE
Update garbage-collection.md

### PR DESCRIPTION
**Pull request by ayushpatil2122**
### Issue
#47871

### CODE REVIEW

**Comment by tengqm** [comment]
Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). To find out what are the upstream changes to be synced, do this **on the main branch**:

```shell
./scripts/lsync.sh content/zh-cn/docs/concepts/architecture/garbage-collection.md
```

/hold

**Comment by ayushpatil2122** [comment]
ok

**Comment by windsonsea** [comment]
After checking

- [English history](https://github.com/kubernetes/website/commits/main/content/en/docs/concepts/architecture/garbage-collection.md)
- [Chinese history](https://github.com/kubernetes/website/commits/main/content/zh-cn/docs/concepts/architecture/garbage-collection.md)

all in-synced content have been synced, so this improvement seems acceptable.

**Comment by tengqm** [comment]
> After checking
> 
>     * [English history](https://github.com/kubernetes/website/commits/main/content/en/docs/concepts/architecture/garbage-collection.md)
> 
>     * [Chinese history](https://github.com/kubernetes/website/commits/main/content/zh-cn/docs/concepts/architecture/garbage-collection.md)
> 
> 
> all in-synced content have been synced, so this improvement seems acceptable.

Thanks for confirmation.
/approve

**Pull request merged**
