### PR TITLE
Clean up gifs under zh/docs/setup/production-environment/windows

### PR DESCRIPTION
**Pull request by ydcool**
Ref: #19116

/kind cleanup

### CODE REVIEW

**Review by tanjunchen — COMMENTED** [review]
Thanks.
/approve

**Comment by tengqm** [comment]
pls point this to the exact upstream change. #19116 is a collective change.

**Comment by ydcool** [comment]
> pls point this to the exact upstream change. #19116 is a collective change.

Okey I'll try to find it out.

**Comment by ydcool** [comment]
It's a little bit hard to find the original deletion of this files because the file history was lost during release of 1.18, current file history just like this: 
```shell
❯ git log --pretty=oneline -- content/en/docs/setup/production-environment/windows/kubecluster.ps1-install.gif --full-history
998fba98d72069a70a8ce5fc2980def92654218d (tag: snapshot-initial-v1.18) Official 1.18 Release Docs (#19116)
b99438cd2830623ecc4656a3bc9dd2355c17070e kubeadm deployment instructions for Windows (#15750)
```

**Comment by ydcool** [comment]
Well I found it in #19217. Maybe I should also do a check for other changes in that pr.
/hold

**Comment by ydcool** [comment]
@tengqm Question:  the file `content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md` which has several lines update in upstream commit, was never translated into Chinese, and translate task still open here [website-tasks#3458](https://github.com/k8smeetup/website-tasks/issues/3458). Should I add a translation here or in a new pr?

**Comment by ydcool** [comment]
content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
content/en/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md

**Comment by ydcool** [comment]
Finished checking for other changes in upstream commit and found no more change need to apply here, they're all updated, for example the `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md`  was updated in #23199.

**Comment by tengqm** [comment]
website-tasks#3458 has been stalling for about a year. Feel free to override it if needed.

**Comment by tengqm** [comment]
About files out of sync, please help file issues.
If this PR is good to go, please leave a comment.
I'm leaving an approval here in case the PR is ready.
/approve

**Comment by ydcool** [comment]
Well, let's move on. I'll open a new issue for those three files.
/unhold

**Pull request merged**
