### PR TITLE
Add dipesh to en-localization reviewers

### PR DESCRIPTION
**Pull request by dipesh-rawat**
I am interested in joining the English reviewers.

As an existing K8s org member for sometime, I have actively participated in reviewing, working, and engaging with incoming issues and pull requests in k/website repo. 

- [Reviewed PRs](https://github.com/kubernetes/website/pulls?q=is%3Aissue+involves%3Adipesh-rawat+label%3Alanguage%2Fen+) with `language/en` label: **200+** 
- The number of [issues engaged with](https://github.com/kubernetes/website/issues?q=is%3Aissue+involves%3Adipesh-rawat+): **150+**
- [sig-doc devstats contributions](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=SIG%20Docs&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All)

Search for PRs involving me (300+): https://github.com/kubernetes/website/pulls?q=is%3Apr+involves%3Adipesh-rawat+

Please consider adding me to the English language reviewers' list as I am confident that I can continue to be of assistance.
If it is not currently feasible to add me, I would be grateful for any feedback or guidance that can assist me in working towards becoming a reviewer in the future.

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
> /hold This should happen in https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml first.

I think this is good to proceed now, given that PR https://github.com/kubernetes/org/pull/4292 has been merged, successfully adding to sig-docs/teams.yaml as per the above instruction.

/unhold

**Comment by dipesh-rawat** [comment]
@sftim @reylejano Just a quick friendly check-in! Since https://github.com/kubernetes/org/pull/4292 has already been merged, could you please consider moving forward with approving this PR as well? Thank you so much!

**Review by sftim — COMMENTED** [review]
Thanks

/lgtm

**Review by sftim — APPROVED** [review]
Thanks @dipesh-rawat

**Pull request merged**
