### PR TITLE
use https for link on md doc

### PR DESCRIPTION
**Pull request by eatjeff**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@eatjeff
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
:wave: @eatjeff .
Would you verify that you have signed the CLA (GitHub account information matches CLA information)?

**Comment by kbhawkey** [comment]
@eatjeff .
This PR includes changes from PRs:
https://github.com/kubernetes/website/pull/26305
https://github.com/kubernetes/website/pull/26304

**Comment by mrbobbytables** [comment]
The CLA has not been signed, going to go ahead and close this for now. It can be reopened at a later date after the CLA issue has been resolved.

/close

**Pull request closed without merging**
