### PR TITLE
[zh-cn] fix outdated link/anchor

### PR DESCRIPTION
**Pull request by hunshcn**
All files involving changes have been checked for anchor availability, and there is no problem.

### CODE REVIEW

**Comment by windsonsea** [comment]
Please refer to [zh-cn localization guide](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#update).

Please confirm that all in-synced content from those 29 files has been included. It is not recommended to make batch changes to these files, as it may compromise the effectiveness of `./scripts/lsync.sh`.

/hold
until all pages are confirmed.

**Comment by hunshcn** [comment]
In addition, I wonder why lsync checking is not a ci action.

**Comment by hunshcn** [comment]
Since the previous batch fixes for link errors caused a lot of Chinese documents to become outdated, I think batch fixes are necessary.

**Comment by windsonsea** [comment]
You need to check those files one by one, by running this command on your `main` branch like:

```
./scripts/lsync.sh content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
```

**Comment by hunshcn** [comment]
I know, but I'm off work and the computer isn't with me, and I've run the

**Comment by hunshcn** [comment]
image

**Comment by windsonsea** [comment]
Run that command on your `main` branch. If it doesn't work, you need to check each zh and en history one by one, find out and sync  those differences.

**Comment by hunshcn** [comment]
not main, `fix/link-zh` is right

**Comment by hunshcn** [comment]
我想图片应该很清晰了，没有差异

**Comment by hunshcn** [comment]
This pr involves more documents, so I hope to get quick access. Do you agree with unhold? @windsonsea

**Comment by windsonsea** [comment]
Please read and understand https://github.com/kubernetes/website/pull/44669#issuecomment-1880933854 and https://github.com/kubernetes/website/pull/44669#issuecomment-1882113562, thanks.

**Comment by hunshcn** [comment]
```bash
 git show HEAD | grep zh-cn| grep +++ | sed -e "s/+++ b\///" | xargs -I {} ./scripts/lsync.sh {}
```
这是等效的，他会列出所有对于 zh-cn 的更改，依次进行 lsync.sh
@windsonsea

**Comment by windsonsea** [comment]
中文本地化团队不接受任何文件的部分修改，这样批量修改 29 个文件会有很大风险，你需要把 29 个文件中与 en 差异的内容全部同步过来，能明白吗？

而且上面已经列了 2 个文件有大量差异，你看不到？

**Comment by hunshcn** [comment]
.........我知道了，我错误理解了这个lsync 的作用，我之前认为他是一个 diff，结果似乎是很简陋的 commit 时间对比。我明白您的意思了，很抱歉。我进行修改

**Comment by hunshcn** [comment]
Well, it probably does need to be held for a while, let me synchronize the contents of these involved files inside a new pr. This pr shouldn't involve changes other than LINK.

**Comment by hunshcn** [comment]
remove the changes of following 8 files
```
content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
content/zh-cn/docs/reference/access-authn-authz/authentication.md
content/zh-cn/docs/reference/access-authn-authz/authorization.md
content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md
content/zh-cn/docs/reference/access-authn-authz/kubelet-authn-authz.md
content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md
content/zh-cn/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
```

They will submit independently (because it will involve more content changes)

**Comment by hunshcn** [comment]
```bash
export hash=a4dd61c;git show $hash | grep zh-cn | grep +++ | sed -e "s/+++ b\///" | xargs -S 10000 -I {} bash -c 'echo ========{}======== && comm -23 <(./scripts/lsync.sh {} | grep -E "^-" | grep -v -E "^---") <(git show $hash {} | grep -E "^-" | grep -v -E "^---")'
```

run on `main`, may be helpful for review sync status

**Comment by hunshcn** [comment]
@windsonsea request for unhold

**Comment by hunshcn** [comment]
ping

**Comment by windsonsea** [comment]
See https://github.com/kubernetes/website/pull/44669#issuecomment-1884072767.

**Comment by hunshcn** [comment]
所以现在的问题是不接受批量提交还是认为内容未同步，内容已同步。如果不接受批量提交我就close了

**Comment by tengqm** [comment]
```
git checkout main
./scripts/lsync.sh content/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node.md
```

There are still partial-sync problems.
Fixing links in a batch is okay, and sometimes even preferred.

**Comment by tengqm** [comment]
Okay, the mentioned file is not part of this PR now.
/lgtm

**Pull request merged**
