### PR TITLE
Fix a typo in flowchart.svg of extend-kubernetes concepts

### PR DESCRIPTION
**Pull request by 3point2**
"Do you want ot change" -> "Do you want to change". The rest of the diff is due to opening and saving the file on draw.io.

### CODE REVIEW

**Comment by 3point2** [comment]
I'm not sure why draw.io saved the file as 1155x911 instead of the original 809x638. I don't see anywhere in the UI where I could specify the original dimensions.

**Review by Affan-7 — COMMENTED** [review]
It's double in the size compared to the previous image (not a significant issue, ~40Kb). But it would be better if we can decrease the resolution.

Overall LGTM

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by windsonsea** [comment]
The size is extended too large. You can use `inkscape` instead of draw.io. Refer to https://kubernetes.io/docs/contribute/localization/#translating-svg-images

**Comment by windsonsea** [comment]
/retitle Fix a typo in flowchart.svg of extend-kubernetes concepts

**Comment by 3point2** [comment]
Thanks for the tip @windsonsea, I've redone the change with Inkscape. The `<!-- Do not edit this file with editors other than draw.io -->` comment at the top put me off trying that initially.

**Comment by anjum-edge** [comment]
check the html and css after that, go to the flowchart to lookout for the bugs

**Comment by 3point2** [comment]
I gave up on using an SVG editor and just directly edited the file using a text editor. I think it looks OK now?

**Review by Gauravpadam — COMMENTED** [review]
The [Preview](https://deploy-preview-43545--kubernetes-io-main-staging.netlify.app/docs/concepts/extend-kubernetes/) looks good

Thanks for the PR!

**Comment by windsonsea** [comment]
/lgtm

Fix a typo from "want ot" to "want to".

**Pull request merged**
