### PR TITLE
Adding Netris

### PR DESCRIPTION
**Pull request by alex-netris**
Netris is an automatic netops software with Kubernetes API integration
This contribution will be useful for Kubernetes users that running local private clusters.

### CODE REVIEW

**Comment by alex-netris** [comment]
I signed it

**Comment by alex-netris** [comment]
I signed it

**Comment by alex-netris** [comment]
I signed it

**Comment by zparnold** [comment]
@alex-netris thanks for your contribution! 🎉 We really would love to have it, unfortunately to continue we need to have your (or your company's) signature on a CLA! For now I'm going to close this, but fret not! You can re-open whenever you have a chance. Thanks!

(Also I believe @jimangel provided the instructions to troubleshoot the problem) 

/close

**Pull request closed without merging**
