### PR TITLE
WIP: PodSecurity alpha 1.22 documentation placeholder

### PR DESCRIPTION
**Pull request by tallclair**
Placeholder PR for PodSecurity alpha v1.22 documentation.

For https://github.com/kubernetes/website/issues/28866, https://github.com/kubernetes/enhancements/issues/2579

### CODE REVIEW

**Comment by sftim** [comment]
/sig security
/sig auth
Great to see this drafted!

**Comment by sftim** [comment]
Tip: update https://kubernetes.io/docs/concepts/security/ to hyperlink to the new policy page. 
Not sure how? SIG Docs can help.

**Comment by ritpanjw** [comment]
Hello @tallclair  :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before **Tuesday 20th of July, 11:59 PM PDT**. Thank you!

**Comment by PI-Victor** [comment]
> Hello @tallclair 👋 please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before **Tuesday 20th of July, 11:59 PM PDT**. Thank you!

Hi @tallclair, friendly reminder that today is the deadline for PRs ready for review, please make sure this PR is ready for review by the end of the day, thank you!

**Comment by liggitt** [comment]
@sejr picked up the documentation for this feature in https://github.com/kubernetes/website/pull/28903, where it is under active review. This PR should probably be closed in favor of that one.

**Comment by PI-Victor** [comment]
thanks, for the heads up
/close

**Pull request closed without merging**
