### PR TITLE
[ja] fix links to ephemeral volume types

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/33565/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Comment by Arhell** [comment]
I only updated the links listed here https://github.com/kubernetes/website/pull/33565/files
For some reason my IDE did the rest.

**Comment by atoato88** [comment]
This PR updates two things:
- updates [links refered in PR discription](https://github.com/kubernetes/website/pull/33565/files).
- replaces CR LF (\r\n) with LF (\n).
 
Almost all files in this repository use LF(\n) not CR LF(\r\n), so it's OK for me.
And links updated by this PR are OK too.

**Pull request merged**
