### PR TITLE
Add kubectl diff in kustomize

### PR DESCRIPTION
**Pull request by zhouya0**
Add `kubectl diff` in `kustomize`.
Part of https://github.com/kubernetes/kubernetes/issues/86525

### CODE REVIEW

**Comment by julianvmodesto** [comment]
Thanks @zhouya0 !

/lgtm

**Comment by julianvmodesto** [comment]
Assigning v1.18 docs release lead, PTAL

/assign @VineethReddy02

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-19586--kubernetes-io-vnext-staging.netlify.com/docs/tasks/manage-kubernetes-objects/kustomization/

**Comment by VineethReddy02** [comment]
/lgtm
@sftim do you any feedback here?

**Pull request merged**
