### PR TITLE
[zh-cn]Sync topology-spread-constraints.md

### PR DESCRIPTION
**Pull request by xzyangPlus**
sync with #37895 

[> content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md](https://github.com/kubernetes/website/pull/37895)

### CODE REVIEW

**Comment by Sea-n** [comment]
Please include #37373 and #37688 as well.

**Comment by tengqm** [comment]
@xzyangPlus This one needs a rebase. Please help check.

**Comment by Sea-n** [comment]
Since you are not respond for a while, someone opened PR #38366 and get the work done already.

Thanks, close as completed.
/close

**Pull request closed without merging**
