### PR TITLE
removed the italics

### PR DESCRIPTION
**Pull request by Deepakktripathy**
removed italics from mermaid figure; fixed issue #30641

### CODE REVIEW

**Review by anubha-v-ardhan — COMMENTED** [review]
/lgtm

Thank you @Deepakktripathy :)

**Comment by anubha-v-ardhan** [comment]
[Preview](https://deploy-preview-30792--kubernetes-io-main-staging.netlify.app/docs/contribute/new-content/)

**Comment by divya-mohan0209** [comment]
Taking lgtm comment (https://github.com/kubernetes/website/pull/30792#pullrequestreview-825545779) from Anubhav and approving the PR.

**Pull request merged**
