### PR TITLE
[ja] Add --rm for temporary pod command

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/41820/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The proposed change in sync with 'en' PR

/lgtm

**Review by Vikash-8090-Yadav — APPROVED** [review]
LGTM, Thank You :+1:

**Comment by atoato88** [comment]
@nasa9084 
Could you review this?

**Review by Arhell — COMMENTED** [review]
@nasa9084

**Pull request merged**
