### PR TITLE
Merged main dev 1.31

### PR DESCRIPTION
**Pull request by MaryamTavakkoli**
Branch sync to update `dev-1.31` branch with `main`

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/approve

**Comment by dipesh-rawat** [comment]
This also needs official approval required from [sig-docs-website-owner](https://github.com/kubernetes/website/blob/dev-1.31/OWNERS_ALIASES#L11)

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks!
/approve

**Pull request merged**
