### PR TITLE
blog: add etcd post for December 11, 2018

### PR DESCRIPTION
**Pull request by gyuho**
Not including the CNCF one, *yet*.

/cc @jpbetz

### CODE REVIEW

**Comment by gyuho** [comment]
@kbarnard10 https://github.com/cncf/toc/pull/143 has been merged and it's announced here https://www.cncf.io/blog/2018/12/11/cncf-to-host-etcd/.

**Comment by gyuho** [comment]
Thanks @kbarnard10

**Comment by d-nishi** [comment]
Thanks @kbarnard10 @gyuho

**Pull request merged**
