### PR TITLE
Update volumes.md

### PR DESCRIPTION
**Pull request by kamyar**
typo fix

### CODE REVIEW

**Comment by tengqm** [comment]
Whoops ... no CLA
/approve cancel

**Review by Arhell — COMMENTED** [review]
More info about CLA
https://github.com/kubernetes/website/pull/28771#issuecomment-873319331

**Comment by kamyar** [comment]
@Arhell @tengqm  I tried to follow instruction, I logged in with github but received nothing to sign.
Honestly the CLA process is more time consuming that it should be imo, this definitely disincentivizes people from contributing.
Please feel free to close this PR and open a new PR by someone already with CLA signed.

**Comment by tengqm** [comment]
@kamyar Sorry to hear that the process has not been smooth for you. Please do raise your concern to the #sig-contribx channel on kubernetes slack.
/close

**Pull request closed without merging**
