### PR TITLE
Branch sync: Merge `master` into `release 1.18`

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Branch sync: Merge `master` into `release 1.18`

cc: @zacharysarah @jimangel @sftim @kbhawkey 

/hold

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @savitharaghunathan .
I don't immediately see any issues. How is this merge coordinated with lifting the hold on the repository?

**Comment by savitharaghunathan** [comment]
@kbhawkey : This needs to be merged first before merging `dev-1.19` into main branch. I will have to manually remove the hold on this once we have a go

**Comment by jimangel** [comment]
Per discussion [here](https://kubernetes.slack.com/archives/C1J0BPD2M/p1598466973088100?thread_ts=1598447979.070600&cid=C1J0BPD2M), I am manually merging this PR as part of the 1.19 release. 🎉

**Pull request merged**
