### PR TITLE
[hi] Footer "Home" now reads "Documentation"

### PR DESCRIPTION
**Pull request by aj11anuj**
Resolves Hindi localization part of Issue #43068

### CODE REVIEW

**Comment by aj11anuj** [comment]
/retitle [hi] Footer "Home" now reads "Documentation"

**Review by Gauravpadam — COMMENTED** [review]
Since I've made the en pr, These changes lgtm

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/lgtm

[Preview Page](https://deploy-preview-43069--kubernetes-io-main-staging.netlify.app/hi/docs/home/)

**Comment by divya-mohan0209** [comment]
The footer is already showing the required content per another PR. Screencap attached below. 
Screenshot 2023-12-07 at 10 20 02 AM

Closing the PR since it is no longer required.
/close

**Pull request closed without merging**
