### PR TITLE
Fix issue with k8s.io/docs/reference/kubectl/cheatsheet/

### LINKED ISSUE #11926: Issue with k8s.io/docs/reference/kubectl/cheatsheet/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#creating-objects
kubectl run nginx --image=nginx  <== will not run with the v1.12+

**Proposed Solution:**
kubectl create deployment nginx --image=nginx 

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/cheatsheet/

### PR DESCRIPTION
**Pull request by tuanvcw**
Close #11926

### CODE REVIEW

**Comment by tengqm** [comment]
netlify failure not related to this PR
/lgtm

**Comment by tuanvcw** [comment]
Hi @tengqm 
Thank you very much.
Do you have any suggestion for netlify failure? Do we have recheck or anything like that?
Have a great day ahead :)

**Comment by tengqm** [comment]
@tuanvcw Try make some trivial changes to your PR and do

```
git commit --amend
git push -f
```

**Comment by rlenferink** [comment]
@tengqm Is it already possible to merge this PR?

**Comment by tuanvcw** [comment]
Hi @tengqm
Thanks to your suggestion, netlify failure has just been solved :)
Wish you a great week ahead !

**Pull request merged**
