### PR TITLE
Update create-cluster-kubeadm.md

### PR DESCRIPTION
**Pull request by mabazyar**
The URL for kube-flannel.yml needs to be updated to get kubeadm worked.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@mabazyar Thanks for the fix!
/lgtm

**Comment by Bradamant3** [comment]
@mabazyar you also need to sign the CLA. Let me know if you need help!

**Comment by tfogo** [comment]
Hi @mabazyar, thank you for the PR. Based on the feedback from @neolit123 I'm going to close this for now. If you do want to update the SHA, please feel free to re-open this PR (or open a new PR) with your new changes. Thanks.

/close

**Pull request closed without merging**
