### PR TITLE
Backport "layouts/docs/release-info.html" to release-1.27

### PR DESCRIPTION
**Pull request by dipesh-rawat**
Addressing issue #42812

Copied layouts/docs/release-info.html from main branch to update release-1.27 docs

Initial PR to add the layout: #41370

PR to refine the layout: #42835

### CODE REVIEW

**Comment by Shubham82** [comment]
Thanks @dipesh-rawat 
/lgtm

**Comment by kbhawkey** [comment]
Hi @dipesh-rawat 
Can you explain why these changes should be back ported to the previous docs versions?
Thanks

**Comment by dipesh-rawat** [comment]
> Hi @dipesh-rawat Can you explain why these changes should be back ported to the previous docs versions? Thanks

Hello @kbhawkey,  The conditional layout was implemented as we needed to display [release information](https://kubernetes.io/releases/) only for the current latest version of http://k8s.io/ while hiding it for older supported versions. Since the conditional layout changes were merged in main branch after the v1.28 release, without back-porting these changes, the older supported versions ([v1.27](https://v1-27.docs.kubernetes.io/releases/), [v1.26](https://v1-26.docs.kubernetes.io/releases/), [v1.25](https://v1-25.docs.kubernetes.io/releases/), [v1.24](https://v1-24.docs.kubernetes.io/releases/)) of docs would not benefit from this functionality.

_**Reference**:
Issue to add layout to hide release information on older versions: https://github.com/kubernetes/website/issues/29428
PR to add the layout: https://github.com/kubernetes/website/pull/41370 (Refined in https://github.com/kubernetes/website/pull/42835)
Issue for back porting to older versions: https://github.com/kubernetes/website/issues/42812_

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-42817--k8s-v1-27.netlify.app/releases/

**Pull request merged**
