### PR TITLE
Update Flannel's configuration file url

### PR DESCRIPTION
**Pull request by kkonovodoff**
# Unable to install Flannel with actual link 
I created a brand new cluster (v1.22.1) and tried to apply the Flannel's config file on it.

Output with actual link:
```bash
$> kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml
serviceaccount/flannel created
configmap/kube-flannel-cfg created
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
unable to recognize "https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
```

Assuming [this config](https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml) as deprecated for Kubernetes v1.17+.

New one found on Flannel's official repository: https://github.com/flannel-io/flannel.

## Behaviour with updated official url

```bash
$> kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
podsecuritypolicy.policy/psp.flannel.unprivileged created
clusterrole.rbac.authorization.k8s.io/flannel created
clusterrolebinding.rbac.authorization.k8s.io/flannel created
serviceaccount/flannel unchanged
configmap/kube-flannel-cfg configured
daemonset.apps/kube-flannel-ds created
```

_(My first PR here, tell me if something's wrong or could be improve)_

### CODE REVIEW

**Comment by kkonovodoff** [comment]
Linked my CLA account after doing this PR, everything should be fine now 👍

**Review by sftim — CHANGES_REQUESTED** [review]
I'm afraid this is the wrong fix @kkonovodoff 

Instead, we should update this page to be current based on the latest English version of https://k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

/hold

**Comment by kkonovodoff** [comment]
Hi @sftim and thank you for your reply

You're right, the page you mention seems way better, do you plan to translate it in French or will you make the English version as default? Can I help somehow?

**Comment by sftim** [comment]
Hi @kubernetes/sig-docs-fr-owners - do we have any specific plans for updating that page?

**Comment by remyleone** [comment]
Not at the moment. Could we merge this PR as a first step?

**Comment by sftim** [comment]
@remyleone our SIG-wide policy is only to make changes when these have been made and accepted into the upstream (English) localization.

@kkonovodoff if _you_ would be willing to update that page based on upstream, I can try to give you some help with the work. I'm not a native French speaker though.

**Comment by kkonovodoff** [comment]
@sftim I would be glad to translate the latest English version in order to update the French one!

**Comment by kkonovodoff** [comment]
@sftim Should I close this PR and open another one with the update of that page based on upstream?

**Comment by sftim** [comment]
I think a new PR is the right way to go here.

**Pull request closed without merging**
