### PR TITLE
KEP 1659 topology: trivial non-English changes

### PR DESCRIPTION
**Pull request by thockin**
This PR implements the "trivial" parts of https://github.com/kubernetes/website/pull/24783 for non-English languages.

There are still some non-trivial changes that will need help.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hi @thockin . Typically, it is helpful to keep changes to a single language. Thanks!
/cc @kubernetes/sig-docs-id-reviews 
/cc @kubernetes/sig-docs-ja-reviews 
/cc @kubernetes/sig-docs-ko-reviews 
/cc @kubernetes/sig-docs-zh-reviews

**Comment by thockin** [comment]
I can break this up if you want, but the changes are all trivial, so it was easy to do them all at once.  There are (should be) no native-language changes, just some k8s label names.

**Comment by kbhawkey** [comment]
> 
> 
> I can break this up if you want, but the changes are all trivial, so it was easy to do them all at once. There are (should be) no native-language changes, just some k8s label names.

I think it is okay to leave the changes as long as the localization teams review.

**Comment by seokho-son** [comment]
As a kubernetes/sig-docs-ko-reviews, 
It is ok for us to accept trivial changes to Ko contents in this PR since the changes have been applied in English documents already. (but I am not sure for other languages)
so, for Ko contents,
/lgtm

**Review by irvifa — COMMENTED** [review]
LGTM for id

**Comment by bells17** [comment]
LGTM for ja contents too

**Review by tanjunchen — COMMENTED** [review]
/LGTM 
for zh

**Comment by kbhawkey** [comment]
@thockin , After a rebase, these changes look ready to move forward.
Also, would you confirm that the changes belong with version 1.19 instead of the current milestone (v1.20)?
Thanks!

**Comment by thockin** [comment]
Rebased.  Version doesn't matter - these label names have been available since 1.17, so whatever is easiest :)

**Comment by bells17** [comment]
Thank you!
/lgtm

**Comment by kbhawkey** [comment]
Thanks @thockin .
/approve

**Pull request merged**
