### PR TITLE
Update the version of echoserver

### LINKED ISSUE #8762: Issue with k8s.io/docs/getting-started-guides/minikube/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Command from instructions fails:

```
$ kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.4 --port=8080
error: no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Proposed Solution:**

Not specifying a version works as expected.

**Page to Update:**

https://kubernetes.io/docs/getting-started-guides/minikube/#quickstart

**Kubernetes Version:**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-04-10T12:46:31Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by xlgao-zju**
close #8762

### CODE REVIEW

**Comment by xlgao-zju** [comment]
Still need approve...

**Comment by xlgao-zju** [comment]
Ping @mistyhacks PTAL

**Comment by xlgao-zju** [comment]
@tengqm This PR need your approve too :)

**Comment by michaelahlers** [comment]
Hold off on merging this; I might've goofed on the proposed solution (the command succeeds without the version, but [`echoserver` in GCR](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/echoserver) doesn't specify a `latest` label and I _think_ this causes the pod to get stuck in `ContainerCreating`).

**Comment by michaelahlers** [comment]
Yes, I goofed. Leaving off the version yields:

```
  Warning  Failed                 0s         kubelet, minikube  Failed to pull image "k8s.gcr.io/echoserver": rpc error: code = Unknown desc = Error response from daemon: manifest for k8s.gcr.io/echoserver:latest not found
```

The correct command ought to be:

```
$ kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
```

Tag for working version obtained by visiting [`echoserver`'s image page at Google Cloud Repository](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/echoserver).

Sorry!

**Comment by mistyhacks** [comment]
/hold

Please close this PR if it is not necessary.

Does this mean that #8762 is not a bug?

**Comment by michaelahlers** [comment]
@mistyhacks, I think it is—the `1.4` tag failed initially while newer versions succeeded.

**Comment by xlgao-zju** [comment]
So, as @michaelahlers said we should use the newer version instead of removing the version.

**Comment by mistyhacks** [comment]
So the change that includes removing the version is correct, or the version should be updated to some newer one? Sorry, but I am still confused.

**Comment by xlgao-zju** [comment]
@mistyhacks I think what @michaelahlers meant is using `echoserver:1.10` instead of `echoserver:1.4`.

Am I right? @michaelahlers

**Comment by michaelahlers** [comment]
@xlgao-zju, exactly!

**Pull request merged**
