### PR TITLE
Remove announcement shortcode

### PR DESCRIPTION
**Pull request by sftim**
The only localization continuing to use that shortcode was French.

/language fr
/kind cleanup

### CODE REVIEW

**Comment by remyleone** [comment]
@sftim it was removed in another PR. I think you can safely delete announcement.html. :)

**Comment by sftim** [comment]
Similar to PR #22564

**Comment by kbhawkey** [comment]
Preview pages:
https://deploy-preview-22131--kubernetes-io-master-staging.netlify.app/docs/concepts/overview/
https://deploy-preview-22131--kubernetes-io-master-staging.netlify.app/fr/docs/concepts/overview/
https://v1-17.docs.kubernetes.io/docs/concepts/overview/components/
https://kubernetes.io/blog/2020/07/27/music-and-math-the-kubernetes-1.17-release-interview/
https://kubernetes.io/community/

**Pull request merged**
