### PR TITLE
Merge main into dev-1.26 to keep in sync

### PR DESCRIPTION
**Pull request by Rishit-dagli**
Merge main branch into dev-1.26 to keep in sync, part of the Docs activities in the release process, see [here](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#maintain-the-current-and-upcoming-dev-branch).

/cc @krol3 @cathchu @mickeyboxell @katmutua

### CODE REVIEW

**Comment by sftim** [comment]
It looks like this needs an update.

**Comment by sftim** [comment]
I made PR https://github.com/kubernetes/website/pull/38242 in case that helps. It's similar to #38197 but includes changes to the Service concept.

**Comment by sftim** [comment]
If / when this lands, PR https://github.com/kubernetes/website/pull/38284 will need a rebase.

**Comment by krol3** [comment]
@Rishit-dagli  Can you close this PR? This PR was merged with the changes that we need https://github.com/kubernetes/website/pull/38242

**Pull request closed without merging**
