### PR TITLE
Localize “email address” placeholder on home page

### PR DESCRIPTION
**Pull request by npu21**
https://github.com/kubernetes/website/issues/19364

### CODE REVIEW

**Comment by sftim** [comment]
:GTM

**Comment by sftim** [comment]
@kubernetes/sig-docs-es-reviews how does this look?

**Comment by sftim** [comment]
@kubernetes/sig-docs-es-reviews please take a look at this

**Comment by raelga** [comment]
Sorry @sftim !

/lgtm
/approve

**Comment by onlydole** [comment]
Thank you, @npu21, @sftim, and @raelga!
/approve

**Pull request merged**
