### PR TITLE
Fix invalid link.

### PR DESCRIPTION
**Pull request by chenhonggc**
Maybe `/docs/task /#handling-initialization` has expired.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6454)

### CODE REVIEW

**Comment by chenhonggc** [comment]
@tengqm  `/docs/user-guide/production-pods/`  Moved Permanently   `/docs/tasks/`.
I am reading `docs/tasks` and have not found other errors.

**Comment by tengqm** [comment]
@chenhonggc  I was asking for a help on cleaning all other occurrences of the dead link. You can do a grep from the root directory, not just the docs/tasks directory.

**Comment by chenhonggc** [comment]
@tengqm I use `find ./docs -name "*.md" | xargs -n1 cat  | grep -E "\[.*\]\(.*\)"`, But there are too many links, I don‘t have a good way to verify what is invalid, do you have any good suggestions? thanks.

**Comment by tengqm** [comment]
sorry, I didn't mean to make this a huge pr. Just search for 'production-pods' and 'handling-initialization' would be fine.

**Comment by chenhonggc** [comment]
@tengqm  Sorry, there is nothing about `production-pods` and `handling-initialization` when I use `grep -rniE "production-pods|handling-initialization" docs/`.

**Comment by tengqm** [comment]
@chenhonggc Thanks.

**Comment by chenhonggc** [comment]
@tengqm For Linux, for docker, for kubernetes.

**Pull request merged**
