### PR TITLE
setup page replaces picking the right solutions

### LINKED ISSUE #9710: Refactor Picking the Right Solution
- [ ] Feature Request
- [x] Bug Report

**Problem:**
[Picking the Right Solution](https://kubernetes.io/docs/setup/pick-right-solution/) is a highly trafficked landing page and critical step in the onboarding experience of users new to Kubernetes and its documentation. It outlines various types of Kubernetes offerings, including local machine, hosted, turnkey, on-premises, and custom solutions. Its purpose is to show the reader a survey of the available solutions -- different ways to setup or procure Kubernetes clusters, to help them decide on one that is appropriate for their circumstances.

Currently, the page is a wall of links. It does not give much explanation for each of the main solution types, nor does it give any rationale for why you would choose one over the other. For example, why would someone choose a hosted solution over a turnkey cloud solution? Consequently, it does not actually help users decide what is best for their needs, which is reflected in the analytics as a high number of page views but low average time on page.

**Proposed Solution:**

The page should be refactored to make it easier for users to decide which solution is appropriate for their situation.

**Page to Update:**
https://kubernetes.io/docs/setup/pick-right-solution/

### PR DESCRIPTION
**Pull request by Rajakavitha1**
Fixes #9710

All the information in https://kubernetes.io/docs/setup/pick-right-solution/ is now available in https://kubernetes.io/docs/setup/.

The content in https://kubernetes.io/docs/setup/ also ensures that:
a. kubernetes is vendor neutral.
b. references to private git repos not maintained anymore are not listed
c. most recent update to picking the right solution page https://github.com/kubernetes/website/pull/14434 has been updated in https://kubernetes.io/docs/setup/
d. vendor specific support level is not listed in the table

Launch card in https://kubernetes.io/docs/home/ has been updated in the latest version of the setup page.
 The card attribute changes reflect in https://deploy-preview-14442--kubernetes-io-master-staging.netlify.com/docs/home/ under "Set up a cluster" card that contained the links to headings in Picking the right solutions page.

All references/links to Table of Solutions in Picking the right solution page has been removed.

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Please review: 
https://deploy-preview-14442--kubernetes-io-master-staging.netlify.com/docs/setup/
https://deploy-preview-14442--kubernetes-io-master-staging.netlify.com/docs/home/
https://deploy-preview-14442--kubernetes-io-master-staging.netlify.com/docs/setup/turnkey/aws/
https://deploy-preview-14442--kubernetes-io-master-staging.netlify.com/docs/setup/turnkey/gce/
https://deploy-preview-14442--kubernetes-io-master-staging.netlify.com/docs/setup/on-premises-vm/cloudstack/
https://deploy-preview-14442--kubernetes-io-master-staging.netlify.com/docs/setup/on-premises-vm/ovirt/
https://deploy-preview-14442--kubernetes-io-master-staging.netlify.com/docs/getting-started-guides/fedora/flannel_multi_node_cluster/

**Comment by sethmccombs** [comment]
@zacharysarah the "picking the right solution" page is referenced in a bunch of places. Case and point this page - https://kubernetes.io/docs/concepts/cluster-administration/cluster-administration-overview//#planning-a-cluster it seems the that page was removed and left a bunch of hanging references.

**Pull request merged**
