### PR TITLE
Fix broken links in container pattern blog

### LINKED ISSUE #13028: Issue with k8s.io/docs/concepts/workloads/pods/pod/
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
There is a kubernetes.io blog post linked directly from the kubernetes docs in multiple instances. The post is linking to expired/missing architectural diagram images. The post talks about Deployment best practices, which is relevant.

**Proposed Solution:**
Please either incorporate the best practices into the document or update the post links to reflect the architectural diagrams.

**Page to Update:**
Post:
https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/

Sample documentation page referencing blog post(there is more):
I https://kubernetes.io/docs/concepts/workloads/pods/pod/

Sample image file link from original blog post:
https://4.bp.blogspot.com/-yEmqGZ86mNQ/WRnPYG1m3jI/AAAAAAAABJo/94DlN54LA-oTsORjEBHfHS_UQTIbNPvcgCEw/s1600/Example%2B%25232-%2BAmbassador%2Bcontainers.png

### PR DESCRIPTION
**Pull request by christophercarney**
fixes #13028

Replaces broken links in ["The Distributed System ToolKit: Patterns for Composite Containers" ](https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/) with static images.

Images should be the exact images from the previous blog post. I took the images from Brendan Burns and David Oppenheimer's paper on container distributed systems: https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45406.pdf

### CODE REVIEW

**Comment by sftim** [comment]
Nice!

**Comment by christophercarney** [comment]
@onlydole @cody-clark Mind taking a look?

**Comment by zparnold** [comment]
@kbarnard10 when you get a sec can you approve this?

**Comment by onlydole** [comment]
So sorry I missed this, @christophercarney!

**Comment by christophercarney** [comment]
@onlydole No problem!

**Pull request merged**
