### PR TITLE
[zh-lang] Replace shortcode code with codenew

### PR DESCRIPTION
**Pull request by DanyC97**
Update the shortcode from `code` to `codenew` to align with rest of the docs

### CODE REVIEW

**Comment by DanyC97** [comment]
@tengqm fyi

**Comment by tengqm** [comment]
@DanyC97 The `codenew` is used to reference sample yaml files from the `examples` directory. Be careful about two things: 1. the referenced file must sit in the right location (refer to how en site is organized). 2. the relative path may need to be explicitly set in the mardown file when referencing an example.

**Comment by chenrui333** [comment]
@DanyC97 I am curious, what is the issue trying to address here?

**Comment by DanyC97** [comment]
@chenrui333 the issue is to replace [`code` shortcode](https://github.com/kubernetes/website/blob/master/layouts/shortcodes/code.html) with the newer [`codenew` shortcode](https://github.com/kubernetes/website/blob/master/layouts/shortcodes/codenew.html) so we can then remove / delete the former one.

My understanding is that the great work done by @tengqm on `codenew` shortcode was to replace the old one hence my action.

**Comment by chenrui333** [comment]
I see, thanks for specifying the details!

**Comment by markthink** [comment]
@DanyC97  建议 base 到 1.14 版本

**Pull request closed without merging**
