### PR TITLE
Add links between Securing a Cluster and Security Checklist for alignment

### LINKED ISSUE #37738: Align securing a cluster task with security checklist
**This is a Feature Request**

We have two pages with similar aims:
- https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/
- https://kubernetes.io/docs/concepts/security/security-checklist/

We should ensure that the advice in the two documents is aligned, and also make sure that the two documents link to each other.

**Why is this needed**
It's a bad idea to document multiple ways to make sure that your cluster is secure, unless those are well aligned.

**Comments**
/sig security
/sig docs
/language en

### PR DESCRIPTION
**Pull request by mrgiles**
Link documents [Securing a Cluster](https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/) (task) with [Security Checklist](https://kubernetes.io/docs/concepts/security/security-checklist/) (concept) for alignment. Fixes #37738

### CODE REVIEW

**Comment by mrgiles** [comment]
FYI @sftim

**Comment by Ritikaa96** [comment]
Hi @mrgiles Please note that the issue was mainly to align both pages advice for secure cluster. Refer to :

> We should ensure that the advice in the two documents is aligned, and also make sure that the two documents link to each other.

> **Why is this needed**
It's a bad idea to document multiple ways to make sure that your cluster is secure, unless those are well aligned.
 
I have not matched the pages but just wanted to add this as a reminder. Thanks for the contribution.

**Comment by Ritikaa96** [comment]
Also please check the reason for the checks being unsuccessful

**Comment by mrgiles** [comment]
Thanks @Ritikaa96, I just saw this note: https://github.com/kubernetes/website/issues/25119#issuecomment-1429280412. 
Where can I find this _Hardening Guide_ @raesene?
What do you think @sftim, is it worth keeping the **Securing a Cluster** doc?

**Comment by sftim** [comment]
> What do you think @sftim, is it worth keeping the **Securing a Cluster** doc?

It is, at least for now.

**Comment by raesene** [comment]
@mrgiles the hardening guide is still in development, definitely not one to link to at the moment :)

**Comment by mrgiles** [comment]
Hi @tengqm, thank you for your review.  If you think that the changes satisfy the requirements in #37738, could you also add an **lgtm** label for the PR to proceed? Thanks!

**Comment by mrgiles** [comment]
@tengqm please disregard the adding the **lgtm** label comment. Thanks!

**Pull request merged**
