### PR TITLE
A utility to view kubernets pods and describe them

### PR DESCRIPTION
**Pull request by anasokan**
A utility to view kubernets pods and describe them

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/28310#issuecomment-855859763

**Comment by anasokan** [comment]
CLA completed

**Comment by anasokan** [comment]
> Pls sign the CLA in order for the PR to be reviewed.
> more info
> https://github.com/kubernetes/website/pull/28310#issuecomment-855859763

CLA signed now

**Review by sftim — CHANGES_REQUESTED** [review]
@anasokan thanks for signing the CLA

This article is a bit too brief and specific. If you wanted to publish a survey of the different tools people can use to visualize their cluster, and mention https://github.com/anasokan/kubevisualizer in that survey, we could consider than for publication.

**Review by sftim — COMMENTED** [review]
@anasokan, we can't accept this article. It's promoting a single product that's outside the Kubernetes project, and that's not what the Kubernetes blog is for.

/hold


There's no problem submitting this article for publication elsewhere, though.

**Review by sftim — COMMENTED** [review]
/close

**Pull request closed without merging**
