### PR TITLE
[zh-cn] Add anchor modify-the-kubelet-configmap

### PR DESCRIPTION
**Pull request by javadoors**
Add anchor:#modify-the-kubelet-configmap

### CODE REVIEW

**Comment by Sea-n** [comment]
Good idea!
But I think it's better to make a PR to English file first, what do you think?

**Comment by javadoors** [comment]
> Good idea! But I think it's better to make a PR to English file first, what do you think?

The en PR:#34466

**Comment by tengqm** [comment]
Mind squash your commits?

**Comment by javadoors** [comment]
> Mind squash your commits?

ok

**Comment by tengqm** [comment]
Thanks.
/lgtm
/approve

**Pull request merged**
