### PR TITLE
Updated the numbering of instructions

### PR DESCRIPTION
**Pull request by eightlimbed**
All of the instructions were numbered like this:
-1. do something
-1. then do this
-1. finally, do this.

I just changed them accordingly to be 1-2-3. There was also a case typo in the `LOG_LEVEL=info` which should be `LOG_LEVEL=INFO` based on the data in the yaml file.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
> Help editing and submitting pull requests:  https://deploy-preview-9510--kubernetes-io-master-staging.netlify.com/docs/contribute/start/#submit-a-pull-request.
> Help choosing which branch to use, see
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by eightlimbed** [comment]
Submitted the signed CLA.

**Comment by Bradamant3** [comment]
@eightlimbed this is a nice catch, but unfortunately the solution is a little more complex. The markdown convention for numbered lists is to start each item with the same arabic numeral, usually `1`. Hugo's markdown processor, Blackfriday, does not however continuously number lists **that contain nested items** -- in this case, the command/code snippets. See https://github.com/kubernetes/website/blob/master/content/en/docs/test.mdl117 and following for guidelines on how to format.

This is an ugly bug with Blackfriday; so sorry you ran into it with your first contribution! Feel free to reply with any questions.

/assign

**Pull request merged**
