### PR TITLE
zh_trans: add automated-tasks-with-cron-jobs.md

### PR DESCRIPTION
**Pull request by AdamDang**
zh_trans: add job/automated-tasks-with-cron-jobs.md

### CODE REVIEW

**Comment by AdamDang** [comment]
@markthink @tengqm 
所有建议已经修改完毕。

**Comment by tengqm** [comment]
@AdamDang Thanks for the fix. It would be great if you can help polish the page by adding spaces between Chinese texts and English texts as suggested before by many people.

After all, this PR is blocked by gate issues at the moment.

**Comment by AdamDang** [comment]
@tengqm Thanks a lot for your patient.
It's fix now.

**Comment by tengqm** [comment]
@AdamDang Please make a copy of `content/en/examples/application/job/cronjob.yaml` under `content/zh/examples/application/job/cronjob.yaml` and add it to the PR. The gate will be happy.

**Comment by AdamDang** [comment]
It's OK now

**Comment by tengqm** [comment]
cronjob yaml 的路径不对。

**Comment by AdamDang** [comment]
改好了

**Pull request merged**
