### PR TITLE
Update Interactive Terminal button

### PR DESCRIPTION
**Pull request by BenHall**
Based on the feedback in #15212

When the terminal now starts, it will use `start.sh`. This is a wrapper script we created that will deploy `minikube` with the new `wait=false` flag so that it starts faster for users. The abstraction will make it easier to keep up-to-date with future changes and optimisations that can be done.

Secondly, we added a "Preview Port 30000" button to the terminal making it easier for people to access the dashboard.

### CODE REVIEW

**Comment by sftim** [comment]
Seems OK. I'm not really familiar with Katacoda; however, I saw that the deploy preview works OK.
/lgtm

**Comment by kbhawkey** [comment]
hello @BenHall. 
Which page displays the new button, `"Preview Port 30000" button to the terminal`?
Page preview (?):
https://deploy-preview-15689--kubernetes-io-master-staging.netlify.com/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by BenHall** [comment]
@kbhawkey Sorry, I should have included the link. This is related to the Hello Minikube tutorial - https://deploy-preview-15689--kubernetes-io-master-staging.netlify.com/docs/tutorials/hello-minikube/

**Comment by kbhawkey** [comment]
Thanks @BenHall . I see the new `Preview Port 30000` tab/button on the terminal now. Seems fine! When clicked, the dashboard is displayed.
/lgtm

**Pull request merged**
