### PR TITLE
[hi] Localize content/hi/docs/reference/glossary/contributor.md

### PR DESCRIPTION
**Pull request by amolmote**
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #35600

### CODE REVIEW

**Review by Babapool — COMMENTED** [review]
Hope you find these suggestions useful. Thanks

**Comment by amolmote** [comment]
Yeah great @Babapool. Will accept the suggestions thank you

**Comment by Babapool** [comment]
The changes LGTM ( I am not a go localization official reviewer/approver). Also can you squash and merge your commits into one to make the PR ready to merge. Thanks

**Comment by amolmote** [comment]
Sure @Babapool

**Comment by amolmote** [comment]
> The changes LGTM ( I am not a go localization official reviewer/approver). Also can you squash and merge your commits into one to make the PR ready to merge. Thanks

having some conflict on branch, need some time to resolve it correctly

**Pull request closed without merging**
