### PR TITLE
remove indent on video block

### PR DESCRIPTION
**Pull request by Arhell**
issue https://github.com/kubernetes/website/issues/23364
remove br for fix indent
en [PR](https://github.com/kubernetes/website/pull/22595)
/language de
/area web-development

### CODE REVIEW

**Comment by Arhell** [comment]
before
https://kubernetes.io/de/#video
after
https://deploy-preview-23395--kubernetes-io-master-staging.netlify.app/de/#video

/assign @rlenferink

**Comment by sftim** [comment]
LGTM

**Comment by rlenferink** [comment]
/lgtm
/approve

thanks for fixing

**Pull request merged**
