### PR TITLE
Remove trailing spaces (#16742)

### PR DESCRIPTION
**Pull request by furukawa3**
This PR removes trailing spaces.  I found all trailing spaces for following command:

```
sed -i 's/[ ]*$//' $(find content/ -type f -not -name "*.png" -not -name "*.jpg" -not -name "*.svg" -not -name "*.gif")
```

### CODE REVIEW

**Comment by sftim** [comment]
@furukawa3 thank you for the PR.
Would you be willing to withdraw this pull request and replace it with several PRs, one per localization?
See [working with localized content](https://kubernetes.io/docs/contribute/intermediate/#working-with-localized-content). Essentially, PRs that cover lots of locales need lots of approval.

**Comment by zacharysarah** [comment]
@furukawa3 Thanks for this update. I'm closing this PR but I agree with @sftim and would love to see these changes go forward in individual PRs per language.

/close

**Comment by furukawa3** [comment]
I see.  Thanks for your suggestion.  I'll split this commit into each language!!

**Pull request closed without merging**
