### PR TITLE
Resync kubelet configuration

### PR DESCRIPTION
**Pull request by tengqm**
This PR updates the kubelet reference which is outdated. There have been some changes in 1.20, but we cannot auto-generate or auto-sync these changes.

### CODE REVIEW

**Comment by tengqm** [comment]
preview: https://deploy-preview-25811--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kubelet/

**Comment by kbhawkey** [comment]
Thanks @tengqm .
/lgtm

**Pull request merged**
