### PR TITLE
Translate docs/concepts/storage/storage-limits.md in Korean

### PR DESCRIPTION
**Pull request by reung37**
문서를 번역했습니다. 리뷰 부탁드리겠습니다.
from #17346
/language ko

### CODE REVIEW

**Comment by gochist** [comment]
@reung37 Thank you!
1. When translating the file in `content/en` into Korean, please place the file in `content/ko` directory.
2. Please match the branch where you added the commit and the base branch to `dev-1.16-ko.4`. FYI, `dev-1.16-ko.4` will be freeze at Nov 04 KST. 

If you have any question, feel free to contact me(june.yi) on the K8s slack channel #kubernetes-docs-ko.

/hold

**Comment by jimangel** [comment]
/unassign
I'll leave final review up to @gochist. Thanks! Let me know if I can help!

**Pull request closed without merging**
