### PR TITLE
Updating Bengali Localization owners

### PR DESCRIPTION
**Pull request by mitul3737**
This PR updates the k/website OWNERS_ALIASES file with the Bengali localization team owners and reviewers

These PR needs to be merged to make the `dev-1.23-bn.1` branch active

Tracking issue: #31677

### CODE REVIEW

**Comment by sftim** [comment]
I see that 76ab2e85786759784141012462e6339876891c98 landed. It's probably OK to skip this until the Bengali localization is closer to launch.

**Comment by mitul3737** [comment]
Yes, sure @sftim

**Comment by Sea-n** [comment]
Hey @mitul3737,

It's been inactive for 3 months. Maybe we could temporarily close this PR or put a `/hold` on it, how do you think?

**Comment by mitul3737** [comment]
@Sea-n yes, I think we can keep it on hold or close it untill we are about to launch as @sftim said

**Comment by sftim** [comment]
I'm happy to keep this open so long as progress is happening on the localization into Bengali.

**Comment by NitishKumar06** [comment]
@mitul3737 You'll need to rebase the PR.

**Pull request closed without merging**
