### PR TITLE
Add Scaleway Kapsule to French providers page

### PR DESCRIPTION
**Pull request by kedare**
This PR adds the Scaleway Kapsule certified Kubernetes provider to the list of the providers in the French part of the documentation

### CODE REVIEW

**Comment by kedare** [comment]
CLA signed

**Review by sftim — COMMENTED** [review]
Localizations should only translate existing content; all new changes should go into the upstream (English) localization.
/hold

**Comment by kedare** [comment]
As far as I know this same page doesn't exist in the English version ?

**Comment by jimangel** [comment]
> As far as I know this same page doesn't exist in the English version ?

Correct it was removed and the French localization team has yet to pick up the latest changes. The removal was due to the [third party content](https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content) guide. At this time, I think it's worth closing if the change can't begin in `en/docs/`.

/close

**Pull request closed without merging**
