### PR TITLE
Merged master into dev 1.18

### PR DESCRIPTION
**Pull request by VineethReddy02**
Merged master into dev 1.18 for sync up. As a part of docs release teamwork.

### CODE REVIEW

**Comment by sftim** [comment]
@VineethReddy02 this PR looks broadly OK to me. It hasn't previewed though - I suspect that's a Netlify issue. You could `git commit --amend`, delete the last blank line of the commit message to trigger a no-op change, and then force-push. That might nudge Netlify.

**Comment by kbhawkey** [comment]
Hello @VineethReddy02, @sftim . Just looked at the log for build errors. I thought the federation task files were deleted? Perhaps there are related files that were missed.

`
3:02:03 AM: Building sites …
3:02:09 AM: ERROR 2020/03/21 07:02:09 [en] no Resource or Page matching "federated-task-tutorial-prereqs.md*".
3:02:09 AM: Total in 6048 ms
3:02:09 AM: Error: Error building site: "/opt/build/repo/content/en/docs/tasks/federation/set-up-placement-policies-federation.md:26:1": failed to render shortcode "capture": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/codenew.html:14:16": execute of template failed: template: shortcodes/codenew.html:14:16: executing "shortcodes/codenew.html" at <readFile $filename>: error calling readFile: file "content/en/examples/federation/scheduling-policy-admission.yaml" does not exist
3:02:09 AM: Makefile:22: recipe for target 'deploy-preview' failed
3:02:09 AM: make: *** [deploy-preview] Error 255
`

**Comment by VineethReddy02** [comment]
@sftim @kbhawkey How can we fix this? 
As 1.18 release is on 24th March. This issue seems to be a release blocker. Usually, sync ups happen very smoothly. This is strange to me.

**Comment by jimangel** [comment]
/hold

Waiting for resolution of another issue and this will most likely need to be re-opened or force updated once resolved.

**Pull request closed without merging**
