### PR TITLE
Translation for i18n/ko.toml

### PR DESCRIPTION
**Pull request by seokho-son**
This PR updates i18n/ko.toml 
to translate i18n/en.toml according to the recent update from #13832.

### CODE REVIEW

**Comment by seokho-son** [comment]
Since this PR includes Korean contents, I expect review comments from Korean localization team.
@gochist. Could you help?

**Comment by seokho-son** [comment]
The preview page for main changes: 
https://deploy-preview-13951--kubernetes-io-master-staging.netlify.com/ko/docs/reference/glossary/

**Comment by gochist** [comment]
@seokho-son Thank you! As a native Korean speaker, it looks good to me.
/lgtm

**Comment by seokho-son** [comment]
@zacharysarah could you take a look on this PR? It is about i18n/ko.toml translation. Thank you.

**Comment by zacharysarah** [comment]
There needs to be a way for localization teams to approve changes in this directory. The easiest way may be to add an `OWNERS` with approval permissions for each `sig-docs-**-owners` team.

**Comment by seokho-son** [comment]
> There needs to be a way for localization teams to approve changes in this directory. The easiest way may be to add an `OWNERS` with approval permissions for each `sig-docs-**-owners` team.

@zacharysarah, I agree with you. It would improve the efficiency for i18n work. (cc: @gochist)

**Pull request merged**
