### PR TITLE
ZH-trans: merge release-1.16-temporary to release-1.17

### PR DESCRIPTION
**Pull request by xichengliudui**
/cc @chenrui333 @markthink @zhangxiaoyu-zidif @idealhack @SataQiu

### CODE REVIEW

**Comment by chenrui333** [comment]
Should be good by just adding `content/zh/examples/controllers/nginx-deployment.yaml` 
```
9:45:21 AM: Error: Error building site: "/opt/build/repo/content/zh/docs/concepts/workloads/controllers/deployment.md:22:1": failed to render shortcode "capture": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/codenew.html:14:16": execute of template failed: template: shortcodes/codenew.html:14:16: executing "shortcodes/codenew.html" at <readFile $filename>: error calling readFile: file "content/zh/examples/controllers/nginx-deployment.yaml" does not exist
9:45:21 AM: Function Dir: /opt/build/repo/functions
9:45:21 AM: Skipping functions preparation step: /opt/build/repo/functions not found
```

**Comment by sftim** [comment]
Should this change actually target the _master_ branch? That's what most localizations seem to merge into when finishing a milestone.

**Comment by xichengliudui** [comment]
> Should this change actually target the _master_ branch? That's what most localizations seem to merge into when finishing a milestone.

*master* #18217
*release-1.16* #18216

**Pull request merged**
