### PR TITLE
Update en/docs

### PR DESCRIPTION
**Pull request by HwangTaehyun**
It is just giving an example string, but its readability could be improved if fixed.

### CODE REVIEW

**Comment by stmcginnis** [comment]
Hi @HwangTaehyun, can you sign the CLA? That will be required to accept any changes.

Are there any other changes needed in this file? I don't think this change actually needs to be made since it is just giving an example string. But if you wanted to change it along with some other needed fixes, I think that would be fine.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by HwangTaehyun** [comment]
@AmarNathChary @Arhell Thank you, I signed it!
@stmcginnis Yes, you're right. But it's a bit uncomfortable to read, so I'd like to fix it!
There aren't any other needed fixes right now

**Comment by HwangTaehyun** [comment]
@stmcginnis Hi! I've updated all `abcxzy` to `abcxyz`!

**Comment by HwangTaehyun** [comment]
@stmcginnis I've reflected!

**Comment by HwangTaehyun** [comment]
@celestehorgan @divya-mohan0209 @Arhell Could you review this PR?

**Comment by reylejano** [comment]
I don't see how this improves the docs
This PR proposes to change the example `mysql-abcxzy` to `mysql-abcxyz` for better readability as stated in the description
To me, the readability is the same

**Comment by electrocucaracha** [comment]
> I don't see how this improves the docs This PR proposes to change the example `mysql-abcxzy` to `mysql-abcxyz` for better readability as stated in the description To me, the readability is the same
> 
> I can be convinced otherwise

Well, readability is arguably subjective, but this particular PR seems to be a first time contribution, so I expect to see more challenging contributions in the future that fixes and/or improves the documentation.

**Comment by HwangTaehyun** [comment]
@celestehorgan @divya-mohan0209 @Arhell Hi!, Could you review this PR? Thanks!

**Review by sftim — COMMENTED** [review]
abcxyz is a metasyntactic value and may be more recognizable than abcxzy.

/approve

**Pull request merged**
