### PR TITLE
svg color update

### PR DESCRIPTION
**Pull request by Arhell**
issue #22393

### CODE REVIEW

**Comment by celestehorgan** [comment]
Preview link (example): https://deploy-preview-22396--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/logging/#basic-logging-in-kubernetes

**Comment by Arhell** [comment]
review page https://deploy-preview-22396--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/logging/#basic-logging-in-kubernetes

I made the color like all our picture links
Example https://kubernetes.io/docs/home/#understand-the-basics

**Comment by sftim** [comment]
/lgtm
/approve

Thanks @Arhell & @celestehorgan

**Pull request merged**
