### PR TITLE
DynamicKubeletConfig has not been supported in kubeadm for a while.

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
/sig node

/kind cleanup

See the comment: https://github.com/kubernetes/website/pull/28474#issuecomment-865184194

### CODE REVIEW

**Comment by chenxuc** [comment]
Thanks for the effort.
/lgtm

**Comment by tengqm** [comment]
/approve
/hold
Please feel free to cancel the hold once it is confirmed that the stated feature(s) are not effective for 1.21 (master/main).

**Review by neolit123 — COMMENTED** [review]
thanks

/lgtm
/sig cluster-lifecycle

**Pull request merged**
