### PR TITLE
Fix links in  API reference docs

### PR DESCRIPTION
**Pull request by tengqm**
This PR fixes the links generated in the API reference docs.

Closes: #9649, #9748

### CODE REVIEW

**Comment by tengqm** [comment]
@xiangpengzhao refer to: kubernetes-incubator/reference-docs project. The logic fixed is in PR https://github.com/kubernetes-incubator/reference-docs/pull/55 

If you want to generate the api references locally, clone the repo, review the first few lines of the Makefile and then do `make api`. The generated files are located under `gen-apidocs/generators/build/`.

**Comment by xiangpengzhao** [comment]
@tengqm Thanks! Awesome!

**Comment by bradtopol** [comment]
Assigning @zacharysarah  I believe this is all correct but its such a huge change I think @zacharysarah should take a look.

**Comment by zacharysarah** [comment]
@tengqm Thanks for this! ✨ 

/lgtm
/approve

**Pull request merged**
