### PR TITLE
Update topology-aware-hints.md

### PR DESCRIPTION
**Pull request by jpreese**
Noticed a couple small typos while reading through this document.

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
@jpreese Thank you for your contribution! This qualifies as a trivial edit & given the efforts expended for reviewing, we'd appreciate if you scanned the entire document for any such issues & made amendments per the trivial edit policy.

**Comment by jpreese** [comment]
@divya-mohan0209 thanks for the reminder. I ran this page through Grammarly and gave it a read through myself and did find another small issue. I feel at this point it should be technically correct, let me know otherwise!

**Comment by robscott** [comment]
Thanks!

/lgtm

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Pull request merged**
