### PR TITLE
[ja] Remove Service Broker reference

### PR DESCRIPTION
**Pull request by Rishit-dagli**
This PR is related to failing tests from #34387 , it seems that the ja docs depend on the glossary entry from the `en` docs

Please see https://github.com/kubernetes/website/pull/34387#issuecomment-1161388134

Note: we still need to make the changes to this file similar to:  https://github.com/kubernetes/website/pull/34387/files#diff-c3ff1d9d7e9d80de144e2e81435a237bcf5ae030d68782cc602a9c471615038aL1-L18

/cc jihoon-seo

### CODE REVIEW

**Comment by tengqm** [comment]
Looks like this one is blocking #34387, IIUC.

**Comment by Rishit-dagli** [comment]
> I think that it would be great if some Japanese reviewer check and confirm whether the Japanese string is okay,
since the word "Service Broker" is just fork-lifted from the original Japanese sentence.

+1, I had also included this in the PR description. Right now this PR only fixes the build errors we run into if we merge #34387 however the other changes (like in the en PR) and verifying the sentence as a whole does require a ja volunteer

**Review by nasa9084 — COMMENTED** [review]
/assign

**Comment by Rishit-dagli** [comment]
@jihoon-seo I believe the hold should now be removed

**Comment by jihoon-seo** [comment]
@Rishit-dagli Okay let's move on!
/unhold

**Pull request merged**
