### PR TITLE
Update Federation API ref docs for 1.14

### PR DESCRIPTION
**Pull request by jimangel**
Previews:

- https://5c96a6a511c0630008cc1fc1--kubernetes-io-vnext-staging.netlify.com/docs/reference/federation/extensions/v1beta1/definitions.html
- https://5c96a6a511c0630008cc1fc1--kubernetes-io-vnext-staging.netlify.com/docs/reference/federation/extensions/v1beta1/operations.html
- https://5c96a6a511c0630008cc1fc1--kubernetes-io-vnext-staging.netlify.com/docs/reference/federation/v1/definitions.html
- https://5c96a6a511c0630008cc1fc1--kubernetes-io-vnext-staging.netlify.com/docs/reference/federation/v1/operations.html
- https://5c96a6a511c0630008cc1fc1--kubernetes-io-vnext-staging.netlify.com/docs/reference/federation/federation/v1beta1/definitions.html
- https://5c96a6a511c0630008cc1fc1--kubernetes-io-vnext-staging.netlify.com/docs/reference/federation/federation/v1beta1/operations.html

edit: It appears this needs some work.

### CODE REVIEW

**Comment by jimangel** [comment]
/hold

After further review, this is just adding back in the non-relative links that @chenrui333 removed recently.

I've reached out to @kubernetes/sig-multicluster on slack to see if we still need to publish the deprecated federation v1 spec... If we stop publishing v1, we should work with sig-multicluster to begin publishing v2.

cc/ @zacharysarah

**Comment by DanyC97** [comment]
@jimangel any particular reason why the non-relative links needs to be added back ?

**Comment by jimangel** [comment]
@DanyC97 this was due to following instructions at https://kubernetes.io/docs/contribute/generate-ref-docs/federation-api/ - however, since Federation v1 is deprecated, I'm wondering if this is even needed any more.

I'm closing for now so the milestone is clean.

/close

**Comment by chenopis** [comment]
Here are the pageview metrics for the federation reference docs for the past month:
image

**Comment by DanyC97** [comment]
wow, nice stats @chenopis (didn't even know we have something like that ... _live and learn i guess_ )

**Pull request closed without merging**
