### PR TITLE
Pod Security Standards doc updates

### PR DESCRIPTION
**Pull request by liggitt**
Addresses last two issues from https://github.com/kubernetes/website/issues/28721

- [x] removes optional non-root group check we declined to include in the in-tree PodSecurity implementation
- [x] switches restricted inline volumes check to require a positive match of an allowed volume type to protect against future volume types

/sig auth security
/cc @tallclair

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
LGTM

Thanks for updating this.

**Comment by sftim** [comment]
@kubernetes/sig-auth-pr-reviews is this OK from your perspective?

/approve
/hold

I would like tech review on these amendments.

**Review by tallclair — COMMENTED** [review]
/lgtm

Thanks.

**Pull request merged**
