### PR TITLE
[zh]Fix markdown link rendering failure caused by using full-width characters

### PR DESCRIPTION
**Pull request by mengjiao-liu**
Use of `（）` full-width characters causing link rendering to fail
image

### CODE REVIEW

**Review by Sea-n — COMMENTED** [review]
/lgtm

BTW, there are some other occurrence you might want to fix together.

```
content/zh-cn/docs/concepts/workloads/controllers/deployment.md
1602:（[`.spec.progressDeadlineSeconds`]（#progress-deadline-seconds））。

content/zh-cn/blog/_posts/2020-09-04-introducing-structured-logs.md
95:虽然在典型部署中，我们已按日志量更新了99％以上的日志条目，但仍有数千个日志需要更新。 选择一个您要改进的文件或目录，然后[迁移现有的日志调用以使用结构化日志]（https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md）。这是对Kubernetes做出第一笔贡献的好方法!

content/zh-cn/blog/_posts/2015-04-00-Borg-Predecessor-To-Kubernetes.md
117:通过揭示集群管理器 Borg 的一些内部工作原理，并将下一代集群管理器构建为一个开源项目（Kubernetes）和一个公开可用的托管服务（[Google Container Engine]（http://cloud.google.com/container-engine))
```

**Comment by mengjiao-liu** [comment]
I was just reading the related blog and found the link was wrong, no batch scan, thanks for the catch, I'll update the above file together. @Sea-n

**Review by Sea-n — COMMENTED** [review]
/lgtm

**Comment by tengqm** [comment]
Actually, it may be not a bad idea to keep a PR focused on a single "issue".
/approve

**Comment by tengqm** [comment]
The only exception, is that, we the reviewers have to make sure each page has been fully sync'ed before new changes are made.

**Pull request merged**
