### PR TITLE
Update Azure file feature gates for 1.20 beta

### PR DESCRIPTION
**Pull request by andyzhangx**
Docs for https://github.com/kubernetes/enhancements/issues/1885

/assign @msau42 @annajung

/sig storage
/hold 
pr pending merge kubernetes/kubernetes#96293

### CODE REVIEW

**Comment by irvifa** [comment]
Hi @andyzhangx Since I saw this issue https://github.com/kubernetes/kubernetes/issues/96508 do you folks will make an exception since the code freeze is on effect or will the enhancement pushed back to 1.21 ?

**Comment by andyzhangx** [comment]
> Hi @andyzhangx Since I saw this issue [kubernetes/kubernetes#96508](https://github.com/kubernetes/kubernetes/issues/96508) do you folks will make an exception since the code freeze is on effect or will the enhancement pushed back to 1.21 ?

it could be pushed back to 1.21, depends, will update if there is any new progress, thanks.

**Comment by annajung** [comment]
hi @andyzhangx this is no longer being tracked for 1.20 release.
Please see https://github.com/kubernetes/enhancements/issues/1885#issuecomment-726531813 for details 
Feel free to reopen when an exception has been filed/approved. 

/milestone clear
/close

**Pull request closed without merging**
