### PR TITLE
[hi] Update .gitignore to ignore .hugo_build.lock #35749

### LINKED ISSUE #35749: Update `.gitignore` to ignore `.hugo_build.lock`
**This is a Bug Report**

**Problem:**

For myself and other folks working on the `/hi` localization, generating a preview of the docs locally seems to add `.hugo_build.lock` file to our pull requests.

**Proposed Solution:**

Update `.gitignore` to reject `.hugo_build.lock`

**Page to Update:**
`.gitignore`

### PR DESCRIPTION
**Pull request by rolfedh**
Fixes #35749
[hi] Update .gitignore to ignore .hugo_build.lock #35749

### CODE REVIEW

**Comment by rolfedh** [comment]
/assign @anubha-v-ardhan 
Please review and assign fellow reviewers as needed. Thank you.

**Comment by sftim** [comment]
/hold

- **This change should not be part of the localization work for Hindi**
  - If we need this change, make it to _main_ and then merge _main_ into _dev-1.22-hi.1_
- I'm not sure that the issue this is associated with is right (it might be, though)

**Comment by rolfedh** [comment]
Not needed. 

https://github.com/kubernetes/website/blob/3692941165eecce44fb929643ebcba0047da5d9a/.gitignore#L32

**Pull request closed without merging**
