### PR TITLE
Fix constant value to variable

### PR DESCRIPTION
**Pull request by manabuishii**
Currently written in constant value , but variable is suitable like others

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @manabuishii,

Please sign the CLA agreement so that we can move on. 😊
https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/34727/#/?version=2

**Review by Arhell — COMMENTED** [review]
CLA info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Sea-n** [comment]
Hey @manabuishii,

Since you didn't sign CLA agreement, we cannot review this PR and move forward.

I'm closing this PR now, but feel free to `/reopen` once you are ready to sign CLA. ([tutorial here](https://git.k8s.io/community/CLA.md))
/close

**Pull request closed without merging**
