### PR TITLE
Updated Windows docs reviewers

### PR DESCRIPTION
**Pull request by perithompson**
Replaced the Windows website doc reviewers with the current Sig Windows Chair and Tech leads.  

/cc @marosset @jsturtevant @jayunit100 

btw I am happy to help out with these if you want an extra reviewer but I just copied the Sig windows Owners files. 

/sig windows

### CODE REVIEW

**Comment by jsturtevant** [comment]
/lgtm

I would be open to having you here. You've helped out a few times with the docs now.  thoughts  @marosset?

**Comment by marosset** [comment]
Please alphabetize :)

**Comment by marosset** [comment]
> I would be open to having you here. You've helped out a few times with the docs now.

Sure!

**Comment by perithompson** [comment]
@marosset alphabetized and added myself, happy to help spread the load 👍

**Pull request merged**
