### PR TITLE
remove community logos

### LINKED ISSUE #22094: Remove /static/images/community_logos
Umbrella issue: #22024

Remove the `/static/images/community_logos` directory and files.

They aren't used anywhere, so this is a fairly easy change.

### PR DESCRIPTION
**Pull request by morrme**
removed community logos.
Fixes #22094

### CODE REVIEW

**Comment by morrme** [comment]
@arhell it doesn't look like there's a way to match it up.  Since this is just a deletion, is it usable? Or should I close the PR?

**Comment by celestehorgan** [comment]
@morrme You can make your emails match up in one of two ways:

1) Login to the [CLA site](https://identity.linuxfoundation.org/projects/cncf) and change it to match what you use as your default email address on your GitHub account
2) Change your default email address on your GH account to the same one you used to sign the CLA.

**Comment by morrme** [comment]
@Arhell  @celestehorgan  Nothing seems to have worked. Thanks anyway!

**Comment by onlydole** [comment]
Howdy, @morrme - have you been able to figure out the CLA, or would you be able to use the email you committed with to sign the SLA to pass this check? We would enjoy having your contribution!

**Comment by morrme** [comment]
> Howdy, @morrme - have you been able to figure out the CLA, or would you be able to use the email you committed with to sign the SLA to pass this check? We would enjoy having your contribution!

Hi ! thanks for checking. I don't think there is a solution to this problem. I learned from another contributor's guide that it is because I chose the "private email" option on my account. Since this was a deletion (and not adding any code), if you're still able to use it somehow, go ahead, otherwise I'm guessing this PR can be closed. 

Thanks for the warm welcome and inclusion. :heart:

**Comment by jimangel** [comment]
>  I learned from another contributor's guide that it is because I chose the "private email" option on my account.

@morrme sorry this PR didn't work out based on permissions. You are welcome to recreate or open it using a CLA signed email if you wish. Given the current state, the automation used to merge PRs will not work.

Let me know if I can help with anything! Until then, I will close this PR. Thanks!

/close

**Pull request closed without merging**
