### PR TITLE
Etiquette for requesting PR reviews

### PR DESCRIPTION
**Pull request by sNathan13**
This PR is a follow up on the discussion that happened in sig-docs meeting earlier today. It is about the process and etiquette for requesting reviewers to review the changes.

### CODE REVIEW

**Comment by gochist** [comment]
@zacharysarah Cloud you please assign another owner for this?

**Comment by zacharysarah** [comment]
@gochist Sure thing. Feel free to assign whoever is the PR wrangler for the week!

/unassign @gochist
/assign @kbarnard10

**Pull request merged**
