### PR TITLE
Update APF documentation for GA

### PR DESCRIPTION
**Pull request by tkashem**
- Promote APF flowcontrol API to `v1` - https://github.com/kubernetes/kubernetes/pull/121089 
- set APF featuregate to stable - https://github.com/kubernetes/kubernetes/pull/121638
- KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness
- Enhancement issue: https://github.com/kubernetes/enhancements/issues/1040

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by tengqm** [comment]
Please do not add `api-ref-assets/api/swagger.json` or change the `toc.yaml` file in this PR.
Those files will be updated in a batch when 1.29 is out.

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
Thanks!

**Comment by sftim** [comment]
This PR should only change one language (English)

/lgtm cancel

**Comment by MikeSpreitzer** [comment]
English only now.
/lgtm

**Comment by reylejano** [comment]
Thank you for replying to comments
/approve

**Pull request merged**
