### PR TITLE
[ja]Update graduated or deprecated feature gates

### PR DESCRIPTION
**Pull request by YuikoTakada**
This PR updates graduated/deprecated feature gates list.
This PR updates below web page:
https://kubernetes.io/ja/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features

FYI: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features

### CODE REVIEW

**Review by t-inu — APPROVED** [review]
Every items seem fine to me.
/lgtm

**Comment by atoato88** [comment]
BTW, the description of this PR says:
> This PR updates alpha or beta feature gates list.

You updated the graduated or deprecated feature gates, right?
If so please update the description.

**Comment by atoato88** [comment]
PR codeset looks goot to me.

**Comment by atoato88** [comment]
/assign @nasa9084 
Could you review this?

**Pull request merged**
