### PR TITLE
Change the expired link about sig-governance, for language es

### PR DESCRIPTION
**Pull request by sivanzcw**
* link of sig-governace.md changed, change the link to the new address

### CODE REVIEW

**Comment by sftim** [comment]
See my feedback on #17605

**Comment by raelga** [comment]
Thank you @sivanzcw!

Let's wait for the upstream resolution as @scrim suggests. 

/hold

**Comment by sivanzcw** [comment]
The conversation in #17605 has been resolved, and I have modified the code to amend the issue, please review again. @raelga

**Comment by raelga** [comment]
Thank you very much @sivanzcw !

/lgtm
/approve

**Pull request merged**
