### PR TITLE
fix the broken link in high-availability

### PR DESCRIPTION
**Pull request by xlgao-zju**
ref #8700

This PR is against the master branch.

Signed-off-by: Xianglin Gao <xianglin.gxl@alibaba-inc.com>

### CODE REVIEW

**Comment by stewart-yu** [comment]
i think you should modify url map file rather than change url link

**Comment by xlgao-zju** [comment]
@stewart-yu Thank you for your advice. Honestly, I am a beginner of this repo, so could you tell me which file should I modify?

**Comment by Bradamant3** [comment]
/assign

/hold

As with #8700 -- it's an open question whether we should even keep this content. It's out of date, and appears to be mooted by more recent content.

**Comment by Bradamant3** [comment]
Sorry @xlgao-zju but this file and its children have been removed from the docs build. Redirect is available at https://kubernetes.io/docs/setup/independent/high-availability/

Thanks for understanding!

(note that the newer file still has some formatting issues, but there are other PRs in flight against it to fix.)

**Pull request closed without merging**
