### PR TITLE
Issue with k8s.io/ja/docs/tutorials/kubernetes-basics/expose/expose-i…

### LINKED ISSUE #14786: Issue with k8s.io/ja/docs/tutorials/kubernetes-basics/expose/expose-intro/
**This is a Bug Report**

**Problem:**
Typo
LoadBalancerの説明の項にTypoがあります。
Sercice→Service

**Proposed Solution:**
Fix typo in docs.

**Page to Update:**
https://kubernetes.io/ja/docs/tutorials/kubernetes-basics/expose/expose-intro/

### PR DESCRIPTION
**Pull request by mhamdisemah**
Fixes #14786
Fix typo in Japanese language docs

### CODE REVIEW

**Comment by mhamdisemah** [comment]
ping @nasa9084

**Comment by nasa9084** [comment]
sorry to be late.
/lgtm
/approve

**Pull request merged**
