### PR TITLE
Update the title on "Imperative Command"

### LINKED ISSUE #32573: Managing Kubernetes Objects Using Imperative Commands rename in Docs
**I propose to rename [this](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-command/) section of the k8s documentation to**:

`Imperative Management of Kubernetes Objects Using Commands`

It improves the readability of the documentation neatly making the first word of the name useful for orientation. Do I need to learn about Declarative/Imperative managmement?

- Why are we solving this issue?
  - Make k8s documentation more readable
- To address this issue, are there any code changes? If there are code changes, what needs to be done in the code and what places can the assignee treat as reference points?
  - No code changes to the k8s project needed.
- Does this issue have zero to low barrier of entry?
  - Yes
- How can the assignee reach out to you for help?
  - Comment on this issue. 

The improved readability in the k8s documentation is best seen in the [section above](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/).

# **OLD version:**
image

# **Proposed new version:**
image

### PR DESCRIPTION
**Pull request by eminalemdar**
Updated the title of the page to "Imperative Management of Kubernetes Objects Using Commands"

Fixes #32573

### CODE REVIEW

**Comment by Sea-n** [comment]
## Related PR / Issues
- #33804
- #32573

**Comment by Sea-n** [comment]
I think those files referring to this document should also be changed.

```
$ grep 'Imperative Commands' ./content/en/docs

tasks/manage-kubernetes-objects/imperative-command.md
Line 2:    title: Managing Kubernetes Objects Using Imperative Commands

tasks/manage-kubernetes-objects/imperative-config.md
Line 163:  * [Managing Kubernetes Objects Using Imperative Commands](/docs/tasks/manage-kubernetes-objects/imperative-command/)

tasks/manage-kubernetes-objects/update-api-object-kubectl-patch.md
Line 442:  * [Managing Kubernetes Objects Using Imperative Commands](/docs/tasks/manage-kubernetes-objects/imperative-command/)

tasks/manage-kubernetes-objects/declarative-config.md
Line 44:   * [Managing Kubernetes Objects Using Imperative Commands](/docs/tasks/manage-kubernetes-objects/imperative-command/)
Line 1006: * [Managing Kubernetes Objects Using Imperative Commands](/docs/tasks/manage-kubernetes-objects/imperative-command/)

concepts/overview/working-with-objects/object-management.md
Line 171:  - [Managing Kubernetes Objects Using Imperative Commands](/docs/tasks/manage-kubernetes-objects/imperative-command/)
```

**Comment by eminalemdar** [comment]
> I think those files referring to this document should also be changed.

You are absolutely right. I can open different PRs for those pages with the required changes as well. What do you think @Sea-n ?

**Comment by Sea-n** [comment]
I think it's better to be done within the same commit.
It can be easily done using a local git client, maybe [GitHub Desktop](https://desktop.github.com/) is a good way to try.

**Comment by eminalemdar** [comment]
@Sea-n I've added the changes but can not pass the CLA. Any ideas?

**Comment by Sea-n** [comment]
It's different mail address in GitHub web editor and local git client, maybe sign your CLA for the new mail address again can solve the problem.

https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/33825/#/?version=2

**Comment by eminalemdar** [comment]
> maybe sign your CLA for the new mail address again can solve the problem.

I've done it but no luck I believe. What do you suggest I should do in this case @Sea-n ?

**Comment by Sea-n** [comment]
Oh, I found that the email `em**@kloia.com` is not linked to your GitHub account.
Please add & verify the mail address here: https://github.com/settings/emails

**Comment by eminalemdar** [comment]
> Please add & verify the mail address here

I can not do that because that's my previous business email address and it's not an active address unfortunately. I've changed the local git config to my current email address and I will revert the commit and make the changes again.

**Comment by Sea-n** [comment]
You can (and should) squash commits into one, and the problem will be solved as well.

For GitHub Desktop, here is the tutorial:
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits

**Comment by Sea-n** [comment]
Hey @eminalemdar,

This PR have `needs-rebase` label for 3 weeks. Would you like to solve it so that we can move forward?

**Pull request closed without merging**
