### PR TITLE
Fixed typo in nl.toml

### PR DESCRIPTION
**Pull request by abhigyadufare**
Kubernates >> Kubernetes

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Thanks

/lgtm

**Comment by abhigyadufare** [comment]
@sftim pleasure, please do let me know if i can contribute more in any way possible 🙂

**Comment by Ritikaa96** [comment]
Hi @abhigyadufare thanks for the enthusiasm. 
You can find more reference and guidelines for contribution from https://www.kubernetes.dev/docs/guide/
and especially https://www.kubernetes.dev/docs/guide/#advanced-topics

**Pull request merged**
