### PR TITLE
Manually copy k8s API ref docs to new Hugo site.

### PR DESCRIPTION
**Pull request by steveperry-53**

### CODE REVIEW

**Comment by steveperry-53** [comment]
/hold
I need to move these files into /static.

**Comment by steveperry-53** [comment]
OK, I put the ref file at /static/en/docs/reference/generated/kubernetes-api/v1.10/index.html.

But I'm not sure where to find the ref file on the site. That is, at what URL?

/assign @Bradamant3 
/cc @zacharysarah 
/cc @chenopis

**Comment by bep** [comment]
These needs to be pulled one level up, i.e. not below /en.

**Comment by steveperry-53** [comment]
Will move to  /static/docs/reference/generated/kubernetes-api/v1.10/index.html.

**Comment by steveperry-53** [comment]
OK, it's pretty much working now.
https://deploy-preview-8325--kubernetes-io-master-staging.netlify.com/docs/reference/generated/kubernetes-api/v1.10/

The right column does a weird black-then-white thing. But we can fiddle with that later, I think.

**Comment by steveperry-53** [comment]
@Bradamant3 Go ahead and merge whenever you're ready. I'll be off line for a while. I'll check back this evening.

**Comment by Bradamant3** [comment]
FWIW the weird black-then-white thing was happening on the Jekyll site too -- not a Hugo or migration-specific issue.

/lgtm
/approve

**Pull request merged**
