### PR TITLE
Automated cherry pick of #28763: Fix default disk type for Azure

### PR DESCRIPTION
**Pull request by ialidzhikov**
Cherry pick of #28763 on release-1.17.

#28763: Fix default disk type for Azure

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by celestehorgan** [comment]
Hi @ialidzhikov 

You've opened the same cherry pick 4 times, so I'm going to close the other 3 first.

**Review by celestehorgan — COMMENTED** [review]
/lgtm

but this needs a technical review 

/sig storage

**Comment by ialidzhikov** [comment]
> Hi @ialidzhikov
> 
> You've opened the same cherry pick 4 times, so I'm going to close the other 3 first.

What is wrong with you? They are for different release branches…

**Pull request merged**
