### PR TITLE
使用 Minikube 安装 Kubernetes

### PR DESCRIPTION
**Pull request by RA489**
使用 Minikube 安装 Kubernetes
fixes https://github.com/kubernetes/website/issues/25106

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
```
$ ./scripts/lsync.sh content/zh/docs/setup/learning-environment/minikube.md
content/en/docs/setup/learning-environment/minikube.md has been removed.
```

**Comment by xichengliudui** [comment]
@RA489

**Comment by RA489** [comment]
@tengqm @xichengliudui I have removed this file content/en/docs/setup/learning-environment/minikube.md

**Review by tanjunchen — COMMENTED** [review]
/lgtm
/approve
/retest

**Pull request merged**
