### PR TITLE
[zh] Translate/sync control plane flags for kubeadm

### PR DESCRIPTION
**Pull request by tengqm**

### CODE REVIEW

**Comment by reylejano** [comment]
I confirmed the changes to the links work on the the En page
/lgtm

**Comment by tengqm** [comment]
@reylejano Would you mind approve this one? Looks like a 'lgtm' is not strong enough to kick this in. Thanks.

**Comment by tanjunchen** [comment]
@tengqm  Is this pr still ok?

**Comment by tengqm** [comment]
Looks like we got a happy conflict. Mengjiao Liu has sync'ed this file and her PR has got merged already.
/close

**Pull request closed without merging**
