### PR TITLE
Remove old Dockerfile for Jekyll site

### PR DESCRIPTION
**Pull request by tfogo**
PR #9128 added a new Dockerfile for the Hugo site. The old
staging container is no longer needed.

### CODE REVIEW

**Comment by mistyhacks** [comment]
@lucperkins Should you cherry-pick your commit from your other PR into this one, to keep all of this type of work into one PR?

**Comment by lucperkins** [comment]
@tfogo I agree with @mistyhacks that it'd be best to consolidate the Docker-related changes into a single PR.

**Comment by tfogo** [comment]
@lucperkins sure thing. @mistyhacks is there a PR from @lucperkins that should be cherry picked into this one or did you mean from my other PR touching the Dockerfile (#9216)?

**Comment by chenopis** [comment]
/hold
Consolidate the PRs and close the one that's no longer needed.

**Comment by tfogo** [comment]
This has been consolidated into #9216. Closing this PR.

**Pull request closed without merging**
