### PR TITLE
fixed ingress minikube 2nd deployment commands

### PR DESCRIPTION
**Pull request by GauravJain98**
The 2nd ingress deployment code was not working as required.
I changed it to similar as the 1st deployment and this code also worked for me.

### CODE REVIEW

**Comment by GauravJain98** [comment]
The CLA registration has been completed

**Comment by GauravJain98** [comment]
The CLA registration has been completed

**Comment by jimangel** [comment]
I'm not sure `nodePort` is the best service type to use behind an ingress controller, but this does improve the documentation beyond the existing one. The problem with `--port` is also mentioned in https://github.com/kubernetes/website/issues/11445

/lgtm
/approve

**Comment by GauravJain98** [comment]
Should I test and change it to clusterIP?
I think this should work.

**Comment by GauravJain98** [comment]
> I'm not sure `nodePort` is the best service type to use behind an ingress controller, but this does improve the documentation beyond the existing one. The problem with `--port` is also mentioned in #11445
> 
> /lgtm
> /approve

I just checked that `nodePort` is the best in the context of this task as we use the command 
`minikube service web --url` which can not work with `clusterIP`.

**Pull request merged**
