### PR TITLE
Added missing HPAScaleToZero feature gate

### PR DESCRIPTION
**Pull request by antoinne85**
I discovered this feature gate when trying to configure scale-to-zero but found that it wasn't included in the documentation.

After reading the PR instructions, it wasn't clear to me if I should submit against `master` or not. If this is incorrect, I'm happy to adjust.

### CODE REVIEW

**Comment by sftim** [comment]
@antoinne85 you can sign the CLA to get this contribution ready for review.
If for any reason you're not able to sign the CLA, mention that and someone (eg me!) can log it as an issue and take things from there.

**Comment by antoinne85** [comment]
@sftim Thanks for the heads up. Should be good-to-go now.

**Pull request merged**
