### PR TITLE
 ko: Fix whitespace in ReplicationController glossary entry

### PR DESCRIPTION
**Pull request by sftim**
The Kubernetes object is called ReplicationController. Fix whitespace in https://kubernetes.io/ko/docs/reference/glossary/?all=true#term-replication-controller.

/kind cleanup

### CODE REVIEW

**Comment by ysyukr** [comment]
Thank you for your PR.
In the original Korean document, the English document is marked as 'Replication Controller'.
URL: https://kubernetes.io/docs/reference/glossary/?all=true#term-replication-controller

Since the Korean document reflects the original document, I think that it must also be reflected in the original document, in order for this PR to be approved.

**Comment by sftim** [comment]
I've just opened #18046 for an upstream fix.

**Comment by ysyukr** [comment]
I checked #18046 of upstream.
If #18046  are merged, this PR can be merged.
/assign

**Comment by gochist** [comment]
/hold
waiting for #18046

**Comment by ysyukr** [comment]
I check #18046 .
@gochist check this pr.

/hold cancel
/lgtm

**Pull request merged**
