### PR TITLE
Service without selectors, command correction issue

### PR DESCRIPTION
**Pull request by ahmedavid**
Service without selectors.
Correct command from proxy to port-forward.
issue #33361

### CODE REVIEW

**Comment by ahmedavid** [comment]
Hi @sftim, can you review?

**Comment by sftim** [comment]
> Hi @sftim, can you review?

I'm happy to let the [assigned reviewers](https://github.com/kubernetes/website/pull/44099#event-11066456804) check the changes. I did spot that the PR title isn't right (we prefer _not_ to include issue IDs).
/retitle Service without selectors, command correction issue

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-44099--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/service/#service-no-selector-access

**Comment by kbhawkey** [comment]
👋 @ahmedavid .
I'm interested in a technical review for this change.
/sig network

**Comment by natalisucks** [comment]
@kubernetes/sig-network-pr-reviews Hi folks – we'd love to get your eyes on this PR for accuracy, thanks!

**Comment by divya-mohan0209** [comment]
Left [a message](https://kubernetes.slack.com/archives/C09QYUH5W/p1718120153216209) on the Slack channel

**Comment by aojea** [comment]
/lgtm

Though I think the original comment refers to this proxying https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls , the existing command is indeed wrong

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks Antonio for the technical signoff!
/approve

**Pull request merged**
