### PR TITLE
fix Docker file link

### PR DESCRIPTION
**Pull request by Arhell**
fix issue https://github.com/kubernetes/website/issues/24673

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-24690--kubernetes-io-master-staging.netlify.app/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#troubleshooting
/assign @tengqm

**Comment by tengqm** [comment]
LGTM from docs perspective.
@PatrickLang Please help verify if the target is the right one to use.

**Review by michmike — APPROVED** [review]
/lgtm

**Review by sftim — COMMENTED** [review]
/approve
/sig windows

**Pull request merged**
