### PR TITLE
Add site search to home page

### PR DESCRIPTION
**Pull request by dipesh-rawat**
Closes https://github.com/kubernetes/website/issues/21867

Deploy Preview: [deploy-preview-42299--kubernetes-io](https://deploy-preview-42299--kubernetes-io-main-staging.netlify.app/)

### CODE REVIEW

**Comment by sftim** [comment]
@stormqueen1990 would you be willing to review this change and add your commentary?

**Comment by stormqueen1990** [comment]
> @stormqueen1990 would you be willing to review this change and add your commentary?

Sure thing!

**Review by stormqueen1990 — COMMENTED** [review]
LGTM! Tested on Chrome, Safari and Firefox and all three both render and perform the search as expected.

**Comment by sftim** [comment]
/lgtm
(also from https://github.com/kubernetes/website/pull/42299#pullrequestreview-1555466237)

/approve

Thanks @dipesh-rawat

**Pull request merged**
