### PR TITLE
Fix left panel navigating bar layout issue for zh

### LINKED ISSUE #18737: Left panel navigating bar layout and link bugs
**This is a Bug Report**

**Problem:**
The left panel navigating bar on Chinese version website has globally a extra sub option who has the same name with the main option. The first two sub options of a main option link to the same page.
bug

**Proposed Solution:**
Remove the first sub option

**Page to Update:**
https://kubernetes.io/...

### PR DESCRIPTION
**Pull request by gavinfish**
Remove comments in `_index.md` file to fix left panel navigating bar layout issue. I think this fix is ok for two reasons:

- The content in `_index.md` is simple and stable.
- Other languages also organize the `_index.md` files like this.

fix #18737

### CODE REVIEW

**Comment by markthink** [comment]
@gavinfish 英文注释不需要移除的

**Comment by gavinfish** [comment]
> @gavinfish 英文注释不需要移除的

Hugo 在处理`_index.md`的时候由于有注释的存在误以为该页面不为空，导致左边导航栏多了额外的子项。

**Comment by tengqm** [comment]
Makes perfect sense to me.
/lgtm
/approve

**Pull request merged**
