### PR TITLE
fix glossary 

### PR DESCRIPTION
**Pull request by ptux**
Reference: 
https://docs.docker.com/engine/reference/commandline/push/

> Use docker image push to share your images to the Docker Hub **registry** or to a self-hosted one.

Comment:
https://github.com/kubernetes/website/pull/31089#discussion_r777190920

> "Repository" is a collection of container images or other artifacts in the registry that have the same name but different tags.

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Waiting for another sig docs approver/reviewer to sign off

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
