### PR TITLE
Add View application logs objective as a contribution CCOSS 2020

### LINKED ISSUE #20378: Content issue with 'hello-minikube' tutorial
**This is a Bug Report**

**Problem:** The tutorial does not cover all the objectives.

- [x] Deploy a hello world application to Minikube.
- [x] Run the app.
- [ ] View application logs.

**Proposed Solution:** Add a sub-section in the tutorial that covers `View application logs` objective. 

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube

The [Enable addons](https://kubernetes.io/docs/tutorials/hello-minikube/#enable-addons) sub-section seems to be out of place, should it have been about the logviewer addon rather than metrics-server addon?

### PR DESCRIPTION
**Pull request by Drake8710**
Add View Application logs section per Fixes #20378 
Documented section taken from existing documentation located in content\en\docs\concepts\cluster-administration\logging.md file

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@Drake8710
Pls sign the CLA in order for the PR to be reviewed.

**Comment by Drake8710** [comment]
@Arhell Hi
Yes, I already did that even before making the commit... don't know what else is missing for cla/linuxfoundation check
image

**Comment by Drake8710** [comment]
cncf-cla: yes

**Comment by sftim** [comment]
It seems like the commit in this PR isn't matching to any GitHub user. See https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/ for more details.

**Comment by sftim** [comment]
@Drake8710 did you have a chance to look at the GitHub committer / CLA signer mismatch?

**Comment by kbhawkey** [comment]
Hi @Drake8710.
To move this PR forward, would you verify that your GitHub account information matches the information you used
to sign the CLA? This pull request cannot be reviewed without a valid CLA. Thanks!

**Comment by kbhawkey** [comment]
Hi @Drake8710 .
I am closing this pull request.
However, you can reopen this PR at any time and continue to work on the changes.
Thank you!
/close

**Pull request closed without merging**
