### PR TITLE
Remove unused scripts

### PR DESCRIPTION
**Pull request by lucperkins**
The scripts removed in this PR appear to be related to the Jekyll version of the site. The `verify-docs-format.sh` script is commented out in the Travis configuration and I don't see any use for them. If they are indeed still in use I'm happy to close this.

### CODE REVIEW

**Comment by lucperkins** [comment]
@tengqm Could you possibly give the /approve as well?

**Comment by chenopis** [comment]
Yup, we don't need these anymore.
/lgtm
/approve

**Pull request merged**
