### PR TITLE
Adds information about Configurable HPA

### PR DESCRIPTION
**Pull request by gliush**
Configurable HPA scaling rules.

KEP issue: https://github.com/kubernetes/enhancements/issues/853
KEP PR: https://github.com/kubernetes/enhancements/pull/883
k8s PR: https://github.com/kubernetes/kubernetes/pull/74525

### CODE REVIEW

**Comment by sftim** [comment]
This is a placeholder / work-in-progress
/retitle [WIP] Adds information about Configurable HPA

**Comment by pgburt** [comment]
Hi @josephburnett @gliush. I'm a Docs shadow for the 1.17 release. I'm writing with a reminder that the deadline for PRs to be "Ready for Review" is by Nov 15, 2019 (this Friday!).

**Comment by josephburnett** [comment]
/retitle Adds information about Configurable HPA

No longer a work in progress.

**Comment by josephburnett** [comment]
pgburt@ this is ready for review.  Thanks for the reminder!

**Comment by daminisatya** [comment]
Is this still going into 1.17?

**Comment by sftim** [comment]
@gliush you need to have a CLA signed. Once you've done that we can look at your pull request.

As it's been a while, I'm going to close this PR. It's absolutely fine to open a new PR if you'd like to, proposing the same changes.

/close

**Pull request closed without merging**
