### PR TITLE
Fix curl arguments

### PR DESCRIPTION
**Pull request by cofyc**
`-O` conflicts with `-o`.

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
```shell
cloud@ubuntu:~$ curl -LO https://pkg.cfssl.org/R1.2/cfssl_linux-amd64 -o cfssl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.8M  100  9.8M    0     0   867k      0  0:00:11  0:00:11 --:--:--  929k
```
seems to be no conflict...

**Comment by cofyc** [comment]
@zhangxiaoyu-zidif Try next command `chmod +x cfssl`.

```
`-O`  Write output to a local file named like the remote file we get. (Only the file part of the  remote
              file is used, the path is cut off.)

`-o <output> ` Write  output  to <file> instead of stdout.
```

`-O` overrides `-o`, so `curl -LO https://pkg.cfssl.org/R1.2/cfssl_linux-amd64 -o cfssl` will save file as `cfssl_linux-amd64` instead of `cfssl`.

**Comment by zhangxiaoyu-zidif** [comment]
@cofyc
Sorry, you are right, I miss it. Thanks.
/lgtm

**Pull request merged**
