### PR TITLE
(doc-fix): Removing extra space in kubectl command

### PR DESCRIPTION
**Pull request by rajdas98**
Signed-off-by: Raj <mail.rajdas@gmail.com>
removing extra space in some kubectl commands
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.18 Features: set Milestone to 1.18 and Base Branch to dev-1.18
>
> For pull requests on Chinese localization, set Base Branch to release-1.16
> Feel free to ask questions in #kubernetes-docs-zh
>
> For pull requests on Korean Localization: set Base Branch to dev-1.16-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by sftim** [comment]
@rajdas98 if you can get the CLA signed, we can take a look; if you have any trouble signing that, and would like help, please reply with your questions.

**Comment by sftim** [comment]
Thanks @rajdas98!

**Comment by rajdas98** [comment]
Thanks. I applied for CLA.
Next time, I will sign the PR.

**Pull request merged**
