### PR TITLE
Fix minikube links and kubectl install pages

### PR DESCRIPTION
**Pull request by mkorbi**
Fixed the minkube links in the DE pages and hit a rabbit hole:

- Deleted minikube pages (as in the EN version)
- Replaced the minikube links with official documentation
- Translated the missing kubectl install pages
- further minor adjustments 

Should solve this issue https://github.com/kubernetes/website/issues/27946

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Hello @mkorbi.
According to the [CI log](https://app.netlify.com/sites/kubernetes-io-master-staging/deploys/609d247822361a00070bfb9e#L71),
these files are required in `content/de/` directory:
- included/install-kubectl-gcloud.md
- included/verify-kubectl.md
- docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
- docs/tasks/tools/included/optional-kubectl-configs-zsh.md
- included/kubectl-whats-next.md
- included/optional-kubectl-configs-zsh.md

```
10:09:08 PM: ERROR 2021/05/13 13:09:08 [de] no Resource or Page matching "included/install-kubectl-gcloud.md*".
10:09:08 PM: ERROR 2021/05/13 13:09:08 [de] no Resource or Page matching "included/verify-kubectl.md*".
10:09:08 PM: ERROR 2021/05/13 13:09:08 [de] tabs include not found for path "docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md"
10:09:08 PM: ERROR 2021/05/13 13:09:08 [de] tabs include not found for path "docs/tasks/tools/included/optional-kubectl-configs-zsh.md"
10:09:08 PM: ERROR 2021/05/13 13:09:08 [de] no Resource or Page matching "included/kubectl-whats-next.md*".
10:09:08 PM: ERROR 2021/05/13 13:09:08 [de] no Resource or Page matching "included/optional-kubectl-configs-zsh.md*".
```

PTAL!

**Comment by jimangel** [comment]
@mkorbi I'm not sure what is needed to fix the failing builds. For now, I think it might be best to open a new PR. If you have any alternative ideas, feel free to reopen this on. Sorry for the extra work.

/close

**Pull request closed without merging**
