### PR TITLE
Update expose-external-ip-address.md

### PR DESCRIPTION
**Pull request by AdamDang**
"is" is duplicated in line 101 and 102.

### CODE REVIEW

**Comment by zacharysarah** [comment]
@AdamDang 👋 I notice you've submitted several small pull requests. Thanks for the improvements! In the future, please group tiny changes into a single aggregate pull request.

**Comment by zacharysarah** [comment]
/lgtm
/approve
/hold
/assign @Bradamant3
Docs are frozen ❄️ for 1.10 release day. Feel free to remove the /hold once docs thaw.

**Comment by AdamDang** [comment]
Thanks @zacharysarah!
I got it.

**Pull request merged**
