### PR TITLE
add new lease namespace

### PR DESCRIPTION
**Pull request by cloudmelon**
Squash the previous 2 commits into 1

### CODE REVIEW

**Comment by cloudmelon** [comment]
@steveperry-53

Melony

**Comment by sftim** [comment]
I'm afraid this PR is out of date Melony - could you either rebase it, or open a new PR with the same changes but based from _master_? A rebase is easier for reviewers.

**Comment by cloudmelon** [comment]
Hi Tim, this is the new PR that I opened. 

Melony

**Comment by jimangel** [comment]
@cloudmelon please [rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) your commit.

**Comment by cloudmelon** [comment]
It’s only 1 commit now, thanks 


Melony

**Comment by jimangel** [comment]
@cloudmelon thank you for squashing you commit, it appears you still need to rebase or a conflicting commit merged after you rebased. Let me know if we can help!

**Comment by cloudmelon** [comment]
Hi Jim, I need your hands this time because initially I created the PR and
edited on Github website from which I couldn't rebase due to the
permissible limits. So I created a second PR  and made the same changes
again on my local PC... I can see only one commit from my view,  would
appreciate if you could help me to squash it, thanks !

**Comment by kbhawkey** [comment]
Hello @cloudmelon .
Are you able to _rebase_ your branch?
Hope these instructions are helpful:
https://kubernetes.io/docs/contribute/new-content/new-content/#merge-conflicts-and-rebasing

**Comment by kbhawkey** [comment]
Hi @cloudmelon .
I am closing this pull request until you have time to _rebase_.
You can reopen this PR at any time or create a new pull request.
Thanks!
/close

**Comment by cloudmelon** [comment]
Hello,

I have done everything I could ( for rebase even rebuilt my branch ) and I was asking help which didn’t raise any attention.

**Comment by kbhawkey** [comment]
Hello @cloudmelon .
How can I help?
You will need to checkout your branch (locally).
I assume `git remote -vv` returns your remotes?
git fetch upstream
git rebase -i upstream/master
I just reviewed your changes and branch. There should be one change to accept (seems optional).
Save. Add single file. Commit single file.
git push origin <your branch name>

**Comment by cloudmelon** [comment]
HI @kbhawkey Thanks for your help, just tried your suggestions ...  how does it look like now ?
image

**Comment by kbhawkey** [comment]
@cloudmelon, Check out the instructions at:
https://kubernetes.io/docs/contribute/new-content/new-content/#fork-the-repo

**Comment by cloudmelon** [comment]
> @cloudmelon, Check out the instructions at:
> https://kubernetes.io/docs/contribute/new-content/new-content/#fork-the-repo

Hi @kbhawkey  I think the key thing is : initially I created my 1st commit on Github rather than locally, then back and forth. I reform the repo gain and made the same changes on my local repo, so I can see only 1 commit for this PR.  I don't get why still need to rebase and refork  ?

**Comment by kbhawkey** [comment]
@cloudmelon , Not sure about your local fork. Have you run:
`git remote add upstream https://github.com/kubernetes/website.git`

**Comment by cloudmelon** [comment]
> @cloudmelon , Not sure about your local fork. Have you run:
> `git remote add upstream https://github.com/kubernetes/website.git`
> 
> At this point, you may want to open a new PR with these changes.

I've redone all those steps, I can truly see only 1 commit, can you have a look see if we can merge it ? 

image

**Comment by kbhawkey** [comment]
This pull request is a duplicate of PR #21674.
/close

**Pull request closed without merging**
