### PR TITLE
Fix the relative link references in the content folder

### PR DESCRIPTION
**Pull request by chenrui333**
issue tracker: https://github.com/kubernetes/website/issues/13231

### CODE REVIEW

**Comment by DanyC97** [comment]
@chenrui333 my 0.02$ feedback:

i personally would have preferred to have a PR per language rather than a giant PR. It would have been easier to:

a) review it by each sub-group team including checking the netlify preview pages (picking few random ones, not every single one ;) )
b) would have kept things separated like we do today with each lang / branch

**Comment by chenrui333** [comment]
@DanyC97 that is totally good point, I will separate out the PRs now 

Thanks for the idea! 👍

**Comment by chenrui333** [comment]
PR has been divided into this localization team's PR based on the language tags.
Thanks @DanyC97 !

**Pull request closed without merging**
