### PR TITLE
Remove Google SDK instructions.

### PR DESCRIPTION
**Pull request by brendandburns**
Ref: https://github.com/kubernetes/website/issues/20232

Per https://github.com/kubernetes/enhancements/tree/master/keps/sig-docs/1326-third-party-content-in-docs this content is not necessary and is vendor specific.

### CODE REVIEW

**Comment by tengqm** [comment]
Thanks.
/approve

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-28165--kubernetes-io-master-staging.netlify.app/docs/tasks/tools/install-kubectl-linux/

**Pull request merged**
