### PR TITLE
Update cheatsheet.md

### PR DESCRIPTION
**Pull request by srirgirhub**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Review by rajitha-source — COMMENTED** [review]
hello

**Comment by kbhawkey** [comment]
👋 @srirgirhub . Thanks for your contribution.
Before this PR can be reviewed, you must have a valid CLA.

**Pull request closed without merging**
