### PR TITLE
Created nl.toml

### PR DESCRIPTION
**Pull request by olku**
Dutch (NL) translation

### CODE REVIEW

**Comment by bradtopol** [comment]
@olku Thank you for your contribution. Please sign the CLA so we can accept your PT for review

**Comment by rlenferink** [comment]
Thanks for applying the feedback. It looks like the `cla/linuxfoundation` says you're authorized, so the CLA check is probably still failing over [your first commit in this PR](https://github.com/kubernetes/website/pull/14131/commits/5303dfb226ae597c0c3bdbc3e6ee56a6adcc59d2). Can you rebase that one as well?

**Comment by olku** [comment]
@rlenferink I'm kind of struggling with the git rebase.

**Comment by rlenferink** [comment]
@olku if you contact me on [slack](https://slack.k8s.io) I will guide you through the rebase ;)

My username on slack is @rlenferink as well

**Comment by rlenferink** [comment]
@olku did you succeed with this? If not, you can follow the following steps:

- Run `git rebase -i HEAD~5`.
- You should see a list of commits, each commit starting with the word "pick".
- Make sure the first commit says "pick" and change the rest from "pick" to "squash". -- This will squash each commit into the previous commit, which will continue until every commit is squashed into the first commit.
- Save and close the editor.
- It will give you the opportunity to change the commit message.
- Save and close the editor again.

Now you squashed all 5 commits to a single commit and we need to update the author:
- Run `git commit --amend --author="olku <olle.kunnen@gmail.com>"` (or any other author which you used to sign the CNCF CLA)
- Then you have to force push the final commit using `git push -f`.

**Comment by rlenferink** [comment]
@olku perfect! Our bot added the cncf-cla:yes label, yay 🎉 

For some reason, it looks like the feedback you processed is not present any more (e.g., check [here](https://github.com/kubernetes/website/pull/14131/files#r280528976)), but luckily they're only small points to process. If you can process these points as well, that would be great 😃

**Comment by olku** [comment]
@rlenferink I didn't see where that disappeared to, but I've processed it again.

**Comment by rlenferink** [comment]
@olku probably something with the rebase, but nevertheless we got everything processed right now and this looks good to me for approval :) Many thanks for processing the feedback given!

/lgtm
/assign @zacharysarah
for approval

**Comment by zacharysarah** [comment]
@olku 👋 Thanks for getting started on a new localization! Please squash your commits so we can merge this PR. 👍

**Comment by olku** [comment]
@zacharysarah squashed and ready.

**Comment by rlenferink** [comment]
Thanks!
/lgtm

**Pull request merged**
