### PR TITLE
[ja] Update `concepts/extend-kubernetes`

### PR DESCRIPTION
**Pull request by ptux**
- put describtion of controller in the same paragraph
- keep consistency with subtitle (Extension Patterns)

Releated PR:

https://github.com/kubernetes/website/pull/30337

### CODE REVIEW

**Comment by ptux** [comment]
@makocchi-git
@nasa9084

Could you guys be my sponsors to get the membership of Kubernetes?
Here are my contributions:

https://github.com/kubernetes/website/commits/main?author=ptux

**Comment by jihoon-seo** [comment]
@ptux Sure! 😊

**Comment by ptux** [comment]
@jihoon-seo 

Thanks for the support.
I'll mention you when I found another sponsor.

**Comment by nasa9084** [comment]
@ptux I can, please create membership request issue ;)

**Comment by nasa9084** [comment]
wait for en PR
/hold

**Comment by ptux** [comment]
The upstream PR https://github.com/kubernetes/website/pull/30337 is closed without merging.

**Pull request closed without merging**
