### PR TITLE
KEP-3857: promote RecursiveReadOnlyMounts feature to beta

### PR DESCRIPTION
**Pull request by AkihiroSuda**
### Description

The gate has reached beta in v1.31.

refs:
- kubernetes/enhancements#3857
- kubernetes/kubernetes#125475

### Issue

Closes: #48614

### CODE REVIEW

**Comment by tengqm** [comment]
dup of https://github.com/kubernetes/website/pull/47852

**Comment by AkihiroSuda** [comment]
> #47852

47852 seems stalled, any chance to just merge this PR?

**Review by dipesh-rawat — COMMENTED** [review]
/lgtm

**Pull request merged**
