### PR TITLE
fix: middle card is not aligned in partners page (zh-cn)

### PR DESCRIPTION
**Pull request by ocleo1**
https://kubernetes.io/zh-cn/partners/

image

### CODE REVIEW

**Comment by ocleo1** [comment]
@k8s-ci-robot /check-cla

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by ocleo1** [comment]
> Please sign CLA

Done

**Comment by ocleo1** [comment]
@k8s-ci-robot check-cla

**Comment by ocleo1** [comment]
@k8s-ci-robot /check-cla

**Pull request closed without merging**
