### PR TITLE
[ko] Fix a bad merge into kubectl install task

### PR DESCRIPTION
**Pull request by sftim**
Fix a bad merge. Helps with https://github.com/kubernetes/website/issues/41005 (but doesn't close it).

### CODE REVIEW

**Comment by seokho-son** [comment]
Thanks!
/lgtm

**Comment by jongwooo** [comment]
duplicate #41994

**Comment by sftim** [comment]
I'd like to see this fixed on _main_ fairly soon.

**Comment by sftim** [comment]
/reopen
I misclicked!

**Comment by seokho-son** [comment]
Likewise: https://github.com/kubernetes/website/pull/41994#issuecomment-1649050028

We currently have two PRs that resolve the same bug, but are targeted towards different branches.

https://github.com/kubernetes/website/pull/41994 (targeting main)
https://github.com/kubernetes/website/pull/42173 (targeting Korean dev branch: [dev-1.27-ko.1](https://github.com/caputdraconis050630/k8s-website/tree/dev-1.27-ko.1))

A Korean Dev branch would be the ideal target for Korean localization PRs. However, considering that this bug fix needs to be quickly applied to our live website, the main branch becomes an appropriate target in this instance.

On this occasion, I see it fit to approve both PRs.

/approve

**Pull request merged**
