### PR TITLE
update LegacyServiceAccountTokenTracking to beta

### PR DESCRIPTION
**Pull request by zshihang**
PR: https://github.com/kubernetes/kubernetes/pull/114523
Issue: https://github.com/kubernetes/enhancements/issues/2799

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA

**Comment by mickeyboxell** [comment]
Hi @zshihang :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review as soon as possible. 01:00 UTC Wednesday 22nd March 2023 / 17:00 PDT Tuesday 21st March 2023 is the official deadline. 

This PR will need a doc review by Tuesday 4th April 2023 to get this into the release. Please reach out to required SIGs to get their review. Thank you!

**Comment by tengqm** [comment]
/lgtm
(reapplied)

**Pull request merged**
