### PR TITLE
Fix Typo on Guide for scheduling Windows containers in Kubernetes Page

### LINKED ISSUE #36554: Typo on Guide for scheduling Windows containers in Kubernetes page
The spelling of the **functionality** i.e funcationality is wrong, I'm attaching the screenshot for the same.
May I open a new PR correcting the spelling?
Typo

### PR DESCRIPTION
**Pull request by UtkarshMishra12**
Fixes #36554

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
Hello @UtkarshMishra12 , this is a trivial edit per our contribution docs. Thank you for your contribution! However, could you please before submitting such PRs scan the entire page for any issues and then submit? I'd be happy to approve this effort, if you can confirm that there are no further typos in this page.

**Comment by UtkarshMishra12** [comment]
Hey @divya-mohan0209 Yes, I have checked it myself, and now there are no more typos on the Page. I've been constantly reviewing other pages also for such typos or mistakes.
I'm starting my open-source journey by contributing to the docs and then moving on to the bigger changes (i.e Code Changes)

**Comment by reylejano** [comment]
This PR duplicates PR https://github.com/kubernetes/website/pull/36566
Issue https://github.com/kubernetes/website/issues/36554 that this PR fixes is now closed and solved
Closing this PR
/close

**Pull request closed without merging**
