### PR TITLE
Update links of apparmor doc

### PR DESCRIPTION
**Pull request by ping035627**
Update links for AppArmor failures and AppArmor_Core_Policy_Reference in apparmor doc.

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@ping035627 Thanks for your PR! I checked the updates you made on : https://deploy-preview-12593--kubernetes-io-master-staging.netlify.com/docs/tutorials/clusters/apparmor/ and they look fine to me. However, there are a couple of other broken links as well.
https://%!s()/blob/master/content/en/docs/tutorials/clusters/deny-write.profile
1. error code: 404 (not found), linked from page(s):
	https://deploy-preview-12593--kubernetes-io-master-staging.netlify.com/docs/tutorials/clusters/apparmor/

https://%!s()/master/content/en/examples/pods/security/hello-apparmor.yaml

2. error code: 404 (not found), linked from page(s):
	https://deploy-preview-12593--kubernetes-io-master-staging.netlify.com/docs/tutorials/clusters/apparmor/

Could you please fix them as well.

**Comment by zparnold** [comment]
@Rajakavitha1 They links seem to work for me.

/lgtm
/approve

**Comment by Rajakavitha1** [comment]
@zparnold The the links that @ping035627 fixed work fine.
However, in the same page (https://deploy-preview-12593--kubernetes-io-master-staging.netlify.com/docs/tutorials/clusters/apparmor/)there are two more broken links:



1.    https://%!s()/blob/master/content/en/docs/tutorials/clusters/deny-write.profile
    error code: 404 (not found), linked from page(s):
    https://deploy-preview-12593--kubernetes-io-master-staging.netlify.com/docs/tutorials/clusters/apparmor/

2.    https://%!s()/master/content/en/examples/pods/security/hello-apparmor.yaml

error code: 404 (not found), linked from page(s):
https://deploy-preview-12593--kubernetes-io-master-staging.netlify.com/docs/tutorials/clusters/apparmor/

**Comment by ping035627** [comment]
@Rajakavitha1 This is a universal problem. The places of "codenew file=" in other pages are error too.

**Comment by Rajakavitha1** [comment]
@ping035627 May I request you to raise an issue and mark it as good first issue and help wanted.

**Pull request merged**
