### PR TITLE
Update eviction example to use policy/v1

### PR DESCRIPTION
**Pull request by liggitt**
docs update for 1.22 for https://github.com/kubernetes/kubernetes/pull/100724

preview at https://deploy-preview-27810--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/safely-drain-node/#eviction-api

/cc @mortent

### CODE REVIEW

**Comment by sftim** [comment]
I think this should target the branch _dev-1.22_ - targeting _master_ would mean we want this change in the live documentation right away.

**Comment by liggitt** [comment]
done, didn't realize the 1.22 branch was already available

**Comment by sftim** [comment]
LGTM

**Review by irvifa — COMMENTED** [review]
/lgtm

**Review by PI-Victor — APPROVED** [review]

**Pull request merged**
