### PR TITLE
Remove support for basic authentication

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mok@vmware.com>

See https://github.com/kubernetes/kubernetes/pull/89069

/milestone v1.19

### CODE REVIEW

**Comment by enj** [comment]
/hold

Until there is a `release-1.19` branch (or maybe its when `master` is tracking `v1.19`).

**Comment by sftim** [comment]
@enj just so you know, this should target the _dev-1.19_ branch (which does not yet exist)

I presume:
/sig auth

**Comment by jimangel** [comment]
@sftim is spot on, this will need to be opened up against the `dev-1.19` branch which has not been created yet.

/hold

**Comment by enj** [comment]
> @enj just so you know, this should target the _dev-1.19_ branch (which does not yet exist)

Thanks for the info - I will update the branch once it exists and the `k/k` PR is merged.

**Comment by enj** [comment]
@sftim @jimangel is there a timeline for the creation of the `dev-1.19` branch?  This `k/k` PR for v1.19 should be merged today.

**Comment by sftim** [comment]
> This `k/k` PR for v1.19 should be merged today.

Hi @enj 
What's this blocking?

**Comment by enj** [comment]
> > This `k/k` PR for v1.19 should be merged today.
> 
> Hi @enj
> What's this blocking?

Does not block anything.  I just do not want to forget about it during the 1.19 release and have it confuse users who expect the functionality to exist because the docs are out of date.

**Comment by enj** [comment]
/hold cancel

I believe this is ready.

/test all

**Comment by sftim** [comment]
@enj, can you revise this PR to include only English changes? It looks like some Chinese whitespace changes have crept in.

**Comment by sftim** [comment]
SIG Docs recommends limiting PRs to a single localization: https://kubernetes.io/docs/contribute/intermediate/#working-with-localized-content

**Comment by enj** [comment]
> SIG Docs recommends limiting PRs to a single localization: https://kubernetes.io/docs/contribute/intermediate/#working-with-localized-content

👍 opened #20133 for the `zh` changes.

**Comment by sftim** [comment]
That was commendably fast @zacharysarah

**Comment by mikedanese** [comment]
For tech review:

/lgtm

**Pull request merged**
