### PR TITLE
urgent!! typo in case study - removed extra letter

### PR DESCRIPTION
**Pull request by alexcontini**
@kbarnard10 @zacharysarah there was as typo in one of the headers, please merge when you have a chance, thank you!!

### CODE REVIEW

**Comment by cody-clark** [comment]
Sorry I didn't see this sooner, @alexcontini!

/lgtm
/approve

**Comment by kbarnard10** [comment]
Thank you @cody-clark!

**Comment by alexcontini** [comment]
@cody-clark  thank you SO much!!!

**Pull request merged**
