### PR TITLE
Typo `etcdutl` in configure-upgrade-etcd.md

### PR DESCRIPTION
**Pull request by TreeKat71**
Typo
Should be `etcdctl` not `etcdutl`

### CODE REVIEW

**Comment by TreeKat71** [comment]
I have signed the CLA, I am not sure if I still need to do something.
Please let me know if I miss anything.

**Comment by divya-mohan0209** [comment]
@wojtek-t / @mml - please review from a technical standpoint.

**Review by justaugustus — APPROVED** [review]
/lgtm

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-30368--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster

**Pull request merged**
