### PR TITLE
Fix issue of broken links to translated docs #2

### LINKED ISSUE #22266: Issue of broken links to translated docs #2
**This is a Bug Report**

**Problem:**
There are lots of translated docs contains broken links of redirects to the other translated docs in content/ko/docs directory.

**Proposed Solution:**
Fix these broken links to the translated docs.

-  content/ko/docs/concepts/cluster-administration/cluster-administration-overview.md
-  content/ko/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
-  content/ko/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
-  content/ko/docs/concepts/extend-kubernetes/extend-cluster.md
-  content/ko/docs/concepts/policy/limit-range.md
-  content/ko/docs/concepts/policy/resource-quotas.md
-  content/ko/docs/concepts/scheduling-eviction/taint-and-toleration.md
-  content/ko/docs/concepts/storage/storage-classes.md
-  content/ko/docs/contribute/style/write-new-topic.md
-  content/ko/docs/reference/using-api/api-overview.md
-  content/ko/docs/reference/using-api/client-libraries.md
-  content/ko/docs/setup/best-practices/cluster-large.md
-  content/ko/docs/setup/learning-environment/minikube.md
-  content/ko/docs/setup/production-environment/tools/kops.md
-  content/ko/docs/tasks/access-application-cluster/web-ui-dashboard.md
-  content/ko/docs/tutorials/hello-minikube.md

**Page to Update:**
https://kubernetes.io/...

/language ko

### PR DESCRIPTION
**Pull request by pjhwa**
Closes #22266 

This PR contains the following translated docs which has the broken links of static/_redirects.

-  content/ko/docs/concepts/cluster-administration/cluster-administration-overview.md
-  content/ko/docs/concepts/extend-kubernetes/api-extension/custom-resources.md
-  content/ko/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
-  content/ko/docs/concepts/extend-kubernetes/extend-cluster.md
-  content/ko/docs/concepts/policy/limit-range.md
-  content/ko/docs/concepts/policy/resource-quotas.md
-  content/ko/docs/concepts/scheduling-eviction/taint-and-toleration.md
-  content/ko/docs/concepts/storage/storage-classes.md
-  content/ko/docs/contribute/style/write-new-topic.md
-  content/ko/docs/reference/using-api/api-overview.md
-  content/ko/docs/reference/using-api/client-libraries.md
-  content/ko/docs/setup/best-practices/cluster-large.md
-  content/ko/docs/setup/learning-environment/minikube.md
-  content/ko/docs/setup/production-environment/tools/kops.md
-  content/ko/docs/tasks/access-application-cluster/web-ui-dashboard.md
-  content/ko/docs/tutorials/hello-minikube.md

### CODE REVIEW

**Comment by pjhwa** [comment]
간단한 스크립트를 하나 만들었습니다. 
참고하세요~

https://github.com/pjhwa/k8s-ko-docs-scripts/findbrokenlinks.sh

- 한글로 번역된 문서 중 이미 번역된 문서 대신 영문 문서를 가리키고 있는 부분을 찾아줍니다.
- 이미 번역된 문서의 URL에서 섹션명(#로 시작하는)이 붙은 URL을 출력하고, 이를 수동으로 확인합니다.
- 한글로 번역된 문서 중 website/static/_redirects 에 포함된 URL(이미 한글 번역이 되어있는 문서로의)이 있는 부분을 찾아줍니다.

**Comment by tengqm** [comment]
sigh ... this is dirty ...
we are suffering from the same problem in zh localization

**Comment by pjhwa** [comment]
> sigh ... this is dirty ...
> we are suffering from the same problem in zh localization

@tengqm I think you can try to use my script for that problem.
https://github.com/pjhwa/k8s-ko-docs-scripts/blob/master/findbrokenlinks.sh
It's very simple, so you can understand how to use it. (just change ko to zh in the script)

**Comment by gochist** [comment]
@pjhwa It looks like duplicated effort with #21996

**Comment by tengqm** [comment]
@pjhwa I'm not referring to the tricks of finding and fixing the links. I'm referring to the fact that the links in the English site is not friendly to localizations. See #19526

**Comment by pjhwa** [comment]
> I'm not referring to the tricks of finding and fixing the links. I'm referring to the fact that the links in the English site is not friendly to localizations. See #19526

Yes, I didn't know that the effort already is on going.
Right. English site is not friendly to localizations.

**Comment by gochist** [comment]
@pjhwa @yoonian I'm sorry that I checked the base branch late. Merging directly into the `master` branch should be avoided if possible. This is because there is a high possibility of conflict in the process of merging the team milestone branch into the `master`.

@pjhwa Would you please rebase this onto `dev-1.18-ko.7`?

**Comment by pjhwa** [comment]
현재 작업 브랜치로 변경하였습니다.

**Comment by gochist** [comment]
> @gochist 현재 작업 브랜치로 변경하였습니다. (링크 수정은 bug fix로 생각해서 master를 타겟으로 했었습니다. 앞으로는 주의하겠습니다.)

리뷰어나 승인자 간 기준이 명확하지 않아 불편을 드린 것 같습니다. master에 직접 변경을 허용하는 경우는 버그 수정 건 중, 라이브에 즉시 적용되어야하는 시급한 건, 또는 팀 마일스톤 브랜치에 익숙하지 않은 업스트림 컨트리뷰터의 작은 변경 건을 기준으로 리뷰, 승인하곤 했습니다. 논의를 거쳐 명문화할 수 있도록 하겠습니다.

**Pull request merged**
