### PR TITLE
localization for subscribe button

### PR DESCRIPTION
**Pull request by Arhell**
issue #21294
en [PR ](https://github.com/kubernetes/website/pull/20878)

/language ko

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-21296--kubernetes-io-master-staging.netlify.app/ko/#kubeweekly

**Comment by gochist** [comment]
As a native Korean speaker, LGTM

/lgtm
/unassign
/assign @onlydole

**Comment by onlydole** [comment]
Thank you @Arhell and @gochist!

/approve

**Pull request merged**
