### PR TITLE
add chenxuc to sig-docs-zh-reviews

### PR DESCRIPTION
**Pull request by chenxuc**
I'd like to apply for sig-docs-zh-reviews role.
I've met the [requirements for reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer):
- 20+ PRs merged: https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+author%3Achenxuc
- 5+ PRs reviewed: https://github.com/kubernetes/website/pulls?q=type%3Apr+reviewed-by%3Achenxuc
- Member of Kubernetes for 3+ months

Thanks!

/cc @tengqm

### CODE REVIEW

**Comment by sftim** [comment]
/hold
Happy with this to happen, but please first make this change to https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-docs/teams.yaml, and then apply the equivalent update here.

**Comment by chenxuc** [comment]
@sftim Thanks a lot for the tips. I've open a PR for teams.yaml : https://github.com/kubernetes/org/pull/2831
Please let me know if anything else needed.

**Pull request merged**
