### PR TITLE
pod-security-policy.md: update to use PSP from policy/v1beta1

### PR DESCRIPTION
**Pull request by php-coder**
* update to use PSP from policy/v1beta1
* fix a broken link

PTAL @liggitt @tallclair

### CODE REVIEW

**Comment by tengqm** [comment]
@php-coder Is this change meant for 1.13 or 1.14?

**Comment by php-coder** [comment]
>  Is this change meant for 1.13 or 1.14?

The change could be applied to both. Could you take care about backporting it to the respective branches, please?

**Comment by php-coder** [comment]
@chenopis PTAL

**Pull request merged**
