### PR TITLE
Update nodelocaldns.md

### PR DESCRIPTION
**Pull request by bnjf**
DNSCahe -> DNSCache

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
@bnjf, Can you sign the CLA(https://kubernetes.io/docs/contribute/start/#sign-the-cla), so that this PR can be reviewed?

**Comment by zacharysarah** [comment]
@bnjf Please feel free to `/reopen` when you're ready to sign the CLA.

/close

**Comment by bnjf** [comment]
signed
/reopen

**Pull request merged**
