### PR TITLE
[zh-cn] sync only update `api_metadata` docs

### PR DESCRIPTION
**Pull request by tico88612**
Update docs:
- Lease
- LimitRange
- EndpointSlice
- ReplicationController

### CODE REVIEW

**Comment by windsonsea** [comment]
It's recommended to combine those similar changes into a PR.

See [your merged PR list](https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Atico88612+is%3Aclosed) has the same front-matter cases.

**Comment by tico88612** [comment]
@windsonsea

Some of the files are updated and some are not, that's why it's done this way.

I'll be sending out only the updates that are added to `api_metadata` in one PR, and the ones that have updated descriptions will be handled by one PR each.

**Review by dipesh-rawat — COMMENTED** [review]
Just a heads-up there is `api_reference_title` string variable in the [en.toml (here)](https://github.com/dipesh-rawat/website/blob/6be32f03db188107f33b56dfab99c00967b42b65/data/i18n/en/en.toml#L6) file that are also part of these "api_metadata" changes. It would enhance the completeness of this update to also include localization of `api_reference_title` for [zh-cn.toml](https://github.com/dipesh-rawat/website/blob/main/data/i18n/zh-cn/zh-cn.toml), either as a complete synchronization zh-cn.toml or by solely addressing this variable.

_(Refer 'en' PR https://github.com/kubernetes/website/pull/45496/files for more context which added the API reference page link based on `api_metadata`)_

I'll defer to the Chinese localization team's preference on how best to proceed with this.

**Comment by tico88612** [comment]
Thanks to @dipesh-rawat for the reminder.

This PR only updates `api_metadata`. I think it's perfect here.

If you want to translate, I suggest `API reference` translate to `API 参考`

**Comment by windsonsea** [comment]
Please squash your commits into a single one. Refer to: https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

**Comment by tico88612** [comment]
@windsonsea Done.

**Pull request merged**
