### PR TITLE
Update broken github link for Japanese Storage-limit doc.

### PR DESCRIPTION
**Pull request by SaranBalaji90**
Updates broken github link for Japanese doc in content/ja/docs/concepts/storage/storage-limits.md. This is follow up PR from - https://github.com/kubernetes/website/pull/43659

### CODE REVIEW

**Review by aj11anuj — APPROVED** [review]
LGTM, 👍

**Review by t-inu — COMMENTED** [review]
/lgtm

**Review by kakts — APPROVED** [review]
LGTM!

**Comment by nasa9084** [comment]
Thank you!
/approve

**Pull request merged**
