### PR TITLE
Fixed the typo in non - template pod acquisitions

### PR DESCRIPTION
**Pull request by thisisharrsh**
Fixes : #46319

### CODE REVIEW

**Comment by thisisharrsh** [comment]
Deployment preview : https://deploy-preview-46320--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/replicaset/#non-template-pod-acquisitions

**Review by divya-mohan0209 — COMMENTED** [review]
Placing a hold on this PR since the [issue](https://github.com/kubernetes/website/issues/46319#issuecomment-2106536647) and the PR introduce trivial edits that don't improve the quality of the documentation. Request approvers/reviewers to unhold only if sufficient justification has been provided regarding the improvement of quality.
/hold

**Comment by divya-mohan0209** [comment]
Latest update on the issue:

Please refer to [this issue comment](https://github.com/kubernetes/website/issues/46319#issuecomment-2121611488). The issue suggests a trivial edit and several other subjective edits that don't significantly improve the quality of the Kubernetes documentation, IMO. 

Note to other **wranglers and approvers**: If you feel that there is a significant change in the readability/quality of documentation, please feel free to go ahead and remove the hold on the PR + accept the triage on the issue.

**Comment by sftim** [comment]
/close

Issue is closed. However, we'd welcome a start-to-finish editorial review (as in, read through the Markdown source and propose fixes) of the existing content about ReplicaSet.

**Pull request closed without merging**
