### PR TITLE
[zh]update file content/zh/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

### PR DESCRIPTION
**Pull request by kinzhi**

### CODE REVIEW

**Comment by tengqm** [comment]
Why this change?

**Comment by tengqm** [comment]
The English version is still there.
https://github.com/kubernetes/website/blob/main/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

**Comment by kinzhi** [comment]
https://github.com/kubernetes/website/pull/33045
https://github.com/kubernetes/website/pull/32941

There was an inappropriate change in the PR, so it was restored. This change was made to synchronize the Dockershim prompt with the English page

**Pull request merged**
