### PR TITLE
WIP: Windows doc set for v1.13 stable

### PR DESCRIPTION
**Pull request by PatrickLang**
Windows Server support is proposed as a stable feature (https://github.com/kubernetes/enhancements/issues/116) for v1.13.

This is a documentation overhaul that will include typical steps and use-case based examples for both application developers and cluster operators. The old content was moved into another file, and most of that will be removed to link to existing cluster setup steps instead.

/milestone 1.13
/hold

### CODE REVIEW

**Comment by tfogo** [comment]
Pushed to 1.14
/assign @jimangel

**Comment by tfogo** [comment]
Changed base to master so it doesn't clutter my base:dev-1.13 searched

**Comment by bgrant0607** [comment]
It looks like maybe other changes were accidentally pulled into this.

@PatrickLang Do you plan to update this PR or just create a new one?

**Comment by bgrant0607** [comment]
@PatrickLang I'm not sure what the current process is, but believe it's documented here:
https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/README.md

I suggest asking on the SIG Docs slack channel or mailing list.

**Comment by jimangel** [comment]
> @bgrant0607 @spiffxp - how does the release team track doc completion? We should follow whatever that process is for v1.14

@PatrickLang I have updated docs deadlines in [k/sig-release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14). Essentially you will need to rebase this against dev-1.14 unless you want to scrap it in favor of another PR. Let me know if I can help! Thanks!

**Comment by PatrickLang** [comment]
/close
Craig has an updated outline and is working with the SIG to get the content finished. https://github.com/kubernetes/website/issues/12426 is the new tracking issue

**Pull request closed without merging**
