### PR TITLE
Update cluster-intro.html: Fix Chinese typo

### PR DESCRIPTION
**Pull request by pplmx**
群集==>集群

### CODE REVIEW

**Comment by xichengliudui** [comment]
good job
but you need to sign the  cncf CLA in order to merge

**Comment by purplemysticx** [comment]
> but you need to sign the cncf CLA in order to merge
@xichengliudui 

Sorry, What's that? How can I do it?

**Comment by purplemysticx** [comment]
I have registered for CLA. After that, how to re-trigger the CLA-check job?

**Comment by tanjunchen** [comment]
I signed it
/retest
/check-cla

**Review by tanjunchen — COMMENTED** [review]
pls comment
```
I signed it
/retest
/check-cla
```

**Comment by purplemysticx** [comment]
I signed it
/retest
/check-cla

**Comment by tanjunchen** [comment]
I signed it
/retest
/check-cla

**Comment by tengqm** [comment]
@pplmx pls try recreate a PR with your email account used for CLA.
This one is not working.
/close

**Pull request closed without merging**
