### PR TITLE
[doc] Fixing the mistakes url

### PR DESCRIPTION
**Pull request by kunzhijia**
底部链接跳转修复，修复之前跳转到英文文档，体验不是很好

### CODE REVIEW

**Comment by kunzhijia** [comment]
I signed it

**Comment by kunzhijia** [comment]
I signed it

**Comment by RA489** [comment]
> I signed it

do you mind verifying that the e-mail address you have on GitHub matches the one you signed the CLA with?

**Comment by kunzhijia** [comment]
I signed it

**Comment by kunzhijia** [comment]
ping @chenrui333 @xichengliudui

**Comment by kunzhijia** [comment]
> > I signed it
> 
> do you mind verifying that the e-mail address you have on GitHub matches the one you signed the CLA with?

Thanks

**Comment by tengqm** [comment]
/lgtm
/approve
Though this is not the best solution.

**Comment by kunzhijia** [comment]
> Though this is not the best solution.

Could you please to show me your idea if you like?

**Comment by tengqm** [comment]
@Dbraum Currently we require docs to adding the `<lang>` prefix to intra-site links, for all localization pages. This is not scalable. We need to figure out a way how this can be done transparently.

**Pull request merged**
