### PR TITLE
Reword pod priority premption

### PR DESCRIPTION
**Pull request by jdrinane**
The way I read the paragraph and the header the header is off. This attempts to reword header to match the paragraph.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/28063#issuecomment-845298696

**Comment by jimangel** [comment]
Hey there! @jdrinane, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
I'm closing this due to CLA issue open for too long. Please feel free to reopen when the agreement is signed.
/close

**Pull request closed without merging**
