### PR TITLE
[ja] Update concepts/cluster-administration/networking.md

### LINKED ISSUE #33000: [ja] `concepts/cluster-administration/networking` might be outdated
**This is a Bug Report**

**Problem:**
The file `content/ja/docs/concepts/cluster-administration/networking.md` might be outdated.

Currently in [upstream (en)](https://kubernetes.io/docs/concepts/cluster-administration/networking/),
- there is no "Romana" section.
  It was removed by the PR #30758.
- there is no section relevant to "AOS from Apstra".
- there is no section relevant to "Big Cloud Fabric from Big Switch Networks".
- there is no section relevant to "Google Compute Engine (GCE)".
- there is no section relevant to "Nuage Networks VCS (Virtualized Cloud Services)".

---

- Also see: #32916

**Proposed Solution:**
Update `content/ja/docs/concepts/cluster-administration/networking.md`.

**Page to Update:**
https://kubernetes.io/ja/docs/concepts/cluster-administration/networking/

/language ja

### PR DESCRIPTION
**Pull request by t-inu**
fixes #33000

Ref: https://github.com/kubernetes/website/pull/35754
Also update addons.md accordance with the above PR.
Add IDs to all headings because they may be linked from other pages in the future.
I verified that adding these IDs don't affect links on existing pages.

Preview:
https://deploy-preview-35051--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/cluster-administration/networking/
https://deploy-preview-35051--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/cluster-administration/addons/
en:
https://kubernetes.io/docs/concepts/cluster-administration/networking/
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/cluster-administration/networking.md
https://kubernetes.io/docs/concepts/cluster-administration/addons/
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/cluster-administration/addons.md

### CODE REVIEW

**Comment by atoato88** [comment]
FYI:
PR #35754 which might be big change to a original EN page is created just yesterday.
I think it's better to keep an eye on that PR. :thinking:

**Comment by t-inu** [comment]
@atoato88 Thank you for the information.
As you said, I'd like to focus on what will be updated.

**Comment by atoato88** [comment]
That PR made progress. More bigger changes may be going to come, but it's easy way to update, I think.
Because which will eliminate the list and create link to other page.
In any case, It's needed to focus on that. :grin:

**Comment by atoato88** [comment]
Finally, PR #35754 was merged.
We can go. :wink:

**Comment by t-inu** [comment]
/retitle [ja] Update concepts/cluster-administration/networking.md

**Comment by atoato88** [comment]
/lgtm
Thank you for updating!

**Comment by t-inu** [comment]
I resolved the conflict.
After rebased, this URL 
```[ネットワーク設計ドキュメント](https://git.k8s.io/community/contributors/design-proposals/network/networking.md)```
changed to 
```[ネットワーク設計ドキュメント](https://git.k8s.io/design-proposals-archive/network/networking.md)```
This change is the same to my updating, so need not to fix anything.

**Pull request merged**
