### PR TITLE
improve format for bootstrap-tokens certificate-signing-requests

### PR DESCRIPTION
**Pull request by my-git9**
Optimize document format:
- Adjust line breaks appropriately
- Remove excess spaces

### CODE REVIEW

**Comment by katcosgrove** [comment]
Thanks for the cleanup!

/lgtm

**Comment by T-Lakshmi** [comment]
@my-git9,
This PR needs a rebase to include the latest changes.
Please rebase the PR.

**Comment by T-Lakshmi** [comment]
@my-git9,

Thanks for the cleanup,
/lgtm

**Comment by T-Lakshmi** [comment]
**Preview pages:**

[Authenticating with Bootstrap Tokens](https://deploy-preview-46544--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/bootstrap-tokens/)
[Certificates and Certificate Signing Requests](https://deploy-preview-46544--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/certificate-signing-requests/)

**Pull request merged**
