### PR TITLE
[WIP] Accessibility checker

### PR DESCRIPTION
**Pull request by lucperkins**

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@lucperkins Thank you so much for the PR.

https://deploy-preview-14218--kubernetes-io-master-staging.netlify.com/accessibility/ looks amazing!!!!

/lgtm

@zacharysarah  could you please take a look and state your approval.

**Comment by lucperkins** [comment]
@Rajakavitha1 Hmmm. For some reason the JS library is now working but it’s not properly reporting the errors (you’ll see that zero errors are reported). I’ll investigate tomorrow.

/hold

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1 Hmmm. For some reason the JS library is now working but it’s not properly reporting the errors (you’ll see that zero errors are reported). I’ll investigate tomorrow.
> 
> /hold

:) Yes, the dependencies can sometimes be unpredictable.  I am happy with the page. It looks really nice and the report is neat.

**Comment by zacharysarah** [comment]
@lucperkins 👋 Please feel free to reopen this when you're ready to continue.

/close

**Pull request closed without merging**
