### PR TITLE
kubeadm: update notes for joining with discovery file

### PR DESCRIPTION
**Pull request by neolit123**
adjusts wording for k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

fixes https://github.com/kubernetes/website/issues/16538

/sig cluster-lifecycle
/priority backlog
cc @fabriziopandini @arianvp @sftim

### CODE REVIEW

**Comment by neolit123** [comment]
/assign @fabriziopandini 
for tech-LGTM

**Comment by neolit123** [comment]
/assign @stewart-yu 
for approval.

**Comment by fabriziopandini** [comment]
Thanks @neolit123 for adding those clarifications
/approve
/lgtm

**Pull request merged**
