### PR TITLE
minikube 1.31 fix for generator to avoid issue

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
with no generator pod was not created

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
I signed it

**Comment by dzmitry-lahoda** [comment]
sorry, i am overwhelmed. i have no rights to add labels or assign somebody. i have signed CLA so. i am in read throughout k8s docs and learn. i hope to send more useful updates to make entrance intko k8s as simple as possible with no error message and deprecation warnings.

**Comment by zacharysarah** [comment]
@dzmitry-lahoda 👋 Welcome to Kubernetes. Sorry you've had a difficult time with your first PR!

Thanks for signing the CLA. It looks like this PR now has merge conflicts that need to be resolved in order to proceed.

**Comment by aimeeu** [comment]
Hi @dzmitry-lahoda - thanks for your pull request! The reason you are seeing a merge conflict is because line 56 was changed 14 days ago (see PR #16533 ). The `run` command was replaced with the `deployment` command. So I'm going to close this PR. Please don't be discouraged. We would be happy to help you with future pull requests. Contact us on the [Kubernetes slack](http://slack.k8s.io/) #sig-docs channel if you have questions or need assistance.

/close

**Pull request closed without merging**
