### PR TITLE
Update kubeadm config reference for 1.21

### PR DESCRIPTION
**Pull request by tengqm**
The `v1beta3` version is a 1.22 thing, not 1.21 (main). This PR replaces the `v1beta3` version by `v1beta2`. A follow up PR will add the `v1beta3` to the `dev-1.22` branch.

### CODE REVIEW

**Comment by sftim** [comment]
@tengqm this sounds like a bug fix where we've documented something too early, and now need to revert that to match the behavior of the current Kubertnetes release?

I wasn't sure from the PR description.

**Comment by sftim** [comment]
Looks related to #28872 
/sig cluster-lifecycle

**Comment by tengqm** [comment]
@sftim Yes, it is a bug fix. The file was committed to the wrong branch previously.

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Pull request merged**
