### PR TITLE
Fix dead link of api-conventions doc

### PR DESCRIPTION
**Pull request by KoyamaSohei**
I replaced all https://git.k8s.io/community/contributors/devel/api-conventions.md in this repo with https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md.

### CODE REVIEW

**Comment by KoyamaSohei** [comment]
Sorry, I made an incorrect command...

**Comment by makocchi-git** [comment]
@KoyamaSohei Thank you for your PR!
First, please sign CLA.
2nd, please split this PR by each language(lang/ja, fr, zh) because each page has different owners.

**Comment by KoyamaSohei** [comment]
I signed it

**Comment by KoyamaSohei** [comment]
@makocchi-git 
Thanks for response! 
I'll split PR and reopen it.

**Pull request closed without merging**
