### PR TITLE
[ja] Localize “Good practices for Kubernetes Secrets” to Japanese

### PR DESCRIPTION
**Pull request by bezalel-7**
Hello!

issue: https://github.com/kubernetes/website/issues/42450
This pull request addresses issue https://github.com/kubernetes/website/issues/42450. It adds the translated content of the secrets-good-practices.md document from English to Japanese.

The purpose of this change is to make the Kubernetes documentation more accessible to Japanese-speaking users by providing a translated version of the "Kubernetes Secretsの適切な使用方法" document.

Thank you for reviewing this pull request!

### CODE REVIEW

**Comment by bezalel-7** [comment]
/retitle Localize “Good practices for Kubernetes Secrets” to Japanese

**Comment by bezalel-7** [comment]
@atoato88  this is the new pr with changes done only in ja section

**Review by Arhell — COMMENTED** [review]
/assign @nasa9084

**Review by t-inu — COMMENTED** [review]
Good translation!
Please refer to [翻訳スタイルガイド](https://kubernetes.io/ja/docs/contribute/localization/#%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89) for notation guidelines.

**Comment by atoato88** [comment]
/lgtm

For other reviewers, here is the updated page on the deploy preview site:
- https://deploy-preview-42730--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/security/secrets-good-practices/

**Comment by bezalel-7** [comment]
@Arhell can you review it

**Comment by Arhell** [comment]
> @Arhell can you review it

Hello, unfortunately I can’t, here is someone who can.
https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES#L107

**Comment by bezalel-7** [comment]
@nasa9084 can you please check this change out

**Pull request merged**
