### PR TITLE
Fixed typo.

### PR DESCRIPTION
**Pull request by devarsh10**
Added "in" in codeblocks explanation section.
You can create code blocks "in" two different ways...

### CODE REVIEW

**Comment by reylejano** [comment]
A few things:

- This is a trivial edit, please look at our policy on trivial edits
https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits

    If you find one grammatical or spelling error, it is likely there are more in that file, you can really make your Pull Request count by checking the formatting, checking for broken links, and fixing errors and then submitting all the fixes at once to that file.

  - Some questions to consider:
    - Can the file be improved further?
    - Does the trivial edit greatly improve the quality of the content?

- I believe the original sentence is accurate and more concise than the proposed change in this PR

**Comment by devarsh10** [comment]
> A few things:
> 
> * This is a trivial edit, please look at our policy on trivial edits
>   https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits
> 
> > If you find one grammatical or spelling error, it is likely there are more in that file, you can really make your Pull Request count by checking the formatting, checking for broken links, and fixing errors and then submitting all the fixes at once to that file.
> > Some questions to consider:
> > Can the file be improved further?
> > Does the trivial edit greatly improve the quality of the content?
> 
> * I believe the original sentence is accurate and more concise than the proposed change in this PR

Okay.
If accurate, great.

Regards.

**Comment by bradtopol** [comment]
Assigning @reylejano since he is already engaged on this
/assign @reylejano

**Comment by natalisucks** [comment]
@devarsh10 Given Rey's feedback, I'll be closing this PR. We definitely recommend addressing our [Trivial Edits guide](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) when making contributions so that better value is delivered to readers. A big thanks for contributing and we look forward to more 🚀 

/close

**Pull request closed without merging**
