### PR TITLE
cluster-myfirst.html

### PR DESCRIPTION
**Pull request by fauwazalijdpro**
creating new cluster

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.13-ko.<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Thanks for the PR @fauwazalijdpro !!!!
Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

**Comment by zparnold** [comment]
Hey there! @fauwazalijdpro, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Bradamant3** [comment]
/close

@fauwazalijdpro Thanks for your PR, but we need you to take a few additional steps. if you want to re-open it, or start a new one, please first sign the CLA. It's also not clear why the proposed change is needed. It's true that the topic is pretty generic, but it does also address Minikube specifically and if the issue is the tangle around starting the interactive tutorial vs starting with Minikube, changing the title only does not clear up any confusion.

**Pull request closed without merging**
