### PR TITLE
working with objects and owner and dependents Hindi file created 

### PR DESCRIPTION
**Pull request by kelvinparmar**
In this PR 

Working with objects and Owners and dependents Hindi version files created

### CODE REVIEW

**Comment by kelvinparmar** [comment]
@Babapool help me to get id for this pr when i am sign in to CLA it will redirect me to my old PR and i am not getting my new id for this PR

**Comment by aj11anuj** [comment]
Its because the email-id you are using to sign CLA, is already CLA signed. The problem maybe lies in your git, try to create a GPG key and connect it to your git and github. (Follow github's documentation for doing so)

**Comment by kelvinparmar** [comment]
> Its because the email-id you are using to sign CLA, is already CLA signed. The problem maybe lies in your git, try to create a GPG key and connect it to your git and github. (Follow github's documentation for doing so)

what is GPG key

**Comment by aj11anuj** [comment]
> > Its because the email-id you are using to sign CLA, is already CLA signed. The problem maybe lies in your git, try to create a GPG key and connect it to your git and github. (Follow github's documentation for doing so)
> 
> what is GPG key

You can read about it, and enable it using this [docs](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**Comment by kelvinparmar** [comment]
> > > Its because the email-id you are using to sign CLA, is already CLA signed. The problem maybe lies in your git, try to create a GPG key and connect it to your git and github. (Follow github's documentation for doing so)
> > 
> > 
> > what is GPG key
> 
> You can read about it, and enable it using this [docs](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

I am facing an error while adding new GPG key to github account

**Comment by aj11anuj** [comment]
You don't have to just cut paste gpg key, but you have to cut paste this whole below thing to github

`*********Your GPG key starts from here`
`kskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjvkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgj`
`Your GPG key ends here********`

Including this text `********Your GPG key starts from here` and `Your GPG key ends here*******`

**Comment by kelvinparmar** [comment]
> You don't have to just cut paste gpg key, but you have to cut paste this whole below thing to github
> 
> `*********Your GPG key starts from here` `kskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjvkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgj` `Your GPG key ends here********`
> 
> Including this text `********Your GPG key starts from here` and `Your GPG key ends here*******`

Ohk

**Comment by kelvinparmar** [comment]
> You don't have to just cut paste gpg key, but you have to cut paste this whole below thing to github
> 
> `*********Your GPG key starts from here` `kskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgjvkskdfvfjkvjkjhckvinbhgiuygkhhyhhgkjjjbvbkljvgj` `Your GPG key ends here********`
> 
> Including this text `********Your GPG key starts from here` and `Your GPG key ends here*******`

Now GPG key is created then what i have to do for this PR?

**Comment by aj11anuj** [comment]
Did you linked your GPG key to your git too, after its creation?

**Comment by kelvinparmar** [comment]
> Did you linked your GPG key to your git too, after its creation?

How to do in git?

**Comment by aj11anuj** [comment]
Follow the documentation

**Comment by kelvinparmar** [comment]
> Follow the documentation

Yes It's completed

**Comment by aj11anuj** [comment]
`git pull`
- Make some changes to the files you are commiting here

`git add .`
- If it showed some kind of warning then again repeat this cmd

`git commit -S -m "Commit_message"`
- It will now ask for your GPG password, that you setted while it's creation

Squash your commits if possible and then
`git push --force-with-lease branch_name`

**Comment by aj11anuj** [comment]
Consider retitling this PR as something like

`[hi] Localized 2 files in docs/concepts/overview/`

**Comment by kelvinparmar** [comment]
> Consider retitling this PR as something like
> 
> `[hi] Localized 2 files in docs/concepts/overview/`

Ok will update this tonight

**Comment by kelvinparmar** [comment]
> Consider retitling this PR as something like
> 
> `[hi] Localized 2 files in docs/concepts/overview/`

Hey @aj11anuj CLA login is not required now?

**Comment by aj11anuj** [comment]
It's required, is your email id verified?

**Comment by aj11anuj** [comment]
Go to your github a/c settings, there you will see an email tab... from their you can verify your email address

**Comment by kelvinparmar** [comment]
> Go to your github a/c settings, there you will see an email tab... from their you can verify your email address

yeah it's already verified

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by kelvinparmar** [comment]
> /easycla

What is the problem now?

**Comment by ydFu** [comment]
@kelvinparmar ,thank you for your contribution.

You must sign the CLA for teams of kubernetes/website to do code reiview.

Please click on the red button `NOT COVERED` line in the first comment.

If you don't know how to do it, here is[the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Comment by kelvinparmar** [comment]
> @kelvinparmar ,thank you for your contribution.
> 
> You must sign the CLA for teams of kubernetes/website to do code reiview.
> 
> Please click on the red button `NOT COVERED` line in the first comment.
> 
> If you don't know how to do it, here is[the CLA tutorial](https://git.k8s.io/community/CLA.md).

I hvae already done but it redirect me to my previous PR where its shows me COVERD

**Comment by aj11anuj** [comment]
Ahm.. see, there is a problem with your account that's why GitHub and bot is not able to track your commit I'd and CLA status. Try out these 3 things to troubleshoot it:-

1. Go to settings of your GitHub a/c and from there fill all account related required details, and remove your old email id from there, make a new email id and put it on GitHub as primary email id and make it verified. Then come back to this PR and click on sign CLA, this time while filling your details and signing CLA, put your new email id there.
2. If this issue still persists then try making a new GitHub a/c and make a new PR and sign CLA. If it worked then migrate your old GitHub a/c to new one from settings.
3. Additionally, try using these steps with a different device.

**Comment by divya-mohan0209** [comment]
Hello @kelvinparmar , thank you for your PR. Since it has been ~2 months with no activity on this PR, I will be closing it. Kindly consider working on getting your CLA issues fixed & reopen the PR to resume contributing.
/close

**Pull request closed without merging**
