### PR TITLE
Add RDMA device plugin

### PR DESCRIPTION
**Pull request by hustcat**
Add RDMA device plugin notes.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.10 Features: set Milestone to 1.10 and Base Branch to release-1.10
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by heckj** [comment]
Thanks @hustcat - nice to have another example of a device plugin! If you haven't already, please sign the CLA so that we can accept this change. The instructions for signing the CLA are included above within this PR.

/approve

**Comment by hustcat** [comment]
I'v signed CLA, PTAL @heckj

**Pull request merged**
