### PR TITLE
Fix en typo in secret.md

### PR DESCRIPTION
**Pull request by allevo**
Fix en typo in secret.md

### CODE REVIEW

**Comment by allevo** [comment]
Signed to CLA

**Comment by allevo** [comment]
Rebased

**Comment by jimangel** [comment]
@allevo I'm going to close this PR for now, feel free to open once you get the email situation / CLA resolved.

https://git.k8s.io/community/CLA.md#the-contributor-license-agreement

Let me know if you have any questions!

/close

**Pull request closed without merging**
