### PR TITLE
add generated kubectl docs for 1.10

### PR DESCRIPTION
**Pull request by Bradamant3**
Makes me a little nervous that we can't compare the diff. But I did figure out branching issues, so will go fix up #7842 

/assign @zacharysarah 
/assign @steveperry-53 

/hold

Adding hold bc I'd like to discuss a few oddities with generating and copying that I encountered. Probably with Steve.
Also need to check order of operations for merging for release.

### CODE REVIEW

**Comment by zacharysarah** [comment]
I’m curious to learn what you learned, @bradamant3!

**Comment by steveperry-53** [comment]
@Bradamant3, You can diff the intermediate Markdown files. 

Generate the docs for 1.9. Then stash the Markdown files that are here:
/kubernetes-incubator/reference-docs/gen-kubectldocs/generators/includes

Next generate the docs for 1.10. Compare your stashed 1.9 files with the 1.10 files here:
/kubernetes-incubator/reference-docs/gen-kubectldocs/generators/includes

**Comment by Bradamant3** [comment]
Closing unmerged in favor of a new PR that gets the files right without weird history or need to squash.

**Pull request closed without merging**
