### PR TITLE
promote LocalStorageCapacityIsolationFSQuotaMonitoring to beta

### PR DESCRIPTION
**Pull request by pacoxu**
Update due to https://github.com/kubernetes/kubernetes/pull/107329 and https://github.com/kubernetes/enhancements/pull/2697

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Do we also need an update to https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage or to some page within https://kubernetes.io/docs/concepts/storage/?

**Comment by pacoxu** [comment]
There are some descriptions before. 
https://people.wikimedia.org/~jayme/k8s-docs/v1.16/docs/concepts/configuration/manage-compute-resources-container/

> 
> When local ephemeral storage is used, it is monitored on an ongoing basis by the kubelet. The monitoring is performed by scanning each emptyDir volume, log directories, and writable layers on a periodic basis. Starting with Kubernetes 1.15, emptyDir volumes (but not log directories or writable layers) may, at the cluster operator’s option, be managed by use of [project quotas](http://xfs.org/docs/xfsdocs-xml-dev/XFS_User_Guide/tmp/en-US/html/xfs-quotas.html). Project quotas were originally implemented in XFS, and have more recently been ported to ext4fs. Project quotas can be used for both monitoring and enforcement; as of Kubernetes 1.16, they are available as alpha functionality for monitoring only.
> 
> Quotas are faster and more accurate than directory scanning. When a directory is assigned to a project, all files created under a directory are created in that project, and the kernel merely has to keep track of how many blocks are in use by files in that project. If a file is created and deleted, but with an open file descriptor, it continues to consume space. This space will be tracked by the quota, but will not be seen by a directory scan.
> 
> Kubernetes uses project IDs starting from 1048576. The IDs in use are registered in /etc/projects and /etc/projid. If project IDs in this range are used for other purposes on the system, those project IDs must be registered in /etc/projects and /etc/projid to prevent Kubernetes from using them.
> 
> To enable use of project quotas, the cluster operator must do the following:
> 
> Enable the LocalStorageCapacityIsolationFSQuotaMonitoring=true feature gate in the kubelet configuration. This defaults to false in Kubernetes 1.16, so must be explicitly set to true.
> 
> Ensure that the root partition (or optional runtime partition) is built with project quotas enabled. All XFS filesystems support project quotas, but ext4 filesystems must be built specially.
> 
> Ensure that the root partition (or optional runtime partition) is mounted with project quotas enabled.
> 

But I cannot find them in master branch.

**Comment by reylejano** [comment]
@pacoxu @xing-yang 
Please see Tim's [comment](https://github.com/kubernetes/website/pull/35653#pullrequestreview-1060199682)
> Do we also need an update to https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage or to some page within https://kubernetes.io/docs/concepts/storage/?

eod tomorrow, August 9th, is the 1.25 Docs Ready for Review deadline
Please make any documentation updates associated with LocalStorageCapacityIsolationFSQuotaMonitoring to beta by eod tomorrow

**Comment by pacoxu** [comment]
> Do we also need an update to https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage or to some page within https://kubernetes.io/docs/concepts/storage/?

Updated. Thanks.

**Comment by pacoxu** [comment]
@sftim do you have time to take a look again? Thanks.

**Comment by pacoxu** [comment]
Rebased. @reylejano ack.

**Review by Sea-n — COMMENTED** [review]
Checked. And re-apply `lgtm` from [previous comment](https://github.com/kubernetes/website/pull/35653#issuecomment-1216796848).
/lgtm

**Pull request merged**
