### PR TITLE
Improve blog article summaries presentation with author metadata in front matter

### PR DESCRIPTION
**Pull request by dipesh-rawat**
This PR contains changes to incorporate `author` metadata into front matter for improved handling of author details instead of listing authors in the blog content. Utilized Docsy's ([example blog](https://www.docsy.dev/blog/2024/0.9.0/)) native support for `author` metadata to ensure consistency and compatibility.

Fixes https://github.com/kubernetes/website/issues/40175

#### Summary of changes

- Modified the blog content files _(only blogs published in 2024)_ to include the following `author` metadata in front matter.

```yaml
slug: 
title: 
date:
author: >
  Author-Name (Affiliation)
```

- Other examples demonstrating inclusion of authors in blog content:

    - Multiple authors:
    ```yaml
    slug: 
    title: 
    date:
    author: >
      Author-1 (Affiliation),
      Author-2 (Affiliation),
      Author-3 (Affiliation)
   ```
   - Author with hyperlink (use markdown inline link format):
      
    ```yaml
    slug: 
    title: 
    date:
    author: >
      [Team of Writers](<url-to-link>)
   ```
- Modify `layouts/blog/list.html` layout to integrate author name(s) into the [index page](https://deploy-preview-45865--kubernetes-io-main-staging.netlify.app/blog) summary alongside the publication date.   
    

#### Useful Links

[Preview New Blog Summary Page](https://deploy-preview-45865--kubernetes-io-main-staging.netlify.app/blog) | [Current  Blog Summary Page](https://kubernetes.io/blog/)

[Preview Single Author Blog](https://deploy-preview-45865--kubernetes-io-main-staging.netlify.app/blog/2024/04/11/sig-architecture-code-spotlight-2024/) | [Current Single Author Blog](https://kubernetes.io/blog/2024/04/11/sig-architecture-code-spotlight-2024/)

[Preview Multiple Author Blog](https://deploy-preview-45865--kubernetes-io-main-staging.netlify.app/blog/2024/04/03/intro-windows-ops-readiness/) | [Current Multiple Author Blog](https://kubernetes.io/blog/2024/04/03/intro-windows-ops-readiness/)

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/cc @sftim

I would really appreciate your review and feedback regarding the suggested modification to the blog template. Thank you in advance for your time and input!

**Comment by sftim** [comment]
I think this works. If we make this change, ideally we go back and (one off) revise all the older articles too - a script might help there.

**Review by steve-hardman — COMMENTED** [review]
This PR makes the page look really nice at https://deploy-preview-45865--kubernetes-io-main-staging.netlify.app/blog/. The blog page also looks cleaner now. It feels like a fresher and more modern design. 

/lgtm

**Comment by steve-hardman** [comment]
@dipesh-rawat I like thorough explanation you write in the PR description. It greatly helps understanding for me. I'll try to keep in mind for my own contributions.

**Pull request merged**
