### PR TITLE
Corrected the number of selectors in network-policies.md file

### LINKED ISSUE #41354: Improper count of Ingress/Egress NetworkPolicy selectors on the `Network Policies` page
https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors

> There are four kinds of selectors that can be specified in an ingress from section or egress to section.

But only three are listed：

- podSelector
- namespaceSelector
- ipBlock

And Kubernetes explain is also these three.
```
kiosk@k8s-master:~$ k explain networkpolicy.spec.ingress.from
KIND:     NetworkPolicy
VERSION:  networking.k8s.io/v1

RESOURCE: from <[]Object>

DESCRIPTION:
     List of sources which should be able to access the pods selected for this
     rule. Items in this list are combined using a logical OR operation. If this
     field is empty or missing, this rule matches all sources (traffic not
     restricted by source). If this field is present and contains at least one
     item, this rule allows traffic only if the traffic matches at least one
     item in the from list.

     NetworkPolicyPeer describes a peer to allow traffic to/from. Only certain
     combinations of fields are allowed

FIELDS:
   ipBlock      <Object>
     IPBlock defines policy on a particular IPBlock. If this field is set then
     neither of the other fields can be.

   namespaceSelector    <Object>
     Selects Namespaces using cluster-scoped labels. This field follows standard
     label selector semantics; if present but empty, it selects all namespaces.

     If PodSelector is also set, then the NetworkPolicyPeer as a whole selects
     the Pods matching PodSelector in the Namespaces selected by
     NamespaceSelector. Otherwise it selects all Pods in the Namespaces selected
     by NamespaceSelector.

   podSelector  <Object>
     This is a label selector which selects Pods. This field follows standard
     label selector semantics; if present but empty, it selects all pods.

     If NamespaceSelector is also set, then the NetworkPolicyPeer as a whole
     selects the Pods matching PodSelector in the Namespaces selected by
     NamespaceSelector. Otherwise it selects the Pods matching PodSelector in
     the policy's own Namespace.

kiosk@k8s-master:~$ 
```
What's the fourth one?

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
fixes #41354 

This PR corrects Improper count of Ingress/Egress NetworkPolicy selectors on the Network Policies page

### CODE REVIEW

**Comment by sambhavgupta0705** [comment]
Preview

**Comment by tengqm** [comment]
Actually, there are four of them mentioned in the same subsection.
Please reread.

**Comment by sambhavgupta0705** [comment]
So we need to change it there also or something else?

**Comment by utkarsh-singh1** [comment]
Hi @sambhavgupta0705, reread below section as it mention four kinds- 

. podSelector 
. namespaceSelector
. podSelector and namespaceSelector
. ipblock

**Comment by sambhavgupta0705** [comment]
Ok @utkarsh-singh1 then I should close this PR

**Comment by utkarsh-singh1** [comment]
Yeah @sambhavgupta0705

**Pull request closed without merging**
