### PR TITLE
adding pt-br translation for Turnkey Cloud Solutions

### PR DESCRIPTION
**Pull request by Sampaiolc**

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Previews:
- https://deploy-preview-32728--kubernetes-io-main-staging.netlify.app/pt-br/docs/setup/best-practices/node-conformance/
- https://deploy-preview-32728--kubernetes-io-main-staging.netlify.app/pt-br/docs/setup/production-environment/turnkey-solutions/

**Comment by Sampaiolc** [comment]
Sorry, I open this PR with only one commit.

I change only file: content/pt-br/docs/setup/production-environment/turnkey-solutions.md

Other file I will using in next PR.

**Review by Arhell — COMMENTED** [review]
/assign @edsoncelio

**Comment by edsoncelio** [comment]
Hi @Sampaiolc, first of all, thanks for your contribution! 
Could you remove the second file that's not part of this PR? 
This one `content/pt-br/docs/setup/best-practices/node-conformance.md`

After that, I can review the PR :D

**Comment by Sampaiolc** [comment]
> Hi @Sampaiolc, first of all, thanks for your contribution! Could you remove the second file that's not part of this PR? This one `content/pt-br/docs/setup/best-practices/node-conformance.md`
> 
> After that, I can review the PR :D

Okay @edsoncelio, I removed it.

Could you check if everything is correct now?

**Comment by edsoncelio** [comment]
> > Hi @Sampaiolc, first of all, thanks for your contribution! Could you remove the second file that's not part of this PR? This one `content/pt-br/docs/setup/best-practices/node-conformance.md`
> > After that, I can review the PR :D
> 
> Okay @edsoncelio, I removed it.
> 
> Could you check if everything is correct now?

Great @Sampaiolc! Looks good now :D
/lgtm

**Pull request merged**
