### PR TITLE
Fix Broken link for storageClass on configure-persistent-volume-storage page

### PR DESCRIPTION
**Pull request by akankshakumari393**
Fixes - #36819

### CODE REVIEW

**Comment by mtardy** [comment]
Thanks a lot for taking the time to create this PR, and I'm sorry, but related to the comment I made here https://github.com/kubernetes/website/issues/36819#issuecomment-1247747442, we will hold this PR for now.

/hold

**Comment by mtardy** [comment]
My bad I was wrong in the comment above.
/unhold

You might want to point to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#storageclass-v1-storage-k8s-io maybe!

**Comment by akankshakumari393** [comment]
Thanks for taking a look. I have updated the PR with correct link.

**Pull request merged**
