### PR TITLE
[zh] remove misleading instructions in kubeadm setup docs

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/25775

### CODE REVIEW

**Comment by tengqm** [comment]
Looks like there are other changes that need a sync.

**Comment by Arhell** [comment]
@tengqm 
but you can make a merge and then someone from your colleagues will be able to sync the changes, because for the most part I can only help with examples from other PR or close this?

**Comment by tengqm** [comment]
#27100 is a complete sync

**Pull request closed without merging**
