### PR TITLE
Update in docs/setup/learning-environment/_index.md

### PR DESCRIPTION
**Pull request by vaibhav2107**
Ref: #28446

### CODE REVIEW

**Comment by jihoon-seo** [comment]
CC: @sftim

PTAL! 😊

**Comment by nate-double-u** [comment]
/lgtm

This looks like it solves the issue, and doesn't interfere with the redirect (https://deploy-preview-28451--kubernetes-io-main-staging.netlify.app/docs/setup/learning-environment)

**Comment by sftim** [comment]
I'm not sure what this is solving, but I don't object either.

/lgtm

**Comment by sftim** [comment]
/approve
even

**Pull request merged**
