### PR TITLE
correct container hyperlinks in init container

### PR DESCRIPTION
**Pull request by ethan-daocloud**
I copy the link for en version, and tested, this link can work.

### CODE REVIEW

**Comment by ethan-daocloud** [comment]
@chenrui333 thanks, i get it. 
I will issue an new pr for this change from that base.
btw, how i get the current working branch info? I won't miss it in the future.

**Comment by idealhack** [comment]
Sorry for the wrong link, please squash your changes per `content/zh/docs/concepts/workloads/pods/init-containers.md` here.

/reopen

**Comment by ethan-daocloud** [comment]
@idealhack thanks for your kind help, i merge the changes in this pr.
Thanks!!!

**Comment by tengqm** [comment]
should we rebase this onto release-1.12?

**Comment by chenrui333** [comment]
@tengqm I dont have permission to do it, can you do that?

**Comment by chenrui333** [comment]
ping @tengqm

**Comment by chenrui333** [comment]
ping @tengqm

**Pull request merged**
