### PR TITLE
Create kubeadm-windows.md

### PR DESCRIPTION
**Pull request by grcusanz**
This is a placeholder for the doc that will describe specifics on how to use kubeadm with windows worker nodes.

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Remember to delete this note before submitting your pull request.
>
> For pull requests on 1.15 Features: set Milestone to 1.15 and Base Branch to dev-1.15
> 
> For pull requests on Chinese localization, set Base Branch to release-1.14
>
> For pull requests on Korean Localization: set Base Branch to dev-1.14-ko.\<latest team milestone>
>
> If you need Help on editing and submitting pull requests, visit:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> If you need Help on choosing which branch to use, visit:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by neolit123** [comment]
/hold
hi, grcusanz thanks for the PR.
please change the file location to be under:
https://kubernetes.io/docs/setup/windows/

thanks.

/sig cluster-lifecycle
xref https://github.com/kubernetes/kubeadm/issues/1393

**Comment by michmike** [comment]
@grcusanz thanks for starting this
@neolit123 , the right place for this doc is under the kubeadm section of the docs since that's where we expect users to look for it. we can link to the doc from the \setup\windows section, but this doc should live with kubeadm. my 2 cents

**Comment by neolit123** [comment]
given the new docs will include mostly Windows PowerShell instructions, i'm inclined to recommend https://kubernetes.io/docs/setup/windows/ as the location and we can possibly link from the official kubeadm pages if the feature graduates to alpha.

**Comment by PatrickLang** [comment]
@grcusanz - can you also retarget this to `dev-1.15` not `master`?

**Comment by cody-clark** [comment]
Seconding @PatrickLang. Please point this to the release branch (`dev-1.15`). 

And please sign the CLA.

> 📝 Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

**Comment by jimangel** [comment]
Should this be targeted for dev-1.15?
/cc @makoscafee

**Comment by makoscafee** [comment]
Hi, @grcusanz you need help for anything to help speed up this work? We are looking to have all PR for release 1.15 merged by June 10th. Let me know if there is anything docs team can assist on this.

**Comment by neolit123** [comment]
@makoscafee as per the recent discussion on slack
this PR is moved for after v1.15 so the milestone can be removed:
https://kubernetes.slack.com/archives/C13J86Z63/p1560196459047800

**Comment by jimangel** [comment]
> m2  [4 hours ago]
> we won't finish it for 1.15. we can push to after 1.15. thanks @claurence
/close

**Pull request closed without merging**
