### PR TITLE
add Antrea description in dev-1.16

### PR DESCRIPTION
**Pull request by yasensim**
add Antrea description in dev-1.16

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Hi @neolit123 Could you please state your approval on this PR.

**Comment by Rajakavitha1** [comment]
on hold as mentioned in : https://github.com/kubernetes/website/pull/17917
merge is up to sig-docs as per the policy discussion for third party content.
kubernetes/enhancements#1327

**Comment by neolit123** [comment]
@Rajakavitha1 as far as i know k/website does not allow backports to old branches.
this PR is for dev-1.16.

/cc @sftim @jimangel

**Comment by jimangel** [comment]
This got into master and will be in the 1.16 docs when 1.17 is released.
/close

**Pull request closed without merging**
