### PR TITLE
Update component reference for v1.28

### PR DESCRIPTION
**Pull request by tengqm**
This PR updates the component references (except for kubelet) for v1.28.

### CODE REVIEW

**Comment by sftim** [comment]
/approve

Thanks

**Comment by sftim** [comment]
This PR fixes https://github.com/kubernetes/website/issues/42680

**Comment by sftim** [comment]
This PR also fixes issues #42678 and #42679

**Review by nate-double-u — COMMENTED** [review]
Thanks for the update @tengqm!

/lgtm

**Pull request merged**
