### PR TITLE
Update config.toml file as part of 1.18 release.

### PR DESCRIPTION
**Pull request by VineethReddy02**
Updated config.toml file as part of the 1.18 release.

### CODE REVIEW

**Comment by sftim** [comment]
Helps with issue #19841

**Comment by jimangel** [comment]
In the build preview, I do not see 1.18 as an option (dropdown menu).

**Comment by sftim** [comment]
Should have checked more. Following https://github.com/kubernetes/website/pull/19842#issuecomment-604094826
/lgtm cancel

**Comment by kbhawkey** [comment]
I looked at the updated preview (https://deploy-preview-19842--k8s-v1-15.netlify.com/).
I assume the changes to the branch patch numbers are correct?
/lgtm

**Pull request merged**
