### PR TITLE
update md file

### PR DESCRIPTION
**Pull request by kpchen**
Accurate Chinese translation，Graceful ==》优雅

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@kpchen Thank you for your first contribution!

In order to make this PR review-ready, you need to sign the Linux Foundation CLA.

Please refer the comment https://github.com/kubernetes/website/pull/30894#issuecomment-992272796 ! 😊

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by tengqm** [comment]
/close
This one is not conformant to the [Chinese localization guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/)

**Comment by kpchen** [comment]
> /close This one is not conformant to the [Chinese localization guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/)

Seriously？Graceful termination，翻译为“体面终止”？？ hook翻译为回调？？？“回调” 那是callback。   看我的https://kubernetes.io/zh/docs/contribute/localization_zh 修改

**Comment by tengqm** [comment]
@kpchen We are serious about all serious contributions. Period.

**Comment by kpchen** [comment]
good，thanks. please check the new PR for https://kubernetes.io/zh/docs/contribute/localization_zh

**Pull request closed without merging**
