### PR TITLE
Update Some Instances of "i.e." Latin Abbreviation

### PR DESCRIPTION
**Pull request by aallbrig**
[SIG Docs recommends avoiding Latin phrases](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-latin-phrases). "i.e.." is a latin abbreviation.

Instances of "i.e." have been considered for update, but not all instances have been updated. This is a best effort attempt to apply the guideline. As @sftim has pointed out -- these guidelines are just guidelines! Feel free to push back on any updates :)

### CODE REVIEW

**Comment by aallbrig** [comment]
> In general, mechanized changes are only acceptable with human review.
You're absolutely right. I may have gone a little overboard with making this set of changes. I need to take a step back and look closely at these changes. I've updated the PR title with `[WIP]` so I can more closely review each change.

> @aallbrig it is also OK to leave in a few cases of “i.e.” or “ie.”; the SIG Docs guidelines are just that: guidelines.
I'll try my best at making these calls.

**Comment by aallbrig** [comment]
@sftim I feel good about this change set now. Please review again, once you can!

**Comment by sftim** [comment]
@aallbrig, do you know how to rebase this pull request?

**Comment by aallbrig** [comment]
@sftim I do!

**Comment by aallbrig** [comment]
@sftim Hey! I'm sorry -- we had an emergency fire fighting, all hands on deck type of situation. I've rebased this PR. Please review, when you can!

This PR has been rebased and is ready for merge consideration.

**Pull request merged**
