### PR TITLE
add necessary heading id

### PR DESCRIPTION
**Pull request by lostsquirrel**
add necessary heading id  referenced in this page

### CODE REVIEW

**Comment by lostsquirrel** [comment]
I signed it

**Comment by lostsquirrel** [comment]
I signed it

**Comment by lostsquirrel** [comment]
I signed it

**Comment by kbhawkey** [comment]
Hi @lostsquirrel .
The heading anchors should be automatically created. I am not sure whether these changes are required.
Is a link anchor text displaying when you hover near the heading on the page?

**Comment by lostsquirrel** [comment]
sorry, my fault, I'll close this

**Pull request closed without merging**
