### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by HaroldTemple**

### CODE REVIEW

**Comment by jimangel** [comment]
@HaroldTemple thanks for the PR. Please sign the CLA by following the instructions here: https://github.com/kubernetes/website/pull/20846#issuecomment-625965896

Let me know if you have any questions! Thanks!

**Comment by raelga** [comment]
Hello @HaroldTemple, 

Thanks for the PR! Have you been able to review the CLA?

Feel free to reach me out if you have any issue with completing the process!

**Comment by zparnold** [comment]
@HaroldTemple thanks for your contribution! 🎉 We really would love to have it, unfortunately to continue we need to have your (or your company's) signature on a CLA! For now I'm going to close this, but fret not! You can re-open whenever you have a chance. Thanks!
/close

**Comment by raelga** [comment]
@HaroldTemple I just created a new PR https://github.com/kubernetes/website/pull/22238 to apply your fix, but let me know if you have any issue with the CLA for your next contribution!

**Pull request closed without merging**
