### PR TITLE
[hi] Update the Build link in README file

### PR DESCRIPTION
**Pull request by vaibhav2107**
Updated the Build link in the README-hi.md file to align with the main [README.md](https://github.com/kubernetes/website/blob/main/README.md) file

Also a ref issue #41241 was opened regarding this

### CODE REVIEW

**Comment by vaibhav2107** [comment]
Hi @sftim @nate-double-u 
Could you please have a look into it

**Comment by dipesh-rawat** [comment]
/retitle [hi] Update the Build link in README file

**Comment by vaibhav2107** [comment]
Thanks @stmcginnis

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks!
/approve

**Pull request merged**
