### PR TITLE
Updated cluster-intro.html for clarity/verbiage

### PR DESCRIPTION
**Pull request by Intelrunner**
Adjusted wording for clarity and reduced redundant language.

### CODE REVIEW

**Comment by Intelrunner** [comment]
Commenting for repull.

**Comment by Intelrunner** [comment]
Signed up for CLA.

**Comment by Intelrunner** [comment]
Actually signed the CLA this time. SOrry about that.

**Review by celestehorgan — COMMENTED** [review]
Hi @Intelrunner!

Once again, the original grammar is correct in this instance. :)

I apologize for having to close this PR as well, as we are _very_ excited for all new contributors.

**Pull request closed without merging**
