### PR TITLE
Ready announcements for Docsy

### PR DESCRIPTION
**Pull request by sftim**
Change how we support dismissable announcement banners.

Serve the JavaScript code using Hugo Pipes; avoid customizing the `head.html` partial.

Here's a [preview](https://deploy-preview-48561--kubernetes-io-main-staging.netlify.app/)

Helps with issue #41171

/area web-development

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!

/lgtm

**Comment by nate-double-u** [comment]
Thanks for this. I agree, this brings things more in line with what upstream Docsy is recommending.

/approve

**Comment by nate-double-u** [comment]
Additional lgtm:

/lgtm

**Pull request merged**
