### PR TITLE
[zh] fix Autoscaling external metrics

### PR DESCRIPTION
**Pull request by eudore**
"use the External metric type instead of Object" is ambiguous, Should `Object` be changed to `Pods`.

The `Object` type describes object information, but `External` does not support it. It should be modified from the `Pods` type that defines the same as `External`.

This problem is also described in other language versions.

```golang
type ObjectMetricSource struct {
	DescribedObject CrossVersionObjectReference struct {
		Kind string `json:"kind" protobuf:"bytes,1,opt,name=kind"`
		Name string `json:"name" protobuf:"bytes,2,opt,name=name"`
		APIVersion string `json:"apiVersion,omitempty" protobuf:"bytes,3,opt,name=apiVersion"`
	} `json:"describedObject" protobuf:"bytes,1,name=describedObject"`
	Metric MetricIdentifier `json:"metric" protobuf:"bytes,3,name=metric"`
	Target MetricTarget `json:"target" protobuf:"bytes,2,name=target"`
}
type PodsMetricSource struct {
	Metric MetricIdentifier `json:"metric" protobuf:"bytes,1,name=metric"`
	Target MetricTarget `json:"target" protobuf:"bytes,2,name=target"`
}
type ExternalMetricSource struct {
	Metric MetricIdentifier `json:"metric" protobuf:"bytes,1,name=metric"`
	Target MetricTarget `json:"target" protobuf:"bytes,2,name=target"`
}
```

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@eudore  Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.

You can follow the steps documented here: [CLA Steps](https://git.k8s.io/community/CLA.md)

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Comment by tengqm** [comment]
This can be abandoned and resync'ed when the English upstream change is out there.
/close

**Pull request closed without merging**
