### PR TITLE
doc(auth): typo

### PR DESCRIPTION
**Pull request by robstoll**

### CODE REVIEW

**Comment by Arhell** [comment]
@robstoll  you might need to check that the email address you're using in Git matches the email address that you signed the CLA with

**Comment by robstoll** [comment]
@Arhell, thanks for your respond, I have not yet signed the CLA and as I am acting as an employee of a company I need to get the company signed up first.. Feel free to close the PR I can also create a new one once I have the necessary stuff.

**Comment by celestehorgan** [comment]
Hey there! @robstoll, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by robstoll** [comment]
@celestehorgan thanks for your respond, I have not yet signed the CLA and as I am acting as an employee of a company I need to get the company signed up first. Feel free to close the PR I can also create a new one once I have the necessary stuff.

**Pull request closed without merging**
