### PR TITLE
Replace kube with minikube

### PR DESCRIPTION
**Pull request by sotayamashita**

### CODE REVIEW

**Comment by bradtopol** [comment]
@sotayamashita Thank you for your contribution. Please sing the CLA so we can accept your pull request.

**Comment by sotayamashita** [comment]
@bradtopol My commit email is `1587053+sotayamashita@users.noreply.github.com` to keep my email address private and it is not a real email address so I cannot confirm the address on `identity.linuxfoundation.org`. Any idea?

ref: https://help.github.com/articles/about-commit-email-addresses/

**Comment by zacharysarah** [comment]
@sotayamashita I'm not sure how to resolve your concern about privacy and the CLA. @castrojo 👋 Any guidance?

In any case, please feel free to reopen this PR when you've signed the CLA.

**Pull request closed without merging**
