### PR TITLE
doc: fix some typo

### PR DESCRIPTION
**Pull request by halfcrazy**
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7229)

### CODE REVIEW

**Comment by heckj** [comment]
@halfcrazy these are great updates, thank you for taking the time to do this PR! That said, there are some that will be only ephemeral changes as the pages that you're making changes are from generated documentation. Pages where the URI includes `generated` or `imported` are generally ones that have come from an automatic process - usually driven by code elsewhere. All this to let you know that the next time those pages are generated and updated (usually on the quarterly release, but sometimes more frequently) the spelling changes you're proposing there will revert.

There's some docs on how we generate content for these pages:
- https://kubernetes.io/docs/home/contribute/generated-reference/kubernetes-components/
- https://kubernetes.io/docs/home/contribute/generated-reference/kubectl/
- https://kubernetes.io/docs/home/contribute/generated-reference/kubernetes-api/
- https://kubernetes.io/docs/home/contribute/generated-reference/federation-api/

But the long and short is that changes to typo's in there usually need to be hunted down and resolved in the source code from where the documentation is generated.

**Comment by halfcrazy** [comment]
@heckj Good catch, I have sent some pr to kubernetes repo to correct some of those typos in the code comment. https://github.com/kubernetes/kubernetes/pulls/halfcrazy

**Comment by zacharysarah** [comment]
@halfcrazy Please resolve the merge conflicts.

/hold

**Comment by halfcrazy** [comment]
@zacharysarah update.

**Pull request merged**
