### PR TITLE
Fix a command in kubectl cheatsheet

### PR DESCRIPTION
**Pull request by tengqm**
for: #17883

### CODE REVIEW

**Comment by zacharysarah** [comment]
@tengqm I see you used your write permissions to remote the `do-not-merge` label. That's not acceptable. It creates problems in later merge PRs during releases. Specifically, #17958 is failing because this PR and #17889 triggered the `do-not-merge` label.

In the future, please follow the warnings and remove GitHub magic words from your PR titles instead of manually removing warning labels.

**Comment by tengqm** [comment]
@zacharysarah I removed it because I thought it was a bug. However, I'm wondering if just mentioning the related issue number is okay if we cannot use 'fixes', 'closes' etc.

**Comment by zacharysarah** [comment]
You can use keywords in the original description, just not in the PR title or in any commit messages.

**Pull request merged**
