### PR TITLE
Correct OpenStack Cloud Provider Table Layout

### PR DESCRIPTION
**Pull request by xsgordon**
Correct the OpenStack cloud provider table layout to use GitHub
compatiable markdown.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6138)

### CODE REVIEW

**Comment by xsgordon** [comment]
OK, that rendering looks betterer :).

**Comment by bradtopol** [comment]
Looks fantastic!  Thanks!

**Pull request merged**
