### PR TITLE
update search placeholder

### PR DESCRIPTION
**Pull request by Arhell**
issue #21947

### CODE REVIEW

**Comment by Arhell** [comment]
review page https://deploy-preview-21949--kubernetes-io-master-staging.netlify.app/docs/home/
65903be8e2

**Comment by sftim** [comment]
@Arhell can you explain why this is the right fix? I looked at the issue you logged and wasn't sure I understood the symptoms this wants to address.

**Comment by Arhell** [comment]
> @Arhell can you explain why this is the right fix? I looked at the issue you logged and wasn't sure I understood the symptoms this wants to address.

@sftim 
Invalid {{T "*******"}} used, so as not to translate a new placeholder, it is better to use the one that was already and is with the string "search", because it is already ready in all languages

**Comment by sftim** [comment]
That makes sense. Commit 1b5ff98a4473be60d94d35e330d9801640d6f58d introduced `ui_search_placeholder` and that matches its meaning better than the name from #20874

@Arhell thanks for clarifying

/lgtm 
/approve

**Pull request merged**
