### PR TITLE
Merge main branch into dev-1.25

### PR DESCRIPTION
**Pull request by krol3**
Merge main into dev-1.25 to keep in sync - SIG-Release 1.25 Docs team 30/07/22
/cc @kcmartin @cathchu @didicodes @sethmccombs

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey, please avoid using `dd/mm/yy`, `mm/dd/yy`, `yy/mm/dd` or something like that. It's confusing in some cases such as `06/08/22`.

I think it's better to use RFC 3339 (or ISO 8601) format like `2022-07-30`.
And it's git / GitHub, we already have timestamp for every operation, maybe it's not necessary to include time in the PR title.

**Comment by reylejano** [comment]
Clean sync 👍 
/approve

**Comment by Sea-n** [comment]
There is no `dd-mm-yy` format. 😅

/retitle Merge main branch into dev-1.25

**Pull request merged**
