### PR TITLE
Update Kuberbetes Blog URLs

### PR DESCRIPTION
**Pull request by tnir**
Replaces #8279

This PR systematically updates Kuberbetes Blog URLs with new ones by the following commands:

- blog.kubernetes.io => kubernetes.io/blog/
- Kubernetes blog => Kuberentes Blog
- Remove *.html from the URL

### CODE REVIEW

**Comment by zacharysarah** [comment]
@tnir Thanks for opening this. Please remove changes to files in `/content/cn/`.

**Comment by ajaeger** [comment]
@zacharysarah , want to remove " Docs Review: Open Issues "? Or do those still exist?

**Comment by craigbox** [comment]
Please see #9026.

**Pull request merged**
