### PR TITLE
Add content/es/docs/concepts/configuration/manage-resources-containers.md

### PR DESCRIPTION
**Pull request by Anynou**
Add content/es/docs/concepts/configuration/manage-resources-containers.md

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@Anynou
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by Anynou** [comment]
cla doesn't work correctly

**Comment by electrocucaracha** [comment]
@Anynou you don't have to close the PRs, contact me on Stack to help you on this

**Comment by Anynou** [comment]
Ok. Thank you

**Pull request closed without merging**
