### PR TITLE
[WIP Waiting for Source Code Merge] Bring StorageObjectInUseProtection feature to GA

### PR DESCRIPTION
**Pull request by pospispa**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.10 Features: set Milestone to 1.10 and Base Branch to release-1.10
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NOTE: After opening the PR, please *un-check and re-check* the ["Allow edits from maintainers"](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) box so that maintainers can work on your patch and speed up the review process. This is a temporary workaround to address a known issue with GitHub.> 
>
> Please delete this note before submitting the pull request.

Allow edits from maintainers checkbox

### CODE REVIEW

**Comment by pospispa** [comment]
/hold
waiting for source code merge; PR https://github.com/kubernetes/kubernetes/pull/61325

**Comment by Bradamant3** [comment]
/assign

@pospispa can you please do the rebase to `release-1.10` soon, without waiting for source code merge? Thanks!

**Comment by pospispa** [comment]
This PR is for K8s 1.11. So I better close it create it once again later.

**Comment by Bradamant3** [comment]
whoops, sorry, did not see that. The release team is a bit hypervigilant on this feature atm. Although yeah even late at night I should have remembered that you're in beta for 1.10. I can let you know as soon as the `release-1.11` branch is created, bc I'll be helping run docs for 1.11 also. But let me ask around on the team. I am pretty sure we want to wait a couple of weeks, to minimize the need for merges from master to keep the release branch reasonably fresh. Adding the 1.11 milestone now, though, even though the PR is closed. Thank you!

**Pull request closed without merging**
