### PR TITLE
Add section about running the documentation site locally

### PR DESCRIPTION
**Pull request by dmathieu**
This adds a section on the `editdocs` page about running the site locally.
I noticed it only mentions forking and opening a PR. But not how to actually check how the changes will be rendered.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6902)

### CODE REVIEW

**Comment by dmathieu** [comment]
Note: I've used the same wording as in the section right above it (`our site`).
I'm not sure this is the best way to phrase things though, and would be happy to change it provided any suggestion.

**Comment by steveperry-53** [comment]
@dmathieu We're trying to keep this kind of detail our of README and instead in topics like [Staging Your Documentation Changes](https://kubernetes.io/docs/home/contribute/stage-documentation-changes/). Could you take a look at [Staging Your Documentation Changes](https://kubernetes.io/docs/home/contribute/stage-documentation-changes/) and make the appropriate updates there instead? Thanks.

**Comment by dmathieu** [comment]
Thank you @steveperry-53. It appears this is already documented as `Staging locally without Docker`.
As an english non-native, I'd just say that "staging" isn't the clearer way to talk about running the changes locally.
I'd also have mentioned that a lot earlier. I'd want to be able to test my changes way before opening the PR.

**Comment by steveperry-53** [comment]
@dmathieu Thanks for the feedback. I'll try to make the local viewing information more discoverable.

**Pull request closed without merging**
