### PR TITLE
Update hello minikube tutorial intro page

### PR DESCRIPTION
**Pull request by RA489**
Update hello minikube tutorial intro page
fixes https://github.com/kubernetes/website/issues/25295

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
This isn't _wrong_, but does `k8s.gcr.io/echoserver:1.4` actually include node.js?

It looks to me as if we might have left the name _hello-node_ in even when the `echoserver` container stopped including it.

I'd like to check whether this is the right clean up. Unless @RA489 you've got time to confirm that?

**Comment by onlydole** [comment]
Howdy, @RA489 - would you have some time to answer back regarding Tim’s question?

**Comment by RA489** [comment]
>> does k8s.gcr.io/echoserver:1.4 actually include node.js?
 @sftim Looking at echoserver container directory i don't think it uses node.js.

**Pull request merged**
