### PR TITLE
Add current version of Google Analytics code, Global Site Tag (gtag.js).

### PR DESCRIPTION
**Pull request by chenopis**
Replace GoogleAnalyticsObject (GAO) with current Global Site Tag (gtag) code.

### CODE REVIEW

**Comment by zacharysarah** [comment]
@chenopis Is there a way to verify in Google Analytics whether this PR works as intended? 

Also: interestingly, the footer in the preview build drops to 2 longer lines instead of 3 with a wrap.

**Comment by chenopis** [comment]
@zacharysarah Yeah, I'm using the Google Analytics Debugger (https://github.com/keithclark/gadebugger) to verify, but I want to do more testing first before we merge it. I'm also having Patricia take a look.

Can't speak to the line wrapping issue. Since the changes are within a `<script>` tag, theoretically it shouldn't affect the rendering.

**Comment by zacharysarah** [comment]
@chenopis OK. 👍 

/lgtm
/approve

**Comment by chenopis** [comment]
Hold until July 8, 2018.

**Pull request merged**
