### PR TITLE
Too complicated to understand... Keep it simple

### PR DESCRIPTION
**Pull request by nekrkris**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
> Help editing and submitting pull requests:  https://deploy-preview-9510--kubernetes-io-master-staging.netlify.com/docs/contribute/start/#submit-a-pull-request.
> Help choosing which branch to use, see
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by bradtopol** [comment]
@nekrkris Thank you for your contribution.  Please sign the CLA so we can accept your PR for review

**Comment by zacharysarah** [comment]
@nekrkris 👋 Thanks for this contribution. Please feel free to reopen this PR when you've signed the CLA. ☝️

**Pull request closed without merging**
