### PR TITLE
API reference for v1.28 (single page version)

### PR DESCRIPTION
**Pull request by tengqm**
Fixes https://github.com/kubernetes/website/issues/42588
Fixes https://github.com/kubernetes/website/issues/42601

### CODE REVIEW

**Comment by sftim** [comment]
This will fix https://github.com/kubernetes/website/issues/42588

**Comment by sftim** [comment]
This will fix https://github.com/kubernetes/website/issues/42601

**Comment by windsonsea** [comment]
Thanks.
/lgtm

**Pull request merged**
