### PR TITLE
Tweak virtual ips reference

### PR DESCRIPTION
**Pull request by sftim**
Split out from https://github.com/kubernetes/website/pull/30817

- fix link to Service tutorial
- Link to Ingress concept from https://kubernetes.io/docs/reference/networking/virtual-ips/

### CODE REVIEW

**Comment by ydFu** [comment]
This Service tutorial link is correct,now.

LGTM, thanks.

/lgtm

**Comment by divya-mohan0209** [comment]
The deploy preview looks okay on re-triggering the Netlify deploy - https://deploy-preview-38561--kubernetes-io-main-staging.netlify.app/docs/reference/networking/virtual-ips/#what-s-next. Thank you @sftim !

/approve

**Comment by divya-mohan0209** [comment]
@sftim Whenever you get a chance, please could you push an empty commit? I think that should help with the merge if I'm not wrong.

**Comment by sftim** [comment]
I can't log in to Netlify at the moment; usually, I could use access to that to trigger a rebuild.

(it'd be nice to have Prow offer a /retest command for that; it'd be handy too if Netlify builds did not time out)

**Pull request merged**
