### PR TITLE
Document deprecation warnings feature

### PR DESCRIPTION
**Pull request by annajung**
A replacement for https://github.com/kubernetes/website/pull/21581
cc @savitharaghunathan @liggitt

### CODE REVIEW

**Comment by annajung** [comment]
Hi @kbhawkey 👋 , 1.19 release docs shadow here. I have made changes to the docs as you suggested here https://github.com/kubernetes/website/pull/21581. Could you please review again to see if it meets your expectations?

Release team have decided to make a new PR to replace the existing one to get the PR in for 1.19 release due to @liggitt being out.

**Comment by savitharaghunathan** [comment]
Hi @deads2k 👋 , 1.19 Release Docs Lead here. Can you take a look at this PR which replaced [#21581 ](https://github.com/kubernetes/website/pull/21581) and provide a tech `lgtm` if everything looks good? Thanks!

**Comment by annajung** [comment]
@liggitt reached out and mentioned that he will be available to review the comments and move the doc forward for the release. Closing to allow https://github.com/kubernetes/website/pull/21581 PR to move forward as intended

**Pull request closed without merging**
