### PR TITLE
Translation error correction with k8s.io/ko/docs/concepts/overview/co…

### PR DESCRIPTION
**Pull request by pjhwa**
from #19719

### CODE REVIEW

**Comment by gochist** [comment]
@pjhwa 감사합니다!
/lgtm

**Comment by gochist** [comment]
@ianychoi As the author and I belong to the same company, I request approval for the PR from other approver.

**Comment by seokho-son** [comment]
I think this PR is approvable. I count on the review from @gochist and checked the preview of the affected page. 
So, lgtm :) and approve.

@pjhwa Thank you for the contribution.

/approve

**Pull request merged**
