### PR TITLE
Replace EN links to ID links

### PR DESCRIPTION
**Pull request by wahyuoi**
This PR only replace EN to ID links iff ID links are already available

script: https://github.com/jk8s/sig-docs-id/pull/26 
/cc @kubernetes/sig-docs-id-reviews

### CODE REVIEW

**Comment by irvifa** [comment]
Is this only applied for page that have been translated?

**Comment by wahyuoi** [comment]
@irvifa yes, it is only scan the translated pages on master

**Comment by tengqm** [comment]
@irvifa As you may have noticed, the localization teams have been suffering from the link problems and they are coming up with duplicated efforts to solve them.

**Comment by girikuncoro** [comment]
@wahyuoi sorry for the delay, I forgot one thing to ask when using the script https://github.com/jk8s/sig-docs-id/blob/master/scripts/localize_url.py

does this check whether the ID links exist or not? if the ID links do not exist, does it keep the EN links? or say if we have ID links with pages that do not exist yet (`/id/` + EN page), does it redirect to the EN page?

**Comment by wahyuoi** [comment]
@girikuncoro it's only check for existing ID pages. so /id + en_links will be safe

**Comment by girikuncoro** [comment]
This is awesome!
/lgtm
/approve

**Pull request merged**
