### PR TITLE
Update deployment.md

### PR DESCRIPTION
**Pull request by piazera**
wrong article used

### CODE REVIEW

**Comment by piazera** [comment]
I signed it

**Comment by piazera** [comment]
I signed it

**Comment by piazera** [comment]
@Arhell I think I had not finished the CLA sign up process. Let's see if it works now.

**Comment by piazera** [comment]
I signed it

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-22445--kubernetes-io-master-staging.netlify.app/docs/concepts/workloads/controllers/deployment/#selector

**Comment by kbhawkey** [comment]
Hello @piazera .
Thanks for opening this pull request.
/lgtm

**Comment by kbhawkey** [comment]
Thanks!
/approve

**Pull request merged**
