### PR TITLE
Update parallel-processing-expansion.md

### PR DESCRIPTION
**Pull request by VineethReddy02**
Focusing simplicity and for better readability in understanding the command inputs and their respective outputs. 
Segregated the inputs and outputs.

### CODE REVIEW

**Comment by VineethReddy02** [comment]
[Changes Preview](https://deploy-preview-12773--kubernetes-io-master-staging.netlify.com/docs/tasks/job/parallel-processing-expansion/)

[Original Preview](https://kubernetes.io/docs/tasks/job/parallel-processing-expansion/)

Beginners can understand better by this segregation. I will make consistent shell previews for inputs and outputs across the docs.

**Comment by Rajakavitha1** [comment]
Hi @VineethReddy02!!!  There is another PR that is addresses the code formatting guidelines.
Please see https://github.com/kubernetes/website/pull/12783. I am closing this PR for now. Please feel free to open the PR after the PR for guidelines are approved.

**Comment by VineethReddy02** [comment]
/open

Considering the better readability reopening this, let me know if $ should be removed from scripts.
@DanyC97

**Pull request closed without merging**
