### PR TITLE
Revise appearance of kubeweekly subscription form

### LINKED ISSUE #42961: "Subscribe to KubeWeekly Newsletter" section, enhancement request
**This is a Feature Request**

**What would you like to be enhanced?**
I think "Subscribe to KubeWeekly Newsletter" section at bottom of Home page is:-
1. Taking too much white/grey space that can be shortend.
2. The input area where user will enter his/her email id is a little small and maybe it will be better if that gets a little enlarged.

Screenshot (667)

### PR DESCRIPTION
**Pull request by satyampsoni**
Fixes #42961

### CODE REVIEW

**Comment by reylejano** [comment]
I'm indifferent to reducing the space, on my screen the spacing looks fine but I can be persuaded
Note, issue https://github.com/kubernetes/website/issues/42961 is not triage/accepted atm

**Comment by satyampsoni** [comment]
No worries! If this gets the triage/accepted label, hope you'll be convinced.

**Comment by sftim** [comment]
/retitle Revise appearance of kubeweekly subscription form

**Comment by Arnett28** [comment]
Ok

**Comment by tengqm** [comment]
/lgtm
/approve
This breaks are actually useless.

**Pull request merged**
