### PR TITLE
add release candidate parameter

### PR DESCRIPTION
**Pull request by kbhawkey**
- Modified update-imported-docs.py and reference.yml to build the reference docs with the k8s release candidate versions.
- Tested with k8s v1.19.0-rc.3 and v1.18.0.

### CODE REVIEW

**Comment by kbhawkey** [comment]
/assign @savitharaghunathan 
This change is dependent upon PR https://github.com/kubernetes-sigs/reference-docs/pull/169.

**Comment by tengqm** [comment]
The change looks good to me. My only concern is about the necessity of introducing this change, just to support release previews...

**Comment by kbhawkey** [comment]
> 
> 
> The change looks good to me. My only concern is about the necessity of introducing this change, just to support release previews...

I agree, though, having the option to build the ref. docs before the final release is an improvement.
Alternatively, we could use the full tag for the value of K8S_RELEASE (v1.18.0, v1.19.0-rc.3, v1.19.5) instead of 1.18 or 1.19.
This could be done, but would require a bit more work on the build side.
/hold

**Comment by kbhawkey** [comment]
Created another PR for this task, https://github.com/kubernetes/website/pull/22898.
/close

**Pull request closed without merging**
