### PR TITLE
[hi] Add content/hi/docs/contribute/analytics.md

### PR DESCRIPTION
**Pull request by Shubh28698**
Hello!

 This PR is a part of ongoing hi localization effort

Hindi localization of page: content/en/docs/contribute/analytics.md

/language hi

@anubha-v-ardhan Can you please review

### CODE REVIEW

**Comment by Polokghosh53** [comment]
The commits here are coming from different merge requests and it seems you wanted to work on Hindi localization but bought in all the localization labels and the large number commits.

**Comment by Shubh28698** [comment]
Can you please guide me . Should I select "main" as base branch first while creating pull request

**Comment by Shubh28698** [comment]
> The commits here are coming from different merge requests and it seems you wanted to work on Hindi localization but bought in all the localization labels and the large number commits.

Can you please guide me . Should I select "main" as base branch first while creating pull request

**Comment by Polokghosh53** [comment]
> > The commits here are coming from different merge requests and it seems you wanted to work on Hindi localization but bought in all the localization labels and the large number commits.
> 
> Can you please guide me . Should I select "main" as base branch first while creating pull request

Refer to this branch and create a PR for the mentioned directory
Link: https://github.com/kubernetes/website/tree/dev-1.22-hi.1/content/hi

One thing you can do is create a new PR for this, as this has become quite cumbersome and a lot of other PRs and labels to remove. But I would request to @anubha-v-ardhan to view this and approve.

**Comment by kranurag7** [comment]
@Shubh28698 I was also facing the same issue. In your case your branch is not correct. Try to make a PR from `dev-1.22-hi.1`. Your PR should look something like this. Ping me if it's still unsolved. I agree with @Polokghosh53 that you should create another fresh PR.
githubpullrequest

**Comment by anubha-v-ardhan** [comment]
Thanks @Polokghosh53 @kranurag7 @Shubh28698 

The general rule is to make branches from the branch to which the PR will be eventually merged.
For eg: In this case you will need make branches from `dev-1.22-hi.1` (not `main`) on your forked repo and work on that.

Since `dev-1.22-hi.1` is far behind `main`, making a PR from a branch (or directly main) that was made from main will carry all those commits with them as happened here.

Also note that while we welcome and value your effort to contribute to HIndi localization, we will need a lot of time to accept it as our first priority is to launch the localization on k8s.io. Once thats done, our reviewers will be available to review this PR.

As of fixing this PR, you can do either of these solutions
- Doing a rebase and dropping the unwanted commits
- Starting a new branch off `dev-1.22-hi.1` and `git cherry-pick` each commit you want to include and make a new PR.
- **Easiest** make a whole new branch from `dev-1.22-hi.1` and copy paste the changes from here and make a new PR.

Feel free to ask if you have any confusions

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de en es fr id it ja ko pl pt ru uk vi zh
/remove-sig release

**Pull request closed without merging**
