### PR TITLE
Fix the feature state of PodSecurity

### PR DESCRIPTION
**Pull request by houjun41544**
Fix the feature state of PodSecurity

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @houjun41544,

Thanks for contributing k8s website! In this repo, we limited to one language for each PR.
Please just update the `en` content and leave the `zh-cn` one to another PR after this one is merged.

**Comment by kbhawkey** [comment]
Hi @houjun41544 . We recommend that you limit a pull request to changes in one language or localization.
In this case, let's see if the `zh` localization team has time to review the change.
Ping @kubernetes/sig-docs-zh-reviews  for review.

**Comment by houjun41544** [comment]
@Sea-n @kbhawkey 
Thanks for your suggestion. This PR has been updated. I will commit another pull request to zh-cn.

**Pull request merged**
