### PR TITLE
[wip] testing rc clone, ref docs

### PR DESCRIPTION
**Pull request by kbhawkey**
Testing script changes with release candidate switch.

### CODE REVIEW

**Comment by kbhawkey** [comment]
:stop_button: DO NOT MERGE
This is a test.
/cc @savitharaghunathan

**Comment by kbhawkey** [comment]
:wave: @savitharaghunathan , I am testing out some ways to accept an `rc` string with the script (and make sure the reference-docs Makefile targets work too).
If you want to try out the script locally, copy the update-imported-docs.py script and reference.yml to your branch, then build
`python3 update-imported-docs.py reference.yml 1.19 --rc 3`

I will review the build of the files.

**Comment by kbhawkey** [comment]
API ref preview:
https://deploy-preview-22829--kubernetes-io-master-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.19/

**Comment by savitharaghunathan** [comment]
> If you want to try out the script locally, copy the update-imported-docs.py script and reference.yml to your branch, then build
> `python3 update-imported-docs.py reference.yml 1.19 --rc 3`
> 
> I will review the build of the files.

Thank you @kbhawkey. I will try this in my local env :)

**Comment by savitharaghunathan** [comment]
Hi @kbhawkey 👋 , I copied `reference.yml` & `update-imported-docs.py` from your PR branch and it worked :) I haven't compared file to file content changes but it quickly did a check on the modified files and newly added files and I have gotten the same result as yours. Thanks!

**Comment by kbhawkey** [comment]
See PR https://github.com/kubernetes/website/pull/22883 for script updates.

**Pull request closed without merging**
