### PR TITLE
docs: Clarity to pod description documentation page.

### PR DESCRIPTION
**Pull request by rukundob451**
Improve clarity of Pod description in "Pods" documentation page: 

https://kubernetes.io/docs/concepts/workloads/pods/

issue number [#41824](https://github.com/kubernetes/website/issues/41824)

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@rukundob451 Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed and merged.
You can follow the steps documented here: https://git.k8s.io/community/CLA.md

**Comment by rukundob451** [comment]
@dipesh-rawat, thank you for this information. I have signed the CLA as suggested. You can now review and merge it.

**Comment by tengqm** [comment]
This PR is not fixing anything in the docs. It is instead introducing errors into the text.
Feel free to reopen if you can clarify what you are trying to fix.

**Pull request closed without merging**
