### PR TITLE
Remove an incorrect warning when using katacoda tutorials

### PR DESCRIPTION
**Pull request by nikitar**
Removes the "The screen is too narrow to interact with the Terminal, please use a desktop/tablet" warnings next to katacoda tutorials. (For example, [here](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/)) The warning appears when using a screen of any size, so it's somewhat confusing. I've also verified that katacoda works on small screens as well (including on mobile), which presumably wasn't the case at the time the message was added six years ago.

Other messages just say "To interact with the Terminal, please use the desktop/tablet version". That's less confusing, but still not necessary. I can leave those messages alone, however, if they are deemed helpful. (The terminal works on mobile, but it's definitely easier to use on desktop)

There are also plans to migrate tutorials off katacoda, but it's likely to take some time. (See #33936)

Fixes: #37431

Signed-off-by: Nikita Rybak <nikita.rybak@gmail.com>

### CODE REVIEW

**Comment by nikitar** [comment]
I've also included translations in the pr. Please let me know if I should just do the english docs instead.

**Review by divya-mohan0209 — DISMISSED** [review]
Hello @nikitar, typically when a change across multiple languages is proposed we try limiting it first to the main website, i.e. the en localization. Once it has been approved and lgtmed, we then make the changes to the other localizations. That being said, please could you do the below

- Remove all language files except the ones under en/docs/tutorials in your next commit.
- Get it reviewed and approved.
- File a separate PR for each language after step 2 has been completed for each language that you're proposing the change in.

**Comment by nikitar** [comment]
@divya-mohan0209 Thanks, I've updated the pr to only include english-language files. Let me know if there's anything else I need to do.

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks, @nikitar! 
/lgtm

**Comment by nikitar** [comment]
Assigning @reylejano as suggested by the ci robot.

/assign @reylejano

**Review by sftim — COMMENTED** [review]
Seems reasonable.

/approve

**Pull request merged**
