### PR TITLE
Update WebhookAdmissionConfiguration example

### PR DESCRIPTION
**Pull request by liggitt**
xref https://github.com/kubernetes/kubernetes/pull/85138

/cc @deads2k 
/sig api-machinery

### CODE REVIEW

**Comment by kbhawkey** [comment]
@liggitt , is there duplicate content with #17547, #17548?

**Comment by liggitt** [comment]
from the description:

> Builds on #17548 and #17547

only the last commit is unique to this PR

**Comment by daminisatya** [comment]
@liggitt needs rebase

**Comment by liggitt** [comment]
done

**Pull request merged**
