### PR TITLE
Simplify kubectl heredoc usage in cheatsheet

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Remove the unnecessary cat command.

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hello @juergenhoetzel , please ensure you submit one PR that gets technically + qualitatively approved by the main website reviewers & approvers (i.e. language/en approvers & reviewers). Once that is done, please open separate PRs for each localisation, since they have different processes of documentation maintenance.

Tl;Dr: Please ONLY submit a change for the English website via this PR & get it approved & reviewed.

**Comment by juergenhoetzel** [comment]
> Tl;Dr: Please ONLY submit a change for the English website via this PR & get it approved & reviewed.

Sorry, I thought since it is only a code change a change in all languages would not be a problem.

I just amended the commit.

**Comment by atoato88** [comment]
/uncc @atoato88 

I uncc-ed myself, since I'm a reviewer on `ja` docs.
Feel free to assign me once you create same updates on `ja` docs.

**Comment by atoato88** [comment]
I remove language labels which are not related with this PR.

/remove-language de
/remove-language fr 
/remove-language id 
/remove-language ja 
/remove-language ko 
/remove-language pt
/remove-language ru
/remove-language vi
/remove-language zh

**Review by divya-mohan0209 — COMMENTED** [review]
/approve

**Review by ydFu — APPROVED** [review]
/lgtm

In "Create multiple YAML objects from stdin" and "Create a secret with several keys", the cat command can be simplified.

**Comment by windsonsea** [comment]
Please run the following commands to trigger the CI again:

```
git reset
git commit --amend --no-edit
git push -f
```

**Pull request merged**
