### PR TITLE
[ko] replace all references to `storage.googleapis.com/kubernetes-release` with `dl.k8s.io`

### PR DESCRIPTION
**Pull request by 9bany**
fixes: https://github.com/kubernetes/website/issues/41069

### CODE REVIEW

**Comment by gochist** [comment]
Hello @9bany :wave:! It was assigned to @jongwooo in issue #38458.

As you can see in issue #38458, Korean localization uses a working branch to keep up with upstream changes from the previous working branch. Currently it is `dev-1.26-ko.1` .

In order to prevent conflicts when merging the working branch into the `main` branch in the future, it seems necessary to coordinate with @9bany and @jongwooo.

I suggest to @9bany to change the base branch of this PR from `main` to `dev-1.26-ko.1`.

**Comment by 9bany** [comment]
Hello @gochist, i don't have any idea how can i create a new branch base from `dev-1.26-ko.1`  
as you can see, i was change base from `main` to `dev-1.26-ko.1`, but it too big PR

**Comment by rjsadow** [comment]
> Hello @gochist, i don't have any idea how can i create a new branch base from `dev-1.26-ko.1` as you can see, i was change base from `main` to `dev-1.26-ko.1`, but it too big PR

Hey @9bany, I think what you'll need to do is:

Go to the top of this PR and click Edit:
image

Select the `base:main` dropdown:
image

Search for `dev-1.26-ko.1` then select it:
image

Confirm that you want to change the base:
image

Verify that the new target is `dev-1.26-ko.1:
image

Note: This was done in my own fork so it shows `rjsadow:dev-1.26-ko.1`. When you're finished it should say "merge 1 commit into `kubernetes:dev-1.26-ko.1` from `9bany/....`"

**Comment by rjsadow** [comment]
Hey @9bany I think what you're going to need to do is:

1. Ensure you have all the latest branches available in your repo. `git pull upstream`
2. Checkout `dev-1.26-ko.1`
3. Cherry pick your commit from your main to `dev-1.26-ko.1`. `git cherry-pick 36cf98b08515f204875338a4d5ff534bc17cb153`
4. Re push.  `git push .... --force`
5. Update the target branch to also be `dev-1.26-ko.1`

**Pull request closed without merging**
