### PR TITLE
Second Japanese l10n work for release-1.17

### PR DESCRIPTION
**Pull request by inductor**
Second Japanese l10n work for release-1.17.

<details>
    <summary><b>Change List</b></summary>
    <ul>
    <li>Fix typo (<a href="https://github.com/kubernetes/website/pull/19878" target="_blank">#19878</a>)</li>
    <li>replace http helm link with https (<a href="https://github.com/kubernetes/website/pull/19889" target="_blank">#19889</a>)</li>
    <li>fix typo (<a href="https://github.com/kubernetes/website/pull/20028" target="_blank">#20028</a>)</li>
    <li>update link to /ja/docs/concepts/services-networking/dns-pod-service/ (<a href="https://github.com/kubernetes/website/pull/20095" target="_blank">#20095</a>)</li>
    <li>update link to /ja/docs/concepts/workloads/pods/pod-lifecycle/ (<a href="https://github.com/kubernetes/website/pull/20100" target="_blank">#20100</a>)</li>
    <li>update link to /ja/docs/concepts/overview/working-with-objects/labels/ (<a href="https://github.com/kubernetes/website/pull/20124" target="_blank">#20124</a>)</li>
    <li>update link to /ja/docs/concepts/overview/kubernetes-api/ (<a href="https://github.com/kubernetes/website/pull/20237" target="_blank">#20237</a>)</li>
    <li>update link to /ja/docs/tutorials/stateless-application/expose-external-ip-address/ (<a href="https://github.com/kubernetes/website/pull/20263" target="_blank">#20263</a>)</li>
    <li>Update Outdated Japanese Translation (<a href="https://github.com/kubernetes/website/pull/20559" target="_blank">#20559</a>)</li>
    <li>update link to /ja/docs/concepts/overview/working-with-objects/kubernetes-objects/ (<a href="https://github.com/kubernetes/website/pull/20746" target="_blank">#20746</a>)</li>
    <li>update link to /ja/docs/concepts/extend-kubernetes/api-extension/custom-resources/ (<a href="https://github.com/kubernetes/website/pull/20771" target="_blank">#20771</a>)</li>
    <li>Translate tasks/configure-pod-container/configure-pod-configmap/ into… (<a href="https://github.com/kubernetes/website/pull/20773" target="_blank">#20773</a>)</li>
    <li>Fix typo: rollinUpdate → rollingUpdate in statefulset.md (<a href="https://github.com/kubernetes/website/pull/20776" target="_blank">#20776</a>)</li>
    <li>update link to /ja/docs/tasks/run-application/force-delete-stateful-set-pod/ (<a href="https://github.com/kubernetes/website/pull/20794" target="_blank">#20794</a>)</li>
    <li>update link to /ja/docs/tasks/run-application/run-stateless-application-deployment/ (<a href="https://github.com/kubernetes/website/pull/20795" target="_blank">#20795</a>)</li>
    <li>update link to /ja/docs/tasks/configure-pod-container/assign-memory-resource/ (<a href="https://github.com/kubernetes/website/pull/20796" target="_blank">#20796</a>)</li>
    <li>Translate setup/production-environment/tools/kubeadm/create-cluster-kubeadm into Japanese (<a href="https://github.com/kubernetes/website/pull/20880" target="_blank">#20880</a>)</li>
    <li>Translate setup/production-environment/tools/kubeadm/ha-topology.md i… (<a href="https://github.com/kubernetes/website/pull/20882" target="_blank">#20882</a>)</li>
    <li>Fix typo (<a href="https://github.com/kubernetes/website/pull/20884" target="_blank">#20884</a>)</li>
    <li>Fix note shortcodes in Deployment concept (ja) (<a href="https://github.com/kubernetes/website/pull/21015" target="_blank">#21015</a>)</li>
    <li>update /ja/docs/concepts/overview/working-with-objects/names/ (<a href="https://github.com/kubernetes/website/pull/21038" target="_blank">#21038</a>)</li>
    <li>update /ja/docs/concepts/overview/working-with-objects/annotations/ (<a href="https://github.com/kubernetes/website/pull/21077" target="_blank">#21077</a>)</li>
    <li>update /ja/docs/concepts/overview/working-with-objects/common-labels/ (<a href="https://github.com/kubernetes/website/pull/21099" target="_blank">#21099</a>)</li>
    <li>update /ja/docs/concepts/overview/working-with-objects/namespaces/ (<a href="https://github.com/kubernetes/website/pull/21120" target="_blank">#21120</a>)</li>
    <li>Translate tasks/access-application-cluster/web-ui-dashboard/ into Japanese (<a href="https://github.com/kubernetes/website/pull/21141" target="_blank">#21141</a>)</li>
    <li>update content/ja/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html (<a href="https://github.com/kubernetes/website/pull/21169" target="_blank">#21169</a>)</li>
    <li>Fix typos (<a href="https://github.com/kubernetes/website/pull/21179" target="_blank">#21179</a>)</li>
    <li>rename container-environment-variable to container-environment (<a href="https://github.com/kubernetes/website/pull/21191" target="_blank">#21191</a>)</li>
    <li>Fix translation "廃止されました" (<a href="https://github.com/kubernetes/website/pull/21192" target="_blank">#21192</a>)</li>
    <li>Translate /docs/concepts/containers/overview/ into Japanese (<a href="https://github.com/kubernetes/website/pull/21195" target="_blank">#21195</a>)</li>
    <li>update /ja/docs/concepts/storage/dynamic-provisioning/ (<a href="https://github.com/kubernetes/website/pull/21201" target="_blank">#21201</a>)</li>
    <li>update /ja/docs/concepts/workloads/controllers/garbage-collection/ (<a href="https://github.com/kubernetes/website/pull/21219" target="_blank">#21219</a>)</li>
    <li>update /ja/docs/concepts/storage/volume-snapshot-classes/ (<a href="https://github.com/kubernetes/website/pull/21221" target="_blank">#21221</a>)</li>
    <li>update /ja/docs/tasks/debug-application-cluster/get-shell-running-container/ (<a href="https://github.com/kubernetes/website/pull/21224" target="_blank">#21224</a>)</li>
    <li>Translate /docs/tasks/inject-data-application/define-environment-variable-container/ into Japanese (<a href="https://github.com/kubernetes/website/pull/21229" target="_blank">#21229</a>)</li>
    <li>Translate concepts/policy/resource-quotas.md into Japanese #19282 (<a href="https://github.com/kubernetes/website/pull/21242" target="_blank">#21242</a>)</li>
    <li>update /ja/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/ (<a href="https://github.com/kubernetes/website/pull/21280" target="_blank">#21280</a>)</li>
    <li>update /ja/docs/concepts/storage/volume-pvc-datasource/ (<a href="https://github.com/kubernetes/website/pull/21282" target="_blank">#21282</a>)</li>
    <li>update /ja/docs/home/ (<a href="https://github.com/kubernetes/website/pull/21288" target="_blank">#21288</a>)</li>
    <li>update /ja/docs/setup/best-practices/multiple-zones/ (<a href="https://github.com/kubernetes/website/pull/21316" target="_blank">#21316</a>)</li>
    <li>issue #21304 "add glossary_tooltip and change word" (<a href="https://github.com/kubernetes/website/pull/21317" target="_blank">#21317</a>)</li>
    <li>issue #21302 Update ja: glossary/kubelet.md (<a href="https://github.com/kubernetes/website/pull/21319" target="_blank">#21319</a>)</li>
    <li>update /ja/docs/setup/best-practices/node-conformance/ (<a href="https://github.com/kubernetes/website/pull/21324" target="_blank">#21324</a>)</li>
    <li>update content/ja/docs/reference/glossary/selector.md (<a href="https://github.com/kubernetes/website/pull/21332" target="_blank">#21332</a>)</li>
    <li>update 'sig' text (Japanese) (<a href="https://github.com/kubernetes/website/pull/21335" target="_blank">#21335</a>)</li>
    <li>Make glossary/kube-scheduler.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21340" target="_blank">#21340</a>)</li>
    <li>update content/ja/docs/reference/glossary/kube-apiserver.md (<a href="https://github.com/kubernetes/website/pull/21341" target="_blank">#21341</a>)</li>
    <li>Transrate glossary/cluster.md to Japanese (<a href="https://github.com/kubernetes/website/pull/21342" target="_blank">#21342</a>)</li>
    <li>Make glossary/kube-proxy.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21344" target="_blank">#21344</a>)</li>
    <li>update volume docs(Ja) (<a href="https://github.com/kubernetes/website/pull/21349" target="_blank">#21349</a>)</li>
    <li>Make glossary/kube-controller-manager.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21356" target="_blank">#21356</a>)</li>
    <li>Translate /docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ into Japanese  (<a href="https://github.com/kubernetes/website/pull/21370" target="_blank">#21370</a>)</li>
    <li>update the outdated ja tutorials/_index.md based on the v1.17 en page (<a href="https://github.com/kubernetes/website/pull/21385" target="_blank">#21385</a>)</li>
    <li>ja: Make tutorials/hello-minikube.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21386" target="_blank">#21386</a>)</li>
    <li>use English for hash flagment #termination-of-pods (<a href="https://github.com/kubernetes/website/pull/21403" target="_blank">#21403</a>)</li>
    <li>ja: Make /docs/tasks/tools/install-kubectl/ follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21405" target="_blank">#21405</a>)</li>
    <li>ja: Make docs/concepts/workloads/pods/pod-overview.md follow v1.17 of… (<a href="https://github.com/kubernetes/website/pull/21425" target="_blank">#21425</a>)</li>
    <li>ja: Make docs/reference/_index.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21427" target="_blank">#21427</a>)</li>
    <li>ja: Make /docs/tasks/access-application-cluster/connecting-frontend-backend/ follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21430" target="_blank">#21430</a>)</li>
    <li>Markdown code blocks described in Shell (<a href="https://github.com/kubernetes/website/pull/21431" target="_blank">#21431</a>)</li>
    <li>ja: Make tutorials/kubernetes-basics/expose/expose-intro.html follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21433" target="_blank">#21433</a>)</li>
    <li>Update tutorials/configuration/configure-redis-using-configmap.md to … (<a href="https://github.com/kubernetes/website/pull/21434" target="_blank">#21434</a>)</li>
    <li>Follow upstream/release-1.16 to upstream/release-1.17 in Japanese (<a href="https://github.com/kubernetes/website/pull/21455" target="_blank">#21455</a>)</li>
    <li>ja: Make docs/concepts/workloads/controllers/replicaset.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21468" target="_blank">#21468</a>)</li>
    <li>ja: Make docs/concepts/workloads/controllers/ttlafterfinished.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21471" target="_blank">#21471</a>)</li>
    <li>Update content/ja/docs/tasks/tools/install-minikube.md (<a href="https://github.com/kubernetes/website/pull/21472" target="_blank">#21472</a>)</li>
    <li>Change the way the RegisterCloudProvider function references the defi… (<a href="https://github.com/kubernetes/website/pull/21475" target="_blank">#21475</a>)</li>
    <li>ja: Make docs/concepts/workloads/pods/pod-lifecycle.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21476" target="_blank">#21476</a>)</li>
    <li>ja: Make docs/concepts/workloads/pods/pod.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21482" target="_blank">#21482</a>)</li>
    <li>ja: Need to fix typo in docs/concepts/workloads/pods/pod-lifecycle.md (<a href="https://github.com/kubernetes/website/pull/21483" target="_blank">#21483</a>)</li>
    <li>ja: Make docs/concepts/storage/persistent-volumes.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21485" target="_blank">#21485</a>)</li>
    <li>ja: Make docs/concepts/workloads/controllers/cron-jobs.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21486" target="_blank">#21486</a>)</li>
    <li>ja: Make docs/concepts/workloads/controllers/daemonset.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21487" target="_blank">#21487</a>)</li>
    <li>ja: Make /docs/tasks/debug-application-cluster/debug-pod-replication-controller/ follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21488" target="_blank">#21488</a>)</li>
    <li>ja: Make docs/concepts/overview/working-with-objects/labels.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21504" target="_blank">#21504</a>)</li>
    <li>ja: Make docs/concepts/scheduling/kube-scheduler.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21507" target="_blank">#21507</a>)</li>
    <li>ja: Make /docs/tasks/access-application-cluster/configure-access-multiple-clusters/ follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21510" target="_blank">#21510</a>)</li>
    <li>ja: Make /docs/tasks/access-application-cluster/service-access-application-cluster/ follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21511" target="_blank">#21511</a>)</li>
    <li>ja: Make tutorials/kubernetes-basics/update/update-intro.html follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21512" target="_blank">#21512</a>)</li>
    <li>ja: Make docs/concepts/overview/working-with-objects/field-selectors.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21521" target="_blank">#21521</a>)</li>
    <li>Add hello-application.yaml file under ja directory (<a href="https://github.com/kubernetes/website/pull/21524" target="_blank">#21524</a>)</li>
    <li>ja: Make docs/concepts/services-networking/dns-pod-service.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21525" target="_blank">#21525</a>)</li>
    <li>ja: Make docs/setup/_index.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21526" target="_blank">#21526</a>)</li>
    <li>Update statefulset.md for v1.17 (<a href="https://github.com/kubernetes/website/pull/21530" target="_blank">#21530</a>)</li>
    <li>Update /docs/tasks/configure-pod-container/quality-service-pod/ follo… (<a href="https://github.com/kubernetes/website/pull/21532" target="_blank">#21532</a>)</li>
    <li>ja: Make docs/concepts/services-networking/service.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21541" target="_blank">#21541</a>)</li>
    <li>Make docs/contribute/_index.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21544" target="_blank">#21544</a>)</li>
    <li>ja: Make docs/concepts/workloads/pods/init-containers.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21557" target="_blank">#21557</a>)</li>
    <li>Follow "Update references to the patch release process" in Japanese (<a href="https://github.com/kubernetes/website/pull/21561" target="_blank">#21561</a>)</li>
    <li>follow ja:glossary/controller.md v1.17 (<a href="https://github.com/kubernetes/website/pull/21579" target="_blank">#21579</a>)</li>
    <li>ja: Make docs/concepts/services-networking/ingress.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21608" target="_blank">#21608</a>)</li>
    <li>Remove announcement and deprecationwarning shortcodes (<a href="https://github.com/kubernetes/website/pull/21620" target="_blank">#21620</a>)</li>
    <li>Follow tutorials/kubernetes-basics/create-cluster/cluster-intro in Ja… (<a href="https://github.com/kubernetes/website/pull/21639" target="_blank">#21639</a>)</li>
    <li>ja: Translate /partners/ into Japanese (<a href="https://github.com/kubernetes/website/pull/21647" target="_blank">#21647</a>)</li>
    <li>ja: Translate /training/ into Japanese (<a href="https://github.com/kubernetes/website/pull/21648" target="_blank">#21648</a>)</li>
    <li>Update content/ja/docs/concepts/services-networking/connect-applications-service.md (<a href="https://github.com/kubernetes/website/pull/21653" target="_blank">#21653</a>)</li>
    <li>ja: fix typo in /training/ (<a href="https://github.com/kubernetes/website/pull/21668" target="_blank">#21668</a>)</li>
    <li>Update ja/docs/tutorials/stateless-application/expose-external-ip-add… (<a href="https://github.com/kubernetes/website/pull/21691" target="_blank">#21691</a>)</li>
    <li>ja: Make docs/concepts/overview/working-with-objects/kubernetes-objects.md follow v1.17 of the original text (<a href="https://github.com/kubernetes/website/pull/21693" target="_blank">#21693</a>)</li>
    <li>ja: fix inconsistent translation of "init container" (<a href="https://github.com/kubernetes/website/pull/21694" target="_blank">#21694</a>)</li>
    <li>Translate /docs/tasks/debug-application-cluster/debug-service.md into Japanese / #21399 (<a href="https://github.com/kubernetes/website/pull/21700" target="_blank">#21700</a>)</li>
    <li>Update certificates.md for v1.17 (<a href="https://github.com/kubernetes/website/pull/21710" target="_blank">#21710</a>)</li>
    <li>Translate /docs/reference/kubectl/overview/ into Japanese (<a href="https://github.com/kubernetes/website/pull/21711" target="_blank">#21711</a>)</li>
    <li>ja: Improve translation of docs/concepts/services-networking/ingress.md (<a href="https://github.com/kubernetes/website/pull/21716" target="_blank">#21716</a>)</li>
    <li>Replace アーキテクチャー to アーキテクチャ (<a href="https://github.com/kubernetes/website/pull/21726" target="_blank">#21726</a>)</li>
    <li>Update deploy-intro.html (<a href="https://github.com/kubernetes/website/pull/21736" target="_blank">#21736</a>)</li>
    <li>Make docs/concepts/workloads/controllers/deployment.md follow v1.17 o… (<a href="https://github.com/kubernetes/website/pull/21743" target="_blank">#21743</a>)</li>
    </ul>
</details>
<br>

Co-authored-by: @taknakamura
Co-authored-by: @arisgi
Co-authored-by: @makochu
Co-authored-by: @ryokotmng
Co-authored-by: @Pick1a1username
Co-authored-by: @jlandowner
Co-authored-by: @chaspy
Co-authored-by: @mochizuki-pg
Co-authored-by: @yu-kasuya
Co-authored-by: @iaoiui
Co-authored-by: @ryok-0319
Co-authored-by: @Bo0km4n
Co-authored-by: @onsd
Co-authored-by: @esakat
Co-authored-by: @akitok
Co-authored-by: @nishipy
Co-authored-by: @tomoyamachi
Co-authored-by: @kenseitogari
Co-authored-by: @makotow
Co-authored-by: @hiyokotaisa
Co-authored-by: @Yoshiki0705
Co-authored-by: @Anorlondo448
Co-authored-by: @ytakaya
Co-authored-by: @inductor
Co-authored-by: @kakts
Co-authored-by: @Climber22
Co-authored-by: @oke-py
Co-authored-by: @y-taka-23
Co-authored-by: @isheik
Co-authored-by: @shuuji3
Co-authored-by: @translucens
Co-authored-by: @chez-shanpu
Co-authored-by: @hikkie3110
Co-authored-by: @k-srkw
Co-authored-by: @tkms0106

### CODE REVIEW

**Comment by inductor** [comment]
https://deploy-preview-21746--kubernetes-io-master-staging.netlify.app/

**Comment by makocchi-ca** [comment]
/lgtm
ざっと全体を確認してページ崩れとか無いこと確認

**Comment by makocchi-git** [comment]
/lgtm
ざっと全体を確認してページ崩れとか無いこと確認

**Comment by cstoku** [comment]
LGTM

**Pull request merged**
