### PR TITLE
Generate single-page API reference for 1.23

### PR DESCRIPTION
**Pull request by jlbutler**
Generated assets for single-page API reference for 1.23 release.

### CODE REVIEW

**Comment by reylejano** [comment]
@sftim @kbhawkey @tengqm , ptal

**Review by sftim — COMMENTED** [review]
/approve

**Comment by sftim** [comment]
[Preview](https://deploy-preview-30795--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.23/) also LGTM

**Comment by sftim** [comment]
Post-merge
/lgtm

**Pull request merged**
