### PR TITLE
Updated to give an example for restore using --data-dir option in etc…

### PR DESCRIPTION
**Pull request by ganeshniyer**
…dctl

### CODE REVIEW

**Review by ganeshniyer — COMMENTED** [review]
/assign @savitharaghunathan

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-27372--kubernetes-io-master-staging.netlify.app/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster

**Comment by kbhawkey** [comment]
Hi @wojtek-t .
Would you have time to provide a technical review?
Thank you!

**Comment by wojtek-t** [comment]
I'm sorry - I missed this.

/remove-lifecycle stale

@serathius - can you please double check this?

**Comment by serathius** [comment]
In etcd v3.5 etcdctl operations on data directory were deprecated and moved to new binary `etcdutl`.
Please update your recommendation to use `etcdutl snapshot restore --data-dir` instead of  `etcdctl snapshot restore --data-dir`.

**Comment by kbhawkey** [comment]
> 
> 
> In etcd v3.5 etcdctl operations on data directory were deprecated and moved to new binary `etcdutl`. Please update your recommendation to use `etcdutl snapshot restore --data-dir` instead of `etcdctl snapshot restore --data-dir`.

👋 @ganeshniyer . What do you think about applying the suggested changes?

**Comment by divya-mohan0209** [comment]
@ganeshniyer this has been fixed by #28601. Closing your PR since it is a duplicate.
/close.

**Pull request closed without merging**
