### PR TITLE
fix training partners on tablet & mobile

### PR DESCRIPTION
**Pull request by Arhell**
Hi!
issue #21142
This fix will make the iframe block **responsive**

### CODE REVIEW

**Comment by Arhell** [comment]
review page
https://deploy-preview-21183--kubernetes-io-master-staging.netlify.app/training/

**Comment by Arhell** [comment]
**test** on all major bowser & mobile devices

**Comment by jimangel** [comment]
Is this still needed since there's an upcoming new theme? https://github.com/kubernetes/website/pull/20874 (https://kubernetes-docsy-staging.netlify.app/training/)

**Comment by Arhell** [comment]
@jimangel 
Hi, at the moment I think yes
I just don’t know when there will be a new topic in the master

**Comment by Arhell** [comment]
irrelevant, new theme
/close

**Pull request closed without merging**
