### PR TITLE
[WIP] Bump PersistentVolumeClaim retention to beta

### PR DESCRIPTION
**Pull request by mattcary**
[KEP #1847](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/1847-autoremove-statefulset-pvcs)

K8s feature gate [PR #111300](https://github.com/kubernetes/kubernetes/pull/111300).

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @mattcary,

Is it intended to update the submodule `themes/docsy` as well?

**Comment by mattcary** [comment]
Oops, no. Some submodule thing. I thought I removed it already.

**Review by sftim — COMMENTED** [review]
Remember to update https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ as well.

**Comment by mattcary** [comment]
> Remember to update https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ as well.

thank you! done

**Comment by kbhawkey** [comment]
Hi @mattcary .
Is there any forward movement on these changes? I plan to close this pull request.

**Comment by kbhawkey** [comment]
@mattcary 
When you have time to look at the changes again, feel free to reopen this pull request.
/close

**Pull request closed without merging**
