### PR TITLE
Fix(`securing-a-cluster.md`): typo

### PR DESCRIPTION
**Pull request by owlet42**
"将" should be used here instead of "讲".

### CODE REVIEW

**Comment by jimangel** [comment]
Hey there! @owlet42, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
@owlet42 Please make sure you have signed the CLA in order for the PR to be reviewed.
Thanks.

**Comment by owlet42** [comment]
@jimangel 
I am sure I have signed the CLI, There(https://identity.linuxfoundation.org/user) contains my information
- First Name: chenlong
- Last Name: ma
- Full Name: chenlong ma
- E-mail address: owlet42@126.com

**Comment by tengqm** [comment]
@owlet42 Pls try `git config` and see if the user.email has been correctly set to the one you used for CLA. Then `git commit --reset-author --amend` followed by `git commit -f`.

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by tengqm** [comment]
Pls feel free to reopen and continue working on this when the CLA is ready.
/close

**Pull request closed without merging**
