### PR TITLE
remove out-of-date HA content

### PR DESCRIPTION
**Pull request by Bradamant3**
Confirmed with #sig-cluster-lifecycle that none of this content is current, so removing entire directory. Checked references to yaml and other included files; none present in /en (a few in /cn, but this PR won't break them)

/assign @steveperry-53

### CODE REVIEW

**Comment by steveperry-53** [comment]
Might need to remove yaml files from examples_test.

**Comment by Bradamant3** [comment]
good catch, thanks @steveperry-53 
also need to add redirect

/hold

**Pull request merged**
