### PR TITLE
Update logging.md

### PR DESCRIPTION
**Pull request by dialto1**
fixed a small typo

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
Hello @PulapakuraBros , please could you sign the CLA as instructed by the bot above so that we can review the PR?

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by bradtopol** [comment]
Hi @PulapakuraBros Thank you for your contribution.  Please sign the CLA so we can accept your PR for review.
/assign

**Comment by annajung** [comment]
Hi @thunderboltsquid, a friendly reminder to sign the CLA for the PR to be reviewed

**Comment by divya-mohan0209** [comment]
Hey @dialto1, please sign the CLA if you want us to further review the PR.

**Comment by dialto1** [comment]
alright I signed the agreement

**Comment by jimangel** [comment]
Hey there! @dialto1, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by dialto1** [comment]
i'm pretty sure i did

**Pull request closed without merging**
