### PR TITLE
zh-trans: modify content/zh/docs/concepts/workloads/controllers/garbage-collection.md

### PR DESCRIPTION
**Pull request by lpf7551321**
zh-trans: modify content/zh/docs/concepts/workloads/controllers/garbage-collection.md
Update: content/zh/docs/concepts/workloads/controllers/garbage-collection.md
Co-Authored-By: lpf7551321

### CODE REVIEW

**Comment by lpf7551321** [comment]
/

**Comment by xichengliudui** [comment]
/lgtm
@lpf7551321  thanks!

**Pull request merged**
