### PR TITLE
Fix incorrect command

### PR DESCRIPTION
**Pull request by kelvinn**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/28218#issuecomment-852076056

**Comment by jihoon-seo** [comment]
Netlify Preview is not available: https://deploy-preview-28218--kubernetes-io-master-staging.netlify.app/
image

/test all

**Comment by shannonxtreme** [comment]
LGTM for this specific change but also, we should fix the `master` and `slave` terminology. 

Relates to @jihoon-seo #30284

**Comment by kbhawkey** [comment]
Thanks @kelvinn .
I agree with the comments (no preview, task needs updating).
/approve

**Pull request merged**
