### PR TITLE
Federation Cleanup (1) doc: clean some outdate redirects and its associated content.

### PR DESCRIPTION
**Pull request by Colstuwjx**
As the title said, this PR is going to mainly cleanup the federation content inside `static/_redirects`.

Something inside `/docs/concepts/cluster-administration/federation.md` has been kept in this PR since there is PR #19525 , and those content should be cleaned once that PR merged.

What's more, the api references part inside this file is skipped right now, it will be followed by another separate PR.

Thanks.

### CODE REVIEW

**Comment by Colstuwjx** [comment]
Besides, if there is no exception case, the federation relative l10n pages should be cleaned by each l10n team.

**Comment by Colstuwjx** [comment]
/cc @zacharysarah @kbhawkey  @sftim .

Since this PR will change the site redirects.

**Comment by zacharysarah** [comment]
@Colstuwjx Thanks for opening this PR. It looks to me like it's headed in the right direction.

/lgtm

**Comment by zacharysarah** [comment]
@kbhawkey I have the nagging feeling you were having a conversation with someone else about federation PR timing at the 1.18 release. 

Is that correct, or am I hallucinating? 🍄 🥴

**Comment by kbhawkey** [comment]
Yep with @sftim in the umbrella issue. Suggested that we should go ahead an clean up the federation content.
👍

**Pull request merged**
