### PR TITLE
Remove resources folder from Git

### PR DESCRIPTION
**Pull request by lucperkins**
Somehow the `resources` folder keeps ending up in `master` (likely due to merges). This PR adds that folder to `.gitignore` to prevent this from happening.

It probably doesn't *hurt* to have that folder around but it's a potential source of confusion so better to eliminate it until we need it.

### CODE REVIEW

**Comment by steveperry-53** [comment]
@lucperkins Do you want to wait for review by @zparnold. Or would it be OK for me to just go ahead and merge this?

**Comment by lucperkins** [comment]
@steveperry-53 Feel free to merge. This folder is definitely not being used currently.

**Comment by Bradamant3** [comment]
Agree about the potential for reducing confusion (I know the presence of the folder when I build locally has been an issue for me ...)

/lgtm
/approve

**Pull request merged**
