### PR TITLE
Make glossary/kube-scheduler.md follow v1.17 of the original text

### LINKED ISSUE #21301: ja: Make glossary/kube-scheduler.md follow v1.17 of the original text
**This is a Feature Request**

**What would you like to be added**
Update glossary/kube-scheduler.md to follow v1.17 of the original (Englist) text.

**Why is this needed**
content/ja/docs/reference/glossary/kube-scheduler.md it outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.2/content/ja/docs/reference/glossary/kube-scheduler.md

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/reference/glossary/kube-scheduler.md

diff between translated and v1.17
https://gist.github.com/oke-py/48add3005eb3f9f36c7e4ab71dc2c967

**Note**
Currently, we use `dev-1.17-ja.2` branch. Please open a PR targeting the branch.

ref
[How To Contribute](https://kubernetes-docs-ja.kibe.la/shared/entries/c5878aa5-ad1f-4f29-a5bb-25853cbc14ec)
[翻訳スタイルガイド](https://kubernetes-docs-ja.kibe.la/shared/entries/5efe4fa7-d2a1-4a1d-8bc3-ce7ccdc064a6)

If you have a question, feel free to ask us here or slack.k8s.io #kubernetes-docs-ja channel.

### PR DESCRIPTION
**Pull request by y-taka-23**
Close #21301

Update the master to the control plane, add tooltips and little tweaks.

BTW, I'm not sure what is the "deadline" which affects scheduling decisions here. Do you have any good idea?

### CODE REVIEW

**Comment by inductor** [comment]
@y-taka-23 Are you talking about the way to translate 「有効期限」?

**Comment by y-taka-23** [comment]
@inductor Yes exactly. Actually it looks a little strange, but I cannot find the better term so left the original translation.

**Comment by inductor** [comment]
@y-taka-23 I would personally translate `期限`.

**Comment by y-taka-23** [comment]
@inductor Hmm... I doubt scheduling decisions depend on any types of "deadlines" -- as far as I know, kube-scheduler doesn't have such functionalities. I wish we could figure out what the deadlines mean and choose the better word.

**Comment by inductor** [comment]
@y-taka-23 If you are doubting the expression of the original document, maybe you should raise it up to the English document maintainers but not just the Japanese translation scope! 🙏

**Comment by y-taka-23** [comment]
@inductor Okay got it. Sorry for confusing you.

**Comment by inductor** [comment]
@y-taka-23 No it's all good. It was really insightful! I will approve this document now because it looks fine for now. If necessary, please make a new issue and we can probably discuss about it there :)

**Pull request merged**
