### PR TITLE
ru translation for project slogan

### PR DESCRIPTION
**Pull request by sftim**
Translate “Production-Grade Container Orchestration”

/language ru
/kind cleanup

Hope this is OK to target _master_ branch.

### CODE REVIEW

**Comment by sftim** [comment]
@dianaabv are you happy to /approve ? (that command is what Prow expects)

**Comment by Colstuwjx** [comment]
@dianaabv  We may need to merge PR by  @k8s-ci-robot ( it would call prow to do CI jobs ) at next time, rather than merging it by manually.

**Comment by dianaabv** [comment]
@Colstuwjx sure sorry, I was thinking it's ok for a minor change

**Pull request merged**
