### PR TITLE
Update website link in Readme and badges to readme (Korean) for consistency

### PR DESCRIPTION
**Pull request by daminisatya**

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Hi @daminisatya The https://img.shields.io/github/release/kubernetes/website.svg reads : release snapshot-initial-v1.13. I am afraid that this becomes a release update that has to be made for every release. Unless the svg automatically updates to read the latest release. OR may be we can have the SVG read: release latest.

**Comment by daminisatya** [comment]
@Rajakavitha1 It automatically picks the lastest release name from this link (https://github.com/kubernetes/website/releases/latest) and updates accordingly. 

Same with the build badge as well.

**Comment by Rajakavitha1** [comment]
> 
> 
> @Rajakavitha1 It automatically picks the lastest release name from this link (https://github.com/kubernetes/website/releases/latest) and updates accordingly.
> 
> Same with the build badge as well.

Thanks @daminisatya !!!

**Comment by daminisatya** [comment]
thank you @Rajakavitha1 😄

**Pull request merged**
