### PR TITLE
kubeadm: remove outdated unit file in kubeadm-init.md

### PR DESCRIPTION
**Pull request by neolit123**
Link to the kubelet-integration.md document instead.

cc @arianvp 
@kubernetes/sig-cluster-lifecycle-pr-reviews 
fixes kubernetes/kubeadm#1496

### CODE REVIEW

**Comment by detiber** [comment]
yikes, didn't realize this was still around. Happy to see it removed.

**Comment by timothysc** [comment]
@kubernetes/sig-docs-maintainers

**Pull request merged**
