### PR TITLE
Fix #12506 - misalignment of the community logos

### LINKED ISSUE #12506: Misalignment of the community logos
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Currently, the community logos are misaligned. Please refer to the screenshot. 

screen shot 1940-11-11 at 12 55 26 pm

**Proposed Solution:**

I hope the misalignment is clearly visible :) 

screen shot 1940-11-16 at 7 07 34 am

**Page to Update:**
https://kubernetes.io/community/

### PR DESCRIPTION
**Pull request by daminisatya**
Fix #12506 

/assign @stewart-yu
/assign @cody-clark 

I need help over here. Can you please help me on how I can compile the scss to css on my local. I'm able to see the changes by manually updating the css and scss, but looking for an option to directly compile scss to css while building my code. 

Thank you.

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hello @daminisatya, currently you need to compile the sass files to generate the relevant css files.
Do you have a local sass installation? See, https://sass-lang.com/install.
After you have a sass installation, run the sass target in the docs project Makefile.
Relevant css files will be created and need to be added and committed to your pull request.
These changes seem fine, though, I wonder why the div attributes are only in _tablet.sass and not in _base.sass.
If this is not clear, let me know. I ran the changes through a local branch and the updates look good.

**Comment by daminisatya** [comment]
@kbhawkey You are awesome!! ✨ 🙌 I was able to compile it. I just had a wrong sass installation which was not linked properly.

**Comment by Rajakavitha1** [comment]
@kbarnard10 could you please take a look at this PR and state your suggestions/approval.
The changes look good to me

**Comment by kbarnard10** [comment]
Thanks for the fix! @daminisatya Could you resolve the merge conflicts and then I'll approve?

**Comment by daminisatya** [comment]
@kbarnard10 I resolved the merge conflicts and tested the changes as well. Kindly review :)

**Pull request merged**
