### PR TITLE
Remove Master/Slave terminology from stateless application tutorial.

### PR DESCRIPTION
**Pull request by jimangel**
Opening this PR to complete efforts that were started in https://github.com/kubernetes/website/pull/22934/files

I need to do a tech review and can address any feedback. If WG Naming agrees, https://github.com/kubernetes/website/pull/22934/files can be closed in favor of this PR.

Many thanks to @paulczar for doing the heavy lifting!

/cc @kubernetes/wg-naming 

> The stateless application tutorial is littered with unsuitable terminology. This update switches the database technology to a database that has already updated their own terminology as well as removes the terminology from the tutorial itself.
> 
> The advanced logging tutorial followup is set to Draft as it will take a larger effort to convert that, and I'm not convinced its even in a working state right now.
> 
> A followup PR to the examples repo to be referenced here will be made.
> 
> Addresses #22918
> 
> Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
> 
> address comments in PR
> 
> Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
> 
> remove confusing comment about dns, we can assume k8s has kube-dns
> 
> Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

### CODE REVIEW

**Comment by sftim** [comment]
> I need to do a tech review

@jimangel how do you want to move forward / @tengqm, does your LGTM count as a review for accuracy?

**Comment by tengqm** [comment]
@sftim Yes, it does.

**Comment by sftim** [comment]
/approve
/holdf

@jimangel happy for you to /unhold

**Review by ydFu — APPROVED** [review]

**Review by nasirhm — APPROVED** [review]
LGTM

**Review by irvifa — COMMENTED** [review]
/hold cancel

**Pull request merged**
