### PR TITLE
[WIP] Reduce the size of the _redirects file

### PR DESCRIPTION
**Pull request by lucperkins**
Per Netlify's support channels, sites deployed to Netlify should expect a reduction in performance when there are 500 or more redirects, which is right about where we're at right now. This PR substantially reduces the size of the `_redirects` file by using Hugo's [aliases](https://gohugo.io/content-management/urls/#how-hugo-aliases-work) feature instead.

As an example, note that...

https://deploy-preview-10382--kubernetes-io-master-staging.netlify.com/docs/admin

...now successfully redirects to...

https://deploy-preview-10382--kubernetes-io-master-staging.netlify.com/docs/concepts/cluster-administration/cluster-administration-overview/

...without the need for an entry in `_redirects`.

### CODE REVIEW

**Comment by zparnold** [comment]
@lucperkins Could you please take a look at this merge conflict for me please?

**Comment by tengqm** [comment]
Need a rebase.
The blog file name cannot have dot ('.') in it.

**Comment by lucperkins** [comment]
I think that this would be beneficial but it's ton of work that I don't have the bandwidth for. If redirects become more of an issue I'll re-open. Closing for now.

**Pull request closed without merging**
