### PR TITLE
V1 hello-world app backend yaml definition has wrong indentation

### PR DESCRIPTION
**Pull request by sobi3ch**
This definition of example-ingress.yaml
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hello-world.info
    http:
      paths:
      - path: /
    backend:
      serviceName: web
      servicePort: 8080
```
should be fixed to this
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hello-world.info
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 8080
```
Check `backend:` part at the end of definition

### CODE REVIEW

**Comment by zacharysarah** [comment]
@sobi3ch 👋 Please verify that the email you used to sign the CLA is the same one attached to your GitHub ID.

**Comment by zacharysarah** [comment]
@sobi3ch 👋 Please feel free to `/reopen` when you're ready to continue.

/close

**Comment by sobi3ch** [comment]
I assume I can only wait now? `Not mergeable. Merging is blocked by issue 23399.`

**Comment by zacharysarah** [comment]
@sobi3ch :wave: Thanks for the fix, and thanks for your patience during the release. 

/lgtm
/approve

**Comment by sobi3ch** [comment]
@zacharysarah thanks! :)

**Pull request merged**
