### PR TITLE
generic ephemeral volumes: beta

### PR DESCRIPTION
**Pull request by pohly**
The feature is scheduled for becoming beta in 1.21.

### CODE REVIEW

**Comment by pohly** [comment]
/hold

This is currently a placeholder PR. The actual change in Kubernetes is currently pending for review in https://github.com/kubernetes/kubernetes/pull/99643 and some other PRs.

**Comment by savitharaghunathan** [comment]
Hi @pohly 👋  Can you change the target branch to `dev-1.21`? 
cc: @reylejano

**Comment by reylejano** [comment]
/milestone 1.21
/assign @mvortizr 
/sig storage
hold until kubernetes/kubernetes#99643  merges and target branch is changed to `dev-1.21`

**Comment by pohly** [comment]
> Can you change the target branch to dev-1.21?

See PR #26801 

/close

**Pull request closed without merging**
