### PR TITLE
Placeholder for 'kubectl events' docs

### PR DESCRIPTION
**Pull request by bboreham**
Docs for https://github.com/kubernetes/enhancements/issues/1440
PR is at https://github.com/kubernetes/kubernetes/pull/99557

I understand the docs will be generated following [this process](https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/)

### CODE REVIEW

**Comment by sftim** [comment]
Should this PR target the _dev-1.23_ branch @bboreham ?

BTW you usually don't need to open a PR for docs changes where these are entirely auto-generated: that happens during the release process anyway.

**Comment by bboreham** [comment]
I have changed the branch, @sftim.
I was asked to open this PR here: https://github.com/kubernetes/enhancements/issues/1440#issuecomment-925102702

**Comment by jlbutler** [comment]
@bboreham if the only changes required to support this enhancement for 1.23 are generated, then we don't need a PR. If that's the case, please feel free to close this out. Sorry for the noise!

cc @sftim

**Comment by kbhawkey** [comment]
Hi @bboreham .
As you know, the kubectl reference documentation is auto-generated by the kubectl reference generator tool.
The tool's configuration will need to be updated before the 1.23 release.
We could hold this PR as a placeholder until the release. You could also open a placeholder PR or issue in [kubernetes-sigs/reference-docs](https://github.com/kubernetes-sigs/reference-docs).

**Comment by chrisnegus** [comment]
@bboreham Today is the deadline for 1.23 Docs Ready for Review. Will docs updates happen automatically as noted above, allowing us to simply close this PR or is more work needing to be done?

**Comment by bboreham** [comment]
Advice here was to leave the docs unchanged as it's an alpha feature: https://github.com/kubernetes/enhancements/issues/1440#issuecomment-954139565

So I'll close this PR.

**Pull request closed without merging**
