### PR TITLE
[bn] Launch Bengali localization

### PR DESCRIPTION
**Pull request by mitul3737**
This PR is created to merge ` dev-1.23-bn.1` into `main` branch

Tracking issue: #31677

### CODE REVIEW

**Comment by sftim** [comment]
/retitle [bn] Merge dev-1.23 bn.1 into main

**Comment by sftim** [comment]
/hold

Before we unhold this, SIG Docs' localization group should check that the new localization is ready to launch

**Comment by mitul3737** [comment]
@sftim  I don't believe we are ready to launch. This PR was created just for the draft version of our future PR.

**Comment by divya-mohan0209** [comment]
Hello @mitul3737 is this ready for review, please?

**Comment by mitul3737** [comment]
Not yet @divya-mohan0209 . This PR is just for draft. We will mention you once we are done. Thank you.

**Comment by sftim** [comment]
Current build errors include:
```
ERROR 2023/04/14 14:24:59 [en] "docs/concepts/architecture/garbage-collection.md": "garbage-collection" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
ERROR 2023/04/14 14:24:59 [en] "docs/concepts/architecture/cloud-controller.md": "cloud-controller-manager" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
ERROR 2023/04/14 14:24:59 [en] "docs/concepts/architecture/controller.md": "controller" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
ERROR 2023/04/14 14:24:59 [en] "docs/concepts/architecture/cri.md": "container-runtime-interface" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
ERROR 2023/04/14 14:24:59 [en] "docs/concepts/configuration/configmap.md": "configmap" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
```

**Comment by sftim** [comment]
How's this work going?

**Comment by mitul3737** [comment]
> How's this work going?

We are almost done with all of the files. Just 2 files remaining before we create the PR. @sftim

**Comment by mitul3737** [comment]
@sftim I hope, we have done the basic localization and can move forward now.

**Comment by sftim** [comment]
Hi @mitul3737 

There are a few obstacles to cover:
- this PR is not mergeable (there is a merge conflict)
- the PR is still marked as draft
- the pull request fails to build
- this PR uses the deprecated `{{< param "fullversion" >}}` shortcode

**Comment by sftim** [comment]
How is progress?

You are welcome to work as a team towards adding a new localization; however, if there is no progress then a maintainer may close this pull request.

Even if that happens, you are welcome to continue the work and to open a new pull request if you find you have more capacity to contribute.

**Comment by sftim** [comment]
Is this OK to close? (in favor of https://github.com/kubernetes/website/pull/45009)

**Comment by asem-hamid** [comment]
@sftim  yes you can close this now .

**Comment by sajibAdhi** [comment]
> Is this OK to close? (in favor of #45009)

Yes, it is ok to close this PR.

**Pull request closed without merging**
