### PR TITLE
Removing GCE bridging/routing config tweaks

### PR DESCRIPTION
**Pull request by ixodie**
Removing this content seems to be appropriate:

Content does not contain a link to a CNI.
Content is not required for k8s to function.
Content seems to be replicated in longer form on the Google Cloud docs site.

### CODE REVIEW

**Comment by mkorbi** [comment]
I agree 
/lgtm

**Comment by ixodie** [comment]
@sftim @thockin @mkorbi Is there something else I need to do?

**Comment by ixodie** [comment]
Still waiting on this.

**Comment by ixodie** [comment]
@mkorbi @sftim @thockin Is there something else I need to do here?

**Comment by jimangel** [comment]
/lgtm
/approve

I think there's more here to clean up too, so I opened: https://github.com/kubernetes/website/issues/30745

**Pull request merged**
