### PR TITLE
Merged master into dev 1.21 - 1/13/21

### PR DESCRIPTION
**Pull request by reylejano**
Merge master into dev-1.21 to keep in sync - SIG-Release 1.21 Docs team 1/13/21

### CODE REVIEW

**Comment by annajung** [comment]
There are two commits with build errors which were resolved in the same PR

https://github.com/kubernetes/website/pull/26083/commits/f51174d518a5cee5e9499f41b01ac8035d818f6f was resolved as you can see from here https://github.com/kubernetes/website/pull/25843/commits

https://github.com/kubernetes/website/pull/26083/commits/9a386e5cac1c10d7f2664d711b727b690b89429c was resolved as you can see from here https://github.com/kubernetes/website/pull/25489/commits

/lgtm

Thanks Rey!

**Comment by savitharaghunathan** [comment]
`02c26ab` is related to https://github.com/kubernetes/website/pull/25489/commits which looks resolved as well.

**Comment by kbhawkey** [comment]
Hi @reylejano .
Any insight into PR #25489 and the deployment error/warnings:
```
WARN 2021/01/07 14:30:39 Failed to get translated string for language "pt" and ID "post_last_mod": %!s(<nil>)
9:30:39 AM: WARN 2021/01/07 14:30:39 Failed to get translated string for language "pt" and ID "post_edit_this": %!s(<nil>)
9:30:39 AM: WARN 2021/01/07 14:30:39 Failed to get translated string for language "pt" and ID "post_create_issue": %!s(<nil>)
```
Earlier today I tested a local build of the docs and saw these warnings.

**Comment by kbhawkey** [comment]
I logged an issue for the warnings: https://github.com/google/docsy/issues/415

**Pull request merged**
