### PR TITLE
[pl] Updated resources of README.md

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/43043/files
/assign @mfilocha

### CODE REVIEW

**Comment by mfilocha** [comment]
Thanks @Arhell 
/lgtm

**Comment by mfilocha** [comment]
Still no way to let localization owners to also own this one `README-pl.md` in the main folder?

**Comment by Arhell** [comment]
@sftim

**Review by Arhell — COMMENTED** [review]
@sftim  https://github.com/kubernetes/website/pull/43369#issuecomment-1751994231

**Pull request merged**
