### PR TITLE
Fix broken link to Localization READMEs

### LINKED ISSUE #44080: Broken quick navigation link for Localization in README.md
**This is a Bug Report**

**Problem:**
image

[Localizations READMEs](https://github.com/kubernetes/website#localization-readmemds) quick navigation link is broken 

**Proposed Solution:**
It looks like it's due to a small typo. 

image

**Page to Update:**
https://github.com/kubernetes/website/blob/main/README.md

### PR DESCRIPTION
**Pull request by rudrakshkarpe**
This PR fixes #44080 :)

### CODE REVIEW

**Review by Gauravpadam — COMMENTED** [review]
lgtm, Thanks for the fix!

**Comment by rudrakshkarpe** [comment]
> lgtm, Thanks for the fix!

My pleasure! thanks for reviewing :)

**Review by kumarankit999 — COMMENTED** [review]
Looking fixed now!!

**Review by dipesh-rawat — COMMENTED** [review]
Thanks!
/lgtm

**Review by kundan2707 — COMMENTED** [review]
/lgtm
thanks

**Pull request merged**
