### PR TITLE
修改guestbook.md

### PR DESCRIPTION
**Pull request by hide-in-code**
修正教程中【PHP 留言板应用程序】教程中错误的描述

### CODE REVIEW

**Comment by hide-in-code** [comment]
激动的心，颤抖的手🤣

**Comment by tengqm** [comment]
@hide-in-code Please sign the CLA in order for this to be reviewed.

**Comment by hide-in-code** [comment]
@tengqm I have already registered for CLA through my personal github account

**Comment by hide-in-code** [comment]
@tengqm I have already registered for CLA through my personal GitHub account, you may check it with username:hide-in-code which same as my GitHub username

**Comment by tengqm** [comment]
@hide-in-code Pls check if you need to recommit the code using your github id for CLA.

**Comment by hide-in-code** [comment]
@tengqm  okey, I will close this PR and recommit

**Pull request closed without merging**
