### PR TITLE
[bn] Updating README-bn.md and  README.md

### PR DESCRIPTION
**Pull request by asem-hamid**
Updating README-bn.md and adding 'Bengali' option in README.md

Fixes Issue : https://github.com/kubernetes/website/issues/44993
Related PR : https://github.com/kubernetes/website/pull/45009
Tracking Issue: https://github.com/kubernetes/website/issues/31677

### CODE REVIEW

**Comment by asem-hamid** [comment]
/language bn

@mitul3737   please review the bengali part

**Review by mitul3737 — APPROVED** [review]

**Review by mitul3737 — APPROVED** [review]

**Review by Imtiaz1234 — APPROVED** [review]

**Comment by sajibAdhi** [comment]
Hey @mitul3737 , @asem-hamid 
There is another PR [Bengali Language Support in README](https://github.com/kubernetes/website/pull/45829) for `README-bn. md`.

**Comment by mitul3737** [comment]
Thank you, @sajibAdhi , for bringing that PR to our attention.
I recommend closing that PR(#45829) in favor of this one.

**Review by divya-mohan0209 — COMMENTED** [review]
LGTM for the English Readme ONLY.

**Comment by asem-hamid** [comment]
@sftim  Requesting  for approval

**Review by sajibAdhi — APPROVED** [review]

**Comment by asem-hamid** [comment]
@sftim Requesting for approval

**Comment by asem-hamid** [comment]
@divya-mohan0209 Requesting for approval

**Comment by asem-hamid** [comment]
@divya-mohan0209  Requesting for Approval

**Review by lavishpal — APPROVED** [review]

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks for this change!
/approve

**Pull request merged**
