### PR TITLE
[ko] Update outdated files in dev-1.26-ko.1 (M174-M188)

### PR DESCRIPTION
**Pull request by jongwooo**
Signed-off-by: jongwooo <jongwooo.han@gmail.com>

## Description

Related Issue: #38458

Updated outdated files in `content/en/docs/tutorials/` and `content/en/docs/tutorials/kubernetes-basics/`.

**15 files to be modified**

- [x] M174.  `content/en/docs/tutorials/_index.md` | 1(+XS) 0(-)
- [x] M175.  `content/en/docs/tutorials/hello-minikube.md` | 1(+XS) 1(-)
- [x] M176.  `content/en/docs/tutorials/kubernetes-basics/_index.html` | 2(+XS) 0(-)
- [x] M177.  `content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html` | 2(+XS) 0(-)
- [x] M178.  `content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html` | 2(+XS) 0(-)
- [x] M179.  `content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html` | 2(+XS) 0(-)
- [x] M180.  `content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html` | 2(+XS) 0(-)
- [x] M181.  `content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html` | 2(+XS) 0(-)
- [x] M182.  `content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html` | 3(+XS) 0(-)
- [x] M183.  `content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html` | 2(+XS) 0(-)
- [x] M184.  `content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html` | 4(+XS) 6(-)
- [x] M185.  `content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html` | 2(+XS) 0(-)
- [x] M186.  `content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html` | 2(+XS) 0(-)
- [x] M187.  `content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html` | 2(+XS) 0(-)
- [x] M188.  `content/en/docs/tutorials/kubernetes-basics/update/update-intro.html` | 3(+XS) 0(-)

### CODE REVIEW

**Review by jongwooo — COMMENTED** [review]
M176-M188은 #34188 의 변경 사항을 적용하였습니다. #38458 에서 addition과 deletion이 반대로 표기된 것 같아 Comment 남깁니다!

**Review by seokho-son — COMMENTED** [review]
감사합니다!
/lgtm

**Pull request merged**
