### PR TITLE
Corrected description for resource limits and requests

### PR DESCRIPTION
**Pull request by joe-testra**
I believe the description deviated from the example.  Still learning this stuff though!

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
This **is** the wrong fix. Instead, we should highlight how you add up two lots of 64MiB to get the 128MiB request, and also add up the CPU values to get a sum.

It would help if the limits for the containers were different to the sums of the requests. I can see how that might confuse.

For example, try this manifest as the thing to explain in the text:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app # main app container
    image: images.my-company.example/app:v4
    resources:
      requests:
        memory: "384Mi"
        cpu: "250m"
      limits:
        memory: "768Mi"
        cpu: "1000m"
  - name: log-aggregator # logging sidecar
    image: images.external-provider.example/log-aggregator:v6
    resources:
      requests:
        memory: "16Mi"
        cpu: "125m"
      limits:
        memory: "16Mi" # same as the request
        cpu: "500m"
```

**Comment by sftim** [comment]
For that example, the Pod level memory request would be 400Mi. What do you think the CPU request would be for the Pod overall, @joe-testra?

**Comment by joe-testra** [comment]
Ahhh!  I see what I did wrong there; I was glossing over the fact that there were two different containers, and the description was thus the sum of those two.  Thanks for your explanation, that was a good way of pointing out my misunderstanding.  You are a strong communicator.  The requests for the cpu would be `375m` then.  I think your example would make it more difficult for others to make the same mistake as I did :)

**Comment by sftim** [comment]
If you'd be happy to re-revise the page @joe-testra (feel free to start a new PR if that's easier), I think the end result would be easier for newcomers to pick up. I hope you will, because you've spotted a place that confuses people, and those are the best places to make a fix.

**Comment by divya-mohan0209** [comment]
Hello @joe-testra , would you be interested in making the fix over a new PR? Or would you be continuing on this one itself?

**Comment by zacharysarah** [comment]
@joe-testra 👋🏻 Please feel free to `/reopen` when you're ready to respond to feedback.

/close

**Pull request closed without merging**
