### PR TITLE
docs: fix broken etcd's official documents link

### PR DESCRIPTION
**Pull request by 738**
This PR fixes broken etcd's official docs link in reference/glossary/etcd.md

- language
  - de
  - id
  - ko
  - zh

### CODE REVIEW

**Comment by irvifa** [comment]
Thanks for noticing this 🎉 
/lgtm

**Comment by irvifa** [comment]
@738 The CLA is still seems to be off, can you please sign it first?

**Comment by seokho-son** [comment]
Thank you for the contribution !
For the Ko content,
/lgtm
/approve

**Pull request merged**
