### PR TITLE
Update config.toml

### PR DESCRIPTION
**Pull request by jimangel**
updating old docs to reference 1.14, updating minor version numbers, and dropping 1.9.

### CODE REVIEW

**Comment by zacharysarah** [comment]
@lucperkins We'd love your input here.

For context: when we release a new version of the docs, we have to update the version selector in the previous four release branches. This requires four separate PRs to update `config.toml` in the respective release branches.

This PR (on Hugo v0.53) is failing. [Release 1.12 docs](https://v1-12.docs.kubernetes.io/) (on Hugo v0.49) continue to display the deprecation warning correctly. 

As near as @jimangel and I can tell, this PR may be failing due to changes introduced in #12079, specifically to syntax changes in the [deprecation warning](https://github.com/kubernetes/website/pull/12079/files#diff-56aee10bf840ac3f21111c869b923fc5R8). 

```sh
3:46:10 PM: ERROR 2019/03/25 22:46:10 "/opt/build/repo/content/ko/_index.html:7:1": failed to render shortcode "deprecationwarning": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/deprecationwarning.html:6:16": execute of template failed: template: shortcodes/deprecationwarning.html:6:16: executing "shortcodes/deprecationwarning.html" at <.Param>: can't evaluate field Param in type *hugolib.ShortcodeWithPage
3:46:10 PM: ERROR 2019/03/25 22:46:10 "/opt/build/repo/content/ja/_index.html:7:1": failed to render shortcode "deprecationwarning": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/deprecationwarning.html:6:16": execute of template failed: template: shortcodes/deprecationwarning.html:6:16: executing "shortcodes/deprecationwarning.html" at <.Param>: can't evaluate field Param in type *hugolib.ShortcodeWithPage
3:46:10 PM: ERROR 2019/03/25 22:46:10 "/opt/build/repo/content/fr/_index.html:7:1": failed to render shortcode "deprecationwarning": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/deprecationwarning.html:6:16": execute of template failed: template: shortcodes/deprecationwarning.html:6:16: executing "shortcodes/deprecationwarning.html" at <.Param>: can't evaluate field Param in type *hugolib.ShortcodeWithPage
3:46:10 PM: ERROR 2019/03/25 22:46:10 "/opt/build/repo/content/it/_index.html:7:1": failed to render shortcode "deprecationwarning": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/deprecationwarning.html:6:16": execute of template failed: template: shortcodes/deprecationwarning.html:6:16: executing "shortcodes/deprecationwarning.html" at <.Param>: can't evaluate field Param in type *hugolib.ShortcodeWithPage
3:46:10 PM: Total in 13696 ms
3:46:10 PM: Error: Error building site: "/opt/build/repo/content/en/_index.html:7:1": failed to render shortcode "deprecationwarning": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/deprecationwarning.html:6:16": execute of template failed: template: shortcodes/deprecationwarning.html:6:16: executing "shortcodes/deprecationwarning.html" at <.Param>: can't evaluate field Param in type *hugolib.ShortcodeWithPage
```

**Comment by jimangel** [comment]
/cc @seokho-son too as this could also be related to this PR: https://github.com/kubernetes/website/pull/12418

As the original CI tests would pass (since master isn't "deprecated") and fail on build as we sunset 1.13 docs (toggling to deprecated, which triggers the notice.html build).

I think we need to look very closely at what all is involved when https://github.com/seokho-son/website/blob/9a4e86dd5da30859bf9bc36d0975bd676c7b2251/layouts/shortcodes/deprecationwarning.html is generated.

**Comment by DanyC97** [comment]
> we have to update the version selector in the previous four release branches. This requires four separate PRs to update config.toml in the respective release branches.

wow, never thought that is the process today, ouch

**Comment by jimangel** [comment]
@zacharysarah @lucperkins @seokho-son  I think I see what is needed:

s/.Param/.Page.Param/ on [line 6](https://github.com/kubernetes/website/blob/master/layouts/shortcodes/deprecationwarning.html#L6)

Adding to this PR now...

**Comment by zacharysarah** [comment]
@jimangel Thanks for your work here!

Unrelated to this PR, I have a nit with the wording of the deprecation warning itself. I'm noting it here for reference in a follow-up PR.

Screen Shot 2019-03-26 at 12 49 16 PM

/lgtm
/approve

**Pull request merged**
