### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by JJJJJJJJJJJJJJJl**
Documentation fix. Secrets are not encrypted on write.

### CODE REVIEW

**Comment by enj** [comment]
There is no typo here - the current documentation is correct.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by bradtopol** [comment]
Thanks @JJJJJJJJJJJJJJJl for your contribution. Please sign the CLA so we can accept your PR for review

**Comment by JJJJJJJJJJJJJJJl** [comment]
Sorry for the absence, so given @enj statement, secrets are encrypted on write by default?

I might have misinterpreted the context, but why is it stated that they're are not at [https://kubernetes.io/docs/concepts/configuration/secret/](https://kubernetes.io/docs/concepts/configuration/secret/) then?

**Comment by enj** [comment]
We cleaned up the verbiage here to make it more clear, see https://github.com/kubernetes/website/pull/39110#issuecomment-1485889904

/close

**Pull request closed without merging**
