### PR TITLE
add cni-ipvlan-vpc-k8s 

### PR DESCRIPTION
**Pull request by bpownow**

### CODE REVIEW

**Comment by bpownow** [comment]
@tengqm how do i get this approved?

**Comment by Hartmarken348** [comment]
Jvc8

**Comment by bpownow** [comment]
@mistyhacks do you mind taking a look?

**Comment by mistyhacks** [comment]
This looks fine, but I'd prefer it if you'd wrap the lines at 80 characters for ease of reviews when this . content is updated.

/lgtm
/approve
/hold
(to give you a chance to address the feedback)

Just lift the hold when you have done this. Thanks!

**Comment by bpownow** [comment]
thanks @mistyhacks!

/hold cancel

**Pull request merged**
