### PR TITLE
updated README-hi.md

### LINKED ISSUE #29519: [hi] Fix README-hi.md
Problem: 
The sentence below in the README-hi.md seems to be incomplete 

"अपने fork में कोई भी परिवर्तन करना चाहते हैं, और जब आप उन परिवर्तनों को हमारे पास भेजने के लिए तैयार हों, तो अपने fork पर जाएं और हमें इसके बारे में बताने के लिए एक नया pull request बनाएं।"
 the first part i.e "अपने fork में कोई भी परिवर्तन करना चाहते हैं" makes no proper connection with the other part

### PR DESCRIPTION
**Pull request by AvineshTripathi**
fixed #29519

### CODE REVIEW

**Comment by anubha-v-ardhan** [comment]
/approve
Thank you @AvineshTripathi

**Review by anubha-v-ardhan — COMMENTED** [review]
Thanks

**Comment by AvineshTripathi** [comment]
> Thanks

Thank you for the help will be waiting for this to be merged

**Review by divya-mohan0209 — COMMENTED** [review]
/lgtm
@anubha-v-ardhan - your thoughts please?

**Comment by anubha-v-ardhan** [comment]
LGTM from me too.

**Pull request merged**
