### PR TITLE
Utilize code style for inline command in "included/verify-kubectl.md"

### PR DESCRIPTION
**Pull request by dev-johnn**
As requested in issue have marked the line as code.

Fixes https://github.com/kubernetes/website/issues/45851

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/retitle Utilize code style for inline command in "included/verify-kubectl.md"

**Review by dipesh-rawat — COMMENTED** [review]
Checking the build preview of the page [(here)](https://deploy-preview-45852--kubernetes-io-main-staging.netlify.app/docs/tasks/tools/install-kubectl-linux/#verify-kubectl-configuration) where this markdown is "included" using shortcode; the updated code style is working as expected. Thanks!

/lgtm

**Review by sftim — COMMENTED** [review]
/lgtm
/approve

**Comment by sftim** [comment]
@dev-johnn when you see issues marked as _good first issue_, please consider leaving them for people who have not yet worked on a Kubernetes website issue. That'll help us integrate new contributors.

**Pull request merged**
