### PR TITLE
[zh-cn] resync: docs/tasks/manage-kubernetes-objects/imperative-command.md

### PR DESCRIPTION
**Pull request by hs0210**
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>

### CODE REVIEW

**Review by Sea-n — CHANGES_REQUESTED** [review]
Please update commented English text as well.

**Comment by jihoon-seo** [comment]
Netlify build failed with no particular reason.
@hs0210 please (force-)push again to reflect [this suggestion](https://github.com/kubernetes/website/pull/35696#pullrequestreview-1061745372), then a new Netlify build will be triggered.

**Comment by hs0210** [comment]
> Please update commented English text as well.

@Sea-n Done. PTAL.

**Review by Sea-n — COMMENTED** [review]
/approve

**Pull request merged**
