### PR TITLE
ko: fix typo in cloud-controller-manager

### PR DESCRIPTION
**Pull request by seokho-son**
This PR fixes a typo in content/ko/docs/reference/glossary/cloud-controller-manager.md

The typo was reported by a Korean reader. 
Due to this is a minor typo fix, I'd like to apply this to master branch.

### CODE REVIEW

**Comment by pjhwa** [comment]
Thank you for fix this issue, @seokho-son 

/lgtm

**Comment by seokho-son** [comment]
Please check this PR can be approved :) 
/assign @gochist

**Pull request merged**
