### PR TITLE
KEP-4622: New topologyManager policy option: max-allowable-numa-nodes

### PR DESCRIPTION
**Pull request by cyclinder**
https://github.com/kubernetes/enhancements/issues/4622#issuecomment-2167918807

### CODE REVIEW

**Comment by mbianchidev** [comment]
Hey @cyclinder, it's Matteo from the 1.31 Release comms team. 
I'm reaching out with a reminder that the blog **ready for review deadline is July 26, 2024**. 

Please let me know how we can help with content, review or anything else 😄

**Comment by mbianchidev** [comment]
> Hey @cyclinder, it's Matteo from the 1.31 Release comms team. I'm reaching out with a reminder that the blog **ready for review deadline is July 26, 2024**.
> 
> Please let me know how we can help with content, review or anything else 😄

Just another reminder, it is totally ok if you don't have time to write this blog, if you do content should be ready for review by Friday this week. Could be a bit of a stretch but it is up to you!

**Comment by cyclinder** [comment]
>  it is totally ok if you don't have time to write this blog

Hi @mbianchidev, I'm sorry about that, I'm busy with working latest days, Can I write the blog next month?

**Comment by mbianchidev** [comment]
> > it is totally ok if you don't have time to write this blog
> 
> Hi @mbianchidev, I'm sorry about that, I'm busy with working latest days, Can I write the blog next month?

The content deadline would be this Friday, 26 of July.
Your current publication date is set for the 19th of August. 

Can you make it early August? Just to give time to our blog reviewers to keep the quality of the review high. 
You would also need to address review comments shortly before the publication date if that is ok.

I can work with you to review the content side but for a technical review you might want to ensure someone from the SIG takes a look at it before publishing!

Let me know what you think @cyclinder

**Comment by cyclinder** [comment]
> Can you make it early August? Just to give time to our blog reviewers to keep the quality of the review high.

@mbianchidev  I should be able to finish it early in August(first week of August). I'm sorry for the delay.

**Comment by mbianchidev** [comment]
Content should be delivered by the following updated dealine: **5th of August.**

@cyclinder just leaving this comment here for blog reviewers and a reminder never hurts!

**Comment by mbianchidev** [comment]
Reminder that the content deadline is Monday next week, **5th of August**.

@cyclinder

**Comment by cyclinder** [comment]
Sorry @mbianchidev, I've been troubled by something for the past two days, and now I'm writing.

**Comment by cyclinder** [comment]
Hi @mbianchidev @ffromani, Sorry for the delay, Could you have time to review the docs?  I'm not sure the document is in the right place. thanks!

**Comment by a-mccarthy** [comment]
Hi @cyclinder I'm Abbie the comms lead for 1.31 👋  I was just taking a look at you recent update, but i noticed it looks like docs updates. I think the docs for this feature were updated in https://github.com/kubernetes/website/pull/46870. 

If you are you still interested in writing a blog, we have a [blog contribution guide](https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/) that has more details about how/where to add blog content to the repo. 

cc: @mbianchidev

**Comment by cyclinder** [comment]
@a-mccarthy Sorry for my bad understanding, I thought the content of the document that needed to be added was the changes in the PR, which also is https://github.com/kubernetes/website/pull/46870, but it's actually a blog, and I think this KEP change is small enough not to need an additional Blog, what do you guys think?

/cc @mbianchidev

**Comment by mbianchidev** [comment]
hey @cyclinder sorry for the absence, I'm here now!

Thanks for clarifying your view on the blog and yes I think you are right, we can close this up as this can be deemed as a small change that doesn't require a full fledged blog for our users, the docs you submitted in the other PR will do a great job at informing them!

Thanks again for your cooperation :)

**Comment by cyclinder** [comment]
Thanks again, let me close this one!

/close

**Pull request closed without merging**
