### PR TITLE
Mark scheduler pod resource metrics as beta

### PR DESCRIPTION
**Pull request by smarterclayton**
They will be part of 1.21 as beta stability as of kubernetes/enhancements#1748

### CODE REVIEW

**Comment by ehashman** [comment]
@smarterclayton looks like your branch might need a rebase

**Review by ehashman — COMMENTED** [review]
/lgtm
for instrumentation

**Review by sftim — COMMENTED** [review]
> The metrics are exposed at the HTTP endpoint `/metrics/resources` and require the same authorization as the `/metrics` endpoint on the scheduler. You must use the `--show-hidden-metrics-for-version=1.20` flag to expose these alpha stability metrics.


Should that be:
> The metrics are exposed at the HTTP endpoint `/metrics/resources` and require the same authorization as the `/metrics`
> endpoint on the scheduler. You must use the `--show-hidden-metrics-for-version=1.21` flag to expose these beta stability metrics.

?

**Pull request merged**
