### PR TITLE
fix serviceaccount-token-volume-projection link

### PR DESCRIPTION
**Pull request by hunshcn**

### CODE REVIEW

**Comment by hunshcn** [comment]
one question: why didn't add linkchecker.py to ci test? Although lintchecker.py looks unintelligent, the error in this pr has not been found, but report some correct link.

**Review by PranitRout07 — COMMENTED** [review]
This looks good . /lgtm

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for fixing these link to the _"ServiceAccount token volume projection"_ section!
/lgtm

[Preview Page 1 ](https://deploy-preview-44557--kubernetes-io-main-staging.netlify.app//docs/tasks/configure-pod-container/configure-service-account/), [Preview Page 2](https://deploy-preview-44557--kubernetes-io-main-staging.netlify.app/docs/tasks/extend-kubernetes/setup-konnectivity/)

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
