### PR TITLE
Translate tasks/administer-cluster/kubeadm/kubeadm-upgrade/ in Korean

### LINKED ISSUE #20734: Translate tasks/administer-cluster/kubeadm/kubeadm-upgrade/ in Korean
**This is a Feature Request**

**What would you like to be added**

Translate tasks/administer-cluster/kubeadm/kubeadm-upgrade/ in Korean.

**Why is this needed**

There is no document of docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ which translated into Korean

**Comments**

Page to translate: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

/language ko

### PR DESCRIPTION
**Pull request by pjhwa**
This fixes #20734 .

This PR contains the following files which translated into Korean:
- content/ko/docs/tasks/administer-cluster/kubeadm/_index.md
- content/ko/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md

### CODE REVIEW

**Comment by pjhwa** [comment]
Deploy preview: https://deploy-preview-20744--k8s-dev-ko.netlify.app/ko/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by gochist** [comment]
@pjhwa 감사합니다!
@ysyukr 작성자와 제가 같은 회사 소속이므로 다른 승인자의 승인을 요청드립니다.

/lgtm
/unassign
/assign @ysyukr

**Comment by ysyukr** [comment]
@pjhwa @gochist 고생하셨습니다.
/approve

**Pull request merged**
