### PR TITLE
[zh-cn]Fix delete extra words“，”

### PR DESCRIPTION
**Pull request by javadoors**
删除多余的“，”

### CODE REVIEW

**Comment by tengqm** [comment]
The English upstream has a cleanup merged, recently.
Ideally, I'd expect this PR to sync the full page again.

**Comment by javadoors** [comment]
> The English upstream has a cleanup merged, recently. Ideally, I'd expect this PR to sync the full page again.

Ok,can I close this PR first?

**Comment by windsonsea** [comment]
Need not close this PR. You can add changes locally, and then:

```git
git commit --amend --no-edit
git push origin patch-24 -f
```

**Comment by windsonsea** [comment]
已更新详细的指示说明，请按顺序操作即可。

**Comment by javadoors** [comment]
> git commit --amend

已按照操作处理，请帮忙看看有没有问题，谢谢

**Comment by windsonsea** [comment]
Seems nothing changed in the last commit. Have you forgotten to edit and save before you run those commands above?

**Comment by javadoors** [comment]
> Seems nothing changed in the last commit. Have you forgotten to edit and save before you run those commands above?

In the master branch,I can't see any changes to the file,
[Cleanup node-pressure-eviction.md](https://github.com/kubernetes/website/commit/3aa5fe0cca9831b587ee10400c8983e49f770edc)
2 weeks ago

**Comment by windsonsea** [comment]
In the master branch, check our your own `patch-24` to edit it:
```
git checkout patch-24
```

**Comment by javadoors** [comment]
The first use the rebase command,he echo below is :
----------------------------------
$ git status
interactive rebase in progress; onto eebc10426f
Last commands done (175 commands done):
   pick ed9ea9c4f2 kubeadm: apply changes around "master" taint for 1.25
   pick edb74f1dec update kubeadm pages to use registry.k8s.io
  (see more in file .git/rebase-merge/done)
Next commands to do (2871 remaining commands):
   pick 90dc4e70a6 kubeadm-init.md: adjust info for UnversionedKubeletConfigMap
   pick fefcf46922 kubeadm: document the option to use kubeletconfiguration patches
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'patch-24' on 'eebc10426f'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working tree clean

**Comment by tengqm** [comment]
Looks like the whole file is still well in sync.
/lgtm
/approve

**Pull request merged**
