### PR TITLE
replace 'the Master' to 'the Control Plane'

### PR DESCRIPTION
**Pull request by uhziel**
## what will change
replace 'the Master' to 'the Control Plane'

## why
'the Master' is a old word.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/28684#issuecomment-870584263

**Comment by uhziel** [comment]
I signed it

**Comment by tengqm** [comment]
You don't have to spell it as "Control Plane", just "control plane" would be fine.

**Pull request merged**
