### PR TITLE
Fix cpu request limit exmaples use the default namespace

### PR DESCRIPTION
**Pull request by nashasha1**
Specify the namespace to `cpu-example`. So, users can copy the yaml and run the task directly.

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6980)

### CODE REVIEW

**Comment by nashasha1** [comment]
@tengqm  Thanks for your review. But now, users need to specify namespace in every yaml if they want to complete the whole task that is really inconvenient . After pr, people could copy the yaml directly.

**Comment by tengqm** [comment]
@nashasha1 I wasn't saying this is not correct or unacceptable. I was feeling a trade-off here. You may want to hard code the namespace into a resource manifest for convenience. Next time, when you want to do the same thing in a different namespace, you will need to change the manifest.
So, I'm neutral here.

**Comment by nashasha1** [comment]
@tengqm  Oh I see. thanks for your reply. 
I thought the yaml is unique. it belongs to this task. no other places refer it.  If users want to use it in other places, they should know replace the namespace.

**Comment by nashasha1** [comment]
ping @abiogenesis-now

**Comment by heckj** [comment]
hi @nashasha1  - would you restrict this to the non `cn/` content? I would love to have the same content applied to kubernetes/kubernetes-docs-cn. but don't want to mix them within a single PR

/assign

**Comment by nashasha1** [comment]
@heckj  Done. Thanks for your reply.

**Pull request merged**
