### PR TITLE
id translation for project slogan

### PR DESCRIPTION
**Pull request by sftim**
Translate “Production-Grade Container Orchestration”

/language id
/kind cleanup

Hope this is OK to target _master_ branch.

### CODE REVIEW

**Comment by gochist** [comment]
Re-assign to the next [PR wrangler after winter holidays](https://github.com/kubernetes/website/wiki/PR-Wranglers)

/unassign
/assign @mistyhacks

**Comment by mistyhacks** [comment]
Sorry, I am no longer an active maintainer.

**Comment by sftim** [comment]
@bradtopol this one is just awaiting approval

**Comment by girikuncoro** [comment]
sorry for the delay, thanks for this!

/lgtm
/approve

**Comment by sftim** [comment]
Based on https://github.com/kubernetes/website/pull/18264#issuecomment-568728714:
/approve

**Pull request merged**
