### PR TITLE
wip [ar] init localization basic structure and translate home

### PR DESCRIPTION
**Pull request by mboukhalfa**
This PR init ar localization by creating basic structure and and translate home docs. It should target the dev-1.25-ar.1 once it is created

/language ar

### CODE REVIEW

**Comment by sftim** [comment]
Thanks for making a start on this.

/hold

We should not launch the Arabic localization by merging directly into _main_; instead, we should work on a branch until the localization is ready to launch.

**Comment by mboukhalfa** [comment]
> Thanks for making a start on this.
> 
> /hold
> 
> We should not launch the Arabic localization by merging directly into _main_; instead, we should work on a branch until the localization is ready to launch.

Yeah I mentioned that already in the description I will be waiting for maintainers to help with creating a hosting branch then I will change the target Branch

**Comment by adowair** [comment]
Hey @mboukhalfa, checking in on your progress here. I'd love to contribute to this issue. @sftim is it right to assume that any PRs towards this issue should target (new) branch `dev-1.19-ar.1`?

**Pull request closed without merging**
