### PR TITLE
Remove CI/CD Pipeline section in tutorials

### LINKED ISSUE #23167: Tutorials overview links to outdated CI/CD Pipeline pages
**This is a Bug Report**

CI/CD Pipeline utorials  horribly out of date.  Depends on kubernetes 1.6

**Proposed Solution:**
I wish I had the time to work on this.  Remove it or update it.

**Page to Update:**
https://kubernetes.io/...

https://kubernetes.io/docs/tutorials/
Links to out of date tutirial: CI/CD Pipeline

### PR DESCRIPTION
**Pull request by habibrosyad**
Closes #23167

### CODE REVIEW

**Comment by mkorbi** [comment]
looks good for DE
/approve

**Comment by girikuncoro** [comment]
LGTM for ID 👍

**Comment by zacharysarah** [comment]
@habibrosyad Please limit changes to [one language per PR](https://kubernetes.io/docs/contribute/new-content/overview/#languages-per-pr). In this case, please limit this PR to English.

/hold

**Comment by habibrosyad** [comment]
@zacharysarah sorry for that, missed that part 😅

**Comment by habibrosyad** [comment]
Removing labels for other languages (maybe later in separate PRs) and limit this PR to English for now.

/remove-language zh 
/remove-language uk
/remove-language ru
/remove-language pt
/remove-language pl
/remove-language ko
/remove-language ja
/remove-language it
/remove-language id
/remove-language fr
/remove-language es
/remove-language de

**Pull request merged**
