### PR TITLE
Fix typo web-ui-dashboard.md

### PR DESCRIPTION
**Pull request by chrismclennon**

### CODE REVIEW

**Comment by chrismclennon** [comment]
Just signed the CLA

**Comment by tengqm** [comment]
try close and open again and see if cla check passes.

**Comment by tengqm** [comment]
@chrismclennon You may have to check your CLA status again. Hints here: https://identity.linuxfoundation.org/projects/cncf

**Comment by cody-clark** [comment]
Hi @chrismclennon, thanks for catching that typo. I can't merge your fix until the CLA is signed. Please double check the CLA.

> If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.

> 📝 Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

**Comment by Rajakavitha1** [comment]
Hi @chrismclennon, I am closing this PR now. However, you can always reopen the PR after you sign the CLA.   You can follow the instructions here: https://git.k8s.io/community/CLA.md#the-contributor-license-agreement.

**Pull request closed without merging**
