### PR TITLE
Upgrade 1.13 to Hugo 0.57.2

### LINKED ISSUE #16066: Broken link to latest Kubernetes documentation
**This is a Bug Report**

**Problem:**
https://v1-15.docs.kubernetes.io/docs/ hyperlinks to the latest documentation, except that the link is actually to https://v1-14.docs.kubernetes.io/docs/ (because the `href` is null).

(oops!)
Here's the markup:
```html
<div class="content deprecation-warning">
      <h3>
	 Kubernetes v1.15
	  documentation is no longer actively maintained. The version you are currently viewing is a static snapshot. For up-to-date documentation, see the 
	 <a href="">latest version.</a>
      </h3>
    </div>
```

**Proposed Solution:**
Fix the link so that it takes readers to https://kubernetes.io/docs/

**Pages to Update:**
https://v1-15.docs.kubernetes.io/docs/
https://v1-14.docs.kubernetes.io/docs/
https://v1-13.docs.kubernetes.io/docs/

### PR DESCRIPTION
**Pull request by zacharysarah**
Fixes #16066 

EDIT: #16066 exhibits behavior characteristic of https://github.com/gohugoio/hugo/issues/5615. To resolve the issue, we need to upgrade Hugo to a version that includes the solution.

### CODE REVIEW

**Comment by sftim** [comment]
:eyes:

**Comment by sftim** [comment]
I have a suspicion that Hugo is having problems turning `<h2>` elements into a table of contents, if the text contains an apostrophe character, eg:
```
## Exceed a Container's memory limit
```

**Comment by sftim** [comment]
https://github.com/kubernetes/website/blame/master/content/en/docs/tasks/configure-pod-container/assign-memory-resource.md#L129 has an apostrophe in a second-level heading.

It seems OK to have a _What's next_ section that renders (in the English localization) with an apostrophe. My hypothesis is that apostrophes in the source markdown (lines starting `##`) are a problem.

**Comment by zacharysarah** [comment]
@sftim
> It seems OK to have a What's next section that renders (in the English localization) with an apostrophe. My hypothesis is that apostrophes in the source markdown (lines starting ##) are a problem.

That checks out. The "What's Next" line populates from a template:
```md
{{% capture whatsnext %}}
```
But it scrambles any content that follows.

It also looks like Hugo is trying to populate "error" sections with another template: https://github.com/kubernetes/website/blob/master/layouts/partials/templates/errorthrower.html

**Comment by zacharysarah** [comment]
I've opened a Hugo issue: https://github.com/gohugoio/hugo/issues/6277

In the meantime, there is literally no way this PR should merge.

/close

**Comment by zacharysarah** [comment]
From https://github.com/gohugoio/hugo/issues/6277#issuecomment-526389964:

> I just tested the Kubernetes site with the version in kubernetes/website#13680 with the latest Hugo and it works fine. You're right that it doesn't work with the current Kubernetes master, but that must just mean that someone has somehow undone the fixes that I applied.

The commit hash for #13680 is [`b51bdc8`](https://github.com/kubernetes/website/commit/b51bdc88ccd5a0146e81b61d1873ad3f8d876478). 

Only one file affected by #13680 has received subsequent updates: [`layouts/case-studies/list.html`](https://github.com/kubernetes/website/blob/master/layouts/case-studies/list.html), updated in [#13832](https://github.com/kubernetes/website/pull/13832/files#diff-f50da96fabb828e23a7126968f44c0b6L54-R54).

At https://kubernetes.io/case-studies/ the `alt` text attribute renders as expected:
```html
<img src=https://d33wubrfki0l68.cloudfront.net/1f25fd3bb7209410ad60613770321deb5959c2e6/e2c98/images/case_studies/story.png alt="Tell your story"></a>
```

So it appears to be a question of whether we want internationalization to work correctly, or for 0.57.2 to work correctly.

**Comment by zacharysarah** [comment]
Yup, sure enough: upgrading to 0.57.2 _and_ cherry picking `b51bdc8` into `release-1.13` fix things great.

@sftim 👋 Take a look around.
https://deploy-preview-16104--k8s-v1-13.netlify.com/docs/home/

**Comment by zacharysarah** [comment]
Side note: Because this PR still invokes Travis (which is dead and gone from our stack), we'll either need to cherry pick the Travis-killing commit into this PR or admin merge it.

**Comment by sftim** [comment]
@zacharysarah I took that look around and things looked fine!

**Comment by sftim** [comment]
[I hope] I can also take some time this coming Sunday to look into the issue more.

**Comment by BenTheElder** [comment]
_trying something re:travis_
/close

**Comment by BenTheElder** [comment]
I think a repo admin can `/override continuous-integration/travis-ci/pr` to have prow force it green https://prow.k8s.io/command-help#override but of course just clicking merge works

**Comment by jimangel** [comment]
Looks like it passed?

/lgtm

**Comment by zacharysarah** [comment]
@chenopis 👋 Hey there, [PR wrangler](https://github.com/kubernetes/website/wiki/PR-Wranglers)! Could you please `/approve` this? Thanks in advance.

**Comment by kbhawkey** [comment]
hi @zacharysarah . I read through the changes. For my information, this branch built a month ago with Hugo 0.57.2? I am trying to understand the open/close and back/forth of this PR. What changed to make the branch pass?

**Comment by zacharysarah** [comment]
@kbhawkey Thanks for the review.

> I am trying to understand the open/close and back/forth of this PR. What changed to make the branch pass? Also, what about o cherry pick the Travis-killing commit into this PR or admin merge it?

See 16104#issuecomment-526452509 ☝️ for details on both.

**Pull request merged**
