### PR TITLE
Update enforce-standards-admission-controller.md

### PR DESCRIPTION
**Pull request by yanrongshi**

### CODE REVIEW

**Comment by Sea-n** [comment]
You have opened four PR for very small (and un-noticeable for current version) sync. Could you merge them into one?
- #34406
- #34407
- #34408
- #34409

Futher more, it's better to fix format errors and make sentences more fluent.

**Review by sftim — COMMENTED** [review]
LGTM

**Comment by sftim** [comment]
@Sea-n a word of caution. Each PR that is reviewed should encompass _one_ set of changes. Not several. Please avoid implying otherwise.

@yanrongshi when you open localization PRs, and you are making changes that are **not related**, then it is OK to open separate PRs. If you are opening more than one PR against the same page or set of pages (such as to localize three tasks that all relate to Secrets), then we'd be right to ask you to combine those.

Sorry about the misleading advice here. Again, the key principle is that a PR should represent a single and identifiable set of changes.

**Comment by yanrongshi** [comment]
> @Sea-n一句警告。_审查的_每个 PR 都应包含一组更改。不是几个。请避免以其他方式暗示。
> 
> @yanrongshi当您打开本地化 PR，并且您正在进行**不相关**的更改时，可以打开单独的 PR。如果您针对同一页面或一组页面打开多个 PR（例如本地化三个都与 Secrets 相关的任务），那么我们要求您将它们结合起来是正确的。
> 
> 很抱歉这里的误导性建议。同样，关键原则是 PR 应该代表一组单一且可识别的更改。

thanks，my brother，this is my first PR,so what should i do in the next time

**Pull request merged**
