### PR TITLE
fix: error message

### PR DESCRIPTION
**Pull request by gosoon**
Fix [#20241](https://github.com/kubernetes/website/issues/20421)

### CODE REVIEW

**Comment by tanjunchen** [comment]
@gosoon
thank you for the PR! 
I would recommend only fixing one language per PR so it does not conflict with other localization teams.
such as : /en pr , /zh pr

Let me know if you have any questions!

**Comment by gosoon** [comment]
@tanjunchen OK，I just modified en doc in this pr.

**Comment by tanjunchen** [comment]
> @tanjunchen OK，I just modified en doc in this pr.

right.

/cc @jimangel 
for en owner

**Pull request merged**
