### PR TITLE
Fix invalid command (kubectl rolling-update)

### PR DESCRIPTION
**Pull request by nonylene**
`kubectl rolling-update` is the right command.

Doc: https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/

### CODE REVIEW

**Comment by ryanmcginnis** [comment]
hey, @nonylene. were you able to sign the CLA necessary to contribute to the repo?

**Comment by nonylene** [comment]
> hey, @nonylene. were you able to sign the CLA necessary to contribute to the repo?

I get a bit problem on my CLA signing process and have requested a support from Linux Foundation. Please wait for a while...

**Comment by ushuz** [comment]
AFAIK, `kubectl rolling-update` is deprecated. Maybe the "Alternative to Deployments" section should be removed instead?
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-strong-deprecated-commands-strong-

**Pull request merged**
