### PR TITLE
Mark PSP deprecated in the docs

### PR DESCRIPTION
**Pull request by tallclair**
See kubernetes/kubernetes#97171

### CODE REVIEW

**Comment by tengqm** [comment]
need to update the content/en/docs/reference/command-line-tools-reference/feature-gates.md as well.
[KEP5](https://github.com/kubernetes/enhancements/issues/5)
[Upstream](https://github.com/kubernetes/kubernetes/pull/97171)

**Comment by tallclair** [comment]
Sorry, what changes are you looking for to the feature gates reference? PSP doesn't have an associated feature gate (predates feature concept).

**Comment by reylejano** [comment]
/hold cancel
@tallclair My mistake, feature-gates.md does not have to be updated

This is deprecation guide is a new page, does it need to be updated?
https://kubernetes.io/docs/reference/using-api/deprecation-guide/

**Comment by tallclair** [comment]
Ah, yes. That one should be updated.

/hold

**Comment by tallclair** [comment]
Whoops, looks like that doesn't exist no the dev-1.21 branch. I'll open a separate PR for that.

/hold canceln

**Comment by reylejano** [comment]
> Whoops, looks like that doesn't exist no the dev-1.21 branch. I'll open a separate PR for that.
> 
> /hold cancel

@tallclair  I'll do a `dev-1.21` branch sync, that file will be there when the PR merges

**Pull request merged**
