### PR TITLE
[ja] s/クラスタ/クラスター/g

### PR DESCRIPTION
**Pull request by ystkfujii**
- translate "cluster" to "クラスター", not "クラスタ".
  - ref: https://kubernetes.io/ja/docs/contribute/localization/#%E9%A0%BB%E5%87%BA%E5%8D%98%E8%AA%9E

---

I executed the following command.

```bash
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタで/クラスターで/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタは/クラスターは/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタに/クラスターに/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタの/クラスターの/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタや/クラスターや/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタを/クラスターを/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタ用/クラスター用/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタ内/クラスター内/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタ上/クラスター上/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタIP/クラスターIP/g' {} \; 
find ./content/ja/ -type f -name '*.html' -exec sed -i -e 's/クラスタの/クラスターの/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタ全体/クラスター全体/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタ設定/クラスター設定/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタノード/クラスターノード/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタ管理者/クラスター管理者/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタIP/クラスターIP/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタアドオン/クラスターアドオン/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタオペレーター/クラスターオペレーター/g' {} \; 
```

Looks good to me.

```bash
$ find ./content/ja/ -type f -name '*.md' | xargs grep -v 'クラスター' | grep --color 'クラスタ'
./content/ja/docs/setup/production-environment/tools/kubeadm/ha-topology.md:詳細については、etcd[クラスタリングガイド](https://github.com/etcd-io/etcd/blob/release-3.4/Documentation/op-guide/clustering.md#static)をご覧ください。
$ find ./content/ja/ -type f -name '*.html' | xargs grep -v 'クラスター' | grep --color 'クラスタ'
$ 
```

### CODE REVIEW

**Comment by ystkfujii** [comment]
@atoato88 

Thanks for the review.
You are right, the target is still there...


I additionally executed the following command.

```bash
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタが/クラスターが/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタID/クラスターID/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタと/クラスターと/g' {} \; 
find ./content/ja/ -type f -name '*.md' -exec sed -i -e 's/クラスタ環境/クラスター環境/g' {} \; 
```

And I also did squash.

**Comment by atoato88** [comment]
/lgtm

Thank you for quick update & it looks perfect for me!! :smile:

**Comment by atoato88** [comment]
/assign @nasa9084 
Could you review this?

**Review by nasa9084 — COMMENTED** [review]
Thank you, 
/approve

**Pull request merged**
