### PR TITLE
Release Notes (correction)

### PR DESCRIPTION
**Pull request by butuzov**
The link to the CRD page ( check link in `CustomResourceDefaulting`
description of Beta section) corrected (before its was generating 404 
due to an encoded anchor symbol.).

### CODE REVIEW

**Comment by sftim** [comment]
Does this need correcting anywhere upstream? Or a fix to the generator code?

**Comment by butuzov** [comment]
@sftim good and valid point. kubernetes/kubernetes#82252 and kubernetes/kubernetes#81872 both introducing a link with anchor. one threated "ok", one "isn't". 

Who can we ask about the generator and how it works?

**Comment by tengqm** [comment]
I just did some research on this. It looks like the upstream code is here:
https://github.com/kubernetes/release/blob/master/pkg/notes/notes.go#L519

For release notes to be properly processed by the code, the notes itself is supposed to be put under "Does this PR introduce a user-facing change" section in  the commit message. E.g. kubernetes/kubernetes/#82252For some reasons, we have PRs not doing this, e.g. kubernetes/kubernetes/#81872. The generator has some logic to process the notes in different ways: https://github.com/kubernetes/release/blob/master/pkg/notes/notes.go#L262

**Comment by butuzov** [comment]
@tengqm Will handle it? (i am not familiar with `release` tools) or I guess there is a slack channel about releases where members can be interested in this info...

**Comment by oQuantumDecayo** [comment]
> The link to the CRD page ( check link in `CustomResourceDefaulting`
> description of Beta section) corrected (before its was generating 404
> due to an encoded anchor symbol.).

**Comment by oQuantumDecayo** [comment]
> > The link to the CRD page ( check link in `CustomResourceDefaulting`
> > description of Beta section) corrected (before its was generating 404
> > due to an encoded anchor symbol.).

**Comment by oQuantumDecayo** [comment]
> @tengqm Will handle it? (i am not familiar with `release` tools) or I guess there is a slack channel about releases where members can be interested in this info...

**Pull request merged**
