### PR TITLE
[zh-cn] Update kubernetes-basics

### PR DESCRIPTION
**Pull request by xuruidong**
the description before is confused

### CODE REVIEW

**Review by my-git9 — CHANGES_REQUESTED** [review]
Please use the following command to detect the synchronization status of the English document and modify it together. Thanks!

```
./scripts/lsync.sh content/zh-cn/docs/tutorials/kubernetes-basics/_index.html
```

**Comment by xuruidong** [comment]
> Please use the following command to detect the synchronization status of the English document and modify it together. Thanks!
> 
> ```
> ./scripts/lsync.sh content/zh-cn/docs/tutorials/kubernetes-basics/_index.html
> ```

Hi:
I run the command and get follwing result:
```
content/zh-cn/docs/tutorials/kubernetes-basics/_index.html is still in sync
```
image

**Comment by tengqm** [comment]
@xuruidong Please run the command in the `main` branch. Your patch-1 branch is "contaminated".

**Comment by xuruidong** [comment]
> @xuruidong Please run the command in the `main` branch. Your patch-1 branch is "contaminated".

@tengqm  Thanks for your reminder！
@my-git9 Please review again, thanks!

**Comment by my-git9** [comment]
LGTM, please squash your commit: https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

**Comment by xuruidong** [comment]
> LGTM, please squash your commit: https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

@my-git9  
 Done !

**Comment by my-git9** [comment]
/lgtm
Thanks

**Pull request merged**
