### PR TITLE
[de] update the html tags

### PR DESCRIPTION
**Pull request by aanchal88**
The strong/b tags have exactly the same effect in most web browsers, but there is a fundamental difference between them: strong tag have a semantic meaning whereas b tag only convey styling information like CSS.

### CODE REVIEW

**Comment by aj11anuj** [comment]
What's the need of changing these tags? It doesn't make any as such difference.

/remove-language de
/area web-development

**Review by aj11anuj — COMMENTED** [review]
Original K8s file in english, contain `<b>` tag everywhere instead of `<strong>` tag. So, i think these `<b>` tags should not be changed with `<strong>` tag without any valid reason.

**Comment by windsonsea** [comment]
Both tag convey the same meaning in html, but <b> is shorter. Personally, I prefer the shorter option as well.

**Comment by reylejano** [comment]
@aanchal88 Please add a description that describes the proposed change in this PR

**Comment by aanchal88** [comment]
Hii @reylejano , updated the description please review.
Thanks

**Pull request closed without merging**
