### PR TITLE
Add docs for ExpandedDNSConfig feature gate

### PR DESCRIPTION
**Pull request by gjkim42**
Add ExpandedDNSConfig feature gate option to kubelet, kube-apiserver(sync with feature-gates.md)

This PR should have been included in https://github.com/kubernetes/website/pull/28096

PRs: 
https://github.com/kubernetes/kubernetes/pull/100651

KEP: 
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2595-expanded-dns-config

Enhancement issue: 
https://github.com/kubernetes/enhancements/issues/2595

### CODE REVIEW

**Comment by gjkim42** [comment]
/cc @aojea @thockin 
I missed some docs for ExpandedDNSConfig.
Could you PTAL?

**Comment by tengqm** [comment]
DOT NOT EDIT THESE FILES.
The reference files are auto-generated. They will be updated when a new version of Kubernetes is out of the door.
/close

**Comment by gjkim42** [comment]
@tengqm 

> DOT NOT EDIT THESE FILES.
> The reference files are auto-generated. They will be updated when a new version of Kubernetes is out of the door.
> /close

Even after v1.22 is live, it seems that we can't see any changes.

**Comment by tengqm** [comment]
@gjkim42 During every release cycle, the references are generated after the release is out. There will be a few days delay because we need to adapt the generator to the latest release. This is done now.

**Pull request closed without merging**
