### PR TITLE
Added the initial of the Russian language for the link

### PR DESCRIPTION
**Pull request by berikulyBeket**
Added the initial of the language ("ru") for the page link in the documentation

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please change the commit to the English version and the name of the PR too, thank you.

Here is an example https://github.com/kubernetes/website/pull/45674

git reset --soft head~1 then force push

**Comment by utkarsh-singh1** [comment]
Hi @berikulyBeket, can you check your Email from which you have force push.

**Comment by utkarsh-singh1** [comment]
Seems like there is a difference between latest committed Email-Id and old one, that's why EASY CLA not authorized occured.

**Comment by shurup** [comment]
@berikulyBeket thanks for your contribution!

Sorry, due to a lack of reviewers, it became stale, and I noticed it occasionally just now. To make it even better, I added the `/ru/` prefix to another link in this list as well. Later, we'll need to fully revise this page since its original English version evolved — I put it in my backlog.

/label tide/merge-method-squash

**Pull request merged**
