### PR TITLE
[zh] Fix translation errors in Chinese document

### LINKED ISSUE #31459: [zh] kubelet options "register-with-taints" is DEPRECATED?
In chinese document the option register-with-taints is DEPRECATED, I wonder if this is a translation mistake

--register-with-taints mapStringString
--
  | 设置本节点的污点标记，格式为 <key>=<value>:<effect>， 以逗号分隔。当 --register-node 为 false 时此标志无效。 **已弃用：将在未来版本中移除。**

--
  | Register the node with the given list of taints (comma separated <key>=<value>:<effect>). No-op if --register-node is false.

### PR DESCRIPTION
**Pull request by xzyangNB**
fix #31459

### CODE REVIEW

**Comment by tengqm** [comment]
This fix is incorrect.

**Comment by xzyangNB** [comment]
> 



> This fix is incorrect.

Excuse me where's the problem

**Pull request closed without merging**
