### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by OgrodMichal**
Fixed typo

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi @OgrodMichal , please sign CLA. Refer to: https://github.com/kubernetes/community/blob/master/CLA.md

**Review by aj11anuj — APPROVED** [review]
Changes lgtm, 👍
But make sure you sign CLA or we will not be able to proceed further with your PR.

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by fykaa** [comment]
Thank you for your PR @OgrodMichal

To proceed with the review of your PR, we kindly request you to sign the CLA. You can find the CLA and the signing instructions [here](https://github.com/kubernetes/community/blob/master/CLA.md). Once you have signed the CLA, please let us know, and we will be more than happy to review your PR promptly!

**Review by dipesh-rawat — COMMENTED** [review]
It seems the typo is already being addressed and incorporated into the [website](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/). Regardless, appreciate your efforts and contribution. 

Closing this PR.
/close

**Pull request closed without merging**
