### PR TITLE
Official 1.28 Release Docs

### PR DESCRIPTION
**Pull request by Rishit-dagli**
## 🛑 DO NOT MERGE 🛑 UNTIL KUBERNETES 1.28 IS RELEASED

Target Date: 2023-08-15

### Release deadlines

From [sig-release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.28#timeline):

| Description | Date |
|:---|:---|
| Docs deadline — Open placeholder PRs | Thursday 20th July 2023
| Docs deadline — PRs ready for review | Tuesday 25th July 2023
| Docs complete — All PRs reviewed and ready to merge | Tuesday 8th August 2023
| **v1.28.0 released** | Tuesday 15th August 2023

### For More Information

cc: Kat Cosgrove ([@katcosgrove](https://github.com/katcosgrove) / Slack: `@katcosgrove`), Tania Duggal ([@taniaduggal](https://github.com/taniaduggal) / Slack: `@Tania Duggal`),  Vibhor Chinda ([@VibhorChinda](https://github.com/VibhorChinda) / Slack: `@Vibhor Chinda`), Michael Levan ([@AdminTurnedDevOps](https://github.com/AdminTurnedDevOps) / Slack: `@Michael Levan`)

/hold

### CODE REVIEW

**Comment by sftim** [comment]
For safety, I'll also
/retitle [WIP] Official 1.28 Release Docs

**Comment by sftim** [comment]
@Rishit-dagli an interesting CLA check failure here. If you'd like help clearing that, let us know.

**Comment by Rishit-dagli** [comment]
Yeah I don't know why that fails because each commit to dev-1.28 does require the CLA. Could you please help me with this @sftim ?

**Comment by sftim** [comment]
> Could you please help me with this @sftim ?

I'll highlight this in the docs maintainers channel on Kubernetes Slack.

**Comment by divya-mohan0209** [comment]
@Rishit-dagli The commit co-authored by Kevin Hannon and Tim is not linked correctly to the Kevin's GitHub account. As a result, the CLA is failing. 

Since this PR has multiple commits, it'd be best if you link it correctly by following the instructions on [the troubleshooting page](https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=86641302). 

You can view Kevin's email ID and first name/last name by appending a .patch to this PR URL & doing cmd + f /ctrl + f.

**Comment by Rishit-dagli** [comment]
This would require me to force push to `dev-1.28` since if I rebased and fixed these authors details in another branch (tried this at https://github.com/Rishit-dagli/website/tree/easycla) and tried to merge that `dev-1.28`, the merge would try to preserve commits from `dev-1.28`  and my new changed branch (which would be changed commits since rebase would update the hash for all commits in between)?

**Comment by Rishit-dagli** [comment]
Based on the discussion in this [Slack thread](https://kubernetes.slack.com/archives/CA1MMM1HU/p1691762522751239), it seems we should go ahead with merging this using write access.

**Comment by sftim** [comment]
@Rishit-dagli do you know how to preview locally? You could do that.

Try this:
```shell
git checkout dev-1.28
git pull --ff-only # this also assumes you pulled from k/website
git checkout main
git pull --ff-only # this assumes you pulled from k/website
git checkout -b test-merge
git merge dev-1.28 --no-ff
# if there are merge conflicts etc, don't fix them here - find out why and fix the dev-1.28 branch first
make container-serve # now visit http://localhost:1313/ and look around
```

**Comment by Rishit-dagli** [comment]
> @Rishit-dagli do you know how to preview locally? You could do that.

Yeah, let me try previewing this.

**Comment by Rishit-dagli** [comment]
The preview for what it would look like when this PR would be merged, generated using a local run: https://64da456df5a8af4f8e46d837--128-test.netlify.app/

**Comment by Rishit-dagli** [comment]
It seems that the Netlify Build just times out.

**Comment by Rishit-dagli** [comment]
Does anyone have any suggestions on making the netlify builds pass (PS: they run well locally see https://128-test.netlify.app/) or should we still merge (in which case could someone else test the build too)?

**Comment by sftim** [comment]
We haven't 100% figured out how to make Netlify builds happen reliably. I would still do the release even though the deploy preview isn't working.

**Comment by Rishit-dagli** [comment]
Sounds good we still need an approve and lgtm on this

**Comment by reylejano** [comment]
@Rishit-dagli , you don't need the lgtm and approve labels since you will manually merge this
Please see this example PR for the 1.23 docs https://github.com/kubernetes/website/pull/29658

**Pull request merged**
