### PR TITLE
Blog post index for past years does not expand making older posts unr…

### LINKED ISSUE #14860: Blog post index for past years does not expand making older posts unreachable
**This is a Bug Report**

**Problem:**
Trying to expand or collapse any of the years in the post index on the right hand navigation does not work.  A javascript error and stack trace appears in the console.  

**Page to Update:**
https://kubernetes.io/blog/

Additional Information:
This is what I see in the console when I click on 2018 to expand it.
```
Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at a.t._getParent (bootstrap-4.3.1.min.js:6)
    at new a (bootstrap-4.3.1.min.js:6)
    at HTMLDivElement.<anonymous> (bootstrap-4.3.1.min.js:6)
    at Function.each (jquery-3.2.1.min.js:2)
    at r.fn.init.each (jquery-3.2.1.min.js:2)
    at r.fn.init.a._jQueryInterface [as collapse] (bootstrap-4.3.1.min.js:6)
    at HTMLDivElement.<anonymous> (bootstrap-4.3.1.min.js:6)
    at Function.each (jquery-3.2.1.min.js:2)
    at r.fn.init.each (jquery-3.2.1.min.js:2)
    at HTMLAnchorElement.<anonymous> (bootstrap-4.3.1.min.js:6)
```

### PR DESCRIPTION
**Pull request by mhamdisemah**
fixes #14860

### CODE REVIEW

**Comment by mhamdisemah** [comment]
ping @tfogo

**Comment by nikhita** [comment]
cc @kbarnard10 @zacharysarah @idvoretskyi

**Comment by kbarnard10** [comment]
Thanks for the fix @mhamdisemah! 

/lgtm
/approve

**Pull request merged**
