### PR TITLE
Fix the content inside docs/home

### PR DESCRIPTION
**Pull request by chandankumar4**
- fix button inside `I am` section in docs/home
- fix content inside `I want to` section in docs/home
- fix "back" navigation broken when visit to docs: Issue(#7391 )`

Signed-off-by: chandan kumar <chandan.kr404@gmail.com>

Page to Update:
https://kubernetes.io/docs/home/

Issue: #8989

### CODE REVIEW

**Comment by bradtopol** [comment]
I think @steveperry-53 is a more appropriate reviewer for this cc @zacharysarah

**Comment by tengqm** [comment]
cc @chenopis

**Comment by steveperry-53** [comment]
@chandankumar4 Thank you for your pull request. But we don't want to accept this. Your change puts back the line that @zparnold removed in #9141.

**Pull request merged**
