### PR TITLE
[pt-br] add /docs/tasks/configure-pod-container/assign-cpu-resource.md

### PR DESCRIPTION
**Pull request by DonatoHorn**
Translate to pt-br

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please sign CLA
Info https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by stormqueen1990** [comment]
Hello there!

It appears to me that there is a little bit of confusion in this PR. I see you translated the page to Brazilian Portuguese, but that was done in the original english version of the file (hosted under `content/en/docs`). The Brazilian Portuguese documentation is hosted under the folder `content/pt-br/docs`. In this case, reverting the changed file and moving the content to the correct folder is required.

**Comment by mehabhalodiya** [comment]
@DonatoHorn I believe what @stormqueen1990 said is correct. You have made the changes in the wrong place.
If you are translating something then you need to choose a directory of that language. 

In this case, you are writing Brazilian Portuguese content and hence, it should go under: https://github.com/kubernetes/website/tree/main/content/pt-br/docs/tasks

Please have a look and do the changes accordingly. Appreciate your first-time contribution.
Thank you 🙂

**Comment by mehabhalodiya** [comment]
/retitle [pt-br] add /docs/tasks/configure-pod-container/assign-cpu-resource.md

**Pull request closed without merging**
