### PR TITLE
Add support for quotas for ephemeral storage monitoring.

### PR DESCRIPTION
**Pull request by RobertKrawitz**
Reference https://github.com/kubernetes/kubernetes/pull/66928

### CODE REVIEW

**Comment by RobertKrawitz** [comment]
@derekwaynecarr @dashpole 

Note that this does not include localizations; it's not clear from the description whether I need to do that or it's done automatically.

/hold

Hold pending merge of https://github.com/kubernetes/kubernetes/pull/66928

**Comment by tengqm** [comment]
/approve

This PR is changing some of the files that are auto-generated, but it should be fine because they will be eventually get overwritten.

**Comment by RobertKrawitz** [comment]
/hold cancel

now that https://github.com/kubernetes/kubernetes/pull/66928 is merged.

**Pull request merged**
