### PR TITLE
Fix config.json interpretation

### PR DESCRIPTION
**Pull request by saschagrunert**
As outlined in https://github.com/kubernetes/kubernetes/issues/119941, the implementation is more specific than a regular glob match. Updating the docs to reflect that.

Fixes https://github.com/kubernetes/kubernetes/issues/119941

PTAL @njgibbon

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Fix config.json interpretation

(avoiding Markdown in commit messages)

**Review by njgibbon — APPROVED** [review]

**Comment by saschagrunert** [comment]
Rebased, PTAL @kubernetes/sig-docs-pr-reviews

**Comment by tengqm** [comment]
Em... this is a dilemma. Sounds to me that the code is being fixed because it is not working as documented. At the same time, we are fixing the docs to be more accurate wrt to code implementation.

Even if the docs should be updated, we need to confirm whether it is something "new" in v1.29 and retarget this to `dev-1.29` branch if answer is positive.

**Comment by tengqm** [comment]
Okay, doubled checked the issue at k/k. This is something to be clarified at docs side.
/lgtm
/approve
Sorry for mistaking this as a code issue.

**Pull request merged**
