### PR TITLE
Improve docs for securityContext.allowPrivilegeEscalation

### PR DESCRIPTION
**Pull request by Kartik494**
Fixes: #30104 
/language en
/kind cleanup

### CODE REVIEW

**Comment by Kartik494** [comment]
/assign @bradtopol
/label tide/merge-method-squash
@divya-mohan0209 PTAL

Thanks!!

**Comment by bradtopol** [comment]
Assigning @divya-mohan0209 since she is already engaged on this.
/unassign
/assign @divya-mohan0209

**Comment by tengqm** [comment]
This is not supposed to be fixed here because the reference is generated from upstream source code comment. Please propose fix to the kubernetes/kubernetes repo.

**Review by divya-mohan0209 — COMMENTED** [review]
Thank you for catching that, @tengqm ! Apologies for the inconvenience, @Kartik494 . Please see [this comment](https://github.com/kubernetes/website/pull/34096#issuecomment-1144385602] and consider opening an issue/PR against the k/k repository.

**Comment by divya-mohan0209** [comment]
Closing this PR off per the previous comment

**Comment by iamNoah1** [comment]
@tengqm would [this](https://github.com/kubernetes/kubernetes/blob/67bde9a1023d1805e33d698b28aa6fad991dfb39/staging/src/k8s.io/api/core/v1/types.go#L6474) be the correct place for the improvement? If not, could you please hint to the correct place?! Thanks :)

**Pull request closed without merging**
