### PR TITLE
docs(zh-cn): update clusters intro contents and hide interactive page in TOC

### PR DESCRIPTION
**Pull request by mo3et**
### Description

>update clusters-intro contents in `tutorials/kubernetes-basics` &&  hide  `tutorials/kubernetes-basics`  interactive page in TOC

This PR solves the issue of hiding certain interactive pages in the TOC and aligning the filenames with the English documentation. Such as `tutorials/kubernetes-basics/explore/explore-interactive` and `tutorials/kubernetes-basics/update/update-interactive`.

I saw in the previous comment message that you seemed to use the term **remove katacoda tutorials**.

At the same time, I’ve also updated the `tutorials/kubernetes-basics/create-cluster/cluster-intro.html` section and made some of the content more human-friendly.

**Running the script produced this output**

```shell
k8s-website on  main via 🐳 orbstack via 🐹 v1.23.2 via  v22.9.0 
➜ ./scripts/lsync.sh content/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html

content/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html is still in sync
```

### Issue

Closes: #

### CODE REVIEW

**Comment by windsonsea** [comment]
Please provide some useful description for your PR. Tell reviewers why this PR comes. If some links to the upstream PR will be more helpful.

Also, you need to check all the in-synced content with the english upstream one by one.
For example,  run this command on your local `main` branch:

```
./scripts/lsync.sh content/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
```
```diff
diff --git a/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html b/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
index 122ed7346e..5a5c77b78a 100644
--- a/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
+++ b/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
@@ -74,7 +74,7 @@ description: |-
         <div class="row">
             <div class="col-md-8">
                 <p><b>The Control Plane is responsible for managing the cluster.</b> The Control Plane coordinates all activities in your cluster, such as scheduling applications, maintaining applications' desired state, scaling applications, and rolling out new updates.</p>
-                <p><b>A node is a VM or a physical computer that serves as a worker machine in a Kubernetes cluster.</b> Each node has a Kubelet, which is an agent for managing the node and communicating with the Kubernetes control plane. The node should also have tools for handling container operations, such as containerd or Docker. A Kubernetes cluster that handles production traffic should have a minimum of three nodes because if one node goes down, both an <a href="/docs/concepts/overview/components/#etcd">etcd</a> member and a control plane instance are lost, and redundancy is compromised. You can mitigate this risk by adding more control plane nodes.</p>
+                <p><b>A node is a VM or a physical computer that serves as a worker machine in a Kubernetes cluster.</b> Each node has a Kubelet, which is an agent for managing the node and communicating with the Kubernetes control plane. The node should also have tools for handling container operations, such as {{< glossary_tooltip text="containerd" term_id="containerd" >}} or {{< glossary_tooltip term_id="cri-o" >}}. A Kubernetes cluster that handles production traffic should have a minimum of three nodes because if one node goes down, both an <a href="/docs/concepts/architecture/#etcd">etcd</a> member and a control plane instance are lost, and redundancy is compromised. You can mitigate this risk by adding more control plane nodes.</p>
```

**Comment by mo3et** [comment]
> Please provide some useful description for your PR. Tell reviewers why this PR comes. If adding some links to the upstream PR will be more helpful.
> 
> Also, you need to check all the in-synced content with the english upstream one by one. For example, run this command on your local `main` branch:
> 
> ```
> ./scripts/lsync.sh content/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> ```
> 
> ```diff
> diff --git a/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html b/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> index 122ed7346e..5a5c77b78a 100644
> --- a/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +++ b/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> @@ -74,7 +74,7 @@ description: |-
>          <div class="row">
>              <div class="col-md-8">
>                  <p><b>The Control Plane is responsible for managing the cluster.</b> The Control Plane coordinates all activities in your cluster, such as scheduling applications, maintaining applications' desired state, scaling applications, and rolling out new updates.</p>
> -                <p><b>A node is a VM or a physical computer that serves as a worker machine in a Kubernetes cluster.</b> Each node has a Kubelet, which is an agent for managing the node and communicating with the Kubernetes control plane. The node should also have tools for handling container operations, such as containerd or Docker. A Kubernetes cluster that handles production traffic should have a minimum of three nodes because if one node goes down, both an <a href="/docs/concepts/overview/components/#etcd">etcd</a> member and a control plane instance are lost, and redundancy is compromised. You can mitigate this risk by adding more control plane nodes.</p>
> +                <p><b>A node is a VM or a physical computer that serves as a worker machine in a Kubernetes cluster.</b> Each node has a Kubelet, which is an agent for managing the node and communicating with the Kubernetes control plane. The node should also have tools for handling container operations, such as {{< glossary_tooltip text="containerd" term_id="containerd" >}} or {{< glossary_tooltip term_id="cri-o" >}}. A Kubernetes cluster that handles production traffic should have a minimum of three nodes because if one node goes down, both an <a href="/docs/concepts/architecture/#etcd">etcd</a> member and a control plane instance are lost, and redundancy is compromised. You can mitigate this risk by adding more control plane nodes.</p>
> ```

Thanks for your feedback. Now I update description in comment, and execute the script it is not problems.

**Comment by windsonsea** [comment]
Please [squash your commits into a single one](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits), thanks.

**Comment by mo3et** [comment]
> Please [squash your commits into a single one](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits), thanks.

I have a question. If i squash into a single, is use merge or squash merge when bot merge it.

My branch is dirty when i  wrong operation. I worry to my PR will dirty the main branch. So I need to solve it to night.

I also to know, If I pulled the upstream branch during some of my commit submissions, do I need to pick them when squashing?

@windsonsea

**Comment by windsonsea** [comment]
If possible, you can separate those changes into different PR. This is your first PR. A tiny change is acceptable.

**Comment by mo3et** [comment]
> If possible, you can separate those changes into different PR. This is your first PR. A tiny change is acceptable.

OK. If possible, I would prefer not to break it down into too many small parts, as this might put unnecessary pressure on the reviewers.
Thank you for your patient response 😃

**Comment by mo3et** [comment]
Fortunately, I found a clean, unpulled upstream branch on my Fedora system, and I have resolved the issue.
Thank you for your support over the past few days.

**Pull request merged**
