### PR TITLE
content/zh/docs/setup/best-practices/cluster-large.md

### PR DESCRIPTION
**Pull request by gaoguangze111**
Update chinese page cluster-large.md. Correct a wrong link which direct to a English version page

### CODE REVIEW

**Comment by xichengliudui** [comment]
can you check what caused the mistake first?

**Comment by gaoguangze111** [comment]
> can you check what caused the mistake first?

It seems like a git server bug on that day

**Comment by tengqm** [comment]
Please help rebase this onto master and see the CI is happy.

**Review by tanjunchen — COMMENTED** [review]
@gaoguangze111
any  update?

**Pull request closed without merging**
