### PR TITLE
add kubesphere as an on-prem VMs solution

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Signed-off-by: FeynmanZhou <pengfeizhou@yunify.com>

[KubeSphere](https://github.com/kubesphere/kubesphere) integrated native Kubernetes to provide users the capabilities with provisioning Kubernetes on OS-compatible machines, it also supports installing on any version-compatible Kubernetes cluster. 

I hope the community can accept KubeSphere as an on-prem VMs solution. It can help users to install and manage Kubernetes out of box.

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@thockin Could you please help to review this guide?

**Comment by sftim** [comment]
@FeynmanZhou, please check that this PR fits in with the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/). If you're confident it fits, please also update the PR description to explain why it's OK to include.

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou, please check that this PR fits in with the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/). If you're confident it fits, please also update the PR description to explain why it's OK to include.

Hi @sftim ,

Thanks for your reply, as I see that [Docs can link to third-party OSS outside the Kubernetes project if it’s necessary for Kubernetes to function.](https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content) from the content guide. 

[KubeSphere](https://github.com/kubesphere/kubesphere) is an open source project, it can help users to install and manage Kubernetes out of box. KubeSphere installer uses kubeadm and ansible to enable installing Kubernetes on premises in Linux machines much easier. 

BTW, Cloudstack, DC/OS and oVirt are already out there,  KubeSphere only requires a single command, or simply configure the host template to quickly set up a Kubernetes cluster, supports v1.15 ~ v1.17.

**Comment by sftim** [comment]
@FeynmanZhou:
>  if it’s necessary for Kubernetes to function

means that without the software, Kubernetes would not work. It seems clear to me that Kubernetes can work without kubesphere.

To be valid content, there would need to be different grounds for inclusion.

**Comment by tengqm** [comment]
While we are attempting to remove 3rd-party content to avoid dual hosted pages, please consider providing a nice intro for Kubesphere somewhere else. Adding a link to your content should be okay.

**Comment by sftim** [comment]
@FeynmanZhou are you able to revise in line with @tengqm's [suggestion](https://github.com/kubernetes/website/pull/19824#issuecomment-604221959)?

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou are you able to revise in line with @tengqm's [suggestion](https://github.com/kubernetes/website/pull/19824#issuecomment-604221959)?

@sftim Yes, I agree with @tengqm's suggestion. Is there any other place to add a link to my content?

**Comment by sftim** [comment]
@FeynmanZhou you might have to look for a place where that hyperlink could fit; nothing immediately springs to mind.

**Comment by sftim** [comment]
I don't think this PR is going to be acceptable.
/close

**Pull request closed without merging**
