### PR TITLE
[pt-br] Add docs/tasks/access-application-cluster/_index.md

### PR DESCRIPTION
**Pull request by PauloGoncalvesLima**
### Changes

Brazilian portuguese translation of the [Access Applications in a Cluster_index](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/access-application-cluster/_index.md)

### Related Issue

https://github.com/kubernetes/website/issues/13939

### CODE REVIEW

**Review by daniso123 — CHANGES_REQUESTED** [review]
I didn't find anything wrong in the translation!

**Comment by stormqueen1990** [comment]
/retitle [pt-br] Add docs/tasks/access-application-cluster/_index.md

**Comment by PauloGoncalvesLima** [comment]
Hello @stormqueen1990 and @MrErlison, thank you for reviewing my PR. :smile:

**Pull request merged**
