### PR TITLE
[ja] Fix broken links in persistent-volumes

### PR DESCRIPTION
**Pull request by highpon**
This PR fixes a broken link in the Japanese persistent-volumes document.

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm

Thank you for creating this PR!
The Update looks good for me!

But the CI for Netlify(a build system for generating webpage) said an error, this looks the error on Netlify side.

Could you empty-commit by doing following to retrigger the build?
```
git commit --amend --no-edit
git push -f
```

**Comment by highpon** [comment]
Thank you for your review!
I built again and the error on the Netlify side is fixed!

**Comment by atoato88** [comment]
Thank you for quick response!

**Comment by atoato88** [comment]
/assign @nasa9084 
Could you review this?

**Review by nasa9084 — COMMENTED** [review]
/approve
Thank you~

**Pull request merged**
