### PR TITLE
[zn-ch]the word  "式"  should be "序",which is more reasonable for this sentence 

### PR DESCRIPTION
**Pull request by JBossBC**

### CODE REVIEW

**Comment by windsonsea** [comment]
This en page has some minor changes recently. Could you please sync with these too? Thanks.

image

**Comment by mengjiao-liu** [comment]
Fixes https://github.com/kubernetes/website/issues/39035

**Comment by tengqm** [comment]
@JBossBC Can you squash your PR into a single commit?

**Comment by mengjiao-liu** [comment]
Can you address the review comments?

**Review by my-git9 — COMMENTED** [review]
/remove-lifecycle stale

**Comment by tengqm** [comment]
Let's close this.
The author is not responding.
/close

**Comment by mengjiao-liu** [comment]
PR https://github.com/kubernetes/website/pull/41251 to resolve it.

**Pull request closed without merging**
