### PR TITLE
[ja] remove "O=system:masters" from "kube-apiserver-etcd-client".md

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/kubernetes/website/pull/42942/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
The proposed change looks in sync with 'en' PR.
LGTM

Deploy Preview: [deploy-preview-43171-/ja/certificates](https://deploy-preview-43171--kubernetes-io-main-staging.netlify.app/ja/docs/setup/best-practices/certificates/)

**Review by t-inu — COMMENTED** [review]
/lgtm

**Comment by atoato88** [comment]
@nasa9084 
Could you review this PR at your convenience?

**Pull request merged**
