### PR TITLE
Updated typo from 'docs' to 'documentation'

### PR DESCRIPTION
**Pull request by Virajbhise**
Beginners may find difficult to interpret what actually 'docs' means so i suggest to use 'documentation' instead

### CODE REVIEW

**Comment by Virajbhise** [comment]
This is my first contribution towards open source !!!

**Comment by anubha-v-ardhan** [comment]
I believe "docs" is very widely used and easily understandable.

**Comment by anubha-v-ardhan** [comment]
I believe "docs" is very widely used and easily understandable.

**Comment by Virajbhise** [comment]
> I believe "docs" is very widely used and easily understandable.

OKay !

**Comment by reylejano** [comment]
Hi @Virajbhise , 
I agree with anubha-v-ardhan that the term docs is widely used and understandable.
I'm closing this PR as there is consensus about the usage of the word docs.

/close

I encourage you to join the SIG Docs Slack channel and SIG Docs meetings if you would like to contribute more

**Pull request closed without merging**
