### PR TITLE
[ar] Add mboukhalfa as owner for arabic content

### PR DESCRIPTION
**Pull request by mboukhalfa**
based on the discussion here https://github.com/kubernetes/website/pull/44862#issuecomment-1995155214

### CODE REVIEW

**Comment by mboukhalfa** [comment]
cc @sftim

**Comment by adowair** [comment]
Approving this change on behalf of myself and Arabic team. Thanks @mboukhalfa!

**Comment by sftim** [comment]
@mboukhalfa, you can't approve this one. Another would-be approver for Arabic should step in here.

**Comment by sftim** [comment]
BTW @adowair you should use `/approve` on a line by itself, so the bot knows you meant it.

**Comment by a-mccarthy** [comment]
/lgtm

@mboukhalfa thanks for joining the AR review team 🎉  

Other folks are planning to get org membership and join the review lists, but so far you are the only member of the team with org membership. Just a reminder, until you get another reviewer on the list @mboukhalfa you will not be able to approve your own PRs.

**Comment by adowair** [comment]
@mboukhalfa I see here that this change was merged into https://github.com/kubernetes/website/tree/dev-1.29-ar.1 rather than https://github.com/kubernetes/website/tree/main. I wonder if that has anything to do with your [issue](https://kubernetes.slack.com/archives/CP9FKRD51/p1710921248918939) approving PRs...

**Comment by sftim** [comment]
The Arabic localization has not yet launched, so we (SIG Docs) aren't yet setting the Arabic team as approvers for the _main_ branch.

**Pull request merged**
