### PR TITLE
Create README-da.md

### PR DESCRIPTION
**Pull request by alex404hm**
Hello,  i have added a danish readme file for those who live in Denmark or talks or read danish.

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
We currently do not have a Danish localization in place, which means there will be an additional barrier following the CLA process (Refer [signing CLA Steps](https://git.k8s.io/community/CLA.md)).

@alex404hm Are you interested in starting localization for Danish? It's important to note that a localization team should consist of at least two members. For guidance on getting started with a new localization, please refer: [Start a new localization](https://kubernetes.io/docs/contribute/localization/#start-a-new-localization)

I suggest discussing the idea of starting Danish localization **_(if that’s the intention here)_** on either the [sig-docs](https://kubernetes.slack.com/messages/sig-docs) or [sig-docs-localization](https://kubernetes.slack.com/messages/sig-docs-localizations) Slack channel if it hasn’t been done already.  (Need a Slack invitation, visit https://slack.k8s.io/)


/hold

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by network-charles** [comment]
Hi @alex404hm, I noticed you haven't signed the CLA yet. Kindly sign the CLA to make your current and future PRs valid.

**Review by dipesh-rawat — COMMENTED** [review]
This PR has been open for about 2 months without any updates on the CLA side. As we cannot accept PRs missing the CLA authorization, I will be closing this one. If you're still interested in contributing, please consider signing the CLA and reopening the PR.

/close

**Pull request closed without merging**
