### PR TITLE
Remove deprecated doc on Topology-aware traffic routing with topology keys

### LINKED ISSUE #40600: Topology-aware traffic routing with topology keys is deprecated, possibly removed.
**This is a Bug Report**

**Problem:**
Topology-aware traffic routing with topology keys is deprecated since 1.21
Confirm if it's removed and remove the related documentation if feature is removed

**Proposed Solution:**
Remove Service Topology page 

**Page to Update:**
https://k8s.io/docs/concepts/services-networking/service-topology/

Deprecated since 1.21

### PR DESCRIPTION
**Pull request by dipesh-rawat**
Resolves #40600

**Additional Context**

- Looks like the Service topologyKeys field has been deprecated and removed since Kubernetes v1.21. Refer the PRs below:

    - https://github.com/kubernetes/kubernetes/pull/96736
    -  https://github.com/kubernetes/kubernetes/pull/102412
    
 - Based on the above info the related [documentation](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/services-networking/service-topology.md) has been removed as part of this PR.
 
 - The references to the delete doc has either been removed or changed the link to static text as part of this PR.
 
 /assign @reylejano

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
LGTM for docs

**Comment by tengqm** [comment]
Not sure this feature is gone or if the feature has graduated from alpha.

**Comment by kbhawkey** [comment]
Hi, @dipesh-rawat 
Checking on the latest comment. Is the feature in the alpha stage or removed?

**Comment by dipesh-rawat** [comment]
From what I could find in https://github.com/kubernetes/kubernetes/pull/96736 and https://github.com/kubernetes/kubernetes/pull/102412, it appears that the feature has been deprecated. The initial issue was raised in response to comment  [k/wesbite-PR#40069](https://github.com/kubernetes/website/pull/40069/files#r1161998431).
@robscott could you please help us to confirm and verify whether the feature has indeed been deprecated and removed, allowing us to safely remove the accompanying documentation.

**Comment by sftim** [comment]
@dipesh-rawat rather than picking one maintainer and nudging them, there's another approach that works well:
ask on Slack (https://kubernetes.slack.com/messages/sig-network). That way, you can get a response on behalf of the SIG, not just from one individual.

If you're not already signed up, visit [Join Kubernetes on Slack](https://slack.k8s.io/).

**Comment by robscott** [comment]
Thanks @dipesh-rawat! LGTM for sig-network.

/lgtm

**Review by sftim — APPROVED** [review]
/approve

Thanks!

**Pull request merged**
