### PR TITLE
Fix dead link of api-conventions doc (ja)

### PR DESCRIPTION
**Pull request by KoyamaSohei**
I replaced all https://git.k8s.io/community/contributors/devel/api-conventions.md in **content/ja/docs** 
 with https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md.

### CODE REVIEW

**Comment by KoyamaSohei** [comment]
I signed CNCF CLA.

**Comment by spurin** [comment]
Non-member feedback:

/lgtm

Checked all the links in the commit, old ones all return 404, new ones work as expected.

**Comment by inductor** [comment]
@KoyamaSohei Hi! We are working on Japanese translation based on `dev-1.17-ja.1` branch which we will start merging work soon. Could you change the base branch to this from `master`?

**Comment by inductor** [comment]
@KoyamaSohei 
軽く確認しましたが、DaemonSetの部分に関しては以下のPull Requestで対応が終わってます
https://github.com/kubernetes/website/pull/18793

**Comment by KoyamaSohei** [comment]
@inductor 
この変更で問題ないですか?
Is this change OK?

**Comment by inductor** [comment]
@KoyamaSohei LGTM! Thank you!

**Pull request merged**
