### PR TITLE
Add kube-scheduler secure options usage

### LINKED ISSUE #10074: Issue with k8s.io//docs/reference/command-line-tools-reference/kube-scheduler/ [File: /content/en/docs/reference/command-line-tools-reference/kube-scheduler.md]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
The options --address is deprecated, and replaced with --bind-address, but I do not see any information about --bind-address on this page. --port(replaced with --secure-port) also has no information on this page.

**Proposed Solution:**
Add --bind-address and --secure-port on the page.  Thanks!

**Page to Update:**
https://kubernetes.io/...

### PR DESCRIPTION
**Pull request by tossmilestone**
Fix #10074 , it needs kubernetes/kubernetes#69663 to be merged first.

### CODE REVIEW

**Comment by tossmilestone** [comment]
kubernetes/kubernetes#68479 has been replaced by kubernetes/kubernetes#69663, waiting for it to be merged.

**Comment by tossmilestone** [comment]
@tengqm Now this PR could be merged, Thanks!

**Comment by xiangpengzhao** [comment]
>it needs kubernetes/kubernetes#68479 to be merged first.

@tossmilestone The referenced link is an issue, not a PR. Please check and modify it in case someone wants to know what the PR is.

**Comment by tossmilestone** [comment]
@xiangpengzhao The PR is now kubernetes/kubernetes#69663, sorry for the previous wrong ref.

**Pull request merged**
