### PR TITLE
fix description about kubeadm

### PR DESCRIPTION
**Pull request by CaoShuFeng**
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

### CODE REVIEW

**Comment by neolit123** [comment]
/kind cleanup

seems good to me.
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by stewart-yu** [comment]
/cc @tengqm 
for approve

**Pull request merged**
