### PR TITLE
Add reviewer to French glossary

### PR DESCRIPTION
**Pull request by bcheronn**

### CODE REVIEW

**Comment by feloy** [comment]
Hi @remyleone the tests seem stuck for 31 days on this PR. Do you know how to cancel/restart them?

**Comment by sftim** [comment]
/retest

(not an actual command to Netlify, but I've done the equivalent)

**Comment by sftim** [comment]
@bcheronn could you rebase this against _master_? I'm afraid it'll need another /lgtm but that does seem like the way forward.

**Comment by sftim** [comment]
@k8s-ci-robot happy now?

**Pull request merged**
