### PR TITLE
[hi] Localize docs/concepts/achitecture/leases.md into Hindi

### PR DESCRIPTION
**Pull request by KumareshSingha97**
hello!

I have changed the `docs/concepts/architecture/leases.md` page from English to Hindi.

preview : [docs/concepts/architecture/leases.md](https://deploy-preview-39026--kubernetes-io-main-staging.netlify.app/hi/docs/concepts/architecture/leases/)

### CODE REVIEW

**Comment by NitishKumar06** [comment]
1. Sign the CLA before passing this PR to review
2. Resolve the failing checks ( try to pass a blanked commit if possible)

**Comment by Babapool** [comment]
Hi @KumareshSingha97, can you please sign the CLA before your PR is reviewed. 

On steps to sign the CLA please visit/see: https://github.com/kubernetes/community/blob/master/CLA.md

Thanks.

**Comment by Babapool** [comment]
/retitle [hi] Localize docs/concepts/achitecture/leases.md into Hindi

**Review by Arhell — COMMENTED** [review]
To check sign `/easycla`

**Comment by reveurguy** [comment]
@KumareshSingha97 Are you facing any issue in signing the CLA. You can follow the link mentioned above to complete that part or reach out to anyone on the slack channel.
Once you sign the CLA, your PR will be reviewed then only.

**Comment by divya-mohan0209** [comment]
Hello @KumareshSingha97 , this PR has been inactive with the CLA unsigned for over 3 months as of today. Please sign the CLA and consider reopening the PR, whenever you have the bandwidth. We'll be closing this for now. 

/close

**Pull request closed without merging**
