### PR TITLE
Fix curl URL to match path regex

### PR DESCRIPTION
**Pull request by MathieuLavigneCC**

### CODE REVIEW

**Comment by jimangel** [comment]
Hey there! @MathieuLavigneCC, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by cody-clark** [comment]
Hi @MathieuLavigneCC, I saw you 👍-ed Jim's comment about signing the CLA. Please [sign the CLA](https://github.com/kubernetes/community/blob/master/CLA.md#how-do-i-sign), and we will start the review process. Thanks!

**Comment by MathieuLavigneCC** [comment]
Hello @cody-clark, I am checking with my company but the process is a little bit long. At that time, I have not received any response...

**Comment by kbhawkey** [comment]
hello @MathieuLavigneCC . Thanks for this PR. While you sort out your CLA, I will close this PR. Feel free to reopen. Thanks!
/close

**Pull request closed without merging**
