### PR TITLE
update table

### PR DESCRIPTION
**Pull request by Arhell**
issue https://github.com/kubernetes/website/issues/24413

### CODE REVIEW

**Comment by Arhell** [comment]
[review page](https://deploy-preview-24421--kubernetes-io-master-staging.netlify.app/docs/concepts/overview/kubernetes-api/#api-specification)
/assign @kbhawkey

**Comment by kbhawkey** [comment]
Hi @Arhell .
Thanks for updating the table to use the table shortcode.
@tengqm pointed out (in PR #24024) that second column has three values in the other columns for "Accept" header.
It is a minor difference in the display. What do you think?

**Comment by tengqm** [comment]
Looks like markdown table is incapable of merge shells.
We may want to keep the HTML version which is not ugly.

**Comment by sftim** [comment]
If the Markdown doesn't do what's needed let's keep the HTML.

**Pull request closed without merging**
