### PR TITLE
en/concepts/services-networking/service: typo

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Comment by shannonxtreme** [comment]
Pls sign the CLA @dilyanpalauzov thank you

**Review by Arhell — COMMENTED** [review]
CLA more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by dilyanpalauzov** [comment]
> Pls sign the CLA @dilyanpalauzov thank you

The contribution procedure is unnecessary complicated.

Do I own copyright on this trivial change?  Can somebody else perform the here propose change now, without my authorization?  If the answer to the latter question is YES, then it is unclear for me what problem does “signing the CLA” solve.

**Comment by bradtopol** [comment]
Thank you @dilyanpalauzov for your contribution.  Please sign the CLA so we can accept your PR for review.
/assign

**Comment by reylejano** [comment]
Closing this PR since the spelling error is fixed
/close

**Pull request closed without merging**
