### PR TITLE
[bn] Partners / index.html

### PR DESCRIPTION
**Pull request by asem-hamid**
Fixes Issue : https://github.com/kubernetes/website/issues/44993

updating as this [PR](https://github.com/kubernetes/website/pull/45869)

### CODE REVIEW

**Comment by asem-hamid** [comment]
/hold 

until we update assets/scss/_custom.scss for bn version as main

**Review by mitul3737 — APPROVED** [review]

**Review by Imtiaz1234 — APPROVED** [review]
/lgtm

**Pull request merged**
