### PR TITLE
[id] Move monitoring.md to system-metrics.md and sync with upstream

### PR DESCRIPTION
**Pull request by habibrosyad**
xref https://github.com/kubernetes/website/issues/26955#issuecomment-802632104

/cc @kubernetes/sig-docs-id-reviews

### CODE REVIEW

**Comment by habibrosyad** [comment]
hmm, @ariscahyadi just realized that you're not in @kubernetes/sig-docs-id-reviews yet

**Review by ariscahyadi — COMMENTED** [review]
/lgtm

**Comment by ariscahyadi** [comment]
> hmm, @ariscahyadi just realized that you're not in @kubernetes/sig-docs-id-reviews yet

@habibrosyad thanks for pointing out... I already ask to join as a member.

**Review by irvifa — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
