### PR TITLE
Revise Service documentation

### PR DESCRIPTION
**Pull request by sftim**
Split out from https://github.com/kubernetes/website/pull/30817
View that PR to see these changes in context.

- improve glossary entry for Service [[preview](https://deploy-preview-37385--kubernetes-io-main-staging.netlify.app/docs/reference/glossary/?fundamental=true&networking=true#term-service)]
  -  _that's the plan, anyway_
- general tidying for Service concept [[preview](https://deploy-preview-37385--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/service/); [original](https://k8s.io/docs/concepts/services-networking/service/)]

### CODE REVIEW

**Comment by sftim** [comment]
Should help with #14770

**Comment by tengqm** [comment]
This is another huge refactoring though not labelled as a huge change. It is mixture of more than three goals. Please think twice, @sftim.

**Comment by kbhawkey** [comment]
👋 @sftim .
Are you splitting up this PR to create new PRs? The changes look familiar.
Can you close this PR if you have pushed the changes into a new pull request?
Thanks

**Comment by sftim** [comment]
I would be happy to see these changes merged and I could rebase, however, the even smaller PRs are getting reviews.

/close

**Pull request closed without merging**
