### PR TITLE
Graduate ServerSideFieldValidation to Beta

### PR DESCRIPTION
**Pull request by tengqm**
Upstream: kubernetes/kubernetes#108889

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
@tengqm I see https://github.com/kubernetes/website/pull/32357 is also opened up for the same purpose but @kevindelgado hasn't made any changes there. 

So, I would like to keep this PR open and consider closing https://github.com/kubernetes/website/pull/32357. Please correct me if I am wrong, thanks!

**Comment by tengqm** [comment]
@mehabhalodiya 

- #32593 is targeting 'main' branch, fixing the problem that the gate appeared but not documented.
- This PR is targeting 'dev-1.24' branch, updating the changes to the gate in 1.24

**Comment by mehabhalodiya** [comment]
> * [Add ServerSideFieldValidation feature #32593](https://github.com/kubernetes/website/pull/32593) is targeting 'main' branch, fixing the problem that the gate appeared but not documented.
> * This PR is targeting 'dev-1.24' branch, updating the changes to the gate in 1.24

Thanks for clearing. I missed noticing that! Apologize!
@tengqm But what about closing #32357?

**Comment by tengqm** [comment]
/hold
I'd like the feature gate page pointing to the docs to be added by @kevindelgado 
Waiting for #32357 to be merged.

**Comment by reylejano** [comment]
Looks like ServerSideFieldValidation to Beta will not be in v1.24 and will target v1.25
See https://github.com/kubernetes/website/pull/32357#issuecomment-1089020163
/close

**Pull request closed without merging**
