### PR TITLE
Correcting issues of kubefed reference section 

### PR DESCRIPTION
**Pull request by rajeshdeshpande02**
Below Changes are done on every page of kubefed reference section :
- Updated the Front matter in the .md files. 
- Removed the line that was introduced inadvertently in the files listed above.
- Changed 'SEE ALSO' to 'What's next' for consistency and compliance.
- Added links of these pages to the documentation side menu
- Added Overview section on each page.
- Added missing body section on every page.
Modified Page list: kubefed.md, kubefed_init.md, kubefed_join.md, kubefed_options.md, kubefed_unjoin.md, kubefed_version.md

### CODE REVIEW

**Comment by rajeshdeshpande02** [comment]
@Rajakavitha1 I have modified kubefed_init.md page to fix issues you raised with #13816 . Can you please have quick look at these changes so that I can replicate those changes in other mentioned pages also.

**Comment by kbhawkey** [comment]
@rajeshdeshpande02, thanks for the PR. As these files are auto-generated, it would be great if, for the next release, that the generation was corrected (I can't recall whether my PR fixed the kube-fed files). In the meantime, have you considered using `templates/tool-reference` instead of `templates/concept`,
`content_template: templates/concept` vs. `content_template: templates/tool-reference`.
For an example, see federation-controller-manager.md or federation-apiserver.md.

**Comment by rajeshdeshpande02** [comment]
@kbhawkey  Thanks for your quick review and yes, we need to fix the root cause. But as this is already generated docs, I submitted PR for this.

Also, this comes under 'reference/setup-tools', I followed the same standard as that of 'kubeadm ' which comes under the same section. 'kubeadm' uses 'content_template: templates/concept' so to maintain similarity I used that template.  

If we want to change it to 'content_template: templates/tool-reference', we need to change for 'kubeadm' and 'kubefed '

**Comment by Rajakavitha1** [comment]
Thanks for the PR @rajeshdeshpande02 . The preview looks good to me: https://deploy-preview-13817--kubernetes-io-master-staging.netlify.com/docs/reference/setup-tools/kubefed/kubefed_init/.

However, as per https://kubernetes.io/docs/contribute/style/page-templates/ the pages that you updated are not concepts. I suggest that you use templates/tool-reference that @kbhawkey  recommends.

**Comment by rajeshdeshpande02** [comment]
@Rajakavitha1 @kbhawkey  I have made changes for template . Now it is changed to 'templates/tool-reference' . Please have a look at it

**Comment by tengqm** [comment]
These are all auto-generated files. Please do not change them here. You can propose a fix to the kubernetes-incubator/reference-docs repo instead.

**Pull request closed without merging**
