### PR TITLE
fix toggle button

### PR DESCRIPTION
**Pull request by Arhell**
issue https://github.com/kubernetes/website/issues/23941
fix toggle button on mobile

### CODE REVIEW

**Comment by Arhell** [comment]
before
https://kubernetes.io/docs/tutorials/kubernetes-basics/ on mobile
after fix
https://deploy-preview-23963--kubernetes-io-master-staging.netlify.app/docs/tutorials/kubernetes-basics/ on mobile

examples image [here](https://github.com/kubernetes/website/issues/23941)

/area web-development
/language en
/assign @kbhawkey

**Comment by kbhawkey** [comment]
Hi @Arhell .
I looked at the rendered change using my desktop browsers (chrome, firefox) reduced to mobile size screen.
I don't see much difference between the current website and the rendered change.
Does the issue render with the docsy site, https://example.docsy.dev/docs/?

**Comment by Arhell** [comment]
> Hi @Arhell .
> I looked at the rendered change using my desktop browsers (chrome, firefox) reduced to mobile size screen.
> I don't see much difference between the current website and the rendered change.
> Does the issue render with the docsy site, https://example.docsy.dev/docs/?

@kbhawkey 
You are right, but on this page it is interrupted by custom styles (styles.css class .btn), I corrected everything to be fine

**Comment by kbhawkey** [comment]
Sure, this change is quite narrow in scope.
/approve

**Pull request merged**
