### PR TITLE
Mention about preparing socat and nsenter for "kubectl port-forward"

### PR DESCRIPTION
**Pull request by makocchi-git**
- kubelet needs `socat` and `nsenter` to accomplish port-forward
- apply code snippets

### CODE REVIEW

**Comment by makocchi-git** [comment]
[preview is here](https://deploy-preview-9902--kubernetes-io-master-staging.netlify.com/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)
[original](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)

**Comment by zacharysarah** [comment]
/sig api-machinery
@kubernetes/sig-api-machinery-pr-reviews 👋 PTAL

**Comment by tengqm** [comment]
@makocchi-git Please help resolve the conflicts so we can kick it in.

**Comment by mistyhacks** [comment]
23 days ago we requested a rebase to fix the conflicts. Please reopen this PR if you get a chance to do that. Thanks!

**Pull request closed without merging**
