### PR TITLE
Merge main branch into dev 1.32

### PR DESCRIPTION
**Pull request by AnshumanTripathi**
## Description
This PR syncs the dev-1.32 branch with the main branch to keep the dev-1.32 branch up to date.

cc: @chanieljdan @AnshumanTripathi @rdalbuquerque @spurin @hacktivist123 @michellengnx

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/lgtm

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by chanieljdan** [comment]
/assign @mrbobbytables 

Hi Bob! Release Docs Lead here for 1.32 👋. Just need your review & approval for the dev 1.32 docs branch sync this week. I believe the following commit is the only one that requires review: [Update data/announcements/scheduled.yaml](https://github.com/kubernetes/website/pull/48161/commits/6acd381eda262e443344186c0e58c5d03ca24732)

**Comment by sftim** [comment]
:thought_balloon: We could possibly avoid the special approval by cherry-picking banner / announcement changes onto the upcoming release branch.

**Comment by dipesh-rawat** [comment]
> [Bot's comment](https://github.com/kubernetes/website/pull/48161#issuecomment-2387778047)
Needs approval from an approver in each of these files:
[data/announcements/OWNERS](https://github.com/kubernetes/website/blob/dev-1.30/data/announcements/OWNERS)

This appears to also require approval from @kubernetes/steering-committee _(As this `dev-1.32` branch sync contains the changes to add KubeCon NA banner already approved added to `main` branch as part of PR https://github.com/kubernetes/website/pull/48086)_

/committee steering

**Pull request merged**
