### PR TITLE
setup page replaces picking the right solutions page

### PR DESCRIPTION
**Pull request by Rajakavitha1**
Fixes https://github.com/kubernetes/website/issues/9710

All the information in https://kubernetes.io/docs/setup/pick-right-solution/ is now available in https://kubernetes.io/docs/setup/.

The content in https://kubernetes.io/docs/setup/ also ensures that: 
a. kubernetes is vendor neutral. 
b. references to private git repos not maintained anymore are not listed  
c. most recent update to picking the right solution page https://github.com/kubernetes/website/pull/14269 has been updated in https://kubernetes.io/docs/setup/ 
d. vendor specific support level is not listed in the table

Launch card in https://kubernetes.io/docs/home/ has been updated in the latest version of the setup page.

All references/links to Table of Solutions in Picking the right solution page has been removed.

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Please review the preview here:
https://deploy-preview-14427--kubernetes-io-master-staging.netlify.com/docs/home/
https://deploy-preview-14427--kubernetes-io-master-staging.netlify.com/docs/setup/

**Comment by zacharysarah** [comment]
Tangentially:
> GitHub didn't allow me to assign the following users: kbhawkey.

@kbhawkey It looks like you're not yet a member of the Kubernetes org. For someone who's closed [almost 60 PRs in k/website](https://github.com/kubernetes/website/pulls/kbhawkey), that feels like an oversight on our part. 😅 Would you please open a [new membership request](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) in `k/org`? I'm happy to sponsor you, and I bet @Rajakavitha1 would be as well.

**Comment by zacharysarah** [comment]
@Rajakavitha1 Can you say more about the addition of the `card:` attribute to the front matter and what changes we should see consequently?

**Comment by kbhawkey** [comment]
@Rajakavitha1, adjoining pages from the Setup section have links to `Table of solutions`. The links should be updated to the new table from the Setup page? See `https://kubernetes.io/docs/setup/turnkey/aws/` as an example.

**Comment by zacharysarah** [comment]
@rajakavitha1 Great issue description btw! ✨

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1, adjoining pages from the Setup section have links to `Table of solutions`. The links should be updated to the new table from the Setup page? See `https://kubernetes.io/docs/setup/turnkey/aws/` as an example.

Thank you so much!!!! I missed it :)

**Comment by tengqm** [comment]
whoops, there is a conflict!!!

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1 Can you say more about the addition of the `card:` attribute to the front matter and what changes we should see consequently?

Thanks @zacharysarah !!! The card attribute changes reflect in https://deploy-preview-14427--kubernetes-io-master-staging.netlify.com/docs/home/ under "Set up a cluster" card that contained the links to headings in Picking the right solutions page.

**Comment by Rajakavitha1** [comment]
@tengqm  I just resolved the conflicts :)

**Comment by zacharysarah** [comment]
@Rajakavitha1 Please squash your commits so we can merge this PR. 👍

**Comment by Rajakavitha1** [comment]
@zacharysarah !!! Please help.... I messed the squash commits

**Comment by Rajakavitha1** [comment]
was not able to squash commits . inadvertently reverted the commits

**Pull request closed without merging**
