### PR TITLE
Change 名字空间 to 命名空间

### PR DESCRIPTION
**Pull request by yinyicao**
命名空间比名字空间更易于理解

### CODE REVIEW

**Comment by Sea-n** [comment]
I agree `namespace` should be translated to `命名空間` instead of `名稱空間` too.

But according to [中文翻譯指南](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7), both term are acceptable.

And `名稱空間` appeared 779 times in 106 files, compares to `命名空間` only appeared 413 times in 98 files.

This should be a GitHub issue instead of send this PR to modify single file, and it need to be discussed with all Chinese translator. 🙃

**Comment by mengjiao-liu** [comment]
I agree with @Sea-n, please submit an issue.@yinyicao
/cc @tengqm  @howieyuen

**Comment by howieyuen** [comment]
We have already discussed this issue for quite a long time, and conclusion just as [术语对照](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7)，these two are both accepted. 
I prefer to "命名空间" because it is a well-known called with all my colleagues, so I suggest to translate as "命名空间" in new docs, but do we have to update the legacy? that's a question.

**Comment by cobb-tx** [comment]
@howieyuen 我也觉得namespace翻译成命名空间，是一个比较好的使用习惯。名字空间看的怪怪的。

**Pull request closed without merging**
