### PR TITLE
Fix out-of-date name for ServiceAccount

### PR DESCRIPTION
**Pull request by mikamboo**
Use coherent code example with description

### CODE REVIEW

**Review by divya-mohan0209 — COMMENTED** [review]
I'm not sure what's the value add here. Please could you clarify what improvement in coherence are you proposing with a change in the name of the token?

**Review by divya-mohan0209 — COMMENTED** [review]
I'm sorry, I didn't see the text above before commenting previously. Thank you for these changes.
/lgtm
/approve
/hold

**Comment by sftim** [comment]
@divya-mohan0209 - can you clarify why you held this PR and when (under what conditions) you feel it'd be OK for an org member to unhold it?

I think this helps with issue #38357

/retitle Fix out-of-date name for ServiceAccount

**Comment by divya-mohan0209** [comment]
I'm sorry I had forgotten to unhold this one right after I checked the other PR that was for the same issue. We are good to unhold this and merge :) I'll do it!

**Pull request merged**
