### PR TITLE
Update Docker installation instructions to use 19.03.8

### PR DESCRIPTION
**Pull request by hakman**
The docs for installing Docker are a bit outdated. The new 19.03.8 contains various bug fixes that should improve stability:
https://docs.docker.com/engine/release-notes/#19038

### CODE REVIEW

**Comment by hakman** [comment]
Thanks @neolit123

**Comment by truongnh1992** [comment]
/lgtm
Thanks

**Comment by VineethReddy02** [comment]
@sftim Can you have a final look on this?

**Comment by sftim** [comment]
/sig cluster-lifecycle
The existing [/lgtm](https://github.com/kubernetes/website/pull/19643#pullrequestreview-374807003) stands, and I'm confident that @neolit123 knows what they are talking about.

/approve

**Pull request merged**
