### PR TITLE
Placehold empty commit for 1.18 Dry-run

### PR DESCRIPTION
**Pull request by apelisse**
This is empty for now.

cc @julianvmodesto

### CODE REVIEW

**Comment by VineethReddy02** [comment]
👋 Please rebase this PR on `dev-1.18` in order to avoid merge conflicts.

Feel free to `/hold cancel` after you've rebased.

/hold

**Comment by sftim** [comment]
@apelisse is this PR still needed? Does #19549 supersede it?

**Comment by VineethReddy02** [comment]
Hi, @apelisse today is the deadline for docs placeholder PR to be ready for review state. I see the status of the doc as still TODO Can I know by when can I expect all the docs to be ready for review state?

**Comment by julianvmodesto** [comment]
Yes https://github.com/kubernetes/website/pull/19549 supersedes this placeholder and is ready for review

**Pull request closed without merging**
