### PR TITLE
zh-trans: merge release-1.12 into  release-1.14

### PR DESCRIPTION
**Pull request by SataQiu**
Ref #13745

/cc @chenrui333 @tengqm @markthink @xichengliudui

### CODE REVIEW

**Comment by SataQiu** [comment]
/cc @zacharysarah 

Hi @zacharysarah @chenrui333 @tengqm @xichengliudui @markthink ，
sig-docs-zh team has worked on release-1.12 for quite a long time. 
Now we should consider to merge release-1.12 into release-1.14 . 
Then we can work on the release-1.14, and translate new content as much as possible to avoid falling behind continually.

But the label `do-not-merge/invalid-commit-message` has been added to this PR.
This could be due to an incorrect comment in the history commit records.
Any good suggestions to deal with this problem?

**Comment by tengqm** [comment]
@SataQiu This is a big job. Many thanks for working on this.
/lgtm

**Comment by markthink** [comment]
@SataQiu thanks
/lgtm

**Comment by chenrui333** [comment]
Thanks for taking the initiative!! Great job!
/lgtm

**Comment by chenrui333** [comment]
@SataQiu 
Besides resolving the conflicts, the only concern is to only having `content-zh` related changes.

That may require one more additional commit.

**Comment by zhangxiaoyu-zidif** [comment]
It's a big job. Some one commit wrong or invalid commit messages in this PR, but it's too hard to find it out. After inner zh-conversations, we ignore it currently.

**Pull request merged**
