### PR TITLE
 Merge main into dev-1.26 to keep in sync

### PR DESCRIPTION
**Pull request by sftim**
Merge main branch into dev-1.26 to keep in sync, part of the Docs activities in the release process, see [here](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#maintain-the-current-and-upcoming-dev-branch).

/cc @krol3 @cathchu @mickeyboxell @katmutua @Rishit-dagli 

This PR could supersede #38197

/sig release
/milestone 1.26

### CODE REVIEW

**Comment by tengqm** [comment]
"merge main into dev-1.26" ... doesn't that mean that this PR should target `dev-1.26` rather than `main`?
/hold

**Comment by sftim** [comment]
Whoops!

**Review by Rishit-dagli — APPROVED** [review]
\lgtm

**Comment by sftim** [comment]
If / when this lands, PR https://github.com/kubernetes/website/pull/38284 will need a rebase.

**Review by Rishit-dagli — APPROVED** [review]
Oops /lgtm

**Review by krol3 — APPROVED** [review]
/lgtm

**Comment by sftim** [comment]
@Rishit-dagli I'm taking your LGTM as a hint that's you're happy for this to supersede https://github.com/kubernetes/website/pull/38197

/hold cancel

**Pull request merged**
