### PR TITLE
Update kubectl docs/Explain beta docs

### PR DESCRIPTION
**Pull request by alexzielenski**
Regenerates kubectl documentation to include quite a few missed changes, as well as the new `explain` functionality.

### CODE REVIEW

**Comment by mickeyboxell** [comment]
Hi @alexzielenski, when you're ready, populate your placeholder PR with feature documentation and change the state of the PR from **draft** to **ready for review**. The official Docs deadline for PRs to be ready for review is tomorrow, March 21st. All docs PRs must be reviewed and ready to merge by April 4th. To mark a pull request as ready for review, navigate to the merge box and click Ready for review.

Regarding the content of your documentation, do your best to describe your feature and how to use it. If you need help structuring your documentation, ask in the #sig-docs Slack channel. For more information, please take a look at [Documenting for a release](https://kubernetes.io/docs/contribute/new-content/new-features/#for-developers-or-other-sig-members) to familiarize yourself with the documentation requirements for the release.

**Comment by alexzielenski** [comment]
I've ran the commands to regenerate the kubectl reference. it has a lot of updates but the new flags for explain are not included.

**Comment by tengqm** [comment]
@alexzielenski You will have to update the `go.mod` file before regenerate the reference. The update must happen before the 1.27 release is out. In addition to this, you may have to update `generators/v1_27/toc.yaml` if old commands are dropped and/or new commands are introduced.

If this is targeting 1.27, you will have to target `dev-1.27` branch, or after the 1.27 docs is released, target `main` branch after the release date.

**Comment by mickeyboxell** [comment]
@alexzielenski Did you get a chance to make @tengqm suggested changes?

**Comment by alexzielenski** [comment]
Unfortunately I'm still having trouble with it.

I rebased on dev-1.27
I updated all kubernetes versions in go.mod and in all the api-ref-generator go.mod files to point to v0.27.0-rc.0. Some were on v0.22.0, others on 0.26.0.
`make createversiondirs` from 0.22 to 0.27 since `generators` folder was missing the last few
`K8S_RELEASE=1.27.0 make copycli`. Hit strange javascript error:

```
❯ K8S_RELEASE=1.27.0 make copycli                                                                                                                                            (55bce68) *​​ ≡
sudo rm -f main
sudo rm -rf /Users/alex/go/src/k8s.io/website/api-ref-generator/gen-kubectldocs/generators/includes
sudo rm -rf /Users/alex/go/src/k8s.io/website/api-ref-generator/gen-kubectldocs/generators/build
sudo rm -rf /Users/alex/go/src/k8s.io/website/api-ref-generator/gen-kubectldocs/generators/manifest.json
pushd gen-kubectldocs && go mod download && go run main.go --kubernetes-version v1_27 && popd
~/go/src/k8s.io/website/api-ref-generator/gen-kubectldocs ~/go/src/k8s.io/website/api-ref-generator
~/go/src/k8s.io/website/api-ref-generator
mkdir -p gen-kubectldocs/generators/build
docker run -v /Users/alex/go/src/k8s.io/website/api-ref-generator/gen-kubectldocs/generators/includes:/source -v /Users/alex/go/src/k8s.io/website/api-ref-generator/gen-kubectldocs/generators/build:/build -v /Users/alex/go/src/k8s.io/website/api-ref-generator/gen-kubectldocs/generators/:/manifest brianpursley/brodocs:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
https://github.com/highlightjs/highlight.js/issues/2877
TypeError: Cannot read property 'substring' of undefined
Please report this to https://github.com/markedjs/marked.
    at Renderer.renderer.code (/brodocs/markedDecorations.js:54:33)
    at Parser.tok (/brodocs/node_modules/marked/lib/marked.js:1058:28)
    at Parser.parse (/brodocs/node_modules/marked/lib/marked.js:1003:17)
    at Function.Parser.parse (/brodocs/node_modules/marked/lib/marked.js:985:17)
    at marked (/brodocs/node_modules/marked/lib/marked.js:1322:19)
    at parseDoc (/brodocs/brodoc.js:84:12)
    at files.forEach (/brodocs/brodoc.js:76:39)
    at Array.forEach (native)
    at parseFileContent (/brodocs/brodoc.js:74:11)
    at fs.readFile (/brodocs/brodoc.js:53:13) '_generated_create.md' '\n------------\n\n# create\n\n>bdocs-tab:example 
<elided long generated markdown file>
ob/brodocs/brodoc.js:79
          throw e;
          ^

TypeError: Cannot read property 'substring' of undefined
Please report this to https://github.com/markedjs/marked.
    at Renderer.renderer.code (/brodocs/markedDecorations.js:54:33)
    at Parser.tok (/brodocs/node_modules/marked/lib/marked.js:1058:28)
    at Parser.parse (/brodocs/node_modules/marked/lib/marked.js:1003:17)
    at Function.Parser.parse (/brodocs/node_modules/marked/lib/marked.js:985:17)
    at marked (/brodocs/node_modules/marked/lib/marked.js:1322:19)
    at parseDoc (/brodocs/brodoc.js:84:12)
    at files.forEach (/brodocs/brodoc.js:76:39)
    at Array.forEach (native)
    at parseFileContent (/brodocs/brodoc.js:74:11)
    at fs.readFile (/brodocs/brodoc.js:53:13)
make: *** [cli] Error 1
```

**Comment by mickeyboxell** [comment]
@sftim @reylejano do you know how to correct the error above?

**Comment by reylejano** [comment]
Looks like you're bringing changes from the `dev-1.27` branch into the `main` branch
If this PR is intended for the 1.27 release, try changing the base to the `main` branch.
You do this with the UI and click edit and change the base branch from the drop down menu to `dev-1.27`
More details with screenshots are found here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by mickeyboxell** [comment]
@alexzielenski could you try what @reylejano suggested when you have a moment?

**Comment by sftim** [comment]
/hold
/approve

I agree with the intent of this PR. You are welcome to unhold it once it has an LGTM that _you_ are happy with @alexzielenski 

(any org member can LGTM, so you might get a review that says LGTM even before the last bug you're aware of is actually dealt with).

**Comment by sftim** [comment]
PS. Would be nice to record that intent in the PR description.

**Comment by mickeyboxell** [comment]
@alexzielenski If you are comfortable removing the hold from this PR, we can get it merged.

**Comment by reylejano** [comment]
We may have to compare with a kubectl ref docs generation after the 1.27 release

/unhold

**Pull request merged**
