### PR TITLE
Add new feature gates to document

### PR DESCRIPTION
**Pull request by charrywanganthony**
ref: [70508](https://github.com/kubernetes/kubernetes/pull/70508)  [70831](https://github.com/kubernetes/kubernetes/pull/70831)

### CODE REVIEW

**Comment by tengqm** [comment]
@charrywanganthony Master is the ongoing maintenance version of 1.12. dev-1.13 is about the 1.13 features under development. When 1.13 is out, dev-1.13 becomes the new master and we will have dev-1.14 for caching new changes for 1.14 release.
This is unlike the upstream code because everything you push into master will become immediately public. So the master branch for doc is only meant for the latest release (`1.12` today).

**Comment by Bradamant3** [comment]
@charrywanganthony sorry I merged #11307 before I saw this one. Can you rebase please? Thanks! (A quick glance suggests we need both, but if this one is duplicated by 11307 you could close instead.)

**Comment by charrywanganthony** [comment]
Conflict resolved(use github website).

**Comment by charrywanganthony** [comment]
Conflict resolved(use github website). @Bradamant3

**Pull request merged**
