### PR TITLE
error in link to edx courses

### PR DESCRIPTION
**Pull request by Vskilet**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7273)

### CODE REVIEW

**Comment by tengqm** [comment]
content okay. pls sign CLA.

**Comment by bradtopol** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/website/7273#-:-L4n8xm7FS_koIKdVhHY:bnfp4nl)*

**Comment by heckj** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/website/7273#-:-L5BIENKD4vqsSI_V0PU:bnfp4nl)*

**Pull request merged**
