### PR TITLE
[ja] Fix a non-existent link

### PR DESCRIPTION
**Pull request by NamikoToriyama**
## Description
This page was linking to a non-existent URL.

## Reference
en: https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/debug-application-cluster/debug-pod-replication-controller.md#insufficient-resources
zh: https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/debug-pod-replication-controller.md#%E8%B5%84%E6%BA%90%E4%B8%8D%E8%B6%B3

### CODE REVIEW

**Comment by NamikoToriyama** [comment]
It's possible that the original link has been moved here🤔
https://kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#join-nodes

**Comment by atoato88** [comment]
/assign @nasa9084
could you review this?

@NamikoToriyama
It's good to assign reviewers for smooth PR process, [as said k8s-ci-bot.](https://github.com/kubernetes/website/pull/29176#issuecomment-890379489)

**Comment by NamikoToriyama** [comment]
@atoato88 Thank you🙏

**Pull request merged**
