### PR TITLE
Localize home/supported-doc-versions.md to Arabic

### PR DESCRIPTION
**Pull request by adowair**
This commit will add a file `content/ar/home/support-doc-versions.md` containing an Arabic translation of the `content/en` counterpart. This is part of the effort to localize the minimum required documents for a new localization, as outlined in **Step 9** of #44682:

>  9. Open PRs to localize all minimum-required-contents and a localized README file
>  https://kubernetes.io/docs/contribute/localization/#minimum-required-content
>  https://kubernetes.io/docs/contribute/localization/#add-a-localized-readme-file
>  **Note:** base and target branches of the PR should be the dev branch of AR.
>  **Note:** at this moment, candidates for Arabic reviewers and approvers do not have an authority yet. However reviews on localized contents from the candidates are required. Use /lgtm to express a PR is ready to be merged.

This pull request replaces #44117.

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Localize home/supported-doc-versions.md to Arabic

(we avoid Markdown in commit messages)

**Comment by sftim** [comment]
This is ready for reviews by people who can speak both Arabic and English.

**Comment by seifrajhi** [comment]
LGTM for Arabic

**Review by sftim — COMMENTED** [review]
Localization LGTM: https://github.com/kubernetes/website/pull/44698#issuecomment-1919352239

Not a change to the live site.

/lgtm
/approve

**Pull request merged**
