### PR TITLE
Fixing docker image building process (v1.18 docs)

### PR DESCRIPTION
**Pull request by chienfuchen32**
Fixing #29785 ,  not sure if this is a good solution here.

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Fixing docker image building process (v1.18 docs)

**Comment by reylejano** [comment]
The proposed change in this PR fails the docker build for me.
Another reviewer should test and confirm

**Review by sftim — COMMENTED** [review]
This change seems to not break things, but I don't think it's needed. I'd want to know why the change was required.

**Comment by chienfuchen32** [comment]
Hi, @sftim, here's the case what I've bump into on Ubuntu 20.04: https://github.com/kubernetes/website/issues/29785
After changing Dockerfile, `make docker-image` worked.

**Comment by sftim** [comment]
Hi @chienfuchen32

I still don't know that this change is needed, and I'd want to know why the change was required. Could you update the PR description accordingly?

Why does this PR specifically target the branch _release-1.18_?

/hold

A reviewer may close this PR if the context does not become sufficiently clear.

**Comment by chienfuchen32** [comment]
Hi @sftim.
I found that is not able to build as docker image on version 1.18, I think it's related to the environment provided by base image of `Dockerfile`. What've changed is reference to main branch. It works on my environment.

**Comment by sftim** [comment]
Docs for v1.18 are no longer supported (see https://kubernetes.io/docs/home/supported-doc-versions/)

Is this pull request useful for the _main_ branch? If so, please explain how it helps.

**Comment by chienfuchen32** [comment]
Dear @sftim, I see. there's no need to merge into `main` branch which works perfectly.
If v1.18 is no longer support, closing this PR is totally fine. Thanks

**Pull request closed without merging**
