### PR TITLE
Remove the page */tools/krib/

### PR DESCRIPTION
**Pull request by Nishikoh**
Issue:  #20239 

> Problem:
> The page [Installing Kubernetes with KRIB](https://kubernetes.io/docs/setup/production-environment/tools/krib/) does not fit with the website [content guide](https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed) and the criteria for permitted content.
> 
> Proposed Solution:
> Remove the page https://kubernetes.io/docs/setup/production-environment/tools/krib/
> Netlify does not support 410 Gone as a response status, so remove the page outright (no redirect etc).

  
Solution:
+ Removed the page 
  - https://kubernetes.io/docs/setup/production-environment/tools/krib/
  - ~~https://kubernetes.io/ja/docs/setup/production-environment/tools/krib/~~
+ No redirect

### CODE REVIEW

**Comment by sftim** [comment]
Removals are a bit easier to approve because they are never incorrectly localized :wink:
_but_ only a few approvers can provide the override approval to approve across localizations, so the removal might take longer overall.

**Comment by sftim** [comment]
There are no technical inaccuracies, so
/lgtm

**Comment by Nishikoh** [comment]
I restricted PR to a single language.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-20515--kubernetes-io-master-staging.netlify.app/docs/setup/

**Comment by kbhawkey** [comment]
This change comes under the umbrella issue, https://github.com/kubernetes/website/issues/20232.
LGTM
Thanks @Nishikoh .
/approve

**Pull request merged**
