### PR TITLE
Update TTL mechanism in Job to stable feature state

### PR DESCRIPTION
**Pull request by atoato88**
This PR updates feature state for [TTL mechanism](https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs) in Job with stable.
[According to here](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/), TTL mechanism (enabled by `TTLAfterFinished` feature gate) has been GA from k8s v1.23, so we can update "beta" to "stable".

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Preview: https://deploy-preview-31608--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs

**Comment by reylejano** [comment]
The change in this PR is correct, this feature graduated to stable in 1.23
/lgtm

**Pull request merged**
