### PR TITLE
fix links

### PR DESCRIPTION
**Pull request by windayski**
fix broken links

### CODE REVIEW

**Comment by xichengliudui** [comment]
/lgtm
/approve
@windayski good job

**Comment by tanjunchen** [comment]
ref:https://github.com/kubernetes/website/issues/17649

**Comment by tanjunchen** [comment]
/cc @sftim  
for en

**Comment by sftim** [comment]
I'm not a blog reviewer. No objection to these changes though.
/uncc

**Comment by bradtopol** [comment]
Approving this as a PR wrangler since blog updates are only link updates

**Comment by tanjunchen** [comment]
ref:https://github.com/kubernetes/website/issues/17649

**Pull request merged**
