### PR TITLE
Make website responsive and don't force min-width

### PR DESCRIPTION
**Pull request by kevinsimper**

### CODE REVIEW

**Comment by kevinsimper** [comment]
I signed it

**Comment by zacharysarah** [comment]
@kevinsimper 👋 Thanks for submitting this fix. Welcome to Kubernetes! 🎉 

Verified on mobile staging (and so much better): https://deploy-preview-13417--kubernetes-io-master-staging.netlify.com/blog/

/lgtm
/approve

**Comment by kevinsimper** [comment]
@zacharysarah Thank you 😄 🎉

**Comment by zacharysarah** [comment]
@kevinsimper If you're interested in joining the org, this PR is one step on the [pathway to membership](https://github.com/kubernetes/community/blob/master/community-membership.md#member). I'm happy to answer questions if you have them.

**Comment by kevinsimper** [comment]
@zacharysarah Thank you for suggesting that, I will definitely take a look!

**Pull request merged**
