### PR TITLE
add Arhell to sig-docs-ru-owners

### PR DESCRIPTION
**Pull request by Arhell**
/assign @shurup

### CODE REVIEW

**Comment by natalisucks** [comment]
@Arhell @shurup Is there a Slack discussion or thread we can reference for the decision to add an approver here? Thanks in advance 🤝

**Comment by Arhell** [comment]
> @Arhell @shurup Is there a Slack discussion or thread we can reference for the decision to add an approver here? Thanks in advance 🤝

Alas, no, I decided to add myself because I have been a member for a long time https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES#L221
and lately there are very few active people who can approve PR

**Comment by shurup** [comment]
There was no discussion indeed, but I would be happy to have @Arhell in the Russian localization team. We didn't have anyone active there for a long time. After my recent addition, it's just me.

/lgtm

P.S. I'm also wondering how we can (and should we?) remove old members who didn't do anything for the localization for a while. I didn't find any specific criteria for that. Currently, they are still automatically assigned for new PRs, but it's misleading since nothing will happen then.

**Comment by natalisucks** [comment]
@shurup @Arhell Having the discussion about decisions like this is fine in a PR like this one, however, it also helps folks outside of your localization (like Qiming and myself) when there's an active Slack thread or issue so we can help approve these additions quicker and more efficiently for you, given the lack of RU contributors at the moment. I'd also recommend having more information in the PR description itself, rather than only assigning the owner for approval.

When it comes to removing other approvers/reviewers who are now inactive, we generally ask that you try and reach out somehow (either in Slack or in issues/PRs) to do a final courtesy check about their status, and then raise the required PR to remove them. Again, some discussions or threads are good to reference so that approvers outside your localization can help move things along for you and make approvals easier 😸 

Feel free to go ahead and raise the needed PR to clean up your approvers and tag me when ready for review so that we can get your localization back into a good state!

cc. @a-mccarthy for visibility (our Localization subproject lead)

**Comment by shurup** [comment]
@natalisucks: thanks a lot for your helpful, detailed feedback! I completely agree that having more information in the PR itself would be great.

As for another problem, I was trying to reach all Russian approvers before, but I'd do it again and raise a relevant PR then.

**Pull request merged**
