### PR TITLE
Fix NodePodSelector annotation name

### PR DESCRIPTION
**Pull request by tengqm**
Resubmitted to master branch.

### CODE REVIEW

**Comment by Bradamant3** [comment]
I can't tell whether I'm nitpicking or catching an issue here. Should the annotation key be the same wherever you use it? If so, should it be `scheduler.alpha.kubernetes.io/node-selector`? Or `scheduler.alpha.kubernetes.io/nodeSelector`?

**Comment by heckj** [comment]
@tengqm 👋 looks like this needs a rebase, and I didn't see any answer to @Bradamant3 question about the content. 

/assign

**Comment by tengqm** [comment]
Closing because the master branch already has this fix.

**Pull request closed without merging**
