### PR TITLE
Consolidate all upgrade/downgrade admin tasks

### PR DESCRIPTION
**Pull request by tengqm**
This propose consolidate cluster upgrade/downgrade pages into one
subtopic which can serve an umbrella for future changes in this field.

### CODE REVIEW

**Comment by steveperry-53** [comment]
/assign
/approve
/lgtm

@tengqm Thanks. If you can fix the merge conflict, this will get merged.

**Comment by zacharysarah** [comment]
@tengqm 👋 Pinging to resolve the merge conflict.

**Comment by tengqm** [comment]
@zacharysarah rebased and solved merge conflicts.

**Pull request merged**
