### PR TITLE
Update manage-resources-containers.md

### PR DESCRIPTION
**Pull request by mercuriete**
Troubleshooting broken link on spanish language

### CODE REVIEW

**Comment by mercuriete** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
>  **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

reply

**Comment by mercuriete** [comment]
the solución de problemas anchor is in this url:

https://deploy-preview-27784--kubernetes-io-master-staging.netlify.app/es/docs/concepts/configuration/manage-resources-containers/#soluci%C3%B3n-de-problemas

and it work as expected.

**Comment by raelga** [comment]
Thanks @mercuriete for fixing the anchor issue. To be able to publish your contribution, you need to sign the Contributor License Agreement (CLA). The instructions are available at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement, feel free to ping on slack if you have any issue with the documentation or the process!

**Comment by mercuriete** [comment]
@raelga I think I signed the CLA but I can't retrigger the checks.

/check-cla

**Comment by mercuriete** [comment]
@raelga definitely there are something wrong with CLA.
Please drop this PR and fix it as you prefer.

definitivamente hay un problema con el CLA.
Por favor cierra esta PR y arreglen el error ustedes mismos.

thanks :)

**Comment by raelga** [comment]
> Por favor cierra esta PR y arreglen el error ustedes mismos.

Buenas @mercuriete, si tienes slack, podemos intentar solucionar el tema de la CLA. Lo más importante es que el correo que usaste para la los commits de la PR sea con el que has firmado la CLA. No hay prisa en solventar el tema de la CLA para poder añadir tu contribución!

**Comment by electrocucaracha** [comment]
@mercuriete crear un ticket en [JIRA](https://jira.linuxfoundation.org/servicedesk/customer/portal/4/create/88), quiza haga falta un ultimo paso

**Comment by jimangel** [comment]
Hey there! @mercuriete, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by mercuriete** [comment]
I think I did.

I am no longer wanting to merge this PR.
(I dont want to spend time figuring out what is preventing me to merging this)
you are allowed to use this code.
if you want to fix it you can create another one with the same changes.

thanks for your support!

**Comment by raelga** [comment]
> (I dont want to spend time figuring out what is preventing me to merging this)

Sorry to hear that, don't worry. Thanks for the effort.

/close

**Pull request closed without merging**
