### PR TITLE
WIP [es] Add concepts/workloads/[pods/disruptions, concepts/security/controlling-access]

### PR DESCRIPTION
**Pull request by gamba47**
First pr with 25% done.

I'll be updating this soon.

### CODE REVIEW

**Comment by raelga** [comment]
Gracias @gamba47, quedamos a la espera de que esté lista para revisar.

/wip

**Comment by raelga** [comment]
/retitle WIP [es] Add concepts/workloads/[pods/disruptions, concepts/security/controlling-access]

**Comment by gamba47** [comment]
I'm still learning for make pr's i will close this and open other with the correct files.

regards.

**Pull request closed without merging**
