### PR TITLE
Fix typo on a word on french documentation

### PR DESCRIPTION
**Pull request by maximeancellin**
This pull request corrects a typo on french documentation.

### CODE REVIEW

**Comment by ydFu** [comment]
@maximeancellin ,thank you for your contribution.

You must sign the CLA for teams of kubernetes/website to do code reiview.

Please click on the red button `NOT COVERED` line in the first comment.

If you don't know how to do it, here is[the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by maximeancellin** [comment]
Hi,
The easyCLA certificate has signed.

**Comment by kbhawkey** [comment]
@maximeancellin Can you push another commit? The deploy preview did not build.

**Pull request merged**
