### PR TITLE
Propose mrerlison as a reviewer for the pt-br docs

### PR DESCRIPTION
**Pull request by MrErlison**
Over the past few months, I have been contributing to the pt-br localization. As a result of my efforts, I would like to be recognized as an official reviewer for the pt-br localization team.

/language pt
/cc @rikatz @stormqueen1990 @edsoncelio @devlware

### CODE REVIEW

**Comment by rikatz** [comment]
Can confirm, Erlison has been doing a great job!!

/lgtm
/approve

**Comment by stormqueen1990** [comment]
Erlison is doing a great job with reviews for the Portuguese localization! 😃
Thanks for your work! 

/approve

**Comment by devlware** [comment]
+1, Erlison is doing a great job and his work is helping the translate development for pt_BR.

**Pull request merged**
