### PR TITLE
Automatically generate a schedule for PR wranglers

### PR DESCRIPTION
**Pull request by josiahbjorgaard**
This PR is for a python script that automatically generates a PR wrangler schedule on a biquarterly basis and prints a file for the website wiki.

### CODE REVIEW

**Comment by josiahbjorgaard** [comment]
This is a WIP, but in it's current state it can be used to generate a new pr-wrangler doc using the function create_new_wranger_doc([N for 1st quarter], [N for 2nd quarter]), after which the dates can be added by hand.

**Comment by josiahbjorgaard** [comment]
Suggestions on how to handle the dates are welcome. Should user provide a list of dates, in case a week is not on, or should a start date and end date be provided with weekly meetings interpolated in between?

**Comment by zacharysarah** [comment]
@josiahbjorgaard Thanks for this! ✨ 
> Should user provide a list of dates, in case a week is not on, or should a start date and end date be provided with weekly meetings interpolated? 

That's a good question. For a first iteration, I think the idea here is workable. Handling dates would require importing calendar, handling for holidays in multiple countries, then require human review anyway (for vacations and conferences, etc.).

> How are the quarter lengths decided?

They're tied to calendar dates: 
Q1 = January 1 - March 31
Q2 = April 1 - June 30
etc.

**Comment by zacharysarah** [comment]
@josiahbjorgaard 👋 I've tested this locally. It looks like there's some additional setup required for this to work, specifically: the creation of a `website.wiki/` directory; and the addition of a Markdown file containing the wrangler list. After doing both of these and running the script, I'm still not seeing any output. Can you please describe your own local testing?

**Comment by josiahbjorgaard** [comment]
@zacharysarah the website.wiki folder is created by cloning website.wiki with
```git clone https://github.com/kubernetes/website.wiki.git```
which contains the file ```PR-Wranglers.md```. 

The path to the ```PR-Wranglers.md``` file in the website.wiki repo is in the variable ```path_to_wiki``` and can be modified based on where you clone the wiki repo. I cloned it into the same directory where I have the website repo. The output is a new ```PR-Wranglers.md``` called ```PR-Wranglers-new.md``` written to the file given by ```path_to_output```. That file can be modified with the dates and replace the old ```PR-Wranglers.md```. The wiki.git repo can than be pushed to update the PR Wrangler list.

I think that there could be an easier way to operate this. I'm not sure how to modify the wiki page in place with a python script, though, so downloading the wiki repo would be necessary. It could easily be modified to operate from command line like below.

```
./gen_pr_wrangler_list.py
What is the path to the PR-Wranglers.md file from the wiki?
../website.wiki/PR-Wranglers.md
Where should the new PR-Wranglers.md file be written?
../website.wiki/.
How many weeks are in the first quarter?
7
How many weeks are in the second quarter?
8
Writing...Done
```

**Comment by zacharysarah** [comment]
@josiahbjorgaard 👋 Please feel free to `/reopen` if you think this might still be valuable.

/close

**Pull request closed without merging**
