### PR TITLE
[ru] remove extra tags in KubeCon section

### PR DESCRIPTION
**Pull request by Arhell**
### Issue

Closes: #

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Based on the preview [page (here)](https://deploy-preview-48550--kubernetes-io-main-staging.netlify.app/ru/), the changes look good to me.
/lgtm

[Fixed 'ru' Homepage](
https://deploy-preview-48550--kubernetes-io-main-staging.netlify.app/ru/) | [Current 'ru' Homepage](https://kubernetes.io/ru/)

**Comment by shurup** [comment]
It was me who put those extra `<br>`'s. Now, I realise there's a problem due to this page being rendered differently in different browsers. 

Here's an updated version as offered in this PR rendered in Chrome/Linux. Looks good:
image

But here's what will happen in Firefox/Linux (which I use by default). Doesn't look good:
image

I need to think about what can be done to avoid this in Firefox after we remove extra `<br>`'s.

**Review by Arhell — COMMENTED** [review]
Close

**Comment by shurup** [comment]
According to my current experiments, it has something to do with the fonts. If we use a smaller font (`15px` instead of `18px`) or a bigger `line-height` (e.g. `1.8` instead of `1.5`) in the Russian version, everything works fine. To conclude, it looks like different fonts are used or they are rendered differently (for the Russian version). Someone with good, relevant experience (CSS for Firefox) is needed to solve this.

**Comment by Arhell** [comment]
> According to my current experiments, it has something to do with the fonts. If we use a smaller font (`15px` instead of `18px`) or a bigger `line-height` (e.g. `1.8` instead of `1.5`) in the Russian version, everything works fine. To conclude, it looks like different fonts are used or they are rendered differently (for the Russian version). Someone with good, relevant experience (CSS for Firefox) is needed to solve this.

Good solution, but in my opinion I would redo this section as a whole.

**Comment by shurup** [comment]
> in my opinion I would redo this section as a whole.

I would definitely support this! It started a while ago with fewer conferences/buttons in place. Later, it hasn't evolved well enough to handle current needs. It should be fixed in the original (English) version first then.

**Comment by shurup** [comment]
JFYI: #49167 should resolve the issue we've discussed here.

**Pull request closed without merging**
