### PR TITLE
Update 2020-04-06-API-Priority-and-Fairness-Alpha.md

### PR DESCRIPTION
**Pull request by Raen123**

### CODE REVIEW

**Comment by network-charles** [comment]
Hi @Raen123, congrats on your first PR. I noticed that you haven’t signed the Contributor License Agreement (CLA) yet. Kindly sign the agreement to proceed with this PR.

**Comment by sftim** [comment]
To learn about the copyright agreement, please visit https://www.kubernetes.dev/docs/guide/#sign-the-cla

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by divya-mohan0209** [comment]
@Raen123 : Please sign the CLA and consider reopening the PR, once done.
/close

**Pull request closed without merging**
