### PR TITLE
Fix grammatical errors

### PR DESCRIPTION
**Pull request by power8993**
Fix grammatical errors
/language ko

### CODE REVIEW

**Comment by gochist** [comment]
@power8993 감사합니다!
/lgtm

**Comment by gochist** [comment]
@seokho-son 최종 승인 부탁드립니다.
/assign @seokho-son 
/unassign @ClaudiaJKang @gochist

**Comment by seokho-son** [comment]
@power8993 Thank you for your contribution !!
I agree with your fix for grammatical errors :)
/approve

**Pull request merged**
