### PR TITLE
Fix link to Volume Plugin FAQ

### PR DESCRIPTION
**Pull request by ebriand**
Hey 👋 

A very small PR to fix the link to the Volume Plugin FAQ (removed a misplaced space) 👍

### CODE REVIEW

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-25761--kubernetes-io-master-staging.netlify.app/docs/concepts/storage/persistent-volumes/#volume-snapshot-and-restore-volume-from-snapshot-support

Thanks @ebriand .
/approve

**Pull request merged**
