### PR TITLE
add ja/case-studies/...

### PR DESCRIPTION
**Pull request by xichengliudui**
cp en/case-studies/... to en/case-studies/...

### CODE REVIEW

**Comment by nasa9084** [comment]
thank you for your PR, but why only case-studies added?

**Comment by xichengliudui** [comment]
@nasa9084  There are many contents. I am translating them，thanks

**Comment by tengqm** [comment]
don't get the point of such batch copies. this PR is coping case study contents from English site to **Japanese** site, by  the way.

**Comment by xichengliudui** [comment]
Do I need to close this PR?

**Comment by tengqm** [comment]
@xichengliudui It is up to the ja translation reviewers. I'd suggest close this PR because: 1. I are not sure you will translate them; 2. ja translation team may have their own agenda which should be respected; 3. this PR is causing more confusion than solving problems.

**Comment by xichengliudui** [comment]
Ok, thanks for reminding me

**Comment by nasa9084** [comment]
there is no problem to translate and create a new PR after you translate the pages.
thank you!

**Pull request closed without merging**
