### PR TITLE
[ja]Update feature gate table

### PR DESCRIPTION
**Pull request by YuikoTakada**
This PR updates `AlphaまたはBetaのフィーチャーゲート` table and `GraduatedまたはDeprecatedのフィーチャーゲート` table in https://kubernetes.io/ja/docs/reference/command-line-tools-reference/feature-gates/ following to original doc: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

### CODE REVIEW

**Comment by s-kawamura-w664** [comment]
I compared ja to en. And I confirmed that the tables in them are same. No problem at all.
/lgtm

**Review by t-inu — APPROVED** [review]
LGTM

**Comment by atoato88** [comment]
The target page on preview site:
https://deploy-preview-38778--kubernetes-io-main-staging.netlify.app/ja/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features

And LGTM.

**Pull request merged**
