### PR TITLE
Update kubectl overview page - update list of available operations

### PR DESCRIPTION
**Pull request by sharet-adl**
Fixing issue with missing operations available in current version of kubectl.
The issue started based on the following statement, which is not accurate: "The following table includes short descriptions and the general syntax for all of the kubectl operations: ..".

The list of operations supported by the current version of kubectl v1.18 is bigger.
It's mainly one of the following 3 options:
a. either update this page manually, with each upgrade ( for now, this is the proposal of current PR )
b. or update the description to say something like "The following table includes short descriptions and the general syntax for some of the most important kubectl operations: .."
c. or find a way to generate this table dynamically, during the CI/release build, based on the kubectl command itself. A nice option would be to reuse the 'kubectl --help' output.. so either to enhance it (as it doesn't fit the need exactly), or to have a separate flag to generate this sort of output needed here. Reuse is the key.

For now, the proposed fix is to go with option a).
The proposed solution is to add the missing options and short description for each of them.

Kubectl version used was 1.18.2 (GitCommit:"52c56ce7a8272c798dbc29846288d7cd).

### CODE REVIEW

**Comment by sharet-adl** [comment]
dummy comment, trigger retest of CLA

**Comment by jimangel** [comment]
Thanks for the PR @sharet-adl, I believe this documentation is generated per release. @kbhawkey and @tengqm will be able to confirm.

If it is missing, we might need to update the scripts in https://github.com/kubernetes-sigs/reference-docs

**Comment by tengqm** [comment]
Em. I dont think we have a generator for the overview page. @kbhawkey WDYT?

**Comment by kbhawkey** [comment]
Hi. No this page is _not_ auto-generated.
I would prefer to rely upon an overview page that is sourced from
the information in the kubectl code.
If the command descriptions in this file add value, perhaps the content could be
added to the kubectl code in `kubernetes/kubernetes`.
I'd like to see more content generated from the kubectl source code.

**Comment by sharet-adl** [comment]
@kbhawkey: this enhancement is what I have suggested as point c)
_c. or find a way to generate this table dynamically, during the CI/release build, based on the kubectl command itself. A nice option would be to reuse the 'kubectl --help' output.. so either to enhance it (as it doesn't fit the need exactly), or to have a separate flag to generate this sort of output needed here. Reuse is the key._

This enhancement could be taken as a separate task.

As a quick fix, I have proposed for now the approach a), just fixing it for current release.

**Comment by kbhawkey** [comment]
Hi @sharet-adl , Are you able to _rebase_ your branch?
https://kubernetes.io/docs/contribute/new-content/new-content/#merge-conflicts-and-rebasing

**Comment by sharet-adl** [comment]
@kbhawkey please recheck

**Comment by kbhawkey** [comment]
Thank @sharet-adl . Changes look good to me.

Page preview:
https://deploy-preview-20848--kubernetes-io-master-staging.netlify.app/docs/reference/kubectl/overview/#operations

Are you able to _squash_ your commits into a single commit?
https://kubernetes.io/docs/contribute/new-content/new-content/#squashing-commits

**Comment by sharet-adl** [comment]
I have created a new PR - https://github.com/kubernetes/website/pull/20909.
I have re-forked and I Github was not able to reference it automatically.
Is there a way to link this new PR to the current issue ? Was an issue automatically created for the original PR in the first place ?

Thank you

**Comment by kbhawkey** [comment]
> 
> 
> I have created a new PR - #20909.
> I have re-forked and Github was not able to reference it automatically.
> Is there a way to link this new PR to the current issue ? Was there an issue automatically created for the original PR in the first place ?

Hi, @sharet-adl .
I will look at the follow-on PR. By referencing #20909 here, you have linked the two pull requests.
An issue was not automatically created for you.

**Comment by kbhawkey** [comment]
Duplicate with #20909.
/close

**Comment by sharet-adl** [comment]
> > I have created a new PR - #20909.
> > I have re-forked and Github was not able to reference it automatically.
> > Is there a way to link this new PR to the current issue ? Was there an issue automatically created for the original PR in the first place ?
> 
> Hi, @sharet-adl .
> I will look at the follow-on PR. By referencing #20909 here, you have linked the two pull requests.
> An issue was not automatically created for you.

@kbhawkey: was there an issue supposed to be automatically created for it when pressing the 'Edit this Page', or it is like this per design ? PRs with no link to any tracking issue don't seem fine.

**Comment by kbhawkey** [comment]
@sharet-adl , You are welcome to submit an issue with your suggestions. Thanks!

**Pull request closed without merging**
