### PR TITLE
Replace dead cosigned with sigstore policy-controller

### PR DESCRIPTION
**Pull request by varas**
`sigstore/cosigned` was moved & renamed to `sigstore/policy-controller`.
Previous links are no longer available.

### CODE REVIEW

**Comment by reylejano** [comment]
/lgtm from a SIG Docs view
@PushkarJ & @puerco , ptal

**Review by hectorj2f — APPROVED** [review]

**Comment by PushkarJ** [comment]
/lgtm 
/approve

(@puerco please revert / update if you see anything missing or incorrect. Thanks to everyone who reviewed this!)

**Comment by PushkarJ** [comment]
assign @onlydole

**Comment by natalisucks** [comment]
Given we've had sign-off from both SIG Docs and Cosign, I'm approving the change – thanks!
/approve

**Comment by puerco** [comment]
Sorry I completely missed my mentions on this PR until now that it merged. Sorry about that. FWIW it LGTM. 

Thanks everybody for your help reviewing!

**Pull request merged**
