### PR TITLE
Update Kubernetes architectural diagram

### PR DESCRIPTION
**Pull request by sftim**
This PR updates the Kubernetes cluster architecture diagram used in [Kubernetes Components](https://kubernetes.io/docs/concepts/overview/components/). [[_preview_](https://deploy-preview-23138--kubernetes-io-master-staging.netlify.app/docs/concepts/overview/components/)]

This PR, a follow-up to #20767, is part of an effort to improve consistency between Kubernetes icons and diagrams on the official Kubernetes Docs website. Collaboration prior to this point includes a [Google Draw document](https://docs.google.com/drawings/d/11P-yXzso7zapqyqP3ulnIsQ1UE7IbzEi-7kp5jNebLM/edit?usp=sharing).

/label merge-method-squash

### CODE REVIEW

**Comment by sftim** [comment]
Relevant to #18512

**Comment by sftim** [comment]
Happy to get some early feedback on this draft PR

**Comment by zacharysarah** [comment]
I tested the diagram on both pages by zooming in, zooming out, scrolling and swiping on desktop and mobile. It behaves like one would expect an SVG image to behave!

Approving, leaving LGTM for another reviewer.

/approve

**Comment by jimangel** [comment]
/lgtm

thanks!

**Pull request merged**
