### PR TITLE
Fix broken link -- downward-api

### PR DESCRIPTION
**Pull request by hs0210**
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>

Fix: #35814

### CODE REVIEW

**Review by vaibhav2107 — COMMENTED** [review]
Looks fine, Thanks @hs0210

**Comment by vaibhav2107** [comment]
cc @sftim

**Comment by tengqm** [comment]
btw, this was caused by a previous change 7f3604a949c1d85b2074cea3e3068e1b522850d8 which is incomplete.

**Pull request merged**
