### PR TITLE
[docs/tutorials]: update kube-state-metrics install details

### PR DESCRIPTION
**Pull request by tariq1890**
Kube-state-metrics installation steps have been updated since this tutorial was published.

### CODE REVIEW

**Comment by pigletfly** [comment]
thanks for your updating @tariq1890

**Comment by seokho-son** [comment]
Contents in Ko are translation of original docs(En).
So, the Ko contents can be changed along with En docs.
Since this PR got lgtm from En reviewer, as a Ko contents reviewer, I'd like to give lgtm. @tariq1890  Thank you for the contribution!!
/lgtm

**Comment by nikhita** [comment]
@seokho-son can you approve again? Prow doesn't pick up edited comments for approval :grimacing:

**Comment by seokho-son** [comment]
@nikhita Sure ! Thank you :)
/approve

**Comment by tariq1890** [comment]
Thanks all for helping to get this PR in :).

**Pull request merged**
