### PR TITLE
Add ReadOnlyAPIDataVolumes in removed feature gates list

### LINKED ISSUE #34026: ReadOnlyAPIDataVolumes feature gate missing
**This is a Bug Report**

**Problem:**
It seems that Kubernetes previously had a feature gate named `ReadOnlyAPIDataVolumes`; however, [Feature Gates (removed)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/) does not mention that feature gate.

**Proposed Solution:**
Update [Feature Gates (removed)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/)  to mention `ReadOnlyAPIDataVolumes`.

**Page to Update:**
~https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/~
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

### PR DESCRIPTION
**Pull request by tamilselvan1102**
Fixes #34026

### CODE REVIEW

**Comment by tamilselvan1102** [comment]
@sftim 
Please review this PR
Thank you

**Comment by sftim** [comment]
I'm happy for anyone to review this PR.
/unassign

**Review by Princesso — COMMENTED** [review]
Thanks for fixing this. It /lgtm however, I'll transfer it to the appropriate SIG. 
/assign @kubernetes/sig-network-misc 
cc: @reylejano

**Pull request merged**
