### PR TITLE
Replace $ symbol in all english docs files

### PR DESCRIPTION
**Pull request by DanyC97**
Tidy up and align all the docs to same guideline

### CODE REVIEW

**Comment by DanyC97** [comment]
/assign @zparnold 

can you please help review it ?

**Comment by DanyC97** [comment]
@neolit123 thank you for being so quick in reviewing it

**Comment by jimangel** [comment]
@DanyC97 @neolit123 any background on this change? I have no problem with it, but have always assumed that the "$ " or ">" indicated an actual command vs the command's output.

**Comment by neolit123** [comment]
@jimangel i haven't requested this change, but there are notes about usage of `$` in the k/website guide: https://kubernetes.io/docs/contribute/style/style-guide/#code-snippet-formatting

**Comment by DanyC97** [comment]
@jimangel the reason for this PR is because i'm trying to get consistency around the docs by following the guidelines.

Today there is a mix around some pages using `$` or `>` or nothing and while is not a major UX benefit it still add values (in my opinion) to feel like the docs were wrote by _same_ team/ people

you agree?

**Comment by DanyC97** [comment]
closing in favor of https://github.com/kubernetes/website/pull/12779

**Pull request closed without merging**
