### PR TITLE
[id] update curl command

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/39643/files
/assign @ariscahyadi

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Link change in sync with English PR
/lgtm

**Comment by Arhell** [comment]
@habibrosyad

**Comment by Arhell** [comment]
@habibrosyad

**Review by Arhell — COMMENTED** [review]
/assign @habibrosyad

**Review by habibrosyad — APPROVED** [review]
Thanks

/lgtm

**Review by habibrosyad — APPROVED** [review]
Thanks

/lgtm

**Pull request merged**
