### PR TITLE
Clean up style user joutneys css file

### PR DESCRIPTION
**Pull request by ZhiFeng1993**
Fixes issue #22096

@celestehorgan
Am I supposed to clean up several references of this file too? Like: 
```
website/deprecated/content/en/docs/user-journeys/users/application-developer/advanced.md:
    3  - chenopis
    4  layout: docsportal
    5: css: /css/style_user_journeys.css
    6  js: https://use.fontawesome.com/4bcc658a89.js, https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js
    7  title: Advanced Topics
```

### CODE REVIEW

**Comment by Arhell** [comment]
/cancel
Hello look please
still need to remove the fonts for this css `/static/fonts/`

**Comment by celestehorgan** [comment]
@ZhiFeng1993 

>Am I supposed to clean up several references of this file too?  

The reference you mentioned is in `website/deprecated/`. This content is deprecated (we're just saving it as a just-in-case) so you don't need to clean these up. Thanks for asking!

**Comment by celestehorgan** [comment]
/lgtm

@Arhell – removing the fonts is a separate issue under the Umbrella: https://github.com/kubernetes/website/issues/22024. Personally I would prefer to only remove the fonts once any stylesheets that call them are removed.

I checked this by:

- Looking at individual content pages in Docs, Community, Case Studies and the Blog
- Checked the Netlify deploy log for this build to ensure that there were no errors
- Did a full-text search for `style_user_journeys.css`. 

That said: the `/no` translation still calls this file. Presumably they'll catch this in their next update.

**Comment by Arhell** [comment]
Got it, but I don’t see the point in saving fonts if the styles that cause them are deleted
possible next PR

**Comment by ZhiFeng1993** [comment]
thanks @celestehorgan . PR description updated.

**Pull request merged**
