### PR TITLE
Reorder docs home page tiles (fix alignment)

### LINKED ISSUE #43147: Poor alignment for tiles on home page for docs
**This is a Feature Request**

**What would you like to be added/enhanced?**
As it can be clearly seen at [/docs/home/ page](https://kubernetes.io/docs/home/) that the layout of this page is looking somewhat inconsistent due to this visible big-small difference in 'Cards' at 2nd and 3rd row.

Screenshot (773)
Screenshot (774)
 
**Solution:**
I think this issue can be easily resolved by replacing the 'Card' of (3rd Column, 2nd Row) with (1st Row, 3rd Column) like this:-

Screenshot (771)

Screenshot (772)

As 'Cards' of 2nd row are all vertically tall and 'Cards' of 3rd row are all vertically small. So, replacing these 2nd 'Cards' with each other will possibly solve the problem.

By Card, i mean that whole thing inside yellow line (Heading, description, hyperlinks and button)

### PR DESCRIPTION
**Pull request by satyampsoni**
fixes #43147

### CODE REVIEW

**Review by aj11anuj — COMMENTED** [review]
Can you share a deploy preview?

**Comment by satyampsoni** [comment]
You mean screenshot of the preview?
image

**Review by aj11anuj — APPROVED** [review]
I mean when you deploy it to view, then a link opens up in browser (deploy preview link). But that screenshot have already fulfilled the purpose. 

This PR have fulfilled the intent of that issue and its now resolved. LGTM 👍
For adding some finishing touch, buttons can be aligned at horizontally same line, but that's out of scope of that issue and this PR, for doing that a separate discussion may be required as it will need discussion on which description to add to make that card a little lengthy, or to short it, or which hyperlinks to add on short cards, and which one to remove on long cards etc.

**Comment by satyampsoni** [comment]
We can raise a separate issue for that

**Comment by aj11anuj** [comment]
Pinging for confirmation @reylejano @sftim 
Should a new issue be raised? or all the discussions and changes should be done in this PR?

**Comment by sftim** [comment]
/retitle Fixes alignment for tiles and buttons on home page for docs

I can't see why we would need a new issue.

**Comment by sftim** [comment]
As it stands, this PR does not appear to fix the misalignment.

Example.

It might still be useful but it's not really a **fix** for https://github.com/kubernetes/website/issues/43147

**Comment by sftim** [comment]
/retitle Fix alignment for tiles and buttons on home page for docs

**Comment by satyampsoni** [comment]
@sftim 
The issue mentioned to changes the places of the columns with one another I did the same. Can you pls highlight on what changes do you want here?

**Comment by sftim** [comment]
Ah OK, let me edit the issue and PR title to match the proposed solution.

**Comment by sftim** [comment]
/retitle Reorder docs home page tiles (fix alignment)

**Pull request merged**
