### PR TITLE
fix --event-qps and --event-burst

### PR DESCRIPTION
**Pull request by liuxu623**
`--event-qps` 0 is not unlimited, it will use DefaultQPS: 5.
https://github.com/kubernetes/client-go/blob/v0.20.2/rest/config.go#L116

### CODE REVIEW

**Comment by tengqm** [comment]
The content of the file is from `kubelet --help`. If there are errors in the output, we should fix it in the upstream code first.

**Comment by liuxu623** [comment]
> The content of the file is from `kubelet --help`. If there are errors in the output, we should fix it in the upstream code first.
@tengqm I have create a pr https://github.com/kubernetes/kubernetes/pull/98869.

**Comment by tengqm** [comment]
@liuxu623 Thanks for proposing a fix to upstream. Please hold this PR until your fix is merged. When the upstream fix is in, the updated message will be in at least 1.21, not 1.20. So your PR here at website should target `dev-1.21` branch rather than `master`.

**Comment by sftim** [comment]
/hold
per https://github.com/kubernetes/website/pull/26423#issuecomment-775120797

**Pull request closed without merging**
