### PR TITLE
Complete unfinished conflict resolution

### PR DESCRIPTION
**Pull request by gochist**
It corrects incomplete conflict resolution mistakes.

@pjhwa Please refer to it when working on issue #23818 .

### CODE REVIEW

**Comment by pjhwa** [comment]
@gochist 
Yes, I've done this problem with #23827

**Comment by gochist** [comment]
@pjhwa Thank you! I've updated by replacing it with the same file as #23827 to avoid conflicts on merging the team milestone branch into master.

**Pull request merged**
