### PR TITLE
Fix banner image scaling on Case Studies pages

### LINKED ISSUE #43019: Text-image overlapping issue at App Direct Case-Study page for small screens
**This is a Bug Report**

**Problem:**
Look at this below page (This is how pages of Case-Studies of other Companies/Organisation look)
Screenshot_2023-09-12-21-10-07-517_org mozilla firefox

Now look at App Direct Case Study page
Screenshot_2023-09-12-21-11-42-732_org mozilla firefox
Screenshot_2023-09-12-21-11-28-584_org mozilla firefox
Screenshot_2023-09-12-21-11-20-362_org mozilla firefox

That background image and text overlapping issue is problem at this page, that i wanted to point out with this issue.

### PR DESCRIPTION
**Pull request by alok0277**
**Description:**

In page case study some images were not covering whole section of the body:

Screenshot from 2023-09-15 11-56-10

**What this PR do ?**
fixes #43019

Fixed the issue 

Screenshot from 2023-09-15 10-04-35
Screenshot from 2023-09-15 10-05-56

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
/retitle Fix banner image scaling on Case Studies pages

**Comment by Gauravpadam** [comment]
Hey @alok0277, Thanks for the PR! Considering this is your first PR in Kubernetes, We can ignore the fact that I've created the PR for the same issue #43039. I'll close my PR on one condition, Limit the changes you've made to a single CSS file ;)
Also, It's polite to check if someone's already working on an issue, But not mandatory

**Review by Gauravpadam — CHANGES_REQUESTED** [review]
Can we limit these changes to a single CSS file?

**Comment by alok0277** [comment]
Ok. Thank you for your suggestions, I will make changes to the code in the same file and apologize for not seeing that anyone is resolving the issue. As a new in contributing I missed that but next time, I keep this in mind.

**Review by Gauravpadam — COMMENTED** [review]
Thanks, lgtm

**Pull request merged**
