### PR TITLE
update default margin of vendorStrip li on narrow-width browser

### PR DESCRIPTION
**Pull request by ydcool**
fix issue #18758

### CODE REVIEW

**Comment by sftim** [comment]
@ydcool does this change apply to narrow viewports only, or to all viewports?

**Comment by ydcool** [comment]
> @ydcool does this change apply to narrow viewports only, or to all viewports?

Yes this just applied to narrow viewports because it'll be override by the `_desktop.scss` on wide screen 
https://github.com/kubernetes/website/blob/11c462e6f166004328e5e7a8cf1a82928ee1351a/assets/sass/_desktop.sass#L299-L302

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-18782--kubernetes-io-master-staging.netlify.com/docs/concepts/

Snippet of narrow width browser:

image

**Comment by kbhawkey** [comment]
@ydcool . I see the difference in the desktop version (The vendor strip items or list of Kubernetes docs categories are shifted to the right). This has a minor effect on the distance between the last list item and the search bar as well as the distance between list items (as expected). 
The location of the left most list item (Home) is not changed.
When the screen is minimized or viewed on a mobile browser the list item's text does not overlap.
This change also slightly changes the `globalnav` unordered list (top most navigation) which you don't notice on mobile screens.

Would it be possible to change _only_ the inner distance between list items for mobile screens?

**Comment by ydcool** [comment]
sorry for the delay , that issue was fixed by #19716 so close this.

**Pull request closed without merging**
