### PR TITLE
Add a theme-color 

### PR DESCRIPTION
**Pull request by remyleone**
This add a theme color on-page. This is used in the evaluation by the chrome lighthouse tool.

https://web.dev/themed-omnibox/

### CODE REVIEW

**Comment by kbhawkey** [comment]
Hello @remyleone .
I see that the attribute is set in the generated HTML.
Is this attribute recognized by most browsers?
What is the advantage of setting this attribute?
The color set is `#326c35`?
Page preview:
https://deploy-preview-18976--kubernetes-io-master-staging.netlify.com/

**Comment by remyleone** [comment]
Indeed I think it is recognized by most mobile browsers.
It is recommended by the chrome audit tool and will give a distinct look to
tabs in the browser on mobile.
I've taken the blue from the Kubernetes logo.

Em seg, 10 de fev de 2020 16:31, Karen Bradshaw <notifications@github.com>
escreveu:

**Comment by remyleone** [comment]
`#326ce5`

**Comment by kbhawkey** [comment]
Thanks for the explanation @remyleone  and the color correction!
Do you have a snippet of what this change looks like?

**Comment by remyleone** [comment]
On my mobile, it looks like this image

**Comment by zacharysarah** [comment]
I don't see it on Safari mobile. That doesn't seem like a blocking concern.

**Comment by kbhawkey** [comment]
Right, my view is as you depicted @remyleone .
I have to explicitly open the browser on my phone to see the change.

**Comment by remyleone** [comment]
Tested using chrome on Android

**Comment by remyleone** [comment]
@zacharysarah Could it be merged?

**Pull request merged**
