### PR TITLE
WIP: [KEP-1748]: Add capacity planning documentation

### PR DESCRIPTION
**Pull request by dgrisonnet**
https://github.com/kubernetes/enhancements/issues/1748

### CODE REVIEW

**Comment by sftim** [comment]
/sig instrumentation

I wonder if we could use an observability overview within https://kubernetes.io/docs/concepts/cluster-administration/

**Comment by dgrisonnet** [comment]
That make total sense :+1: I'll split that up once this one is done.

**Comment by dgrisonnet** [comment]
I'll move that doc there as well since it is more appropriate I think

**Comment by dgrisonnet** [comment]
Closing, I'll reopen a new PR targeting the correct branch.

**Pull request closed without merging**
