### PR TITLE
Translate manage-resources/cpu-default-namespace.md into Korean

### LINKED ISSUE #21083: Translate manage-resources/cpu-default-namespace.md into Korean
**This is a Feature Request**

**What would you like to be added**

Translate tasks/administer-cluster/manage-resources/cpu-default-namespace.md into Korean.

**Why is this needed**

There is no document of tasks/administer-cluster/manage-resources/cpu-default-namespace.md which translated into Korean.

**Comments**

Page to translate: https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/

/language ko

### PR DESCRIPTION
**Pull request by pjhwa**
Closes #21083

This PR contains the following files which translated into Korean.

- content/ko/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md
- content/ko/examples/admin/resource/cpu-defaults.yaml
- content/ko/examples/admin/resource/cpu-defaults-pod.yaml
- content/ko/examples/admin/resource/cpu-defaults-pod-2.yaml
- content/ko/examples/admin/resource/cpu-defaults-pod-3.yaml

This PR depends on #21047 , #21082 , #21084 , #21085 , #21086 for translated docs links.

### CODE REVIEW

**Comment by pjhwa** [comment]
Deploy preview: https://deploy-preview-21090--k8s-dev-ko.netlify.app/ko/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/

**Comment by ysyukr** [comment]
@seokho-son 님께서 리뷰가 어려우신듯하여 제가 대신하겠습니다.
/unassign @seokho-son
/assign @ysyukr

/lgtm

**Pull request merged**
