### PR TITLE
cluster-intro.html: Remove advice that lacks argumentation

### PR DESCRIPTION
**Pull request by hexagonrecursion**
IMHO in the current version of the article the statement "A Kubernetes cluster that handles production traffic should have a minimum of three nodes" is completely superfluous. Without sufficient argumentation it only serves to promote cargo cult.

In order for it to become useful technical advice at least the following questions would have to be answered:
* Why does the author recommend against using clusters of fewer than tree nodes to handle production workloads?
* Why does the author consider tree nodes to be enough for a minimum production workload?
* What kinds of production workloads does the author have in mind? Production is a very broad term.
* Does this advice apply across all possible ways to configure and deploy kubernetes? Does it apply on GCP manages kubernetes? What about AWS?
* Are there other knobs that one would need to tune to make the cluster production-worthy?

I propose to remove the above statement because I think that adding the necessary argumentation would make this introductory tutorial much longer and more complicated. I also currently do not know enough about kubernetes to answer any of the above questions.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@hexagonrecursion
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by hexagonrecursion** [comment]
> ****
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

I have signed the CLA yesterday but did not read the instructions closely enough to notice that I have to leave a comment to make the bot recheck the status.

**Comment by tengqm** [comment]
A better fix would be a short explanation e.g. to serve the quorum read of a HA etcd cluster.

**Comment by sftim** [comment]
I agree with @tengqm, but as we're talking about nodes let's not mention etcd as the sample workload (it could get confused with a self-hosted control plane, and that is a lot of detail to take in for a first tutorial).

**Review by sftim — CHANGES_REQUESTED** [review]
Let's explain why production clusters should have multiple nodes, rather than omit the advice.
_restating https://github.com/kubernetes/website/pull/25912#issuecomment-753709727_

**Comment by sftim** [comment]
It's OK to hyperlink to a document that explains how to run a production cluster. I didn't see this detail mentioned in https://kubernetes.io/docs/setup/production-environment/ so it might _also_ be worth tracking an issue to add it.

**Comment by hexagonrecursion** [comment]
> Let's explain why production clusters should have multiple nodes, rather than omit the advice.
> _restating [#25912 (comment)](https://github.com/kubernetes/website/pull/25912#issuecomment-753709727)_

As I already stated I do not know why

> A better fix would be a short explanation e.g. to serve the quorum read of a HA etcd cluster.

> I agree with @tengqm, but as we're talking about nodes let's not mention etcd as the sample workload (it could get confused with a self-hosted control plane, and that is a lot of detail to take in for a first tutorial).

This two comments make it sound like certain *specific* applications (eg etcd) may have an *application-specific* minimum recommended number of replicas running on different nodes (and therefore minimum number of nodes). Are there other reasons why a one node cluster would be bad?

**Comment by sftim** [comment]
A single node can fail, causing an application outage. With multiple nodes the cluster can run resilient copies of an application's Pods. Kubernetes Deployments can consist of more than one identical Pods; a Deployment (and its ReplicaSet) can't deliver the outcomes expected of it if there is only one node to place tasks onto.

**Comment by sftim** [comment]
@hexagonrecursion if you're not sure how to implement the alternative approach sketched in https://github.com/kubernetes/website/pull/25912#pullrequestreview-561384474, then it's OK to close this PR.

**Comment by hexagonrecursion** [comment]
I like the following quote from https://kubernetes.io/docs/concepts/overview/components/:

> In production environments, the control plane usually runs across multiple computers and a cluster usually runs multiple nodes, providing fault-tolerance and high availability

**Comment by sftim** [comment]
@hexagonrecursion what are your intentions to move this pull request forward?

**Pull request closed without merging**
