### PR TITLE
Adding details to use Resource bin packing using RequestedToCapacityR…

### PR DESCRIPTION
**Pull request by sudeshsh**

### CODE REVIEW

**Comment by makoscafee** [comment]
Hi, @sudeshsh Sorry, Since PR is targeting release 1.15 would you mind open it against branch `dev-1.15`?. Thanks

/milestone 1.15

**Comment by tengqm** [comment]
This should go dev-1.15.

**Comment by sudeshsh** [comment]
@tengqm @makoscafee  updated it

**Comment by tengqm** [comment]
@sudeshsh need some help for tech reviews now.

**Comment by sudeshsh** [comment]
@tengqm closing the PR as the fix did not make it to 1.15, will reopen when it gets merged

**Pull request closed without merging**
