### PR TITLE
First Korean l10n work for release-1.16

### PR DESCRIPTION
**Pull request by gochist**
First Korean l10n work for release-1.16

* Modify #16415, #16417 korean docs. (#16467)
* Modify #16364 and links in korean docs. (#16508)
* Translate concepts/workloads/controllers/statefulset.md in Korean (#16443)
* Update outdated content in dev-1.16-ko.1 (#16502)
* Translate concepts/workloads/controllers/daemonset.md in Korean (#16477)
* Translate concepts/services-networking/dns-pod-service in Korean (#16299)

Co-Authored-By: June Yi <june.yi@samsung.com>
Co-Authored-By: Yoon <learder@gmail.com>
Co-Authored-By: Seokho Son <shsongist@gmail.com>
Co-Authored-By: SoHye Choi <wergreat10@naver.com>
Co-Authored-By: Yuk, Yongsu <ysyukr@gmail.com>

### CODE REVIEW

**Comment by gochist** [comment]
Waiting for #16299

**Comment by seokho-son** [comment]
@gochist #16299 has been merged to dev-1.16-ko.1 ~ You can go ahead.

**Comment by seokho-son** [comment]
@gohist looks nice ! Thank you.
/lgtm

**Pull request merged**
