### PR TITLE
Fix mismatch in Labels and Selectors concept page

### PR DESCRIPTION
**Pull request by hmspisharody**
negative matching 'notin' to match the example

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Fix mismatch in Labels and Selectors concept page

**Comment by reylejano** [comment]
Preview of updated page:
https://deploy-preview-39205--kubernetes-io-main-staging.netlify.app/docs/concepts/overview/working-with-objects/labels/

Thank you for the fix
/approve

**Pull request merged**
