### PR TITLE
Update access-cluster.md

### PR DESCRIPTION
**Pull request by liuchong**
Delete space character when get TOKEN with `get/cut`

### CODE REVIEW

**Comment by zparnold** [comment]
@liuchong thanks for your contribution! 🎉 We really would love to have it, unfortunately to continue we need to have your (or your company's) signature on a CLA! For now I'm going to close this, but fret not! You can re-open whenever you have a chance. Thanks!

**Comment by liuchong** [comment]
CLA signature completed 👀

**Comment by tengqm** [comment]
need rebase to resolve netlify issue.

**Comment by liuchong** [comment]
branch is rebased

**Comment by tengqm** [comment]
reapproving
/lgtm
/approve

**Pull request merged**
