### PR TITLE
[zh] update [creating a sample user] link

### PR DESCRIPTION
**Pull request by niltor**
update  [creating a sample user]  link

### CODE REVIEW

**Comment by niltor** [comment]
Signed recheck.

**Comment by reylejano** [comment]
/retitle [zh] update [creating a sample user] link

**Comment by mengjiao-liu** [comment]
Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the guideline. To find out what are the upstream changes to be synced, do this on the main branch:
```
./scripts/lsync.sh content/zh/docs/tasks/access-application-cluster/web-ui-dashboard.md
```
/hold

**Comment by tengqm** [comment]
@nitor  Still interested in pushing this forward?

**Pull request closed without merging**
