### PR TITLE
Fix ambiguous translation in kubeadm.md

### PR DESCRIPTION
**Pull request by anxk**
Fix ambiguous translation in content/zh/docs/reference/setup-tools/kubeadm/kubeadm.md

### CODE REVIEW

**Comment by anxk** [comment]
Have signed CLA

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by xichengliudui** [comment]
@anxk

**Comment by xichengliudui** [comment]
@anxk thank you for your contribution.
/lgtm
/approve

**Pull request merged**
