### PR TITLE
Updating SIG Co-chair requirements

### PR DESCRIPTION
**Pull request by jimangel**
Removing archaic requirements for SIG Docs co-chairs. For the record, that I did not fully meet when becoming a co-chair a couple years ago. The current set of requirements hurt more than they help.

/cc @parispittman

### CODE REVIEW

**Comment by onlydole** [comment]
Thank you, @jimangel! 

/lgtm

**Comment by parispittman** [comment]
very supportive of this!
LGTM for sure - 100%

**Comment by reylejano** [comment]
Preview of updated page:
https://deploy-preview-30986--kubernetes-io-main-staging.netlify.app/docs/contribute/advanced/

I agree with the changes
/lgtm

**Comment by divya-mohan0209** [comment]
Thank you Jim! LGTM, 100% :)

**Comment by sftim** [comment]
We might want to list an expectation that a **tech lead** has already been an approver for _n_ months.
(I sense a good-first-issue or something near to it).

**Pull request merged**
