### PR TITLE
[zh]Sync content/zh/examples/policy/restricted-psp.yaml

### PR DESCRIPTION
**Pull request by kinzhi**

### CODE REVIEW

**Comment by howieyuen** [comment]
en version updated only 3 days ago. You may reference the original commit for tracing.
/approve

**Review by tanjunchen — COMMENTED** [review]
/lgtm

**Comment by tanjunchen** [comment]
@kinzhi   could you push this commit again? the robot seems bad.

**Comment by kinzhi** [comment]
> @kinzhi could you push this commit again? the robot seems bad.

Yes, I will commit again, please help to review @tanjunchen

**Comment by tengqm** [comment]
/lgtm
reapply

**Pull request merged**
