### PR TITLE
KEP-4153: Declarative Validation - Alpha Docs

### PR DESCRIPTION
**Pull request by alexzielenski**
Placeholder for https://github.com/kubernetes/enhancements/issues/4153

### CODE REVIEW

**Comment by katcosgrove** [comment]
Hi, @alexzielenski! Just dropping by to remind you that the deadline for docs PRs to be ready for review is tomorrow, November 14. Is there anything we can help you with to get this PR ready?

**Comment by alexzielenski** [comment]
Hi @katcosgrove for the first alpha of this enhancement we have no user facing changes (other than bugfixes which are already in release notes). I think it should be okay to close this?

**Comment by katcosgrove** [comment]
Hi @alexzielenski. It looks like your KEP defines two feature gates, and therefore is a user-visible feature that must be documented with when and why you may want to enable or disable them.

**Comment by alexzielenski** [comment]
The feature gates where not yet added to the release, so they are not user visible. The gates you mentioned in the KEP are for an additional alpha phase. I confirmed with @sreeram-venkitesh that it is OK for this KEP to not enable feature yet during this alpha

**Comment by katcosgrove** [comment]
Gotcha. Okay to close this PR then, see you next release!

**Pull request closed without merging**
