### PR TITLE
Use Kubernetes blue within logo (correct shade)

### PR DESCRIPTION
**Pull request by sftim**
Use the correct RGB value within the Kubernetes logo. See https://github.com/kubernetes/kubernetes/blob/master/logo/colors.md

/area web-development

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Looks good.

/lgtm
`/approve` _(Unofficially giving the nod of approval; official approval required from `sig-docs-website-owner`)_

**Comment by sftim** [comment]
If https://github.com/kubernetes/website/pull/48431 merges first, this may need rework.

**Comment by sftim** [comment]
All looks good

**Pull request merged**
