### PR TITLE
feat: graduate ScheduleDaemonSetPods to GA

### PR DESCRIPTION
**Pull request by draveness**
ref: https://github.com/kubernetes/enhancements/issues/548
/assign @k82cn
/cc @irvifa

### CODE REVIEW

**Comment by daminisatya** [comment]
@draveness Thank you for the update.

Do we need to update this file as well? - https://github.com/kubernetes/website/blob/master/content/en/docs/reference/command-line-tools-reference/feature-gates.md

It's a question Im not sure though. Let me know about it.

**Comment by draveness** [comment]
> @draveness Thank you for the update.
> 
> Do we need to update this file as well? - https://github.com/kubernetes/website/blob/master/content/en/docs/reference/command-line-tools-reference/feature-gates.md
> 
> It's a question Im not sure though. Let me know about it.

Thanks, I've updated the file.

**Comment by irvifa** [comment]
Thanks @draveness 
/lgtm

**Comment by draveness** [comment]
> Thanks @draveness
> /lgtm

Thanks for the lgtm, I just removed the section which has already been removed from the codebase in 1.17

**Pull request merged**
