### PR TITLE
Remove Weave Cloud

### LINKED ISSUE #37748: Broken link on Installing Addons page
**Problem:**
The text [**Weave Cloud account**](https://cloud.weave.works/) on [link](https://kubernetes.io/docs/concepts/cluster-administration/addons/#visualization-amp-control) is not working, on the official website of weave, it has mentioned that the service has ended so; I believe it should point to this https://www.weave.works/blog/weave-cloud-end-of-service
Check the page [Installing Addons
](https://kubernetes.io/docs/concepts/cluster-administration/addons/) for the problem.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/addons/

**Suggested Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the text **Weave Cloud account** link to https://www.weave.works/blog/weave-cloud-end-of-service and not to this [link](https://cloud.weave.works/).

/kind document
/assign
/language en

### PR DESCRIPTION
**Pull request by Affan-7**
This fixes #37748

Reference: https://www.weave.works/blog/weave-cloud-end-of-service

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
This proposed change looks good. Just noticed a suggestion in comment https://github.com/kubernetes/website/issues/37748#issuecomment-1305295833. Could we consider implementing those too? It would be nice to have them included.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge.

/lgtm

**Review by r0b2g1t — APPROVED** [review]

**Pull request merged**
