### PR TITLE
[kr] fix text

### PR DESCRIPTION
**Pull request by pasudo123**
노트 -> 노드

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @pasudo123,

Please sign the CLA agreement so that we can move on. 😊
https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/34732/#/?version=2

**Comment by pasudo123** [comment]
@Sea-n 
Signed the CLA Agreement. thank you

**Comment by seokho-son** [comment]
@pasudo123 
Thank you for the bug fix !! :) 

/lgtm

**Pull request merged**
