### PR TITLE
Fix broken link on Enforcing Pod Security Standards page

### LINKED ISSUE #36929: Broken link on Enforcing Pod Security Standards page
**Problem:**
The text [**example**](https://kubernetes.io/docs/concepts/security/pod-security-admission/#applying-to-all-namespaces) on [link](https://kubernetes.io/docs/setup/best-practices/enforcing-pod-security-standards/) should point to these https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/#applying-to-all-namespaces
Check the page [Enforcing Pod Security Standards](https://kubernetes.io/docs/setup/best-practices/enforcing-pod-security-standards/) for the problem.

Page to **Update:**
https://kubernetes.io/docs/setup/best-practices/enforcing-pod-security-standards/

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the link on the text **example** to https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/#applying-to-all-namespaces and not to this [link](https://kubernetes.io/docs/concepts/security/pod-security-admission/#applying-to-all-namespaces).

/kind document
/assign
/language en

### PR DESCRIPTION
**Pull request by kadtendulkar**
Fixes #36929 

Updated page [Enforcing Pod Security Standards](https://kubernetes.io/docs/setup/best-practices/enforcing-pod-security-standards/)

### CODE REVIEW

**Comment by mtardy** [comment]
Thanks for the fix!

/lgtm

**Comment by reylejano** [comment]
The page updated by this PR states Pod Security Admission has the Feature State for Pod Security Admission as beta as of 1.23. Can you also update the feature state to be `FEATURE STATE: Kubernetes v1.25 [stable]`

**Review by chrisnegus — COMMENTED** [review]
/lgtm

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-36930--kubernetes-io-main-staging.netlify.app/docs/setup/best-practices/enforcing-pod-security-standards/#configure-all-cluster-namespaces

/king cleanup

**Pull request merged**
