### PR TITLE
update commitee-steering alias following 2022 election

### PR DESCRIPTION
**Pull request by BenTheElder**
see: https://github.com/kubernetes/steering/issues/256

### CODE REVIEW

**Comment by BenTheElder** [comment]
typo-ing my own username is a new one 😂 
fixed

**Comment by sftim** [comment]
Steering committee folks: would you LGTM this?

**Review by mrbobbytables — COMMENTED** [review]
/approve

**Review by mrbobbytables — COMMENTED** [review]
/lgtm
if its needed in addition to approve

**Comment by sftim** [comment]
Ta
/approve

**Pull request merged**
