### PR TITLE
[hi] Add example yaml files for "Configuring Redis using a ConfigMap" tutorial

### PR DESCRIPTION
**Pull request by Aryan-Singla**
Add example yaml files for "Configuring Redis using a ConfigMap" tutorial
Regarding the issue #44794

### CODE REVIEW

**Comment by Aryan-Singla** [comment]
Hello @dipesh-rawat Please Check I have created the example-redis-config.yaml regarding the issue on #44794

**Review by dipesh-rawat — COMMENTED** [review]
Thanks for your contribution. There's an additional `redis-pod.yaml` [yaml file ](https://github.com/kubernetes/website/blob/main/content/en/examples/pods/config/redis-pod.yaml)required in this directory to help with the localization changes in [#44794](https://github.com/kubernetes/website/pull/44794/files)

As a suggestion, it would nice to consider making these changes _(i.e. adding of example files)_ in the previous PR [#44794](https://github.com/kubernetes/website/pull/44794/files) itself. It would streamline the review process and keep all the necessary localization changes together.

**Comment by dipesh-rawat** [comment]
/retitle [hi] Add example yaml files for "Configuring Redis using a ConfigMap" tutorial

**Comment by Aryan-Singla** [comment]
Hello @dipesh-rawat Please check I have added the redis-pods.yaml

**Pull request closed without merging**
