### PR TITLE
Adding msb.com to the list of online learning platforms

### PR DESCRIPTION
**Pull request by dmitriy-at-msb**

### CODE REVIEW

**Comment by dmitriy-at-msb** [comment]
I signed it

**Comment by kbhawkey** [comment]
Hello @dmitriy-at-msb . Thanks for this pull request.
There is active discussion about the policies of including third party content in the Kubernetes docs. For further information , see the kubernetes/enhancements#1327.
/hold

**Comment by mstipetic** [comment]
hey @kbhawkey are there any updates on this issue? I've had a look at the discussion you posted and I understand the concerns, but i don't think MSB is any different from any other links already posted there

**Comment by jimangel** [comment]
@dmitriy-at-msb @mstipetic Thanks for the PR. However, the KEP @kbhawkey linked (kubernetes/enhancements#1327) led to the removal of the online-training page which now redirects to: https://kubernetes.io/training/.

/close
/cc @zacharysarah @kbarnard10

**Pull request closed without merging**
