### PR TITLE
Synchronize zh to en: move admin

### PR DESCRIPTION
**Pull request by rainingmaster**
`authorization/_index.md` is moved to `content/zh/docs/reference/access-authn-authz/authorization.md` now.
`daemon.yaml`, `high-availability/_index.md` and `ovs-networking.md` are useless.

Other files are moved to a new location according to the `en` directory

### CODE REVIEW

**Comment by chenrui333** [comment]
Just curious, does this issue exist in release-1.14? If yes, we should sync there first? If no, I am fine with the change.

**Comment by rainingmaster** [comment]
@chenrui333 Thanks for review.
Some file has move to the new position, such as [abac.md](https://github.com/kubernetes/website/blob/master/content/en/docs/reference/access-authn-authz/abac.md), in the commit [1f557bde2ca62f22954a9ec3345094d07e5e0dda](https://github.com/kubernetes/website/commit/1f557bde2ca62f22954a9ec3345094d07e5e0dda).
And we will sync the file changes with the verison of en.

**Comment by rainingmaster** [comment]
@chenrui333 Another migration job is https://github.com/kubernetes/website/pull/14843. I think it is fine to all versions

**Comment by chenrui333** [comment]
cc @kubernetes/sig-docs-zh-reviews

**Comment by chenrui333** [comment]
@rainingmaster, ideally (for the next time), it would be good to submit an issue first and track down the work across different languages. :)

Nice job!

**Pull request merged**
