### PR TITLE
[ko] Update assign-pod-node.md

### PR DESCRIPTION
**Pull request by gamggi**
preferredDuringSchedulingIgnoredDuringExecution -> requiredDuringSchedulingIgnoredDuringExecution
requiredDuringSchedulingIgnoredDuringExecution -> requiredDuringSchedulingRequiredDuringExecution 으로 수정.

원문 
In the future we plan to offer requiredDuringSchedulingRequiredDuringExecution which will be identical to requiredDuringSchedulingIgnoredDuringExecution except that it will evict pods from nodes that cease to satisfy the pods' node affinity requirements.

### CODE REVIEW

**Comment by seokho-son** [comment]
@gamggi Thank you for the contribution !

Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
📝 Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

**Review by Arhell — COMMENTED** [review]
more info about CLA, check please
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jimangel** [comment]
Hey there! @gamggi, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by tengqm** [comment]
I'm closing this due to CLA issue open for too long. Please feel free to reopen when the agreement is signed.
/close

**Pull request closed without merging**
