### PR TITLE
Added new Cluster-Architecture.

### PR DESCRIPTION
**Pull request by devarsh10**
Added new Cluster Architecture. 
As in this(#[39389](https://github.com/kubernetes/website/pull/39389)) PR, the svg file is not appearing. So, maybe this PR solves it.

### CODE REVIEW

**Comment by tengqm** [comment]
Wait, why don't we resolve it in the same PR?

**Comment by devarsh10** [comment]
> 

Because, when I upload svg file from my pc it's showing some kind of rendering image error.
So, I commited this directly from [Flowchart & Diagram Maker](https://app.diagrams.net/), which is raising another PR.

Regards.

**Comment by tengqm** [comment]
I'd suggest we fix an issue in the same PR using a single commit, or else neither PR is self-contained.
/hold

**Comment by devarsh10** [comment]
Okay, let me try to solve this issue from that PR itself.

**Comment by devarsh10** [comment]
> I'd suggest we fix an issue in the same PR using a single commit, or else neither PR is self-contained. /hold

Hey @tengqm, I solved the issue within that PR only.
So, may I close this PR?

**Pull request closed without merging**
