### PR TITLE
table of solution in alphabetical order + more

### PR DESCRIPTION
**Pull request by karthequian**
Simplifies PR 13143 (https://github.com/kubernetes/website/pull/13143). PR fixes 3 things:
1) `Oracle Cloud Infrastructure Container Engine for Kubernetes (OKE)` was `IaaS Provider Oracle Cloud Infrastructure Container Engine for Kubernetes (OKE)`
2) capitalized all instances of GCE
3) Alphabetized list
4) Removes note section per @cody-clark

### CODE REVIEW

**Comment by karthequian** [comment]
@DanyC97 here's the new PR for the the alphabetical table.

**Comment by DanyC97** [comment]
@karthequian thank you for sending out the PR.

it looks good however i need more time to see what _more_  means - ie what has been added.
I like having everything ordered though.

If you have already a list of the _new_ stuff you added would help speeding up the review process

**Comment by karthequian** [comment]
@DanyC97 the `more` part is in the description section in the PR. Here's the gist again:

> * `Oracle Cloud Infrastructure Container Engine for Kubernetes (OKE)` was `IaaS Provider Oracle Cloud Infrastructure Container Engine for Kubernetes (OKE)`
> * capitalized all instances of GCE
> * Alphabetized list
> * Removes note section per @cody-clark

Let me know if it's too complicated, and I can break it up into smaller chunks too.

**Comment by karthequian** [comment]
Thanks @cody-clark! FWIW, #13177 looks like it's still good as well.

**Pull request merged**
