### PR TITLE
failed in aws redhat, need delete the exclude

### PR DESCRIPTION
**Pull request by ShaneKing**
failed in aws redhat, need delete the exclude

### CODE REVIEW

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by neolit123** [comment]
@ShaneKing hi, please sign the CLA.
see more information in the second comment.

**Comment by ShaneKing** [comment]
@neolit123 signed

**Comment by neolit123** [comment]
@ShaneKing 
the bot is not accepting your CLA, did your sign it?
for any troubles with that please email info@cncf.io

**Comment by neolit123** [comment]
/close

going with this fix instead:
https://github.com/kubernetes/website/pull/9670

**Pull request closed without merging**
