### PR TITLE
[uk] Remove some vertical space between lines of text

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/43234/files

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Proposed change looks in sync with 'en' PR https://github.com/kubernetes/website/pull/43234/files

LGTM

[Preview Page](https://deploy-preview-44012--kubernetes-io-main-staging.netlify.app/uk/docs/tutorials/) | [Original Page](https://kubernetes.io/uk/docs/tutorials/)

**Comment by MaxymVlasov** [comment]
Lol, looks like someone apply markdownlint 

/lgtm
/approve

**Pull request merged**
