### PR TITLE
Change Go Doc URL to pkg.go.dev

### PR DESCRIPTION
**Pull request by inductor**
Fixes https://github.com/kubernetes/website/issues/31318

### CODE REVIEW

**Comment by tengqm** [comment]
Please don't change the config-api references which are generated from upstream source code.
If you want to fix them, you will need to propose to the upstream source code instead.

**Comment by divya-mohan0209** [comment]
@inductor : Thank you for the documentation. However, since the reference documentation is generated from upstream code, it would not make sense to modify this in all these files. Please could you open a new PR to work with the upstream code and modify the content there instead of modifying the reference documentation directly?
Closing this PR since we cannot accept these changes.
/close

**Comment by tengqm** [comment]
We can merge this if the commit only contains the last three files.
As for the configuration APIs, I'm working on fixing the generator (kubernetes-sigs/reference-docs#269).

**Pull request closed without merging**
