### PR TITLE
Issue with k8s.io/zh/docs/tutorials/kubernetes-basics/scale/scale-intro/

### LINKED ISSUE #15147: Issue with k8s.io/zh/docs/tutorials/kubernetes-basics/scale/scale-intro/
**This is a Bug Report**

/language zh
/good-first-issue

**Problem:**

carousel not working  

**Proposed Solution:**

add carousel item class as bootstrap 4

**Page to Update:**
https://kubernetes.io/zh/docs/tutorials/kubernetes-basics/scale/scale-intro/

Related PR:
 #15129

### PR DESCRIPTION
**Pull request by Koderok**
Carousel scrolling not working on https://kubernetes.io/zh/docs/tutorials/kubernetes-basics/scale/scale-intro/.

Fixes #15147

### CODE REVIEW

**Comment by Koderok** [comment]
language zh

**Comment by Koderok** [comment]
Netlify page with working carousel - https://deploy-preview-15515--kubernetes-io-master-staging.netlify.com/zh/docs/tutorials/kubernetes-basics/scale/scale-intro/.

**Comment by idealhack** [comment]
Hi @Koderok, thanks for the fix!

I actually prefer to merge the first PR https://github.com/kubernetes/website/pull/15179 since we just need an approver there, I hope you may find another issue to work on, feel free to `/cc` me on your future PRs!

**Comment by xiangpengzhao** [comment]
Agree with @idealhack . Thanks for your contribution @Koderok and we welcome you to contribute to docs by fixing other issues in the future!

**Comment by tengqm** [comment]
Closing as a dup. Thanks for the help anyway.

**Comment by Koderok** [comment]
Thanks @idealhack and @xiangpengzhao for taking a look! I'll find other issues to work on.

**Pull request closed without merging**
