### PR TITLE
Remove slack web hook integration script

### LINKED ISSUE #22060: Investigate removing /functions-src/deploy-succeded.js
Umbrella issue: https://github.com/kubernetes/website/issues/22024

Investigate removing `/functions-src/deploy-succeded.js` and its containing folder.

This appears to be a script for a slack bot. To my knowledge, we don't use any slack bots. I think it's safe to remove this.

### PR DESCRIPTION
**Pull request by luckyvs1**
- Fixes #22060 
- Removed slack web hook integration script as it isn't used 
- Tested by looking for the functions in repository and wasn't used elsewhere and also checked the website was built successfully locally and checked a couple pages

### CODE REVIEW

**Comment by luckyvs1** [comment]
I signed it

**Comment by kbhawkey** [comment]
Related to #22306.

**Comment by celestehorgan** [comment]
Asked around on slack; consensus is that this is probably safe to remove (thanks @mrbobbytables!) Approving but definitely going to watch to make sure nothing goes arwy post-merge.

/approve

**Pull request merged**
