### PR TITLE
URL to version 1.10 should have a dot instead of a slash

### PR DESCRIPTION
**Pull request by brianmacdonald**
`https://v1-10.docs/kubernetes.io/docs/reference/` is an invalid URL and does not resolve. Changing to `https://v1-10.docs.kubernetes.io/docs/reference/` links to the correct site.

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
@brianmacdonald Thanks for fixing this!!!!
/lgtm

**Comment by Rajakavitha1** [comment]
@brianmacdonald could you please resolve the conflicts.

**Comment by chenopis** [comment]
Looks like this was already fixed in PR https://github.com/kubernetes/website/pull/9310.

**Pull request closed without merging**
