### PR TITLE
[ja] Update links in ja/docs/concepts/storage/persistent-volumes.md

### PR DESCRIPTION
**Pull request by s-kawamura-w664**
This PR fixes some links error in ja/docs/concepts/storage/persistent-volumes.md.

### CODE REVIEW

**Comment by irvifa** [comment]
/retitle [ja] Update links in ja/docs/concepts/storage/persistent-volumes.md

**Comment by atoato88** [comment]
This PR doesn't change since getting LGTM.
Is it OK to add assingnment?
/assing @inductor

**Comment by atoato88** [comment]
This PR doesn't change since getting LGTM.
Is it OK to add assingnment?
/assign @inductor

**Pull request merged**
