### PR TITLE
[zh] fix:Reference of Blog in Nodes

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/42901/files

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Looking at the [deploy preview](https://deploy-preview-43024--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/nodes/), I see that the link is directing to a 404 error. This could be because the linked blog content hasn't been localized into Chinese yet. I'll leave it up to the Chinese localization maintainers to decide how to proceed with this.

Deploy Preview: [deploy-preview-43024-architecture/nodes/](https://deploy-preview-43024--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/nodes/)

_Blog Link: [deploy-preview-43024-2023/08/24/swap-linux-beta/](https://deploy-preview-43024--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2023/08/24/swap-linux-beta/)_

**Comment by windsonsea** [comment]
We can open an issue to localize that blog into zh-cn, and find some contributors to assign that job.

That process is not very long, so this `zh-cn` url is acceptable.

**Review by ydFu — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
