### PR TITLE
chore(kubectl-cmds): add redirect to skip reundant page

### LINKED ISSUE #24133: No page content for https://k8s.io/docs/reference/kubectl/kubectl-cmds/
A page just to provide a link another page? 
My be you are planning more links on this page. 
If not this page it self can point to target page.

### PR DESCRIPTION
**Pull request by jai**
Fixes #24133 

Signed-off-by: Jai Govindani <jai@honestbank.com>

### CODE REVIEW

**Comment by jai** [comment]
Are the redirect rules supposed to work locally? I can't seem to get it working, will wait for the deploy preview.

If anyone sees anything wrong with my syntax, would be appreciated 🙏🏽

**Comment by sftim** [comment]
> Are the redirect rules supposed to work locally? I can't seem to get it working, will wait for the deploy preview.

Redirect rules only work when previewed / published via Netlify; these are a Netlify mechanism (I'm not sure how well we document that).

**Review by cleverndbest — COMMENTED** [review]
939f0881abbf33cebdf8e51838fce9c0529781ce

**Comment by jai** [comment]
@cleverndbest not sure what the comment means? If anything jumps out at you as incorrect would appreciate if you could let me know 🙏🏽

My understanding is that:
https://deploy-preview-27904--kubernetes-io-master-staging.netlify.app/docs/reference/kubectl/kubectl-cmds/

should redirect to:
https://deploy-preview-27904--kubernetes-io-master-staging.netlify.app/docs/reference/generated/kubectl/kubectl-commands/

but for some reason I'm not getting a 301 from the first URL - just a 200:
```shell
(⎈ |test-api:default)❯ curl -v https://deploy-preview-27904--kubernetes-io-master-staging.netlify.app/docs/reference/kubectl/kubectl-cmds/ | more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 206.189.46.168...
* TCP_NODELAY set
* Connected to deploy-preview-27904--kubernetes-io-master-staging.netlify.app (206.189.46.168) port 443 (#0)
...
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Netlify, Inc; CN=*.netlify.app
*  start date: Mar  9 00:00:00 2021 GMT
*  expire date: Mar  1 23:59:59 2022 GMT
*  subjectAltName: host "deploy-preview-27904--kubernetes-io-master-staging.netlify.app" matched cert's "*.netlify.app"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8a89010a00)
> GET /docs/reference/kubectl/kubectl-cmds/ HTTP/2
> Host: deploy-preview-27904--kubernetes-io-master-staging.netlify.app
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 200
```

**Comment by shannonxtreme** [comment]
Try adding an exclamation point after the 301? So `301!` and see if that helps?

**Comment by jai** [comment]
@shannonxtreme it works! Thanks for the tip!

**Comment by jai** [comment]
Confirmed that

https://deploy-preview-27904--kubernetes-io-master-staging.netlify.app/docs/reference/kubectl/kubectl-cmds/

now redirects to:

https://deploy-preview-27904--kubernetes-io-master-staging.netlify.app/docs/reference/generated/kubectl/kubectl-commands/

**Review by sftim — COMMENTED** [review]
Seems reasonable
/lgtm
/approve

**Pull request merged**
