### PR TITLE
Merged master into dev 1.21 - 2/12/21

### PR DESCRIPTION
**Pull request by ChandaniM123**
Merge master into dev-1.21 to keep in sync - SIG-Release 1.21 Docs team 1/19/21
/cc @reylejano @mvortizr @tengqm @PI-Victor

### CODE REVIEW

**Comment by ChandaniM123** [comment]
Looks like [d38c741 ](https://github.com/kubernetes/website/pull/26488/commits/d38c74124a89f1978e5d5f74989f439ca0cc8196) was resolved by commit [18b8846 ](https://github.com/kubernetes/website/pull/26488/commits/18b8846b9be9a1f78f432b1867ddf4792143ce44) in the same PR #26488

**Comment by reylejano** [comment]
Commit d38c741 with a build error, looks fixed in commit 18b8846 in same PR, [k/website PR 25425](https://github.com/kubernetes/website/pull/25425)

**Review by irvifa — COMMENTED** [review]
/approve

**Pull request merged**
