### PR TITLE
[ko] Fix wrong custom heading ID

### LINKED ISSUE #27858: [ko] Wrong custom heading ID
**This is a Bug Report** from [this review comment](https://github.com/kubernetes/website/pull/27728#discussion_r624591737).

**Problem:**
Wrong custom heading ID in https://kubernetes.io/ko/docs/concepts/services-networking/dns-pod-service/
image

**Proposed Solution:**
```diff
-### 파드의 setHostnameAsFQDN 필드 {# pod-sethostnameasfqdn-field}
+### 파드의 setHostnameAsFQDN 필드 {#pod-sethostnameasfqdn-field}
```

**Page to Update:**
- https://kubernetes.io/ko/docs/concepts/services-networking/dns-pod-service/#%ED%8C%8C%EB%93%9C%EC%9D%98-sethostnameasfqdn-%ED%95%84%EB%93%9C-pod-sethostnameasfqdn-field
- https://kubernetes.io/ko/docs/reference/command-line-tools-reference/feature-gates/#feature-gates

/language ko

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Resolves #27858
- Related review comment: https://github.com/kubernetes/website/pull/27728#discussion_r624591737

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Direct links to the preview:
- https://deploy-preview-27859--k8s-dev-ko.netlify.app/ko/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field
- https://deploy-preview-27859--k8s-dev-ko.netlify.app/ko/docs/reference/command-line-tools-reference/feature-gates/#feature-gates

**Comment by pjhwa** [comment]
감사합니다!!!

/lgtm

**Comment by seokho-son** [comment]
@gochist 님~ 확인 및 승인 부탁드립니다~!

**Comment by seokho-son** [comment]
Thank you !
/approve

**Pull request merged**
