### PR TITLE
[ru] Typo fix: "превышет" -> "превышает"

### PR DESCRIPTION
**Pull request by aermolaev**

### CODE REVIEW

**Comment by reylejano** [comment]
/retitle [ru] Typo fix: "превышет" -> "превышает"

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by Sea-n** [comment]
The Netlify build is stuck for 105 days.
/close
/reopen

**Comment by Sea-n** [comment]
Hum.. The bot doesn't work like what I think. 😅

/reopen
/remove-lifecycle stale

**Comment by Sea-n** [comment]
Hi @aermolaev,

It seems a little glitch happened on our side. Are you still interested in contributing Kubernetes website? Please do a force-push to trigger CI/CD rerun so that we can move forward.

**Pull request merged**
