### PR TITLE
remove feature gate SupportIPVSProxyMode.

### PR DESCRIPTION
**Pull request by tangwz**
Feature gate SupportIPVSProxyMode is GA.Any reference to this Feature Gate needs to be removed from the docs.

Issue: https://github.com/kubernetes/kubernetes/issues/94497

### CODE REVIEW

**Comment by tangwz** [comment]
PTAL @rikatz

**Review by sftim — CHANGES_REQUESTED** [review]
@tangwz we don't remove GA feature gates; we move them to https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features

/hold until that's addressed

**Comment by tangwz** [comment]
> @tangwz we don't remove GA feature gates; we move them to https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features
> 
> /hold until that's addressed

I think `SupportIPVSProxyMode` already in the https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features.
So we no need to change anything in the docs?

**Comment by sftim** [comment]
It looks as if no change is required.

**Comment by rikatz** [comment]
Let's move forward then with the code cleanup @tangwz 

@sftim thanks for the review. For now, I think this can be closed :)

/close

**Pull request closed without merging**
