### PR TITLE
Replace incorrect `granular` by `set/map`

### LINKED ISSUE #25153: Server-Side Apply listType documentation is inconsistent
In the [Merge Strategy](https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy) section, the `//+listType` annotation documentation gives possible values of `atomic`/`set`/`map`, but the description describes `atomic` and `granular`.

There's a more-detailed behaviour description in #16725 which might be useful to draw from.

### PR DESCRIPTION
**Pull request by apelisse**
Fixes #25153

/cc @TBBle

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
I'm sure this is right; however
@kubernetes/sig-api-machinery-pr-reviews, please add LGTM for tech review.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-25155--kubernetes-io-master-staging.netlify.app/docs/reference/using-api/server-side-apply/#merge-strategy

**Pull request merged**
