### PR TITLE
Translate tasks doc podpreset into Chinese

### PR DESCRIPTION
**Pull request by lichuqiang**
CN doc translation

/cc @tengqm @zhangxiaoyu-zidif

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6145)

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
Hi @tengqm 
keeping those yamls is OK.  If there are no yamls in current dir， the CI would collapse

**Comment by zhangxiaoyu-zidif** [comment]
Except that, would you approve it? @tengqm

**Comment by tengqm** [comment]
@zhangxiaoyu-zidif  Yes. The translation itself looks good. I'd approve that.
I'm not aware of the CI limitation that is forcing us to replicate each and every yaml.

**Comment by zhangxiaoyu-zidif** [comment]
@tengqm 
yes, I remember this PR[https://github.com/kubernetes/website/pull/5381] made the repo's CI collaspe for a while...

**Comment by zjj2wry** [comment]
https://github.com/kubernetes/website/issues/6055

**Comment by tengqm** [comment]
@lichuqiang can you please try pointing to the original manifests and see if the gate is happy with that?

**Comment by lichuqiang** [comment]
I thought the docs in path "/cn" should be a Chinese copy of original docs, and should not rely on that in other paths. But would like to remove the reference since it might cause other problems

**Comment by lichuqiang** [comment]
@tengqm @zhangxiaoyu-zidif @zjj2wry The CI seems went wrong without the reference
```
 Liquid Exception: Could not locate the included file 'podpreset-pod.yaml' in any of ["/opt/build/repo/cn/docs/tasks/inject-data-application"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in cn/docs/tasks/inject-data-application/podpreset.md
5:12:12 PM: jekyll 3.3.1 | Error:  Could not locate the included file 'podpreset-pod.yaml' in any of ["/opt/build/repo/cn/docs/tasks/inject-data-application"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
5:12:12 PM: make: *** [build-preview] Error 1
```

**Comment by zhangxiaoyu-zidif** [comment]
seems that i am right...

**Comment by tengqm** [comment]
em, that is sad news.
/cc @steveperry-53 @chenopis @zacharysarah Please advise if there is a solution to avoid duplicating the manifests for Chinese translation?

**Comment by lichuqiang** [comment]
Any suggestions for the manifests reference issue? My another ongoing translation is facing the same situation。

**Comment by zhangxiaoyu-zidif** [comment]
take those manifest files back. and wait for other maintainers' good idea to solve duplication problem.

**Comment by lichuqiang** [comment]
@zhangxiaoyu-zidif done :)

**Comment by zhangxiaoyu-zidif** [comment]
@tengqm 
how about this PR now. Let‘s solve duplication problem later...
Is that available？’

**Comment by tengqm** [comment]
agreed. The manifest duplication problem can be solved later.

**Pull request merged**
