### PR TITLE
Update apt keyring installation

### PR DESCRIPTION
**Pull request by MattTheCuber**
See https://github.com/kubernetes/website/pull/41307
> The plain google signing key for apt does not work anymore. It needs to be "deamord" using gpg.

### CODE REVIEW

**Comment by MattTheCuber** [comment]
Dahh, stupid code editor tried to format the pages

**Comment by MattTheCuber** [comment]
Fixed, sorry about that XD

**Review by dipesh-rawat — COMMENTED** [review]
Hi @MattTheCuber Thank you for your contribution!
We have different processes followed within different localisations of the project. Therefore, I'd request you to make changes to ONLY the main website i.e. the English language with this PR and then raise a separate PR for other languages.

Also, there have been PR(s) already raised (waiting to be reviewed/merged) by other contributors to address this same issue.

**Comment by MattTheCuber** [comment]
@dipesh-rawat I see, I will check the other PRs, and split, update, or close this one as needed.

**Comment by MattTheCuber** [comment]
@dipesh-rawat After reviewing related PRs, it looks like they are also updating the writing to point out this error. Maybe I should just close this PR as I could only update the description of the English version whish is already done?

**Comment by sftim** [comment]
/hold

One PR per language, please. We'd be happy to have those individual PRs, but not all in one change.

**Comment by MattTheCuber** [comment]
Moved to PRs listed above

**Pull request closed without merging**
