### PR TITLE
Second Japanese l10n work for release-1.18

### PR DESCRIPTION
**Pull request by inductor**
Second Japanese l10n work for release-1.18.

<details>
    <summary><b>Change List</b></summary>
    <ul>
    <li>Update ingress-controllers.md (<a href="https://github.com/kubernetes/website/pull/25002" target="_blank">#25002</a>)</li>
    <li>delete conflict message (<a href="https://github.com/kubernetes/website/pull/25023" target="_blank">#25023</a>)</li>
    <li>update ja/docs/_index.md (<a href="https://github.com/kubernetes/website/pull/25253" target="_blank">#25253</a>)</li>
    <li>ja: Make docs/reference/glossary/kube-apiserver.md follow v1.18 of the original text  (<a href="https://github.com/kubernetes/website/pull/25264" target="_blank">#25264</a>)</li>
    <li>ja: Make docs/setup/release/version-skew-policy.md follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/25268" target="_blank">#25268</a>)</li>
    <li>Update the outdated file ja/docs/home/supported-doc-versions.md (<a href="https://github.com/kubernetes/website/pull/25279" target="_blank">#25279</a>)</li>
    <li>fix typo (<a href="https://github.com/kubernetes/website/pull/25280" target="_blank">#25280</a>)</li>
    <li>ja: Make docs/tutorials/kubernetes-basics/explore/explore-intro.html follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/25297" target="_blank">#25297</a>)</li>
    <li>Make docs/reference/kubectl/cheatsheet.md follow v1.18 of the origina… (<a href="https://github.com/kubernetes/website/pull/25331" target="_blank">#25331</a>)</li>
    <li>ja: Make docs/setup/production-environment/container-runtimes.md follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/25347" target="_blank">#25347</a>)</li>
    <li>Update ja: docs/concepts/workloads/controllers/deployment.md (<a href="https://github.com/kubernetes/website/pull/25588" target="_blank">#25588</a>)</li>
    <li>ja: Translate reference/command-line-tools-reference/kubelet-authentication-authorization.md into Japanese (<a href="https://github.com/kubernetes/website/pull/25633" target="_blank">#25633</a>)</li>
    <li>update nodes.md for v1.18 (<a href="https://github.com/kubernetes/website/pull/26000" target="_blank">#26000</a>)</li>
    <li>fix typo (<a href="https://github.com/kubernetes/website/pull/26008" target="_blank">#26008</a>)</li>
    <li>Update Japanese localization on concepts/configuration/manage-resourc… (<a href="https://github.com/kubernetes/website/pull/26010" target="_blank">#26010</a>)</li>
    <li>fix typo of MTU (<a href="https://github.com/kubernetes/website/pull/26268" target="_blank">#26268</a>)</li>
    <li>[ja] removed install-minikube.md (<a href="https://github.com/kubernetes/website/pull/26495" target="_blank">#26495</a>)</li>
    <li>ja: Make docs/setup/production-environment/windows/user-guide-windows-containhers.md follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26531" target="_blank">#26531</a>)</li>
    <li>Update docs/setup/production-environment/windows/intro-windows-in-kubernetes.md (<a href="https://github.com/kubernetes/website/pull/26550" target="_blank">#26550</a>)</li>
    <li>Remove four files to follow the original. (<a href="https://github.com/kubernetes/website/pull/26552" target="_blank">#26552</a>)</li>
    <li>ja: Make docs/setup/production-environment/tools/kubeadm/high-availability.md follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26553" target="_blank">#26553</a>)</li>
    <li>Reflects differences from the original (#26506) (<a href="https://github.com/kubernetes/website/pull/26555" target="_blank">#26555</a>)</li>
    <li>Update docs/setup/production-environment/turnkey/gce.md to follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26557" target="_blank">#26557</a>)</li>
    <li>Update docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md to follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26558" target="_blank">#26558</a>)</li>
    <li>Update docs/setup/production-environment/turnkey/icp.md to follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26559" target="_blank">#26559</a>)</li>
    <li>Update docs/setup/production-environment/tools/kubespray.md to follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26560" target="_blank">#26560</a>)</li>
    <li>Remove docs/setup/production-environment/turnkey/clc.md to follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26561" target="_blank">#26561</a>)</li>
    <li>Update `ja/create-cluster-kubeadm.md` (<a href="https://github.com/kubernetes/website/pull/26571" target="_blank">#26571</a>)</li>
    <li>Update: docs/setup/production-environment/tools/kubeadm/ha-topology.md (<a href="https://github.com/kubernetes/website/pull/26579" target="_blank">#26579</a>)</li>
    <li>Update docs/setup/production-environment/tools/kubeadm/kubelet-integr… (<a href="https://github.com/kubernetes/website/pull/26592" target="_blank">#26592</a>)</li>
    <li>Update docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md to follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26634" target="_blank">#26634</a>)</li>
    <li>ja: Make docs/setup/production-environment/turnkey/aws.md follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26637" target="_blank">#26637</a>)</li>
    <li>ja: Update docs/setup/production-environment/on-premises-vm/cloudstack.md follow v1.18 of the original text (<a href="https://github.com/kubernetes/website/pull/26655" target="_blank">#26655</a>)</li>
    <li>ja: Make docs/setup/production-environment/tools/kubeadm/self-hosting.md follow v1.18 of the original text #26513 (<a href="https://github.com/kubernetes/website/pull/26763" target="_blank">#26763</a>)</li>
    </ul>
</details>
<br>

Co-authored-by: @KobayashiD27
Co-authored-by: @hikkie3110
Co-authored-by: @task4233
Co-authored-by: @an-0305
Co-authored-by: @akitok
Co-authored-by: @takaf04
Co-authored-by: @tettsu
Co-authored-by: @hase1128
Co-authored-by: @mox692
Co-authored-by: @taiju
Co-authored-by: @tanaka-takayoshi
Co-authored-by: @movingfinger
Co-authored-by: @m3y
Co-authored-by: @kennygt51
Co-authored-by: @arisgi
Co-authored-by: @JIIOryo
Co-authored-by: @hokkai7go
Co-authored-by: @butterv
Co-authored-by: @marimo713
Co-authored-by: @AnguillaJaponica
Co-authored-by: @RyuSA
Co-authored-by: @mwu966
Co-authored-by: @kosehy
Co-authored-by: @yoichiro0217
Co-authored-by: @ken-tunc
Co-authored-by: @masanetes

### CODE REVIEW

**Comment by inductor** [comment]
Ah, you're assigned as approver because there's a change in `static/_redirects`, brad. I will ping you after this has been approved by local team.

**Comment by bradtopol** [comment]
So @inductor contacted me.  He has obtained all the necessary approvals from the Japanese team. However the PR contains an update to static/_redirects so it needs an overall maintainer to approve.  I looked at the redirect change and its a straightforward update so I'm going to lgtm and approve since no other tech leads are around and we promised expedited reviews for these types of things.  /cc @jimangel @irvifa 
/lgtm
/approve

**Review by bradtopol — COMMENTED** [review]
PR already received Japanese team review and approval.

**Pull request merged**
