### PR TITLE
refresh controller role list on rbac description page

### PR DESCRIPTION
**Pull request by WanLinghao**
Now the cluster got more controller roles, refresh the list.

### CODE REVIEW

**Comment by tengqm** [comment]
@WanLinghao Should we target this at dev-1.13 branch?

**Comment by WanLinghao** [comment]
@tengqm  Yeah, I think so

**Comment by WanLinghao** [comment]
@tengqm But I do't know how to target this.. Could give me some hints?

**Comment by tengqm** [comment]
@WanLinghao When raising the PR, choose the upstream branch you are targeting.

**Comment by tengqm** [comment]
@WanLinghao I don't have a better solution.

**Comment by Bradamant3** [comment]
@WanLinghao you can also change the base branch in the GitHub UI, if it helps. (I can't see how to do it myself, as a maintainer. If you continue to have issues, though, I can pull down your fork and do it on the command line. I'll get through other 1.13 PRs and then check back here. lmk if I can help further.)

**Comment by WanLinghao** [comment]
@Bradamant3 Hello,plz check this one https://github.com/kubernetes/website/pull/11290

**Comment by Bradamant3** [comment]
replaced by #11290

**Pull request closed without merging**
