### PR TITLE
Fix typo in https://kubernetes.io/blog/2020/06/30/sig-windows-spotlight-2020/

### PR DESCRIPTION
**Pull request by sftim**
Fix typo spotted in https://github.com/kubernetes/website/pull/22179/files#r450381366

[Preview](https://deploy-preview-22395--kubernetes-io-master-staging.netlify.app/blog/2020/06/30/sig-windows-spotlight-2020/)

### CODE REVIEW

**Comment by kaslin** [comment]
Thanks for getting that! I was about to do the same.

**Comment by sftim** [comment]
@kaslin happy to review? You can reply with “/lgtm” and approvers will take account of it, even if Prow doesn't recognize you as an official blog reviewer.

**Comment by kaslin** [comment]
Do I need to assign it back to you to approve @sftim ?

**Comment by sftim** [comment]
I _can_ approve my own PR, but I'll let someone else do that.

**Pull request merged**
