### PR TITLE
[blog] Emphasis on person's name.

### PR DESCRIPTION
**Pull request by ystkfujii**

### CODE REVIEW

**Comment by ystkfujii** [comment]
Edited section: 

https://deploy-preview-45303--kubernetes-io-main-staging.netlify.app/blog/2024/02/22/k8s-book-club/#joining-the-book-club

**Review by sftim — COMMENTED** [review]
Sure

/lgtm
/approve

**Comment by sftim** [comment]
Please consider opening a PR to fix https://www.k8s.dev/blog/2024/02/22/k8s-book-club/ too.

**Comment by ystkfujii** [comment]
Of course!

https://github.com/kubernetes/contributor-site/pull/475

**Pull request merged**
