### PR TITLE
[zh] Fixed markdown syntax problem

### PR DESCRIPTION
**Pull request by kongwu-**
image

### CODE REVIEW

**Comment by kongwu-** [comment]
> 感谢您的拉取请求。在我们查看您的拉取请求之前，您需要签署一份贡献者许可协议 (CLA)。
> 
> 📝 **请按照https://git.k8s.io/community/CLA.md#the-contributor-license-agreement上的说明签署 CLA。**
> 
> CLA 签名可能需要几分钟才能完全注册；之后，请在此处回复一条新评论，我们将进行验证。谢谢。
> 
> * 如果您已经签署了 CLA，则可能我们没有您的 GitHub 用户名，或者您使用的是其他电子邮件地址。检查您现有的 CLA 数据并验证您的[电子邮件是否设置在您的 git commits 上](https://help.github.com/articles/setting-your-email-in-git/)。
> * 如果您以公司身份签署 CLA，请使用您组织的凭据登录https://identity.linuxfoundation.org/projects/cncf以获得授权。
> * 如果您已完成上述操作，但仍遇到被报告为未签名的 CLA 问题，请在 Linux 基金会帮助台上登记一张票：[https](https://support.linuxfoundation.org/) : [//support.linuxfoundation.org/](https://support.linuxfoundation.org/)
> * 如果您在 Linux Foundation Helpdesk 中遇到任何问题，请向备用电子邮件支持地址发送消息：[login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> [此处](https://git.k8s.io/community/contributors/guide/pull-requests.md)提供了有关使用 PR 评论与我互动的说明。如果您对我的行为有任何疑问或建议，请针对[kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:)存储库提出问题。我了解[此处](https://go.k8s.io/bot-commands)列出的命令。



> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

I have finished the CLA

**Comment by kongwu-** [comment]
The problem url: 

https://kubernetes.io/zh/docs/concepts/configuration/manage-resources-containers/

**Comment by tengqm** [comment]
```
$ ./scripts/lsync.sh content/zh/docs/concepts/configuration/manage-resources-containers.md
diff --git a/content/en/docs/concepts/configuration/manage-resources-containers.md b/content/en/docs/concepts/configuration/manage-resources-containers.md
index db2962180..5c30840f6 100644
--- a/content/en/docs/concepts/configuration/manage-resources-containers.md
+++ b/content/en/docs/concepts/configuration/manage-resources-containers.md
@@ -181,8 +181,9 @@ When using Docker:
   flag in the `docker run` command.

 - The `spec.containers[].resources.limits.cpu` is converted to its millicore value and
-  multiplied by 100. The resulting value is the total amount of CPU time that a container can use
-  every 100ms. A container cannot use more than its share of CPU time during this interval.
+  multiplied by 100. The resulting value is the total amount of CPU time in microseconds
+  that a container can use every 100ms. A container cannot use more than its share of
+  CPU time during this interval.
```

**Comment by tengqm** [comment]
```
$ ./scripts/lsync.sh content/zh/docs/concepts/configuration/manage-resources-containers.md
diff --git a/content/en/docs/concepts/configuration/manage-resources-containers.md b/content/en/docs/concepts/configuration/manage-resources-containers.md
index db2962180..5c30840f6 100644
--- a/content/en/docs/concepts/configuration/manage-resources-containers.md
+++ b/content/en/docs/concepts/configuration/manage-resources-containers.md
@@ -181,8 +181,9 @@ When using Docker:
   flag in the `docker run` command.

 - The `spec.containers[].resources.limits.cpu` is converted to its millicore value and
-  multiplied by 100. The resulting value is the total amount of CPU time that a container can use
-  every 100ms. A container cannot use more than its share of CPU time during this interval.
+  multiplied by 100. The resulting value is the total amount of CPU time in microseconds
+  that a container can use every 100ms. A container cannot use more than its share of
+  CPU time during this interval.
```

**Review by anubha-v-ardhan — APPROVED** [review]

**Comment by tengqm** [comment]
This PR is outdated. There are some other changes to be considered.
/close

**Pull request closed without merging**
