### PR TITLE
Fix duplicate localization strings for Portuguese

### LINKED ISSUE #22930: Website does not build
**This is a Bug Report**

**Problem:** After PR #20569 was merged, the website does not build. This is because the Portuguese localization includes a duplicate translation for a string.

**Proposed Solution:**
- Remove the duplication
**Additional Information:**

/priority critical-urgent
/kind bug

### PR DESCRIPTION
**Pull request by sftim**
Sort the Portuguese localization strings and remove duplicates. Fixes #22930.

/language pt
/kind cleanup

### CODE REVIEW

**Comment by sftim** [comment]
Fixes an error introduced with PR #20569

**Comment by sftim** [comment]
Fix for bug #22930

**Comment by kbhawkey** [comment]
I gave this a quick review. Thanks for fixing.
/lgtm

**Pull request merged**
