### PR TITLE
Generate single-page API reference for 1.24

### PR DESCRIPTION
**Pull request by nate-double-u**
Generated assets for single-page API reference for 1.24 release.

### CODE REVIEW

**Comment by nate-double-u** [comment]
It might be a touch early for this PR as code freeze hasn't hit yet--but I wanted to go through the process early in case I had any questions.

**Comment by nate-double-u** [comment]
Deploy preview: https://deploy-preview-32426--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.24/

**Comment by nate-double-u** [comment]
I'm not at all convinced that my dev setup is correct. @PI-Victor, I heard that you were working on potentially containerizing this process. Have you made any progress on it?

**Comment by nate-double-u** [comment]
This last commit looks better, someone, please confirm 🙂. We'll still need to wait on a subsequent release (something past the alpha stage).

Also, I built this using https://gitpod.io -- the default environment had Go and Python set up correctly, and I didn't need to muck about with it to get it to build. It may be easier to write instructions on using it rather than setting up a containerized system.

[etcd.io](https://github.com/etcd-io/website/#etcdio) has a basic gitpod.io example, though, for k/website, we'd probably have to include the forking the repo and explaining the process a bit more.

**Comment by sftim** [comment]
This PR at least doesn't look wrong. I'm not very familiar with the tooling used here.

**Comment by sftim** [comment]
/approve

The intent here makes sense and I'm happy to have v1.24 documented using the legacy / single-page reference.

**Comment by nate-double-u** [comment]
I should have rebased on dev-1.24 first...

I think I may close this PR and start fresh, might be easier/less confusing.

**Comment by jihoon-seo** [comment]
/remove-area blog release-eng
/remove-language de es fr id it ja ko pt ru vi zh
/remove-sig release

**Pull request closed without merging**
