### PR TITLE
Modify text in top page for KubeCon announcement

### PR DESCRIPTION
**Pull request by inductor**
KubeCon NA 2020 is now virtual

image

### CODE REVIEW

**Comment by inductor** [comment]
It now looks like this

**Comment by kbhawkey** [comment]
I'd like to get a CNCF reviewer to approve this change.
/hold
/cc @celestehorgan

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-23009--kubernetes-io-master-staging.netlify.app/

**Comment by celestehorgan** [comment]
/approve 

Thanks!!

**Pull request merged**
