### PR TITLE
Unsplit the doc view

### PR DESCRIPTION
**Pull request by sftim**
This reverts commit 589d67a7fa58184a6739ad85e970a1206b64cf74 from PR #41695, because we have found problems with the mobile view.

/area web-development

### CODE REVIEW

**Review by aj11anuj — APPROVED** [review]
I compared commits of this PR with that PR and as per me, It reverts changes of #41695 exactly without any error.
Fixes: #42921

**Comment by tengqm** [comment]
I believe someone is attempting to fix this using some CSS magic. Can we wait and see if that works out?

**Comment by sftim** [comment]
How about a time-box. Eg, we revert if we don't have a fix by 00:00 UTC on the 8th of September.

**Comment by Gauravpadam** [comment]
That might be a crunch, I'll try my best

**Comment by tengqm** [comment]
Another reference: https://www.creativebloq.com/javascript/expert-guide-making-your-javascript-responsive-71412226

**Comment by Gauravpadam** [comment]
@tengqm @sftim I tinkered around with a few possibilities that came to my mind. One of the closest plausible were setting display none on splitter components in smaller viewports (and I thought I'd later play with the html markup to fix the layout). The only problem is that the javascript leaves a lingering effect on the DOM :) I think It's the best if we revert these changes

**Review by dipesh-rawat — COMMENTED** [review]
I think it's better to temporarily undo the modifications, and subsequently, we can tackle the issues numbered #42947 #42921 (and other undiscovered layout issues). In the meantime, the website will have a correct layout.

/lgtm

**Comment by reylejano** [comment]
With https://github.com/kubernetes/website/pull/42943 merged, do we need this revert PR?
The preview from my mobile device for this PR and https://github.com/kubernetes/website/pull/42943 show the same

**Pull request closed without merging**
