### PR TITLE
Fix docs/reference/glossary/quantity.md page showing exception

### PR DESCRIPTION
**Pull request by Mr-Linus**

### CODE REVIEW

**Comment by Mr-Linus** [comment]
/assign @zacharysarah
I just changed the file to match the master branch, but why does netlify fail and I can't see the deploy log?

**Comment by chenrui333** [comment]
Error log
```
8:13:15 PM: ERROR 2018/11/28 12:13:15 error processing shortcode "shortcodes/codenew.html" for page "docs/tutorials/k8s101.md": template: shortcodes/codenew.html:14:16: executing "shortcodes/codenew.html" at <readFile $filename>: error calling readFile: stat /opt/build/repo/content/no/content/zh/examples/pods/simple-pod.yaml: no such file or directory
8:13:15 PM: ERROR 2018/11/28 12:13:15 error processing shortcode "shortcodes/codenew.html" for page "docs/tutorials/k8s101.md": template: shortcodes/codenew.html:14:16: executing "shortcodes/codenew.html" at <readFile $filename>: error calling readFile: stat /opt/build/repo/content/no/content/zh/examples/pods/simple-pod.yaml: no such file or directory
8:13:15 PM: ERROR 2018/11/28 12:13:15 error processing shortcode "shortcodes/codenew.html" for page "docs/tutorials/k8s101.md": template: shortcodes/codenew.html:14:16: executing "shortcodes/codenew.html" at <readFile $filename>: error calling readFile: stat /opt/build/repo/content/no/content/zh/examples/pods/storage/redis.yaml: no such file or directory
```

Need two files:
content/zh/examples/pods/simple-pod.yaml
content/zh/examples/pods/storage/redis.yaml

**Comment by Mr-Linus** [comment]
@chenrui333 Sure.

**Comment by Bradamant3** [comment]
/assign @tengqm 

This looks like a Chinese-translation focused effort, although the content page is in English. Can you help?

**Comment by Mr-Linus** [comment]
We find the problem at <https://github.com/kubernetes/website/pull/11311> and Thanks @xiangpengzhao and @tengqm for the advice.

**Comment by chenrui333** [comment]
@Bradamant3 It mainly trying to fix the format issue (which has some leftover of git merge), it /lgtm 😄

**Pull request merged**
