### PR TITLE
Add OpenStack vendor implementation link

### PR DESCRIPTION
**Pull request by ialidzhikov**
- Add OpenStack vendor implementation link
- Reorder vendor implementions in alphabetical order

### CODE REVIEW

**Comment by sftim** [comment]
This comes under “Content that simply links to information about a non-Kubernetes project” from the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/) (which changed recently).

It doesn't look acceptable to me. @aimeeu do you concur?

**Comment by ialidzhikov** [comment]
@sftim, I just added link to https://github.com/kubernetes/cloud-provider-openstack (which is a project in the kubernetes org) and I just reordered the vendor implementations in alphabetical order to easier navigation?
What's wrong?

**Comment by sftim** [comment]
I hadn't spotted that the new link is to a CNCF / Kubernetes project.
/lgtm

**Pull request merged**
