### PR TITLE
Updated the ResourceQuota doc for NodePort and LoadBalancer

### PR DESCRIPTION
**Pull request by yashsingh74**
Fixes : https://github.com/kubernetes/kubernetes/issues/125188

### CODE REVIEW

**Comment by T-Lakshmi** [comment]
[Original](https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota) | [Preview](https://deploy-preview-46592--kubernetes-io-main-staging.netlify.app/docs/concepts/policy/resource-quotas/#object-count-quota)

**Comment by yashsingh74** [comment]
I will close this PR and create a new one again.
This easycla is not working.

**Pull request closed without merging**
