### PR TITLE
Remove useless file and bump up deployment version

### PR DESCRIPTION
**Pull request by nashasha1**
Do the same thing as #7318  in cn doc folder.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7343)

### CODE REVIEW

**Comment by heckj** [comment]
Could you please review that recommendation and update these PRs to [include min-kubernetes-server-version in the front-matter of the various documents](https://kubernetes.io/docs/home/contribute/style-guide/#versioning-kubernetes-examples)?

**Comment by nashasha1** [comment]
@heckj  Should I close this PR? Such as other PRs, this PR should  be applied to kubernetes/kubernetes-docs-cn. Or we need to remove all those useless files out of kubernetes/website.

**Comment by heckj** [comment]
@nashasha1 yes - close this and re-apply these changes to the other repository

**Comment by nashasha1** [comment]
@heckj  Thank you.

**Pull request closed without merging**
