### PR TITLE
[WIP] KEP 2837 (Pod Level Resources) alpha blog

### PR DESCRIPTION
**Pull request by ndixita**
### Description
Placeholder PR for blog post on alpha changes to Pod Level Resources

### Issue
https://github.com/kubernetes/enhancements/issues/2837

Closes: #

### CODE REVIEW

**Comment by kannon92** [comment]
@ndixita Can you make sure this PR only includes your changes?

**Comment by utkarsh-singh1** [comment]
Also please add the description of the PR if you are ready for the review on your PR.

**Comment by jihoon-seo** [comment]
/remove-language bn de es fr hi id it ja ko pl pt ru uk vi zh
/remove-sig release

**Comment by ndixita** [comment]
working on this today, and will also request an extension

**Comment by sftim** [comment]
As this is a placeholder
/retitle [WIP] KEP 2837 (Pod Level Resources) alpha blog

**Comment by sftim** [comment]
Kubernetes 1.32 has been released (and the article PR wasn't ready by the deadline)

/close

**Pull request closed without merging**
