### PR TITLE
API Reference v1.22

### PR DESCRIPTION
**Pull request by feloy**
Replaces https://github.com/kubernetes/website/pull/28635

1. Move the assets necessary to build the API Reference from the api-ref-generator submodule (https://github.com/kubernetes-sigs/reference-docs) to this repository. This is in preparation to add translation assets for the API Reference (https://github.com/kubernetes/website/pull/27842)

 2. Generated files for the API Reference for v1.22 (beta.0 at this time)

### CODE REVIEW

**Comment by annajung** [comment]
Hi @feloy looks like there is a conflict in the README. would you be able to address this?

**Comment by sftim** [comment]
/approve
We can push a merge commit if need be, but a rebase against current _dev-1.22_ would be ideal.

**Comment by feloy** [comment]
> Hi @feloy looks like there is a conflict in the README. would you be able to address this?

Hi @annajung I addressed the conflict

**Comment by kbhawkey** [comment]
Did this merge accidentally (no lgtm)?

**Pull request merged**
