### PR TITLE
Use https for link on Stackoverflow 

### PR DESCRIPTION
**Pull request by eatjeff**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@eatjeff
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by kbhawkey** [comment]
👋 @eatjeff . Thanks for contributing!
Would you verify that you have signed the CLA?

**Comment by kbhawkey** [comment]
Related to PRs: https://github.com/kubernetes/website/pull/26305, https://github.com/kubernetes/website/pull/26306

**Comment by mrbobbytables** [comment]
The CLA has not been signed, going to go ahead and close this for now. It can be reopened at a later date after the CLA issue has been resolved.

/close

**Pull request closed without merging**
