### PR TITLE
Merge main branch into dev-1.25

### PR DESCRIPTION
**Pull request by cathchu**
Merge main into dev-1.25 to keep in sync
/cc @kcmartin @krol3 @sethmccombs @didicodes

### CODE REVIEW

**Comment by krol3** [comment]
> Merge main into dev-1.25 to keep in sync /cc @kcmartin @krol3 @sethmccombs @didicodes

@cathchu is this PR against k8s/dev-1.25 instead of main?

**Comment by cathchu** [comment]
> > Merge main into dev-1.25 to keep in sync /cc @kcmartin @krol3 @sethmccombs @didicodes
> 
> @cathchu should this PR against k8s/dev-1.25 instead of main?

My bad, @krol3. Just adjusted it. Thanks for the heads up!

**Comment by sftim** [comment]
Thanks

/lgtm
/approve

**Comment by sftim** [comment]
Oops.There were issues; I'll fix them.

**Pull request merged**
