### PR TITLE
Update custom-resource-definition-versioning.md

### PR DESCRIPTION
**Pull request by dancnfoo**
`stored` should be `storage`

### CODE REVIEW

**Comment by dancnfoo** [comment]
I signed it

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-27573--kubernetes-io-master-staging.netlify.app/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions

**Comment by dancnfoo** [comment]
@kbhawkey Could you review?  The PR has been idle for a while.

**Comment by tengqm** [comment]
Thanks.
/lgtm
/approve

**Pull request merged**
