### PR TITLE
Clickable video feature

### PR DESCRIPTION
**Pull request by ankush1233**
Clickable video feature on watch video

### CODE REVIEW

**Comment by windsonsea** [comment]
Please sign CLA before review, refer to: https://git.k8s.io/community/CLA.md

**Review by Arhell — COMMENTED** [review]
/easycla

**Comment by windsonsea** [comment]
If changed, it will be inconsistent with [en source](https://github.com/kubernetes/website/blob/main/content/en/_index.html).

How about to change to en version firstly?

**Review by akhil888binoy — COMMENTED** [review]
I don't think its  necessary over here as it will distort the UI/UX of website.

**Comment by reylejano** [comment]
Changes should be made in the `en` site first before to any localizations
I agree with @windsonsea 's comment

**Comment by reylejano** [comment]
Closing this PR in agreement with several reviewers that this change needs to be in the `en` site first and another reviewer stating this change is not needed
If you feel otherwise, feel free to reopen this PR with `/reopen` in a comment
/close

**Pull request closed without merging**
