### PR TITLE
Update hello-minikube.md

### PR DESCRIPTION
**Pull request by thachnv92**
I want to update hello-minikube.md

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
@thachnv92 
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by bradtopol** [comment]
Hi @thachnv92 Thank you for your contribution.  Please sign the CLA so we can accept your PR for review.
/assign

**Comment by kbhawkey** [comment]
Hi @thachnv92 .
Would you verify that you have signed the CLA?
Without a CLA, your pull request cannot be reviewed.

**Comment by kbhawkey** [comment]
Hi @thachnv92 .
I am closing this pull request. You need to sign the CLA.
Feel free to reopen this PR at any time. Reach out if you need help or more information. Thanks!
/close

**Pull request closed without merging**
