### PR TITLE
[hi] Update /hi/docs/setup/ to align with English

### PR DESCRIPTION
**Pull request by Vikash-8090-Yadav**
What would you like to be added

I want to update this page and make this page doc align with the English one as it is an outdated one.

This https://kubernetes.io/hi/docs/setup/ to align with https://kubernetes.io/docs/setup/

Why is this needed
https://kubernetes.io/hi/docs/setup/ looks like stale

Issue it solves #42755

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/assign @divya-mohan0209

**Review by aj11anuj — CHANGES_REQUESTED** [review]
<html>
<body>
<div class="gE iv gt" style="font-size: 0.875rem; cursor: auto; padding: 20px 0px 0px; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

</div><div id=":nb" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="btm"></div></div><div class="" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aHl" style="margin-left: -38px;"></div><div id=":no" tabindex="-1"></div><div id=":nd" class="ii gt" jslog="20277; u014N:xr6bB; 1:WyIjdGhyZWFkLWE6cjYxNzA5NjI5OTg4ODc2NjQyMyIsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsW11d; 4:WyIjbXNnLWE6cjgwMzI1Mjk4NjIwNzAzMTk2MDYiLG51bGwsW10sbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsW10sW10sW11d" style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":nc" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;"><div dir="auto">Line 23:<br>"क्लस्टर के भीतर" is more appropriate here than "भी क्लस्टर के भीतर"<br>"इमेजेस" should be replaced with "इमेजिस"<br><br>Line 25:<br>Last phrase can be paraphrased for more better understanding of this line as "जिन संगठनो को कंटेनर चल़ाते हैं उन्हें इस श्रे्णी में शामिल नही किया जा सकता - विशेष रूप से kubelet |</div></div></div></div>
</body>
</html>

**Review by aj11anuj — COMMENTED** [review]
Line 23: Whether 2nd link will work or not, i doubt

**Comment by Vikash-8090-Yadav** [comment]
@aj11anuj sorry for the late reply. I will update all mentioned changes by EOD. 
Thanks!

**Pull request closed without merging**
