### PR TITLE
[zh] fix kubelet flag description

### PR DESCRIPTION
**Pull request by liuxu623**
same as #28809

### CODE REVIEW

**Comment by chenxuc** [comment]
Thank you for proposing this fix. However, we will not merge partial fixes as per stated in the [guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). To find out what are the upstream changes to be synced, do this on the main branch:
```
./scripts/lsync.sh content/zh/docs/reference/command-line-tools-reference/kubelet.md
```
谢谢贡献。根据指南约定，我们会拒绝对页面的部分修改。部分修改针对的是对应页面的英文上游还有其他改动需要同步的情况。
一旦我们合并了此 PR，将来就无法根据文件的最后更改时间来判断是否有其他上游变更尚未同步。请理解。

请在 main 分支上执行以下命令查看上游尚未同步的更改：
```
./scripts/lsync.sh content/zh/docs/reference/command-line-tools-reference/kubelet.md
```

**Comment by liuxu623** [comment]
@chenxuc So I should to sync all upstream changes and translate to Chinese?

**Comment by chenxuc** [comment]
@liuxu623 We need to translate all the new English contents that is shown in the lsync.sh command. Someone commit one more change to the kubelet.md file after you submitted the initial PR. So your initial PR does not contain the translation for that commit's content. You should translate that addtional content in your PR too, so that after your PR is merged, the Chinese doc is fully synced with the English doc. thanks.

**Comment by tengqm** [comment]
/hold
The English version is out of date. Need a manual fix. I'm working on it.

**Comment by tengqm** [comment]
See #29284 for the English version update.

**Comment by tengqm** [comment]
@liuxu623 Suppose you are still interested in making this changes, please run the following command on the **main** branch and perform a complete resync:

```bash
./scripts/lsync.sh content/zh/docs/reference/command-line-tools-reference/kubelet.md
```

**Comment by tengqm** [comment]
No response from the author for a long time. Feel free to reopen and continue working on this.
/close

**Pull request closed without merging**
