### PR TITLE
Align dev-1.17-it.1 with current master

### PR DESCRIPTION
**Pull request by Fale**
as title

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@sftim @zacharysarah PTAL

**Comment by sftim** [comment]
Ah, what merge-method should this PR have? Eg /tide merge-method-merge

**Comment by Fale** [comment]
I think it should be `/tide merge-method-rebase` or eventually `/tide merge-method-merge`, though I think the first one would be better than the latter, keeping the history easier to follow

**Comment by sftim** [comment]
I think `/tide merge-method-merge` is safest. I'm not sure how well Tide handles rebasing merge commits.

**Comment by Fale** [comment]
Ok for me to go with `/tide merge-method-merge`.

Should someone with special access set it, isn't it?

**Comment by fabriziopandini** [comment]
@sftim any suggestion to get this moving?

**Comment by sftim** [comment]
How about cutting a new branch _dev-1.18-it.1_ based off _master_, and then merge _dev-1.17-it.1_ into that? This should be mechanical work (I can do it without needing to speak Italian well).

Once that is done, create a PR to merge _dev-1.18-it.1_ into _master_.

How does that sound?

**Comment by Fale** [comment]
this solution would work for me!

**Comment by sftim** [comment]
I'll see how I can help.

**Comment by Fale** [comment]
would it be possible to at least create the branch? If so, I can then open the PR for the merge, since I believe it will have some conflicts to manage ;-)

**Comment by sftim** [comment]
It's creating the branch that I need to learn how to do (or, really, how to get access to do).

**Comment by Fale** [comment]
Reading from https://kubernetes.io/docs/contribute/localization/#branching-strategy I think the person that creates the branch needs to be a website maintainer, so I guess one of those people will need to create it https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L159

**Comment by sftim** [comment]
Ah, that saved me a job. Let me add myself there.

**Comment by sftim** [comment]
The branch thing needs sorting, I'm [working on that](https://github.com/kubernetes/website/pull/20109).

**Comment by sftim** [comment]
@Fake I made a branch [_dev-1.18-it.1_](https://github.com/kubernetes/website/tree/dev-1.18-it.1)

**Comment by Fale** [comment]
@sftim thanks! I've opened a PR to merge `dev-1.17-it.1` into `dev-1.18-it.1`. As soon as it is merged, I'll close this PR and rebase all other PRs.

**Pull request closed without merging**
