### PR TITLE
Merge main into dev 1.22 

### PR DESCRIPTION
**Pull request by PI-Victor**
Branch sync that fixes all conflicts in the integration branch and syncs the dev-1.22 branch with the latest changes from master.

/cc @ashnehete @carlisia @chrisnegus @ritpanjw

### CODE REVIEW

**Comment by PI-Victor** [comment]
no failed commits, impressive

**Comment by sftim** [comment]
/hold
There's now a conflict
/approve

**Comment by sftim** [comment]
Release docs folks: unhold this at will.

**Comment by PI-Victor** [comment]
/hold cancel
can someone give me a lgtm on this again, when the tests have passed, thanks!

**Pull request merged**
