### PR TITLE
[en] fix access-cluster.md link error

### PR DESCRIPTION
**Pull request by shuaijinchao**
/language en

Related PR #29078

It does not point to the correct document address, and it will stay on the current page when clicked.

### CODE REVIEW

**Comment by chrisnegus** [comment]
@shuaijinchao It appears that this fix is already in progress. See [PR #31019](https://github.com/kubernetes/website/pull/31019). I suggest we close this PR.

**Review by chrisnegus — COMMENTED** [review]
@shuaijinchao It appears that this fix is already in progress. Your fix matches [PR #31019](https://github.com/kubernetes/website/pull/31019). I suggest we close this PR.

**Comment by shuaijinchao** [comment]
> @shuaijinchao It appears that this fix is already in progress. Your fix matches [PR #31019](https://github.com/kubernetes/website/pull/31019). I suggest we close this PR.

Okay, sorry, I didn’t notice, I will close this PR

/close

**Comment by chrisnegus** [comment]
> > @shuaijinchao It appears that this fix is already in progress. Your fix matches [PR #31019](https://github.com/kubernetes/website/pull/31019). I suggest we close this PR.
> 
> Okay, sorry, I didn’t notice, I will close this PR
> 
> /close

No problem. Better to have two people try to fix it than none!

**Pull request closed without merging**
