### PR TITLE
Add reference doc for kube-scheduler policy

### PR DESCRIPTION
**Pull request by tengqm**
This is a reference for kube-scheduler policy config generated from kubernetes-sigs/reference-docs/genref tool.
More specifically, it is generated using the following command:

```
./genref --include kube-scheduler-policy-config
```

### CODE REVIEW

**Comment by tengqm** [comment]
Preview: https://deploy-preview-26602--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kube-scheduler-policy-config.v1/

**Comment by tengqm** [comment]
/hold
Depends on: https://github.com/kubernetes-sigs/reference-docs/pull/214

**Comment by tengqm** [comment]
/hold cancel
kubernetes-sigs/reference-docs#214 is in.

**Comment by sftim** [comment]
/lgtm
This is generated from reviewed code. No technical review needed.

**Comment by kbhawkey** [comment]
Hi @tengqm .
The preview shows several duplicate strings under the "Appears In" sections, see:
https://deploy-preview-26602--kubernetes-io-master-staging.netlify.app/docs/reference/config-api/kube-scheduler-policy-config.v1/#kubescheduler-config-k8s-io-v1-ServiceAntiAffinity

Otherwise, looks great!

**Comment by tengqm** [comment]
> content/en/docs/reference/scheduling/policies.md

Good spot. Manually fixed. Will investigate the generator logic.

**Pull request merged**
