### PR TITLE
Update CSS for GitHub info bar

### PR DESCRIPTION
**Pull request by lucperkins**
Current:

screen shot 2018-10-04 at 10 57 36 am

With these fixes:

screen shot 2018-10-04 at 10 56 33 am

### CODE REVIEW

**Comment by kbhawkey** [comment]
@lucperkins, glad you are fixing this. Though, I wonder if this pre footer section should span the page, or left align, but with a left margin? It is a banner on every page, like the nav menu in the footer.  Also, would it be possible to reduce the size of the commit message text, so that it does not interfere with the actual page content?

**Comment by Bradamant3** [comment]
@lucperkins what do you want to do with this PR now? Rebase? Rewrite anything else? (trying to clean up the backlog queue ...)

**Comment by lucperkins** [comment]
@Bradamant3 I've rebased this and checked the preview build. Feel free to re-review.

**Comment by bhavin192** [comment]
This fixed #9719 Thank you @lucperkins

**Pull request merged**
