### PR TITLE
tą instalację -> tę instalację 

### PR DESCRIPTION
**Pull request by wojtekidd**
https://sjp.pwn.pl/poradnia/haslo/te-czy-ta;1598.html

### CODE REVIEW

**Comment by kpucynski** [comment]
@wojtekidd you have to sign up the CLA before proceeding further with your PR...

**Comment by wojtekidd** [comment]
I already have the CLA signed - it's connected to my GitHub account and the email in the CLA is identical with the one in the commit. Please refer [to this PR](https://github.com/kubernetes/website/pull/18701)

I was trying to do a PR on a clean slate, but something is wrong again and I'm questioning my sanity 😕

**Comment by kpucynski** [comment]
hm, have you tried this?
> 7. My pull request still doesn't pass!
> If you haven't yet, post a comment ("I signed it") to the PR—this is needed for the system to recheck your contribution authorization.

maybe you can try to sign commit?
`git commit --amend -s`

**Comment by wojtekidd** [comment]
I signed it

**Comment by mfilocha** [comment]
Maybe it's time to?

> If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/

**Comment by wojtekidd** [comment]
I think I fixed it after contacting the Linux Foundation. Would you please try to check my CLA now 🤞

**Comment by kpucynski** [comment]
I have no idea if this /check-cla is working. Maybe try with new PR :|

**Comment by wojtekidd** [comment]
Info from the helpful staff at Linux Foundation

> I checked this morning and see that you got the ICLA signed, but resending the ICLA must have broken the automation that puts you in the correct authorized group. I did that for you manually just now, so now you should be able to comment on your pr and pass the cla check.

**Comment by wojtekidd** [comment]
I signed it

**Comment by kpucynski** [comment]
whoa, it worked :D :fireworks:

**Comment by kpucynski** [comment]
and, like, ten days later we are ready to approve :D
ping @nvtkaszpir @mfilocha

**Pull request merged**
