### PR TITLE
[de] Fix typo in hello-minikube.md

### PR DESCRIPTION
**Pull request by jarmee**
Fixes minor typo in `hello-minikube.md`.  `anzigen` should be `anzeigen`

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/check-cla

**Comment by RA489** [comment]
> Contributor License Agreement has been signed.

/check-cla

**Comment by jarmee** [comment]
Sorry, for the inconvenience.

**Review by bene2k1 — APPROVED** [review]

**Pull request merged**
