### PR TITLE
Promote DaemonSet MaxSurge to GA

### PR DESCRIPTION
**Pull request by atiratree**
adds docs for  DaemonSet MaxSurge GA promotion

- https://github.com/kubernetes/enhancements/issues/1591
- https://github.com/kubernetes/kubernetes/pull/111194

### CODE REVIEW

**Comment by atiratree** [comment]
@ravisantoshgudimetla @soltysh

**Comment by tengqm** [comment]
Please propose this to the 'dev-1.25' branch, not the 'main' branch.

**Comment by atiratree** [comment]
thanks, updated (sorry for the mixup)

**Review by soltysh — APPROVED** [review]
/lgtm
from tech pov

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

Thank you for working on this @atiratree

**Pull request merged**
