### PR TITLE
Align pre-footer

### LINKED ISSUE #10638: align or add left margin for pre-footer buttons, page last modified info
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The `Create an issue button`, `Edit this page buttons`, `Page last modified banner` in the pre-footer for most pages, except the home doc page, could be better aligned on the page and with the page footer.

**Proposed Solution:**
Add margin or align the pre-footer section (two buttons + page modified banner).
Could make the page modified banner text smaller.

**Page to Update:**
Most content pages.
ex: https://kubernetes.io/docs/reference/

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Applied margin to the buttons and pre-footer banner.
Closes #10638

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
https://github.com/kubernetes/website/issues/10638#issuecomment-431298402

**Comment by jamesgeorge007** [comment]
@xiangpengzhao  @stewart-yu @kbarnard10 What do you think?

**Comment by stewart-yu** [comment]
little knowledge about it

**Comment by jamesgeorge007** [comment]
@stewart-yu As you can from the image above, the ``` pre-footer ``` appear cluttered. I had displaced them a bit so that it looks pretty. What do you think?

**Comment by mistyhacks** [comment]
Closing this in favor of the other PR.

**Pull request closed without merging**
