### PR TITLE
Added Giant Swarm to On-Prem and Turnkey

### PR DESCRIPTION
**Pull request by tommyhobin**
Please contact me with questions or concerns.

### CODE REVIEW

**Comment by zparnold** [comment]
Hey there! @tommyhobin, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by zparnold** [comment]
@tommyhobin Could you please fix the merge conflict? Then we're good to go?

**Comment by tommyhobin** [comment]
@zparnold, I have made changes to the merge conflict and signed the CLA back in early Sept. Beyond that, I don't have the skillset to go further. If there is still an issue, I will need to ask a colleague to help. Sorry about the inconvenience. 
[cla_individual-eebd5c430fce50f48f714bda00d0a73204e78129.pdf](https://github.com/kubernetes/website/files/2445417/cla_individual-eebd5c430fce50f48f714bda00d0a73204e78129.pdf)

**Pull request merged**
