### PR TITLE
Translate tasks/manage-daemon/rollback-daemon-set.md into Korean

### LINKED ISSUE #21377: Translate tasks/manage-daemon/rollback-daemon-set.md into Korean
**This is a Feature Request**

**What would you like to be added**

Translate tasks/manage-daemon/rollback-daemon-set.md into Korean.

**Why is this needed**

There is no document of tasks/manage-daemon/rollback-daemon-set.md which is translated into Korean.

**Comments**

Page to translate: https://kubernetes.io/docs/tasks/manage-daemon/rollback-daemon-set/

/language ko

### PR DESCRIPTION
**Pull request by pjhwa**
Closes #21377 

This PR depends on PR #21376 due to the followings:
- tasks/manage-daemon/_index.md file
- links to translated docs with PR #21376 (tasks/manage-daemon/update-daemon-set.md)

### CODE REVIEW

**Comment by pjhwa** [comment]
> There's lots of English still in this page. Is that intended?

Oops! I totally forgot to remove the original text. :-) Thank you!!!

**Comment by sftim** [comment]
@pjhwa are you also OK to squash this down to 1 commit?

**Pull request merged**
