### PR TITLE
[zh-cn] enforce-standards-admission-controller.md

### PR DESCRIPTION
**Pull request by gaogao101**
Signed-off-by: Gao Qian <gaoq.jy@fujitsu.com>

### CODE REVIEW

**Comment by Sea-n** [comment]
Hey @gaogao101,

Please also include a minor tweak from #39476.

**Comment by Zhuzhenghao** [comment]
SEE https://github.com/kubernetes/website/blob/main/content/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md

Thank you for submitting this PR. I noticed that the changes made in this PR have already been made in the main branch. Therefore, I suggest that you close this PR and merge your changes into the latest main branch. Please let me know if you need any further assistance.

**Comment by tengqm** [comment]
> SEE https://github.com/kubernetes/website/blob/main/content/zh-cn/docs/tasks/configure-pod-container/enforce-standards-admission-controller.md
> 
> Thank you for submitting this PR. I noticed that the changes made in this PR have already been made in the main branch. Therefore, I suggest that you close this PR and merge your changes into the latest main branch. Please let me know if you need any further assistance.

There is not conflict reported on this PR. The changes loos acceptable. WDYT?

**Comment by windsonsea** [comment]
A long time passed. Let's kick this in and allow another PR covers those minor changes.

/lgtm
/approve

**Pull request merged**
