### PR TITLE
Use consistent pluralization for API groupings in reference

### PR DESCRIPTION
**Pull request by feloy**
Fixes https://github.com/kubernetes/website/issues/26361

Files generated with this version of the generator: https://github.com/kubernetes-sigs/reference-docs/pull/209

### CODE REVIEW

**Review by onlydole — APPROVED** [review]
Looks good to me, thank you @feloy!

**Comment by kbhawkey** [comment]
👋 @feloy .
PR https://github.com/kubernetes-sigs/reference-docs/pull/209 has merged.
This PR updates: policy-resources, service-resources, and workload-resources.
I noted several changes to text in two files in  `extend-resources`. Did you use an updated spec to generate the files?
With these updates, should the api-ref-generator submodule change?

**Comment by feloy** [comment]
>  @feloy .
> PR [kubernetes-sigs/reference-docs#209](https://github.com/kubernetes-sigs/reference-docs/pull/209) has merged.
> This PR updates: policy-resources, service-resources, and workload-resources.
> I noted several changes to text in two files in `extend-resources`. Did you use an updated spec to generate the files?
> With these updates, should the api-ref-generator submodule change?

I'm unable to find where the old text for these changes comes from. I pefer to remove these changes from this PR

**Comment by kbhawkey** [comment]
@feloy This PR is ready to merge?
/hold cancel

**Comment by kbhawkey** [comment]
Thanks @feloy 
/lgtm

Remove hold if ready.
/hold

**Pull request merged**
