### PR TITLE
Fix customized CSS for case study

### LINKED ISSUE #10486: Layout broken on several Case Study pages (with customized layout)
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

There are several case studies with custom (not general) CSS.

The full list of such case studies are following:

- https://kubernetes.io/case-studies/amadeus/
- https://kubernetes.io/case-studies/ancestry/
- https://kubernetes.io/case-studies/blablacar/
- https://kubernetes.io/case-studies/blackrock/
- https://kubernetes.io/case-studies/buffer/
- https://kubernetes.io/case-studies/golfnow/
- https://kubernetes.io/case-studies/peardeck/
- https://kubernetes.io/case-studies/wink/

/cc @kbhawkey 

**Proposed Solution:**

Fix customized CSS.

**Page to Update:**

The list are shown as above.

cf. #10462 (PR: #10463)

### PR DESCRIPTION
**Pull request by tnir**
Closes #10486 

**Problem:** Layout is broken on several case study detail pages with custom (not general) CSS.

**Proposed Solution:** Modernize and fix customized CSS.

**Pages to Update:**

- https://kubernetes.io/case-studies/amadeus/
- https://kubernetes.io/case-studies/ancestry/
- https://kubernetes.io/case-studies/blablacar/
- https://kubernetes.io/case-studies/blackrock/
- https://kubernetes.io/case-studies/box/
- https://kubernetes.io/case-studies/buffer/
- https://kubernetes.io/case-studies/crowdfire/
- https://kubernetes.io/case-studies/golfnow/
- https://kubernetes.io/case-studies/haufegroup/
- https://kubernetes.io/case-studies/huawei/
- https://kubernetes.io/case-studies/peardeck/
- https://kubernetes.io/case-studies/wink/
- https://kubernetes.io/case-studies/zalando/

----

Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

### CODE REVIEW

**Comment by tnir** [comment]
To reviewers, use the following links to the pages updated in this PR:

- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/amadeus/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/ancestry/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/blablacar/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/blackrock/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/box/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/buffer/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/crowdfire/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/golfnow/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/haufegroup/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/huawei/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/peardeck/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/wink/
- https://deploy-preview-10531--kubernetes-io-master-staging.netlify.com/case-studies/zalando/

/assign @zparnold

**Comment by tnir** [comment]
(forgot to add at-mark in the previous command 😭 )

/cc @kbhawkey

**Comment by tengqm** [comment]
@tnir Please see if there are conflicts to be resolved...

**Comment by tnir** [comment]
Thanks for notifying me if there are conflicts. Just resolved it 😄 

/cc @tengqm

**Comment by kbhawkey** [comment]
@tnir, things look much better. I compared the changes against v1.11 and the first section of the case studies is the two column, multiple paragraph format. Is this columnar format supposed to be in v1.12? I am guessing this should be fixed in a generic way.
Also, what color is the footer supposed to be, black or dark gray?

**Comment by Bradamant3** [comment]
I might be missing something, but I don't see layout or color differences between this PR and the live site.

/approve

**Pull request merged**
