### PR TITLE
add kube-ovn installation

### PR DESCRIPTION
**Pull request by oilbeater**
Add a new CNI installation

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Hi @oilbeater!! Thanks for the PR. However, there is another PR in progress for removing third party CNI plugin content. Please see: https://github.com/kubernetes/website/pull/17694

**Comment by Rajakavitha1** [comment]
sig/cluster-lifecycle

**Comment by Rajakavitha1** [comment]
assign @neolit123

**Comment by oilbeater** [comment]
@Rajakavitha1 Thanks for the notification. Kube-OVN is now in the CNCF landscape and being actively maintained. If the decision is made to not add any network plugin in this doc, I am fine with that. It's really too many content here :)

**Comment by neolit123** [comment]
/hold

thanks for the PR.
let's see how the discussions in https://github.com/kubernetes/website/issues/17634
and https://github.com/kubernetes/website/pull/17694 develop first.

in the meantime you can get kube-ovn to pass the conformance tests using Sonobuoy https://github.com/cncf/k8s-conformance/blob/master/instructions.md

**Comment by sftim** [comment]
@neolit123 what course of action do you recommend for this PR?

**Comment by neolit123** [comment]
/close

recently i saw some reports that kube-ovn had issues, or rather breaking changes with latest k8s.
but cannot find the discussion.

for the kubeadm guide, my preference is to not add more plugins for the time being unless they match our criteria.
- part of CNCF landscape
- pass conformance tests
- being somewhat popular

and of course final judgement is left to the kubeadm maintainers who babysit issue trackers and the code base.

also i'm going to rebase https://github.com/kubernetes/website/pull/17694 so that we can proceed with merging that too.

**Pull request closed without merging**
