### PR TITLE
Document “Panic: no auth provider found” error message and advice for kubectl

### LINKED ISSUE #35896: Document setting up cloud provider kubectl auth via plugin (AKS, GKE)
**This is a Feature Request**

**What would you like to be added**
(As I understand it), Kubernetes ~v1.25~ v1.26 ships an updated `kubectl`. The updated `kubectl` won't include built-in plugins for authenticating to AKS or GKE.
This is likely to surprise folks.

Update 3 pages:
- https://kubernetes.io/docs/tasks/tools/install-kubectl-linux
- https://kubernetes.io/docs/tasks/tools/install-kubectl-macos
- https://kubernetes.io/docs/tasks/tools/install-kubectl-windows

to **signpost** users to the right internal ~and external~ docs. We can remove this signposting once Kubernetes v1.27 (sic) is the oldest supported version of Kubernetes (consider adding an HTML comment with that detail).

Optionally, also update https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins to mention that earlier versions of `kubectl` included built-in support for authenticating to AKS and GKE, but this is no longer present.

**Why is this needed**
Readers may follow the “install kubectl” docs and get a tool that's missing functionality they thought was built in.

**Comments**
> The gcp and azure auth plugins have been removed from client-go and kubectl. See [AKS](https://github.com/Azure/kubelogin) and [GKE](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke) documentation for details about the cloud-specific replacements.

/sig cli
/language en

### PR DESCRIPTION
**Pull request by kadtendulkar**
Fixes #35896

Updated pages
Install and Set Up kubectl on [Linux](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux), [macOS](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/), [Windows](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows).

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Document “Panic: no auth provider found” error message and advice for kubectl

**Review by sftim — COMMENTED** [review]
/hold

This removal didn't actually happen, AIUI. I recommend checking whether the built-in integrations were truly removed (OK to unhold if they were).

However, this could be good text to include in Kubernetes 1.26 docs

**Comment by reylejano** [comment]
Kubernetes 1.25 did not remove these auth plugins due to a regression issue in PR https://github.com/kubernetes/kubernetes/pull/111918

**Comment by reylejano** [comment]
Closing this PR as Kubernetes 1.25 did not remove Google and Azure auth plugins due to a regression issue. The revert is in PR https://github.com/kubernetes/kubernetes/pull/111918

**Comment by reylejano** [comment]
Closing this PR as Kubernetes 1.25 did not remove Google and Azure auth plugins due to a regression issue. The revert is in PR https://github.com/kubernetes/kubernetes/pull/111918

/close

**Pull request closed without merging**
