### PR TITLE
Fix word 'anda' to 'kamu' for Indonesian translation

### PR DESCRIPTION
**Pull request by nsetya12**
Fixing words suggested in Kubernetes contributor workshop in Openinfra Day Surabaya Indonesia

/language.id
/cc @girikuncoro

### CODE REVIEW

**Comment by nsetya12** [comment]
Fixing words suggested in Kubernetes contributor workshop in Openinfra Day Surabaya Indonesia

/language.id
/cc @girikuncoro

**Comment by irvifa** [comment]
@nsetya12 can you please fix the conflict first? Thanks..

**Comment by tfogo** [comment]
Hi @nsetya12, thanks for the PR! Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA so that we can review this PR, thanks!

**Comment by girikuncoro** [comment]
closing this since there is no response from the author after 27 days

/close

**Pull request closed without merging**
