### PR TITLE
update controller.md

### PR DESCRIPTION
**Pull request by lojies**
Update controller.md, change “ to ".

### CODE REVIEW

**Comment by bradtopol** [comment]
@lojies What is the purpose of this change? I did not see a change in how this was rendered in 
https://deploy-preview-17417--kubernetes-io-master-staging.netlify.com/docs/concepts/architecture/controller/

compared to 
https://kubernetes.io/docs/concepts/architecture/controller/

**Comment by lojies** [comment]
@bradtopol, this seems like the same.But i think it's better to use quotation marks in  an en doc, not Chinese quotation marks.

**Comment by sftim** [comment]
@lojies `“` and `”` are common [quotation characters in English](https://en.wikipedia.org/wiki/Quotation_marks_in_English) (as are `"`).

**Comment by lojies** [comment]
@sftim, thanks.

**Pull request closed without merging**
