### PR TITLE
[pt-br] Update Secrets page to latest English version

### PR DESCRIPTION
**Pull request by stormqueen1990**
### Changes
* Update the Brazilian Portuguese version of the Secrets page to reflect the latest English version.

### CODE REVIEW

**Comment by edsoncelio** [comment]
Thanks @stormqueen1990! 
It looks like you need to rebase to fix some conflicts, after that will be a LGTM :D

**Comment by stormqueen1990** [comment]
> Thanks @stormqueen1990! It looks like you need to rebase to fix some conflicts, after that will be a LGTM :D

Hi there, @edsoncelio!

Just rebased the branch, could you please re-review?

Thanks!

**Comment by edsoncelio** [comment]
Thanks!
/lgtm

**Comment by rikatz** [comment]
/approve
Thanks

**Pull request merged**
