### PR TITLE
Fix phrasing.

### PR DESCRIPTION
**Pull request by nurayko**

### CODE REVIEW

**Review by palnabarun — APPROVED** [review]
Thanks for raising the PR!

/lgtm
/approve
/hold for more steering members to have a look

@kubernetes/steering-committee -- this is a trivial change, and I don't think we need a formal consensus here for a typo fix. WDYT?

**Review by ydFu — APPROVED** [review]
/lgtm
LGTM for fix typo.

**Comment by cblecker** [comment]
/hold cancel
/approve
@palnabarun no this is fine

**Pull request merged**
