### PR TITLE
[bn] localize : application-architect.md

### PR DESCRIPTION
**Pull request by MRH-Romit**
I've localized application-architect.md from issue no: #45729

### CODE REVIEW

**Comment by asem-hamid** [comment]
@MRH-Romit  , are you still working on this task? Please let me know; otherwise, I will close this PR and unassign you.

Since we now have our new working branch `dev-1.31-bn.1`, you'll need to create a fresh PR with the following details:

- **Source repo**: `kubernetes/website`
- **Source branch**: `dev-1.31-bn.1`
- **Target branch**: `dev-1.31-bn.1`

**Comment by MRH-Romit** [comment]
Sorry for the delay, i'll be working on it

**Pull request closed without merging**
