### PR TITLE
apply content_template

### LINKED ISSUE #9117: Issue with k8s.io/docs/tasks/debug-application-cluster/debug-pod-replication-controller/
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
1) Code examples in published docs have misformatted, "printing" quotes instead of original, single quotes. That makes this code unusable without manual fixing.

2) Code examples in published doc do not keep line endings.

Code in original .md file is correct:

https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/debug-application-cluster/debug-pod-replication-controller.md

Code published on page:
<p>kubectl get nodes -o yaml \| grep &lsquo;\sname\|cpu\|memory&rsquo;
--
  | kubectl get nodes -o json \| jq &lsquo;.items[] \| {name: .metadata.name, cap: .status.capacity}&rsquo;</p></li>
  | </ul>

**Proposed Solution:**

Get better md2html formatter as this creates harder to use doc (looks like the docs are broken)

**Page to Update:**
https://kubernetes.io/...

### PR DESCRIPTION
**Pull request by makocchi-git**
closes #9117

* change page title to `Debug Pods and ReplicationControllers`
* apply `content_template/task` instead of `content_template/concept`
* add overview and prerequisites
* apply code snippet formatting

### CODE REVIEW

**Comment by makocchi-git** [comment]
[check url is here](https://deploy-preview-9136--kubernetes-io-master-staging.netlify.com/docs/tasks/debug-application-cluster/debug-pod-replication-controller/)
[original](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-pod-replication-controller/)

**Comment by tengqm** [comment]
@makocchi-git, pls resolve the conflicts.

**Comment by makocchi-git** [comment]
@tengqm I got it. I will resolve soon.

**Comment by tengqm** [comment]
/lgtm
/approve
Thanks.

**Pull request merged**
