### PR TITLE
[ru] *main* Replace deprecated fullversion shortcode

### PR DESCRIPTION
**Pull request by rolfedh**
Fixes https://github.com/kubernetes/website/issues/41487 on the `main` branch.

### CODE REVIEW

**Comment by rolfedh** [comment]
Preview topics:
- https://deploy-preview-41492--kubernetes-io-main-staging.netlify.app/ru/docs/concepts/containers/container-environment/
- https://deploy-preview-41492--kubernetes-io-main-staging.netlify.app/ru/docs/setup/learning-environment/minikube/
- https://deploy-preview-41492--kubernetes-io-main-staging.netlify.app/ru/docs/tasks/tools/install-kubectl/

**Comment by rolfedh** [comment]
Related to https://github.com/kubernetes/website/issues/41005

**Review by sftim — COMMENTED** [review]
/lgtm

**Comment by shurup** [comment]
Thank you, @rolfedh!
/lgtm
/approve

**Pull request merged**
