### PR TITLE
Glossary for PersistentVolumeClaim added

### PR DESCRIPTION
**Pull request by varadaprasanth**
Added the glossary to PersistentVolumeClaim for a reference and better navigation.

### CODE REVIEW

**Comment by varadaprasanth** [comment]
@kbhawkey raised this new PR and incorporated the inputs. Please review the same.

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-20194--kubernetes-io-master-staging.netlify.com/docs/concepts/storage/volume-snapshots/

**Comment by sftim** [comment]
[Preview](https://deploy-preview-20194--kubernetes-io-master-staging.netlify.com/docs/concepts/storage/volume-snapshots/#persistent-volume-claim-as-snapshot-source-protection)

**Comment by varadaprasanth** [comment]
> (if there's an issue that this fixes, please update or close that issue)

@sftim  the earlier PR related to this had got closed already. No other open issue on this, Thank you

**Pull request merged**
