### PR TITLE
Fix typo in tasks/debug-application-cluster/local-debugging.md

### PR DESCRIPTION
**Pull request by bang9211**
from #36138

### CODE REVIEW

**Review by kundan2707 — COMMENTED** [review]
seems good to me

**Comment by mk46** [comment]
> from #36138

Could you please update this as `fixes #36138`? that will help to autoclose linked issue in this PR.
See step 7 in https://kubernetes.io/docs/contribute/new-content/open-a-pr/#open-a-pr.

**Comment by mk46** [comment]
> from #36138

Could you please update this as `fixes #36138`? that will help to autoclose linked issue in this PR.
See step 7 in https://kubernetes.io/docs/contribute/new-content/open-a-pr/#open-a-pr.

**Pull request merged**
