### PR TITLE
Add Swift client library

### PR DESCRIPTION
**Pull request by iabudiab**
This is a new client library in Swift, that I'm currently maintaining.

### CODE REVIEW

**Comment by iabudiab** [comment]
I've signed the CLA, and here's me testing the bot

/joke

**Review by Arhell — COMMENTED** [review]
Hi, you can check, the mail on github and cla must match.

**Comment by iabudiab** [comment]
@Arhell I signed in via GitHub account so emails should match. It is the same email address, in GitHub, commit signature, and now in https://identity.linuxfoundation.org

**Review by sftim — COMMENTED** [review]
/lgtm

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-25197--kubernetes-io-master-staging.netlify.app/docs/reference/using-api/client-libraries/#community-maintained-client-libraries

**Comment by kbhawkey** [comment]
Thanks @iabudiab .
/approve

**Pull request merged**
