### PR TITLE
[ja] Ready Hello, Minikube page for vanilla Docsy

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/45938/files

### CODE REVIEW

**Review by dipesh-rawat — COMMENTED** [review]
Change look in sync with 'en' PR https://github.com/kubernetes/website/pull/45938/files
LGTM

[Current Page](https://k8s.io/ja/docs/tutorials/hello-minikube) | [Preview Page](https://deploy-preview-46456--kubernetes-io-main-staging.netlify.app/ja/docs/tutorials/hello-minikube)

**Comment by Okabe-Junya** [comment]
Thank you!!

/assign nasa9084

**Review by Okabe-Junya — APPROVED** [review]
/lgtm

**Pull request merged**
