### PR TITLE
White stripe after footer fix

### PR DESCRIPTION
**Pull request by Arhell**
issue #19755

### CODE REVIEW

**Comment by onlydole** [comment]
Thank you for this fix, @Arhell 🎉 

/lgtm

**Comment by sftim** [comment]
@Arhell / @onlydole - can you explain what these changes do and why these changes are the right fix?

(if you can provide this kind of information in the PR description, it will mean that reviewing takes less time - and the smaller the amount of time a review takes, the more chance that reviewers / approvers can have of finding a slice of time big enough).

**Comment by Arhell** [comment]
Oh sure
Scroll down, after the footer a white stripe.
https://kubernetes.io/

This PR solves this problem.
https://deploy-preview-19825--kubernetes-io-master-staging.netlify.com/

**Comment by sftim** [comment]
@Arhell, some more questions
- do I need to use particular software to verify this fix?
- what have you already done to test it?
- how can we be sure this is the right way to fix the issue?

**Comment by Arhell** [comment]
Hello! @sftim 

- Found this problem in chrome.
- Checked on the desktop + mobile phone
- I looked at what gave such an effect, the styles built into the browser, I reset them.

**Comment by onlydole** [comment]
@sftim and @kbhawkey - is there anything more you'd like to see in this PR from @Arhell, or would you prefer it be closed for now?

**Comment by sftim** [comment]
Really I'm (still) not sure how to be confident that this fix makes the site better / that it's the right way to fix the symptom. A more thorough explanation would help there I think.

(CSS _is_ a bit like that).

**Comment by kbhawkey** [comment]
Hi. I only see a very small white strip on the page, between the footer and the end of the browser window.
It is very difficult to see the problem when viewing the docs from firefox (strip is tiny).
A very narrow strip is evident on chrome. Here is a screen capture:
white-strip-footer
Perhaps the problem is more obvious on a mobile browser (I viewed on my desktop).
I think we could defer to fix this for now.

**Comment by onlydole** [comment]
Apologies for the long back and forth, @Arhell! We’re going to close this PR for now and we may revisit later after we update to Docsy and implement some other UI/UX changes. 

/close

**Pull request closed without merging**
