### PR TITLE
Added Learnk8s Academy as online training offering

### PR DESCRIPTION
**Pull request by danielepolencic**
Added Learnk8s Academy as online training offering

### CODE REVIEW

**Comment by danielepolencic** [comment]
I signed it

**Comment by Rajakavitha1** [comment]
Thanks for your PR @danielepolencic !!!! Could you please list the course in the alphabetical order like the rest of the courses in the list.

**Comment by danielepolencic** [comment]
@Rajakavitha1 thanks for reviewing this :)
I made the change.

**Comment by Rajakavitha1** [comment]
Checked the updates at: https://deploy-preview-12737--kubernetes-io-master-staging.netlify.com/docs/tutorials/online-training/overview/
 nit: the rest of the online training academy are listed as [name of the course] (academy)

Would you want to add a specific course name?

**Comment by danielepolencic** [comment]
@Rajakavitha1 We offer one course only. Unlike the other platforms, we don't try to offer other courses. So I'm not sure it applies, but I changed it anyway.

Let me know if this looks better.

**Comment by Rajakavitha1** [comment]
Thanks for the PR @danielepolencic !!!
I checked the updates on : https://deploy-preview-12737--kubernetes-io-master-staging.netlify.com/docs/tutorials/online-training/overview/

/lgtm
/approve

**Pull request merged**
