### PR TITLE
[zh-cn]sync concepts/overview/_index.md

### PR DESCRIPTION
**Pull request by my-git9**
[zh-cn]sync concepts/overview/_index.md

### CODE REVIEW

**Comment by windsonsea** [comment]
Thanks.

/lgtm

**Review by Sea-n — COMMENTED** [review]
/approve

**Comment by Sea-n** [comment]
FYI, you can do this to keep trigger retest while keeping <kbd>lgtm</kbd> label.

```
git commit --amend --no-edit
git push -f
```

**Pull request merged**
