### PR TITLE
Update explore-intro.html

### PR DESCRIPTION
**Pull request by ruye-18**
群集 --> 集群

### CODE REVIEW

**Comment by tengqm** [comment]
Thanks.
/approve
/lgtm

**Comment by tengqm** [comment]
/approve cancel

Looks like we got a problem of CLA.

**Review by Arhell — COMMENTED** [review]
More info about CLA
https://github.com/kubernetes/website/pull/28548#issuecomment-865619081

**Comment by tengqm** [comment]
I'm closing this due to CLA issue open for too long. Please feel free to reopen when the agreement is signed.
/close

**Pull request closed without merging**
