### PR TITLE
[zh] Added kubernetes-cluster-architecture.svg in content/zh-cn/docs/concepts/_index.md

### PR DESCRIPTION
**Pull request by utkarsh-singh1**
Description:
Updated /docs/zh-cn/concepts/architecture/_index.md and added kubernetes-cluster-architecture.svg in /static/images/docs.

Page to Update:
https://kubernetes.io/docs/zh-cn/concepts/architecture/

### CODE REVIEW

**Comment by utkarsh-singh1** [comment]
Hi @ydFu, Please review this PR.

**Comment by windsonsea** [comment]
Is any special for zh-cn to have this svg? The en upstream has nothing image included: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/architecture/_index.md

Normally, we need to follow the en upstream. Maybe, you shall add this image into en version first.

**Comment by sftim** [comment]
We shouldn't make this change, because we're adding a new English diagram and changing Chinese content.

SIG Docs strongly prefers PRs that can be reviewed by reviewers who speak a single language.

**Comment by windsonsea** [comment]
Please change the en upstream first. This will be closed.

**Pull request closed without merging**
