### PR TITLE
i18n/ko.toml added kubeweekly's contents

### PR DESCRIPTION
**Pull request by ClaudiaJKang**
#12873's updated contents added i18n/ko.toml.

### CODE REVIEW

**Comment by gochist** [comment]
As a native Korean speaker, LGTM.

**Comment by ClaudiaJKang** [comment]
@cody-clark ping?

**Comment by cody-clark** [comment]
Hi @ClaudiaJKang, sorry for the delay. I'm not a ko-owner, but I didn't hear back in the Slack. I'll go ahead and try to to approve this to not be a blocker. 

/lgtm
/approve

**Comment by zacharysarah** [comment]
@cody-clark Good call. 👍

**Comment by ClaudiaJKang** [comment]
@cody-clark  Thank you!

**Pull request merged**
