### PR TITLE
PR for diff docs

### PR DESCRIPTION
**Pull request by apelisse**

### CODE REVIEW

**Comment by tfogo** [comment]
Hi @apelisse, was there a reason you closed this?

**Comment by apelisse** [comment]
@tfogo Not sure what happened ... :-)

**Comment by tfogo** [comment]
Hi @apelisse, can you please complete this PR as soon as you can? The docs deadline is approaching fast and we want to start reviews ASAP.

**Comment by AishSundar** [comment]
@apelisse @jennybuckley the deadline to merge all docs PR is tomorrow, 11/27. Do you think you can get this PR merged by then?

**Comment by tfogo** [comment]
@apelisse @jennybuckley Can you please add any reviewers you would like?

My one point on this is can you please mention the feature state of kubectl diff in the docs? Thanks!

**Comment by Bradamant3** [comment]
@apelisse we're getting down to the wire with the release, but if you could add this information also to the following pages, that would be great (the current PR is excellent -- please add, don't replace):

- https://kubernetes.io/docs/reference/kubectl/overview/
- https://kubernetes.io/docs/reference/kubectl/kubectl/

Thanks!

**Comment by apelisse** [comment]
thanks @Bradamant3, I'm on it!

**Comment by tfogo** [comment]
@Bradamant3 correct me if I'm wrong but I believe https://kubernetes.io/docs/reference/kubectl/kubectl/ is generated so @apelisse should only need to edit https://kubernetes.io/docs/reference/kubectl/overview/?

**Comment by apelisse** [comment]
I've updated the overview, thanks

**Comment by Bradamant3** [comment]
@apelisse thanks, and thanks also to @tfogo for catching my misstep with the generated doc.

still needs tech review -- please add appropriate reviewer?

**Pull request merged**
