### PR TITLE
Mark PSP deprecated in the docs

### PR DESCRIPTION
**Pull request by tallclair**
See https://github.com/kubernetes/kubernetes/pull/97171

### CODE REVIEW

**Comment by pweil-** [comment]
lgtm (but not signing off since I'm not active)

Thanks @tallclair!  Good to see the new proposals the sig was discussing to replace PSP.

**Comment by tallclair** [comment]
Question for website maintainers - should this go in the v1.21 branch? Since the deprecation is already committed, I think it's valuable to indicate that the deprecation is coming sooner rather than later. I suppose it could technically still be rolled back, but I think that's extremely unlikely.

**Comment by kbhawkey** [comment]
> 
> 
> Question for website maintainers - should this go in the v1.21 branch? Since the deprecation is already committed, I think it's valuable to indicate that the deprecation is coming sooner rather than later. I suppose it could technically still be rolled back, but I think that's extremely unlikely.

Hi @tallclair . 
When was the feature deprecated (after v1.20.0)?
I suggest to create this change in the `dev-1.21` branch.

**Comment by tallclair** [comment]
Done: https://github.com/kubernetes/website/pull/26581

**Pull request closed without merging**
