### PR TITLE
IPv6: Updating doc related to IPv6.

### PR DESCRIPTION
**Pull request by pmichali**
Made updates for files, related to IPv6 to address issue 7566. Note: The release notes
cover 1.9. When 1.10 release notes are added, the comment about
the /66 restriction for IPv6 can be removed.

### CODE REVIEW

**Comment by pmichali** [comment]
Not sure if I did this right (first doc push)...

- How do I set the milestone?
- Should I have pushed this change on the release-1.10 branch (just saw that in the comment template)?
- How do I associate this with Issue 7566?

**Comment by Bradamant3** [comment]
@pmichali this looks fine -- thank you for your contribution! But based on your questions here and in Slack, some follow-up questions:
- It looks as though the IPv6 restriction is current -- that is, it applies to v1.9? If this is correct, then a PR to master is the way to go. If the restriction will be lifted in v1.10, then please submit another PR after this one is merged, to the 1.10 branch, to remove the text about restrictions.
- OR -
- The lazy approach would be to close this PR unmerged IFF the IPv6 restriction is lifted for 1.10, because the release is schedule for less than three weeks from now.
- The milestones are listed to the right of the comments, in the column that also includes reviewers and approvers. But you don't need to set the milestone if this PR is to master. You would set it in a PR to the 1.10 branch.
- You associate a PR with an issue by prepending the hashtag, thus: #7566 
- Release notes are tracked separately, either in comments to code PRs or in another markdown doc. Flagging @nickchase who's managing release notes for 1.10, to see how he'd like to do things.
/assign

**Comment by pmichali** [comment]
OK, this is targeted for the 1.10 release (we're trying to make sure doc is ready for 1.10 as well as code to go to beta, from alpha). Although, the changes made, apply to 1.9.

Should I be rebasing this on release-1.10 branch?

Regarding the /66 comment in release notes. It is correct, as-is for 1.9, but will be lifted for 1.10 (so the 1.10 release notes should no longer have this comment).

**Comment by Bradamant3** [comment]
If the changes apply to 1.9 also, then the PR to master is fine -- this means that the doc will be updated as soon as we merge it.
@thockin @bprashanth tech review please?

**Comment by heckj** [comment]
@pmichali please rebase this PR to the `release-1.10` branch (edit the PR and change the target branch from `master` to `release-1.10`) and we'll get this included!

**Comment by pmichali** [comment]
@heckj Sure I can do the rebase, but was wondering, since the changes apply to 1.9 as well should it be merged into master instead of, or in addition to 1.10?

Just let me know what actions are needed, and I can do the steps.

**Comment by heckj** [comment]
@pmichali since the updates are equally relevant and correct for the current release, we'll just merge this to master!

**Comment by pmichali** [comment]
@heckj Thanks!

**Pull request merged**
