### PR TITLE
[ko] 8th Korean l10n work for release-1.20

### PR DESCRIPTION
**Pull request by seokho-son**
8th Korean l10n work for release-1.20

Consists of following contributions ([is:pr base:dev-1.20-ko.8 is:merged](https://github.com/kubernetes/website/pulls?q=is%3Apr+base%3Adev-1.20-ko.8+is%3Amerged+))

- [ko] Update outdated files in dev-1.20-ko.8 (p3)  #27901 by @jihoon-seo 
- [ko] Update outdated files in dev-1.20-ko.8 (p2)  #27760 by @jihoon-seo 
- [ko] Update outdated files in dev-1.20-ko.8 (p1)  #27728 by @jihoon-seo 

Reviewed by @kubernetes/sig-docs-ko-reviews

### CODE REVIEW

**Comment by jihoon-seo** [comment]
This PR resolves #27491.

**Comment by seokho-son** [comment]
@gochist 확인 및 승인 가능하실까요~? ^^

**Pull request merged**
