### PR TITLE
Update team membership for current best practices

### LINKED ISSUE #20488: OWNERS_ALIASES cleanup
## Repo groups are out of alignment with current best practices

The [`website-maintainers`](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L160) group in OWNERS_ALIASES is a historical artifact with no permissions associated with it. 

## How to fix it

Remove the `website-maintainers` team from OWNERS_ALIASES.

I'm also proposing to update the description of `sig-docs-leads` from "Website admins" to "Website chairs and tech leads" and add @kbhawkey, @onlydole, and @sftim to the group.

For more information, see https://github.com/kubernetes/website/pull/20109#issuecomment-617430190. 

## Tangential issues

We need to update the [`website-admins` team in k/org](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml#L276) to replace @Bradamant3 with @kbarnard10. I propose continuing to limit repo admin access to current chairs.

/assign @jimangel @kbarnard10

### PR DESCRIPTION
**Pull request by zacharysarah**
Fixes #20488 

/assign @kbhawkey @onlydole @sftim 
/cc @jimangel @kbarnard10

### CODE REVIEW

**Comment by onlydole** [comment]
Thank you, @zacharysarah - this looks good to me! 

/lgtm

**Comment by zacharysarah** [comment]
For the `@kubernetes/sig-docs-leads` alias to work in issues and PRs, we'll need to [create a team with that name](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml) in k/org. I'll include that as part of the membership update (see #20488).

**Comment by onlydole** [comment]
/lgtm
👍

**Comment by jimangel** [comment]
This `/lgtm` but I would like to validate the team exists before merging.

**Comment by zacharysarah** [comment]
@jimangel @kubernetes/sig-docs-leads 

The notification so nice, you got it twice! 👯 

dancing

**Pull request merged**
