### PR TITLE
Update korean pick right solution solves issue #14479

### PR DESCRIPTION
**Pull request by jhbiggs**
Hi,

This issue is in reference to good-first-issue #14479.  I removed the broken links and set them to refer to their own pages.  I understand this issue may be moot, but it was fun to tease through the site in Korean.  I hope it's helpful to you.

### CODE REVIEW

**Comment by sftim** [comment]
Thanks for the pull request @jhbiggs.

It looks like you have [included](https://github.com/kubernetes/website/pull/15130/commits/246ea853f108e581b0be5d041fa201b756e2ee2f) some changes to the English language documentation as well. I wonder if that was by mistake?

**Comment by jhbiggs** [comment]
Whoops.  My rebasing skills have a little way to go.  I will take out the en commit.

**Comment by gochist** [comment]
@jhbiggs Thank you! Please resolve conflict.

**Comment by jhbiggs** [comment]
Ok, done.  I took out the line whose link I had updated because it didn't appear at all in the English version.

**Comment by gochist** [comment]
@jhbiggs Thank you!
@kubernetes/sig-docs-ko-owners  The base branch of this PR is not our current team milestone branch, `dev-1.15-ko.1` or `dev-1.14-ko.6`. But I think it can be merged to the master directly as it is a bug obviously.   If you agree, please give an approval.

/lgtm

**Pull request merged**
