### PR TITLE
Update mermaid diagram to svg image

### LINKED ISSUE #32420: Mermaid diagram on Authenticating page is unreadable
The mermaid diagram in the https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens section is unreadable. The text is overlapping. That might be dependent on your screen width, i guess. But it doesn't render properly on a regular 15" MBP.

Here is a screenshot - 
image

@sftim rightly pointed out that I have a user css applied (Dark Reader chrome plugin). I tried to get a screenshot with the plugin turned off but I haven't been able to reproduce.

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #32420

### CODE REVIEW

**Comment by chrismetz09** [comment]
@championshuttler, diagram looks good. Tx for plugging in the live editor link as a comment in the .md file.

**Comment by reylejano** [comment]
See my comment on the related issue as I'm not able to replicate what this PR solves
https://github.com/kubernetes/website/issues/32420#issuecomment-1075684187

**Comment by sftim** [comment]
For me, the SVG image uses the wrong colors. Compare https://deploy-preview-32423--kubernetes-io-main-staging.netlify.app/docs/reference/access-authn-authz/authentication/#openid-connect-tokens to https://k8s.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens (which also uses the wrong colors, in that the text that's on a blue background should actually be white).

LGTM but with a caveat that it's not 100% the right fix.

**Comment by sftim** [comment]
My screenshot of the “before” rendering, using Mermaid locally:
Screenshot

**Comment by sftim** [comment]
Hi @championshuttler 

Would you be willing to fix that SVG image so that it uses the right colors?

**Comment by Sea-n** [comment]
Hey @championshuttler,

There are some comments you haven't replied yet. We are closing stale Pull Requests to maintain a clean project.

Feel free to `/reopen` when you are ready to move forward.
/close

**Pull request closed without merging**
