### PR TITLE
Mark KMSv2 and KMSv2KDF feature gates as removed

### PR DESCRIPTION
**Pull request by aramase**
Mark KMSv2 and KMSv2KDF feature gates as removed

fixes https://github.com/kubernetes/kubernetes/issues/126859

### CODE REVIEW

**Comment by tamilselvan1102** [comment]
page preview: https://deploy-preview-47621--kubernetes-io-main-staging.netlify.app/docs/reference/command-line-tools-reference/feature-gates-removed/

**Review by dipesh-rawat — COMMENTED** [review]
/approve

**Pull request merged**
