### PR TITLE
[pt-br] Update deploy-intro tutorial

### PR DESCRIPTION
**Pull request by stormqueen1990**
### Changes
* Update the deploy intro tutorial to both reflect the latest English version and remove references to Katacoda.

### CODE REVIEW

**Comment by MrErlison** [comment]
Hello @stormqueen1990! 

Thank you very much for your contribution! Great job!

/lgtm

/cc @devlware

**Review by jcjesus — APPROVED** [review]
Well done @stormqueen1990!
Thanks

**Pull request merged**
