### PR TITLE
Update apiversion of deployment in v1.9

### LINKED ISSUE #6990: Issue with k8s.io/docs/tasks/run-application/run-single-instance-stateful-application/
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Deployment yaml file:
mysql-deployment.yaml api version does not fit 1.9 version:
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment

**Proposed Solution:**
change apiVersion to: apps/v1

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

Kubernetes Version:
1.9
apiversionupdate_docs

### PR DESCRIPTION
**Pull request by islinwb**
fix #6990 

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6992)

### CODE REVIEW

**Comment by tengqm** [comment]
Thanks. We surely should encourage users to use the GA version.

**Comment by steveperry-53** [comment]
@islinwb @tengqm Time out. I'm not sure the statements in this PR are correct.
This statement, "For versions before 1.9.0 use apps/v1beta2", seems to say that I should use apps/v1beta2 for any version prior to 1.9.0. That says I should use apps/v1beta2 for 1.8, 1.7, 1.6, 1.5, etc. But I don't think apps/v1beta2 exists for all those earlier versions.

**Comment by islinwb** [comment]
@steveperry-53 @tengqm  The statement  "For versions before 1.9.0 use apps/v1beta2" is not strict indeed. I copied this statement from the yaml in [this page](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) . And there are similar statements in some older versioned docs: 
```
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
```
Shall we just remove "# for versions before 1.6.0 use extensions/v1beta1" or add more comments referring to different older versions?

**Comment by steveperry-53** [comment]
@islinwb @tengqm Yes, I'm sure there are similar statements elsewhere in the current and older docs. But I don't want track them down right now. For this PR, I think we should do one of two things:

* Option 1: Delete the comment about prior versions.
* Option 2: For version 1.8, use apps/v1beta2.

**Comment by tengqm** [comment]
@steveperry-53 Yes, I agree to your opinion. I'd vote for removing the comment to avoid possible confusion. If we add info for 1.8, a few months later, we have to remove it again because ... it is no longer supported. For old versions of deployments, we can always point users to the old docs. At the same time, we keep the master fresh.

**Pull request merged**
