### PR TITLE
Bump up Deployment version in cn concepts/overview/working-with-objec…

### PR DESCRIPTION
**Pull request by nashasha1**
I am creating a bunch of PRs for bumping up deployment version. A pr contains all changes in a folder.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7351)

### CODE REVIEW

**Comment by heckj** [comment]
Hey @nashasha1 - thanks for waiting and apologies for the delay in getting back to you. We discussed the topic in the SIG Docs meeting and came to consensus on how to represent the versioning for examples, and what needs to be done when versions are updated. I posted this information to the SIG Docs mailing list just a few seconds ago, and it's also been included in the style guide at https://kubernetes.io/docs/home/contribute/style-guide/#versioning-kubernetes-examples

Could you please review that recommendation and update these PRs to include min-kubernetes-server-version in the front-matter of the various documents? If that doesn't make sense, or you have questions, please don't hesitate to ask.

**Comment by steveperry-53** [comment]
@nashasha1 Changes to the cn content are done by the translation team in the kubernetes/kubernetes-docs-cn repo. So we don't take direct changes to cn content here in the kubernetes/website repo. Thanks.

**Comment by heckj** [comment]
@nashasha1 I'm going to go ahead and close these PRs for kubernetes/website - would love to have the same content applied to kubernetes/kubernetes-docs-cn

**Pull request closed without merging**
