### PR TITLE
[ja] fix typo cluster-level-pss.md

### PR DESCRIPTION
**Pull request by mmmommm**
fix typo in ja document page `cluster-level-pss.md`

### CODE REVIEW

**Comment by dipesh-rawat** [comment]
@mmmommm Thanks you for your contribution.
Could you please sign the CLA before the PR can be reviewed.
You can follow the steps documented here: https://git.k8s.io/community/CLA.md

**Review by dipesh-rawat — COMMENTED** [review]
/easycla

**Comment by mmmommm** [comment]
@dipesh-rawat 
I have signed the CLA. Could you please check again?

**Comment by Okabe-Junya** [comment]
Thank you for your contribution and catching up typo!!

/lgtm
/assign nasa9084

**Comment by nasa9084** [comment]
Thank you for your first contribution, welcome~
/approve

**Pull request merged**
