### PR TITLE
better alignment in yaml files - tested

### PR DESCRIPTION
**Pull request by aysabzevar**
Just a few improvements on yaml indentation in example files.

### CODE REVIEW

**Comment by aysabzevar** [comment]
Tested after changes.

**Comment by tengqm** [comment]
I don't think this is an improvement. Indentation of list is a personal preference, rather than a syntax requirement. My preference is the existing style, i.e. explicitly indent list members, for readability's sake.

**Comment by aysabzevar** [comment]
Starting a list with the same indentation as the parent improves visualization. As far as I've seen, most of Kubernetes documentations follow that rule (i.e. https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/#schedule-a-pod-using-required-node-affinity) , but I found this one violates it and started the lists with the indentations.

**Comment by aysabzevar** [comment]
The indentation I suggested, is the one that you get when you execute **kubectl get command with -o yaml** option.

For example:

kubectl run nginx --image=nginx && kubectl get pod/nginx -o yaml

So, it improves it to be better aligned with the internal yaml formatting of kubernetes.

**Comment by tengqm** [comment]
@aysabzevar I'm aware of the variants of the list format. However, I do believe an extra indentation helps improve readability.
To me, the following format is "good", because the list items are indented as children of `bar`.

```yaml
foo:
   bar:
    - name: joe
      role: op
    - name: doe
      role: admin
```

But the following format is valid but not so clear, because the list items looks like siblings of `bar`.

```yaml
foo:
   bar:
  - name: joe
    role: op
  - name: doe
    role: admin
```

**Again, this is a personal preference rather than a hard requirement. Just like some people may prefer 2 spaces for indentation, while others may prefer 4 spaces. It is not a right-or-wrong issue.**

**Comment by bradtopol** [comment]
Assigning @tengqm since he is already engaged on this.  
Also, just an FYI. @aysabzevar If this eventually gets accepted you will need to break it up into multiple PRs.  We don't permit a single PR to update multiple localizations.  That causes our localization teams problems when you do that.
/assign @tengqm

**Comment by reylejano** [comment]
Hi @aysabzevar , this PR has no progress in the past 33 days and needs to be broken into separate PRs for each localization: en, ko, zh.
Feel free to open separate PRs for each localization.

/close

**Pull request closed without merging**
