### PR TITLE
Remove Travis CI dependency

### PR DESCRIPTION
**Pull request by lucperkins**
This PR removes the need for Travis CI in the build pipeline, running everything on Netlify CI instead

### CODE REVIEW

**Comment by zacharysarah** [comment]
@lucperkins This will need a follow-up PR in [k/test-infra](https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L215).

**Comment by lucperkins** [comment]
@zacharysarah FYI: https://github.com/kubernetes/test-infra/pull/12050

**Comment by fejta** [comment]
What is the advantage of netlify over prow?

**Comment by lucperkins** [comment]
@fejta None, really. There’s just no need for Prow/Travis when all of our CI workloads can be on Netlify rather than split across multiple platforms. We have hundreds of contributors across an expanding range of language communities, and anything we can do to reduce the per-PR cognitive burden of contributing is a small win.

**Comment by fejta** [comment]
Running everything on a single system makes sense for sure.

Prow is built by the community and the most commonly used CI system, so if you're going to pick a single system for your workloads, all things being equal I would recommend using that over Netlify.

**Comment by lucperkins** [comment]
@fejta Prow was not, however, used to build and deploy websites

**Comment by fejta** [comment]
Prow has a good gitops story. It will trigger arbitrary kubernetes pod workflows in response to git events. These building blocks will compose into a decent CD system.

For example, over in test-infra we use prow to github events and:
* [Publish new images at each commit](https://testgrid.k8s.io/sig-testing-prow#push-prow)
* [Create daily PRs requesting to update to these latest images](https://github.com/kubernetes/test-infra/pull/12044)
* [Update deployments to use these new images when the PR merges](https://testgrid.k8s.io/sig-testing-prow#deploy-prow)

Similarly, I suspect we can use kubernetes pods to deploy the kubernetes websites. Long-term this would seem an interesting space to explore.

**Comment by lucperkins** [comment]
@fejta Netlify is a fully featured web publishing platform that offers Kubernetes ecosystem projects an enormous feature set, including per-PR deploy previews, cache invalidation, global CDN delivery, support for numerous build tools, file-based redirects, and much more. I think it would be unwise to attempt to recreate this feature set in *any* system.

**Comment by tengqm** [comment]
Conclusions?

**Comment by lucperkins** [comment]
@tengqm The original intent behind the PR stands

**Comment by zacharysarah** [comment]
P.S. Comedy gold:

Screen Shot 2019-04-11 at 1 36 50 AM

**Pull request merged**
