### PR TITLE
Update _index.md

### LINKED ISSUE #17125: Improvement for kubernetes.io/de/docs/concepts/
**This is a Bug Report**

**Problem:**
the german translation could be more sophisticated

**Proposed Solution:**
gerna translation based on the corresponding english version

**Page to Update:**
https://kubernetes.io/de/docs/concepts/

Kubernetes Version:
1.16

### PR DESCRIPTION
**Pull request by bscheller-iso**
rework of the german translation based on the english version
fixes #17125

### CODE REVIEW

**Comment by rlenferink** [comment]
Hi @bscheller-iso, thanks for submitting this PR. Can you please sign the CNCF CLA? After that I’ll have a look at your PR.

Instructions on how to submit the CLA are described above ;)

**Comment by bscheller-iso** [comment]
Hello, I signed the CNCF CLA.

**Comment by rlenferink** [comment]
@bscheller-iso it looks like the CLA is not picked up then. Are you sure the e-mail for the commit is the same as the one used to sign the CLA? If so, the CLA guide has the following procedure:

> ### 7. My pull request still doesn't pass!

> If you haven't yet, post a comment ("I signed it") to the PR—this is needed for the system to recheck your contribution authorization.

> Each commit in the pull request needs to pass. If you have commits that didn't attribute to a Github username, or to a different user that hasn't signed the CLA, that will fail that commit and all subsequent commits.

> If that does not help, please submit a [support request](https://jira.linuxfoundation.org/servicedesk/customer/portal/4/create/88).

**Comment by bscheller-iso** [comment]
I signed it

**Comment by rlenferink** [comment]
/lgtm
@bene2k1 I’ll leave approval to you

**Pull request merged**
