### PR TITLE
Official 1.24 Release Docs

### PR DESCRIPTION
**Pull request by nate-double-u**
## :stop_sign: **DO NOT MERGE** :stop_sign: **UNTIL KUBERNETES 1.24 IS RELEASED**
Target date: ~2022-04-19~ 2022-05-03

### Release deadlines
(from [sig-release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.24#timeline))

Date | Description
-- | --
March 31, 2022 | Open Placeholder PRs
April 5, 2022 | PRs ready for review
April 12, 2022 | All PRs reviewed and ready to merge

Contact: @nate-double-u, @chrisnegus, @didicodes, @mehabhalodiya, @PI-Victor 

/hold
/milestone 1.24

### CODE REVIEW

**Comment by sftim** [comment]
@nate-double-u it looks like _another_ dev branch update would be useful, already

**Comment by nate-double-u** [comment]
I'll open another PR today. Thanks @sftim.

**Comment by nate-double-u** [comment]
> @nate-double-u it looks like _another_ dev branch update would be useful, already

https://github.com/kubernetes/website/pull/32305

**Comment by jimangel** [comment]
Hey there! @nate-double-u, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by sftim** [comment]
Tsk! @nate-double-u :wink:

**Comment by jimangel** [comment]
> @jimangel brings up a good point

Shout out to automation and https://github.com/zparnold/k8s-docs-pr-botherer 😄 

> I've signed the CLA, but I think that this PR/release cycle was started before not signing was a blocker for merging so there are a few individual commits without a valid CLA.

This could be the case, however, I do want to bring up an old thread where we had a commit force pushed that had a non-CLA signed signature and how we resolved it: https://kubernetes.slack.com/archives/C1J0BPD2M/p1588704907427600

I'm not sure we're dealing with the same thing, but I think the context might help...

**Comment by sftim** [comment]
What I think has happened here is that there are commits that were accepted by the previous CLA bot but aren't acceptable to the new CLA bot, and some of those commits landed on the _dev-1.24_ branch before the new CLA bot was in enforcing mode.

_BUT_ I haven't verified this suspicion.

**Comment by nate-double-u** [comment]
I've been having a conversation about the CLA issues in the CNCF #easycla slack that's worth sharing here:
https://cloud-native.slack.com/archives/CK8QVEXQB/p1651163657532939

**Comment by nate-double-u** [comment]
Based on the conversation linked above, we plan to deal with the easyCLA issues by:
* verifying that the commits that EasyCLA doesn't like do in fact have a CLA, checked by the old bot
* `/lgtm` and `/approve` as expected on release day
* having the release docs lead use their power to merge the PR manually (_which they do **anyway**, because they have to bypass a repo freeze_)

Noting that we should add a comment to the PR to document the decision to bypass the normal easyCLA process.

(paraphrased from [Tim's suggestion](https://cloud-native.slack.com/archives/CK8QVEXQB/p1651185347783249?thread_ts=1651163657.532939&cid=CK8QVEXQB))

Please correct me if I've misunderstood the plan here @sftim, @mrbobbytables, @dims.

**Comment by PI-Victor** [comment]
i went through all the failed tests, and it looks to me like they're all related to the CLA and not a real issue.
then i had a looked at the deployed website, and checked stuff like the generated API ref docs: e.g. CSIStorageCapacity to v1 https://deploy-preview-31225--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.24/#csistoragecapacity-v1-storage-k8s-io
and then i checked node graceful shutdown https://deploy-preview-31225--kubernetes-io-vnext-staging.netlify.app/docs/concepts/architecture/nodes/#non-graceful-node-shutdown

and then i checked kubeadm init with feature gates for example https://deploy-preview-31225--kubernetes-io-vnext-staging.netlify.app/docs/reference/setup-tools/kubeadm/kubeadm-init/#feature-gates

i think we're good, whenever anyone else has the chance, please give this another look, thanks!

/lgtm

**Comment by PI-Victor** [comment]
re-applying 
/lgtm

**Comment by nate-double-u** [comment]
let's try this again
/remove-hold

**Pull request merged**
