### PR TITLE
Generate single-page API reference for 1.24

### PR DESCRIPTION
**Pull request by nate-double-u**
Generated assets for single-page API reference for 1.24 release.

### CODE REVIEW

**Comment by nate-double-u** [comment]
deploy preview: https://deploy-preview-33239--kubernetes-io-vnext-staging.netlify.app/docs/reference/generated/kubernetes-api/v1.24/

**Comment by nate-double-u** [comment]
I think this looks generally correct.

/cc @sftim @tengqm @reylejano @jlbutler

**Comment by nate-double-u** [comment]
/cc @kbhawkey
(sorry, meant to include you in the first set of ccs, but it doesn't look like github tags folks on edits)

**Comment by sftim** [comment]
I agree with the intent of the change and a quick look at the preview suggests it's right.
/approve

/hold
to allow reviewers a chance to point out errors. Lazy consensus and one /lgtm are enough grounds to unhold.

**Comment by nate-double-u** [comment]
/remove-hold

Thanks everyone!

**Pull request merged**
