### PR TITLE
Update resource-metrics-pipeline.md

### PR DESCRIPTION
**Pull request by redopalfruit**
Updated git repository URLs as the original ones are giving 404 errors

### CODE REVIEW

**Comment by redopalfruit** [comment]
I signed it!

**Comment by redopalfruit** [comment]
CLA check

**Comment by redopalfruit** [comment]
check

**Comment by jimangel** [comment]
@redopalfruit please rebase when time permits. Thanks!

**Comment by kbhawkey** [comment]
Thanks @redopalfruit for opening this pull request.
To go forward, this PR needs to be _rebased_.
https://kubernetes.io/docs/contribute/new-content/new-content/#merge-conflicts-and-rebasing

**Pull request closed without merging**
