### PR TITLE
Update apiVersion to apps/v1 for tasks/debug-application-cluster

### PR DESCRIPTION
**Pull request by liubin**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7336)

### CODE REVIEW

**Comment by heckj** [comment]
Could you please review that recommendation and update these PRs to [include min-kubernetes-server-version in the front-matter of the various documents](https://kubernetes.io/docs/home/contribute/style-guide/#versioning-kubernetes-examples)?

**Comment by zacharysarah** [comment]
@liubin 👋 We've migrated the site's framework to Hugo. Please re-open this PR with changes to files in their post-migration location (`/content/en/docs/...`).

**Pull request closed without merging**
