### PR TITLE
[zh-cn] Fix typo in zh-cn/docs/tasks/administer-cluster/topology-manager.md

### PR DESCRIPTION
**Pull request by saintube**
Fix a typo in the page [topology-manager/#policy-single-numa-node](https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/topology-manager/#policy-single-numa-node).

### CODE REVIEW

**Comment by saintube** [comment]
/assign @ydFu
PTAL

**Review by windsonsea — COMMENTED** [review]
Thanks. This file has [no changes in en upstream recently](https://github.com/kubernetes/website/commits/main/content/en/docs/tasks/administer-cluster/topology-manager.md) and no insync content.

/approve

**Review by ydFu — APPROVED** [review]
Fixed the typo,thanks.

/approve

**Pull request merged**
