### PR TITLE
Cherrypick PR #6417 to 1.7

### PR DESCRIPTION
**Pull request by msau42**
/assign @jsafrane

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6828)

### CODE REVIEW

**Comment by heckj** [comment]
thanks for the update @msau42 but as a general pattern we're not attempting to back-port updates to previous releases for the documentation. Is there an extenuating circumstance where you or @jsafrane think we should make an explicit exception?

**Comment by msau42** [comment]
Nothing extreme.  It's just these doc updates were missed initially.

**Pull request closed without merging**
