### PR TITLE
Securing a Cluster: Remove before you begin section

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by surajssd** [comment]
I see following error in the output https://deploy-preview-13857--kubernetes-io-master-staging.netlify.com/docs/tasks/administer-cluster/securing-a-cluster/

How do I get rid of this error?

Screenshot from 2019-04-17 16-45-46

**Comment by kbhawkey** [comment]
@surajssd, the error message on the rendered page indicates that the template requires a `prerequisites` section.

**Comment by sftim** [comment]
@surajssd, can you outline your motivation here? I want to help make reviewers have an easy time in verifying how well these changes line up with your intent.

**Comment by Bradamant3** [comment]
@sftim thanks very much for your question, but as @kbhawkey correctly notes, the section is required by the template for this entire part of the website. It's possible that the content belongs elsewhere, using a different template, but that's a different solution. Closing this PR because it's not actionable. @surajssd probably the best approach is for you to file an issue that explains what you think this page should do, and sig-docs can figure out an implementation. Thanks for understanding!

**Pull request closed without merging**
