### PR TITLE
link not valid

### PR DESCRIPTION
**Pull request by busyboy77**
link mentioned was not working, got 
```
[root@devops230 ~]# kubectl apply -f https://k8s.io/examples/application/nginx/
error: unable to read URL "https://k8s.io/examples/application/nginx/", server reported 404 Not Found, status code=404
```

### CODE REVIEW

**Comment by reylejano** [comment]
We should keep that a directory can be used
This still works when I have k/website cloned locally and change the `kubectl apply -f <path-to-dir>` accordingly
I'll try to have a better suggestion so that we keep the content and a working example with using a directory with `kubectl apply -f`

**Comment by Shubham82** [comment]
> We should keep that a directory can be used
> This still works when I have k/website cloned locally and change the kubectl apply -f <path-to-dir> accordingly
> I'll try to have a better suggestion so that we keep the content and a working example with using a directory with kubectl apply -f
> 

I agree with @reylejano, we can't remove it, there is some issue with the link. 

Can we use another example other nginx from /content/en/examples/application/ but in that case we have to change the whole page because it uses nginx as an example for the Managing Resources page.

Is there any way to fix this link? If ye, then it is better to change the nginx example

WDYT @reylejano @busyboy77 ?

**Comment by tengqm** [comment]
Maybe we can advise users to clone the repo and then provide a local path to the `kubectl` command.

**Comment by tengqm** [comment]
I gave it a second thought. Removing the incorrect instructions is appropriate anyway.
/lgtm
/approve

**Pull request merged**
