### PR TITLE
How You Can Help Localize Kubernetes Docs

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR adds a blog post on how to help localize Kubernetes docs.

/assign @kbarnard10

### CODE REVIEW

**Comment by daminisatya** [comment]
This is much needed 😄

**Comment by raelga** [comment]
Great post!

**Comment by Rajakavitha1** [comment]
Thank you!!!!
This is awesome!!!!

**Comment by zacharysarah** [comment]
@kbarnard10 👋 Ping

**Pull request merged**
