### PR TITLE
ko-trans: add concur/..., zulily/..., comcast/..., yahoo-japan/...

### PR DESCRIPTION
**Pull request by xichengliudui**
ko-trans:  add concur/..., 
ko-trans:  add zulily/..., 
ko-trans:  add comcast/..., 
ko-trans:  add yahoo-japan/...

### CODE REVIEW

**Comment by markthink** [comment]
@xichengliudui 参考：https://github.com/k8smeetup/k8s-official-translation
为更好的协作，需要统一任务领取..

**Comment by xichengliudui** [comment]
@markthink  请问怎么加入 k8smeetup 组织，我刚刚注册了 Slack，谢谢

**Comment by gochist** [comment]
@xichengliudui  :wave: Thank you for your contribution! As @chenrui333 has pointed out. Currently ko i18n/l10n team is working on the `dev-1.13` branch for new features (such as newly translated pages). And if there's bugs such as typo in the released website, it is fixed onto the `master` branch and they are eventually applied to the long running branch. 

In this case, it looks like new features, so please change the base branch to `dev-1.13-ko.2` which is the current working branch of ko team.

/hold

**Comment by xichengliudui** [comment]
@gochist  Thanks for reminding me. I'm working on it

**Pull request closed without merging**
