### PR TITLE
check-service-exists

### PR DESCRIPTION
**Pull request by mietnik**
Following tutorial step by step at this point service is not defined.

### CODE REVIEW

**Comment by network-charles** [comment]
Do we need to check if the service exists again? Considering we've already scaled our application in a previous tutorial as specified in the section on the page titled "Updating an application," it seems redundant to me. What are your thoughts, @divya-mohan0209 and @natalisucks?

**Review by divya-mohan0209 — COMMENTED** [review]
Thanks!
/approve

**Pull request merged**
