### PR TITLE
update documentation for metrics now that code freeze is in effect

### PR DESCRIPTION
**Pull request by logicalhan**
Metrics have been added since the last time I updated this file and when code freeze went into effect. This commit resolves that delta.

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Thanks

/sig instrumentation
/approve

**Review by dashpole — APPROVED** [review]

**Comment by sftim** [comment]
Oops, this merged too early. I think we should revert it and then apply a similar change to the _dev-1.26_ branch.

**Pull request merged**
