### PR TITLE
Added "Overview of Kubernetes Architecture".

### PR DESCRIPTION
**Pull request by KiranAminPanjwani**
## Modifications:
I have made an addition to the user guide by creating a new section titled "Overview of Kubernetes Architecture." The purpose of this section is to provide a comprehensive overview of essential Kubernetes components, including control plane components, worker nodes, and the Kubernetes API. This addition is particularly aimed at assisting new users who may not be familiar with the architecture of Kubernetes, allowing them to gain a better understanding of the platform before diving into configuring and deploying a Windows container in Kubernetes.

## Purpose:
The main objective of this addition is to equip new learners with prior knowledge of Kubernetes architecture. By doing so, they will have a better understanding of the platform's fundamental components and be able to establish meaningful connections, making it easier for them to navigate the platform. The addition aims to support new users in gaining a comprehensive understanding of Kubernetes, helping them to efficiently use the platform to manage containerized applications at scale.

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
@jsturtevant @marosset Kindly review and merge my PR. Thank you.😊✨

**Comment by jsturtevant** [comment]
@KiranAminPanjwani Thanks for the interest in helping Windows users, the summary is very concise! Alot of this information would be covered in the Kubernetes documentation already under sections like https://kubernetes.io/docs/home/#understand-kubernetes.  To avoid duplication, I would prefer to point folks to other sections when necessary, though I am not sure in this case it is needed as the tree structure for the doc there are already links to overview of Kubernetes.  

I would be interested what the Docs maintainers have to say.

**Comment by T-Lakshmi** [comment]
Hi @KiranAminPanjwani,
As per the [issue comment](https://github.com/kubernetes/website/issues/40738#issuecomment-1512034445) this information is already documented in a separate page under the [Concepts section](https://kubernetes.io/docs/concepts/) before the [Windows in Kubernetes](https://kubernetes.io/docs/concepts/windows/) section.
So it is not required to duplicate the information again, if you think its worth to mention you can provide reference link in such cases.

**Comment by T-Lakshmi** [comment]
Hi @KiranAminPanjwani,
As per the https://github.com/kubernetes/website/issues/40738#issuecomment-1512034445 this information is already documented in a separate page under the [Concepts section](https://kubernetes.io/docs/concepts/) before the [Windows in Kubernetes](https://kubernetes.io/docs/concepts/windows/) section.
So it is not good practice to duplicate the information again. if you think its worth to mention, we can provide reference links in such cases.

**Comment by KiranAminPanjwani** [comment]
> Hi @KiranAminPanjwani, As per the [#40738 (comment)](https://github.com/kubernetes/website/issues/40738#issuecomment-1512034445) this information is already documented in a separate page under the [Concepts section](https://kubernetes.io/docs/concepts/) before the [Windows in Kubernetes](https://kubernetes.io/docs/concepts/windows/) section. So it is not good practice to duplicate the information again. if you think its worth to mention, we can provide reference links in such cases.

Noted sir, thank you so much for guidance.✨
Should I add the reference here?

**Comment by sftim** [comment]
/hold

Please see https://github.com/kubernetes/website/issues/40738#issuecomment-1512739977

We should not merge this PR as it stands.

**Comment by T-Lakshmi** [comment]
> > Hi @KiranAminPanjwani, As per the [#40738 (comment)](https://github.com/kubernetes/website/issues/40738#issuecomment-1512034445) this information is already documented in a separate page under the [Concepts section](https://kubernetes.io/docs/concepts/) before the [Windows in Kubernetes](https://kubernetes.io/docs/concepts/windows/) section. So it is not good practice to duplicate the information again. if you think its worth to mention, we can provide reference links in such cases.
> 
> Noted sir, thank you so much for your guidance.sparkles Should I add the reference here?

Sorry, this can be answered by someone from sig who has "better experience". You can share your opinion for the [issue comment](https://github.com/kubernetes/website/issues/40738#issuecomment-1512739977), so team will decide accordingly.
Thanks,

**Comment by jsturtevant** [comment]
Maybe a link to review the concepts in the "before you begin section"?

**Comment by KiranAminPanjwani** [comment]
> Maybe a link to review the concepts in the "before you begin section"?

Yes right. This would be a great approach.😊

**Comment by divya-mohan0209** [comment]
Hello @KiranAminPanjwani please advise if you'd be able to continue working on the PR based on the above suggestions?

**Comment by reylejano** [comment]
Hi @KiranAminPanjwani , I'm closing this PR in agreement with other reviewers that the change proposed in this PR should not merge and this PR has a merge conflict and requires rebase
If you have time to rebase and strongly feel otherwise to the reviewers, feel free to reopen this PR with `/reopen` to further discuss
/close

**Pull request closed without merging**
