### PR TITLE
fix: Dockedr -> Docker

### PR DESCRIPTION
**Pull request by lmx-Hexagram**
fix a Misspell

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
more info about CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by jimangel** [comment]
Hey there! @lmx-Hexagram, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Review by pigletfly — APPROVED** [review]

**Comment by lmx-Hexagram** [comment]
I am very sorry for the long absence of reply
I have now completed the verification

**Review by tanjunchen — COMMENTED** [review]
/approve

**Review by tanjunchen — COMMENTED** [review]
Thanks

**Pull request merged**
