### PR TITLE
Issue #18498 Convert URL Request and Hello World to Korean

### PR DESCRIPTION
**Pull request by SupriyaSirbi**
Reference to Localization Request #18498

Update 'Received request for URL: ' + request.url and 'Hello World!' to be in Korean, on https://kubernetes.io/ko/examples/minikube/server.js.

### CODE REVIEW

**Comment by inductor** [comment]
FYI, Chinese & Japanese localization team decided not to translate this.

**Comment by gochist** [comment]
@inductor For example code blocks in the documentation, the Korean localization team has localized some comments. I think it's okay to localize static strings where possible. But I think it is also important to maintain consistency among localization teams. May I ask why not to translate?

**Comment by inductor** [comment]
@gochist Hello!

>I think it's okay to localize static strings where possible.

Yes, I agree with this, too! but we had some reasons to block the PR from the contributor.

1. The PR in Japanese contained the translation for 'Hello World!' which most developers in the world would understand what's supposed to mean. 
Ref: https://github.com/kubernetes/website/pull/18532/files#diff-5858ef8483a7dd7cd132c253eaa4e31bL6

2. The issue was not brought from a native Japanese speaker(in our perspective) and we thought it doesn't necessarily have to be translated and the PR's Japanese was not very natural anyway(no offence, though).

3. The Chinese team denied the PR, too.
We did not have "much motivation" to address the issue because this kind of comment wouldn't be a problem to understand the key concept of the documentation. so we kinda respected the decision of Chinese team which made sense to us.

**Comment by gochist** [comment]
@inductor 
Thank you very much for sharing your thoughts. I think this exchange of opinions between localization teams is very desirable.

Reason 1 is the same in Korean. But for reason number 2, I have a slightly different opinion. I am not a native English speaker either, but I sometimes contribute to English documents.

Behind reason 3, I understand that because we are localizing with limited human resources, it is efficient to focus our efforts on more important issues.

I will soon share the ideas of the Korean localization team about whether to allow localization for example code.

**Comment by inductor** [comment]
The point of reason 2 was that the translation was not natural enough while the priority was very low. Maybe I should not have mentioned "non-native" 🙇

**Comment by SupriyaSirbi** [comment]
@inductor @gochist Thanks for your response!

But the reason why this PR was raised is due to 2 main reasons

- The Russian language has "Request for URL" In Russian Language. So I thought there is a need to have a universal way of handling in all languages. If you people think that translation is not needed then it needs to hold good for Russian language as well :) So ideally I need to raise a PR to change "Request for URL:" from Russian to English as well. It does not make sense to have different handling for different languages.

- I agree with the "Hello World" inputs that the translation is not at all needed. In Russian also there is no translation. 

I shall close this PR on your inputs

**Comment by gochist** [comment]
@SupriyaSirbi 
The Korean localization team decided not to translate static strings in the example code during the team's regular online meeting today.

I would like to inform you that the decision was made to manage the human resources of the Korean localization team more efficiently.

I am very sorry for not accepting the PR and thank you very much for giving me a chance to discuss about this.

**Pull request closed without merging**
