### PR TITLE
Fixing names and links for EN files for IBM Cloud Kubernetes Service

### PR DESCRIPTION
**Pull request by artberger**
* Updating instances of deprecated name `Bluemix`
* Updating old links

### CODE REVIEW

**Comment by bradtopol** [comment]
@artberger Thank you for your submission. Can you please break this into multiple PRs where it is 1 PR for each language you are updating. We have different approvers for each language and a PR that updates across multiple languages could cause rebase issues in the future.  Thanks! /cc @zacharysarah @kbarnard10 @jimangel

**Comment by artberger** [comment]
@bradtopol, thank you for letting me know. I have removed all languages except the `en` files in this PR. I opened PRs for the other languages as follows:
* `fr`: https://github.com/kubernetes/website/pull/18103
* `ja`: https://github.com/kubernetes/website/pull/18104
* `ko`: https://github.com/kubernetes/website/pull/18107

Please let me know if I should do anything else.

**Pull request merged**
