### PR TITLE
Removing Rajakavitha1 from the approvers list

### PR DESCRIPTION
**Pull request by Rajakavitha1**
It has been a pleasure working with the SIG-Docs team.
Might not be able to contribute actively to the docs because of my current professional commitments.

### CODE REVIEW

**Comment by tengqm** [comment]
@Rajakavitha1 Best wishes to you. Hope you are not walking too far from the community.

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1 Best wishes to you. Hope you are not walking too far from the community.

Thank you @tengqm . I will always look forward for an opportunity to join this awesome community. I have always admired your relentless and committed contribution to SIG-Docs.

**Comment by kbhawkey** [comment]
@Rajakavitha1 ,
I appreciate your contributions to SIG-Docs!
Hope to see you around again.

**Comment by celestehorgan** [comment]
/approve

😢

**Pull request merged**
