### PR TITLE
Fix a Hugo panic cause by table shortcode

### PR DESCRIPTION
**Pull request by tengqm**

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by sftim** [comment]
I reverted the change that led to the site breaking: 18578288959f949ed9cf0418b2d72e34bc485797.

**Comment by tengqm** [comment]
sigh.
/close

**Comment by sftim** [comment]
Some feedback on this PR: the description is empty. I'd have welcomed extra context, perhaps a link to a GitHub issue.

@tengqm thanks for sending this in; I'm sorry that our tasks crossed and I only saw this fix after I'd made mine.

**Pull request closed without merging**
