### PR TITLE
update note for windows minikube install

### PR DESCRIPTION
**Pull request by kbhawkey**
See issue #13722.

### CODE REVIEW

**Comment by kbhawkey** [comment]
@craiglpeters, comments welcome!

**Comment by kbhawkey** [comment]
Preview page:
https://deploy-preview-13752--kubernetes-io-master-staging.netlify.com/docs/tasks/tools/install-minikube/

**Comment by afbjorklund** [comment]
Note that the first sentence on that page links back to:
https://kubernetes.io/docs/tasks/tools/install-minikube/

So there is some infinite link recursion going on here,
but maybe that is a good think, to keep them in sync ?

**Comment by kbhawkey** [comment]
@afbjorklund, happy to update if needed, but does the first sentence link to the tutorial page:
https://deploy-preview-13752--kubernetes-io-master-staging.netlify.com/docs/tutorials/hello-minikube/

**Comment by afbjorklund** [comment]
It does not, so maybe I was mistaken

**Pull request merged**
