### PR TITLE
Fix reference to API groups

### PR DESCRIPTION
**Pull request by tengqm**
closes: #2979

### CODE REVIEW

**Comment by tengqm** [comment]
/hold
Depends on: #24635

**Comment by kbhawkey** [comment]
Let's try this again
/approve cancel

**Comment by kbhawkey** [comment]
Page preview:
https://deploy-preview-24636--kubernetes-io-master-staging.netlify.app/docs/reference/using-api/api-overview/#api-groups

**Comment by kbhawkey** [comment]
The reference is updated,
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#-strong-api-groups-strong-

**Pull request merged**
