### PR TITLE
Minor Typo --- Windows HostProcess Beta 1.23 Documentation

### PR DESCRIPTION
**Pull request by brasmith-ms**
Quick typo fix from the 1.23 updates.

### CODE REVIEW

**Comment by tengqm** [comment]
please squash your commits.

**Comment by sftim** [comment]
/label tide/merge-method-squash

As this is 9 commits @brasmith-ms, if you _can_ [squash](https://k8s.dev/docs/guide/github-workflow/#squash-commits) it down to 1 commit, that's even better:
```bash
git checkout dev-1.23
git rebase -i 2fa721a7a75990a9b12f516e29b9756f00574838 # the merge base of your dev-1.23 and our upstream
# check rebase worked OK!
git push --force-with-lease
```

**Comment by jlbutler** [comment]
Thanks for handling this @brasmith-ms !

I think this PR wants to just be the final commit. Maybe just need a sync and rebase and that should fix this up.

**Comment by brasmith-ms** [comment]
Sorry I goofed this up, should be fixed now

**Pull request merged**
