### PR TITLE
Fixes broken install command for OSX.

### PR DESCRIPTION
**Pull request by jkodroff**
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.9 Features: set Milestone to `1.9` and Base Branch to `release-1.9`
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/6078)

### CODE REVIEW

**Comment by jkodroff** [comment]
CLA has been signed.

**Comment by kairen** [comment]
@jkodroff This change broken in zsh terminal.

**Comment by steveperry-53** [comment]
@jkodroff Can you give us some context about why you think this change is needed? For me, the existing command works, and your proposed command fails. Thanks.

**Comment by steveperry-53** [comment]
Closing for now. @jkodroff If you want to move forward with this, pleas reopen.

**Pull request closed without merging**
