### PR TITLE
[pt-br] Update persistent-volumes.md

### PR DESCRIPTION
**Pull request by rafael-romao**
## Description
 - This PR add a forgotten blank space on line 25

### CODE REVIEW

**Review by Sea-n — COMMENTED** [review]
Wow, nice catch! The change looks good to me.
/lgtm

BTW, would you like to go through the file again? I think there would be some other errors in this file you could point out. 😊

**Review by yagonobre — APPROVED** [review]
Thanks
/lgtm
/approve

**Pull request merged**
