### PR TITLE
[en] update custom-resources

### PR DESCRIPTION
**Pull request by ptux**
- Make it clear that the main API server delegates request to the user-created API server.

- Explanation for API aggregation, not standalone API server.

### CODE REVIEW

**Comment by geoffcline** [comment]
Hi 👋 

It looks like you've got two very similar PRs? https://github.com/kubernetes/website/pull/30406

Can you combine them to just one?

**Comment by ptux** [comment]
@geoffcline

Done!

**Review by RinkiyaKeDad — APPROVED** [review]
LGTM to me too!

**Pull request merged**
