### PR TITLE
Update nginx to modern versions

### PR DESCRIPTION
**Pull request by inductor**
Fixes https://github.com/kubernetes/website/issues/19195

I will do the same for Chinese and Japanese branches later

### CODE REVIEW

**Comment by sftim** [comment]
@inductor, can you explain the steps to you've taken to verify that these changes are valid? For example, have you run some tests?

(if you have, then I'm willing to take your word on that)

**Comment by inductor** [comment]
@sftim Sorry for late reply. I confirmed!

**Comment by sftim** [comment]
Drawing on https://github.com/kubernetes/website/pull/19198#issuecomment-596154597:
/approve

**Comment by jimangel** [comment]
It seems like we should have a way to automate these version / substitutions... I will bring this up at the weekly meeting. If no better solution comes around, this can be merged.

/approve

**Pull request merged**
