### PR TITLE
Change kubernetesVersion from v1.21 to v1.21.0

### LINKED ISSUE #27638: kubeadm init with default config : version "v1.21" doesn't match patterns for neither semantic version nor labels (stable, latest, ...)
I'm at this page : https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

If I follow the guide with the default configuration it will failed.

````
vagrant@2k8s-master:~$ kubeadm init --config kubeadm-config.yaml
version "v1.21" doesn't match patterns for neither semantic version nor labels (stable, latest, ...)
To see the stack trace of this error execute with --v=5 or higher
````

The config from the webapge
````
vagrant@2k8s-master:~$ cat kubeadm-config.yaml
# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.21
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
vagrant@2k8s-master:~$
````

but if I remove the line : kubernetesVersion: v1.21  it will works.

````
vagrant@2k8s-master:~$ sudo kubeadm init --config kubeadm-config.yaml --dry-run
[init] Using Kubernetes version: v1.21.0
[preflight] Running pre-flight checks
[preflight] Would pull the required images (like 'kubeadm config images pull')
[certs] Using certificateDir folder "/etc/kubernetes/tmp/kubeadm-init-dryrun478188129"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [2k8s-master kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.50.180]
[certs] Generating "apiserver-kubelet-client" certificate and key
````

### PR DESCRIPTION
**Pull request by shannonxtreme**
Fixes #27638

### CODE REVIEW

**Comment by shannonxtreme** [comment]
Signed CLA.

**Review by neolit123 — COMMENTED** [review]
thank you!

/lgtm
/sig cluster-lifecycle

**Comment by kbhawkey** [comment]
Thanks @shannonxtreme .
/approve

**Pull request merged**
