### PR TITLE
[zh-cn]  update tasks/administer-cluster/cluster-upgrade.md

### PR DESCRIPTION
**Pull request by yanrongshi**

### CODE REVIEW

**Comment by tengqm** [comment]
/retitle [zh-cn]  update tasks/administer-cluster/cluster-upgrade.md

**Comment by tengqm** [comment]
/retitle [zh-cn] update tasks/administer-cluster/cluster-upgrade.md

**Comment by jihoon-seo** [comment]
@yanrongshi you need to perform a rebase.

**Pull request closed without merging**
