### PR TITLE
[zh] Change sig-docs-xx-reviewers to -reviews

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/35587/files

### CODE REVIEW

**Comment by windsonsea** [comment]
Thanks.

/lgtm

**Comment by Sea-n** [comment]
There are some other changes, please check with local diff tool.

```bash
vimdiff content/en/docs/contribute/participate/_index.md content/zh-cn/docs/contribute/participate/_index.md
```

/hold

**Comment by Arhell** [comment]
> There are some other changes, please check with local diff tool.
> 
> ```shell
> vimdiff content/en/docs/contribute/participate/_index.md content/zh-cn/docs/contribute/participate/_index.md
> ```
> 
> /hold

Looked, only these changes that I made in this file are changed.
there are no other changes with the main file on the en version

**Comment by Sea-n** [comment]
Please check through the whole file.

https://github.com/kubernetes/website/blob/main/content/zh-cn/docs/contribute/participate/_index.md?plain=1#L42-L47

**Comment by Arhell** [comment]
Ok, I'm looking at the file according to the script `./scripts/lsync.sh`
it says is still in sync after my change

**Pull request merged**
