### PR TITLE
Fix links MD syntax typo in FR documentation

### PR DESCRIPTION
**Pull request by bobsaintcool**
Hi,

One can find attached few proposals to fix link issue within FR documentation.

### CODE REVIEW

**Review by irvifa — COMMENTED** [review]
Please sign the CLA

**Review by irvifa — COMMENTED** [review]
/cc @kubernetes/sig-docs-fr-reviews

**Review by irvifa — COMMENTED** [review]
/lgtm

**Comment by bobsaintcool** [comment]
thx

**Pull request merged**
