### PR TITLE
[pt-br] Update obsolete links in Portuguese locale

### PR DESCRIPTION
**Pull request by stormqueen1990**
Update obsoleted links that were still pointing to `/pt/` instead of `/pt-br/`

### CODE REVIEW

**Comment by stormqueen1990** [comment]
/unhold

Removed the changes to `scale-intro.html` as the change itself was obsolete (page will change in the context of #43646 and that should remove the need to fix the link).

**Comment by MrErlison** [comment]
Thank you @stormqueen1990 

/lgtm

**Comment by edsoncelio** [comment]
Thanks!!
/approve

**Pull request merged**
