### PR TITLE
[ru]Replace k8s.gcr.io references with registry.k8s.io

### PR DESCRIPTION
**Pull request by asa3311**

### CODE REVIEW

**Comment by shurup** [comment]
Thank you, @asa3311! We did a massive replacement in #39245 before. However, some new content got merged since that time, and it had this old domain mentioned. I double-checked we don't have more `k8s.gcr.io` in the current `content/ru` directory.

/lgtm
/approve

**Review by Arhell — COMMENTED** [review]
/lgtm

**Comment by shurup** [comment]
We came across the "Build exceeded maximum allowed runtime" error here, which is not related to the PR itself (#35780).

@asa3311 can you, please, do this to trigger a rebuild for this PR?

> git commit --amend
> git push --force

**Comment by asa3311** [comment]
ok，I will rebuild

**Pull request merged**
