### PR TITLE
Updated 'exec' description

### PR DESCRIPTION
**Pull request by ashish-billore**
Minor updates to 'exec' operation's description, completed it with '.' to be consistent with other operation descriptions.

### CODE REVIEW

**Comment by ashish-billore** [comment]
CLA done!

**Comment by ashish-billore** [comment]
CNF CLA Done!

**Comment by Bradamant3** [comment]
@ashish-billore thanks for the fix! And welcome to K8s docs!

/lgtm
/approve

**Comment by ashish-billore** [comment]
Thanks @Bradamant3 :)

**Pull request merged**
