### PR TITLE
Add the code of conduct

### PR DESCRIPTION
**Pull request by nikhita**
For https://github.com/kubernetes/community/issues/3053

The content is from https://github.com/kubernetes/kubernetes-template-project.

/assign @Bradamant3

### CODE REVIEW

**Comment by Hartmarken348** [comment]
11919

**Comment by nikhita** [comment]
Can we get this in? This is the only repo without CoC today. :grimacing:

**Comment by dims** [comment]
/approve

Let's see if i have karma here

**Pull request merged**
