### PR TITLE
[WIP][Scheduler User Guide Documentation] Kube-schedule design and implementation from source code

### PR DESCRIPTION
**Pull request by huynq0911**
The draft version of scheduler design and implementation from source code
This PR is for [Learning kube-scheduler's design and implementation from source code](https://github.com/kubernetes/kubernetes/issues/69771)

/sig scheduling
/kind documentation

### CODE REVIEW

**Comment by zparnold** [comment]
@huynq0911 Where are you at with this? Still a WIP?

**Comment by huynq0911** [comment]
> @huynq0911 Where are you at with this? Still a WIP?

Thanks for asking! I'm still working on this PR. I hope to push some changes this week.

**Comment by zparnold** [comment]
@huynq0911 Had a chance to take a look at these changes?

**Comment by mistyhacks** [comment]
There are about 4 seeming-related WIP PRs about the scheduler. #10702 is the earliest one. What's the current status of this one, and does it relate to that one?

**Comment by sftim** [comment]
If #14637 gets merged, I'd like to borrow commits or text from this PR.

**Comment by tengqm** [comment]
@sftim Shall we close this one now?

**Comment by sftim** [comment]
@huynq0911 would you like to make a new PR that complements the page at https://kubernetes.io/docs/concepts/scheduling/kube-scheduler/?

I think it does make sense to close this particular pull request. There is definitely still room to improve the concept section about scheduling.

**Comment by huynq0911** [comment]
> @huynq0911 would you like to make a new PR that complements the page at https://kubernetes.io/docs/concepts/scheduling/kube-scheduler/?
> 
> I think it does make sense to close this particular pull request. There is definitely still room to improve the concept section about scheduling.

@sftim: hmm, it's long time I contribute to K8S community, so I missed some updates. But if you see this PR is useful, you can use anything from this. Thanks!

**Comment by kbhawkey** [comment]
Based upon the previous comments, will close this PR. Feel free to reopen if needed. Thanks!
/close

**Pull request closed without merging**
