### PR TITLE
Operator Patterns ID Localization.

### PR DESCRIPTION
**Pull request by ariscahyadi**
Hi,

I added ID localization for `concepts/extend-kubernetes/operator.md`.

Thank you,
Aris.

### CODE REVIEW

**Comment by irvifa** [comment]
Hi @ariscahyadi 👋 Any update on this?

**Comment by ariscahyadi** [comment]
> thanks for translating this page, I learned a lot about Operator's useful resources for my daily work :P
> I gave couple of comments, please address them. Most importantly:
> 
> * We use "kamu" instead of "anda" in our translations, because it's more friendly and warm welcoming
> * All API objects must be written in CamelCase without Backtick, you can take a look at the list [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/)
> * Italicize imported english word: write "_controller_" instead of "controller".
> * You also have to translate the hyperlink (the word inside [] bracket), and its anchor

I have pushed new commit.

**Comment by ariscahyadi** [comment]
> Hi @ariscahyadi 👋 Any update on this?

I just pushed new commit.

**Comment by irvifa** [comment]
Thank you, by the way can you please squash it to one commit?

**Comment by ariscahyadi** [comment]
> Thank you, by the way can you please squash it to one commit?

In my branch? I am not sure how to do it :)

**Comment by irvifa** [comment]
Yes on your branch.
`git rebase -i master`
After that you can see there is a several lines that either you can pick or squash. 
Then you can change pick to squash. Usually we left the first pick clause as it is. And change the rest to squash. 

https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Comment by ariscahyadi** [comment]
> Yes on your branch.
> `git rebase -i master`
> After that you can see there is a several lines that either you can pick or squash.
> Then you can change pick to squash. Usually we left the first pick clause as it is. And change the rest to squash.
> 
> https://github.com/wprig/wprig/wiki/How-to-squash-commits

It is done! Thanks.

**Comment by girikuncoro** [comment]
thanks mas @ariscahyadi , great work! 🎉  one last request from me, can you replace `Kamu` with lowercase `kamu`, then we can get this in

**Comment by ariscahyadi** [comment]
> thanks mas @ariscahyadi , great work! 🎉 one last request from me, can you replace `Kamu` with lowercase `kamu`, then we can get this in

It's done :)
Please check!

**Comment by girikuncoro** [comment]
Amazing, thanks! Looking forward to your next contribution 😄 

/lgtm
/approve

**Pull request merged**
