### PR TITLE
zh_trans: kubeadm_alpha_phase_selfhosting.md

### PR DESCRIPTION
**Pull request by zgfh**
zh_trans: kubeadm_alpha_phase_selfhosting.md

### CODE REVIEW

**Comment by xichengliudui** [comment]
Before the translation, you can check the pr, because some of them have been translated and are under approval. thanks!
https://github.com/kubernetes/website/pull/11881
https://github.com/kubernetes/website/pull/11880
https://github.com/kubernetes/website/pull/11879
https://github.com/kubernetes/website/pull/11921

**Comment by zgfh** [comment]
@xichengliudui  very sorry，I was notified to claim the task by https://github.com/k8smeetup/website-tasks/issues/517 ，I will close this

**Comment by xichengliudui** [comment]
No, it's my problem. I noticed that you translated the files in this directory. I should have told you. sorry

**Comment by xichengliudui** [comment]
@zgfh, I suggest that next time when you receive the task, you can actually check whether it has been translated, because there are many Issues that have been solved

**Comment by zgfh** [comment]
thanks, I forget to check PR 😂，I thought everyone is claiming the task in k8smeetup/website-tasks。

**Pull request closed without merging**
