### PR TITLE
[zh-cn]Add the Chinese translation doc for user namespaces under workloads/pods

### PR DESCRIPTION
**Pull request by aim-for-better**
Add the Chinese translation doc for user namespaces under workloads/pods.
Sync  docs\concepts\workloads\pods\user-namespaces.md

### CODE REVIEW

**Comment by aim-for-better** [comment]
Hi reviewers,
could you please help trigger CLA again? Thanks

**Comment by tengqm** [comment]
> Hi reviewers, could you please help trigger CLA again? Thanks

This can be done only by the author. Please check if the email you used for CLA is the same as the one you used for the PR.

**Comment by Sea-n** [comment]
Hey @aim-for-better,

The email used for commit this PR (`zh***ou@microsoft.com`) is not binding to your GitHub account, so the CLA validation won't pass.

Please goto GitHub Settings > Access > Emails > Add email address:
https://github.com/settings/emails

If you have other issues, please take a look at [the CLA tutorial](https://git.k8s.io/community/CLA.md).

**Pull request closed without merging**
