### PR TITLE
fix docs style

### PR DESCRIPTION
**Pull request by zgfh**
fix docs style

### CODE REVIEW

**Comment by idealhack** [comment]
- https://5c3d4946055f560009f40e27--k8s-v1-12.netlify.com/zh/docs/tasks/administer-cluster/change-default-storage-class/
- https://kubernetes.io/zh/docs/tasks/administer-cluster/change-default-storage-class/

It seems not quite right to me.

Please always clone the repo to render it locally, instead of editing on GitHub.

**Comment by zgfh** [comment]
@idealhack sorry, I think editing docs on GitHub  is simple and fast . I will build my local environment later.

**Comment by idealhack** [comment]
@zgfh It's OK. GitHub editing is good enough for some small fixes, but I think things like these indenting are tricky ;)

**Comment by zgfh** [comment]
sorry about that, I just want make it same with this: https://github.com/kubernetes/website/edit/master/content/en/docs/tasks/administer-cluster/change-default-storage-class.md

**Comment by idealhack** [comment]
That's fair. We can fix the intent and other things in both files, or we keep the same as the English version as is, either works for me.

**Comment by zgfh** [comment]
@idealhack  updated  :https://deploy-preview-12225--k8s-v1-12.netlify.com/zh/docs/tasks/administer-cluster/change-default-storage-class/

**Comment by idealhack** [comment]
thanks! hope we can fix the indents in the future ;)

/lgtm
/assign @tengqm

**Pull request merged**
