### PR TITLE
[ko] update outdated korean files in dev-1.24-ko.2 (M90-M93)

### PR DESCRIPTION
**Pull request by having-dlrow**
M90 ~ M93 까지의 변경사항들을 반영하였습니다( M90 띄어쓰기 변경이므로, 수정사항 없음 )

* Related issue : https://github.com/kubernetes/website/issues/34903 (dev-1.24-ko.1)

> - [ ] M90. content/en/docs/tasks/debug/debug-application/debug-pods.md | 2(+XS) 2(-)
> - [ ] M91. content/en/docs/tasks/debug/debug-cluster/_index.md | 61(+M) 48(-)
> - [ ] M92. content/en/docs/tasks/debug/debug-cluster/resource-metrics-pipeline.md | 2(+XS) 2(-)
> - [ ] M93. content/en/docs/tasks/debug/debug-cluster/resource-usage-monitoring.md | 5(+XS) 2(-)

/language ko

### CODE REVIEW

**Comment by NitishKumar06** [comment]
Hey @having-dlrow ! We appreciate your contribution but please sign in the CLA before this PR can be reviewed.

**Review by Arhell — COMMENTED** [review]
Please sign CLA
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by having-dlrow** [comment]
> Please sign CLA https://github.com/kubernetes/community/blob/master/CLA.md

Thank you for letting me know, @Arhell
By the way, I received a sign CLA and a certification email.
But the sign CLA check (Missing CLA Authorization.) doesn't change. 
Can you tell me what to do next to move on?

image

**Comment by seokho-son** [comment]
Hi @having-dlrow 
Thank you for your contribution ! :)

I think you need to check the above comment.
regarding mismatched User IDs (Github & commit).

> ❌ The commit (https://github.com/kubernetes/website/commit/d7f4ab31b7be2504f076b443e8389ce3c3ce70fc). This user is missing the User's ID, preventing the EasyCLA check. [Consult GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve.For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

**Pull request closed without merging**
