### PR TITLE
[WIP] Re-add the kubectl generated ref

### PR DESCRIPTION
**Pull request by zacharysarah**

### CODE REVIEW

**Comment by mtaufen** [comment]
Still 404s in the netlify preview? https://deploy-preview-8427--kubernetes-io-master-staging.netlify.com/docs/reference/generated/kubectl/kubectl/

**Comment by zacharysarah** [comment]
@mtaufen Please note that this PR is marked `[WIP]`: work in progress. Please hold feedback until the `do-not-merge/work-in-progress` label is removed.

**Comment by zacharysarah** [comment]
@steveperry-53 A quick look at the content and how it's laid out shows that the kubectl API docs aren't going to live well in `static/`. There's no obvious way to make them appear nicely in documentation/reference. I'm open to fixing them later, but for now, let's do what we can to make them appear locally.

**Comment by zacharysarah** [comment]
@steveperry-53 I've tried tackling the kubectl generated docs, but it's kicking my butt. Do you mind taking this on?

**Comment by steveperry-53** [comment]
@zacharysarah Yes, I'll take the kubectl command ref docs.

**Pull request closed without merging**
