### PR TITLE
Add Yandex Cloud to Service Internal Load Balancer

### PR DESCRIPTION
**Pull request by etifontaine**
Update service documentation to add Internal load balancer for Yandex Cloud

### CODE REVIEW

**Comment by sftim** [comment]
Hi @etifontaine 

Usually we don't accept PRs adding content about third party products, because that's not allowed by the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/).

Are there any exceptions that are relevant here?
/hold

**Comment by etifontaine** [comment]
> Hi @etifontaine
> 
> Usually we don't accept PRs adding content about third party products, because that's not allowed by the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/).
> 
> Are there any exceptions that are relevant here?
> /hold

Hello!

There was already multiple tabs with other Cloud providers (GCP, AWS, Alibaba Cloud, Baidu Cloud). As they are also third party products and Kubernetes on Yandex Cloud is growing I thought it was relevant to add the information concerning Internal Load Balancer annotations.

**Comment by sftim** [comment]
I'm afraid some of those will be pending removal - we haven't yet updated all pages to remove this type of information.

Where the cloud provider integration uses code donated to Kubernetes, it's OK to include that detail (for example, the GCP integration is currently in-project).

**Comment by etifontaine** [comment]
Very clear! I'm closing the PR 👌

**Pull request closed without merging**
