### PR TITLE
Fix the grammar in storage-capacity.md

### PR DESCRIPTION
**Pull request by ydFu**
Fix the small grammar in storage-capacity.md .

### CODE REVIEW

**Comment by tengqm** [comment]
This change doesn't make a lot senses to me.

**Comment by ydFu** [comment]
Thank you for your guidance.
These changes are small in this PR.
But I suggest that first letter should be capitaized.

**Comment by tengqm** [comment]
@ydFu The first letter should be a capital one for a sentence. If it is not a complete sentence, there is no such requirement.

**Comment by ydFu** [comment]
Thank.

**Pull request closed without merging**
