### PR TITLE
fix the format of shell content

### PR DESCRIPTION
**Pull request by izhaomeng**

### CODE REVIEW

**Comment by tengqm** [comment]
@izhaomeng pls sign the CLA for this to be merged.

**Comment by markthink** [comment]
@izhaomeng  翻译分支建议使用 v1.14  参考：https://github.com/k8smeetup/k8s-official-translation

**Comment by markthink** [comment]
@izhaomeng  翻译分支建议使用 v1.14  参考：https://github.com/k8smeetup/k8s-official-translation

**Comment by tengqm** [comment]
Closing due to CLA problem for over 30 days. Feel free to reopen when CLA is ready. Thanks.

**Pull request closed without merging**
