### PR TITLE
Metrics reference is for (unreleased) v1.29

### LINKED ISSUE #44008: Metrics reference is for (unreleased) v1.29
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reference/instrumentation/metrics/ says that it is for Kubernetes v1.29, which has yet to be released.

**Proposed Solution:**
Revise https://kubernetes.io/docs/reference/instrumentation/metrics/ to cover v1.28 metrics

**Page to Update:**
https://kubernetes.io/docs/reference/instrumentation/metrics/

**Additional Information:**
We should fix this before the v1.29 release.

/priority important-soon
/sig instrumentation
/language en
/triage accepted

### PR DESCRIPTION
**Pull request by coder12git**
Fixes #44008

To fix this issue, this PR revert this PR -> #42823

### CODE REVIEW

**Comment by coder12git** [comment]
@kubernetes/sig-docs-en-owners

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
