### PR TITLE
fix the command output

### PR DESCRIPTION
**Pull request by tanshanshan**
I have verified on version v1.11

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
> Help editing and submitting pull requests:  https://deploy-preview-9510--kubernetes-io-master-staging.netlify.com/docs/contribute/start/#submit-a-pull-request.
> Help choosing which branch to use, see
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by tengqm** [comment]
@tanshanshan If we now look back at your recent PRs (#9946, #9949, #9950, #9951, #9952, #9954, #9955, #9956, #9957, #9958, #9965, #9966, #9969 ...) do you think we should have considered combine several changes into fewer PRs?

**Comment by tanshanshan** [comment]
It is ok, thanks .@tengqm

**Comment by Bradamant3** [comment]
/approve for docs review

@tengqm can you add the lgtm? I think the multiple PRs are OK -- preferable to rolling them all into one, at least.

**Pull request merged**
