### PR TITLE
Merge main branch into dev-1.30

### PR DESCRIPTION
**Pull request by Princesso**
This PR syncs the dev-1.30 branch with the main branch to keep the dev-1.30 branch up to date.

cc: @Vyom-Yadav @drewhagen @chanieljdan @celestehorgan

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
@Princesso The target branch needs to be `dev-1.30`

**Review by Arhell — COMMENTED** [review]
lgtm

**Review by dipesh-rawat — COMMENTED** [review]
/lgtm

**Review by sftim — COMMENTED** [review]
/approve

**Pull request merged**
