### PR TITLE
Update create-cluster-kubeadm.md

### PR DESCRIPTION
**Pull request by krisdock**
Update Canal version (1.7) in pod network apply commands

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/5761)

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@krisdock thanks for contribution! Can you sign your CLA please? :)

**Comment by xiangpengzhao** [comment]
Cool! CLA status updated.

Seems like there are other places wrt version in this doc need to update.

cc @luxas

**Comment by steveperry-53** [comment]
@luxas I can't find any other mention rbac.yaml and canal.yaml in the doc set.

@krisdock Are you ready for me to merge this?

**Comment by krisdock** [comment]
I believe so.

**Pull request merged**
