### PR TITLE
Add warning that liveness probe must be configured carefully

### PR DESCRIPTION
**Pull request by KanishkaVerma054**
#### Title of the Commit

A warning that liveness probe must be configured carefully.

#### Which issue(s) this PR fixes

Part of #16607 

#### Description

An improved warning that Liveness Probe should be used with caution, as incorrect configuration of liveness probes can lead to cascading failures.

### CODE REVIEW

**Comment by KanishkaVerma054** [comment]
Hello, @bradtopol  & @natalisucks I've added the changes as desired. May you both please review my changes.

**Comment by binboum** [comment]
Hey, in tune with this new form of warning, I think a typo slipped through :

- Incorrect configuration of liveness probes can lead to cascading failures. For example, killing the ~pod~ -> **container** when it has high load, as opposed to being crashed, can lead to failed client requests or traffic being shifted onto other pods in the same deployment or service, thereby overloading them.

After on the term "killing", to think about, it can be ambiguous, we can use "restart" like [on the doc](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/), at your choice.

**Comment by KanishkaVerma054** [comment]
@binboum I've done the changes as you've said. The changes are in the PR #39930. May you please review the changes.

**Comment by sftim** [comment]
/retitle Add warning that liveness probe must be configured carefully

**Pull request closed without merging**
