### PR TITLE
described Pod pair for better understanding

### PR DESCRIPTION
**Pull request by kundan2707**
Fixes: #38026 

Described pod pair for better understanding

### CODE REVIEW

**Comment by kundan2707** [comment]
@daminisatya  Can you PTAL?

**Comment by mehabhalodiya** [comment]
Hey @kundan2707 
I would highly recommend you wait for the `triage-accepted` label on the corresponding linked issue, then one of the reviewers can look ahead on this. Thanks!

**Comment by tengqm** [comment]
A simple fix would be removing the 'pair' word.

**Comment by kundan2707** [comment]
> A simple fix would be removing the 'pair' word.

@tengqm  changed as suggested

**Pull request merged**
