### PR TITLE
Fixes naming for OKE service

### PR DESCRIPTION
**Pull request by karthequian**
Fixes service naming, and added to table

### CODE REVIEW

**Comment by karthequian** [comment]
@cody-clark unrelated, but would it make sense to redo that table in an alphabetical order? The way it is right now is an eyesore...

**Comment by cody-clark** [comment]
@karthequian No kidding. I think it'd be worthwhile to democratize / give logical order to the table. 

Preview: https://deploy-preview-13137--kubernetes-io-master-staging.netlify.com/docs/setup/pick-right-solution/#table-of-solutions

**Comment by karthequian** [comment]
> @karthequian No kidding. I think it'd be worthwhile to democratize / give logical order to the table.
> 
I'll create a separate PR for this to alphabetize it by the IaaS Provider column. Happy to do something else if you see fit!

**Pull request merged**
