### PR TITLE
fix tooltip overflows

### PR DESCRIPTION
**Pull request by Arhell**
issue #22398

### CODE REVIEW

**Comment by Arhell** [comment]
review page https://deploy-preview-22417--kubernetes-io-master-staging.netlify.app/docs/concepts/cluster-administration/monitoring/#metrics-in-kubernetes
/assign @kbhawkey

**Comment by tengqm** [comment]
we are still using `static/css/custom-jekyll/tags.css`???

**Comment by Arhell** [comment]
Here I see that only js was deleted #22044

**Comment by sftim** [comment]
/lgtm

There's a clear case for a bigger cleanup here.

**Comment by celestehorgan** [comment]
/approve 

but yes, there's more cleanup to this feature needed. :/

**Pull request merged**
