### PR TITLE
WIP: Translate tasks/manage-kubernetes-objects/declarative-config into Japanese

### LINKED ISSUE #27596: [ja] Translate tasks/manage-kubernetes-objects/declarative-config/
**This is a Feature Request**

**What would you like to be added**

Translate [tasks/manage-kubernetes-objects/declarative-config/](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/) into Japanese.

**Why is this needed**

This page has not been translated.

**Comments**

/language ja
/assign

### PR DESCRIPTION
**Pull request by shuuji3**
resolve #27596

### CODE REVIEW

**Comment by shuuji3** [comment]
The current WIP translation is based on the original article as of May 2021. it needs the update.

**Comment by divya-mohan0209** [comment]
Hello folks, there has been no activity on this PR since ~6 months and I'll be therefore, closing this PR off.

We understand that the localization cadence is different & that contributors/approvers may dip in & out based on their bandwidth. Please feel free to reopen this once you have the cycles to work on this together.

/close

**Pull request closed without merging**
