### PR TITLE
Generate the reference documentation for 1.26

### PR DESCRIPTION
**Pull request by krol3**
Generate the reference documentation for 1.26, following this [step](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#generate-the-reference-documentation)

cc: @divya-mohan0209  @onlydole

### CODE REVIEW

**Comment by sftim** [comment]
This is missing most of the reference documentation updates. Right now I only see the legacy API reference update - was that what you intended @krol3.

**Comment by tengqm** [comment]
@krol3 There are some updates to the generator, for adapting to changes in 1.26. Please make sure you are using  the latest reference-docs generator.

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/pull/38350

**Comment by nate-double-u** [comment]
This needs to target `main` now.

**Comment by sftim** [comment]
/approve

Thanks @krol3

**Pull request merged**
