### PR TITLE
ResilientWatchCacheInitialization documentation

### PR DESCRIPTION
**Pull request by wojtek-t**
/assign @jpbetz

### CODE REVIEW

**Comment by tengqm** [comment]
/lgtm

I'm not sure if users can understand when to toggle these gates.
I mean we may need more user documentation on the watch cache.

**Comment by hacktivist123** [comment]
Hello @wojtek-t 👋! I'm reaching out from the Docs team. Just checking in as we approach Docs Freeze on Tuesday July 30th 18:00 PDT. This documentation appears to still be under review. To meet the Docs Freeze, this PR must have a technical review as well as lgtm and approve labels applied, without any unaddressed comments or concerns from SIG Docs. The status of this enhancement is marked as at risk for docs freeze. Thank you!

**Comment by wojtek-t** [comment]
> I'm not sure if users can understand when to toggle these gates.
I mean we may need more user documentation on the watch cache.

I don't expect an arbitrary user to play with those at all - it's for the most sophisticated users, who understand it.
As for documentation on the watchcache - I partially agree, but that's orthogonal to this PR itself.

@hacktivist123 - this already has technical lgtm from Joe above and is waiting for sig docs approval.

**Pull request merged**
