### PR TITLE
Fix typo in networking.md

### PR DESCRIPTION
**Pull request by kobus-v-schoor**
Just fixes a small typo in the networking documentation

### CODE REVIEW

**Comment by annajung** [comment]
Hi @kobus-v-schoor, please sign the CLA for the PR to be reviewed

**Review by Arhell — COMMENTED** [review]
Plase sign CLA
https://github.com/kubernetes/website/pull/31209#issuecomment-1005477076

**Comment by kobus-v-schoor** [comment]
The section containing the typo was deleted in a recent commit in main, so this PR is moot. Closing

**Pull request closed without merging**
