### PR TITLE
[ja] fix typo

### PR DESCRIPTION
**Pull request by Arhell**
en PR https://github.com/kubernetes/website/pull/34278/files
/assign @atoato88
/assign @nasa9084

### CODE REVIEW

**Comment by mk46** [comment]
/lgtm
Thanks!!

**Comment by atoato88** [comment]
LGTM too 😀

**Comment by Arhell** [comment]
I re-pushed the fix and did a rebase, the build took a very long time

**Review by mk46 — APPROVED** [review]
/lgtm

**Pull request merged**
