### PR TITLE
Added cron job monitoring

### PR DESCRIPTION
**Pull request by pietervogelaar**
Added cron job monitoring with the Kubernetes job monitor

### CODE REVIEW

**Comment by zparnold** [comment]
Hey there! @pietervogelaar, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by pietervogelaar** [comment]
@zparnold I did sign the CLA. The robot changed the label, so I think that is correct now?

**Comment by zparnold** [comment]
Sweet! That it is, but can you rebase your changes on the master branch? Looks like we have a merge conflict.

**Comment by pietervogelaar** [comment]
@zparnold Okay, the merge conflict is resolved!

**Pull request merged**
