### PR TITLE
Corrected network policy port notation

### PR DESCRIPTION
**Pull request by delaman**
Corrected how the ports are defined in the network-policy documentation.

### CODE REVIEW

**Comment by caseydavenport** [comment]
@delaman was this throwing validation errors for you?

I think the current yaml is correct - the "from" and "ports" sections are ANDed together.

**Comment by heckj** [comment]
@delaman - thank you for taking the time to help us improve this! It seems from Casey's comment that the original is intended to be correct, and that your suggestion would result in validation errors - could you double check that please?

If it is correct, could you please sign the CLA so that we could consider your contribution.

**Comment by thockin** [comment]
I am pretty sure Casey's right on this one.

**Comment by heckj** [comment]
thanks @thockin

**Comment by delaman** [comment]
I signed the CLA

I verified that my PR doe not cause a validation error.  Both the current and my PR do **not** give validation errors.

My PR in JSON format makes more sense to me:

```json
{
  "apiVersion": "networking.k8s.io/v1",
  "kind": "NetworkPolicy",
  "metadata": {
    "name": "test-network-policy",
    "namespace": "default"
  },
  "spec": {
    "podSelector": {
      "matchLabels": {
        "role": "db"
      }
    },
    "policyTypes": [
      "Ingress",
      "Egress"
    ],
    "ingress": [
      {
        "from": [
          {
            "ipBlock": {
              "cidr": "172.17.0.0/16",
              "except": [
                "172.17.1.0/24"
              ]
            }
          },
          {
            "namespaceSelector": {
              "matchLabels": {
                "project": "myproject"
              }
            }
          },
          {
            "podSelector": {
              "matchLabels": {
                "role": "frontend"
              }
            }
          }
        ]
      },
      {
        "ports": [
          {
            "protocol": "TCP",
            "port": 6379
          }
        ]
      }
    ],
    "egress": [
      {
        "to": [
          {
            "ipBlock": {
              "cidr": "10.0.0.0/24"
            }
          }
        ]
      },
      {
        "ports": [
          {
            "protocol": "TCP",
            "port": 5978
          }
        ]
      }
    ]
  }
}
```

**Comment by delaman** [comment]
I take it back.  I accept the current documentation.  

My fault.  Thanks for your time guys.

**Pull request closed without merging**
