### PR TITLE
Update broken link and Hugo metadata

### LINKED ISSUE #33780: Update broken link and Hugo metadata of `tasks/debug/*`
**This is a Bug Report**

**Problem:**
In https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/ ,
[one link](https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#:~:text=troubleshooting%20document) is broken.

**Proposed Solution:**
In https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/debug/debug-application/debug-pods.md?plain=1 ,

```diff
-You may also visit [troubleshooting document](/docs/tasks/debug/overview/) for more information.
+You may also visit [troubleshooting document](/docs/tasks/debug/) for more information.
```

**Page to Update:**
https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/

---

**Problem:**
The `content_type` of these pages is `concept`, but it seems that it should be `task`.
- https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/debug/debug-application/debug-pods.md?plain=1
- https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/debug/debug-application/debug-service.md?plain=1

**Proposed Solution:**

```diff
-content_type: concept
+content_type: task
```

**Page to Update:**
- https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/debug/debug-application/debug-pods.md?plain=1
- https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/debug/debug-application/debug-service.md?plain=1

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
Fixes #33780

### CODE REVIEW

**Comment by mk46** [comment]
@PrajwalBorkar Please replace `concept` by `task` https://github.com/kubernetes/website/blob/dab4e5d146711e048a96181d1695ecd6fa115c67/content/en/docs/tasks/debug/debug-application/debug-service.md?plain=1#L5
as mentioned in https://github.com/kubernetes/website/issues/33780

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar Please replace `concept` by `task`
> 
> https://github.com/kubernetes/website/blob/dab4e5d146711e048a96181d1695ecd6fa115c67/content/en/docs/tasks/debug/debug-application/debug-service.md?plain=1#L5
> 
> 
> as mentioned in #33780
> Thanks!!

I already replaced. Please check this [commit](https://github.com/kubernetes/website/pull/33725/commits/e313e234e59f6c1c2f3338e81f63ef5a5fc0efbb)

**Comment by mk46** [comment]
@PrajwalBorkar You have updated `content/en/docs/tasks/debug/debug-application/debug-pods.md` not `content/en/docs/tasks/debug/debug-application/debug-service.md`
Kindly recheck

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar You have updated `content/en/docs/tasks/debug/debug-application/debug-pods.md` not `content/en/docs/tasks/debug/debug-application/debug-service.md` Kindly recheck

Yeah Updated. thanks 👍

**Review by sftim — CHANGES_REQUESTED** [review]
@PrajwalBorkar: this PR fixes separate things (the debug tasks, and also the page about reviewing PRs).

Pull requests that fix bugs should fix either one bug, or fix multiple bugs that are clearly related to each other.

You could:
- open two new PRs, one for each fix
- edit this PR to cover just one fix, and open a new PR for the other fix.

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar: this PR fixes separate things (the debug tasks, and also the page about reviewing PRs).
> 
> Pull requests that fix bugs should fix either one bug, or fix multiple bugs that are clearly related to each other.
> 
> You could:
> 
> * open two new PRs, one for each fix
> * edit this PR to cover just one fix, and open a new PR for the other fix.

I done some changes please check and can u elaborate how to create new PR now?

**Comment by zacharysarah** [comment]
@PrajwalBorkar 👋🏻 If you'd like to continue the work in this PR, please open two separate PRs to address each concern individually.

/close

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar 👋🏻 If you'd like to continue the work in this PR, please open two separate PRs to address each concern individually.
> 
> /close

Made [PR](https://github.com/kubernetes/website/pull/34320). Please check.

**Pull request closed without merging**
