### PR TITLE
[zh-cn] resync: docs/tasks/manage-kubernetes-objects/imperative-config.md

### PR DESCRIPTION
**Pull request by hs0210**
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>

### CODE REVIEW

**Review by Sea-n — CHANGES_REQUESTED** [review]
Please also update the commented English text.

**Comment by Sea-n** [comment]
For small sync like this, it's better to update 2 - 5 files with similar changes in the same PR.
- #35694
- #35696

**Comment by hs0210** [comment]
> Please also update the commented English text.

@Sea-n Done. PTAL.

> For small sync like this, it's better to update 2 - 5 files with similar changes in the same PR.

Thanks for the reminder, I will pay attention to it later.

**Pull request merged**
