### PR TITLE
Update taint-and-toleration.md

### PR DESCRIPTION
**Pull request by Tharegorn**
Just correcting a tiny mistake on Taint and Toleration page !
I just need the contributor badge 😉

### CODE REVIEW

**Review by divya-mohan0209 — CHANGES_REQUESTED** [review]
@Tharegorn , please sign the CLA. Also, per our policy on [trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) please could you consider reviewing the entire page & see if there are any other grammatical/spelling errors and amend them? The reviewing effort for each PR is massive, so we appreciate it if the submitter of a PR for a minor change is able to review the file wholly & amend grammatical/spelling mistakes if any, as well.

**Comment by Tharegorn** [comment]
> e sign the CLA. Also, per our policy on [trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) please could you consider reviewing the entire page & see if there are any other grammatical/spelling errors and amend them? The reviewing effort for each PR is massive, so we appreciate it

Alright, I'll do that, and check the whole page!

**Review by Arhell — COMMENTED** [review]
CLA info
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by divya-mohan0209** [comment]
Hello @Tharegorn , please could you advise if you're able to sign the CLA or are facing issues? We need you to sign it before proceeding for further review.

**Comment by Sea-n** [comment]
Hey @Tharegorn,

Since you didn't sign CLA agreement, we cannot review this PR and move forward.

I'm closing this PR now, but feel free to `/reopen` once you are ready to sign CLA. ([tutorial here](https://git.k8s.io/community/CLA.md))
/close

**Pull request closed without merging**
