### PR TITLE
Bump up Deployment version in cn tasks/access-application-cluster folder

### PR DESCRIPTION
**Pull request by nashasha1**
Do the same thing as #7324  in CN doc folder.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7347)

### CODE REVIEW

**Comment by heckj** [comment]
Could you please review that recommendation and update these PRs to [include min-kubernetes-server-version in the front-matter of the various documents](https://kubernetes.io/docs/home/contribute/style-guide/#versioning-kubernetes-examples)?

**Comment by steveperry-53** [comment]
@nashasha1 Changes to the cn content are done by the translation team in the kubernetes/kubernetes-docs-cn repo. So we don't take direct changes to cn content here in the kubernetes/website repo. Thanks.

**Comment by nashasha1** [comment]
@steveperry-53  Thanks for your reply. So I can close all the pr about cn changes?

**Comment by steveperry-53** [comment]
@nashasha1 Yes, you can close all cn PRs.

**Comment by heckj** [comment]
@nashasha1 I'm going to go ahead and close these PRs for kubernetes/website - would love to have the same content applied to kubernetes/kubernetes-docs-cn

**Pull request closed without merging**
