### PR TITLE
Update custom-resources.md

### PR DESCRIPTION
**Pull request by liutaot**

### CODE REVIEW

**Comment by tengqm** [comment]
54、64 行需要更新，以与英文内容同步。

**Comment by liutaot** [comment]
> 

OK

**Comment by tengqm** [comment]
please squash your commits into one. there are 3 of them now.

**Comment by liutaot** [comment]
> please squash your commits into one. there are 3 of them now.

OK.

**Comment by tengqm** [comment]
/lgtm
/approve
Thanks.

**Pull request merged**
