### PR TITLE
replace deprecated TOC style (#8890)

### LINKED ISSUE #8890: Issue with k8s.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

`TOC {:toc}` is appeared in rendered output.

**Proposed Solution:**

remove TOC tag

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/

### PR DESCRIPTION
**Pull request by makocchi-git**
closes #8890

### CODE REVIEW

**Comment by liggitt** [comment]
without these, there's no clear way to link to a particular section of the doc... hovering over the headers doesn't give section links

**Comment by liggitt** [comment]
actually, I don't understand the issue... I'm not seeing TOC in the rendered output at https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authorization

/hold

**Comment by liggitt** [comment]
ah, it looks like the content got duplicated

rather than remove it, should we convert to the style used on the other page: `{{< toc >}}`?

**Comment by makocchi-git** [comment]
@liggitt Thank you for your review.
I replaced old TOC style to new style "`{{< toc >}}`".

**Pull request merged**
