### PR TITLE
Update non-preempting option Doc

### PR DESCRIPTION
**Pull request by denkensk**
https://github.com/kubernetes/enhancements/issues/902

### CODE REVIEW

**Comment by denkensk** [comment]
@sftim  please take a look again.

**Comment by sftim** [comment]
Markdown looks good to me

**Comment by nasa9084** [comment]
seems japanese content is not changed, just because of base branch issue
/remove-language ja

**Comment by divya-mohan0209** [comment]
@denkensk : Please could you confirm in light of the revised deadlines if this is right now ready for review?

**Comment by denkensk** [comment]
Thanks @divya-mohan0209   It's ready for review~

**Pull request merged**
