### PR TITLE
Update hugo, node, docsy versions

### PR DESCRIPTION
**Pull request by dtzar**
This makes the website work utilizing the latest version of hugo and node via the netlify configuration file. 
Removes all node.js vulnerabilities (there are medium and high ones on main today).
Updates the docsy theme to most recent version without causing breakage (0.6.0).

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/lgtm

**Review by sftim — CHANGES_REQUESTED** [review]
Thanks for proposing this.

I'd prefer to split the Hugo, Node, and Docsy updates into separate, smaller PRs.

/hold
The PR updates Docsy without mentioning that in the PR title. We ought to make the situation clear. OK to unhold when the changes match the summary.

**Comment by sftim** [comment]
/lgtm cancel

based on https://github.com/kubernetes/website/pull/43811#pullrequestreview-1713747448

**Comment by dtzar** [comment]
Updated the title to reflect

**Comment by sftim** [comment]
/hold cancel

I still recommend we **don't** merge this combined PR. It's easier to review - and, if needed, revert - the individual smaller changes.

**Comment by dtzar** [comment]
Broke out the first PR for hugo/netlify: https://github.com/kubernetes/website/pull/44640
Will create a second PR for docsy after that's merged.

**Comment by sftim** [comment]
@dtzar did you open that follow-up PR?

**Comment by dtzar** [comment]
No I didn't.  The docsy update I gave still doesn't get to the latest version of docsy due to the [significant breaking changes when the project switches to bootstrap v5.](https://www.docsy.dev/blog/2023/bootstrap-5-migration/)  Furthermore, the ideal/recommended pattern with docsy moving forward is using their git submodules of which is a much more significant effort/change to the k/k website repo.  I've done this migration for the karpenter website.

I really believe we need to have someone get an updated hugo/docsy template with the latest docsy version which works with various features, especially the [drop down menu versions for languages](https://github.com/google/docsy-example/issues/254).

Related sig meeting discussions in case others care to know more.  Also open to file an issue in this regards if you'd like @sftim versus just notes here.
[Sig Docs meeting](https://docs.google.com/document/d/1emuO4nmaQq3K8JZ9-MQeIygtrCPO9kWv7U7RzTaW4F8/edit#heading=h.eecmw28791qv) 
[CNCF Tech Docs office hours](https://docs.google.com/document/d/1roexHTLCrErYjNT2NEoRsVnn_YNbQzZ1gyXNK8hXR4Q/edit#heading=h.f19hbaugtdtu)

**Comment by sftim** [comment]
If you're willing to file that issue @dtzar, please do.

**Comment by dtzar** [comment]
https://github.com/kubernetes/website/issues/45410

**Pull request closed without merging**
