### PR TITLE
Users should choose network plugin before initializing cluster

### PR DESCRIPTION
**Pull request by nirvanagit**
Before you initialize the master, choose the pod network plugin you want to use and then check if the pod network requires any other parameters that need to be passed on to kubeadm while initializing the cluster.

### CODE REVIEW

**Comment by nirvanagit** [comment]
updated

**Comment by Rajakavitha1** [comment]
Thanks @nirvanagit 
/lgtm

**Comment by nirvanagit** [comment]
Your welcome. Can this be merged?

**Pull request merged**
