### PR TITLE
suspend cstoku and MasayaAoyama in sig-docs-ja

### PR DESCRIPTION
**Pull request by nasa9084**
They are busy for their main business, do not have time to review PRs.
They will come back in the future, when time permits.

### CODE REVIEW

**Comment by inductor** [comment]
I leave a comment to say this is a valid request as another SIG Docs JA owner :)

**Comment by jimangel** [comment]
Would it be possible to remove the lines entirely for cleanliness? If / when adding them back, this PR can be referenced or an approver can review the git history.

**Comment by inductor** [comment]
@jimangel Sure thing.

**Comment by inductor** [comment]
@jimangel But what about this though? https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L80
https://github.com/kubernetes/website/pull/17515

**Comment by inductor** [comment]
We discussed in sig-docs-maintainer channel on Slack and decided to go it as-is for now.

**Pull request merged**
