### PR TITLE
Add KUBECTL_KUBERC environment variable description

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR adds new environment variable into the docs for https://github.com/kubernetes/enhancements/issues/3104

### CODE REVIEW

**Comment by Shubham82** [comment]
Hold this PR until the corresponding upstream PR [kubernetes/kubernetes#125230](https://github.com/kubernetes/kubernetes/pull/125230) merges.

/hold

**Comment by sftim** [comment]
Thanks for the pull request.

:information_source: Please also document the format of kuberc files.

**Comment by Princesso** [comment]
Hello @ardaguclu :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday July 16th 2024 18:00 PST. Thank you!

**Comment by ardaguclu** [comment]
Unfortunately we couldn't make this in 1.31. 
/close

**Pull request closed without merging**
