### PR TITLE
Create Ten Commandants to Hack in Kubernetes World

### PR DESCRIPTION
**Pull request by AbhiGitHubKube**
This is Document for Blog Post on Kubernetes Site

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Please delete this note before submitting the pull request.
>
> For 1.14 Features: set Milestone to 1.14 and Base Branch to dev-1.14
> 
> For Chinese localization, base branch to release-1.12
>
> For Korean Localization: set Base Branch to dev-1.13-ko.<latest team milestone>
>
> Help editing and submitting pull requests:
> https://kubernetes.io/docs/contribute/start/#improve-existing-content.
>
> Help choosing which branch to use:
> https://kubernetes.io/docs/contribute/start#choose-which-git-branch-to-use.
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>

### CODE REVIEW

**Comment by mistyhacks** [comment]
/assign @kbarnard10 

I am not the right person to review blog posts.

I also have some editorial concerns about tying a blog post with a religious concept.

**Comment by AbhiGitHubKube** [comment]
@kbarnard10 can you please review the blog and suggest inputs

**Comment by kbarnard10** [comment]
@AbhiGitHubKube - This post has numerous issues that must be resolved before it can be considered for publishing. The content does not meet the standards for community conduct or editorial quality. Please note that content with religious themes is inappropriate for any Linux Foundation blog.

I'm going to close this out. If you'd like to revise and resubmit, please take a look at our [style guide](https://kubernetes.io/docs/contribute/style/style-guide/) and [code of conduct](https://kubernetes.io/community/code-of-conduct/).

**Pull request closed without merging**
