### PR TITLE
Fix pod.md (ko)

### PR DESCRIPTION
**Pull request by kjo6152**
delete incorrectly duplicated phrases.

### CODE REVIEW

**Comment by seokho-son** [comment]
@kjo6152 Thank you for your contribution ! 
Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

After you sign the CLA, the k8s-ci-robot will remove "cncf-cla: no" label. Thank you.

**Comment by kjo6152** [comment]
Oops. I signed a Contributor License Agreement.

**Comment by seokho-son** [comment]
Hello, @kjo6152. It seems there is another minor problem here. ("commit missing GitHub user")

It seems there is no associated GitHub user in [your commit](https://github.com/kubernetes/website/pull/19187/commits/2c7fc78ea869f1b44809a9c0731bb2a23bea3674). 

Please check below link to resolve it :)
https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

**Comment by seokho-son** [comment]
ping :) @kjo6152

**Comment by seokho-son** [comment]
@kjo6152 Thank you for your contribution !

/lgtm
/approve

**Pull request merged**
