### PR TITLE
Add selector in deployment example

### PR DESCRIPTION
**Pull request by nashasha1**
Add selector field in depoyment example.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/website/7113)

### CODE REVIEW

**Comment by heckj** [comment]
Could you please review that recommendation and update these PRs to [include min-kubernetes-server-version in the front-matter of the various documents](https://kubernetes.io/docs/home/contribute/style-guide/#versioning-kubernetes-examples)?

**Comment by heckj** [comment]
@nashasha1 this one also looks like it needs a rebase due to conflicting changes in the underlying content

**Comment by nashasha1** [comment]
@heckj  Thanks for your reply. Since the change has been merged into master. I will close this pr. Thank you very much.

**Pull request closed without merging**
